### PR TITLE
sshtunnel: Add support for "ProxyCommand" [v3]

### PR DESCRIPTION
**Pull request by lars18th**
Maintainer: @nunojpg
Compile tested: mips
Run tested: TP-Link Archer C2 v3, OpenWrt 19.07.2

Description:

A simple update to support the ProxyCommand parameter. Installing the OpenSSH client and NCat tool it's possible to stablish the SSH tunnel over an authenticated HTTP proxy or over a SOCKS4/5 proxy.

This implementation fully works when using the OpenSSH client and one compatible helper tool (NCat as example).

Replaces #13789

Signed-off-by: Lars Theorin <lars18th@users.noreply.github.com>

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @nunojpg,

Please check my final version of the ProxyCommand support for the "sshtunnel" package.

Regards.

**Comment by nunojpg** [comment]
I will review. In the future it's enough to force-push to your branch. No need to create multiple pull requests or issues.

**Comment by lars18th** [comment]
> I will review. In the future it's enough to force-push to your branch. No need to create multiple pull requests or issues.

Hi @nunojpg ,

Is there anything else I can do to get this patch approved?

**Comment by feckert** [comment]
Please add to all your commit this header `sshtunnel: <your message>` so we know that this commit is related to the package sshtunnel.

**Comment by lars18th** [comment]
Hi @feckert ,

> Please add to all your commit this header `sshtunnel: <your message>` so we know that this commit is related to the package sshtunnel.

OK, but any idea to do this "change" with git? I don't want to generate a new PR.
I know, it's a newbie request, so I apologize for this request.

**Comment by feckert** [comment]
Xou have to execute in your pullrequest branch the command `git rebease -i HEAD~3` and then started editor replace pick with reword. After that your could amend every commit with the new commit message. After this is done I have to do a push force to your pullrequest branch. This will update your comits in this P/R.

**Comment by nunojpg** [comment]
@lars18th why are you using a temporary file to execute the command? Is it to avoid specify ncat (eg.) full path?

**Comment by lars18th** [comment]
> @lars18th why are you using a temporary file to execute the command? Is it to avoid specify ncat (eg.) full path?

That's because the quote of the proxycommand. It's the best way to overcome the troubles with this parameter as you can include anything inside it. So the parsing is more simple in this way. In fact it's the recommended option to use it.

Regards.

**Comment by nunojpg** [comment]
> In fact it's the recommended option to use it.

Can you provide a reference?

How this this handle %h and %p? You have to forward them into the script over $1 and $2?

**Comment by lars18th** [comment]
Hi @nunojpg ,

I feel you're the official maintainer of the SSHTunnel package. So, please can you review _another time_ this patch?

Regarding your question: I don't have any real "reference" related to the use of a temporal file. Only after my reasearch and testing I've arrived to the conclusion that is not possible to call to the ssh client tool with a proxycommand including spaces. So the only solution is to generate a temporal file with the command, then call to the ssh binary and finally remove the temporal file. This workaround works and I'm using it for years without any trouble.

So please, consider if you want to add this funcitionality. This is necessary for example if you use some proxy for connecting to the ssh server. In this case without the proxycommand it's impossible to stablish the tunnel.

Regards.

**Comment by nunojpg** [comment]
> How this this handle %h and %p? You have to forward them into the script over $1 and $2?

I think you didn't answer this.

**Comment by lars18th** [comment]
Hi @nunojpg ,

>> How this this handle %h and %p? You have to forward them into the script over $1 and $2?

> I think you didn't answer this.

Ah, sorry! Now I get it. In my example `%h` and `%p` are not handled. The proxy command is passed directly:
`option ProxyCommand 'ncat --proxy-type http --proxy-auth user:pass --proxy ip:port server.disney.com 22'`

If you think it's necessary (or mandatory) to support them. Then in this case, I suggest that you modify the generation of the temporal file to include in them the parameters. I'm not sure about the best method to do it. For example, it will be acceptable `option ProxyCommand 'ncat --proxy-type http --proxy-auth user:pass --proxy myproxy.lan:port %h %p'` or not? My original idea is to not add a lot of different paramenters, but only a new parameter `ProxyCommand` with a _single_ line. And the user can put on it whatever he needs. Then it will be more clean. Therefore, if the user requires to use the host and port parameters, then he can add them manually in the proxy line. That's my point of view.

What you think?

**Comment by nunojpg** [comment]
It must work in the typical ProxyCommand form to avoid introducing a custom idiom:

`option ProxyCommand 'ncat --proxy-type http --proxy-auth user:pass --proxy ip:port %h %p'
`

**Comment by lars18th** [comment]
Hi @nunojpg ,

Ok. So then please help me (to go more fast) to make the changes _before_ this line
```
		echo "exec ${ProxyCommand}" >> $proxy_option
```

The idea is to replace the `%h` and `%p` values inside the variable `${ProxyCommand}` before writing the content to the tmp file.
Do you know the most simple way to achieve this?

**Comment by lars18th** [comment]
Hi @nunojpg ,

The replace (with sed) of the `%h` and `%p` parameteres in the proxycommand is implemented. You can check it now.

Regards.

**Comment by lars18th** [comment]
Hi @nunojpg ,

Any problem with this patch? It's all ready from my side. Please, comment.

**Comment by nunojpg** [comment]
About the code I will know if there are problems when I review it.

About the commits, you have to fix them according to the project rules as explained to you above, in specific from https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md:

> Commits in your pull-requests should
Have a useful description prefixed with the package name (E.g.: "foopkg: Add libzot dependency")
Include Signed-off-by tag in the commit comments. See: [Sign your work](https://openwrt.org/submitting-patches#sign_your_work)

**Comment by nunojpg** [comment]
You have now 6 commits in this pull request which don't follow any feature logic, and they don't have valid subjects (starting with "sshtunnel:"). You have to rebase it or start clean and make a new commit if it is easier for you. In the end just force push into this branch, don't open a new PR.

**Comment by lars18th** [comment]
Hi @nunojpg ,

> You have now 6 commits in this pull request which don't follow any feature logic, and they don't have valid subjects (starting with "sshtunnel:"). You have to rebase it or start clean and make a new commit if it is easier for you. In the end just force push into this branch, don't open a new PR.

I've created another PR (sorry if this is not the best option, but for me it's more easy to start from zero).
Check it at https://github.com/openwrt/packages/pull/20163
On it I feel I've done right: only one commit, signed in the commit, full description in the PR.
I'm missing something? 

So I close this PR. Please, check the new.
Regards.

**Pull request closed without merging**
