### PR TITLE
wshaper: Retire package

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @jow- 
Compile tested: N/A
Run tested: N/A

Description:
Wondershaper has been superseded by both qos-scripts and sqm-scripts, it's time to retire it for good.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by thess** [comment]
Move to packages-abandoned (Submit PR there) ?

**Comment by EricLuehrsen** [comment]
Its already archived in the git commit history. Its not that this is a fringe package with absentee maintainer. This package is just plain obsolete.

**Comment by thess** [comment]
@jow- OK to merge/remove?

**Comment by diizzyy** [comment]
@blogic approved dropping it fwiw

**Pull request merged**
