### PR TITLE
lang: python: flup: drop package

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: n/a
Run tested: n/a

-----------------------------------------

Was mostly required for Seafile.
Now it isn't.
It's also pretty ancient.
   https://www.saddi.com/software/flup/

Page was last updated in 2005.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
i'm vague on whether there is a new procedure about 'abandoned' packages
do we move this to https://github.com/openwrt/packages-abandoned/ ?
or?

@hnyman @jefferyto @neheb 
[ you guys committed stuff there ] 

personally, i don't care about dropped packages much   ¯\_(ツ)_/¯

but anyway, i'd like to drop this from here;
it looks like mostly dead code [a dead project];

**Comment by jefferyto** [comment]
I think adding it to the abandoned packages repo would be good.

I have a related question: Do we (as a project) have a policy for deciding whether/when a package should be dropped?

For example, I dropped obfsproxy earlier since it was Python 2 only. obfsproxy was the only dependant of python-twisted; no other in-tree package uses python-twisted. One would think we can drop python-twisted as well...

But @Cynerd added a Python 3 variant in #8197, so I would assume they are using it in some way in their feed.

So how do we decide when or whether to drop a package? Is it only the decision of the maintainer (or lack or maintenance)? Do we consult with downstream / end users first?

(This was something I wanted to ask in the forum, but I posted about [adding a category for the packages feed](https://forum.openwrt.org/t/new-category-for-packages-feed-packages-development/59450) earlier but there hasn't been any response. Apologies for hijacking another comment/PR :joy:)

**Comment by BKPepe** [comment]
> One would think we can drop python-twisted as well...
But @Cynerd added a Python 3 variant in #8197, so I would assume they are using it in some way in their feed.

Nooo! We need python-twisted! :)  It is being used by [haas-proxy](https://gitlab.labs.nic.cz/turris/turris-os-packages/-/blob/master/collect/haas-proxy/Makefile) package indeed in our feed. I think, there's a plan to add it to this repository. I will try to push it forward. It's question if it is going to be accepted, but let's see. [Fail2ban](https://forum.turris.cz/t/any-way-how-to-use-iptables-inside-lxc-containers/12326/5?u=pepe) can be useful, but If I am not mistaken, it might do a lot of writes on the internal storage, which is not good. That's why the [Honeypot as a Service](https://haas.nic.cz/) can be useful.  You can see attacker's IP addresses, which credentials they used and their behavior and what they were trying to do.

**Comment by neheb** [comment]
No real policy on dropping packages. In my PR, the main goal is to remove the Facebook packages as they are unused and unmaintained. I looked through the libraries and saw a bunch of other unused ones.

**Comment by jefferyto** [comment]
Apologies for filling this PR up with unrelated comments - I didn't know about #11764 or #11766 (I don't browse the issues or PR lists in my spare time).

BTW I don't plan on removing python-twisted any time soon, I only mentioned it as an example for package removal policy (or our lack of it).

**Comment by commodo** [comment]
> Apologies for hijacking another comment/PR joy)

no problems for hijacking this thread; i don't mind; it's probably good to have this discussion whenever possible;

> So how do we decide when or whether to drop a package? Is it only the decision of the maintainer (or lack or maintenance)? Do we consult with downstream / end users first?

no idea what's best;
i do know that consulting with downstream usually works best when you break stuff (or in this case remove it), then you get reports/issues like "hey, i needed that";
it's not perfect, but it is the more common feedback [that works];  ¯\_(ツ)_/¯
every-now-n-then it also works to ask before-hand;

for `flup` specifically, i don't know; i've been watching it for a while and wanted to remove it [because of Seafile];
i just noticed that the last release was in 2018 [not so long ago];
it's usage [specifically version 1.0.3] though isn't too great
https://libraries.io/pypi/flup/usage
i do feel it's more like Python developers [well, ruby-on-rails & nodejs developers as well] are a bit of library-hoarders; when they create a project they cram it with many libraries, and some of the libs just get unmaintained
`flup` can also be installed manually or via pip on the target directly;  no need to carry it in the build-system; [1]

> But thinking on how the old packages repo got filled with non-maintained ancient packages, it is better to do some cleanup every now and then, especially with ancient packages that have no clear purpose or usage any more.

it's how i got to be maintainer of Python :P  
because of the old-packages transitioning to Github

coming back to [1] and specifically only for Python packages: initially i did not want to package more than python + setuptools + pip on OpenWrt, because of the vastness of Python libs [on pypi.org];
but @sbyx at the time made a point that `if people want to package python packages, let them` and i thought `ok ¯\_(ツ)_/¯`
in the meantime, it made sense to package python libs that have binary [arch-specific] source code;
also, in the meantime we added python-only libs for some other projects;
we never made a rule about enforcing anything [about this] anyhow;

but this made me [co-]maintainer on ~50 packages since people didn't want to take ownership sometimes, or were abandoning things;
so, i kind of have a personal reason when wanting to drop some of my own packages: reduce some of the load where things feel pointless

> There is no clear policy about packages to be dropped.

we could let maintainers decide whether things get dropped or not;
usually when a maintainer decides to drop a package he either can do that, or drop himself as a maintainer which is kind of a limbo state anyway that ends up in a mass-removal thing;

the part where i don't really know/care atm; is the move to the new abandoned packages repo;
that one may have value over time

> Moving to abandoned feed is ok, if the package may have value later, but maybe not necessary for all removed packages. (for "flup" I do not see it as necessary, as it is ancient and has only been used by seafile, apparently)

i would say for python-only packages being dropped, that we should probably point people to pypi.org to download it manually;
the only value for moving it to abandoned [for python-only packages], is to keep the Makefile rules for packaging;
other than that, dunno

what i don't know about the abandoned repos, is if there is policy to keep things building there?
because if pypi.mk & python3-package.mk evolve over time, abandoned packages won't work well after a while [to build], needing attention/work

**Comment by hnyman** [comment]
"Abandoned" repo is just for storage, no compilation or maintenance requirement. 
(Although the same archival is in practice also on git in the normal repo)

The most difficult part are hit-and-run maintainers, who want introduce a library, may use it for their personal projects for a month, and then disappear, leaving the package maintained in theory, but not in practice.

Thatswhy I am very reluctant to add new packages that do not have a clear use case in the home / small office router context.  Data center or big data oriented functionalities/things are not really OpenWrt core. The same goes for many python-only libraries, that may be nice, but what is their actual usage in the main OpenWrt population???

**Comment by jefferyto** [comment]
> i do know that consulting with downstream usually works best when you break stuff (or in this case remove it), then you get reports/issues like "hey, i needed that";

I think if we know beforehand that an action may break something for downstream/end users, then it would irresponsible of us not to say something beforehand and give users the chance to prepare and/or give feedback.

I agree that maintainers should have final say on what happens (in most cases anyway), but we maintain packages not just for ourselves but for other people too. Our decisions affect users and we should take their feedback into account.

> The most difficult part are hit-and-run maintainers, who want introduce a library, may use it for their personal projects for a month, and then disappear, leaving the package maintained in theory, but not in practice.

Instead of deterring these people from adding packages, I think we should find ways of keeping them engaged and more involved in the project.

(An example off the top of my head: what if we send an email to maintainers every month, saying how many people have downloaded or installed their packages in the past month? Like how LinkedIn sends an email saying how many people have viewed your profile this week.)

> Thatswhy I am very reluctant to add new packages that do not have a clear use case in the home / small office router context. Data center or big data oriented functionalities/things are not really OpenWrt core.

I'm not sure we have a consensus on what the home / small office router context is, or if that is the right focus/criteria for accepting packages.

> The same goes for many python-only libraries, that may be nice, but what is their actual usage in the main OpenWrt population???

There are different ways of measuring usage, not just of Python libraries but of all packages:
* Do they have package dependants, i.e. is this package used by another package? (Obviously this applies more to library than program packages)
* How often are they downloaded/installed/run?

Until we have more data, we are only using our own intuition on what should we keep or remove.

**Comment by commodo** [comment]
> Until we have more data, we are only using our own intuition on what should we keep or remove.

yeah, is this info available?
can we make it?
we've been shooting darts in the dark with no idea/feedback other than "hey, it hurts", with silence being the default answer for "all is fine, or just useless"

**Comment by hnyman** [comment]
Some stats are there:
https://downloads.openwrt.org/stats/

Note that adding a package to repo means that it will be compiled for 30+ architectures semi-regularly. If that is a package with minimal interest, the compilation & storage is rather pointless.

**Comment by Cynerd** [comment]
My opinions on few things that were noted here:

_Abandoned_ repo makes no sense if you don't at least try to build it. We have git and that is it in that case I think.

I think that it should be all right to drop packages that seems to be unmaintained. If you drop them then and nobody complains then they were not used. If somebody complains then it is one `git revert` away from getting it back. I agree that that is not nice but there is no other way at the moment to get size and build time of OpenWrt under control without having package usage statics at hand I think. There is something to say about some channel directly to routers that would tell users of those packages that they are going to be dropped unless maintainer says otherwise or new maintainer is found.

In general I think that OpenWrt build system is not currently prepared to handle increasing number of packages. I am sure that we (Turris) are not the only one noticing increasing build time and storage requirements. Most of that can be contributed to packages that might not be even usable on small router devices. This is my personal opinion (not Turris) but I think that OpenWrt would benefit from better build system or from decreased scope. I would prefer better build system but that requires development time and a vision to move it forward.

I don't think that we should deny adding new packages that are outside of router functionality. I rather think that we should better define router functionality and mark packages outside that definition. There should be rather policy that adding new packages is easy but (with exclusion of router functionality) it is also easy to drop them. There should be no package without active maintainer outside router functionality in repository I think.

**Comment by BKPepe** [comment]
Sorry for opening it once again here. But we found that we are using python-flup in Turris routers, which is kinda funny as I and @cynerd were responding here. We are in the process of redesigning our web interface, which we provide, and in the previous one we were using it, but in the new one, we forgot to add flup as a dependency.

@shenek did a small research and described in our issue:
https://gitlab.nic.cz/turris/foris/foris/-/issues/196#note_153576
and come to the conclusion 
> the flup is still the easiest and the most lightway way.

So what's about bringing it back? If you agree, I will do a revert commit.

**Comment by commodo** [comment]
> So what's about bringing it back? If you agree, I will do a revert commit.

fine by me;
anyone for co-maintainer?

reason for me taking down some packages is that i maintain a lot of [python] them;
and i have no feedback over which/what is used;
[there was some discussion about trying to get better usage stats or using the current download stats [better]]
i try to find co-maintainers over time so that if i get run-over by a car or something, at least some of them go on;

also, i remember, at some point @hnyman was afraid that these python packages would get out of hand [and just overload the build infrastructure];
it didn't go too bad [from my point of view]; maybe it could have been slightly better;

**Comment by BKPepe** [comment]
I'm in favor to be maintainer or co-maintainer.

**Comment by commodo** [comment]
> I'm in favor to be maintainer or co-maintainer.

cool;
you want to do the PR or shall i?

**Pull request merged**
