### PR TITLE
motion: Update to 4.1.1 and switch to codeload

### PR DESCRIPTION
**Pull request by neheb**
Simpler.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @roger- 
Compile tested: ipq806x

### CODE REVIEW

**Comment by cshoredaniel** [comment]
Please note that project stance on codeload is under review: https://github.com/openwrt/packages/issues/6748

**Comment by neheb** [comment]
ping @roger-

**Comment by neheb** [comment]
ping @roger- Can we get this merged?

**Comment by roger-** [comment]
Looks good.

**Pull request merged**
