### PR TITLE
tor: Fix compilation without OpenSSL ENGINES

### PR DESCRIPTION
**Pull request by neheb**
This will become default soon.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @hauke @tripolar 
Compile tested: ramips

### CODE REVIEW

**Comment by tripolar** [comment]
did send this patch upstream?

**Comment by neheb** [comment]
I have not. Figured it was simple enough.

**Comment by tripolar** [comment]
Please send it upstream. It makes no sense to take care of patches that belong in the upstream release

**Comment by neheb** [comment]
@tripolar https://trac.torproject.org/projects/tor/ticket/29026

**Comment by neheb** [comment]
Updated and Rebased.

**Comment by neheb** [comment]
This is already a default option in OpenSSL’s config. The depend just prevents disabling it (I test my changes by disabling almost everything)

**Comment by hnyman** [comment]
> This is already a default option in OpenSSL’s config. The depend just prevents disabling it 

Then leave it as "depends" @  instead of "selects" +@

**Comment by diizzyy** [comment]
@neheb 
Looks like there's progress upstream, you can close this PR
https://github.com/torproject/tor/pull/689

**Pull request closed without merging**
