### PR TITLE
dnscrypt-proxy: Update to latest git revision

### PR DESCRIPTION
**Pull request by neheb**
Includes a security fix.

Fixed usage with latest libsodium.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @damianorenfer 
Compile tested: arc700

https://github.com/openwrt/packages/issues/9158

### CODE REVIEW

**Comment by BKPepe** [comment]
ping @damianorenfer

**Comment by BKPepe** [comment]
Btw: shouldn't we rather to switch [dnscrypt-proxy 2](https://github.com/jedisct1/dnscrypt-proxy)?

**Comment by neheb** [comment]
It's quite big for embedded devices.

**Comment by damianorenfer** [comment]
> Btw: shouldn't we rather to switch [dnscrypt-proxy 2](https://github.com/jedisct1/dnscrypt-proxy)?

Sorry for the late reply, I already tried to package it in the past. dnscrypt-proxy 2 is written in Go which was not well/fully integrated in the OpenWrt toolchain at that moment. Maybe now it could be compiled more easily. 
In my opinion, if someone decides to package dnscrypt-proxy 2, it should be done in a new package which will interfere with this one.

BR

**Comment by damianorenfer** [comment]
> Includes a security fix.
> 
> Fixed usage with latest libsodium.
> 
> Signed-off-by: Rosen Penev [rosenp@gmail.com](mailto:rosenp@gmail.com)
> 
> Maintainer: @damianorenfer
> Compile tested: arc700
> 
> #9158

thanks

**Pull request merged**
