### PR TITLE
lighttpd: update to lighttpd 1.4.70 release hash

### PR DESCRIPTION
**Pull request by gstrauss**
Maintainer: @flyn-org
Compile tested: arm_cortex-a9 OpenWrt master

Description:
* update to lighttpd 1.4.70 release hash
* select wolfssl for default cryptolib
* include mod_h2 in base package

### CODE REVIEW

**Comment by gstrauss** [comment]
@flyn-org @1715173329 @BKPepe 

CI passes (once I remembered to build target `refresh QUILT=1` to fixup the patches)

lighttpd 1.4.70 and these patches now use wolfssl by default (instead of Nettle) as the base crypto library for digest functions (MD5, SHA256, etc).  After a couple weeks on the openwrt master branch, I plan to backport this to OpenWRT 21.02 and to OpenWRT 22.03.  Starting with OpenWRT 21.02, wolfssl is included in openwrt base.

Also in these patches is a change to move lighttpd HTTP/2 code into an optional module mod_h2, so that memory use can be reduced if HTTP/2 support is disabled in lighttpd.conf.  HTTP/2 support remains enabled by default in lighttpd, since lighttpd 1.4.59.

Note: I do have a concern about the startup performance of wolfssl, and so plan to omit the backport of changing to use wolfssl for digest functions.  I have previously observed that lighttpd starts up very quickly with nettle and mod_openssl on a very old NetGear router I have, but takes close to 10 seconds to start when using lighttpd with nettle and mod_wolfssl.

**Comment by 1715173329** [comment]
Okay, what about mbedtls? It's the default crypto lib we used in base now.

**Comment by gstrauss** [comment]
> Okay, what about mbedtls? It's the default crypto lib we used in base now.

Neat.  I personally prefer mbedtls.  I'll update the PR.

**Comment by neheb** [comment]
wolfSSL has been awful for OpenWrt 22.03. Too much ABI breakage.

**Comment by gstrauss** [comment]
CI passes with small change to make mbedtls to default lib that lighttpd uses for digest functions and randomness.

When backporting to OpenWRT 21.02 and 22.03, I plan to leave the default cryptolib in lighttpd as Nettle.

**Pull request merged**
