### PR TITLE
strongswan: add wolfssl plugin

### PR DESCRIPTION
**Pull request by derekyerger**
Maintainer: @stintel 
Compile tested: With gcc 7.5.0 on v19.07 x86_64-glibc and musl
Run tested: v19.07 x86_64 musl, gcc 7.5.0

Description: Adds WolfSSL module to strongswan

Verification:

```
root@OpenWrt:/# ipsec statusall
Status of IKE charon daemon (strongSwan 5.8.2, Linux 4.14.195, x86_64):
  uptime: 54 seconds, since Nov 27 21:31:04 2020
  worker threads: 11 of 16 idle, 5/0/0/0 working, job queue: 0/0/0/0, scheduled: 0
  loaded plugins: charon aes des rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pgp dnskey sshkey pem wolfssl fips-prf gmp xcbc hmac a
ttr kernel-netlink resolve socket-default connmark stroke updown xauth-generic
Listening IP addresses:
  192.168.1.1
  fdee:4407:1377::1
Connections:
Security Associations (0 up, 0 connecting):
  none
root@OpenWrt:/# ipsec listalgs

List of registered IKE algorithms:

  encryption: AES_CBC[aes] AES_ECB[aes] 3DES_CBC[des] DES_CBC[des] DES_ECB[des] RC2_CBC[rc2] AES_CTR[wolfssl]
              NULL[wolfssl]
  integrity:  HMAC_MD5_96[wolfssl] HMAC_MD5_128[wolfssl] HMAC_SHA1_96[wolfssl] HMAC_SHA1_128[wolfssl]
              HMAC_SHA1_160[wolfssl] HMAC_SHA2_256_128[wolfssl] HMAC_SHA2_256_256[wolfssl] HMAC_SHA2_384_192[wolfssl]
              HMAC_SHA2_384_384[wolfssl] HMAC_SHA2_512_256[wolfssl] HMAC_SHA2_512_512[wolfssl] AES_XCBC_96[xcbc]
  aead:       AES_GCM_16[wolfssl] AES_GCM_12[wolfssl] AES_CCM_16[wolfssl] AES_CCM_12[wolfssl] AES_CCM_8[wolfssl]
              CHACHA20_POLY1305[wolfssl]
  hasher:     HASH_SHA1[sha1] HASH_SHA2_224[sha2] HASH_SHA2_256[sha2] HASH_SHA2_384[sha2] HASH_SHA2_512[sha2]
              HASH_MD5[md5]
  prf:        PRF_KEYED_SHA1[sha1] PRF_HMAC_MD5[wolfssl] PRF_HMAC_SHA1[wolfssl] PRF_HMAC_SHA2_256[wolfssl]
              PRF_HMAC_SHA2_384[wolfssl] PRF_HMAC_SHA2_512[wolfssl] PRF_FIPS_SHA1_160[fips-prf] PRF_AES128_XCBC[xcbc]
  xof:       
  drbg:      
  dh-group:   ECP_256[wolfssl] ECP_384[wolfssl] ECP_521[wolfssl] ECP_224[wolfssl] ECP_192[wolfssl] MODP_3072[wolfssl]
              MODP_4096[wolfssl] MODP_2048[wolfssl] MODP_2048_224[wolfssl] MODP_2048_256[wolfssl] MODP_1536[wolfssl]
              MODP_1024[wolfssl] MODP_1024_160[wolfssl] MODP_768[wolfssl] MODP_CUSTOM[wolfssl] MODP_6144[gmp]
              MODP_8192[gmp]
  random-gen: RNG_WEAK[wolfssl] RNG_STRONG[random] RNG_TRUE[random]
  nonce-gen:  [nonce]
```

### CODE REVIEW

**Comment by neheb** [comment]
This needs a PKG_RELEASEbump.

**Comment by hnyman** [comment]
Nitpicking, but while  you bump PKG_RELEASE, you might also "refresh" the patch to beautify it a bit. (cleanup to the normal a/ b/ patch style)

`make package/strongswan/{clean,refresh} V=s`

**Comment by stintel** [comment]
Please implement this for master first.

**Comment by Neustradamus** [comment]
@derekyerger: Any news?

**Comment by derekyerger** [comment]
@stintel @Neustradamus updated and based on master

**Comment by pprindeville** [comment]
Why does `RSA_PSS_SALT_LEN_DEFAULT` need to be renamed?  This isn't explained.

**Comment by pprindeville** [comment]
Adding @Thermi

**Comment by Thermi** [comment]
I have the same question regarding `RSA_PSS_SALT_LEN_DEFAULT`.

**Comment by derekyerger** [comment]
@pprindeville I hadn't realized the issue only occurs with glibc, and does not apply to builds using musl.

With glibc, the following error occurs during compilation:

```
In file included from ../../../../src/libstrongswan/credentials/certificates/certificate.h:30:0,
                 from ../../../../src/libstrongswan/credentials/credential_set.h:28,
                 from ../../../../src/libstrongswan/credentials/credential_manager.h:31,
                 from ../../../../src/libstrongswan/library.h:113,
                 from wolfssl_common.h:26,
                 from wolfssl_rsa_public_key.c:23:
../../../../src/libstrongswan/credentials/keys/signature_params.h:109:34: error: expected identifier before '-' token
 #define RSA_PSS_SALT_LEN_DEFAULT -1
                                  ^
Makefile:617: recipe for target 'wolfssl_rsa_public_key.lo' failed
make[8]: *** [wolfssl_rsa_public_key.lo] Error 1
```

Should I remove the patch entirely, or amend it with `#if defined(__GLIBC__)` and such?

**Comment by Thermi** [comment]
That looks like a gcc/C issue, not a clib issue.

**Comment by derekyerger** [comment]
@Thermi The issue has been resolved on a fresh build from latest sources. May have been artifacts on the particular build environment used the last time around.

**Review by Thermi — APPROVED** [review]

**Comment by neheb** [comment]
ping @pprindeville

**Comment by pprindeville** [comment]
> ping @pprindeville

Needs a `PKG_RELEASE` bump.

**Comment by lowjoel** [comment]
Hey @derekyerger are you able to respond to @pprindeville's comment? Otherwise, if that's all the work that's needed I could reopen another PR with the same changes +`PKG_RELEASE` bump.

**Comment by pprindeville** [comment]
Please retest and confirm that it still works.

**Comment by derekyerger** [comment]
@lowjoel Sounds good. I've been swamped so haven't had the bandwidth to address this in a timely manner.

**Comment by lowjoel** [comment]
@derekyerger @pprindeville Please see #18312 that contains a rebase, as well as output from OpenWrt 21.03-rc1 hardware (the cherry pick cleanly applies.)

**Pull request closed without merging**
