### PR TITLE
sispmctl: Change URL to HTTPS

### PR DESCRIPTION
**Pull request by neheb**
HTTPS goes through firewalls easier.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @rkunze

### CODE REVIEW

**Comment by neheb** [comment]
Travis failure is SourceForge being slow.

**Comment by neheb** [comment]
Travis no longer complains. @rkunze ?

**Comment by rkunze** [comment]
Looks good to me.

**Comment by neheb** [comment]
@hnyman ?

**Pull request merged**
