### PR TITLE
strongswan: Update to 5.9.9

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me, @Thermi 
Compile tested: x86_64, generic, HEAD (fb15cb4ce95)
Run tested: same, installed on production router

Description:

Update to version 5.9.9.

### CODE REVIEW

**Review by aparcar — APPROVED** [review]

**Comment by pprindeville** [comment]
@Thermi any insight on the build failures?

**Comment by Thermi** [comment]
Not possible, the error is in config.log and that is not provided by the runner

**Comment by Thermi** [comment]
@pprindeville can you try to restart the actions? I want to see if it is reproducible here

**Comment by pprindeville** [comment]
> @pprindeville can you try to restart the actions? I want to see if it is reproducible here

Running

**Comment by Thermi** [comment]
Thank you. No idea why it happens though. I can only guess it might be a problem with the wolfssl headers that cause redefinition of something within the wolfssl plugin file.

**Comment by cotequeiroz** [comment]
I took a jab at this, and it appears that the culprit is wolfssl's defining `RNG` in [settings.h](https://github.com/wolfSSL/wolfssl/blob/6cc5c1a42823099456202edc7868a6cca3553a0a/wolfssl/wolfcrypt/settings.h#L298)
Strongswan tries to [purge that definition](https://github.com/strongswan/strongswan/blob/cbd69ec73290fdbbfee6a67c264ae54e25e0aaac/src/libstrongswan/plugins/wolfssl/wolfssl_common.h#L84), but it appears to have crept in somewhere else--possibly the inclusion of `<wolfssl/ssl.h>` after the undef.
Try this
``` patch
--- a/src/libstrongswan/plugins/wolfssl/wolfssl_plugin.c
+++ b/src/libstrongswan/plugins/wolfssl/wolfssl_plugin.c
@@ -50,6 +50,9 @@
 #ifndef FIPS_MODE
 #define FIPS_MODE 0
 #endif
+#ifdef RNG
+#undef RNG
+#endif
 
 typedef struct private_wolfssl_plugin_t private_wolfssl_plugin_t;
 
```

**Comment by pprindeville** [comment]
> I took a jab at this, and it appears that the culprit is wolfssl's defining `RNG` in [settings.h](https://github.com/wolfSSL/wolfssl/blob/6cc5c1a42823099456202edc7868a6cca3553a0a/wolfssl/wolfcrypt/settings.h#L298) Strongswan tries to [purge that definition](https://github.com/strongswan/strongswan/blob/cbd69ec73290fdbbfee6a67c264ae54e25e0aaac/src/libstrongswan/plugins/wolfssl/wolfssl_common.h#L84), but it appears to have crept in somewhere else--possibly the inclusion of `<wolfssl/ssl.h>` after the undef. Try this
> 
> ```diff
> --- a/src/libstrongswan/plugins/wolfssl/wolfssl_plugin.c
> +++ b/src/libstrongswan/plugins/wolfssl/wolfssl_plugin.c
> @@ -50,6 +50,9 @@
>  #ifndef FIPS_MODE
>  #define FIPS_MODE 0
>  #endif
> +#ifdef RNG
> +#undef RNG
> +#endif
>  
>  typedef struct private_wolfssl_plugin_t private_wolfssl_plugin_t;
>  
> ```

Added as a patch.

**Comment by pprindeville** [comment]
Waiting for CI/CD

**Pull request merged**
