### PR TITLE
shadowsocks-libev: drop the package

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: me
Compile tested: N/A
Run tested: N/A

Description:

The upstream project is declared as bugfix-only and received no update for about 2 years.  The developement focus there has shifted.  It does not compile with current openwrt main branch.

### CODE REVIEW

**Comment by yousong** [comment]
Related links
- https://github.com/openwrt/packages/issues/24168
- https://github.com/openwrt/packages/pull/24530

**Comment by msdos03** [comment]
I think we shouldn't remove it, because this is the most lightweight implement of shadowsocks. Rust version of it takes up to 4 times more RAM. For many routers, this is important. And we have solution to the compilation problem now.

**Comment by yousong** [comment]
> I think we shouldn't remove it, because this is the most lightweight implement of shadowsocks. Rust version of it takes up to 4 times more RAM. For many routers, this is important. And we have solution to the compilation problem now.

OpenWrt as a downstream project is not to act as a fork of shadowsocks-libev.  Like said in the description, the dev efforts of shadowsocks community has shifted.  Shadowsocks-libev is now a stale project.

**Comment by msdos03** [comment]
@yousong I think before shadowsocks-rust is added to packages, shadowsocks-libev should be reserved. It's common to add dependency fix patch to those projects that are not willing to do that.

**Comment by zxlhhyccc** [comment]
@yousong I agree @msdos03 viewpoint. whether a project is abandoned should consider whether it is actually used by users. For now, this software is still being used by a large number of people, including the server side. So I wouldn't recommend abandoning the project. Unless it's no longer maintained or obsolete.

**Comment by BKPepe** [comment]
There was PR https://github.com/openwrt/packages/pull/22477

**Comment by msdos03** [comment]
> There was PR #22477

But it still haven't been merged. And indeed, shadowsocks-rust have very large binary size (more than 5MB) and RAM consumption (more than 10MB) compared to libev. For routers, these are important.

**Comment by zxlhhyccc** [comment]
@BKPepe @yousong Retention strongly recommended `shadowsocks-libev`.

**Review by 1715173329 — APPROVED** [review]

**Comment by 1715173329** [comment]
The upstream has abandoned libev port and does not accept PRs anymore, there are no active forks too, so it's just dead.

> The community is still paying effort on this package, so at least keep it until nobody want to fix it.

As metioned above, we have discussed removing this package several times, but basically nobody cares.
Maintaining a deprecated (now broken) stuff is really painful, and yousong seems to be too busy to have much effort to maintain it.
In this case, removing it is definitely a better choice rather than wait a (maybe nonexistent) random person to fix it.

> Rust version of it takes up to 4 times more RAM. For many routers, this is important.

I don't think it's that "important". It's 2024, any modern routers should have at least 256 MB RAM, it's pretty enouth for ss-rust and other daemons. Not to mention there are even a certain number of people running clash on mt7621.
For those old devices with limited performance, using old branches is a better option.

**Comment by WeihanLi** [comment]
Should the document be updated to reflect this change, currently, the links in the docs page would lead to 404 due to this remove
docs page link: https://openwrt.org/docs/guide-user/services/proxy/shadowsocks

**Comment by yousong** [comment]
> Should the document be updated to reflect this change, currently, the links in the docs page would lead to 404 due to this remove docs page link: https://openwrt.org/docs/guide-user/services/proxy/shadowsocks

I just added a note describing the drop done here and updated links there to point to the `openwrt-23.05` branch.

**Comment by zdj0925** [comment]
现在有什么推荐的替代品吗？体积小、快速、占用内存小。

**Comment by WeihanLi** [comment]
> 现在有什么推荐的替代品吗？体积小、快速、占用内存小。

v2ray 安装包有点大，路由器装不了 😂

**Comment by yousong** [comment]
I am going to lock the session here.  Please open a new issue or forum post for further discussions.

Show your respects guys.  This is a open place where English is the preferred lang. Not that we are all native or master speakers of that lang, but that other people can join.

**Pull request merged**
