### PR TITLE
mv88e6xxx_dump: add new packages to debug switch issues

### PR DESCRIPTION
**Pull request by champtar**
Maintainer: me
Compile tested: mvebu turris omnia / master https://github.com/openwrt/openwrt/commit/2a20dc717a897efe54f241636ee1566b695dbc7d
Run tested: no (I don't have access to my router for now)
Description:
This might help debug issues like https://github.com/openwrt/openwrt/issues/11877

### CODE REVIEW

**Comment by champtar** [comment]
@chealy thanks for pointing out the existence of this tool (https://github.com/openwrt/openwrt/issues/11077#issuecomment-1399146533), should it work out of the box / anything special to enable ? I just added libmnl as dependency, and I can't test as I don't have access to my router for ~3 weeks

**Comment by robimarko** [comment]
Can't you just use mdio-tools which provide `mvls` tool for the Marvell Linkstreet switches?

**Comment by chealy** [comment]
> Can't you just use `mdio-tools` which provide `mvls` tool for the Marvell Linkstreet switches?

mdio-tools will only provide register values and some of the items being accessed via devlink regions requires querying the contents of MAC database by banging on multiple indirect registers.  This would proof challenging for most people debugging on the platform.

Additionally, the tool I'm pointing to above decodes the register data to human readable data such as the MAC and VLAN databases and port configurations.

**Comment by chealy** [comment]
> @chealy thanks for pointing out the existence of this tool ([openwrt/openwrt#11077 (comment)](https://github.com/openwrt/openwrt/issues/11077#issuecomment-1399146533)), should it work out of the box / anything special to enable ? I just added libmnl as dependency, and I can't test as I don't have access to my router for ~3 weeks

I'm not aware of any special kernel configuration necessary to enable said feature (beyond the Marvell DSA driver in the first place.)  On the userspace side, I'm not aware of the full scope of dependencies.  I wouldn't expect much though.

**Review by chealy — APPROVED** [review]
Reviewed-by: Chris Healy <cphealy@gmail.com>

**Comment by robimarko** [comment]
LGTM, so:
`Reviewed-by: Robert Marko <robimarko@gmail.com>`

**Comment by dhewg** [comment]
A DEPENDS on the kernel CONFIG_NET_DSA_MV88E6XXX would be nice, but I guess that doesn't work as it's compiled in and not a kmod package?
So maybe a DEPENDS on imx||kirkwood||mvebu||qoriq or something like that?

**Comment by champtar** [comment]
@dhewg will add the depends later today / tonight
Still looking for someone to run test this before merging

**Comment by ynezz** [comment]
@champtar package seems to work on Omnia and wrt3200acm.

**Comment by chealy** [comment]
@ynezz  any chance you can share some output from the tool in pastebin or via some other method?

**Comment by ynezz** [comment]
> @ynezz any chance you can share some output from the tool in pastebin or via some other method?

http://sprunge.us/2wsMKk from wrt3200acm

**Comment by chealy** [comment]
@ynezz  Excellent, thank you!
That the VTU is missing may be because the kernel you are using is too old.  Was this tested with 5.10 or 5.15 kernel?

**Comment by ynezz** [comment]
>  That the VTU is missing may be because the kernel you are using is too old. Was this tested with 5.10 or 5.15 kernel?

Indeed, it's running 5.10 kernel, here is output from Omnia running latest snapshot http://sprunge.us/9h6ZAu

**Comment by chealy** [comment]
@ynezz  All the output looks correct.  It could be enhanced to provide more human readable output, but that's a problem for later.  This tool seems good to integrate as it is.

**Comment by champtar** [comment]
@dhewg DEPENDS added
@ynezz thanks for testing
All, thanks for the reviews

**Pull request merged**
