### PR TITLE
shorewall-core: force use of ip-tiny's ip

### PR DESCRIPTION
**Pull request by brianjmurrell**
Maintainer: @wvdakker
Compile tested: ar71xx, wndr4300, 17.01.4
Run tested: same as above

Description:
Add a patch to force the use of ip-tiny's ip command by
shorewall[6]-lite.  This is needed because the PATH used
by shorewall[6]-lite ends up finding the busybox ip command
which does not support some of the needed functionality of
shorewall[6]-lite such as fwmark FWMARK[/MASK].

Signed-off-by: Brian J. Murrell <brian@interlinx.bc.ca>

### CODE REVIEW

**Comment by wvdakker** [comment]
Just a thought: wouldnt it be beter to depend on the IP-FULL package? We dont have to patch the sourcecode then.

**Comment by brianjmurrell** [comment]
> Just a thought: wouldnt it be beter to depend on the IP-FULL package? We dont have to patch the sourcecode then.

Two things about this.  _ip-full_ is bigger than _ip-tiny_ with no (yet) appreciable benefit as far as _shorewall_ is concerned.  Seconddly, it does not resolve the `$PATH` issue.  I actually had both _ip-tiny_ and _ip-full_ installed on my _shorewall-lite_ LEDE router and the _busybox_ `ip` was still being found first.

I think the only non-source-code patching solution is to break the `ip` applet out of the main _busybox_ package into a separate _busybox-ip_ package.

**Comment by wvdakker** [comment]
I second the busybox path option. 
If I look at my system (P2812, trunk) I see the /usr/sbin/ip symlinked to ip-full. My other systems (linksys 3800, P2812 both 17.01.4) the 'ip' is replaced by the 'ip' from the ip-full. 
The 'ip'-option in busybox is enabled but I can not find the busybox 'ip'. So where is it conflicting then?

**Comment by brianjmurrell** [comment]
On my system, built from 17.01.4 using the imagebuilder:

```
root@gw-test:~# find / -name ip-full
root@gw-test:~# find / -name ip-tiny
root@gw-test:~# find / -name ip
/rom/sbin/ip
/rom/usr/bin/ip
/sbin/ip
/usr/bin/ip
# opkg files ip-tiny
Package ip-tiny (4.4.0-9) is installed on root and has the following files:
/usr/bin/ip
root@gw-test:~# opkg files busybox | grep /ip
/sbin/ip
```

**Comment by brianjmurrell** [comment]
Ahh.  So... the default `$PATH` on my LEDE box is `/usr/sbin:/usr/bin:/sbin:/bin` which does put _ip-tiny_'s `ip` at higher precedence than `busybox`'s.

The problem must be that _shorewall_ is setting it's own `$PATH` when calling over to `shorewall-lite` on the LEDE box.

I'm not sure of the best place to fix that so that everyone using _shorewall_ (on their Linux machine for example) with _shorewall-lite_ on LEDE doesn't have to apply a manual fix of the `$PATH` being set when calling `shorewall-lite` on a LEDE box.

**Comment by wvdakker** [comment]
It looks like the trunk version symlinks the 'ip' on a different way.
find / -name ip
/rom/sbin/ip
/sbin/ip

ls /rom/sbin/ip -al
lrwxrwxrwx    1 root     root            13 Dec  7 04:46 /rom/sbin/ip -> /sbin/ip-full

**in 17.01.4**
find / -name ip
/rom/sbin/ip
/rom/usr/sbin/ip
/sbin/ip
/usr/sbin/ip
ls /rom/sbin/ip -al
lrwxrwxrwx    1 root     root            14 Oct 17 19:46 /rom/sbin/ip -> ../bin/busybox

**Comment by brianjmurrell** [comment]
I am rolling up a different patch to set the `$PATH` in _shorewall[6]-lite_'s `shorewall[6]-lite.conf` to the same `$PATH` that LEDE sets in a shell.  That should fix the precedence issue.

**Comment by wvdakker** [comment]
But the shorewall[6]-lite $PATH is empty. So that wont change the default LEDE path?

**Comment by brianjmurrell** [comment]
Right.  I'm still working through this but I believe when the `$PATH` is empty in `shorewall[6]-lite.conf` it's set to a default value in `get_config()`:

```
get_config() {
    local config
    local lib

    ensure_config_path

    config=$(find_file ${PRODUCT}.conf)

    if [ -f $config ]; then
        if [ -r $config ]; then
            . $config
        else
            fatal_error "Cannot read $config! (Hint: Are you root?)"
        fi
    else
        fatal_error "$config does not exist!"
    fi

    ensure_config_path

    [ -f ${VARDIR}/firewall.conf ] && . ${VARDIR}/firewall.conf

    [ -n "$PATH" ] || PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
...
```

which is what is giving precence to the _busybox_ `ip` in _/sbin_.

Just doing another rebuild of my image to verify this and that my alternate patch fixes it.

**Comment by wvdakker** [comment]
But this only solves an issue which is present in 17.01.x and earlier.
Users who are backporting it should then add the right PATH into the config.

We are now solving a backporting issue. But shorewall is not backported and
probably never will. 
The full packages fills in the PATH option in the config to
"/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin"

**Comment by brianjmurrell** [comment]
> But this only solves an issue which is present in 17.01.x and earlier.

I don't think so.  The [different] symlinking that is done is master doesn't solve the problem with which `ip` is found by shorewall's default `$PATH` setting as explained above.  The [different] symlinking just ensures that if somebody wants `ip-tiny` (for example) they can force it by using `ip-tiny` instead of `ip` and leaving it up to `$PATH` to decide which one they get.

> The full packages fills in the PATH option in the config to
"/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin"

Which will yield the _busybox_ `ip`.

**Comment by brianjmurrell** [comment]
#5290 I think is the correct fix for all of this.

**Comment by wvdakker** [comment]
The  'ip' conflict is resolved in the follow commit of package iproute2:
https://git.lede-project.org/?p=source.git;a=commit;h=cfa58651872f6f7b5cb3fa6897883891d1b28617
Making it work in the master repository.

Backporting the iproute2 commit to 17.1.4 would be a nicer option then changing the $PATH option in the config.

**Comment by brianjmurrell** [comment]
No disagreement about how backporting of https://git.lede-project.org/?p=source.git;a=commit;h=cfa58651872f6f7b5cb3fa6897883891d1b28617 would be generally good and useful, but #5290 still resolves the mismatch between the value of `$PATH` on LEDE generally vs. what it is for shorewall[6]-lite, which I think is good in and of itself.  Less surprise and confusion.

In any case, with #5290 landed, this particular issue can be closed.

**Pull request closed without merging**
