### PR TITLE
check: bump to 0.11.0

### PR DESCRIPTION
**Pull request by eduardoabinader**
Maintainer: Nicolas Thill nico@openwrt.org
Compile tested: ar71xx
Run tested: ar71xx

Description:

updated new package url and solved some issues:
https://github.com/libcheck/check/releases/tag/0.10.0

Signed-off-by: Eduardo Abinader eduardoabinader@gmail.com

### CODE REVIEW

**Comment by diizzyy** [comment]
@psycho-nico 
You can please have a look at this?

@eduardoabinader 
You can please refresh this pull request to 0.11.0?
Are you willing to take maintainership if needed?

**Comment by eduardoabinader** [comment]
@diizzyy Sorry for the huge delay...I will refresh the PR.

And yes, I would enjoy taking maintainership.

**Comment by diizzyy** [comment]
@eduardoabinader 
It's all yours, make sure to change maintainer when you fresh this pull request.

**Comment by eduardoabinader** [comment]
@diizzyy done and thanks.

**Pull request merged**
