### PR TITLE
don't use unitialised vars when UNBOUND_D_DHCP_LINK != odhcpd

### PR DESCRIPTION
**Pull request by tripolar**
Signed-off-by: Peter Wagner <tripolar@gmx.at>

Maintainer: me

Description:
don't use unitialised vars when UNBOUND_D_DHCP_LINK != odhcpd

### CODE REVIEW

**Comment by diizzyy** [comment]
Why a new pull request?
https://github.com/openwrt/packages/pull/5920

**Comment by tripolar** [comment]
as i couldn't find a way to tell travis to recheck the code. the easiest way would be to just push this code or add a way to restart the travis check. i updated the Signed-off-by line, how can i now restart the travis check?

**Comment by diizzyy** [comment]
Just close and open your pull request

**Comment by tripolar** [comment]
why doesn't it use the updated text?

**Comment by tripolar** [comment]
i think i will have to repush it with updated signed line

**Comment by diizzyy** [comment]
You haven't pushed an updated commit :-)
```git push --force```

**Comment by tripolar** [comment]
now the name is correct and it still breaks with the same error

**Comment by diizzyy** [comment]
"Commit subject line MUST start with '<package name>: ' (don't use unitialised vars when UNBOUND_D_DHCP_LINK != odhcpd)"

Suggestion (last line is the actual commit msg):

```
unbound: Fix uninitialized variables

Don't use uninitialized variables when UNBOUND_D_DHCP_LINK != odhcpd
```

**Comment by EricLuehrsen** [comment]
Don't forget to ping "@maintainer" in your pull request; it is easy for us to lose track of these.

@hnyman this one is good to merge.

**Pull request merged**
