### PR TITLE
nmap: fix ncat proxy mode with upstream patches

### PR DESCRIPTION
**Pull request by ValdikSS**
Maintainer: @rockdrilla, @diizzyy, @nunojpg
Compile tested: x86 23.03.3
Run tested: x86 23.03.3

Description:
ncat utility from nmap package has a bug in 7.90 and 7.91 version which prevent it from working via proxy.
Cherry-pick patches from 7.92 release.

See #20266

### CODE REVIEW

**Comment by rockdrilla** [comment]
I'm not the maintainer but LGTM.

**Comment by ValdikSS** [comment]
"Dirty patches detected, please refresh and review the diff"

Is this due to the fact that I'm using pre-built SDK? Is it safe to ignore? The patches itself doesn't seem to be dirty (`Patch 04*-proxyfix.patch is unchanged`)

**Comment by trippleflux** [comment]
@ValdikSS 

Why not going more updated nmap, which is version 7.93?.

But need the following additional patch : 
```
diff -Naur a/ncat/http_digest.c b/ncat/http_digest.c
--- a/ncat/http_digest.c
+++ b/ncat/http_digest.c
@@ -132,11 +132,12 @@
 
     return 0;
 }
-
+/*
 #if OPENSSL_API_LEVEL < 10100
 #define EVP_MD_CTX_new EVP_MD_CTX_create
 #define EVP_MD_CTX_free EVP_MD_CTX_destroy
 #endif
+*/
 static char *make_nonce(const struct timeval *tv)
 {
     char *buf = NULL;

```

**Comment by rockdrilla** [comment]
@trippleflux nmap as of version 7.93 is moved to own license (NPSL), 7.92 is last release with "legacy" (but common) license.

**Comment by ValdikSS** [comment]
@trippleflux 
> Why not going more updated nmap, which is version 7.93?.

I'm not very familiar with OpenWRT and I don't have enough time to test everything after a version update. That's why I choose the most safe approach to patch the issue and test only it.

**Comment by ValdikSS** [comment]
Pull request branch switched to master. Please cherry-pick it to 22.03 when it's merged.
PKG_RELEASE is also set to 3.

**Comment by diizzyy** [comment]
Looks fine to be (not tested)

**Comment by nunojpg** [comment]
43c990c43fb145c6b24ac1adbf2a5647dc1aa69e

**Comment by ValdikSS** [comment]
This patch still needs to be applied to 23.03.x.

**Pull request closed without merging**
