### PR TITLE
reptyr: add package

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: me
Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master

Description:
- Add package [reptyr](https://github.com/nelhage/reptyr/)

### CODE REVIEW

**Comment by BKPepe** [comment]
Hm, this fails for mips_24k. I will look at it.

**Comment by BKPepe** [comment]
It seems that mips is not supported looking at https://github.com/nelhage/reptyr/blob/master/platform/linux/linux_ptrace.c#L77

**Comment by BKPepe** [comment]
Disabled for ramips and arc.

**Comment by neheb** [comment]
Should be !mips in DEPENDS.

**Comment by BKPepe** [comment]
> 
> 
> Should be !mips in DEPENDS.

Good to know, I will try it. 
I was a little bit struggling with this as I was trying `TARGET_ramips`, `TARGET_mips`, and both were not working. :(

**Comment by neheb** [comment]
https://github.com/openwrt/packages/blob/master/lang/perl/Makefile#L67 as an example.

**Comment by BKPepe** [comment]
Thanks! I got it, now.

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
As the SDK was broken (should be fixed tomorrow), the buildbots did not catch compilation failures:

https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/reptyr/compile.txt

**Pull request merged**
