### PR TITLE
treewide: update packages to use new toolchain define

### PR DESCRIPTION
**Pull request by Ansuel**
Update packages to use new toolchain define and drop usage of TOOLCHAIN_DIR.

---

This depends on https://github.com/openwrt/openwrt/pull/13738 that needs to be merged first.

### CODE REVIEW

**Comment by BKPepe** [comment]
I retrigged the CI, if it does not help, most likely, it will not, then please try to rebase your repository on the current master branch. I see that the "dependency" (if we can say it like this) was merged, this can be merged as well.

**Comment by jefferyto** [comment]
Rebasing on current master should fix the perl build error for riscv64 (#18668). gummiboot build error for x64_64 is #22433.

**Comment by 1715173329** [comment]
looks like that PR was merged already, so rebase and merge this one?

**Comment by Ansuel** [comment]
@BKPepe CI is good I guess we can merge this?

**Review by 1715173329 — APPROVED** [review]

**Comment by 1715173329** [comment]
Is it good to go?

**Comment by Ansuel** [comment]
Yep

**Pull request merged**
