### PR TITLE
luaposix: disable detection of ldoc

### PR DESCRIPTION
**Pull request by psycho-nico**

### CODE REVIEW

**Comment by mstorchak** [comment]
:+1:

**Comment by karlp** [comment]
Confirmed this works, but shouldn't this bump the package version up as well?  I can add this in and merge it if you both agree.  Thanks for the configure magic @psycho-nico :+1:

**Comment by mstorchak** [comment]
Works for me, please bump PKG_RELEASE and merge it.

**Comment by karlp** [comment]
merged via rebase in 048a311c7a0d4221abf7fc6e07bacec5eef52fdf

**Pull request closed without merging**
