### PR TITLE
gpsd: do not strip gpsd

### PR DESCRIPTION
**Pull request by hauke**
The not strip command is not strip=no, but it is nostrip=yes.
This fixes building this gpsd.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

### CODE REVIEW

**Comment by hauke** [comment]
@psidhu please have a look.

**Comment by Gateworks** [comment]
Yes, you're right. gpsd-3.10 used "strip" in it's SConstruct, while 3.15 uses "nostrip". Note that strip doesn't break building gpsd, but if the host binutils doesn't support elf32-littlearm, then the build will fail. When cross compiling/building for other systems, generally installing binutils-multiarch is the best choice when you require changing binaries meant for other architectures.

**Comment by psidhu** [comment]
Ah, oops. The comment above was by me.

**Comment by hauke** [comment]
In OpenWrt we try to avoid that the user has to install many special packages to make the build work.

**Pull request merged**
