### PR TITLE
dawn: update to latest version

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Includes:
- dawn_iwinfo: fix whitespace
- dawn_iwinfo: indentation
- dawn_iwinfo: iwinfo_finish();
- dawn_iwinfo: filter out global interface
- dawn_iwinfo: release iwinfo after usage
- tcpsocket: fix port print
- github: set CONFIG_SRC_TREE_OVERRIDE in actions CI
- github: fix link to dawn source
- github: use v2 for checkout action
- github: add GitHub Actions CI
- ubus: only update TCP socket list when using TCP connections
- add notice that full wpad is requirement
- fix link to luci-app-dawn
- update readme and install instructions

### CODE REVIEW

**Comment by neheb** [comment]
make check FIXUP=1 can be used to get the hash.

**Comment by PolynomialDivision** [comment]
> make check FIXUP=1 can be used to get the hash.

@neheb 
Can I somehow see why the buildproces fails? I can no longer access the logs

**Comment by neheb** [comment]
```
=== Checking commit 'ac08b94fa955b3a0acc54701661345cf42af5cde'
Author name (Polynomialdivision) need to be your real name 'firstname lastname'
Commit subject line seems ok (dawn: update to latest version)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Polynomialdivision <vincent@systemli.org>')
```

https://patch-diff.githubusercontent.com/raw/openwrt/packages/pull/12243.patch

Notice how From: doesn't match the signoff line.

Accessing the logs doesn't work under mobile. No idea why.

**Comment by PolynomialDivision** [comment]
@neheb K. Fixed everything, please merge. :)

**Pull request merged**
