### PR TITLE
bind: Update named.init and db.root

### PR DESCRIPTION
**Pull request by DonkZZ**
The variable "config_file" appears twice.

### CODE REVIEW

**Comment by yousong** [comment]
Hi, @DonkZZ , thanks for the work.  A few quick notes on the pr

- According to the contributing guide, commits need to be signed off by you, https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#commits-in-your-pull-requests-should
- Please prefix the subject of commit message with the package name, such as `bind: `
- `PKG_RELEASE` in the package makefile needs to be increased to indicate the revision

**Comment by DonkZZ** [comment]
Signed-off-by: DonkZZ donk@evhr.net

**Comment by nmeyerhans** [comment]
Hi, @DonkZZ. The content of the changes looks good. However, please review what @yousong stated previously, as well as the guidelines at https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#commits-in-your-pull-requests-should In particular, the commit messages themselves need to have the package name in the message body, and the commits (each of them) needs to have a Signed-off-by, as added by `git commit -s`

If you can send an updated PR with the commits formatted according to these guidelines, I'll merge it promptly.

**Comment by DonkZZ** [comment]
New Pull requests

https://github.com/openwrt/packages/pull/2526

**Pull request closed without merging**
