### PR TITLE
travelmate: Update README.md

### PR DESCRIPTION
**Pull request by richb-hanover**
I am delighted to learn about the Travelmate package. I don't think it gets enough attention in the OpenWrt community. (I've been contributing for over a decade, and this is the first time I've understood what it could do for me.)

I took the liberty of editing this README (fixing typo's, tweaking Markdown syntax) in advance of creating a page on the OpenWrt wiki that mentions it along with [other Wi-Fi repeaters](https://openwrt.org/docs/guide-user/network/wifi/wifiextenders/start) I also [converted the document to Dokuwiki](https://openwrt.org/docs/guide-user/network/wifi/wifiextenders/start) in advance of that change.

Thanks for this cool tool.

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by BKPepe** [comment]
Btw, this goes into the stable branch. Not sure that's correct.

**Comment by dibdot** [comment]
@BKPepe Good point, as usual.

@richb-hanover Sorry, this PR can't be accepted. It's going to 22.03-branch which is EOL. Please open a PR for master/main branch instead.

**Comment by richb-hanover** [comment]
OK. I will squash and re-submit to main.

**Comment by richb-hanover** [comment]
@dibdot I have to confess that I'm in over my head on this. The file below is squashed, but I'm not sure how to submit it as a PR against master/main.

Would you do this? Thanks.

https://github.com/richb-hanover/packages/blob/master/net/travelmate/files/README.md

**Comment by dibdot** [comment]
Of course I can so this...will take a while cause I'm on vacation.

**Comment by richb-hanover** [comment]
Thanks. No rush on my part...

**Pull request closed without merging**
