### PR TITLE
devel/m4: upgrade to release 1.4.18

### PR DESCRIPTION
**Pull request by xypron**
NEWS has these comments:

Noteworthy changes in release 1.4.18 (2016-12-31) [stable]
* Diagnose --word-regexp as unsupported if it was not configured.
* Preliminary support for OS/2.
* A number of portability improvements inherited from gnulib.

Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

### CODE REVIEW

**Comment by hnyman** [comment]
Could you please update the PR a bit and replace the MD5 hash with a SHA256 hash.

(Leave the variable name as it is now, but replace the hash itself with the longer SHA256 hash.)

Same goes for other packages that you maintaining. MD5 is being phased out, so please use SHA256 when issuing updates as PRs.

**Comment by diizzyy** [comment]
Also, this should perhaps wait a little while until the same version is in /tools (LEDE repo at least?)

Is this runtime tested in any way?

**Comment by xypron** [comment]
Hello Hannu,

why should a variable be called MD5 if it holds an SHA256 hash? That
does not make any sense.

Could you, please, point me to the thread on the openwrt or lede list
that discussed this weird idea.

Abusing the MD5 variable with SHA256 hashes will break compatibility
with older openwrt releases.

If you want an SHA256 hash, please, use an SHA256 variable.

This was already pointed out in
https://bugs.lede-project.org/index.php?do=details&task_id=326&order=id&sort=asc&order2=summary&sort2=desc

Anyway it is safer to use multiple hashes.

Best regards

Heinrich Schuchardt

**Comment by diizzyy** [comment]
SHA256 is preferred and a good portion of the tree already uses SHA256 in PKG_MD5SUM so breakage is already done if that's your concern.

Not sure what happens if you use both PKG_MD5SUM and PKG_HASH but it doesn't make much sense.

**Comment by hnyman** [comment]
> why should a variable be called MD5 if it holds an SHA256 hash?

LEDE has already introduced PKG_HASH with https://github.com/lede-project/source/commit/7416d2e046b87b262b407f8af70b8dd9b2927c70 as the old PKG_MD5SUM name is confusing with sha256 hash there, just like you say. And most core packages in LEDE were switched to use sha256 and the new variable with https://github.com/lede-project/source/commit/720b99215da295a2e7b4acdef30b58bec6acedc2 

Since https://github.com/lede-project/source/commit/7a315b0b5d6aa91695853a8647383876e4b49a7a you can also check the packages' hash usage in your repo/config with "make check".

But as Openwrt has not yet introduced PKG_HASH, we can't yet use it in this packages repo that is common to both.

However, the old PKG_MD5SUM accepts also SHA256 hash since January ( https://dev.openwrt.org/changeset/48253/ ) and quite many packages in the repo have already been converted to use sha256.

But if you are strongly against changing it in this package, let's leave it for now.

> Abusing the MD5 variable with SHA256 hashes will break compatibility with older openwrt releases. 

The master branch is only meant for DD/trunk/master in Openwrt and master in LEDE, both of which support sha256 hash in that variable. Older releases use for-15.05 branch etc.

**Comment by xypron** [comment]
@hnyman 

SHA256SUM is used now as hash.

**Comment by hnyman** [comment]
LEDE master now has 1.4.18 of m4, so let's merge this.

Note that the PKG_HASH variable functionality has been backported to Openwrt in the meanwhile, so in the next version upgrade, please switch the variable name to PKG_HASH

**Pull request merged**
