### PR TITLE
travelmate: added login script for mikrotik captive portal

### PR DESCRIPTION
**Pull request by ChristianKuehnel**
Maintainer: @dibdot
Compile tested: xRX200 rev 1.2, AVM FRITZ!Box 7362 SL, OpenWrt 19.07.7 r11306-c4a6851c72
Run tested: same as compile tested

Description:
Added handling of Mikrotik captive portals

### CODE REVIEW

**Comment by dibdot** [comment]
@ChristianKuehnel Thanks for that! Just a few remarks:

- please remove this "set -eu" stuff, this subscript may error out in the middle of nowhere ... - you should return/error out if user/password parameter are not filled
- travelmate 1.5.x has no dependency to curl, therefore you should check for that, e.g.
```
cmd="$(command -v curl)"

# curl check
#
if [ ! -x "${cmd}" ]
then
	exit 1
fi
```

**Comment by ChristianKuehnel** [comment]
`set -eu` does exactly what you want: It fails if the arguments are missing or if curl is not installed. There is no need for additional checks there. Undefined variables and failing commands are errors, so the script should exit. This make debugging much easier.

Also this PR is for the master branch, I guess there we do have a curl dependency there, right?

**Comment by dibdot** [comment]
No, that doesn't help cause it always breaks with a unspecific "parameter not set" error. I want to receive individual return/error codes which will be evaluated/logged by the calling travelmate.

**Comment by ChristianKuehnel** [comment]
You're the maintainer, so I updated the script to match your requests. Please take a look.

**Comment by dibdot** [comment]
Sorry, still something todo:
- please remove the "echo" statements, only the return codes are visible in the log
- a final return is currently missing at the end of your file
- you need to squash your commits

Thanks!

**Comment by dibdot** [comment]
now superseded by/included in #15254

**Pull request closed without merging**
