### PR TITLE
[23.05] yggdrasil: overhaul package with netifd support

### PR DESCRIPTION
**Pull request by wfleurant**
Maintainer: me
Compile tested: none, see below
Run tested: all package compiling and qa testing done in snapshots
Description: we must backport v0.5 into 23.05 because the breaking protocol situation with v.0.4. the counterpart package, luci-proto-yggdrasil is already in 23.05 feeds.

### CODE REVIEW

**Comment by wfleurant** [comment]
rebuilding.. was missing ./files content

**Comment by 1715173329** [comment]
use `git cherry-pick -x <hash>` to backport your commits from master branch.

**Comment by turretkeeper** [comment]
Looking forward to finally seeing it in a stock build. Big props to @wfleurant

**Comment by wfleurant** [comment]
i think i tried to cherry pick the change, but there was a conflict, so i just hand-patched because it's quite urgent due to breaking protocol changes. is there any exceptions for this reason? i'll try again i guess.

**Comment by wfleurant** [comment]
i will add @stangri patch from shellcheck #22792 when back to workstation ⏳

**Comment by wfleurant** [comment]
are we good?

**Comment by neilalexander** [comment]
Would really appreciate if this can get some attention as the network has already moved onto the new 0.5 protocol, thanks!

**Review by rmilecki — APPROVED** [review]

**Comment by rmilecki** [comment]
Those are backports, looks good to me. If no one handles it (or comments against it) I can merge it soon.

**Review by systemcrash — APPROVED** [review]

**Pull request merged**
