### PR TITLE
sound/shairport: Remove from tree

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @thess 
Compile tested: N/A
Run tested: N/A

Description:
Shairport is unmaintained and superseded by shairport-sync which
is in tree so there's no point in keeping this obsolete package.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@mikebrady ...or am I missing something? :-)

**Comment by mikebrady** [comment]
I think your statement is correct, but it's not really my call as to whether shairport should be dropped – it may still have active users...

**Comment by diizzyy** [comment]
We'll always have users however having that as an argument effectively means that you can never deprecate anything.

**Comment by mikebrady** [comment]
That's a good point. I think that new users should use Shairport Sync and that existing users of Shairport should/could move over to it.

**Comment by pprindeville** [comment]
So we've got shairplay, shairport, shairport-sync-*... is the functionality (and security aspects) equivalent?

**Comment by diizzyy** [comment]
shairport-sync is a fork (continuation) of shairport which is abandoned

**Comment by pprindeville** [comment]
> shairport-sync is a fork (continuation) of shairport which is abandoned

Then I say "nuke it".

**Comment by pprindeville** [comment]
Are the configs the same?  Is migration seamless?

**Comment by mikebrady** [comment]
Unfortunately not – they started out the same, but they have drifted somewhat. All the functionality [that still makes sense] is still there, and more besides.

It's not for me to say, but if it was, I'd also say "nuke it" :)

**Comment by thess** [comment]
OK with me. I'll move this to **packages-abandoned** and remove MAINTAINER.

**Pull request merged**
