### PR TITLE
libjpeg-turbo: Add new package

### PR DESCRIPTION
**Pull request by neheb**
It's faster than regular libjpeg with ASM optimizations for various
platforms.

This is meant to replace the regular libjpeg.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: me
Compile tested: ath79

This is a revival of https://github.com/openwrt/packages/pull/6331

I updated to the latest version and added PROVIDES lines for the two packages. Also replaced InstallDev with CMAKE_INSTALL.

### CODE REVIEW

**Comment by neheb** [comment]
Ugh on first try, it seems this doesn't work right. It exports a libjpeg.so.62 , which conflucts with libjpeg's libjpeg.so.9

Either we get rid of jpeg-9 or make it configurable. The former is a lot simpler.

Initial testing reveals that if the MIPS arch is set to 74kc, optimized assembly gets compiled in. There's actually quite a bit of that:

https://github.com/libjpeg-turbo/libjpeg-turbo/tree/master/simd

Testing powerpc and i386 compilation is next. The latter might fail because of https://github.com/openwrt/openwrt/blob/master/include/target.mk#L180 (patch is available on the mailing list).

**Comment by neheb** [comment]
I ran a decoding benchmark on my Archer C7v2. Results are quite disappointing:

```
https://github.com/libjpeg-turbo/libjpeg-turbo/pull/403#issuecomment-574519524
```

QEMU is not only faster, it's actually slower with DSPr2 enabled. 

It seems there are further improvements available as pull requests: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/373 , https://github.com/libjpeg-turbo/libjpeg-turbo/pull/377

**Comment by neheb** [comment]
libjpeg-turbo is more than twice as fast as libjpeg when it come to decoding jpeg files:

```
libjpeg-turbo:

root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.82s
user	0m 7.73s
sys	0m 0.07s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.86s
user	0m 7.78s
sys	0m 0.07s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.86s
user	0m 7.80s
sys	0m 0.04s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.90s
user	0m 7.83s
sys	0m 0.05s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.84s
user	0m 7.80s
sys	0m 0.02s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.85s
user	0m 7.80s
sys	0m 0.03s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.90s
user	0m 7.81s
sys	0m 0.08s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.90s
user	0m 7.82s
sys	0m 0.06s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.93s
user	0m 7.82s
sys	0m 0.11s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real	0m 7.83s
user	0m 7.66s
sys	0m 0.16s
```

```
libjpeg:

root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.38s
user    0m 16.29s
sys     0m 0.06s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.37s
user    0m 16.27s
sys     0m 0.08s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.34s
user    0m 16.25s
sys     0m 0.06s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.42s
user    0m 16.30s
sys     0m 0.10s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.34s
user    0m 16.29s
sys     0m 0.03s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.36s
user    0m 16.25s
sys     0m 0.09s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.36s
user    0m 16.23s
sys     0m 0.11s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.38s
user    0m 16.29s
sys     0m 0.07s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.37s
user    0m 16.24s
sys     0m 0.10s
root@OpenWrt:/tmp# time djpeg wallhaven-8363o2.jpg > /dev/null
real    0m 16.33s
user    0m 16.22s
sys     0m 0.09s
```

Tests performed on a quite weak TP-LINK TL-WR1043NDv1. On my desktop, time takes 0.07 seconds total time.

**Comment by D-stefaang** [comment]
Thanks for bringing this up! I'd suggest to go for v8c, this can be set with a compiler flag.
I vote to get rid of libjpeg9 for now. Those who need it can set it up manually.

**Comment by neheb** [comment]
Turns out some of the DSPr2 support is totally broken.

I backported three patches that patch out the broken functionality.

I still have no solution to the libjpeg vs turbo issue. I think the way forward is to remove it entirely.

**Comment by neheb** [comment]
It seems @ssvb is interrested in adding dsp support for mt7621. I unfortunately do not have such hardware. Testing would be appreciated.

**Comment by neheb** [comment]
Removed SIMD from mips. Not only is it slower, I assume it will break with older mips stuff.

**Comment by neheb** [comment]
Marking this as ready. I've compile tested this on several "problematic" platforms. It compiles fine.

**Comment by neheb** [comment]
Updated to 2.0.5. Got rid of the patches.

**Comment by lloyd18** [comment]
> WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libjpeg', which does not exist
> WARNING: Makefile 'package/feeds/packages/graphicsmagick/Makefile' has a build dependency on 'libjpeg', which does not exist

WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libjpeg', which does not exist
WARNING: Makefile 'package/feeds/packages/graphicsmagick/Makefile' has a build dependency on 'libjpeg', which does not exist

**Pull request merged**
