### PR TITLE
rp-pppoe: Add back from oldpackages with build fixes and enhanced pac…

### PR DESCRIPTION
**Pull request by dfc-d**
…kaging

Add back from oldpackages with fixes for build errors and UCIfication
(for LuCI app submitted in a related PR (against LuCI repo)).

NOTE: Untested packages have been marked with @BROKEN.  This can
be undone of others report success with the relay and sniffer

Signed-off-by: Daniel Dickinson <openwrt@daniel.thecshore.com>

### CODE REVIEW

**Comment by thierry-dt** [comment]
Is this a copy of PR #2496 ?
I'll just repeat my comment then ;
I've done a quick test for pppoe-relay with your package. Compile and install is ok.
But the init script doesn't support stop/restart/reload, so after reconfig a reboot would be required.
I configured a pppoe-relay instance with both client and server interfaces being separate bridge interfaces, which seemed to work fine.
Why didn't you re-use the existing datamodel as used in AA package 'rp-pppoe '? Now we have to fix config when upgrading a board from AA to CC.

**Comment by dfc-d** [comment]
On 16-05-16 05:21 PM, thierry-dt wrote:
> Is this a copy of PR #2496 <https://github.com/openwrt/packages/pull/2496> ?

I accidentally closed it.

> I'll just repeat my comment then ;
> I've done a quick test for pppoe-relay with your package. Compile and
> install is ok.
> But the init script doesn't support stop/restart/reload, so after
> reconfig a reboot would be required.

Sorry missed that message, will review.

> I configured a pppoe-relay instance with both client and server
> interfaces being separate bridge interfaces, which seemed to work fine.
> Why didn't you re-use the existing datamodel as used in AA package
> 'rp-pppoe '? Now we have to fix config when upgrading a board from AA to CC.

What datamode?  Is it uci-based?  If not then it's a no-go because the
point of the uci is the corresponding LuCI app I created.

oldpackages didn't have an uci config that I noticed.

Regards,

Daniel

**Comment by dfc-d** [comment]
On 16-05-16 05:21 PM, thierry-dt wrote:
> Is this a copy of PR #2496 <https://github.com/openwrt/packages/pull/2496> ?
> I'll just repeat my comment then ;
> I've done a quick test for pppoe-relay with your package. Compile and
> install is ok.

Ok, I'll remove the @BROKEN take from relay then.

> But the init script doesn't support stop/restart/reload, so after
> reconfig a reboot would be required.

Actually those should be handled automagically by procd.  Explicitly
specifying such sections is unnecessary with procd.

> I configured a pppoe-relay instance with both client and server
> interfaces being separate bridge interfaces, which seemed to work fine.
> Why didn't you re-use the existing datamodel as used in AA package
> 'rp-pppoe '? Now we have to fix config when upgrading a board from AA to CC.

I'll add an option to skip the uci config and use the non-openwrt way
(which is all I see in oldpackages).

Regards,

Daniel

**Comment by dfc-d** [comment]
Ok, this now needs testing: I have made the following changes:

1) Removed @BROKEN from relay
2) Added option to allow use of /etc/default/pppoe-* to configure rp-pppoe instead the uci config
3) If /etc/default/pppoe-* already exists set using that as the default instead of the uci config.

**Comment by dfc-d** [comment]
Oh, I also added procd_reload_triggers so that if  you're using the uci config and it changes then the daemon is automatically restart.

**Comment by dfc-d** [comment]
I've also added the procd options to notice changes to /etc/default/pppoe-* so that daemon actually restarts using /etc/init.d/* if those files have changed.  This is probably the issue you were observing.

**Comment by dfc-d** [comment]
I've also added network reload triggers, so if the interfaces change (e.g. up/down) then the daemon should restart in that case as well.

**Comment by dfc-d** [comment]
Pending testing

**Comment by dfc-d** [comment]
Since I've updated with an untested version marked as Untested Request for Comments until I or someone else verifies it works in it's current iteration.

**Comment by dfc-d** [comment]
I've discover that procd no longer has a network_trigger but now has an interface_trigger and a raw_trigger.  I'm not sure which applies here; I've got it set to interface trigger for now.

**Comment by dfc-d** [comment]
Ok, this is now working in my test build, so I believe is ready for merge.

**Comment by dfc-d** [comment]
any more comments or is okay to merge?

**Comment by dfc-d** [comment]
BTW Would it be possible to push access and in case like this with no comments for a month is it okay to merge, or still wait for ACKs (if I get push access)?

**Comment by dfc-d** [comment]
ping

**Pull request merged**
