### PR TITLE
transmission-daemon: change judge logic to 'true/false' value in transmission.init file

### PR DESCRIPTION
**Pull request by siwind**
Maintainer:  @\<github-user> (find it by checking history of the package Makefile)
Compile tested:  Arch Linux x86-64, OpenWrt master
Run tested: (arm_cortex-a7_neon-vfpv4, OpenWrt master, tests done)

Description:

The configuation file of tranmsission-daemon is settings.json,   and its enabled value in this file is 'true/false',  but not '0/1'.
so the judgement logic in  transmission  init file need  change from '0/1'  to 'true/false'.

See this issue:
https://github.com/openwrt/packages/issues/19012

### CODE REVIEW

**Comment by neheb** [comment]
ping @dangowrt

**Comment by dangowrt** [comment]
In a way it would be more coherent with OpenWrt to change the values in `/etc/config/transmission` to be 0/1 instead of "true"/"false" and then generate settings.json based on that. But I can see that your suggestion will fix the problem is the user spells "false" exactly like that (and not "FALSE" or "False" or anything like that...)

**Comment by salim-b** [comment]
This PR doesn't make much sense. See https://github.com/openwrt/packages/pull/20484 for a proper solution.

**Comment by salim-b** [comment]
I'd strongly suggest to close this now that https://github.com/openwrt/packages/pull/20484 is merged.

**Comment by dangowrt** [comment]
Closed in favor of #20484

**Pull request closed without merging**
