### PR TITLE
nfs-kernel-server: update to v2.6.2

### PR DESCRIPTION
**Pull request by oskarirauta**
Also added patch that is from alpine's same package to assist building on musl.
Some overrides for hostpkg configure were also necessary to make it possible to build **on** musl.

Maintainer: Peter Wagner / @tripolar 
Compile tested: x86_64, recent git
Run tested: x86_64, recent git

### CODE REVIEW

**Comment by oskarirauta** [comment]
@1715173329 

Some tests are failing, problem with my PR or with tests?

**Comment by 1715173329** [comment]
see https://github.com/openwrt/openwrt/pull/12049

**Comment by 1715173329** [comment]
You don't need to add this dependency to nfs, it's caused by openssl and already fixed in latest tree.

**Comment by oskarirauta** [comment]
Oh, sorry- I'll revert it :)

**Comment by oskarirauta** [comment]
@1715173329 review maybe..?

**Pull request merged**
