### PR TITLE
golang: Update to 1.18, update patch

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me
Compile tested: armvirt-32 / x86-64, 2022-03-17 snapshot sdk
Run tested: armvirt-32 (qemu), 2022-03-17 snapshot

Description:
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
The CI success on this PR is a false positive, it isn't actually compiling the updated package. I will set this to draft status until the CI issue has been resolved.

**Comment by jefferyto** [comment]
CI should be fixed - marking this as ready for review.

**Comment by Vladdrako** [comment]
<details>
<pre>
Finding targets

Building targets
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# runtime/cgo
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# net
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# net
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# net
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# net
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# net
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# net
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# os/user
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# os/user
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# os/user
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# os/user
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
# os/user
Assembler messages:
Warning: a different -march was already specified, is now 1004kc
github.com/lucas-clemente/quic-go/internal/qtls
# github.com/lucas-clemente/quic-go/internal/qtls
../../vendor/github.com/lucas-clemente/quic-go/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

make[2]: *** [Makefile:68: /home/vladdrako/openwrt/build_dir/target-mipsel_24kc_musl/syncthing-1.18.2/syncthing/.built] Error 2
</pre>
</details>
ramips/mt7621 (compiling with -march=1004kc)
Hmm... It wak ok on previous version...

**Comment by jefferyto** [comment]
Where do you specify -march=1004kc?

**Comment by jefferyto** [comment]
Also, if you look at the error message:

```
# github.com/lucas-clemente/quic-go/internal/qtls
../../vendor/github.com/lucas-clemente/quic-go/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```

syncthing 1.81.2 [uses quic-go 0.22.0](https://github.com/syncthing/syncthing/blob/v1.18.2/go.mod#L31), and quic-go 0.22.0 [doesn't support Go 1.18](https://github.com/lucas-clemente/quic-go/blob/v0.22.0/internal/qtls/go118.go).

I suggest you wait for an update for the syncthing package (or open a PR with an update).

**Comment by Vladdrako** [comment]
> Where do you specify -march=1004kc?

`CONFIG_TARGET_OPTIMIZATION="-O3 -pipe -mips32r2 -march=1004kc -mdsp -mmt -mframe-header-opt"`

> syncthing 1.18.2 [uses quic-go 0.22.0](https://github.com/syncthing/syncthing/blob/v1.18.2/go.mod?rgh-link-date=2022-03-29T07%3A45%3A38Z#L31), and quic-go 0.22.0 [doesn't support Go 1.18](https://github.com/lucas-clemente/quic-go/blob/v0.22.0/internal/qtls/go118.go?rgh-link-date=2022-03-29T07%3A45%3A38Z).

Yeah, updating syncthing to 1.19.1 fixed the issue.

**Comment by aparcar** [comment]
What was the CI issue?

**Comment by jefferyto** [comment]
The CI wasn't building the package from this PR, it was building the original package from the packages feed.

This was the result of the first issue in my commit message ("The src-link line for $GITHUB_WORKSPACE in feeds.conf is overridden."). If you look at [this line](https://github.com/openwrt/gh-action-sdk/blob/d29e7cc00b266b489491a0c04663562780268063/entrypoint.sh#L18), the `> feeds.conf` is clobbering the existing file instead of append to it.

Without the packages_ci feed in feeds.conf, the CI found and built the Go package from the packages feed, and so the build success was a false positive.

**Comment by jefferyto** [comment]
In fact it's probably a bad idea to include both packages_ci and packages feeds at the same time. I suggest adding a configuration option to optionally add the packages feed.

**Comment by stangri** [comment]
@jefferyto any plans to backport to either 21.xx or upcoming 22.xx?

**Comment by jefferyto** [comment]
@stangri if you had checked the [golang commit log in the openwrt-22.03 branch](https://github.com/openwrt/packages/commits/openwrt-22.03/lang/golang), you would have seen that this update was applied a while ago.

21.02 is already released and as such will only receive bug fix updates - this means it will stay on 1.17.

**Pull request merged**
