### PR TITLE
apcupsd: add driver modbus-usb

### PR DESCRIPTION
**Pull request by tru7**
Signed-off-by: Othmar Truniger <github@truniger.ch>

### CODE REVIEW

**Comment by thess** [comment]
Thanks

**Comment by hnyman** [comment]
Does patching "a/include/libusb.h.in.orig" really work?
Should it be "a/include/libusb.h.in"?

libusb.h.in.orig sounds like a leftover from creating the patch manually.

**Comment by tru7** [comment]
It definitively works in my build root. That's the way I do it everywhere when I do it manually. But I'm kind of fresh in github environment and would have no problem doing it differently. I always thought only the target name is relevant. Do you have any hint for a problem with it?

**Comment by hnyman** [comment]
I didn't actually test it, but the notation looked so unorthodox that I raised my voice.

I think that the typical way is to use "a" and "b":
```
--- a/include/libusb.h.in
+++ b/include/libusb.h.in
```

**Comment by tru7** [comment]
thanks for the hint, I will go like that next time so nobody needs to get nervous about it.

**Pull request merged**
