### PR TITLE
iperf3: fix usage with big endian

### PR DESCRIPTION
**Pull request by neheb**
Upstream submissions.

Maintainer: @nbd168

### CODE REVIEW

**Comment by neheb** [comment]
Fixes: https://github.com/openwrt/packages/issues/24116

**Comment by Djfe** [comment]
thanks ❤️
are you going to backport theses fixes eventually?

**Comment by neheb** [comment]
Where do you want it backported?

**Comment by Djfe** [comment]
I thought about the current release
https://github.com/openwrt/packages/tree/openwrt-23.05

**Comment by neheb** [comment]
pushed to 23.05.

**Pull request merged**
