### PR TITLE
Bring back the Tcl language (lang/tcl package)...

### PR DESCRIPTION
**Pull request by mistachkin**
These changes bring back the Tcl language, updating it to the latest stable version (8.6.4).

### CODE REVIEW

**Comment by thess** [comment]
All commits are not signed-off-by. Better yet, rebase/squash these to a single commit. Otherwise, looks good.

**Comment by mistachkin** [comment]
Thanks for the feedback.  I would be happy to make them into a single commit; however, I do not use git enough to know how to do that reliably (i.e. I've read several different and somewhat conflicting sets of steps on how to do this).  Do you know which commands will result in a commit that is acceptable to your project?

**Comment by thess** [comment]
Easiest sequence to do is:

> git rebase -i HEAD~n     (where n = \# of commits to edit/squash)
> (your editor will be invoked with messages to squash, etc. - help is provided)
> git push -f

You PR will be automatically updated.

Likewise you can use: "`git commit --amend`" if all you want to do is fix the commit messsage (like add a signature).

**Comment by mistachkin** [comment]
Thanks for the hints.  I think it should better meet your requirements now.

**Comment by thess** [comment]
Tcl fans rejoice :clap:

**Comment by hnyman** [comment]
the package fails to build, both at buildbot and locally:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/tcl/compile.txt
```
make[2]: Entering directory `/store/buildbot/slave/ar71xx/build/feeds/packages/lang/tcl'
. /store/buildbot/slave/ar71xx/build/include/shell.sh; gzip -dc /store/buildbot/slave/ar71xx/build/dl/tcl8.6.4-src.tar.gz | tar -C /store/buildbot/slave/ar71xx/build/build_dir/target-mips_34kc_musl-1.1.12/tcl8.6.4/.. -xf - 

Applying ./patches/100-disable_tzdata_and_msgs_install.patch using plaintext: 
patching file unix/Makefile.in
Hunk #1 FAILED at 817.
1 out of 1 hunk FAILED -- saving rejects to file unix/Makefile.in.rej
Patch failed!  Please fix ./patches/100-disable_tzdata_and_msgs_install.patch!
```

And when I look manually at the contents of the patch 100-... and the file unix/Makefile.in in the downloaded tcl source, they look totally different, so no wonder that the patch does not apply. (similarly the patch 200-... looks mismatched, although the make never reaches that.)

@mistachkin , please verify the contents of the patches.

**Comment by mistachkin** [comment]
Apparently, the "Makefile.in" has been updated since that patch was created.  Maybe it would be good to simply remove the patch, which would cause the tzdata and messages to be installed?  Otherwise, I can try to work up a replacement patch.

**Comment by mistachkin** [comment]
Also, the second patch (200) appears to be superfluous with Tcl 8.6.4 as well.

**Comment by mistachkin** [comment]
Simply removing both patches may be the best "fix" here.

**Comment by hnyman** [comment]
Possibly so.
how did you manage to compile/test this, when you created the pull request for the import?

**Comment by mistachkin** [comment]
I had a virtual machine setup for it.  I believe it was compiling all of OpenWRT, which took quite a while.  Maybe the patches were simply ignored?

**Comment by hnyman** [comment]
Well, patches are not "simply ignored"...

I have tried compiling the "new" version here without patches, but that fails at the final stages.
I have also tried compiling the "old" version (from oldpackages) with the patches (as the patches apparently target that old version), and that fails too (but differently).

So far the whole package looks broken to me.
But please try to fix it.

**Comment by mistachkin** [comment]
Can you share the build logs for the failure when the patches are left out?  I don't have the virtual machine anymore, so I'll need to set it up again.  Hopefully, I'll have time this weekend.

**Comment by hnyman** [comment]
Here is the core part with the error of building 8.6.4 without patches (for ar71xx mips architecture).
The error comes from a ranlib command:
```
mips-openwrt-linux-musl-gcc-ranlib libitcl4.0.3.so
/Openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-5.2.0_musl-1.1.12/lib/gcc/mips-openwrt-linux-musl/5.2.0/../../../../mips-openwrt-linux-musl/bin/ranlib: libitcl4.0.3.so: File format not recognized
Makefile:270: recipe for target 'libitcl4.0.3.so' failed
make[4]: *** [libitcl4.0.3.so] Error 1
make[4]: Leaving directory '/Openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.12/tcl8.6.4/unix/pkgs/itcl4.0.3'
Makefile:1743: recipe for target 'packages' failed
make[3]: *** [packages] Error 2
make[3]: Leaving directory '/Openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.12/tcl8.6.4/unix'
Makefile:73: recipe for target '/Openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.12/tcl8.6.4/.built' failed
make[2]: *** [/Openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.12/tcl8.6.4/.built] Error 2
```

Full build log of the package:
https://gist.github.com/hnyman/a04a51c36d9d616b41c5

**Comment by mistachkin** [comment]
Ah, the bundled packages.  I think the "pkgs" directory should probably be removed prior to building as I do not think it will cross-compile correctly.  If people really need Thread and/or ITcl, etc, they can always install them later?

**Comment by mistachkin** [comment]
Actually, I think the children of the "pkgs" directory should be removed, since they are not hard-coded into the Tcl build process (it uses a glob pattern to grab them).

**Comment by hnyman** [comment]
Feel free to draft a suitable solution and issue a pull request. That is your job as the maintainer ;-)
And please test the fix first.

(I have no knowledge on tcl and no special interest on it. I just noticed from the buildbot logs that something is fundamentally wrong with this package as the patches do no apply to the sources.  The initial pull request has apparently been invalid. The package should either be fixed or moved to the abandoned packages repo.)

**Comment by mistachkin** [comment]
It would be far easier to deal with this issue (and any others that may arise) if I had access to a "known good" environment suitable for building the OpenWRT packages.  Perhaps there is a bre-baked VM image somewhere I can use?

**Comment by hnyman** [comment]
There is no special things needed. A normal Linux in a VM should be enough.

Personally I am using an Ubuntu 15.10 x64 image, into which I installed the prerequisites (as listed on Wiki: https://wiki.openwrt.org/doc/howto/buildroot.exigence#examples_of_package_installations  ) and then checked out the Openwrt trunk. The tools & toolchain will be compiled according to your router's platform.

You might also use the SDK that is available from the downloads, but I have never used that, as it is easy enough to compile normally the full toolchain.

**Comment by thess** [comment]
OKAY - I played around with this a bit and at a minimum, you need to:
* Remove the __pkgs__ directory as you already mentioned (hint: define Build/Prepare function)
* Remove the __patches__ from the repo - they no longer apply.
* Install missing files like /usr/lib/tcl8.6/init.tcl, and maybe other library stuff.

Until this is done, I am marking this package BROKEN.

**Comment by mistachkin** [comment]
I also need to update it to 8.6.5.  I'll get to this as soon as I can.

**Comment by NightBlues** [comment]
Please, consider my attempt to repair package according to @thess advices: https://github.com/openwrt/packages/pull/7205

**Pull request merged**
