### PR TITLE
wifidog-ng: remove package

### PR DESCRIPTION
**Pull request by zhaojh329**
Signed-off-by: Jianhui Zhao <zhaojh329@gmail.com>

Maintainer: me
Compile tested:
Run tested:

Description:

### CODE REVIEW

**Comment by neheb** [comment]
Curious why

**Comment by zhaojh329** [comment]
Too dependent on the linux kernel version.

**Comment by neheb** [comment]
Please open a pull request adding this package here: https://github.com/openwrt/packages-abandoned

**Comment by neheb** [comment]
https://github.com/openwrt/packages-abandoned/pull/13

works for me.

**Pull request merged**
