### PR TITLE
rust-lang: Version 1.68.0

### PR DESCRIPTION
**Pull request by lu-zero**
Maintainer: me
Compile tested: aarch64 master
Run tested: aarch64 master

Description: Version bump

### CODE REVIEW

**Comment by lu-zero** [comment]
@PolynomialDivision I couldn't find where `Warning: Skipping rust due to unsupported architecture` is produced, is it possible to change it to print which is the architecture not supported? I have no idea why the CI for `i386_pentium-mmx` now.

**Comment by 1715173329** [comment]
commit title should be `rust-lang: bump to 1.68.0` or `rust-lang: update to 1.68.0` ;)

**Comment by trippleflux** [comment]
@lu-zero 
Wow, just realize your rust lang package got accepted yesterday, congrats and great work for all these times :-).

Really appreciated from me, still building bandwhich, bottom, and trippy for x86_64 glibc.

I hope that if you have the chances to take a look or upgrade python-cryptography with rust?, also suricata.

**Comment by lu-zero** [comment]
python-cryptography is in a separate branch and works (I have packaged about 2/3 of the Home Assistant dependencies). Keep in mind that some discussion is required since supporting the ARC target requires a separate fork of rust.

**Comment by trippleflux** [comment]
Does the ARC you've meant are glibc and musl? or x86_64 ?.

If it's about libc (musl & glibc) then are there any possibilities to supports both in a single OpenWrt Makefile?

**Comment by lu-zero** [comment]
> Does the ARC you've meant are glibc and musl? or x86_64 ?.
> 
> If it's about libc (musl & glibc) then are there any possibilities to supports both in a single OpenWrt Makefile?

No it is about the ARC processor target I see in the CI. And the strange change that makes i386_pentium-mmx not pick the update

**Comment by trippleflux** [comment]
Probably pentium-mmx CPU intruction sets are just too old?, or the OpenWrt CI is using old cache.

Does your python-cryptography OpenWrt package is available for public?, if yesCan you point/direct me into the repo?.

Tried in [here](https://github.com/lu-zero/rust/tree/openwrt-targets), but nothing about python-cryptography.

**Comment by lu-zero** [comment]
https://github.com/domo-iot/packages/commit/e7f4af327348a9febe4d6d5910c46cb64ce54c66 it needs a rebase though.

**Comment by trippleflux** [comment]
Thanks man, also digging up from your old PR, incase it's helpful to others, baseline for suricata work can be checked from [here](https://github.com/Itus-Shield/packages/commits/working).

**Comment by jefferyto** [comment]
CI runs now appear to take forever to complete. Would it be possible to limit CI runs for Rust-related packages to 1-2, so it doesn't block other PRs?

**Comment by trippleflux** [comment]
@lu-zero 
Failed to compiling bandwhich and trippy for x86_64 glibc, have you tested x86_64 glibc before?, also using this PR.

**Comment by lu-zero** [comment]
I never tried, so I do not know which are the errors?

**Comment by trippleflux** [comment]
bandwhich errors : 
```
    |                      ^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `Err` in this scope
    --> /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/json.rs:2540:23
     |
2540 |             Err(_) => Err(fmt::Error)
     |                       ^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
    --> /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/json.rs:2551:22
     |
2551 |             Ok(_) => Ok(()),
     |                      ^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `Err` in this scope
    --> /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/json.rs:2552:23
     |
2552 |             Err(_) => Err(fmt::Error)
     |                       ^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
    --> /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/json.rs:2560:23
     |
2560 |         self.indent = Some(indent);
     |                       ^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
    --> /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/json.rs:2575:22
     |
2575 |             Ok(_) => Ok(()),
     |                      ^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `Err` in this scope
    --> /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/json.rs:2576:23
     |
2576 |             Err(_) => Err(fmt::Error)
     |                       ^^^ not found in this scope

Some errors have detailed explanations: E0405, E0408, E0412, E0425, E0433, E0463, E0531.
error: could not compile `rustc-serialize` due to 1394 previous errors

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_serialize /home/username/works/openwrt/staging_dir/host/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=380 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=6908cb68259709c4 -C extra-filename=-6908cb68259709c4 --out-dir /home/username/works/openwrt/build_dir/target-x86_64_glibc_custom/bandwhich-0.20.0/target/stripped/deps -C linker=x86_64-openwrt-linux-gnu-gcc -C strip=symbols -L dependency=/home/username/works/openwrt/build_dir/target-x86_64_glibc_custom/bandwhich-0.20.0/target/stripped/deps --cap-lints allow` (exit status: 1)
error: failed to compile `bandwhich v0.20.0 (/home/username/works/openwrt/build_dir/target-x86_64_glibc_custom/bandwhich-0.20.0)`, intermediate artifacts can be found at `/home/username/works/openwrt/build_dir/target-x86_64_glibc_custom/bandwhich-0.20.0/target`
make[2]: *** [Makefile:47: /home/username/works/openwrt/build_dir/target-x86_64_glibc_custom/bandwhich-0.20.0/.built] Error 101
make[2]: Leaving directory '/home/username/works/openwrt/feeds/packages/net/bandwhich'
time: package/feeds/packages/bandwhich/compile#1.36#0.84#2.80
    ERROR: package/feeds/packages/bandwhich failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/bandwhich/compile] Error 1
make[1]: Leaving directory '/home/username/works/openwrt'
make: *** [/home/username/works/openwrt/include/toplevel.mk:231: package/bandwhich/compile] Error 2
```

Tried ripgrep also not successfully compiling for x86_64 glibc, also trippy, getting nearly same errors.
I think rust for glibc is still incomplete.

Do you active in OpenWrt forums?, if you don't mind to get in touch about these in there?, what is your username.

**Comment by lu-zero** [comment]
the username `lu_zero`, it looks like there is a target mismatch.

**Comment by 1715173329** [comment]
> I couldn't find where Warning: Skipping rust due to unsupported architecture is produced, is it possible to change it to print which is the architecture not supported? I have no idea why the CI for `i386_pentium-mmx` now.

It's expected as this package is host-build only, but I have no idea why it just failed for i386.

**Comment by lu-zero** [comment]
As long llvm is recent enough it can be shared for the two purposes, llvm needs to support the same targets needed: host, target and bpf.

**Comment by 1715173329** [comment]
> CI runs now appear to take forever to complete. Would it be possible to limit CI runs for Rust-related packages to 1-2, so it doesn't block other PRs?

Looks like it's not that possible to limit concurrency for just specific packages...

**Comment by 1715173329** [comment]
Comfirmed it builds for i386 target on a x64 host.

**Comment by lu-zero** [comment]
> > As long llvm is recent enough it can be shared for the two purposes, llvm needs to support the same targets needed: host, target and bpf.
> 
> I don't know much about llvm and rust-lang. Perhaps, you might consider submitting a PR to implement it.
> 
> @lu-zero I have some questions not related to this PR.
> 
>     1. This action seems to be useless for now, because the backups cannot be reused by the compilation process.
>        https://github.com/openwrt/packages/blob/1dfb13eaebfe2907cdf48bd2053bc0bd7919a42f/lang/rust/Makefile#L111-L119
> 
>     2. I'm curious if these dependencies are used since this is only a host build. If the they are used by the host build, you may add them by `HOST_BUILD_DEPENDS`.
>        https://github.com/openwrt/packages/blob/1dfb13eaebfe2907cdf48bd2053bc0bd7919a42f/lang/rust/Makefile#L127
> 
>     3. The `CONFIGURE_ARGS` in this file will also not used because it is not included in any files and it has no effect in host builds.
>        https://github.com/openwrt/packages/blob/1dfb13eaebfe2907cdf48bd2053bc0bd7919a42f/lang/rust/rust_config.mk#L2

They are all inherited from the initial effort that assumed we want to package rust for the target as well, they can be removed or we can add it as option.

Regarding `HOST_BUILD_DEPENDS`, when I checked openwrt does not have those packages as host packages, libressl is provided and luckily the current rustc supports it, the lzma provided seems problematic so I update the internal dependencies to make a static build of it.

**Comment by jefferyto** [comment]
> Looks like it's not that possible to limit concurrency for just specific packages...

Perhaps can only open 1-2 Rust program PRs at a time, instead of triggering the CI for all of them?

**Comment by 1715173329** [comment]
> Perhaps can only open 1-2 Rust program PRs at a time, instead of triggering the CI for all of them?

Yup, but it's up to our contributors😂

**Comment by 1715173329** [comment]
> > CI runs now appear to take forever to complete. Would it be possible to limit CI runs for Rust-related packages to 1-2, so it doesn't block other PRs?
> > Edit: @PolynomialDivision most (all?) of the Rust program PRs appear to be yours
> 
> I have used the [llvm-bpf](https://github.com/openwrt/openwrt/tree/master/tools/llvm-bpf) as the custom LLVM and it will save about half the compiling time.The llvm-bpf tarball size will increase ~72MiB.
> 
> llvm-bpf needs to disable `LLVM_INSTALL_TOOLCHAIN_ONLY` and enable `LLVM_INSTALL_UTILS` to install the necessary libraries, headers and binaries.
> 
> ```
> --- a/tools/llvm-bpf/Makefile
> +++ b/tools/llvm-bpf/Makefile
> @@ -32,11 +32,10 @@ CMAKE_HOST_OPTIONS += \
>         -DLLVM_INCLUDE_EXAMPLES=OFF \
>         -DLLVM_INCLUDE_TESTS=OFF \
>         -DLLVM_ENABLE_PROJECTS="clang;lld" \
> -       -DLLVM_TARGETS_TO_BUILD=BPF \
> +       -DLLVM_TARGETS_TO_BUILD="X86;BPF" \
>         -DCLANG_BUILD_EXAMPLES=OFF \
> -       -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
>         -DLLVM_LINK_LLVM_DYLIB=ON \
> -       -DLLVM_TOOLCHAIN_TOOLS="llvm-objcopy;llvm-objdump;llvm-readelf;llvm-strip;llvm-ar;llvm-as;llvm-dis;llvm-link;llvm-nm;llvm-ranlib;llc;opt" \
> +       -DLLVM_INSTALL_UTILS=ON \
>         -DCMAKE_SKIP_RPATH=OFF
>  
>  define Host/Install
> ```
> 
> ```
> --- a/feeds/packages/lang/rust/Makefile
> +++ b/feeds/packages/lang/rust/Makefile
> @@ -59,13 +59,13 @@ HOST_CONFIGURE_ARGS = \
>         --datadir=$(CARGO_HOME)/share \
>         --mandir=$(CARGO_HOME)/man \
>         --dist-compression-formats=xz \
> -       --enable-llvm-link-shared \
>         --enable-llvm-plugins \
>         --enable-missing-tools \
>         --enable-ninja \
>         --disable-sanitizers \
>         --release-channel=stable \
>         --enable-cargo-native-static \
> +       --llvm-root=$(STAGING_DIR_HOST)/llvm-bpf \
>         $(TARGET_CONFIGURE_ARGS)
>  
>  define Host/Prepare
> @@ -87,7 +87,7 @@ endef
>  # Makes and then packages the dist artifacts
>  define Host/Compile
>         cd $(HOST_BUILD_DIR) && \
> -         $(PYTHON) x.py --config ./config.toml dist build-manifest cargo llvm-tools \
> +         $(PYTHON) x.py --config ./config.toml dist build-manifest cargo \
>             rustc rust-std rust-src
>  
>         $(call Host/PackageDist)
> ```

cc @nbd168 for llvm-bpf change

**Comment by PolynomialDivision** [comment]
@1715173329 I would say go for it and put that into a PR to main repository. With that you will get more attention. ;)

**Comment by 1715173329** [comment]
I hate llvm... After switching to my host llvm toolchain (`--llvm-root=/usr`), the whole rust build just takes 10 minutes...🤦‍♀️

**Comment by 1715173329** [comment]
> llvm-bpf needs to disable `LLVM_INSTALL_TOOLCHAIN_ONLY` and enable `LLVM_INSTALL_UTILS` to install the necessary libraries, headers and binaries.

... and need to disable `LLVM_ENABLE_ZSTD` otherwise `rustc_driver` will fail to link to zstd:

>   = note: /usr/bin/ld: cannot find -lzstd
>           collect2: error: ld returned 1 exit status

I can't find a way to pass extra ldflags.

**Comment by lu-zero** [comment]
that looks like is a problem with the link line provided by the llvm component, is zstd shared-only or static-only?

**Comment by 1715173329** [comment]
it's static-only. see https://github.com/openwrt/openwrt/blob/513d15cb799eade5ad85a44fae03862a56790a8b/tools/zstd/Makefile#L22

and llvm need to enable more targets when doing a crossing-compile:
LLVM_TARGETS_TO_BUILD="X86;AArch64;BPF"

**Comment by 1715173329** [comment]
I've started thinking enabling the prebuilt llvm toolchain with `--set=llvm.download-ci-llvm=true`, which would greatly reduce the build time, so we will have more time working on improving `llvm-bpf`.

**Comment by lu-zero** [comment]
It is another option, we could add a second provider for rustc that leverages rustup as long the host is one of those supported by rustup (and we trust it).

**Comment by 1715173329** [comment]
I'm not sure if the newer version of rustup will work for OpenWrt: https://github.com/openwrt/packages/pull/13040#issuecomment-804654116.
But generally speaking, we would perfer building everything from source as much as possible.

**Comment by lu-zero** [comment]
they do (softfloat and hardfloat are both supported), but I assumed that preference as well :)
factoring llvm is the best option if we want to minimize the build time.

**Comment by 1715173329** [comment]
Oh, maybe I wrote the wrong path, will check it later today.

**Comment by 1715173329** [comment]
I have no idea how `HOST_LDFLAGS` works for you, looks like rustc doesn't pick it at all.

zstd is also disabled in their own llvm build:
https://github.com/rust-lang/rust/blob/85123d2504885e4670d80dab96f4f9629f2be98b/src/bootstrap/native.rs#L351

**Comment by 1715173329** [comment]
> I would like to say that I did not modify the default HOST_LDFLAGS. My modifications are listed in https://github.com/openwrt/packages/pull/20629#issuecomment-1465415954 and it works for SDK builds. I'm not opposed to disabling zstd. I'm just curious about the link failure itself.

I did it in buildroot (build everything from source), maybe there're some minor differences.

From the rust's build log it's only linked to its internal path and the llvm-bpf directory:
> "-L" "/home/openwrt/openwrt-master/staging_dir/host/llvm-bpf-15.0.7.Linux-x86_64/lib"

**Comment by 1715173329** [comment]
> Can you check if zstd was built after llvm-bpf?

Nah, zstd is built before llvm-bpf (I have to rebuild llvm-bpf after making changes)

**Comment by 1715173329** [comment]
fine, thanks for the test. maybe I need run it on another clean host...

**Pull request merged**
