### PR TITLE
[19.07] nextdns: Update to version 1.12.3

### PR DESCRIPTION
**Pull request by rs**
Update to version 1.12.3

### CODE REVIEW

**Comment by neheb** [comment]
19.07 has golang 1.13.15. I take it this doesn't work with that?

**Comment by neheb** [comment]
Yeah looks like it:

```
2021-04-19T23:30:02.4007865Z go build github.com/lucas-clemente/quic-go/internal/qtls: build constraints exclude all Go files in /home/build/openwrt/build_dir/target-x86_64_musl/nextdns-1.12.3/.go_work/build/pkg/mod/github.com/lucas-clemente/quic-go@v0.20.0/internal/qtls
```

**Comment by rs** [comment]
That's probably the issue. I will submit a version without quic/http3 support for 19.07 so it does compile.

**Comment by rs** [comment]
@neheb seems like GO_PKG_TAGS is not supported in 19.07. Do you know another way to pass a Go build tag?

**Comment by rs** [comment]
A 1.12.5 is coming with a workaround

**Pull request closed without merging**
