### PR TITLE
sms-tool: update to 2023-09-21

### PR DESCRIPTION
**Pull request by helllamer**
Maintainer: @bam80 , @helllamer (me)
Compile tested: x86_64_v3, ipq40xx, OpenWrt SNAPSHOT r24723-7ddd3abd27
Run tested: zte mf286d, OpenWrt SNAPSHOT r24707-4693514ca8 / LuCI Master git-23.357.52396-5355b7b
```
root@router:/tmp# opkg install sms-tool_2023-09-21-1b6ca032-1_arm_cortex-a7_neon-vfpv4.ipk
Upgrading sms-tool on root from 2022-03-21-f07699ab-1 to 2023-09-21-1b6ca032-1...
Configuring sms-tool.
root@router:/tmp# sms_tool -d /dev/ttyUSB1 recv
MSG: 0
From: MTC_ID
Date/Time: 01/01/24 20:54:40
Reference number: 53
SMS segment 1 of 2
0585 - ваш код для доступа к сервису МТС
```

Description:
This is rebase of  #22204 , see comments and descriptions there.

Also, i've confirming that [issue #9 with sms displaying](https://github.com/4IceG/luci-app-sms-tool-js/issues/9) is fixed, and sms table properly displayed.

### CODE REVIEW

**Comment by BKPepe** [comment]
There is something wrong with the commits, which you want to merge into the master branch. Three commits and actually only one is required.

**Comment by helllamer** [comment]
@BKPepe  You are right. This PR is just bumping for other's stalled commits.

I've force-pushed with squashed normalized commit message. Now, it looks prettier and simpler.

**Comment by bam80** [comment]
I fixed original #22204, so probably this one can be closed.
Thanks.

**Comment by helllamer** [comment]
@bam80 Sounds good.

Waiting for maintainers decision @BKPepe

**Comment by BKPepe** [comment]
I dont care which one will be merged. Yours or his... the important part is that it will be merged, nothing else matters.

**Comment by helllamer** [comment]
@BKPepe Ok, please merge  #22204

**Pull request closed without merging**
