### PR TITLE
libgphoto2 and gphoto2: Update to 2.5.14

### PR DESCRIPTION
**Pull request by DocLM**
Maintainer: me / @DocLM
Compile tested: (ramips, mt7688, LEDE 17.01.0)
Run tested: (ramips, mt7688, LEDE 17.01.0)

Description:
Update libgphoto2 and gphoto2 to version 2.5.14

### CODE REVIEW

**Comment by hnyman** [comment]
Please drop the deprecated PKG_MD5SUM next time, as you already have the PKG_HASH there.

**Comment by hnyman** [comment]
@DocLM

gphoto fails now in buildbot as there are missing dependencies:
```
Package libgphoto2-drivers-ax203 is missing dependencies for the following libraries:
libgd.so.3
libjpeg.so.9
libpng16.so.16
libz.so.1
Makefile:826: recipe for target '/data/bowl-builder/mips_24kc/build/sdk/bin/packages/mips_24kc/packages/libgphoto2-drivers-ax203_2.5.14-1_mips_24kc.ipk' failed
```
http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/libgphoto2/compile.txt

Please look into it.

(If you have not seen that in your local build, it may be possibly triggered by buildbot having all libs available and when gphoto's configure script finds libjpeg, it activates that feature for that subpackage.)

**Comment by DocLM** [comment]
I think it is related to libgd, the "--without-gd" configure arg was wrong.

**Comment by nsmith1024** [comment]
Hello,

Its been 5 years since OpenWRT got the latest updates of gphoto2 and libgphoto2, a lot of bug fixes and improvements have been done in 5 years.

I would like to request that you upgrade those packages gphoto2 and libgphoto2 (and camera sub-packages) to their latest version for OpenWRT.

Thanks

**Pull request merged**
