### PR TITLE
Reduce python dependencies

### PR DESCRIPTION
**Pull request by grosjo**
Maintainer: grosjo
Compile tested: ath79, 24.10
Run tested: ath79, 24.10

Description:
Purpose is to reduce the number of libraries and related size that are useless for some modules

### CODE REVIEW

**Comment by grosjo** [comment]
@commodo and @vidplace7 : How to push this in master ?
Thank you so much

**Comment by commodo** [comment]
PKG_RELEASE needs to be incremented in both `Makefile`

**Comment by commodo** [comment]
Test formalities need to be addressed

**Comment by jefferyto** [comment]
* python3-urllib depends on python3-email (#12942), until that issue is resolved that's why python-cryptography includes the dependency on python3-email
* If you run `make package/python-urllib3/configure PY3=stdlib V=s` you will see the package depends on:
  * python3-asyncio
  * python3-ctypes
  * python3-email
  * python3-logging
  * python3-openssl
  * python3-urllib

  asyncio appears to be only used in the dummyserver, but the other packages appear to be real dependencies. That's why python-urllib3 depends on python3 (instead of the 5 separate packages)

> Maintainer: grosjo

This line should mention the package maintainers (@BKPepe and myself), not the author of the PR.

**Comment by BKPepe** [comment]
I will add more dependencies in separate PR for urllib3, thanks for checking, @jefferyto.

**Comment by grosjo** [comment]
Instead of arguing on urllib3 having a circular dep on email (which is wrong, as I can compile properly without any issue using my PR), maybe better test/fix it instead ?

**Pull request closed without merging**
