### PR TITLE
perl: Run make depend to fix build race condition

### PR DESCRIPTION
**Pull request by Rondom**
Maintainer: @Naoir @pprindeville 
Compile tested: x86_64, qemu, master
Compile tested: aarch64, mt7986 rfb, fork based on 23.05.2.  <= This has removed the failures mentioned in the log messages, but did not fix all races on 23.02.
Run tested: x86_64, qemu, master, Ran ` perl -E 'say("hello")'`

I could not see any races on master after applying this patch. On 23.05.2 I still see other races, but this patch seems to fix all occurences of the race described in the commit message and in the linked Debian bug report. Admittedly the testing on master was less thorough compared to the testing on 23.05.2, but I can confirm that this patch successfuly fixes one race and does not create any known new issues, so I think it is good to merge

~~Currently in draft status, because I am still waiting to confirm that the fix really fixes all issues. So I would like to wait a week or so, so I can see whether we really do not see any parallel build failures anymore.~~ I would appreciate if others who are encountering the issue (@mweinelt @blocktrron ?) can test this as well and confirm that the issue is fixed for them.

# Description:

## perl: Run make depend to fix build race condition

Run make depend before building perl. This fixes parallel build failures on machines with a high number of cores.

Example error 1:

    /bin/ln -s /build/staging_dir/hostpkg/usr/bin/generate_uudmap generate_uidmap
    make[5]: ./generate_uudmap: Command not found
    make[5]: *** [Makefile:321: bitcount.h] Error 127

Example error 2:

    /bin/ln -s /build/staging_dir/hostpkg/usr/bin/generate_uudmap generate_udmap
    ./generate_uudmap uudmap.h bitcount.h mg_data.h
    /bin/ln: failed to create symbolic link 'generate_uudmap': File exists
    make[5]: *** [Makefile:325: generate_uudmap] Error 1

Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996953
Link: https://salsa.debian.org/perl-team/interpreter/perl/-/commit/366bc98c916a3455f15c532aa33a5636d2fe2803
Closes: https://github.com/openwrt/packages/issues/8238

### CODE REVIEW

**Comment by BKPepe** [comment]
Ping @muzikr, because I know that Turris OS (which is using OpenWrt with its own additional feed) have same issues with perl regarding parallel builds.

**Comment by mweinelt** [comment]
Sorry, not in a position to reproduce any longer.

**Comment by Rondom** [comment]
I could not see any races on master after applying this patch. On 23.05.2 I still see other races, but this patch seems to fix all occurrences of the race described in the commit message and in the linked Debian bug report and build failures on 23.05.2 which were very common before  have become a very seldom occurrence after applying this patch.

Admittedly the testing on master was less thorough compared to the testing on 23.05.2, but I can confirm that this patch successfully fixes one race and does not create any known new issues, so I think it is good to merge.

**Review by pprindeville — CHANGES_REQUESTED** [review]
You'd need to bump the `PKG_VERSION`.

**Comment by Rondom** [comment]
> You'd need to bump the `PKG_VERSION`.
Done

**Review by pprindeville — APPROVED** [review]
LGTM

**Pull request merged**
