### PR TITLE
strongswan: allow to specify per-connection reqid with UCI

### PR DESCRIPTION
**Pull request by paulfertser**
Signed-off-by: Paul Fertser <fercerpav@gmail.com>

Maintainer: @stintel

### CODE REVIEW

**Comment by feckert** [comment]
@paulfertser please fix your indentation

**Comment by stintel** [comment]
Can you explain in the commit message why this is useful?

**Comment by paulfertser** [comment]
@stintel , hey, is this enough of justification now?

**Comment by stintel** [comment]
That is actually very useful. I have never thought of doing it like that and use a custom up script.
Thanks for your contribution.

**Comment by paulfertser** [comment]
All credit should go to the fellow on IRC who preferred to offload upstreaming of this small patch to me :) Thanks, stintel!

**Pull request merged**
