### PR TITLE
joe: update resource file for version safety

### PR DESCRIPTION
**Pull request by aTanW**
Signed-off-by: Vitaly Protsko
---
 joerc |    5 -----
 1 file changed, 5 deletions(-)

### CODE REVIEW

**Comment by karlp** [comment]
So, what exactly is "version safety" please?  This change stops joe from displaying it's version on startup.  Why?  Further it removes the help text showing the default keymaps to exit.  I don't understand the motivation of this patch.

**Comment by thess** [comment]
I think this whole version hiding thing is getting out of hand. There were some PRs submitted for dropbear and other packages to no longer show their versions in SSL negotiation protocol which IS prescribed by the standard. I don't get it - hiding a version number does not stop any attack probes looking for vulnerabilities (if the attack software is any good) AND it makes support more difficult.

NAK on this one - just my opine.

**Comment by aTanW** [comment]
Hi!

The only thing is time save for old joe users coming to owrt.

Ok, lets nak it.

/aTan


14 сентября 2016 г. 20:06:39 GMT+03:00, Ted Hess <notifications@github.com> пишет:
>I think this whole version hiding thing is getting out of hand. There
>were some PRs submitted for dropbear and other packages to no longer
>show their versions in SSL negotiation protocol which IS prescribed by
>the standard. I don't get it - hiding a version number does not stop
>any attack probes looking for vulnerabilities (if the attack software
>is any good) AND it makes support more difficult.
>
>NAK on this one - just my opine.

**Comment by aTanW** [comment]
Hi!

Means old joe versions does not interpret this directives, but this file can be easily used outside owrt.

Ok, nessecity is doubt. Lets nak it.

/aTan


14 сентября 2016 г. 18:53:35 GMT+03:00, Karl Palsson <notifications@github.com> пишет:
>So, what exactly is "version safety" please?  This change stops joe
>from displaying it's version on startup.  Why?  Further it removes the
>help text showing the default keymaps to exit.  I don't understand the
>motivation of this patch.

**Comment by hnyman** [comment]
It has been NAKed and as it is from your master, new commits start to accumulate here. Let's close this.

**Comment by aTanW** [comment]
Thanx, I forgot...

**Pull request closed without merging**
