### PR TITLE
coremark: switch to local git tarball

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: @abajk
Compile tested: rockchip/armv8
Run tested: n/a

Description:
Make version apk compatible.

### CODE REVIEW

**Comment by abajk** [comment]
From what I remember [codeload is preferred](https://github.com/openwrt/packages/pull/6916#discussion_r271954481).

**Comment by 1715173329** [comment]
Basically we only use codeload for tags, and it has been no longer preferred since last xz issue (I would say it does not make sense, but anyway...). Main intention of this update is to make the version compatible with apk.

**Comment by abajk** [comment]
By the way, codeload is used by many packages. Does this mean that they are all not apk-compatible?
~~~
$ grep -rni "codeload" . | wc -l
240
~~~

**Comment by 1715173329** [comment]
> By the way, codeload is used by many packages. Does this mean that they are all not apk-compatible?
> 
> ```
> $ grep -rni "codeload" . | wc -l
> 240
> ```

It's irrelevant to codeload, but `PKG_VERSION`. However the current code works fine, I guess I mixed the error from other packages, will close it. Sorry for the noise.

**Pull request closed without merging**
