### PR TITLE
xtables-addons: fix build error with target x64, bump to 3.26

### PR DESCRIPTION
**Pull request by httpstorm**
Fixes
``` C
make[6]: Entering directory '/Volumes/x64/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.6.36'
  CC [M]  /Volumes/x64/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.24/extensions/LUA/prot_buf_ip.o
In file included from /Volumes/x64/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.24/extensions/LUA/prot_buf_ip.c:20: ./include/net/checksum.h: In function 'csum_shift': ./include/net/checksum.h:90:40: error: implicit declaration of function 'ror32' [-Werror=implicit-function-declaration]
   90 |                 return (__force __wsum)ror32((__force u32)sum, 8);
      |                                        ^~~~~
In file included from ./include/linux/kernel.h:22,
                 from ./include/linux/skbuff.h:13,
                 from ./include/linux/tcp.h:17,
                 from ./include/net/tcp.h:20,
                 from /Volumes/x64/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.24/extensions/LUA/prot_buf_ip.c:21:
./include/linux/bitops.h: At top level:
./include/linux/bitops.h:135:21: error: conflicting types for 'ror32'; have '__u32(__u32,  unsigned int)' {aka 'unsigned int(unsigned int,  unsigned int)'}
  135 | static inline __u32 ror32(__u32 word, unsigned int shift)
      |                     ^~~~~
./include/net/checksum.h:90:40: note: previous implicit declaration of 'ror32' with type 'int()'
   90 |                 return (__force __wsum)ror32((__force u32)sum, 8);
      |                                        ^~~~~
cc1: some warnings being treated as errors
```

Update to version 3.26, and change `${top_srcdir}` to `../../`, as used in 3.24 `extensions/ACCOUNT/Makefile.am` to fix the following error:
```
cp: cannot stat '/Volumes/x64/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.26/ipkg-install/usr/lib/iptables/libxt_ACCOUNT.so': No such file or directory
```

Maintainer: @jow- 
Compile tested: x64 target on macOS 14.5 x64 host
Run tested: x64 target, OpenWRT main

@robimarko @neheb @Ansuel @aparcar @PolynomialDivision 

BTW I noticed that patches 201 and 210 modify files created by 200.
- [x] Should we merge them? DONE
- [x] Should we also update to xtables-addons-3.26? DONE

### CODE REVIEW

**Comment by neheb** [comment]
Yes and yes

**Comment by httpstorm** [comment]
@neheb done

**Comment by httpstorm** [comment]
@robimarko 
Hmm, the last time this happened it was after we pushed an update to the toolchain. And the runners were still rebuilding it.
I can wait until tomorrow and force push without any changes. I compiled successfully each of the three commits on top of your `x86-macos-debug` branch. The test logs do not indicate errors in `xtables-addons`:
```
SHELL= flock /builder/tmp/.root-copy.flock -c 'cp -fpR /builder/build_dir/target-x86_64_musl/perl/perl-5.40.0/.pkgdir/perlbase-sdbm-file/. /builde
This step has been truncated due to its large size. Download the full logs from the  menu once the workflow run has completed.
```

**Comment by neheb** [comment]
```
cp: cannot stat '/builder/build_dir/target-mipsel_24kc_musl/linux-ramips_rt288x/xtables-addons-3.26/ipkg-install/usr/lib/iptables/libxt_ACCOUNT.so': No such file or directory
```

**Comment by httpstorm** [comment]
@neheb @robimarko 
Thanks! I enabled `iptables-mod-account` and now I get the same error. I see some changes in `extensions/ACOUNT/Makefile.{am|in}` between 3.24 and 3.25. I can give it a try, but I can't promise a good fix. Or I can remove the last commit and leave it for you to update the package.

**Comment by httpstorm** [comment]
@neheb @robimarko 
Build and run tested with all `xtables-addons` enabled, target x64, host macOS 14.6 x64. Please check if the solution is good, then let's wait for the tests.

**Pull request merged**
