### PR TITLE
python,python3: batch updates

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @dangowrt, @jefferyto 
Compile tested: https://github.com/lede-project/source/commit/a3d232e1e6e5a49e7d1c1d9bc56be9ebd8ae6171 x86_64
Run tested: https://github.com/lede-project/source/commit/a3d232e1e6e5a49e7d1c1d9bc56be9ebd8ae6171 x86_64

Description:

I'm touching on a few python packages.
* python,python3: remove .egg-info dirs from packages ; they're useless
* pyodbc: fix python-pyodbc variant ; wasn't working
* for python-cffi (deps & variants) : drop host builds ; newer version does not seem to require host build ; so w00h00 ; shorter build times
* python-six : add python3-six variant ; this will be needed for python3-cryptography variant ; not sure, whether to do it; but let's see

For all python & python3 variants: added conditional DEPENDS ; seems that both Python & Python3 interpreters are built only if building `python-xxx` variant (or the other).
This should also reduce build times.

All of these changes were tested on x86_64 VM ; quick testing ; start python & python3 interpreters, import packages, do dir (<imported_package>)

Will monitor build bot for the next few days to watch for any fallout I did not see locally.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
No comments so far? good to merge?

**Comment by commodo** [comment]
ack from me
let's see how this goes, and i'll add a few more updates to the python packages

seems `python-cryptography` has been failing for a while 
and `python-pyopenssl` is not working too well (see https://github.com/openwrt/packages/issues/4499)

so, i decided to address them, but mostly by going about and doing some cleanup first

**Comment by commodo** [comment]
i'll close this for a while 
i just arrived around to looking into `python-cryptography`
seems the package may need some `python-cffi` host stuf...... sigh
[ i hope i can find a way to get around that ]

this sort of confuses me
because i don't understand how the whole binding cffi does binding at build time and that binding works cross-platform

**Comment by commodo** [comment]
maybe i'll split the PR into smaller ones that can go individually

**Pull request closed without merging**
