### PR TITLE
zip: rename package to infozip to avoid name collision with tools

### PR DESCRIPTION
**Pull request by hnyman**
Let's try renaming zip to infozip to enable buildbots to build it...

Rename "zip" to "infozip" to avoid name collision, as the same zip package has been introduced to the build tools as zip. Buildbot does not like that.

Reference to #10985 and #11089 as well as
https://github.com/openwrt/openwrt/commit/ad8c2d6099a7da5192ee6e2c52a8303642271877

Compile-tested for ipq806x/R7800

Run-tested: fails immediately with  ` zip error: Not supported (uzoff_t not same size as zoff_t) `

Apparently the configure bug for this package (last updated in 2008) that was supposedly fixed by 39af758c7 still/again materializes, depending on the buildhost/router combination.

I wonder if we should simply remove this antiquated package.

cc @Noltari as the maintainer...

But let's see if CircleCI would be happy with this name change first.

### CODE REVIEW

**Comment by hnyman** [comment]
Yep. Now CircleCI finally builds it.

**Comment by neheb** [comment]
That's just weird. Maybe there's something special about "zip" that's breaking things.

I vote for removing it. There are much better alternatives in the tree such as bsdtar. Could also introduce p7zip as a direct replacement for zip.

**Comment by hnyman** [comment]
> That's just weird. 

It is likely some name collision triggered by something in the phase1/SDK /// phase2 logic in buildbot (and CirleCI), so that it fails if the SDK contains zip tools package. 

But yeah, it makes no sense to spend time on debugging this antique package from 2008. No worder that it does not work with the current gcc and autotools etc.

Unless @Noltari wants to fix the compiled program to actually work, I am inclined to remove the package from master and 19.07.

**Comment by neheb** [comment]
Well, it's not present in either, so :).

**Comment by 4k3or3et** [comment]
> That's just weird. Maybe there's something special about "zip" that's breaking things.
> 
> I vote for removing it. There are much better alternatives in the tree such as bsdtar. Could also introduce p7zip as a direct replacement for zip.

Could please tell how to install p7zip on OpenWRT? 

opkg update && opkg install p7zip gives:

`Unknown package 'p7zip'.
Collected errors:
 * opkg_install_cmd: Cannot install package p7zip.`

**Comment by neheb** [comment]
That would need for it to be introduced to the packages feed. Why not use bsdtar?

**Comment by hnyman** [comment]
I think that I will merge this rename in master (to leave the fix for name collision into history) and then remove the package a bit later.

(And buildbot might even compile this ok for those targets, where 32/64 bit difference gets eliminated.)

For 19.07 the most clear solution would be to remove the package.

**Comment by 4k3or3et** [comment]
> That would need for it to be introduced to the packages feed. Why not use bsdtar?

With bsdtar i cant find a way to password protect zip files so they could be decompressed under Windows...

**Comment by neheb** [comment]
OTOH, zip encryption is very weak: https://mobile.twitter.com/hashcat/status/1129441728761610242?lang=en

**Pull request merged**
