### PR TITLE
[RFC] [WIP]: initial xorg support

### PR DESCRIPTION
**Pull request by lucize**
preliminary xorg and vnc-server support

xterm si failing with `ttydev: No such device or address` and won't start anything in fluxbox

maybe there are some things still missing
this is only a RFC, any input and advice is welcome  !
the goal is to have a possibility of a thin client using openwrt SDK

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Maintainer: me
Compile/Run tested: x86

### CODE REVIEW

**Comment by diizzyy** [comment]
Anything X-related should go in its own repo
https://github.com/openwrt/video

Out of curiosity, if you want to pull in X etc why not run a proper packaged distro instead of "re-inventing" the wheel?

**Comment by lucize** [comment]
I've missed the video repo
is in mind for thin client, pxe booting, or devices with 256/512 flash (vnc-viewer,rdesktop) useful for schools classes or something similar

**Comment by diizzyy** [comment]
I was under the impression that Arch and Alpine could be easily adapted for such applications but I might be wrong. :-)

**Comment by lucize** [comment]
there is something that can do ~400mb, but it won't fit the 256 devices we have in some classes or 512 ram so the safe way should be openwrt
also the arm boards could be used for something like libreelec

**Comment by diizzyy** [comment]
@BKPepe @neheb 
Should go in separate repo when/if it compiles? No?

**Comment by lucize** [comment]
it will compile, I think that all prerequisites are merged, I'll recheck

**Comment by feckert** [comment]
I think openwrt is an embedded platform.
I agree with @diizzyy that X11 stuff should go into a separate repository.
From my side NOK to add this stuff into the package feed.
There's too much maintenance jobs and a lot more disadvantages.

**Comment by diizzyy** [comment]
@BKPepe @hnyman @neheb 
Any ideas?

**Comment by neheb** [comment]
Sounds pointless to me. Then again, I have no such devices.

**Comment by hnyman** [comment]
Well, one thing is a introduction of a massive set of packages with maintainer being declared. Lucize takes one package himself and assigns one to @commodo, but all others after without a maintainer.

I don't like the massive amount of new packages that do not serve the OpenWrt core of embedded headless devices. That package amount would likely slow down the builtbot even more (as typically the GUI oriented main packages tend to be rather large.)

I feel NAK.

**Comment by BKPepe** [comment]
I think it would be a pity if much work came to nothing. There were created so many packages, but I think it will be good to include it in video feed as it was mentioned.

**Comment by dangowrt** [comment]
I think this clearly belongs in https://github.com/openwrt/video Please PR there.

**Comment by commodo** [comment]
i'm happy to take python-mako here if it helps with xorg;
but  the `python-` variant can be dropped; we've moved to Py3 for master and there is no more Py2 anymore;

i think the `video` repo looks like a good idea for this;
maybe someday there can be some infra to build it; i don't think there is atm;

what would be interesting [these days], is if we can create a docker-build-bot slave image that anyone can download, get an auth-key, and run it to build some packages that a build-bot master would provide per slave;
a sort of `crowd-building` thingi;
i know it's a lot of work to setup the initial dockers, but it may help;

fwiw: there are some OpenWrt Xorg/XFCE packages around;
i know more about these; i haven't tried them though:
https://github.com/larsclausen/openwrt-gnome-packages
https://github.com/larsclausen/openwrt-desktop-packages
https://github.com/larsclausen/openwrt-xfce-4.6-packages
https://github.com/larsclausen/openwrt-lxde-packages  -- this looks empty

i guess, OpenWrt is one of the few distros that could still fit in certain limitations;
maybe some really old computers, that you can get out from the scrap?
i may be able to find my first PC, which was 133 MHz, 32 Mb of RAM, 1.2 GB of disk;
no idea if it still runs [physically though]
though, i don't have any time now to try this;

i agree with @hnyman that we should let these packages clog up the current/main infra [used for the packages] feed, but having them ready in a repo [even if not build] is a beacon to others to get interest;
and as @BKPepe said: it would be a shame to waste this work;

though, in all fairness even these packages should list maintainers;
we have precedence with the old-packages [from before 2014-2015] where most packages had no maintainer listed;

**Comment by lucize** [comment]
@BKPepe @hnyman @neheb @diizzyy @commodo 
Hi, all
first off, I would like to understand why this failed on buildbot but was a bit busy to try it again (it seems it can't be reopen for CI tests).
the main target for this is for vnc support as a jump server between to networks, so no video output is mandatory on the device, just enough memory available to run a vnc server and a rdesktop app
there was no maintainer because it was wip, I would have added me if no one offered, anyhow, the last problem was with xinit failing to start a terminal console
maye adding a CI to https://github.com/openwrt/video would help on this

**Comment by BKPepe** [comment]
>  maye adding a CI to https://github.com/openwrt/video would help on this

You can take a look at how I did it for the telephony feed. I created an issue and then sent a pull request.

**Comment by bkuhls** [comment]
@lucize 

> there was no maintainer because it was wip, I would have added me if no one offered

Hi,

is it ok for you if I PR some of your new packages from this PR to https://github.com/openwrt/video and take maintainership of these packages myself?
Currently I am thinking about libva, on top of it I already added the libva intel driver package: https://github.com/bkuhls/OpenWrt_video/commits/master

My goal with these packages is to run Kodi 19 based on gbm/opengles@x86_64.
This means no X.org packages, but some of Kodi's dependencies are part of this PR.

**Comment by lucize** [comment]
Feel free to do anything you want with this, I'm a bit busy with anything else and don't have time to review this!

**Comment by firmwarecostum** [comment]
The xorg package is actually needed as an example to create an openjdk package. but the xorg package is not updated again until it is finally removed. In my opinion, the xorg package is really needed for package experiments

**Comment by esaaprillia** [comment]
@hnyman @lucize 

I was going to add Xorg but after seeing this discussion I doubt whether Xorg will be accepted but in my opinion if Xorg is in the video package it's really crazy, even the video updates are no longer there and some of the existing packages are broken. Xorg packages should be acceptable here without having to include them in the video

**Pull request closed without merging**
