### PR TITLE
"<ddns-scripts>:" Duiadns - IPv6 support added / IPv4 authentication method changed"

### PR DESCRIPTION
**Pull request by pliviu**
Maintainer: Liviu Pislaru / @pliviu
Compile tested: using a duiadns account on OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45)
Run tested: using a duiadns account on OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45)

Description:
Duiadns IPv6 support added.
Authentication method changed for Duiadns IPv4; user & pass encoded base64 in header.

Signed-off-by: Liviu Pislaru liviu@duiadns.net

### CODE REVIEW

**Comment by chris5560** [comment]
Thanks Liviu.
Ok for me to merge. Thanks.

**Comment by pliviu** [comment]
Thanks Chris. After a short conversation with duiadns guys, i removed "200" from both ipv6 and ipv6 URL and commit the changes.

**Comment by chris5560** [comment]
@pliviu
why removing the success answer ?
does Duiadns not give a positive or negativ response for an update send ?
The success of an update is monitored by ddns-scripts (if defined) and if failed reported to syslog.

**Comment by pliviu** [comment]
Duiadns will give you a http code 200 for success and the http page will contain message that include hostname and IPs.
You can see a specific example if copy-paste the link below in a browser:
http://ip.duia.ro/dynamic.duia?host=openwrt.duia.ro&password=79dcca5af01847d34d07c4fae3dc5a13&ip4=127.0.0.1&ip6=::1

The problem is that when i added "200" and tested on my openwrt, the process refused to re-start.

 153422  WARN : Custom update_script not found! - TERMINATE
 153422  WARN : PID '2940' exit WITH ERROR '1' at 2016-09-03 15:34

Without "200" there's no issue and for ipv4 updates has been working for two years. I just want to add ipv6 with this commit and keep the same logic and in the near future i'll include server response as well.

**Comment by hnyman** [comment]
superseeded by  #3136

**Pull request closed without merging**
