### PR TITLE
mwan3: Document hotplug events and $DEVICE not being available on ifdown

### PR DESCRIPTION
**Pull request by jamesmacwhite**
Maintainer: @feckert 
Compile tested:  N/A
Run tested: N/A

Description:

Relates to https://github.com/openwrt/packages/issues/13759, $DEVICE is not available on ifdown, so it cannot be used in any custom logic in `/etc/mwan3.user` workaround would be to use $INTERFACE instead which is available on ifdown. $DEVICE is usable on any other event.

While it has been discussed that ifupdate is not mwan3 related, it is possible to hook into this action event with the mwan3.user file, therefore I think it can be mentioned, but clarified it is not a mwan3 event.

### CODE REVIEW

**Comment by feckert** [comment]
Could we please remove the line https://github.com/openwrt/packages/pull/13867/files#diff-3886166364a8812230202269afb1b464f007ad9d9b186815632c175bdd9e60b9R12 Because if we add this then we have to add all other actions as well. But mwan3 does only use for now ifup, ifdown, connected and disconnected. In the documentation we have already mentioned this https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3?s[]=mwan3#alertsnotifications

The hint for $DEVICE is sufficient

**Comment by jamesmacwhite** [comment]
@feckert Thanks! I hadn't updated the documentation at the time of this PR but have since rewrote and expanded the section around the `/etc/mwan3.user` file so I'll amend accordingly.

**Comment by feckert** [comment]
If we merge this [P/R](https://github.com/openwrt/packages/pull/13889#pullrequestreview-528169654). We react also on ifupdate events. So I think the ifupdate info add for mwan3.user should go this P/R. Then it fits together

**Comment by jamesmacwhite** [comment]
@feckert I've dropped ifupdate for now, I've added a reference to the URL path of the alerts/notifications documentation which covers the purpose and details of the `/etc/mwan3.user` file.

**Comment by feckert** [comment]
@jamesmacwhite Sorry if I'm annoying but can you please also update the PKG_RELEASE number.

**Comment by jamesmacwhite** [comment]
@feckert No problem! I've just resynced the latest changes in master, as this PR is behind, so the Makefile is old. I've just bumped the PKG_RELEASE to `2` as this is a minor change.

**Comment by feckert** [comment]
Thanks

**Pull request merged**
