### PR TITLE
digitemp: bringback from oldpackages

### PR DESCRIPTION
**Pull request by cvbkf**
- package source updated to latest version from my github fork of
digitemp
- compiled and tested successfully on barrier breaker and chaos calmer

### CODE REVIEW

**Comment by TimelessNL** [comment]
**What is the final status of this issue?**

I recently searched for Digitemp and found that it was abandoned somehow? Instead I used [this old Makefile](https://dev.openwrt.org/browser/packages/utils/digitemp/Makefile) which failed. I solved the compiling issues by adding "sys/types.h" to several files, see [my patch](https://github.com/openwrt/packages/files/1158701/0001_add_missing_includes.zip).

**The resulted binary is working perfectly** and I'm using it ever since.
It would be great to have it in the OpenWRT/LEDE repo again :)

**Comment by fape** [comment]
Yes, that would be great if we got digitemp back.

**Comment by TimelessNL** [comment]
Any status on this? I can create a new pull request against the master branch. But it would be nice to know why this one is closed.

**Comment by TimelessNL** [comment]
@fabe Just letting you know that digitemp is reintroduced with #5308.

**Comment by fape** [comment]
Thanks!

**Pull request closed without merging**
