### PR TITLE
boost: Package Version Update (1.71.0) + bugfixes

### PR DESCRIPTION
**Pull request by ClaymorePT**
Maintainer: @ClaymorePT 
Compile tested: arc700
Run tested: N/A

Description:

This commit updates Boost to version 1.71.0 and disables Boost.Context
 for arc and mips64 architectures, since either jump_fcontext or
 getcontext are undefined for those architectures.

It also fixes a bug were Boost.Fiber was not properly disabled for
mips32 and mips64 architectures.

Boost.Coroutine2 option was removed since it was redundant. By selecting
the Coroutine package, Coroutine2 is also installed.

Boost.Fiber has been disabled for target brcm47xx_generic and brcm47xx_legacy
due to misssing opcode support from instruction set.

Boost 1.71.0 brings a new header-only library
 - Boost.Variant2 [1]
   -> A never-valueless, strong guarantee implementation of std::variant, from Peter Dimov.

More info about Boost 1.71.0 can be found at the usual place [2].

[1]: https://www.boost.org/doc/libs/1_71_0/libs/variant2/doc/html/variant2.html
[2]: https://www.boost.org/users/history/version_1_71_0.html

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

### CODE REVIEW

**Comment by ClaymorePT** [comment]
@neheb Please review when you have a moment. Thank you!

**Comment by ClaymorePT** [comment]
@neheb It seems that the buildpr pipeline has hanged. Can you do something about it, when you have the time? Thank you.

**Comment by ClaymorePT** [comment]
> Didn't compile for me on arc700. It seems boost-filesystem was not updated with the release. Meaning this is still needed: #9611

Dammit :/ I completly forgot that they had already closed the release for new additions on the 3rd of July :/ I'm gonna have to add the patch to the branch.

> The uclibc-ng-2 patch needs renaming. It's not prefixed with a number.

It was already like that but I will fix it.

> boost-context is not selectable on ARC, so no idea why libfolly is.

HmmI'm gonna look at it also, to see if find anything.

@neheb I won't be able to make the changes until Friday, probably during the weekend. 
If you find out other issues, please let me know.

**Comment by ClaymorePT** [comment]
@neheb Can you check the Makefile and see if it builds successfully from your side? CircleCI still does not build everything properly :/

**Comment by neheb** [comment]
Problems I see are: 

Applying ./patches/002-utime-filesystem.patch using plaintext: 
patching file libs/filesystem/src/operations.cpp
Hunk #3 succeeded at 1461 (offset 8 lines).
Hunk #4 succeeded at 1488 (offset 8 lines).

Applying ./patches/101-uclibc-ng-math.patch using plaintext: 
patching file boost/math/tools/roots.hpp
Hunk #1 succeeded at 800 (offset 135 lines).
Hunk #2 succeeded at 809 (offset 135 lines).

warning: Graph library does not contain MPI-based parallel components.
note: to enable them, add "using mpi ;" to your user-config.jam.
note: to suppress this message, pass "--without-graph_parallel" to bjam.

It would also be good to add HOST_BUILD_PARALLEL to speed it up.

From the Makefile, there's mention of versions below GCC5. I would remove mention and/or support for old versions as GCC5 is currently the minimum.

**Comment by neheb** [comment]
These two also don't build.

```
    - locale                   : not building
    - python                   : not building
```

No idea why.

**Comment by neheb** [comment]
I'm also getting this now:

```
tmp/.config-package.in:61321:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:61321:	symbol PACKAGE_boost is selected by PACKAGE_libfolly
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:64405:	symbol PACKAGE_libfolly is selected by PACKAGE_libfizz
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:64360:	symbol PACKAGE_libfizz is selected by PACKAGE_libwangle
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:69652:	symbol PACKAGE_libwangle is selected by PACKAGE_fbthrift
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:62311:	symbol PACKAGE_fbthrift is selected by PACKAGE_fbzmq
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:62329:	symbol PACKAGE_fbzmq depends on boost-context-exclude
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:61511:	symbol boost-context-exclude depends on PACKAGE_boost
```

**Comment by neheb** [comment]
Getting this with rsocket-cpp:

```
CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::context" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::chrono" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::date_time" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::filesystem" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::program_options" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::regex" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::system" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::thread" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::context" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::chrono" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::date_time" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::filesystem" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::program_options" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::regex" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::context" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::chrono" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::date_time" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::filesystem" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::program_options" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::regex" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::system" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:202 (add_library):
  Target "ReactiveSocket" links to target "Boost::thread" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::context" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::chrono" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::date_time" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::filesystem" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::program_options" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::regex" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at yarpl/CMakeLists.txt:66 (add_library):
  Target "yarpl" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ASM_COMPILER
    CMAKE_ASM_COMPILER_ARG1
    CMAKE_MODULE_LINKER_FLAGS
    DL_LIBRARY


CMake Generate step failed.  Build files cannot be regenerated correctly.
Makefile:67: recipe for target '/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/rsocket-cpp-bc76800e3f5861e92f60825f691aa0a74223a4a1/.configured_68b329da9893e34099c7d8ad5cb9c940' failed
make[2]: *** [/home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/rsocket-cpp-bc76800e3f5861e92f60825f691aa0a74223a4a1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/feeds/packages/libs/librsocket-cpp'
time: package/feeds/packages/librsocket-cpp/compile#0.81#0.24#1.73
package/Makefile:111: recipe for target 'package/feeds/packages/librsocket-cpp/compile' failed
make[1]: *** [package/feeds/packages/librsocket-cpp/compile] Error 2
make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
/home/mangix/devstuff/openwrt/include/toplevel.mk:216: recipe for target 'package/fbthrift/compile' failed
make: *** [package/fbthrift/compile] Error 2
```

everything is installed in staging_dir

**Comment by ClaymorePT** [comment]
> Problems I see are:
> 
> Applying ./patches/002-utime-filesystem.patch using plaintext:
> patching file libs/filesystem/src/operations.cpp
> Hunk #3 succeeded at 1461 (offset 8 lines).
> Hunk #4 succeeded at 1488 (offset 8 lines).
> 
> Applying ./patches/101-uclibc-ng-math.patch using plaintext:
> patching file boost/math/tools/roots.hpp
> Hunk #1 succeeded at 800 (offset 135 lines).
> Hunk #2 succeeded at 809 (offset 135 lines).
> 

This isn't really a problem as long as diff is successful in applying the patch. Creating patches specifically for each version can be cumbersome. Since diff is perfectly capable of noticing the offset, there's really no problem with this.

> warning: Graph library does not contain MPI-based parallel components.
> note: to enable them, add "using mpi ;" to your user-config.jam.
> note: to suppress this message, pass "--without-graph_parallel" to bjam.
> 

Ah! This was my fault. I will revert the default value for graph-parallel.

> It would also be good to add HOST_BUILD_PARALLEL to speed it up.

I think I've tried this in the past and there were some issues with it. I will check this again.

> 
> From the Makefile, there's mention of versions below GCC5. I would remove mention and/or support for old versions as GCC5 is currently the minimum.

I've removed some. I will recheck again to remove the ones I missed.

**Comment by ClaymorePT** [comment]
> I'm also getting this now:
> 
> ```
> tmp/.config-package.in:61321:error: recursive dependency detected!
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:61321:	symbol PACKAGE_boost is selected by PACKAGE_libfolly
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:64405:	symbol PACKAGE_libfolly is selected by PACKAGE_libfizz
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:64360:	symbol PACKAGE_libfizz is selected by PACKAGE_libwangle
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:69652:	symbol PACKAGE_libwangle is selected by PACKAGE_fbthrift
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:62311:	symbol PACKAGE_fbthrift is selected by PACKAGE_fbzmq
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:62329:	symbol PACKAGE_fbzmq depends on boost-context-exclude
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:61511:	symbol boost-context-exclude depends on PACKAGE_boost
> ```

I've also noticed those. I think I can resolve them.

**Comment by ClaymorePT** [comment]
> It would also be good to add HOST_BUILD_PARALLEL to speed it up.
 
For what I can see, neither HOST_BUILD_PARALLEL or PACKAGE_BUILD_PARALLEL are working as intended because boost uses its own building system. Boost `-j` flag contains a space between the letter and the number of jobs.

Also, `PKG_JOBS` is evaluated to` --jobserver-auth=3,4`. Is this correct? Shouldn't it return the number of available jobs to be passed to the `-j ` flag?

**Comment by ClaymorePT** [comment]
@neh

> I'm also getting this now:
> 
> ```
> tmp/.config-package.in:61321:error: recursive dependency detected!
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:61321:	symbol PACKAGE_boost is selected by PACKAGE_libfolly
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:64405:	symbol PACKAGE_libfolly is selected by PACKAGE_libfizz
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:64360:	symbol PACKAGE_libfizz is selected by PACKAGE_libwangle
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:69652:	symbol PACKAGE_libwangle is selected by PACKAGE_fbthrift
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:62311:	symbol PACKAGE_fbthrift is selected by PACKAGE_fbzmq
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:62329:	symbol PACKAGE_fbzmq depends on boost-context-exclude
> For a resolution refer to Documentation/kbuild/kconfig-language.txt
> subsection "Kconfig recursive dependency limitations"
> tmp/.config-package.in:61511:	symbol boost-context-exclude depends on PACKAGE_boost
> ```

Fixed this.

**Comment by ClaymorePT** [comment]
> Getting this with rsocket-cpp:
> 

librsocket-cpp should no longer be active for arc700, since its dependency (boost-context) is disabled for arc700.

**Comment by ClaymorePT** [comment]
@neheb can you check the latest update from your side. thank you!

**Comment by neheb** [comment]
> > Problems I see are:
> > Applying ./patches/002-utime-filesystem.patch using plaintext:
> > patching file libs/filesystem/src/operations.cpp
> > Hunk #3 succeeded at 1461 (offset 8 lines).
> > Hunk #4 succeeded at 1488 (offset 8 lines).
> > Applying ./patches/101-uclibc-ng-math.patch using plaintext:
> > patching file boost/math/tools/roots.hpp
> > Hunk #1 succeeded at 800 (offset 135 lines).
> > Hunk #2 succeeded at 809 (offset 135 lines).
> 
> This isn't really a problem as long as diff is successful in applying the patch. Creating patches specifically for each version can be cumbersome. Since diff is perfectly capable of noticing the offset, there's really no problem with this.

Sure. There are some that complain about this though.

In other news, I submitted the remaining patches upstream. Hopefully these will not be needed soon.

https://github.com/boostorg/math/pull/249
https://github.com/boostorg/asio/pull/279

**Comment by ClaymorePT** [comment]
> In other news, I submitted the remaining patches upstream. Hopefully these will not be needed soon.
> 
> [boostorg/math#249](https://github.com/boostorg/math/pull/249)
> [boostorg/asio#279](https://github.com/boostorg/asio/pull/279)

Thanks! I will add those also.

**Comment by neheb** [comment]
This is erroring oin:

```
mips-openwrt-linux-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugs.openwrt.org/> for instructions.
```

I use GCC9 on my local builds. Compiles fine on armeb and arc700 from a quick test.

**Comment by ClaymorePT** [comment]
> This is erroring oin:
> 
> ```
> mips-openwrt-linux-gcc: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://bugs.openwrt.org/> for instructions.
> ```
> 
> I use GCC9 on my local builds. Compiles fine on armeb and arc700 from a quick test.

Don't know what to say :/ I will try on my side and see what happens.

**Comment by ClaymorePT** [comment]
@neheb I noticed that Boost.Fiber cannot be compiled for mipsel. I have disabled that package for that target.

**Comment by neheb** [comment]
Hmm? What was the error?

**Comment by ClaymorePT** [comment]
> Hmm? What was the error?

Something about opcode not available for  mips32. I didn't record it.

**Comment by ClaymorePT** [comment]
Btw, I cannot remove the verification for GCC 5.0 since there are targets who still have that compiler version available.

**Comment by neheb** [comment]
Well, it seems nothing uses it. So it's probably fine.

**Comment by ClaymorePT** [comment]
@neheb I've added the GCC compiler verification, which checked for GCC 5.X presence and used the gnu14 or gnu17 accordingly. 

Regarding your patches for Boost.Math and Boost.Asio, I will wait until they are merged upstream and then add them here.

**Comment by ClaymorePT** [comment]
@neheb I've re-enabled Boost.Fiber for mipsel 
It seems that there are targets using that instruction set for which boost.fiber can be built.
I will have to check other targets to see what's wrong.

**Comment by ClaymorePT** [comment]
> Hmm? What was the error?

```
...failed gcc.compile.c++ bin.v2/libs/fiber/build/gcc-7.4.0/release/abi-o32/threading-multi/visibility-hidden/timed_mutex.o...
gcc.compile.c++ bin.v2/libs/fiber/build/gcc-7.4.0/release/abi-o32/threading-multi/visibility-hidden/scheduler.o
{standard input}: Assembler messages:
{standard input}:1959: Error: opcode not supported on this processor: mips32 (mips32) `pause'
{standard input}:2041: Error: opcode not supported on this processor: mips32 (mips32) `pause'
```

**Comment by ClaymorePT** [comment]
@neheb Boost.Fiber is now disabled for brcm47xx_generic and brcm47xx_legacy.

**Comment by ClaymorePT** [comment]
@neheb I've done what I could for now. Can you test from your side? Thank you!

**Comment by ClaymorePT** [comment]
@neheb 

It seems that the CI job was killed again.
I've done a [short search](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61860) and it seems the kernel killed the CI job due to lack of RAM.

**Comment by neheb** [comment]
brcm47xx_generic causes issues with fiber but ath79 does not? That's just weird.

The difference is that brcm47xx gets compiled as mips74kc whereas ath79 gets compiled as mips24kc. mips24kc is less capable so it's surprising that mips74kc mode causes issues. Must be a GCC bug.

If RAM is the issue, then this should be good to go.

**Comment by ClaymorePT** [comment]
@neheb If you want, we can wait for your patches to be accepted upstream. 
Otherwise, I'm happy with the current effort and you can merge the changes.

**Pull request merged**
