### PR TITLE
opencv: Update to 4.1.1

### PR DESCRIPTION
**Pull request by neheb**
Update Makefile to modern standards.

Switched to local tarballs..xz archives are smaller. The .gz archive that
codeload comes with is 85MB.

Replaced PKG_INSTALL with CMAKE_INSTALL to get rid of Build/InstallDev.

Added PKG_BUILD_PARALLEL for faster compilation.

Removed inactive maintainer.

Added uClibc-ng patch to fix compilation.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody
Compile tested: arc700

ping @ja-pa

### CODE REVIEW

**Comment by diizzyy** [comment]
Source tarball can be found at SF:
https://sourceforge.net/projects/opencvlibrary/files/4.1.1/OpenCV%204.1.1.tar.gz

**Comment by neheb** [comment]
Oh that's nasty. I wonder if the build system can handle spaces in PKG_SOURCE.

**Comment by neheb** [comment]
The tarball has the directory "opencv-opencv-1eef240", which is a git revision. I don't like this.

**Comment by diizzyy** [comment]
Use codeload instead if that's any better, git should really be the last resort.

**Comment by neheb** [comment]
I'd rather keep it like this. xz is smaller. There's also disagreement on whether to use local tarballs or codeload. Upstream seems to like local:

```
mangix@mangix-pc:~/devstuff/openwrt$ git grep PKG_SOURCE_PROTO\:=git | wc -l
66
mangix@mangix-pc:~/devstuff/openwrt$ git grep codeload | wc -l
1
```

**Comment by diizzyy** [comment]
Availability > Size
At least that's how I would go about it...

**Comment by neheb** [comment]
Well, currently it falls back to doing a shallow clone of the actual repository. I'm currently not sure how safe this is...

**Pull request merged**
