### PR TITLE
automake: Update to 1.15.1

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @xypron 
Compile tested: ipq806x

### CODE REVIEW

**Comment by neheb** [comment]
Hrm Fedora 28 also uses 15.1. I will update to that instead.

**Comment by neheb** [comment]
Local compile fails with: 

```
pp.c: In function 'Perl_pp_crypt':
pp.c:3741:47: error: 'struct crypt_data' has no member named 'current_saltbits'
      PL_reentrant_buffer->_crypt_struct_buffer->current_saltbits = 0;
                                               ^~
make[4]: *** [makefile:251: pp.o] Error 1
make[4]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/hostpkg/perl/perl-5.26.2'
```

But that's a failure in Perl. ping @pprindeville

**Comment by pprindeville** [comment]
pong.  @neheb What is the build environment?

**Comment by neheb** [comment]
Fedora 28. The referenced pull request fixes the issue. This pull request failed because of a different problem.

**Comment by pprindeville** [comment]
Sorry, going to 1.15.1 fixes the problem?  Or 1.16.1?

**Comment by pprindeville** [comment]
I just did a build from scratch (as a `-j1` it took about 2 hours) with no issues.

**Pull request closed without merging**
