### PR TITLE
tinc: fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ErwanMAS 
Compile tested: mips64el

### CODE REVIEW

**Review by ErwanMAS — COMMENTED** [review]
Hi @neheb  , Can you tell me in which context you need this patch ?

**Comment by neheb** [comment]
OpenSSL with disabled deprecated OpenSSL APIs.

**Comment by ErwanMAS** [comment]
@neheb in which case device / platform  , OpenSSL is configured with disabled deprecated ?

**Comment by neheb** [comment]
OpenSSL can be configured that way using make menuconfig. It is not done by default.

**Comment by ErwanMAS** [comment]
@neheb so : 
i use this sdk ( `snapshots/targets/ath79/generic/openwrt-sdk-ath79-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz` ) to compile 
i uncheck  `      [ ]   Include deprecated APIs `

i dont have any error without your patch . i compiled the last version of tinc .

**Comment by neheb** [comment]
Weird. Maybe openssl or tinc needs rebuilding.

**Comment by neheb** [comment]
Merged upstream: https://github.com/gsliepen/tinc/pull/258

**Comment by neheb** [comment]
Because this was merged upstream, this will come with a package update. Closing.

**Pull request closed without merging**
