### PR TITLE
php7: update to 7.2.0

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: @mhei 
Compile tested: x86_64, generic, LEDE HEAD (95fe3c5)
Run tested: same

Rebuilt.

Description:

Also drop `mcrypt` module as it's deprecated.

Dropped patches have been accepted upstream or something homologous.

### CODE REVIEW

**Comment by pprindeville** [comment]
@champtar Build timed out on Travis...

**Comment by pprindeville** [comment]
@mhei Hi Michael, how is it looking?

**Comment by champtar** [comment]
Hey @pprindeville
I want to test circleci but I dont know if I will have time before next year

**Comment by pprindeville** [comment]
Understood. What’s circleci?

**Comment by champtar** [comment]
https://circleci.com/ (first google answer ;) )
Like Travis but it seems there is no time limit, and instead of having a default ubuntu 14.04 image, you can choose your docker container (so we can have up to date gcc & co)

**Comment by mhei** [comment]
Review quality before speed :smile: I'm still testing. At the moment I'm running into the error:
`php-7.2.0/sapi/cgi/cgi_main.c:100:33: fatal error: valgrind/callgrind.h: No such file or directory`
but I'm not yet sure, whether this is a local issue. Still investigating.

But another question:
Why did you drop  0013-Add-support-for-use-of-the-system-timezone-database.patch?
I do not expect that upstream has something equivalent included already.

**Comment by pprindeville** [comment]
@champtar I guess unlike Travis, you run it on your own servers?

**Comment by pprindeville** [comment]
> Why did you drop 0013-Add-support-for-use-of-the-system-timezone-database.patch?

@mhei Here is part of the deleted `0013-Add-support-for-use-of-the-system-timezone-database.patch`:

```
-@@ -59,6 +73,11 @@ static int read_preamble(const unsigned char **tzf, timelib_tzinfo *tz)
- {
-       uint32_t version;
- 
-+      if (memcmp(*tzf, "TZif", 4) == 0) {
-+              *tzf += 20;
-+              return 0;
-+      }
-+
-       /* read ID */
-       version = (*tzf)[3] - '0';
-       *tzf += 4;
```

here is what the code from the release looks like:

```
static int read_tzif_preamble(const unsigned char **tzf, timelib_tzinfo *tz)
{
        uint32_t version;

        /* read ID */
        switch ((*tzf)[4]) {
                case '\0':
                        version = 0;
                        break;
                case '2':
                        version = 2;
                        break;
                case '3':
                        version = 3;
                        break;
                default:
                        return -1;
        }
        *tzf += 5;

        /* set BC flag and country code to default */
        tz->bc = 0;
        tz->location.country_code[0] = '?';
        tz->location.country_code[1] = '?';
        tz->location.country_code[2] = '\0';

        /* skip rest of preamble */
        *tzf += 15;

        return version;
}

static int read_preamble(const unsigned char **tzf, timelib_tzinfo *tz, unsigned int *type)
{
        /* read marker (TZif) or (PHP) */
        if (memcmp(*tzf, "PHP", 3) == 0) {
                *type = TIMELIB_TZINFO_PHP;
                return read_php_preamble(tzf, tz);
        } else if (memcmp(*tzf, "TZif", 4) == 0) {
                *type = TIMELIB_TZINFO_ZONEINFO;
                return read_tzif_preamble(tzf, tz);
        } else {
                return -1;
        }
}
```

so as far as I can tell, `TZif` files *are* handled and some version of the patch has been integrated upstream.

**Comment by pprindeville** [comment]
> A traditional `--with-valgrind=dir` or so should be the best solution for all...

Works for me.  Do you want to put them that in as a back-to-back commit with this so we can revert it later when it becomes unnecessary?

**Comment by mhei** [comment]
Short update: the patch 0013-Add-support-for-use-of-the-system-timezone-database.patch is still necessary, but needs to be updated. The goal of this patch is that PHP does not ship its internal timezone database, but uses the system-wide installed ones. Your quote of the sources above only shows that some functionality is now also available in vanilla PHP, so the patch might become smaller, but the desired functionality is not yet included upstream. This is what I was wondering because PHP upstream refused these patches, I would have been surprised if they had changed their mind.

> Do you want to put them that in as a back-to-back commit with this so we can
> revert it later when it becomes unnecessary?

Sorry, I can't follow or understand your question correctly. What do you mean with back-to-back commit? My hope is, that the upstream development does not evolve so that the valgrind stuff is a hard requirement and thus it will be possible to make it optional via configure parameter...

**Comment by pprindeville** [comment]
> Sorry, I can't follow or understand your question correctly. What do you mean with back-to-back commit?

Did you want to go ahead with this commit (with the updated TZ patch added back), and then immediately commit the valgrind workaround patch separately?

**Comment by pprindeville** [comment]
> Short update: the patch 0013-Add-support-for-use-of-the-system-timezone-database.patch is still necessary, but needs to be updated.

@mhei I pulled the patch from Fedora 26, since Joe (Orton) works for Redhat.

**Comment by pprindeville** [comment]
Thanks!

**Comment by eliz82** [comment]
I don't think rushing to update PHP7 versions is a good idea. Switching from PHP5 to PHP7 was a good idea because improvement in speed was almost 2x. But there is no point in switching so fast to PHP7.1 and PHP7.2 if the old branch still receive security updates. No big improvement in speed ... only compatibility breaks with php software. PHP 7.1 have break a ton of compatibility with PHP 7.0 . From the reports i have seen so is the case with PHP 7.2 vs PHP 7.1 . **Seems in PHP7 the things are not so backwards compatible like they used to be in PHP5.**  (my opinion). 

Not all the software is Wordpress to have 100 peoples working on it. Their are CMS software maintain by one single person in their free time. You must give time to CMS developers to update their software and not rush updating PHP7 versions.

**Comment by pprindeville** [comment]
Part of the move to 7.2 was for the improved logging which integrates better into OpenWrt.

**Comment by mhei** [comment]
@eliz82: I understand your point. However, here some random thoughts:

- which CMS software do you think about? Is it packaged as OpenWrt package? if packaged then coordination should be possible, but it would be difficult to track random external PHP7 "users"
- it's always possible to use a custom build with updates reverted
- updates are not surprising, it's always possible to email me and discuss this in advance
- here in packages master branch we should follow upstream releases closely to detect problems early, release branches should stay with the major.minor version which was current during release; problem here is that last OpenWrt/LEDE release is already out a few months
- during php5/php7 migration, we had a time with both versions in parallel; however, this requires more efforts and package maintaining is also done is free time

**Pull request merged**
