### PR TITLE
stress-ng: bump to version 0.14.05

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/3f814ecd2408da6ac96f741d3d6331ce93b79734
Run tested: same

------------------------------

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

no longer needed: 010-dont_define_fortify.patch
upstreamed: 020-stress-sysinval-fix-fstat-fstat64-compat-check.patch

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
pfew...

seems some archs fail

will come back with this

**Comment by commodo** [comment]
> pfew...
> 
> seems some archs fail
> 
> will come back with this

this was fixed upstream in 0.14.06

initial package update was for 0.14.05 but that seemed broken for some archs

**Comment by hnyman** [comment]
@commodo 

stress-ng seems to fail for most targets in buildbot.
Reason is missing dependencies.

Usually libxxhash, sometimes also libGLESv2:
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a7_neon-vfpv4/packages/stress-ng/compile.txt

```
Package stress-ng is missing dependencies for the following libraries:
libGLESv2.so
libxxhash.so.0
```

https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3-d16/packages/stress-ng/compile.txt
```
Package stress-ng is missing dependencies for the following libraries:
libxxhash.so.0
```

Libxxhash was recently added along borgbackup in #19973 by @julienmalik 
So likely stress-ng now detects that, and stress-ng configuration should be changed to disable the optional libxxhash functionality.

I did not look much into libGLESv2, but I can't actually see where that is coming from. Is that package somewhere, or just misdetected something...

**Comment by commodo** [comment]
will take a look

**Comment by commodo** [comment]
@hnyman 



> @commodo
> 
> stress-ng seems to fail for most targets in buildbot. Reason is missing dependencies.
> 
> Usually libxxhash, sometimes also libGLESv2: https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a7_neon-vfpv4/packages/stress-ng/compile.txt
> 
> ```
> Package stress-ng is missing dependencies for the following libraries:
> libGLESv2.so
> libxxhash.so.0
> ```
> 
> https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3-d16/packages/stress-ng/compile.txt
> 
> ```
> Package stress-ng is missing dependencies for the following libraries:
> libxxhash.so.0
> ```
> 
> Libxxhash was recently added along borgbackup in #19973 by @julienmalik So likely stress-ng now detects that, and stress-ng configuration should be changed to disable the optional libxxhash functionality.
> 
> I did not look much into libGLESv2, but I can't actually see where that is coming from. Is that package somewhere, or just misdetected something...

i've updated a PR [to update stress-ng here](https://github.com/openwrt/packages/pull/20016)
and for 22.03 I have made [another PR here](https://github.com/openwrt/packages/pull/20017)

tbh: i don't know how libGLESv2 gets mis-detected, but i tried to disable the code via a patch; hopefully that works on buildbots; it works on my machine;

**Pull request merged**
