### PR TITLE
hdparm: Updated to latest version 9.47, removed obsolete patch.

### PR DESCRIPTION
**Pull request by rkunze**

### CODE REVIEW

**Comment by thess** [comment]
Please amend your commit mesage - needs package prefix (as you did for the PR title). The commit is what goes into the repository history, not the pull-request.

**Comment by rkunze** [comment]
OK, here's the amended commit. No other changes beside the commit message.

**Comment by thess** [comment]
Could you please squash/rebase these 3 commits to a single one, fix up the comment, include the signed-off-by tag, and then I'll push it. Sorry to bug you again

**Comment by rkunze** [comment]
OK, squashed everything into a single commit.

**Comment by thess** [comment]
Thanks for your updates... and, patience

**Pull request merged**
