### PR TITLE
mariadb: bump to 10.2 release series

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: me
Compile tested: ar71xx
Run tested: Not yet

Description:
This bumps mariadb from 10.1.x to 10.2.x. The main goal is to use a version which supports OpenSSL 1.1.x (10.1.x does not). This also includes an updated init script (procd), some plugin additions/changes and small fixes.

I'm currently "on the road" and can't run test. @lucize and @patrikx3 could you maybe check this out and let me know any griefs you have about this? Sorry for imposing. I'll run test when I get home, promise.

Kind regards,
Seb

### CODE REVIEW

**Comment by lucize** [comment]
don't know why, but 
```
Package dovecot is missing dependencies for the following libraries:
libmariadb.so.3
```
and as a side note, -j is not evaluated so the build is painfully slow, maybe you can add something like this `NUM_CORES ?= $(shell grep -c "vendor_id" /proc/cpuinfo)` then `-j$(NUM_CORES) `, it is safe to be build using multi cpu

**Comment by cotequeiroz** [comment]
@lucize 
I'm trying to reproduce your `missing dependencies` error here, but I'm not able to so far.  I know the soname has changed from `libmysqlclient.so.18` to `libmariadb.so.3`, but the files are correctly copied to the package dir, and appear correctly in `$STAGING_DIR/pkginfo/libmysqlclient.provides`.  So, I'm guessing that somehow the `CheckDependencies` is looking at the old mariadb's `libmysqlclient.provides`.  That would happen if you installed files by hand to the staging dir, or if the installation somehow failed to update that file during libmariadb install.

Here's how it is in my system:
```
$ cat staging_dir/target-mipsel_mips32_musl/pkginfo/libmysqlclient.provides
libatomic.so.1
libatomic.so.1.2.0
libc.so
libcrypto.so.1.1
libgcc_s.so.1
libmariadb.so
libmariadb.so.3
libmysqlclient.so
libmysqlclient_r.so
libssl.so.1.1
libstdc++.so.6
libstdc++.so.6.0.24
libstdc++.so.6.0.24-gdb.py
libz.so
libz.so.1
libz.so.1.2.11
```
Another possibility would be if dovecot was not configured to build the mysql module, but somehow the dovecot build system built it anyway.  Then, `CheckDependencies` wouldn't even look at the provides file.

Cheers,
Eneas

**Comment by lucize** [comment]
I have selected dovecot-mysql, the package is built with 10.1 but fails with 10.2
on 10.1 I have
```
build_dir/target-x86_64_musl/mariadb-10.1.33/ipkg-x86_64
libmariadbclient  mariadb-client  mariadb-server
```
but 10.2 only
```
build_dir/target-x86_64_musl/mariadb-10.2.15/ipkg-x86_64
mariadb-client  mariadb-server

```

**Comment by cotequeiroz** [comment]
Did you update your `.config` file, and selected the library?  The library package name has changed, from `libmariadbclient` to `lbmariadb`.

**Comment by lucize** [comment]
I ran make menuconfig, the dovecot-mysql is set to select libmysqlclient as a dependency that is set as PROVIDES in Packages/libmariadb
and mariadb is patched the packages folder with 6301.patch, 
so the .config file should be ok

**Comment by lucize** [comment]
maybe that I didn't do a clean before and is linking to libmysqlclient.so.18 instead of  libmariadb.so.3 ?

**Comment by micmac1** [comment]
But it did tell you:

Package dovecot is missing dependencies for the following libraries: libmariadb.so.3

So it seems to link to the right lib. Maybe you just need to recreate your package index. Will try out dovecot when I get home.

**Comment by cotequeiroz** [comment]
@lucize 
You're not generating the libmariadb package, probably because it is not selected in your `.config` file.  Try to run `egrep libmariadb .config`.  It should have `CONFIG_PACKAGE_libmariadb=` m or y.  If you're getting `CONFIG_PACKAGE_libmariadbclient=`, then you have an old .config.
If it's not your intent to have the library, or dovecot support for mysql, installed, see if dovecot is not messing things up.  You're not supposed to have `CONFIG_DOVECOT_MYSQL=` on your `.config` if you don't have `libmariadb` selected.  And if you don't have `CONFIG_DOVECOT_MYSQL=`, then dovecot is trying to build with mysql support even though it is not supposed to.
The library files are installed to the staging dir, independent of whether the library is selected in .config or not.  So if dovecot is told to not build mysql support, then it shouldn't.  Mine is working as expected.

**Comment by cotequeiroz** [comment]
@micmac1 
I just noticed the mysql* binaries are always linked statically to the mariadb libraries, increasing package size.  It that intended behavior?  I noticed you have `-DENABLE_STATIC_LIBS=OFF`, which tells me it is not.  That option, by the way, does noting for the mariadb build system, and it did not in the previous version as well.  I'm investigating how we can have them link dynamically.

**Comment by micmac1** [comment]
Don't waste your time. It's not possible to work around it. I found a bug report for upstream some time ago where somebody complained about this. But upstream said that's the way they want it.

Don't have the link anymore it seems.

The linked-in lib is more extensive than what libmariadb offers.

**Comment by micmac1** [comment]
See

https://bugs.launchpad.net/ubuntu/+source/mysql-5.5/+bug/898340

and

https://bugs.mysql.com/bug.php?id=64570

Regards,
Seb

**Comment by cotequeiroz** [comment]
Thanks for explaining that.  Good thing I told you first, otherwise I would have wasted a lot of time on this.
Cheers,
Eneas

**Comment by cotequeiroz** [comment]
I've hit a compiling failure with php7: https://bugs.php.net/bug.php?id=75612
```
In file included from /home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/php-7.2.6/ext/mysqli/php_mysqli_structs.h:63:0,
                 from /home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/php-7.2.6/ext/mysqli/mysqli.c:34:
/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include/mysql/my_global.h:3:2: warning: #warning This file should not be included by clients, include only <mysql.h> [-Wcpp]
 #warning This file should not be included by clients, include only <mysql.h>
  ^~~~~~~
In file included from /home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/php-7.2.6/ext/mysqli/php_mysqli_structs.h:79:0,
                 from /home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/php-7.2.6/ext/mysqli/mysqli.c:34:
/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include/mysql/my_sys.h:3:2: warning: #warning This file should not be included by clients, include only <mysql.h> [-Wcpp]
 #warning This file should not be included by clients, include only <mysql.h>
  ^~~~~~~
In file included from /home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/php-7.2.6/ext/mysqli/mysqli.c:34:0:
/home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/php-7.2.6/ext/mysqli/php_mysqli_structs.h:82:10: fatal error: my_list.h: No such file or directory
 #include <my_list.h>
```
PHP 7.2.6 is the latest production release.

**Comment by cotequeiroz** [comment]
`python-mysql` fails in a very similar way:
```
In file included from _mysql.c:44:0:
/home/equeiroz/src/openwrt/staging_dir/target-mipsel_mips32_musl/usr/include/mysql/my_config.h:3:2: warning: #warning This file should not be included by clients, include only <mysql.h> [-Wcpp]
 #warning This file should not be included by clients, include only <mysql.h>
  ^~~~~~~
In file included from _mysql.c:46:0:
/home/equeiroz/src/openwrt/staging_dir/target-mipsel_mips32_musl/usr/include/mysql/mysql.h:440:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   MYSQL_CLIENT_PLUGIN_HEADER
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
_mysql.c: In function '_mysql_ConnectionObject_get_autocommit':
_mysql.c:913:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   Py_RETURN_TRUE;
   ^~~~~~~~~~~~~~
_mysql.c:915:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  Py_RETURN_FALSE;
  ^~~~~~~~~~~~~~~
_mysql.c: In function '_mysql_ConnectionObject_ping':
_mysql.c:2005:41: error: 'MYSQL {aka struct st_mysql}' has no member named 'reconnect'
  if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                         ^
_mysql.c: In function 'init_mysql':
_mysql.c:3105:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  Py_INCREF(&_mysql_ConnectionObject_Type);
  ^~~~~~~~~
_mysql.c:3109:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  Py_INCREF(&_mysql_ResultObject_Type);
  ^~~~~~~~~
```

**Comment by micmac1** [comment]
Found some php bug reports here (link to another bug at the bottom):

https://bugs.php.net/bug.php?id=75612

**Comment by micmac1** [comment]
Hi all,

Run tested it. Found some issues while doing so, corrected them. Looks fine now, runs.

Regarding make -jx I don't have an issue with that. Both HOST_BUILD_PARALLEL and PKG_BUILD_PARALLEL are set in Makefile and that seems to produce parallel build.

I'll wait a few days and if nothing pops up I'll ask for it to get commited in trunk.

Thanks for all your help !

Kind regards,
Seb

**Comment by cotequeiroz** [comment]
Hello again.
I'm running a whole tree compile, and found another compile error:
```
mipsel-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/equeiroz/src/openwrt-asus/build_dir/target-mipsel_74kc_musl/luasql-mysql/luasql-2.3.0:luasql-2.3.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fpic -std=gnu99 -I/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include -I/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/include -I/home/equeiroz/src/openwrt-asus/staging_dir/toolchain-mipsel_74kc_gcc-7.3.0_musl/usr/include -I/home/equeiroz/src/openwrt-asus/staging_dir/toolchain-mipsel_74kc_gcc-7.3.0_musl/include/fortify -I/home/equeiroz/src/openwrt-asus/staging_dir/toolchain-mipsel_74kc_gcc-7.3.0_musl/include -DLUA_USE_LINUX -I/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include/mysql   -c -o src/ls_mysql.o src/ls_mysql.c
In file included from src/ls_mysql.c:21:0:
src/ls_mysql.c: In function 'luaopen_luasql_mysql':
src/ls_mysql.c:605:25: error: expected ')' before 'MYSQL_SERVER_VERSION'
     lua_pushliteral (L, MYSQL_SERVER_VERSION);
                         ^
src/ls_mysql.c:605:5: error: too few arguments to function 'lua_pushlstring'
     lua_pushliteral (L, MYSQL_SERVER_VERSION);
     ^
/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include/lua.h:175:16: note: declared here
 LUA_API void  (lua_pushlstring) (lua_State *L, const char *s, size_t l);
                ^~~~~~~~~~~~~~~
```
I haven't investigated this, but it doesn't look too menacing.
Cheers,
Eneas

**Comment by cotequeiroz** [comment]
@micmac1 
In fact, this is all it takes:
```
--- a/src/ls_mysql.c
+++ b/src/ls_mysql.c
@@ -17,6 +17,9 @@
 #endif

 #include "mysql.h"
+#ifndef MYSQL_SERVER_VERSION
+#include "server/mysql_version.h"
+#endif

 #include "lua.h"
 #include "lauxlib.h"
```
I haven't opened a PR for this, but if you want me to, let me know.
Cheers,
Eneas

**Comment by micmac1** [comment]
Bumped the release from 10.2.15 to 10.2.16. Run-tested on ar71xx,

**Comment by cotequeiroz** [comment]
```
Package gammu is missing dependencies for the following libraries:
libmariadb.so.3
```
I'm not sure this is the right way to do it, but I would add a commit here to change gammu to depend on libmariadb, so that they get updated together.
```
diff --git a/utils/gammu/Makefile b/utils/gammu/Makefile
index 4ac542421..08a61f82b 100644
--- a/utils/gammu/Makefile
+++ b/utils/gammu/Makefile
@@ -10,7 +10,7 @@ include $(TOPDIR)/rules.mk

 PKG_NAME:=gammu
 PKG_VERSION:=1.38.4
-PKG_RELEASE:=2
+PKG_RELEASE:=3

 PKG_SOURCE_URL:=http://dl.cihar.com/gammu/releases/
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
@@ -31,7 +31,7 @@ define Package/gammu
        URL:=http://dl.cihar.com/gammu/releases/
        DEPENDS:=+libpthread +libcurl +glib2 $(ICONV_DEPENDS) $(INTL_DEPENDS)
        DEPENDS+=+PACKAGE_python:python +PACKAGE_bluez-libs:bluez-libs
-       DEPENDS+=+PACKAGE_libmariadbclient:libmariadbclient +PACKAGE_unixodbc:unixodbc +PACKAGE_libpq:libpq
+       DEPENDS+=+PACKAGE_libmariadb:libmariadb +PACKAGE_unixodbc:unixodbc +PACKAGE_libpq:libpq
        DEPENDS+=+PACKAGE_libusb-1.0:libusb-1.0
 endef
```

**Comment by micmac1** [comment]
Hi,

Is this really needed? Mariadb Makefile sets up PROVIDES.

Regards
Seb

**Comment by micmac1** [comment]
Am June 29, 2018 9:12:56 PM UTC schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Hi,
>
>Is this really needed? Mariadb Makefile sets up PROVIDES.
>
>Regards
>Seb

Oh yes it is. Good thinking.

**Comment by cotequeiroz** [comment]
Yes, because of the conditional. PACKAGE_libmariadbclient would never be true.  You could write +PACKAGE_libmariadb:libmariadbclient and it would work.

**Pull request merged**
