### PR TITLE
treewide: Use default PKG_BUILD_DIR when possible

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: too many to list here
Compile tested: armvirt-64 / x86-64, 2019-10-04 snapshot sdks
Run tested: none

Description:
This removes lines that set `PKG_BUILD_DIR` when the set value is no different from the default value.

Specifically, the line is removed if the assigned value is:

* `$(BUILD_DIR)/$(PKG_NAME)-$(BUILD_VARIANT)/$(PKG_NAME)-$(PKG_VERSION)`

  The default `PKG_BUILD_DIR` was [updated][1] to incorporate `BUILD_VARIANT` if it is set, so now this is identical to the default value.

* `$(BUILD_DIR)/$(PKG_NAME)-$(BUILD_VARIANT)/$(PKG_SOURCE_SUBDIR)`

  if `PKG_SOURCE_SUBDIR` is set to `$(PKG_NAME)-$(PKG_VERSION)`, making it the same as the previous case

* `$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)`

  This is the same as the default `PKG_BUILD_DIR` when there is no `BUILD_VARIANT`.

* `$(BUILD_DIR)/[name]-$(PKG_VERSION)`

  where `[name]` is a string that is identical to `PKG_NAME`

[1]: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=e545fac8d968864a965edb9e50c6f90940b0a6c9

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
Something weird is happening with lcd4linux... each tarball that `make package/lcd4linux/download` creates has a different checksum.

[First CircleCI run](https://circleci.com/gh/openwrt/packages/5565):

```
make[1]: Entering directory '/home/build/build_dir'
make[2]: Entering directory '/home/build/openwrt_packages/utils/lcd4linux'
WARNING: PKG_MIRROR_HASH is missing, set to 30a8a4fb9698adc8685919d887315d06c6d7571169f7c70a92e66c0fdaf32cb8
make[2]: Leaving directory '/home/build/openwrt_packages/utils/lcd4linux'
time: package/feeds/packages/lcd4linux/custom/check#0.01#0.00#0.02
make[2]: Entering directory '/home/build/openwrt_packages/utils/lcd4linux'
WARNING: PKG_MIRROR_HASH is missing, set to 30a8a4fb9698adc8685919d887315d06c6d7571169f7c70a92e66c0fdaf32cb8
make[2]: Leaving directory '/home/build/openwrt_packages/utils/lcd4linux'
time: package/feeds/packages/lcd4linux/full/check#0.01#0.00#0.02
make[1]: Leaving directory '/home/build/build_dir'
=> Package HASH check failed
Exited with code 1
```

[Second CircleCI run](https://circleci.com/gh/openwrt/packages/5566):

```
make[1]: Entering directory '/home/build/build_dir'
make[2]: Entering directory '/home/build/openwrt_packages/utils/lcd4linux'
WARNING: PKG_MIRROR_HASH is missing, set to 40ff936b0a73e94c80a2201a4f629daf13201ed0059b0e20dab46a6a4c112c33
make[2]: Leaving directory '/home/build/openwrt_packages/utils/lcd4linux'
time: package/feeds/packages/lcd4linux/custom/check#0.01#0.00#0.02
make[2]: Entering directory '/home/build/openwrt_packages/utils/lcd4linux'
WARNING: PKG_MIRROR_HASH is missing, set to 40ff936b0a73e94c80a2201a4f629daf13201ed0059b0e20dab46a6a4c112c33
make[2]: Leaving directory '/home/build/openwrt_packages/utils/lcd4linux'
time: package/feeds/packages/lcd4linux/full/check#0.01#0.00#0.02
make[1]: Leaving directory '/home/build/build_dir'
=> Package HASH check failed
Exited with code 1
```

I'm going to undo the change to lcd4linux to keep this PR going and come back to it later if/when this weirdness is resolved.

**Comment by neheb** [comment]
That's a known issue with svn. My solution is at: https://github.com/openwrt/packages/pull/9916

That PR seems stalled unfortunately.

**Comment by jefferyto** [comment]
@neheb thanks for the tip - I should have done a search first :man_facepalming:

**Comment by neheb** [comment]
Hrm so boost is failing again (as it does everytime) because of too little RAM in CircleCI.

Just gonna merge this.

**Pull request merged**
