### PR TITLE
ci: use openwrt/gh-action-sdk@v4

### PR DESCRIPTION
**Pull request by ynezz**
In order to use feeds from GH mirror for GH actions, thus saving a lot
of resources being wasted. While at it fix whitespace issue.

Signed-off-by: Petr Štetiar <ynezz@true.cz>

### CODE REVIEW

**Comment by ynezz** [comment]
v4 contains just [following change](https://github.com/openwrt/gh-action-sdk/commit/d29e7cc00b266b489491a0c04663562780268063) so we don't hammer the poor Git server on every push in the PR:

```diff

diff --git a/entrypoint.sh b/entrypoint.sh
index 35e367c..99d6117 100755
--- a/entrypoint.sh
+++ b/entrypoint.sh
@@ -15,7 +15,10 @@ fi
 echo "src-link $FEEDNAME $GITHUB_WORKSPACE/" > feeds.conf
 
 if [ -z "$NO_DEFAULT_FEEDS" ]; then
-	cat feeds.conf.default >> feeds.conf
+	echo 'src-git-full luci https://github.com/openwrt/luci' > feeds.conf
+	echo 'src-git-full routing https://github.com/openwrt/routing' >> feeds.conf
+	echo 'src-git-full packages https://github.com/openwrt/packages' >> feeds.conf
+	echo 'src-git-full telephony https://github.com/openwrt/telephony' >> feeds.conf
 fi
 
 #shellcheck disable=SC2153
```

IIUC current CI failures seems unrelated to this change.

**Comment by champtar** [comment]
Instead of hardcoding the feeds, should we have a feeds.conf.defaultgh in the OpenWrt repo ?
LGTM for now

**Comment by ynezz** [comment]
> Instead of hardcoding the feeds, should we have a feeds.conf.default in the OpenWrt repo?

AFAIK there is still a preference to use project infrastructure for such purposes.

**Comment by ynezz** [comment]
Thank you for the review!

**Comment by champtar** [comment]
I meant a second file with `gh` at the end pointing to the github infra, not to change the current file
I 100% agree default should stay openwrt.org servers

**Comment by jefferyto** [comment]
FYI v4 was changed to include https://github.com/openwrt/gh-action-sdk/commit/ceb805159560c20ffb752f6677bae2b661cafd91.

**Comment by ynezz** [comment]
> FYI v4 was changed to include [openwrt/gh-action-sdk@ceb8051](https://github.com/openwrt/gh-action-sdk/commit/ceb805159560c20ffb752f6677bae2b661cafd91).

@jefferyto Sorry for the breakage and thank you for the fix!

**Pull request merged**
