### PR TITLE
lftp: updated to 4.7.5

### PR DESCRIPTION
**Pull request by fededim**
sstp-client: updated to 1.0.11 and moved under VPN submenu

Signed-off-by: fededim@gmail.com

### CODE REVIEW

**Comment by zorun** [comment]
@fededim  Why would you move lftp to the VPN submenu?

**Comment by zorun** [comment]
Ah I see, sorry, you updated two packages in the same commit.

Please try to keep changes to separate packages in separate commits/PR, because otherwise it's harder to follow.

**Comment by fededim** [comment]
Only sstp-client has moved, not lftp. Usually I use a single commit single PR for all new packages while I batch multiple minor package updates in a single commit  PR. Anyway you prefer just separate commits or also separate pr (e.g. 2 commits/1 pr or 2 commits/2pr) ?

**Comment by hnyman** [comment]
Minor updates to several packages can be combined to the same PR, but having a separate commit per package would be great. That helps keeping the git history more clear.

**Comment by fededim** [comment]
Fine, so for next times multiple commits single PR.

**Pull request merged**
