### PR TITLE
znc: Fix compilation without deprecated APIs in OpenSSL 1.0.2

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @KanjiMonster 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
Oh. Upstream commits:

https://github.com/znc/znc/pull/1615
https://github.com/jimloco/Csocket/pull/75

**Comment by neheb** [comment]
Not that it matters, The first commit was upstreamed.

**Comment by KanjiMonster** [comment]
What was the reason for closing it? Seemed good to me on a first glance?

**Comment by neheb** [comment]
This was merged.

**Pull request closed without merging**
