### PR TITLE
audit: move from packages to openwrt

### PR DESCRIPTION
**Pull request by M95D**
Maintainer: @tpetazzoni
Compile tested: x86-64, Gentoo Linux, OpenWrt r25618
Run tested: mvebu / Turris Omnia / r25618, installs ok, rules are loaded, daemon starts, logging to file works. Remote logging not tested. Dependent packages not tested.

Description:
This package was moved to OpenWrt packages and combined with libaudit from there. Tests were done on that package.

See https://github.com/openwrt/openwrt/pull/15138

PLEASE MERGE AT THE SAME TIME!

### CODE REVIEW

**Comment by feckert** [comment]
I already made this suggestion 3 years ago https://github.com/openwrt/openwrt/pull/4447

**Comment by M95D** [comment]
> I already made this suggestion 3 years ago [openwrt/openwrt#4447](https://github.com/openwrt/openwrt/pull/4447)

Yes, but now there's a version update too! :partying_face:

**Comment by feckert** [comment]
Let's hope it works this time. I would welcome it. It simply makes no sense to maintain the package in the `core` and in the `package feed`.

**Comment by hauke** [comment]
https://github.com/openwrt/openwrt/pull/15138 was merged, please merge this too.

**Pull request merged**
