### PR TITLE
python-requests: bump to version 2.24.0

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @BKPepe , me
Compile tested: https://github.com/openwrt/openwrt/commit/870588b6ebd8d818f65e5784bc866a8d67de0a31   x86
Run tested:  https://github.com/openwrt/openwrt/commit/870588b6ebd8d818f65e5784bc866a8d67de0a31   x86

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by BKPepe** [comment]
@commodo Should we update it in OpenWrt 19.07?

**Comment by commodo** [comment]
> @commodo Should we update it in OpenWrt 19.07?

no idea;
i still don't have a clear view/idea on 19.07 getting updates;
i can do a PR if you want;

**Comment by hnyman** [comment]
> i still don't have a clear view/idea on 19.07 getting updates;

19.07 should get security updates /fixes
19.07 can get backports of other fixes, assuming that they do not affect other packages or invalidate current uci config etc.

**Comment by commodo** [comment]
I can't tell if this version bump really has only security updates.
Maybe for 19.07 it may not make sense to update?

**Pull request merged**
