### PR TITLE
cshark: fix compilation with GCC12

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lperkov 
Compile tested: mips24

### CODE REVIEW

**Comment by BKPepe** [comment]
My usual questions related to the patch, which you want to add.

Patch:
- Who is the author
- Where is the commit subject and commit description in the patch
- Was the patch upstreamed? If yes, it is unclear from the PR or the commit itself.

**Comment by neheb** [comment]
I wrote it. It's a fairly simple patch. Upstream seems dead.

**Comment by BKPepe** [comment]
:-( Sending it upstream and then backporting the patch has many advantages, like a commit description in the patch, etc. Even though it is dead, it forces you to do such things. Otherwise, we will need to carry this patch for ages, and we do not know what it is doing, who the author is, etc.

**Comment by neheb** [comment]
Honestly this package probably doesn't even work. I agree generally speaking and I do upstream most of my patches. For some stuff I don't even want to touch it (*cough* CMake Iconv *cough*)

**Pull request merged**
