### PR TITLE
python-cryptography: update to version 1.9 ; add python3 variant, and simplify/remove python-cffi host dep 

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @jefferyto 
Compile tested: http://github.com/lede-project/source/commit/d72371e42bd5b8738a75a75d970bc73b90cd9839 x86_64
Run tested: http://github.com/lede-project/source/commit/d72371e42bd5b8738a75a75d970bc73b90cd9839 x86_64

Description:

Fixes: https://github.com/openwrt/packages/issues/4638

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
i was hoping i'd get a bit more relaxed time to get this change in :)
i wasn't aware this would break buildbot that badly

but in any case, my current "sprint" of cleaning up the Python eco-system [and some of my other packages] is nearing an end ;
i may have 1-2 PRs after this

**Comment by hnyman** [comment]
You might add yourself as the second maintainer to those packages, as you seem to be taking care of them in any case ;-)

**Comment by hnyman** [comment]
Could you also please update python-six to use PKG_HASH.

That is the error that travis complains about: 
https://travis-ci.org/openwrt/packages/builds/258050643#L3015

**Comment by commodo** [comment]
oh right ;
i updated the PKG_HASH in another branch and not on this one [ for six ]

hmm ; i could add myself as 2nd maintainer ;
i wonder how that would be done ; comma-separated ? or ?

**Comment by commodo** [comment]
found example ; re-spinned

**Pull request merged**
