### PR TITLE
boost: Use @SF macro for PKG_SOURCE_URL.

### PR DESCRIPTION
**Pull request by neheb**
More flexible + easier to read.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ClaymorePT

### CODE REVIEW

**Comment by ClaymorePT** [comment]
I'm not comfortable in using the shortcut. Explicit is better in this case.

It was removed in https://github.com/openwrt/packages/pull/3326 because the evaluation was providing the wrong link at sourceforge.  There's a comment from me in the pull request, explaining it.

**Comment by neheb** [comment]
The link in this pull request is different than in https://github.com/openwrt/packages/pull/3326 . sha256sum still matches.

**Comment by ClaymorePT** [comment]
Travis is probably failing because of a timeout. Lack of build time to complete building boost.

If all checks out, it's fine by me.

**Comment by diizzyy** [comment]
@ClaymorePT 
It's much easier if we all follow the same syntax as far as URLs goes and using the alias actually retries SF mirrors several times while using a static URL doesn't.
https://github.com/lede-project/source/blob/master/scripts/download.pl#L190

**Comment by ClaymorePT** [comment]
@diizzyy 

You are right. But there were issues in the past, with allowing Source Forge to provide a link. From time to time, Source Forge seems to provide the wrong link to the proper file, ending up with a failed hash verification. This is why I ended up using a static link.

I could fallback again to the @SF macro, but I honestly don't know what will happen if Source Forge doing their thing once again...

PS: We really need a server/mirror for LEDE/OpenWRT to maintain a copy of packages sources.

**Comment by diizzyy** [comment]
@ClaymorePT 
In the past I suggested that we'd piggyback (fallback) on Gentoo's dist-files mirrors as it covers most of packages but it was deemed as an unnecessary precaution. I'm not sure how updated the current mirrors are however.

**Comment by ClaymorePT** [comment]
@diizzyy 

As Soon As I Can, I will update the Boost makefile and change it to use the @SF . Let's see how it goes. If it start's to develop the same symptoms, I can always easily rollback the commit.

**Comment by diizzyy** [comment]
Sure, sounds great!

**Comment by neheb** [comment]
So uhhh. Should I close this?

**Comment by ClaymorePT** [comment]
@neheb yes you can close it. 👍 
I will reference it, in the next boost pull-request.

**Comment by neheb** [comment]
Cool

**Pull request closed without merging**
