### PR TITLE
mwan3: update to version 2.0-0

### PR DESCRIPTION
**Pull request by Adze1502**
IPv6 support! :D
Big code overhaul; expect bugs..

Signed-off-by: Jeroen Louwes <jeroen.louwes@gmail.com>

### CODE REVIEW

**Comment by Adze1502** [comment]
Trunk release only
Wiki documentation will follow

**Comment by sbyx** [comment]
I'm interested to know how you deal with IPv6 in that regard. Do you remove the delegated prefixes when an IPv6 interface is not used or do you only remove the routes?

**Comment by Adze1502** [comment]
@sbyx ,  I make use of stateless prefix nat and use only ULA (fc00::/7) address space for LAN. Users have to configure NAT themselves for this to work. I have only tested it with static ipv6 addresses though.

**Comment by sbyx** [comment]
IPv6 and NAT? You are truely evil :p 
On a serious note: I believe this will break so and so many applications assuming there is no NAT on v6 ever (which in the end was one of the goals of v6), e.g. WebRTC in the browser etc.

That said that is no blocker for merging this here, merely a friendly note.

**Comment by Adze1502** [comment]
@sbyx  Unless the end user has ipv6 PI space, i see no other way around the problem than to use NAT. At least it can be stateless, so breakage of apps will be minimal...

Thnx for merging!

**Comment by sbyx** [comment]
Well, the canonical solution would be to dynamically add and remove assigned prefixes from the client interfaces, i.e. when switching from IPV6 ISP A to ISP B remove the assigned prefixes from A from the LAN interfaces and add those of B. The router would then send a Router Advertisement immediately telling all clients to change addresses.

The added benefit would be that clients would be actively notified of a change in connectivity. Plus applications actively transporting client addresses in the protocol would not break. It would also allow clients to make use of MPTCP or QUIC to seamlessly switch between uplinks.

**Pull request merged**
