### PR TITLE
bind libjson-c patch

### PR DESCRIPTION
**Pull request by taeasy**
Maintainer: jerry @<88336@live.com> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:
fix bind: include/json/config.h No such file or directory

### CODE REVIEW

**Comment by neheb** [comment]
This has formal issues.

I also do not like this patch. I assume this can be overridden with CONFIGURE_VARS.

**Comment by neheb** [comment]
I see the problem. jsoncpp installs to /usr/include/json whereas json-c installs to /usr/include/json-c

**Comment by neheb** [comment]
The error I get is different:

```
/home/mangix/devstuff/openwrt/staging_dir/target-mips_24kc_musl/usr/include/json/config.h:8:10: fatal error: cstddef: No such file or directory
    8 | #include <cstddef>
```

**Comment by neheb** [comment]
```
TARGET_CFLAGS += -DHAVE_JSON_C -UHAVE_JSON
```

Seems to do the trick

**Comment by nmeyerhans** [comment]
Closing in favor of #11788

**Pull request closed without merging**
