### PR TITLE
openwrt-22.03: openvswitch: bump to 2.15.3 

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: me
Compile tested: none
Run tested: none

Description:

Backport of https://github.com/openwrt/packages/pull/18096

Ping @stintel

### CODE REVIEW

**Comment by BKPepe** [comment]
@aparcar Can we ask you to have Docker images for 22.03?

CI log:
```
manifest for openwrt/sdk:aarch64_cortex-a53-openwrt-22.03 not found: manifest unknown: manifest unknown
```

**Comment by JonnyTischbein** [comment]
I am a bit unsure how cherry-picks are used here, but as far as I unterstood it I should cherry-pick from the openwrt/packages master branch.
Your cherry-picks are from "yousong/packages"
https://github.com/yousong/packages/commit/cf1e1468588d69f413fc1305a3bdf811197551e6
https://github.com/yousong/packages/commit/f8c8348f32a91ce1f60d9fe09d3c9fce607b0fe9

Is that correct ?

**Comment by yousong** [comment]
> 

I cherry-picked by commit ids which are present in both repos.  GitHub decides to replace those two text commit ids in the commit messages to my fork repo.  That's a presentation detail.

**Comment by ynezz** [comment]
> @aparcar Can we ask you to have Docker images for 22.03?

I've re-run the jobs and it seems to work now.

**Comment by yousong** [comment]
Merged.  Thanks everyone!

**Pull request merged**
