### PR TITLE
python-attrs: Update to 18.2.0

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jefferyto 
Compile tested: mvebu

### CODE REVIEW

**Comment by champtar** [comment]
@neheb If you can rebase your PRs to trigger CircleCI and have one of CircleCI or Travis to build properly that would be great

**Comment by neheb** [comment]
Not seeing the circle but done.

**Comment by champtar** [comment]
Can you refresh the page, because right now I see it (and build is successful ! )

**Comment by neheb** [comment]
Yeah it's fine now

**Pull request merged**
