### PR TITLE
[RFC] exfat-nofuse: fix compile error on kernel 4.18+

### PR DESCRIPTION
**Pull request by dengqf6**
Switched to https://github.com/AndyLavr/exfat-nofuse

Maintainer: @yousong @diizzyy 
Compile tested: mvebu kernel 4.19.10; ramip kernel 4.14.88
Run tested: mvebu kernel 4.19.10

### CODE REVIEW

**Comment by diizzyy** [comment]
Perhaps it's time for another look at sdfat which is more "active" in that regard?
https://github.com/cryptomilk/kernel-sdfat
I'd also think we should do a runtime test just to be safe.

**Comment by dengqf6** [comment]
@diizzyy The sdfat driver doesn't support 4.18+, either.
I found a more recent fork which supports 4.18+, https://github.com/AndyLavr/exfat-nofuse, but it doesn't have backward compatibility.

**Comment by diizzyy** [comment]
@dengqf6 
My "concern" is that sdfat seems to follow upstream much more closely compared the current repo. Having said that I don't have enough knowledge to evalutate the quality between the two repos so my concern might be unjustified.

**Comment by dengqf6** [comment]
@AndyLavr @cryptomilk

**Comment by cryptomilk** [comment]
The sdfat is the successor for exfat. You should use sdfat and it shouldn't be that hard to get it working on a newer kernel.

**Comment by dengqf6** [comment]
Switched to https://github.com/AndyLavr/exfat-nofuse
Added a patch to fix backward compatibility.

**Comment by yousong** [comment]
Looks like the dorimanx/exfat-nofuse repo hasn't been updated for a few months.  It will take me a while to evaluate switching to another fork.

the maintenance work of building out of tree module against different kernel versions is very big.  If this package goes in that direction too far, I may propose to drop it from OpenWrt.  Right now a few dozen patches should be fine.

As for the `cryptomilk/kernel-sdfat` repo, if you really need it, open a pull request for review.  It can exist as a separate package with dependency on `LINUX_4_4`.

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/6238 ?
I'm not sure if we need to modify the defaults and/or set anything regarding the kernel config.

**Comment by yousong** [comment]
Sorry, it seems to me the AndyLavr/exfat-nofuse fork has its own goal of fitting with its own forked dragon kernel, not geared/maintained for use in OpenWrt or other distro.

I cannot find any targets in OpenWrt trunk switched to 4.19 yet, as such I tend to close this pull request for now.

The plan would be keep picking minor patches from dorimanx/exfat-nofuse so that the package at least compiles and works out of box in the near future.  Then at some point when it's clear that the module is really abandoned upstream, I will propose to just drop it here.

**Comment by dengqf6** [comment]
OK, let's carry a patch like [Arch Linux did](https://aur.archlinux.org/cgit/aur.git/tree/4.18.patch?h=exfat-dkms-git)..

**Comment by dengqf6** [comment]
As @diizzyy mentioned here https://github.com/dorimanx/exfat-nofuse/issues/102#issuecomment-317361401, https://github.com/coolshou/exfat seems like another option

**Pull request closed without merging**
