### PR TITLE
podman: fix build on MIPS

### PR DESCRIPTION
**Pull request by dangowrt**
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by neheb** [comment]
```
/dev/tty.go:116:22: cannot use s.Rdev (type uint32) as type uint64 in argument to minDevNum
2020-12-21T13:05:01.4801404Z ../../../../../dl/go-mod-cache/github.com/containers/psgo@v1.5.1/internal/dev/tty.go:117:22: cannot use s.Rdev (type uint32) as type uint64 in argument to majDevNum
2020-12-21T13:05:01.4900295Z # github.com/containers/podman/v2/pkg/signal
2020-12-21T13:05:01.4900946Z ../../pkg/signal/signal_common.go:20:13: undefined: signalMap
2020-12-21T13:05:01.4901542Z ../../pkg/signal/signal_common.go:35:20: undefined: signalMap
2020-12-21T13:05:01.4902148Z ../../pkg/signal/signal_linux_mipsx.go:95:42: undefined: signalMap
2020-12-21T13:05:01.4902778Z ../../pkg/signal/signal_linux_mipsx.go:96:20: undefined: signalMap
```

**Comment by Luap99** [comment]
Please try with https://github.com/containers/podman/commit/1ad796677e1ce3f03463c791818176586987c389.patch Notice the lowercase `s` in signalMap

**Comment by neheb** [comment]
ping @dangowrt

**Comment by Luap99** [comment]
Also add https://github.com/containers/podman/commit/bc21fabbd7be9269187775dc74644ca898006fe8.patch to fix the other issue.

**Comment by dangowrt** [comment]
@Luap99 
still failing
```
2021-01-06T15:16:52.2559365Z Finding targets
2021-01-06T15:16:53.0316568Z 
2021-01-06T15:16:53.0317303Z Building targets
2021-01-06T15:16:54.0557289Z github.com/containers/podman/v2/pkg/signal
2021-01-06T15:16:54.0876930Z # github.com/containers/podman/v2/pkg/signal
2021-01-06T15:16:54.0877783Z ../../pkg/signal/signal_common.go:20:13: undefined: signalMap
2021-01-06T15:16:54.0878563Z ../../pkg/signal/signal_common.go:35:20: undefined: signalMap
2021-01-06T15:16:54.0879332Z ../../pkg/signal/signal_linux_mipsx.go:95:42: undefined: signalMap
2021-01-06T15:16:54.0880132Z ../../pkg/signal/signal_linux_mipsx.go:96:20: undefined: signalMap
2021-01-06T15:16:54.1377678Z 
2021-01-06T15:16:54.2627676Z make[2]: *** [Makefile:78: /home/build/openwrt/build_dir/target-mips_24kc_musl/podman-2.2.1/.built] Error 2
```

**Comment by Luap99** [comment]
> Please try with https://github.com/containers/podman/commit/1ad796677e1ce3f03463c791818176586987c389.patch Notice the lowercase s in signalMap

Use https://github.com/containers/podman/commit/1ad796677e1ce3f03463c791818176586987c389.patch the old patch (ade28a74cc402426518e26550b8e23a1f02af9d5) was wrong.

**Comment by dangowrt** [comment]
> > Please try with https://github.com/containers/podman/commit/1ad796677e1ce3f03463c791818176586987c389.patch Notice the lowercase s in signalMap
> 
> Use https://github.com/containers/podman/commit/1ad796677e1ce3f03463c791818176586987c389.patch the old patch (ade28a74cc402426518e26550b8e23a1f02af9d5) was wrong.

Updated, thanks!

**Comment by dangowrt** [comment]
@Luap99 now this unveils a new error:
```
2021-01-06T17:04:57.1702578Z Finding targets
2021-01-06T17:04:57.8298237Z 
2021-01-06T17:04:57.8299103Z Building targets
2021-01-06T17:04:58.7157298Z github.com/containers/podman/v2/libpod
2021-01-06T17:04:58.7165031Z github.com/containers/podman/v2/pkg/bindings/containers
2021-01-06T17:04:58.7626567Z # github.com/containers/podman/v2/pkg/bindings/containers
2021-01-06T17:04:58.7627634Z ../../pkg/bindings/containers/attach.go:137:28: undefined: "github.com/containers/podman/v2/pkg/signal".SIGWINCH
2021-01-06T17:04:58.7628849Z ../../pkg/bindings/containers/attach.go:327:15: undefined: "github.com/containers/podman/v2/pkg/signal".SIGWINCH
2021-01-06T17:04:58.7630033Z ../../pkg/bindings/containers/attach.go:446:28: undefined: "github.com/containers/podman/v2/pkg/signal".SIGWINCH
2021-01-06T17:04:59.1873457Z # github.com/containers/podman/v2/libpod
2021-01-06T17:04:59.1874486Z ../../libpod/container_api.go:256:49: undefined: "github.com/containers/podman/v2/pkg/signal".SIGWINCH
2021-01-06T17:04:59.1900458Z 
2021-01-06T17:04:59.3017696Z make[2]: *** [Makefile:78: /home/build/openwrt/build_dir/target-mips_24kc_musl/podman-2.2.1/.built] Error 2
2021-01-06T17:04:59.3020291Z make[2]: Leaving directory '/home/runner/work/packages/packages/utils/podman'
```

**Comment by Luap99** [comment]
OK, Patch https://github.com/Luap99/libpod/commit/fcba0df068d07ee7a26ec9d891220233d7d17dfd.patch should fix this error. 

I'm sorry to bother you. I have no way to test the build on my system. This is hopefully the last one.

**Comment by dangowrt** [comment]
@Luap99  How do it hot-patch that into podman? Wouldn't you first need to tag psgo?

Other than that, test-building is available through github-CI as well as circle-ci by opening a PR like this in this repository.
You could do that yourself for test-builds, just clearly mark the PR to be for testing only, so people don't spend time reviewing them.

**Comment by Luap99** [comment]
The last patch contains changes only in podman so we don't have to tag psgo. I will open a PR in podman with the patch if you can confirm that it builds successfully. But I can also open a PR here to test the changes myself if you prefer that.

**Comment by neheb** [comment]
Does signal_linux_mipsx.go apply to mips64 as well?

**Comment by Luap99** [comment]
> Does signal_linux_mipsx.go apply to mips64 as well?

Yes it should apply to mips mipsle mips64 mips64le

**Comment by neheb** [comment]
```
github.com/containers/podman/v2/pkg/specgen/generate
../../pkg/specgen/generate/container.go:285:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Major
../../pkg/specgen/generate/container.go:286:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Minor
../../pkg/specgen/generate/container.go:296:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Major
../../pkg/specgen/generate/container.go:297:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Minor
../../pkg/specgen/generate/container.go:307:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Major
../../pkg/specgen/generate/container.go:308:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Minor
../../pkg/specgen/generate/container.go:318:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Major
../../pkg/specgen/generate/container.go:319:37: cannot use statT.Rdev (type uint32) as type uint64 in argument to unix.Minor
# github.com/containers/podman/v2/pkg/spec
../../pkg/spec/config_linux.go:297:39: cannot use wdStat.Rdev (type uint32) as type uint64 in argument to unix.Major
../../pkg/spec/config_linux.go:298:39: cannot use wdStat.Rdev (type uint32) as type uint64 in argument to unix.Minor
../../pkg/spec/config_linux.go:360:39: cannot use ltdStat.Rdev (type uint32) as type uint64 in argument to unix.Major
../../pkg/spec/config_linux.go:361:39: cannot use ltdStat.Rdev (type uint32) as type uint64 in argument to unix.Minor

```

**Comment by neheb** [comment]
@Luap99 https://github.com/docker/engine/commit/5f0231bca193320e1a3d785a3ade0e64241fe580

**Comment by neheb** [comment]
@dangowrt https://github.com/neheb/packages/commit/69e2b17176963a2d5ad4d9a55f59c9f2e76e477c compiles fine.

**Comment by Luap99** [comment]
Sorry for not reporting back earlier. I already made changes in https://github.com/containers/podman/pull/8907.

The first podman 3.0 release candidate should be released later today. It should compile on mips without any extra patches. I will ping you once the tag is created to test it.

**Pull request merged**
