### PR TITLE
openssh: bump to 9.7p1

### PR DESCRIPTION
**Pull request by graysky2**
Release notes: https://www.openssh.com/txt/release-9.7

Removed upstreamed patch: 010-better_fzero-call-detection.patch

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

Maintainer: @SibrenVasse, @tripolar

### CODE REVIEW

**Comment by SibrenVasse** [comment]
Run tested: MIR4A / ramips / master

**Comment by BKPepe** [comment]
@SibrenVasse, so could you please approve this PR? :)

**Comment by SibrenVasse** [comment]
@BKPepe I could, but I'm not the maintainer. Does me approving it as a random contributor do anything?

**Comment by graysky2** [comment]
I emailed the maintainer but I do not know how to find the person's github name based on email...

**Comment by graysky2** [comment]
I emailed the maintainer

**Comment by BKPepe** [comment]
@SibrenVasse - Well, it counts. If it is helpful, it depends on the guy, who will merge it like me. :)

**Comment by BKPepe** [comment]
In the commit, you removed one patch, but in the commit description, there isnt said anything about it. Is it intentional?

**Comment by SibrenVasse** [comment]
@BKPepe That is an patch from upstream that I back ported to 9.6p1 to fix a compilation error on one of the platforms. It is included in upstream 9.7p1 and can be removed.

**Review by SibrenVasse — APPROVED** [review]

**Comment by graysky2** [comment]
@BKPepe - sorry, should have commented on the patch removed.  Fixed in latest commit.

**Pull request merged**
