### PR TITLE
netifyd: update to 5.0.61

### PR DESCRIPTION
**Pull request by neheb**
Fix versioning to be compatible with apk.

Small cleanups.

Maintainer: @dsokoloski

### CODE REVIEW

**Comment by hnyman** [comment]
@neheb 
Based on the answer from maintainer, would it be better to just adjust versioning for apk?

**Comment by neheb** [comment]
@hnyman you can handle it if you want.

**Comment by hnyman** [comment]
I did that in #25436

**Comment by hnyman** [comment]
I will close this, as based on the discussion above, the PR would still need lots of changes to the package logic, and neheb is likely not going to do them (as his main idea was the apk compatibility).

**Pull request closed without merging**
