### PR TITLE
seafile: update to 4.1.2, create config file

### PR DESCRIPTION
**Pull request by kissg1988**
Please revise and merge the changes.

Thanks!

### CODE REVIEW

**Comment by hnyman** [comment]
Is there a reason why you don't included the config file as a static file in the package (like usually), but instead you create it on the fly with postinst action? The config contents seems static, so why not use the normal way.

**Comment by kissg1988** [comment]
Yes, there is, opkg would overwrite the config file otherwise each time when upgrading or reinstalling the seafile-server package. At least that's what I saw when I set up fastcgi mode in the init script directly.

If there is a more elegant way to avoid that I'm all ears. :)

-----Original Message-----

**Comment by hnyman** [comment]
To my knowledge, opkg would insert the new file from the package as /etc/config/seafile.opkg and leave the existing file intact.

**Comment by kissg1988** [comment]
Thanks, I'm going to fix that and let you know when done.

**Comment by kissg1988** [comment]
Done, please check and merge the modifications.

**Pull request merged**
