### PR TITLE
libs/glib2: update to 2.82.0

### PR DESCRIPTION
**Pull request by yegorich**
Maintainer: @tripolar
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software

Description: update package to version 2.82.0 and remove an obsolete patch.

Also remove -Ddefault_library option from MESON_HOST_ARGS and MESON_ARGS as
this is now the default behavior.

### CODE REVIEW

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/24866#issuecomment-2305599353

**Comment by yegorich** [comment]
@neheb should I change anything or is the PR feasible so far?

**Comment by neheb** [comment]
I pointed out what needs to be changed.

**Comment by yegorich** [comment]
OK. I see now. Have just overlooked the MESON_ARGS variable as pcre fix was already implemented.

**Pull request merged**
