### PR TITLE
tinc: update to 1.1 branch (with ECC support)

### PR DESCRIPTION
**Pull request by msva**
Updating tinc package to latest version from 1.1 branch, featuring ECC cryptography, better peers discovery, interactive managing utility and many more.

### CODE REVIEW

**Comment by msva** [comment]
@zioproto ping? what do you think? would you ack this?

**Comment by zioproto** [comment]
I am not sure this is the way to go.

What happens for users that are running 1.0.x ? When they install the this new version of the package it will brake compatibility with other tinc nodes ?
What about configuration and startup scripts ?

The tinc web site still say Latest stable version: 1.0.28

Until there is not a defined migration strategy from tinc 1.0.x to tinc 1.1 I would keep this package as it is.

You can make a pull request to create a completely new package for tinc1.1 for people that want to experiment with it.

**Comment by zioproto** [comment]
I sent an email to the tinc mailing list to get some feedback.

**Comment by msva** [comment]
В письме от воскресенье, 29 мая 2016 г. 0:00:30 TSK пользователь Saverio Proto 
написал:
> I am not sure this is the way to go.
> 
> What happens for users that are running 1.0.x ?

Nothing. They do coexist in my VPN-networks.

> When they install the this new version of the package it will brake 
compatibility with other tinc nodes ?

It shouldn't (until user will made it theyself).

> What about configuration and startup scripts ?

Works out of the box without changes (although, there was complains in logs, 
that Ed25519-curve keys are not set, and proposition for user to run `tinc -n 
netname generate-ed25519-keys`.

Moreover, except for nodes coexistance, I even flawlessly switched 1.0<=>1.1 
tinc package on openwrt on my router with the same config, and all's going 
fine.

It even everything fine with all ways of 1.0 and 1.1 being a target of 
ConnectTo or machine that just performing ConnectTo, but has no another 
machines connecting to it.

> The tinc web site still say Latest stable version: 1.0.28

It is. All 1.1 packages still (after years) counting as pre-release, while 
there are many neat things, which 1.0.x missing :(

> Until there is not a defined migration strategy from tinc 1.0.x to tinc 1.1
> I would keep this package as it is.

There is no need for migration strategy, as I mentioned above, but...

> You can make a pull request to create a completely new package for tinc1.1
> for people that want to experiment with it.
Yes, I'll do in this way, thanks! ;)
(and will maintain it myself, if you have no objections) ;)

> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openwrt/packages/pull/2757#issuecomment-222346099


-- 
wbr,
mva

**Comment by zioproto** [comment]
Yes sure create a new package :) No objections :+1: 
I also strongly suggest to read tinc mailing list when you maintain the 1.1 package.

**Comment by aparcar** [comment]
@zioproto @msva Can we reopen this PR and use the most recent version pre15? I just tried and both seem to stay compatible.

**Pull request closed without merging**
