### PR TITLE
python: fix host compile in macos

### PR DESCRIPTION
**Pull request by jjm2473**
Just a fix of compile error in macos.

Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

Maintainer: Alexandru Ardelean <ardeleanalex@gmail.com>
Compile tested: Macos 10.15.6, Openwrt 18.06
Run tested: 

Description:

### CODE REVIEW

**Comment by neheb** [comment]
ping @commodo @jefferyto 

This should be applied to 19.07 I think.

**Comment by commodo** [comment]
> ping @commodo @jefferyto
> 
> This should be applied to 19.07 I think.

that would be a good idea;
do you want to do the PR, or shall i?

i run-tested this on x86 https://github.com/openwrt/openwrt/commit/c90db26e051e4f0e7cd32333b3bd8c94a13d599a

**Comment by commodo** [comment]
> > ping @commodo @jefferyto
> > This should be applied to 19.07 I think.
> 
> that would be a good idea;
> do you want to do the PR, or shall i?
> 
> i run-tested this on x86 [openwrt/openwrt@c90db26](https://github.com/openwrt/openwrt/commit/c90db26e051e4f0e7cd32333b3bd8c94a13d599a)

wait; disregard this message; i tested this on master;

**Comment by commodo** [comment]
this fix is similar to the one @neheb did for master;
i don't mind which version gets applied here;

**Comment by jefferyto** [comment]
I would prefer to backport #12997 for 19.07 (and also apply for Python 2). I'm not sure this issue is serious enough to warrant fixing in 18.06. (I guess building on Mac is broken but no one should be building 18.06 at this point.)

Also, I'm wondering if this is really necessary:

```make
ifeq ($(HOST_OS),Darwin)
HOST_LDFLAGS += -framework CoreFoundation
endif
```

It wasn't when I tested macOS compilation a while ago, but my Mac is stuck on El Capitan; maybe it is necessary with newer versions of macOS. I can try building on a Mac VM but I don't have a lot of free time at the moment.

**Comment by jjm2473** [comment]
@jefferyto I have compiled on macos this week many times, success after some fixes, so I have committed some PRs for macos works. 
Without '-framework CoreFoundation', ld will failed when linking to 'libintl' (or said 'gettext').
Not only the python affected by 'libintl', but also rpcsvc-proto (rpcgen).

PS: '-framework CoreFoundation' also appeared in packages/net/subversion/patches/301-cross-compilation-macos.patch , but is not affected by libintl.

**Comment by jjm2473** [comment]
Here is another page https://bugs.python.org/msg88604, it is said that 'Python 3.1 rc1 will not build on OS X 10.5.7 with macports libintl', but I did not used macport, libintl was built by openwrt toolchain with default configuration.

**Comment by jefferyto** [comment]
I don't doubt adding `-framework CoreFoundation` worked for you, but you are compiling 18.06 which is two years old. I would like to know if the issue still persists in master. (Build logs, environment details, etc. would also be helpful.)

I prefer to be able to reproduce issues and verify their fixes.

Also note that the [issue](https://bugs.python.org/issue6154) to which the message you linked to belongs has been marked fixed and closed.

**Comment by neheb** [comment]
I don't like this PR.

Is https://github.com/openwrt/packages/commit/769d51fa933e3dc492193b12ad1c5dc01f30072f enough?

**Comment by jjm2473** [comment]
not enough, samba4 depends on python3, should fix python3

**Comment by jefferyto** [comment]
37857a3f2fc8ee7dd9c06e89e044c98995588635, also #12997

**Comment by jjm2473** [comment]
OK, I will backport these PRs and check it

**Comment by jjm2473** [comment]
@neheb Did you check `lang/python/python3/Makefile` in `openwrt-18.06` branch? In this file, `HOST_LDFLAGS` **NOT** comes from `python3-host.mk`, so we must set `HOST_LDFLAGS` in `Makefile`.
Please check it.

**Comment by jefferyto** [comment]
This is not a security issue, we won't be making this change for 18.06.

**Comment by neheb** [comment]
@jefferyto It's a bugfix nonetheless. It helps to have more platforms being able to build OpenWrt. I still run a CentOS7 VM to test compilation on its old GCC version which needs -std=gnu99 or -std=c++11 for host packages.

I'm not happy with this PR as is. I would prefer that https://github.com/openwrt/packages/commit/37857a3f2fc8ee7dd9c06e89e044c98995588635 be backported.

I have no idea what the story is with -framework CoreFoundation . Is it a problem that is not present on newer versions of Python?

**Comment by jjm2473** [comment]
`CoreFoundation` was introduced by libintl, maybe we should check why libintl need that.

**Comment by neheb** [comment]
I manually applied this here: https://github.com/openwrt/packages/commit/4f4f708542318294e328afe52d30704137ef96c1

Please rebase if this is still a problem.

**Comment by jjm2473** [comment]
OK, I will check

**Comment by jjm2473** [comment]
I use last openwrt-18.06 branch, configure failed:
```
configure:3936: checking whether the C compiler works
configure:3958: gcc -O2 -I/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/host/include -I/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/hostpkg/include -I/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/target-aarch64_cortex-a53_musl/host/include -I/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/host/include -I/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/hostpkg/include -I/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/target-aarch64_cortex-a53_musl/host/include -L/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/host/lib -L/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/hostpkg/lib -L/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/target-aarch64_cortex-a53_musl/host/lib -L/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/hostpkg/lib -lssl -lcrypto -Wl,-rpath=/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/hostpkg/lib conftest.c  >&5
ld: warning: directory not found for option '-L/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/target-aarch64_cortex-a53_musl/host/lib'
ld: unknown option: -rpath=/Volumes/sd/src/openwrt-realtek-android-build/staging_dir/hostpkg/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3962: $? = 1
configure:4000: result: no
configure: failed program was:
| /* confdefs.h */
| #define _GNU_SOURCE 1
| #define _NETBSD_SOURCE 1
| #define __BSD_VISIBLE 1
| #define _BSD_TYPES 1
| #define _DARWIN_C_SOURCE 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4005: error: in `/Volumes/sd/src/openwrt-realtek-android-build/build_dir/hostpkg/Python-3.6.12':
configure:4007: error: C compiler cannot create executables
```

I think it was caused by `lang/python/python3/Makefile:267`

**Comment by jjm2473** [comment]
And `lang/python/python/Makefile:271` should be fixed, too.

**Comment by jjm2473** [comment]
@neheb

**Comment by neheb** [comment]
This needs a rebase if it's even an issue anymore.

**Pull request closed without merging**
