### PR TITLE
bash: update to 5.2.37

### PR DESCRIPTION
**Pull request by jen1-sys**
bash: update to 5.2.37

### CODE REVIEW

**Comment by 1715173329** [comment]
CI is failing, please check.

You don't need to write `tools/` prefix, package name is enough.

**Comment by jen1-sys** [comment]
CI is failing because it was not signed with my full name, I don't know who change that

**Comment by jen1-sys** [comment]
@1715173329  I though we could use the full path as the package is located in 2 locations?

**Comment by 1715173329** [comment]
bash is only in utils in this repo. Anyway, please check our documentation: https://openwrt.org/submitting-patches#submission_guidelines

Full name is required too.

**Comment by jen1-sys** [comment]
This package is not compiled anymore for my Asus RT-AC88U / BCM53xx / arm_cortex-a9. So I will close this PR as I can test it anymore. Will open a new one if it is complied again

**Comment by jen1-sys** [comment]
This package is not compiled anymore for my Asus RT-AC88U / BCM53xx / arm_cortex-a9. So I will close this PR as I can test it anymore. Will open a new one if it is complied again

**Pull request closed without merging**
