### PR TITLE
nginx: upstep, footprint optimizations and support for lua-nginx

### PR DESCRIPTION
**Pull request by dirkfeytons**
Here's a set of 3 commits related to nginx. The first brings the package to the latest version. The second does some footprint optimizations and the third adds support for the lua-nginx module.

### CODE REVIEW

**Comment by heil** [comment]
ive commited the update to 1.9.9. Could you please refresh your lua-nginx-module patch?

**Comment by champtar** [comment]
ping @dirkfeytons

**Comment by dirkfeytons** [comment]
I'm working on a new PR with an upstep to the just released nginx 1.10.0 stable version.

**Comment by heil** [comment]
thx

**Pull request closed without merging**
