### PR TITLE
[openwrt-22.03] transmission: add syscalls to seccomp filter

### PR DESCRIPTION
**Pull request by jjm2473**
Add missing syscalls found using `/etc/init.d/transmission trace`.

fix crash on adding torrent on x86_64 platform

(openwrt 23.05 and master use transmission 4.0, so this patch cannot be upstreamed)

Maintainer: Daniel Golle <daniel@makrotopia.org> @dangowrt 
Compile tested: x86_64, 22.03.5
Run tested: x86_64, Intel N100, openwrt 22.03.5

### CODE REVIEW

**Comment by BKPepe** [comment]
This needs to be added first to OpenWrt master branch, then it could be backported to the stable branches.

**Comment by jjm2473** [comment]
@BKPepe master branch use Transmission 4.0, not affected by this.

**Comment by jjm2473** [comment]
cc @dangowrt

**Comment by jjm2473** [comment]
cc @neheb

**Pull request merged**
