### PR TITLE
treewide: add PKG_CPE_ID for cvescanner

### PR DESCRIPTION
**Pull request by ja-pa**
Maintainer: 
Compile tested: N/A
Run tested: N/A

Description:
This PR adds 27 PKG_CPE_ID and remove one duplicate PKG_CPE_ID from python-requests.
These changes don't change build packages so there is no PKG_RELEASE BUMP. 
Related to https://github.com/openwrt/packages/pull/10018 

Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>

### CODE REVIEW

**Comment by neheb** [comment]
Build failure is, boost again. This PR is fine.

**Comment by neheb** [comment]
@ja-pa will you be doing this for 19.07 and 18.06?

**Comment by neheb** [comment]
I backported this to 19.07 as well as other packages to make it easier to cherry-pick. Please review: https://github.com/neheb/packages/commits/openwrt-19.07

**Comment by poranje** [comment]
> Op 24 sep. 2019, om 13:50 heeft ja-pa <notifications@github.com> het volgende geschreven:
> 
> Maintainer:
> Compile tested: N/A
> Run tested: N/A
> 
> Description:
> This PR adds 27 PKG_CPE_ID and remove one duplicate PKG_CPE_ID from python-requests.
> These changes don't change build packages so there is no PKG_RELEASE BUMP.
> Related to #10018
> 
> Signed-off-by: Jan Pavlinec jan.pavlinec@nic.cz
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/openwrt/packages/pull/10062
> 
> Commit Summary
> 
> 	• treewide: add PKG_CPE_ID for cvescanner

A liitle OT, but LWN just ran an article "What to do about CVE numbers" that point out some problems with how CVEs are assigned and used.
Interesting reading: https://lwn.net/Articles/801157/ (for now still subscribers only).

**Pull request merged**
