### PR TITLE
subversion: update to the latest stable release

### PR DESCRIPTION
**Pull request by val-kulkov**
Maintainer: me
Compile tested: bcm53xx, Buffalo WXR-1900DHP, OpenWrt SNAPSHOT r9908-17cb490
Run tested: bcm53xx, Buffalo WXR-1900DHP, OpenWrt SNAPSHOT r9908-17cb490

Description:
Update to v1.12.0, the latest stable release.

Signed-off-by: Val Kulkov <val.kulkov@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Hmm I can't seem to review the whole Makefile directly. Anyway

libsqlite3, libapr, and zlib can be removed. They are satisfied by the others.

The URL can be switched to HTTPS.

--disable-nls can be removed as the build system passes that already: https://github.com/openwrt/openwrt/blob/master/include/package-defaults.mk#L77 (I find it interesting that it doesn't pass --enable-nls),

LARGEFILE support I assume can alternatively be passed using CONFIGURE_VARS.

Build/Compile can be simplified using

$(call Build/Compile/Default,all local-install) or MAKE_FLAGS += all local-install

**Comment by neheb** [comment]
Funny. The CPPFLAGS line in CONFIGURE_VARS is not being passed (missing \). Should be removed anyway.

**Comment by neheb** [comment]
Tested this. Build/Compile is totally wrong. The proper section is Build/Install.

This is the diff I tested locally:

```
diff --git a/net/subversion/Makefile b/net/subversion/Makefile
index 596c94c97..74134af7c 100644
--- a/net/subversion/Makefile
+++ b/net/subversion/Makefile
@@ -18,6 +18,8 @@ PKG_MAINTAINER:=Val Kulkov <val.kulkov@gmail.com>
 PKG_FIXUP:=autoreconf
 PKG_MACRO_PATHS:=build/ac-macros
 PKG_BUILD_DEPENDS:=apr-util
+PKG_BUILD_PARALLEL:=1
+PKG_INSTALL:=1
 
 include $(INCLUDE_DIR)/package.mk
 include $(INCLUDE_DIR)/nls.mk
@@ -28,9 +30,8 @@ define Package/subversion/Default
   CATEGORY:=Network
   SUBMENU:=Version Control Systems
   TITLE:=A compelling replacement for CVS
-  DEPENDS:=+zlib +libsqlite3 +PACKAGE_unixodbc:unixodbc +libapr +libaprutil +libmagic \
-  	$(ICONV_DEPENDS) $(INTL_DEPENDS)
-  URL:=http://subversion.apache.org/
+  DEPENDS:=+PACKAGE_unixodbc:unixodbc +libaprutil +libmagic $(ICONV_DEPENDS) $(INTL_DEPENDS)
+  URL:=https://subversion.apache.org/
 endef
 
 define Package/subversion/Default/description
@@ -78,8 +79,6 @@ define Package/subversion-server/conffiles
 endef
 
 TARGET_CFLAGS += $(FPIC)
-TARGET_CPPFLAGS += -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
-APU_LIBS=$(shell $(STAGING_DIR)/usr/bin/apu-1-config --link-libtool --libs)
 
 CONFIGURE_ARGS += \
 	--with-apr="$(STAGING_DIR)/usr/bin/apr-1-config" \
@@ -98,21 +97,8 @@ CONFIGURE_ARGS += \
 
 ifdef $(INTL_FULL)
 	CONFIGURE_ARGS += --enable-nls
-else
-	CONFIGURE_ARGS += --disable-nls
 endif
 
-CONFIGURE_VARS += \
-	LDFLAGS="$(TARGET_LDFLAGS) $(APU_LIBS) -lcrypt -lm \
-		-lz -lpthread $(if $(INTL_FULL),-lintl)"
-	CPPFLAGS="$(TARGET_CPPFLAGS)"
-
-define Build/Compile
-	$(MAKE) -C $(PKG_BUILD_DIR) \
-		DESTDIR="$(PKG_INSTALL_DIR)" \
-		all local-install
-endef
-
 define Package/subversion-libs/install
 	$(INSTALL_DIR) $(1)/usr/lib
 	$(CP) $(PKG_INSTALL_DIR)/usr/lib/libsvn_*.so.* $(1)/usr/lib/
```

**Comment by val-kulkov** [comment]
@neheb : applied all your suggestions except the one about disable-nls (read on, I'll explain later). It worked. I view it as an excellent result. I cannot recall all the history about APU_LIBS and the Build/Compile section now, it's been a few years APU_LIBS and apu-1-config were causing problems needing fixes. It is possible that the upstream code changed making references to APU_LIBS and apu-1-config no longer necessary.

The disable-nls switch is actually there for a reason. Subversion's automake scripts are a little too smart. They try to detect presence of libintl/libiconv files and, if those files are detected, nls is enabled regardless of what the actual values of ICONV_DEPENDS or INTL_DEPENDS are. Therefore, if you have a development system and you do some work requiring the full nls and then disable it, Subversion will not compile because it will detect presence of libintl/libiconv files and require the full nls support. Explicitly disabling nls removes this problem.

I deliberately have not squashed commits for now, awaiting for comments. Once I get positive comments from committers, I will squash both commits to prepare this PR for merging.

Last but not least: I would be happy to pass on the maintainership of this package to someone who cares. I am no longer using Subversion regularly. If someone volunteers, I would be happy to add the maintainership change to this PR or submit a new PR for that reason.

**Comment by neheb** [comment]
Hmm? --disable-nls should be passed by default when full NLS is disabled. I keep seeing configure scripts locally saying unrecognized option: --disable-nls.

**Comment by val-kulkov** [comment]
Please see my [subversion build log](https://gist.github.com/val-kulkov/ffd4d5b684589e5045283b63d93dab1b), obtained with the version of Makefile that appends "--disable-nls" to CONFIGURE_ARGS if INTL_FULL is not defined.

Although --disable-nls is passed twice in line 1473, it is passed only once in lines 21 and 141.

If --disable-nls is not appended to CONFIGURE_ARGS in Makefile, it is not passed to configure script in what are now lines 21 and 141 in [subversion build log](https://gist.github.com/val-kulkov/ffd4d5b684589e5045283b63d93dab1b).

**Comment by neheb** [comment]
Fair enough. Merging.

**Pull request merged**
