### PR TITLE
mwan3: add nping to tracking method

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: me
Compile tested: only scripts
Run tested: x86, APU3, OpenWrt master, done

Description:
Add **nping** to the usable tracking methods.

### CODE REVIEW

**Comment by feckert** [comment]
This follow up PR requested in this discussion https://github.com/openwrt/packages/issues/7526#issuecomment-444106683

**Comment by feckert** [comment]
@champtar what is wrong with this PR?

**Comment by champtar** [comment]
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Michael Stoll <michael.stoll@meadow-robotics.com>')

**Comment by feckert** [comment]
@chapter thanks for the hint

@mistoll Am i allowed to add your sign-off?

**Comment by mistoll** [comment]
You may add my sign-off.
But most of it is just copy-paste. It's also ok, if you claim it's your's.
However, be warned, I never tested that code.

**Comment by feckert** [comment]
@mistoll I have added your **Signed-off-by**.
I have also tester your code and it works for me.
thanks

**Comment by feckert** [comment]
@champer this could be merged if you have time. I have update the Sign-off-by
thanks

**Comment by champtar** [comment]
@feckert you are killing my pseudo :P

**Comment by feckert** [comment]
@champtar sorry :-)

**Pull request merged**
