### PR TITLE
micropython: update micropython and micropython-lib to v1.8.6

### PR DESCRIPTION
**Pull request by sbreuss**
Maintainer: @roger-
Compile tested: (AR7xxx/AR9xxx, carambola2, OpenWRT/LEDE master)
Run tested: (AR7xxx/AR9xxx, carambola2, OpenWRT/LEDE masters, tests done)
 
Description:
update of micropython and micropython-lib to v1.8.6 for OpenWRT/LEDE.
added patch to remove -Werror flag from the makefile due to 2 unused variables in the axtls ssl library.

### CODE REVIEW

**Comment by hnyman** [comment]
cc to maintainer: @roger-

**Comment by roger-** [comment]
Looks good to me.

**Comment by hnyman** [comment]
@sbreuss 
You need to add the "signed-off-by" line to the commit message itself.

Please amend the commit. advice can be found in  https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by sbreuss** [comment]
Thanks for the information. I just added the signed-off-by line.

**Pull request merged**
