### PR TITLE
screen: Replace patches with upstream backports

### PR DESCRIPTION
**Pull request by neheb**
Allows proper Makefile testing as well as easy removal from the next
version.

Reorganized the Makefile a bit for consistency between packages.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @champtar 
Compile tested: ramips ath79 mvebu
Run tested: GnuBee PC1, TP-Link Archer C7v2, Turris Omnia

reopened previous pull request

### CODE REVIEW

**Comment by stintel** [comment]
The Makefile reorganization should go in a separate commit.

**Comment by neheb** [comment]
@stintel I think this is what you meant. Reworded commit messages. Please review.

**Comment by neheb** [comment]
Going to merge. This has been tested on a daily basis since January. It also adds PKG_FIXUP:=autoreconf , which seems to be preferred.

**Comment by champtar** [comment]
A bit late but thanks @neheb

**Pull request merged**
