### PR TITLE
ModemManager : README.md improvement

### PR DESCRIPTION
**Pull request by jonesmz**
Maintainer: @nickberry17

Description:

Provide some additional ModemManager UCI configuration information.

### CODE REVIEW

**Comment by feckert** [comment]
Please add a Signed-off-by to your commit

**Comment by jonesmz** [comment]
No, I won't do that, unless there's a mechanism inside of the github editor to do it.

**Comment by nickberry17** [comment]
> No, I won't do that, unless there's a mechanism inside of the github editor to do it.

All commits in OpenWrt have to be signed off.  You can do this easily by running 
`git commit --amend --signoff`

**Comment by jonesmz** [comment]
OpenWRT's inability to properly use the platform that github provides is not my problem. 

The documentation improvements in this PR are trivial. But important. 

Take them or leave them.

**Comment by nickberry17** [comment]
> OpenWRT's inability to properly use the platform that github provides is not my problem.
> 
> The documentation improvements in this PR are trivial. But important.
> 
> Take them or leave them.

Okay, unfortunately we cannot accept your MR due to the missing sign off (which is also required in Linux).  For your information, Github.com is a mirror, not the true repository.  The real repo is here https://git.openwrt.org/  It would be nice if Github had this functionality in the website, but they do not and it is a problem most of us have had to confront at some stage or another.  Most of us work from local repos.

**Comment by jonesmz** [comment]
The OpenWRT wiki directs people to github when dealing with the packages repository.

Doesn't sound like a Mirror to me.

I appreciate that OpenWRT has a policy and is sticking with it, but there are several problems here.

1) You're accepting contributions, including pull requests and bugs, on Github, and have not disabled the "edit file in place" functionality that github has.
2) The "--signoff" flag has serious legal implications that are not obvious to the person using the "--signoff" flag in their commit. OpenWRT has no way to confirm that the person typing "--signoff" on the commandline actually understands what that means, *especially* since the meaning of that flag changes based on what project is being submitted to.
3) --signoff is meaningless if you have no ability to verify my actual identity. There's very little stopping me from creating a new account on github that has no relationship to my real identity, and using the --signoff flag to, in essence, lie about the authorship of the commit in the PR. By not having some form of external verification as to who I am, you're just asking for me to put additional noise into the signal, and you'll never be able to actually contact my fake identity to verify the authorship in the future. Essentially just giving the lawyers more money for no change in outcome.

I'm sure the specifics of the OpenWRT policy are not things you wish to discuss with me in this particular venue, so I'll leave the subject alone now.

You're welcome to close this PR.

I won't be adding the --signoff flag to this PR, at the very least.

**Comment by neheb** [comment]
@jonesmz This is not a mirror. git.openwrt.org is the mirror.

The signoff stuff is quite silly, I agree. Unfortunately, that's how the powers that be have set it up.

As far as legal questions go, that's the tip of the iceberg. There are also questions regarding patented stuff. faad2 for example, is not legal in any way to distribute. Yet it's not covered by the BUILD_PATENTED flag. I don't think a lawyer has done a review of OpenWrt.

**Comment by nickberry17** [comment]
> @jonesmz This is not a mirror. git.openwrt.org is the mirror.

News to me, when did that change?  https://openwrt.org/docs/guide-developer/working-with-github-pr still says it's a mirror.

**Comment by jonesmz** [comment]
@nickberry17

That screenshot if from https://github.com/openwrt/openwrt

This is https://github.com/openwrt/packages

**Comment by nickberry17** [comment]
> @nickberry17
> 
> That screenshot if from https://github.com/openwrt/openwrt
> 
> This is https://github.com/openwrt/packages

Touché, but you will note that it's in Contributing.md that work be signed off https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by nickberry17** [comment]
> Further, https://openwrt.org/submitting-patches#sign_your_work should be amended to discourage the use of tools that make complying with the "signoff" policy difficult or cumbersome, such as the github edit-in-place functionality.

But to be fair, if you followed the instructions you would have a local copy on your computer thus signing your work by running those commands would already be part of the process.

**Comment by jonesmz** [comment]
> But to be fair, if you followed the instructions you would have a local copy on your computer thus signing your work by running those commands would already be part of the process.

When does anyone actually ever follow instructions?

It's a 10+ page essay essentially saying "Do development things". Why would I read that? I've been writing software for ages.

Then, I submit a trivial documentation improvement, and come to find out that I should have read it *NOT* because it contained actually important things to me, as a developer, but because it contained special requirements that *only* the OpenWRT project actually cares about.

Since I don't care about following the OpenWRT way of doing things, OpenWRT has now officially made the barrier to entry so high that I'm not going to create new PRs until the burden of carrying patches on my own fork of the repo becomes high enough to justify doing all of the special one-off requirements that OpenWRT has.

Developers love to write out rules and requirements (I mean, it is our job, after all).

But you're missing the human factor, which says "Any rule you write will be ignored".

Instead of having a legally (very) questionable policy like "--signoff" (at least in the form it currently exists), that is contrary to your tooling / infrastructure being very eager to ignore the policy, you could instead adapt the tooling to embrace the policy, and adopt policies that actually solve the problems you're trying to solve. (E.g., the OpenWRT project being GPL has nothing to do with the legal attestation of who wrote what code).

Anyway, like I said before, this isn't really the place to discuss the policy.

If you're not going to merge this PR without me doing silly, and legally questionable, things, then please close it.

So long as filing bug reports doesn't require a "--signoff" I imagine I'll continue creating them when appropriate. But don't expect (nor ask for) PRs from me at this time.

**Comment by neheb** [comment]
Closed on request.

**Pull request closed without merging**
