### PR TITLE
yggdrasil: bump to 0.5.5

### PR DESCRIPTION
**Pull request by dalfos**
Maintainer: @wfleurant 
Compile tested: ARMv7, ZyXEL NBG6817, master branch
Run tested: ARMv7, ZyXEL NBG6817, 23.05.2

### CODE REVIEW

**Comment by wfleurant** [comment]
thanks for testing. everyone is waiting for the latest fixes thanks again.

**Comment by wfleurant** [comment]
ping?

**Comment by dalfos** [comment]
Is there anything required from me?

**Comment by wfleurant** [comment]
may be force push an empty commit to retrig the build

**Pull request merged**
