### PR TITLE
[URFC] net/ddns-scripts: Use capabilties to de-duplicate and handle wget-nossl

### PR DESCRIPTION
**Pull request by dfc-d**
This is an Untested Request for Comments.

I've reworked the way do_transfer determines what functionality to use,
when using wget or uclient-fetch (as wget).

ddns-scripts was determining capabilities via the name of the binary
used to do http(s) based on specific binary names which breaks if
PR https://github.com/openwrt/packages/pull/2729 is accepted, which
is advisable for both issue https://github.com/openwrt/packages/issues/2728
and for avoiding hardcoding the preferences for which wget to use
into ddns-scripts (this really should be a user choice, and
in openwrt/lede the way this is done is that openwrt/lede binaries
are later in the search path than full versions (e.g. the wget
symlink to uclient-fetch is /bin/wget but wget-ssl and wget-nossl
use /usr/bin/wget).

The change honours user preference for wget, while at the same
time allowing wget-ssl and wget-nossl to move to installing
as /usr/bin/wget (and therefore properly conflicting) instead
of symlink hackery that trunk devs don't like (and misses
causing wget-ssl and wget-nossl to conflict).

Signed-off-by: Daniel Dickinson <lede@daniel.thecshore.com>

### CODE REVIEW

**Comment by dfc-d** [comment]
I've simplified the check for libustream-polarssl and thus determining uclient-fetch's capabilities.

**Comment by dfc-d** [comment]
I've streamlined the detection of which wget is in use and thus figuring out the capabilities.

**Comment by dfc-d** [comment]
I've also taken the opinion that the uclient-fetch ustream-ssl will probably get fixed soon enough hardcoding checks for ustream-polarssl is probably the wrong way to go.

**Comment by hnyman** [comment]
@chris5560

**Comment by chris5560** [comment]
As stated, I see no need for #2729 discussion.
For the offered optimisations I have to look at but I'm currently very short on time.

**Comment by dfc-d** [comment]
I've updated the patch to avoid using opkg to figure out what is wget, but for GNU wget, use wget -V to figure out if the ssl vs non-ssl version. This patch doesn't actually depend on openwrt/packages#2739 and work with or without it.

**Comment by chris5560** [comment]
I still see no reason why to merge the check of various separate file transfer programs into one check for a "wget" command.

**Comment by dfc-d** [comment]
1) It honours the users choice of what to use as wget
2) It avoids hardcoding a specific order of what gets preferred
3) If fixes an outstanding issue with current wget package
4) It reduces duplication in ddns-scripts as capabilities are used based on the presence of capabilities rather than if/then blocks per executable
5) See the note in https://github.com/openwrt/packages/pull/2740 for why the symlink thing matters for wget (will attach the same explanation to wget ticket later).

**Comment by dfc-d** [comment]
Updated to avoid the question of wget binaries as it turns out not the be the core issue; however this PR is still useful for
a) de-duplicating code paths
b) handling the wget-nossl case

**Comment by dfc-d** [comment]
@chris5560 - are you happier with this (once I test and debug)?

**Comment by dfc-d** [comment]
I have some fixes, and then it should be good for other's to try out.

**Comment by dfc-d** [comment]
I tested the patch in the form it is now, except that ddns-scripts has been updated since I created the patch so I've had to rebase the patch and must therefore retest.  However the new way of checking for the executable to use and getting the capabilities has been verified in the uclient-fetch fetch case; GNU wget still needs to be tested. (I've successfully used uclient fetch with mbedtls for https).

**Comment by dfc-d** [comment]
This has been handled another way to my understanding; see no reason to worry about it now.

**Pull request closed without merging**
