### PR TITLE
libtins: Update to 4.0

### PR DESCRIPTION
**Pull request by neheb**
Switched to codeload. Simpler.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @StevenHessing 
Compile tested: ipq806x

### CODE REVIEW

**Comment by StevenHessing** [comment]
Getting compilation errors with libtins-4.0, needs investigation

**Comment by neheb** [comment]
It's working on ar71xx and ipq806x for me. Any platform it's failing on?

**Comment by neheb** [comment]
I just looked through the Makefile. InstallDev is missing.

Why is the versioned file the one installed? Replacing it with the non-versioned one on that line copies the file and not the symlink. I've force-pushed a new commit.

**Comment by cshoredaniel** [comment]
Please note that project stance on codeload is under review: https://github.com/openwrt/packages/issues/6748

**Comment by neheb** [comment]
Rebased

**Comment by hnyman** [comment]
no reaction from the maintainer for months, and Travis & circleci seem happy, so let's try it.

**Pull request merged**
