### PR TITLE
prometheus-node-exporter-lua: use the new ubus dsl metrics

### PR DESCRIPTION
**Pull request by dhewg**
This is significantly faster.

This is the package feed part of: http://patchwork.ozlabs.org/project/openwrt/list/?series=220557
That needs to be merged first before this can go in

### CODE REVIEW

**Comment by neheb** [comment]
hehehe. Please rebase to current master.

**Comment by champtar** [comment]
need to bump version in Makefile

**Comment by dhewg** [comment]
Done, thanks (why do I keep forgetting that...)

**Comment by hauke** [comment]
Thank you for the work, the related changes in the main repository were also merged.

**Pull request merged**
