### PR TITLE
miniupnpd: convert to procd

### PR DESCRIPTION
**Pull request by neheb**
Massive cleanup of the shell script. Many issues were fixed.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody

### CODE REVIEW

**Comment by neheb** [comment]
Initial results is poor:

```
Fri Feb  7 16:15:36 2020 daemon.err miniupnpd[2479]: could not open lease file: /var/run/miniupnpd.leases
Fri Feb  7 16:15:36 2020 daemon.warn miniupnpd[2479]: Cannot get IP address for ext interface . Network is down
Fri Feb  7 16:15:36 2020 daemon.notice miniupnpd[2479]: HTTP listening on port 5000
Fri Feb  7 16:15:36 2020 daemon.notice miniupnpd[2479]: HTTP IPv6 address given to control points : [fd9f:300d:aab8::1]
Fri Feb  7 16:15:36 2020 daemon.notice miniupnpd[2479]: Listening for NAT-PMP/PCP traffic on port 5351
Fri Feb  7 16:15:36 2020 daemon.notice procd: /etc/rc.d/S94miniupnpd: allow 1024-65535 0.0.0.0/0 1024-65535 #Allow high ports
Fri Feb  7 16:15:36 2020 daemon.notice procd: /etc/rc.d/S94miniupnpd: deny 0-65535 0.0.0.0/0 0-65535 #Default deny
Fri Feb  7 16:15:36 2020 daemon.err miniupnpd[2538]: MiniUPnPd is already running. EXITING
```

It's not working on initial boot as something else launches it. Maybe the hotplug script.

Anyway, after killing this non-procd process and launching it from /etc/init.d/miniupnpd , it works perfectly fine. There seem to be minor issues:

```
root@OpenWrt~# /etc/init.d/miniupnpd start
allow 1024-65535 0.0.0.0/0 1024-65535 #Allow high ports
deny 0-65535 0.0.0.0/0 0-65535 #Default deny
```

Those are not being printed to the file.

**Comment by neheb** [comment]
lease file and those allow/deny ports entries were fixed.

It seems I was partially wrong about the hotplug. /etc/init.d/miniupnp stop is not working at all. I have no idea why.

Help would be appreciated.

**Comment by neheb** [comment]
Ah never mind. It's daemonizing. I forgot to add -d.

**Comment by neheb** [comment]
Seems I had to patch out the daemonize function. The -d parameter does not work like I want it to.

**Comment by jow-** [comment]
Miniupnpd is supposed to be started by interface hotplug on boot

**Comment by neheb** [comment]
One issue with that is that it starts too early. I increased the number from 50 to 94 to work around that.

**Comment by neheb** [comment]
This is what I mean:

```
Sat Feb  8 19:23:13 2020 daemon.warn miniupnpd[2009]: Cannot get IP address for ext interface . Network is down
Sat Feb  8 19:23:13 2020 daemon.notice miniupnpd[2009]: HTTP listening on port 5000
Sat Feb  8 19:23:13 2020 daemon.notice miniupnpd[2009]: HTTP IPv6 address given to control points : [fd9f:300d:aab8::1]
Sat Feb  8 19:23:13 2020 daemon.notice miniupnpd[2009]: Listening for NAT-PMP/PCP traffic on port 5351
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: PCPSendUnsolicitedAnnounce() IPv6 sendto(): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: sendto(udp_notify=8, [fd9f:300d:aab8::1]): Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=490, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=486, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=472, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=458, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=478, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=482, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=410, dest=[ff0e::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=490, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=486, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=472, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=458, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=478, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=482, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=410, dest=[ff05::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=490, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=486, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=472, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=458, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=478, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=482, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto(sock=8, len=410, dest=[ff02::c]:1900): sendto: Address not available
Sat Feb  8 19:23:13 2020 daemon.err miniupnpd[2009]: try_sendto failed to send 39 packets
```

**Comment by neheb** [comment]
Seems I subtly broke the hotplug script. Fixed now.

**Comment by neheb** [comment]
@jow- seems I broke it again.

What does service -C do?

**Comment by MoKi3** [comment]
@neheb I've tested on 19.07.1 with the miniupnpd_2.1.20191006-2_mipsel_24kc.ipk which built after curent PR #11275 megred. I'm disable the IPv6 on my openwrt router  and  on window 10 (Build 18363) also disable the IPv6. The miniupnpd seems wrok well. But when I came to the log I found out this.
```
Sun Mar  1 12:37:52 2020 user.notice upnp daemon: external interface not found, not starting
Sun Mar  1 12:37:52 2020 daemon.warn miniupnpd[1491]: Cannot get IP address for ext interface . Network is down
Sun Mar  1 12:37:52 2020 daemon.notice miniupnpd[1491]: HTTP listening on port 5000
Sun Mar  1 12:37:52 2020 daemon.warn miniupnpd[1491]: no HTTP IPv6 address, disabling IPv6
Sun Mar  1 12:37:52 2020 daemon.notice miniupnpd[1491]: Listening for NAT-PMP/PCP traffic on port 5351
Sun Mar  1 12:37:52 2020 daemon.err miniupnpd[1491]: PCPSendUnsolicitedAnnounce() IPv6 sendto(): Bad file descriptor
Sun Mar  1 12:37:52 2020 daemon.info procd: - init complete -
Sun Mar  1 12:37:54 2020 daemon.info pppd[1104]: Remote message: 0;User(********) Authenticate OK, Request Accept by sxkd
Sun Mar  1 12:37:54 2020 daemon.notice pppd[1104]: PAP authentication succeeded
Sun Mar  1 12:37:54 2020 daemon.notice pppd[1104]: peer from calling number *:*:*:*:*:* authorized
Sun Mar  1 12:37:54 2020 daemon.notice pppd[1104]: local  IP address *.*.*.*
Sun Mar  1 12:37:54 2020 daemon.notice pppd[1104]: remote IP address *.*.*.*
Sun Mar  1 12:37:54 2020 daemon.notice pppd[1104]: primary   DNS address 8.8.8.8
Sun Mar  1 12:37:54 2020 daemon.notice pppd[1104]: secondary DNS address 8.8.4.4
Sun Mar  1 12:37:54 2020 daemon.notice netifd: Network device 'pppoe-wan' link is up
Sun Mar  1 12:37:54 2020 daemon.notice netifd: Interface 'wan' is now up
Sun Mar  1 12:37:54 2020 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
```
It seems the pppd inited after the miniupnpd , I increased the number from 94 to 99 but couldn't help.

I can't tell this will effect the upnp function or not , nothing went wrong except those logs . Here goes some other info.
```
root@owrt:~# cat /etc/config/upnpd
config upnpd 'config'
	option enabled '1'
	option enable_natpmp '1'
	option enable_upnp '1'
	option secure_mode '1'
	option log_output '0'
	option download '1024'
	option upload '512'
	option internal_iface 'lan'
        option external_iface 'wan'
	option port '5000'
	option upnp_lease_file '/var/run/miniupnpd.leases'
	option igdv1 '0'
	option uuid '9e3085aa-8326-4698-bf64-c672a967e411'

config perm_rule
	option action 'allow'
	option ext_ports '1024-65535'
	option int_addr '0.0.0.0/0'
	option int_ports '1024-65535'
	option comment 'Allow high ports'

config perm_rule
	option action 'deny'
	option ext_ports '0-65535'
	option int_addr '0.0.0.0/0'
	option int_ports '0-65535'
	option comment 'Default deny'
```
```
root@owrt:~# netstat -nap | grep miniupn
tcp        0      0 :::5000                 :::*                    LISTEN      1491/miniupnpd
udp        0      0 192.168.6.1:47718       0.0.0.0:*                           1491/miniupnpd
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           1491/miniupnpd
udp        0      0 192.168.6.1:5351        0.0.0.0:*                           1491/miniupnpd
unix  2      [ ]         DGRAM                       709 1491/miniupnpd 
```
Thanks for your work.

**Comment by neheb** [comment]
miniupnpd gets started not by the init script but by hotplug.

**Comment by techzilla** [comment]
Mine shows the lease, and a firewall rule in iptables, but still doesn't actually open the port.

**Pull request merged**
