### PR TITLE
wget: update to 1.19.1

### PR DESCRIPTION
**Pull request by hnyman**
Update wget to 1.19.1

changelog in http://git.savannah.gnu.org/cgit/wget.git/tree/NEWS?h=v1.19.1&id=6620c5156f363036079d413bfa567e9d871bb30d 

Maintainer: @mstorchak 
Compile and run tested: ar71xx, LEDE r4832-ae57675bba

### CODE REVIEW

**Comment by mstorchak** [comment]
Ack.
Thank you @hnyman

**Comment by hnyman** [comment]
Looks like wget now looks for libunistring, which causes buildbot to fail:
```
Package wget-nossl is missing dependencies for the following libraries:
libunistring.so.2
```
I will look into it.

**Comment by hnyman** [comment]
Well, most likely an over-eager configure.ac script that finds libunistring and tries to use it. Log first says that it is not requested, but then says that as libunistring is found, let's link with it...
```
checking whether included libunistring is requested... no
checking for libunistring... yes
checking how to link with libunistring... /var/lib/buildbot/slaves/slave-lede-builds4/mips_24kc/build/sdk/staging_dir/target-mips_24kc_musl/usr/lib/libunistring.so
checking for libunistring version... 0.9.6
```
In my own build it is only suggested to be installed:
```
checking whether included libunistring is requested... no
checking for libunistring... no, consider installing GNU libunistring
```

The surfacing error is likely due to several commits:
* first libidn was bumped up to libidn2 and a check for libunistring was included in http://git.savannah.gnu.org/cgit/wget.git/commit/?id=00ae9b4ee2caa6640776e9777e7ef5a374d082c0 and it was added as optional for bootstrap. We have explicitly disabled IRI, so the modules should likely stay unused.
* then later the check for needing libunistring was removed with http://git.savannah.gnu.org/cgit/wget.git/commit/?id=990f3d67d340d226bbd4187f5d310a4d2bf2bfe4 as apparently some other function may need it.

Libunistring would be 550 kB addition, so that sounds like a no-go for me.

I think that the straightforward way would be to somehow diasble libunistring linkage.

But I am not quite sure if the best way is to 
* revert that removal of the IRI-setting based clearing of libunistring option, or 
* also remove the "libunistring-optional" from bootstrap.conf that was added by the libidn2 bump

**Comment by hnyman** [comment]
Reverting the one upstream patch did not work. Buildbot fails, but in a different way. 

I will likely revert the version bump later today to fix buildbot, and then try to find ways to avoid libunistring linkage.

**Pull request merged**
