### PR TITLE
perl: update to 5.28

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me / @Naoir
Compile: x86_64, generic, HEAD (5f5d812)
Run tested: same, built and installed on production router, ran sanity tests

Also re-ran `/etc/firewall.user` after rerunning `xt_geoip_dl` and `xt_geoip_build *.csv`, which uses `perl` and `perl-text-csv_xs`.

No anomalies observed.

Description:

*Note*: this fixes _CVE-2018-12015_ which exists up through 5.26.2.

### CODE REVIEW

**Comment by pprindeville** [comment]
Including the patch from Tony Cook from here:

https://rt.perl.org/Ticket/Display.html?id=133411

**Comment by pprindeville** [comment]
@sdwalker @diizzyy Any comments?

**Comment by pprindeville** [comment]
If there are no objects, I'll merge at COB Wednesday.

**Comment by diizzyy** [comment]
LGTM

**Comment by pprindeville** [comment]
Okay, merging now.

**Pull request merged**
