### PR TITLE
dnsdist: Enable custom load-balancing policies in the light version

### PR DESCRIPTION
**Pull request by rgacogne**
Maintainer: me
Compile tested: CI
Run tested: x86_64 docker

Description:
Fixes https://github.com/openwrt/packages/issues/22994

### CODE REVIEW

**Comment by neheb** [comment]
@Habbie is the maintainer, no?

**Comment by Habbie** [comment]
You can treat @rgacogne as maintainer too, and not wait for my review. I'll hit approve on this one though, just to be clear.

Is there a syntax for multiple maintainers in the Makefile?

**Review by Habbie — APPROVED** [review]

**Comment by Habbie** [comment]
> Is there a syntax for multiple maintainers in the Makefile?

ah, I see

```
utils/swig/Makefile:PKG_MAINTAINER:=John Crispin <blogic@openwrt.org>, Hirokazu MORIKAWA <morikw2@gmail.com>
```

etc.

**Comment by killgufo** [comment]
Running the package as built from the pipeline for mips_24kc allowed to set the policy to fix the problem described in https://github.com/openwrt/packages/issues/22994 

I'll wait to test the same as built in https://github.com/openwrt/packages/pull/23006 to be sure as I'm running 23.05 and the package I'm testing now is built for master.

**Comment by BKPepe** [comment]
This was merged, so fast @neheb. We do need commit description. Why it needs to be enabled, noone wants to go through multiple issues, pull requests to find out the answer. Also, I am curious about the size difference - when it is enabled or disabled.

**Comment by killgufo** [comment]
The IPK sizes (comparing master patched with https://github.com/openwrt/packages/pull/23001 and 22.05 as is)
631920 bytes  for dnsdist_1.8.**3-2**_mips_24kc.ipk in master with load balancing policies and newer release
610644 bytes for dnsdist_1.8.**2-1**_mipsel_24kc.ipk in 22.05 without load balancing policies

**Pull request merged**
