### PR TITLE
libimobiledevice, usbmuxd, libplist, libusbmuxd: move to github

### PR DESCRIPTION
**Pull request by lukbaj**
This libraries and util are necessary to connect and use Apple devices with OpenWrt software.

### CODE REVIEW

**Comment by qianguozheng** [comment]
@lukbaj  Hi, I use these libraries and the utils to connect with Apple device, but I found that the usbmuxd latest version , would consume whole CPU(100%) resource at the meantime(when connect Apple Device and push Trust Button), do you have any idea about that ? or will you help me check out what happened ? thanks

**Comment by lukbaj** [comment]
I think this 100% CPU usage is only when you connect Apple device for the first time, right? It is because there is a lot of stuff going on like authentication key generation (this is going on when you press "Trust" button). When it's successful then you shouldn't be asked to click "Trust" when you connect the same device again and of course there should be no 100% CPU usage.

**Comment by qianguozheng** [comment]
@lukbaj  Yes, what you said about the first time is absolutely right, and if it generates the UDID.plist in /var/lib/lockdown folder, if this file exist it would not ask you to "Trust" again.
So, if I want to speed up the Trust process, I must add other coprocessor ? or do you have any other choice ? I am using MT7610A SoC, and the Trust process cost me about 15 seconds and more, I want to eliminate the time to the least.

**Comment by lukbaj** [comment]
Only faster CPU will decrease this time. How much? I don't know, I', not author of this libraries. Certificate generation is run in single process/thread, so CPU speed does matter. You can try to see how long does it take for example with you PC/computer which has for sure much faster CPU.

**Comment by qianguozheng** [comment]
@lukbaj  Thanks very much, I've found the way to decrease the CPU consumption, and it currently works fine.

**Comment by acalatrava** [comment]
I know this thread is old but would you please explain how did you decreased the CPU consumption?

**Comment by qianguozheng** [comment]
@acalatrava  It's very easy, using static key not dynamic during communicating with iOS devices.

**Pull request merged**
