### PR TITLE
frp: add new package

### PR DESCRIPTION
**Pull request by ysc3839**
Signed-off-by: Richard Yu <yurichard3839@gmail.com>

Maintainer: me
Compile tested: x86-64, sunxi-cortexa7, mt7621, snapshot
Run tested: x86-64

Description:
frp is a fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.
https://github.com/fatedier/frp

### CODE REVIEW

**Comment by ysc3839** [comment]
@neheb It seems that this is a mistake?
https://github.com/openwrt/packages/blob/205df2eb36971840849254816a602fa726faee7d/net/geth/Makefile#L38

**Comment by neheb** [comment]
No idea. ping @jefferyto

**Comment by ysc3839** [comment]
Changed `INSTALL_CONF` to `INSTALL_DATA` because INSTALL_CONF sets permission to 600 which makes daemon run as `nobody` failed to read config file.

**Comment by jefferyto** [comment]
That does look like a mistake (I think because there use to be source packages, those has `PKGARCH:=all`).

**Comment by ysc3839** [comment]
@neheb 
Any update? Frp does not have any self test. I just install the server on my VPS and did not find any bug. Previously I'm using binaries in [releases](https://github.com/fatedier/frp/releases).
uci and luci integration is not implemented yet. And I will add soon.

**Comment by neheb** [comment]
I see no problem here.

**Comment by dengqf6** [comment]
Because it is a proxy, please add `SUBMENU:=Web Servers/Proxies` to `Package/frp/template` section.

**Comment by funnypro** [comment]
99太靠后了

**Pull request merged**
