### PR TITLE
aria2: Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @kuoruan 
Compile tested: ar71xx

### CODE REVIEW

**Comment by kuoruan** [comment]
Could you please give more information about this pr?

**Comment by neheb** [comment]
Sure.

OpenSSL 1.1.1 support is expected to be merged soon. OpenSSL has a compile-time setting to enable deprecated APIs that is enabled by default. Disabling it reduces the size of openssl in exchange for breaking compilation of some packages including aria2.

As far as the code is concerned, initialization in OpenSSL is deprecated and should not be done. Those functions are defined away in 1.1.

**Comment by kuoruan** [comment]
OK, find it. aria2/aria2#1315

But why you delete this line:

```
#ifdef HAVE_OPENSSL
```
In my opinion, OpenSSL is a optional dependency to aria2. We need to keep this line to check if user compile with OpenSSL.

**Comment by neheb** [comment]
Updated this as well as upstream pull request.

**Pull request merged**
