### PR TITLE
snort3: complete rework

### PR DESCRIPTION
**Pull request by efahl**
- Add many options to config file.
  - Move rules and generated snort.lua to /tmp.
  - Add script for downloading rules.
  - Add preliminary reporting capabilites.

Maintainer: @flyn-org
Compile tested: None needed
Run tested: x86/64

Description:

Major updates to configuration and tools for snort3.

### CODE REVIEW

**Comment by graysky2** [comment]
@flyn-org is the maintainer, I am not.

**Comment by neheb** [comment]
needs a PKG_RELEASE bump.

**Comment by neheb** [comment]
```
git fetch origin
git rebase origin/master
```

**Comment by graysky2** [comment]
I am not an expert, maybe someone else can help.

**Comment by efahl** [comment]
Redid with

git fetch origin
git rebase -i origin/master
... edit 'drop' on those two commits ...
git push -f

Looks like it's ok now?

**Comment by flyn-org** [comment]
Looks good. Recommend merge.

**Pull request merged**
