### PR TITLE
dosfstools: bump to new upstream version 3.0.27

### PR DESCRIPTION
**Pull request by zxdavb**
Bump to v3.0.27 & add ICONV support
 - move over from oldpackages
 - with thanks to Dirk Neukirchen

Signed-off-by: David Bonnes <david.bonnes@gmail.com>

### CODE REVIEW

**Comment by thess** [comment]
@zxdavb - please squash/rebase this PR to a single commit and remove the extraneous merge info.

**Comment by zxdavb** [comment]
I am sorry, I am new to GIT, I hope I did it right?

**Comment by zxdavb** [comment]
Is that OK?

**Comment by thess** [comment]
Looks good -- Since this is a new package, I'm going to test it before merge.

**Comment by thess** [comment]
Just curious - what is the purpose of dosfsck.sh (installed to /lib/functions/fsck) and why is not executable (INSTALL_DATA vs INSTALL_BIN)? Nothing seems to reference it.

**Comment by zxdavb** [comment]
@thess from the wiki: "The function libmount_fsck is called with the device, fstype, and boolean fsck_enabled as parameters. If fsck is enabled and fstype is one of the known types, and the filesystem is not already mounted, or a swap, then the function will attempt to call fsck_{fstype} $device"

That is, when (say): fstab.@mount[0].enabled_fsck=1, then fsck should be run automatically if the dirty bit is set, and before the volume is mounted (this feature definitely worked in AA)

However, this feature doesn't seem to be working (for dos volumes at least) in CC, and I was always planning to address that issue, once I got dosfstools ported over from oldpackages.

I don't know why not INSTALL_BIN, but it is INSTALL_DATA in the e2fsprogs Makefile as well...

**Pull request merged**
