### PR TITLE
treewide: add missing mirror hash

### PR DESCRIPTION
**Pull request by yousong**
They are missed out from the FIXUP check probably because of a flaw in
the fixup-makefile.pl script

Signed-off-by: Yousong Zhou <yszhou4tech@gmail.com>

### CODE REVIEW

**Comment by yousong** [comment]
Hello @heil , I re-organized the nginx Makefile a bit to allow the build system to add or fix mirror hash for nginx modules.  Please have a look.  Thank you.

**Comment by yousong** [comment]
v3 <- v2

 - libsoc: fix compilation error caused by multiple goals on make.   @yegorich , please have a look at this one, thank you.

**Comment by yegorich** [comment]
@yousong I'm OK with this change for `libsoc`.

**Comment by Ansuel** [comment]
ok  for uwsgi

**Comment by Ansuel** [comment]
(if this #6328  gets merged i think you will need to rebase)

**Pull request merged**
