### PR TITLE
[RFCv2] exfat-nofuse: fix compile error on kernel 4.18+

### PR DESCRIPTION
**Pull request by dengqf6**
Switched to https://github.com/coolshou/exfat

Maintainer: @yousong 
Compile tested: mvebu 4.19.12, ramips 4.14.90
Run tested: mvebu 4.19.12

### CODE REVIEW

**Comment by diizzyy** [comment]
@dengqf6 
Instead of switching to random forks perhaps we should bite the bullet and import sdfat instead? Feel free to use my PR if you want however I couldn't figure out how to pass kernel symbols and how to make block-mount happy.

**Comment by dengqf6** [comment]
@diizzyy @cryptomilk
Only if you solve these errors on 4.19
```make[3]: Entering directory '/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-mvebu_cortexa9/linux-4.19.13'
  CC [M]  /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.o
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function '__sdfat_revalidate_common':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:1178:19: error: invalid operands to binary != (have 'long unsigned int' and 'atomic64_t {aka struct <anonymous>}')
   (dentry->d_time != dentry->d_parent->d_inode->i_version))) {
    ~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function '__sdfat_create':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2330:16: error: wrong type argument to increment
  dir->i_version++;
                ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2343:18: error: wrong type argument to increment
  inode->i_version++;
                  ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function '__sdfat_lookup':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2460:17: error: incompatible types when assigning to type 'long unsigned int' from type 'atomic64_t {aka struct <anonymous>}'
  dentry->d_time = dir->i_version;
                 ^
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_unlink':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2494:16: error: wrong type argument to increment
  dir->i_version++;
                ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2504:17: error: incompatible types when assigning to type 'long unsigned int' from type 'atomic64_t {aka struct <anonymous>}'
  dentry->d_time = dir->i_version;
                 ^
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_symlink':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2543:16: error: wrong type argument to increment
  dir->i_version++;
                ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2556:18: error: wrong type argument to increment
  inode->i_version++;
                  ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function '__sdfat_mkdir':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2594:16: error: wrong type argument to increment
  dir->i_version++;
                ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2608:18: error: wrong type argument to increment
  inode->i_version++;
                  ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_rmdir':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2642:16: error: wrong type argument to increment
  dir->i_version++;
                ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2653:17: error: incompatible types when assigning to type 'long unsigned int' from type 'atomic64_t {aka struct <anonymous>}'
  dentry->d_time = dir->i_version;
                 ^
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function '__sdfat_rename':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2687:20: error: wrong type argument to increment
  new_dir->i_version++;
                    ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:2708:20: error: wrong type argument to increment
  old_dir->i_version++;
                    ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_fill_inode':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3830:18: error: wrong type argument to increment
  inode->i_version++;
                  ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3885:27: error: passing argument 2 of 'sdfat_time_fat2unix' from incompatible pointer type [-Werror=incompatible-pointer-types]
  sdfat_time_fat2unix(sbi, &inode->i_mtime, &info.ModifyTimestamp);
                           ^
In file included from /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:65:0:
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.h:366:13: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 extern void sdfat_time_fat2unix(struct sdfat_sb_info *sbi, struct timespec *ts,
             ^~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3886:27: error: passing argument 2 of 'sdfat_time_fat2unix' from incompatible pointer type [-Werror=incompatible-pointer-types]
  sdfat_time_fat2unix(sbi, &inode->i_ctime, &info.CreateTimestamp);
                           ^
In file included from /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:65:0:
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.h:366:13: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 extern void sdfat_time_fat2unix(struct sdfat_sb_info *sbi, struct timespec *ts,
             ^~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3887:27: error: passing argument 2 of 'sdfat_time_fat2unix' from incompatible pointer type [-Werror=incompatible-pointer-types]
  sdfat_time_fat2unix(sbi, &inode->i_atime, &info.AccessTimestamp);
                           ^
In file included from /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:65:0:
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.h:366:13: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 extern void sdfat_time_fat2unix(struct sdfat_sb_info *sbi, struct timespec *ts,
             ^~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_build_inode':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3908:19: error: incompatible types when assigning to type 'atomic64_t {aka struct <anonymous>}' from type 'int'
  inode->i_version = 1;
                   ^
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function '__sdfat_write_inode':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3956:27: error: passing argument 2 of 'sdfat_time_unix2fat' from incompatible pointer type [-Werror=incompatible-pointer-types]
  sdfat_time_unix2fat(sbi, &inode->i_mtime, &info.ModifyTimestamp);
                           ^
In file included from /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:65:0:
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.h:368:13: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 extern void sdfat_time_unix2fat(struct sdfat_sb_info *sbi, struct timespec *ts,
             ^~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3957:27: error: passing argument 2 of 'sdfat_time_unix2fat' from incompatible pointer type [-Werror=incompatible-pointer-types]
  sdfat_time_unix2fat(sbi, &inode->i_ctime, &info.CreateTimestamp);
                           ^
In file included from /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:65:0:
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.h:368:13: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 extern void sdfat_time_unix2fat(struct sdfat_sb_info *sbi, struct timespec *ts,
             ^~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:3958:27: error: passing argument 2 of 'sdfat_time_unix2fat' from incompatible pointer type [-Werror=incompatible-pointer-types]
  sdfat_time_unix2fat(sbi, &inode->i_atime, &info.AccessTimestamp);
                           ^
In file included from /hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:65:0:
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.h:368:13: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 extern void sdfat_time_unix2fat(struct sdfat_sb_info *sbi, struct timespec *ts,
             ^~~~~~~~~~~~~~~~~~~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_read_root':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:4751:18: error: wrong type argument to increment
  inode->i_version++;
                  ^~
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c: In function 'sdfat_fill_super':
/hdd/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/kernel-sdfat-daca7c28f28dbe9bf1791ae883dfc83d38ac4e8a/sdfat.c:4875:24: error: incompatible types when assigning to type 'atomic64_t {aka struct <anonymous>}' from type 'int'
  root_inode->i_version = 1;
                        ^
cc1: some warnings being treated as errors
```

**Comment by yousong** [comment]
Sorry, switching to yet another random fork is not an option.  If the upstream project is not maintained, and not working anymore for newer kernels, the less hairy option would be just to mark it broken then drop support for it.

**Comment by dengqf6** [comment]
@yousong @cshoredaniel 
So you think the only proper way to solve this is not to switch to any source but include a patch like [Arch Linux already did](https://aur.archlinux.org/cgit/aur.git/tree/4.18.patch?h=exfat-dkms-git)?

**Comment by diizzyy** [comment]
@cshoredaniel 
That's just a silly argument, should we also drop widely adopted formats such as AAC because of this reason? Also, feel free to suggest another multiplatform file system without the limitations of FAT32. NTFS is by far less suitable than exFAT for multiple reasons.

**Comment by cshoredaniel** [comment]
What I meant is that it's not worth the effort -- the patented is just another problem, now the main one, but it limits its utility sufficiently that the degree of effort required isn't justified IMO.  Of course if someone actually cares enough to do the work, that's up to them.

**Comment by cshoredaniel** [comment]
*now=not

**Comment by cryptomilk** [comment]
FYI: https://github.com/cryptomilk/kernel-sdfat/pull/13

**Comment by cshoredaniel** [comment]
Hey looks like there might be a better solution -- thanks @cryptomilk

**Comment by yousong** [comment]
@dengqf6 , I just added two patches in commit 5cb4bc686c5c4af84dbd2b29a1ac1afe16f3691b, simple tests indicated that it worked on qemu malta/be with kernel 4.19.9.  Please test and open a new issue if it does not work for you.  Thank you.

**Comment by dengqf6** [comment]
Looks fine. Thanks.

**Comment by cshoredaniel** [comment]
I guess it wasn't as much of an issue as I thought.  Great work!

**Pull request closed without merging**
