### PR TITLE
treewide: use new extra_command function for init

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: The follwing maintainer should get pinged to verify the changes I have made to call the new extra_command function.

- [ ] @Shulyaka for postfix
- [x] @dibdot for adblock
- [ ] @liudf0716 apfree-wifidog
- [x] @dibdot banip
- [ ] @dangowrt gnunet
- [x] @gladiac1337 haproxy
- [x] @Ansuel nginx
- [x] @yousong openvswitch
- [ ] @chris5560 radicale
- [x] @jefferyto seafile-server
- [x] @stangri simple-adblock
- [ ] @mstorchak tgt
- [x] @zioproto tinc
- [x] @dibdot tavelmate
- [x] @stangri vpn-policy-routing
- [x] @stangri vpnbypass
- [x] @cotequeiroz wifidog
- [x] @G-M0N3Y-2503 docker-ce

Compile tested: not needed only script changes
Run tested: todo if package maintainer verified my changes

Description:
This is a draft P/R if the following openwrt [P/R](https://github.com/openwrt/openwrt/pull/3246) is merged in the openwert master. For consistency the init scripts in the package feed must also use the new function extra_command, to ensure that the help is displayed consistently.

If every think works as expected I will also update the PKG_RELEASE number of each package.

### CODE REVIEW

**Comment by Ansuel** [comment]
LGTM for nginx

**Comment by gladiac1337** [comment]
I am fine with the change for **haproxy**. Also, I like the new extra_command().

**Review by jefferyto — APPROVED** [review]
LGTM for seafile-server - thanks!

**Comment by stangri** [comment]
@feckert does this change mean that the init files for releases (18.06 and 19.04) and snapshots will be irrevocably diverged from now on? There's no way to keep the same init file for releases and snapshots?

**Comment by cotequeiroz** [comment]
LGTM for wifidog.

**Comment by Shulyaka** [comment]
LGTM for postfix

**Comment by dibdot** [comment]
OK for adblock, banIP and travelate - thanks.

**Comment by yousong** [comment]
LGTM for openvswitch

**Comment by feckert** [comment]
> As I'd like to maintain the same init script for releases and snapshots, if the `extra_command` is not going to be backported to releases, can we do the following?
> 
> ```shell
> if type extra_command 1>/dev/null 2>&1; then
> extra_command "..." "...."
> ...
> else
> EXTRA_COMMANDS="..."
> EXTRA_HELP="..."
> fi
> ```
> 
> My git-fu is not strong enough to submit the changes to this PR, but I can submit another PR with if-else after, please advise @feckert.

If this code change works for you ( I did not tested ) you could push another commits on top of this/my P/R. I will take care and squash the commits with my commits that changes your maintained packages ?

**Comment by G-M0N3Y-2503** [comment]
I can't foresee any issue with this change.
LGTM for docker-ce

**Comment by zioproto** [comment]
I dont know what to say for `tinc`.
Is this `extra_command` function documented anywhere ?

Here: https://openwrt.org/docs/techref/initscripts
Still provides the following example:
```
EXTRA_COMMANDS="custom"
EXTRA_HELP="        custom  Help for the custom command"
 
custom() {
        echo "custom command"
        # do your custom stuff
}
```

**Comment by feckert** [comment]
@zioproto Good point we have also update the docs too.
But the function is not merged in the master branch so I have not update the docs and this P/R is still a draft.

**Comment by stangri** [comment]
> > As I'd like to maintain the same init script for releases and snapshots, if the `extra_command` is not going to be backported to releases, can we do the following?
> > ```shell
> > if type extra_command 1>/dev/null 2>&1; then
> > extra_command "..." "...."
> > ...
> > else
> > EXTRA_COMMANDS="..."
> > EXTRA_HELP="..."
> > fi
> > ```
> > 
> > 
> > My git-fu is not strong enough to submit the changes to this PR, but I can submit another PR with if-else after, please advise @feckert.
> 
> @stangri If this code change works for you ( I did not tested ) you could push another commits on top of this/my P/R. I will take care and squash the commits with my commits that changes your maintained packages ?

Thanks, I'll try to test my suggestion and reply/push the fix to your repo over the weekend!

**Comment by stangri** [comment]
> @stangri If this code change works for you ( I did not tested ) you could push another commits on top of this/my P/R. I will take care and squash the commits with my commits that changes your maintained packages ?

I don't have permissions to push to your branch, I've created [this](https://github.com/stangri/packages/tree/extra-command) with fixes. Alternatively, just push your fixes and when I update my packages, I'll push the release-agnostic fix. LGTM.

**Comment by feckert** [comment]
@stangri If that suits you, I'll merge it as long as the openwrt master chagen is merged.
But can you please not combine the 3 commits into one? 
I think it's better to separate this one, they have nothing to do with each other, because they are 3 different files or packages.

**Comment by stangri** [comment]
> @stangri If that suits you, I'll merge it as long as the openwrt master chagen is merged.
> But can you please not combine the 3 commits into one?
> I think it's better to separate this one, they have nothing to do with each other, because they are 3 different files or packages.

Oh, I thought they'd be squashed anyways. Just merge this change and I'll send individual PRs for affected packages later?

**Comment by feckert** [comment]
Since openwrt master has merged the depending P/R. This is not a draft anymore.
https://github.com/openwrt/openwrt/commit/1a69f50dc627f6fc5860f871edec357cc0a187e6

Outstand comments about my changes?

ping @Shulyaka postfix @liudf0716 apfree-wifidog @dangowrt gnunet @chris5560 radicale @mstorchak tgt

If not I will merge this.

**Comment by G-M0N3Y-2503** [comment]
I was testing master before this went in and I'm getting some strange behaviour for `docker-ce`.
Looking at the trace it looks like setting `EXTRA_COMMANDS` overrides it, but appending seemed to work ok.
image
@stangri, looking at that branch you linked you might run into the same trouble if you haven't tested it yet.

**Comment by dibdot** [comment]
@feckert Should I prepare individual updates for adblock, banIP and travelmate? Currently all packages above are broken in master ...

**Comment by feckert** [comment]
> @feckert Should I prepare individual updates for adblock, banIP and travelmate? Currently all packages above are broken in master ...

I know, the change was merged into the openwrt master yesterday. I'm still waiting for the go from the package maintainer of most of them I have the go. I still have to update the PKG_RELEASE number. I will do that tomorrow and merge the change when I don't hear anything from the others anymore.

**Pull request merged**
