### PR TITLE
coova-chilli: Fix UCI parse error

### PR DESCRIPTION
**Pull request by rajanvaja**
Maintainer: @kaloz 

UCI commands report errors in parsing coova-chilli
sample configuration file. This PR fixes this issue by using
proper format in configuration.

Signed-off-by: Rajan Vaja <rajan.vaja@gmail.com>

### CODE REVIEW

**Comment by hojuruku** [comment]
Remember to merge this coova chilli update if you haven't already done so.
https://github.com/openwrt/packages/pull/2737/commits/f3898d3e2be47c414882b93d8f54e7bd919c4628
https://github.com/openwrt/packages/pull/2737/
CC @Spomky

**Comment by hojuruku** [comment]
@rajanvaja can you add @Spomky 's changes in #2737 to your pull request commits?

**Comment by thess** [comment]
Hi @rajanvaja 
Please read and follow PR guidelines: https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

Minimally you need to bump PKG_RELEASE for the config file change. I there a dependency on #2737?

@champtar / @kaloz

**Comment by rajanvaja** [comment]
Hi @thess 

Thanks for pointing out. I have updated PR with PKG_RELEASE change. 

This PR has no dependency on #2737 . 

Thanks,
Rajan

**Comment by rajanvaja** [comment]
Hi @hojuruku 

I think these this PR and #2737 are independent and can be merged individually. is there any reason to merge both PRs?

Thanks,
Rajan

**Comment by champtar** [comment]
@hojuruku #2737 is not ready to merge
this one is simple and ready to merge, so not waiting for @kaloz

**Pull request merged**
