### PR TITLE
openldap: Fix compilation without deprecated OpenSSL 1.0.2 APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @MikePetullo 
Compile tested: ar71xx

### CODE REVIEW

**Comment by cshoredaniel** [comment]
Please clarify if there is no change to the binary why compilation fails when deprecated APIs are turned off.  i.e. have you verified the package doesn't need patching to correct a dependency on now-deprecated API?

**Comment by neheb** [comment]
No it's just a threading API introduced in 1.0.0 and which was deprecated in 1.1.0 (which is coming soon).

**Comment by neheb** [comment]
Backported upstream fix. It's either a coincidence that the same issue got fixed upstream shortly after I fixed it here or someone is watching.

**Comment by neheb** [comment]
Closing as master uses 1.1 now.

**Pull request closed without merging**
