### PR TITLE
[openwrt-19.07] gammu: Fix lib symlinks

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @aTanW 
Compile tested: armvirt-64, 2019-10-04 snapshot sdk
Run tested: none

Description:
This fixes the symlinks for `libGammu.so` and `libgsmsd.so`. Previously, the symlinks were overwritten by `$(INSTALL_BIN)` with copies of their sources.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
I think the package update should also be backported.

**Comment by jefferyto** [comment]
That's a good point... should I keep or remove the Python dependency?

**Comment by neheb** [comment]
Remove.

For reference, I'm freezing 19.07 for bugfixes only when an rc gets released. 19.07 was branched too early.

**Comment by jefferyto** [comment]
It's done - I cherry-picked the previous commits instead of squashing them.

Any idea when the rc will be ready?

**Comment by neheb** [comment]
No idea. From what I know, LuCI bugs are the holdup.

**Pull request merged**
