### PR TITLE
file: Update to 5.33

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ratkaj 
Compile tested: mvebu

### CODE REVIEW

**Comment by neheb** [comment]
Hrm I never looked into the mirrors.

As the GitHub page has releases, could also switch to that. Would be simpler. Need to autoreconf anyways. Filename format is ugly though...

Static build I'm guessing is for libmagic.a. No idea how useful it actually is.

**Comment by diizzyy** [comment]
ftp.astron.com is the official tarball source site, I don't think we should diverge from upstream in that regard.

**Comment by neheb** [comment]
I'm reluctant on putting ftp first as I've had curl hang on FTP for several minutes on Ubuntu 16.04 WSL. May be why it's not first in the mirror list here.

I will think about this.

**Comment by diizzyy** [comment]
In general I think we should use the following order
Official mirror(s) (HTTP/HTTPS) --> Official site/tarball location (any protocol) --> "Generic" mirror (if needed) (any protocol if needed)

**Comment by ratkaj** [comment]
@neheb did your run test this? 
I'm getting run errors with versions never than 5.25, that's why i run the old version.

Run testing your patch on RPi get's me this:
file: bad magic in `/usr/share/misc/magic.mgc' (No such file or directory)

File ofcourse exists and permissions are ok.

**Comment by neheb** [comment]
I ran strace. As I though, the error message is wrong. It errors on a different file..

stat64("/root/.magic.mgc", 0x7fc88210)  = -1 ENOENT (No such file or directory)
stat64("/root/.magic", 0x7fc88210)      = -1 ENOENT (No such file or directory)

will investigate further.

**Comment by neheb** [comment]
Nope. The error is related to that magic symlink. Replacing that with touch seems to work, but then it gives a different error.

**Comment by ratkaj** [comment]
@neheb It works now, thank you

**Pull request merged**
