### PR TITLE
sqlite3: change maintainer

### PR DESCRIPTION
**Pull request by micmac1**
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

Maintainer: @champtar 
Compile tested: N/A
Run tested: N/A

Description:
Hello Etienne,

As discussed. I won't send a pull request for 17.01 as that would kick off another build there basically for nothing :) 

Kind regards,
Seb

### CODE REVIEW

**Comment by diizzyy** [comment]
Don't update copyright unless you're affiliated with OpenWrt.org

**Comment by champtar** [comment]
@micmac1 I agree with @diizzyy, please remove the copyright change

**Comment by micmac1** [comment]
I don't agree with @dizzy on this. Updating the year is normal practice.

Kind regards,
Seb

**Comment by jow-** [comment]
Updating the year on your own copyright notices might be, but not on foreign ones.

**Comment by thess** [comment]
As noted in [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) - First bullet in ["Makefile contents should contain"](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#makefile-contents-should-contain) explains how to handle Copyright.

**Comment by micmac1** [comment]
OK, amended. Thanks for the information.

Kind regards,
Seb

**Comment by champtar** [comment]
Thanks @micmac1

**Pull request merged**
