### PR TITLE
libsoup: Add glib2 build dependency

### PR DESCRIPTION
**Pull request by neheb**
glib-mkenums is a binary used by the make system that glib2 provides.

Should fix the buildbots (local has always worked for me).

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @MikePetullo 
Compile tested: mvebu

Should fix libdmapsharing and dmapsharing as well.

### CODE REVIEW

**Comment by thess** [comment]
CI build failures aside -- I don't think this change fixes the underlying problem. Adding the glib2/host dependency is redundant due to the already existing +glib2 dependency.

The actual problem that needs solving is the glib2 package-config file (.pc) points to /usr/bin and not the host path. In other words:
>GLIB_MKENUMS=`$PKG_CONFIG --variable=glib_mkenums glib-2.0`

returns "/usr/bin/glib-mkenums" instead of ".../staging_dir/\<build-target>/usr/bin/glib-mkenums".

If the buildbots have libglib2.0-dev-bin then libsoup, etc. builds. Otherwise, the libsoup configure script aclocal.m4 may need patching.

**Comment by thess** [comment]
NAK - Root problem is still a buildbot config issue - these changes do not fix it.
BTW - the intltool problem exists in libpsl which needs nls.mk + $(INTL_DEPENDS)

**Comment by neheb** [comment]
I could have sworn glib2 host was not built by default. Need to retest.

**Comment by thess** [comment]
I finally figured out the REAL fix for this problem. Our build tool variant of **pkg-config** did not handle the proper redirection of the `bindir` variable like it does for `libdir` and `includedir`. I will push a patch to tools/pkg-config which will make this package build correctly with glib2. You'll have to wait for newer SDK's to be generated.

I'm also looking into the **intltool** issue mentioned elsewhere and will be fixing up **libpsl** so all this builds correctly with BUILD_NLS=y.

Closing this for now - I will push the necessary fixes shortly.

**Comment by neheb** [comment]
Sounds good. Thanks for looking into this.

**Pull request closed without merging**
