### PR TITLE
openwisp-config: polarssl has been removed

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: @nemesisdesign
Compile tested: n/a
Run tested: n/a

Description:

Can build polarssl variant if there isn't any polarssl...

### CODE REVIEW

**Comment by pprindeville** [comment]
@diizzy "Should I stay or should I go?"

**Comment by nemesisdesign** [comment]
Beginning of september I am going to send an upgrade of openwisp-config

**Comment by pprindeville** [comment]
> Beginning of september I am going to send an upgrade of openwisp-config

Okay, so what does that mean for this PR?  Should we proceed?  Should we abandon it?

**Comment by diizzyy** [comment]
I'd save remove it, it's an invalid option anyway.

**Comment by pprindeville** [comment]
Okay... I'll proceed with the removal if I don't hear back in the next day or so.

**Pull request merged**
