### PR TITLE
lua-openssl: Update to version 0.8.5-1

### PR DESCRIPTION
**Pull request by amnonpaz**
Maintainer: @amnonpaz 
Compile tested: x86, latest
Run tested: x86, VirtualBox emulation

Description:
Updating lua-openssl from v0.8.2-1 to v0.8.5-1. No major changes in build or usage.

### CODE REVIEW

**Comment by BKPepe** [comment]
CI is failing, because of dirty patches. All patches needs to be refreshed.

You can do that by:

``make package/foo/refresh V=s``

Instead of foo, add the package name

**Comment by amnonpaz** [comment]
Thank you for your input, and sorry for my possibly ignorant questions, but I could not reproduce this and I after reading the docs I still don't understand what the problem is.
I am executing: `make package/lua-openssl/update V=sc`, and this is the output, no error there:
```
WARNING: Makefile 'package/feeds/packages/python-cryptography/Makefile' has a build dependency on 'python-setuptools-rust/host', which does not exist
make[2]: Entering directory '/home/amnon/projects/openwrt/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/amnon/projects/openwrt/openwrt/scripts/config'
make[1]: Entering directory '/home/amnon/projects/openwrt/openwrt'
make[2]: Entering directory '/home/amnon/projects/openwrt/openwrt/feeds/packages/lang/lua-openssl'
if [ -s "/home/amnon/projects/openwrt/openwrt/build_dir/target-x86_64_musl/lua-openssl-0.8.5-1/patches/series" ]; then (cd "/home/amnon/projects/openwrt/openwrt/build_dir/target-x86_64_musl/lua-openssl-0.8.5-1"; if quilt --quiltrc=- next >/dev/null 2>&1; then quilt --quiltrc=- push -a; else quilt --quiltrc=- top >/dev/null 2>&1; fi ); fi
Applying patch 010-no-luajit.patch
patching file CMakeLists.txt

Now at patch 010-no-luajit.patch
touch "/home/amnon/projects/openwrt/openwrt/build_dir/target-x86_64_musl/lua-openssl-0.8.5-1/.quilt_checked"
mkdir -p ./patches
rm -f ./patches/* 2>/dev/null >/dev/null
'/home/amnon/projects/openwrt/openwrt/build_dir/target-x86_64_musl/lua-openssl-0.8.5-1/patches/010-no-luajit.patch' -> './patches/010-no-luajit.patch'
make[2]: Leaving directory '/home/amnon/projects/openwrt/openwrt/feeds/packages/lang/lua-openssl'
time: package/feeds/packages/lua-openssl/update#0.15#0.06#0.22
make[1]: Leaving directory '/home/amnon/projects/openwrt/openwrt'
```

**Comment by jefferyto** [comment]
Run `make package/lua-openssl/{clean,refresh}`. That will update 010-no-luajit.patch; amend your commit with the changes and force-push to update your branch here.

**Comment by amnonpaz** [comment]
Thanks. Done.

**Comment by amnonpaz** [comment]
All checks have passed, please merge.

**Pull request merged**
