### PR TITLE
net/coova-chilli: Coova-Chilli V1.3.1.4

### PR DESCRIPTION
**Pull request by Spomky**
coova-chilli: This PR updates the coova-chilli package with the lastest release of the captive portal (v1.3.1.4).
It also includes new configuration options to create fine grained packages and fixes #2934.

Signed-off-by: Florent Morselli florent+git@morselli.fr

### CODE REVIEW

**Comment by champtar** [comment]
Hi @Spomky,
please follow https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by Spomky** [comment]
Commit signed off.

**Comment by diizzyy** [comment]
@Spomky 
Can you refresh this patch? 
Are you willing to take maintainership if need?
I'll poke some ppl about maintainer timeout.

**Comment by diizzyy** [comment]
@Spomky 
I think something went wrong here, you're not allowed to touch files outside of your package.
Also, you need to squash all commits into one.

**Comment by Spomky** [comment]
You are right.
I have rebased the PR but something went wrong.
I am trying to fix it.

sorry for the inconvenience.

**Comment by Spomky** [comment]
I created a new PR based on the last repository revision.
Please see https://github.com/openwrt/packages/pull/3780

**Pull request closed without merging**
