### PR TITLE
netifyd: add reproducibility patch

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dsokoloski 
Compile tested: ath79

### CODE REVIEW

**Comment by dsokoloski** [comment]
@neheb Hi Rosen!

Thanks for the patch.  I'm not sure what you mean by "reproducibility".  Could you explain what the motivation is here?

Maybe we should just remove that line of output altogether?

**Comment by 1715173329** [comment]
> Thanks for the patch. I'm not sure what you mean by "reproducibility". Could you explain what the motivation is here?

@dsokoloski This means users could build the same binaries from source as what OpenWrt buildbot built.
Yes, they even share the same HASH.

**Comment by dsokoloski** [comment]
@1715173329 I understand...  I have removed the git date/time text from the source.

**Comment by neheb** [comment]
https://tests.reproducible-builds.org/openwrt/dbd/packages/arm_cortex-a8_vfpv3/packages/netifyd_2020-09-15-v3.05-1_arm_cortex-a8_vfpv3.ipk.html

**Pull request merged**
