### PR TITLE
libulfius: new package

### PR DESCRIPTION
**Pull request by lnslbrty**
Maintainer: me
Compile tested: x86_64, debian-stable, OpenWrt SNAPSHOT r13247+9-631c437a91
Run tested: mvebu, linksys3200ac, OpenWrt SNAPSHOT r13247+9-631c437a91
Run tested: x86_64, qemu-kvm, OpenWrt SNAPSHOT r13247+9-631c437a91

Description:
Web Framework to build REST APIs, Webservices or any HTTP endpoint in C language.

### CODE REVIEW

**Comment by neheb** [comment]
https://8832-20307838-gh.circle-artifacts.com/0/%7E/build_dir/logs/package/feeds/packages/libulfius/gnutls/compile.txt

**Comment by lnslbrty** [comment]
libulfius depends and downloads the source of another lib (liborcania; maintained by the same guy). Basically a wrapper for some libc functions. Should I include that library in the libulfius Makefile or create an additional package for liborcania? (latter one does not really makes sense to me)

**Comment by neheb** [comment]
Whichever. For the latter, you can create a BUILDONLY package and link statically. See spdlog, taglib, pugixml, as examples.

**Comment by lnslbrty** [comment]
will go the static way, thanks

**Comment by lnslbrty** [comment]
Whoops, accidentally deleted.

**Comment by neheb** [comment]
```
cp: cannot create symbolic link '/usr/lib/libulfius.so.2.6': Permission denied
cp: cannot create regular file '/usr/lib/libulfius.so.2.6.7': Permission denied
```

**Comment by lnslbrty** [comment]
I disabled websocket support as I do not need it and there is already `libuwsc`.

FYI: I did not go the static way as it did not worked me.

**Comment by neheb** [comment]
Weird.

**Pull request merged**
