### PR TITLE
gitlab-runner: add new package

### PR DESCRIPTION
**Pull request by ja-pa**
Maintainer: me
Compile tested: Turris Omnia (TOS6), OpenWrt master
Run tested: Turris Omnia (TOS6), OpenWrt master

Description:
This PR adds new package gitlab-runner. It is useful in case you want to connect GitLab CI/CD to the router.

More info https://docs.gitlab.com/runner/

### CODE REVIEW

**Comment by ja-pa** [comment]
Test mips_24kc fails on following error:
```
../../../../../dl/go-mod-cache/github.com/docker/engine@v1.4.2-0.20190822180741-9552f2b2fdde/pkg/system/stat_linux.go:11:3: cannot use s.Rdev (type uint32) as type uint64 in field value
```
It is probably related to https://github.com/containers/storage/issues/444

**Comment by BKPepe** [comment]
In any case, this should be reviewed by @jefferyto

**Comment by jefferyto** [comment]
Looks like there are [variables](https://gitlab.com/gitlab-org/gitlab-runner/-/blob/v13.5.0/Makefile#L43-45) that can be set with `GO_PKG_LDFLAGS_X`, but LGTM otherwise.

> Test mips_24kc fails on following error:

This was fixed in https://github.com/docker/engine/commit/5f0231bca193320e1a3d785a3ade0e64241fe580, not sure why gitlab-runner is using such an old version of that package.

**Comment by ja-pa** [comment]
> Looks like there are [variables](https://gitlab.com/gitlab-org/gitlab-runner/-/blob/v13.5.0/Makefile#L43-45) that can be set with `GO_PKG_LDFLAGS_X`, but LGTM otherwise.
> 
> > Test mips_24kc fails on following error:
> 
> This was fixed in [docker/engine@5f0231b](https://github.com/docker/engine/commit/5f0231bca193320e1a3d785a3ade0e64241fe580), not sure why gitlab-runner is using such an old version of that package.

I have forbidden build for MIPS and mipsel architecture. (Upstream issue https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27234) 
When it comes to variables, I left it unfilled (or do you think it's blocker? @jefferyto )

**Comment by jefferyto** [comment]
> When it comes to variables, I left it unfilled (or do you think it's blocker? @jefferyto )

I haven't looked into where they are used, but usually variables like these are only for the version string. On the one hand, the version string isn't critical (though it might confuse users); on the other hand, it's probably not hard to set some/all of the variables. I think it's nice to have but not a strict blocker.

**Pull request merged**
