### PR TITLE
python-gnupg: Use a less braindead URL

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dangowrt

### CODE REVIEW

**Comment by cshoredaniel** [comment]
What is the official upstream (python-gnupg) recommendation for canonical release location?

**Comment by cshoredaniel** [comment]
Wouldn't the official BitBucket release page https://bitbucket.org/vinay.sajip/python-gnupg/downloads/ be a better place (in this case: https://bitbucket.org/vinay.sajip/python-gnupg/downloads/python-gnupg-0.4.3.tar.gz)

**Comment by neheb** [comment]
Most of the python packages here use some variation of this URL.

**Comment by cshoredaniel** [comment]
Fair enough, just wondering since the official source URL is available...not sure that's the case for 'most python packages'.  I wonder if pypi should be used a primary URL (since it presumably has more capacity), with fallback  to official URL.  Actually I wonder if Travis CI is failing for Python due to rate-limiting or such on PyPi?  (Not likely, but I'd be curious to know ... I did notice the usual error is that the test download succeeds but for the build the download fails).

**Comment by neheb** [comment]
I think it has to do with some bad configuration on the part of Travis. @comodo is looking into it.

**Comment by neheb** [comment]
Force pushed a new commit. I actually meant this URL.

Hmm I actually wonder if this is right.

https://pypi.io/packages/source/p/python-gnupg/python-gnupg-0.4.3.tar.gz redirects to

https://pypi.org/packages/source/p/python-gnupg/python-gnupg-0.4.3.tar.gz which redirects to

https://files.pythonhosted.org/packages/source/p/python-gnupg/python-gnupg-0.4.3.tar.gz which redirects to

https://files.pythonhosted.org/packages/fd/a6/4ae8ec46a256444f65d745a92827c05fe6d4f3f4e1a40289a58ac37fe2b9/python-gnupg-0.4.3.tar.gz

In other cases like @GITHUB and codeload, the last URL is preferred. But in this case the URL needs to updated every time the version is bumped. Maybe the second to last URL should be used?

**Comment by commodo** [comment]
hey;
so, typically for python packages people [and me] would copy + paste the URL from the pypi site;
those URLs have some magic numbers there which differ based on version

then after a while we found that there are static URLs like `https://pypi.io/packages/source/p/python-gnupg/python-gnupg-0.4.3.tar.gz `  or `https://files.pythonhosted.org/packages/source/p/python-gnupg/python-gnupg-0.4.3.tar.gz`  which have a fixed base URL [ i.e. https://pypi.io/packages/source/p/python-gnupg or https://files.pythonhosted.org/packages/source/p/python-gnupg ] 

long-term it would be nice to use the ones with the fixed base, but I would do this for each package when it's being upgraded

**Comment by neheb** [comment]
I'm going to update this to use the latter since there are fewer redirections involved.

**Comment by neheb** [comment]
ping @dangowrt

**Comment by neheb** [comment]
Rebased to current master and edited the commit message.

@hnyman OK to merge?

**Pull request merged**
