### PR TITLE
lang/lua-penlight: Update to 1.4.1

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @karlp 
Compile tested: Kirkwood, iomega iConnect, LEDE trunk
Run tested: N/A

Description:
Update lua-penlight to 1.4.1
Fix package tarball file name
Changelog: https://github.com/stevedonovan/Penlight/blob/master/CHANGES.md

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by karlp** [comment]
I'd like to see a basic summary of the changes, or a link to the changelog.  Also, run testing _is_ appropriate.  It can be "no" but it's not "N/A"

**Comment by diizzyy** [comment]
I have no idea how to run-test this, it's mainly for fixing the tarball file name to avoid clashes.

**Comment by karlp** [comment]
Maybe a single standalone commit that only "fixed" the tarball names then perhaps :)

**Comment by karlp** [comment]
Updated to 1.5.4 in master via f561f3faacd38accaeb1725c663aee14fc654398

**Pull request closed without merging**
