### PR TITLE
[RFC] shadowsocks-client: remove

### PR DESCRIPTION
**Pull request by dengqf6**
Maintainer: @zhao-gang 

It hasn't been maintained for years and doesn't have recent features such as [AEAD crypto](https://shadowsocks.org/en/spec/AEAD-Ciphers.html) and [IPv6](https://github.com/zhao-gang/shadowsocks-tiny/issues/1).
(The "recent" update is _fix compilation without deprecated OpenSSL APIs_, which is made by @neheb)
It has been superseded by shadowsocks-libev, which is recently maintained by community and has LuCI frontend.
Despite its smaller size, it depends on OpenSSL, which is way larger than MbedTLS, the one shadowsocks-libev used. Thus, it doesn't really fit in space-constrained devices.

### CODE REVIEW

**Comment by zhao-gang** [comment]
Unfortunately I don't have the time to continue the work on shadowsocks-client project. I am OK to remove it from OpenWrt packages.

**Comment by neheb** [comment]
I have no opinion in the matter.

**Comment by zhao-gang** [comment]
@yousong I think it's the time to let users to switch to shadowsocks-libev. It's actively developed and maintained. Feel free to remove shadowsocks-client.

**Comment by yousong** [comment]
Done.  Thank you.

**Pull request merged**
