### PR TITLE
bandwidthd: fix format warnings

### PR DESCRIPTION
**Pull request by neheb**
Should fix crashing errors under musl 1.2

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @padre-lacroix 

Fixes: https://github.com/openwrt/packages/issues/19352

I think.

### CODE REVIEW

**Comment by neheb** [comment]
Oh cool there's an up to date fork: https://codeberg.org/post-factum/bandwidthd

**Comment by padre-lacroix** [comment]
OK, I will look at it.  Thismake takes a few days has I have to create a new virtual machine for building OpenWRT (the current one that I have is old).

For the up to date fork, I will look at it for the solution delpoyed.  But, it seems to be the same problem (but I am not an expert).

@neheb : did you try to execute the patch that you made?  This is why I have to compile it myself to see if the executable works on a 32 bit virtual machine (that is the problem isn't it: on a 32 bit router, this would not work properly).

**Comment by neheb** [comment]
It executes fine under malta.

**Comment by padre-lacroix** [comment]
OK: I approve the pull request.

Sorry that it took me so long: I have been pretty sick in the last 10 days.

**Comment by frankgrant** [comment]
Updated to the latest version 2.0.1-35-6 and still get the error
do_page_fault(): sending SIGSEGV to bandwidthd for invalid read access from 00000018
epc = 77e9e534 in libc.so[77e12000+a9000]
ra = 77e9e410 in libc.so[77e12000+a9000]

**Pull request merged**
