### PR TITLE
git: Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tripolar 
Compile tested: ar71xx

### CODE REVIEW

**Comment by hnyman** [comment]
conflict due to 89ef798deccf5375cc

**Comment by neheb** [comment]
@hnyman fixed. FWIW I've had this fixed in my local tree for a long time.

**Comment by tripolar** [comment]
did you send this patch upstream?

**Comment by neheb** [comment]
Did now: https://public-inbox.org/git/20181227023548.396-1-rosenp@gmail.com/T/#u

**Comment by neheb** [comment]
Replaced patch with the one sent upstream. Turns out the number was wrong (copy/paste error).

**Comment by tripolar** [comment]
thanks

**Pull request merged**
