### PR TITLE
spice: Fix compilation with uClibc-ng

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @yousong 
Compile tested: arc700

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/spice/compile.txt

### CODE REVIEW

**Comment by neheb** [comment]
https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/spice/compile.txt

**Comment by yousong** [comment]
If this is a target specific issue and we are not going to fix it in the near future, I prefer we disable spice build for that specific target.  Turning off a security precaution because one target lacks proper support does not look fair to users of other targets.

**Comment by neheb** [comment]
Maybe make it conditional on $(CONFIG_SSP_SUPPORT) ?

**Comment by yousong** [comment]
Should be fixed now by 5a25cf86ea56.  Thanks for letting me know.

**Pull request closed without merging**
