### PR TITLE
Migrate pyload, ossp-js, tesseract and leptonica to new packages feed

### PR DESCRIPTION
**Pull request by currywurst76**

### CODE REVIEW

**Comment by currywurst76** [comment]
I hope it's better now.

**Comment by thess** [comment]
Package structure looks fine - However, there are serveral missing dependencies called out by these packages (not in current packages repo). So I doubt things will build.

leptonica -- giflib
pyload -- pyopenssl python-curl python-crypto python-expat python-imaging-library(python-imglib?)

**Comment by currywurst76** [comment]
Well, it compiles fine for me..

**Comment by thess** [comment]
Perhaps you have __oldpackages__ installed on your buildroot. The standard environment does not.

**Comment by currywurst76** [comment]
Okay, I'll try to add the missing dependencies.

**Comment by thess** [comment]
OK, I've tested your packages on a clean buildroot. Indeed, they all compile. Some of the packages however, will not install (using opkg) due to the missing dependencies. Either remove them from the Makefiles if they are not needed or import the missing packages to github. Image build seems to be OK in spite of the missing dependencies -- Hmmmm, bug in build scripts?

leptonica -- ignores giflib (not found by configure), fails install.
ossp-js -- OK
tesseract -- Will not install without libleptonica
pyload -- will not install due to several missing deps.

**Comment by thess** [comment]
If you'd like, I'll do the import (and maintain) giflib. The python stuff should be separate pull-requests as they are reviewed by others who may want to tweak them. Python has been problematic at best lately.

**Comment by thess** [comment]
giflib done -- see 99263ff5734fef8525fc055f69721b6e041af7f3

**Comment by champtar** [comment]
ping @currywurst76

**Comment by champtar** [comment]
ping @currywurst76

**Pull request closed without merging**
