### PR TITLE
libnetfilter-queue: fix compatibility with musl

### PR DESCRIPTION
**Pull request by mstorchak**
Signed-off-by: Maxim Storchak <m.storchak@gmail.com>

### CODE REVIEW

**Comment by mstorchak** [comment]
@psycho-nico , please review and approve

**Comment by nbd168** [comment]
Why is this package still in the tree? It is already present in trunk.

**Comment by mstorchak** [comment]
Hm.. no idea. Maybe I have stale links. It didn't work so I fixed it. If it's been moved to trunk, please ignore this PR.

**Comment by thess** [comment]
Yup - libnetfiler-queue, -cthelper & -cttmeout will be removed from here. I guess no one noticed the move back in March. @nbd168 - Anything else moved we didn;t catch?

**Pull request closed without merging**
