### PR TITLE
python3: update to version 3.9.9

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainers: @jefferyto , @commodo 
Compile and run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt 21.02

Description:
- Changelog: https://www.python.org/downloads/release/python-399/
- Updated setuptools and pip
- Refreshed patches

### CODE REVIEW

**Comment by commodo** [comment]
fine from my side :)

but can you also remove me as maintainer from Python in 21.02?
[ i've already done that in master, but i forgot about 21.02 ]
19.07 will be EOL-ed soon ; so no stress/hurry to remove me from there; also no objections to remove me from there;

it's been a journey for me [with Python], and i will park myself for now :)

**Comment by BKPepe** [comment]
> it's been a journey for me [with Python], and i will park myself for now :)

Understood! Take your time. You were and still doing a great job about Python here. 

> but can you also remove me as maintainer from Python in 21.02?

Should I do this in this PR or in another? I don't mind both.

**Comment by commodo** [comment]
> Should I do this in this PR or in another? I don't mind both.

i don't mind either :)
your choice

// in Romanian this minor "deadlock" is described roughly as a "allow me to allow you [and a potential recursion]" situation

**Comment by BKPepe** [comment]
I'm going to merge this, and removing you as the maintainer will be done in separate PR in a few minutes.

**Comment by commodo** [comment]
> I'm going to merge this, and removing you as the maintainer will be done in separate PR in a few minutes.

ack :)
thanks

**Comment by regae** [comment]
this breaks meson in 21.02

`Traceback (most recent call last):
  File "/Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/meson.py", line 18, in <module>
    from mesonbuild._pathlib import Path
  File "/Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/mesonbuild/_pathlib.py", line 38
    def resolve(self, strict: bool = False) -> 'Path':
                            ^
SyntaxError: invalid syntax`

**Comment by BKPepe** [comment]
@regae Can you please provide me more details about your configuration? For all Turris routers, ```meson``` is compiled just fine with this PR.

**Comment by regae** [comment]
> SHELL= flock /Volumes/openWRT-21.02/tmp/.libevdev-1.12.0.tar.xz.flock -c '  	/Volumes/openWRT-21.02/scripts/download.pl "/Volumes/openWRT-21.02/dl" "libevdev-1.12.0.tar.xz" "2f729e3480695791f9482e8388bd723402b89f0eaf118057bbdea3cecee9b237" "" "https://www.freedesktop.org/software/libevdev/"    '
> rm -f /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/.configured_*
> rm -f /Volumes/openWRT-21.02/staging_dir/target-aarch64_cortex-a53_musl/stamp/.libevdev_installed
> /Volumes/openWRT-21.02/staging_dir/host/bin/sed -e "s|@CC@|'gcc',|" -e "s|@CXX@|'g++',|" -e "s|@PKGCONFIG@|/Volumes/openWRT-21.02/staging_dir/host/bin/pkg-config|" -e "s|@CFLAGS@|'-O2', '-I/Volumes/openWRT-21.02/staging_dir/host/include', '-I/Volumes/openWRT-21.02/staging_dir/hostpkg/include', '-I/Volumes/openWRT-21.02/staging_dir/target-aarch64_cortex-a53_musl/host/include', '-I/Volumes/openWRT-21.02/staging_dir/host/include', '-I/Volumes/openWRT-21.02/staging_dir/hostpkg/include', '-I/Volumes/openWRT-21.02/staging_dir/target-aarch64_cortex-a53_musl/host/include',|" -e "s|@CXXFLAGS@|'-I/Volumes/openWRT-21.02/staging_dir/host/include', '-I/Volumes/openWRT-21.02/staging_dir/hostpkg/include', '-I/Volumes/openWRT-21.02/staging_dir/target-aarch64_cortex-a53_musl/host/include',|" -e "s|@LDFLAGS@|'-L/Volumes/openWRT-21.02/staging_dir/host/lib', '-L/Volumes/openWRT-21.02/staging_dir/hostpkg/lib', '-L/Volumes/openWRT-21.02/staging_dir/target-aarch64_cortex-a53_musl/host/lib',|" -e "s|@PREFIX@|/Volumes/openWRT-21.02/staging_dir/hostpkg|" < /Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/openwrt-native.txt.in > /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/openwrt-native.txt
> /Volumes/openWRT-21.02/staging_dir/host/bin/sed -e "s|@CC@|'aarch64-openwrt-linux-musl-gcc',|" -e "s|@CXX@|'aarch64-openwrt-linux-musl-g++',|" -e "s|@AR@|aarch64-openwrt-linux-musl-gcc-ar|" -e "s|@STRIP@|aarch64-openwrt-linux-musl-strip|" -e "s|@NM@|aarch64-openwrt-linux-musl-gcc-nm|" -e "s|@PKGCONFIG@|/Volumes/openWRT-21.02/staging_dir/host/bin/pkg-config|" -e "s|@CFLAGS@|'-O3', '-pipe', '-march=armv8-a+crypto', '-mtune=cortex-a53', '-fno-caller-saves', '-fno-plt', '-fhonour-copts', '-Wno-error=unused-but-set-variable', '-Wno-error=unused-result', '-fmacro-prefix-map=/Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0=libevdev-1.12.0', '-Wformat', '-Werror=format-security', '-fstack-protector', '-D_FORTIFY_SOURCE=1', '-Wl,-z,now', '-Wl,-z,relro', '-I/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/usr/include', '-I/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/include/fortify', '-I/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/include',|" -e "s|@CXXFLAGS@|'-O3', '-pipe', '-march=armv8-a+crypto', '-mtune=cortex-a53', '-fno-caller-saves', '-fno-plt', '-fhonour-copts', '-Wno-error=unused-but-set-variable', '-Wno-error=unused-result', '-fmacro-prefix-map=/Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0=libevdev-1.12.0', '-Wformat', '-Werror=format-security', '-fstack-protector', '-D_FORTIFY_SOURCE=1', '-Wl,-z,now', '-Wl,-z,relro', '-I/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/usr/include', '-I/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/include/fortify', '-I/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/include',|" -e "s|@LDFLAGS@|'-L/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/usr/lib', '-L/Volumes/openWRT-21.02/staging_dir/toolchain-aarch64_cortex-a53_gcc-10.3.0_musl/lib', '-znow', '-zrelro',|" -e "s|@ARCH@|"aarch64"|" -e "s|@CPU@|"64"|" -e "s|@ENDIAN@|little|" < /Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/openwrt-cross.txt.in > /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/openwrt-cross.txt
> /Volumes/openWRT-21.02/staging_dir/host/bin/python /Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/meson.py  --buildtype plain --native-file /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/openwrt-native.txt --cross-file /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/openwrt-cross.txt -Dtests=disabled -Ddocumentation=disabled -Dcoverity=false /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/openwrt-build /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/openwrt-build/..
> Traceback (most recent call last):
>   File "/Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/meson.py", line 18, in <module>
>     from mesonbuild._pathlib import Path
>   File "/Volumes/openWRT-21.02/staging_dir/hostpkg/lib/meson/mesonbuild/_pathlib.py", line 38
>     def resolve(self, strict: bool = False) -> 'Path':
>                             ^
> SyntaxError: invalid syntax
> make[2]: *** [Makefile:66: /Volumes/openWRT-21.02/build_dir/target-aarch64_cortex-a53_musl/libevdev-1.12.0/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
> make[2]: Leaving directory '/Volumes/openWRT-21.02/feeds/packages/libs/libevdev'
> time: package/feeds/packages/libevdev/compile#0.23#0.24#0.50
>     ERROR: package/feeds/packages/libevdev failed to build.
> make[1]: *** [package/Makefile:114: package/feeds/packages/libevdev/compile] Error 1
> make[1]: Leaving directory '/Volumes/openWRT-21.02'
> make: *** [/Volumes/openWRT-21.02/include/toplevel.mk:230: package/libevdev/compile] Error 2

building for armvit 64

**Comment by regae** [comment]
this pull solved my issue
https://github.com/openwrt/packages/pull/11843

**Comment by BKPepe** [comment]
The first reference, which you mentioned, is it not relevant to this pull request. It says about Python 3.5/3.6. In OpenWrt 21.02, there is Python 3.9 and you can check what I did. It was simple bump. You can check the previous version if it is same and I am pretty sure that it will be.

The other reference says that your environment does not have a full Python installation.

It makes that your discussion is not relevant to my pull request at all. I don't have Mac OS, so most likely you are on your own to solve it. What I did for you is that I ran a clean build for OpenWrt 21.02 and wanted to compile ``libevdev``, and it was compiled successfully.

Also, according to faillogs available by OpenWrt, there is no indication that it is broken. For now, I suggest to use GNU/Linux distributions or check your Python installation in Mac OS.

**Comment by paper42** [comment]
This was also reported in #17308, so it seems to be a new issue. The syntax error can only happen with Python 2.

**Comment by jefferyto** [comment]
@regae what do you see if you open Terminal and run this:

```
python3 --version
```

**Comment by regae** [comment]
@jefferyto python3 installed from brew
/usr/bin/python3 3.8.9
/usr/local/bin/python3 3.9.9

**Comment by jefferyto** [comment]
@regae If you do a test compile with a new checkout of the 21.02 buildroot or sdk, do you still get the same error?

**Comment by regae** [comment]
i can't use the sdk, available only for linux, if i'm not mistaken.
after i encountered with this problem, i did clean all, restart from scratch
performed a cleanse in brew (remove unused packages and reinstall necessary packages for openwrt)
after all that, i do not need https://github.com/openwrt/packages/pull/11843 anymore.

however as i mentioned in another topic, i can't compile samba4 because the configuration detects python host sys.platform as darwin, and tried to build samba4 for darwin instead of linux.

**Comment by jefferyto** [comment]
@regae to sum up:

* Your libevdev compile error was because of an issue with your buildroot
* The samba problem is a separate/different issue

**Pull request merged**
