### PR TITLE
muninlite: added a patch for correctly parse ifname with - char

### PR DESCRIPTION
**Pull request by fabys77**
Hi,
i found three problems:
1)  interface name with - char inside wasn't correctly parsed (for example pppoe-wan) because the script substitutes '-' with '_'. This patch substitute the same cher on /proc/net/dev before interface matching.
2) /proc/net/dev has more spaces as delimiter (variable), changing regexp   with "  *" instead of "  "
3)After two splitting matching row in /proc/net/dev, remaing an initial space that shift the correct column number. Removed initial space

### CODE REVIEW

**Comment by champtar** [comment]
hi @fabys77 
you still have 3 commits, please squash everything into 1

**Comment by fabys77** [comment]
ok, i have rebased.

**Comment by jow-** [comment]
The changed code is extremely inefficient, it also produces wrong results. The last sed substitution will put a space after each character instead of collapsing white space.

**Comment by jow-** [comment]
You can replace the entire "sed | grep | cut | sed" chain with just the command below:
`IINFO=$(sed -ne "/^ *${1//_/-}: / { s/^.\+: \+//; s/[[:space:]]\+/ /gp }" /proc/net/dev)`

**Comment by champtar** [comment]
hi @fabys77,
please make it one commit, having "fix" and "fix the fix" is not really usefull

@jmccrohan is it ok for you?

**Comment by jmccrohan** [comment]
@champtar @fabys77 

@jow- feel free to sign off and merge your patch.

Otherwise I'll do it in a day or two.

Jon

**Comment by jmccrohan** [comment]
@jow- Can you take a look at your regex again please?

It doesn't provide any output.

Thanks,
Jon

```
root@host:~# sed -ne "/^[[:space:]]*${1//_/-}:[[:space:]]/ { s/^.\+:[[:space:]]\+//; s/[[:space:]]\+/ /gp }" /proc/net/dev
root@host:~# grep "$1:" /proc/net/dev | cut -d: -f2 | sed -e 's/  / /g'
 174055139092 158462525  0  0  0   0     0     0 174055139092 158462525  0  0  0   0    0     0
 11972648891 97624789  0  0  0   0     0  278569 148868600159 138399648  0  0  0   0    0     0
 10535160 107826  0  0  0   0     0     0 10535160 107826  0  0  0   0    0     0
 3894601  6608  0  0  0   0     0     0  875665  6261  0  0  0   0    0     0
    0    0  0  0  0   0     0     0    0    0  0  0  0   0    0     0
 861350689 3055430  0  0  0   0     0     0 1705699176 5873782  0  0  0   0    0     0
 4267845687 191954687  0  0  9   0     0     0 2520009775 107121416  0  0  0   0    0     0
    0    0  0  0  0   0     0     0    0    0  0  0  0   0    0     0
 106467800 211173  0  0  0   0     0     0 12795047 201256  0  0  0   0    0     0
 1998927148 10062140  0  0  0   0     0     0 3101916548 16880799  0  0  0   0    0     0
 844996080 97624823  0  0  14   0     0     0 3393311730 138399649  0  0  0   0    0     0
 2393764  32079  0  0  0   0     0     0 32610543  40859  0  0  0   0    0     0
 13521169372 109649268  0  0  0   0     0     0 173292656519 157120924  0  0  0   0    0     0
root@host:~# 
```

**Comment by jow-** [comment]
It does not provide output because "$1" is not set while your 2nd test command will merely grep for ":".

    root@jj:~# grepdev() { sed -ne "/^[[:space:]]*${1//_/-}:[[:space:]]/ { s/^.\+:[[:space:]]\+//; s/[[:space:]]\+/ /gp }" /proc/net/dev; }; grepdev br-lan
    8693264622 21875411 0 0 0 0 0 0 25554447414 27067518 0 0 0 0 0 0
    root@jj:~#

**Comment by champtar** [comment]
ping @fabys77 @jmccrohan

**Pull request closed without merging**
