### PR TITLE
prometheus-node-exporter-lua: fix netclass duplicate TYPE lines

### LINKED ISSUE #19508: prometheus-node-exporter-lua: netclass.lua may produce duplicated '# TYPE' lines
Maintainer: @champtar
Environment: Ubiquiti EdgeRouter X, OpenWrt 22.03.0 r19685-512e76967f
Package version: 2022.06.12-1

Description:

The netclass.lua collector may produce duplicated `# TYPE node_network_*` lines.
This is invalid per the [Prometheus documentation on the exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information).
> If the token is TYPE, exactly two more tokens are expected. The first is the metric name, and the second is either counter, gauge, histogram, summary, or untyped, defining the type for the metric of that name. *Only one TYPE line may exist for a given metric name.* The TYPE line for a metric name must appear before the first sample is reported for that metric name. If there is no TYPE line for a metric name, the type is set to untyped.

On my router with `prometheus-node-exporter-lua` and `prometheus-node-exporter-lua-nat_traffic` installed:

```
% wget -q http://192.168.0.254:9100/metrics -O - | grep "# TYPE" | sort | uniq -cd
      8 # TYPE node_network_address_assign_type gauge
      8 # TYPE node_network_carrier_changes_total counter
      8 # TYPE node_network_carrier_down_changes_total counter
      8 # TYPE node_network_carrier gauge
      8 # TYPE node_network_carrier_up_changes_total counter
      8 # TYPE node_network_device_id gauge
      8 # TYPE node_network_dormant gauge
      8 # TYPE node_network_flags gauge
      8 # TYPE node_network_iface_id gauge
      8 # TYPE node_network_iface_link gauge
      8 # TYPE node_network_iface_link_mode gauge
      8 # TYPE node_network_info gauge
      8 # TYPE node_network_mtu_bytes gauge
      8 # TYPE node_network_net_dev_group gauge
      8 # TYPE node_network_protocol_type gauge
      5 # TYPE node_network_speed_bytes gauge
      8 # TYPE node_network_transmit_queue_length gauge
```

Using the `inputs.prometheus' plugin of Telegraf to scrape the metrics produces an error.

```
E! [inputs.prometheus] Error in plugin: error reading metrics for http://192.168.0.254:9100/metrics: reading text format failed: text format parsing error in line 268: second TYPE line for metric name "node_network_info", or TYPE reported after samples
```

The netclass.lua collector has been developed by @rtreffer and merged in PR #18170

### PR DESCRIPTION
**Pull request by champtar**
Fixes a315c40b7232bbc83582685c98e41466d84d7a35

[initial fix]
Signed-off-by: René Treffer <treffer@measite.de>
[fixup René version]
Signed-off-by: PichetGoulu <pichet@nosuid.be>
[actual commit]
Signed-off-by: Etienne Champetier <champetier.etienne@gmail.com>

Maintainer: me

Fixes #19508

### CODE REVIEW

**Comment by champtar** [comment]
@rtreffer @PichetGoulu I took the code from #19508, please confirm I can use your Signed-off-by

**Comment by PichetGoulu** [comment]
Yes you can, thank you.

**Comment by champtar** [comment]
@rtreffer as it was your code you are fixing and you offered to make it a PR I'm assuming I have your SoB (https://github.com/openwrt/packages/issues/19508#issuecomment-1266035817)

**Comment by rtreffer** [comment]
Totally! Saw the PR and I am super happy this is happening
 Sorry for being unresponsive, I have been busy with other things and forgot about this.

**Comment by champtar** [comment]
> Totally! Saw the PR and I am super happy this is happening Sorry for being unresponsive, I have been busy with other things and forgot about this.

Can't blame anyone for being unresponsive :), this fix is old enough it can walk and talk already

**Pull request merged**
