### PR TITLE
unbound: allow forwarding to link-local and localhost IPs

### PR DESCRIPTION
**Pull request by charlessuh**
Maintainer: @EricLuehrsen
Tested: x64 / 19.07.01
Description: `valid_subnet_any` is currently used to determine whether to populate `forward-addr` or `forward-host` in `unbound.conf`.

However, `valid_subnet_any` returns "not" for some IP address like `127.0.0.1`:
https://github.com/openwrt/packages/blob/master/net/unbound/files/iptools.sh#L110-L113

As a result, you get output like `forward-host: 127.0.0.1@53` instead of `forward-addr: 127.0.0.1@53`

### CODE REVIEW

**Comment by EricLuehrsen** [comment]
What this is trying to prevent is unintentional circular DNS loops. With UCI or LuCI an amateur user can easy cause this. Configuring to be host isn't the intended fall back though. Please explain the use case that needs this, otherwise it might be best a "power user" custom setting in the extended conf file.

Style note, if it doesn't need to change to `awk` then it should stay in shell and use glob expresses.

**Comment by charlessuh** [comment]
Good point. I hadn't explicitly considered this, but now that I think about it, there /was/ sort of a "power user" setting I had to turn on in unbound in order to query localhost:

```
do-not-query-localhost: <yes or no>
      If  yes, localhost is added to the do-not-query-address entries,
      both IP6 ::1 and IP4 127.0.0.1/8. If no, then localhost  can  be
      used to send queries to. Default is yes.
```

My use case is I'm trying to forward some queries to [ipset-dns]( https://github.com/openwrt/openwrt/blob/master/package/network/services/ipset-dns/files/ipset-dns.config) running on the router itself. I had also looked at compiling in unbound's ipset support, but didn't have luck getting it to work like some [users have also reported](https://github.com/NLnetLabs/unbound/pull/28).

The reason for using `awk` is that I noticed the rest of this file uses `awk` for regular expressions so 1) I wanted to be consistent and 2) wasn't sure if `expr` or built-in shell regular expressions are supported. But happy to change it if either is not a correct assumption?

I can also just edit the unbound configuration files by hand, so this PR is not critical, but thought it'd be nice to have.

**Comment by EricLuehrsen** [comment]
Unbound 1.10.0-2 package does support ipset. Does that change what you wanted here?

**Comment by EricLuehrsen** [comment]
Maybe I didn't express my concern well. If UCI/LuCI allows 127.0.0.0/8 in the configuration, then it needs to detect it and activate the bypass option. That would allow a less than prepared new user to cause himself some grief with a simple error in LuCI. At some point, power users will need to use the `unbound_srv.conf` and `unbound_ext.conf` files to implement custom use cases. Again package 1.10.0-2 does support ipset and I wonder if that changes what you wish to achieve here.

**Comment by charlessuh** [comment]
Hi, apologies for the delayed response.

1. I've added some additional code that attempts to set `do-not-query-localhost` if forwarding to a server IP that is 127.0.0.1/8 or ::1.

2. As some [other users have reported](https://github.com/NLnetLabs/unbound/pull/28) (and I've also tried compiling in ipset support before) this support does not appear to work -- at least on OpenWrt.

	I've also tried compiling in the latest master with the heavy variant, and it still does not appear to work. The output of my `unbound -V` shows ipset support is compiled in:

	```
	Version 1.10.0  

	Configure line: --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/us r --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir= /usr/man --infodir=/usr/info --disable-nls --disable-dsa --disable-gost --enable-allsymbols --enable-ecdsa --enable-tfo-client --enable-tfo-server --w ith-libexpat=/home/cws/openwrt/staging_dir/target-x86_64_musl/usr --with-ssl=/home/cws/openwrt/staging_dir/target-x86_64_musl/usr --with-user=unbound  --with-run-dir=/var/lib/unbound --with-conf-file=/var/lib/unbound/unbound.conf --with-pidfile=/var/run/unbound.pid --enable-ipset --with-pthreads --wi th-libevent=/home/cws/openwrt/staging_dir/target-x86_64_musl/usr --with-libmnl=/home/cws/openwrt/staging_dir/target-x86_64_musl/usr --enable-event-api 
	Linked libs: pluggable-libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1g  21 Apr 2020 
	Linked modules: dns64 ipset respip validator iterator
	 TCP Fastopen feature available  

	BSD licensed, see LICENSE in source package for details. 
	Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
	```

	Have other users (to your knowledge) tested this and verified it is working successfully?

**Comment by EricLuehrsen** [comment]
Okay. I have though about this one some more. What I don't want is a one-click cyclic loop in LuCI. That leaves an amateur or a professional with glitchy Bluetooth pointer device too exposed. I would rather add `ipset-dns` as a target application. Then knowing full well there is a server at exactly its UCI configured address and port, it won't go cyclic. This is how dnsmasq is done.

**Comment by EricLuehrsen** [comment]
There were bigger fish to fry, but I have a first cut idea. With your feedback, the #12580 should be able to supersede this one.

**Pull request closed without merging**
