### PR TITLE
irqbalance: upgrade to 1.6.0

### PR DESCRIPTION
**Pull request by fantom-x**
Maintainer: @hnyman 

Upgraded from 1.2.0 to 1.6.0 to pick up
all the latest fixes and improvements

Compile-tested: ipq806x/R7800 & ipq40xx/GL-B1300
Run-tested:     ipq806x/R7800 & ipq40xx/GL-B1300

Signed-off-by: Marc Benoit <marcb62185@gmail.com>

### CODE REVIEW

**Comment by fantom-x** [comment]
This is not complete yet due to the following outstanding issues

1. The build pulls files from two locations below. Let me know the process to add them. My local build just pulls the file from GitHub and is using `PKG_MIRROR_HASH` to validate the download.

```
https://sources.openwrt.org/irqbalance-1.6.0.tar.xz
https://mirror2.openwrt.org/sources/irqbalance-1.6.0.tar.xz
```

2. What hash function is used for `PKG_SOURCE_VERSION`? I will update it properly once I know.

3. This conflicts with #11423 on the `PKG_RELEASE` line. I will fix it in due time.

**Comment by hnyman** [comment]
How does the compiled binary size (and the size of included libraries) change?

1.2.0 was the last one without a requirement for glib2 library, and including that will increase the effective size quite much.

(I also notice that your change does not add glib2 as a dependency. Is that not needed any more in 1.6.0?)

**Comment by hnyman** [comment]
To your questions:
* the source file gets downloaded/uploaded to the OpenWrt mirrors by buildbot when it does the first build pulling source out of upstream Github.
* PKG_SOURCE_VERSION is the git has of the release in upstream Github repo:
   https://github.com/Irqbalance/irqbalance/releases

**Comment by fantom-x** [comment]
Surprisingly, the file sizes did not change. I have even double checked my local changes and the build and it is indeed picking up the 1.6.0 version.

```
ipq40xx / GL-B1300

1.2.0	33,619
1.6.0	33,619

ipq806x / R7800

1.2.0	33,619
1.6.0	33,619
```

**Comment by fantom-x** [comment]
I found the problem. The build downloads **irqbalance-1.6.0.tar.xz**, but the source in that archive is **1.2.0**. It must be using `PKG_SOURCE_VERSION` to get the source code from the tree and then calls it **1.6.0**. Back to work...

```
build@06481ac4c36a:/build/tmp$ ls -la
total 60
drwxr-xr-x 3 build build  4096 Feb 25 07:38 .
drwxr-xr-x 4 build root   4096 Feb 25 07:37 ..
drwxr-xr-x 5 build build  4096 Feb 25 08:06 irqbalance-1.6.0
-rw-r--r-- 1 build build 47560 Feb 25 07:37 irqbalance-1.6.0.tar.xz
build@06481ac4c36a:/build/tmp$ head irqbalance-1.6.0/configure.ac 
AC_INIT(irqbalance,1.2.0)

```

**Comment by hnyman** [comment]
> It must be using PKG_SOURCE_VERSION to get the source code from the tree 

Sure, as the release filename in upstream repo is stupid (plain version without software name), it is not used for download. With the proto git the git hash is used to fetch the correct revision, and then it gets stored as the PKG_SOURCE file.

**Comment by fantom-x** [comment]
```
irqbalance --version
irqbalance version 1.6.0
```

Moving to 1.6.0 requires **DEPENDS:=+glib2 +libncursesw**, which looks to be ~1.2MB of additional code. I do not know what targets does **irqbalance** build for, but those should be 2 or more cores. Not sure how to get a list, but those model could already have enough storage to support the size increase.

GL-B1300 (ipq40xx) is probably the best use case here due to being 4-core and how interrupts are mapped. The default install can do 500..600 MB/s (NAT'ed and routed) LAN-to-WAN due to only a single core being utilized. Just installing and activating **irqbalance** increases the throughout to ~900..940 MB/s without any additional tuning. At that point one of my computers is running out of CPU cycles so I am not sure that the router itself is the bottleneck in this test.

```
 20,789 ./bin/packages/arm_cortex-a7_neon-vfpv4/packages/irqbalance_1.6.0-6_arm_cortex-a7_neon-vfpv4.ipk
152,192 ./bin/packages/arm_cortex-a7_neon-vfpv4/base/libncurses6_6.1-5_arm_cortex-a7_neon-vfpv4.ipk
  6,903 ./bin/packages/arm_cortex-a7_neon-vfpv4/base/terminfo_6.1-5_arm_cortex-a7_neon-vfpv4.ipk
894,559 ./bin/packages/arm_cortex-a7_neon-vfpv4/packages/glib2_2.58.3-5_arm_cortex-a7_neon-vfpv4.ipk
```

**Comment by hnyman** [comment]
Sounds like you did not disable GUI in config if libncursesw is needed.

I have avoided updating from 1.2.0 to 1.3.0 and further, as I noticed the glib2 requirement.

Does 1.6.0 bring you visible benefits compared to 1.2.0?

**Comment by fantom-x** [comment]
> Sounds like you did not disable GUI in config if libncursesw is needed.

I was hoping that the build would honour the flag that was added in 1.3.0 **--without-irqbalance-ui** (I pushed the current code changes). I will track this down.

> I have avoided updating from 1.2.0 to 1.3.0 and further, as I noticed the glib2 requirement.

Three years later the routers got bigger and more powerful. This package is only needed for the big ones routers. Is having two packages an option: **irqbalanace-tiny** / **irqbalance** or **irqbalance** / **irqbalance-glib2**?

> Does 1.6.0 bring you visible benefits compared to 1.2.0?

Yes, it does. It seems to keep IRQ's balanced across multiple cores better than the old one. Below are the results of an 8h run for hard and soft IRQ's with the totals per a CPU under each table. 

```
           CPU0       CPU1       CPU2       CPU3       
 18:    2855396    2855403    2855403    2855403     GIC-0  20 Level     arch_timer
 22:     131609     145134     115210     143152     GIC-0 270 Level     bam_dma
 23:    3564096    5054513    1674494    3655303     GIC-0 127 Level     78b5000.spi
 24:          0          0          0          0     GIC-0 239 Level     bam_dma
 25:          5          0          0          0     GIC-0 139 Level     msm_serial0
 42:         13          0          0          0     GIC-0 200 Level     ath10k_ahb
 59:         17          0          0          0     GIC-0 201 Level     ath10k_ahb
 60:   38214400   40581803   39441144   53674605     GIC-0  97 Edge      edma_eth_tx0
 61:          2          0          2          0     GIC-0  98 Edge      edma_eth_tx1
 62:   15297209   15256067   12981549   14432550     GIC-0  99 Edge      edma_eth_tx2
 63:          0          0          0          2     GIC-0 100 Edge      edma_eth_tx3
 64:        334        150        246        100     GIC-0 101 Edge      edma_eth_tx4
 65:     342751     415575     381666     407722     GIC-0 102 Edge      edma_eth_tx5
 66:   19292172   20189935   15563446   13776997     GIC-0 103 Edge      edma_eth_tx6
 67:          0          0          0          0     GIC-0 104 Edge      edma_eth_tx7
 68:        200        163        180        152     GIC-0 105 Edge      edma_eth_tx8
 69:          0          0          0          0     GIC-0 106 Edge      edma_eth_tx9
 70:   29600642   20318760   19828682   23625770     GIC-0 107 Edge      edma_eth_tx10
 71:          0          0          0          0     GIC-0 108 Edge      edma_eth_tx11
 72:        440        514        193        393     GIC-0 109 Edge      edma_eth_tx12
 73:          2          0          2          0     GIC-0 110 Edge      edma_eth_tx13
 74:   28248320   29337848   23986959   19990497     GIC-0 111 Edge      edma_eth_tx14
 75:          0          0          0          2     GIC-0 112 Edge      edma_eth_tx15
 76:   22596709   11893856   16558512   13456539     GIC-0 272 Edge      edma_eth_rx0
 78:   18051939   21699836   18579228   13062310     GIC-0 274 Edge      edma_eth_rx2
 80:   13033751   12522131   14228854   12746920     GIC-0 276 Edge      edma_eth_rx4
 82:   15831384   15262694   21334790   15970255     GIC-0 278 Edge      edma_eth_rx6
 92:          1          0          0          0   msmgpio   5 Edge      keys
 93:          1          0          0          0   msmgpio  63 Edge      keys
 94:          0          0          0          0     GIC-0 164 Level     xhci-hcd:usb1
 95:          0          0          0          0     GIC-0 168 Level     xhci-hcd:usb3
IPI0:          0          0          0          0  CPU wakeup interrupts
IPI1:          0          0          0          0  Timer broadcast interrupts
IPI2:    4574137    4572578    5292729    5113115  Rescheduling interrupts
IPI3:         11         17         19         16  Function call interrupts
IPI4:          0          0          0          0  CPU stop interrupts
IPI5:     355533     332942     339236     337252  IRQ work interrupts
IPI6:          0          0          0          0  completion interrupts
Err:          0

CPU0=211991077
CPU1=200439929
CPU2=193162568
CPU3=193249076
```

```
                    CPU0       CPU1       CPU2       CPU3       
          HI:          0          0          0          0
       TIMER:    2852534    2828993    2828651    2828859
      NET_TX:   25940110   27531909   22645331   27606140
      NET_RX:  171848272  159275565  154978781  153595893
       BLOCK:          0          0          0          0
    IRQ_POLL:          0          0          0          0
     TASKLET:     214379     227498     204062     232511
       SCHED:    2072205    2066555    2081877    2029682
     HRTIMER:          0          0          0          0
         RCU:    1698432    1821868    1694683    1846376

CPU0=204625935
CPU1=193752393
CPU2=184433396
CPU3=188139473
```

**Comment by fantom-x** [comment]
I have removed the dependency on **libncurses**. Do you know how to use the package build system to statically link **glib2**? **irqbalance** is using very little of **glib2**, so the final size might not be too big. 
I found I could use `PKG_BUILD_DEPENDS` for build time dependencies, but cannot find another package that would use static linking.
```
ldd /usr/sbin/irqbalance
	/lib/ld-musl-armhf.so.1 (0xb6e85000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xb6d8a000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6d6e000)
	libc.so => /lib/ld-musl-armhf.so.1 (0xb6e85000)
```

**Comment by fantom-x** [comment]
BTW, there are quite a few packages depending on **glib2** already.

```
grep -rl glib2 . | grep "/Makefile"
./net/ksmbd-tools/Makefile
./net/nbd/Makefile
./net/keepalived/Makefile
./net/gnunet/Makefile
./net/sshfs/Makefile
./net/seafile-ccnet/Makefile
./net/seafile-server/Makefile
./net/irssi/Makefile
./net/bitlbee/Makefile
./net/modemmanager/Makefile
./utils/mbtools/Makefile
./utils/irqbalance/Makefile
./utils/qemu/Makefile
./utils/mc/Makefile
./utils/open-vm-tools/Makefile
./utils/bluez/Makefile
./utils/gammu/Makefile
./libs/libsoup/Makefile
./libs/glib2/Makefile
./libs/libsearpc/Makefile
./libs/libgee/Makefile
./libs/libgabe/Makefile
./libs/vips/Makefile
./libs/libmbim/Makefile
./libs/quasselc/Makefile
./libs/loudmouth/Makefile
./multimedia/gstreamer1/Makefile
./multimedia/grilo/Makefile
./multimedia/grilo-plugins/Makefile
./admin/syslog-ng/Makefile
./admin/gkrellmd/Makefile
./lang/vala/Makefile
./sound/pulseaudio/Makefile
./devel/pkg-config/Makefile

```

**Comment by hnyman** [comment]
> Do you know how to use the package build system to statically link glib2? 

Sorry, not my specialty. 

> there are quite a few packages depending on glib2 already.

Sure, but those are not very common packages.

> is having two packages an option: irqbalanace-tiny / irqbalance

I though that already before you mentioned it. That is likely the best solution.
I am uncomfortable with forcing large glib2 stuff for all users, but providing the small-footprint old 1.2 as tiny might be viable.

**Comment by keithwky** [comment]
@fantom-x You can check ksmbd-tools as example of pkg build with static glib2 https://github.com/openwrt/packages/commit/664479fa8965c469e552eeec94e7678c28bc157b

**Comment by fantom-x** [comment]
Thx, not sure how I missed that one...

**Comment by fantom-x** [comment]
I will update the PR once I complete an e2e test.

```
52,964 irqbalance_1.6.0-6_arm_cortex-a7_neon-vfpv4.ipk

1.2.0	 33,619
1.6.0	128,438
```
```
# ls -la irqbalance 
-rwxr-xr-x    1 root     root        128436 Feb 28 18:47 irqbalance
# ldd irqbalance 
	/lib/ld-musl-armhf.so.1 (0xb6ecd000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6eb1000)
	libc.so => /lib/ld-musl-armhf.so.1 (0xb6ecd000)
# ./irqbalance --version
irqbalance version 1.6.0
```

**Comment by fantom-x** [comment]
It is actually smaller when stripped. Let me know if anything else is missing.

```
1.2.0 size: 33,619
1.6.0 size: 99,539
```

**Comment by hnyman** [comment]
Looks good. I will test it myself.

Btw, did you experiment further optimization with compiler and linker flags, as done in the referenced ksmhd commit?

**Comment by fantom-x** [comment]
Experiment why? I needed to pick up as little if glib2 as possible and did not see anything else that was required.

**Comment by fantom-x** [comment]
I see that **buildpr** is complaining.  I have so far built ipq806x and ipq40xx with no issues. Building a mips_24c now just like the pr builder.

**Comment by hnyman** [comment]
I have compiled and installed this to ipq806x/R7800 and mvebu/WRT3200ACM

Did you succeed with ath79 (for mips_24kc)?

```
ld_dir/staging_dir/toolchain-mips_24kc_gcc-8.3.0_musl/lib /home/build/build_dir/staging_dir/target-mips_24kc_musl/usr/lib/libglib-2.0.a /home/build/build_dir/build_dir/target-mips_24kc_musl/libiconv/libiconv.a -lm
mips-openwrt-linux-musl-gcc: error: /home/build/build_dir/build_dir/target-mips_24kc_musl/libiconv/libiconv.a: No such file or directory
Makefile:559: recipe for target 'irqbalance' failed
make[5]: *** [irqbalance] Error 1
```

My hunch is that the error is due to you trying to use "build_dir" instead of "staging_dir". As the buildbot (and buildpr) uses the SDK from phase1, the packages built from the main OpenWrt source base are not compiled again by the phase2 packages buildbot.

Additionally, isn't the whole iconv needed just for GUI?  Should it be disabled?  And when looking at the other packages that mention iconv, there is usually also the nls.mk define to set the config options.

**Comment by fantom-x** [comment]
> Did you succeed with ath79 (for mips_24kc)?

Yup, the local build succeeded.

> Additionally, isn't the whole iconv needed just for GUI? Should it be disabled?

**--without-irqbalance-ui** takes care of the UI. iconv is brought in by these. 

```
/build/openwrt19.07/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: /build/openwrt19.07/tmp/ccVkDdtV.ltrans0.ltrans.o: in function `close_converter':
<artificial>:(.text+0xae2): undefined reference to `libiconv_close'
/build/openwrt19.07/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: /build/openwrt19.07/tmp/ccVkDdtV.ltrans0.ltrans.o: in function `try_conversion':
<artificial>:(.text+0xaf2): undefined reference to `libiconv_open'
/build/openwrt19.07/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: /build/openwrt19.07/tmp/ccVkDdtV.ltrans0.ltrans.o: in function `strdup_convert':
<artificial>:(.text+0x5156): undefined reference to `libiconv'
/build/openwrt19.07/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: /build/openwrt19.07/tmp/ccVkDdtV.ltrans0.ltrans.o: in function `g_convert.constprop.33':
<artificial>:(.text+0x5490): undefined reference to `libiconv'
/build/openwrt19.07/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/lib/gcc/mips-openwrt-linux-musl/7.5.0/../../../../mips-openwrt-linux-musl/bin/ld: <artificial>:(.text+0x554a): undefined reference to `libiconv'
```

> And when looking at the other packages that mention iconv, there is usually also the nls.mk define to set the config options.

I will add it.

**Comment by fantom-x** [comment]
It builds now.

**Comment by hnyman** [comment]
Ok, let's merge it then.
Thanks for your work.

**Pull request merged**
