### PR TITLE
ddns-scripts: update to version 2.4.2-1

### PR DESCRIPTION
**Pull request by chris5560**
* fix Makefile to force compression of tld_names.dat reported in OpenWrt Ticket 19597
* change default of retry_count to "0" (retry endless) suggested by Henning Schild
* updated tld_names.dat include changes until 07.05.2015

Signed-off-by: Christian Schoenebeck <<christian.schoenebeck@gmail.com>>

### CODE REVIEW

**Comment by hnyman** [comment]
Two comments regarding retry_count 0 :
* after setting retry_count = 0, the line 313 looks suspicious:
https://github.com/chris5560/openwrt-packages/blob/8161cba303ad1b30ce157f004a2627977d26f9c3/net/ddns-scripts/files/dynamic_dns_updater.sh#L313
	[ $retry_count -gt 0 -a $ERR_UPDATE -gt $retry_count ] && \

  I think that it will always fail.
  Should it be "-ge 0" (instead of "-gt") now that it is 0 ???

* Other observation is that having infinite retry loop may lead into network congestion (or even "ddos attack" like behaviour. Typically there should be an increasing delay between retry attempts, because there usually is some real reason why the attempt fails. That is the behaviour e.g. with TCP/IP retransmits. Maybe you should use a "sleep $ERR_UPDATE" type of timer?

  Some links on the subject:  http://www.pcvr.nl/tcpip/tcp_time.htm 
http://en.wikipedia.org/wiki/Exponential_backoff

**Comment by chris5560** [comment]
It's not a general setting it's only the (old from ddns-scripts 1.x) default, if not set inside configuration.
So line 313 make still sense if retry_count is set (via /etc/config/ddns) to something gt 0.

You are right looking on network congestion but 99% of ddns-scripts problems are problems with the used provider e.g. lost ppp or satellite communication so there is anyway no package send to public network. I'm using 6to4 communication on my IPv4 provider and sometimes IPv6 communication is not working. Before setting retry_count to 0 the IPv6 ddns-scripts configuration died without my notice. OK I should monitor my syslog continously ;-).

I've no idea and no user feedback, if it make sense to wait after each error a longer time before retry.
Something like $ERR_UPDATE * $RETRY_SECONDS.
But looking on a lost ppp or satellite connection after an longer disconnect will wait an additional long time before retrying. That makes no sense for me.

I'm thinking about defining a minimum RETRY_SECONDS between 30 - 60 seconds. What do you think ?

**Comment by sbyx** [comment]
@chris5560 shall I merge this or not?

**Comment by chris5560** [comment]
@sbyx please merge. thanks.

**Pull request merged**
