### PR TITLE
multimedia/crtmpserver: Remove from repo

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @heil 
Compile tested: N/A
Run tested: N/A

Description:
crtmpserver has been dead upstream since years and it's more often broken
than actually working (compiling). PR#7512 also got merged even despite not
compiling properly. It's has also been missing in releases because it doesn't
even compile so at this point we can most likely safely assume that the userbase
is close to none.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@thess @hnyman @cshoredaniel 
Can we please remove this one out once and for all

**Comment by cshoredaniel** [comment]
AFAIK I have no access to do that, but I'd like to see it removed too, for the reasons you state.

**Comment by neheb** [comment]
I would as well given than nobody has complained.

On a sidenote, https://github.com/shiretu/crtmpserver seems to be a more up to date version.

**Comment by neheb** [comment]
If for whatever reason someone wants to update it instead, there's this: https://github.com/neheb/packages/commit/34090f22785c13865b41234ffc8c8b3ed908006d

**Comment by diizzyy** [comment]
@thess @hnyman 
Ping

**Comment by diizzyy** [comment]
Ping again...

**Comment by neheb** [comment]
This would need to be rebased.

Let's wait until after the release. So that we can get download numbers. Then we can remove.

**Comment by diizzyy** [comment]
Since it's been unavailable for the 18.X-series so I seriously doubt you need to get any download numbers but since you went ahead I'm closing this

**Pull request closed without merging**
