### PR TITLE
ddns-scripts: update dnsexit.com update URL+response

### PR DESCRIPTION
**Pull request by zorxd**
Otherwise the script was stuck in an update loop.

### CODE REVIEW

**Comment by champtar** [comment]
hi @zorxd, you forgot to increase ```PKG_RELEASE``
@chris5560

**Comment by zorxd** [comment]
OK thanks done

**Comment by chris5560** [comment]
Hi Xavier,

thanks for your.
Looking into the doc-file you find "Any code > 2 means errors"
Because dnsexit.com using "4=" to accept the update but asking to save their resources, the best way is to remove error checking completely for dnsexit.
So please remove the "0=|...." sting completely.
That's the way I would handle #4082

**Comment by zorxd** [comment]
I checked the official client. They consider valid any answer starting with the equal sign followed by a number. I don't think the current ddns-scripts code allows that, which is why I coded only for numbers up to 6. My first goal was to handle code =4, which they currently seem to use when the IP address is the same.

Removing the check for the answer works too, however I was afraid we would miss some other kind of failures. I made the change.

**Comment by chris5560** [comment]
OK for me to merge. Thanks

@zorxd
looking into log at #4082 you can see that dnsexit answered "4=..."
ddns-scripts verify the answer with: grep -i -E "$UPD_ANSWER" $DATFILE
you find it inside dynamic_dns_functions.sh at line 881.
$UPD_ANSWER is filled with the string from services file.

**Pull request merged**
