### PR TITLE
collectd: add dhcpleases plugin

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Count the current dhcpleases. Currently, we use a bash script
that does the same job (Freifunk Berlin). We want to use native
collectd plugin for that.

Maintainer:@hnyman

### CODE REVIEW

**Comment by BKPepe** [comment]
Are we sure that we want to merge and have new features in OpenWrt 19.07? :thinking:

**Comment by PolynomialDivision** [comment]
> Are we sure that we want to merge and have new features in OpenWrt 19.07? thinking

Hmmm. I would be happy to have that statistics in 19.07 since we build our community wireless mesh network on it.
But if 20.X will be soon released, I'm also fine. ;)

**Comment by hnyman** [comment]
We can later backport minor features, if there is no negative feedback from master once it is there.

**Comment by PolynomialDivision** [comment]
Okay, then I will close this and reopen later. ;)

**Pull request closed without merging**
