### PR TITLE
nginx: nginx-dav-ext-module: update to v2.0.0

### PR DESCRIPTION
**Pull request by zhouruixi**
Maintainer:  @Ansuel

Compile and Run tested:  x86_64, arm with Wrt1200ac, 7f3facfce29639ec50677aa2b0eecebe259aa4d3

Description: nginx: nginx-dav-ext-module: update to v2.0.0

Signed-off-by: Ruixi Zhou <zhouruixi@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Maintainer is @Ansuel

**Comment by zhouruixi** [comment]
There is some issue with the V2.0.0 version， closed for now.
* can't access some floder
* can't show hidden files

**Comment by vitaliy-kuzmich** [comment]
@zhouruixi Hello, when do you plan to release with this feature ? https://github.com/openwrt/packages/blob/6c8460432090dc718776a5c41d32960ac6afd440/net/nginx/Makefile#L408

**Comment by zhouruixi** [comment]
I asked the auther for this problem, but no reply. So I am still waiting.

**Pull request closed without merging**
