### PR TITLE
 python,python3: define config option for bluetooth support

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me 
Compile tested: https://github.com/lede-project/source/commit/b0b289ea45d5917f5ba75701db5a66863d9a7dfb ar71xx
Run tested: N/A

---------------------------------------

It was reported via
https://github.com/openwrt/packages/pull/5122#issuecomment-347395472
that if bluez-libs is selected as an installable package,
then the error below will show up:
```
     * satisfy_dependencies_for: Cannot satisfy the following dependencies for python-light:
     *      bluez-libs *
     * opkg_install_cmd: Cannot install package python-light.
```
    
This looks like a limitation in the design of package deps,
and maybe a misuse of conditional deps (i.e. PACKAGE_bluez-libs:bluez-libs).
    
So, to fix this, an idea we're adding an extra symbol
that enfoces installation of bluez-libs if selected.
    
We also need to add a way to disable bluetooth build
if PYTHON(3)_BLUETOOTH_SUPPORT is de-selected.
Otherwise, bluetooth is installed and the socket
module is broken due to linker errors.
    
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
Need to check something first

**Comment by commodo** [comment]
@lynxis 
I've added commit 379ebbfe42ad21fdf465d58f52805cb1f12bebfd to this PR, to fix the build with Python/Python3 

can you take a look and see if you agree ? :)

**Comment by commodo** [comment]
@champtar @lynxis 
any more thoughts on this ? :)

**Comment by champtar** [comment]
@commodo for me the bug should be fixed where it is, not worked-around ;)
If I understand this is only affecting the SDK? if this is the case you can remove the travis patch and I will merge this PR (if you don't have the time to investigate more)

**Comment by commodo** [comment]
it could be a bug with the SDK ;
in my case, the SDK works fine on Ubuntu 17.04;
i'll try to get a Ubuntu 12.04 or 14.04 image to try it out 

but in the meantime, i'm fine to remove the commit and see later about fixing the SDK

**Comment by champtar** [comment]
And now it's building fine ... ;)

**Comment by commodo** [comment]
hmm ; that's weird
either travis changed something or something in the SDK changed

either way i'm happy that it works

**Pull request merged**
