### PR TITLE
[openwrt-18.06] python,python3: Fix ctypes.util.find_library()

### LINKED ISSUE #9448: <python - 2.7.16-7>:ctypes.util.find_library('c') does not work
Maintainer: @\<jeffreyto> 
Environment: (x86-64, generic, build trunk)

Description:
The python function ctypes.util.find_library() depends on platform specific code that seems to be not working in OpenWrt. The function ctypes.util.find_library() is supposed to return a string which is the filename of the system library referenced in the passed string argument. I have tried ctypes.util.find_library('c') and ctypes.util.find_library('bz2') and neither of them work. The issue can be reproduced using the python code block below
``
root@OpenWrt:/lib# python
Python 2.7.16 (default, Jul 08 2019, 05:38:51) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> import ctypes.util
>>> name = ctypes.util.find_library('c')
>>> print(name)
None
>>> import os
>>> print os.name
posix
>>> import sys
>>> print(sys.platform)
linux2
>>> name = ctypes.util.find_library('bz2')
>>> print(name)
None
>>> 

```
I found libc.so in /lib on my OpenWrt installation and libbz2.so.1.0 is in /usr/lib/.

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me, @commodo 
Compile tested: x86-generic, 18.06.4 sdk
Run tested: x86-generic, 18.06.4 (qemu)

Description:
Python's ctypes.util.find_library() function currently [doesn't work for musl libraries/systems][1].

This adds a patch to fix this function, based on a [patch from Alpine Linux][2].

Fixes #9448.

[1]: https://bugs.python.org/issue21622
[2]: https://git.alpinelinux.org/aports/tree/main/python2/musl-find_library.patch

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
Since this is a bug fix, I think it would be good to get it out for 18.06.

**Comment by BKPepe** [comment]
I can cherry-pick it to openwrt-18.06 based on your request in the previous pull request, but if @commodo is fine with your changes, I will merge it.

**Comment by jefferyto** [comment]
I refreshed the patch so the offsets are slightly different, but cherry-picking the commit would also work.

@commodo Are you ok with merging this fix for 18.06?

**Comment by commodo** [comment]
> @commodo Are you ok with merging this fix for 18.06?

fine from my side;

**Pull request merged**
