### PR TITLE
gpsd: Update to 3.20, add/refresh patches

### LINKED ISSUE #10993: gpsd: build fails as of missing python distutils.sysconfig
Maintainer: @psidhu @p-wassi 
Environment: OpenWrt master (around 1.1.2020); mvebu-cortexa9

Description: building gpsd fails with a missing dependency to python module distutils.sysconfig

```
scons: Reading SConscript files ...
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py):
  File "/mnt/local/btrfs/build/freifunk/ffberlin/firmware/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/gpsd-3.19/SConstruct", line 46:
    from distutils import sysconfig
make[3]: *** [Makefile:148: /mnt/local/btrfs/build/freifunk/ffberlin/firmware/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/gpsd-3.19/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 2
make[3]: Leaving directory '/mnt/local/btrfs/build/freifunk/ffberlin/firmware/packages/packages/utils/gpsd'
time: package/feeds/packages/gpsd/compile#0.42#0.10#0.51
make[2]: *** [package/Makefile:113: package/feeds/packages/gpsd/compile] Error 2
```

Installing the python-module via the hosts apt-get fixes the build, but this seems not the way to go.

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @psidhu 
Compile tested: armvirt-64, 2020-01-15 snapshot sdk
Run tested: none

Description:
New patches (both for SConstruct):

* Do not import from distutils. Since Python support/modules are not built, there is no need to import from distutils. (Importing from distutils may prevent the package from being built on systems without a full distutils module, e.g. Debian with python3-minimal.)

  I have added back the import in places where it may be helpful to have, if scons is run manually.

  Fixes #10993.

* Do not check the size of `time_t`. The way this is done is to compile and run a test program; this [fails][1] when cross-compiling.

  This doesn't appear to affect any functionality (other than missing a compile-time warning that things will fail in 2038 if `time_t` is too small).

[1]: https://gitlab.com/gpsd/gpsd/issues/48

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I've fixed the second issue (size of `time_t`) [upstream](https://gitlab.com/gpsd/gpsd/merge_requests/65), but the full patch (adapted for 3.20) would only accomplish the same thing as the patch in this PR, i.e. skip the check.

**Comment by neheb** [comment]
btw this broke olsrd: https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/routing/olsrd/compile.txt

**Comment by ElonH** [comment]
@neheb @zioproto 
I got same error on x86_64. I check the code and find that it may be not only in 3.20 version also 3.19.
1 year ago, [this commit](https://gitlab.com/gpsd/gpsd/-/commit/65f9daadd1d82e7ba77510e5f3a193bbe6d32606#fbec23e759c01a5d296e7d1e3a17e9b131df6ae4_84_84) changed type of `timestamp_t`

**Comment by jefferyto** [comment]
openwrt-routing/packages#547 is probably the better place to track the olsrd build failure.

@cotequeiroz has a patch (OLSR/olsrd#79) - hopefully it works :joy:

**Pull request merged**
