### PR TITLE
stubby: update to version 0.3.0

### PR DESCRIPTION
**Pull request by jonathanunderwood**
Signed-off-by: Jonathan G. Underwood <jonathan.underwood@gmail.com>

Maintainer: me
Compile tested: x86
Run tested: x86

Description: update to version 0.3.0. This version uses the CMake build system.

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
Now tested on x86 and ready for merge.

**Comment by jmarcet** [comment]
It is falling with `Could not schedule query: The library did not have the requested API feature implemented.`  on x86-64 for me.

**Comment by jmarcet** [comment]
Reverting this update does not fix it yet, so the issue is in getdns probably.

**Comment by jmarcet** [comment]
Indeed, stubby with getdns-1.6.0 is failing with the above error, reverting #12679 fixes it.

**Pull request merged**
