### PR TITLE
mosquitto: make DNS SRV support optional

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: @karlp 
Compile tested: LEDE r2987-25200ae on x86/64 and Octeon

### CODE REVIEW

**Comment by karlp** [comment]
Is the motivation here to avoid the 25k of libcares?  How about simply dropping SRV support entirely?  This seems like an unnecessary complication of options.  It's disabled by default in upstream 1.5.x branch.

**Comment by stintel** [comment]
My main motivation is indeed size + the fact SRV lookup is not used in the daemon. So if someone wants just the lib or run the daemon, SRV support is not useful and adds useless size.

For clients I can still see the advantage, so I would definitely not drop it completely.

**Comment by karlp** [comment]
The daemon package doesn't have the libcares dependency now, it's only for the library and client tools.  I had tended to believe that given the size of openssl, libcares was largely irrelevant.  Would it perhaps make sense to just make  cares optional on the "nossl" ("minimal") library package?

**Comment by hauke** [comment]
This does not apply any more, please rebase, I would also suggest to completely remove the libcares dependency.

**Pull request closed without merging**
