### PR TITLE
micropython-lib: add 0 return code for `install` rule/script

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @roger- 
Compile tested: https://github.com/lede-project/source/commit/c1b12aa838587952b269a75ad278e8805aa9a65f  ar71xx
Run tested: N/A

----------------------------------------------------------
I get these weird errors:
```
Makefile:8: recipe for target 'install' failed
make[4]: *** [install] Error 123
```

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by roger-** [comment]
Does this fix the issue you mentioned?

**Comment by commodo** [comment]
@roger- 
yes it does ; 
nope, haven't tried PR-ing ; this was a bit more comfortable for me

i'll send a PR there too
do we drop this or go only through upstreaming this and updating it from there ?

**Comment by roger-** [comment]
I think upstream would also appreciate the bug fix, so I think it's better to submit it there and then we'll update this package.

**Comment by commodo** [comment]
now that i think about it more
my fix more likely hides any issues that could have gone wrong with the `install` build rule

i'll have to think about it a bit more

**Comment by commodo** [comment]
after that i will push something to micropython-lib

**Comment by roger-** [comment]
Ah, okay.

Thanks and let me know if you come up with something.

**Comment by commodo** [comment]
Looked a bit closer.
The errors are (let's say) false positives.
I saw them before but did not take much notice:

```
cp: './weakref.py' and '/home/sandu/work/lede/build_dir/target-mips_24kc_musl-1.1.16/micropython-lib-1.8.6-f81e979c56dddb771ad36ec381b7f2c6cd12111f-f81e979c56dddb771ad36ec381b7f2c6cd12111f/_install_tmp/weakref.py' are the same file
cp: './xmltok.py' and '/home/sandu/work/lede/build_dir/target-mips_24kc_musl-1.1.16/micropython-lib-1.8.6-f81e979c56dddb771ad36ec381b7f2c6cd12111f-f81e979c56dddb771ad36ec381b7f2c6cd12111f/_install_tmp/xmltok.py' are the same file
cp: './zipfile.py' and '/home/sandu/work/lede/build_dir/target-mips_24kc_musl-1.1.16/micropython-lib-1.8.6-f81e979c56dddb771ad36ec381b7f2c6cd12111f-f81e979c56dddb771ad36ec381b7f2c6cd12111f/_install_tmp/zipfile.py' are the same file
```

I'm guessing it's because the `PREFIX` and the build dir have a common path;
PREFIX is provided via the package Makefile as  `PREFIX=$(PKG_BUILD_DIR)/_install_data`

so, it looks like the `find` command eventually finds the files in the `_install_data` folder [which is on the same level as the other lib folders ] and tries to copy some files to themselves, which is an error [ one that could be ignored or fixed ; either way it does not make much difference in this case ]

i think the sanest thing to be done, is to throw-away that find logic, and just list the directories to install
while automagic is nice sometimes, here it seems to have these weird side-effects

**Pull request closed without merging**
