### PR TITLE
forked-daapd: Update to 25.0

### PR DESCRIPTION
**Pull request by ejurgensen**
Signed-off-by: Espen Jürgensen <espenjurgensen+openwrt@gmail.com>

-------------------------------

Maintainer: Espen Jürgensen / @ejurgensen
Compile tested: ar7xxxx, OpenWRT trunk
Run tested: no

Description:
Version update

### CODE REVIEW

**Comment by hnyman** [comment]
Please set PKG_MIRROR_HASH to enable buildbot source download caching:
https://travis-ci.org/openwrt/packages/builds/257449666#L2185

> PKG_MIRROR_HASH is missing, set to c2b14595761d250a168d9dfb1f93d0ff969e456e6761b251d530a6b49284589d

You could also switch the URL to use https instead of git, so that it is more friendly to corporate firewalls
https://github.com/openwrt/packages/pull/4628/files#diff-a913eeeeab5a4b57215ea11b4d28e525R15

**Comment by diizzyy** [comment]
Since you're the author, please provide a proper tarball (xz preferably)

**Comment by ejurgensen** [comment]
Ok, updated. Don't know how to offer xz from Github? Also not sure I understand what Travis is complaining about - something about my github name and my real name being different?

I actually just copied the approach from another Makefile (shairport-sync) in my previous pr. I noticed that there are many different ways of using Github as a source in the Makefiles, perhaps you could consider a Github macro like you have for gnu, or a note in contributing.md about the right way to do it?

The copyright thing is also not quite obvious from the guide: "An up-to-date copyright notice. Use OpenWrt if no other present or supply your own."

**Comment by diizzyy** [comment]
Well, uhm.. you can't remove the copyright but omit your own/your changes. :-)
I think this is what you're looking for: https://help.github.com/articles/creating-releases/

**Comment by ejurgensen** [comment]
Sorry, don't get it? What does "you can't remove the copyright but omit your own/your changes" mean?

I release on github exactly the same way I have always done (and others before me), so I don't get the problem. There are plenty of releases as you can see:
https://github.com/ejurgensen/forked-daapd/releases

**Comment by diizzyy** [comment]
Leave the copyright line alone and add your own or don't touch anything at all.
Those are rolling tarballs (ie not static ones) so if github decides to change something in their infrastructure (such as compression lib) checksum will mismatch.

**Comment by ejurgensen** [comment]
I won't change the way I release upstream, but I will adjust the Makefile any way you want. It would be most helpful if you could link to some other package Makefile that uses github in a "best practice" manner - then I will just copy that approach.

I have put back in the original copyright notice. I still don't understand the feedback you are giving me on that:
1. It's pretty much the opposite of the reply I got on one of the previous version updates: https://github.com/openwrt/packages/pull/2662
2. I think what I did was what CONTRIBUTING.md says: "An up-to-date copyright notice. Use OpenWrt if no other present or supply your own." - while omitting the year change means it is not up-to-date?
3. The Makefile for this package has always been provided by me, so the previous copyright notice was also from a PR by me - so what's changed?

**Comment by hnyman** [comment]
> Also not sure I understand what Travis is complaining about - something about my github name and my real name being different?

Most likely because you have not set your real name properly in your local git client, so the original git commit data has "ejurgensen" as the author instead of "Espen Jürgensen" that is in the signed-off-by line.
https://git.lede-project.org/?p=feed/packages.git;a=commit;h=49186dfaefa40fca79222b7fed8dbeec567dc538

In recent packages changelog, you are the exception without a proper real name: https://git.lede-project.org/?p=feed/packages.git;a=shortlog 
(additionally, "champtar" has that username for Github merge commits (due to missing real name in github?), but his real name is used for his original commits)

>  so what's changed?

It had long been customary to copy the "standard" Openwrt copyright header to new packages, like you have done in 2014, and the copyright years were bumped along the new commits (like you have done in 2016). But since the Openwrt-LEDE split in May 2016, that has not been quite logical any more, as the packages feed is shared with Openwrt and LEDE, and many package maintainers are working only with LEDE-base systems nowadays. And as most maintainers have no contractual relationship with either Openwrt or LEDE, it seems quite unnecessary to assign away the original copyright (from you). So, the existing copyright messages have been mostly left intact, and optionally a new line added about your copyright. Or for new packages, just the author's copyright.  

Openwrt and LEDE are supposed to merge again, so let's see how the copyright practice evolves. 

Regarding sources, tarballs are preferred (compared to git checkout). In general, xz is preferred as it is smallest, then bz2 and finally gz (that is largest). But I think that github only creates gz by default.

Your current Makefile version looks good enough, so let's merge it.

**Comment by ejurgensen** [comment]
Thanks for a good explanation. I have not followed the Openwrt/LEDE thing, but I understand why the copyright becomes an issue. Maybe you should consider updating CONTRIBUTING.md.

You are right about my git client name, I didn't think of that.

**Comment by thess** [comment]
@ejurgensen - To offer an **.xz** tarball, I usually download the **.gz** and recompress it using xz
Example: 
``
wget -O - https://github.com/ejurgensen/forked-daapd/archive/25.0.tar.gz | gunzip | xz > forked-daapd-25.0.tar.xz
``

Then, on GitHub, _edit_ your release and add the additional archive,

This may not be the simplest way, but I've used it for other projects OK.

**Pull request merged**
