### PR TITLE
Sysrepo update

### PR DESCRIPTION
**Pull request by mislavn**
Maintainer: @mislavn
Compile tested: Marvell Armada 37x/38x/XP / x86_64 docker, lede master
Run tested: SolidRun ClearFog Base / x86_64 docker, lede master

Description:

1) Updated the Sysrepo/Netopeer2 packages with the latest release of Sysrepo, Libyang, Libnetconf2 and Netopeer2 (https://github.com/sysrepo/sysrepo/releases/tag/v0.7.0).

2) Change package source/subdir format to: 
'$(PKG_NAME)-$(PKG_VERSION)-$(PKG_SOURCE_VERSION)'

3) Replace patch in Sysrepo for auto generated protobuf files.

3) Add patch to Sysrepo for missing struct ucerd.

4) Add new package libredblack. When Sysrepo was linked with '-libavl', a sysrepo application would crash if it would get linked with '-lubox' also, so libredblack replaces libavl from now on.

Also libyang introduced some breaking changes and all other libraries depend on it, so should I squash all of the patches into one patch?

### CODE REVIEW

**Comment by mislavn** [comment]
Also libredblack is added with sysrepo patch, should I break that into a new git patch?

**Comment by diizzyy** [comment]
Please change packaging of source code to xz instead of bz2, it's the preferred archive format since ~1y back.

**Comment by mislavn** [comment]
> Please change packaging of source code to xz instead of bz2, it's the preferred archive format since ~1y back.

OK.

Also there was a problem with the Sysrepo release https://github.com/sysrepo/sysrepo/pull/921

I would like to wait for this to get resolved before merge. It should be fixed in the next few days.

**Comment by mislavn** [comment]
Hi,

I made the request changes, also I separated the packages sysrepo and libredblack into two patches.

Also I made some other small changes like package dependency or add new patches, the rest is the same.

Regards,
Mislav

**Comment by champtar** [comment]
Hi @mislavn 
please have a look at Travis errors

**Comment by mislavn** [comment]
Hi @champtar ,

I fixed the failed buid, also can you wait a few more days, I need to discuss some changes with other developers on the project.

**Comment by mislavn** [comment]
Hi @champtar,

we are fine with the changes now.

The only thing to discuss now is if commit's libyang, libnetconf2, sysrepo and netopeer2 should be squashed because they all depend on libyang and libyang has introduced some breaking changes.

If somebody made a git-bisect it will fail if the current hash lands between libyang and netopeer2 in this pull request, therefor I think we should merge them.

The actual order of the commits are:
 libyang: update to 0.13.46
 libnetconf2: update to 0.9.15
 sysrepo: update to 0.7.0
 netopeer2: update to version 0.4.0
 libredblack: add package

What do you think @champtar ?

Regards,
Mislav

**Comment by champtar** [comment]
Hi @mislavn 
sorry for the delay, you can squash so we can then merge

**Comment by mislavn** [comment]
Hi @champtar,

it's done.

**Comment by champtar** [comment]
@mislavn as sysrepo* depends on libredblack, can you put libredblack commit first

**Comment by mislavn** [comment]
Thank's @diizzyy, I'll make a pull request.

**Pull request merged**
