### PR TITLE
treewide, affected packages: fix build with golang 1.16

### LINKED ISSUE #14879: golang: 1.16 update breaks dependent packages
Maintainer: @jefferyto 
Environment: master, 21.02, apparently all arches

Description:

Since the update, packages are failing like:

### cni

```
/builder/shared-workdir/build/sdk/staging_dir/target-mipsel_74kc_musl/usr/share/gocode/src does not exist, skipping symlinks

Finding targets
no required module provides package github.com/containernetworking/cni/cnitool: working directory is not part of a module

Building targets
go: cannot find main module; see 'go help modules'

Makefile:50: recipe for target '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_74kc_musl/cni-0.8.0/.built' failed
make[3]: *** [/builder/shared-workdir/build/sdk/build_dir/target-mipsel_74kc_musl/cni-0.8.0/.built] Error 1
```

### Docker

```
Building statically linked build/docker-linux-mipsle
no required module provides package github.com/docker/cli/cmd/docker: working directory is not part of a module
Makefile:54: recipe for target '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_74kc_musl/docker-20.10.2/.built' failed
```

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainers: @gekmihesg @jefferyto @dangowrt @aparcar @G-M0N3Y-2503
Compile tested: mvebu, arm_cortex-a9+vfpv3-d16, openwrt master
Run tested: none
Description: 
Golang 1.16 changed the default package build mode to "module-aware" mode.  The intention is to drop GOPATH mode (opposite of module-aware) in go 1.17. See https://blog.golang.org/go116-module-changes

To enable GOPATH mode, this PR adds `GO111MODULE=auto` to `GO_PKG_BUILD_VARS`.  Affected packages are

- restic-rest-server
- tor-fw-helper
- cni
- containerd
- docker
- dockerd
- libnetwork
- oci-runtime-tools

#### Sample error messages

```
Finding targets
no required module provides package github.com/containernetworking/cni/cnitool: working directory is not part of a module

Building targets
go: cannot find main module; see 'go help modules'
```
```
go: cannot find main module, but found vendor.conf in /builder/shared-workdir/build/sdk/build_dir/target-mipsel_24kc_musl/containerd-1.4.3/.go_work/build/src/github.com/containerd/containerd
	to create a module there, run:
	go mod init
Makefile:193: recipe for target 'bin/ctr' failed
```

Fixes #14879

### CODE REVIEW

**Comment by aparcar** [comment]
LGTM

**Comment by G-M0N3Y-2503** [comment]
It doesn't look like the `PKG_RELEASE` was bumped for `dockerd`.

But the others LGTM.

**Comment by cotequeiroz** [comment]
`dockerd` should be fixed now.  Thanks for spotting this.

**Comment by BKPepe** [comment]
@cotequeiroz , @jefferyto since we are now using Golang 1.21 in OpenWrt master branch and as well OpenWrt 23.05, we can drop ``GO111MODULE=auto`` from Makefiles, right? It seems like leftover now. I know... 2 years later:-)

**Comment by jefferyto** [comment]
It depends on each affected package, if they have updated to using Go modules. I think most Go projects have switched, though I believe docker still has not.

tor-fw-helper has not but it also hasn't been updated in years; maybe it would be better to remove that package entirely instead.

**Comment by BKPepe** [comment]
After two years? Definitely, they updated it. If not, it needs to be reported to them. That sounds like easy job, isn't it? :)

Ok, let's drop ``tor-fw-helper``. I will prepare PR in a sec.

**Comment by jefferyto** [comment]
> After two years? Definitely, they updated it. If not, it needs to be reported to them. That sounds like easy job, isn't it? :)

https://github.com/docker/cli/pull/4116#issuecomment-1492980108

**Pull request merged**
