### PR TITLE
unzip: unicode support

### PR DESCRIPTION
**Pull request by ryzhovau**
Please, consider to add UTF8 filenames support.

### CODE REVIEW

**Comment by ryzhovau** [comment]
Binaries will grow up to 3%:
```
$ ls -la bin
total 844
drwxr-xr-x 2 ryzhovau ryzhovau   4096 Dec  6 17:47 .
drwxr-xr-x 3 ryzhovau ryzhovau   4096 Dec  6 17:46 ..
-rwxr-xr-x 1 ryzhovau ryzhovau  24132 Dec  6 17:46 funzip
-rwxr-xr-x 1 ryzhovau ryzhovau  24132 Dec  6 12:21 funzip.utf8
-rwxr-xr-x 1 ryzhovau ryzhovau 158772 Dec  6 17:46 unzip
-rwxr-xr-x 1 ryzhovau ryzhovau  73700 Dec  6 17:46 unzipsfx
-rwxr-xr-x 1 ryzhovau ryzhovau  76468 Dec  6 12:21 unzipsfx.utf8
-rwxr-xr-x 1 ryzhovau ryzhovau 163300 Dec  6 12:21 unzip.utf8
-rwxr-xr-x 1 ryzhovau ryzhovau   2953 Dec  6 17:46 zipgrep
-rwxr-xr-x 1 ryzhovau ryzhovau   2953 Dec  6 12:21 zipgrep.utf8
-rwxr-xr-x 1 ryzhovau ryzhovau 158772 Dec  6 17:46 zipinfo
-rwxr-xr-x 1 ryzhovau ryzhovau 163300 Dec  6 12:21 zipinfo.utf8
```

**Comment by ryzhovau** [comment]
BTW, `unzip` and `zipinfo` binaries is just the same:)
```
$ md5sum ./zipinfo
d29737e26d5f8c6efabd9df9f7eebe8a  ./zipinfo
$ md5sum ./unzip
d29737e26d5f8c6efabd9df9f7eebe8a  ./unzip
```
We can pack just one of them.

**Comment by ryzhovau** [comment]
Yes, we can (c) :)) https://github.com/openwrt/packages/pull/2082

**Comment by Noltari** [comment]
Please bump package release when altering the Makefile without updating to a new version.
Ammend your commit without adding a new commit and push to the same branch.

**Comment by ryzhovau** [comment]
I can increase `PKG_RELEASE`, but you have to rework https://github.com/openwrt/packages/pull/2082 then (`PKG_RELEASE` is changed there).

so what should I do?
* increase `PKG_RELEASE` in this PR (and break https://github.com/openwrt/packages/pull/2082)
* nothing:) Just sit on this and wait while both PRs will be merged (with one `PKG_RELEASE` increment for both PRs).

**Comment by Noltari** [comment]
Merge both PRs in this one.

**Comment by ryzhovau** [comment]
Done.

**Pull request closed without merging**
