### PR TITLE
[21.02] snowflake: add package

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Package Tor's Snowflake system components so users can offer e.g. a standalone Snowflake proxy on their routers or other devices.

Signed-off-by: Daniel Golle [daniel@makrotopia.org](mailto:daniel@makrotopia.org)
(cherry picked from commit https://github.com/openwrt/packages/commit/cf120a7effd5d13a7f705b5eb9d22410b73d71f3)

Maintainer: @dangowrt, me
Compile tested: tbd
Run tested: tbd

### CODE REVIEW

**Comment by BKPepe** [comment]
Is there a reason, why you want to add this package to version, which is a feature complete or we can say also old stable?

**Comment by PolynomialDivision** [comment]
21.02 is still not dead. Even some devices like wdr4900v1 are not supported anymore in 22.03. So I thought we keep it in sync with 22.03 also. If a user wants to add his router to "snowflake-network", we should make that as easy as possible.

**Comment by BKPepe** [comment]
Compile and run tested on 21.02?

**Comment by Akira25** [comment]
> Compile and run tested on 21.02?

Compiling on 21.02 was done by the CI. As all the runs are green, I assume it was successful. I run-tested the artifacts for mips-24kc on my `tplink,archer-c5-v1`. I didn't see any issues with this, so we should be safe on merging this.

**Comment by BKPepe** [comment]
It is the stable branch, you needs to be tested on the real device, which OP does not do, that's why I was asking that. Thanks @Akira25 for testing it! Quality over quantity, guys. :)

What should be done is to add ``test.sh`` file to be even run tested in CI, when we have it. On the other hand, you should not count on CI, too much. It just compiles a few packages, it does not do full builds. It can reveal some missing dependencies, etc.

**Comment by 1715173329** [comment]
> It just compiles a few packages, it does not do full builds. It can reveal some missing dependencies, etc.

Anyway, this is a standalone and dependency-free golang package ;)

**Pull request merged**
