### PR TITLE
Update syncthing to 1.18.5

### PR DESCRIPTION
**Pull request by pmoya-in-the-web**
Maintainer: @aparcar
Compile tested: Linksys WRT32X
Run tested: Linksys WRT32X

Description: update utils/syncthing to 1.18.5 version

### CODE REVIEW

**Comment by BKPepe** [comment]
What's the purpose of doing a commit with the subject: "dd"? That's not even useful for testing.

Well, there are also other issues with your pull request, and you should take them. There are mostly formal ones.

1. Wrong commit subject and thus, the CI failed for you almost immediately once you submitted PR, and it is not fixed. 🙄
CI is not just for fancy things, though.
2. There is no `Signed-off-by`.

Now, skip the formal ones.

3. You said that you tested it on the router. Can we know more details about it? For example, on which branch/version of OpenWrt?

And please do not create two PRs. First, it is important to have it merged in master branch and then in the stable branch. Use force-push if possible.

**Comment by pmoya-in-the-web** [comment]
sorry, it was my first commit to openwrt. You can mark it as deleted, i will try a new one soon (need to read more). The purpose is to update syncthing to v1.18.5 
Thanks

**Comment by BKPepe** [comment]
No, don't create a new one. Use the existing ones with force-push.

**Comment by BKPepe** [comment]
The CI still fails for you. Please, take a look at my comment. You are still missing `Signed-off-by`, commit subject is wrong, etc.

**Comment by BKPepe** [comment]
Closing. Submitter does not respond.

**Pull request closed without merging**
