### PR TITLE
Migrate xtables addons

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: @jow-
Compile tested: x86_64, generic, OpenWRT HEAD (c5ca1c9)
Run tested: same, built complete new image and installed via sysupgrade

### CODE REVIEW

**Comment by pprindeville** [comment]
@jow- Am I missing a step?  When I run `make defconfig oldconfig` it drops all the `CONFIG_PACKAGE_kmod-ipt-*` entries from my `.config` and I have to put them back manually.

I ran:

```
% scripts/feeds update -i
% scripts/feeds install -p packages xtables-addons
```

so I thought it reacquired the package definitions, but maybe not.  What am I missing?

**Comment by pprindeville** [comment]
@champtar How to deal with this?  I'm moving a package from `openwrt` to `packages` and bringing the history with it, which means that the commits aren't in my name...

**Comment by champtar** [comment]
Hi @pprindeville,
If you really want to keep the history (I personally wouldn't), the Travis script only check that there is a signed-off-by line that match the git author, and if you rebase, you will be the git commiter
Can you try rebasing?

**Comment by jow-** [comment]
Please squash the commits, afaik packages were never imported with history so far.

**Comment by pprindeville** [comment]
@champtar @jow- Okay, so I have a branch called `migrate-xtables-addons` which I generated via:

(1) clone `pprindeville/openwrt` with `enable-config_nf_conntrack_mark` branch into `openwrt-working` directory and `cd` into it
(2) `git filter-branch --subdirectory-filter package/network/utils/xtables-addons -- --all`
(3) `mkdir -p net/xtables-addons`
(4) `mv Makefile patches` net/xtables-addons`
(5) `git add .`
(6) `git checkout -b reposition-filtered-xtables-addons`
(7) `git commit`

then switched to the `pprindeville/packages` cloning:

(1) `git checkout -b migrate-xtables-addons`
(2) `git remote add xtables-repo /home/philipp/openwrt-working`
(3) `git pull xtables-repo reposition-filtered-xtables-addons`
(4) `git rebase -i HEAD~44`

And this is what I pushed.

If you want me to do something else please list the steps.  Thanks.

**Comment by pprindeville** [comment]
> Please squash the commits, afaik packages were never imported with history so far.

@jow- Done.

**Comment by pprindeville** [comment]
@champtar Can we change the script to accept multiple `Signed-off-by:` lines where only one of them has to match the committer?

**Comment by champtar** [comment]
Hey @pprindeville 
The Travis script is already doing the right thing (tm)
https://github.com/openwrt/packages/blob/master/.travis_do.sh#L179
It's looking if there is a signed-off-by from the commit author
In this case (https://github.com/openwrt/packages/pull/5357/commits/b112412b6f520d31baf91d3f471a76f9ae3ea8fe) the commit author is jow, but there is no signed-off-by jow
Put yourself as author and you are done

**Comment by pprindeville** [comment]
@champtar Thanks, fixed.

**Comment by jow-** [comment]
Committed via 3ba01ac1

**Comment by pprindeville** [comment]
Thanks!

**Pull request closed without merging**
