### PR TITLE
[18.06] Libmraa compilation fix

### PR DESCRIPTION
**Pull request by Kulipator**
Maintainer: @Kulipator
Compile tested: (ramips LinkIt Smart 7688 OpenWrt 18.06.4)
Run tested: (ramips LinkIt Smart 7688 OpenWrt 18.06.4)

Description: openwrt-18.06 branch libmraa package compile fix.
libmraa updated to version 0.8.1 & compilation bugfix applied (support SWIG_V8_VERSION > 0x040000)

### CODE REVIEW

**Comment by neheb** [comment]
That MIRROR_HASH change is bogus.

You also need to sign off your commit.

**Comment by neheb** [comment]
ping @nxhack

**Comment by nxhack** [comment]
@Kulipator 
Have you tested compile?

Is this patch necessary?
0005-ramips_fixes.patch 

Please fix this further.
```
diff --git a/libs/libmraa/patches/0001-base.patch b/libs/libmraa/patches/0001-base.patch
index 5094389..d790296 100644
--- a/libs/libmraa/patches/0001-base.patch
+++ b/libs/libmraa/patches/0001-base.patch
@@ -21,11 +21,11 @@ Subject: [PATCH 1/4] base
  # Make a version file containing the current version from git.
 -include (GetGitRevisionDescription)
 -git_describe (VERSION "--tags")
--if ("x_${VERSION}" STREQUAL "x_GIT-NOTFOUND" OR "x_${VERSION}" STREQUAL "x_HEAD-HASH-NOTFOUND")
+-if ("x_${VERSION}" STREQUAL "x_GIT-NOTFOUND" OR "x_${VERSION}" STREQUAL "x_HEAD-HASH-NOTFOUND" OR "x_${VERSION}" STREQUAL "x_-128-NOTFOUND")
 -  message (WARNING " - Install git to compile a production libmraa!")
--  set (VERSION "v0.8.0-dirty")
+-  set (VERSION "v0.8.1-dirty")
 -endif ()
-+set (VERSION "v0.8.0")
++set (VERSION "v0.8.1")
  
  message (INFO " - libmraa Version ${VERSION}")
  
diff --git a/libs/libmraa/patches/0004-fixes.patch b/libs/libmraa/patches/0004-fixes.patch
index 40e5930..7acdea7 100644
--- a/libs/libmraa/patches/0004-fixes.patch
+++ b/libs/libmraa/patches/0004-fixes.patch
@@ -655,7 +655,7 @@ Subject: [PATCH 4/4] fixes
              b->gpio_count++;
 --- a/src/gpio/gpio.c
 +++ b/src/gpio/gpio.c
-@@ -113,6 +113,8 @@
+@@ -114,6 +114,8 @@
          close(export);
      }
```

**Comment by Kulipator** [comment]
@nxhack 
After provided changes in patches 0001-base.patch & 0004-fixes.patch compilation is OK and no need in 0005-ramips_fixes.patch.

**Comment by BKPepe** [comment]
Three commits (two about the same) must be squashed before merging it!

**Comment by BKPepe** [comment]
Three commits (two about the same) must be squashed before merging it! Also, where is CI check? The last commit subject is just wrong!

**Comment by neheb** [comment]
Good question. I remember seeing a green check mark before merging.

**Pull request merged**
