### PR TITLE
collectd: enable smart plugin

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @hnyman 
Compile tested: x86_64, APU3, latest OpenWrt master)
Run tested: x86_64, APU3, latest OpenWrt master

Description:
This P/R enables the smart plugin.
For the plugin to work it needs the [libatasmart](https://git.0pointer.net/libatasmart.git/).
In order for the library to be compile correctly, a host tool `strpool` must be compiled before.
So a host build is neeeded.
We also need the file `atasmart.strpool.c` which was not part of the sources. I copied this from [debian](https://salsa.debian.org/utopia-team/libatasmart/-/blob/master/atasmart.strpool.c).
I Also had to fix the smart collectd plugin with a patch to work correctly on my system.

This was hard debug work so I added a missing configuration option to enable debug easily with `make menuconfig`.

### CODE REVIEW

**Comment by hnyman** [comment]
Looks ok to me. 
Please merge it, once the CI builds have completed ok.

**Comment by hnyman** [comment]
Fails, due to libudev dependencies.  Not sure if the addition will affect even more plugins...

```
2021-03-12T17:29:03.3165556Z Package collectd-mod-disk is missing dependencies for the following libraries:
2021-03-12T17:29:03.3174547Z libudev.so.1
2021-03-12T17:29:03.3179144Z make[2]: *** [Makefile:453: /home/build/openwrt/bin/packages/arm_cortex-a9_vfpv3-d16/packages_ci/collectd-mod-disk_5.12.0-8_arm_cortex-a9_vfpv3-d16.ipk] Error 1
```

**Comment by feckert** [comment]
@hnyman Thanks for the hint.

I don't use the `collectd-mod-disk` package, so I didn't switched it on in my build and so did not got this build error.
I have now fixed it with the [following line](https://github.com/openwrt/packages/pull/15105/commits/092902a87ee14e3b4b0b37a4ddb81719ae27fcc8#diff-c96adb50b3292983e82f073a25229ef3b3be1bbd938622d100a747a30947f73eR423).
I have also done the counter testcase.
If the package `collect-mod-smart` is not switched on, then the dependency is not added, because libudev is not enabled by this package.

Should fit

**Comment by hnyman** [comment]
@feckert 
I would like to keep collectd in 21.02 in sync with master, so I think that we might backport also this. I would have already done that, but this introduces also "libatasmart", which I have not tested.
have you tested this with 21.02 ?   
(I guess that your other recent addition, the ubi plugin, should work ok)

**Comment by feckert** [comment]
@hnyman If its ok from your side, then I will test this in my build on manday and backport the missing commits for smart and ubi. So the package collectd for openwrt-21.02 is even with master

**Comment by feckert** [comment]
@hnyman works on my build and on my dev system as expected
Backport done https://github.com/openwrt/packages/commits/openwrt-21.02

```
root@st-dev-07 /tmp/rrd/st-dev-07/smart-sda # uname -r
5.4.111

root@st-dev-07 /tmp/rrd/st-dev-07/smart-sda # ls
smart_attribute-airflow-temperature-celsius.rrd  smart_attribute-runtime-bad-block-total.rrd
smart_attribute-erase-fail-count-total.rrd       smart_attribute-total-lbas-written.rrd
smart_attribute-good-block-rate.rrd              smart_attribute-udma-crc-error-count.rrd
smart_attribute-hardware-ecc-recovered.rrd       smart_attribute-used-reserved-blocks-total.rrd
smart_attribute-power-cycle-count.rrd            smart_attribute-wear-leveling-count.rrd
smart_attribute-power-on-hours.rrd               smart_badsectors.rrd
smart_attribute-program-fail-count-total.rrd     smart_powercycles.rrd
smart_attribute-reallocated-sector-count.rrd     smart_poweron.rrd
smart_attribute-reported-uncorrect.rrd           smart_temperature.rrd
```

**Pull request merged**
