### PR TITLE
v2ray-geodata: Use APK style release number

### PR DESCRIPTION
**Pull request by qosmio**
Maintainer: Tianling Shen <cnsztl@immortalwrt.org>
Run tested: aarch64, Dynalink DL-WRX36, Master Branch

### CODE REVIEW

**Comment by 1715173329** [comment]
https://github.com/openwrt/packages/blob/50810923da4373c9a6e997e2c2ce7b1d453f5ac9/net/v2ray-geodata/Makefile#L54

It's by design as in this Makefile `VERSION` has been overridden so `r` won't be populated automatically.

**Comment by qosmio** [comment]
I see. 

Does removing `r` impact anything specifically within the build?

My PR was mostly to keep consistency across the build system. Docs say `PKG_RELEASE` must be a number. 

```
# Compliant
❯ grep -rEl "^PKG_RELEASE:=[0-9]" feeds/packages/ | wc -l
1403
```

```
# Non-compliant
❯ grep -rEl "^PKG_RELEASE:=[^0-9]" feeds/packages/ | wc -l
8
```

Just trying to avoid instances where packages show up like the following:
```
adblock-fast         1.1.1-rr7
curl                 8.7.1-rr1
https-dns-proxy      2023.11.19-rr1
libcurl4             8.7.1-rr1
libnghttp3           1.2.0-rr1
libngtcp2            1.4.0-rr1
nebula               1.8.2-rr2
nebula-cert          1.8.2-rr2
nebula-proto         1.8.2-rr2
nebula-service       1.8.2-rr2
pbr                  1.1.4-rr7
pbr-iptables         1.1.4-rr7
```

I noticed when checking for upgrades I would see instances like:
```
➤ opkg list-upgradable
curl - 8.7.1-r1 - 8.7.1-rr1
libcurl4 - 8.7.1-r1 - 8.7.1-rr1
```

**Comment by 1715173329** [comment]
> Docs say `PKG_RELEASE` must be a number.

Yes I missed that. So if possible please change
`VERSION:=$(GEOIP_VER)-$(PKG_RELEASE)`
to
`VERSION:=$(GEOIP_VER)-r$(PKG_RELEASE)`.

Or I will do that.

**Comment by 1715173329** [comment]
suspended by #23937

**Pull request closed without merging**
