### PR TITLE
dnsdist: replace PKG_BUILD_DEPENDS with normal one

### PR DESCRIPTION
**Pull request by neheb**
It adds it there anyway.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @Habbie 
Compile tested: ath79

### CODE REVIEW

**Comment by Habbie** [comment]
> It adds it there anyway.

What adds what where anyway? I removed boost from the runtime dependencies to save (a few kilobytes) of disk space.

**Comment by neheb** [comment]
AFAIK the boost package does not install anything.

All dependencies become build dependencies.

**Comment by Habbie** [comment]
> AFAIK the boost package does not install anything.

Yes, I recall it is empty, but having it still costs a few kilobytes. I did this during a cleanup that yielded megabytes in other places. If you prefer a simpler Makefile that does not go as far as I did, this PR is fine with me :-)

**Comment by neheb** [comment]
Eh it's fine.

**Pull request closed without merging**
