### PR TITLE
postfix: Add SQLite support and fix musl compile without POSTFIX_TLS

### PR DESCRIPTION
**Pull request by lucize**
Add SQLite support and fix musl compile without POSTFIX_TLS

split PR (#4093)

Compile/Run tested x86_64 LEDE/Reboot

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by lucize** [comment]
splitted

**Comment by stintel** [comment]
Thanks for splitting. LGTM, except a minor nit, the patch prefix does not follow https://dev.openwrt.org/browser/trunk/target/linux/generic/PATCHES, but I'm not sure if we enforce this in this feed. Did you send the fix upstream, too?

**Comment by stintel** [comment]
@Shulyaka can you ACK/NAK?

**Comment by Shulyaka** [comment]
Yes, I'm OK with it. Thank you!

**Pull request merged**
