### PR TITLE
gcc: update to 12.3.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Maintainer: @bk138
Compile tested: CI
Run tested: tbd

### CODE REVIEW

**Comment by 1715173329** [comment]
Is it ready to go? CI is passing now ;)

**Comment by bk138** [comment]
@PolynomialDivision you'd probably want to runtime-test this, other than that it looks fine from the patch perspective.

**Comment by 1715173329** [comment]
@PolynomialDivision let's merge it or it will fail forever. as the toolchain works fine there shouldn't exist critical breaking changes.

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision let's merge it or it will fail forever. as the toolchain works fine there shouldn't exist critical breaking changes.

I'm fine with that. I was not able to test it since I need a big enough target. That's why I currently failed.

**Comment by PolynomialDivision** [comment]
Run-tested banana pi r64. Works fine! :)

**Pull request merged**
