### PR TITLE
python: Add pyproject.toml-based builds for host Python packages, add host packages

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainers:
* me
* @BKPepe (python-yaml)
* @commodo (numpy, python-dateutil)
* @dynasticorpheus (python-pycares)
* @flyn-org (setools)
* @ja-pa (onionshare-cli, python-apipkg, python-augeas, python-bidict, python-execnet, python-iniconfig, python-packaging, python-pluggy, python-psutil, python-py, python-pytest, python-pytest-forked, python-pytest-xdist, python-typing-extensions, python-zipp)
* @jmarcet (python-jsonschema, python-pynacl)
* @julienmalik (borgbackup)
* @oskarirauta (apparmor)

Compile tested: armvirt-32/armvirt-64/malta-be, 2023-03-05 snapshot sdk
Run tested: armvirt-32/armvirt-64/malta-be (qemu), 2023-03-05 snapshot

Description:

Things accomplished by this series of commits:

* **Add pyproject.toml-based (PEP 517) builds for host Python packages, replacing the use of host pip to install host packages**

  Using pip to install host packages with pyproject.toml-based (PEP 517) builds is problematic:

  * If build isolation is used, pip will create an isolated build environment, install any build dependencies for the requested package, then build the requested package.

    [It does not appear currently possible to have pip install the build dependencies with hash-checking mode enabled](https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020).

  * If build isolation is not used, [any build dependencies must be installed in the build environment before invoking pip to build the requested package](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation).

    This would require creating a package dependency resolution system to install build dependencies, and any dependencies of dependencies, in the correct order.

  * It is very difficult to patch the packages installed by pip.

  This adds a new include file (python3-host-build.mk) with recipes to install host Python packages with pyproject.toml-based builds. This is backwards-compatible with packages that require running setup.py.

  Besides addressing the above issues (the OpenWrt build system already resolves dependencies between packages, checks all source downloads against known hashes, and supports patching packages), host packages also:

  * Capture package licensing and maintainer information
  * Enable uscan checking for package updates/CVEs
  * Are a known concept for OpenWrt packagers/developers

  The existing functionality of using host pip to install packages will remain for now, but should be considered deprecated and expected to be removed in the future.

* **Add host packages / host builds for packages essential for pyproject.toml-based builds (for both host and target packages)**

  * flit-core
  * installer
  * build (and dependencies: packaging, tomli, pyproject-hooks)
  * wheel

* **Replace existing host pip requirements files with host packages / host builds**

  * cython
  * ply
  * pycparser
  * cffi
  * setuptools-scm (and dependencies: typing-extensions)

* **Add host packages / host builds to be used for pyproject.toml-based builds of target packages**

  * poetry-core
  * flit-scm
  * hatchling (and dependencies: editables, pathspec, pluggy)
  * hatch-vcs
  * hatch-fancy-pypi-readme

* * *

Due to incompatibility caused by some package upgrades, python3-packaging and python3-pytest will be marked BROKEN. These will be resolved in a future PR after this one is merged that introduces proper support for pyproject.toml-based builds for target packages.

### CODE REVIEW

**Review by commodo — APPROVED** [review]

**Comment by commodo** [comment]
welcome back :)

**Comment by flyn-org** [comment]
Looks good, but I want to confirm setools still builds. Did all of the affected packages build?

**Comment by jefferyto** [comment]
The CI is failing at the package test step:

* aarch64, arm, and i386 failed when it tried to install tor-basic; tor was already installed and there is a conflict
* x86_64 failed when it tried to install acl; it could not find/install libacl (there seems to be some major build issue, many packages are [failing](https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/))

All the CI builders passed the build step.

**Comment by jefferyto** [comment]
Now all failed CI failed at the same point (conflict with tor while testing tor-basic). Having fixed many, many issues with the CI in the past, I am not so interested in fixing it at this moment.

**Comment by jefferyto** [comment]
Updated versions for installer, pathspec, poetry-core, and wheel.

**Pull request merged**
