### PR TITLE
Optional IPv6 support 

### PR DESCRIPTION
**Pull request by ryzhovau**
Turn on/off IPv6 support, according to global `CONFIG_IPV6` setting.
Replacement of https://github.com/openwrt/packages/pull/1177

### CODE REVIEW

**Comment by jow-** [comment]
Seems the PR needs a rebase, however the changes themselves look fine to me.

@luizluca @heil @tripolar @jmccrohan @mstorchak - do you approve the changes to your respective packages?

@ryzhovau can you rebase this PR?

**Comment by luizluca** [comment]
I'm currently away until Sat so I cannot compile-test it.
Anyway, @ryzhovau, the rebase is needed, at least for ruby. Nothing serious but release
number might conflict (or not as both uses release 2).

if $(call autoconf_bool,CONFIG_IPV6,ipv6) is converted to --enable/disable-ipv6, then it is ok.
It would be nice to someone, at least, compile these packages with/without ipv6 before merge. @jow- if someone do it, its is ack for me (or I'll do it on Sat if rebased).

**Comment by ryzhovau** [comment]
Done.

**Comment by mstorchak** [comment]
No objections.

**Comment by tripolar** [comment]
No objections.

**Comment by heil** [comment]
No objections.

**Comment by luizluca** [comment]
I just tested. No objections.

**Comment by jmccrohan** [comment]
No objections from me. Thanks @ryzhovau!

**Comment by jow-** [comment]
thanks!

**Pull request merged**
