### PR TITLE
netatalk: upgrade to version 3.1.11

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @dangowrt 
Compile tested: https://github.com/lede-project/source/commit/9235a29e1a9764361940d4b38f4fce0358d8d9ee x86_64
Run tested: https://github.com/lede-project/source/commit/9235a29e1a9764361940d4b38f4fce0358d8d9ee x86_64

----------------------------------------------

Addresses: https://github.com/openwrt/packages/issues/4319

```
root@LEDE:/# afpd -V
afpd 3.1.11 - Apple Filing Protocol (AFP) daemon of Netatalk

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version. Please see the file COPYING for further information and details.

afpd has been compiled with support for these features:

          AFP versions:	2.2 3.0 3.1 3.2 3.3 3.4 
         CNID backends:	dbd last tdb 
      Zeroconf support:	No
  TCP wrappers support:	No
         Quota support:	No
   Admin group support:	Yes
    Valid shell checks:	No
      cracklib support:	No
            EA support:	ad | sys
           ACL support:	No
          LDAP support:	No
         D-Bus support:	No
     Spotlight support:	No
         DTrace probes:	No

              afp.conf:	/etc/afp.conf
           extmap.conf:	/etc/extmap.conf
       state directory:	/var/netatalk/
    afp_signature.conf:	/var/netatalk/afp_signature.conf
      afp_voluuid.conf:	/var/netatalk/afp_voluuid.conf
       UAM search path:	/usr/lib/uams//
  Server messages path:	/var/netatalk/msg/
```

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by dangowrt** [comment]
@commodo: Thanks! Would you like to take over maintainership for this package? I hardly get to use and test it these days...

**Comment by dangowrt** [comment]
Yes, please fire up a PR to assign yourself, I'll merge it right away.

**Comment by Neustradamus** [comment]
Updated by:
- https://github.com/openwrt/packages/pull/7850

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/openwrt/packages/issues/4318
- https://github.com/openwrt/packages/issues/4319

Updated by:
- https://github.com/openwrt/packages/pull/7850

**Pull request merged**
