### PR TITLE
libgphoto2 and gphoto2: update to 2.5.23

### PR DESCRIPTION
**Pull request by DocLM**
Maintainer: @DocLM 
Compile tested: ar71xx, 18.06.2

### CODE REVIEW

**Comment by neheb** [comment]
```
cp: cannot stat '/home/build/build_dir/build_dir/target-mips_24kc_musl/libgphoto2-2.5.23/ipkg-install/usr/lib/libgphoto2/2.5.23/adc65.so': No such file or directory
```

**Comment by diizzyy** [comment]
libgphoto
```--enable-static``` - Why?

**Comment by DocLM** [comment]
@diizzyy I don't know. I resumed a libgphoto Makefile two years ago from an old OpenWrt repository and never checked that. I'll check if it is necessary.

For some reason `--with-camlibs="all"` doesn't build adc65 camlib but with an explicit `--with-camlibs="adc65"` it works. Obviously I cannot use "all" with an explicit list of camlibs. I'm trying to understand why this happens but I'm little busy these days.

**Comment by DocLM** [comment]
I found out that `--with-camlibs="all"` doesn't compile outdated cameras anymore. Using `--with-camlibs="all,outdated"` should fix the issue.

**Comment by nsmith1024** [comment]
Hello,

Could you update gphoto2 and libgphoto2 (and sub-packages) to the latest versions?

for Onion Omega2+ hardware?

ghoto2 VERSION 2.5.28
libgphoto2 VERSION 2.5.30 (and camera sub-packages)

Is it possible to upgrade it without using patching or patch files?

**Pull request merged**
