### PR TITLE
fail2ban: bpo for python3.10

### PR DESCRIPTION
**Pull request by erdoukki**
Maintainer: @erdoukki
Compile untested

May replace https://github.com/openwrt/packages/pull/18781

May fix: https://github.com/openwrt/packages/issues/18681

cc @ryzhovau
cc @paper42

### CODE REVIEW

**Comment by BKPepe** [comment]
Why are there now two PRs for the same thing? Both look identical and in my point of view, I prefer one patch instead of three patches, though. Also, your PR is totally untested instead of https://github.com/openwrt/packages/pull/18781

- In your commit message, you don't follow what is here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

and by each force push you are spamming this: https://github.com/openwrt/packages/issues/18681

- Both commit messages (yours and in the referenced PR), there is missing proper ``Fixes`` as this was wrong in the previous PR, though, but at least from @paper42 there is reference for the commit, which was only partial.

**Comment by erdoukki** [comment]
it was a last try to help.
you said differently in the past for patches !
In french we say "allez vous faire foutre !"

I give you 2 hours of my precious time.
I will never more and already regret !

**Comment by paper42** [comment]
I don't care much which approach will be merged, both should work fine and both do the same changes, so it functionally shouldn't matter. I slightly prefer one patch for fixing one issue even if it contains multiple commits because I personally find it cleaner, but as I said, both are ok from my side.

It would be nice if you told me to update my PR instead of opening your own though, this way we are just spamming everyone who follows this repository with extra notifications for no reason.

**Comment by BKPepe** [comment]
@erdoukki I don't want anything new from you. You don't need to reinvent the wheel again. Please check this out:
- [Submitting patches (OpenWrt Wiki)](https://openwrt.org/submitting-patches) - there are all formal things explained.
- [CONTRIBUTING.md of this repository](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) says:
> Have been tested to compile with the correct includes and dependencies. Please also test with "Compile with full language support" found under "General Build Settings" set if language support is relevant to your package.

Yes, usually, patches should be done in separate files, but these patches are related to each other, thus it should be done in patch series in one file or all changes in one files as it was done by @paper42 . Seeing this in big picture, I see that this small package has already 4 patches and you want to introduce another 2. Also, your commit message is somehow cryptic, tbh.

**Pull request closed without merging**
