### PR TITLE
SSHTunnel: Proxycommand support

### PR DESCRIPTION
**Pull request by lars18th**
Maintainer: @nunojpg
Compile tested: mips
Run tested: TP-Link Archer C2 v3, OpenWrt 19.07.2

Description:

A simple update to support the ProxyCommand parameter. Installing the OpenSSH client and NCat tool it's possible to stablish the SSH tunnel over an authenticated HTTP proxy or over a SOCKS4/5 proxy.

### CODE REVIEW

**Comment by ja-pa** [comment]
You should also bump PKG_RELEASE

**Comment by lars18th** [comment]
Hi @ja-pa 

> You should also bump PKG_RELEASE

The main developer is @nunojpg. I hope he can help us. I don't have much time to sign and refine the patch. So I publish here for revision/testing, and I hope someother maintainer will sign and merge it. Thank you for understand this point.

Regards.

**Comment by lars18th** [comment]
Hi, I widthdraw this PR and will create a new one.
Sorry!

**Comment by lars18th** [comment]
Replaced by #13789

**Pull request closed without merging**
