### PR TITLE
fdk-aac: Update to 2.0.1 and add free version

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @thess 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
ping @diizzyy 

Note that this messes up ffmpeg somewhat. There's a rule that x264 and fdk-aac cannot coexist. No idea what that's about.

Also note that faad2 should be placed under BUILD_PATENTED as it most definitely has functionality that is still patented.

I believe the original reasoning for not doing so was to keep pianod or squeezelite available. Those packages should be ported to use fdk-aac APIs.

**Comment by diizzyy** [comment]
What do you mean by "messes up ffmpeg somewhat"?
Please drop the unofficial patches as they serve very little to no practical purpose.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/blob/master/multimedia/ffmpeg/Makefile#L522

**Comment by diizzyy** [comment]
Oh, you mean the licensing (simplified here)
https://github.com/diizzyy/packages/blob/ffmpeg4-pkg/multimedia/ffmpeg4/Config.in#L7
We should probably move to 4.X now that 19.X is branched and it fixes several issues.

**Comment by neheb** [comment]
I've decided to merge this.

The buildbots do not enable BUILD_PATENTED, which means no fdk-aac. While the -free variant is a constrained version (no HE and related features), it's better than nothing. Most AAC content uses LC anyway. The HE stuff is usually used with audiobooks.

I'll keep this in master in case this ends up being reverted before the 20 release.

**Comment by diizzyy** [comment]
On what basis? It's used for encoding not decoding so your reasoning is flawed. Please back this out as it doesn't add anything valuable and on top of that not even documented.

**Comment by neheb** [comment]
It most certainly supports decoding. The library anyway.

**Comment by diizzyy** [comment]
The only user is ffmpeg which doesn't use decoding, either way the new behavior isn't documentend anywhere so back this out and/or do it properly.

**Comment by neheb** [comment]
I seem to recall when mpd-full is built with BUILD_PATENTED it gained AAC decoding support. It should also be true here.

**Comment by diizzyy** [comment]
ffmpeg has its own decoder, mpd doesn't use fdk-aac at all (unless it silently includes it which would be a bug) not that it matter as this commit is improper either way.

**Comment by neheb** [comment]
The ffmpeg configure script has this line:

```
--enable-libfdk-aac      enable AAC de/encoding via libfdk-aac [no]
```

The ffmpeg Makefile here uses libfdk-aac as well.

I downloaded the git repo. libfdk-aac is indeed used for decoding as well as encoding, in contrast to the documentation.

**Comment by diizzyy** [comment]
It's only used if you specify (which is you in don't in 99.9%) but again, either way this commit is incorrect so please fix it o I'll revert it until you do.

**Pull request merged**
