### PR TITLE
mwan3: Add link quality checks - latency & packet loss.

### PR DESCRIPTION
**Pull request by codemarauder**
Signed-off-by: Nishant Sharma <codemarauder@gmail.com>

Maintainer: @feckert 
Compile tested: No. Scripts.
Run tested: x86, geode, 17.01.4

Description:
Added option for enabling/disabling link quality checks by comparing ICMP ping packet loss and latency against predefined max & min values.

* Consider link up if latency < min_latency AND loss < min_loss
* Consider link down if latency > max_latency OR loss < max_loss

Added variables to /etc/config/mwan3:
* check_quality (boolean)
* max_latency (numeric in milliseconds)
* min_latency (numberic in milliseconds)
* min_loss (numeric representing %)
* max_loss (numeric representing %)

Keeping failure_time and recovery_time high (> 50 seconds) avoids frequent switching of links.

To-do: Update luci-app-mwan3

### CODE REVIEW

**Comment by codemarauder** [comment]
Closing. Have to resend against @feckert 's latest commit to resolve conflicts.

**Comment by codemarauder** [comment]
Giving up for now :(

**Comment by feckert** [comment]
@codemarauder 
nice feature will test this on monday.
Could we also add this to the ubus interface?
This information could be interesting.

**Comment by codemarauder** [comment]
@feckert 
I have resolved the conflict and sent another pull request #5884 which passed Travis checks.
Regarding ubus interface, I will need handholding as I have never played with ubus.

**Pull request closed without merging**
