### PR TITLE
Update Zabbix to 5.4.7

### PR DESCRIPTION
**Pull request by hangnail-en**
Maintainer: Etienne CHAMPETIER <champetier.etienne@gmail.com>
Compile tested: (mips_24kc, Archer A7, 21.0.2)
Run tested: (mips_24kc, Archer A7, 21.0.2)

Description:
Update to 5.4.7

### CODE REVIEW

**Comment by svlobanov** [comment]
Zabbix 5.4 is not LTS. Previously, only LTS version were in openwrt. If you want to add non-LTS version, maybe you need to create package e.g. zabbix-current

**Comment by hangnail-en** [comment]
I won't lie my man, I don't know too much about making packages. I reviewed
the development pages and all but I work in cyber security and manages
devices so software development is not my thing. I'd appreciate it if you
could point me in the right direction though. I really do want to get an
updated Zabbix for OpenWRT though. Otherwise I won't be able to manage my
routers.

**Comment by svlobanov** [comment]
Zabbix-server 5.4 can communicate with zabbix-agent 5.0 so you can use zabbix-agent 5.0 on your routers. It is officially supported by zabbix developers. 

Do you really use 5.4-specific features on zabbix-agent?

**Comment by BKPepe** [comment]
Closing. This is going to be addressed in https://github.com/openwrt/packages/pull/17290.

**Pull request closed without merging**
