### PR TITLE
prometheus-node-export-lua: add my email

### PR DESCRIPTION
**Pull request by lyda**
Add my email address to the copyright for the file.

Signed-off-by: Kevin Lyda <kevin@lyda.ie>

Maintainer: @champtar
Compile tested: N/A
Run tested: N/A

Description: New PR based on feedback in #15682. Not totally clear who the maintainer is. I also think some other names should be added there because some folks have added really significant features - ones I'll definitely be using!

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
Since it is a change in the code, you have to bump `PKG_VERSION:=2021.02.15`? ;)

**Comment by BKPepe** [comment]
That's a question. I would say that I would not bump it just because of added email address in the copyright. See it in the mentioned PR (https://github.com/openwrt/packages/pull/15682#issuecomment-851872233) Otherwise, you will force it to all users who has it installed and worn out their flash memory on their routers because of the missing copyright. I think we can bump it once there are some other changes as well.

**Comment by PolynomialDivision** [comment]
Fine with me.

**Comment by lyda** [comment]
No need to increment the version.  I might have some future fixes/additions that might merit it, but no, not for this.

**Pull request merged**
