### PR TITLE
dovecot & pigeonhole: Fix managesieve-login needs libdovecot-login

### PR DESCRIPTION
**Pull request by cshoredaniel**
Maintainer: @lucize @MikePetullo 
Compile tested: ath79, CR5000, Aug 15 master + Aug 16 package master; Travis-CI ;-)
EDIT: also brcm2708, Raspberry Pi B+, current masters

Run tested: Same as compile tested.

Tests: 

1) readelf on the managesieve-login binary
2) used Thunderbird sieve plugin
3) checked dovecot logs
ADDED:
4) used ldd on files in /usr/lib/dovecot and /usr/lib/dovecot/modules to verify they can find their dependencies.

Description:

When trying to use managesieve my MUA complained sieve wasn't supported.
On investigation dovecot logs the following could be seen:

    Aug 16 00:28:44 managesieve-login: Fatal: master:
      service(managesieve-login): child 1430 returned error 127
    Aug 16 00:31:32 managesieve-login: Error: Error loading shared
      library libdovecot-login.so.0: No such file or directory
      (needed by /usr/lib/dovecot/managesieve-login)
    Aug 16 00:31:32 managesieve-login: Error: Error loading
      shared library libdovecot.so.0: No such file or directory
      (needed by /usr/lib/dovecot/managesieve-login)
    Aug 16 00:31:32 managesieve-login: Error: Error relocating
      /usr/lib/dovecot/managesieve-login: net_ip2addr: symbol not found

The issue (verified with readelf on non-working build and build with my fix)
is that there is no RPATH information in the pigeonhole binaries (like
managesieve-login).

The dovecot-config that is 'installed' in the staging dir
assumes that plugins will be built on the same host as the installed files.
The 'installed' dovecot-config (partial) looks like:

LIBDOVECOT='-L/usr/lib/dovecot -ldovecot'
LIBDOVECOT_LOGIN='-ldovecot-login -L/home/user/Build/openwrt/openwrt-ath79/staging_dir/target-mips_24kc_musl/usr/lib -lssl -lcrypto'
LIBDOVECOT_SQL=-ldovecot-sql
LIBDOVECOT_COMPRESS=-ldovecot-compression
LIBDOVECOT_LDA=-ldovecot-lda
LIBDOVECOT_STORAGE='-ldovecot-storage '
LIBDOVECOT_DSYNC=-ldovecot-dsync
LIBDOVECOT_LIBFTS=-ldovecot-fts

The solution I used was to modify dovecot-config to add the rpath to
DOVECOT_BINARY_LDFLAGS, and to replace references to host directories
with staging_dir directories.

This results in RPATH being added as it needs to be, and results in a working
version of dovecot+pigeonhole.

NB: I've also touched package version of pigeonhole as this change in dovecot
results in (needed) binary changes for pigeonhole.

Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

### CODE REVIEW

**Comment by cshoredaniel** [comment]
Discovered I missed one new (to me) functionality, which need one more rpath - to /usr/lib/dovecot/modules....I'll add that shortly.

**Comment by cshoredaniel** [comment]
Upon further review this doesn't appear to introduce new issues, just that I've run across issues that were already there from working on this.  Still, unless you object I'll fix the issues with standard dovecot plugins like the virtual module in a separate commit in the same PR.

**Comment by cshoredaniel** [comment]
Note: still under test, but I pushed for possible comments.

**Comment by cshoredaniel** [comment]
plugins packaged with dovecot not working yet, but it's also an RPATH issue that I might have solved in my current build.

**Comment by cshoredaniel** [comment]
So apparently my plugin trouble was actually user error - the plugins probably work fine without worrying about RPATH (will verify).

**Comment by cshoredaniel** [comment]
ManageSieve really was broken, but virtual and other plugins distributed with dovecot are fine (I think).

**Comment by cshoredaniel** [comment]
@MikePetullo @lucize  We're good to go. The first commit fixes sieve.  The second commit is 'nice to have' in that it restores the 'normal' file hiearchy (/usr/libexec for binaries that dovecot calls; /usr/lib for plugins and libraries) but probably isn't necessary (however I haven't tried 'normal' plugins without the second patch, so there is a chance it's actually required and not just 'nice').

**Comment by cshoredaniel** [comment]
Latest push doesn't make any changes, just adds the dovecot/pigeonhole changes on top of current master instead of some commits ago.

**Comment by cshoredaniel** [comment]
Success with Raspberry Pi B+ (brcm2708) with current masters (compile and run-testing, and active use).

**Comment by cshoredaniel** [comment]
https://github.com/lucize https://github.com/MikePetullo Any idea when you might be able to look at this?

**Comment by lucize** [comment]
sorry, maybe next week I could try it

Thanks!

**Comment by MikePetullo** [comment]
The pigeonhole side looks fine.

**Comment by cshoredaniel** [comment]
@lucize ok, thanks for letting me know....I'll ping you in 10-12 days if you haven't got to just to make sure you're just busy and not forgotten it ;-)

**Comment by lucize** [comment]
@cshoredaniel you moved the binary location but in dovecot.init still `procd_set_param command /usr/sbin/dovecot -F
`

**Comment by cshoredaniel** [comment]
@hnyman @dibdot @pprindeville Ok the maintainers are okay with the PR, any objections from any of you, or could you merge?

**Comment by cshoredaniel** [comment]
Thanks!

**Pull request merged**
