### PR TITLE
kea: update package to 1.8.0

### PR DESCRIPTION
**Pull request by tiagogaspar8**
Maintainer:BangLang Huang<banglang.huang@foxmail.com>, Rosy Song<rosysong@rosinson.com>
Compile tested: Latest OpenWRT master ARM
Run tested: Latest OpenWRT master ARM

Description:

Update kea to the latest stable version (1.8.0) and add kea-shell 
package.
Signed-off-by: Tiago Gaspar <tiagogaspar8@gmail.com>

PS: For some reason after boot this appeared in the syslog, but everything is working fine.

```
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: /usr/sbin/keactrl: line 101: rev: not found
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: /usr/sbin/keactrl: line 101: rev: not found
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: INFO/keactrl: Starting /usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: /usr/sbin/keactrl: line 101: rev: not found
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: /usr/sbin/keactrl: line 101: rev: not found
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: INFO/keactrl: Starting /usr/sbin/kea-dhcp6 -c /etc/kea/kea-dhcp6.conf
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: /usr/sbin/keactrl: line 101: rev: not found
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: /usr/sbin/keactrl: line 101: rev: not found
Tue Sep 15 23:12:39 2020 daemon.notice procd: /etc/rc.d/S95done: INFO/keactrl: Starting /usr/sbin/kea-dhcp-ddns -c /etc/kea/kea-dhcp-ddns.conf
```
UPDATE 1: This proved to be deadly, I'll try to pind out where these errors came from, as soon as I find it I'll give an update. If anyone has any Idea please enlighten me.

UPDATE 2: I have no idea what's wrong, maybe a missing dependency? this is an output example of the error:
```
root@OpenWrt:~# keactrl status
/usr/sbin/keactrl: line 101: rev: not found
/usr/sbin/keactrl: line 101: rev: not found
DHCPv4 server: inactive
/usr/sbin/keactrl: line 101: rev: not found
/usr/sbin/keactrl: line 101: rev: not found
DHCPv6 server: inactive
/usr/sbin/keactrl: line 101: rev: not found
/usr/sbin/keactrl: line 101: rev: not found
DHCP DDNS: inactive
/usr/sbin/keactrl: line 101: rev: not found
/usr/sbin/keactrl: line 101: rev: not found
Control Agent: inactive
```

### CODE REVIEW

**Comment by neheb** [comment]
Sign off line is missing.

The keactrl script uses rev, which is not in OpenWrt.

I think the rev thing can be patched out with awk.

**Comment by neheb** [comment]
This is the problem: https://github.com/isc-projects/kea/blob/master/src/bin/keactrl/keactrl.in#L101

I use this pattern on normal linux. I don't know of a more portable way to do it. ping @micmac1

**Comment by neheb** [comment]
ping @aparcar what is this lint error?

**Comment by aparcar** [comment]
I guess it's trying to find a linter for both "makefile" and "patch", which don't exists... I'll look into the documentation to see how to ignore such errors.

**Comment by micmac1** [comment]
On Tue, Sep 15, 2020 at 06:49:03PM -0700, Rosen Penev wrote:
> This is the problem: https://github.com/isc-projects/kea/blob/master/src/bin/keactrl/keactrl.in#L101
>
> I use this pattern on normal linux. I don't know of a more portable way to do it. ping @micmac1

There's lots of results when searching for reversing strings in the
shell. I guess the important thing is that the output is the same as the
one from rev. I tried a few, no luck so far regarding output equality.
And rev seemed to be quicker than the others. :)

We have util-linux available. Maybe creating a small package for rev
wouldn't be a bad idea. It's a tiny tool, after all.

**Comment by neheb** [comment]
Hrm unfortunate. I have a rust utility on my desktop that does this well:

```
git grep HostBuild | choose -2 -f '/'
```

which is equivalent to

```
git grep HostBuild | rev | cut -d '/' -f 2 | rev
```

cut's -f doesn't support negative numbers.

**Comment by aparcar** [comment]
OFFTOPIC: I reported the linting issue [upstream](https://github.com/github/super-linter/issues/733)

**Comment by neheb** [comment]
@tiagogaspar8 replace rev | cut | rev with

```
awk -F"." '{print $(NF)}'
```

**Comment by tiagogaspar8** [comment]
> @tiagogaspar8 here's a patch:
> 
> ```
> --- a/src/bin/keactrl/keactrl.in
> +++ b/src/bin/keactrl/keactrl.in
> @@ -98,7 +98,7 @@ get_pid_from_file() {
>      # Extract the name portion (from last slash to last dot) of the config file name
>      # File name and extension are documented in src/lib/util/filename.h
>      local conf_name
> -    conf_name=$(basename -- "${kea_config_file}" | rev | cut -f2- -d'.' | rev)
> +    conf_name=$(basename -- "${kea_config_file%.*}")
>  
>      # Default the directory to --localstatedir / run
>      local pid_file_dir
> ```

You're a life saver.
Give me a few minutes.

**Comment by tiagogaspar8** [comment]
Wait a second, on the kea sourceone of the devs suggested this:
> can you use awk?
> 
> replace rev with: awk '{for(i=length($0); i>0;i--) printf (substr($0,i,1));}'
> 
> conf_name=$(basename -- "${kea_config_file}" | awk '{for(i=length($0); i>0;i--) printf (substr($0,i,1));}' | cut -f2- -d'.' | awk '{for(i=length($0); i>0;i--) printf (substr($0,i,1));}')

Shouldn't we use this? Or does OpenWRT not have awk?

**Comment by neheb** [comment]
That looks quite complicated. But whatever.

**Comment by tiagogaspar8** [comment]
Nice.
Thanks for the help everyone!

**Pull request merged**
