### PR TITLE
ngircd: Update to 25

### PR DESCRIPTION
**Pull request by neheb**
Remove upstreamed patch.

Switch to .xz archives for smaller size.

Add PKG_BUILD_PARALLEL to speed up compilation.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @leitec 
Compile tested: ramips

### CODE REVIEW

**Comment by neheb** [comment]
I don't use this either. I can remove the maintainer section if you want.

**Comment by leitec** [comment]
That would be great. Thank you!

**Comment by neheb** [comment]
Done. Also reorganized the Makefile a little bit (FTP link is dead).

**Comment by leitec** [comment]
Thanks again.

**Pull request merged**
