### PR TITLE
crowdsec-firewall-bouncer: update to 0.0.25

### PR DESCRIPTION
**Pull request by ne20002**
Update crowdsec-firewall-bouncer to latest upstream release version 0.0.25

Description: backport from master

### CODE REVIEW

**Comment by ne20002** [comment]
Cherry picked from master.

**Comment by trippleflux** [comment]
@ne20002 

Have you realize that both of crowdsec-firewall-bouncer and crowdsec OpenWrt package is using the same config file (/etc/config/crowdsec). Is it intended as it is?.

**Comment by ne20002** [comment]
> Have you realize that both of crowdsec-firewall-bouncer and crowdsec OpenWrt package is using the same config file (/etc/config/crowdsec).

Yes, I've realized that. It works and is intended. For the next packages I wil probably change the packages from using/copying a default config file to writing the default config to the files if the sections aren't there.

**Comment by 1715173329** [comment]
cc: @erdoukki

**Pull request merged**
