### PR TITLE
openconnect: separate out vpnc-scripts and import vpnc

### PR DESCRIPTION
**Pull request by danielg4**
I have been in touch with Nikos by e-mail and he asked me to submit a pull request.

### CODE REVIEW

**Comment by sbyx** [comment]
thanks, however please sign-off your 3 commits in the commit message as noted in our guidelines.

**Comment by danielg4** [comment]
On Fri, 2015-02-06 at 01:14 -0800, Steven Barth wrote:
> thanks, however please sign-off your 3 commits in the commit message
> as noted in our guidelines.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
Is there a way to change that retroactively?

**Comment by nmav** [comment]
Yes you can do it retroactively. You can make the commits again on the same branch you have, and do a forced push.

**Comment by danielg4** [comment]
OK, is this better?

**Comment by nmav** [comment]
It looks fine. I'd prefer to split the second commit into another pull request so I'll have more time to check and align it with the luci module.

**Comment by nmav** [comment]
Ignore the latter. Pull request accepted as is. I've already made a pull request to luci.

**Pull request merged**
