### PR TITLE
vips: update to 8.6.1

### PR DESCRIPTION
**Pull request by MikePetullo**
Signed-off-by: W. Michael Petullo mike@flyn.org
Maintainer: me
Compile tested: ar71xx, mikrotik, master b153dbf0

Description:
vips: update to 8.6.1

### CODE REVIEW

**Comment by hnyman** [comment]
@MikePetullo 

Seems to fail in buildbot, as additional dependencies are detected:
http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/vips/compile.txt
```
Package vips is missing dependencies for the following libraries:
libgif.so.7
Makefile:82: recipe for target '/build/lede-snapshots/mips_24kc/build/sdk/bin/packages/mips_24kc/packages/vips_8.6.1-1_mips_24kc.ipk' failed
```

**Comment by MikePetullo** [comment]
I added +giflib to the vips package's DEPENDS statement, but now I get the following when I run "./scripts/feeds install vips":

[...]
WARNING: Makefile 'package/feeds/packages/vips/Makefile' has a dependency on 'giflib', which does not exist

This is despite the fact the giflib is listed by "./scripts/feeds list".

I am using https://git.openwrt.org/openwrt/openwrt.git as of the date of this post.

**Comment by hnyman** [comment]
Can't reproduce that error. Maybe some invisible garbage on your makefile?

Adding the dependency removes the dependency error for me, and does not cause  any defconfig errors.

```
@@ -29,7 +29,7 @@ define Package/vips
   TITLE:=An image manipulation library
   URL:=http://www.vips.ecs.soton.ac.uk/
   MAINTAINER:=W. Michael Petullo <mike@flyn.org>
-  DEPENDS:=+glib2 +libexif +libexpat +libjpeg +libpng +libstdcpp +libxml2 $(INTL_DEPENDS)
+  DEPENDS:=+glib2 +libexif +libexpat +libjpeg +libpng +giflib +libstdcpp +libxml2 $(INTL_DEPENDS)
 endef
 
 TARGET_LDFLAGS+= \

```

**Comment by hnyman** [comment]
I will push that myself, and let's see what buildbot says.

**Comment by MikePetullo** [comment]
I would appreciate if you pushed what you have. I tried to apply your change, and I still got the error I described above. The strange thing is that I entirely wiped my OpenWrt build tree and tried from scratch. I suspect the problem is on my end.

**Comment by hnyman** [comment]
I pushed it right after I wrote the previous message.
b1ba3b163d

Buildbot seems happy with 8.6.1-2

**Pull request merged**
