### PR TITLE
curl: Fix compiling curl wolfSSL when IPv6 is disabled

### LINKED ISSUE #18082: curl: wolfssl build without IPv6 is broken
Maintainer: @stangri 
Environment:
OpenWrt 21.02.2
mvebu-cortexa9-linksys_wrt3200acm

Description:
The 7.82 release of curl is broken when using wolfssl and IPv6 is disabled. It's patched in the latest curl source but not in the release.

Here is a patch for the 7.82 code:

```patch
--- curl-7.82.0.orig/lib/vtls/wolfssl.c
+++ curl-7.82.0.new/lib/vtls/wolfssl.c
@@ -462,9 +462,9 @@
     const char * const hostname = SSL_HOST_NAME();
     size_t hostname_len = strlen(hostname);
     if((hostname_len < USHRT_MAX) &&
-       (0 == Curl_inet_pton(AF_INET, hostname, &addr4)) &&
+       (0 == Curl_inet_pton(AF_INET, hostname, &addr4))
 #ifdef ENABLE_IPV6
-       (0 == Curl_inet_pton(AF_INET6, hostname, &addr6))
+       && (0 == Curl_inet_pton(AF_INET6, hostname, &addr6))
 #endif
       ) {
       size_t snilen;
```

### PR DESCRIPTION
**Pull request by c---**
Fixes #18082

Maintainer: @stangri 
Compile tested: master mvebu-cortexa9-linksys_wrt3200acm

### CODE REVIEW

**Comment by BKPepe** [comment]
If you take GitHub URL commit/PR and add suffix ``.patch``, it will result in this: ``https://github.com/curl/curl/commit/471d5f44c5189bd78f8839ce8ac1b4b14f4b7d61.patch`` and in this format, it should be added here.

**Comment by c---** [comment]
`git format-patch` does the same thing but got filtered on my first commit. I have updated with the unfiltered version.

**Comment by BKPepe** [comment]
CI still fails for you.

1. Formalities:
```
: === Checking commit 'f39863f8cc706292e0c74c8518b911ef4aec6919'
: Author name (chris) need to be your real name 'firstname lastname'
: Commit subject line MUST start with '<package name>: ' (Fix truncated patch)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: chris <chris@functionalfuture.com>')
: === Checking commit 'faf0ae9f63c9e7de1a697cef9bd313c3d89e70dd'
: Author name (Chris) need to be your real name 'firstname lastname'
: Commit subject line MUST start with '<package name>: ' (Fix compiling curl wolfSSL when IPv6 is disabled)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Chris <chris_github@functionalfuture.com>')
```

2. Patch needs to be refreshed by running ``make package/curl/refresh``

3. All your commits should be squashed to single one.

**Comment by c---** [comment]
Hopefully it's correct now. There was a mix-up between the original filter problem then I had to change my name then OpenWrt filtered it again so I had to do 3 pushes but they should all be merged in to one. I'm still not 100% sure what the OpenWrt tests require (this is why I didn't do a PR in the first place).

**Comment by stangri** [comment]
Thank you @c--- and @BKPepe !

**Pull request merged**
