### PR TITLE
coova-chili: fix compilation with kernel 5.10

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @teslamint 
Compile tested: mips64el

### CODE REVIEW

**Comment by neheb** [comment]
more CI false positives...

**Comment by teslamint** [comment]
@neheb the commit message says 'kernel 4.10', not 5.10.

**Comment by neheb** [comment]
Haha whoops

**Comment by neheb** [comment]
fixed.

**Review by teslamint — APPROVED** [review]

**Pull request merged**
