### PR TITLE
prometheus: update to 2.8.0

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <mail@aparcar.org>

Maintainer: me

### CODE REVIEW

**Comment by BKPepe** [comment]
Would you please tell us on which router (model and architecture) and OpenWrt version, it was compiled and run tested?

**Comment by neheb** [comment]
This passes CircleCI. Looks like no more bzr dependency.

**Comment by aparcar** [comment]
CI got bzr

**Comment by neheb** [comment]
You'll want to backport this then: https://github.com/prometheus/prometheus/commit/2833ad490b66900883b9635940ed5f489cd4c8e3

The buildbots have no bzr.

**Comment by aparcar** [comment]
> You'll want to backport this then: prometheus/prometheus@2833ad4

I'd love to do so. Add the commit as a single patch doesn't work and I'm to unfamiliar with Go to know how to fix it myself. Do you see an easy way to solve this?

**Comment by aparcar** [comment]
> The buildbots have no bzr.

Just to avoid a missunderstading, CI aka CircleCI got bzr so PRs pass, however buildbots don't and therefore the package is never really build.

**Comment by aparcar** [comment]
Works now without `brz`, however these patches are quite big...

**Comment by jefferyto** [comment]
@aparcar You're patching way too much... All you need to do is recreate prometheus/prometheus@2833ad4 on the `release-2.8` branch. The commit message explains what to do:

> hashicorp/serf is only required as a dependency of hashicorp/consul so
bumping the version has no direct consequence for Prometheus itself. The
net gain is that we don't depend anymore on launchpad.net/gocheck which
required the bzr binary to be installed.

[Scrolling down the diff](https://github.com/prometheus/prometheus/commit/2833ad4#diff-37aff102a57d3d7b797f152915a6dc16R48) to find `github.com/hashicorp/serf` you will find the version you want to bump to (`v0.8.2`).

So:
1. Checkout prometheus, switch to `release-2.8` branch
2. `go get github.com/hashicorp/serf@v0.8.2` ([How to Upgrade and Downgrade Dependencies](https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies))
3. `go mod tidy` ([How to Prepare for a Release](https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release)), to actually remove the unnecessary dependencies
4. `git diff -p`, to get the patch

I haven't tried compiling with this change though so you should probably do at least a test compile locally first.

**Comment by aparcar** [comment]
great, thank you very much! will try this latet

**Comment by aparcar** [comment]
@jefferyto seems to work for now. Are you okay with that patch?

**Comment by jefferyto** [comment]
@aparcar I would prefer if you used Go tools to update the dependencies, instead of editing go.mod by hand (you don't know what dependencies the updated version of `github.com/hashicorp/serf` require). Also I'm pretty sure you need to update go.sum also (which would automatically happen if you used the Go way).

As a minor note, you don't need to update Makefile AFAIK, as the OpenWrt Go build process doesn't use it.

**Comment by aparcar** [comment]
all done (hopefully)

**Comment by jefferyto** [comment]
LGTM - thanks!

**Pull request merged**
