### PR TITLE
[openwrt-22.03] dnsproxy: Update to 0.42.2

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: me
Compile tested: mediatek/mt7622
Run tested: redmi ax6s

Description:
- Backported from #18406

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
lgtm

**Comment by PolynomialDivision** [comment]
what about 21.02?

**Comment by 1715173329** [comment]
> what about 21.02?

Well this is not exist on 21.02

**Comment by PolynomialDivision** [comment]
Did not check that. ;) Okay.

**Pull request merged**
