### PR TITLE
python, python3, python-*: use default prefix for host install

### PR DESCRIPTION
**Pull request by NeoRaider**
Maintainers: @commodo, @jefferyto
Compile tested: LEDE r1737
Run tested: Affects host build only, seems to run fine.

Description:

Cleanup & preparation for a staging dir restructuring we're planning in LEDE. Also fixes a few broken `$(STAGING_DIR_HOST)/host` paths.

### CODE REVIEW

**Comment by hnyman** [comment]
any comments here from @commodo @jefferyto ???

**Comment by commodo** [comment]
oh ; my bad for missing this
sorry ; i sometimes miss emails when they're flowing 

+1 for python, python-setuptools & python3 packages
@jefferyto wil handle the rest

q1: do we need to bump PKG_RELEASE for these packges ? 
q2: should we extend this for python-pip ?, python-packages ?

**Comment by hnyman** [comment]
There have been also other small changes lately (e.g. python-pip host build), so I guess that bumping up PKG_RELEASE "just in case" might be a good thing.

**Comment by jefferyto** [comment]
Sorry I've been busy with other things. Looks good to me, though I haven't had time to test.

I wonder, does this affect compiling with OpenWrt, i.e. is `HOST_BUILD_PREFIX` also defined in OpenWrt buildroot? (I haven't had time to investigate/test, sorry) Is this a concern?

**Comment by commodo** [comment]
oh right ; do we care about OpenWrt 15.05 ?
one issue with $(STAGING_DIR)/host I've had was due to 15.05 ;

**Comment by hnyman** [comment]
@NeoRaider knows best, but I think that it should build ok also in Openwrt master (DD), as the relevant things have been backported from LEDE to Openwrt master in https://github.com/openwrt/openwrt/pull/121

So far this concerns only master, not 15.05. (I think that the stable 15.05 should be left unchanged, as the underlying build system path changes have not been backported there. And likely will not be backported.)

**Comment by commodo** [comment]
Ah ; good point.
I think some users maybe we trying to use trunk packages [instead of for-15.05 packages] with a 15.05 base.
And that threw me off.
I guess some people want latest packages with a released base.

**Comment by NeoRaider** [comment]
I think PKG_RELEASE doesn't have any effect for host builds anyways?

I don't think we can (or should) support building the packages master with 15.05.

**Comment by hnyman** [comment]
> I think PKG_RELEASE doesn't have any effect for host builds anyways?

PKG_RELEASE has no effect on the host build itself, but a change in the host tools may have an effect on packages built with the host tools. Packages built with the different host tool versions might be slightly incompatible. So bumping up the PKG_RELEASE helps to ensure that all components are from the same build (or at least the need to re-build/upgrade is seen more clearly). But as this PR is about passing the same directory via a different variable, I guess that there is no real need to the bump.

> I don't think we can (or should) support building the packages master with 15.05.

Agreed, we should not aim to support that. Master/trunk branch is for building for Openwrt & LEDE master/trunk, while the for-15.05 branch packages are for the 15.05 build system. Trying to use/build master/trunk packages with the release 15.05 is and should be unsupported.

As both @commodo  and @jefferyto  said ok, I will merge this. Let's see what happens.

**Comment by hnyman** [comment]
Well, so far the LEDE buildbot faillogs show several python packages failing since the change...
e.g. arm_cortex-a9 has been already compiled: https://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a9/packages/ 

Curiously, the list seems to contain (only?) packages not directly touched here. So I guess that impact coming via the host section of the main python package (or setuptools?)

**Comment by commodo** [comment]
looks like python is expected to be at `/bin/python2.7`
i wonder if something changed path-wise ; will check tomorrow

**Comment by NeoRaider** [comment]
Ugh. Now that python-host.mk and python3-package.mk use HOST_BUILD_PREFIX, they also need $(INCLUDE_DIR)/host-build.mk. I wonder if we want to make HOST_BUILD_PREFIX available though rules.mk like STAGING_DIR_HOST?

**Comment by yousong** [comment]
Hi, @NeoRaider , is there a text of plan available describing the "staging dir restructuring ... in LEDE" that we can refer to to plan/review the needed changes here?

**Comment by hnyman** [comment]
At the first glance it looks like those python packages that explicitly include ``` $(INCLUDE_DIR)/host-build.mk ``` compile ok (like -cffi), but those that only reference ```python-package.mk``` (which then references ```python-host.mk```) fail to compile (like -pyserial and -dns), as ```python-host.mk``` does not reference ```host-build.mk```. 

Should ```python-host.mk``` include ```host-build.mk``` ?

**Comment by commodo** [comment]
From my side, it sounds reasonable for `python-host.mk` to include `host-build.mk`

`python-package.mk` requires `python-host.mk` for the `HostPython` function.
It sounds a bit not-sane, having 2 these interdependent ; but the issue is that Python build requires a Python [of the same version] on the host side to build.

**Comment by commodo** [comment]
or, we could throw a build error with a message if a package Makefile includes `python-host.mk` if a package does not include host-build.mk before `python-host.mk` and/or `python-package.mk`

this is to offer some sanity/enforcement on including mk files for python packages

**Comment by hnyman** [comment]
> From my side, it sounds reasonable for ```python-host.mk``` to include ```host-build.mk```

> or, we could throw a build error with a message if a package Makefile includes ```python-host.mk``` if a package does not include ```host-build.mk``` before ```python-host.mk``` and/or ```python-package.mk```

If I get it right, all python packages using the python installation tools require the host build parts in practice. I would prefer to keep the Makefiles of individual packages as simple as possible. If ```python-package.mk``` is meant to be the top-level umbrella for a python-based package, then it should include the necessary underlying stuff like  ```host-build.mk``` either directly or via lower-level inclusions like ```python-host.mk```.

So I would prefer ```python-host.mk``` to include ```host-build.mk``` instead of forcing dozens of Makefiles to be edited.

**Comment by commodo** [comment]
also fine from my side

**Pull request merged**
