### PR TITLE
libwebp: bump to 1.2.1 and add myself as maintainer ; pillow: add webp support 

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/fc050c7b53116b6e3f2c31797b27cfc76af60e74
Run tested: x86 https://github.com/openwrt/openwrt/commit/fc050c7b53116b6e3f2c31797b27cfc76af60e74

Requested via: #16732

Continuing from #16765  

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by anomeome** [comment]
Presumably caused this
```
/home/kc/wrtpac/source/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-11.2.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/11.2.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: cannot find -llibwebpmux
/home/kc/wrtpac/source/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-11.2.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/11.2.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: cannot find -llibwebpmux
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:126: /home/kc/wrtpac/source/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/libgd-default/libgd-2.3.2/.built] Error 1
make[3]: Leaving directory '/home/kc/wrtpac/source/feeds/packages/libs/libgd'
time: package/feeds/packages/libgd/default/compile#0.27#0.10#0.37
    ERROR: package/feeds/packages/libgd failed to build (build variant: default).
make[2]: *** [package/Makefile:116: package/feeds/packages/libgd/compile] Error 1

```
although it has manifested in two  different ways across two attempts.

**Comment by riptidewave93** [comment]
@commodo seeing the same issue as @anomeome , but on x86:

```
[1/30] Linking C shared library Bin/libgd.so.3.0.10
FAILED: Bin/libgd.so.3.0.10 
: && /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-gcc -fPIC -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/riptide_wave/Repos/OpenWRT-MX100/openwrt/build_dir/target-x86_64_musl/libgd-default/libgd-2.3.2=libgd-2.3.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -flto -DNDEBUG  -L/home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions -shared -Wl,-soname,libgd.so.3 -o Bin/libgd.so.3.0.10 src/CMakeFiles/gd.dir/gd.c.o src/CMakeFiles/gd.dir/gd_avif.c.o src/CMakeFiles/gd.dir/gd_bmp.c.o src/CMakeFiles/gd.dir/gd_color.c.o src/CMakeFiles/gd.dir/gd_color_map.c.o src/CMakeFiles/gd.dir/gd_color_match.c.o src/CMakeFiles/gd.dir/gd_crop.c.o src/CMakeFiles/gd.dir/gd_filename.c.o src/CMakeFiles/gd.dir/gd_filter.c.o src/CMakeFiles/gd.dir/gd_gd.c.o src/CMakeFiles/gd.dir/gd_gd2.c.o src/CMakeFiles/gd.dir/gd_gif_in.c.o src/CMakeFiles/gd.dir/gd_gif_out.c.o src/CMakeFiles/gd.dir/gd_heif.c.o src/CMakeFiles/gd.dir/gd_interpolation.c.o src/CMakeFiles/gd.dir/gd_io.c.o src/CMakeFiles/gd.dir/gd_io_dp.c.o src/CMakeFiles/gd.dir/gd_io_file.c.o src/CMakeFiles/gd.dir/gd_io_ss.c.o src/CMakeFiles/gd.dir/gd_jpeg.c.o src/CMakeFiles/gd.dir/gd_matrix.c.o src/CMakeFiles/gd.dir/gd_nnquant.c.o src/CMakeFiles/gd.dir/gd_png.c.o src/CMakeFiles/gd.dir/gd_rotate.c.o src/CMakeFiles/gd.dir/gd_security.c.o src/CMakeFiles/gd.dir/gd_ss.c.o src/CMakeFiles/gd.dir/gd_tga.c.o src/CMakeFiles/gd.dir/gd_tiff.c.o src/CMakeFiles/gd.dir/gd_topal.c.o src/CMakeFiles/gd.dir/gd_transform.c.o src/CMakeFiles/gd.dir/gd_version.c.o src/CMakeFiles/gd.dir/gd_wbmp.c.o src/CMakeFiles/gd.dir/gd_webp.c.o src/CMakeFiles/gd.dir/gd_xbm.c.o src/CMakeFiles/gd.dir/gdcache.c.o src/CMakeFiles/gd.dir/gdfontg.c.o src/CMakeFiles/gd.dir/gdfontl.c.o src/CMakeFiles/gd.dir/gdfontmb.c.o src/CMakeFiles/gd.dir/gdfonts.c.o src/CMakeFiles/gd.dir/gdfontt.c.o src/CMakeFiles/gd.dir/gdft.c.o src/CMakeFiles/gd.dir/gdfx.c.o src/CMakeFiles/gd.dir/gdhelpers.c.o src/CMakeFiles/gd.dir/gdkanji.c.o src/CMakeFiles/gd.dir/gdtables.c.o src/CMakeFiles/gd.dir/gdxpm.c.o src/CMakeFiles/gd.dir/wbmp.c.o  /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/target-x86_64_musl/usr/lib/libz.so  /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/target-x86_64_musl/usr/lib/libpng.so  /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/target-x86_64_musl/usr/lib/libz.so  /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/target-x86_64_musl/usr/lib/libjpeg.so  -lwebpdecoder  -lwebp  -lwebpdemux  -llibwebpmux  /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/target-x86_64_musl/usr/lib/libpng.so  /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/target-x86_64_musl/usr/lib/libjpeg.so  -lwebpdecoder  -lwebp  -lwebpdemux  -llibwebpmux && :
/home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.2.0/../../../../x86_64-openwrt-linux-musl/bin/ld: cannot find -llibwebpmux
/home/riptide_wave/Repos/OpenWRT-MX100/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.2.0/../../../../x86_64-openwrt-linux-musl/bin/ld: cannot find -llibwebpmux
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:126: /home/riptide_wave/Repos/OpenWRT-MX100/openwrt/build_dir/target-x86_64_musl/libgd-default/libgd-2.3.2/.built] Error 1
make[3]: Leaving directory '/home/riptide_wave/Repos/OpenWRT-MX100/openwrt/feeds/packages/libs/libgd'
time: package/feeds/packages/libgd/default/compile#0.12#0.02#0.13
    ERROR: package/feeds/packages/libgd failed to build (build variant: default).
make[2]: *** [package/Makefile:116: package/feeds/packages/libgd/compile] Error 1
```

**Comment by commodo** [comment]
so, what happened in the 1.2.1 release is that libwebpmux got enabled by default;
i.e. yay, a new feature supported;

what i'm puzzled is why the generated `gdlib.pc` file in libgd ends up getting `libwebpmux`  instead of `webpmux` for the linker args;
looks like CMake voodoo magic gone wrong;

**Comment by neheb** [comment]
I'm part of the problem :).

So libgd has a patch for webp to replace its broken webp search with libwrbp's CMake files. Unfortunately looks like libwrbp's CMake files broke again.

I guess this should be patched to use pkgconfig.

**Comment by commodo** [comment]
it's a CMake issue;
will submit the fix

**Comment by commodo** [comment]
Fix https://github.com/openwrt/packages/pull/16784
Will send upstream later;

**Pull request merged**
