### PR TITLE
prometheus: Update to 2.6.0

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @aparcar 
Compile tested: ramips

### CODE REVIEW

**Comment by jefferyto** [comment]
Looks like the build failed because there are [dependencies that depend on bzr](https://github.com/prometheus/prometheus/pull/4802#issuecomment-435802254). Not sure how to require this in the Makefile.

**Comment by neheb** [comment]
No way to fix that without updating CircleCI.

**Comment by neheb** [comment]
Ugh how nasty. It's failing because of this: https://github.com/prometheus/prometheus/commit/b021025e47135d6f69e162db12885996aa3a21b3#diff-f949e2d81c8076ebbf8af38fcbb72c1f

The solution is to either revert that commit or update go itself.

The latter is better but that requires a new pull request.

**Comment by jefferyto** [comment]
I'll try to have an PR for Go 1.11.4 in the next day or two.

**Comment by neheb** [comment]
> I'll try to have an PR for Go 1.11.4 in the next day or two.

Great. Thanks a lot.

**Comment by jefferyto** [comment]
It's merged (#7729), can try it now.

**Comment by neheb** [comment]
Builds fine now.

**Comment by cshoredaniel** [comment]
Have you **run** tested the changes?  There is no mention of that, or explanation why it is not necessary.

**Pull request merged**
