### PR TITLE
libgpg-error: Fix compilation with GAWK 5.0

### PR DESCRIPTION
**Pull request by neheb**
Patch from Upstream.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @flyn-org

### CODE REVIEW

**Comment by neheb** [comment]
I noticed that staging_dir has awk in the host/bin directory. I wonder if it's copying it from somewhere... I can't find it under tools/

**Comment by patrakov** [comment]
@neheb This is applied to master but not to 19.07, please cherry-pick.

**Comment by neheb** [comment]
Done

**Comment by languitar** [comment]
Any chance to get this to the 18.06 branch?

**Comment by GanesanGuru** [comment]
[patrakov](https://github.com/patrakov),

**Comment by patrakov** [comment]
19.07 is dead.

Anyway, the master commit that fixes this issue is 88026d17bff198b5abdd739de0a6a54cf5e1a721 (from July 11, 2019). Commit cf19fd0cb59f6e91e87f74a5471ea92a751e91d0 does not exist, so I don't know what you are talking about.

**Pull request merged**
