### PR TITLE
Sqm-scripts backport to BB14.07

### PR DESCRIPTION
**Pull request by hnyman**
sqm-scripts: backport package from trunk to BB14.07

Backport of sqm-scripts and luci-app-sqm packages from trunk.
I have been using them in my BB14.07 build without any problems since a few months. 
Backported files are identical to trunk.

There was recently discussion in the openwrt-mailing list about using sqm in BB14.07, so I thought to create a backport, so that others can get sqm in BB14.07.  See e.g. https://lists.openwrt.org/pipermail/openwrt-devel/2015-February/031267.html

There has been no negative feedback since the introduction of sqm to trunk. Instead there has been some positive feedback. So, I think that there are good reasons to backport the package to the release branch for-14.07. The packages are just scripts and lua code, and they are not forced to anybody, so there should no risk of breaking anything.

@tohojo @moeller0

### CODE REVIEW

**Comment by tohojo** [comment]
We have one outstanding bug against sqm-scripts; a fix should be pending. Once that is in, I'd have no qualms about backporting it, but I'd prefer it if someone else from the openwrt team signed off on this :)

**Comment by sbyx** [comment]
@tohojo any updates on this?

**Comment by tohojo** [comment]
Hmm, that other bugfix seems to have stalled... Will have a look at it ASAP!

**Comment by moeller0** [comment]
Hi there,

I am still incapacitated by the flu; I have a hunch that the issue at hand lis complicated by changes in openwrt between the pre-BB state of cerowrt, BB itself and CC trunk, I will try to look at it again today, but can not make any promises as I have a hard time thinking straight and my attention spann is reduced to 3 seconds.

Best Regards
	Sebastian

**Comment by moeller0** [comment]
Hi Toke,

so I think I have got something checked into there cerowrt 3.10 repository that at least survives my testing. But I am not sure whether the changes to the Makefile result in a valid and complete package file (and I do not know how I can test that (I am not setup to build a full cerowrt myself). I would be delighted if other’s could test the changes especially on BB and CC so that we know we have fixed that bug for good. (Actually I rather consider this an added feature, not so much a bug, but certainly a most welcome feature).

	I tries to attach the current source to this email to make testing easier...





Best Regards
	Sebastian

**Comment by tohojo** [comment]
The Makefile looks good as far as I can tell, but it seems you forgot to check in the hotplug script itself, so it fails to build for that reason...

**Comment by hnyman** [comment]
> The Makefile looks good as far as I can tell

The PKG_VERSION should be bumped too, as functionality changes.

**Comment by tohojo** [comment]
On 3 March 2015 14:46:35 CET, hnyman <notifications@github.com> wrote:
>> The Makefile looks good as far as I can tell
>
>The PKG_VERSION should be bumped too, as functionality changes.
Ah yes, of course. Thanks for catching that! :)

**Comment by moeller0** [comment]
Hi Toke,

guess I got a bit rusty with git. Just joking I never got acquainted well enough to begin with. I hope this is fixed now�

Best Regards
	Sebastian

**Comment by moeller0** [comment]
Hi Hannu,


On Mar 3, 2015, at 14:46 , hnyman <notifications@github.com> wrote:

> The Makefile looks good as far as I can tell
> 
> The PKG_VERSION should be bumped too, as functionality changes.

	Done we are at version 8 revision 0 now, I hope this is correct or is revision starred at 1?

Best Regards
	Sebastian

**Comment by hnyman** [comment]
revision is usually started at 1, but to my knowledge having 0 there makes no negative difference

**Comment by hnyman** [comment]
I copied your commits at cerowrt to my own community build, so the patch will get some real-life testing. At least in my own PC it functions ok (but I do not have any reconnecting interfaces).

**Comment by moeller0** [comment]
Hi Hannu

On March 3, 2015 4:52:12 PM GMT+01:00, hnyman <notifications@github.com> wrote:
>I copied your commits at cerowrt to my own community build, so the
>patch will get some real-life testing. At least in my own PC it
>functions ok (but I do not have any reconnecting interfaces).
>

        Excellent, this change really needs diverse testing before being declared sane. So hopefully after say a week we can declare this tested and check it in...

Best Regards
        Sebastian


>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/packages/pull/918#issuecomment-76971684

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tohojo** [comment]
I fixed up the patch (changed the PKG_RELEASE to 1 to keep with tradition and merged the commits into one), and pushed them to the master branch of this repo. Let's leave them there for testing, then merge this pull request to the backports once it's been tested a bit :)

**Comment by sbyx** [comment]
@tohojo and friends: please note that we do have some guidelines for commits here ;)
Your latest one lacks a proper commit title and a signed-off-by.

**Comment by tohojo** [comment]
> @tohojo and friends: please note that we do have some guidelines for commits
> here ;)
> Your latest one lacks a proper commit title and a signed-off-by.

Yeah, sorry, my bad; was a bit trigger-happy there I guess.

Do you also have a guideline for how to fix such oversights? I assume
you don't want me to change the commit; so just do it properly next
time, or is there some procedure to retro-actively add a signed-off-by? :)

**Comment by sbyx** [comment]
You just gave some innocent kittens terrible nightmares. No there's nothing you can do about it right now just please follow the rules next time.

**Comment by tohojo** [comment]
> You just gave some innocent kittens terrible nightmares.

My greatest fear :(

> No there's nothing you can do about it right now just please follow
> the rules next time.

Will do, thanks. And sorry for the inconvenience!

**Comment by tohojo** [comment]
Right, this has now had a couple of weeks to stew... Should we just get the backport underway? @sbyx any objections to merging this? :)

**Comment by hnyman** [comment]
no objections so far...

**Comment by moeller0** [comment]
Hi,

so since the switch to hotplug, we picked up a sensitivity to races between the inial start up of SQM on all sqm-configured interfaces and hotplug starting sqm on a subset of these interfaces. (Or potentially multiple hotplug starts of sqm on the sam interface). In practice it seems to not be a problem, but sqm-scripts definitely is not as robust as it could be. I have not yet a good plan to solve this (without needlessly complicating run.sh).
	I do not believe this to be a merge stopper, but nevertheless it should be fixed�

Best Regards
	Sebastian

**Comment by tohojo** [comment]
Right, let's just get this underway. It's not like anything we come up with is going to be perfect anyway ;)

**Comment by moeller0** [comment]
Hi Toke,


On Mar 25, 2015, at 10:30 , Toke H�iland-J�rgensen <notifications@github.com> wrote:

> Right, let's just get this underway. It's not like anything we come up with is going to be perfect anyway ;)

	Excellent & mange tak or is it m�nga tack now?

Best Regards
	Sebastian

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> Excellent & mange tak or is it m�nga tack now?

Both work -- selv tak / tack själva ;)

-Toke

**Pull request merged**
