### PR TITLE
chrony: change configure flags to meet OpenWrt specifics

### PR DESCRIPTION
**Pull request by thuehn**
As OpenWrt is a root-only system, chrony does not start when
dropping root privileges is enabled. This patch changes chrony
to be compiled with root privileges and removes the dependency to
libcap. Furthermore two features: (1) asynchronous dns request
and (2) rtc support are enabled. The complied ipkg shrinks in
size from former 116kB down to 91kB (on mips).

Signed-off-by: Thomas Huehn <thomas@net.t-labs.tu-berlin.de>

### CODE REVIEW

**Comment by hnyman** [comment]
cc to maintainer @mlichvar

**Comment by mlichvar** [comment]
The package specifies a user/group (USERID:=chrony=323:chrony=323), which should be automatically created when the package is installed and chronyd should be able to start in the default configuration. If that doesn't work, it's a bug that needs to be investigated and fixed. Dropping root privileges is a useful security feature and a lot of packages in OpenWrt seem to do that. Is the user/group present in /etc/passwd and /etc/group when chronyd fails to start? What is the error message?

As for the asynchronous name resolving, it was disabled to avoid dependency on libpthread, which used to be a fairly large package. In the current builds it seems to be much smaller (is it just a dummy package with musl?) and if it will stay like that in DD, I think it's ok to enable the async DNS resolving. Shouldn't the package still specify libpthread in DEPENDS?

As for enabling the RTC support, why do you need that? My understanding is that most devices running OpenWrt don't have an RTC. For the few that do have RTC, I think the kernel RTC support should be good enough. The chrony RTC tracking is mainly useful when the machine is shut down for longer periods of time and it's necessary to adjust the clock by the RTC drift before NTP servers can be reached.

The reported decrease in the package size looks suspicious to me, wasn't there some unrelated change in the toolchain (e.g. uclibc vs musl) between the two packages? After enabling the RTC support the package should be slightly larger.

**Comment by thuehn** [comment]
Hi all,

If the user/group stuff is to be fixed, let's do it!
On our Tplink 4300 v1 MIPS platform, chrony does not start with the following error:

after issueing "/etc/init.d/chrony start", logread shows:
  daemon.crit chronyd[3301]: Fatal error : Could not get chrony uid/gid

In /etc/passwd there is no entry for chrony on the MIPS target.
root:x:0:0:root:/root:/bin/ash
daemon:*:1:1:daemon:/var:/bin/false
network:*:101:101:network:/var:/bin/false
nobody:*:65534:65534:nobody:/var:/bin/false

and /etc/group:
root:x:0:
daemon:x:1:
users:x:100:
network:x:101:
nogroup:x:65534:

But, on our TPLink 4900 platform (POWERPC), there chrony starts properly and the /etc/passwd shows:
root:x:0:0:root:/root:/bin/ash
daemon:*:1:1:daemon:/var:/bin/false
network:*:101:101:network:/var:/bin/false
nobody:*:65534:65534:nobody:/var:/bin/false
chrony:x:1000:1000::/home/chrony:

and /etc/group:
root:x:0:
daemon:x:1:
users:x:100:
network:x:101:
nogroup:x:65534:
chrony:!:1000:

It seems that the USERID from chronys  Makefile (USERID:=chrony=323:chrony=323) is not respected on both platforms. But the powerpc one at least sets the chrony user/group but with wrong values.

By adding the chrony user/group on the MIPS platform by hand to /etc/passwd, chrony starts properly.

The user/group settings in chronys Makefile seem not get respected properly.

Greetings Thomas

**Comment by mlichvar** [comment]
That's odd. It seems to be working for me on ar71xx and x86 kvm targets. Both user and group are created with ID of 323 and chronyd starts without any problems.

Can you please verify after installing the package that /usr/lib/opkg/info/chrony.control has "Require-User: chrony=323:chrony=323" ?

The code that uses this information to create the user and group seems to be in /lib/functions.sh in the default_postinst() function. That would be a good place where to start debugging this issue. FWIW, the changelog for this file says it wasn't changed in last 5 months:

https://github.com/openwrt-mirror/openwrt/commits/master/package/base-files/files/lib/functions.sh

**Comment by hnyman** [comment]
In any case, this pull request currently contains 5 unrelated commits (collectd, watchcat), which should not be merged with this possible change.

**Comment by thuehn** [comment]
ahj ... my fault .... I skrewed up the pull request proccess.
Sorry for that. Whats the best way get this cleared ? Closing this one and open dedicated new ones ?

Greetings Thomas

**Comment by hnyman** [comment]
The core problem is that you have used the "master" branch to the pull request. While PR is open, you should not pull/push more stuff to the branch, or it all gets automatically uncluded in the PR, just like in this case. The main advice (also visible in https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests ) is to always use a new "feature branch" for commits for a pull request.

Depending on your git skills, you could revert the extra commits to your master and "push -f" to update the PR, but easiest might be to abandon this pull request and create a new one to a clean branch.

But that should wait until the discussion with the maintainer has ended and it is seen that the changes are needed. (And you should also increase PKG_RELEASE in Makefile when you change config or functionality.)

**Comment by thuehn** [comment]
Hi Hannu Nyman,

Thy for you advise. I will adapt my git handling to your suggestions.
And lets wfix this first :)

Greeting Thomas

**Comment by thuehn** [comment]
Hi all,

The user owner/rigth of the file /usr/lib/opkg/info/chrony.control are on my TPLink 4900 as follwos:
root@TPLink4900_HA-Raum:~# ls -la /usr/lib/opkg/info/chrony.control
-rw-r--r--    1 root     root           482 Feb  1 18:04 /usr/lib/opkg/info/chrony.control

So /lib/functions.sh uses the root user I guess. So where is the .control file generated ? .. in the opkg process ?

Greetings THomas

**Comment by thuehn** [comment]
Hi again,

I have just flashed a snapshot image from download/openwrt.org and installed chrony via opkg on a ar71xx UBIQUITY Bullet M2. The file rigths of /usr/lib/opkg/info/chrony.control are:

root@Hinterhof:~# ls -la /usr/lib/opkg/info/chrony.control
-rw-r--r--    1 root     root           488 Feb  7 14:30 /usr/lib/opkg/info/chrony.control

So same problem here.

**Comment by mlichvar** [comment]
The owner of the file looks ok and it shouldn't matter for this issue. I was interested in the content of the file. If it has the Require-User line, the chrony package was created correctly and the problem is more likely in the installation phase. In that case I'd suggest to sprinkle the default_postinst() function in /etc/functions.sh with debugging commands (e.g. echo foo >> /tmp/debug.log), reinstall the package and see what path the code takes, if it calls the group_add_user() function, etc.

**Comment by champtar** [comment]
ping @thuehn

**Comment by thuehn** [comment]
Dear champtar,

I have just tested the new chrony version and all works fine (no root user process and the rest)
Thy for the effort !

Greetings from Berlin
Thomas

**Comment by champtar** [comment]
@thuehn this can be closed?

**Comment by thuehn** [comment]
Jupp … this one can be closed.

Greetings Thomas

**Pull request closed without merging**
