### PR TITLE
libuwsc: Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Some consistency updates.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @zhaojh329 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
CircleCI is failing on OpenSSL for some reason...

**Comment by champtar** [comment]
I need to have a look, we don't have per step logs anymore

**Comment by neheb** [comment]
https://github.com/zhaojh329/libuwsc/pull/3

**Comment by neheb** [comment]
Merged upstream.

**Comment by neheb** [comment]
Decided to update to 3.1.1 instead which has this fix.

**Pull request merged**
