### PR TITLE
Python/python3: refresh license information

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainers: @commodo @jefferyto
Compile tested: mvebu, WRT3200ACM, openwrt master
Run tested: not needed

Description:
While looking for a SPDX tag for defusedxml, I looked at these as examples, but found out they had an incorrect SPDX tag, so I changed them. While at it, I looked into the `PKG_LICENSE_FILES`, and got into trouble.  There were non-existing files, files related to windows stuff we don't use/distribute, and packages we are adding to the build, so I'm trying to get these right.

I've run this to find license-related files from the source:
```
Python-2.7.16 $ find . -iregex '.*\(copy\|licens\|notice\|gpl\).*' -a -not -iregex '.*\.\(py\|c\|decTest\|js\)' | egrep -v Doc.library
./Modules/_ctypes/libffi_osx/LICENSE
./Modules/_ctypes/darwin/LICENSE
./Modules/_ctypes/libffi/LICENSE
./Modules/_ctypes/libffi_msvc/LICENSE
./Modules/expat/COPYING
./Tools/pybench/LICENSE
./Tools/pynche/X/xlicense.txt
./Tools/msi/crtlicense.txt
./LICENSE
./Doc/copyright.rst
./Doc/license.rst
./Mac/BuildScript/resources/License.rtf
./Mac/Demo/applescript/Disk_Copy
```
./Modules/_ctypes/libffi_msvc/LICENSE, ./Tools/msi/crtlicense.txt, ./Mac/BuildScript/resources/License.rtf & ./Mac/Demo/applescript/Disk_Copy are obviously not needed, since we're not using any of this.
The Tools are not being built/used either, so I left them out as well.
The most complete of the files above is `Doc/license.rst`, which includes expat, and libffi licenses, so to me, it could be the only one needed to be listed.  I'm no expert, so I'm not minimizing this unless told.
However, after building, the list grows with the inclusion of pip & setuptools: 
```
./install-setuptools/lib/python2.7/site-packages/setuptools-40.6.2.dist-info/LICENSE
./install-pip/lib/python2.7/site-packages/pip-18.1.dist-info/LICENSE.txt
```
I don't know how to handle the multiple source "bundles" inside inside a single Makefile.  I did not touch them at all, since they seem to be versioned (and thus subject to change) but their licenses are both MIT, btw.  It seems to me, if we are looking exclusively at the licensing point of view, that we should be separating them so they each get their own license tags and files, but just bundling them together should be an acceptable compromise.

Here's the same run in Python 3.7:
```
find . -iregex '.*\(copy\|licens\|notice\|gpl\).*' -a -not -iregex '.*\.\(py\|c\|decTest\|js\)' | egrep -v Doc.library
./Modules/_ctypes/libffi_osx/LICENSE
./Modules/_ctypes/darwin/LICENSE
./Modules/_ctypes/libffi_msvc/LICENSE
./Modules/expat/COPYING
./Tools/pynche/X/xlicense.txt
./Tools/msi/bundle/bootstrap/LICENSE.txt
./Tools/msi/exe/crtlicense.txt
./LICENSE
./Doc/copyright.rst
./Doc/license.rst
./Mac/BuildScript/resources/License.rtf
```
and
```
./install-setuptools/lib/python3.7/site-packages/setuptools-40.6.2.dist-info/LICENSE
./install-pip/lib/python3.7/site-packages/pip-18.1.dist-info/LICENSE.txt
```

### CODE REVIEW

**Comment by cotequeiroz** [comment]
@neheb, I think this was merged too soon.  Well, I should have tagged it with a "work needed" label, and I will do it the next time, so I'll share the responsibility.
@commodo, @jefferyto, I've just figured out where to add the pip & setuptools licenses: `files/python-package-*.mk`.  I'll test them and make sure they do what I intend them to, and then I'll open a new PR for it.

**Comment by commodo** [comment]
I think it would work to add
```
define Package/python-pip
$(call Package/python/Default)
  TITLE:=Python $(PYTHON_VERSION) pip module
  VERSION:=$(PYTHON_PIP_VERSION)-$(PYTHON_PIP_PKG_RELEASE)
  DEPENDS:=+python +python-setuptools +python-pip-conf
+  LICENSE:=
+  LICENSE_FILES:+
endef
```

**Comment by cotequeiroz** [comment]
Exactly what I had in mind (almost, I added them above `DEPENDS`).  My next (final?) question is wether to add the CPE_ID:= there?  Both pip and setuptools have a CPE id assigned.  It appears they are not being used by the build system, but I know it's being scanned.  I'm not sure they'll be picked up, but I guess it won't hurt, so I'll add them as well.

**Comment by commodo** [comment]
I have no idea how it is scanned.
But, it would be a good idea to suggest a change in core here (somewhere):
https://github.com/openwrt/openwrt/blob/master/include/package-defaults.mk#L16

**Comment by cotequeiroz** [comment]
I've opened #9047.  I _think_ it is scanned from outside the build system.  One example is the stdowa+uscan mails we get whenever there's a new version of a package upstream.  Another one is https://sdwalker.github.io/uscan/index.html.  The latter does not list pip or setuptools separately, for example.  It is not clear wether or not CPE_ID is used by either.

**Pull request merged**
