### PR TITLE
sudo: preserve sudoers during sysupgrade

### PR DESCRIPTION
**Pull request by puleglot**

### CODE REVIEW

**Comment by sbyx** [comment]
@puleglot please include a Signed-Off-By tag in your commit message.
@kissg1988 okay with you?

**Comment by puleglot** [comment]
@sbyx done.

**Comment by jow-** [comment]
Instead of shipping a keep.d file yourself you can/should use `define Package/sudo/conffiles`.
Existing files (`sudoers`) are tracked by opkg and only kept if they changed compared to the original. Directories are added to `keep.d` automatically.

**Comment by kissg1988** [comment]
@sbyx Fine with me but please consider  @jow- 's comment before merging. Thanks!

**Comment by puleglot** [comment]
@jow- indeed. Thanks!

**Comment by jow-** [comment]
thanks!

**Pull request merged**
