### PR TITLE
https-dns-proxy: switch to https-dns-proxy package name

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin <stangri@melmac.net>

Maintainer: me / @aarond10 
Compile tested: mvebu, WRT3200ACM, 18.06.5
Run tested: mvebu, WRT3200ACM, 18.06.5, start/stop, NS lookups

Description: 
1. As the principal package switched from supporting outdated JSON API to RFC8484, supported by most modern DoH resolvers, the old config file would have broken name resolution with the new version if the package name was kept the same, hence the package name was changed. 
2. Some of the config options were renamed to better reflect their purpose.
3. Support for more command line options of the principal package introduced to the init-file.
4. Maintainer change has been previously acknowledged by @aarond10.

With this PR accepted, I will also be pushing the updated luci app which would list 11 (instead of 3 being supported by the older version) compatible resolvers.

### CODE REVIEW

**Comment by aarond10** [comment]
Signed-off-by: Aaron Drew <aarond10@gmail.com>

**Comment by stangri** [comment]
I have no idea why the 19.07 build has completed and 18.06 and master are failing.

**Comment by hnyman** [comment]
My hunch is that simply changing "-" to "_" does not fully work. Possibly at some step some escaping handles them similarly an dcauses a mixup at filename. Or something like that.

I suggest doing some other change to the name.

**Comment by stangri** [comment]
The 19.07 branch built successfully with the same file names: https://github.com/openwrt/packages/pull/10753 and I have no problem building with 18.06 SDK on my build server as well.

**Comment by hnyman** [comment]
Yeah, I tried to figure it out from the CI logs, but did not succeed. Somehow the master shows a source download failure, while 19.07 apparently gets the sources from somewhere.

**Comment by stangri** [comment]
Could it be failing because of the `PKG_SOURCE_DATE:=2019-12-03` maybe? I've added it as an afterthought. Can you have another look at the Makefile for parameters?

**Comment by stangri** [comment]
Is there a way to force the build attempt again to see if it would work this time?

**Comment by pkgadd** [comment]
Force pushing the branch (e.g. tiny change in the commit description or some other whitespace change) might be enough to consider the CI to try again (I don't know of any different approach, nor do I know for sure the the CI isn't smart enough to filter out white-space-only changes, but in general that should work).

**Comment by hnyman** [comment]
I already retrriggered the ci build three days ago. No help.
I can do it again. (There is a " rerun checks " button.)

**Comment by tapper82** [comment]
On a fresh install this is not working for me.
####
/etc/config/dhcp

config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option nonegcache '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.auto'
	option nonwildcard '1'
	option localservice '1'
	list doh_backup_server '127.0.0.1#5054'
	list server '127.0.0.1#5054'
	option serversfile '/tmp/adb_list.overall'
	option noresolv '0'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv6 'server'
	option ra 'server'
	option ra_slaac '1'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'
####
/etc/config/https_dns_proxy

config https_dns_proxy
	option listen_addr '127.0.0.1'
	option listen_port '5054'
	option bootstrap_dns '1.1.1.1,1.0.0.1'
	option url_prefix 'https://cloudflare-dns.com/dns-query?ct=application/dns-json&'
	option user 'nobody'
	option group 'nogroup'

#####
/etc/config/network

config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fde1:15f1:f440::/48'

config interface 'lan'
	option type 'bridge'
	option ifname 'eth0.1'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option ip6assign '60'

config interface 'wan'
	option ifname 'eth1.2'
	option proto 'dhcp'

config interface 'wan6'
	option ifname 'eth1.2'
	option proto 'dhcpv6'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option ports '0 1 2 3 5t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option ports '4 6t'

All the config files were change by luci.

**Comment by aarond10** [comment]
The option url_prefix '
https://cloudflare-dns.com/dns-query?ct=application/dns-json&' is wrong
with the latest build.
JSON is no longer used. I suspect it should be '
https://cloudflare-dns.com/dns-query'.

**Comment by tapper82** [comment]
I will try the new url thanks. I just wanted to ad that if I set noresolv  to 1 it breaks dns.

**Comment by hnyman** [comment]
> On a fresh install this is not working for me.
> ...
> All the config files were change by luci.

And you also used the updated (not yet merged) LuCI app  from https://github.com/openwrt/luci/pull/3402 ?

**Comment by tapper82** [comment]
> 
> 
> > On a fresh install this is not working for me.
> > ...
> > All the config files were change by luci.


Sorry I just ment to say that I had used the LUCI app to make changes.

> 
> And you also used the updated (not yet merged) LuCI app from [openwrt/luci#3402](https://github.com/openwrt/luci/pull/3402) ?

No I am sorry. I was talking about the package that is in master now. I did not know that this change was not in master yet. pleas forget all about it. Sorry for the noise.

**Comment by stangri** [comment]
> I already retrriggered the ci build three days ago. No help.
> I can do it again. (There is a " rerun checks " button.)

Hannu, have you tried re-running the build script? Before I go make more dramatic changes (like switching the package name to `doh_proxy` for example) I want to understand why the build process is failing on two branches our of three.

**Comment by stangri** [comment]
Uhm, looks like master and 18.06 can't download the sources from repo because of this:
```
https-dns-proxy-2019-12-03.tar.xz: Download from https://github.com/aarond10/https_dns_proxy/ failed
https-dns-proxy-2019-12-03.tar.xz: Cannot fetch commit ts:
  /repos/aarond10/https_dns_proxy/git/commits/2adeafb67cbe8d67148219c48334856ae4f3bd75: the JSON object must be str, not 'bytes'
  /repos/aarond10/https_dns_proxy/commits/2adeafb67cbe8d67148219c48334856ae4f3bd75: the JSON object must be str, not 'bytes'
Checking out files from the git repository...
Cloning into 'https-dns-proxy-2019-12-03'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

I've googled the ```github JSON object must be str, not 'bytes'``` error and there's a bunch of closed issues with fix for python available [here](https://github.com/docusign/docusign-python-client/issues/7) and [here](https://github.com/jupyterlab/jupyterlab-toc/issues/26). Could that be that the build scripts need to be fixed for affected branches?

**Comment by hnyman** [comment]
You might be on the right track, (but the success on 19.07 is the strange thing here.)

I have no python skills, so not much comments from me, but @commodo or @jefferyto  might be able to determine better the correct approach if the problem is a python related in the build system. Also maybe @champtar knows if something has recently changed with circleci images, which could cause this.

We could also merge this and just see if the buildbots build it ok, so that this error is circleci related, or if the buildbots also choke, then it might be a wider issue, (or maybe something related to the github config of aarond10's repo there.)

**Comment by stangri** [comment]
Can you first merge 19.07 (and the Luci app) which built successfully with circleci?

**Comment by jefferyto** [comment]
Can you force-push this again to trigger another CI check?

**Comment by hnyman** [comment]
The circleci build has already been re-triggered three times (once by close/reopen, twice from circleci control panel)

**Comment by jefferyto** [comment]
Sorry, for some reason I thought all previous CI runs occurred on the same day.

This part of the error message:

```
https-dns-proxy-2019-12-03.tar.xz: Download from https://github.com/aarond10/https_dns_proxy/ failed
https-dns-proxy-2019-12-03.tar.xz: Cannot fetch commit ts:
  /repos/aarond10/https_dns_proxy/git/commits/2adeafb67cbe8d67148219c48334856ae4f3bd75: the JSON object must be str, not 'bytes'
  /repos/aarond10/https_dns_proxy/commits/2adeafb67cbe8d67148219c48334856ae4f3bd75: the JSON object must be str, not 'bytes'
```

came from this command:

```
/home/build/build_dir/scripts/dl_github_archive.py --dl-dir="/home/build/build_dir/dl" --url="https://github.com/aarond10/https_dns_proxy/" --version="2adeafb67cbe8d67148219c48334856ae4f3bd75" --subdir="https-dns-proxy-2019-12-03" --source="https-dns-proxy-2019-12-03.tar.xz" --hash="58088baa092cd9634652d65f9b5650db88d2e102cb370710654db7b15f2f0e42"
```

while this part of the error message:

```
Checking out files from the git repository...
Cloning into 'https-dns-proxy-2019-12-03'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

came from this command:

```
echo "Checking out files from the git repository..."; mkdir -p /home/build/build_dir/tmp/dl && cd /home/build/build_dir/tmp/dl && rm -rf https-dns-proxy-2019-12-03 && [ \! -d https-dns-proxy-2019-12-03 ] && git clone  https://github.com/aarond10/https_dns_proxy/ https-dns-proxy-2019-12-03 && (cd https-dns-proxy-2019-12-03 && git checkout 2adeafb67cbe8d67148219c48334856ae4f3bd75 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd https-dns-proxy-2019-12-03 && git log -1 --format='\''@%ct'\''` && rm -rf https-dns-proxy-2019-12-03/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c https-dns-proxy-2019-12-03 | 	xz -zc -7e > /home/build/build_dir/tmp/dl/https-dns-proxy-2019-12-03.tar.xz && mv /home/build/build_dir/tmp/dl/https-dns-proxy-2019-12-03.tar.xz /home/build/build_dir/dl/ && rm -rf https-dns-proxy-2019-12-03;
```

This looks more like a git repo / GitHub issue rather than a Python issue.

**Comment by stangri** [comment]
> This looks more like a git repo / GitHub issue rather than a Python issue.

Can you reproduce the problem with cloning & checkout on your system?

**Comment by jefferyto** [comment]
This is what I get from reproducing the CI script manually inside of the Docker image/container:

```
build@5629a8f18aca:~/build_dir$ make "package/https-dns-proxy/download" V=s
Collecting package info: done
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'bnx2x-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
tmp/.config-package.in:91:warning: ignoring type redefinition of 'PACKAGE_libc' from 'boolean' to 'tristate'
tmp/.config-package.in:119:warning: ignoring type redefinition of 'PACKAGE_libgcc' from 'boolean' to 'tristate'
tmp/.config-package.in:235:warning: ignoring type redefinition of 'PACKAGE_libpthread' from 'boolean' to 'tristate'
#
# configuration written to .config
#
make[1]: Entering directory '/home/build/build_dir'
make[2]: Entering directory '/home/build/openwrt_packages/net/https-dns-proxy'
mkdir -p /home/build/build_dir/dl
SHELL= flock /home/build/build_dir/tmp/.https-dns-proxy-2019-12-03.tar.xz.flock -c '    /home/build/build_dir/scripts/download.pl "/home/build/build_dir/dl" "https-dns-proxy-2019-12-03.tar.xz" "58088baa092cd9634652d65f9b5650db88d2e102cb370710654db7b15f2f0e42" "" || (  /home/build/build_dir/scripts/dl_github_archive.py --dl-dir="/home/build/build_dir/dl" --url="https://github.com/aarond10/https_dns_proxy/" --version="2adeafb67cbe8d67148219c48334856ae4f3bd75" --subdir="https-dns-proxy-2019-12-03" --source="https-dns-proxy-2019-12-03.tar.xz" --hash="58088baa092cd9634652d65f9b5650db88d2e102cb370710654db7b15f2f0e42" || (         echo "Checking out files from the git repository..."; mkdir -p /home/build/build_dir/tmp/dl && cd /home/build/build_dir/tmp/dl && rm -rf https-dns-proxy-2019-12-03 && [ \! -d https-dns-proxy-2019-12-03 ] && git clone  https://github.com/aarond10/https_dns_proxy/ https-dns-proxy-2019-12-03 && (cd https-dns-proxy-2019-12-03 && git checkout 2adeafb67cbe8d67148219c48334856ae4f3bd75 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd https-dns-proxy-2019-12-03 && git log -1 --format='\''@%ct'\''` && rm -rf https-dns-proxy-2019-12-03/.git &&       tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c https-dns-proxy-2019-12-03 |     xz -zc -7e > /home/build/build_dir/tmp/dl/https-dns-proxy-2019-12-03.tar.xz && mv /home/build/build_dir/tmp/dl/https-dns-proxy-2019-12-03.tar.xz /home/build/build_dir/dl/ && rm -rf https-dns-proxy-2019-12-03; );  )    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/https-dns-proxy-2019-12-03.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/https-dns-proxy-2019-12-03.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
https-dns-proxy-2019-12-03.tar.xz: Download from https://github.com/aarond10/https_dns_proxy/ failed
https-dns-proxy-2019-12-03.tar.xz: Cannot fetch commit ts:
  /repos/aarond10/https_dns_proxy/git/commits/2adeafb67cbe8d67148219c48334856ae4f3bd75: the JSON object must be str, not 'bytes'
  /repos/aarond10/https_dns_proxy/commits/2adeafb67cbe8d67148219c48334856ae4f3bd75: the JSON object must be str, not 'bytes'
Checking out files from the git repository...
Cloning into 'https-dns-proxy-2019-12-03'...
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 677 (delta 65), reused 72 (delta 35), pack-reused 563
Receiving objects: 100% (677/677), 191.30 KiB | 0 bytes/s, done.
Resolving deltas: 100% (443/443), done.
Note: checking out '2adeafb67cbe8d67148219c48334856ae4f3bd75'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2adeafb... Stylistic change to logging and a fix for linked-list free in https_client.cc
Packing checkout...
make[2]: Leaving directory '/home/build/openwrt_packages/net/https-dns-proxy'
time: package/feeds/packages/https-dns-proxy/download#0.73#0.53#7.37
make[1]: Leaving directory '/home/build/build_dir'
```

The same Python error occurs because the Docker image is based on Debian 9 (stretch) which has Python 3.5.3. I don't think it's necessary to update dl_github_archive.py to fix this since most systems will have Python 3.6 or newer, and because there is a fallback to the "clone-and-pack" method (which worked in this case).

The only thing I could think of that may have caused the CI failures was some kind of connection problem between CircleCI and GitHub. I'd still be interested to see if the same issue persists in a new CI run.

**Comment by hnyman** [comment]
>  I'd still be interested to see if the same issue persists in a new CI run.

You are welcome.
I triggered a new circleci run a few seconds ago.

image

**Comment by hnyman** [comment]
And it finished now, with a failure:

image

**Comment by jefferyto** [comment]
@stangri Please remove the trailing slash from `PKG_SOURCE_URL` - that's the reason for `fatal: Could not read from remote repository.`

Also, not sure why you removed `PKG_LICENSE_FILES:=LICENSE` from the Makefile. That is the correct license file.

**Comment by jefferyto** [comment]
@hnyman thanks for your help :slightly_smiling_face:

**Comment by stangri** [comment]
> @stangri Please remove the trailing slash from `PKG_SOURCE_URL` - that's the reason for `fatal: Could not read from remote repository.`
> 
> Also, not sure why you removed `PKG_LICENSE_FILES:=LICENSE` from the Makefile. That is the correct license file.

Thank you so much @jefferyto! That seem to have fixed the build problem!

**Comment by hnyman** [comment]
Great.
Let's see what happens in buildbot...

**Comment by commodo** [comment]
> @stangri Please remove the trailing slash from `PKG_SOURCE_URL` - that's the reason for `fatal: Could not read from remote repository.`
> 
> Also, not sure why you removed `PKG_LICENSE_FILES:=LICENSE` from the Makefile. That is the correct license file.

Sorry for jumping in so late. Super-busy & super-tired.

Would it be worth to do some lint/validation for these variables and point them out?
Not sure where to do it [via OpenWrt's build or whether some CI script] but it does feel like a bit of effort was spent for something silly.
This happens every now-n-then [and that's fine], but moving forward, an auto/tool check would be nice to prevent from repeating this effort spending
This is more so that we can move on to the next silly thing that spends effort :)

**Comment by jefferyto** [comment]
> Would it be worth to do some lint/validation for these variables and point them out?

I thought about something like this a while back (for Python packages). `make package/<package name>/check` would seem to be the best place to do this, but there aren't any hooks to run custom checks. (Frankly I'm a little tired of writing patches for the main repo and having to "catch the eye" of a main developer.)

Another issue would be, these custom checks would need to be included in every relevant package makefile. For Python packages that wouldn't be a problem (there already is `python[3]-package.mk`), but there isn't an equivalent way to include checks for all packages in a feed/repo (unless there is a feed-level include file).

The CI script already does [some checks](https://github.com/openwrt/packages/blob/c996e6b4708daffda6bb0ce1057a03e142a396d0/.circleci/config.yml#L28-L57) so we could add more there, though I think it would be best if any linting can be done locally (before opening a PR).

**Pull request merged**
