### PR TITLE
nss: disable parallel compilation

### PR DESCRIPTION
**Pull request by neheb**
Fails too reliably and too often. Just disable.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lucize 
Compile tested: ath79

### CODE REVIEW

**Comment by lucize** [comment]
I thought this was fixed upstream

**Comment by neheb** [comment]
As of this version, doesn't look like it.

**Comment by lucize** [comment]
let's see with the new version ?

**Comment by neheb** [comment]
Fails even with new version.

**Comment by neheb** [comment]
Switched commit to a version update and PKG_BUILD_PARALLEL disabled.

**Comment by neheb** [comment]
ping @lucize

**Comment by lucize** [comment]
LGTM

**Pull request merged**
