### PR TITLE
tvheadend: Upgrade to 4.2.6

### PR DESCRIPTION
**Pull request by sjjgo**
Maintainer: @sairon
Compile tested: MIPS, [BT HomeHub 5a](https://openwrt.org/toh/bt/homehub_v5a), master
Run tested: MIPS, [BT HomeHub 5a](https://openwrt.org/toh/bt/homehub_v5a), master

Description:
This package has been stuck on the deprecated 4.0 series for some time. There have been a number of requests for updates:
https://github.com/openwrt/packages/issues/4409

Simply increasing the version number results in a segfault. This is recorded here:
https://tvheadend.org/issues/4286#change-26436
https://tvheadend.org/boards/4/topics/30019?r=30968#message-30968

Between this, and other information, the problem is with the linking of the iconv. In the 4.0 series, simply linking the musl libiconv-stub was sufficient. This is no longer the case in the 4.2 series – hence the segfault with the previous Makefile.

The issue stems from the having `--enable-bundle` turned on in the build process. The 'bundle' in Tvheadend is responsible for the web front-end used for configuration, EPG etc. If the bundle is not enabled, then things will build and run OK, just without the front end.

I have made the bundle a separate build option. To enable it, users will need to enable CONFIG_BUILD_NLS (i.e., native language support). Without this, libiconv-full it won't be properly linked, even if it is added as a dependency. (I think this is related to the flags that are passed to the C compiler.) Therefore this is a hard dependency – BUILD_NLS is required for the webfront end.

Moving this out has an added advantage in that it reduces the size of the binary by approximately 5x. That means that Tvheadend takes significantly less space. It can still be configured through other means (e.g., editing text files, other utilities).

I have tested building with and without the bundle. The correct libiconv is pulled in and linked. My build has been up for 24hrs now.

In tidying up everything I have introduced a build option (it is disabled by default) for HDHomeRun as requested here:
https://github.com/openwrt/packages/issues/3342

I have also started the process of adding configuration options for the different build options.  This should allow people to customize the installation, saving compile time and vital flash space. I also dropped out more of the video libraries, although I plan to add them back in with arch-specific flags so that those running on machines that can build the video libraries can do so.

Would really appreciate testers for this PR. Thanks.

### CODE REVIEW

**Comment by hnyman** [comment]
> I'm not sure if @sairon is maintaining the package any more. I am happy to take this responsibility on if they no longer wish to be involved in looking after this package.

You could add yourself as the second maintainer to the maintainer line in Makefile. It is a comma-separated list.

At the same time, please remove the extra space at the end of line 34 of Makefile.

**Comment by sjjgo** [comment]
@hnyman OK, done.

**Comment by sairon** [comment]
@sjjgo Thanks for the PR. I am not using the package anymore so I can't update and test it myself. Btw. the email used in the maintainer line is not working anymore.
If you are willing to take the maintenance over, I (and others) will appreciate it.

**Comment by hnyman** [comment]
How essential is that web front-end for practical usage?
I am just thinking from average user's perspective. Does he need/want that web GUI?

**Comment by sjjgo** [comment]
@sairon I'm happy to take it over, no problem. Would you like me to remove you as the maintainer?  

@hnyman When people install the package they will probably expect to see the front end, I think? The 'bundle' being disabled isn't very clean (it loads a blank webpage) and you might think that something was broken. (Everything works fine if you have a pre-existing configuration without the bundle, though.) Are you suggesting the dependencies should be altered so that, by default, the bundle is enabled, but those who want to minimize the install size can disable it if they so wish?

**Comment by hnyman** [comment]
> Are you suggesting the dependencies should be altered so that, by default, the bundle is enabled, but those who want to minimize the install size can disable it if they so wish?

Not quite sure, as I do not use the package myself.  I am just wondering what the casual first-time user expects to see there. Is the application usable without previous installation and the front-end?

(The requirement for full iconv is nuisance as the whole buildbot build is done without BUILD_NLS, I think. I am a bit surprised that it is a hard requirement.)

**Comment by sjjgo** [comment]
A casual first time user would expect the web frontend to be there. So if that's the aim then `--enable-bundle` should be the default. But that does, as you say, necessitate full iconv and BUILD_NLS.

I spent a lot of time working out if it were possible to get it running another way. Using iconv-stub will cause a segfault. Linking iconv-full but not enabling BUILD_NLS also results in segfaults (presumably something to do with compiler switches in the build process).

The iconv requirements were present but lax in 4.0.10 (the current version in the repo). But it is even stricter in the current Tvheadend master – at the moment I can only get it to gracefully die after being unhappy with the results of testing iconv . Something I will need to work out when I have time, because as far as I can tell iconv-full is the GNU version. Looking at the commit log it's musl related in some way. (I haven't tried to compile with the other C libraries.)

iconv is [used extensively](https://github.com/tvheadend/tvheadend/search?q=intlconv) in Tvheadend. I think attempting to patch it to, say, only work in English without iconv-full would be more trouble than it's worth.

What do you think? We could just hide the whole package behind BUILD_NLS, but then one might wonder what the point of having the package in the repo would be if people using buildbot builds (presumably the majority) can't see it. Not sure what's for the best.

**Comment by hnyman** [comment]
Sounds nasty.

One not-perfect option is to leave the current old version 4.0.x there. That seems to work without BUILD_NLS. Yes, it is deprecated, but may actually still work as expected by the user.

Hiding the package behind BUILD_NLS would hide the whole package from buildbot and thus from casual users. So that does not provide much help.

Hmmm.
Based on your link, the usage is not quite that extensive. A dozen instances.

**Comment by sjjgo** [comment]
Yeah, it's not super ideal. Hopefully I'll have some time later in the week to see just how critical iconv is for some of this stuff. Going down the 'perhaps it could be patched' rabbit hole. Will let you know when I have something new.

**Comment by sairon** [comment]
@sjjgo 
> I'm happy to take it over, no problem. Would you like me to remove you as the maintainer?

Yes please, remove me. Thanks!

Btw. the iconv dependency isn't used just because of the UI localization but also to convert texts in the EPG, see for example this historic PR for context: https://github.com/tvheadend/tvheadend/pull/90

**Comment by benteam10** [comment]
Here is Tvheadend 4.2.6 for LEDE 17.1.4     for architecture  AR7xxx 
i run it on a Archer C7 V2  MIPS 24Kc   
https://drive.google.com/open?id=1k1Bs-GCsIyG68wdNGnPL6B-ybdjyRda5

runs very well

i couldnt compile it for chaos calmer since the built system is not complete it doesnt have the packages anymore. 
if it starts and ask for a username and password  edit the /etc/init.d/tvheadend    in the line that shows the ARGS  -B   ad  -C  save and start it, is not going to ask you for credentials anymore.

**Comment by benteam10** [comment]
Compiled for 4.2.6 fine for ar71xx and 4.3 for ar71xx tplink archer c7 V2, and Cortex a9 Linksys WRT3200ACM works like a charm.

https://1drv.ms/u/s!Ar_ONyLrmjE06zzKPkoHGdxQzLRk
https://1drv.ms/u/s!Ar_ONyLrmjE06zvaWyMIpJeh-Y72

**Comment by 9000000** [comment]
@benteam10 
Can you help me to compile the ramips xiaomi r3g for real, really i am a user do not know how to do both

Thanks you

**Comment by BKPepe** [comment]
@sjjgo May I ask you to look at it, so we can have it in OpenWRT? If you want, I can take a look to at it as there is already version 4.2.8.

**Comment by sjjgo** [comment]
I haven't had the time to write the patches for this, sorry. We have a new arrival in the house so I don't know when I will be able to get around to it.

**Comment by diizzyy** [comment]
Closing this, please submit a new PR if/when you have time.

**Pull request closed without merging**
