### PR TITLE
vpnbypass: add procd reload trigger for vpnbypass config

### PR DESCRIPTION
**Pull request by ysc3839**
Maintainer: @stangri
Compile tested: N/A
Run tested: N/A

Description:
https://github.com/openwrt/luci/pull/3388

### CODE REVIEW

**Comment by stangri** [comment]
Thank you Richard.

Is the purpose of this to get rid of ucitrack completely? Should the ucitrack-related code be also removed from the [Makefile](https://github.com/ysc3839/openwrt-packages/blob/vpnbypass/net/vpnbypass/Makefile#L57-L87).

**Comment by feckert** [comment]
I think we should merge this and then remove the ucitrack add from the luci feed of luci-app-vpnbypass?

**Comment by ysc3839** [comment]
@stangri Thanks for reminding.

**Comment by stangri** [comment]
@ysc3839 I don't have merge rights, but this looks good.

**Pull request merged**
