### PR TITLE
openCV: Add library openCV2.4.10

### PR DESCRIPTION
**Pull request by SchumyHao**
we(WRTnode team) add opencv support on openwrt. And we have tested it on our board--WRTnode(based on mt7620n).

### CODE REVIEW

**Comment by sbyx** [comment]
thanks however please change your commit https://github.com/SchumyHao/packages/commit/e0dacef19a6463bc3ef49447a13eb86814b75ad1 to include a Signed-off-by tag as noted in guidelines and please use the package name as a prefix in your commit title (e.g. openvc: Add library)

**Comment by SchumyHao** [comment]
I'v re-commit the repo. Changed commit message into right formate, add a sign-off. Am I right this time?

**Comment by roger-** [comment]
@sbyx how does this look now?

**Comment by champtar** [comment]
hi @SchumyHao,
please squash your commits into one

**Pull request closed without merging**
