### PR TITLE
libuwifi: update to latest master

### PR DESCRIPTION
**Pull request by neheb**
Fix version to be apk compatible.

Maintainer: @br101

### CODE REVIEW

**Comment by br101** [comment]
There is a bug in master, I don't recommend to use it...

**Comment by BKPepe** [comment]
Was it solved? I can not see any new commits in the master branch.

**Comment by br101** [comment]
Nope, sorry

**Comment by BKPepe** [comment]
Is there at least some issue created, so we can track it?

**Comment by br101** [comment]
Ah, sorry, i said something wrong. libuwifi master is fine, there was a hard to track bug in horst, but that's a different story. So please go ahead and sorry.

**Pull request merged**
