### PR TITLE
nmap: bump to 7.91

### PR DESCRIPTION
**Pull request by rockdrilla**
Maintainer: @nunojpg
Compile tested: ath79/mips_24kc_musl (TP-Link Archer C7 v2)
Run tested: ath79/mips_24kc_musl (TP-Link Archer C7 v2)

Description: nmap: bump to 7.91

changes: https://nmap.org/changelog#7.91

drop patches (applied upstream):
- 010-Avoid-using-namespace-std-causing-name-conflicts.patch

refresh patches:
- 020-Python3-port-of-ndiff.patch
- 030-libcxx.patch

Package size changes:

```
ncat      |   68441 ->   68533 | +92
ncat-ssl  |  199066 ->  198521 | -545
ncat-full |  199957 ->  199558 | -399
ndiff     |   19151 ->   19374 | +223
ndiff-src |   11938 ->   11959 | +21
nmap      | 2267993 -> 2295370 | +27377
nmap-ssl  | 2270065 -> 2298571 | +28506
nmap-full | 5438057 -> 5478547 | +40490
nping     |  194540 ->  194901 | +361
nping-ssl |  197917 ->  198120 | +203
```

Binary size changes:

```
ncat      |  137712 ->  137700 | -12
ncat-ssl  |  162776 ->  158676 | -4100
ncat-full |  162872 ->  162868 | -4
ndiff     |    2580 ->    2613 | +33
ndiff-src |   54524 ->   54884 | +360
nmap      | 2489164 -> 2426532 | -62632
nmap-ssl  | 2497524 -> 2430784 | -66740
nmap-full | 2651488 -> 2588840 | -62648
nping     |  466176 ->  470272 | +4096
nping-ssl |  478692 ->  478680 | -12
```

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
**Not tested (!)**: ndiff/python3.
However, there's no error during package build.

**Comment by BKPepe** [comment]
Not sure, if we can merge this because of https://github.com/openwrt/packages/issues/14459

**Comment by rockdrilla** [comment]
@nunojpg, @BKPepe, friendly ping: https://github.com/nmap/nmap/issues/2199#issuecomment-792048244

**Comment by hnyman** [comment]
@BKPepe @nunojpg @rockdrilla 

Could this be backported/cherry-picked to 21.02?  There seems to be some interest for it.
(and this has been here without any further change needs since March, so I guess that it should fit into 21.02 easily, as it was branched off in February)

**Comment by BKPepe** [comment]
Although I am not the maintainer, why not.

**Comment by Nemesis77swe** [comment]
> Although I am not the maintainer, why not.

thank you, because the existing 7.8-3 is buggy, and when it crashes, it won't work anymore..

**Pull request merged**
