### PR TITLE
net/wireguard - bump to experimental-0.0.20161116.1

### PR DESCRIPTION
**Pull request by viisauksena**
use latest tag https://git.zx2c4.com/WireGuard/tag/?h=experimental-0.0.20161116
Maintainer @zorun 
PR by wireguard@viisauksena.de

### CODE REVIEW

**Comment by zorun** [comment]
You're missing the signed-off-by, and you should not increase PKG_RELEASE.

Also, there is a newer snapshot experimental-0.0.20161116.1

**Comment by viisauksena** [comment]
thought pkg release is needed by opkg - so updater know that there is a new package - otherwise it would stick with it. 
so you want me to change your 2 hints? or do an own PR ?

**Comment by hnyman** [comment]
> thought pkg release is needed by opkg - so updater know that there is a new package - otherwise it would stick with it. 

Think it as PKG_VERSION+PKG_RELEASE combination. 

When you increase PKG_VERSION, you should actually reset PKG_RELEASE back to 1, as it is the first release of that version.

And yes, you need a proper signed-off-by line in the commit message.

**Comment by viisauksena** [comment]
so i should have done the opposite, instead of increasing it to 4 - set it back to 1 ? 
ok than, i wait for Zoruns answer - no need for double work

**Comment by hnyman** [comment]
> so i should have done the opposite, instead of increasing it to 4 - set it back to 1 ? 

Yes. But that is no big mistake. I feel that if unsure about the need to increase it, it is always best to increase it just in case ;-)

opkg uses PKG_VERSION+PKG_RELEASE combination, so PKG_RELEASE is the minor version, not the main thing.

**Comment by viisauksena** [comment]
so, and how do i get this proper signed off by now into it? do i have to do a new PR ? or any magic

**Comment by hnyman** [comment]
> so, and how do i get this proper signed off by now into it? do i have to do a new PR ? or any magic

You have the stuff in a branch, so it is easy. Just squash the two commits together (with git rebase -i) and edit the commit message at the same time. Then "git push -f" to update this PR automatically (the new commit overwrites the two existing ones).

I gave more detailed advice already once today:
https://github.com/openwrt/packages/pull/3528#issuecomment-261703071

**Comment by viisauksena** [comment]
ok, somehow i still have 2 commits, but now everything should be fine

**Comment by zorun** [comment]
Please squash the commits together, as explained by @hnyman

**Comment by hnyman** [comment]
And at the same edit the signed-off-by to have your correct name. "fuzzle" does not fly.

"git rebase -i HEAD~2"

**Comment by viisauksena** [comment]
done ..

**Comment by zorun** [comment]
Looks good to me now, thanks!

**Pull request merged**
