### PR TITLE
protobuf: upgrade to version 3.3

### PR DESCRIPTION
**Pull request by persandstrom**
Maintainer: Per Sandström / @persandstrom
Compile tested: Freescale i.MX28 series,
Run tested:

Description:
Upgrade protobuf to version 3.3

### CODE REVIEW

**Comment by hnyman** [comment]
Thanks, 
at the next version upgrade please switch checksum hash from PKG_MD5SUM to sha256 PKG_HASH.

**Comment by persandstrom** [comment]
@artynet The patch seems to be applied to v3.3, have you experienced any problems with this version?

**Comment by hnyman** [comment]
Yep. that patch is included in the 3.3.0 (branch/tag inclusion info is visible, if you go directly to the proper commit instead of via pull request: 

`https://github.com/google/protobuf/commit/b7f25d42d3bd1b8cd9d995111e654a4601fe2ac8`
https://github.com/google/protobuf/commit/b7f25d42d3bd1b8cd9d995111e654a4601fe2ac8

**Comment by artynet** [comment]
ok thank you ! @hnyman @persandstrom

**Pull request merged**
