### PR TITLE
libimobiledevice: Fix compilation without deprecated OpenSSL 1.0.2 APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: ???
Compile tested: ar71xx

### CODE REVIEW

**Comment by cshoredaniel** [comment]
+run tested; what uses this?

**Comment by neheb** [comment]
usbmuxd. The packages are basically abandoned. This is only a compilation fix.

To actually fix problems with these packages they need updates. There's been some pushback against that.

**Comment by cshoredaniel** [comment]
I really think we need to better define what is an abandoned package where this is acceptable and what is a properly maintained package that should not be auto-merged for stuff like this.

**Comment by neheb** [comment]
@lukbaj

**Comment by neheb** [comment]
Closing as there's no interest.

**Pull request closed without merging**
