### PR TITLE
auc: fix typo - determing → determine

### PR DESCRIPTION
**Pull request by lynxthecat**

### CODE REVIEW

**Comment by BKPepe** [comment]
CI is still failing for you.

- You should fix the commit title
- You should use the real name in the ``Signed-off-by``

**Comment by lynxthecat** [comment]
Are you in a position to override? This is getting a bit silly for fixing a typo.

**Comment by BKPepe** [comment]
CI still complains.

```
Author name (lynxthecat) need to be your real name 'firstname lastname'
: Commit subject line seems ok (auc: fix typo - determing → determine)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: lynxthecat <lynx.light0@gmail.com>')
```

**Comment by 1715173329** [comment]
correct style:
```
git config user.name "Lynx TheCat"
git commit --amend --reset-author --signoff
```

though i dont think somebody would be named "TheCat"

**Comment by lynxthecat** [comment]
I think and hope that I managed that with the most recent commit?

**Pull request closed without merging**
