### PR TITLE
[RFC] net/mwan3: add ubus interface for mwan3track

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: me
Compile tested: lantiq, xrx200, LEDE
Run tested: lantiq, xrx200, LEDE

Description:
Add ubus interface to mwan3track to get some important tracking data. In the future the other datas
ike policies, rules and connected. should also be made available through the ubus interface.

### CODE REVIEW

**Comment by feckert** [comment]
@hnyman any hints about the implementation? Or should i change it into a PR?

**Comment by hnyman** [comment]
> @hnyman any hints about the implementation? Or should i change it into a PR?

Sorry, no help/feedback from me. I don't have experience with json handling.
Hopefully somebody more experienced on that front would look through your code.

I guess that  if no feedback comes for a while, we could just merge this.

**Comment by feckert** [comment]
@hnyman thanks for comment

**Comment by jow-** [comment]
LGTM on the ubus implementation.

**Comment by feckert** [comment]
@jow- thanks for review i will to a follow up PR to add the ubus interface. During review i have already added the connected section of mwan3 to ubus.

**Pull request closed without merging**
