### PR TITLE
net/zerotier: Fix source tarball filename

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @mwarning 
Compile tested: arm, orange pi plus, LEDE trunk
Run tested: No

Description:
HTTP header content-disposition isn't honored resulting in source tarball name only containing version number.
Switch to GIT repo as workaround to avoid clashing filenames.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Sorry for not noticing earlier :-/

**Comment by antonlacon** [comment]
As far as I know, PKG_HASH is LEDE only; OpenWrt still requires PKG_MD5SUM.

**Comment by diizzyy** [comment]
Fixed, sorry...
Shouldn't do this stuff late at night...

**Comment by hnyman** [comment]
@mwarning has not yet commented, but this is trivial and works for me,
so let's merge it as it clarifies the filename.

Ps. zerotier seems to still fail in buildbot.
E.g. http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/zerotier/
```
undefined reference to `LZ4_compress'
```
Compiles ok for me, so something strange with compiling in buildbot. 
As buildbot compiles with all packages enabled, it is possible that zerotier's configure script(?) enables some functionality that should not be enabled.

**Comment by mwarning** [comment]
@hnyman imo, no need for me comment regarding this merge :-)

I will look into the LZ4 problem. I have never tried to build for cortex-a15.

**Comment by hnyman** [comment]
> I will look into the LZ4 problem. I have never tried to build for cortex-a15.

It is not to be related to that platform specifically . I just picked that up as an example, as it was the most recent build from up-to-date sources...

Other architectures fail, too:
http://downloads.lede-project.org/snapshots/faillogs/mips_mips32/packages/zerotier/compile.txt
http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/zerotier/compile.txt
http://downloads.lede-project.org/snapshots/faillogs/x86_64/packages/zerotier/compile.txt

**Comment by diizzyy** [comment]
Works for me too locally so I think it unintentionally picks up lz4,

**Comment by mwarning** [comment]
There are references to lz4 in the makefile: https://github.com/openwrt/packages/blob/master/net/zerotier/patches/0002-fix-build.patch#L19

**Comment by diizzyy** [comment]
Since we have more than one package of lz4 add this a dep.
+liblz4

**Comment by mwarning** [comment]
zerotier uses it's own lz4 if it can't find it.

`mips-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/mwarning/lede/build_dir/target-mips_24kc_musl-1.1.15/ZeroTierOne-1.1.14:ZeroTierOne-1.1.14 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/mwarning/lede/staging_dir/target-mips_24kc_musl-1.1.15/usr/include -I/home/mwarning/lede/staging_dir/target-mips_24kc_musl-1.1.15/include -I/home/mwarning/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/usr/include -I/home/mwarning/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/mwarning/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include  -Wall -fPIE -pthread  -DNDEBUG    -c -o ext/lz4/lz4.o ext/lz4/lz4.c`

**Pull request merged**
