### PR TITLE
Add lxc-device applet to the utils/lxc

### PR DESCRIPTION
**Pull request by samm-git**
Signed-off-by: Alex Samorukov <samm@os2.kiev.ua>

### CODE REVIEW

**Comment by jow-** [comment]
@lperkov

**Comment by lperkov** [comment]
Hi Alex,

can you please put it in alphabetical order? And please put one sentance about what is device applet. Thanks.

Regards,
Luka

**Comment by samm-git** [comment]
@lperkov done, thanks

**Comment by dangowrt** [comment]
looks good to me, @lperkov ?

**Comment by lperkov** [comment]
Done, thanks.

I will need to figure out how these git pull requests actually work... Idealy it would be a fixed-up in one commit and not two.

**Pull request merged**
