### PR TITLE
treewide: mostly remove AUTORELEASE

### PR DESCRIPTION
**Pull request by paulfertser**
For the (most) packages present in x86_64 snapshots the following scripts were used to extract and substitute PKG_RELEASE:

cat Packages | sed -n '/^Package/{s/.*: //;h};/^Version/{s/.*: .*-\([0-9]*\)/\1/;H;x;s/\n/\t/;p}' > package.releases

for i in $(git grep -l PKG_RELEASE:=..AUTORELEASE); do
  rel=$(grep "^$(sed -n '/BuildPackage/{s/.*,//;s/))//;p;q}' $i)[0-9]*	" package.releases | head -n1 | cut -f2)
  [ -n "$rel" ] && sed -i "s/\$(AUTORELEASE).*/$rel/" $i
done

Plus few manual fix-ups.

The rest will require a different approach or more manual interventions.

Signed-off-by: Paul Fertser <fercerpav@gmail.com>

Maintainer: various
Compile tested: no
Run tested: no

Description:

### CODE REVIEW

**Comment by BKPepe** [comment]
This needs to be rebased, if we want to get rid of autorelease, which I don't want as it is a quite an amazing feature at least from my side, because as we started to remove it, then the issue, which autorelease tried to fix is showing again - forgetting to bump ``PKG_RELEASE``.

cc: @aparcar and @Ansuel

**Comment by aparcar** [comment]
Hey sorry I wasn't pinged on the first one and missed this PR, I'm a big fan!

**Comment by paulfertser** [comment]
@aparcar Hey! If you think this change is worth it and will get merged, I'll work on rebasing/reworking it shortly.

**Comment by aparcar** [comment]
Anyway could you please rebase this and I'll review it asap

**Comment by aparcar** [comment]
Thank you very much for your work and patience. 

PS: In the future please don't post diffs directly in the commit message, it confuses git very much.

**Pull request merged**
