### PR TITLE
jool: fix PKG_BUILD_DIR to avoid kernel ABI mismatch

### PR DESCRIPTION
**Pull request by NeoRaider**
As jool builds a kernel module, a PKG_BUILD_DIR under KERNEL_BUILD_DIR must
be used to avoid reusing build artifacts when switching to a different
target of the same architecture. Otherwise, kernel ABI mismatches may
result, leading to an unusuable module, or build failures like the
following:

    Package kmod-jool is missing dependencies for the following libraries:
    crypto_hash.ko

Maintainer: @danrl - please ACK, and I'll apply the patch to both the master and lede-17.01 branches.

### CODE REVIEW

**Comment by champtar** [comment]
@NeoRaider the bug you describe impact every KernelPackage no ?

**Comment by NeoRaider** [comment]
@champtar Only packages that explicitly set PKG_BUILD_DIR (which is necessary in this case because it must include PKG_SOURCE_SUBDIR); otherwise, a correct PKG_BUILD_DIR is set by default as long as *kernel.mk* is included before *package.mk*.

**Comment by champtar** [comment]
thanks @NeoRaider

**Comment by NeoRaider** [comment]
No reply from the maintainer for a week, merging to fix the build issue.

**Comment by danrl** [comment]
I was busy. Of course ACK. Thanks for merging.

**Pull request merged**
