### PR TITLE
libssh: simplify endianness check

### PR DESCRIPTION
**Pull request by nmav**
Signed-off-by: Nikos Mavrogiannopoulos <n.mavrogiannopoulos@gmail.com>

Maintainer: Mislav Novakovic <mislav.novakovic@sartura.hr>
Compile tested: mvebu
Run tested: -

Description:
This simplifies the endianness checks.

### CODE REVIEW

**Comment by neheb** [comment]
I noticed after the last version bump, it was failing to compile without deprecated OpenSSL APIs. Patch:

```
--- a/src/libcrypto.c
+++ b/src/libcrypto.c
@@ -536,7 +536,7 @@ static int evp_cipher_set_encrypt_key(struct ssh_cipher_struct *cipher,
     int rc;
 
     evp_cipher_init(cipher);
-    EVP_CIPHER_CTX_init(cipher->ctx);
+    EVP_CIPHER_CTX_reset(cipher->ctx);
 
     rc = EVP_EncryptInit_ex(cipher->ctx, cipher->cipher, NULL, key, IV);
     if (rc != 1){
@@ -569,7 +569,7 @@ static int evp_cipher_set_decrypt_key(struct ssh_cipher_struct *cipher,
     int rc;
 
     evp_cipher_init(cipher);
-    EVP_CIPHER_CTX_init(cipher->ctx);
+    EVP_CIPHER_CTX_reset(cipher->ctx);
 
     rc = EVP_DecryptInit_ex(cipher->ctx, cipher->cipher, NULL, key, IV);
     if (rc != 1){
@@ -652,7 +652,7 @@ static void evp_cipher_decrypt(struct ssh_cipher_struct *cipher,
 
 static void evp_cipher_cleanup(struct ssh_cipher_struct *cipher) {
     if (cipher->ctx != NULL) {
-        EVP_CIPHER_CTX_cleanup(cipher->ctx);
+        EVP_CIPHER_CTX_reset(cipher->ctx);
         EVP_CIPHER_CTX_free(cipher->ctx);
     }
 }
@@ -1080,11 +1080,11 @@ int ssh_crypto_init(void)
     if (libcrypto_initialized) {
         return SSH_OK;
     }
-    if (SSLeay() != OPENSSL_VERSION_NUMBER){
+    if (OpenSSL_version_num() != OPENSSL_VERSION_NUMBER){
         SSH_LOG(SSH_LOG_WARNING, "libssh compiled with %s "
             "headers, currently running with %s.",
             OPENSSL_VERSION_TEXT,
-            SSLeay_version(SSLeay())
+            OpenSSL_version(OpenSSL_version_num())
         );
     }
 #ifdef CAN_DISABLE_AESNI
```

**Comment by neheb** [comment]
https://github.com/openwrt/packages/blob/cfda983becf0eb51856beb8b2fc53ba7a74b6dbb/libs/libssh/patches/002-disable-libssp.patch seems to be needed as well: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/Netopeer2/compile.txt

**Comment by nmav** [comment]
@neheb would you like to propose this patch to [the upstream repo](https://gitlab.com/libssh/libssh-mirror/)? I wouldn't like to check that in without upstreaming it first. I will try to check how we can work-around the ssp without a patch.

**Comment by neheb** [comment]
I send two patches to the mailing list. No idea if successful or not. Posted them here:

https://gist.github.com/neheb/58418a124c2cc23c50f9838e208b89f8
https://gist.github.com/neheb/508befec8ce0e106d64a50eb956fee6b

**Comment by nmav** [comment]
Thanks. I'll merge them separately once they are upstream. I think I have addressed the SSP issue as well without a patch.

**Pull request merged**
