### PR TITLE
openCV: Add library openCV2.4.10

### PR DESCRIPTION
**Pull request by SchumyHao**
Signed-off-by: Jialei Hao <schumy@wrtnode.com>

### CODE REVIEW

**Comment by SchumyHao** [comment]
We(WRTnode team) add opencv support on openwrt. And we have tested it on our board--WRTnode(based on mt7620n).

**Comment by champtar** [comment]
merged b4e860f6226a6b2722031bcf2c974b30d476b5bd
thanks @SchumyHao

**Comment by hnyman** [comment]
Two comments from the long-run maintenance angle:
- It might be better to use PKG_VERSION in the download path. Then the path would not need to be modified after the next version update. 
https://github.com/openwrt/packages/commit/b4e860f6226a6b2722031bcf2c974b30d476b5bd#diff-29191d2a16ae6be490ffca96f5610d05R15

  ````
  PKG_SOURCE_URL:=http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.10/
  -->
  PKG_SOURCE_URL:=http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/$(PKG_VERSION)/
  ````
- Title includes the version number for some reason. I feel that it is more typical to have just the package name there, not the version. That also creates something additional to update next time. Is there a specific reason for having 2.4.10 in title?
https://github.com/openwrt/packages/commit/b4e860f6226a6b2722031bcf2c974b30d476b5bd#diff-29191d2a16ae6be490ffca96f5610d05R37

  ````
  TITLE:=opencv-2.4.10
  ````

**Comment by SchumyHao** [comment]
@hnyman Thank you for your advice! We'll fix it next time

**Pull request closed without merging**
