### PR TITLE
postfix: Fix compilation with uClibc-ng

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @Shulyaka 
Compile tested: arc700

### CODE REVIEW

**Comment by Shulyaka** [comment]
Does uClibc-ng provide res_query()? I mean, here is the patch that CZ-NIC used for their OpenWRT fork: https://github.com/CZ-NIC/turris-os/blob/test/patches/packages/postfix.patch
Do you think adopting it would be a good idea?

**Comment by neheb** [comment]
Interesting...I will look into this.

**Comment by neheb** [comment]
Updated with the Turris patch. Upstream actually told me to do the same as this patch.

**Comment by Shulyaka** [comment]
Thank you!

**Comment by diizzyy** [comment]
...if upstream is aware, why not push it upstream instead?

**Comment by neheb** [comment]
Already done. Should be fixed in next version.

**Pull request merged**
