### PR TITLE
treewide: Replace PKG_LICENSE_FILE with PKG_LICENSE_FILES

### PR DESCRIPTION
**Pull request by neheb**
The latter is actually what is used by the build system. Increased
PKG_RELEASE for all packages as this changes the ipk.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ammubhave @rosysong @hbl0307106015 @amir-sabbaghi

### CODE REVIEW

**Comment by amir-sabbaghi** [comment]
It looks fine to me.

**Comment by feckert** [comment]
Make it so

**Comment by rosysong** [comment]
Looks good to me.

**Comment by hnyman** [comment]
Thanks. Merged.

Reference to the place where it PKG_LICENSE_FILES is actually used:
https://github.com/openwrt/openwrt/blob/master/include/package-defaults.mk#L61

**Pull request merged**
