### PR TITLE
apcupsd: move from old-packages and update to new version

### PR DESCRIPTION
**Pull request by tru7**
This creates the feed for package apcupsd as copy from old-packages with updated Makefile.
apcupsd in old-packages should be deleted afterwards.

### CODE REVIEW

**Comment by sbyx** [comment]
could you please squash this into a single commit?

**Comment by tru7** [comment]
Yes I can. But last time a committed multiple files thess requested to have each file in a separate commit.

**Comment by sbyx** [comment]
you can separate them, but preferrably in groups.
11 commits which are inseparable are a bit excessive i think.

**Comment by tru7** [comment]
I agree, I just wanted to follow exactly what was requested last time. Maybe I got something wrong. I start over when I get back to my system.

**Comment by thess** [comment]
@tru7 - In my own defense... You had submitted 4 new packages (#703) and I requested each package be a separate PR - not each commit.

**Comment by tru7** [comment]
Sorry I messed with PRs and commits. I'm sorry to bug you both. As I just always worked directly in the web GUI I did every file change with a separate commit. Am I correct that this is the only way in the GUI and that I have to use a local git branch to have multiple files in a single commit? I'm still a beginner.

**Comment by sbyx** [comment]
You should probably get a git client, doesn't have to be commandline. Github has some nice GUI-stuff for Windows and Mac.

**Comment by tru7** [comment]
OK. I'll try to come back with a commit with multiple files and create a new pull request. Thanks for you patience.

**Pull request closed without merging**
