### PR TITLE
mxml: update to 2.11

### PR DESCRIPTION
**Pull request by ejurgensen**
Signed-off-by: Espen Jürgensen <espenjurgensen+openwrt@gmail.com>

Maintainer: Espen Jürgensen / @ejurgensen
Compile tested: Yes, ar7xxx
Run tested: No

Description:
Update 2.10 -> 2.11

### CODE REVIEW

**Comment by hnyman** [comment]
This change looks like making the download with collision-prone source file name vXXXX.tar.gz from the perspective of the common Openwrt source archive.

At least with the first glance there seems to be also a more normally named file available:
https://github.com/michaelrsweet/mxml/releases/download/v2.11/mxml-2.11.tar.gz

**Comment by ejurgensen** [comment]
Yes, I tried to use the file you mention initially, but upstream seems to have made a mistake when packaging it. Using that file will extract the source in the root build dir, not in the appropriate subdir. Maybe there is some Makefile-trick to avoid that, but I couldn't find it, so I used github's tar.gz instead.

I hope you will advise on what the best solution would be.

**Comment by ejurgensen** [comment]
Any advice on what I should do? Otherwise I suppose I should close this and contact upstream so perhaps the next mxml release can be packaged in a kosher way.

**Comment by hnyman** [comment]
> Any advice on what I should do? 

One option to avoid the name collision would be to git checkout the release by git hash (and then store is normally as tar.xz file).
https://github.com/openwrt/packages/blob/a1a96fc9fa8312c87ee997d613e9e9de3f3a82d9/utils/irqbalance/Makefile

Other option is to use the codeload approach that some packages are using:
https://github.com/openwrt/packages/blob/master/net/kadnode/Makefile
https://github.com/openwrt/packages/blob/master/libs/libiio/Makefile
```
PKG_VERSION:=2.2.3
PKG_SOURCE_URL:=https://codeload.github.com/mwarning/KadNode/tar.gz/v$(PKG_VERSION)?
PKG_SOURCE:=kadnode-$(PKG_VERSION).tar.gz
PKG_HASH:=1f5538a4b904fd2a624a2046f9320f72357af619190188f14bfdb15b5e5f8488
PKG_BUILD_DIR:=$(BUILD_DIR)/KadNode-$(PKG_VERSION)
```

**Comment by ejurgensen** [comment]
Thanks! I have updated the PR with the option 1 solution.

**Pull request merged**
