### PR TITLE
django-picklefield: Update to 2.0

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @kissg1988 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
Travis is failing because Python is not being built. Need it is a dependency.

**Comment by kissg1988** [comment]
Apologies, please ignore my comment about not including django as a dependency as that's not the case.

**Comment by kissg1988** [comment]
@neheb I've just realized it's just a typo, I'm pretty sure you wanted to set `python/host` as a build dep instead of `pytz/host`.

However, I still have my concerns about why this is required as pointed out in #7534

**Comment by neheb** [comment]
On further inspection with both Travis and CircleCI, this is failing on readline. The buildbots run this connamd: rm -f libreadline.so.7.0 , which is totally missing locally. This is going to be a fun one...

**Comment by neheb** [comment]
Removed dependency.

**Comment by neheb** [comment]
Actually let's see if the build can be fixed individually.

**Comment by neheb** [comment]
Nope. It's failing on either gettext or readline. Need expert help here.

**Comment by neheb** [comment]
readline "fails" at installing a .a file which ends up getting installed anyway. gettext actually fails at installing its library.

**Pull request closed without merging**
