### PR TITLE
emailrelay: Update to 2.1

### PR DESCRIPTION
**Pull request by neheb**
Remove uClibc++ reference. This requires C++11 features not provided by
uClibc++.

Cleaned up Makefile for consistency between packages.

Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @fededim 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
Added size optimizations. This package is huge.

**Comment by neheb** [comment]
It also turns out that emailrelay has compatibility code for those missing uClibc++ features. Would be interesting to try out uClibc++ again especially given how huge libstdcpp has gotten:

```
uclibcxx_0.2.5-3_mips_24kc.ipk | 66.5 KB
libstdcpp6_8.3.0-2_mips_24kc.ipk | 375.4 KB
```

**Comment by fededim** [comment]
Ok changes are fine for me

**Comment by fededim** [comment]
> It also turns out that emailrelay has compatibility code for those missing uClibc++ features. Would be interesting to try out uClibc++ again especially given how huge libstdcpp has gotten:
> 
> ```
> uclibcxx_0.2.5-3_mips_24kc.ipk | 66.5 KB
> libstdcpp6_8.3.0-2_mips_24kc.ipk | 375.4 KB
> ```

If I remember correctly I had to switch to libstdcpp due to a strange loop happening with uclibcxx (the thread is [here](https://github.com/openwrt/packages/issues/2401)), so please do a thorough test if you plan to switch back.

**Comment by neheb** [comment]
That piece of code has been changed btw: https://github.com/aclemons/emailrelay/blob/master/src/gnet/gsocketprotocol.cpp#L601

I don't know if I'll get time to test this with uClibc++.

**Comment by fededim** [comment]
Hmmm no the code which was looping is  [here ](https://github.com/aclemons/emailrelay/blob/b518daed37cfb55b37eb80959ad51d9371297c88/src/gpop/gpopserverprotocol.cpp#L184)...the problem was that the uclibc++ did not raise the fail bit after it had reached the eof of the stream (so Emailrelay kept looping forever)

**Comment by neheb** [comment]
What's an easy way to reproduce?

**Comment by fededim** [comment]
Hmmm you should know...Change again the package to use the uclibc++, install it and test it with a pop3 client. If the client loops when fetching messages, the issue is still there (in this case you can put additional logs in the code I mentioned to see that the fail bit never gets set). If the loop is still happening (uclibc++ might have changed meanwhile) and you are very good at debugging you can check why this strange behaviour of fail bit happens, my knowledge of linux debugging is limited.

**Comment by fededim** [comment]
Oh by way let me know if you happen to do such a test

**Pull request merged**
