### PR TITLE
ddns-scripts: Added dy.fi service

### PR DESCRIPTION
**Pull request by olmari**
Added dy.fi dynamic dns provider into ddns-scripts (ipv4) services file.

Tested-by: Vaasa Hacklab ry <info@vaasa.hacklab.fi>
Signed-off-by: Sami Olmari <sami@olmari.fi>

### CODE REVIEW

**Comment by chris5560** [comment]
@olmari
Could you please also increase PKG_RELEASE in Makefile to document changes inside package.
Is there a chance to send IP-address by ddns-client ? [IP]-parameter currently not part of update url!
Any information about IPv6 support ?

Thanks
Christian

**Comment by olmari** [comment]
@chris5560 whole git is new to me, so I'm learning as doing :) Certainly I can bumb the PKG_RELEASE, but I need to test the if dy.fi accepts any form of IP as parameter, or IPv6... Their "specs" says only hostname and then offline=yes is supported... https://www.dy.fi/page/specification

**Comment by hnyman** [comment]
Could you please use ```git rebase -i``` to squash the three commits into one. (There should be no merge commits in pull requests.)

**Comment by olmari** [comment]
@hnyman I could, in theory... I'll try to learn how to do that =)

**Comment by hnyman** [comment]
You might read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests for some advice.

In short: checkout the branch, use git rebase -i HEAD~3 to squash commits into one, then use git push -f to overwrite the previous three commits in the branch.

**Comment by olmari** [comment]
@hnyman 
Ha! Thank you for the hints! Seems I got it, with a variation of that, but anyways :) Yes I do need still lots of learning, I'm just glad you don't hate me already :D

**Comment by hnyman** [comment]
@olmari 
Thanks. Looks ok to me. (Github is pretty flexible with pull requests, as long as you have stuff in a separate branch.)

@chris5560
Ok to merge?

**Comment by olmari** [comment]
Aside mine (lack of) git-fu, This is best dy.fi can do for now, I have mailed them and asked and suggested about adding IP-parameter and support for AAAA-records too... But should that ever happend,  we'll get back here then with another patch :) So maybe never =)

**Comment by chris5560** [comment]
@olmari
Sorry but I asked to update PKG_RELEASE not PKG_VERSION.
There is a short description for both inside Makefile.

If this is fixed, it could be merged. Thanks

**Comment by olmari** [comment]
@chris5560 
Oh for... sakes, fixed it now... I suppose I was totally overwhelmed by git that I messed even that up, but anyways... third times the charm eh? =)

**Comment by hnyman** [comment]
Merged.

**Pull request merged**
