### PR TITLE
perl: add powerpc64 support

### PR DESCRIPTION
**Pull request by neheb**
Needed by the QoriQ target.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @pprindeville 
Compile tested: ppc64

### CODE REVIEW

**Review by pprindeville — APPROVED** [review]
LGTM

**Comment by pprindeville** [comment]
What's required to get CI/CD coverage of this target?  The `powerpc_464fp` and `powerpc_8540` are both 32-bit, aren't they?

**Comment by neheb** [comment]
Not possible right now. QoriQ is source only so no SDK available. Maybe @stintel can also test.

**Comment by stintel** [comment]
I cannot test that as the current version doesn't build at all.

**Pull request merged**
