### PR TITLE
nginx: add stream support

### PR DESCRIPTION
**Pull request by Ansuel**
This adds support for stream function in nginx

Rework PR #6677

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Fails in travis?

**Comment by Ansuel** [comment]
Actually no this module require a lib that I can't manage to include...
Think we can close this

Il giorno Dom 11 Nov 2018, 10:27 Hannu Nyman <notifications@github.com> ha
scritto:

**Comment by dengqf6** [comment]
So are you going to rework this PR or not? :smiley: Please also include stream SSL module and stream SSL preread module
btw 1.15.7 is available

**Comment by Ansuel** [comment]
the pr is already open ahahha  (about the additional module can you do it for me? )

**Pull request closed without merging**
