### PR TITLE
bonding: use shorter interface prefix

### PR DESCRIPTION
**Pull request by vgaetera**
Maintainer: @he-ma
Compile tested: -
Run tested: -

Description:
Change the interface protocol prefix from "bonding-" to "bond-".
This allows longer custom interface names and useful for VLANs.

Related issue:
https://forum.openwrt.org/t/shorten-interface-names-bonding/104117

Signed-off-by: Vladislav Grigoryev <vg.aetera@gmail.com>

### CODE REVIEW

**Comment by he-ma** [comment]
@neheb 
Could you merge this PR please

**Comment by neheb** [comment]
Needs a PKG_RELEASE bump.

**Comment by he-ma** [comment]
@vgaetera
Please extend your PR by adjusting the PKG_RELEASE.

**Comment by he-ma** [comment]
@neheb 
Thank you, you are right.

**Pull request merged**
