### PR TITLE
libuwsc: fix compilation without ssl

### PR DESCRIPTION
**Pull request by neheb**
The examples require SSL support.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @zhaojh329 
Compile tested: ath79

### CODE REVIEW

**Comment by champtar** [comment]
missing PKG_RELEASE bump ?
also better to have this fixed upstream to have a CMAKE_OPTIONS

**Comment by neheb** [comment]
It's set to AUTORELEASE. Makes no difference anyway since examples don't get installed.

@zhaojh329 is upstream. Up to him.

**Comment by champtar** [comment]
> It's set to AUTORELEASE. Makes no difference anyway since examples don't get installed.

indeed, I was looking at 21.02 ...

> @zhaojh329 is upstream. Up to him.

yup, my point was more let's wait for an answer before we merge

**Comment by neheb** [comment]
This was a ccache bug. Closing.

**Pull request closed without merging**
