### PR TITLE
libgpg-error: Update to 1.36

### PR DESCRIPTION
**Pull request by neheb**
Updated patch to fix compilation on mips64.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @MikePetullo 
Compile tested: mips64

### CODE REVIEW

**Comment by MikePetullo** [comment]
Looks good. Recommend we merge.

I think this might resolve the libgpg-error issue described at https://github.com/openwrt/packages/issues/8548.

**Comment by diizzyy** [comment]
Don't forget the runtime test...

**Comment by neheb** [comment]
@diizzyy merging as soon as I do. this package causes long range build failures on mips64 as it breaks libgcrypt, which is a dependency for many packages. protobuf is the other big one.

**Comment by neheb** [comment]
Briefly tested with forked-daapd. Couldn't find anything wrong. Merging.

**Pull request merged**
