### PR TITLE
libgpg-error: Fix compilation with GAWK 5.0

### PR DESCRIPTION
**Pull request by jjm2473**
Patch from Upstream.

Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

Maintainer: W. Michael Petullo <mike@flyn.org>
Compile tested: Host MacOS, Openwrt 18.06
Run tested: 

Description:

### CODE REVIEW

**Comment by neheb** [comment]
ping @flyn-org

**Comment by neheb** [comment]
Just noticed this needs a PKG_RELEASE bump.

**Comment by jjm2473** [comment]
@neheb It just fix the compile error, does it really needs a PKG_RELEASE bump?

**Comment by neheb** [comment]
Hmm I guess not. These all look like Makefile fixes.

The rule regarding PKG_RELEASE is that if any installed file changes, PKG_RELEASE gets bumped so that opkg install works properly. opkg checks the ipkg filesize to see if it is correct.

**Comment by flyn-org** [comment]
This looks fine to me, assuming @neheb is satisfied with the PKG_RELEASE. I believe the corresponding work upstream is in https://github.com/gpg/libgpg-error/commit/7865041c77f4f7005282f10f9b6666b19072fbdf.

**Pull request merged**
