### PR TITLE
uacme: add retries

### PR DESCRIPTION
**Pull request by lemoer**
Maintainer: @lucize
Compile tested: x86-64, openwrt master (bc2538a)
Run tested: x86-64, openwrt master (bc2538a)

Description:

Prior to this commit, the acme service attempted to obtain certificates
once and then terminated, regardless of whether the certificate could be
obtained or not. This commit introduces a new uci option "retries" to
the "certificate" section. If this option is set to N, the acme service
will attempt to obtain the certificate up to N times before terminating.
There is a waiting pause between the retries to comply with the rate
limits of Let'sEncrypt.

The waiting pause is:
-  2 minutes for staging certificates
- 24 minutes for production certificates

The current "Failed Validation" rate limits of Let'sEncrypt are:
- staging:   60 per hour -> 1 failure every 1 minute in avg.
- production: 5 per hour -> 1 failure every 12 minutes in avg.

This means that we are within rate limits by a factor of two.

By default the option "retries" is set to "1", which means that acme
behaves as before by default. If the variable is set to "0", infinite
retries are performed.

This feature is helpful, when you already want to initiate the
certificate request, but you are still waiting for your dns server to be
configured, your network to appear or other conditions.

Note: Please only review the commit "uacme: add retries" here. The first two commits are part of #15259. This PR is rebased on #15259, as #15259 is most likely to be merged before this PR.

### CODE REVIEW

**Comment by lucize** [comment]
LGTM

**Comment by lemoer** [comment]
Thanks for the quick feedback.

Note for anyone, who will merge this: Please merge #15259 first. This PR is rebased on #15259.

**Comment by lucize** [comment]
but you have to bump the pkg_release for each

**Comment by lemoer** [comment]
PKG_RELEASE is set to $(AUTORELEASE) for this package. Therefore this shouldn't be necessary, should it? (Reference: https://github.com/openwrt/openwrt/commit/9ae3c6f94c616cfbf854d3ec749c7fafc9893942)

**Comment by lucize** [comment]
ah, yes, my bad !

**Comment by neheb** [comment]
Needs a rebase.

**Comment by lemoer** [comment]
@neheb Thanks, done.

**Pull request merged**
