### PR TITLE
netcat: fix Illegal instruction on listen udp

### PR DESCRIPTION
**Pull request by rfrankla**
Maintainer: @adam2104
Compile tested: mvebu cortexa9 linksys_wrt1200ac, OpenWrt 19.07.3
Run tested: mvebu cortexa9 linksys_wrt1200ac, OpenWrt 19.07.3  # nc -l -u -p 4000

Description:
When listening to a udp port an Illegal instruction occurs.
This did NOT happen when compiled with debug on.

Fixes issue openwrt#4747, FS#2937

Signed-off-by: Rick Frankland <rfrankla@yahoo.com>

### CODE REVIEW

**Comment by neheb** [comment]
Maintainer is @adam2104

**Comment by neheb** [comment]
This needs a PKG_RELEASE bump.

**Comment by rfrankla** [comment]
> Maintainer is @adam2104

updated the request.

**Comment by rfrankla** [comment]
> This needs a PKG_RELEASE bump.

I believe I have successfully amended the commit and the Makefile is updated.

**Pull request merged**
