### PR TITLE
python-package.mk: fix cross-compiling C++ modules.

### PR DESCRIPTION
**Pull request by attila-lendvai**
Signed-off-by: Attila Lendvai <attila@lendvai.name>

### CODE REVIEW

**Comment by attila-lendvai** [comment]
ok, created a separate pull request.

shall i delete it from the other one?

**Comment by sbyx** [comment]
@commodo please review.

**Comment by commodo** [comment]
The change is fine. So +1.

nitpick: I'd change the title from `python-package.mk:.......` to `python:...........`
I don't feel the title would be a major blocker, so I'll leave the decision up to you guys

Thanks :)

**Comment by karlp** [comment]
merged in 2bb9f6b9c786ffdcd738ad3611ee1091d08ffc59

**Pull request closed without merging**
