### PR TITLE
refine mwan3 link selection

### PR DESCRIPTION
**Pull request by ptpt52**
Maintainer: me / Florian Eckert @feckert
Compile tested: x86_64 ar71xx ipq40xx, openwrt 18.1
Run tested: x86_64 ipq40xx

Description:
1. Select the routing table corresponding to the line according to the inbound interface.
2. The local out data, first select the line by rule, and then check the corresponding routing table to go out.

### CODE REVIEW

**Comment by ptpt52** [comment]
this pull request fix:
https://github.com/openwrt/packages/issues/6455

**Comment by ptpt52** [comment]
for now we just support ipv4. ipv6 leave no effect

**Comment by ptpt52** [comment]
@feckert please help review this.

**Comment by lucize** [comment]
does it work fine with flow_offloading, not the hw mode ?

**Comment by ptpt52** [comment]
@lucize it works with flow_offloading.

**Comment by feckert** [comment]
@ptp52 thanks for this PR i will test this next week and do a review.
Sorry I have a lot todo this week
@lucize did you do any tests so far?

**Comment by lucize** [comment]
Sorry, can't, I want to use it on ath79 target with flow offload but right now the device is using ar71xx image and I don't have physical access to it at the moment so I don't want to risk soft bricking it

**Comment by ptpt52** [comment]
update:
now I add support for ipv6, but without test.

**Comment by feckert** [comment]
Why do we need the **x** on if else statements?

**Comment by feckert** [comment]
Could we replace the **`** backticks with the new **$()**

**Comment by feckert** [comment]
Why do we need a mwanrtmon is it not enough to update the routing table during the netifd ifup/ifdown events?

**Comment by ptpt52** [comment]
@feckert  updated

**Comment by feckert** [comment]
Thanks for updating your PR :-)

Could you also please update the PKG_VERSION to 2.7 to get this merged.

>>Why do we need the x on if else statements?

>Prevent empty string

I have not seen this before could you please remove this?
It think other will have the same questions as I. And i think it is unecssary.

Could you also remove the line
`. /usr/share/libubox/jshn.sh ` in 16-mwan3 this function are not used.

Sorry but i dont get it. Why do we need the mwan3rtmon?
Your sentence is incomplete
> mwanrtmon keep watching the main route table, I think it is enough enough

I could see that the service polls the routing table and if something has changed then we update the dedicated routing tables for all interface. But does we need really a new service for this? I want to avoid to start another service (this is a problem for small devices). I am using a small device lantiq_xrx200. Is it not enough to change 16-mwan3 to do this job on interface ifup/ifdown event?

**Comment by ptpt52** [comment]
ok
- drop . /usr/share/libubox/jshn.sh in 16-mwan3
- drop x on if-else statements.

mwan3rtmon is necessary
casue:
not all routes changes cause the interface ifup/ifdown event.
for custom static routes setting, it just add them to the main table without the ifup/ifdown event.

Maybe there is a better way to synchronize these routing tables
but the current compromise is to monitor it using a background process, the mwan3rtmon

code updated/rebased @feckert

**Comment by feckert** [comment]
Thanks for your fast respond.
I will do some test next week and then we could merge this

Thanks :+1:

**Comment by ptpt52** [comment]
I found a bug, now I push a fix:
mwan3: fix interface fail to recover after tracking down/up

this happens when interface down with tracking active. it cannot make the interface recover to up when the link is actually up.

**Comment by ptpt52** [comment]
for some case, when all the interfaces are down, we make sure local-out packets work properly

**Comment by feckert** [comment]
@ptpt52 i made some test and i think we should make the mwan3rtmon sleep time configurable.
0 never start mwan3rtmon
<1,2,3,4,5 ...> sleep time in seconds

So if some one does not need the recalculation it could be disabled and on the other side it is possible to configurable how often we check the routing table. 
The configuration option could get into the globals section of mwan3.
Maybe **rtmon_sleep**?

**Comment by ptpt52** [comment]
updated.
seems ok.
I added an option 'rtmon_interval'
mwan3rtmon runs one-time on each mwan3 reload,
it should stop the loop if rtmon_interval equal 0

**Comment by feckert** [comment]
@ptpt52 thanks great work.
I will do some test with the new PR and then we could merge this

**Comment by Per9** [comment]
I am currently using 18.06.0. I tested this by downloading these files individually:
/usr/sbin/mwan3
/usr/sbin/mwan3rtmon
/lib/mwan3/mwan3.sh
/etc/hotplug.d/iface/16-mwan3
from here: https://github.com/openwrt/packages/pull/6515/files
I had already done the same with /lib/mwan3/mwan3.sh from master to fix IPv6. This PR fixed this issue: https://github.com/openwrt/packages/issues/6551

Unfortunately it also broke IPv6. It is now saying Status: Offline.

**Comment by ptpt52** [comment]
@Per9 
thanks for your test and feedback
could you post some more detail of IPv6 setup?
Execute the following commands and give the results back to me

ip -6 r
ip -6 rule
ip -6 r s t 1
ip -6 r s t 2
ip6tables-save
mwan3 status

**Comment by Per9** [comment]
Here is the output: https://gist.github.com/Per9/4576ba1eb5fbbe7eca341a8f9354c399

**Comment by ptpt52** [comment]
@Per9 
what is your setup in /etc/config/mwan3

**Comment by Per9** [comment]
mwan3 config: https://gist.github.com/Per9/c2dff815051a39b8b77edbdfb28daa27

**Comment by Per9** [comment]
@ptpt52 mwan3 with this patch makes it go offline. It is online with Mwan3 2.6.18 or if I make sure this version of mwan3 is not running. I have posted various diagnostics with working IPv6 in this bug: https://github.com/openwrt/packages/issues/6551

**Comment by ptpt52** [comment]
i shows offline but
does the ipv6 network work fine?
ping6 xxxxxx ok?

**Comment by ptpt52** [comment]
@feckert @Per9 I push some more commits for bug fix.
if everything ok I will stash into one commit.

**Comment by Per9** [comment]
@ptpt52 No, the network does not work while it says offline. ping6 says
ping6: sendto: Network unreachable

I tried updating mwan3.sh with your new modifications but unfortunately it still doesn't work. I ran the diagnostics commands you posted earlier and compared the output with diff, and there are no relevant changes.

**Comment by Per9** [comment]
Like this?
# ping6 -I eth0.2 openwrt.org
PING openwrt.org (2a03:b0c0:3:d0::1af1:1): 56 data bytes
ping6: sendto: Network unreachable

**Comment by Per9** [comment]
Here is a diff between old mwan3 diagnostics (with working ipv6) and the one with your changes:
https://gist.github.com/Per9/facd4358e3c3902602ed73c785766341
(diff -b -B old.txt new.txt)

**Comment by ptpt52** [comment]
Is it possible to debug remotely, I don't have an IPv6 environment

**Comment by ptpt52** [comment]
ok I know the cause of your problem
it your bad config

you have to change this section:

> config policy 'wan_wan2'
        list use_member 'wan_m1_w3'
        list use_member 'wan2_m2_w2'
        option last_resort 'unreachable'

to

>config policy 'wan_wan2'
        list use_member 'wan_m1_w3'
        list use_member 'wan2_m2_w2'
        list use_member 'wan6_m1_w3'
        option last_resort 'unreachable'

**Comment by Per9** [comment]
You are right, it works now. Thank you :)

**Comment by ptpt52** [comment]
@feckert so now it may be bug free. and ready to be merged.

**Comment by feckert** [comment]
@ptpt52 sorry for the delay but i have to do some more test but i am on vacation so please wait thanks

**Comment by Per9** [comment]
@ptpt52 : Sorry, it turns out that ipv6 still doesn't work properly. I can ping v6 addresses from the router but not from my computer.

**Comment by feckert** [comment]
@ptpt52 I have merge the PR to my working tree.

With my default setup i get the following output if i do a **/etc/init.d/mwan3 start**

>  Try `iptables -h' or 'iptables --help' for more information.
Bad argument `mark'
Try `iptables -h' or 'iptables --help' for more information.

This will be generated by your new lines
https://github.com/openwrt/packages/pull/6515/files#diff-ccaf6dffccf2fc134d63b5c33d5ee8e1R622

I am note sure what the problem is. I have to look deeper.

**Comment by feckert** [comment]
@ptpt52 I have found the problem.

If we do not get a valid device from this line https://github.com/openwrt/packages/pull/6515/files#diff-ccaf6dffccf2fc134d63b5c33d5ee8e1R545 
then the error is thrown in line
https://github.com/openwrt/packages/pull/6515/files#diff-ccaf6dffccf2fc134d63b5c33d5ee8e1R622

This could happen if the interface of this policy is not up! And so has not valid physical interface (for example eth0)

**Comment by ptpt52** [comment]
got it. it could be fixed

**Comment by feckert** [comment]
@ptpt52 @hnyman We could merge this now

**Comment by feckert** [comment]
> Please provide a it of an explanation what this interval timings are used for

The time interval is used to update the dedicated **wan** interface table. If you add a **0** to this option on the globals config section of mwan3, then the tables are only update on netifd ifup/ifdown events.

**Comment by ptpt52** [comment]
@feckert 

for @thuehn 's case, the routing table is updated by OLSR as routing daemon dynamically
so it is not suitable to set interval timings to 0. The mwan3rtmon is needed to watch the main table's changes and clone them to route table 1/2/3...

This is used to fix this problem
https://github.com/openwrt/packages/issues/5055

to route traffic sourced from router

**Comment by jetom** [comment]
after installing mwan3 on the OpenVPN server in "failover" mode I can not connect to the OpenVPN server as a client.

I need help!

**Comment by feckert** [comment]
On my setup I have add a interface to the network config for example `openvpn` and add `tun0` as a device. If so I think mwan3 handled openvpn (tun0) traffix as a local connected network.

**Pull request merged**
