### PR TITLE
libwebsockets: Bump to version 1.6-stable

### PR DESCRIPTION
**Pull request by inindev**
Note that at LWS_CYASSL_LIB has changed to LWS_CYASSL_LIBRARIES

Signed-off-by: John Clark <inindev@gmail.com>

### CODE REVIEW

**Comment by karlp** [comment]
Thanks for this, I'd been meaning to get  to i t last week, will hopefully get to it today!

**Comment by karlp** [comment]
You've changed to using a branch name, rather than a release name, I think that will be confusing and hard to track.  I'll use 1.6.1, the last release tag, rather than the branch name.  Did you run into any issues with missing libpthread dependencies?

**Comment by karlp** [comment]
I've been rebuilding these, and somehow pthread is getting required as a dep now, do you know of any other libwebsockets changes that would be causing this?

**Comment by inindev** [comment]
I did not run into any libpthread issues.  My issues were around 
renaming and the lib include changing.  The port was mainly just search 
and replace -- pretty painless all things considered.

Thanks,

--John

**Comment by karlp** [comment]
I mean, openwrt's buildroot complains about the bump from 1.5 to 1.6, as libwebsockets now has an undeclared libpthread dependency.  I've filed https://github.com/warmcat/libwebsockets/issues/408 to clarify with upstream what they inntended here.

**Comment by karlp** [comment]
Fixed in master, thanks for pushing me to get this sorted.  We've gone to 1.6.2 after upstream fixed the pthreads dependency for us.

**Pull request closed without merging**
