### PR TITLE
rng-tools: add upstreamed patch to fix newlines in syslog messages

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: @nwf 
Compile tested: x86_64, generic, LEDE HEAD (b91a38d)
Run tested: same

Built complete image, scp'd it over, ran sysupgrade... let the system reboot, then `grep`'d `/var/log/messages` for `rngd`.

Did not see any blank lines.

Description:

Fixes `\n` being embedded in format strings to `message()`.

### CODE REVIEW

**Comment by nwf** [comment]
Looks good to me.

**Comment by hnyman** [comment]
You should bump the PKG_RELEASE in Makefile.
Your change is cosmetics, but let's just follow good practices...

**Comment by pprindeville** [comment]
> You should bump the PKG_RELEASE in Makefile.

Done.

**Comment by pprindeville** [comment]
Thanks!

**Pull request merged**
