### PR TITLE
nsutils: version bump

### PR DESCRIPTION
**Pull request by oskarirauta**
Few minor changes, like -h flag for program (help).
Added URL to package definition.

Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

Maintainer: Oskari Rauta / @oskarirauta
Compile tested: x86_64
Run tested: x86_64

### CODE REVIEW

**Comment by jefferyto** [comment]
I think for `$(AUTORELEASE)` to work correctly, the first line of the commit message needs to have either `: update to ` or `: bump to ` in it (see #14537, https://github.com/openwrt/openwrt/blob/d9a063c3967c72773616cf5eadd4f978b9724c50/rules.mk#L421)

**Comment by oskarirauta** [comment]
Changes were made to commit message..

**Comment by jefferyto** [comment]
Upstream switched to cmake (https://github.com/rd235/nsutils/commit/68902b42ab4f2ee65b71d6fd8ec8ae9c51e87e8a), and the CI downloaded the tarball for the previous version to build :sweat: 

I'm working on a fix :pray:

**Comment by oskarirauta** [comment]
Sounds good to me- I never got too fond of cmake, GNU make is more for me 😄

Lähetetty iPhonesta

**Pull request merged**
