### PR TITLE
domoticz: disable searching for boost-cmake

### PR DESCRIPTION
**Pull request by ammubhave**
Summary:
This package fails to compile with boost 1.70 when the boost cmake
config gets used.
As far as I can tell, Boost 1.70 introduced
BoostConfigVersion.cmake. In that file, the value of PACKAGE_VERSION is
set to 1.70. This makes CMake auto set the variable Boost_VERSION to
1.70. Historically, Boost_VERSION has been using the format like 170000,
and not 1.70. Some package cmake files still depend on this behavior
and make assertions such as Boost_VERSION > 168000. This is incompatible
with the new scheme.

Test Plan:
`make package/domoticz/compile`
Also compiled all other packages that have a boost dependency, they seem
to be working fine.
tested on nbg6817

### CODE REVIEW

**Comment by kofec** [comment]
Hi @stintel,
Can you also update to latest stable release. This single patch is not needed any more on latest release

**Comment by neheb** [comment]
The commit says tree but these two need this

https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/packages/libftdi/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/packages/libftdi1/compile.txt

**Comment by stintel** [comment]
Why did you include -DBUILD_SHARED_LIBS=yes? Is it required for the Cmake change? If not, remove it, if yes, explain it in the commit message.

**Comment by stintel** [comment]
Both changes were required, but the fix a different problem, so they should go in a different commit. Fixed with b93d39ac744529210e61c45d9d35a2e95e4813ef and a73b3b2d753fa4734cec0c8a3effa910fe550f71

**Pull request closed without merging**
