### PR TITLE
strongswan: try to model kdf optional dependencies

### PR DESCRIPTION
**Pull request by Thermi**
Maintainer: me, @pprindeville
Compile tested: x86_64, generic, HEAD (23c77384f3)
Run tested: same, installed on production router

Description:

Just a test compile with the CI for now, don't know if that is going to work out all right.

### CODE REVIEW

**Comment by pprindeville** [comment]
Confirmed by building/running locally.

**Comment by Thermi** [comment]
Are the dependencies correctly expressed?

**Comment by pprindeville** [comment]
Anyone upgrading from 5.9.6 to 5.9.7 will need to remember to explicitly select the `mgf1` subpackage.

**Comment by Thermi** [comment]
I think we could also just swiftly implement that aswell

**Comment by pprindeville** [comment]
> I think we could also just swiftly implement that aswell

Sorry, how do you mean?

**Comment by pprindeville** [comment]
You mean make it a default packaging?

**Comment by Thermi** [comment]
Yes, basically. You require it for everything anyway.

**Comment by pprindeville** [comment]
> Yes, basically. You require it for everything anyway.

See PR #19146.

**Comment by pprindeville** [comment]
Seems there’s now a circular dependency.

**Comment by Thermi** [comment]
I looked for one and  did not find it TBH. Can you show me how that occurs?

**Pull request merged**
