### PR TITLE
boost: Package Version Update (1.72.0)

### PR DESCRIPTION
**Pull request by ClaymorePT**
Maintainer:  @ClaymorePT
Compile tested: Broadcom BCM2711/Raspberry 4B with OpenWRT/master
Run tested: N/A

**Description:**
This commit updates Boost to version 1.72.0
There are no new libraries in this release.

**Note:**
- This commit also adds a post-release patch to fix an issue with Boost.Coroutine

More info about Boost 1.72.0 can be found at the usual place [1].

[1]: https://www.boost.org/users/history/version_1_72_0.html

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

### CODE REVIEW

**Comment by ClaymorePT** [comment]
@neheb Can you take a look? Thank you!

**Comment by neheb** [comment]
Yeah I took a look. uClibc-ng is still broken with this. I found two problems. For the first, I submitted a patch here: https://github.com/boostorg/math/pull/283

For the second problem, I have no idea how to fix it. I posted an issue here: https://github.com/boostorg/math/issues/284

I can get it to compile just by removing that line, but that breaks the template as copysign (the C function) returns a double only.

**Comment by neheb** [comment]
Hrm replacing

**Comment by neheb** [comment]
Looks like replacing the offending line with

```
using boost::math::copysign;
```

works. Not sure if it's the right solution.

**Comment by ClaymorePT** [comment]
> Looks like replacing the offending line with
> 
> ```
> using boost::math::copysign;
> ```
> 
> works. Not sure if it's the right solution.

It's not the right solution but in my opinion, it may be an acceptable one as long as `boost::math::copysign` is not marked as deprecated. I think the one in the `std::` was first developed in boost, so it should work as expected.

I will add the patches which you submitted as soon as I can.

**Comment by neheb** [comment]
Those upstream submissions passed the tests so :shrug:

**Comment by wongsyrone** [comment]
Run tested on x86_64 with libraries: boost-date_time, boost-program_options and boost-system

**Comment by ClaymorePT** [comment]
@neheb  I've updated the branch and added the two patches which provide the fixes you refereed. I hope this fixes the issues you've detected in Boost.Math.

**Comment by neheb** [comment]
Hmmm about that last patch. Maybe it might makes sense to wrap it in an if directive like so:

```
#if defined(BOOST_GNU_STDLIB) && !defined(_GLIBCXX_USE_C99_MATH_TR1)
using boost::math::copysign;
#else
using std::copysign;
#endif
```

**Comment by ClaymorePT** [comment]
@neheb You're right. Your approach is cleaner since it prevents the patch application in non-uclibc situations.

I've updated the branch.

**Comment by neheb** [comment]
I found a seriously stupid typo from a previous commit of mind. I pushed the fix directly into the master branch. Hope you don't mind.

**Comment by ClaymorePT** [comment]
No worries. Mistakes happen.

**Pull request merged**
