### PR TITLE
sshtunnel: support Dropbear

### PR DESCRIPTION
**Pull request by stokito**
**Maintainer:** @nunojpg

**Compile tested:** OpenWrt 23
**Run tested:** tested in VirtualBox and Turris

**Description:**
This is the same PR as was in the #21263. 
I just removed the branch accidentally and now have to recreate the PR.

The only difference is that I changed dependency line: now it will depend ether on dbclient or openssh-client.
I copied the depends line from pppossh package but improved it to be more precise and depend on the dbclient and not just on the dropbear package.
The PR also contains update for the pppossh with the same depends change so @yousong please have a look.

### CODE REVIEW

**Comment by nunojpg** [comment]
Hi @stokito can you move the pppossh change into another PR?

**Comment by stokito** [comment]
You can merge if we have a commit to other app?

**Comment by stokito** [comment]
Ok, I dropped the last commit

**Comment by nunojpg** [comment]
Thanks for all the effort!

**Comment by stokito** [comment]
@nunojpg thank you! Could you also check the https://github.com/openwrt/luci/pull/6424

**Pull request merged**
