### PR TITLE
package domoticz: fix build

### PR DESCRIPTION
**Pull request by berenyibalazs**
Fix CMake not to check for execinfo.h (not provided by uClibc caused fail to build for me).
Use builtin MQTT and fix it for new OpenSSL by removing depreciated API.
Fix old boost API usage in domoticz webserver (patch from upstream domoticz).

Signed-off-by: BERENYI, Balazs <beba@wee.hu>

Maintainer: Stijn Tintel <stijn@linux-ipv6.be>
Compile tested: x86, arm-cortex-a7 (cross compiled on x86)
Run tested: x86/FreeBSD-bhyve*; arm-cortex-a7/sunxi
Revisions: various from this week.

Description:
Restore build of Domoticz. Starts up successfully. (Not tested any further).
Sorry no capable MIPS hw to test on.

* FreeBSD-bhyve is not stated as supported on the website but raw VM image runs out of box.

### CODE REVIEW

**Comment by hnyman** [comment]
> CMake not to check for execinfo.h (not provided by uClibc caused fail to build for me).

hmm. Master does not use uClibc

cc maintainer @stintel

**Comment by berenyibalazs** [comment]
Just checked. Yep sorry. Musl-libc also does not provides that header/funcionality. Thanks.

**Comment by stintel** [comment]
Please backport https://github.com/domoticz/domoticz/commit/388c7b51716cdb6221ec292cc2456ceca6ee9b02 as a single patch in a separate commit with prefix 001- keeping the original commit author and message.

Please elaborate why we need the execinfo.h change, as domoticz compiles fine without it.

I am tempted to NAK the MQTT/mosquitto changes. If you really want this, please create a different PR and thoroughly elaborate why.

**Comment by berenyibalazs** [comment]
Hope the commits will be fine now. Please merge it so we can have the snapshot package.

**Comment by stintel** [comment]
I cherry-picked the Boost compat fix and pushed it so the package will be built by the buildbots again. Will look into the OpenSSL thing when I find some more time.

**Comment by berenyibalazs** [comment]
From OpenSSL CHANGES files:

...
Changes between 0.9.8n and 1.0.0  [29 Mar 2010]
...
     Note that ERR_remove_state() is now deprecated, because it is tied
     to the assumption that thread IDs are numeric.  ERR_remove_state(0)
     to free the current thread's error state should be replaced by
     ERR_remove_thread_state(NULL).
...

But i guess this was also fixed in upstream somewhere....

**Comment by stintel** [comment]
Apparently this is not fixed upstream. I guess nobody used the builtin MQTT, as any sane distro uses OpenSSL >=1.0.0... 

Can you submit a fix for this upstream, and then do a new PR with that fix? As long as it's not accepted upstream the patch prefix here should be 1xx. And in the same PR, but a separate commit, add an option to configure USE_BUILTIN_MQTT? You can find examples with `git grep ^menu`

Thanks!

**Pull request closed without merging**
