### PR TITLE
[21.02] Bump yggdrasil to 0.4.3

### PR DESCRIPTION
**Pull request by zhoreeq**
Maintainer: @wfleurant
Compile tested: none
Run tested: none

Description:
Cherrypicking from https://github.com/openwrt/packages/pull/17907

### CODE REVIEW

**Comment by BKPepe** [comment]
1. You should not use noreply GitHub address.
2. In the commit message, there should be that it was cherry-picked.
You can do it by ``git cherry-pick -x hash``.

**Comment by zhoreeq** [comment]
@BKPepe 

>You should not use noreply GitHub address.

What is wrong with it?

**Comment by BKPepe** [comment]
Let me quote it from here:
> https://openwrt.org/submitting-patches
 
- all commits must contain ``Signed-off-by: My Name <my@email.address>`` where you **write your real name and real email address**, in accordance with [Section 11 of the Linux Kernel patches guide](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416)

**Comment by zhoreeq** [comment]
OK, I have reasons to not doxx myself

@wfleurant I'm being restricted from contributing, so I will not bump versions anymore

**Comment by zhoreeq** [comment]
If anyone will need an up-to-date Yggdrasil package, I have set up a custom repo here https://github.com/popura-network/openwrt_packages

**Comment by wfleurant** [comment]
it is surprisingly unnecessary to enforce this... after more than 2 years of this users (maintainers) contributions.  

> using your real name (sorry, no pseudonyms or anonymous contributions.)

zh is not even violating the submitted patch guidelines. contributions are submitted, emailed and signed off with their unique username handle. this is not an anonymous form of submitting a patch and the github no-reply hostname is a FQDN.  

Linus clearly meant that if any kernel patches originating from Jane Doe fake@microsoft.gov would (obviously) be rejected.  

OpenWrt should not be loosing contributors over this...

**Pull request merged**
