### PR TITLE
adblock: add German list

### PR DESCRIPTION
**Pull request by Nokius**
Signed-off-by: Nokius <foss@nokius.net>

-------------------------------

Maintainer:  @dibdot
Run tested: (ar71xx, WDR4300, OpenWRT trunk))

Description:
add the list for Germany

### CODE REVIEW

**Comment by dibdot** [comment]
looks good to me - thank you!

**Comment by Nokius** [comment]
@dibdot Thanks for your work :)

**Comment by hnyman** [comment]
Looks otherwise ok, but I think that you have used spaces instead of a tab in the config file.

**Comment by Nokius** [comment]
yes I shall use tab? :)

**Comment by hnyman** [comment]
Using tab in config file is the standard.
Please do that

**Comment by Nokius** [comment]
@hnyman fixed

**Comment by dibdot** [comment]
@hnyman  Thanks for the good catch - I've only checked the regex.
Thanks for all your efforts!

**Pull request merged**
