### PR TITLE
apr+apr-util+apache: Third party mods build

### LINKED ISSUE #3720: Apache: do not list modules
I installed Apache and configured after reading this https://wiki.openwrt.org/doc/howto/http.apache
Is running fine.

httpd -M or apachectl -M in the shell should list installed modules. All i get is "Syntax OK"

The response should be something like this:
Loaded Modules:
core_module (static)
mpm_prefork_module (static)
http_module (static)
so_module (static)
auth_basic_module (shared)
cgi_module (shared)
version_module (shared)
wsgi_module (shared)
Syntax OK

http://www.shellhacks.com/en/List-Loaded-Enabled-Apache-Modules

### LINKED ISSUE #4840: apache proxy segfault
Maintainer @heil 
with --enable-proxy on sun7i target (arm) I get this error and it will loop forewer

```
[Sat Sep 16 13:52:16.047623 2017] [proxy_hcheck:info] [pid 34359738384:tid 3064544580] (70023)This function has not been implemented on this platform: AH03312: apr_thread_pool_create() with 16 threads failed
[Sat Sep 16 13:52:16.047849 2017] [watchdog:debug] [pid -5264627648507674620:tid 3069363352] mod_watchdog.c(585): AH02981: Watchdog: Created worker thread (_proxy_hcheck_).
[Sat Sep 16 13:52:16.048519 2017] [proxy:debug] [pid -5264506015033851904:tid 3069363352] proxy_util.c(1777): AH00925: initializing worker proxy:reverse shared
[Sat Sep 16 13:52:16.048586 2017] [proxy:debug] [pid -5264506015033851904:tid 3069363352] proxy_util.c(1819): AH00927: initializing worker proxy:reverse local
[Sat Sep 16 13:52:17.043593 2017] [core:notice] [pid -4715750481822642040:tid 3069363352] AH00052: child pid 10645 exit signal Segmentation fault (11)
[Sat Sep 16 13:52:17.044001 2017] [core:notice] [pid -4715750481822642040:tid 3069363352] AH00052: child pid 10646 exit signal Segmentation fault (11)
[Sat Sep 16 13:52:17.044068 2017] [core:notice] [pid -4715750481822642040:tid 3069363352] AH00052: child pid 10647 exit signal Segmentation fault (11)
[Sat Sep 16 13:52:17.044124 2017] [core:notice] [pid -4715750481822642040:tid 3069363352] AH00052: child pid 10648 exit signal Segmentation fault (11)
```

### LINKED ISSUE #10884: apr: Remove --without-pic from ./configure
Maintainer @heil

Description:

In the following commit the --without-pic flag has been added to apr. This has memory footprint implications, and ideally should be removed.

https://github.com/openwrt/packages/commit/165f72234dfe8cbb5cfc45b49bf3af134ffa834e

CC: @neheb

### LINKED ISSUE #10886: apr-util: Build apr-util dbd/crypto/ldap as modules
Maintainer @heil

Description:

The apr-util library is currently built as a monolithic library, with some modules included, and some modules removed.

Ideally apr-util should be built with modules such as apr_dbd_mysql, apr_crypto_openssl and apr_ldap in modular packages.

### PR DESCRIPTION
**Pull request by minfrin**
Compile tested: ar71 on master
Run tested: ar71 master, run-tested with net/apr-util, apache/httpd

Description:
Make it possible for third party modules to be built against apr,
apr-util and apache by fixing cross compilation support in all three.

The following patches are committed upstream:

libs/apr/patches/401-cross-compile.patch
libs/apr-util/patches/101-mariadb.patch
libs/apr-util/patches/401-cross-compile.patch
net/apache/patches/001-cross-compile.patch
net/apache/patches/020-config_layout.patch
net/apache/patches/030-apxs-cross-compile.patch

This PR includes the following PRs:

https://github.com/openwrt/packages/pull/10906
https://github.com/openwrt/packages/pull/10898

Fixes #4840
Fixes #3720
Fixes #10886
Fixes #10884

CC: @micmac1

Signed-off-by: Graham Leggett <minfrin@sharp.fm>

### CODE REVIEW

**Comment by micmac1** [comment]
> This PR includes the following PRs:
>
> https://github.com/openwrt/packages/pull/10906
> https://github.com/openwrt/packages/pull/10898
>
> Fixes #4840
> Fixes #3720
> Fixes #10886
> Fixes #10884
>
> CC: @micmac1
>
> Signed-off-by: Graham Leggett &lt;minfrin@sharp.fm&gt;

I don't like this. You copied most of my changes and made it out like
you typed them up yourself. Also, some of the stuff you put into
apr-util looks strange ("$(SDK)"). And last but not least you provide
one commit, where it should be a series of commit with proper commit
series.

**Comment by minfrin** [comment]
No idea how to do this differently I'm afraid. The CI tests and deploys each change as a single unit, which makes it very difficult to develop changes that depend on changes that depend on changes.

apr was broken, and so was apr-util, and so was apache, all three needed fixing before building third party modules was possible.

The PR is here for reference, you can layer each commit as you see fit.

**Comment by minfrin** [comment]
> Also, some of the stuff you put into apr-util looks strange ("$(SDK)")

Everything in the Makefiles is based on existing examples in the code. The existing code is all I have to work from, so it's the best I can do.

If there are fixes needed, please describe them for me so they can be fixed.

**Comment by minfrin** [comment]
> ("$(SDK)")

A search turned up many examples of where the SDK variable is used, here is the top one:

https://github.com/openwrt/packages/blob/6d2ec456bd43e896ea369e813316c06ccf593681/lang/php7/Makefile#L178

Can you confirm it is being used correctly?

**Comment by micmac1** [comment]
On Wed, Jan 01, 2020 at 10:03:36AM -0800, minfrin wrote:
> > ("$(SDK)")
>
> A search turned up many examples of where the SDK variable is used, here is the top one:
>
> https://github.com/openwrt/packages/blob/6d2ec456bd43e896ea369e813316c06ccf593681/lang/php7/Makefile#L178
>
> Can you confirm it is being used correctly?

Those are checks that test if a package is selected. If it is ("m" or
"y") then the required switches are set (--enable-ctype=shared), if not
then the opposite (--disable-ctype). On top of that they put the SDK
variable in there. So even if the package is disabled (in menuconfig,
""), if the SDK variable is set to something, enable the switch.

Not sure of the merit of that. Looks dubious to me. Most packages do not
use the SDK variable.

But why look at other packages? The question is what is your use-case
for it?

**Comment by minfrin** [comment]
Ultimately the use case is to build and contribute a third party set of Apache modules to openwrt. This uncovered a long series of bugs:

- To build third party modules, you need apxs, this was missing.

- After apxs was re-added, it turned out it was a moot point, as httpd had been compiled statically with all support for loadable modules removed. This was in turn caused by apr-util being compiled statically with all loadable modules removed.

- apr-util has dynamic module support enabled in this PR. Turns out you were working on a similar thing in https://github.com/openwrt/packages/pull/10906 but only enabled a subset of the modules, my version enabled all modules supported in openwrt.

- apr-util, like httpd, supports dynamic modules. This is so that you can package and distribute something like a SQL database or LDAP and not bind it into the core server. In the same way that you added httpd modules in https://github.com/openwrt/packages/pull/10898, I added apr-util modules in this PR.

- apr-util supports mysql, but someone had switched it off. Switching it on revealed that mariadb doesn't build against APR. That was fixed upstream and the patch added here in this PR.

- apxs was then tested and discovered to not support cross compiling, which is probably why it was removed. I then fixed apxs upstream, the patch is in this PR.

- apxs was then discovered to still be broken, caused by both apr and apr-util having broken cross compilation support. Both of them were fixed upstream, and the fixes are in this PR.

- apr-util also supports gdbm, this was enabled, but due to bugs in httpd httpd tries to link to it when it shouldn't do so (that's apr-util's loadable modules' job). The workaround is to tell openwrt to depend on libgdbm. I'm up to my eyeballs in bugs, I plan to fix this one too, but let me at least get third party modules working.

Next step was to add module support to httpd, at which point I discovered we'd both been working from either end, and had met in the middle. Given you'd committed first, this PR came third, and is layered above yours and the apr changes. There was no way to work on this without conflicting with both, so I started from scratch and layered this PR in top of yours. As soon as yours is committed, this PR will conflict, and in theory github's merging should sort it out without much trouble.

Ultimately I was hoping that wiring in a third party module would be an hour or two's work over the holiday, but it's turned out to involve fixing everything from the ground up. It works now, and apr-util and httpd both have loadable modules switched on, and that's the important thing.

With two people having working on the same thing at the same time we will need to figure out the order of the commits, but this should not be a problem, just commit the PRs in date order.

So, to the SDK variable. Looking at the autotools in apr-util, building statically seems to be an all or nothing thing, so the SDK variable doesn't make much sense there. But in httpd each module can be selected either statically or as a module, the variable would be of use there assuming someone wants to make a monolithic httpd binary (which is now no longer the default). So SDK makes sense in httpd.

**Comment by micmac1** [comment]
> Ultimately the use case is to build and contribute a third party set of Apache modules to openwrt. This uncovered a long series of bugs:

Actually I was referring to why you want to use the SDK variable.

> - apr-util has dynamic module support enabled in this PR. Turns out
> you were working on a similar thing in
> https://github.com/openwrt/packages/pull/10906 but only enabled a
> subset of the modules, my version enabled all modules supported in
> openwrt.

dbd-odbc and dbm-gdbm I didn't add. You can add these later, no problem.

> - apr-util supports mysql, but someone had switched it off. Switching
> it on revealed that mariadb doesn't build against APR. That was fixed
> upstream and the patch added here in this PR.

Also can be added later.

> - apxs was then tested and discovered to not support cross compiling,
> which is probably why it was removed. I then fixed apxs upstream, the
> patch is in this PR.

Actually it does support cross-compiling. It just needs a leg up. I
already have a sed script setting up config_vars.mk for us. One is
missing for apxs. I'll add it to my pull request. I'm able to compile
mod_gnutls with it, so it should be OK for other external plugins as
well.

**Comment by micmac1** [comment]
Hello @minfrin 

Am I assuming correctly that you're still interested in getting certain changes in? Could you please rebase on current master and split the changes into different commits with proper commit messages?

Kind regards,
Seb

**Comment by micmac1** [comment]
I think this can be closed. Thanks!

**Comment by micmac1** [comment]
@minfrin can this be closed now?

**Comment by neheb** [comment]
Closing. Please make a new PR for further changes.

**Pull request closed without merging**
