### PR TITLE
mwan3: Add latency and packet loss check

### PR DESCRIPTION
**Pull request by codemarauder**
Maintainer: me / @feckert 
Compile tested: No
Run tested: x86, geode, 17.01.4

Description:
While using mwan3 in a production scenario, there was the need to monitor link quality on the basis of packet loss and latency. This is the first cut of the changes made to consider online/offline the monitored link.

### CODE REVIEW

**Comment by hnyman** [comment]
Well, the current maintainer is @feckert  (as shown in the package Makefile)

@codemarauder 
* your config file change has partially spaces instead of tabs, likely due to copy-paste errors.
* you haven't signed-off your commit

**Comment by codemarauder** [comment]
Replaced "spaces" by "tab".
Updated current maintainer to @feckert

**Comment by codemarauder** [comment]
Hi,

I have tried to fix spaces with tab. Updated the current maintainer and 
added Signed-off-by:, but the build is still failing.

This is my first ever pull request. Kindly advise.

Regards,
Nishant

**Comment by hnyman** [comment]
> This is my first ever pull request. Kindly advise.

Directly from the Travis error log:

```
=== Checking commit '641779dafc179129688a8d1d66742b319b1eafef'
Author name (Nishant Sharma) seems ok
Commit subject line seems ok (mwan3: Add latency and packet loss check.)
Signed-off-by match author
=== Checking commit 'a566bfd54b2e6e7bd165a7cc1f34dff413fea3ef'
Author name (Nishant Sharma) seems ok
Commit subject line seems ok (mwan3: Add latency and packet loss check. Fix tab/space issues Signed-off-by: Nishant Sharma <codemarauder@gmail.com>)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Nishant Sharma <codemarauder@gmail.com>')
=== Checking commit '12de6ab0b73334f66940bc5e34581e66998777fe'
Author name (Nishant Sharma) seems ok
Commit subject line MUST start with '<package name>: ' (Add latency and packet loss check)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Nishant Sharma <codemarauder@gmail.com>')
```
You have three commits, and only one of them is signed.
You should "squash" them together into one proper commit.
Advice in https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

(you have the commits on master, which is bad practice. But you can still use "git rebase -i HEAD~3" to squash the three commits. Read the git docs for git rebase -i  / squashing: https://www.google.com/search?q=git+squash )

**Comment by codemarauder** [comment]
Closing. Will resend request once commits are cleaned up.

**Pull request closed without merging**
