### PR TITLE
libs/sqlite: Update to 3.24.0

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @champtar 
Compile tested: apm821xx, WD MyBook Live, OpenWrt master
Run tested: apm821xx, WD MyBook Live, OpenWrt master

Description:
Update sqlite to 3.24.0

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
No idea why travis fails

**Comment by cshoredaniel** [comment]
Yeah, I just had a fail too and it's long before the package I was changing even was started for compilation.

**Comment by cshoredaniel** [comment]
The one thing I see in common in the recently failing builds vs. successful builds is zlib  - where there is zlib Travis fails, or so it seems to me.

**Comment by diizzyy** [comment]
Without any logs it's down to guesswork which isn't very efficient :/

**Comment by commodo** [comment]
I'd definitely try to clear the build cache.
So, https://travis-ci.org/openwrt/openwrt/caches   [for those who have any admin rights] and clear all caches.

I don't feel that Travis CI is way more complicated than running something locally.
But, if the errors look funky, this build cache is a good suspect to start with.

**Comment by cshoredaniel** [comment]
FYI it looks like Travis is behaving again.  You might want to close and reopen to kick off a new build.

**Comment by diizzyy** [comment]
Let's give it a go...

**Comment by diizzyy** [comment]
@hnyman @dibdot 
Ok to merge?

**Pull request merged**
