### PR TITLE
openconnect: fix compilation against libp11 >= 0.4.7

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: @dangowrt @nmav 
Compile tested: ar71xx, LEDE r5461-01c5cf0
Run tested: not yet.

Description:

With the updated libp11 0.4.7, header file p11_err.h is missing in the InstallDev section and error code definition has also changed cause api incompatibility issue with openconnect

The other thing is that the bulidbot seems to have also failed catching this error in the check-compile.txt stage: it did not even try to reconfigure, recompile the code: http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/openconnect/check-compile.txt

### CODE REVIEW

**Comment by nmav** [comment]
Hi,
 Thanks. Could you sent this patch on the openconnect upstream?

**Comment by yousong** [comment]
I cannot find a patch not that hacky to be included into the upstream openconnect repo.  An issue was just opened for libp11 instead: https://github.com/OpenSC/libp11/issues/197

**Comment by dwmw2** [comment]
We either need a patch which makes OpenConnect build with all versions, or a configure check to complain about broken ones. A bare compilation failure is not good.

**Comment by dwmw2** [comment]
Fixing libp11 is also the right thing to do, of course. But the offending release does already exist so we need to cope with it.

**Comment by yousong** [comment]
@dwmw2 I updated the patch for openconnect.  If you think the it's acceptable, feel free to apply it to openconnect repo ;)

**Pull request merged**
