### PR TITLE
perl: add build config for aarch64

### LINKED ISSUE #2963: perl is missing arm64(aarch64) config
reported by buildbot: 
http://buildbot.openwrt.org:8010/broken_packages/arm64/perl/compile.txt

& replicated locally

```
Can't open files/aarch64.config: No such file or directory
```

### PR DESCRIPTION
**Pull request by tmn505**
Because nonexistent aarch64.config the build of perl will fail for ARM
64-bit targets. Fix it by adding mentioned config. Fixes #2963.

The config.sh file was generated on ESPRESSObin with OpenWrt/master and perl 5.26.1 source.
Package tested on the same system.

Maintainer: @Naoir  @pprindeville

### CODE REVIEW

**Comment by pprindeville** [comment]
We can merge this but I have no way to test it for now.

**Comment by pprindeville** [comment]
Can you pull PR #5504 and rebuild with it?  I want to make sure that this change, which is going in soon, doesn't stomp on your changes.

**Comment by tmn505** [comment]
> Can you pull PR #5504 and rebuild with it? I want to make sure that this change, which is going in soon, doesn't stomp on your changes.

It compiles and works without issues.

**Comment by pprindeville** [comment]
> It compiles and works without issues.

Sorry, I should have been more explicit...  all modules too?  When I'm testing any changes to Perl, I build *all* modules.  Some of them are a little fragile.

**Comment by tmn505** [comment]
Yep, they build all fine.

**Comment by pprindeville** [comment]
Excellent.

**Pull request merged**
