### PR TITLE
dnsdist: Update to v1.6.1 

### PR DESCRIPTION
**Pull request by WBNet-Wout**
Maintainer: @Habbie 
Compile tested: ramips (MIPS), HLK-7621 evaluation board, OpenWrt commit 2c9a07ed28e87bbe2d221d48aaa19b04672646a5
Run tested: ramips (MIPS), HLK-7621 evaluation board, OpenWrt commit 2c9a07ed28e87bbe2d221d48aaa19b04672646a5, checked if dnsdist works with a simple configuration that hands all queries to 1.1.1.1

Description:
I have updated dnsdist to v1.6.1 and removed the now unnecessary time_t check patch from all PowerDNS packages.

cc @stintel

### CODE REVIEW

**Review by Habbie — APPROVED** [review]
LGTM (maintainer), assuming the second commit message works well with AUTORELEASE.

**Comment by neheb** [comment]
Hmm. Old SDK maybe...

**Comment by stintel** [comment]
Is there a way to trigger the checks again, besides pushing another commit?

**Comment by neheb** [comment]
> Is there a way to trigger the checks again, besides pushing another commit?

I can do so manually. I'll wait a day before I do.

**Comment by neheb** [comment]
The SDK is located at https://hub.docker.com/r/openwrtorg/sdk

Seems it hasn't had a recent update...

**Comment by Habbie** [comment]
> Seems it hasn't had a recent update...

I now see 'last pushed 16 hours ago by aparcar' for a ton of architectures there.

**Comment by neheb** [comment]
time_t is not the failure now.

**Comment by Habbie** [comment]
> time_t is not the failure now.

ah, right.

`    ERROR: package/feeds/packages_ci/pigeonhole failed to build.`

**Comment by neheb** [comment]
Oh. Rebase against current master.

**Comment by WBNet-Wout** [comment]
I have rebased it.

**Review by stintel — APPROVED** [review]

**Pull request merged**
