### PR TITLE
opencv: remove gtk dependency

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: WRTnode Team <pub@wrtnode.com>, @noello (a member of the WRTnode Team that I could find) / @champtar (even though you're not listed as the maintainer, you have the first and last commits here)
Compile tested: ramips, openwrt master
Run tested: none

Description:
Avoids this:
```
Package opencv is missing dependencies for the following libraries:
libglib-2.0.so.0
libgthread-2.0.so.0
```
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by cotequeiroz** [comment]
Another one that needs #7588

**Comment by thess** [comment]
CircleCI updated - rebase PR and see if OK now.

**Comment by cotequeiroz** [comment]
```
bash: unzip: command not found
```
Not ready yet?

**Comment by thess** [comment]
You are still using the previous Docker image - You didn't rebase your PR to pickup the newer image and script updates.

**Comment by cotequeiroz** [comment]
I guess I had fetched the latest commits.  It works now.

**Comment by hnyman** [comment]
You should increase the PKG_RELEASE, just in case, I think.

In general, this is one of the last few packages failing in buildbot for any of selected major targets (like the the package archs for ar71xx, mvebu, ipq806x and x86). I have never seen the failure list for ar71xx, ipq806x and mvebu to be only approx. 5 packages at the same time, like now, so really a spectacular situation at the moment. So, big thanks for @cotequeiroz and @neheb for fixing a bunch of packages that were failing for a long time.

**Comment by cotequeiroz** [comment]
The PKG_RELEASE was an oversight, sorry.  It does change configure parameters, which may reflect in the final binary.  I usually don't increase if it's a host-only fix.

As for making packages work, it was a pleasure helping you out.

Cheers

**Comment by neheb** [comment]
No problem. Next release should be in pretty good shape.

**Pull request merged**
