### PR TITLE
bwm-ng: add patch to fix GCC 7.x compatibility

### PR DESCRIPTION
**Pull request by sch-m**
Maintainer: @Zokormazo 
Compile tested: x86_64, apu3, r6290+17-50641a0f9a

Description:
Fixes compilation against GCC 7.x

### CODE REVIEW

**Comment by dibdot** [comment]
Does it fix  #5686?

**Comment by neheb** [comment]
Yes it does

**Comment by Zokormazo** [comment]
Just tested, merge it ;)

**Comment by dibdot** [comment]
OK, thanks!

**Comment by Zokormazo** [comment]
@sch-m you should PR to upstream too: 

https://github.com/vgropp/bwm-ng

**Comment by sch-m** [comment]
This patch is already upstream:
https://github.com/vgropp/bwm-ng/commit/d5daf15c2098040b8b01753d3cdce8c1c79fc528

**Pull request merged**
