### PR TITLE
rtty: Update init script

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @zhaojh329 
Compile tested: armvirt-32, 2019-02-07 snapshot sdk
Run tested: armvirt-32, 2019-02-07 snapshot

Description:
The first commit changes indentation from spaces to tabs, leading to a smaller file size.

The second commit:
This replaces the use of `uci_validate_section()` with `uci_load_validate()`, which removes the need to declare local variables for every config option.

This also adds a `service_triggers()` function.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I've only run-tested this with minimal changes to the default config; I can do more extensive tests if necessary.

**Comment by neheb** [comment]
ping @zhaojh329

**Comment by feckert** [comment]
I think we should also a` Package/rtty/conffiles` section so that on an upgrade to a newer version this will be saved

**Comment by neheb** [comment]
Maintainer timeout. Merging.

**Pull request merged**
