### PR TITLE
i2c-tools: Update to 4.0

### PR DESCRIPTION
**Pull request by neheb**
Added a libi2c package as that is now needed.

Fixed the home URL to fix uscan.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dangowrt

### CODE REVIEW

**Comment by neheb** [comment]
For some reason, it's complaining about missing dependencies for i2c-tools when it's all there. Any ideas?

**Comment by diizzyy** [comment]
What is complaining?
Log?

**Comment by neheb** [comment]
install -d -m0755 /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools/usr/sbin
install -m0755 /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/tools/i2cdetect /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools/usr/sbin/
install -m0755 /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/tools/i2cdump /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools/usr/sbin/
install -m0755 /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/tools/i2cset /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools/usr/sbin/
install -m0755 /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/tools/i2cget /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools/usr/sbin/
install -m0755 /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/tools/i2ctransfer /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools/usr/sbin/
find /home/mangix/devstuff/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/i2c-tools-4.0/ipkg-arm_cortex-a9_vfpv3/i2c-tools -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package i2c-tools is missing dependencies for the following libraries:
libi2c.so.0

**Comment by diizzyy** [comment]
As far as I can tell that symlink isn't installed?

**Comment by neheb** [comment]
That was the issue. Looks like this is ready to go.

**Pull request merged**
