### PR TITLE
ttyd: update to 1.7.3

### PR DESCRIPTION
**Pull request by oskarirauta**
- fixes linking issue that appeared after gcc 13
 - removed obsolete (merged) patch
 - ttyd now depends on libcap, added that as a dependency.

release notes: https://github.com/tsl0922/ttyd/releases

Maintainer: @tsl0922
Compile tested: x86_64 / latest git
Run tested: n/a

### CODE REVIEW

**Comment by 1715173329** [comment]
thanks, btw upstream changed some arguments and we need to adjust our init script:
https://github.com/tsl0922/ttyd/blob/a2312cbfabcd085664626d4f16877125f2d8ad96/src/server.c#L87-L129

**Comment by tsl0922** [comment]
> --read-only was replaced with --writable

It's not included in 1.7.3 release yet.

**Comment by oskarirauta** [comment]
@tsl0922

Thanks. I'll revert that..

**Comment by 1715173329** [comment]
@tsl0922 could you approve it?

**Review by tsl0922 — APPROVED** [review]

**Comment by 1715173329** [comment]
Thank you all!

**Comment by 1715173329** [comment]
> Thanks. I'll revert that..

@oskarirauta please update your commit message as well

**Comment by oskarirauta** [comment]
@1715173329 updated

**Pull request merged**
