### PR TITLE
ncdu: update to version 1.14

### PR DESCRIPTION
**Pull request by Cynerd**
Maintainer: @clehner 
Compile tested: Turris Omnia, Mox
Run tested:

### CODE REVIEW

**Comment by diizzyy** [comment]
@neheb 
Please don't merge untested PRs

**Comment by BKPepe** [comment]
No need to worry about as it is tested on cortexa53, Turris MOX, OpenWrt master. ;-)

See:
Screenshot from 2019-03-29 21-38-16
Screenshot from 2019-03-29 21-39-27

**Comment by neheb** [comment]
While I personally did not test this, I do use it from time to time.

**Comment by diizzyy** [comment]
That's not the point

**Pull request merged**
