### PR TITLE
icu: Backport ARMEB support patch

### PR DESCRIPTION
**Pull request by neheb**
This should fix php compilation on PPC.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @nxhack 

edit:
https://downloads.openwrt.org/snapshots/faillogs/armeb_xscale/packages/icu/compile.txt

### CODE REVIEW

**Comment by nxhack** [comment]
LGTM

**Comment by diizzyy** [comment]
"Backport ARMEB support patch" from where? Please be more verbose

**Comment by neheb** [comment]
icu has an included version of libdouble-convert for some reason. Patch got accepted upstream. icu will probably have it included in the next few versions.

**Comment by diizzyy** [comment]
Such information should be in the commit message

**Pull request merged**
