### PR TITLE
pulseaudio: update to 17.0

### PR DESCRIPTION
**Pull request by jmv2009**
Update to 17.0. (Was: Prepare for 17.0, using 16.99.1)
dbus-1 per https://github.com/pulseaudio/pulseaudio/commit/e96d278bfc514f290b60c9e924fabc1c772e1689 from /etc/ to /usr/shared/

010-meson-gio.patch was upstreamed

Maintainer: @neheb
Compile tested: armsr/armv8
Run tested: armsr/armv8

### CODE REVIEW

**Comment by BKPepe** [comment]
Why this is still draft?

**Comment by neheb** [comment]
.99 versions are betas AFAIK

**Comment by jmv2009** [comment]
17.0 is now out...

**Comment by 1715173329** [comment]
> Update to 17.0. (Was: Prepare for 17.0, using 16.99.1) dbus-1 per [pulseaudio/pulseaudio@e96d278](https://github.com/pulseaudio/pulseaudio/commit/e96d278bfc514f290b60c9e924fabc1c772e1689) from /etc/ to /usr/shared/
> 
> 010-meson-gio.patch was upstreamed

Please mention these in your commit message.

BTW, please use real mail address rather than "noreply". fyi: https://openwrt.org/submitting-patches#submission_guidelines

**Comment by jmv2009** [comment]
Same as merged https://github.com/openwrt/packages/pull/23701. Thanks.

**Pull request closed without merging**
