### PR TITLE
WIP: gitea: add package

### PR DESCRIPTION
**Pull request by nirizr**
Signed-off-by: Nir Izraeli <nirizr@gmail.com>

Maintainer: me

Description:
I'd like to have a gitea package and willing to create and maintain it. However I have no familiarity with openwrt package management (and have never maintained a package).

### CODE REVIEW

**Comment by nirizr** [comment]
The package's source is downloaded, compilation starts but gets stuck on golang compilation (gitea is written in go).

During go compilation, go complains about $GOROOT being inside a module:
```
go tool dist: found go.mod file in /root/openwrt/openwrt/build_dir/target-mips_24kc_musl: $GOROOT must not be inside a module
```

A longer chunk of the compilation error:
```
SHELL= flock /root/openwrt/openwrt/tmp/.go1.16.src.tar.gz.flock -c '    /root/openwrt/openwrt/scripts/download.pl "/root/openwrt/openwrt/dl" "go1.16.src.tar.gz" "7688063d55656105898f323d90a79a39c378d86fe89ae192eb3b7fc46347c95a" "" "https://dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju.edu.cn/golang/"    '
rm -f /root/openwrt/openwrt/build_dir/target-mips_24kc_musl/go-1.16/.built
touch /root/openwrt/openwrt/build_dir/target-mips_24kc_musl/go-1.16/.built_check
mkdir -p "/root/openwrt/openwrt/tmp/go-build"
Building target Go first stage
( cd "/root/openwrt/openwrt/build_dir/target-mips_24kc_musl/go-1.16/src" ; GOROOT_FINAL="/usr/lib/go-1.16"  GOROOT_BOOTSTRAP="/root/openwrt/openwrt/staging_dir/hostpkg/lib/go-cross" GO_GCC_HELPER_CC="gcc" GO_GCC_HELPER_CXX="g++" GOCACHE="/root/openwrt/openwrt/tmp/go-build" GOENV=off GO_GCC_HELPER_PATH="$PATH" CC=gcc CXX=g++ PKG_CONFIG=pkg-config PATH="/root/openwrt/openwrt/staging_dir/hostpkg/lib/go-cross/openwrt:$PATH"  bash make.bash --no-banner ; )
Building Go cmd/dist using /root/openwrt/openwrt/staging_dir/hostpkg/lib/go-cross. (go1.16 linux/amd64)
go tool dist: found go.mod file in /root/openwrt/openwrt/build_dir/target-mips_24kc_musl: $GOROOT must not be inside a module
make[2]: *** [Makefile:360: /root/openwrt/openwrt/build_dir/target-mips_24kc_musl/go-1.16/.built] Error 1
make[2]: Leaving directory '/root/openwrt/openwrt/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/compile#0.61#0.10#0.52
    ERROR: package/feeds/packages/golang failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/golang/compile] Error 1
make[1]: Leaving directory '/root/openwrt/openwrt'
make: *** [/root/openwrt/openwrt/include/toplevel.mk:230: package/gitea/compile] Error 2
```

**Comment by nirizr** [comment]
Cleaning and rebuilding resulted in another error (hopefully a sign of progress):
```
mips-openwrt-linux-musl-gcc: error: unrecognized command line option '-m64'
```

**Comment by jefferyto** [comment]
I suggest changing the status of this PR to Draft until you are ready to have it considered for merging.

Also the Go compiler package was just updated to 1.16.5, not sure if it has any impact on this package.

**Comment by nirizr** [comment]
> I suggest changing the status of this PR to Draft until you are ready to have it considered for merging.

How I can I do that?

> Also the Go compiler package was just updated to 1.16.5, not sure if it has any impact on this package.

Thanks, I'll check that and see if there's any (hopefully positive) impact.

**Comment by jefferyto** [comment]
> How I can I do that?

Under "Reviewers" in the right-side column, there should be a "Convert to draft" link.

**Comment by nirizr** [comment]
Got to running gitea's makefile after setting up host' golang...

Currently stuck at
```Running go generate...
CGO_CFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fmacro-prefix-map=/root/openwrt/openwrt/build_dir/target-mips_24kc_musl/golang-gitea-1.14.2=golang-gitea-1.14.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" go build -mod=vendor -v  -tags '' -ldflags '-s -w -L/root/openwrt/openwrt/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/usr/lib -L/root/openwrt/openwrt/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/lib -znow -zrelro  -X "main.MakeVersion=GNU Make 4.2.1" -X "main.Version=1.14.2" -X "main.Tags="' -o gitea
# code.gitea.io/gitea
flag provided but not defined: -L/root/openwrt/openwrt/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/usr/lib
```

**Comment by nirizr** [comment]
Compilation seems to be working. Still need to add the bindata tag and fix installation.

**Comment by BKPepe** [comment]
Closing. There is no work for more than 5 months.

**Pull request closed without merging**
