### PR TITLE
Fix time_t logging in https-dns-proxy #19366

### PR DESCRIPTION
**Pull request by schmaller**
Maintainer: Stan Grishin <stangri@melmac.ca>
Compile tested: mips_24kc, TP-Link Archer C6 v2, OpenWrt r22998-066441b5e4
Run tested: mips_24kc, TP-Link Archer C6 v2, OpenWrt r22998-066441b5e4
Signed-off-by: Daniel Stränger <dev@schmaller.de>

### CODE REVIEW

**Comment by stangri** [comment]
@schmaller Daniel, thank you for the patch! I've refreshed it for the current source in https://github.com/stangri/source.openwrt.melmac.net/commit/f7efafeaecf2d987e674da67e18c4520571a0f16. Could you please update the patch and bump the version number as per commit above?
Thanks!

**Comment by schmaller** [comment]
@stangri  Hi Stan, I'm not too experienced in Git patching and Github CI.
Is that what you thought?
You may adopt my PR to your needs by yourself if you can. Thanks!

**Comment by stangri** [comment]
@schmaller I believe the issues right now are:
* merge commit in the PR
* you've included the luci app in this PR, as I wasn't clear that only the principal app version number needs to be bumped when I referred to the commit to my personal repo

Sorry, my git-fu is not strong enough to undo the merge commit in this PR. 

If you want to close this and create a new PR with only the https-dns-proxy version bump and the refreshed patch (either from my commit or if you want to follow the OpenWrt wiki on refreshing patches and create one yourself), I believe the CI should successfully test that.

I can also create a new PR myself, but you've done all the work investigating and fixing the issue and testing the fix, it's only right if you make a PR. ;)

**Comment by schmaller** [comment]
@stangri I could edit the PR, remove the luci-app file and fix the version number.
I hope it works now.

**Comment by schmaller** [comment]
No luck with this dirty PR ... i'll create a new one.

**Pull request closed without merging**
