### PR TITLE
adblock: update 4.0.5-6

### PR DESCRIPTION
**Pull request by amteza**
New options under YouTube SafeSearch: restrictive, moderate or disabled. This allows for better YouTube filter control, as for some even moderate filtering is too intrusive, e.g. with music. This will allow to disable completely YouTube filtering and keeping SafeSearch enabled for the other search engines.

Signed-off-by: Alberto Martínez Álvarez <amteza@gmail.com>

Maintainer: Dirk Brenken <dev@brenken.org> @dibdot    @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (aarch64, RPi4, OpenWrt master)
Run tested: (aarch64, RPi4, OpenWrt master, tested all options on interface)

### CODE REVIEW

**Comment by hnyman** [comment]
As you are pushing from master, the PR contains unrelated ffmpeg files.

**Comment by dibdot** [comment]
I don't like this "youtube-only" way. Why should we limit a disabled safesearch provider functionality to youtube? I'll provide a more generic approach with the next update.

**Comment by dibdot** [comment]
generic approach implemented in #12494 and https://github.com/openwrt/luci/pull/4166

**Comment by amteza** [comment]
> As you are pushing from master, the PR contains unrelated ffmpeg files.

Apologies, messed up.

**Comment by amteza** [comment]
> generic approach implemented in #12494 and [openwrt/luci#4166](https://github.com/openwrt/luci/pull/4166)

Thanks, I like your generic approach better. Only YouTube has an explanation, usually you want to filter searching in all the engines; however, YouTube filters are very restrictive in their nature, so even under moderate you will find that —for example— common music videos get blocked, which is more an annoyance than anything else. Same thing happens to other contents.

**Comment by dibdot** [comment]
The generic variant has been merged - closing this.

Thanks!

**Pull request closed without merging**
