### PR TITLE
ddns-scripts: Add support for the service dtdns.com

### PR DESCRIPTION
**Pull request by dedeckeh**
Support is added to the service file for dtdns.com (https://www.dtdns.com)

Signed-off-by: Hans Dedecker <dedeckeh@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@chris5560

**Comment by chris5560** [comment]
@dedeckeh
Could you please also increase PKG_RELEASE in Makefile to document changes inside package.
Do you have any information about IPv6 support.
Thanks.
Christian

**Comment by dedeckeh** [comment]
@chris5560 
Increased the PKG_RELEASE which I initially forgot
IPv6 does not seem to be supported by dtdns (http://www.ipv6-spider.com/en/host/dtdns.net)

**Comment by chris5560** [comment]
@hnyman 
OK from my side, could you please merge
thanks Christian

**Pull request merged**
