### PR TITLE
nbd: Update to 3.19 and remove unneed patches

### PR DESCRIPTION
**Pull request by cshoredaniel**
Current version in OpenWrt (3.16.2) fails against the Arch Linux
in System Rescue CD's NBD as rootfs (to allow sharing ISO across
network).  Based on resolved issues and web searching it seems
nbd had endianness issues (which affected my ath79 device).

This updates to 3.19 which allows System Rescue CD PXE boot with
NBD rootfs to work.

Removed patches no longer required due to upstream changes, and
added new configure option (--without-libnl) required to avoid
linking against full libnl and libnl-genl (if present in build).

Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

Maintainer: @marcin1j
Compile tested: ath79, pcs_cr5000, recent snapshot SDK & IB with current master of packages
Run tested: same arch, model, etc

nbd-server lightly tested (serving an ISO to System Rescue CD PXE boot which fails with 3.16.2 during the negotiation phase).  nbd-client not run tested.

### CODE REVIEW

**Comment by cshoredaniel** [comment]
Erm SDK failed to download?

**Comment by BKPepe** [comment]
> Erm SDK failed to download?

It will be fixed once https://github.com/openwrt/packages/pull/9024 is merged.

**Comment by neheb** [comment]
Yeah don’t worry about it: https://github.com/openwrt/packages/pull/9020

**Comment by cshoredaniel** [comment]
repushed after rebase for proper SDK -- now passing CI

**Comment by marcin1j** [comment]
@cshoredaniel 
Please append `--enable-syslog` to `CONFIGURE_ARGS`.

I've tested your changes and everything is OK. Previous version indeed fails to handle connection from x86 clients. Wonder when that has happened. It used to work and that scenario was specifically tested.

**Comment by cshoredaniel** [comment]
``--enable-syslog`` appended and nbd-server retested against system rescue cd  Arch Linux derivative.
I had not used nbd before, so I have no idea when things changed.

**Comment by marcin1j** [comment]
LGTM

Thanks for your contribution!

**Pull request merged**
