### PR TITLE
strongswan: update to 5.4, add plugins, fixes

### LINKED ISSUE #2038: please apply https://wiki.strongswan.org/issues/1212
please apply https://wiki.strongswan.org/issues/1212
and enable forecast plugin!

### PR DESCRIPTION
**Pull request by stintel**
Last 2 commits close #2038.

### CODE REVIEW

**Comment by stintel** [comment]
@DocMAX: please test and report if this solves #1868 and #2038 for you.

**Comment by stintel** [comment]
ping @sbyx

**Comment by DocMAX** [comment]
iptables MARK work

**Comment by stintel** [comment]
@DocMAX thanks for the feedback.
The changes have also been merged into strongswan and will be part of the 5.4.0 release: https://wiki.strongswan.org/issues/1212

**Comment by champtar** [comment]
@stintel i think you can remove commit 8ca29a2 and just bump to 5.4.0

**Comment by champtar** [comment]
ping @sbyx 
this has been tested by @stintel and @DocMAX

**Comment by stintel** [comment]
@sbyx ping?

**Comment by champtar** [comment]
compile tested on ar71xx LEDE master

**Comment by stintel** [comment]
Thanks @champtar

**Pull request merged**
