### PR TITLE
mwan3: add chnroute support

### PR DESCRIPTION
**Pull request by kingyond**
two steps to config chnroute support
first step:
goto mwan3 load balancing page->advanced->Hotplug Script, using the new
16-mwancustom script , copy and paste , click submit.
note:you need to upload /etc/chinadns_chnroute.txt youselft or install
ChinaDNS which include installing the file.
second step:
goto mwan3 load balancing page->config->rules, add a mark type rules
for chnroute balancing Policy. add the default full to vpn Policy.
note:you need to install vpn and configure mwan3
interface/members/policies. suggest using ShadowVPN.
reboot router and enjoy chnroute with mwan3.

### CODE REVIEW

**Comment by champtar** [comment]
Hi @kingyond,
please follow https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by champtar** [comment]
@Adze1502 if you can review the mwan3 part
@kingyond, you need (at least) to start your commits with ```mwan3:``` or ```mwan3-luci:```, add signed-off-by line.

**Comment by Adze1502** [comment]
Most of the changes proposed by @kingyond are for luci-app-mwan3 package. Only the last changes applies to mwan3 package itself. But the change will break functionality. Therefor i will not add the suggested changes.

**Comment by champtar** [comment]
Is there a way to integrate @kingyond modifications without breaking mwan3?

**Comment by Adze1502** [comment]
No. The very first commit "add chnroute support" suggests that he wants to override the mark value with config parameters. With this he will be able to steer traffic using the default routing table. But this functionality is already there. He just has to use policy "default". None of the suggested commits make sense to me.

Besides, i'm working on 1.6 version, which has ipset support, which makes the changes obsolete.

**Comment by champtar** [comment]
@kingyond, please take a look at mwan3 1.6

**Pull request closed without merging**
