### PR TITLE
softflowd: add traffic capture filter

### PR DESCRIPTION
**Pull request by jesferman**
softflowd can filter the traffic with an optional bpf program,
specified on the command-line as a BPF expression

Signed-off-by: Jesus Fernandez Manzano <jesus.manzano@galgus.net>

### CODE REVIEW

**Review by BKPepe — CHANGES_REQUESTED** [review]
Requires ``PKG_RELEASE`` bump.

**Comment by jesferman** [comment]
You are right, my bad. Pull request updated.

**Comment by jesferman** [comment]
Refloating this PR just in case it got forgotten. The requested changes were added, @BKPepe.

**Comment by neheb** [comment]
ping @rvandegrift

**Comment by rvandegrift** [comment]
lgtm, thanks!

**Pull request merged**
