### PR TITLE
ipsec-tools: add ability to exclude some addresses from SA config

### PR DESCRIPTION
**Pull request by aTanW**
Signed-off-by: Vitaly Protsko <villy@sft.ru>
---
 functions.sh |   35 +++++++++++++++++++++++++++++++++++
 racoon       |    4 ++++
 racoon.init  |   12 ++++++++----
 3 files changed, 47 insertions(+), 4 deletions(-)

### CODE REVIEW

**Comment by hnyman** [comment]
cc to maintainer: @nmeyerhans 

@aTanW 
you need to increase PKG_RELEASE in Makefile.

**Comment by aTanW** [comment]
Can pulls be squashed?

**Comment by hnyman** [comment]
They can be easily squashed. 
First squash, then force push the branch.

Advice in https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by aTanW** [comment]
No moving from Feb'6. As it was previous time. Can it be merged w/o review?

**Comment by hnyman** [comment]
As @nmeyerhans does not seem to react to this PR, just add yourself as the second maintainer to the package. 

And then please squash/rebase the commits into one. (currently there are five extra commits.)

**Comment by aTanW** [comment]
erroneous squash

**Pull request closed without merging**
