### PR TITLE
numpy: bump to version 1.21.1

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: x86  https://github.com/openwrt/openwrt/commit/6c148116f778bfd2db88476cee4753b32538eafe
Run tested: x86 https://github.com/openwrt/openwrt/commit/6c148116f778bfd2db88476cee4753b32538eafe

-----------------------------------------------

Also bump Cython version to 0.29.23.
And add support for OpenBLAS.
Currently optional, but will be enabled by default on some architectures
later.

Depends on PR https://github.com/openwrt/packages/pull/15685

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
Changelog v1 -> v2:
* bump to 1.21.1 - a new version since PR was opened

**Comment by hnyman** [comment]
This seems to cause circular dependency:

```
perus@ub2104:/Openwrt/wrt3200$ make defconfig
tmp/.config-package.in:32970:error: recursive dependency detected!
tmp/.config-package.in:32970:	symbol PACKAGE_python3-numpy depends on NUMPY_OPENBLAS_SUPPORT
tmp/.config-package.in:33000:	symbol NUMPY_OPENBLAS_SUPPORT depends on PACKAGE_python3-numpy
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

#
# No change to .config
#

```

**Comment by commodo** [comment]
> This seems to cause circular dependency:
> 
> ```
> perus@ub2104:/Openwrt/wrt3200$ make defconfig
> tmp/.config-package.in:32970:error: recursive dependency detected!
> tmp/.config-package.in:32970:	symbol PACKAGE_python3-numpy depends on NUMPY_OPENBLAS_SUPPORT
> tmp/.config-package.in:33000:	symbol NUMPY_OPENBLAS_SUPPORT depends on PACKAGE_python3-numpy
> For a resolution refer to Documentation/kbuild/kconfig-language.rst
> subsection "Kconfig recursive dependency limitations"
> 
> #
> # No change to .config
> #
> ```

will take a look
for some reason, this did not show up when i did the change;
i remember trying to avoid circular deps;
will see;

**Comment by hnyman** [comment]
Pure guess, but might be due to the menu dependecy (line 45) causing the config symbol NUMPY_OPENBLAS_SUPPORT to indirectly depend on python3-numpy:

https://github.com/openwrt/packages/pull/16054/files#diff-483985d242c8091825468817f8caec48b48e98690cc6b28c1b469d4b1f45e291R45

`depends on PACKAGE_python3-numpy`

**Comment by commodo** [comment]
yep
that fixes it

**Comment by commodo** [comment]
opened PR #16242

**Pull request merged**
