### PR TITLE
[22.03] ubnt-manager/prometheus-node-exporter-lua: add airos monitoring

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add ubnt-manager for managing airos devices. Based on that package ubnt-manager-collector collects statistics.

@champtar

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @champtar ?

**Comment by champtar** [comment]
Sorry, I used rebase and merge, so can you make sure "cherry picked from" points to the commit inside the repo ? (At least last one need fixing)

**Comment by PolynomialDivision** [comment]
> Sorry, I used rebase and merge, so can you make sure "cherry picked from" points to the commit inside the repo ? (At least last one need fixing)

@champtar Updated :)

**Comment by PolynomialDivision** [comment]
ping @champtar ;)

**Comment by champtar** [comment]
Last commit is still not fixed, just click on it in the UI it points to your repo

**Comment by PolynomialDivision** [comment]
> Last commit is still not fixed, just click on it in the UI it points to your repo

@champtar I guess that is a failure from GitHub:
https://github.com/openwrt/packages/commit/42e841039bba1daa2af11b3b3cebe367e2a3d7c3

And my commit message also contains:
42e841039bba1daa2af11b3b3cebe367e2a3d7c3

**Comment by PolynomialDivision** [comment]
```
https://github.com/openwrt/packages/commit/42e841039bba1daa2af11b3b3cebe367e2a3d7c3
```

```
42e841039bba1daa2af11b3b3cebe367e2a3d7c3
```

**Comment by champtar** [comment]
Just checked manually, GH sends me to your repo, and the commit is not in your repo and only in openwrt repo

**Pull request merged**
