### PR TITLE
libidn: bump to v1.34 (2018-03-31)

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Bump to v1.34
Refresh patches.
Update Makefile to use new '--disable-doc' configure flag.

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by diizzyy** [comment]
@kaloz @iamperson347 @dangowrt @heil @fededim @salzmdan @psycho-nico @mhei 

Since libidn only supports IDNA2003 (deprecated) it's probably a good idea to import libidn2 (IDNA2008) and do a treewide sweep removal of libidn as only a handful of packages uses it. Preferably soon due to the proposed release scheduled.

Red Hat etc are moving in this direction soon too:
https://fedoraproject.org/wiki/Changes/IDNA2008

```
Upstream status:
curl		-->	ok
getdns		-->	ok
gnunet		-->	ok
prosody		-->	can be replaced with icu (no libidn2 yet)
lftp		-->	ok
knot		-->	ok
gnunet		--> 	patch --> https://ng.gnunet.org/bugs/view.php?id=5173&nbn=2
msmtp		--> 	no needed (deactivated in package)
php7-pecl-http	--> 	ok
```

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/5866
No idea if it works but at least it compiles... :-)

**Comment by diizzyy** [comment]
Works fine with curl at least

**Comment by iamperson347** [comment]
I can update the getdns package once libidn2 is added. To my knowledge, stubby supports both.

**Comment by diizzyy** [comment]
Friendly reminder that https://github.com/openwrt/packages/pull/5878 is committed

**Pull request closed without merging**
