### PR TITLE
python,python3: add Jeffery To as co-maintainer

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me / @jefferyto ?
Compile tested: N/A
Run tested: N/A

---------------------------------------------------------------

For a while now, Jeffery has helped quite a lot with Python, and is now
unofficial go-to guy [for problems] with Python packages.

This change adds him as co-maintainer [if he also agrees].

I'm not going away; I'll be still doing the same work for Python.
This change serves to recognize Jeffery in an official way, since he's
already taking on these things. And 2 co-maintainers is better in case one
kicks the bucket [by accident].

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I'm fine with this, as long as everyone knows I'm _famously_ unreliable :joy:

**Comment by commodo** [comment]
so am i :)
welcome to the _famously_ unreliable club 

if no objections; this can be merged

**Comment by commodo** [comment]
i suspect @hnyman is rolling his eyes now [ like, oh no: double [python] trouble ]

**Comment by hnyman** [comment]
Now there are two guys to push at Python problems.... Nice.
The whole python package universe is rather complex and has evolved during the years, so it is great that there are many eyes.

**Pull request merged**
