### PR TITLE
net: socat: add option user

### PR DESCRIPTION
**Pull request by paulfertser**
Allow UCI configuration to specify username to run this service as.
Defaults to root.

Signed-off-by: Paul Fertser <fercerpav@gmail.com>

Maintainer: @neheb 
Compile tested: 21.02-rc3
Run tested: 21.02-rc3

Description:

### CODE REVIEW

**Comment by neheb** [comment]
Needs a PKG_RELEASE bump.

**Comment by paulfertser** [comment]
Thank you. Tend to forget about it every time. Probably the CI should be taught to detect that somehow?

**Comment by neheb** [comment]
@aparcar handles the CI.

**Comment by aparcar** [comment]
Please use $(AUTORELEASE)

**Pull request merged**
