### PR TITLE
tinyproxy: Update to 1.11.1

### PR DESCRIPTION
**Pull request by autoexpect**
Maintainer: Jo-Philipp Wich <jo@mein.io>
Compile tested: amd64
Run tested: amd64 tests done

Description:
- Added BasicAuth support

### CODE REVIEW

**Comment by 1715173329** [comment]
cc @jow-

**Comment by 1715173329** [comment]
Please mention your changes in commit message
- Added BasicAuth support
- Removed upstreamed patch (?)

also cc @neheb

**Comment by neheb** [comment]
Seems fine

**Comment by autoexpect** [comment]
@1715173329 @neheb 
The net/tinyproxy/patches/120-fix_INET6.patch patch has been force committed.

**Pull request merged**
