### PR TITLE
postfix/dovecot: Add SQLite support and #4077

### PR DESCRIPTION
**Pull request by lucize**
Maintainer: @Shulyaka 

Add SQLite support
Also disable icu #4077 as is not yet upstream

If 2 commits are not ok I separate them, but right now I don't know how 

Compile/Run tested x86_64 LEDE/Reboot (SNAPSHOT, r3624-23bf153)

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by nxhack** [comment]
dovecot: LGTM

postfix:
typo ?
```
--- a/Makefile
+++ b/Makefile
@@ -111,7 +111,7 @@
   CCARGS+=-DNO_DB
 endif
 
-ifdef CONFIG_POSTFIX_CDB
+ifdef CONFIG_POSTFIX_SQLITE
   CCARGS+=-DHAS_SQLITE -I$(STAGING_DIR)/usr/include/
   AUXLIBS+=-L$(STAGING_DIR)/usr/lib -lsqlite3 -lpthread
 endif
```

And When using musl, need this patch
```
--- a/src/posttls-finger/posttls-finger.c
+++ b/src/posttls-finger/posttls-finger.c
@@ -318,6 +318,7 @@
 #include <sys/un.h>
 #include <netinet/in.h>
 #include <arpa/inet.h>
+#include <stdio.h>
 
 #ifdef STRCASECMP_IN_STRINGS_H
 #include <strings.h>
```

**Comment by lucize** [comment]
yes, sorry about that, it worked because CDB was also selected, I'll read how to amend the commit

Regards!

**Comment by lucize** [comment]
yes, sorry about that, it worked because all were selected
I've updated it

Regards

**Comment by nxhack** [comment]
If 'POSTFIX_TLS' is defined, stdio.h related problems will not appear.
Because the openssh related header file contains "#include <stdio.h>" line.

**Comment by lucize** [comment]
Added the stdio.h include

Regards!

**Comment by nxhack** [comment]
I think it is better to increase PKG_RELEASE.

**Comment by nxhack** [comment]
LGTM, build fine! 
```
#                                                                                                                             
# Select postfix build options                                                                                                
#                                                                                                                             
# CONFIG_POSTFIX_TLS is not set                                                                                               
# CONFIG_POSTFIX_SASL is not set                                                                                              
# CONFIG_POSTFIX_LDAP is not set                                                                                              
# CONFIG_POSTFIX_DB is not set                                                                                                
CONFIG_POSTFIX_CDB=y
CONFIG_POSTFIX_SQLITE=y
# CONFIG_POSTFIX_EAI is not set                                                                                               
# CONFIG_PACKAGE_ssmtp is not set                                                                                             
```
BTW: In actual world, POSTFIX_TLS must set y ;)

**Comment by Shulyaka** [comment]
I'm ok with it on the high level, however there is a problem if only SQLITE is selected with CDB and DB unselected.

In the following section:
```
+ifdef CONFIG_POSTFIX_SQLITE
+  CCARGS+=-DHAS_SQLITE -I$(STAGING_DIR)/usr/include/
+  AUXLIBS+=-L$(STAGING_DIR)/usr/lib -lsqlite3 -lpthread
+endif
```
I believe you should set default_database_type variable to sqlite if both CONFIG_POSTFIX_CDB and CONFIG_POSTFIX_DB are undefined. Also, in the `Build/Configure` section please amend
```
 	if [ "$(CONFIG_POSTFIX_DB)" = "" -a "$(CONFIG_POSTFIX_CDB)" = "" ]; then\
 	  echo "Build error: You must select at least one of the DB types";\
           exit 1;\
 	fi
```
to include CONFIG_POSTFIX_SQLITE into condition:
```
 	if [ "$(CONFIG_POSTFIX_DB)" = "" -a "$(CONFIG_POSTFIX_CDB)" = "" -a "$(CONFIG_POSTFIX_SQLITE)" = "" ]; then\
 	  echo "Build error: You must select at least one of the DB types";\
           exit 1;\
 	fi
```

**Comment by Shulyaka** [comment]
Should we also send the 501-include_stdio.patch fix upstream?

**Comment by nxhack** [comment]
I agree with your implementation on DB select.

> Should we also send the 501-include_stdio.patch fix upstream?

I think that it is better for corresponding to various patterns.

**Comment by lucize** [comment]
I've read somewhere that sqlite can't be a default database type.
In postfix manual I found this: 

```
**default_database_type (default: see "postconf -d" output)**
The default database type for use in newaliases(1), postalias(1) and postmap(1) commands. On many UNIX systems the default type is either dbm or hash. The default setting is frozen when the Postfix system is built.

Examples:

default_database_type = hash
default_database_type = dbm

```

Regards

**Comment by hnyman** [comment]
You should increase PKG_RELEASE for postfix, as functionality changes.

And you should dquash these commits together, one per package.
(and properly sign off ALL of them)

@tripolar seems to be the maintainer for dovecot. Any objections for the changes?

**Comment by lucize** [comment]
ok, I've squashed them and made all the changes

**Comment by nxhack** [comment]
@lucize 

As @Shulyaka mentioned:
>I believe you should set default_database_type variable to sqlite if both CONFIG_POSTFIX_CDB and CONFIG_POSTFIX_DB are undefined. Also, in the Build/Configure section please amend

I think it better to do this.
```
ifdef CONFIG_POSTFIX_SQLITE
  CCARGS+=-DHAS_SQLITE -I$(STAGING_DIR)/usr/include/
  AUXLIBS+=-L$(STAGING_DIR)/usr/lib -lsqlite3 -lpthread
  ifndef CONFIG_POSTFIX_CDB
    ifndef CONFIG_POSTFIX_DB
      default_database_type=sqlite
    endif
  endif
endif
```

**Comment by lucize** [comment]
I tried only with sqlite and I'm seeing this error

```
postalias: fatal: unsupported map type for this operation: sqlite
postmap: fatal: unsupported map type for this operation: sqlite
```

so I don't think that we should consider running it withour DB or CDB

**Comment by nxhack** [comment]
@lucize
I see. Let's revert "Build/Configure".

**Comment by Shulyaka** [comment]
Ok, didn't know that.

**Comment by lucize** [comment]
@hnyman squashed and signed

**Comment by tripolar** [comment]
hi, i don't use dovecot anymore. anyone motivated to become the maintainer of dovecot? As i don't use it anymore I would delete it from the tree if no one is interested.

**Comment by lucize** [comment]
For the moment I have to figure out how to package perl modules but I would like to make a postfix,dovecot,postgrey,clamav,spamassassin,postfixadmin solution so i'll try to maintain it if no one  is interested.
I see that last version is 2.2.28, I'll bump it

regards

**Comment by tripolar** [comment]
thanks, do you have commit rights to the openwrt repo?
if yes, please set yourself as the maintainer in the makefile of dovecot

**Comment by lucize** [comment]
no, I don't have!

regards

**Comment by tripolar** [comment]
so maybe go to the irc freenode channel #openwrt-devel or write a mail to the mailing list, so someone gives you commit access

**Comment by hnyman** [comment]
Most maintainers do not have commit access and submit their changes via PRs.
Just edit the Makefile in the pull request to have you as the maintainer.

**Comment by tripolar** [comment]
i can't and will never commit stuff i never tested. and i won't start using dovecot again just to test it. dovecot needs a mainainer that uses it, otherwise it will get deleted from the tree

**Comment by lucize** [comment]
I don't need commit access I'm just fine in making PR's
added me

regards

**Comment by tripolar** [comment]
but who will fix stuff if your last commit is introducing some regressions? i think the maintainer should have commit access

**Comment by champtar** [comment]
Hi @tripolar,
"Signed-off-by" just imply that you have the legal right to publish this code under the project license, and it has no meaning regarding testing
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst#n416

Now if you have commit access, you push a patch with regressions, and you go MIA, that's the same problem, other people with commit access can take the decision to revert last changes or step up to fix the problem.

Being maintainer mean for me:
1) I'm an active user of this package
2) I'm willing to review and test other people patches against this package

People with commit access merging maintainer PR often only review the patches for obvious errors, and trust that this was run tested because of 1) (and because they said so in the PR)

I haven't done stats, but it seems to me that PR submitted by the maintainer himself are merged pretty fast

Regards
Etienne

**Comment by tripolar** [comment]
okay so i'm fine with this. please set yourself as mantainer and i will commit it
@champtar thanks for the info

**Comment by lucize** [comment]
I've already done it, I've installed 2.2.28 , I'll make a PR after a few days if nothing appears

regards

**Comment by tripolar** [comment]
i'll commit it when 2.2.28 is finished

**Comment by lucize** [comment]
I've pushed the update and made separate PR's #4108 and #4109 

regards

**Pull request closed without merging**
