### PR TITLE
Radicale 2.x as radicale2

### PR DESCRIPTION
**Pull request by cshoredaniel**
Maintainer: me / @cshoredaniel 

EDIT: @jefferyto (maintainer of Radicale (1.x))

 [**EDIT**: It's ready now]  This isn't ready yet,, but I wanted to make a PR to gather comments.  This is v2 of Radicale CalDAV/CardDAV server for which 1.x is now deprecated (which is currently in the packages repo).  v2 is significantly different so I decided to get a fresh start.

python-dateutils is updated to allow python3 build and a few new dependencies are added.

EDIT: remove merged or no longer relevant PR dependencies

### CODE REVIEW

**Comment by cshoredaniel** [comment]
grr git add before git amend and git push ...

**Comment by cshoredaniel** [comment]
Also depends on https://github.com/openwrt/packages/pull/7899 and https://github.com/openwrt/packages/pull/7900

**Comment by cshoredaniel** [comment]
Now depends on https://github.com/openwrt/packages/pull/7869 instead of  https://github.com/openwrt/packages/pull/7829

**Comment by cshoredaniel** [comment]
One last round of testing and should be good to go (mostly to make sure I didn't make any silly typos in the packaging changes or adding the trigger logic).

**Comment by cshoredaniel** [comment]
Once the dependencies are in in place it should be good to go.

**Comment by cshoredaniel** [comment]
And now this is ready!

**Comment by hnyman** [comment]
Any comments from @jefferyto  ?
Does it make sense to keep both v1 and v2 in the long run?

**Comment by jefferyto** [comment]
I don't use radicale so I don't have any thoughts (I think I was pinged because it's written in python). I've pinged other folks who have mentioned radicale v2, was hoping they would have some comments.

FWIW @chris5560 also [preferred having separate v1 and v2 packages](https://github.com/openwrt/packages/issues/5467#issuecomment-358437536).

**Comment by kedront** [comment]
Excuse the question, but how can I use the pre-built package? I am using OpenWRT 18.06.1 and opkg does not list the package. Do I have to build it myself or does it still migrate to the official package lists?

**Comment by cshoredaniel** [comment]
@kedront This was added after 18.06 release hence until 19.0x release is only available in snapshots or as a self-build with master.

**Comment by kedront** [comment]
@cshoredaniel Thank you for your answer and great work. I compiled it and it runs great on my system.
Anyway, I would recommend to upgrade python3-bcrypt too. It's not a hard dependency but really useful if you want secure hashes.
Again, thank you very much for this radicale2 build!

**Pull request merged**
