### PR TITLE
swig: bump to 3.0.12

### PR DESCRIPTION
**Pull request by nxhack**
Maintainer: @blogic 
Compile tested: ar71xx, LEDE trunk r6718-3c79bb5
 Run tested: NONE

Description:
update version to 3.0.12

#Prepare node.js v8.x support for libmraa, libupm.

Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@blogic 
Still interested on the package?
Or should @nxhack  just add himself as the second (or only) maintainer?

**Comment by nxhack** [comment]
I will take over the maintainer if @blogic want.

**Comment by hnyman** [comment]
@nxhack 
Just assume maintainership in the commit or add yourself as a second maintainer.
(blogic hasn't made changes to this package since 2015)

**Comment by nxhack** [comment]
OK, Add myself to the maintainers.

**Pull request merged**
