### PR TITLE
jsoncpp: update to version 1.9.2

### PR DESCRIPTION
**Pull request by ja-pa**
Maintainer: me
Compile tested: Turris Omnia (TOS5), OpenWrt master

Description:
This PR updates jsoncpp to version 1.9.2. It also switches build to meson build system

### CODE REVIEW

**Comment by neheb** [comment]
Note that upstream considers this version to be a pre-release.

I don't like the switch to meson. I want a compelling argument for it.

Note that CMake itself can generate meson files.

**Comment by BKPepe** [comment]
ping @ja-pa

**Comment by ja-pa** [comment]
I rebased it to master. 

And the reason why to switch to meson. I think that with bigger meson adoption it could make build time a little bit faster see https://mesonbuild.com/Simple-comparison.html
. 
I would like to update it to the new version since 1.8.4 is from 2017 and there is lots of fixes https://github.com/open-source-parsers/jsoncpp/releases/tag/1.9.0

**Comment by diizzyy** [comment]
Many major distros have already adopted 1.9.2 so that should be fine.
https://repology.org/project/jsoncpp/versions

**Pull request merged**
