### PR TITLE
wifidog-ng: Update init script

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @zhaojh329 
Compile tested: armvirt-32, 2019-02-03 snapshot sdk
Run tested: armvirt-32, 2019-02-03 snapshot

Description:
The first commit converts the init script to use tabs for indentation. (I thought separating this into its own commit would make the real init script changes easier to see.)

The second commit ("wifidog-ng: Update init script"):
This replaces the use of `uci_validate_section()` with `uci_load_validate()`, which removes the need to declare local variables for every config option.
    
This also adds a `service_triggers()` function.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I've only run-tested this with minimal changes to the default config; I can do more extensive tests if necessary.

Also, when I ran this in armvirt-32, I got this error:

    ipset v7.1: Syntax error: '4294967' is out of range 0-2147483

If I changed the timeout value to 2147483, the script appears to work correctly. I'm not familiar enough with ipset (or Linux networking, honestly :joy:) to know if this should be changed or not, so I left it as-is. (From the [ipset changelog](http://ipset.netfilter.org/changelog.html), the max timeout value may have been changed in 7.0 (kernel part).)

**Comment by jefferyto** [comment]
I decided to update the timeout value as well :joy:

**Comment by neheb** [comment]
ping @zhaojh329

**Comment by neheb** [comment]
Timeout. Merging.

**Pull request merged**
