### PR TITLE
lftp: add new mirror for old versions

### PR DESCRIPTION
**Pull request by tolbkni**

### CODE REVIEW

**Comment by jow-** [comment]
@fededim

**Comment by fededim** [comment]
Updated to 4.6.2, PR created

https://github.com/openwrt/packages/pull/1277

**Comment by fededim** [comment]
Examing the four mirrors specified on lftp website (http://lftp.yar.ru/get.html) we have:
- Japan (ftp://ftp.st.ryukoku.ac.jp/pub/network/ftp/lftp/) contains only latest 4.6.2 and old ones till version 3.2.0
- Austria (ftp://ftp.tuwien.ac.at/infosys/browsers/ftp/lftp/) contains only versions from 4.3.2 to 4.4.9
- Berlin (ftp://ftp.cs.tu-berlin.de/pub/net/ftp/lftp/) contains only latest 4.6.2
- Karlsruhe (http://lftp.cybermirror.org/) contains only versions from 4.4.9 to 4.4.15

If you have another mirror website which contains at least latest versions let me know.

**Comment by fededim** [comment]
In any case if you wish to merge the mirrors change it's fine for me, they are the official ones and maybe in future they will keep the most recent versions of lftp

**Comment by fededim** [comment]
Forget what I told before, http://lftp.yar.ru/ftp/old/ contains all versions of lftp, please merge this change.

**Pull request closed without merging**
