### PR TITLE
Dockerd: Added option to configrue docker to use host Dnsmasq for DNS

### PR DESCRIPTION
**Pull request by G-M0N3Y-2503**
Maintainer: @G-M0N3Y-2503
Compile tested: x86_x64, VirtualBox, OpenWrt Master
Run tested: x86_x64, VirtualBox, OpenWrt Master

Description:
* Added configuration option for docker to make it use the hosts `dnsmasq` for DNS queries instead of 8.8.8.8
* Made `docker` firewall zone accepts local traffic so we can access the hosts `dnsmasq` 
  (This should be fine as wan traffic is blocked by default)

### CODE REVIEW

**Comment by G-M0N3Y-2503** [comment]
FYI @feckert

**Comment by G-M0N3Y-2503** [comment]
Separated, miscellaneous maintenance changes into another PR so that they can be flushed prior to these changes.
https://github.com/openwrt/packages/pull/14816

**Comment by G-M0N3Y-2503** [comment]
Double checked everything was working after the recent influx of changes and it's all good to go :)

**Comment by feckert** [comment]
This should also got to owrt-21.02 if the issue in the ci pipline is fixed

**Pull request merged**
