### PR TITLE
watchcat: add support for running a script

### PR DESCRIPTION
**Pull request by jtkohl**
Maintainer: @roger- 
Compile tested: ipq806x, R7800, 22.03.0-rc1
Run tested: ipq40xx, MR8300, 22.03.0-rc1
recent commiters: @rozhuk-im @neheb and @nickberry17 

Description:
* added a new mode, `run_script` to run a script, with similar logic to the `restart_iface` mode.  I need this to be able to restart *only* wan6, but not wan, on the same underlying interface eth0.
* added explicit IPv4/IPv6 support for the ping
* fixed incomplete support for unlockbands configuration value
* cleaned up some logging commands

I've got corresponding luci changes in https://github.com/openwrt/luci/pull/5824

### CODE REVIEW

**Comment by nickberry17** [comment]
Hi, thanks for your contribution.  Can you please run the script through Shellcheck first, it flagged some issues

**Comment by jtkohl** [comment]
> Hi, thanks for your contribution. Can you please run the script through Shellcheck first, it flagged some issues

There are some flagged issues in both watchcat.init and watchcat.sh in the master branch.  What do you recommend for those issues...fix them too?

**Comment by kofec** [comment]
hi @jtkohl, base on https://www.shellcheck.net/
`$ shellcheck myscript
 
[Line 3:](javascript:setPosition(3, 1))
USE_PROCD=1
^-- [SC2034](https://www.shellcheck.net/wiki/SC2034) (warning): USE_PROCD appears unused. Verify use (or export if used externally).
 
[Line 5:](javascript:setPosition(5, 1))
START=97
^-- [SC2034](https://www.shellcheck.net/wiki/SC2034) (warning): START appears unused. Verify use (or export if used externally).
 
[Line 6:](javascript:setPosition(6, 1))
STOP=01
^-- [SC2034](https://www.shellcheck.net/wiki/SC2034) (warning): STOP appears unused. Verify use (or export if used externally).
 
[Line 12:](javascript:setPosition(12, 9))
        local actual
        ^-- [SC3043](https://www.shellcheck.net/wiki/SC3043) (warning): In POSIX sh, 'local' is undefined.
 
[Line 15:](javascript:setPosition(15, 9))
        new="${actual:+$actual$separator}$add"
        ^-- [SC2034](https://www.shellcheck.net/wiki/SC2034) (warning): new appears unused. Verify use (or export if used externally).
 
[Line 76:](javascript:setPosition(76, 31))
                        if [ "$mmifacename" != "" ] && [ "$period" -lt 30 ]; then
                              ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): mmifacename is referenced but not assigned.
 
[Line 102:](javascript:setPosition(102, 41))
                procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
                                        ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                 ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                                       ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([6,7,8])), apply [all SC2086](javascript:applyFixCode(2086)))
                procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
 
[Line 107:](javascript:setPosition(107, 101))
                procd_set_param command /usr/bin/watchcat.sh "ping_reboot" "$period" "$forcedelay" "$pinghosts" "$pingperiod" "$pingsize" "$addressfamily"
>>                                                                                                  ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): pinghosts is referenced but not assigned.
>>                                                                                                                             ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): pingsize is referenced but not assigned.
>>                                                                                                                                         ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): addressfamily is referenced but not assigned.
 
[Line 108:](javascript:setPosition(108, 41))
                procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
                                        ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                 ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                                       ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([12,13,14])), apply [all SC2086](javascript:applyFixCode(2086)))
                procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
 
[Line 113:](javascript:setPosition(113, 128))
                procd_set_param command /usr/bin/watchcat.sh "restart_iface" "$period" "$pinghosts" "$pingperiod" "$pingsize" "$interface" "$mmifacename" "$unlockbands" "$addressfamily"
>>                                                                                                                             ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): interface is referenced but not assigned.
>>                                                                                                                                                         ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): unlockbands is referenced but not assigned.
 
[Line 114:](javascript:setPosition(114, 41))
                procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
                                        ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                 ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                                       ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([17,18,19])), apply [all SC2086](javascript:applyFixCode(2086)))
                procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
 
[Line 120:](javascript:setPosition(120, 41))
                procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
                                        ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                 ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
>>                                                                                       ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([20,21,22])), apply [all SC2086](javascript:applyFixCode(2086)))
                procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"

$`

**Comment by jtkohl** [comment]
> > Hi, thanks for your contribution. Can you please run the script through Shellcheck first, it flagged some issues
> 
> There are some flagged issues in both watchcat.init and watchcat.sh in the master branch. What do you recommend for those issues...fix them too?

Some of them are shellcheck not understanding the variable evaluation functions like `append_string` in watchcat.init (how it defines values, how it uses eval to read variables) and other init-script-isms from /etc/rc.common

Others are shell-dialect issues: OpenWrt uses ash, I believe?  Is that similar enough to one of shellcheck's dialects to use with one of the options for -shell=<sh, bash, dash, ksh> ?

**Comment by jtkohl** [comment]
I fixed the SC2086 issues (some mine, some from before).

The others are all either wrong dialect, or shellcheck not understanding eval defining variables, use of rc.common, or use of config library to define variables picked up out of uci

**Comment by nickberry17** [comment]
Yeah, was only referring to the ones that were valid issues.  Yes OpenWrt/BusyBox uses ash.  

Please squash your fixup commit.  But before you do that, I think it may be better to split the IP Family part into its own commit; doesn't feel like it fits with the "run script" feature.  Doing so make it easier to bisect/revert in future if that is possible.

**Comment by jtkohl** [comment]
> Yeah, was only referring to the ones that were valid issues. Yes OpenWrt/BusyBox uses ash.
> 
> Please squash your fixup commit. But before you do that, I think it may be better to split the IP Family part into its own commit; doesn't feel like it fits with the "run script" feature. Doing so make it easier to bisect/revert in future if that is possible.

Do you want a separate package revision and pull request for the IP family change and for the "run script" feature?  Or just two commits on this branch/PR, and only one bump of the package revision?  There are some places where both appear together, so they're not totally independent, but I can make the "run script" depend on the IP family change.

**Comment by nickberry17** [comment]
Since they are semi-related, they can go in the same PR, we just need separate commits for the reasons I mentioned earlier.

**Comment by jtkohl** [comment]
> Since they are semi-related, they can go in the same PR, we just need separate commits for the reasons I mentioned earlier.

OK, I think I have that done (and similarly for the matching luci pull request)?

**Comment by nickberry17** [comment]
Sorry if I wasn't clear, the package version should be bumped for each commit.

**Comment by nickberry17** [comment]
Actually you could just set package version to auto release

**Comment by jtkohl** [comment]
> Actually you could just set package version to auto release

I tried that and I got a build that produced watchcat_1-4_all.ipk, instead of what I'd expect of 15 or 16 ?

**Comment by jtkohl** [comment]
> > Actually you could just set package version to auto release
> 
> I tried that and I got a build that produced watchcat_1-4_all.ipk, instead of what I'd expect of 15 or 16 ?

Any guidance @nickberry17 ?

**Comment by kofec** [comment]
@roger- Are you OK to merge these changes ?

**Comment by roger-** [comment]
+1

**Comment by jtkohl** [comment]
any chance to get this (and the luci changes that go with it) into 22.03.0 ?

**Comment by neheb** [comment]
Done

**Comment by sages** [comment]
> Done

Does this include the changes to luci-app-watchcat to allow config of the script?

**Comment by jtkohl** [comment]
> > Done
> 
> Does this include the changes to luci-app-watchcat to allow config of the script?

No, that's a separate PR that is still pending: https://github.com/openwrt/luci/pull/5824

**Comment by cowwoc** [comment]
@jtkohl @kofec It doesn't look like this bug was ever fixed: https://github.com/openwrt/packages/pull/18593#issuecomment-1192325025

Did this fall through the cracks or is another issue tracking it?

**Comment by jtkohl** [comment]
reading through the linked issue 19010, the other commits mentioned there and in another referenced issue contain the fixes.

**Comment by cowwoc** [comment]
Sorry, you are right. My issue was caused by https://github.com/openwrt/packages/issues/24253

**Pull request merged**
