### PR TITLE
ldns: Avoid perl bug for ldns

### LINKED ISSUE #2663: ldns: build error - try to install man pages
```
./libtool --tag=CC --quiet --mode=finish /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/lib
./install-sh  -d /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/bin
./install-sh  -c -m 755 packaging/ldns-config /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/bin
./install-sh  -d /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/man/man1
./install-sh  -c -m 444 ./packaging/ldns-config.1 /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/man/man1/
./install-sh  -d /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/man/man3
for f in doc/man/man3/*; do \
	./install-sh  -c -m 444 $f /home/owbuild/trunk/build_dir/target-i386_i486_musl-1.1.14/ldns-1.6.17/ipkg-install/usr/man/man3/; \
done
./install-sh: doc/man/man3/* does not exist.
Makefile:297: recipe for target 'install-manpages' failed
make[4]: *** [install-manpages] Error 1
```

### PR DESCRIPTION
**Pull request by k0ste**
Fix #2663

Signed-off-by: Konstantin Shalygin <k0ste@cn.ru>

### CODE REVIEW

**Comment by champtar** [comment]
hi @k0ste 
please follow https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
commit message should start with "ldns:" and should include signed-off-by

**Comment by champtar** [comment]
also please bump PKG_RELEASE

**Comment by k0ste** [comment]
Hello, @champtar. Check it.

**Comment by champtar** [comment]
@k0ste typo (lds)

**Comment by k0ste** [comment]
@champtar, OMG. Fixed.

**Comment by champtar** [comment]
@psycho-nico

**Comment by champtar** [comment]
merged in a4a9038

**Pull request closed without merging**
