### PR TITLE
perl-cgi: Update to 4.42

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me / @Naoir 
Compile tested: x86_64, generic, HEAD (fbe2e7d)
Run tested: same, rebuilt for production router

Description:

Update to 4.42

### CODE REVIEW

**Comment by diizzyy** [comment]
```PKG_LICENSE:=GPL Artistic-2.0``` --> ```PKG_LICENSE:=Artistic-2.0```
https://github.com/leejo/CGI.pm/blob/master/LICENSE
https://spdx.org/licenses/

Looks good otherwise :)

**Comment by pprindeville** [comment]
> `PKG_LICENSE:=GPL Artistic-2.0` --> `PKG_LICENSE:=Artistic-2.0`
> https://github.com/leejo/CGI.pm/blob/master/LICENSE
> https://spdx.org/licenses/
> 
> Looks good otherwise :)

Fixed.

**Comment by neheb** [comment]
The other URL could also use HTTPS

**Comment by pprindeville** [comment]
Hmm....

```
perl-authen-sasl/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-authen-sasl-xs/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-cgi/Makefile:PKG_LICENSE:=Artistic-2.0
perl-compress-bzip2/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-dbi/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-device-serialport/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-device-usb/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-encode-locale/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-file-listing/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-file-sharedir-install/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-html-form/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-html-parser/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-html-tagset/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-html-tree/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-http-cookies/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-http-daemon/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-http-date/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-http-message/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-http-negotiate/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-http-server-simple/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-inline-c/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-inline/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-io-html/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-lockfile-simple/Makefile:PKG_LICENSE:=GPL-2.0+ Artistic-1.0-Perl
perl-lwp-mediatypes/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl/Makefile:PKG_LICENSE_FILES:=Copying Artistic README
perl-net-http/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-net-telnet/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-parse-recdescent/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-sub-uplevel/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-test-harness/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-test-warn/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-text-csv_xs/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-uri/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-www-curl/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-www-curl/Makefile:PKG_LICENSE_FILES:=LICENSE
perl-www/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-www-mechanize/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-www-robotrules/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
perl-xml-parser/Makefile:PKG_LICENSE:=GPL-1.0+ Artistic-1.0-Perl
```

**Comment by BKPepe** [comment]
> The other URL could also use HTTPS

Yeah, the right one is https://metacpan.org/release/CGI

**Comment by pprindeville** [comment]
> > The other URL could also use HTTPS
> 
> Yeah, the right one is https://metacpan.org/release/CGI

Wow.  Tough crowd tonight.

**Comment by neheb** [comment]
Everything looks good. Merging.

**Pull request merged**
