### PR TITLE
Flask, Jinja2: update maintainer

### PR DESCRIPTION
**Pull request by autobakterie**
Maintainer: me
Compile tested: N/A
Run tested: N/A

Description:

As I will be no longer working for Turris at CZ.NIC, I'd like to update my maintainer email address.

If somebody else is willing to take over the maintainership instead, I am open to that as well. ( I guess @bkpepe or @paper42 might be interested? Speak up in that case. )

### CODE REVIEW

**Comment by paper42** [comment]
I would adopt these packages because we are using them in Turris.

**Comment by autobakterie** [comment]
Rebased, got rid of AUTORELEASE, maintainership switched to @paper42.

**Review by BKPepe — APPROVED** [review]

**Comment by BKPepe** [comment]
Formality check is failing due to this issue:
``Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Šimon Bořek <simon.borek@nic.cz>')``

**Comment by commodo** [comment]
`pyproject.toml` is now supported by the build-system;

so, these packages can be updated (if desired)

**Comment by autobakterie** [comment]
Signoff updated to please the formality check. Rebased on current master.

**Comment by BKPepe** [comment]
Thank you. :)

**Pull request merged**
