### PR TITLE
[WIP] kadnode: Update to version 2.4.0

### PR DESCRIPTION
**Pull request by mwarning**
* add support for mbedtls 3.0.0
* fix newline in init script

Maintainer: me
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by mwarning** [comment]
The failing pipelines show `/builder/staging_dir/host/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /builder/staging_dir/host/lib/libfakeroot.so)` - is that a known issue?

**Comment by neheb** [comment]
> The failing pipelines show `/builder/staging_dir/host/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /builder/staging_dir/host/lib/libfakeroot.so)` - is that a known issue?

that sounds like the SDK is built by Debian 10 or 11 whereas the CI uses Ubuntu 24.04.

**Comment by neheb** [comment]
I recommend switching to local tarballs instead of codeload.

**Comment by mwarning** [comment]
I have changed to a git checkout. But the error remains the same. No idea..

**Comment by mwarning** [comment]
o.O

**Pull request merged**
