### PR TITLE
clamav: update to 0.103.1

### PR DESCRIPTION
**Pull request by neheb**
Convert to using CMake in order to speed up compilation and to fix
compilation under glibc.

Signed-off-by: Rosen Penev <rosenp@gmail.com>
 
Maintainer: @lucize 
Compile tested: arc700

### CODE REVIEW

**Comment by neheb** [comment]
Seems I'll need to patch the CMake file to work with musl-fts...

**Comment by neheb** [comment]
Finally got it building. With gettext-full too.

**Comment by neheb** [comment]
That failure looks bogus...

**Comment by neheb** [comment]
@lucize all green now.

**Comment by lucize** [comment]
LGTM

**Pull request merged**
