### PR TITLE
remove inactive maintainer emails

### PR DESCRIPTION
**Pull request by damirsamardzic**
Description: remove inactive maintainer emails

### CODE REVIEW

**Comment by champtar** [comment]
@lperkov are you mixing accounts ?
Also I see that they are / were in the same company as you, but could they just confirm they are fine with the removal ?

**Review by ratkaj — CHANGES_REQUESTED** [review]
Change marko.ratkaj@sartura.hr to markoratkaj@gmail.com and add your email as a second maintainer. I do not give permission to remove my email.

**Comment by ratkaj** [comment]
@damirsamardzic I updated my email on all packages I maintain. Please rebase to latest master to remove other inactive maintainers. Thanks.

**Comment by BKPepe** [comment]
Closing. This needs to be rebased and discussed with @ratkaj

**Pull request closed without merging**
