### PR TITLE
lxc: Use more FSH compliant /srv/lxc instead of new root dir

### PR DESCRIPTION
**Pull request by miska**
Normally LXC uses /var/lib, but due to hack OpenWRT employs this is not an
option. But instead of introducing new top-level directory, FSH compatible /srv
can be used.

Signed-off-by: Michal Hrusecky <michal.hrusecky@nic.cz>

### CODE REVIEW

**Comment by hnyman** [comment]
You should increase PKG_RELEASE

cc to maintainer: @lperkov

**Comment by miska** [comment]
Fixed commit to bump release number

**Comment by lperkov** [comment]
Do the rpcd-mod-lxc and the LuCI LXC packages need to be updated too due to this change?

**Comment by miska** [comment]
rpcd-mod-lxc not, LuCI yes, updated just now.

**Pull request merged**
