### PR TITLE
kernel/exfat-nofuse: Update to 1.2.24

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @br101 
Compile tested: mvebu, Linksys WRT3200ACM, LEDE trunk
Run tested: mvebu, Linksys WRT3200ACM, LEDE trunk

Description:
Switch repo to one that has updated to 1.2.24

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by br101** [comment]
Hi! Just a question: Why the "coolshou" instead of "dorimanx" repository? The latter also has updates for Kernel 4.11 and seems to be maintained...

**Comment by diizzyy** [comment]
It's based on the dorimanx tree as far as I can tell and includes the 4.11 patches
https://github.com/coolshou/exfat/commits/master

**Comment by br101** [comment]
So the question is still why is the "coolshou" version better, apart from having a version tag? I considered "dorimanx" to be the main repo...

**Comment by br101** [comment]
BTW would you be willing to maintain the package? I don't use it any more...

**Comment by diizzyy** [comment]
It contains the latest upstream code from Samsung while the dorimanx repo uses the rather old 1.2.6 version. I'm willing to switch back once this is imported.

**Comment by diizzyy** [comment]
Hmm.. found some regressions...

**Comment by diizzyy** [comment]
Close this as we have regressions...

**Pull request closed without merging**
