### PR TITLE
Backport "xtables-addons: Support IPTV Timeshift" to openwrt-19.07 branch

### PR DESCRIPTION
**Pull request by jgora**
Solves Issue #10373 and PR #10428

Signed-off-by: Jose Olivera <oliverajeo@gmail.com>
(bumped PKG_RELEASE)
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by jgora** [comment]
This PR is about issue https://github.com/openwrt/packages/issues/13769

**Comment by neheb** [comment]
Requires a PKG_RELEASE bump.

**Comment by neheb** [comment]
ping @jow-

**Comment by jgora** [comment]
@neheb, increase the PKG_RELEASE broke the build.

**Comment by neheb** [comment]
```
Author name (jgora) need to be your real name 'firstname lastname'
Commit subject line MUST start with '<package name>: ' (PKG_RELEASE bump)
```

**Comment by jgora** [comment]
Discardes

**Pull request closed without merging**
