### PR TITLE
Update libdmapsharing and dmapd

### PR DESCRIPTION
**Pull request by MikePetullo**
Maintainer: me
Compile tested: x86, x86_64, OpenWrt 96288dc1
Run tested: x86, x86_64, OpenWrt 96288dc1

Description:
Update libdmapsharing and dmapd. The dmapd update depends on the libdmapsharing update due to an API change.

### CODE REVIEW

**Comment by diizzyy** [comment]
@MikePetullo 
dmapd fails, can you have a look at it?

**Comment by MikePetullo** [comment]
@diizzyy, silly question: where can I find the output of a build with V=s? The continuous integration build does not seem to use the verbose flag, so it is hard to diagnose.

**Comment by diizzyy** [comment]
Unfortunately you can't, you need to build it yourself on a mips platform.

**Comment by MikePetullo** [comment]
@diizzyy, I found that the packages would not compile locally unless I manually selected a number of GStreamer plugin packages. (I had selected these packages during my first compile test.) The trouble was due to some incorrect DEPEND statements. I made some adjustments, and the packages now build locally. However, the CI still build fails.

I did find that the build consumed all of the flash space on the default AR7xxx subtarget. Selecting MikroTik RouterBoard with >= 128 MB flash allowed the build to complete. I does not seem that the CI build is failing due to lack of flash space.

**Comment by MikePetullo** [comment]
@diizzyy, can we merge this? I think fixing issue #6045 is beyond the scope of this merge request.

**Pull request merged**
