### PR TITLE
Drop maintainership

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: me

### CODE REVIEW

**Comment by champtar** [comment]
@stintel thanks for all the work, if you know some users could you ping them ?
@ammubhave @dwmw2 are you still interested in domoticz / want to become maintainer ?
@ratkaj are you still interested in openzware / want to become maintainer ?

**Comment by neheb** [comment]
Doesn't this require a PKG_RELEASE bump? I think changing the maintainer changes the ipk.

**Comment by hnyman** [comment]
It doesn't change the functionality or packaged in binaries or config files.  Just a metadata change.
Not need to bump, I think.

**Comment by diizzyy** [comment]
No need to bump PKG_RELEASE as mentioned above

**Comment by dwmw2** [comment]
I'll take then; I'm using Domoticz and OpenZwave on OpenWRT in my production home automation system.

**Comment by neheb** [comment]
Going to merge.

@dwmw2 please open a new PR adding yourself as the maintainer.

**Pull request merged**
