### PR TITLE
ddns-scripts: Add do.de as ddns provider

### PR DESCRIPTION
**Pull request by TobleMiner**
Maintainer: @chris5560
Run tested: x86_64/PC/OpenWrt master, updates both ipv4 and ipv6 fine

Description:
Add support for do.de dyndns

Signed-off-by: Tobias Schramm <tobleminer@gmail.com>

### CODE REVIEW

**Comment by chris5560** [comment]
Which response does do.de send on success ?

**Comment by TobleMiner** [comment]
The responses are listed at [do.de wiki](https://www.do.de/wiki/FlexDNS_-_Entwickler). It returns 200 OK containing

> good $ipaddress

It is just the standard dyndns protocol.

**Comment by chris5560** [comment]
What is the answer, if transfer ok but no change happen ?
Default answers are "good <IP>" or "nochg <IP>"
If do.de answer this way please append "good|nochg" like on other services inside services files.
If they only answer "good <IP>" then please append "good".
Many Thanks

**Comment by TobleMiner** [comment]
Sorry, my bad. Should be ok now

**Comment by chris5560** [comment]
OK for me to merge
Many thanks

**Pull request merged**
