### PR TITLE
minidlna: update to version 1.2.1

### PR DESCRIPTION
**Pull request by jcadduono**
1.2.1 - Released 24-Aug-2017
--------------------------------
- Added Movian client detection and subtitle support.
- Fixed an issue with discovery on non-Linux systems.
- Fixed Bonjour discovery compatibility with TiVo Bolt.
- Fixed NFO file parsing, and added change monitoring support for them.
- Added a workaround for video thumbnails on some Samsung clients.
- Added DoS protection for event subscriptions.
- Fixed content browsing issues with some Samsung TVs.
- Improved non-destructive update scan support.

Signed-off-by: James Christopher Adduono <jc@adduono.com>

-------------------------------

Maintainer: @medaved 
Compile tested: armhf, R7800, LEDE 4904, LEDE GCC 5.4 and 7.2.0
Run tested: Streaming videos, music, pictures - pass

Description: above

### CODE REVIEW

**Comment by luizluca** [comment]
@medaved is the maintainer

**Comment by diizzyy** [comment]
LGTM

**Comment by antonlacon** [comment]
LGTM

**Comment by thess** [comment]
Another candidate for a Travis exception list?

**Pull request merged**
