### PR TITLE
vnstat: Allow define number of tries of downloading from remote

### PR DESCRIPTION
**Pull request by kubco2**
-------------------------------

Maintainer: Jo-Philipp Wich <jo@mein.io>

Description:

Implemented uci option 'remote_tries' in vnstat config file,
which allow variable timeout before it give up and
start statistics from zero.

Signed-off-by: Jakub Janco <kubco2@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@jow- 
any objections for this?
The change looks harmless

( @kubco2  it has currently conflict due to vnstat upgrade )

**Comment by kubco2** [comment]
problem that I have with high number is that procd complete takes a lot of time(e.g. 5minutes), and it wont reboot until procd complete.

**Comment by hauke** [comment]
Please rebase to fix the conflict

**Comment by champtar** [comment]
@jow- please review

**Comment by diizzyy** [comment]
Doesn't seem to be in vnstat anymore?

**Comment by diizzyy** [comment]
@hnyman @thess 
Close due to submitter timeout

**Pull request closed without merging**
