### PR TITLE
sendmail: disable libnsl.so search

### PR DESCRIPTION
**Pull request by uxgood**
Openwrt has no libnsl.so library, which causes the linker to not find
-lnsl

Signed-off-by: Guo Li <uxgood.org@gmail.com>

Maintainer: @val-kulkov 
Compile tested: x86_64, r8001-067e2f5
Run tested: x86_64, r8001-067e2f5
Description:

### CODE REVIEW

**Comment by val-kulkov** [comment]
Compile tested on bcm53xx, r7862-ae9c310. No problems found.

**Comment by uxgood** [comment]
@val-kulkov did you mean this pr is good or is not need？

**Comment by val-kulkov** [comment]
If this change fixes compilation issue on x86_64, it is good. I never tried cross-compiling sendmail for OpenWrt on x86_64, and therefore never experienced this issue. It seems that the proposed change does not break compilation for other targets, at least for bcm53xx, so I think this PR is good to go.

**Comment by yousong** [comment]
@uxgood Can you elaborate more about the said issue?  Because the OpenWrt buildbot says it builds the package for x86_64 just fine without this patch.  https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libmilter-sendmail_8.15.2-1_x86_64.ipk

**Comment by uxgood** [comment]
[compile.txt](https://github.com/openwrt/packages/files/2359288/compile.txt)
@yousong I don't know what's wrong. In my build environment, sendmail always asks for a link to libnsl.
I can't understand the build system of sendmail very well. I don't know how it detects nsl. There is no log left yet.
I will do a clean build, I hope it is a problem with my workspace.

**Comment by yousong** [comment]
Can you check whether you have libnsl installed on your build machine?  Looks like `confLIBSEARCHPATH` defaults to `/lib /usr/lib /usr/shlib` and the search is an plain file existence one.  We will need to override the search path.

**Comment by uxgood** [comment]
yes, my build machine has libnsl.so.
CenOS 7 x86_64, only openwrt need packages installed

[compile@localhost openwrt]$ rpm -q --whatprovides /usr/lib64/libnsl.so
glibc-devel-2.17-222.el7.x86_64

package list:

coreutils
bash
which

make
gcc
gcc-c++
glibc-devel
binutils
patch

git-core

ncurses-devel
zlib-devel
zlib-static

time
file
tar
gzip
bzip2
unzip
wget
gawk
findutils
diffutils
grep
xz

#gettext
#texinfo
#subversion
#asciidoc

perl
perl-Thread-Queue
perl-Data-Dumper
perl-Switch
python

# clamav softethervpn/host 
openssl-devel

# apcupsd
mailx

# apcupsd
sysvinit-tools

# kbr5
libcom_err-devel

# luajit
glibc-devel.i686
libgcc.i686

# grilo
perl-XML-Parser

# classpath
java-1.7.0-openjdk-devel

# loudmouth
gtk-doc

# rxtx
java-1.7.0-openjdk

# ...
vim-enhanced
ctags
cscope
hostname
git-email
git-svn
git-extras
git-tools

**Comment by yousong** [comment]
@uxgood can you please patch `confLIBSEARCHPATH` to search `staging_dir/` and see if it works for you?

**Comment by uxgood** [comment]
@yousong ok，let me try.

**Comment by yousong** [comment]
@uxgood , please do, also keep the change of removing libnsl from `confLIBSEARCH`.  Thank you.

**Comment by uxgood** [comment]
@yousong is this ok?

**Comment by yousong** [comment]
Thank you.

**Pull request merged**
