### PR TITLE
openvswitch: upgrade to version 2.3.90

### PR DESCRIPTION
**Pull request by emabo**
Openvswitch upgraded to version 2.3.90.
Some patches were removed because already present in new code.
Other two patches were switched in order to remove a warning when applying them.

### CODE REVIEW

**Comment by sbyx** [comment]
@commodo

**Comment by commodo** [comment]
@emabo 
[ a bit curious ]
Are you needing/using OVS newer than version 2.3.1 ?
This is mostly for me, to get an idea of OVS usage in OpenWRT.

As far as releases go with OVS, the latest stable LTS is 2.3.1, according to the official page:
http://openvswitch.org/download/

There's also a tendency in OpenWRT to upgrade to more recent kernels, and OVS is somewhat lagging behind, because they're also trying to be compatible with pre-3.0 kernels (damned CentOS 5 & 6 have pretty old kernels).

OpenWRT's tendency to move forward fast (with kernel versions) is one reason I'd agree with this change.
I'd have to test this first, so I'll come back with more later.

But a few notes before:
- please increment PKG_RELEASE
- you'd need to also include LINUX_3_18; while at it, maybe
 - create a variable `SUPPORTED_KERNELS:=LINUX_3_8||LINUX_3_10||LINUX_3_13||LINUX_3_14||LINUX_3_18`
 - put this in all DEPENDS in the Makefile where LINUX_X_XX is present; something like `DEPENDS:=@(SUPPORTED_KERNELS)`
- As I recall (I've tried the latest OVS recently) the lib files are renamed to version 1.0.0 ? Is this the case in your situation too ? I'd prefer if possible to have lib files versioned the same as in the Makefile to prevent confusion. I did notice that you changed 
```
-	$(CP) $(PKG_BUILD_DIR)/lib/.libs/libsflow-$(PKG_VERSION).so  $(1)/usr/lib/
-	$(CP) $(PKG_BUILD_DIR)/lib/.libs/libopenvswitch-$(PKG_VERSION).so  $(1)/usr/lib/
-	$(CP) $(PKG_BUILD_DIR)/ofproto/.libs/libofproto-$(PKG_VERSION).so  $(1)/usr/lib/
-	$(CP) $(PKG_BUILD_DIR)/ovsdb/.libs/libovsdb-$(PKG_VERSION).so  $(1)/usr/lib/
```
to 
```
+	$(CP) $(PKG_BUILD_DIR)/lib/.libs/libsflow.so*  $(1)/usr/lib/
+	$(CP) $(PKG_BUILD_DIR)/lib/.libs/libopenvswitch.so*  $(1)/usr/lib/
+	$(CP) $(PKG_BUILD_DIR)/ofproto/.libs/libofproto.so*  $(1)/usr/lib/
+	$(CP) $(PKG_BUILD_DIR)/ovsdb/.libs/libovsdb.so* $(1)/usr/lib/```
```
As long as the version suffix is 2.3.90, I'm fine with this change; if not, we'd need to invest in fixing this. I'll  also take a look to fix this if needed.

Thanks :)

**Comment by sbyx** [comment]
A few noted:
All kernels except 3.18 and 4.0 have been dropped for CC.
Usually PKG_RELEASE is reset to 1 whenever the package version is updated. The main reason for this field is to reflect changes in the packaging or after adding a patch without the upstream version changing.

**Comment by commodo** [comment]
About the kernel versions: I did note that they were dropped.
Maybe I should try to do a  `if (KERNEL <= 3.18) build/include-in-build`

**Comment by emabo** [comment]
I try to give you a feedback on your notes:
-Are you needing/using OVS newer than version 2.3.1? yes, I needed a couple of patches that weren't present in last official release, so I found more natural to upgrade the release instead of porting the patches.
-As far as releases go with OVS, the latest stable LTS is 2.3.1: yes, probably you're right the best thing is to follow the LTS. The decision is up to you. Anyway, we can prepare the patch for the next release.
About the notes, I updated the patch.
About the lib version: yes, latest OVS changed version numbering, so now they are numbered as 1.0.0. The simplest way I found was changing the CP command lines.

**Comment by commodo** [comment]
Regarding the 
```
+   $(CP) $(PKG_BUILD_DIR)/lib/.libs/libsflow.so*  $(1)/usr/lib/
+   $(CP) $(PKG_BUILD_DIR)/lib/.libs/libopenvswitch.so*  $(1)/usr/lib/
+   $(CP) $(PKG_BUILD_DIR)/ofproto/.libs/libofproto.so*  $(1)/usr/lib/
+   $(CP) $(PKG_BUILD_DIR)/ovsdb/.libs/libovsdb.so* $(1)/usr/lib/```
```

That seems fine.
I've looked through the commits and it seems that this was a intended change that they did, so this is good.

**Comment by sbyx** [comment]
@commodo aside for the SUPPORTED_KERNELS is this ok with you?

**Comment by commodo** [comment]
@sbyx I would still like to add support for older 3.x kernels down to 3.10 (if it's ok with you).
Something like:
```
SUPPORTED_LINUX_3:=10 11 12 13 14 15 16 17 18
SUPPORTED_KERNELS:=$(subst $(space),$(empty),$(foreach v,$(SUPPORTED_LINUX_3),LINUX_3_$(v)||))LINUX_4_0
```

Currently testing this approach.

Reason is (bit selfish): we're running an older kernel version with OpenWRT, and until we manage to upgrade, I'd like this to be in there, and we can probably chip out versions in time.
As I see things, there people are running not the latest versions of OpenWRT, and consequently some older kernel versions, and they sync their packages against this repo.
`packages` seems a bit decoupled from `openwrt`;

allow me 10-20 minutes to come back with a final result

**Comment by sbyx** [comment]
Take all the time you need, i was just asking if you liked to have this merged. Can surely merge this later this week or next ;)

**Comment by commodo** [comment]
To conclude:
- changing `@(SUPPORTED_KERNELS)` to `@($(SUPPORTED_KERNELS))` is required
- changing `SUPPORTED_KERNELS:=LINUX_3_18||LINUX_4_0` to 
```
SUPPORTED_LINUX_3:=10 11 12 13 14 15 16 17 18
SUPPORTED_KERNELS:=$(subst $(space),$(empty),$(foreach v,$(SUPPORTED_LINUX_3),LINUX_3_$(v)||))LINUX_4_0
```
is optional
- rest is fine for merging

Thanks :)

**Comment by haizeiwang507** [comment]
@commodo :
          my Openvswitch have upgraded to version 2.3.90 in OpenWRT.  That compile and install Openvswitch to router is no problem . I start Openvswitch with command "/etc/init.d/openvswitch start", everything is also okay. But when I reboot the router, the router can't work normal anymore, I can't telnet router anyway and no wireless signal ,  Except update router's  fireware in u-boot.  
           In my OpenWRT , linux kernel's version is 3.18.36, GCC's version is 5.3.1. The router is TP-LINK Archer C7.  I just use OpenWRT: Chaos Calmer 15.05.1 , and do not know where is wrong , Can you help me ? 
Thanks.

**Comment by commodo** [comment]
@haizeiwang507 
what does your logread output say ?

or maybe if you filter it by ` logread | grep -i ovs`

**Comment by haizeiwang507** [comment]
@commodo 
     Thanks for your help. I‘m sorry to you , the openvswitch is okay, It's just some problem about ovs configure while I delet br-lan and add bro with "ovs", 
     When I delet br-lan'interface"eth1" ("eth1" is wireless network card of lan in my router), and add "eth1" to "br0" . When I reboot the router, the router can't connect normal anymore.
     Here is configure file:
"
#!/bin/sh
#make sure your ap openvswitch is start.if not,start manully
echo "openvswitch start..."
/etc/init.d/openvswitch start
echo "openvswitch end..."

#clean env
ovs-vsctl del-br br0
#delete the old bridge
#ifconfig br-lan down
#brctl delbr br-lan

#instantiate OpenvSwitch
ovs-vsctl add-br br0
ifconfig br-lan 0.0.0.0
ifconfig br0 192.168.1.1 netmask 255.255.255.0 up

brctl delif br-lan eth1
ovs-vsctl add-port br0 eth1
#ovs-vsctl set-controller br0 tcp:192.168.1.8:6633  
#ovs-vsctl add-port br0 br-lan
"
      And there is Amazing thing,  when I bridge br-lan to br0 with command"ovs-vsctl add-port br0 br-lan", Is there anything I have ignored?  this configure is ok when I used openvswith-2.3.0 some time ago.
      Thanks. Best wishes to you！

**Comment by commodo** [comment]
i remembered that OVS does not work well with Linux bridges ; it's either OVS or Linux bridges, but not both

maybe try to use OVS instead of Linux bridges
OVS should be able to do everything that Linux bridges can do, and more

**Comment by haizeiwang507** [comment]
just like you say , I want only use OVS, but when I delet br-lan and  bridge "eth1" to br0 (br0 creat by OVS), When I reboot router, I can't connect it anymore.

**Comment by commodo** [comment]
no ; i mean, you need to remove the kernel module for Linux bridges
see example:  `https://github.com/openvswitch/ovs/blob/master/utilities/ovs-ctl.in`

so, something like:  `rmmod bridge`
ideally, your build should not have the kernel module for Linux bridges at all, if using OVS

regarding your configure script:
`ifconfig br-lan 0.0.0.0`  is weird; maybe you could just do   `ifconfig br-lan up` ; setting the 0.0.0.0 IP addr to a bridge seems weird ; 

maybe I should upgrade OVS 2.3.90 to 2.4 in OpenWrt CC

if your configure script worked in OVS version 2.3, it does not mean it may work in newer versions
OVS seems to change a lot from one version to another ; the latest released version is 2.6.1 ; and I have a few problems with that

maybe you could try to rework your configure script from scratch to fit the newer OVS version

**Pull request merged**
