### PR TITLE
tvheadend: update to latest master

### PR DESCRIPTION
**Pull request by neheb**
Removed PKG_VERSION for compatibility with apk.

Maintainer: @m95d

### CODE REVIEW

**Comment by M95D** [comment]
I see this also includes a version update. Please write it in the commit mesage.
Did you test this new version?

**Comment by neheb** [comment]
No

**Comment by M95D** [comment]
Tested. It won't even build.
```
make[2]: Entering directory '/build/openwrt.pkg/multimedia/tvheadend'
touch -r /build/openwrtb/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/tvheadend-2024.08.12~adef81b8/.built /build/openwrtb/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/tvheadend-2024.08.12~adef81b8/.autoremove 2>/dev/null >/dev/null
make[2]: [Makefile:255: compile] Error 1 (ignored)
find /build/openwrtb/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/tvheadend-2024.08.12~adef81b8 -mindepth 1 -maxdepth 1 -not '(' -type f -and -name '.*' -and -size 0 ')' -and -not -name '.pkgdir'  -print0 | xargs -r -0 rm -rf
find: '/build/openwrtb/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/tvheadend-2024.08.12~adef81b8': No such file or directory
make[2]: Leaving directory '/build/openwrt.pkg/multimedia/tvheadend'
time: package/feeds/packages/tvheadend/compile#0.41#0.09#0.45
```
This is the complete build log generated as `logs/package/feeds/packages/tvheadend/compile.txt`

**Comment by neheb** [comment]
weird given that CI and locally there's no such error.

**Comment by M95D** [comment]
OK, it's working now. Tested with DVB-C and everything appears to be fine.

Someone shoud take a look at that cleanup command. It shoudn't fail if the dir doesn't exist, but create it instead. This isn't the first time I've seen a build fail with missing dir/path errors. It mostly happens with binutils after a `make dirclean` or `git clean -dxf`.

**Review by M95D — APPROVED** [review]

**Pull request merged**
