### PR TITLE
runc/containerd: Fix incomplete cleanup in Build/InstallDev

### PR DESCRIPTION
**Pull request by tete1030**
Maintainer:  @G-M0N3Y-2503 
Compile tested: x86_64, OpenWrt master
Run tested: x86_64, OpenWrt master

Description:
Currently it only cleans up binaries when executing `Build/InstallDev` without deleting .built stamp file.

This leads to wrong information about existence of built runc/containerd binaries and causes error when executing `package/{runc,containerd}/install` twice.

Related PR/Issues (in Chinese): 
* coolsnowwolf/packages#34 (PR)
* coolsnowwolf/lede#3222
* coolsnowwolf/lede#3282
* coolsnowwolf/lede#3213
* coolsnowwolf/lede#1759

### CODE REVIEW

**Comment by tete1030** [comment]
Thanks. changed it

**Comment by jefferyto** [comment]
There are reports that this change causes errors:

* https://forum.openwrt.org/t/runc-and-containerd-compilation-fails/60572
* https://github.com/openwrt/packages/issues/12793#issuecomment-658738040

I haven't looked into this issue/change enough to know what is going on or how it should be fixed, just wanted to point it out here.

**Comment by tete1030** [comment]
Hi @jefferyto, thanks! I'll look into this and try to fix it ASAP

**Comment by jefferyto** [comment]
Looking a little closer, I'm not sure doing `$(call Build/Compile/Default,clean)` inside `Build/InstallDev` is safe... I'm pretty sure no one expects a clean to happen here. I would suggest deleting the binaries from `$(1)` after `$(call GoPackage/Build/InstallDev,$(1))` instead.

But actually, I'm not sure having a `Build/InstallDev` for these packages is necessary... The original intention was to have Go library packages (e.g. golang.org/x/text) that only contains source code, and Go program packages that (build-)depend on these library packages. The library packages would install their source code with `Build/InstallDev` to be used by programs packages during build.

(With Go programs using modules or vendoring their dependencies, this system has become mostly unnecessary.)

I don't know enough about how the docker packages here are built or how they depend on each other, so maybe the source code is still necessary. If not, then just having `Build/InstallDev:=:` would undo the `Build/InstallDev` set by golang-package.mk.

Or you could just keep the binaries installed in `Build/InstallDev`; I don't see what negative effect this would have.

**Comment by tete1030** [comment]
I agree that `$(call Build/Compile/Default,clean)` is not appropriate. However forgive me I am not able to give a fix for this currently since I am not very familiar with the role `Build/InstallDev` plays here. It would be better if @G-M0N3Y-2503 can look at this problem.

**Comment by G-M0N3Y-2503** [comment]
I recall docker-ce having some strange vendoring that made this necessary but don't recall much more than that.
But It's quite possible that things have progressed since so it's might not be necessary anymore. I did a brief test without defining `Build/InstallDev` and it seemed to work but I'm not sure of the ramifications... it'll need further investigation/testing.

So it's clear, the current issue is that containerd/runc won't compile on aarch64? or subsequent builds after a clean build?

**Comment by tete1030** [comment]
The original issue for this PR is an install error in subsequent build
```
install -m0755 /home/openwrt/master/openwrt/build_dir/target-x86_64_musl/runc-1.0.0-rc8+91-3e425f80/.go_work/build/src/github.com/opencontainers/runc/runc /home/bang/lede/build_dir/target-x86_64_musl/runc-1.0.0-rc8+91-3e425f80/ipkg-x86_64/runc/usr/sbin/
install: cannot stat '/home/openwrt/master/openwrt/build_dir/target-x86_64_musl/runc-1.0.0-rc8+91-3e425f80/.go_work/build/src/github.com/opencontainers/runc/runc': No such file or directory
```
Basically, it cannot find a bin file to install. It was due to that our bin file has already been cleaned up but the stamp file incorrectly indicated its existence. So in my PR I deleted the stamp file to make sure this package to be rebuilt in subsequent builds.

Current problem in both links is
```
make: *** /home/openwrt/master/openwrt/build_dir/target-x86_64_musl/runc-1.0.0-rc10/.go_work/build/src/github.com/opencontainers/runc: No such file or directory.  Stop.
make[3]: *** [/home/openwrt/master/openwrt/build_dir/target-x86_64_musl/runc-1.0.0-rc10/.built] Error 2
```
It seems now it's the folder `runc` that went missing, not bin file. They found reverting this PR works for them, but they didn't mention if they were doing clean build. I'm not sure how deleting a stamp file causes its missing and I have never encounter their problem during both subsequent and clean builds.

**Comment by alex9434** [comment]
Dear @G-M0N3Y-2503,

I have the issue with runc and containerd on arm64. The build system stops with the error:
` No such file or directory.  Stop.`
I am using the master from today. 

In the openwrt forum several users seem to have the same issue: 

https://forum.openwrt.org/t/runc-and-containerd-compilation-fails/60572

The proposed solution in that forum to comment out in both Makefiles
`#rm -f $(STAMP_BUILT)`
solved the problem for me. Is this a solution that you would like to include in master?

**Comment by tete1030** [comment]
Hi @alex9434 , are you having this problem in a clean build or a subsequent build (without `make clean` before compiling) ?

**Comment by alex9434** [comment]
Hi @tete1030, I had an error in the build using -j5. I then re-started the build process (without make clean) with -j1 V=sc to see the details. This is when I saw the error. So technically the error on the clean build could have been something else.

**Comment by G-M0N3Y-2503** [comment]
@alex9434 I'm having a look into refactoring these Makefiles as Jeffery suggested so it's more maintainable

**Comment by G-M0N3Y-2503** [comment]
Theoretically, this should allow you to find the initial error, but  I wasn't able to reproduce your scenario so I'd appreciate if someone could verify.
https://github.com/openwrt/packages/pull/12967

**Pull request merged**
