### PR TITLE
gerbera: add

### PR DESCRIPTION
**Pull request by neheb**
This is a proper replacement for MiniDLNA with none of its problems.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Took the package from entware and ported it here.

Posting it here to get feedback. I haven't gotten much of an opportunity to test this.

The Turris people will probably be interested in this. MiniDLNA has been a pain point there, at least according to the forums.

I have theories as to why, but no real desire or time to investigate.

### CODE REVIEW

**Comment by TimelessNL** [comment]
I've compiled your makefile and run-tested on a NanoPi NEO2, everything seems to work.
Just one side node, why did you chose to use `gerbera.init` instead of `gerbera` for your `procd `script?

**Comment by neheb** [comment]
The .init is a mistake. Will fix.

The database is included with file, not libmagic. Will fix.

**Comment by TimelessNL** [comment]
I've installed `file` and that fixed the magic error. So I think `file` should also be a dependency together with `libmagic`.

**Comment by neheb** [comment]
Fixed both issues. Should work now.

**Comment by TimelessNL** [comment]
Great! I've been testing gerbera some more and it seems to run stable on my NEO2. It even supports livestreaming over DLNA from my tvheadend instance, which MiniDLNA didn't.

One last note, it seems Gerbera does not create its own `/etc/gerbera` directory and therefor is unable to create its initial `config.xml`. Maybe we have to create that folder during install?

**Comment by neheb** [comment]
Note the postinst message. gerbera --create-config > /etc/gerbera/config.xml will do just that.

**Comment by TimelessNL** [comment]
Yeah indeed. And since this is a config file I think if would be nice to have it backed up during sysupgrade using:
```
define Package/gerbera/conffiles
/etc/gerbera/config.xml
```
Only unfortunate is that the default gerbera config puts it's database out of the `etc/gerbera` folder. It would be nice to have it included as well but I have no idea how, we can either include a specific OpenWrt config here which we have to maintain, alert the user to change the path or use some `sed` magic in postinstall. What do you think?

**Comment by neheb** [comment]
The proper way to do it would be to add a UCI config, similar to current MiniDLNA.

Having the config in /etc/gerbera is not ideal since we're writing to flash. MiniDLNA currently writes to /tmp by default.

Writing an init script will take a while. I don't have much time to test.

**Comment by TimelessNL** [comment]
That's correct. But MiniDLNA initializes its database on startup based on its configuration.

I tried to add a folder in config.xml and sometimes Gerbera starts to index the folder and other times it doesn't.

And still if you have a large media collection it can take a while before MiniDLNA and now Gerbera found them all and the load on the CPU is very high the entire time. I think the flashwrites is minimal since it only happens if a media file is removed or added.

If I look at other packages nginx/samba/monit they also store their config files without uci. Samba is even more special it's partly integrated in uci but users are still added using smbadd and stored separately.

**Comment by neheb** [comment]
Sounds like what I've experienced as well. The Turris people use ARM stuff, which should be able to handle gerbera decently.

**Comment by TimelessNL** [comment]
Yeah me to. My NEO2 handles MiniDLNA and Gerbera fine. And if the SD card breaks it's easily replaceable.

**Comment by neheb** [comment]
Sure.

In other news, I found that this doesn't compile with libcxx...

**Comment by TimelessNL** [comment]
Sorry, can you enlighten that a bit? Are you compiling using macOS and thus libc++?

**Comment by neheb** [comment]
No, OpenWrt. It's a non-default option.

Current Makefile uses libstdcpp which works.

**Comment by TimelessNL** [comment]
Libstdcpp is still commonly used on linux. Why do you need libcpp for exactly?

**Comment by neheb** [comment]
libcpp is smaller than libstdcpp. I added it to the tree as several C++ packages can have a smaller size with it.

There are two remaining issues preventing it from being so. One is that is needs to be linked to libssp for several platforms and the other being that it needs a C++ ABI library. I haven't been able to get libcxxabi ported here. Needs a host build or something.

**Comment by TimelessNL** [comment]
Ah ok thank's for the explanation. I noticed that you opened an issue in the Gerbera repo about this.

**Comment by neheb** [comment]
Yeah won't be fixed sounds like. That codepath is gone with the new version which is almost RC. It shouldn't have that problem there.

**Comment by TimelessNL** [comment]
Do you want to wait with this merge request until 1.5.0 is out? Or is the current state merge able?

**Comment by neheb** [comment]
I've been meaning to test out gerbera on malta first.

I assume everything is fine on your end?

**Comment by TimelessNL** [comment]
Yeah I've been testing Gerbera for a couple of days now (even with livetv from tvheadend) and it works great.

I did some investigation on Gerbera a while back, but since at the time libupnp did not support custom headers and thus my Samsung TVs did not work I stopped using it. But these are now mostly resolved and it works great.

**Comment by neheb** [comment]
Hmm? didn't I add that?

**Comment by TimelessNL** [comment]
Oh... yeah you did. Didn't notice it last time I checked :see_no_evil: 

So yeah. Then everything is fine by me  :+1:

**Comment by neheb** [comment]
Turns out that build failure is not with libcxx but with glibc...

Looks like I'll need to fix it first.

**Comment by neheb** [comment]
```
root@OpenWrt:/# gerbera --help
terminate called after throwing an instance of 'cxxopts::invalid_option_format_error'
  what():  Invalid option format ‘compile-info’
Aborted
```

hahaha.

**Comment by neheb** [comment]
Hmm this needs work.

On fedora, gerbera runs under its own user and group. This needs to be replicated here.

--create-config writes <home>/root/.config/gerbera</home>. I think this file should be created with the init script. Looks like I'll need to figure out how to write xml with ash...

Does the web interface work for you?

**Comment by TimelessNL** [comment]
Huh? doesn't it write the config to stout? [According to the docs](http://docs.gerbera.io/en/latest/config-generate.html#generateconfig) it should.

Running it as the `gerbera` user is not that difficult, yet most of the processes run as root on OpenWrt, and if you want to use the `gerbera` user it still needs to have access to the media library somehow, which the user has to do manually.

Is the uci integration needed for the initial version? If the package is in snapshot many more people can start using it I guess.

Yes the web interface works but if you didn't specify a port number it will be random by default. And it should be [49152 because of UPnP](http://docs.gerbera.io/en/latest/config-server.html#port).

**Comment by TimelessNL** [comment]
> ```
> root@OpenWrt:/# gerbera --help
> terminate called after throwing an instance of 'cxxopts::invalid_option_format_error'
>   what():  Invalid option format ‘compile-info’
> Aborted
> ```
> 
> hahaha.
runtime

**Comment by neheb** [comment]
I meant that in the config file, the home directory is specified as /root/.config/gerbera . That needs to be changed. Not sure if the init script should write its own xml file or SED the entries to their proper value.

**Comment by TimelessNL** [comment]
You added a warning to edit the config file first, so that's a start. This gives the user the opportunity to decide where the database (_and others_?) should be stored.

> we can either include a specific OpenWrt config here which we have to maintain, alert the user to change the path or use some sed magic in postinstal

Yeah some `sed` magic to change the dir would be the easiest but still functional option.

**Comment by neheb** [comment]
Found a solution to that problem.

I added a super basic UCI config to force people to configure the directory. The default I imagine is not so good.

I have no idea if this works properly.

**Comment by neheb** [comment]
Edited to force people to modify the config file. I'm not too sure of this since it forces people to modify /etc/config/gerbera once and /etc/init.d/gerbera start twice.

**Comment by neheb** [comment]
Going to merge. I really want people to start testing this.

**Comment by BKPepe** [comment]
Are you planning to backport it to OpenWrt 19.07?

**Comment by neheb** [comment]
I do not. I have no objection to doing so. It should be fine for 19.07. Forget about 18.06. GCC5 does not support C++17.

Next version will be interesting. It will require either libupnp 1.12.1 or libupnpp, both of which are not in the tree currently.

Let’s not even mention the size increase.

**Comment by TimelessNL** [comment]
But [libupnpp](https://github.com/openwrt/packages/blob/master/libs/libupnpp/Makefile) is in the OpenWrt tree? And do you see any difficultly to update libupnp to 1.12.1?

**Comment by neheb** [comment]
That’s just it. libupnpp is compatible with 1.8 and a C++ fork of nupnp. It is not compatible with libupnp 1.12.1. There’s also the question of other packages here that depend on libupnp. No idea if they’ll break with the newer version.

**Pull request merged**
