### PR TITLE
ksmbd-tools: update to latest 3.4.8 release

### PR DESCRIPTION
**Pull request by Gingernut1978**
Changelog: https://github.com/cifsd-team/ksmbd-tools/releases/tag/3.4.8

Maintainer: nobody
Compile tested: Mediatek filogic, Asus TUF AX4200, lastest master 
Run tested: Mediatek filogic, Asus TUF AX4200, lastest master

### CODE REVIEW

**Comment by 1715173329** [comment]
```
ksmbd-tools-3.4.8.tar.xz: Wrong hash (probably caused by .gitattributes), expecting a05d70b9751eb7237bf1bec8ae084913f35d2525e823a51aa8dab7e3e307f1bb, got e374c6e5053e82bc321e13927dbf3baf0d636205516564324686d002c084c5d6
```

**Comment by Gingernut1978** [comment]
```sha256sum ksmbd-tools-3.4.8.tar.gz 
a05d70b9751eb7237bf1bec8ae084913f35d2525e823a51aa8dab7e3e307f1bb  ksmbd-tools-3.4.8.tar.gz

**Comment by 1715173329** [comment]
We don't use that gzip tarball provided from release.
You should check .tar.xz

**Comment by pesa1234** [comment]
Hi, I use `make package/ksmbd-tools/check FIXUP=1 V=s` and it give `PKG_MIRROR_HASH:=e374c6e5053e82bc321e13927dbf3baf0d636205516564324686d002c084c5d6`

**Comment by 1715173329** [comment]
Yes and it's the real hash.

**Comment by Neustradamus** [comment]
Good PR is here:
- https://github.com/openwrt/packages/pull/20862

**Pull request closed without merging**
