### PR TITLE
golang: bump to v1.14

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: @jefferyto 
Compile tested: x86_64, OpenWrt master
Run tested: x86_64, OpenWrt master

Description:
- golang: bump to v1.14

### CODE REVIEW

**Comment by jefferyto** [comment]
You'll need to use your real name for the `Signed-off-by:` line.

**Comment by 1715173329** [comment]
Sorry but does it really necessary?

**Comment by jefferyto** [comment]
Yes, I believe pseudonyms are not allowed: https://openwrt.org/submitting-patches#sign_your_work

If you don't want to (and you can wait) I will open a PR tomorrow for this update.

**Comment by 1715173329** [comment]
All right, I've updated the sign-off.

**Comment by 1715173329** [comment]
All right, I wait for your PR, thank you so much.

**Pull request closed without merging**
