### PR TITLE
treewide: fix mirror hash for faad2, libmbim, libqmi, zlog, atlas-probe and  modemmanager

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @neheb
Compile tested: no
Run tested: no

Description:Due to the change in the version description, the package must be downloaded again.
In addition, the standard compression method has changed to `zst`.
The checksum must therefore be recalculated.

Recalculation was done with the following commands:
1. make package/<path-to-your-package>/download
2. make package/<path-to-your-package>/check FIXUP=1

### CODE REVIEW

**Comment by BKPepe** [comment]
CI fails:
```
  WARNING: PKG_MIRROR_HASH does not match modemmanager-1.22.0.tar.zst hash 72d129a00d51f0acf4c421f02dd342728ca42980bd9644e3c9a69ca0792fd60b
  make[2]: Leaving directory '/feed/net/modemmanager'
  time: package/feeds/packages_ci/modemmanager/check#0.01#0.01#0.03
  make[1]: Leaving directory '/builder'
Package HASH check failed
```

Anyway, I thought this was already done via https://github.com/openwrt/packages/commit/272f55e87f0731b3f04aefd39598a127b317abf4 , because it includes all the packages which you try to fix and I find this sentence quite misleading: ```In addition, the standard compression method has changed to zst.``` in your OP at least for me, because the commit , which I referenced addressed it.

Maybe something was wrong once you push it directly to the master branch without checking it with the CI/CD in those Fixes tags. Why we can not do that in one treewide commit and we need to have it per package?

**Comment by neheb** [comment]
@BKPepe @feckert updated the version for these packages without updating the hash. The previous treewide commit is unrelated.

**Comment by BKPepe** [comment]
Yeah, I noticed that as well, but this has nothing to do with zst as it is being said in the OP and as well in each commit, because the migration to zst was done. The difference is that Robert created PR, it was tested by CI/CD. 😇 Those commits pushed to the master without PR were not, though and it is still failing even here.

**Comment by feckert** [comment]
@BKPepe @neheb What happens next?

**Comment by neheb** [comment]
I assume pass CI and merge?

**Comment by feckert** [comment]
I took a closer look at the compressed tar.zst files. When I open them, there is a sub folder with the name modemmanger-$(PKG_VERSION).  By changing the $(PKG_VERSION) through my commit, this sub folder name has also changed because of a new git clone and new creation of the tar.zst. This has resulted in a new checksum.

 @BKPepe I would therefore merge this regardless of the CI error, as it is correct.

I don't think everyone was aware that the sub directory changes with a $(PKG_VERSION). change and therefore the checksum also changes. Another lesson learned

**Comment by neheb** [comment]
```
faad2-2.11.1.tar.zst: Download from https://github.com/knik0/faad2 failed
faad2-2.11.1.tar.zst: Wrong hash (probably caused by .gitattributes), expecting 3bedd29eb3a55a052158bb27f68c69177ebacb93c6a0643c0aac6303512eeb15, got 8dfc89b418293a91c0fc0d11013205449669ce973f5e951500c1e11e3ac61970
```

I have no idea how you got these hashes.

**Comment by neheb** [comment]
@robimarko can you look into this?

**Comment by robimarko** [comment]
I am getting incorrect hashes as well on these.

@feckert Did you have OpenWrt tools built before recalculating the hash?
Cause for modemmanager I am getting `72d129a00d51f0acf4c421f02dd342728ca42980bd9644e3c9a69ca0792fd60b` as the proper hash instead

**Comment by BKPepe** [comment]
It looks like the GitHub Actions were correct, alright and we just ignored it by merging it #yolo. It's a pity, though.

**Comment by robimarko** [comment]
> It looks like the GitHub Actions were correct, alright and we just ignored it by merging it #yolo. It's a pity, though.

I have to agree here, to me this seems like another instance where host ZSTD was used instead of the OpenWrt one to calculate hashes(We have had this pop-up in the main repo as well).

Issue is that currently, you can download and refresh packages before first building OpenWrt tools as the buildsystem does not enforce it, so I gotta look into making sure that tooling is always built.

**Comment by feckert** [comment]
Sorry for the inconveniece!!

I removed the PKG_MIRROR_HASH. Executed the command 'make
packages/feed/packages/medemmanager/download' after the download the new
source packages 'modemmanager-<PKG_VERSION>.xzt' was in my dl directory.
After that I executed the command 'sha256sum
modemmanager-<PKG_VERSION>.xzt'. I do Not know what I Made wrong!!

Sorry I can give you more assistance. I am in Holiday and so AFK. I am back
on Juni.

Robert Marko ***@***.***> schrieb am Mi., 22. Mai 2024, 13:57:

**Comment by robimarko** [comment]
There is no need to do anything manually, build system allows you to update the hash via
```make packages/feed/packages/modemmanager/check FIXUP=1```

**Pull request merged**
