### PR TITLE
transmission: Update to latest git and fix syslog.

### PR DESCRIPTION
**Pull request by neheb**
The init script runs transmission with the foreground parameter for procd to control it. However, if transmission is ran in the foreground, nothing is logged to syslog. Added a patch to remove this restriction.

Also added a sysctl file that removes these warnings:

UDP Failed to set receive buffer: requested 4194304, got 262142 (tr-udp.c:75)
UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:80)
UDP Failed to set send buffer: requested 1048576, got 262142 (tr-udp.c:86)
UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:91)

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @obsy 
Compile tested: ramips, LEDE trunk
Run tested: mt7621, GnuBee, LEDE trunk

### CODE REVIEW

**Comment by obsy** [comment]
Do you want to be the maintainer of this package?

**Comment by neheb** [comment]
Sure

**Comment by obsy** [comment]
If you want, so please, change also MAINTAINER and package is yours.

**Comment by neheb** [comment]
Done

**Pull request merged**
