### PR TITLE
smartmontools: Update to 7.0

### PR DESCRIPTION
**Pull request by neheb**
Removed weird uclibc++ compatibility stuff as it seems to not be needed
anymore.

Switched to standard variables.

Added PKG_BUILD_PARALLEL for faster compilation.

Removed PKG_FIXUP as it seems the package has been fixed already.

A few changes to the CFLAGS and linker options resulted in ipk size going
from 244694 to 244283, possibly due to previous overlinking.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @mstorchak 
Compile tested: mt7621 - both uclibc++ aand libstdc++
Run tested: GnuBee PC1

### CODE REVIEW

**Comment by diizzyy** [comment]
CONFIGURE_ARGS should probably be set to avoid buildbot failures and -flto slims it down a bit more for me.

```
TARGET_CFLAGS += -flto
TARGET_LDFLAGS += -flto

CONFIGURE_ARGS+= \
        --with-update-smart-drivedb=no \
        --with-gnupg=no \
        --with-smartdplugindir=no \
        --with-libcap-ng=no \
        --with-libsystemd=no \
        --with-systemdsystemunitdir=no \
        --with-systemdenvfile=no \
        --with-nvme-devicescan=no \
        --with-cxx11-regex=yes
```

We should also copy the packaged drive database...
```
define Package/smartmontools/install
....
        $(INSTALL_DIR) $(1)/usr/share
        $(CP) $(PKG_INSTALL_DIR)/usr/share/smartmontools $(1)/usr/share/
```

**Comment by neheb** [comment]
From a quick look at those, libcap-ng might be the only problematic one. I will look into it when I get time.

**Comment by neheb** [comment]
That last configure arg results in

utility.h:28:10: fatal error: regex: No such file or directory
 #include <regex>

uclibc++ targets c++98 AFAIK. Could enable it if libstdcpp is used but then what's the benefit?

Getting rid of nvme sounds wise. No platform except x86 exposes a pcie x4 interface. Not that I know of anyway. Except disabling it increases file size...

--with-nvme-devicescan=no = 243103
--without-nvme-devicescan = 243096
missing = 243075 ...

Some of those configure arguments behave oddly. For example, 

--with-libcap-ng=no = 243142
--without-libcap-ng = 243117
with nothing = 243096
(OpenWrt does not have libcap-ng)

I've seen similar behaviour with the other configure args. For now, I'm only going to disable the so called fast-lebe (the other path is not slower. gcc since 5 or 6 has learned how to recognize bswap and optimize it away) as well as update-smart-drivedb since we're working with embedded devices here. Amuzingly, adding --without-update-smart-drivedb and --without-gnupg decreases filesize by only 2 bytes.

And now it seems that manipulating CONFIGURE_VARS gives an even lower file size.

I have no explanation for this configure weirdness...

**Comment by neheb** [comment]
getting rid of NVME through CONFIGURE_VARS gets rid of 2 bytes. Adding in the other options through there does not increase filesize. So that's how I'll do it. I still would like an explanation...

**Comment by dhewg** [comment]
>  No platform except x86 exposes a pcie x4 interface

https://www.solid-run.com/marvell-armada-family/clearfog-cx-com-express-carrier/

</random drive-by comment>

**Comment by diizzyy** [comment]
The main reason isn't to cut down on size, rather to avoid broken behaviour. The regex functionality seems to parse HDD data, https://sourceforge.net/p/smartmontools/mailman/message/23614112/ which I think is wise.

**Comment by neheb** [comment]
@dhewg didn't know that. I guess if it only bloats the ipk by 2 bytes we can keep it in...

@diizzyy sure. but I can only include it if libstdcpp is used. uclibc++ does not support c++11 regex.

**Comment by neheb** [comment]
I just noticed that bug report is from 2009...

Original bug was probably fixed.

**Comment by neheb** [comment]
Sure.

**Comment by diizzyy** [comment]
Can you also include the share directory?

**Comment by neheb** [comment]
Sure.

**Comment by neheb** [comment]
Turns out some variables are better off being set in ARGS while others in VARS. What a mess...

Updated.

**Comment by mstorchak** [comment]
ACK
Great work, thank you, @neheb!
I had a plan to update smartmontools, but didn't realize that so many changes and ARGS/VARS fine tuning were required.

**Pull request merged**
