### PR TITLE
wavemon: Update to 0.9.0

### PR DESCRIPTION
**Pull request by neheb**
Added PKG_BUILD_PARALLEL for faster compilation

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jmccrohan 
Compile tested: ramips

### CODE REVIEW

**Comment by neheb** [comment]
ping @jmccrohan

**Comment by diizzyy** [comment]
Ping again, @jmccrohan

**Comment by cotequeiroz** [comment]
I've run-tested this in my Asus RT-N56U.  I didn't get that nice level bars, but I didn't get it with the previous version either.

**Comment by neheb** [comment]
@cotequeiroz I think this is what you meant?

I'd rather stick to stable versions and backport fixes as necessary. Except in circumstances like the libimobiledevice situation where they don't bother.

**Comment by cotequeiroz** [comment]
Precisely.

**Comment by neheb** [comment]
Merging

**Pull request merged**
