### PR TITLE
gummiboot: release bump

### PR DESCRIPTION
**Pull request by oskarirauta**
Changes:
 - fixes conflicts with EFI headers mentioned in issue #22433

Maintainer: me
Compile tested: x86_64

### CODE REVIEW

**Comment by BKPepe** [comment]
I need to say that commit subject is misleading as hell in this case. :-/ There is no release bump, but backport or rather adding patch. Would be good to know if the patch is going to be upstreamed or it is backport, etc.

**Comment by 1715173329** [comment]
It's already landed on 23.05 branch.
Real upstream is probably dead, but it still works.
Alpine holds a similar patch here: https://git.alpinelinux.org/aports/commit/main/gummiboot/remove-conflicts.patch?id=3662c7846023c45561b5b5ceb57e261aaf56ad45

**Comment by oskarirauta** [comment]
@BKPepe Are you saying that I forgot to bump release number?

**Comment by 1715173329** [comment]
> @BKPepe Are you saying that I forgot to bump release number?

It's commit title. `gummiboot: release bump` is general and not clear enough to describe main changes.
For example, Alpine one is `main/gummiboot: fix build with latest GNU-EFI`.

**Comment by BKPepe** [comment]
Yep, I agree with @1715173329 .

**Comment by oskarirauta** [comment]
Ok

**Pull request merged**
