### PR TITLE
cyrus-sasl: Fix compilation without deprecated APIs on OpenSSL

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @MikePetullo 
Compile tested: mvebu

### CODE REVIEW

**Comment by neheb** [comment]
https://github.com/cyrusimap/cyrus-sasl/pull/544 for upstream pull request

**Comment by MikePetullo** [comment]
Recommend merge. We have been waiting for the next complete cyrus-sasl version since at least January of 2017. See https://lists.andrew.cmu.edu/pipermail/cyrus-sasl/2017-January/002941.html. Thank you for the accompanying upstream report.

**Comment by neheb** [comment]
Merged upstream.

**Comment by champtar** [comment]
@neheb if you can amend you commit to reference the upstream commit then we can definitely merge it
thanks for your work!!

**Comment by neheb** [comment]
@champtar Fixed

**Pull request merged**
