### PR TITLE
nano: update to 2.5.3

### PR DESCRIPTION
**Pull request by hnyman**
* Update nano editor to 2.5.3
* Change download to use GNU alias to provide fault tolerance

CC to maintainer: @oneru

### CODE REVIEW

**Comment by yousong** [comment]
Ahh, I saw @oneru 's commit first and merged that one.  I agree that `@GNU/nano` is nice to have.

**Comment by oneru** [comment]
I didn't know that @gnu/nano was an option.  I take it that pulls from some set of mirrors instead of just the nano-editor.org site?  I have no problem with it, and I'm not sure why I didn't notice being tagged in hnyman's pull request.

**Comment by yousong** [comment]
Hi @oneru, the relevant code is at https://github.com/openwrt/openwrt/blob/master/scripts/download.pl#L185

**Comment by oneru** [comment]
OK, That's great.  If @hnyman wants to tweak his pull request so it applies cleanly, I think the suggested change would be a good idea.  Didn't intend to ignore it, sorry about that.

**Comment by hnyman** [comment]
I rewrote the download location change and pushed it directly as https://github.com/openwrt/packages/commit/b49d41f289b8b5a72731228f2abff32d468a2809

**Pull request closed without merging**
