### PR TITLE
Borg update 1.2.3

### PR DESCRIPTION
**Pull request by julienmalik**
Maintainer: me
Compile tested: x86 / openwrt master
Run tested: no

Description:
Bump to new minor release for borg and python-exceptiongroup (dependency)

### CODE REVIEW

**Comment by julienmalik** [comment]
Hi,

Any help with this build error ?
It looks to me it's probably more an issue with the CI itself than a build issue of this particular package.

```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ply/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ply/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ply/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ply/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ply/
Could not fetch URL https://pypi.org/simple/ply/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ply/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement ply==3.11 (from versions: none)
ERROR: No matching distribution found for ply==3.11
```

Thanks!

**Comment by 1715173329** [comment]
> It looks to me it's probably more an issue with the CI itself than a build issue of this particular package.

yep

**Comment by julienmalik** [comment]
Any way to relaunch the CI to see if I'm more lucky ?

**Comment by 1715173329** [comment]
there's no luck. it's caused by the outdated sdk image (last update is 2 months ago).

**Pull request merged**
