### PR TITLE
prometheus-node-exporter-lua: ltq-dsl.lua: use errors_fecs_*

### PR DESCRIPTION
**Pull request by sch-m**
This is part of the FECS counter fix and related to openwrt/openwrt#2357

### CODE REVIEW

**Comment by dhewg** [comment]
lgtm

**Comment by champtar** [comment]
@sch-m you need to bump `PKG_VERSION`

**Comment by sch-m** [comment]
> @sch-m you need to bump `PKG_VERSION`

I think you have meant `PKG_RELEASE`. -> Done.

**Comment by dhewg** [comment]
Tested and confirmed working.
@champtar please merge, it's a required fix

**Comment by champtar** [comment]
Thanks @sch-m, do you need a backport to 19.07 ?

**Comment by sch-m** [comment]
> Thanks @sch-m, do you need a backport to 19.07 ?

@champtar 
Not at the moment. It's needed when openwrt/openwrt#2357 is backported to 19.07.

**Pull request merged**
