### PR TITLE
icu: update to 60.2

### PR DESCRIPTION
**Pull request by nxhack**
Maintainer: me
Compile tested: ar71xx, LEDE trunk r5488-893a1ed
Run tested: NONE

Description:
update to 60.2

Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>

### CODE REVIEW

**Comment by nxhack** [comment]
hmm...

```
   g++	 ...  calendar.cpp
calendar.cpp: In constructor 'icu_60::Calendar::Calendar(UErrorCode&)':
calendar.cpp:711:16: error: incompatible types in assignment of 'const char [1]' to 'char [157]'
 actualLocale("")
                ^
calendar.cpp:711:16: error: incompatible types in assignment of 'const char [1]' to 'char [157]'
calendar.cpp: In constructor 'icu_60::Calendar::Calendar(icu_60::TimeZone*, const icu_60::Locale&, UErrorCode&)':
calendar.cpp:739:16: error: incompatible types in assignment of 'const char [1]' to 'char [157]'
 actualLocale("")
                ^
calendar.cpp:739:16: error: incompatible types in assignment of 'const char [1]' to 'char [157]'
calendar.cpp: In constructor 'icu_60::Calendar::Calendar(const icu_60::TimeZone&, const icu_60::Locale&, UErrorCode&)':
calendar.cpp:773:16: error: incompatible types in assignment of 'const char [1]' to 'char [157]'
 actualLocale("")
                ^
calendar.cpp:773:16: error: incompatible types in assignment of 'const char [1]' to 'char [157]'
```

I compiled well in my build environment.
my host gcc version:
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```
Travis:
```
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

icu4c Trac changeset:
https://ssl.icu-project.org/trac/changeset/40670/trunk/icu4c/source/i18n/calendar.cpp

**Comment by nxhack** [comment]
https://tutel.me/c/programming/questions/19114321/trouble+on+initializing+a+struct+with+the+constructor+initialization+list

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43453

**Comment by champtar** [comment]
Travis most recent ubuntu version is 14.04 ...
I'll look into updating gcc

**Comment by nxhack** [comment]
http://site.icu-project.org/

> 2017-12-12: ICU 60.2 maintenance update is not available. See ICU 60 download page for details.

It seems that this version has been canceled. It seems that it was due to the problem of "c ++ 11" correspondence. This PR will also be suspended until it is resolved upstream.

However, it is desirable to update gcc-4 to gcc-5 or higher.

**Comment by champtar** [comment]
Hi @nxhack,
The problem with Travis is that you don't really update, you install the update every time
I want to look at circleci but I don't known when I will have time

**Comment by nxhack** [comment]
Upstream has addressed gcc-4 issue.
Travis CI build passed

**Pull request merged**
