### PR TITLE
xl2pd: fixed segmentation fault at start

### PR DESCRIPTION
**Pull request by neva-blyad**
Maintainer: me
Compile tested: ARM Cortex-A7, Freescale i.MX 6 ULL, OpenWRT v21.02.0
Run tested: same

Description:
https://github.com/xelerance/xl2tpd/issues/243

### CODE REVIEW

**Comment by feckert** [comment]
Please use a valid commit header in your commit:
`xl2pd: <Describe what you are fixing>`
Please use a valid `Signed-off-by: firstname lastname <valid@mail.com>`

**Comment by neva-blyad** [comment]
> Please use a valid commit header in your commit: `xl2pd: <Describe what you are fixing>` Please use a valid `Signed-off-by: firstname lastname <valid@mail.com>`

Done.

**Comment by feckert** [comment]
If this is the case, then I would suggest that the commit message looks like this.
`xl2pd: fixed segmentation fault at start`
Are you planning to send this to the upstream project as well?

**Comment by neva-blyad** [comment]
> If this is the case, then I would suggest that the commit message looks like this. `xl2pd: fixed segmentation fault at start` Are you planning to send this to the upstream project as well?
I fixed the commit message as you've adviced.
I sent this to the upstream project.
Current Pull Request is needed anyway.

**Comment by feckert** [comment]
Sorry but this was the pullrequest message.

**Comment by neva-blyad** [comment]
> Sorry but this was the pullrequest message.

?

**Pull request closed without merging**
