### PR TITLE
freeradius3: Add support for SQL

### PR DESCRIPTION
**Pull request by yangfl**
Signed-off-by: David Yang <mmyangfl@gmail.com>

Maintainer: @LucileQ
Compile tested: sdk-18.06.1-ar71xx
Run tested: 18.06.1-ar71xx

Description:
Various SQL-related modules.

### CODE REVIEW

**Comment by neheb** [comment]
Please remove the maintainer. She is not active. Just leave an empty PKG_MAINTAINER:= line.

**Comment by neheb** [comment]
This also needs a PKG_RELEASE bump.

**Comment by diizzyy** [comment]
@yangfl 
If possible, can you bump this to 3.0.18 while at it?
https://github.com/FreeRADIUS/freeradius-server/releases/tag/release_3_0_18

**Comment by yangfl** [comment]
@diizzyy done

**Comment by neheb** [comment]
Looks good. Merging.

**Pull request merged**
