### PR TITLE
[18.06] nut: Backport fixes from master

### PR DESCRIPTION
**Pull request by cshoredaniel**
Backport and squash the following commits from master:

  5790053eb nut: Add missing conffiles
  ceff68837 nut: Reorganize nut-server to clarify nut-driver
  f6a2a97d2 nut: Use 'real' procd init for nut-monitor
  918a62f91 nut: Make FSD really work
  a2f64b3ba nut: Reduce user error with POWERDOWNFLAG
  461393810 nut: Use quotes around filenames
  1b6dbe7a7 nut: Remove duplicate/extraneous lines
  0a49d0ffb nut: Fix checking for path before it exists
  3b5a8eee8 nut: Various startup fixes for monitor and server
  44e57d4bd nut: Fix variables for NUT drivers
  36fd59dc7 nut: Fix extraneous config_get
  192b0f164 nut: Fix a typo in setting a driver parameter
  f48b060fa nut: Fix upsd runs as root

And bump PKG_RELEASE

Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

Maintainer: me / @cshoredaniel 

Testing to be done -- straight rebase applicable commits and bump PKG_RELEASE so there shouldn't be any surprises but I'm hoping folks that are using nut will double-check.

### CODE REVIEW

**Comment by hnyman** [comment]
If it is straight chrry-pick backport, let's just merge it and then see if there is any fallout.

**Comment by cshoredaniel** [comment]
Great!  Thanks!

**Comment by mantinan** [comment]
Well... I don't know where to start, so...
Running as root seems to work ok, but if we try to run it as nut with /etc/config/nut_server:
config driver 'riello'
        option driver riello_usb
        option port /dev/ttyUSB0
	option runas nut
config listen_address
        option address X.X.X.X
        option port 3493
config upsd 'upsd'
	option maxage 15
	option statepath /var/run/nut
	option maxconn 1024
	option runas nut

The first runas nut can be removed with exactly the same results: only the riello driver is started, not upsd and it is started as root no matter what user you specify, this is what I saw after the start when I switched to the above config with runas nut:
# ps|grep nut
 1018 root      1320 S    /lib/nut/riello_usb -D -a riello
#  ls -la /var/run/nut/
drwxr-x---    2 nut      nut             60 Jan 11 14:06 .
drwxr-xr-x    5 root     root           320 Jan 11 14:07 ..
srw-rw----    1 root     root             0 Jan 11 14:06 riello_usb-riello
# ls -la /var/etc/nut/
drwxr-xr-x    2 root     root           120 Jan 11 14:06 .
drwxr-xr-x    3 root     root            60 Jan 11 14:06 ..
-rw-r--r--    1 root     root            15 Jan 11 14:06 nut.conf
-rw-r-----    1 root     root           104 Jan 11 14:06 ups.conf
-rw-r-----    1 root     nut            125 Jan 11 14:06 upsd.conf
-rw-r-----    1 root     nut             54 Jan 11 14:06 upsd.users
# /usr/sbin/upsd -D -u nut
Network UPS Tools upsd 2.7.4
   0.000000     fopen /var/run/nut/upsd.pid: No such file or directory
   0.002591     listening on 172.22.54.32 port 3493
   0.004968     Can't open /etc/nut/ups.conf: Can't open /etc/nut/ups.conf: Permission denied
# opkg list-installed|grep nut
nut - 2.7.4-9
nut-common - 2.7.4-9
nut-driver-riello_usb - 2.7.4-9
nut-server - 2.7.4-9

So... it looks like permisions on config files are not being set right and also the riello driver is not being launched as user nut.

:-(

This was tested on a newly installed stable openwrt by installing just the kmod-usb-serial-pl2303 and nut-driver-riello_usb version 2.7.4-9 packages available on the stable openwrt repositories.

If you need any farther testing just let me know.

Regards.

**Comment by cshoredaniel** [comment]
Hi all, finally pushed https://github.com/openwrt/packages/pull/8017 -- this should be the final iteration as I've run the scripts through shellcheck to catch a bunch of silly (or rare) cases, as well as removing any important load the UPS so that I could properly test.  Hope the results are good which case I'll backport master to 18.06 as 18.06 doesn't satisfy me at the moment.

**Comment by t4thfavor** [comment]
I'm running 18.06.4, and it seems that some of this has either risen again, or was not entirely fixed. 
My device is a Meraki MX60, and when I install the above mentioned packages, I get no /etc/config/nut(anything), and the simlink to /etc/nut/nut.conf is broken (the file it points to is not there)

What else do I need to provide to try and correct this?

**Comment by cshoredaniel** [comment]
Hey is this on a freshly installed system, or one which had a nut 
install before? I'm wondering if the overlay has the 'whiteout's from 
previously deleting files (i.e. has the system 'remembered' the config 
was deleted so doesn't replace it, since it's a conffile?).  If that's 
not the case I'll have to take a closer look.

Regards,

Daniel

**Comment by cshoredaniel** [comment]
I created PR #9841 which was merged yesterday which ought to fix this.  
I'm not sure if that means it's available in the packages feed or not.  
If it is, then fresh installs will pull the new fixed version.  If not 
then then the only way is to use the SDK (or full buildroot) to build 
the openwrt-18.04 branch of the openwrt/packages repo.  @neheb @dizzzy 
@karlp Do you know if updates to 18.04 branch result in changes to the 
packages in the binary feed?

**Comment by t4thfavor** [comment]
Sorry about hay, apparently I wasn’t getting notifications. It was fresh install, but never installed. I removed and reinstalled several times, and eventually I got the proper binaries. I’ve since upgraded to a snapshot and all seems well. Thanks for putting effort into this for me!

**Comment by cshoredaniel** [comment]
@t4thfavor awesome!  Thank you for reporting!

**Pull request merged**
