### PR TITLE
python-service-identity: Update to 18.1.0

### PR DESCRIPTION
**Pull request by neheb**
Switched URL to standard one.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jefferyto 
Compile tested: ramips

### CODE REVIEW

**Comment by jefferyto** [comment]
The [dependencies](https://github.com/pyca/service_identity/blob/18.1.0/setup.py#L35) have changed a bit with this version:

* ipaddress (`python-ipaddress`) required for the Python 2 package
* pyOpenSSL (`python-pyopenssl`) no longer required (now optional)
* cryptography (`python-cryptography`) required (replacing pyOpenSSL)

Can you update the Makefile `DEPENDS` as well?

**Comment by neheb** [comment]
Done

**Comment by jefferyto** [comment]
Sorry, can you also update the `DEPENDS` for the Python 3 package (`python3-service-identity`)?

**Comment by neheb** [comment]
Done

**Comment by jefferyto** [comment]
There isn't a `python3-ipaddress` (ipaddress is a built-in module for Python 3, `python-ipaddress` is the module backported for Python 2) :sweat_smile:

**Comment by neheb** [comment]
Noted.

**Pull request merged**
