### PR TITLE
acme: Fix loading credentials 

### PR DESCRIPTION
**Pull request by dauriata**
Maintainer: @tohojo

Move credentials loading function before cert renewal call as credentials might be needed for some renewal operations ( ex: DNS )

### CODE REVIEW

**Comment by tohojo** [comment]
Needs DCO, and please bump the package release as well. Otherwise, LGTM :)

**Comment by diizzyy** [comment]
It also needs a proper commit message

**Comment by dauriata** [comment]
sorry about that, I used the web github editor and was not sure how to use it. Should be correct now

**Comment by tohojo** [comment]
Yup, that's better, thanks!

**Pull request merged**
