### PR TITLE
tinyproxy: Fix incorrect configuration + Add Socks support

### PR DESCRIPTION
**Pull request by lars18th**
Maintainer: me / @jow- 
Compile tested: mips & x86_64
Run tested: TP-Link Archer C2 v3 & X86-PC, OpenWrt 19.07.2

Description:

The package is broken when updating the tinyproxy to version 1.10.0, as the configuration doesn't include the correct type (HTTP by default). This bug is fixed in this PR. Moreover, support in the conguration is added for Socks4/5 upstream proxies.

Regards.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi,

This patch _fixes_ a bug in the current package.
So, please, review this PR.

**Comment by neheb** [comment]
```
=== Checking commit 'c7a663e45780741ee3d7c2519f98bc781299ebb8'
Author name (Lars The) seems ok
Commit subject line MUST start with '<package name>: ' (Fix incorrect package version)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Lars The <lars18th@users.noreply.github.com>')
=== Checking commit '6d2976445da7040ff31849545f3a71312a7867dd'
Author name (Lars The) seems ok
Commit subject line MUST start with '<package name>: ' (Bump version)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Lars The <lars18th@users.noreply.github.com>')
=== Checking commit '898b3ee80ade33d9db32e221607b7f2e377b02dd'
Author name (Lars The) seems ok
Commit subject line MUST start with '<package name>: ' (Update examples with Socks4/5 upstreams)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Lars The <lars18th@users.noreply.github.com>')
=== Checking commit '6d85316e5db38666c78e4818c6bfa3571604a2ec'
Author name (Lars The) seems ok
Commit subject line MUST start with '<package name>: ' (Fix missing type with version >= 1.10.0)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Lars The <lars18th@users.noreply.github.com>')
```

**Comment by BKPepe** [comment]
Closing as `Signed-off-by` does not match, and it does not include the real name. Once you make these changes, feel free to reopen.

**Comment by lars18th** [comment]
Hi @BKPepe 

> Closing as `Signed-off-by` does not match, and it does not include the real name. Once you make these changes, feel free to reopen.

I suggest some other signes the patch. The bug continues until someone provides the fix.

**Comment by lars18th** [comment]
Hi @stokito ,

Can you please help refactoring (and signing) this "ancient" (but nor resolved) patch?
I'm using it for years and today I found that isn't fixed.

Thank you.

**Pull request closed without merging**
