### PR TITLE
python3-readline: add package

### PR DESCRIPTION
**Pull request by oskarirauta**
Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

Maintainer: Oskari Rauta / @oskarirauta
Compile tested: x86_64, xeon powered server, recent OpenWRT snapshot
Run tested: x86_64, xeon powered server, recent OpenWRT snapshot

Description:
Python wrapper to libreadline

### CODE REVIEW

**Comment by oskarirauta** [comment]
@neheb I mean, how can I fix this, if quilt reverts back to un-acceeptable?

**Comment by neheb** [comment]
make package/python3-readline/refresh gives me:

```
--- a/lang/python/python3-readline/patches/001-remove-whitespace.patch
+++ b/lang/python/python3-readline/patches/001-remove-whitespace.patch
@@ -1,6 +1,6 @@
 --- a/setup.py
 +++ b/setup.py
-@@ -83,7 +83,7 @@
+@@ -83,7 +83,7 @@ if building and not os.path.exists('read
          os.system('cd rl && /bin/bash ./build.sh')
          print("\n============ Building the readline extension module ============\n")
      else:
```

**Comment by neheb** [comment]
the way you fix is by running make package/python3-readline/clean and then running make package/python3-readline/refresh .

Or manually wiping build_dir/xxx

**Comment by oskarirauta** [comment]
Same result..

So quilt says my patches --- line is empty? Check my commit, that can't be correct..

**Comment by neheb** [comment]
Alright. refresh is officially hard.

@aparcar @lipnitsk thoughts?

@oskarirauta what OS are you trying to compile on?

**Comment by oskarirauta** [comment]
Same result.

What is quilt's issue with this patch?

**Comment by oskarirauta** [comment]
Do I really need ti wipe entisten target dir? All other compiled software as well???

**Comment by neheb** [comment]
Sigh. no.

build_dir/target-xxx/pypi/readline-6.2.4.1/

make package/python3-readline/clean already does this.

**Comment by oskarirauta** [comment]
> Alright. refresh is officially hard.

Indeed.

> @oskarirauta what OS are you trying to compile on?

ArchLinux, few months old installation in BHyve VM

**Comment by neheb** [comment]
Anyway, I already ran this locally and gave you a fix.

I'd prefer that all these commits get squashed since a lot of these commits are noise.

**Comment by oskarirauta** [comment]
> Sigh. no.
> 
> 
> 
> build_dir/target-xxx/pypi/readline-6.2.4.1/
> 
> 
> 
> make package/python3-readline/clean already does this.

After make -j1 package/python3-readline/refresh V=s my 001- patch is deleted from local tree and 002- is reverted to what it was before 001-

Local development directory is not even in ANY git, so revert cannot come from there either. I wiped tmp, thought quilt keeps one version there, but no.. How can I add even more verbosity so I could see what it really does?

**Comment by neheb** [comment]
Why not run find to find the file?

**Comment by oskarirauta** [comment]
> I'd prefer that all these commits get squashed since a lot of these commits are noise.

I do not know how and I've been asked to not create a new prs.

**Comment by neheb** [comment]
Assuming you have a local dev environment:

git rebase -i HEAD~7
<< replace pick with s for the last 5 commits <<
git push --force

**Comment by oskarirauta** [comment]
> Why not run find to find the file?

Great idea actually. I'll check that out later, I am at car now, so I am replying here with my phone..

**Comment by neheb** [comment]
Umm. Run

git rebase origin/master

**Comment by oskarirauta** [comment]
> Assuming you have a local dev environment:
> 
> git rebase -i HEAD~7
> << replace pick with s for the last 5 commits <<
> git push --force

I messed it up really hard, somehow I managed to get knot-resolver included in my commit. Even though it's not advised to do so, a new PR will be absolutely the best solution to fix this.. Closing this now and giving up on this one for now..

**Comment by oskarirauta** [comment]
> Umm. Run
> 
> git rebase origin/master

Sorry, I already deleted branch and then created it again so it's gone...

**Comment by oskarirauta** [comment]
Replaced by #15369

**Comment by lipnitsk** [comment]
> thoughts?

Seems more of a git learning curve issue than refresh being hard in this case?

**Comment by neheb** [comment]
Sounds like both honestly.

**Pull request closed without merging**
