### PR TITLE
sound/upmpdcli: Update to 1.4.0

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @ignisf
Compile tested: sunxi, Orange Pi PC, OpenWrt master
Run tested: sunxi, Orange Pi PC, OpenWrt master

Description:
Update upmpdcli to 1.4.0
Backport commit https://opensourceprojects.eu/p/upmpdcli/code/ci/256394399f57ba6e3057ee2c981127a14e4623f8/tree/
Drop icon patch

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by ignisf** [comment]
I am okay with this change

**Comment by thess** [comment]
@diizzyy - very old branch. Please rebase so CI runs correctly

**Comment by diizzyy** [comment]
@thess 
It'll still fail so I don't see the point but oh well...

**Comment by diizzyy** [comment]
@thess 
Fixed

**Pull request merged**
