### PR TITLE
python-psycopg2: fix build

### PR DESCRIPTION
**Pull request by commodo**
Fixes https://github.com/openwrt/packages/issues/1945

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
@hnyman just noticed this was not merged but closed
is there a reason ? I can't seem to find it ?

**Comment by hnyman** [comment]
Well, I have only merged #2062 and that action seems to have closed this PR. I have not explicitly closed this.

Googling for  "github merge auto closes issue" reveals this:
https://help.github.com/articles/closing-issues-via-commit-messages/

I think that Github has tried to be helpful and has closed this PR, because your intro message in PR 2062 includes also the keyword "fixes #2061": Github has interpreted that to mean that this 2061 will be unnecessary after 2062 is merged.

PR message in 2062:
> Does not affect nor does fix #1945
> This fixes #2061 handles issue #1945
> 
> Signed-off-by: Alexandru Ardelean ardeleanalex@gmail.com

**Comment by commodo** [comment]
ah ; 
i think this has happened sometime in the past;
auto-magic can be annoying

**Comment by commodo** [comment]
so, any idea the Github ID of the maintainer on this to ping him ?

**Comment by hnyman** [comment]
@the-alien seems to be the maintainer

**Comment by the-alien** [comment]
OK, I'll look at this soon. The patch seems OK to me, but the build will be broken if pg_config already present on host system. So $(STAGING_DIR)/bin should come first in PATH variable.

**Comment by commodo** [comment]
Good point.
Will re-spin.

**Comment by commodo** [comment]
re-spinned; @the-alien

**Comment by the-alien** [comment]
Well, I was not able to reproduce this build issue even from virginal clean repository,
and with setuptools 18.7. The solution given by @commodo  also works for me,
so if it solves the issue, I think, it won't get worse than it already is.

**Comment by the-alien** [comment]
Now I see the problem, it occurred on the second pass, at which it still tried to find pg_config, even if build_ext step has already passed. In my case it gets found in host system. Pythonistas are pythonic as always.

**Comment by commodo** [comment]
Should we close this https://github.com/openwrt/packages/issues/1716 ?

**Pull request merged**
