### PR TITLE
cifsd: update to git (2019-08-19)

### PR DESCRIPTION
**Pull request by Andy2244**
Maintainer: me
Compile tested: arm/mips/mipsel (snapshots)
Run tested: arm, mips (qemu)

Description:
* update to git (2019-08-19)
* use new "kill_server" sysfs option on stop
* ensure reload_service() works correctly
* add `inherit owner`, `force create mode`, `force directory mode` UCI options
* add patches for mips target

### CODE REVIEW

**Comment by Andy2244** [comment]
Seem upstream needs to fix the vfree() vs kvfree() also for mips.

**Comment by neheb** [comment]
This is related I think: https://github.com/cifsd-team/cifsd/pull/187

**Comment by dengqf6** [comment]
@neheb Fixed in the latest version

**Comment by Andy2244** [comment]
ok, updated and fixed.

PS: Seems buildpr environment is bugged atm?

**Comment by Andy2244** [comment]
@jow- I don't get why buildpr is broken for me here, in the prepare step, other PR seem to build fine?

```
src-git base https://github.com/openwrt/openwrt.git;master
src-link packages /home/build/openwrt_packages
src-git luci https://github.com/openwrt/luci.git;master
Updating feed 'base' from 'https://github.com/openwrt/openwrt.git;master' ...
Cloning into './feeds/base'...
remote: Enumerating objects: 9091, done.        
remote: Counting objects: 100% (9091/9091), done.        
remote: Compressing objects: 100% (7628/7628), done.        
remote: Total 9091 (delta 1629), reused 4767 (delta 832), pack-reused 0        
Receiving objects: 100% (9091/9091), 12.32 MiB | 10.07 MiB/s, done.
Resolving deltas: 100% (1629/1629), done.
Create index file './feeds/base.index' 
make: *** [staging_dir/host/.prereq-build] Error 1
Collecting target info: doneUpdating feed 'packages' from '/home/build/openwrt_packages' ...
Create index file './feeds/packages.index' 
make: *** [staging_dir/host/.prereq-build] Error 1
Collecting target info: doneUpdating feed 'luci' from 'https://github.com/openwrt/luci.git;master' ...
Cloning into './feeds/luci'...
remote: Enumerating objects: 4140, done.        
remote: Counting objects: 100% (4140/4140), done.        
remote: Compressing objects: 100% (2105/2105), done.        
remote: Total 4140 (delta 915), reused 3002 (delta 562), pack-reused 0        
Receiving objects: 100% (4140/4140), 4.16 MiB | 0 bytes/s, done.
Resolving deltas: 100% (915/915), done.
Create index file './feeds/luci.index' 
make: *** [staging_dir/host/.prereq-build] Error 1
Collecting target info: donemake: *** [staging_dir/host/.prereq-build] Error 1
Exited with code 2
```

**Comment by neheb** [comment]
Rebase against current master.

**Comment by Andy2244** [comment]
ok seems i build the wrong test target, since not all vfree/vmalloc cases are fixed. Waiting again for upstream fixes.

**Comment by Andy2244** [comment]
@neheb ok worked and added the mips patches.

**Pull request merged**
