### PR TITLE
mutt: bump to version 1.12.0

### PR DESCRIPTION
**Pull request by philenotfound**
Signed-off-by: Phil Eichinger <phil@zankapfel.net>

Maintainer: me
Compile tested: (ar71xx, TL-WDR4300, 18.06.2)
Run tested: (ar71xx, TL-WDR4300, 18.06.2)

### CODE REVIEW

**Comment by neheb** [comment]
Ah bummer. I would have suggested changing the first link to http.

**Comment by philenotfound** [comment]
Do you want to drop ftp and use https instead?

**Comment by neheb** [comment]
FTP is problematic on some platforms where it just doesn't work for some reason. HTTP is more reliable. The first mirror can be switched to http://

**Comment by philenotfound** [comment]
I've switched to https with #9089

**Pull request merged**
