### PR TITLE
ddns-scripts: Fix problems detecting if curl is SSL capable

### PR DESCRIPTION
**Pull request by mark0n**
Maintainer: @chris5560, @maxberger 
Run tested: OpenWRT 18.06.0

### CODE REVIEW

**Comment by chris5560** [comment]
Found the problem.
Setting CURL_SSL was moved from global section to function do_transfer unknown time ago.
Will prepare fix

**Comment by cshoredaniel** [comment]
LGTM

**Comment by mark0n** [comment]
Done

**Comment by dibdot** [comment]
Thanks!

**Pull request merged**
