### PR TITLE
ruby: respect LDFLAGS

### PR DESCRIPTION
**Pull request by ryzhovau**

### CODE REVIEW

**Comment by luizluca** [comment]
@ryzhovau , I'm curious why defining EXTLDFLAGS is needed. Is it for ext compilation? Or host one?

TARGET_LDFLAGS do get into LDFLAGS inside Makefile (as expected, only for target and not for host build).

```
$ grep -- -Lxxx feeds/packages/lang/ruby/Makefile build_dir/target-i386_i486_musl-1.1.11/ruby-2.2.3/Makefile
feeds/packages/lang/ruby/Makefile:TARGET_LDFLAGS += (....) -Lxxx
build_dir/target-i386_i486_musl-1.1.11/ruby-2.2.3/Makefile:LDFLAGS =  $(CFLAGS) (....) -Lxxx (...)
```

I guess EXTLDFLAGS="$(TARGET_LDFLAGS)" will also apply for host compilation. It breaks the semantic of a TARGET_XXX variable. Is it the intention?

If the reason of this patch is to add extra flags for both host and target build, It should use HOST_LDFLAGS or directly passing it to configure/make as, AFAIK, there is no common openwrt XXX_LDFLAGS for both target and host.

**Comment by ryzhovau** [comment]
Just checked: without this PR I get:
```
…
Target: mipsel-openwrt-linux-uclibc
Configured with: /home/ryzhovau/Entware-ng/build_dir/toolchain-mipsel_mips32r2_gcc-4.8.5_uClibc-1.0.9/gcc-4.8.5/configure --with-bugurl=https://dev.openwrt.org/ --with-pkgversion='OpenWrt GCC 4.8.5 unknown' --prefix=/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-4.8.5_uClibc-1.0.9 --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=mipsel-openwrt-linux-uclibc --with-gnu-ld --enable-target-optspace --disable-libgomp --disable-libmudflap --disable-multilib --disable-nls --with-host-libstdcxx=-lstdc++ --with-float=soft --with-gmp=/home/ryzhovau/Entware-ng/staging_dir/host --with-mpfr=/home/ryzhovau/Entware-ng/staging_dir/host --with-mpc=/home/ryzhovau/Entware-ng/staging_dir/host --disable-decimal-float --with-mips-plt --enable-libssp --with-cloog=/home/ryzhovau/Entware-ng/staging_dir/host --with-isl=/home/ryzhovau/Entware-ng/staging_dir/host --disable-__cxa_atexit --with-headers=/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-4.8.5_uClibc-1.0.9/include --disable-libsanitizer --enable-languages=c,c++ --enable-shared --enable-threads --with-slibdir=/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-4.8.5_uClibc-1.0.9/lib
Thread model: posix
gcc version 4.8.5 (OpenWrt GCC 4.8.5 unknown)
linking shared-library libruby.so.2.2.0
/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-4.8.5_uClibc-1.0.9/lib/gcc/mipsel-openwrt-linux-uclibc/4.8.5/../../../../mipsel-openwrt-linux-uclibc/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Makefile:240: recipe for target 'libruby.so.2.2.0' failed
make[3]: *** [libruby.so.2.2.0] Error 1
make[3]: Leaving directory '/home/ryzhovau/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.9/ruby-2.2.3'
```
`LDFLAGS` are ignored for target binaries without this PR.

**Comment by luizluca** [comment]
@rkunze ,

It seems that you are not using a pure OpenWRT build envorioment. You have a new uclibc-1.0.9 (while CC uses uClibc-0.9.33.2 and DD mostly uses musl) with an old gcc-4.8.5 (the default for CC is 4.8-2014.04 and DD is gcc-5.2.0). I wasn't able to reproduce your envorioment. Could you share a .config file that works with OpenWRT and is able to reproduce your problem?

I have no problem merging a fix specific for your build if it does not mess with all the other OpenWRT targets. It currently do compile with all targets for CC and trunk (DD). I wish to keep it like this. :-)

It seems that your problem only happens with your setup. The output you sent does not show much as all Make commands are hidden. You can get full gcc cmdline adding to .../lang/ruby/Makefile:

``` 
HOST_MAKE_FLAGS += V=1
MAKE_FLAGS += V=1
``` 

That way, you'll see which args got to gcc.

At least I can see that the problem is with target compilation and not host one. Host does not depend on gmp since 84c04a7. However, the same strategy does not apply for target build.

**Comment by rkunze** [comment]
Hi Luiz,

Am 07.12.2015 um 18:54 schrieb Luiz Angelo Daros de Luca:
> @rkunze <https://github.com/rkunze> ,
>
> It seems that you are not using a pure OpenWRT build envorioment. You
> have a new uclibc-1.0.9 (while CC uses uClibc-0.9.33.2 and DD mostly
> uses musl) with an old gcc-4.8.5 (the default for CC is 4.8-2014.04 and
> DD is gcc-5.2.0). I wasn't able to reproduce your envorioment. Could you
> share a .config file that works with OpenWRT and is able to reproduce
> your problem?

Looks like you've got the wrong recipient for your reply.

While I do run a non-standard OpenWRT build on some of my devices, I 
don't have any problem with Ruby on those boxes. In fact, I don't even 
build Ruby for any of my OpenWRT boxes ;-)

Judging from the linked Github page, you probably wanted to direct your 
comment to @ryzhovau instead of me...

Best regards,

Richard

**Comment by luizluca** [comment]
You are right @rkunze. Thanks. I'll update the text to @ryzhovau.

**Comment by ryzhovau** [comment]
> It seems that you are not using a pure OpenWRT build envorioment. You have a new uclibc-1.0.9 (while CC uses uClibc-0.9.33.2 and DD mostly uses musl) with an old gcc-4.8.5 (the default for CC is 4.8-2014.04 and DD is gcc-5.2.0). I wasn't able to reproduce your envorioment.

I'm using my own toolchain and modified OpenWrt packages. https://github.com/Entware-ng/entware-packages/tree/master/lang/ruby So I should return a favour with this PR:) If you think it's useless, NP, just close it.

>  Could you share a .config file that works with OpenWRT and is able to reproduce your problem?

[Here it is](https://github.com/Entware-ng/Entware-ng/blob/master/configs/mipselsf.config).
 
> It seems that your problem only happens with your setup. The output you sent does not show much as all Make commands are hidden. You can get full gcc cmdline adding to .../lang/ruby/Makefile:
…
That way, you'll see which args got to gcc.

[Here](http://pastebin.com/ykKT4LAJ) is a full build log.

**Comment by luizluca** [comment]
@ryzhovau , now I got what is the problem. Ruby uses LDFLAGS but for binaries only. Libraries uses DLDFLAGS. Both share the opts in XLDFLAGS (included in DLDFLAGS or just after any LDFLAGS ). Blame ruby devs for this. :-)

So, in fact, LDFLAGS is respected, but not for shared libraries. It seems that OpenWRT already included '-L$(PKG_BUILD_DIR)' by default (implicitly) as removing it did not changed the build. The gcc linking command that fails with you is equal to the one that works here. The TARGET_LDFLAGS line is something inherit from oldpackages introduced by [this-commit](http://git.openwrt.org/?p=packages.git;a=commitdiff;h=26f434738a86f1705dad065eb669dbc1b686e8a5;hp=f7a3fb33289cec537cb894567baadbb8a632736c).

Back to your problem: I guess the best point to implant the required opts in CONFIGURE_VARS like:

```
CONFIGURE_VARS += XLDFLAGS="-L$(PKG_BUILD_DIR)"
```

And removing the TARGET_LDFLAGS.

In order to avoid more breaks in the future for other packages, it would be interesting to make your buildenv match what openwrt provides by default.

If you want to update your PR, I'll gladly commit it. Also, you need to inc the RELEASE.

**Comment by ryzhovau** [comment]
Done.

> Back to your problem: I guess the best point to implant the required opts in CONFIGURE_VARS like: 
```
CONFIGURE_VARS += XLDFLAGS="-L$(PKG_BUILD_DIR)"
```

As log as libgmp is in staging dir, I've added:
```
CONFIGURE_VARS += XLDFLAGS="-L$(STAGING_DIR)/usr/lib"
```

**Comment by luizluca** [comment]
@ryzhovau ,

Hum... what you needed is not added '-L$(PKG_BUILD_DIR)' but the '-L$(STAGING_DIR)/usr/lib' which is already include in standard TARGET_LDFLAGS. Sorry for the confusion (what's what you get working overnight).

So, the best solution is to simply copy TARGET_LD_FLAGS to DLD_FLAGS (as you first suggested). 
I also discovered that MAKE_FLAGS does not apply to HOST as there is a special HOST_MAKE_FLAGS for it. However, adding to CONFIGURE is still be best solution:

```
CONFIGURE_VARS += DLDFLAGS="$(TARGET_LDFLAGS)"
```

Concluding, OpenWRT does not like to have "your progress" in history, only the final result. So, you would need to squash all commits into one.

I'm still curious about why your linker (gcc) does not include the staging/usr/lib by default while OpenWRT does. Maybe it is not defined in your gcc specs:

```
staging_dir/toolchain-mipsel_mips32r2_*/lib64/gcc/mipsel-openwrt-linux-*/*/specs
```

**Comment by luizluca** [comment]
@ryzhovau , I created a new PR #2163 that updates ruby and also include what you needed.

**Comment by ryzhovau** [comment]
I forgot about my promise to fix this PR, sorry.

**Comment by luizluca** [comment]
No problem. You just lost the chance of being the author this time ;-)
Could you test the proposed PR to confirm it solves your problem?

**Comment by ryzhovau** [comment]
> Could you test the proposed PR to confirm it solves your problem?

Just checked. No, it doesn't:
```
linking shared-library libruby.so.2.2.0
/home/ryzhovau/Entware-ng/staging_dir/toolchain-mipsel_mips32r2_gcc-4.8.5_uClibc-1.0.9/lib/gcc/mipsel-openwrt-linux-uclibc/4.8.5/../../../../mipsel-openwrt-linux-uclibc/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Makefile:240: recipe for target 'libruby.so.2.2.0' failed
make[3]: *** [libruby.so.2.2.0] Error 1
```

**Comment by luizluca** [comment]
@ryzhovau , just to check, the proposed PR isn't merged yet. Did you copy the makefile or are you using the proposed branch?

**Comment by luizluca** [comment]
You are right again... :-) It does not apply. Ruby Makefile/configure is very confusing...

DLDFLAGS in configure is used to set LIBRUBY_DLDFLAGS (at first). However, LIBRUBY_DLDFLAGS is simply redefined when target is linux (ignoring DLDFLAGS).  And, LIBRUBY_DLDFLAGS is what will define DLDFLAGS in Makefile...

DLDFLAGS and XLDFLAGS behavior seems to vary depending on target/arch. Sometimes it respect what was defined while others don't. And this variants are different for DLDFLAGS and XLDFLAGS for each target! For linux, it is OK as it only appends values. The problem is that DLDFLAGS does not define DLDFLAGS in Makefile (LIBRUBY_DLDFLAGS does). And LIBRUBY_DLDFLAGS does not use DLDFLAGS for linux.

So, let's go with the brute-force approach: XLDFLAGS. At least its values are kept by configure and it is used to define XLDFLAGS in Makefile. The side effect is that it will duplicate all opts when LDFLAGS is used.

I'll fix this

**Comment by luizluca** [comment]
@ryzhovau , could you test it again?

**Comment by ryzhovau** [comment]
Now it's fine.
```
CONFIGURE_VARS += XLDFLAGS="$(TARGET_LDFLAGS)"
```
fixes linkage issue. PR https://github.com/openwrt/packages/pull/2163 is ready to merge.

**Comment by luizluca** [comment]
Thanks @ryzhovau !

**Pull request closed without merging**
