### PR TITLE
[openwrt-21.02] zerotier: update to 10.1.2

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>

Maintainer: me
Compile tested: Nexx WT3020 (ramips/mt7620), OpenWrt v21.02.5
Run tested: TODO

### CODE REVIEW

**Comment by 1715173329** [comment]
Thanks for your work! I will test this version later today.

However, please use `git cherry-pick -x` which allows us easier to track changes (commit history).

For 21.02 branch:
```bash
git cherry-pick -x 2f488873eb2256dacbbc0d4b01fc24a9ea7dd7e8
git cherry-pick -x a5f19e2e83cb650cb2dc090b6e39b680a56ddf9d
git cherry-pick -x 48487a3423cfb060164536e0f5cef8ee935180e4
git cherry-pick -x 9e397926032c8204e5d2a691ace6920eab172b92
git cherry-pick -x 51faaa09f5170825881d61400047db7af19ce3c7
```

**Comment by 1715173329** [comment]
Tested on x86_64, everything is functional.

**Comment by mwarning** [comment]
LGTM

**Comment by 1715173329** [comment]
Merged, thanks!

**Pull request merged**
