### PR TITLE
python packages: move all things python under lang/python

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @kissg1988, @psycho-nico, @mickeprag, @jefferyto, @roger-, @the-alien, @yousong, @smutt, @Shulyaka, @lperkov 
Compile tested: https://github.com/lede-project/source/commit/f7fd2abf259c7a463d215fc0e52c15ae77a050de ar71xx
Run tested: N/A

-------------------------------

I admit this may be be a bit aggressive, but the lang
folder is getting cluttered/filled up with Python, PHP, Perl,
Ruby, etc. packages.

Makes sense to try to group them into per-lang folders.

I took the Pythons.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by Shulyaka** [comment]
It's ok with me

**Comment by smutt** [comment]
I think this is a good idea.

I have an outstanding PR to merge new package lang/python-dpkt.
https://github.com/openwrt/packages/pull/4256

It would be great if someone could merge that PR before making this change. If not I guess will go back and redo that PR.

**Comment by kissg1988** [comment]
Fine with me, too. Hope it won't break anything. :)

**Comment by commodo** [comment]
AFAICT it doesn't yet ; if it does, i'll fix it

**Comment by hnyman** [comment]
Sounds like a good idea. Pure file move/rename should not break anything, so let's merge it.

@commodo 
did you check that the packages are also in the "Python" submenu in the menuconfig instead of "lang" main menu ? That would also make sense. I checked a few of those Makefiles, but did not try to do an exhaustive search.

@smutt 
you need to amend your PR

**Comment by commodo** [comment]
@hnyman 
yep ; packages are in the Python submenu ; and I managed to build them
as i recall, i did a clean build [on ar71xx]

**Pull request merged**
