### PR TITLE
nft-qos: shield meaningless log records

### PR DESCRIPTION
**Pull request by smallprogram**
Maintainer: me
Compile tested: SNAPSHOT
Run tested: SNAPSHOT

Description:
nft-qos: shield meaningless log records

### CODE REVIEW

**Comment by BKPepe** [comment]
The CI is failing for you. Would you mind to take a look at it?

**Comment by smallprogram** [comment]
> The CI is failing for you. Would you mind to take a look at it?

Got it, I’ll check on it and follow up soon.

**Comment by smallprogram** [comment]
@BKPepe workflows awaiting approval

**Comment by smallprogram** [comment]
@BKPepe workflows awaiting approval

**Comment by smallprogram** [comment]
@BKPepe I feel like I'll never pass the Test Formalities

**Pull request closed without merging**
