### PR TITLE
golang: Update to 1.11.1, add mips64 / mips64el builds

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me
Compile tested: ar71xx / armvirt (32, 64) / malta (be, le, be64, le64) / ramips (mt76x8) / x86 (legacy, 64), OpenWrt sdk 2018-10-09 (trunk for malta)
Run tested: malta (le, be64, le64)

Description:
Go 1.11 added [softfloat support for 64-bit MIPS systems](https://golang.org/doc/go1.11#mips), so this also adds builds for mips64 and mips64el.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
Basic tests on malta-le worked fine, but for malta-be64 and malta-le64 I was stopped by golang/go#15416. (Even `go version` throws this error.) Because the error is a goroutine panic and not something like a segfault, I believe it should still work on real mips64/mips64el hardware (which unfortunately I don't have any to test with).

**Comment by hnyman** [comment]
@jefferyto 

Buildbot does not seem to like this.

http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/golang/compile.txt

http://downloads.lede-project.org/snapshots/faillogs/x86_64/packages/golang/compile.txt


```
Building target Go first stage
Building Go cmd/dist using /var/lib/buildbot/slaves/weimar/x86_64/build/sdk/staging_dir/hostpkg/lib/go-cross.
# runtime
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:64:2: bucketCntBits redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:64:18
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:65:2: bucketCnt redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:65:23
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:69:2: loadFactorNum redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:69:18
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:70:2: loadFactorDen redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:70:18
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:76:2: maxKeySize redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:76:17
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:77:2: maxValueSize redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:77:17
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:82:2: dataOffset redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:85:4
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:91:2: empty redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:91:19
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:92:2: evacuatedEmpty redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:92:19
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:93:2: evacuatedX redeclared in this block
	previous declaration at ../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/hashmap.go:93:19
../../../../staging_dir/hostpkg/lib/go-cross/src/runtime/map.go:93:2: too many errors
Makefile:270: recipe for target '/var/lib/buildbot/slaves/weimar/x86_64/build/sdk/build_dir/target-x86_64_musl/go-1.11.1/.built' failed
make[3]: *** [/var/lib/buildbot/slaves/weimar/x86_64/build/sdk/build_dir/target-x86_64_musl/go-1.11.1/.built] Error 2
time: package/feeds/packages/golang/compile#0.73#0.79#1.80


```

**Comment by jefferyto** [comment]
@hnyman thanks for the heads up. Looks like the previous host Go isn't removed completely and is interfering with the updated host Go. I'm testing a fix (and an update to 1.11.2), should be ready soon.

**Comment by jefferyto** [comment]
Should be fixed in #7325.

**Pull request merged**
