### PR TITLE
net/mwan3: add me as co maintainer

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @Adze1502
Compile tested: --
Run tested: --

Description:
Maintainer does not answer on my PR since months.
So I added me (@feckert) as a co maintainer.

### CODE REVIEW

**Comment by champtar** [comment]
@feckert did you try to contact @Adze1502 directly by mail?

**Comment by feckert** [comment]
@champtar no i have not contact him directly via mail. I always highlighted him with @Adze1502.
If I will be highlight I always get an mail from github.
I will contact him per mail.

**Comment by champtar** [comment]
@feckert thanks
He might have a filter rule for github mail?

**Comment by Adze1502** [comment]
Yes, please add @feckert as maintainer. Please feel free to do anything with mwan3 package as you please, to make it better or more suitable to the LEDE community!

For what it's worth: sorry i did not respond sooner to any outstanding github/mwan3 issues. I'm no longer using OpenWrt nor developing on it. So if you please, you could make @feckert  the only maintainer if he pleases.

**Pull request merged**
