### PR TITLE
sqlite3: Fix compilation with glibc

### PR DESCRIPTION
**Pull request by neheb**
Missing linker flag.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1 
Compile tested: mvebu, arc700

Tested with musl, uClibc-ng, and glibc.

### CODE REVIEW

**Comment by micmac1** [comment]
Hi Rosen,

LGTM but I wonder if instead we should add it in general (not just for glibc) and maybe add "-ldl".

https://www.sqlite.org/howtocompile.html

https://www.musl-libc.org/faq.html

Will check tomorrow.

Regards,
Seb

**Comment by neheb** [comment]
Probably not. Extra linking increases file size (Not sure if -Wl,--as-needed works around this). Flags of this form are used throughout the tree for ICONV_FULL for example.

**Comment by micmac1** [comment]
On Sun, May 19, 2019 at 03:33:39PM -0700, Rosen Penev wrote:
> Probably not. Extra linking increases file size (Not sure if
> -Wl,--as-needed works around this). Flags of this form are used
> throughout the tree for ICONV_FULL for example.

I don't think it does. The binaries in ipkg-install are a bit bigger.
But the binaries in ipkg-mips_24kc (for example) are the same size.
Those are the binaries that end up on the target devices. libpthread and
libdl also never show up in the ELF headers.

I'll check how things go on uclibc tonight. I think we should line the
LDFLAGS to CONFIG_SQLITE3_THREADSAFE and
CONFIG_SQLITE3_DYNAMIC_EXTENSIONS respectively.

**Comment by micmac1** [comment]
Also no difference on uclibc. glibc still compiling. Will continue
tomorrow.

Thanks,
Seb

**Comment by micmac1** [comment]
I cannot reproduce this. I spun up a master build for target i386 generic using glib as libc. sqlite detected automatically that it needed to link in libpthread and libdl and added the correct linker flags. That being said I would prefer not to double the flags by forcing them into TARGET_LDFLAGS. Is there maybe something wrong with you builder?

**Comment by neheb** [comment]
I tried again. Cannot reproduce either. Will close.

**Comment by neheb** [comment]
Spoke too soon. I reproduced it. Requires wiping build_dir/sqlite and deselecting thread safe library in the options. Looks like it's not being deselected properly.

**Comment by micmac1** [comment]
Oh, OK, thanks. Will check that.

**Comment by micmac1** [comment]
I think this is a bug in sqlite.c. configure sets SQLITE_THREADSAFE=1 if --enable-threadsafe is given. So not in the case which we're talking about here. Then we run into the following, starting in 13082.
```
#if !defined(SQLITE_THREADSAFE)
# if defined(THREADSAFE)
#   define SQLITE_THREADSAFE THREADSAFE
# else
#   define SQLITE_THREADSAFE 1 /* IMP: R-07272-22309 */
# endif
#endif
```

THREADSAFE is *not* defined so we run into "else". Then SQLITE_THREADSAFE is set to 1. Next we run into this block in line 16020:

```
#if !SQLITE_THREADSAFE
# define SQLITE_MUTEX_OMIT
#endif
#if SQLITE_THREADSAFE && !defined(SQLITE_MUTEX_NOOP)
#  if SQLITE_OS_UNIX
#    define SQLITE_MUTEX_PTHREADS
#  elif SQLITE_OS_WIN
#    define SQLITE_MUTEX_W32
#  else
#    define SQLITE_MUTEX_NOOP
#  endif
#endif
```
SQLITE_MUTEX_NOOP is not defined and bang, SQLITE_MUTEX_PTHREADS gets defined, which leads to pthreads getting used.

This doesn't look sound to me.

Remember that we are talking about libpthread. If we say "--disabled-threadsafe" we should _not_ need libpthread. Due to the above this won't work. And we shouldn't sweep this under the rug by adding "-lpthread". Also because then we won't be able to drop the libpthread dep when CONFIG_SQLITE3_THREADSAFE is off (which we don't do right now, but we really should).

I'd suggest that we remove the threadsafe choice from the Makefile until this is fixed upstream. What do you think?

**Comment by micmac1** [comment]
I also checked why it seemingly works when one has threadsafe enabled, compiles the pkg, then turns threadsafe off and recompiles without "clean". The object files aren't touched anymore. The remain unchanged. So PKG_CONFIG_DEPENDS causes a rerun of configure, but the objects don't get compiled again. This looks like another bug.

**Comment by neheb** [comment]
I have no issue with getting rid of the threadsafe option.

**Comment by micmac1** [comment]
OK good. I'm waiting for a forum user to confirm a patch is working for an arm endian issue. Will post a PR for both once I get confirmation.

**Pull request closed without merging**
