### PR TITLE
aircrack-ng: use libnl-genl

### PR DESCRIPTION
**Pull request by commodo**
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
@ZeroChaos-

**Comment by ZeroChaos-** [comment]
we need both libnl and libnl-genl, not just genl (afaik)

**Comment by commodo** [comment]
lbnl-genl also pulls libnl[-core]

**Comment by commodo** [comment]
also, the [build failure](http://buildbot.openwrt.org:8010/broken_packages/ar71xx/aircrack-ng/compile.txt) may be caused by the fact that the pkgconfig file points to `$(STAGING_DIR)/usr/include/libnl3`, and libnl installs the headers in `$(STAGING_DIR)/usr/include/libnl`
(my fault for this)

there is a patch on the openwrt mailing list that will fix this (from Bruno Randolf)

**Comment by ZeroChaos-** [comment]
while libnl-genl deps on libnl, it is always better to explicitly specify deps.  there are a lot of reasons for this, but I don't expect you will need more than my polite request to set both as deps ;-)

**Comment by commodo** [comment]
I thought you weren't aware of this.
Will re-spin.

**Comment by ZeroChaos-** [comment]
ACK love it.  thanks

FYI, the reason to always dep on things you use is that it cuts down on ambiguity and prevents dep changes down the line from breaking things.  There are also some parallel install package manager issues which likely wouldn't matter in openwrt but may matter significantly with more advanced package managers.

**Comment by ZeroChaos-** [comment]
(I have no commit powers but this is good to go if someone can hit the button please)

**Comment by ZeroChaos-** [comment]
thanks @sbyx !

**Pull request merged**
