### PR TITLE
forked-daapd: update to 26.1

### PR DESCRIPTION
**Pull request by ejurgensen**
Signed-off-by: Espen Jürgensen espenjurgensen+openwrt@gmail.com

Maintainer: Espen Jürgensen / @ejurgensen
Compile tested: Yes, ar7xxx
Run tested: No

Description:
Update 25.0 -> 26.1

### CODE REVIEW

**Comment by ejurgensen** [comment]
Build seems to fail because protobuf-c does not build, which is due to issue #6031.

@jsiverskog can you fix the Makefile?

**Comment by hnyman** [comment]
still fails.

**Comment by ejurgensen** [comment]
Looks like it is now avahi that doesn't build? I tried to reproduce with a completely virgin Ubuntu Trusty, like Travis uses, but it built just fine. Since the Travis logs don't have much detail I'm not sure where to go from here?

**Comment by hnyman** [comment]
It can simply be a timeout in Travis
Let's try merging, and see if the buildbot itself succeeds.

**Comment by hnyman** [comment]
At least the first target succeeded, so likely it is ok.

forked-daapd_26.1-1_arm_cortex-a8_vfpv3.ipk | 254.4 KB | Sat Jun  9 09:18:50 2018

**Pull request merged**
