### PR TITLE
rsync: update to 3.2.0

### PR DESCRIPTION
**Pull request by neheb**
Disable several options to enable compilation.

Simplified several configure options.

Remove pointless configure var.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @mstorchak 
Compile tested: ath79 arc700

### CODE REVIEW

**Comment by mstorchak** [comment]
The PR looks good in general, but rsync-3.2.1 has been already released, which requires `--disable-asm` on ath79.
Also, -4/-6/--ipv4/--ipv6 seems to not work properly with ssh:
```
root@vortex-box:~# /tmp/rsync -6 -vvv -aPzz user@localhost:/etc/passwd .
opening connection using: ssh -l user -4 localhost rsync --server --sender -vvvlogDtpre.iLfxCIv --new-compress . /etc/passwd  (12 args)
WARNING: Ignoring unknown option -4
user@localhost's password:
```
I propose to disable this hinting, please see this patch: https://gist.github.com/mstorchak/c781e67ea6be79e77b9507d883fbc87e

**Comment by neheb** [comment]
Is that with dropbear?

**Comment by mstorchak** [comment]
Yes, and fortunately dropbear ignores -4/-6. Note that even if I pass -6 to rsync, ssh runs with -4.

**Comment by mstorchak** [comment]
Yes, and fortunately dropbear ignores -4/-6. Note that even if I pass -6 to rsync, ssh runs with -4.

**Comment by mstorchak** [comment]
It looks configure can't detect ipv6 support on musl: `checking ipv6 stack type... unknown`

**Comment by mstorchak** [comment]
https://bugzilla.samba.org/show_bug.cgi?id=10715

I'll check if the attached patch is applicable to 3.2.1...

**Comment by mstorchak** [comment]
@neheb , please give a try to this patch https://gist.github.com/mstorchak/0fa4ef4f5b3e89462dc37ffde5ade9d7
It applies on top of #12605

**Comment by mstorchak** [comment]
@neheb, please see https://github.com/neheb/packages/pull/1

**Comment by neheb** [comment]
Applied here. Couldn't see a better solution.

**Comment by mstorchak** [comment]
LGTM.
Thank you, @neheb !

**Pull request merged**
