### PR TITLE
Micropython : update to 1.22 and fix compile on external mbedtls3

### PR DESCRIPTION
**Pull request by orangepizza**
Maintainer: Jeffery To <jeffery.to@gmail.com>
Compile tested:  x86_64, main
Run tested: x86_64, master
Description:
upstream version already uses mbedtls 3.5.1, but config mismatch bring some mbedtls2 only Macros from somewhere
update to 1.22.0 as bonus too

### CODE REVIEW

**Comment by neheb** [comment]
second commit title has a space after micropython.

**Comment by orangepizza** [comment]
I found it need deeper patch because compiled image broke anything has tls13: will make second one
(Doe github allows close a PR and make a new one from same branch?)

**Comment by neheb** [comment]
I believe if you delete it on github and then repush it that works.

**Comment by Neustradamus** [comment]
Replaced by:
- https://github.com/openwrt/packages/pull/24664
- https://github.com/openwrt/packages/pull/25184

Linked to:
- https://github.com/micropython/micropython/issues/14447
- https://github.com/openwrt/packages/pull/23795

**Pull request closed without merging**
