### PR TITLE
ddns-scripts: bump to version 2.7.5

### PR DESCRIPTION
**Pull request by chris5560**
Maintainer: me
Compile tested: DD trunk 
Run tested: DD trunk x86 and WNDR3800

Description:
- commands to apply changes introduced during release changes, moved from Makefile postinst to /etc/uci-defaults/ddns
- do not break execution if using nslookup and force_ipversion=1
- add support of knsupdate (update_nsupdate.sh
- url update easydns.com
- add some service answers
- alphabetic reorder services files for easier reading
- rename services/provider (Makefile postinst handle /etc/config/ddns)

1. freedns.afraid.org -> afraid.org
2. free.editdns.net -> editdns.net
3. domains.google.com -> google.com
4. spdns.de -> spdyn.de
5. strato.de -> strato.com

- new provider (looking in deep into https://sourceforge.net/projects/inadyn-mt project)

1. dyn.com (= dyndns.org)
2. ddnss.de
3. dhis.org
4. dnspark.com (IPv4 only)
5. dynsip.org (IPv4 only)
6. dynv6.com
7. joker.com (IPv4 only)
8. loopia.com (= loopia.se)
9. sitelutions.com (IPv4 only)
10. system-ns.com (IPv4 only)

- new provider (looking in deep into /etc.defaults/ddns_provider.conf file for Synology DiskStation published at https://gist.github.com/ntrepid8/6653274)

1. able.or.kr (IPv4 only)
2. ddo.jp (IPv4 only)
3. dnsmadeeasy.com (IPv4 only)
4. oray.com (IPv4 only)

- new provider (looking in deep into https://github.com/ipfire/ddns project)

1. all-inkl.com
2. desec.io
3. domopoli.de (IPv4 only)
4. opendns.com (IPv4 only)
5. udmedia.de
6. xlhost.de (IPv4 only)

- new provider (looking in deep into https://github.com/yaddns/yaddns project )

1. dyndns.it (IPv4 only)

Signed-off-by: Christian Schoenebeck <<christian.schoenebeck@gmail.com>>

### CODE REVIEW

**Comment by hnyman** [comment]
I wonder about the usage of "postinst" to do one-time changes with sed to the old config file. Using uci-defaults would look more natural to me. 

I think that postinst will work for those who install the package to router with a snapshot firmware and have an existing config. But I think that private builds with ddns-scripts embedded in the firmware will not see the effects of the change, as postinst is run while compiling the firmware and not after the flash when seeing the existing old config, right?

**Comment by chris5560** [comment]
During package update the existing config is not overwritten. That's right.
But renaming services inside services files needs to change settings inside existing configurations.
I want grant that an existing config still working after package update.
So postinst is doing the job.
Or do you think to better put sed's into init script?

**Comment by hnyman** [comment]
My point, apparently unclear, was that I think that using postinst does miss all those who compile a private build with ddns-scripts included and then sysupgrade with old settings preserved. 

Afaik, postinst is run at the firmware image preparation phase and at the package installation phase (when you manually install the package), but there is no execution point in sysupgrade after restoring the old settings.

I feel that uci-defaults would be the correct place to do this kind of one-time "change the old settings" things.

**Comment by chris5560** [comment]
@hnyman 
thanks for your advice
I implement script inside uci-defaults also called during package update inside postinst

**Comment by hnyman** [comment]
One more round of nitpicking:
I think that there is no need to explicitly call uci_defaults from the ddns package's postinst function, as the default_postinst already does that both in LEDE and in Openwrt trunk since May. See  
* https://git.lede-project.org/?p=source.git;a=blob;f=package/base-files/files/lib/functions.sh;h=232a1c4ed250a71ffe7a78f3864d415a49b94550;hb=HEAD#l219
* https://github.com/openwrt/openwrt/blob/master/package/base-files/files/lib/functions.sh#L211

Commit explanations (from LEDE):
* https://git.lede-project.org/?p=source.git;a=commitdiff;h=9b9c78e071469313566473984fb79f54c1881c10;hp=f6adbdf3cdb8ce0d5a730575cab797ced956a59e
* https://git.lede-project.org/?p=source.git;a=commitdiff;h=7f6945829640e82dadf928c9e214470fa0c5a321;hp=749d4b77bdbf0b31b9e15c42207ae448ac45c7d9

You might test deleting that explicit call. (I don't think that it actually hurts, but it is likely unnecessary)

(Sad note: I just noticed that in Openwrt trunk the same patch has been applied twice, so /lib/functions.sh default_postinst contains the "run uci-defaults" code two times :-(   And the code in Openwrt is the first version without the later patch from Jow

**Comment by hnyman** [comment]
I merged it.

One thing that you might need to enhance in the next version: 
The current code may cause /etc/config/ddns to get unnecessarily edited by 'sed' after each subsequent firmware flash due to uci-defaults being re-run after each flash. I am not quite sure, but it looks like that may happen. uci is smart and does not edit unnecessarily, but sed is likely a brute-force tool.

You might first evaluate the need for changes e.g. by grep for "freedns.afraid.org" and then use 'sed' only if needed. 

Or you might take the 'adblock' approach, where the config file is rather similar as it defines the blocklists. There the config has a separate version number that is evaluated at the service startup and depending on the seriousness of the config change, the user may be either 
* prompted in the log to update his config and the service startup is breaked, or 
* notified about "partially outdated config" and is encouraged to update his config.

**Comment by chris5560** [comment]
@hnyman
thanks.

scripts inside uci-defauls run once at reboot or package update and are deleted afterwards, so I think it's not a big deal to sed without grep.

Am 27.09.2016 um 10:32 schrieb Hannu Nyman:

**Pull request merged**
