### PR TITLE
zerotier: update to 1.4.4

### PR DESCRIPTION
**Pull request by mwarning**
Maintainer: me
Compile tested: openwrt master
Run tested: rampis, nexx wt3020, program starts, soft link to config file is created

### CODE REVIEW

**Comment by mwarning** [comment]
@ian-droid

**Comment by ian-droid** [comment]
> @ian-droid local.conf is usually to big to put it into one line. I added a file link now for local.conf now.

That's great, thanks!

**Comment by diizzyy** [comment]
Please squash PR. Regarding binary size, you might want to try LTO (```-flto```).

**Comment by mwarning** [comment]
@diizzyy -flto did not have any effect.

**Comment by mwarning** [comment]
I just noticed that 1.4.4 changed the license to a commercial license (https://github.com/zerotier/ZeroTierOne/releases/tag/1.4.4).

Does that mean that the package has to be pulled? I have opened a ticket and hope that things become clearer: https://github.com/zerotier/ZeroTierOne/issues/1027

**Pull request merged**
