### PR TITLE
antfs: patch for linux >= 5.8.0

### PR DESCRIPTION
**Pull request by lipnitsk**
Signed-off-by: Ilya Lipnitskiy <ilya.lipnitskiy@gmail.com>

Maintainer: @neheb @dengqf6 
Compile tested: mt7621, linux 5.10

### CODE REVIEW

**Comment by neheb** [comment]
Interesting. I wonder if paragon will make an out of tree module for their driver.

**Comment by neheb** [comment]
ping @klukonin There's a version 7.21.

**Comment by lipnitsk** [comment]
Yeah I tried 7.21 but it didn't bring any new changes... But yeah, looks like the Paragon driver is [on its way](https://lore.kernel.org/lkml/20210128090455.3576502-1-almaz.alexandrovich@paragon-software.com/#r), probably for 5.12.

**Comment by neheb** [comment]
I wonder how hard it would be to backport.

**Comment by lipnitsk** [comment]
Probably easier to port to 5.10 than to 5.4 :) So maybe when we switch away from 5.4 completely?

**Comment by dengqf6** [comment]
https://github.com/LGA1150/ntfs3-oot

**Comment by dengqf6** [comment]
I'd like to abandon ANTFS and use NTFS3 instead.

**Comment by lipnitsk** [comment]
We could merge this to fix antfs until it is removed from the modules completely, how does that sound?

**Comment by neheb** [comment]
lol kernel 5.10 isn't even in the tree.

@dengqf6 that port is...newer than when you posted. strange.

**Comment by lipnitsk** [comment]
Strange indeed, maybe https://aur.archlinux.org/packages/ntfs3-dkms/ is a better source - it is based directly on the patchset. Although `readahead` patching (https://github.com/LGA1150/ntfs3-oot/commit/3fbb0e8e01145982515798055ee360eb7fce36a5) will be needed for older kernels.

**Comment by neheb** [comment]
@dengqf6 just looked. antfs is in master only and not in 19.07. Might as well abandon it before release.

**Comment by 1715173329** [comment]
> @dengqf6 that port is...newer than when you posted. strange.

The owner used git rebase so...

**Comment by klukonin** [comment]
@neheb I can update my fork.

**Comment by 1715173329** [comment]
Maybe it's more reasonable to backport the patches directly than introduce a 3rd-party fork?

**Comment by klukonin** [comment]
Well. There are no any changes between 07.19 and 07.22 as I can see.

**Comment by klukonin** [comment]
So if it's a semi-stable code, why not?

**Comment by neheb** [comment]
@1715173329 there's a difference between the packages feed and base. base will almost certainly not accept such a thing. Which leaves an out of tree module for the packages feed.

**Pull request merged**
