### PR TITLE
lighttpd: update to lighttpd 1.4.63 release hash

### PR DESCRIPTION
**Pull request by gstrauss**
Maintainer: @flyn-org
Compile tested: mips_24kc OpenWrt 21.02

Description:
lighttpd: update to lighttpd 1.4.63 release hash

depend on libpcre2 instead of libpcre
also remove patches incorporated upstream into lighttpd 1.4.62

Signed-off-by: Glenn Strauss <gstrauss@gluelogic.com>

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Again this x86 cryptodev stuff. :S
```
 make[4]: Entering directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.82'
make[5]: *** No rule to make target '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12/ioctl.o', needed by '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12/cryptodev.o'.  Stop.
make[4]: *** [Makefile:1822: /home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12] Error 2
make[3]: *** [Makefile:27: build] Error 2
make[2]: *** [Makefile:61: /home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12/.built] Error 2
make[4]: Leaving directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.82'
make[3]: Leaving directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12'
make[2]: Leaving directory '/home/build/openwrt/feeds/base/package/kernel/cryptodev-linux'
time: package/feeds/base/cryptodev-linux/compile#0.98#0.55#1.46
    ERROR: package/feeds/base/cryptodev-linux failed to build.
make[1]: *** [package/Makefile:116: package/feeds/base/cryptodev-linux/compile] Error 1
make: *** [/home/build/openwrt/include/toplevel.mk:223: package/lighttpd/compile] Error 2
make[1]: Leaving directory '/home/build/openwrt'
Error: Process completed with exit code 2.
```

**Comment by gstrauss** [comment]
Relabelling to draft.  A crashing bug has been reported in lighttpd 1.4.62 and is under investigation, so please hold off on this PR for now.

**Comment by gstrauss** [comment]
lighttpd 1.4.63 addresses a memory issue in (recently released) lighttpd 1.4.62, which occurred when config used url.rewrite* or url.redirect with %0, %1, %2, etc in the substitutions targets.

@flyn-org please approve

**Review by BKPepe — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
ping @flyn-org

**Comment by flyn-org** [comment]
Looks good. Recommend merge.

Thank you, @gstrauss!

**Pull request merged**
