### PR TITLE
3proxy: Add to repo

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: (Needs one)
Compile tested:
mt7621, D-Link DIR-860L, OpenWrt Master
octeon, EdgeRouter Lite, OpenWrt Master

Run tested: 
mt7621, D-Link DIR-860L, OpenWrt Master
octeon, EdgeRouter Lite, OpenWrt Master

Description:
Add 3proxy to repo

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
I'm struggling with adding plugins without breaking things, any ideas if it's possible without making another Makefile? These end up in the same dir as the binaries however they should go elsewhere...

@pprindeville any ides? :-)

I've seen a few requests for 3proxy so I figured I'd give it a go.
In the end it probably also needs fancy init.d script(s) too.

**Comment by pprindeville** [comment]
Adding _other_ plugins than the ones in the initial commit?

**Comment by diizzyy** [comment]
Guess I need to be more specific. :-)
They get compiled but I can't figure out a working solution to actually install those either as separate packages or (perferably) with 3proxy itself.

**Comment by pprindeville** [comment]
Okay, let's start with what `build_dir/target-*/3proxy-92b3dd8/ipkg-*` looks like?

**Comment by diizzyy** [comment]
```
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-3proxy
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-ftppr
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-mycrypt
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-pop3p
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-proxy
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-smtpp
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-socks
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-tcppm
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-udppm
```

**Comment by pprindeville** [comment]
Sorry, I meant `ls -lR`.

**Comment by diizzyy** [comment]
```
build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc:
total 36
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-3proxy
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-ftppr
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-mycrypt
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-pop3p
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-proxy
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-smtpp
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-socks
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-tcppm
drwxr-xr-x 4 diizzy diizzy 4096 May  7 23:15 3proxy-udppm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-3proxy:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-3proxy/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 232 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-3proxy/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-3proxy/usr/bin:
total 184
-rwxr-xr-x 1 diizzy diizzy 187495 May  7 23:15 3proxy

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-ftppr:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-ftppr/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-ftppr/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-ftppr/usr/bin:
total 48
-rwxr-xr-x 1 diizzy diizzy 46103 May  7 23:15 ftppr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-mycrypt:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-mycrypt/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 233 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-mycrypt/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-mycrypt/usr/bin:
total 16
-rwxr-xr-x 1 diizzy diizzy 12507 May  7 23:15 mycrypt

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-pop3p:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-pop3p/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-pop3p/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-pop3p/usr/bin:
total 40
-rwxr-xr-x 1 diizzy diizzy 37891 May  7 23:15 pop3p

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-proxy:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-proxy/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-proxy/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-proxy/usr/bin:
total 64
-rwxr-xr-x 1 diizzy diizzy 62611 May  7 23:15 proxy

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-smtpp:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-smtpp/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-smtpp/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-smtpp/usr/bin:
total 44
-rwxr-xr-x 1 diizzy diizzy 42067 May  7 23:15 smtpp

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-socks:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-socks/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-socks/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-socks/usr/bin:
total 44
-rwxr-xr-x 1 diizzy diizzy 41999 May  7 23:15 socks

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-tcppm:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-tcppm/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-tcppm/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-tcppm/usr/bin:
total 40
-rwxr-xr-x 1 diizzy diizzy 37879 May  7 23:15 tcppm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-udppm:
total 8
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 CONTROL
drwxr-xr-x 3 diizzy diizzy 4096 May  7 23:15 usr

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-udppm/CONTROL:
total 12
-rw-r--r-- 1 diizzy diizzy 230 May  7 23:15 control
-rwxr-xr-x 1 diizzy diizzy 160 May  7 23:15 postinst
-rwxr-xr-x 1 diizzy diizzy 117 May  7 23:15 prerm

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-udppm/usr:
total 4
drwxr-xr-x 2 diizzy diizzy 4096 May  7 23:15 bin

build_dir/target-mipsel_24kc_musl/3proxy-92b3dd8/ipkg-mipsel_24kc/3proxy-udppm/usr/bin:
total 36
-rwxr-xr-x 1 diizzy diizzy 33779 May  7 23:15 udppm
```

**Comment by diizzyy** [comment]
I don't think there's a way around this issue without writing a new Makefile, at least I haven't been able to figure out another solution.

**Comment by diizzyy** [comment]
Works fine, plugins will be added later if needed.

**Comment by pprindeville** [comment]
Sorry I can't help on the sub-packaging issue.  I get tripped up occasionally by that myself, so I'm not a very good authority...

**Comment by diizzyy** [comment]
@pprindeville 
No worries, it's just one SSL plugin that's not in and it's not the end of the world. :-)

**Comment by diizzyy** [comment]
I'll keep in it my own repo

**Comment by JuniorJPDJ** [comment]
@diizzyy are you going to add this?

**Comment by diizzyy** [comment]
@JuniorJPDJ 
Hi, no... I mainly wanted it in for the simple socks proxy (the ratelimiting was just a bonus) but as it turns out 3proxy locks up after getting a bit hammered. I never bothered to look into whether it's an issue with musl and/or 3proxy and packaged something else instead.

**Comment by JuniorJPDJ** [comment]
I need it for the same reason. Do you have any working alternative @diizzyy ?

**Comment by diizzyy** [comment]
@JuniorJPDJ 
I ended up porting these two as I didn't know which one would work best ;-)
https://github.com/diizzyy/packages/commit/aa207888ab5d4233f9040a9f92fa9ea5180404e4
https://github.com/diizzyy/packages/commit/93c1920b448c8a83a3384361c5d484c390676a35

**Comment by JuniorJPDJ** [comment]
How to add your package feeds to own build?
Do you have in your plans pulling it to main package repo?

**Comment by diizzyy** [comment]
```
cd feeds/packages
curl -O https://github.com/diizzyy/packages/commit/93c1920b448c8a83a3384361c5d484c390676a35.patch
git am 93c1920b448c8a83a3384361c5d484c390676a35.patch
rm 93c1920b448c8a83a3384361c5d484c390676a35.patch
cd ../..
./scripts/feeds update -i
./scripts/feeds update -a
make menuconfig
```

**Comment by JuniorJPDJ** [comment]
@diizzyy and how about plans in pulling it to main package repository?

**Comment by diizzyy** [comment]
Not really, there's something wonky with the socks server which I have no interest in (or time) to debug.
If you want a socks server I'd suggest you look at the following instead:

https://github.com/openwrt/openwrt/tree/master/package/network/utils/dante (in tree)
https://github.com/diizzyy/packages/commit/93c1920b448c8a83a3384361c5d484c390676a35
https://github.com/diizzyy/packages/commit/aa207888ab5d4233f9040a9f92fa9ea5180404e4

**Pull request closed without merging**
