### PR TITLE
ffmpeg: update to 3.2.7

### PR DESCRIPTION
**Pull request by antonlacon**
Maintainer: me & @thess 
Compile tested: mips/ar71xx, x86-64/generic, arm/mvebu, arm/imx6, arm/bcm47xx, LEDE trunk
Run tested: Partial on mips/ar71xx

Description:

This series updates ffmpeg to 3.2.7, cleans up the Makefile and adds some new optimizations. The commits mostly detail what they're doing, but to summarize it removes ./configure that have no affect on our builds. A minor change is made to x86-64 where it is set to not build with limiting size of code as a priority.

Patch 2 removes the parser selection for libffmpeg-audio-dec and libffmpeg-custom to allow ffmpeg's configure script to choose the necessary parsers for the chosen decoders/encoders. I left this patch unsquashed for Ted to look at first.

Patch 3 toggles on LTO for arm and x86-64. Building for mips failed so I will look at it again when gcc6/7 becomes default. I lack the hardware to run test this patch, so I've left it separate for easy revert if buildbots error.

### CODE REVIEW

**Comment by champtar** [comment]
doing some travis tests (closing / reopening)

**Comment by thess** [comment]
@antonlacon - I think we still to pay attention to streaming/multi-media extensions such as SSE, MMX, 3DNOW, etc on some of our supported CPUs. In particular, the AMD Geode LX does not have SSE and i486 configs do not have MMX either. There were a number of these types of CPU issues that we dealt with in libx264 which also spanned a number of ARM cores.

While things will compile OK with these types of options enabled, they definitely will not execute. Neither, do I trust run-time CPU detection to handle these cases.

**Comment by thess** [comment]
On the bright side - this is a good set of updates - thanks.

**Comment by antonlacon** [comment]
My understanding is that every x86 profile, including Geode, is set to soft_float=n. The soft_float test in the Makefile determining whether to use SIMD instructions or runtime detection has been in since September 2016, so it would cover all of the LEDE 17.01 release. I am not aware of any issues regarding ffmpeg failing on those platforms. Is my understanding wrong?

**Comment by thess** [comment]
Let's go with these changes as-is and keep an eye out for crash reports. If I could free up my Alix (Geode LX) system for a day or 2, I could test this out.

In the meantime, we need to check out #4734.

**Pull request merged**
