### PR TITLE
treewide: replace old wiki links

### PR DESCRIPTION
**Pull request by leonghui**
Maintainers: @champtar @nonicknamewasleftforme @yousong
Compile tested: N/A
Run tested: N/A

Description:
Replaced all references to "wiki.openwrt.org" with links to the latest wiki pages.

Signed-off-by: Leong Hui Wong <leonghui@users.noreply.github.com>

### CODE REVIEW

**Comment by BKPepe** [comment]
You need to bump `PKG_RELEASE`.

**Comment by leonghui** [comment]
For minor changes (similar to https://github.com/openwrt/packages/pull/9559), is a `PKG_RELEASE` bump required?

**Comment by yousong** [comment]
> For minor changes (similar to #9559), is a `PKG_RELEASE` bump required?

My understanding is that whatever changes content distributed to user should also bump `PKG_RELEASE`.  If you think the change is so small and do not want to make fuss, just think it like a best practice we follow.

The other thing is that I would recommend using real email address instead of the dummy noreply one of github.

Thanks for working on the issue.  The change on xl2tpd LGTM.

**Comment by leonghui** [comment]
Thanks all for your feedback and review. I bumped `PKG_RELEASE` for all 4 packages and squashed the commits. No further changes made.

**Pull request merged**
