### PR TITLE
tinc: backport  from master modifications 

### PR DESCRIPTION
**Pull request by ErwanMAS**
Signed-off-by: Erwan MAS <erwan@mas.nom.fr>

Maintainer: me 
Compile tested: N/A
Run tested: Linksys WRT1900ACS with 21.02.3 on mvebu/cortexa9 
Description:

backport of :
   - use 'uci_get_state' instead of 'uci -P /var/state get'  ( 440d3c04505719df09e39706e6af7c470a49d458 )
   - add creation of hosts directory for each network configuration ( fb99d50c1edd4be765bef6d55bee26bfb90576b6 )

### CODE REVIEW

**Comment by ErwanMAS** [comment]
@neheb  so 21.02 release are aligned with master and 22.02

**Comment by BKPepe** [comment]
This should not pass the CI check. The commit subject looks wrong.

**Comment by BKPepe** [comment]
Added CI check with formal things into OpenWrt 21.02 - https://github.com/openwrt/packages/commit/29ad225700915998cad973d9919009c925d15944 , you should rebase your branch on top of it.

**Comment by BKPepe** [comment]
Force pushed and corrected, how it should be. Your solution was not correct as the commit subject was empty there was just ``tinc:``, which is not a good for Git history.  Cherry-pick should be done with git cherry-pick -x as it should be clear that it was cherry-picked and from which commit. You had this somehow in the commit description, if you take a look https://github.com/openwrt/packages/commit/4b53cbd44954b56c4efddd7bd8513e04d2e7c441 , but it was in one commit instead of two, but that's just a nitpicking as the commit subject was worse.

If this is fine for you, please let me know and I will merge this.

**Comment by ErwanMAS** [comment]
> Force pushed and corrected, how it should be. Your solution was not correct as the commit subject was empty there was just `tinc:`, which is not a good for Git history. Cherry-pick should be done with git cherry-pick -x as it should be clear that it was cherry-picked and from which commit. You had this somehow in the commit description, if you take a look [4b53cbd](https://github.com/openwrt/packages/commit/4b53cbd44954b56c4efddd7bd8513e04d2e7c441) , but it was in one commit instead of two, but that's just a nitpicking as the commit subject was worse.
> 
> If this is fine for you, please let me know and I will merge this.

Thank you for the fix  , i will know for the future  what i must do .

**Pull request merged**
