### PR TITLE
pigeonhole: fix runtime dependency on dovecot's ABI

### LINKED ISSUE #5062: dovecot: fails to start after upgrade if it uses pigeonhole (Sieve) plugin
Maintainer: @lucize 
Attention Pigeonhole maintainer: @MikePetullo 
Environment: arm_cortex-a9, bcm53xx/generic, LEDE Reboot SNAPSHOT r5102-c5f97c9

Description:

If the Pigeonhole plugin is used with Dovecot, Dovecot fails to start after an upgrade:
```
root@LEDE:/etc/dovecot# /usr/sbin/dovecot
doveconf: Error: Couldn't load plugin /usr/lib/dovecot/modules/settings/libmanagesieve_login_settings.so: Module is for different ABI version 2.2.ABIv32(2.2.32) (we have 2.2.ABIv33(2.2.33.1))
doveconf: Error: Couldn't load plugin /usr/lib/dovecot/modules/settings/libmanagesieve_settings.so: Module is for different ABI version 2.2.ABIv32(2.2.32) (we have 2.2.ABIv33(2.2.33.1))
doveconf: Error: Couldn't load plugin /usr/lib/dovecot/modules/settings/libpigeonhole_settings.so: Module is for different ABI version 2.2.ABIv32(2.2.32) (we have 2.2.ABIv33(2.2.33.1))
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf: protocols: Unknown protocol: sieve
```
Recompiling the Pigeonhole package and then removing and re-installing pigeonhole fixes the issue completely.

It looks like pigeonhole should not be a separate package but rather a compile option for dovecot. Should I suggest a PR?

### PR DESCRIPTION
**Pull request by val-kulkov**
Maintainer: @MikePetullo
Attention dovecot package maintainer: @lucize
Compile tested: bcm53xx, Buffalo WXR-1900DHP, LEDE Reboot SNAPSHOT r5297-bddffc5
Run tested: bcm53xx, Buffalo WXR-1900DHP, LEDE Reboot SNAPSHOT r5297-bddffc5

Description:

Closes #5062. With ABI_VERSION declaration in dovecot's Makefile introduced in PR #5182, pigeonhole plugin will now be rebuilt on every dovecot upgrade. To announce the rebuilt pigeonhole plugin to opkg, introduce a different model of version numbering. The new version numbering now includes both dovecot and pigeonhole plugin version numbers. Therefore, the rebuilt pigeonhole plugin will be visible to opkg whenever dovecot or pigeonhole plugin version changes.

Rename "pigeonhole" to "dovecot-pigeonhole". There are several reasons for renaming the package:

1. pigeonhole is a plugin. There seems to be a convention to name plugins by adding corresponding suffixes to the parent package name, such as lua-\*, luci-\*, php7-mod-\*, perlbase-\*, transmission-\* etc.

2. When named as "dovecot-pigeonhole", the pigeonhole plugin is displayed right next to dovecot in config manager ("make menuconfig") and is therefore highly visible to anyone who explores the available
modules for dovecot.

3. When named as "dovecot-pigeonhole", the package version number consisting of both dovecot and pigeonhole version numbers makes more sense: "dovecot-pigeonhole_2.2.33.2-0.4.20-2" looks more comprehensible than "pigeonhole_2.2.33.2-0.4.20-2", however admittedly both variants
look rather ugly.

Add ManageSieve to the package. Adding managesieve-login and its libraries increases the size of the package by about 11% from 702061 bytes to 781294 bytes on the bcm53xx platform. As dovecot is unlikely to be used on a low-end LEDE/OpenWrt box, the addition of ~80KB to the package size is not likely to make a noticeable difference but it adds the capability to use pigeonhole plugin for dovecot with
systems that talk ManageSieve, such as RoundCube.

Signed-off-by: Val Kulkov <val.kulkov@gmail.com>

### CODE REVIEW

**Comment by lucize** [comment]
I don't use pigeonhole, can't test it but I'm ok with the proposed plan

**Comment by champtar** [comment]
@val-kulkov maybe you should rename the directory also?
ping @MikePetullo

**Comment by champtar** [comment]
@val-kulkov maybe you should rename the directory also?
ping @MikePetullo 
(closing/reopening to trigger Travis)

**Comment by val-kulkov** [comment]
@lucize : it seems to me that the directory name is less significant than the package name. The package name should leave no doubt both to developers and users that it is related to dovecot (a plugin for dovecot). IMO the directory name is fine "as is", because those who need to locate the package Makefile and edit it to fit their needs will very likely have no problem locating it.

**Comment by lucize** [comment]
you misquoted me ? :)

**Comment by MikePetullo** [comment]
Building now to test.

**Comment by MikePetullo** [comment]
I just built and tested this on x86_64. Looks good.

**Pull request merged**
