### PR TITLE
chaosvpn: add compatibility with openssl 1.1

### PR DESCRIPTION
**Pull request by cotequeiroz**
The patch was accepted upstream for the next release.  Also, if you upgrade to the next release (1.19), consider making it to c842faae63b562acc7d989a9cdc815def9ee2ed6 (the attached patch), which is just two commits ahead of 1.19 (the other is just a log message change).

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

Maintainer: @TuxCoder  
Compile tested: ramips/bcm47xx, openwrt master

### CODE REVIEW

**Comment by TuxCoder** [comment]
Ah nice, will also test the patch soon.
Thanks for the update.

**Comment by TuxCoder** [comment]
Tested the package, successfully.

Had a small bug, the path of `ip` has changed from the old to the new LEDE release/17.01,
Old path `/usr/sbin/ip` new path `/usr/bin/ip`.
This can be patched in the `chaosvpn.conf`

Beside that it works perfect.

**Comment by cotequeiroz** [comment]
It needs to be changed, but are you sure it's not `/sbin/ip`.  I've tripled checked it, and at least in master, that's where `ip` lives, and it's pretty standard.  There was a sed that changed it at Package/install time.  I just removed it, but if `/usr/sbin/ip` was used before, it may be better to search for it, so it will still install in older versions.

**Comment by cotequeiroz** [comment]
The change was introduced by commit `cfa5865187`.
`iproute2` does not install `ip` anywhere in `STAGING_DIR`.  There are some header files that started to be installed by the same commit, so we can check for their existence to decide whether or not to patch `chaosvpn.conf`. However, besides being ugly and fragile, this may change in the future.
`[-f $(STAGING_DIR)/usr/include/libgenl.h ] || sed  -i -e 's/"\/sbin\/ip /"\/usr\/sbin\/ip /' $(PKG_BUILD_DIR)/chaosvpn.conf`.  What are your thoughts?  Personally, I would just leave it at `/sbin/ip`.

**Comment by hnyman** [comment]
since that cfa5865187 the correct location is `/sbin/ip`
https://github.com/openwrt/openwrt/commit/cfa58651872f6f7b5cb3fa6897883891d1b28617#diff-9160d6dab6235e3baa39350b00ea4372

Earlier (until 17.01) the location of "ip" depended on the version installed (ip-full in `/usr/sbin`, ip-tiny in `/usr/bin`), while PATH provided a way to allow them to co-exist and the full-version to get run if that was installed. 

Now (in master and 18.06) the same thing is handled via ALTERNATIVES at the package installation and all ip variants install as `/sbin/ip`

**Pull request merged**
