### PR TITLE
python3: fix host compilation with clang

### PR DESCRIPTION
**Pull request by neheb**
Matched rpath parameter with Makefile.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @commodo @jefferyto 
Compile tested: Fedora 32

### CODE REVIEW

**Comment by jjm2473** [comment]
You may check this PR https://github.com/openwrt/packages/pull/13000 (for openwrt-18.06).

**Comment by commodo** [comment]
i run-tested this on x86 [openwrt/openwrt@c90db26](https://github.com/openwrt/openwrt/commit/c90db26e051e4f0e7cd32333b3bd8c94a13d599a)

**Comment by jefferyto** [comment]
@neheb Forgot to ask, would you mind backporting this for 19.07 (and for python 2)?

**Comment by neheb** [comment]
pushed.

**Comment by jefferyto** [comment]
Thanks! :pray:

**Pull request merged**
