### PR TITLE
python: Refresh patches

### PR DESCRIPTION
**Pull request by neheb**
git is intollerant when it comes to fuzz. this fixes it.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @commodo / @jefferyto 

No code changes so no release bump.

### CODE REVIEW

**Comment by commodo** [comment]
AFAIK, git works fine with fuzz ; I guess it depends on settings.
But a periodical fuzz-update is fine.

Thanks for fixing.

**Comment by neheb** [comment]
doesn't for me. eg:

tar -xf Python.tar.xz
git init . && git add . && git commit -m m
git apply 001.patch <-- fails

There's probably a setting to make git tolerant towards fuzz, but by default (on Ubuntu, Fedora, and Cygwin) it is not.

**Comment by commodo** [comment]
> There's probably a setting to make git tolerant towards fuzz, but by default (on Ubuntu, Fedora, and Cygwin) it is not.

That probably varies with distribution. But as I remember, the `patch` tool from OpenWrt's build works relatively ok with fuzz.

**Comment by commodo** [comment]
[LGTM](https://scontent.fdub2-2.fna.fbcdn.net/v/t1.0-9/50589056_2067228833365893_7527438199266738176_n.png?_nc_cat=107&_nc_ht=scontent.fdub2-2.fna&oh=c8fbd979dd2b5188e8161fb07f1ebe4f&oe=5CFD7462)

**Pull request merged**
