### PR TITLE
python/README.md: add notice of deprecation

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @jefferyto , me
Compile tested: N/A
Run tested: N/A

----------------------------------------------------------------

A plan was formulated & proposed.
Let this plan be the law.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
let's notify people on this thread:
https://github.com/openwrt/packages/issues/8520

@diizzyy @BKPepe @commodo @jefferyto @cotequeiroz @neheb

**Comment by BKPepe** [comment]
Fine with me.

**Comment by diizzyy** [comment]
LGTM

**Comment by jefferyto** [comment]
I'm disappointed CircleCI didn't like the change :laughing:

As I mentioned in   [#8520](https://github.com/openwrt/packages/issues/8520#issuecomment-486274050), I'd like to wait a little bit before making this the law :joy:

**Comment by commodo** [comment]
> As I mentioned in [#8520](https://github.com/openwrt/packages/issues/8520#issuecomment-486274050), I'd like to wait a little bit before making this the law joy

ack;
we can wait;

**Comment by commodo** [comment]
let's close PR, until then

**Pull request closed without merging**
