### PR TITLE
emailrelay: Update to 2.0

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @fededim 
Compile tested: ipq806x

### CODE REVIEW

**Comment by fededim** [comment]
May I ask you why you removed the emailrelay-poke executable from package ?

**Comment by neheb** [comment]
It no longer gets built.

**Comment by fededim** [comment]
Due to a new configure arg ?

**Comment by neheb** [comment]
No idea. Maybe it's part of testing now.

**Comment by fededim** [comment]
You added disable-debug to configure args, when CONFIG_EMAILRELAY_SUPPORT_VERBOSE_DBG is true it also adds --enable-debug=yes to configure args, could this lead to some problems with configure ? I'd rather remove the disable-debug flag from configure args

**Comment by neheb** [comment]
oversight. fixed.

**Comment by fededim** [comment]
Ok, the changes are fine for me.

**Comment by tru7** [comment]
does not get built in daily snapshots. Please fix:
Package emailrelay is missing dependencies for the following libraries:
libpam.so.0

**Pull request merged**
