### PR TITLE
tvheadend: update to v4.2.8, remove static ffmpeg

### PR DESCRIPTION
**Pull request by M95D**
Signed-off-by: Marius Dinu <m95d+git@psihoexpert.ro>

Maintainer: @M95D
Compile tested: mvebu (Marvel Armada XP), Linksys WRT1900AC v1 (mamba), OpenWRT latest snapshot, gcc 10 works, gcc 11 works, binutils 2.37 works, full language support doesn't work.
Run tested: same router, OpenWRT r16521-a3c7633ddc. tvheaded used for a few months with USB DVB tuner. UI works, live streaming works, recording works, playback works.

Description:
- version update
- updated 2 patches (no changes in patch code), removed 1 patch (not needed)
- removed static ffmpeg to avoid build errors (and because a router is not usually capable of transcoding)
```
nasmlib/realpath.c: In function 'nasm_realpath':
nasmlib/realpath.c:60:16: error: implicit declaration of function 'canonicalize_file_name' [-Werror=implicit-function-declaration]
   60 |     char *rp = canonicalize_file_name(rel_path);
      |                ^~~~~~~~~~~~~~~~~~~~~~
nasmlib/realpath.c:60:16: warning: initialization of 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
```
- added --nowerror=unused-variable to avoid build errors
```
src/input/mpegts.h:1135:36: error: 'mpegts_listeners' defined but not used [-Werror=unused-variable]
 1135 | static LIST_HEAD(,mpegts_listener) mpegts_listeners;
```

### CODE REVIEW

**Comment by hnyman** [comment]
Note that all automatic test builds fail. Lieky the buildbot would fail, too.

Possibly due to 
```
2021-08-14T15:28:41.5057584Z make[2]: Leaving directory '/home/runner/work/packages/packages/multimedia/tvheadend'
2021-08-14T15:28:41.5066094Z time: package/feeds/packages_ci/tvheadend/refresh#1.53#0.60#1.85
2021-08-14T15:28:41.5075640Z make[1]: Leaving directory '/home/build/openwrt'
2021-08-14T15:28:41.6140054Z Dirty patches detected, please refresh and review the diff
2021-08-14T15:28:43.4003014Z ##[error]Process completed with exit code 1.
```

cc @sairon

**Comment by M95D** [comment]
What is a "dirty patch"? I don't know what that error means. They work fine on my system.

**Comment by hnyman** [comment]
You might try refreshing the patches with ` make package/tvheadend/refresh V=s ` and see if that helps.

Maybe ` make package/tvheadend/{clean,refresh} V=s `

**Comment by hnyman** [comment]
> What is a "dirty patch"?

Also new to me, but googling for "Dirty patches detected" finds this:
https://github.com/openwrt/gh-action-sdk/blob/master/entrypoint.sh#L75-L78

Apparently a message from the OpenWrt QA automatics at Github.
Maybe @aparcar can explain what exactly triggers it.
Ps. That explanation might maybe also added to Contributing.MD

**Comment by M95D** [comment]
I did `make package/tvheadend/refresh V=s` and it just added a timestamp in one of the patches.

**Comment by hnyman** [comment]
Can you please squash the two commits into one.

**Comment by hnyman** [comment]
And please check the new errors found out by the CA buildbot:

```
Package tvheadend is missing dependencies for the following libraries:
libffi.so.7
```

You apparently need to add the libffi depency, or configure it out if that library is not relevant for the app. (sometimes the package configuration scripts too eagerly include unnecessary stuff/functionality)

**Comment by M95D** [comment]
> You apparently need to add the libffi depency, or configure it out if that library is not relevant for the app. (sometimes the package configuration scripts too eagerly include unnecessary stuff/functionality)

I don't know what configure option eliminates the libffi dependency, if any. They are not documented. Disabling stuff may remove important functionality and I can't test them all to see what they do.

**Comment by hnyman** [comment]
I launched the automatic tests again. Check the results in an hour.

You can still rebase the branch.

First checkout master, and git pull it for updating it.
Then checkout this PR branch and "git rebase master", to rebase the branch on top of the updated master. That should get rid on the master-related  merge commits.
Then "git rebase -i HEAD~3" and squash the extra commits.

See https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by hnyman** [comment]
I merged it with 326da3dbbc57

**Pull request closed without merging**
