### PR TITLE
btrfs-progs: remove patch for  xattr.h path

### PR DESCRIPTION
**Pull request by mstorchak**
Signed-off-by: Maxim Storchak <m.storchak@gmail.com>

### CODE REVIEW

**Comment by mstorchak** [comment]
This should be merged with #1933 - this change restores compatibility with xattr from #1933

**Comment by mstorchak** [comment]
@dangowrt , please review

**Comment by mstorchak** [comment]
tested on ar71xx (mkfs.btrfs, btrfs check)

**Comment by mstorchak** [comment]
It does, it's a fix for exactly for this error.

**Comment by thess** [comment]
ping @dangowrt - please review

**Comment by DocMAX** [comment]
it's not clear to me now what to do. can you explain please?

**Comment by mstorchak** [comment]
@DocMAX, I didn't mean anything besides asking here to merge this patch, but since you are asking, you could try to apply it (it's just removes a patch file, so this could be done even without git), try to build it and post a confirmation here it this fixes your issue.

**Comment by mstorchak** [comment]
Fixed by 021c3e119874ba8b7b88b53f69f6b286cbe524d9

**Pull request closed without merging**
