### PR TITLE
libxs: Moddable SDK XS JavaScript Engine Library

### PR DESCRIPTION
**Pull request by bfriedkin**
Signed-off-by: Brian Friedkin brian@moddable.tech

This pull request references #9738

Maintainer: Brian Friedkin / @bfriedkin
Compile tested: (arm_cortex-a9_vfpv3, LINKSYS WRT1900ACS, 18.06.02)
Compile tested: (mips_24kc,GL-AR300M, 18.06.02)
Compile tested: (mipsel_24kc,GL-MT300N-V2, 18.06.02)
Compile tested: (aarch64_cortex-a53, Raspberry Pi 3 Model B+, 18.06.02)
Run tested: (arm_cortex-a9_vfpv3, LINKSYS WRT1900ACS, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)
Run tested: (mips_24kc,GL-AR300M, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)
Run tested: (mipsel_24kc,GL-MT300N-V2, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)
Run tested: (aarch64_cortex-a53, Raspberry Pi 3 Model B+, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)

Description:

This pull request is for a Moddable SDK port of the XS JavaScript engine library to OpenWrt. XS is the JavaScript engine at the core of Moddable applications and tools, designed to run efficiently on resource constrained SoC and microcontroller platforms. This Makefile builds libxs, which is a shared library that contains the XS JavaScript engine. Using the Moddable SDK and XS on OpenWrt allows developers to build and deploy applications written in JavaScript to OpenWrt router and device targets.

https://www.moddable.com

### CODE REVIEW

**Comment by diizzyy** [comment]
From what I can tell DEBUG is enabled by default and overrides toolchain?
https://github.com/Moddable-OpenSource/moddable/blob/public/build/devices/openwrt/targets/make.libxs.mk#L128

I'd also like to see users of this lib before merging it

**Comment by bfriedkin** [comment]
Hello -

Just a quick follow-up to ask if there's anything else I need to provide in order for `libxs` to be merged into this repository. Also, a few more data points:

This release of XS (`libxs`) passes **99.84%** of the language tests and **99.78%** of the tests for built-in objects. The full test262 [conformance results](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Conformance.md) are available in the Moddable SDK repository. XS fully supports the ECMAScript 2018 standard, the same one used in web browsers today.

XS is the first JavaScript engine to implement [Secure ECMAScript](https://blog.moddable.com/blog/secureprivate/), which aligns well with OpenWrt's emphasis on performance, stability and security.

Moddable is also the only embedded engine provider participating in [Ecma TC39](https://www.ecma-international.org/memento/spc.htm), the JavaScript language committee. Moddable joined TC39 to help sure that JavaScript remains a great language for use in embedded.

Moddable helped to form [Ecma TC53](https://www.ecma-international.org/memento/tc53.htm),  a new standards initiative to define standard JavaScript APIs for use in Wearables and IoT. This effort further advances and underscores our goals for open standards shared in common across diverse hardware. Similarly, OpenWrt is very successful in delivering standardized packages that work well on any supported device platform.

Regards,
Brian

**Comment by jefferyto** [comment]
I think what was meant by "users" was, are there other software packages (ideally also waiting to be packaged for OpenWrt) that depend on libxs?

If not, are there individual/corporate users that are already building libxs for OpenWrt for their own use (and so would benefit from a pre-built package)?

**Comment by neheb** [comment]
Closing. It’s problematic to introduce a library with no users.

**Pull request closed without merging**
