### PR TITLE
boinc: Update to 7.20.2

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by mpratt14** [comment]
adding yourself as a maintainer should be done in a separate commit and should be approved by the other maintainers

for just bumping the version, editing copyright years is not necessary

**Comment by mpratt14** [comment]
ping @N30dG 

updating boinc would make the patch in my PR for autotools not necessary

**Comment by AenBleidd** [comment]
@mpratt14, any way to get why patch was applied not clean enough? I can't reproduce this locally on regular linux

**Comment by mpratt14** [comment]
it's hard to catch with so much output from the CI, but it's this

`Refreshed patch 002-hosttypeRespected`

keyword is "refreshed" meaning some lines are offset and it needs to be refreshed

there is a build-target for automatically refreshing patches

`make feeds/packages/net/boinc/refresh`

but I prefer to do it manually

`make feeds/packages/net/boinc/prepare QUILT=1 V=s`

cd into the build_dir of boinc and

`quilt push -f`
`quilt refresh`

until all patches processed then copy that patches directory back to openwrt source patches directory
(but without the "series" file)

**Comment by AenBleidd** [comment]
This seems to be more complicated than I thought before. I'm closing this for now and will open a new PR once I have all this done on my fork. @mpratt14, thanks for the hints.

**Comment by mpratt14** [comment]
@AenBleidd please dont open a new PR, the members dont like that

if you need help with Git or quilt just ask 👍🏼 

basically all you need to do is refresh the patch with `quilt`

test build of boinc is simple:

`make feeds/packages/net/boinc/clean feeds/packages/net/boinc/compile`

all you need to do is run the prepare stage alone with quilt

`make feeds/packages/net/boinc/clean feeds/packages/net/boinc/prepare QUILT=1`

then cd to the build directory

```
cd build_dir
cd target*
cd boinc*
```

and run quilt

```
quilt push -f
quilt refresh
quilt push -f
quilt refresh
....
...
```
then copy the patches in `patches` directory back to `net/boinc/patches` in openwrt/packages

**Comment by mpratt14** [comment]
I don't remember which way works but, you may have to use the symlink as the make target instead of direct path

`make package/feeds/packages/boinc/clean package/feeds/packages/boinc/prepare QUILT=1`

**Pull request closed without merging**
