### PR TITLE
frp: update to 0.37.0

### PR DESCRIPTION
**Pull request by brvphoenix**
Signed-off-by: Van Waholtz <vanwaholtz@gmail.com>

Maintainer: @ysc3839
Compile tested: x86_64
Run tested: x86_64

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@ysc3839 Merge?

**Comment by ysc3839** [comment]
@PolynomialDivision LGTM.

**Comment by PolynomialDivision** [comment]
Okay, thanks. I will test that on my local pc before I merge, since I never saw someone writing functions for defining a package. ;) If that is okay, I will merge.

**Comment by PolynomialDivision** [comment]
Okay, compile tested on ath79. Looks good! :) Thanks for your contribution!

**Pull request merged**
