### PR TITLE
emailrelay: update to v2.4.1

### PR DESCRIPTION
**Pull request by stokito**
Maintainer: @fededim
Compile tested: yes, on Ubuntu amd64

Also please check my #18536

@BKPepe you may be interested

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]

**Comment by stokito** [comment]
Please don't merge it until this fixed https://sourceforge.net/p/emailrelay/bugs/52/
I'll update the PR

**Comment by BKPepe** [comment]
> https://sourceforge.net/p/emailrelay/bugs/52/

Reproduced for Turris OS 6.0.4, which is based on top of the latest OpenWrt 21.02. I think your PR is fine for OpenWrt master, so we can merge this as it is. If you would like to backport your update to the stable releases and be sure that it is compiled, you can open a pull request to the relevant branches.

**Comment by 1715173329** [comment]
would `PKG_FORTIFY_SOURCE:=0` help the build?

**Comment by BKPepe** [comment]
Nope, it doesnt. I already tried that

Dne ne 11. 12. 2022 22:22 uživatel Tianling Shen ***@***.***>
napsal:

**Comment by stokito** [comment]
Maybe that compilation error relates to some gcc or musl version and not related to the ER itself.

@BKPepe could we merge the PR now to the OpenWrt? The ER author anyway have nothing to do here and Turris OS build may came latter.

**Comment by BKPepe** [comment]
Backported to OpenWrt 22.03 branch - https://github.com/openwrt/packages/commit/0dab01d3988c81fff1e31068f5fab1b109cb8288.

**Pull request merged**
