### PR TITLE
python,python3: include host-build.mk in python-host.mk & python3-package.mk

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: LEDE trunk
Run tested: N/A

Description:

Fixes build issues introduced in https://github.com/openwrt/packages/pull/3297

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Thanks. 
Let's hope that this fixes all python-dependent packages that hit the issue.

**Comment by hnyman** [comment]
Looks like python & related packages got fixed and compile ok in buildbot, but python3 now fails in patching sources in the normal compile, although uncompressing and patching source for host-compile was ok..

E.g. https://downloads.lede-project.org/snapshots/faillogs/mipsel_24kc/packages/python3/
host-compile goes ok:
```
make[3]: Entering directory '/data/bowl-builder/mipsel_24kc/build/sdk/feeds/packages/lang/python3'
. /data/bowl-builder/mipsel_24kc/build/sdk/include/shell.sh; xzcat /data/bowl-builder/mipsel_24kc/build/sdk/dl/Python-3.5.2.tar.xz | tar -C /data/bowl-builder/mipsel_24kc/build/sdk/build_dir/target-mipsel_24kc_musl-1.1.15/host/Python-3.5.2/.. -xf - 
[ ! -d ./src/ ] || cp -fpR ./src/* /data/bowl-builder/mipsel_24kc/build/sdk/build_dir/target-mipsel_24kc_musl-1.1.15/host/Python-3.5.2

Applying ./patches/001-enable-zlib.patch using plaintext: 
patching file Modules/Setup.dist
```
but compile fails:
```
make[3]: Entering directory '/data/bowl-builder/mipsel_24kc/build/sdk/feeds/packages/lang/python3'
true
[ ! -d ./src/ ] || cp -fpR ./src/* /data/bowl-builder/mipsel_24kc/build/sdk/build_dir/target-mipsel_24kc_musl-1.1.15/Python-3.5.2

Applying ./patches/001-enable-zlib.patch using plaintext: 
can't find file to patch at input line 14
```
Note the line "true" there instead of the uncompression line in host-compile, although the sources go to different directories (right?).

I got the same result when I tested locally.

**Comment by commodo** [comment]
will look into it
thanks :)

**Comment by commodo** [comment]
shall we move the discussion to https://github.com/openwrt/packages/issues/3430 ?

**Pull request merged**
