### PR TITLE
netbird: Update to 0.33.0

### PR DESCRIPTION
**Pull request by mlsmaycon**
Maintainer: me / @wehagy
Compile tested:  TODO
Run tested: TODO

Description: update NetBird package version to 0.32.0

### CODE REVIEW

**Review by wehagy — CHANGES_REQUESTED** [review]
Thanks Maycon,

Requested changes for the new version, also change the commit and PR title to `netbird: update to 0.33.0`.

I am planning to test the changes as soon as possible, because of the recent changes from `opkg` to `apk`, my automated build and environment need adjustment.

**Comment by mlsmaycon** [comment]
Thanks, @wehagy. I've committed to your suggestions and updated the title. I might also be able to test on Raspberry Pi 5 tomorrow.

**Comment by hnyman** [comment]
You need to squash the 3 commits together to just 1 commit.

And @oskarirauta is mentioned in Makefile as maintainer, but as other have been more active lately, either @wehagy or @mlsmaycon might be mentioned there instead?

**Comment by wehagy** [comment]
> You need to squash the 3 commits together to just 1 commit.

And change commit prefix title to `netbird:` to make CI happy.

> And @oskarirauta is mentioned in Makefile as maintainer, but as other have been more active lately, either @wehagy or @mlsmaycon might be mentioned there instead?

I can open a PR putting myself as a maintainer, to be honest, I haven't done this yet because I am not familiar with the GO language or OpenWrt codebase.

## Compile and run tested

| Package architecture | Target | Subtarget | Brand | Model | Hardware Version | OpenWrt version |
|----------------------|--------|-----------|-------|-------|------------------|-----------------|
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r28146-52b6c92479 |

### Version

- [v0.33.0](https://github.com/netbirdio/netbird/releases/tag/v0.33.0)

## Additional information

`x86_64` running as container with [`incus`](https://github.com/lxc/incus).
Compiled package with container [`sdk`](https://github.com/openwrt/docker), and build `openwrt` image with container [`imagebuilder`](https://github.com/openwrt/docker).

My repo with my automated build can be see here:
- https://github.com/wehagy/openwrt-builder/tree/update/netbird

And my artifacts here:
- https://github.com/wehagy/openwrt-builder/actions/runs/12061741121

Tested-by: Wesley Gimenes <wehagy@proton.me>

**Comment by mlsmaycon** [comment]
@wehagy I've made the changes, but since you did the test I will be more than happy to close this one and wait for your PR.

**Comment by wehagy** [comment]
> @wehagy I've made the changes, but since you did the test I will be more than happy to close this one and wait for your PR.

I don't like to interfere with others PR's, I appreciate your contribution. However, since you've given your permission, you can close this PR. I've opened the PR below to replace the existing one and update `netbird` to version 0.34.0.

- Superseded by: https://github.com/openwrt/packages/pull/25493

**Comment by mlsmaycon** [comment]
> > @wehagy I've made the changes, but since you did the test I will be more than happy to close this one and wait for your PR.
> 
> I don't like to interfere with others PR's, I appreciate your contribution. However, since you've given your permission, you can close this PR. I've opened the PR below to replace the existing one and update `netbird` to version 0.34.0.
> 
> - Superseded by: https://github.com/openwrt/packages/pull/25493
> 
> 

Sounds good, thanks.

**Pull request closed without merging**
