### PR TITLE
dnsdist: fix various build failures

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @James-TR 
Compile tested: ath79
Run tested: I was bored, but not that bored, so no run-testing from me :)

Description:
Hi all,

Since the recent dnsdist update it fails on the build bots, for various reasons. Here's some fix suggestions that should get the build bots going again.

Regards,
Seb

### CODE REVIEW

**Comment by neheb** [comment]
tinycdb still should have $(FPIC), no?

**Comment by micmac1** [comment]
>tinycdb still should have $(FPIC), no?

I was thinking shared lib install. There's also problems with flags, they aren't used rn.

**Comment by micmac1** [comment]
Hi @neheb 

I removed the third commit which removed CDB from dnsdist. I added some commits to take care of the flags and also install the shared lib. And then some commits on top to update deps for dnsdist and postfix (the latter is the only user user of tinycdb that I found).

Please check it out. If you like it we could add tinycdb and postfix maintainers. I could also split up the PR into parts.

**Comment by James-TR** [comment]
Change looks good to me for dnsdist. Didn't think to line split the dependencies... There's a few!

**Pull request merged**
