### PR TITLE
lxc: change maintainer

### PR DESCRIPTION
**Pull request by damirsamardzic**
Description: change maintainer

### CODE REVIEW

**Comment by BKPepe** [comment]
@ratkaj agrees with that?

**Comment by ratkaj** [comment]
@BKPepe, @damirsamardzic ,

I don't agree. Since I am no longer in any way connected to Sartura organization you can change my email to markoratkaj@gmail.com and add yourself as a second maintainer. I don't aprove removing me...

Regards,
Marko Ratkaj

**Review by ratkaj — CHANGES_REQUESTED** [review]
Please change my email to markoratkaj@gmail.com and add yourself as a second maintainer.

**Comment by ratkaj** [comment]
Hi @damirsamardzic. Same as for libuv, email updated in #18206. Feel free to contribute and co-maintain. Will close.

**Pull request closed without merging**
