### PR TITLE
Armsr target support for dmidecode/efivar/efibootmgr

### PR DESCRIPTION
**Pull request by anta5010**
Maintainer: @Noltari @jefferyto @oskarirauta  @1715173329 
Compile tested:  armsr-armv8, 2023-09-20 snapshot 
Run tested: armsr-armv8 (NXP i.MX8plus, Kontron Box), 2023-09-20 snapshot

Description: 
 These packages can be used on Arm SystemReady platforms

### CODE REVIEW

**Comment by oskarirauta** [comment]
I have no hardware available to test this. But start by refreshing patches;
run make package/PACKAGE_NAME/refresh

this fixes package's patches from being dirty, which means that they have some offset.

**Comment by anta5010** [comment]
> I have no hardware available to test this. But start by refreshing patches; run make package/PACKAGE_NAME/refresh
> this fixes package's patches from being dirty, which means that they have some offset.

Thanks I will do that. Although I don't understand why I don't see the issue when build locally.

**Comment by oskarirauta** [comment]
@anta5010 

It is not really an issue; patch can be applied, because patching software supports offset. Cl also supports offset, it's not a problem, but it has been set up to reject _dirty patches_ - when next release on patched software is made available, previous patch might still be relevant and might be possible to be applied again as is, but this time, with small offset. Now, if your patch already has offset, and is accepted as-is, and the next release comes, patches can have too much offset to be applied; and then _refreshing patches_ won't work. So it's not that they wouldn't work, patches just are requested to be _a perfect match_.. Though, this is just my reasoning, ofcourse reason could be different, but for me; this makes sense..

Dirty patches detected in a log file though, could be more explanatory; or documented better, few years back I also was wondering what it does mean, and it took quite some time to find out about refreshing mechanism of patches. But luckily, at least some times, someone will be here explaining it throroughly enough, that even old stubborn like myself realises what that error means :)

Best of luck, but for me this looks pretty solid, yet what I said is still valid on my side; I can't test it. Hopefully someone else can push this forward...

**Comment by anta5010** [comment]
Tested the tools on some boards:
```
root@OpenWrt:/# cat /etc/os-release
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r23995-ce7209bd21"
OPENWRT_BOARD="armsr/armv8"
OPENWRT_ARCH="aarch64_generic"
OPENWRT_TAINTS="no-all"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt SNAPSHOT r23995-ce7209bd21"

root@OpenWrt:/# efivar -l
8be4df61-93ca-11d2-aa0d-00e098032b8c-OsIndications
8be4df61-93ca-11d2-aa0d-00e098032b8c-OsIndicationsSupported
8be4df61-93ca-11d2-aa0d-00e098032b8c-PlatformLang
8be4df61-93ca-11d2-aa0d-00e098032b8c-PlatformLangCodes
8be4df61-93ca-11d2-aa0d-00e098032b8c-VendorKeys
8be4df61-93ca-11d2-aa0d-00e098032b8c-DeployedMode
8be4df61-93ca-11d2-aa0d-00e098032b8c-AuditMode
8be4df61-93ca-11d2-aa0d-00e098032b8c-SetupMode
8be4df61-93ca-11d2-aa0d-00e098032b8c-SecureBoot

root@OpenWrt:/# dmidecode -t 0
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.0 present.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
        Vendor: U-Boot
        Version: 2021.10-rc3-00036-gb2df4857b8
        Release Date: 10/01/2021
        ROM Size: 64 kB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                Selectable boot is supported
                Targeted content distribution is supported
                UEFI is supported
        BIOS Revision: 21.10
```

**Review by pprindeville — APPROVED** [review]
LGTM

**Review by pprindeville — CHANGES_REQUESTED** [review]
Doh... just noticed the `PKG_VERSION` bumps were missing.

**Comment by anta5010** [comment]
> Doh... just noticed the `PKG_VERSION` bumps were missing.

@pprindeville you meant `PKG_RELEASE` bumps, didn't you?

**Comment by pprindeville** [comment]
Please don't merge `master` into your branch.  Use `git pull --rebase origin master` instead.

**Comment by anta5010** [comment]
> Please don't merge `master` into your branch. Use `git pull --rebase origin master` instead.

@pprindeville  Yes, sorry, I didn't notice merging it's default github option. Fixed.

**Review by 1715173329 — APPROVED** [review]

**Comment by 1715173329** [comment]
Ping @oskarirauta for review

**Comment by 1715173329** [comment]
Merged, thank you!

**Pull request merged**
