### PR TITLE
[23.05] netatalk: Update to 4.0.7 (backport)

### PR DESCRIPTION
**Pull request by APCCV**
Maintainer: Antonio Pastor / @APCCV
Compile tested: ipq806x SDK (23.05.3, snapshot)
Run tested: ipq806x - C2600: start server, connect from MacOS, read/write files to home share, create/update TimeMachine backups. File sharing from MacOS 9.2.

Description: Backport of Netatalk to 23.05. Cherry-picked commits:
- 645b04cb4: update to 3.2.0 restore from abandoned packages
- be5ca7d40: update to 3.2.5
- d0abe3d52: update to 4.0.4 using meson build
- 049a055b7: Makefile cleanup for 4.0.4
- 09a2427c2: AppleTalk feature on 4.0.4
- 07efd504a: glib2 dependency fix for 4.0.4
- c487146f173318ffb13dbc25f4c32789ebcfab23: update to 4.0.7

AppleTalk feature tested fully working under 23.05 (provided a separate PR for kernel module is merged too).

### CODE REVIEW

**Comment by APCCV** [comment]
Hmmm.... @Neustradamus we might be too late for this (is 23.05 is still being built?)

**Comment by APCCV** [comment]
Just a friendly push --force to see if tests work.

**Comment by APCCV** [comment]
There we go. All green.
It's not easy being green.

**Comment by Neustradamus** [comment]
@APCCV: Good job!
All the users community will be happy!

**Comment by APCCV** [comment]
@Neustradamus Ha. Nobody but you and I have seen this PR yet. Don't get too excited.

**Comment by APCCV** [comment]
@ OpenWrt maintainers: please merge with 23.05. AppleTalk functionality has issues with DSA images but works beautifully with 23.05. It might be the case that 23.05 is the last release that supports Appletalk.

Note that applies only to AppleTalk feature. AFPD (Apple File Sharing through IP) works great in 23.05, 24.10 & snapshot.

**Comment by APCCV** [comment]
@BKPepe - apologies for the ping... but I would hate to miss the opportunity to get out a fully working AppleTalk daemon on an OpenWrt release. Full disclosure - for that to happen I will also need to PR a change to openwrt (not packages) so kmod-appletalk is also included in 23.05. I will submit that PR once this one is merged.
Even if that second PR for backport is not accepted there is still value with a working AFP daemon in 23.05.
If there is a policy not to proceed with merge given 24.10 is branched already, please close.

**Comment by Neustradamus** [comment]
I hope that it will be possible to add the latest possibility in OpenWrt 23.05.x.
The World needs it.

**Comment by Neustradamus** [comment]
@hauke, @hnyman: What do you think?

**Comment by hnyman** [comment]
> for that to happen I will also need to PR a change to openwrt (not packages) so kmod-appletalk is also included in 23.05. I will submit that PR once this one is merged.

the kmod should be merged first to the main OpenWrt repo, I think, and this PR should depend on that getting accepted.

**Comment by APCCV** [comment]
> merged first to the main OpenWrt repo

Hey, @hnyman, thank you for taking a look. Snapshot and 24.10 are both up to date.

Snapshot - module: 5eb25dddb17fa3cf4958e91dfc9fc868c9eb03ac
Snapshot - package: 07efd504aa565b07d0e2c522c5b4c236b80e0b5f

24.10 - module: b2f3713801c22d496791949877e6466864eaaa41
24.10 - package: 69521178e5147851f7c761fb47b556c2bb25af46

All tested and working on two targets, ipq806x and ath79.

This is the PR for 23.05 package. It can stand alone for AFP support (that part of it doesn't require the module).
I will submit the PR for backport of the module and cross-reference.

**Comment by APCCV** [comment]
PR for appletalk kmod sent... but (apologies for repeating) that is a very much "nice to have" for this package. Netatalk v4 will deliver functioning Apple File Sharing Protocol (AFPD) without the kmod. 
With the kmod it will also deliver a functioning AppleTalk (atalkd).

**Comment by Neustradamus** [comment]
@APCCV: Good job, thanks!
Thanks to @hnyman for merging :)

**Pull request merged**
