### PR TITLE
elektra: Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @haraldg 
Compile tested: mips64

### CODE REVIEW

**Comment by haraldg** [comment]
@markus2330 can you review if this is the right thing to do? I can't match this with https://wiki.openssl.org/index.php/Library_Initialization trivially. Also if we are to add such a patch you will likely want the same code upstream anyway.

**Comment by markus2330** [comment]
Thank you for pinging! @petermax2 is the author of this plugin.

@petermax2 is the right thing to do? Can you create a PR for Elektra doing this?

**Comment by petermax2** [comment]
> is the right thing to do? Can you create a PR for Elektra doing this?

Yes I'll try. But I probably won't have time for it within the next two weeks.

**Comment by neheb** [comment]
@haraldg the document states:

‘’’
The rest of this page discusses initializing the library in 1.0.2. If you are using 1.1.0 or above then you don't need to take any further steps.
‘’’

**Comment by haraldg** [comment]
Rosen Penev writes:
> @haraldg the document states:
> 
> ‘’’ The rest of this page discusses initializing the library in   
> 1.0.2. If you are using 1.1.0 or above then you don't need to take any  
> further steps. ‘’’                                                

Yes, I read that. But "need not" is not the same as "should not" and
AFAICS the code in question is not exactly the most straight forward
default initialization suggested in the document. Thus I feel waiting
for input from the original author is sensible.

This is the kind of change where an ACK from upstream is more important
then an ACK from the maintainer. And upstream should fix this anyway, so
this doesn't even cause any extra work.

**Comment by neheb** [comment]
@haraldg First API is located here: https://github.com/openssl/openssl/blob/6caf7f3aec5484ee65067e9671299d3411565dc1/include/openssl/evp.h#L956

It is only defined before 1.1.0.

second is at: https://github.com/openssl/openssl/blob/7c3a7561b536264b282f604efc959edad18807d7/include/openssl/err.h#L263

Defined only before 1.1.0.

The equivalent OPENSSL_init_crypto calls are called internally by OpenSSL. No explicit initialization is necessary. See: https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_init_crypto.html

**Comment by neheb** [comment]
Upstream merged this.

**Comment by haraldg** [comment]
JFR: Upstream commit is https://github.com/ElektraInitiative/libelektra/commit/dc0beeb38e8f4914b7e411310d984d6c79504a50

In case somebody still waits for this:
Acked-By: Harald Geyer <harald@ccbib.org>

**Pull request merged**
