### PR TITLE
treewide: add conffiles

### PR DESCRIPTION
**Pull request by zhanhb**
Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>
Description: Add conffiles. Keep files when install or upgrade packages

### CODE REVIEW

**Comment by hnyman** [comment]
You have overlooked that the contents of /etc/config are handled as conffiles automatically". 
Adding them should be unnecessary.

Looking at your changes, there seems to be just one actual change related to wifidog-ng. All others are these /etc/config changes.

**Comment by zhanhb** [comment]
```bash
root@router:/usr/lib/opkg/info# ls -1 shadowsocks-libev-config.*
shadowsocks-libev-config.control
shadowsocks-libev-config.list
shadowsocks-libev-config.postinst
shadowsocks-libev-config.prerm
```
There's no conffiles in the list, I'm working SNAPSHOT r13096-c998ae7f0e. Not sure with other versions.
If the package got installed or upgraded. The file `/etc/config/shadowsocks-libev` will be overwrited.

**Comment by zhanhb** [comment]
Install:
```
echo hello > /etc/config/shadowsocks-libev
opkg install shadowsocks-libev-config
cat /etc/config/shadowsocks-libev
```
Upgrade:
```
opkg install shadowsocks-libev-config
echo hello > /etc/config/shadowsocks-libev
sed -i '/Package: shadowsocks-libev-config/{N; s/Version: .*/Version: 0/}'
opkg upgrade shadowsocks-libev-config
cat /etc/config/shadowsocks-libev
```

**Comment by neheb** [comment]
This also needs PLG_RELEASE bumps.

**Comment by zhanhb** [comment]
Done

**Comment by zhanhb** [comment]
Done

**Comment by neheb** [comment]
I've tested gerbera without this. It works as intended. /etc/config/gerbera gets saved across flashes.

**Comment by zhanhb** [comment]
It works as expected across flashes. But won't work if install/upgrade package.

**Comment by neheb** [comment]
Hmmmm a quick grep of the tree shows that 112 packages already do this.

This needs a rebase btw.

**Comment by zhanhb** [comment]
Do I need to create another PR?

**Comment by neheb** [comment]
No, just run

```
git rebase origin/master
git push --force
```

**Comment by zhanhb** [comment]
Done

**Comment by pprindeville** [comment]
> I've tested gerbera without this. It works as intended. /etc/config/gerbera gets saved across flashes.

Sorry, trying to double-check my understanding... Looking at `/lib/upgrade/keep.d/base-files` on my running system:

```
/etc/config/
/etc/config/network
/etc/config/system
/etc/crontabs/
/etc/dropbear/
/etc/profile.d
```

why isn't the `/etc/config/` line adequate on its own (lines 2 & 3 are redundant, aren't they)?

Also don't understand why we have a `Package/base-files/conffiles` section in `package/base-files/Makefile` *and* the file `package/base-files/files/lib/upgrade/keep.d/base-files-essential`.  Do we really need both?

Couldn't we add the latter to the former?  The latter contains:

```
# Essential files that will be always kept
/etc/hosts
/etc/inittab
/etc/group
/etc/passwd
/etc/profile
/etc/shadow
/etc/shells
/etc/shinit
/etc/sysctl.conf
/etc/rc.local
```

**Comment by pprindeville** [comment]
Actually, the contents of my `/lib/upgrade/keep.d/base-files` doesn't match the `Makefile`...

**Comment by neheb** [comment]
I think I'll merge this.

This is already done with other packages.

On opkg upgrade, I believe the result will be opkg creating an x-opkg config file for the default.

**Pull request merged**
