### PR TITLE
phantap: new version

### PR DESCRIPTION
**Pull request by champtar**
Maintainer: me
Compile & run tested: ar71xx GL-AR150 / OpenWrt SNAPSHOT r10675+1-c070662980

Description:
```
This includes a major bug fix (2ed9c76) and some minor fixes/improvements

f104742 phantap-learn: do not use proto for ip neigh
9849b0f phantap-learn: cleanup
159653d Readme.md: update install instructions
ff3acc2 phantap: add support for talking to victim.
2ed9c76 phantap: Fix MAC snat
f6f2d2d Phantap: fix dns configuration
40fa14b phantap: look at DNS response instead of request
0d62deb Improve Readme
```

(running the checks then merging)

### CODE REVIEW

**Comment by diizzyy** [comment]
Can you change commit message to latest commit or something as this repo doesn't tag "versions"?
Also, it would be nice if it could use codeload like the majority of packages.

**Comment by champtar** [comment]
Hi @diizzyy 
If I remember correctly codeload doesn't provide reproducible archive, so I prefer to stay with OpenWrt buildroot git facility.
Just updated the commit title.

**Comment by neheb** [comment]
Neither do honestly. Bugs keep being found.

OTOH local tarballs are smaller.

**Comment by champtar** [comment]
@neheb I haven't heard of PKG_MIRROR_HASH issue for local tarballs, could you point me to a report (i'm curious)
(for codeload not sure it happened either but Github provides no guarantee)

**Comment by champtar** [comment]
@diizzyy @neheb ok to merge ?

**Comment by diizzyy** [comment]
Yes

**Comment by diizzyy** [comment]
@champtar 
You need to search the commit logs, there's no buglist or such afaik. I haven't grepped the tree but the majority of packages uses codeload so I think you can safely assume at this point that it's good enough and much easter to find later if instead of a OpenWrt specific compressed tarball but that's just my personal opinion. Many other distros also rely on codeload instead of spinning their own tarballs fwiw.

@neheb 
Yep, xz vs gz but I think that's a very minor issue in this case ;-)

**Pull request merged**
