### PR TITLE
python: Support building without deprecated APIs

### PR DESCRIPTION
**Pull request by neheb**
Tested with OpenSSL 1.1.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @commodo 
Compile tested: mvebu

Description:
I will not be upstreaming this as I have no idea how the whole process works. I can explain the patch if needed.

### CODE REVIEW

**Comment by neheb** [comment]
Travis failure is due to zlib being compiled with fPIC. I tried adding PKG_ASLR_PIE:=1 but it seems that had no effect on Travis. Let's just assume it's broken :).

**Comment by commodo** [comment]
Will try to take a look over this in the next couple of days.
Upstreaming to Python is not as difficult in other big open-source projects.
One way to try to address this, is to also take a look at Python master [the latest 3.X code] and see what/if they did [to address this] there and backport it.

**Comment by neheb** [comment]
Oh python3 needs something similar.

Seems python doesn't really do pull requests and have some weird system.

**Comment by cotequeiroz** [comment]
They have a couple of open PRs that address this:
https://github.com/python/cpython/pull/3934
https://github.com/python/cpython/pull/3943

**Comment by commodo** [comment]
@neheb 
I sent a few things upstream to Python via Github PRs ; I think they are shifting [or shifting] to Github.
They do use a separate tracking system for bugs though, but it's highly integrated with Github & their CLA stuff.

**Comment by neheb** [comment]
@cotequeiroz while I can adapt my patch to some of the changes, it's probably better to use upstream patches like you do in those two commits. Should I close this?

**Comment by cotequeiroz** [comment]
This should probably be answered by @commodo.   
For the "upstream patches", notice that even though they both tackle the same issue `#30008`, they are not really in sync, and they are apparently, not close to being merged.
I haven't really tested the patches thoroughly, so I can't say they are a better choice.  
As for your patch, the only thing I would change on yours would be the protocol version choice, where you set the minimum version.  You should probably set `SSL_CTX_set_max_proto_version` as well, since they are forcing a specific version.

**Comment by neheb** [comment]
Pushed an updated version anyway.

**Comment by neheb** [comment]
Fair enough. Will close.

One of the commits above is from February. It's probably just inaction on upstream's part since it builds fine with deprecated APIs, which pretty much everyone enables.

**Pull request closed without merging**
