### PR TITLE
nasm: new package

### PR DESCRIPTION
**Pull request by oskarirauta**
Maintainer: me / @oskarirauta
Compile tested: x86-64, recent git
Run tested: x86-64, recent git

Description:
nasm compiler

Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

### CODE REVIEW

**Comment by oskarirauta** [comment]
@dangowrt 

Could you check this out if changes are needed?

**Comment by oskarirauta** [comment]
@neheb or maybe you?

**Comment by hnyman** [comment]
Should this depend on being on x86_64 ?
Seems unnecessary to build it for all the mips and arm targets.

**Comment by oskarirauta** [comment]
@hnyman 

Depending on x86 now...

**Pull request merged**
