### PR TITLE
libs/xmlrpc-c: install pkgconf files

### PR DESCRIPTION
**Pull request by yegorich**
Maintainer: @thess
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software

Description: copy `*.pc` files into the staging directory.

### CODE REVIEW

**Comment by micmac1** [comment]
Hello all,

the pc files point to the wrong locations. Example xmlrpc.pc:

```
Name:        xmlrpc
Description: Xmlrpc-c basic XML-RPC library
Version:     1.54.6

Requires: xmlrpc_util xmlrpc_expat
Libs:     -L/usr/lib -lxmlrpc
Cflags:   -I/usr/include
```

I think this is the cause of some recent compile problems, i.e. rtpengine in telephony, but I guess also some other packages may be affected.

@yegorich can you look at this again? Maybe get the commit the reverted if the paths can't be fixed?

Kind regards,
Seb

**Comment by yegorich** [comment]
@micmac1 I am at this. The fixes [1](https://sourceforge.net/p/xmlrpc-c/code/3203/) and [2](https://sourceforge.net/p/xmlrpc-c/code/3205/) are already upstream.

**Comment by micmac1** [comment]
Thank you!

**Comment by yegorich** [comment]
@micmac1 please check this PR https://github.com/openwrt/packages/pull/23044

**Comment by micmac1** [comment]
Thanks Yegor, with these two commits rtpengine compiles fine again. And
the pc files look OK now.

**Pull request merged**
