### PR TITLE
openzwave: fix gcc7 compile and remove bad patch

### PR DESCRIPTION
**Pull request by ratkaj**
Maintainer: Stijn Tintel <stijn@linux-ipv6.be> / @stintel 
Compile tested: OpenWrt master, brcm2708/bcm2709 & mvebu
Run tested: RPi3 & ClearFog Pro

Description:

Patch 903-no-examples.patch removes MinOZW binary. This is wrong since
install section of openzwave is still using it. We can either remove the
patch or remove install section for openzwave. It seems people are using
this binary so we remove the patch.

After removing the patch the following issue appears with gcc7:
cc1plus: error: -Wformat-security ignored without -Wformat

This is resolved by adding the following to Makefile
TARGET_CPPFLAGS+=-Wno-format -Wno-format-security

Signed-off-by: Marko Ratkaj <marko.ratkaj@sartura.hr>

### CODE REVIEW

**Comment by stintel** [comment]
Both changes are unrelated, so each should go in its own commit.

**Comment by stintel** [comment]
Ah, I didn't get that from the commit message. Just mention that due to removing the patch there now is an error with gcc7 and ...

**Comment by ratkaj** [comment]
@stintel I changed the PR and commit message to make things a bit more clear.

My other pull request fails due to the this issue. 
https://github.com/openwrt/packages/pull/5806

Would you be nice to merge this if all checks pass and there are no more changes you want me to take. I can also merge if it's ok with you. I would like to update my other pull request as well.

**Comment by stintel** [comment]
LGTM - feel free to merge if it takes me too long ;-)

**Pull request merged**
