### PR TITLE
exfat-nofuse: bump to source date 2017-06-20

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: @br101 
Compile tested: malta be, LEDE master
Run tested: QEMU malta be machine, kmod load

### CODE REVIEW

**Comment by yousong** [comment]
v2 <- v1: use makefile assignment of the form `:=` instead of just `=`

**Comment by poranje** [comment]
ExFAT is a proprietary file system from Microsoft for which no official specification has been made public and is encumbered by patents. (see https://en.wikipedia.org/wiki/ExFAT).
In other words: good reasons exist to keep support for ExFAT out of the LEDE/OpenWrt code. We do not want to see the legal department of Microsoft make starting demands (see groklaw.net for some idea what taht could entail).

**Comment by yousong** [comment]
@poranje  To get such topic clarified we will need advice from legal professionals.  If simply maintaining Makefile without distributing binaries is still not acceptable in legal terms, then we will need to remove this package and possibly all other with the `@BUILD_PATENTED` tag in them.

Very likely we will need to disable `CONFIG_BUILD_PATENTED` in the buidlbot default config

**Comment by br101** [comment]
ACK for the maintainer change from me

**Comment by yousong** [comment]
I am merging this for now and will investigate and see further actions are needed.  Thanks for the heads up @poranje , @br101

**Pull request merged**
