### PR TITLE
stubby: enable configuration through uci system

### PR DESCRIPTION
**Pull request by jonathanunderwood**
Signed-off-by: Jonathan G. Underwood jonathan.underwood@gmail.com

Maintainer: @iamperson347
Compile tested: None
Run tested: mips/Lantiq (Homehub 5a)

Description:
This PR moves stubby configuration to using the UCI system. In comparison to the current stubby package, this PR also adjusts the out of the box configuration in the following ways:
* Add more cloudflare resolvers
* ~~Add SPKI data for resolvers~~
* Ensures that stubby is only started when the relevant network interface is fully initialized
* Stores the trust anchor data under /var/lib/stubby
* Places no ulimit on coredumps

This is lightly tested so far. I believe it to be feature complete and ready for review, but the UCI configuration options aren't detailed in the README.md. I wasn't sure if that was even the appropriate place to document them.

I'll leave the commits unsquashed for now for review, but will squash them down for merge.

@EricLuehrsen, @karlp  - it would be great to get your feedback on this.

Note: the scope of this PR doesn't include integration with dnsmasq. Once this feature is merged, I'll submit a follow on PR that integrates stubby and dnsmasq (i.e. stubby  handling the TLS connection, and optionally DNSSEC. DNSMASQ caching, and optionally proxying the DNSSEC validation).

**Still Todo before merge list:**

- [x] Re-instate a default `/etc/stubby/stubby.yml` file
- [x] Add option to use stubby.yml rather than the uci file for config - copy to /var/etc/stubby at start as we do with the generated config
- [x] Add option for log verbosity, and option for passing other command line args (empty by default)
- [x] Document UCI config file options in config file. Be sure to add note about ipv6 listen_address format - ::1 isn't accepted, needs to be 0::1.
- [x] Remove spki keys from default configuration
- [x] Fix bug where empty list still results empty section - move header creation to callback, use global var to determine if header needed
- [x] Update README.md
- [x] Comment out log_level in default config
- [x] Don't set options which are not set in upstream default config. Also don't write default values from init file if these options aren't set in the config i.e. honour upstream unless user explicitly sets the option.

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
> Don't delete this file. Some folks may want to configure raw. Instead add a UCI option (option manual '0') to otherwise bypass the rest of UCI and copy this file in whole to the temporary configuration directory: cp /etc/stubby/stubby.yml /var/lib/stubby/stubby.yml. With that, a jail and other procd instructions stay common.

Good point, will do so in the next day or so. I don't quite understand the last sentence though - the part about the jail. Can you elaborate, @Ericluerhrsen?

**Comment by EricLuehrsen** [comment]
Eventually, we will want to jail stubby. That is, it doesn't get access to resources or files it doesn't need. Either it has a change root option, or procd can enforce one. So write or copy all semi-persistent files in one place to make this easier. Except PID file is created before the jail is locked. Stubby is experimental yet, but change-root and drop-to-user (not root all day) are common behaviors to expect from the cast of developers there.

**Comment by jonathanunderwood** [comment]
Ok, understood, thanks. I am travelling now, but will get to this on Tuesday evening.

**Comment by EnergyMouse** [comment]
Option for controlling log verbosity would be nice. Also it is probably worth to point somewhere that IPv6 localhost must be written as '0::1' because stubby config doesn't like '::1'.
Thanks for you work on this.

**Comment by jonathanunderwood** [comment]
Thanks @EnergyMouse .

> Option for controlling log verbosity or/and extra arguments would be nice. 

Log verbosity option is a great suggestion, will add that. What "extra arguments" did you have in mind?

> Also it is probably worth to point somewhere that IPv6 localhost must be written as '0::1' because stubby config doesn't like '::1'.

Yeah - documentation of the uci file config options is missing. Where's the best place for such information? In the README.md file? That doesn't seem very user-visible.

> Thanks for you work on this.
No problem, am keen to see OpenWRT more secure and private by default - DNS over encrypted link and DNSSEC out of the box is part of that, and stubby is looking like a good route to getting us closer to that.

**Comment by jonathanunderwood** [comment]
To do list:

- [ ] Re-instate a default `/etc/stubby/stubby.yml` file
- [ ] Add option to use stubby.yml rather than the uci file for config - copy to /var/etc/stubby at start as we do with the generated config
- [ ] Add option for log verbosity
- [ ] Document UCI config file options somewhere

**Comment by EnergyMouse** [comment]
> What "extra arguments" did you have in mind?

Option to pass arguments like '-v' or any added in future directly to stubby daemon.

> That doesn't seem very user-visible.

Config is only user-visible and good place in my opinion.

**Comment by saradickinson** [comment]
Hi there, I'm one of the developers of Stubby and it was pointed out to me that this update adds SPKI pins to the Cloudflare server configurations. I would strongly advise *against* doing this. Cloudflare have deliberately not published SPKI pins themselves which means the pins are _not_ guaranteed to remain the same. The management of the SPKI pins is up to the operator and if they haven't committed to keeping the same pins (which Cloudflare haven't) then don't count on them, just use the authentication name.

Since your default is to require authentication then if the pins change, authentication will fail (stubby requires _all_ specified credentials to match).

**Comment by jonathanunderwood** [comment]
> Hi there, I'm one of the developers of Stubby and it was pointed out to me that this update adds SPKI pins to the Cloudflare server configurations. I would strongly advise _against_ doing this. Cloudflare have deliberately not published SPKI pins themselves which means the pins are _not_ guaranteed to remain the same. The management of the SPKI pins is up to the operator and if they haven't committed to keeping the same pins (which Cloudflare haven't) then don't count on them, just use the authentication name.
> 
> Since your default is to require authentication then if the pins change, authentication will fail (stubby requires _all_ specified credentials to match).

Thanks @saradickinson , that's a super helpful clarification of the situation - I had been in two minds over whether it was a good idea to add these by default or not. I'll remove them from the default configuration as you suggest.

Since I have your ear: stubby seems to try to get the dnssec trust anchor at startup, and if it fails, gives up on dnssec validation. Is there any scope for having stubby re-try to get the trust anchor on future lookups? At the moment this PR adds in some trigger code which ensures stubby is only started once the WAN is available in order to avoid this problem, but it would be nice if stubby handled it more robustly. Shall I raise an issue against stubby? Or is this simply out of scope for stubby?

**Comment by saradickinson** [comment]
@jonathanunderwood Please open an issue against the [getdns](https://github.com/getdnsapi/getdns/issues) library for the trust anchor issue, I think your suggestion makes sense but @wtoorop knows that code much better than I do.

**Comment by jonathanunderwood** [comment]
The only remaining work to do is to document the config file. 

However, for some reason the travis task is failing because of commit messages for commits before my changes, so I am not sure what's happening there ?

**Comment by jonathanunderwood** [comment]
A question. Currently the stubby init file has it starting after dnsmasq:

```
START=50
STOP=51
```

Presumably it would be better to start stubby before dnsmasq, and so replace those two lines with

```
START=18
```
Does that seem reasonable @EricLuehrsen ? (the `STOP` seems to be unecessary as far as I can see).

**Comment by EnergyMouse** [comment]
@jonathanunderwood I think it is better not to declare options that are not declared in the default config, like 'tls_connection_retries':
1. Literally no reason to.
2. They can be changed in future releases but people will use your defaults for years.

**Comment by jonathanunderwood** [comment]
> @jonathanunderwood I think it is better not to declare options that are not declared in the upstream default config, like 'tls_connection_retries':
> 
>     1. Literally no reason to.
> 
>     2. They can be changed in future releases but people will use your defaults for years.

Yeah, I ummed and ahhed over that for a while, and had a slight lean towards preferring explicit to implicit and not exposing users to upstream config changes when they think they're restoring old configurations. But really no strong feeling about it, so I'll do as you suggest.

**Comment by EnergyMouse** [comment]
@jonathanunderwood I agree that this is a good reason but for sure if the developers decide to change these options they will have a reason for this. In my opinion is a better to stick with upstream config until you have reasons not to do. You always can ask Sara Dickinson (sara@sinodun.com) for opinion.

**Comment by jonathanunderwood** [comment]
> @jonathanunderwood I agree that this is a good reason but for sure if the developers decide to change these options they will have a reason for this. In my opinion is a better to stick with upstream config until you have reasons not to do. You always can ask Sara Dickinson ([sara@sinodun.com](mailto:sara@sinodun.com)) for opinion.

Yup, on balance, I agree with you, thanks for thinking about it. I'll make the changes you suggest (have added it to the TODO list at the top, but probably won't get to this until the weekend).

**Comment by EnergyMouse** [comment]
@jonathanunderwood
> Although CloudFlare have published SPKI pinsets

They didn't.

**Comment by jonathanunderwood** [comment]
@energymouse thanks for the good suggestions and corrections. Am still working on the read me (more commits to come), but will incorporate those.

**Comment by jonathanunderwood** [comment]
Thanks @EricLuehrsen 

> Many long comments are in the UCI file. The convetion is normally to keep this file uncommented except for occasional uncomment-me to enable. The command line UCI tools delete comments on save; affects LuCI. Make sure README is comprehensive and we can point OpenWrt wiki at it.
> 

Yes; I was intending to have the same info in the README as well - still working on that. I do see other highly commented configs in packages though (uhttpd springs to mind).

> It seems some of the UCI options have long names. Nothing wrong with that, but users will naturally associate long names with advanced options not to be touched. Consider clever meaningful contractions for daily use options.

Well, I've used the same names that the upstream configuration uses. I think consistency with upstream config names is more important than having short names - do you agree?

> 
> Also commits are piling up here with significant rework content. Its probably time to consider `squash` or `fixup` for related commits.

Yeah :) I was planning to squash down at the end of the work. Presumably you want a single commit?

**Comment by jonathanunderwood** [comment]
@EricLuehrsen @EnergyMouse @iamperson347 

All outstanding issue are now resolved, and I have squashed the commits down to a single commit. As far as I can see, this should be merge ready. Please let me know if you spot anything else that needs fixing.

**Comment by jonathanunderwood** [comment]
Ping @EricLuehrsen @EnergyMouse @iamperson347 @karlp - any chance we can move this forward?

**Comment by jonathanunderwood** [comment]
@didbot can we merge this?

**Comment by dibdot** [comment]
@jonathanunderwood Please rebase your commit & I will apply your PR. Thanks!

**Comment by jonathanunderwood** [comment]
@didbot rebased.

**Comment by jonathanunderwood** [comment]
@didbot bumped.

**Comment by dibdot** [comment]
@jonathanunderwood Many thanks for your efforts!

**Comment by jonathanunderwood** [comment]
Thanks @didbot.

**Pull request merged**
