### PR TITLE
safe-search: Dynamic Updates

### PR DESCRIPTION
**Pull request by farmergreg**
Maintainer: me
Compile tested: x86, archer-c7/a7
Run tested: OpenWRT 19.07.5; Install/Uninstall, verified each safe-search dns provider works correctly and is updated correctly. Currently running at four different test sites and is working well.

Description:
Ensure that the best available IP is always used for all supported
safe-search providers. This is accomplished by periodically checking
DNS for the most recent list of IP addresses associated with each
provider. This corrects a problem identified by @dibdot in #13340.

Signed-off-by: Gregory L. Dietsche <gregory.dietsche@cuw.edu>

If possible, I would also like to request commit access so that I can more easily maintain the packages I have in openwrt. Thanks!

### CODE REVIEW

**Comment by neheb** [comment]
ping @aparcar

**Comment by aparcar** [comment]
> ping @aparcar 

What?

**Comment by neheb** [comment]
He wants commit access.

**Comment by aparcar** [comment]
Again, I'm okay with granting more people commit access when we limit access via a CODEOWNER file. Apart from that the rest of @openwrt/package-maintainers shoudl decide.

**Comment by farmergreg** [comment]
However it works out is fine with me. I just saw someplace where it encouraged asking, so I asked since I have a couple of projects in this repo :) CODEOWNER makes a lot of sense to me.

**Comment by farmergreg** [comment]
Just checking in - are there any issues that are preventing this PR from being merged? Thanks!

**Comment by aparcar** [comment]
You're the maintainer. If you say it's fine I'll merge it.

**Comment by farmergreg** [comment]
@aparcar yes, please merge it, thanks!

**Pull request merged**
