### PR TITLE
getdns: update to version 1.5.0

### PR DESCRIPTION
**Pull request by jonathanunderwood**
Maintainer: @iamperson347 
Compile tested: ar71xx-generic, x86_64, master branch
Run tested: x86_64

Description:
Update to new upstream release 1.5.0.

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
@iamperson347 @dibdot It probably makes sense for me to add myself to the maintainers of this package as well as stubby - any objections?

**Comment by iamperson347** [comment]
Hi Jonathan. I've actually put some pull requests in to add you as
maintainer and remove me. I unfortunately haven't had the proper time to
support, and I also have recently moved to different access points that do
not run openwrt. (So I can't test on an actual device.)

On Jan 3, 2019 10:41 AM, "jonathanunderwood" <notifications@github.com>
wrote:

@iamperson347 <https://github.com/iamperson347> @dibdot
<https://github.com/dibdot> It probably makes sense for me to add myself to
the maintainers of this package as well as stubby - any objections?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openwrt/packages/pull/7856#issuecomment-451181399>, or mute
the thread

**Comment by jonathanunderwood** [comment]
@iamperson347 have added a commit to this branch to switch maintainer to me. 

FYI, just in case you're transferring other packages to people, those PRs didn't notify me - you need to use the github username rather than an email address in the comment.

**Comment by jonathanunderwood** [comment]
@didbot anything impeding merging this one?

**Comment by dibdot** [comment]
No! ;-) Just a question: Any special reason why it has not been run tested?

**Comment by neheb** [comment]
Can you take a look at this? https://github.com/openwrt/packages/pull/7522

**Comment by jonathanunderwood** [comment]
OK, this should be ready to merge.

**Comment by ysc3839** [comment]
@jonathanunderwood Version 1.5.2 is released, please update. Or let me make a pull request?
Also stubby v0.2.6.
https://getdnsapi.net/releases/
https://github.com/getdnsapi/stubby/releases

**Pull request merged**
