### PR TITLE
adguardhome: update to v0.107.36

### PR DESCRIPTION
**Pull request by hnyman**
Maintainer: @dobo90 

Update to v0.107.36 to provide compatibility with Go 1.21. 

Current old version v0.107.33 fails in buildbot:
```
go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.
com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet.
```

Upstream Adguardhome has now deprecated Go 1.20 in [v0.107.36](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.36):
> Deprecated :    Go 1.20 support. Future versions will require at least Go 1.21 to build.

Compile testing ongoing for aarch64 (seems to take a while), CI testing in PR.

Run tested: -

### CODE REVIEW

**Comment by hnyman** [comment]
Doesn't compile locally, so a false hope.

Still the same error.
```
Building targets
github.com/quic-go/quic-go/internal/qtls
# github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

**Comment by dobo90** [comment]
@hnyman Can you can reopen the PR an cherry-pick https://github.com/dobo90/packages/commit/80ac8903e7577f97be152d0336fa700ed59a494b on the top? I've tested it on latest master on NanoPi R2S and AdGuardHome works fine.

**Comment by hnyman** [comment]
Would be better if you do a whole new PR by yourself (including the version bump from me).

(I am not using adguardhome myself, but just briefly wanted to test if a simple upstream version bump would be enough to solve the build breakage.)

**Comment by dobo90** [comment]
I've opened https://github.com/openwrt/packages/pull/21882

**Pull request closed without merging**
