### PR TITLE
[18.06] simple-adblock: boot-up optimization

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin stangri@melmac.net

Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.4
Run tested: mvebu, WRT3200ACM, 18.06.4

Description: prevent multiple restarts on boot-up.

### CODE REVIEW

**Comment by stangri** [comment]
Should I put the [18.06] after package-name: in the future?

**Comment by neheb** [comment]
Don't make it a part of the commit title. Only the GitHub PR title.

**Comment by stangri** [comment]
Rosen, should I resubmit?

**Comment by neheb** [comment]
I'd just git commit --amend, remove the leading 18.06, and git push --force

**Comment by stangri** [comment]
Looks like there's been an other commit since then. My git-foo is not that great, I'll close and recommit.

**Pull request closed without merging**
