### PR TITLE
aria2: update to 1.23.0

### PR DESCRIPTION
**Pull request by kuoruan**
Signed-off-by: Hsing-Wang Liao <kuoruan@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
I notice that aria2 was actally imported here by #117 by @obsy while kaloz was still stated as the package maintainer in Makefile. I wonder if either @kuoruan or @obsy should take over aria2 maintainership.

**Comment by kuoruan** [comment]
I am OK.

**Comment by hnyman** [comment]
I think that the easiest thing forward is if @kuoruan takes over maintainership as you seem to have current interest in the package.
* please amend the "update 1.23" commit https://github.com/openwrt/packages/pull/2756/commits/3424ffc8d209140e19d3cd822c82ed499d412c5b to include the maintainer change (or add a new commit)
* I do not like the commit https://github.com/openwrt/packages/pull/2756/commits/35d65352e04755fb16e1142ac910aaae353b241c (aria2: Move Config.in to files) as /files dir is generally for files that go into the final package. Config.in should be  located next the Makefile in the package's main dir (or if there would be several config files, there could be a config subdir). I think  that you should remove that commit.

**Comment by kuoruan** [comment]
OK, modified.

**Comment by hnyman** [comment]
new aria2 v 1.23 seems to be missing a dependency:
```
find /mnt/build-dir/lede-build/mips_34kc/build/sdk/build_dir/target-mips_34kc_musl-1.1.14/aria2-1.23.0/ipkg-mips_34kc/aria2 -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package aria2 is missing dependencies for the following libraries:
libssh2.so.1
make[3]: *** [/mnt/build-dir/lede-build/mips_34kc/build/sdk/bin/packages/mips_34kc/packages/aria2_1.23.0-1_mips_34kc.ipk] Error 1
```
You might fix that.

**Comment by kuoruan** [comment]
OK, I well check that.

**Comment by kuoruan** [comment]
Please check the new pull request #2804 , and I think #2776 can be merged.

**Pull request merged**
