### PR TITLE
v4l2tools: get rid of x264 and vpx

### PR DESCRIPTION
**Pull request by neheb**
Patched as it seems they can't be disabled.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @mpromonet 
Compile tested: ath79

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Maybe some stupid question, but is this a general issue? I remember I had to fix gpsd to not use host library. Using pkg_check_modules should be fine?

(not against this PR just asking)

**Comment by mpromonet** [comment]
Hi,

Maybe the openwrt build system doesnot use the right pkgconfig settings and use the host system. It should have a way settings some cmake variable to detect the target system ?

Best Regards,
Michel.

**Comment by neheb** [comment]
It finds target packages. X264 should not be used.
.

**Comment by mpromonet** [comment]
Hi,

Neither libx264 nor libx265 seems to be package of openwrt, but libvpx is, so it may be interesting to build v4l2tools with it.
I think https://github.com/openwrt/packages/pull/17084 is fixing the build problem describe in issue https://github.com/openwrt/packages/issues/17072. I am verifying this before submitting the PR.

Best Regards,
Michel.

**Pull request closed without merging**
