### PR TITLE
strongswan: Add the eap-dynamic plugin

### PR DESCRIPTION
**Pull request by lowjoel**
Maintainer: @pprindeville @Thermi 
Compile tested: Linksys E8450, aarch64, OpenWrt 23.03.3
Run tested: Linksys E8450, aarch64, OpenWrt 23.03.3, configured the eap-dynamic plugin for both eap-tls and eap-radius.

```
#  swanctl --stats
uptime: 4 seconds, since Feb 27 17:48:31 2023
worker threads: 16 total, 11 idle, working: 4/0/1/0
job queues: 0/0/0/0
jobs scheduled: 5
IKE_SAs: 1 total, 0 half-open
loaded plugins: charon eap-dynamic aes des rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pgp dnskey sshkey pem openssl fips-prf gmp xcbc hmac attr kernel-netlink resolve socket-default connmark farp vici updown eap-identity eap-radius xauth-generic dhcp
```

Description:

This adds the ability to switch between various EAP modes when negotiating a Phase 1 association.

### CODE REVIEW

**Comment by lowjoel** [comment]
I think the powerpc_8540 failure is unrelated to the change, and the others seem to be because I'm adding a new package? Guidance appreciated.

**Comment by BKPepe** [comment]
In the commit description, there should be the reason why you are doing such a change or how the eap dynamic plugin can help others, so we can follow [guidelines for contributing](https://openwrt.org/submitting-patches#submission_guidelines).

**Comment by lowjoel** [comment]
Sorry about that - after checking with the strongswan maintainer it seems like I've misunderstood what the plugin does, so I'll be closing this PR.

**Comment by tarvip** [comment]
@lowjoel what you misunderstood exactly? I also started using `eap-dynamic` plugin, would be nice to have it in upstream.

**Comment by lowjoel** [comment]
@tarvip have a look at https://github.com/strongswan/strongswan/discussions/1574

**Comment by tarvip** [comment]
> @tarvip have a look at [strongswan/strongswan#1574](https://github.com/strongswan/strongswan/discussions/1574). Feel free to open another PR with the right motivation etc in the description though :)

Thanks, yeah, my use case is a bit different indeed. Will try to open another PR.

**Pull request closed without merging**
