### PR TITLE
python-pcapy:Add package python-pcapy

### PR DESCRIPTION
**Pull request by smutt**
Maintainer: Andrew McConachie <andrew@depht.com>
Compile tested: AMD64
Run tested: AMD64

Description:
Pcapy is a Python extension module that interfaces with the libpcap packet capture library. Pcapy enables python scripts to capture packets on the network. 
https://www.coresecurity.com/corelabs-research/open-source-tools/pcapy

### CODE REVIEW

**Comment by hnyman** [comment]
> Hopefully I did it correctly this time. If not, kick me again and I'll fix it. I'm rather Git stupid.

Sorry but no go. There are four commits, one of which is a merge commit.

Advice can be found from https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
Or you can google for "git squash" or "git rebase interactive". E.g. this pops up: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

I can try to explain the commands for you:

* ```  git checkout python-pcapy  ```
* ```  git rebase -i HEAD~4  ```
* then you get an "interactive rebase" screen in an editor that lists the four commits. All lines start with "pick". Leave the first commit as "pick", but change on the other three lines "pick"-->"s" (or "squash").
* Now the four commits get squashed together. An editor will open again, and displays all four commit messages as one. Edit it to have a clear commit message for the enw combined commit. 
   * Title line should be something like "python-pcapy: add new python package to use libpcap"
   * The the short explanation (your description)
   * And finally the signed-of-by line
* Now your ```  git log  ``` should show just one pcapy commit and that should have the new commit message
* You can now update this pull request by doing ```  git push -f ``` to overwrite the old four commits in the Github repo with your new combined commit.

**Comment by smutt** [comment]
Thank you very much for working with me. I really appreciate it. I just 
deleted everything and started over, it seemed easier than figuring all 
this out. Hopefully now everything is kosher.

**Comment by hnyman** [comment]
You should have tried it. The Github PR system is really nice as it enables conversation and offers a really easy way to adjust an already made PR.

**Comment by smutt** [comment]
I really appreciate the time you spent explaining this to me, but I just 
want to code. All this source code control process stuff just frustrates 
me so I always just take the fastest way out.

**Pull request closed without merging**
