### PR TITLE
libglog: Remove libunwind dependency

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @amir-sabbaghi 
Compile tested: mvebu

Buildbots are failing since they have libunwind.

### CODE REVIEW

**Comment by amir-sabbaghi** [comment]
It shouldn't check for host headers in the first place!

@neheb Can you add it as an option?

**Comment by diizzyy** [comment]
While at it, use codeload?

**Comment by neheb** [comment]
Ugh fine.

@amir-sabbaghi I'd rather not. It's simpler to just leave it out. I don't know that there's much of a benefit to having it.

It picks up headers in staging_dir AFAIK.

**Comment by amir-sabbaghi** [comment]
@neheb Ok. I see no problem.
But I do not know how to merge this. I don't have access.

**Comment by neheb** [comment]
@dibdot

**Pull request merged**
