### PR TITLE
unbound: Remove deprecated OpenSSL API

### PR DESCRIPTION
**Pull request by neheb**
This will become pointless once OpenSSL 1.1.1 enters the tree.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @EricLuehrsen 
Compile tested: ar71xx

### CODE REVIEW

**Comment by EricLuehrsen** [comment]
Again this is glossing over symptoms and not addressing root cause. Patch is unnecessary when openssl is built propperly through `.config`. Considering the impending openssl 1.1.1 merge with options to retrograde, I dont know if this change supports the future direction.

**Comment by neheb** [comment]
How is using deprecated APIs not the root cause?

This is useful even with the 1.1.1 merge as it allows using 1.0.2, where the build fails.

**Comment by neheb** [comment]
There are multiple packages with patches that fix deprecated API usage. This is no different.

**Comment by neheb** [comment]
So that API is used in util/net_help which does not seem to be used or installed. I will verify later that this is the case.

**Comment by NeoRaider** [comment]
As far as I can tell, the removal of CRYPTO_set_id_callback breaks locking that is still necessary for multithreaded usage in OpenSSL 1.0.2. Of course, this isn't a problem if the code in question is actually not used at all (which I didn't look into).

My grasp of the situation (which might be inaccurate) is that there are 3 API versions to consider:

* pre-1.0.2: CRYPTO_set_id_callback()
* 1.0.2: CRYPTO_set_id_callback() is deprecated; CRYPTO_THREADID_set_callback()  should be used instead (or build with deprecated APIs and just used the old call)
* 1.1.0+: neither of the calls is necessary anymore; only in this version, removing the calls completely is acceptable

All in all, I think the general approach of replacing the deprecated APIs is a good idea to fix our issues - if it is done properly.

**Comment by neheb** [comment]
Fixed. I used this as an inspiration: https://github.com/pycurl/pycurl/pull/492/commits/a8c923c601d93d4dd246f0552dfddb8adcfd6442

I didn't bother to keep pre-1.0.2 support as it is EOL'd. No support in OpenWrt either.

**Comment by neheb** [comment]
@EricLuehrsen thoughts?

**Comment by EricLuehrsen** [comment]
It _looks_ right. The trick is stress testing it to see if their is a mistake. Again, threaded errors are often random. So the question is should we just commit it, hope, and wait for a complaint? Or do we bail on this PR and wait for openssl 1.1.1 which fixes it all anyway?

**Comment by EricLuehrsen** [comment]
@dibdot @hnyman this seems okay to merge.

**Pull request merged**
