### PR TITLE
mpd changes

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @thess 
Compile tested: malta arc770d

The first one is related to https://downloads.openwrt.org/snapshots/faillogs/arc_archs/packages/mpd/mini/compile.txt

Fixes compilation there. ping @dhewg . Since the conversion to meson, does ICONV_FULL even work properly?

The second relates to this thread: https://forum.openwrt.org/t/mp3-streams-in-mpd-mini/35763/32

Several people are reporting problems with mpd-mini not being able to decode mp3 streams. Because upstream is not merging my patch that fixes mpd-full for legacy x86, mpd-full is unavailable as a solution.

This should be done anyway as libmad is smaller and does not use floating point, making it ideal for softfloat equipment.

### CODE REVIEW

**Comment by dhewg** [comment]
iconv worked in either the full or the stub version, I know because I fixed that specifically: https://github.com/MusicPlayerDaemon/MPD/commit/96a9670c69bb21a9f12643b118d06e27c73f8fbd

But I didn't test with uclibc

**Comment by neheb** [comment]
No way.

uClibc-ng uses the stub. The check in meson is for the libc iconv: https://github.com/MusicPlayerDaemon/MPD/blob/master/src/lib/icu/meson.build#L21

**Comment by neheb** [comment]
Updated the uClibc-ng commit to use boost rounding functions. Sent upstream here: https://github.com/MusicPlayerDaemon/MPD/pull/723

**Comment by neheb** [comment]
Updated to 0.21.19

**Comment by neheb** [comment]
Let's just merge for now. Patch 210 has been upstreamed. These are close.

**Comment by diizzyy** [comment]
@neheb 
This is a bad decision, libmad has been dead upstream for years and extremely slow (see https://reviews.freebsd.org/D22263#491184). mpg123 also supports no FPU platforms just fine.

Like:
```
--with-cpu=generic_nofpu
--with-cpu=ppc_nofpu
--with-cpu=i386_nofpu
--with-cpu=arm_nofpu
```

**Comment by neheb** [comment]
I’ll try to ask the people having mp3 issues with mpd-mini if they are still present.

**Comment by neheb** [comment]
@diizzyy Benchmark on my Archer C7v2:

```
root@OpenWrt:/tmp# time madplay -o null:/dev/null Adele\ -\ Set\ Fire\ to\ the\ Rain\ \(Ember\ Waves\ Remix\).mp3 
11278 frames decoded (0:04:54.6), +2.5 dB peak amplitude, 0 clipped samples
real	0m 6.06s
user	0m 5.69s
sys	0m 0.18s
root@OpenWrt:/tmp# time mpg123 -t Adele\ -\ Set\ Fire\ to\ the\ Rain\ \(Ember\ Waves\ Remix\).mp3 
[4:54] Decoding of Adele - Set Fire to the Rain (Ember Waves Remix).mp3 finished.
real	0m 8.85s
user	0m 8.20s
sys	0m 0.36s
```

libmad may be slower on x86 and ARM, but it seems faster on MIPS.

Maybe there's some way to tweak mpg123 to get better performance...

**Comment by neheb** [comment]
zombie revive. this is on mt7621:

```
root@OpenWrt:/tmp# time madplay -o null:/dev/null Adele\ -\ Set\ Fire\ to\ the\ Rain\ \(Ember\ Waves\ Remix\).mp3
real    0m 10.01s
user    0m 9.88s
sys     0m 0.11s

root@OpenWrt:/tmp# time mpg123 -t Adele\ -\ Set\ Fire\ to\ the\ Rain\ \(Ember\ Waves\ Remix\).mp3
real    0m 24.39s
user    0m 23.50s
sys     0m 0.74s
```

That's...horrible.

**Comment by diizzyy** [comment]
Probably doesn't help in terms of speed
https://github.com/openwrt/packages/blob/master/sound/mpg123/Makefile#L76

There's also --enable-ieeefloat=yes/no but I guess it's not being used for integer decoding

No idea if disabling mips16 makes any difference

**Comment by neheb** [comment]
If I had to guess, libmad decodes to 24-bit, sacrificing some accuracy for speed. I only posted that because I've been doing benchmarks under aarch64 recently. The situation is flipped there.

**Pull request merged**
