### PR TITLE
python-cython: update to version 3.0.7

### PR DESCRIPTION
**Pull request by predators46**
Maintainer:Josef Schlehofer <pepe.schlehofer@gmail.com>
Maintainer:Jan Pavlinec <jan.pavlinec1@gmail.com>
Maintainer:Jeffery To <jeffery.to@gmail.com>
Maintainer:Alexandru Ardelean <ardeleanalex@gmail.com>

Compile tested: armsr
Run tested: armv8

Description:

updating every package that requires the cyhton-3.0.7 dependency I did it in one commit it is not possible to do it in a different commit

I will explain every change I 

made update the version:

python-msgpack ==> requires host cython-3.0.7 
python-zeroconf ==> requires host cython-3.0.7 
python-greenlet ==> updates and adds the hosts that python-gevent needs 
pyproject-metadata ==> adds the pyproject-metadata package that numpy requires
numpy ==> updated to version 1.26.2 and added one patch to prevent numpy from building mesons and removed one deprecated patch 
python-cython ==> update to version 3.0.7

### CODE REVIEW

**Comment by predators46** [comment]
@jefferyto 

What do you think

**Comment by BKPepe** [comment]
No, I dont like this. The previous solution was better and preferred. You can not put everything into the single commit. Why would you do that? it ruins the git history.

**Comment by predators46** [comment]
@BKPepe 

Have you tried making them separate? do packages that depend on cyhton-3.0.7 not fail to build? what about numpy and msgpack and zeroconf? If you just talk, it's easy to say that if you do it, the results will be different

**Comment by BKPepe** [comment]
Seriously are you talking to me, how I should do that? Hmmm. :-) That's great. Of course, I can talk a lot, haha and do that as well. You can look at my history, but lets not be rude here. I bet there are better approach, how you can do it and I am sure you will find it. Don't reinvent a wheel here. It is not necessary.

Let my share what can be done:

**1. One single PR, containing multiple commits**
- Yeah, it works, why dont do that?
- There is nothing wrong with that.

Look how @jefferyto did it in the past. Just check history. Right now, it seems like you are trying to discover new approach and you failed with that.

**2. Open one PR with one commit with one commit, if you take care about your GitHub account and takes credit for that.**
- That's what you did in the past. I fail to see reason, why you decided to do this like you did now. 
- If it fails, because it depends on different PR, yeah, thats expected. You could rebase it.  There is also nothing wrong about that. Thats why do we have labels for that and there is pull request description, where you can see that it depends on other PR. 


Everyone makes mistakes, we are humans, thats expected, but if you are trying to do something, please try to do your best. Like mention GitHub accounts in the PR description instead of copy&pasting emails, no one gets notification for that.

Just my 2c here.

**Comment by predators46** [comment]
@BKPepe 

ok, I get it

**Comment by predators46** [comment]
@BKPepe 

I'm going to open a pull request again because I've done a rebase, I can't reopen the pull request here and the other pull requests that I've closed. I've split up each update and added packages if you don't mind seeing my closed pull request trash

**Pull request closed without merging**
