### PR TITLE
python3: Rebase deprecated API patch against current version

### PR DESCRIPTION
**Pull request by neheb**
Looks like it was changed from when I last applied. Fixes breakage with
several packages.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @commodo / @jefferyto 
Compile tested: mvebu

Fixes https://github.com/openwrt/packages/issues/8399

### CODE REVIEW

**Comment by commodo** [comment]
why not run-tested ?

this patch looks messy enough to actually worth some testing;

i'm starting to believe that this whole deprecated OpenSSL API is not worth the trouble and we should leave it up to upstream Python

**Comment by neheb** [comment]
The whole issue is caused by an wrong patch where

```
int result = 0;
```
was missing.

It's quite unlikely that upstream will fix this, especially for 2.7.

**Comment by neheb** [comment]
Note that the buildbots are failing on bcrypt, python-cffi, python-dateutil, python-pycparser, python-twisted. This fixes them.

**Comment by commodo** [comment]
NAK for this fix.
Let's remove those 2 patches

**Pull request closed without merging**
