### PR TITLE
luajit: Switch to versioned releases

### PR DESCRIPTION
**Pull request by neheb**
Allows to simplify the Makefile

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @milani 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
Buildbots fail, as the Makefile says: *** Requires GCC Multilib on host system to build! ***

**Comment by milani** [comment]
Thanks. I try to build it here to make sure everything works as expected. The build nodes do not support multilib, so no worries.

**Comment by milani** [comment]
LGTM

**Comment by milani** [comment]
@hnyman I built and tested. looks good to me.

**Comment by neheb** [comment]
Rebased. Note that https://github.com/openwrt/packages/pull/5025 is long obsolete and should be closed.

**Comment by hnyman** [comment]
Luajit still fails in buildbot for some targets  (but e.g. x86_64 has been compiled ok)

https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/luajit/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/luajit/compile.txt

```
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[5]: Entering directory '/data/bowl-builder/mips_24kc/build/sdk/build_dir/target-mips_24kc_musl/LuaJIT-2.1.0-beta3/src'
HOSTCC    host/minilua.o
In file included from /usr/include/limits.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:168,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:34,
                 from host/minilua.c:33:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
Makefile:691: recipe for target 'host/minilua.o' failed
make[5]: *** [host/minilua.o] Error 1
make[5]: Leaving directory '/data/bowl-builder/mips_24kc/build/sdk/build_dir/target-mips_24kc_musl/LuaJIT-2.1.0-beta3/src'
Makefile:112: recipe for target 'default' failed
make[4]: *** [default] Error 2
```

**Comment by neheb** [comment]
@hnyman it’s expected. Build bots need 33-bit libraries

**Pull request merged**
