### PR TITLE
mailsend: bump to v. 1.19, add openssl 1.1

### PR DESCRIPTION
**Pull request by cotequeiroz**
Applied a patch merged upstream that adds support to openssl 1.1.0, and added a (cosmetic, really) patch, just submitted upstream, that removed deprecated API.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

Maintainer: @thess 
Compile tested: brcm47xx, WRT 610N, openwrt master
Run tested: brcm47xx, WRT 610N, openwrt master

### CODE REVIEW

**Comment by cotequeiroz** [comment]
Has anybody looked at this?  I'd like to get some feedback, or have this merged.
Cheers

**Comment by karlp** [comment]
I'd rather see the openssl 1.1 support patch in a separate commit to the version bump, as it's not required as part of the version bump, and 1.1 isn't the default (yet) otherwise ok

**Comment by cotequeiroz** [comment]
I've done separate commits, as you proposed. Do you mean a second PR?  Regarding openssl support, my intention is to get the packages ready for it before we make the switch.  The patches add support for openssl 1.1, without removing support for previous versions.

**Comment by karlp** [comment]
This looks good to me now, but i've not tested it in anyway.  Let's let @thess have a bit more time to catch this.

**Comment by cotequeiroz** [comment]
Thanks for your feedback.  I'll wait for @thess.

**Comment by hnyman** [comment]
It has been a month. Let's merge.

**Pull request merged**
