### PR TITLE
luarocks: Allow building luarocks for the host

### PR DESCRIPTION
**Pull request by mrkiko**
ldbus: lua bindings for DBUS

Compile tested on: ramips/mt7621
lede master branch, at commit 1928fc93ced752bd1e304ab3837fb41e7a80b9d9

### CODE REVIEW

**Comment by mrkiko** [comment]
Please let me know what you think of this and if there are any problems.
I'll fix them as soon...

**Comment by hnyman** [comment]
What is the purpose of that host build? Is that host build really needed for building the package itself?

Unnecessary compilations should be avoided, as they may break things in buildbot for some of the ~50 target platforms.

And note that automatic Travis build fails as the commit title is non-standard...
https://travis-ci.org/openwrt/packages/builds/297446563?utm_source=github_status&utm_medium=notification
```
Author name (Enrico Mioso) seems ok
Commit subject line MUST start with '<package name>: ' (Allow building luarocks for the host)
Signed-off-by match author
```

**Comment by mrkiko** [comment]
Hello.
First of all - thank you very much for the review and recommendations.
this isn't necessary to build the package itself, but it can be confortable to help in packaging lua modules using the luarocks module management system.
I plan to package one such module, in a successive pull request. In this case also a Makefile is provided, but I think that due to the extensive use of lua in OpenWRT/LEDE, it makes sense to have a tool like this one available.
I would like to help in making all that's possible to avoid creating any trouble / breaking anything, and for this I ask  for your help. I have a lot to learn.
I am convinced this can be useful.
Am I supposed to close this PR and do another one now?
thank you very much,
Enrico

**Comment by mrkiko** [comment]
Sorry...
PR updated.

Enrico Mioso
Mobile Phone Number: +393807096934 ( +Telegram :) )
My Tox ID is: 7C593F402A3C8632D87AB4B948D492294C39A6A614464ECF843CA3429FB023284180472C7475

I like / recommend the usage of open messaging standards.

**Comment by mrkiko** [comment]
Pull request updated, and this time it seems I got the title right :) .
Wating for suggestions and comments.

**Comment by mrkiko** [comment]
Thank you very much @hnyman for your attention and reply.
I commented / replied, but by mistake I deleted my own comment - I 
intended to delete later ones I guess, but still don't know.

Anyway: I think this is a worth addition, since it may ease porting of 
luacorks-based packages (case in point: ldbus).
It may be avoidable, but given the heavy use of LUA in the OpenWRT/LEDE, I 
think integrating luarocks can be a good thing.
Thank you all for the attention, and waiting on your comments.

**Comment by mrkiko** [comment]
Hello!
This is an updated version of the pull request, and the ci-status is 
eventually successful.
thanks to all.
Waiting on your comments and feedback.

**Comment by mrkiko** [comment]
Compile tested on: ramips/mt7621

**Comment by mrkiko** [comment]
Hello guys.
Still waiting for any comments / notices. If I can do something to improve 
my PR, I would be glad to do so.
thank you very much!

**Comment by mrkiko** [comment]
Hello to everyone of you.
Let me know if I can do anything to improve this PR or if something should 
be fixed / redone.
Thank you very much for your work, and all.

**Comment by champtar** [comment]
making it easier to package luarocks projects seems to be a good thing to me, as lua is a great fit for the small cpu of our routers
@hnyman is your only worry about the host build going wrong? can you details a bit?

**Comment by hnyman** [comment]
> is your only worry about the host build going wrong? can you details a bit?

Yes, and nothing special about that. Just a general question about the necessity of the host build. (As the host binary does not get included in the shipped package, the benefits will go only to those who build luarocks themselves.)

**Comment by champtar** [comment]
@hnyman ldbus use the luarocks host build to build itself (`PKG_BUILD_DEPENDS:=+luarocks/host`)

**Comment by mrkiko** [comment]
Yeah, that was the idea behind adding the host luarocks build.
Any package needing luarocks to build can depend on it and have the luarocks binary ready for use as happens in the ldbus Makefile.
Sorry if I wasn't able to communicate this idea, and thank you very much to all of you guys for your help and patience.

**Comment by mrkiko** [comment]
Thank you very much @champtar ...

**Pull request merged**
