### PR TITLE
[22.03] xfrpc: add xfrpc to 22.03

### PR DESCRIPTION
**Pull request by liudf0716**
add xfrpc to 22.03 branch

Signed-off-by: Dengfeng Liu <liudf0716@gmail.com>

### CODE REVIEW

**Comment by 1715173329** [comment]
no idea why ci fails, have you checked it with SDK-s?

**Comment by liudf0716** [comment]
@1715173329 Yes, I have successfully compiled in my SDK environment.

**Comment by yousong** [comment]
Try bumping version of the workflow action.

```diff
diff --git a/.github/workflows/multi-arch-test-build.yml b/.github/workflows/multi-arch-test-build.yml
index ed5dc366a..f8a907b15 100644
--- a/.github/workflows/multi-arch-test-build.yml
+++ b/.github/workflows/multi-arch-test-build.yml
@@ -87,7 +87,7 @@ jobs:
           echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
 
       - name: Build
-        uses: openwrt/gh-action-sdk@v4
+        uses: openwrt/gh-action-sdk@v5
         env:
           ARCH: ${{ matrix.arch }}-${{ env.BRANCH }}
           FEEDNAME: packages_ci
```

**Comment by 1715173329** [comment]
Whoa, nice catch!

**Comment by liudf0716** [comment]
@yousong Does this mean I don't need to change my PR? Because I can't change the workflow files.

I have a question, cause my PR is just a usual PR without any special feature, why it trigger such ci problem. I doubt there exists something I'm not working properly. 

thank you both for deeply checking the problem!

@yousong @1715173329

**Comment by yousong** [comment]
> @yousong Does this mean I don't need to change my PR? Because I can't change the workflow files.

I'd say just edit the workflow file as a separate commit and update the pull request to give it a try.  I am not sure about the actual cause, but it's worth a try since v5 has explicit intent to match file ownership (chown) with Dockerfile USER.

**Comment by 1715173329** [comment]
v5 should work, I will create a PR for it tonight.

**Comment by aparcar** [comment]
I merged https://github.com/openwrt/packages/pull/20436 please remove the change for this PR again, thank you.

**Comment by liudf0716** [comment]
@aparcar ok

**Comment by 1715173329** [comment]
Could you use `git cherry-pick -x` to backport the existing commits rather than create a new one? It would help us track the commit history.

**Comment by liudf0716** [comment]
@1715173329 thanks

**Pull request merged**
