### PR TITLE
collectd: refactor snmp6

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Getifaddrs() is not working all the time (e.g. wireguard interfaces).
Instead we use if_nameindex() syscall as suggested in:
 https://stackoverflow.com/a/45796495/8474618

Maintainer: @hnyman 
Compile tested: trunk
Run tested: wdr4300 (trunk)

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
I added another changes. We saw now in production some weird stuff happening.

If u compare that:
http://monitor.berlin.freifunk.net/host.php?h=ohlauer-gw&p=snmp6
to
http://monitor.berlin.freifunk.net/host.php?h=ohlauer-gw&p=interface
You see that the is a difference with factor ~10?

I double check that now that the correct values are read. Not sure what is happening.

**Comment by hnyman** [comment]
Any more changes coming?

**Comment by PolynomialDivision** [comment]
> Any more changes coming?

Not now.
The changes are running in production now for 1 day. I definitely read the correct values.

**Comment by PolynomialDivision** [comment]
Please merge. ;)

**Comment by PolynomialDivision** [comment]
@hnyman Tested again with iperf and it is correct. Maybe there are issues with with a wireguard tunnel that has an ip4 endpoint? Further, it is weird that the values are in Byte/s and noch Mbit/s. Not sure if I can convert them somehow in the luci statistics app?

**Comment by PolynomialDivision** [comment]
Okay, I tested again with wireguard interface and local graphs and the plugin is definitely correct! :) The difference is from the web interface plugin... xD

**Comment by hnyman** [comment]
> the values are in Byte/s and noch Mbit/s. Not sure if I can convert them somehow in the luci statistics app?

Sure you can. 
data operations can be applied with RPN (reverse polish notation) format.
(See rrdgraph rrdtool docs upstream)

Just look examples from some other graphs. Ping, nut, chrony, sqm

**Comment by PolynomialDivision** [comment]
> data operations can be applied with RPN (reverse polish notation) format.

Thanks! But now the total value is also in Bit? :/

**Comment by hnyman** [comment]
> the total value is also in Bit?

It is just a number without any unit. It is upto you to give it a sensible unit as label in the graph.

**Comment by PolynomialDivision** [comment]
> > the total value is also in Bit?
> 
> It is just a number without any unit. It is upto you to give it a sensible unit as label in the graph.

I mean it is now multiplied also by 8.

**Comment by hnyman** [comment]
> I mean it is now multiplied also by the factor I give.

The data item that you tell rrdgraph to multiply, gets multiplied according to your instructions both in the graph and in the totals/last labels data table.

**Pull request merged**
