### PR TITLE
adguardhome: update to 0.107.36 and fix compilation with Go 1.21

### PR DESCRIPTION
**Pull request by dobo90**
Maintainer: me
Compile tested: aarch64_generic, NanoPi R2S, OpenWrt SNAPSHOT r23783
Run tested: aarch64_generic, NanoPi R2S, OpenWrt SNAPSHOT r23783

Fixes: https://github.com/openwrt/packages/issues/21866

### CODE REVIEW

**Comment by hnyman** [comment]
Fails for the new patch.
It does not fully apply cleanly, or actually fails the "refresh should not change patch" test.
 
> Now at patch 0001-go-get-github.com-quic-go-quic-go-v0.37.6.patch
> **Refreshed patch 0001-go-get-github.com-quic-go-quic-go-v0.37.6.patch**
> mkdir -p ./patches
> rm -f ./patches/* 2>/dev/null >/dev/null
> '/builder/build_dir/target-aarch64_generic_musl/adguardhome-0.107.36/patches/0001-go-get-github.com-quic-go-quic-go-v0.37.6.patch' -> './patches/0001-go-get-github.com-quic-go-quic-go-v0.37.6.patch'
> make[2]: Leaving directory '/feed/net/adguardhome'
> time: package/feeds/packages_ci/adguardhome/refresh#0.48#0.15#0.57
> make[1]: Leaving directory '/builder'
> **Dirty patches detected, please refresh and review the diff**

You need to do package/adguardhome/refresh, in order to get the patch correctly formatted.
Then you can re-commit and force-push the branch.

**Comment by hnyman** [comment]
Seems t compile now. Thanks.

**Comment by goppinath** [comment]
Please be kind enough to merge these changes to the current stable which is the **OpenWrt 23.03**, because we are waiting for this since last December 2022.

**Comment by hnyman** [comment]
> Please be kind enough to merge these changes to the current stable which is the OpenWrt 23.03 as well, because we are waiting for this since January 2023.

Waiting for what?
Adguardhome in 23.05 has been updated four times in 2023...
(or do you mean 22.03 ?)

Note that Adguardhome 0.107.36 requires Go 1.21, while 23.05 has only 1.20.x and 22.03 has 1.19.x

> Deprecated:   Go 1.20 support. Future versions will require at least Go 1.21 to build.

**Comment by goppinath** [comment]
@hnyman Thank you for the explanation. Yes, it was a typo and I really meant the `current stable the 22.03`. I am waiting for the AdGuard Home update since January 2023. 

The current 22.03 is getting the AdGuard v0.107.21 and by considering the Go version 1.19.x limitation the AdGuard v0.107.24 with the revision [040d00a](https://github.com/openwrt/packages/commit/040d00a2aff108816a71320c5a7cfb1d33ec53c7) can be merged to 22.03.

What is the reason that the OpenWrt versions are bounded to the Go language versions? Is it because of hardware versions or some other dependencies?

This implies that if I always want to have the latest AdGuard then I have to install AdGuard manually and as a consequence the installation won't be preserved after every sysupgrade.

**Comment by hnyman** [comment]
> What is the reason that the OpenWrt versions are bounded to the Go language versions?

It is actually upstream...

https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.36

> Deprecated:     Go 1.20 support. Future versions will require at least Go 1.21 to build.

**Comment by az0** [comment]
> > What is the reason that the OpenWrt versions are bounded to the Go language versions?
> 
> It is actually upstream...
> 
> https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.36
> 
> > Deprecated:     Go 1.20 support. Future versions will require at least Go 1.21 to build.

Go 1.20 is deprecated, so Go 1.20 still works with ADH 0.107.36. It is not until a future version that Go 1.20 will break.

Also, the way I read the question was: "why cannot Go be upgraded in OpenWRT 23.03"? In other words, why not upgrade OpenWRT 23.03 to have Go 1.21?

**Pull request merged**
