### PR TITLE
crun: update to 1.7.2

### PR DESCRIPTION
**Pull request by oskarirauta**
Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

Maintainer: me / @oskarirauta 
Compile tested: x86-64, recent git
Run tested: x86-64, recent git

Description:
[Changelogs](https://github.com/containers/crun/releases)

### CODE REVIEW

**Comment by 1715173329** [comment]
> Please do no longer set _PKG_RELEASE_ to _AUTORELEASE_ as the feature is deprecated. Please use an integer instead. Below is a list of affected packages including correct _PKG_RELEASE_:
> 
> * utils/crun/Makefile: PKG_RELEASE:=2

it should be `1`....

**Comment by oskarirauta** [comment]
> > Please do no longer set _PKG_RELEASE_ to _AUTORELEASE_ as the feature is deprecated. Please use an integer instead. Below is a list of affected packages including correct _PKG_RELEASE_:
> > 
> > * utils/crun/Makefile: PKG_RELEASE:=2
> 
> it should be `1`....

Crap, didn't come to think about it at all, just made it as instructed - I'll fix it..

**Comment by hnyman** [comment]
Fails in buildbot due to missing dependency on a detected library...

E.g.
https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/crun/compile.txt

```
make[4]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-mips64_octeonplus_64_musl/crun-1.7.2'
Package crun is missing dependencies for the following libraries:
libgcrypt.so.20
make[3]: *** [Makefile:90: /builder/shared-workdir/build/sdk/bin/packages/mips64_octeonplus/packages/crun_1.7.2-1_mips64_octeonplus.ipk] Error 1
```

Please either modify package configuration to disable the optional library, or alternatively add the dependency.

**Comment by 1715173329** [comment]
ping @oskarirauta 

https://github.com/containers/crun/commit/dd310aaf5aee336d0f6236c1c2add7b7cb030482
seems like upstream did not provide an option for disabling it.
`+PACKAGE_libgcrypt:libgcrypt` should be okay?

**Comment by hnyman** [comment]
Based on that upstream commit, the libgcrypt library might be always needed, as they seem to install devel libraries on their build env examples?

Then it would make more sense to declare the dependecy to be there always (instead of it being conditional).

**Comment by cotequeiroz** [comment]
It will build without libgcrypt, if you add:
```
CONFIGURE_VARS+= \
        ac_cv_search_gcry_check_version=no
```

It will miss the ability to use a cache for seccomp.bpf:
https://github.com/containers/crun/commit/3ebaba33ef41951b9eb335efa3433be88f52c752

I don't know how important that functionality would be, but it appears to be nice.  I would add a straight dependency for it (plain `libgcrypt`).

Please don't add a dependency with a package selection condition (`+PACKAGE_libgcrypt:libgcrypt`).  If support should be conditional, create a specific option for it.

**Comment by 1715173329** [comment]
Got it, thanks!

**Comment by oskarirauta** [comment]
@1715173329 

Sorry. Notifications didn't get throught. libgcrypt dependency add seems to be merged. Is this or any other issue still active?

**Comment by 1715173329** [comment]
> @1715173329
> 
> Sorry. Notifications didn't get throught. libgcrypt dependency add seems to be merged. Is this or any other issue still active?

It's not a big deal. The issue was gone.

**Comment by oskarirauta** [comment]
@1715173329 thanks..

**Pull request merged**
