### PR TITLE
[18.06] psqlodbc: bump to 10.03.0000, fix --with-unixodbc

### PR DESCRIPTION
**Pull request by neheb**
Update to 10.03.0000.

--with-unixodbc should point to the odbc_config binary, not to the top
of the install directory $(STAGING_DIR)/usr.

Acked-by: Rosen Penev <rosenp@gmail.com>
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

Maintainer: @dangowrt 

Fixes: https://downloads.openwrt.org/releases/faillogs/arm_xscale/packages/psqlodbc/compile.txt

### CODE REVIEW

**Comment by dangowrt** [comment]
Why not jump to 11.00.0000 which is already in master branch?
I suggest you prepare a PR to backport 2bc28eb40c84894f5ec3394656a90f015ee7a70f and 5ec4eb76c3628d64526d30637226c34260b5f004 instead.

**Comment by neheb** [comment]
Added.

**Comment by dangowrt** [comment]
I'm ok with this, but generally think that we should cherry-pick commits from master into 18.06 when ever possible (and in this case it would be possible). In case you want to make it really perfect, really replace those commits with the ones in master and reference them in the commit message (see other commits in openwrt-18.06 branch for reference).

**Comment by neheb** [comment]
These commits are cherry picked from master. Well, the first one I used git format-patch and then git am.

**Comment by dangowrt** [comment]
Nice. It be even nicer to reference the commits in master in each commit message.

**Comment by neheb** [comment]
Went with the kernel.org approach. How's that?

**Comment by dangowrt** [comment]
Term 'upstream' seems inappropriate here, but that's really just details. For consistency, why not use
`    (cherry picked from commit 2bc28eb40c84894f5ec3394656a90f015ee7a70f)` like all other commits in openwrt-18.06 branch?

**Comment by dangowrt** [comment]
Ok, closer look: things are already less consistent than I thought.... I'll merge it like this now. Thanks!

**Pull request merged**
