### PR TITLE
tor: package improvements

### PR DESCRIPTION
**Pull request by rockdrilla**
- remove "torify" script
- tor-geoip: fix "install" recipe
- tor-geoip: honor CONFIG_IPV6
- drop deprecated configure option
- disable unwanted build targets
- build in parallel
- use global hardening configuration
- build with -ffunction-sections, -fdata-sections, --gc-sections and -flto
- update OpenWrt copyright years
- remove trailing whitespace
- bump package version

Compile- and run-tested on ar71xx/generic (TP-Link Archer C7 v2, world-wide version).

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
Works fine so far. @hauke, @tripolar, I'm waiting for your review. If ok, I'll squash all commits into one and rebase PR branch for easier merging.

**Comment by tripolar** [comment]
tor: remove 'torify' script  - why do you remove torify?
tor: use global hardening configuration - why disable all hardening? - with an application like tor a nogo, the file size doesn't matter here
tor: disable unwanted build targets - why? i mean this patch has to be updated on every release and this 1 min in compile time is unimportant

**Comment by tripolar** [comment]
split them up in seperate PRs and i will merge them one by one or we will have to talk about them :)

**Comment by rockdrilla** [comment]
1) For now, torify is just a wrapper around torsocks, which is absent in OpenWrt distribution (AFAIK).
2) Ok, i'll revert that commit.
3) This patch is pretty simple, so keeping it up to date is easy task. These unwanted build targets are tests, fuzzing, etc irrelevant binaries. If we'll keep them _**and**_  enable GCC LTO, then compile time and memory pressure during build will increase drastically (i've already tested this case).

So, i'm waiting your reply about 1) and 3).

PS: my further work is so-called "tor-mini": client-only tor with stripped down "server" functionality. As i can see, patches on top of tor source will be kind of headache of maintainer, so there's no reason to put them in "net/tor/", but create new package/directory like "net/tor-mini/". What do you think?

**Comment by alanswanson** [comment]
This pull request is still valid and I've been using it for my OpenWRT builds. Just that deleting a branch automatically closes pull requests from it. Could you reopen please?

**Comment by rockdrilla** [comment]
@alanswanson, I'm going to split PR as requested in near future. If it's applicable to you, I'll push branch back named "tor-wip" ASAP.

**Comment by tripolar** [comment]
i looked through all the patches. i looks fine to me. to save time on your site, combine them in on PR i will merge it as one

**Comment by rockdrilla** [comment]
@tripolar, btw, what's wrong with "disable unwanted build targets"? :)

**Pull request closed without merging**
