### PR TITLE
python-curl: update to version 7.43.0.4

### PR DESCRIPTION
**Pull request by valdi74**
Signed-off-by: Waldemar Konik <informatyk74@interia.pl>

Maintainer: me
Compile tested: mipsel_24kc, x86_64

Description:
python-curl: update to version 7.43.0.4
+ WolfSSL support from upstream => remove 0001-Add-locking-support-to-wolfSSL.patch)

PycURL changelog:
Version 7.43.0.4 - 2020-01-15
-----------------------------------------------------------------
- Minimum supported Python 3 version is now 3.5.
- Python 2 is no longer officially supported.
- Improved thread safety of multi code.
- Added Python 3.8 support (patch by Michael Treanor).
- Fixed link order when linking statically against OpenSSL (patch by Ashley Whetter).
- Fixed Darwin detection.
- Added support for wolfSSL (patch by Eneas U de Queiroz).
- Added PROXY_SSL_VERIFYHOST (patch by Amir Rossert).

### CODE REVIEW

**Comment by BKPepe** [comment]
I've just one proposal. May I ask you to split your commits or short your commit subject, please? Right now, it is too long.

**Comment by valdi74** [comment]
> 
> 
> I've just one proposal. May I ask you to split your commits or short your commit subject, please? Right now, it is too long.

Sure. Done.

**Comment by jefferyto** [comment]
I know upstream has removed support for Python 2 with this version, but we are trying to keep Python 2 packages in-tree until [end of March](https://github.com/openwrt/packages/tree/master/lang/python#transition-policy--schedule).

May I ask, does this version still work with Python 2 (even if it isn't officially supported)?

**Comment by valdi74** [comment]
I did some tests on x86_64 and it still works on Python 2. So - we can leave in place support for Python 2 or ... freeze this PR until end of March.

**Comment by jefferyto** [comment]
I don't want to block updates, so I would be in favour of leaving Python 2 support in place. The chances of someone compiling from master, using Python 2 and finding an issue with this version in the next 2 months are probably minimal :joy:

**Comment by valdi74** [comment]
OK. Python 2 support not removed.

**Pull request merged**
