### PR TITLE
gstreamer1: update to 1.16.0

### PR DESCRIPTION
**Pull request by MikePetullo**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64
Run tested: x86_64

Description:

### CODE REVIEW

**Comment by neheb** [comment]
I prefer that all the gstreamer packages be placed on this pull request so that CircleCI can test compilation properly.

**Comment by MikePetullo** [comment]
@neheb, this combines all of the GStreamer pull requests with the benefit of permitting a better CI check. I agree this is better, but I had been under the impression the reviewers preferred individual merge requests.

I modified my gst1-libav work. I think the "ifneq" change resulted from me missing 2eb46edaa48d2ad9f39aaeb9801ded2bb75eaa86, which you committed on the same day I did my work.

I am going to have to revert your addition of "--disable-option-parsing" in a5a0a350817f4398ef9c6094e1d6e11af478c219. This breaks applications because it configures GStreamer to return NULL from gst_init_get_option_group() without initializing the GStreamer system. This will come in another merge request after someone approves this one.

**Comment by neheb** [comment]
```
Configuring included Libav instance with args --prefix=/usr         --enable-static --enable-pic         --disable-avdevice --disable-postproc --disable-swscale         --disable-programs --disable-ffplay --disable-ffprobe --disable-ffmpeg         --disable-encoder=flac --disable-protocols --disable-devices         --disable-network --disable-hwaccels --disable-dxva2 --disable-vdpau         --disable-filters --enable-filter=yadif --disable-doc --disable-d3d11va         --disable-audiotoolbox --disable-videotoolbox --disable-vaapi --disable-crystalhd         --disable-mediacodec --disable-nvenc --disable-mmal --disable-omx         --disable-omx-rpi --disable-cuda --disable-cuvid --disable-libmfx         --disable-libnpp --disable-iconv --disable-jni --disable-v4l2_m2m --enable-optimizations --enable-cross-compile         --target-os=linux --arch=mips --cross-prefix=mips-openwrt-linux- --ar="$AR" --as="$orig_AS" --cc="$CC" --ld="$CC" --nm="$NM" --disable-ffmpeg  --cpu=octeon+ --disable-bsfs --disable-programs --disable-devices --disable-debug --disable-doc --disable-extra-warnings --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-runtime-cpudetect --disable-encoders                               --disable-decoders     --enable-decoder='ac3'            --enable-decoder='jpegls'      --enable-decoder='mp3'   --enable-decoder='mpeg1video'   --enable-decoder='mpeg2video'      --enable-decoder='mpegvideo'   --enable-decoder='pcm_s16be'   --enable-decoder='pcm_s16le'   --enable-decoder='png'   --enable-decoder='vorbis'         --enable-decoder='zlib'  --disable-muxers                                  --disable-demuxers  --enable-demuxer='ac3'         --enable-demuxer='mp3'         --enable-demuxer='mpegvideo'   --enable-demuxer='ogg'              --disable-parsers     --enable-parser='ac3'      --enable-parser='mpegaudio'   --enable-parser='mpegvideo'   --enable-parser='mpeg4video'  --disable-protocols                   --disable-asm --disable-altivec --disable-amd3dnow --disable-amd3dnowext --disable-mmx --disable-mmxext --disable-sse --disable-sse2 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-xop --disable-fma3 --disable-fma4 --disable-avx2 --disable-inline-asm --disable-x86asm
mips-openwrt-linux-musl-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
config.status: error: Failed to configure embedded Libav tree
Makefile:215: recipe for target '/home/build/build_dir/build_dir/target-mips_24kc_musl/gst-libav-1.16.0/.configured_c3004cb90b7a2c340455637c286fadbf' failed
make[2]: *** [/home/build/build_dir/build_dir/target-mips_24kc_musl/gst-libav-1.16.0/.configured_c3004cb90b7a2c340455637c286fadbf] Error 1
make[2]: Leaving directory '/home/build/openwrt_packages/multimedia/gst1-libav'
time: package/feeds/packages/gst1-libav/compile#7.66#3.65#19.68
package/Makefile:107: recipe for target 'package/feeds/packages/gst1-libav/compile' failed
make[1]: *** [package/feeds/packages/gst1-libav/compile] Error 2
make[1]: Leaving directory '/home/build/build_dir'
/home/build/build_dir/include/toplevel.mk:209: recipe for target 'package/gst1-libav/compile' failed
make: *** [package/gst1-libav/compile] Error 2
Exited with code 2
```

This needs to be fixed somehow... ping @cotequeiroz

**Comment by neheb** [comment]
I changed the if statement to 
```
ifneq ($(findstring octeonplus,$(CONFIG_CPU_TYPE)),)
```
seems to work fine on mips64 and PPC.

**Comment by MikePetullo** [comment]
@neheb, I modified the ifneq statement. It looks like the CI system is happy now.

**Comment by diizzyy** [comment]
Is there a reason why most optimization is disabled?

**Comment by neheb** [comment]
Seems good to me.

@diizzyy I would guess compile failures on less capable targets.

For now I will merge this as gst-libav is curently broken on the buildbots because of my mistake.

**Pull request merged**
