### PR TITLE
tcp_wrappers: Remove

### PR DESCRIPTION
**Pull request by neheb**
Currently no packages depend on tcp_wrappers. It also seems to have
compilation problems as in PR #5106 .

Additionally, fedora has removed support for it for similar reasons.

See: https://fedoraproject.org/wiki/Changes/Deprecate_TCP_wrappers

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tripolar

### CODE REVIEW

**Comment by pprindeville** [comment]
It's also been dropped from several distros because Wietse has said he doesn't want to maintain it and thinks that it's no longer necessary.

**Comment by pprindeville** [comment]
@tripolar Can I merge this?

**Comment by tripolar** [comment]
nfs-kernel-server and pulseaudio depend on it.  i don't want to drop it

**Comment by pprindeville** [comment]
> nfs-kernel-server and pulseaudio depend on it. i don't want to drop it. it's possible to restrict access to services based on ip addresses

Well, yes... with `iptables`.  Which we use everywhere else.  Would these applications not be better served with a more integrated, mainstream solution leveraging `iptables` plugins?

**Comment by pprindeville** [comment]
I don't think anyone was offering up Fedora as an example.

http://ftp.porcupine.org/pub/security/tcp_wrappers_7.6.BLURB

`@(#) BLURB 1.28 97/03/21 19:27:18`

Last release 1997.

**Comment by pprindeville** [comment]
I think we should proceed w/ deprecation.

**Pull request closed without merging**
