### PR TITLE
wireguard: update snapshot version to 0.0.20170517

### PR DESCRIPTION
**Pull request by zx2c4**
Maintainer: me / @danrl 

This version bump is ready to be merged.

### CODE REVIEW

**Comment by zx2c4** [comment]
The new version has been released here -- https://lists.zx2c4.com/pipermail/wireguard/2017-May/001334.html . @danrl -- please ACK. Maintainers -- please merge.

**Comment by danrl** [comment]
Tested it and updated the corresponding LuCI protocol application.
https://github.com/openwrt/luci/pull/1169

**Comment by zx2c4** [comment]
I'm pretty sure you mean https://github.com/openwrt/luci/pull/1160 . Anyway, let's get this merged.

**Comment by diizzyy** [comment]
@hnyman 
Ping?

**Pull request merged**
