### PR TITLE
iodine: fix musl compatibility

### PR DESCRIPTION
**Pull request by mstorchak**
Acked-by: Uwe Kleine-König
Signed-off-by: Maxim Storchak <m.storchak@gmail.com>

### CODE REVIEW

**Comment by sbyx** [comment]
@ukleinek please review

**Comment by mstorchak** [comment]
> A more verbose commit log would be nice. I assume for musl you don't need daemon() because it's already provided, right?

Comments like this worked for other packages, so I thought that was enough. If you think it should be more verbose, I can update it, no problem.
Yes, the problem is that daemon function gets redefined by iodine.

> Also this patch probably breaks Android and Windows. I guess this isn't a big loss because the patch is local to openwrt.

Yes, that was the main driving idea behind my patch.

> Did you consider to fix it right (by appending a && !defined(__WHATEVER_SYMBOL_IDENTIFIES_MUSL__) to get this upstream?

Please see http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_there_no_MUSL_macro_.3F: there is no MUSL macro, and this is done for purpose. For OpenWRT this check effectively resolves into `if(uClibc)`

>  Without this patch, does iodine fail to build?

Yes, it does: https://gist.github.com/mstorchak/58db74d2543356da9ea0

**Comment by ukleinek** [comment]
My preferred fixup then is: Add to the patch description (that's still better than the commit log) that breaking Android and Windows doesn't matter for openwrt, and note that musl comes with a daemon function and redefining it breaks building.

I wonder if it's correct but lacking in practical relevance that there is no musl symbol, but this is not the place to discuss that.

**Comment by mstorchak** [comment]
@ukleinek, please check. Is it better now?

**Comment by mstorchak** [comment]
Not sure how to integrate your Ack into a PR :-/.
I guess a comment with approval here should be enough.

**Comment by ukleinek** [comment]
I'm not that into the openwrt development process, for the Linux kernel I'd just put:

  Acked-by: Uwe Kleine-König <uwe+openwrt@kleine-koenig.org>

before the Signed-off-by line.

**Pull request merged**
