### PR TITLE
dbus: Add optional dependency on systemd

### PR DESCRIPTION
**Pull request by jdub**
See https://github.com/jdub/openwrt-systemd for the openwrt-systemd project.

Signed-off-by: Jeff Waugh <jdub@bethesignal.org>

### CODE REVIEW

**Comment by jdub** [comment]
Note: I will probably update this to a dependency on libsystemd once I've made that split.

**Comment by jdub** [comment]
Oh, the original reason for fixing the daemon location was because the service files use EXPANDED_BINDIR, and that's hard to tease apart without mucking around with sed, etc., etc.

**Comment by sbyx** [comment]
Sorry, but as per our guidelines we do not accept dependencies to third-party feeds.
So you would need to submit and maintain your systemd package here in order for this to be accepted.

**Comment by jdub** [comment]
@sbyx Cool, no worries. It's in an experimental stage right now, but once it's solid I'll submit it for review. I'll send my kmod package ASAP though. Thanks!

**Pull request closed without merging**
