### PR TITLE
nextdns: Update to version 1.8.4

### PR DESCRIPTION
**Pull request by rs**
Update to version 1.8.4

### CODE REVIEW

**Comment by aparcar** [comment]
Hi, the CI fails to install the package within a simulated OpenWrt container. What does the `nextdns install` step do?

```
Configuring nextdns.
 * pkg_run_script: package "nextdns" postinst script returned status 2.
 * opkg_configure: nextdns.postinst returned 2.
No test.sh script available
Removing package nextdns from root...
system not supported
Collected errors:
 * pkg_run_script: package "nextdns" prerm script returned status 1.
```

**Comment by rs** [comment]
It installs the init script.

**Comment by aparcar** [comment]
I run-tested the resulting binaries and it seem to work fine. I'll merge this.

For automated CI tests it would be cool to be installable in the simulated OpenWrt container, which can't use procd with PID1 but uses a shell which the CI can control.

This effectively breaks your checks at https://github.com/nextdns/nextdns/blob/7b07323040622acbcba542996ba60ba615db1771/host/service/procd/service.go#L23 and therefore fails the install.

Within the CI it looks more like the following:

```
  PID USER       VSZ STAT COMMAND
    1 root      1096 S    ash
   10 root       932 T    /sbin/init
   12 root      1000 T    /sbin/procd -h /etc/hotplug-preinit.json
```

**Comment by rs** [comment]
Any suggestion on how to detect such environment?

**Pull request merged**
