### PR TITLE
motion: add basic procd init script and fix streaming

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: @roger-
Compile tested: OpenWrt master r11602-5f68333952 on RPi0W
Run tested: OpenWrt master r11602-5f68333952 on RPi0W

### CODE REVIEW

**Comment by neheb** [comment]
this needs a PKG_RELEASE bump, no?

**Comment by stintel** [comment]
> this needs a PKG_RELEASE bump, no?

Right. Totally did not think of that. I noticed another problem too. For some reason, even though I added /etc/config/motion to `Package/motion/conffiles`, reinstalling the ipk overwrites /etc/config/motion even though I made changes to it. Wonder what's up with that ... Any clues?

**Comment by neheb** [comment]
On a quick look, nothing pops out,

**Comment by stintel** [comment]
Bumping the PKG_RELEASE fixed the config overwrite, so this is good to go.

**Comment by dibdot** [comment]
Please decrease the START parameter below 95, 's95done' is intended to run at last in chain.

**Comment by stintel** [comment]
> Please decrease the START parameter below 95, 's95done' is intended to run at last in chain.

Since when are we enforcing this? See `git grep START=9[5-9]` in both core and packages-feed.

**Comment by dibdot** [comment]
Nobody's forcing anything, it just makes sense. It doesn't get any better just because others have done it wrong as well

**Comment by stintel** [comment]
Modified it. But if it is wrong to use anything >=95 because /etc/init.d/done uses START=95, it would make more sense that done uses START=99, would it not?

**Comment by neheb** [comment]
Merging as this fixes behavior.

**Pull request merged**
