### PR TITLE
Atlas SW probe to version 5040 and its busybox version 

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @ja-pa 
Compile and run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master

Probe is running, but Probe version on website was not updated. 

Changelog:
```
5040 (released 2021-10-21)
Measurement changes (version 2.4.1):
Firmware 5030 introduced a regression where a specific type of TCP connect failure would cause the probe to stop performing measurements.

5030 (released 2021-09-13)
Config variable to disable the check that atlas data is on tmpfs
Support for software probes on OpenWrt (by Jan Pavlinec)
Measurement changes (version 2.4.0):
Solve issue with duplicate src_addr in DNS measurements
Remove as much as possible source files that are not used by Atlas
Fix bug in sslgetcert if there is a connection failure
Replace stime with clock_settime
Support a lot more network interfaces in reporting traffic statistics
Option to set AD bit in DNS queries
Initial support for testing Atlas measurement code
```

### CODE REVIEW

**Comment by neheb** [comment]
I have a local patch for fixing compilation without deprecated OpenSSL APIs:

```
--- a/libevent-2.1.11-stable/test/regress_ssl.c
+++ b/libevent-2.1.11-stable/test/regress_ssl.c
@@ -148,9 +148,9 @@ ssl_getcert(EVP_PKEY *key)
        X509_set_issuer_name(x509, name);
        X509_NAME_free(name);

-       X509_time_adj(X509_get_notBefore(x509), 0, &now);
+       X509_time_adj(X509_getm_notBefore(x509), 0, &now);
        now += 3600;
-       X509_time_adj(X509_get_notAfter(x509), 0, &now);
+       X509_time_adj(X509_getm_notAfter(x509), 0, &now);
        X509_set_pubkey(x509, key);
        tt_assert(0 != X509_sign(x509, key, EVP_sha1()));

@@ -469,8 +469,8 @@ regress_bufferevent_openssl(void *arg)
        type = (enum regress_openssl_type)data->setup_data;

        if (type & REGRESS_OPENSSL_RENEGOTIATE) {
-               if (SSLeay() >= 0x10001000 &&
-                   SSLeay() <  0x1000104f) {
+               if (OPENSSL_VERSION_NUMBER  >= 0x10001000 &&
+                   OPENSSL_VERSION_NUMBER  <  0x1000104f) {
                        /* 1.0.1 up to 1.0.1c has a bug where TLS1.1 and 1.2
                         * can't renegotiate with themselves. Disable. */
                        disable_tls_11_and_12 = 1;
```

I assume it's still needed.

**Comment by BKPepe** [comment]
@neheb You should send it to upstream first and then I will backport it.

**Review by paper42 — APPROVED** [review]
Tested on Turris Omnia, armv7, Turris OS 6.0 (OpenWrt 21.02), lgtm

**Comment by BKPepe** [comment]
I'm merging this as it is. Hopefully, @ja-pa don't mind it.

**Comment by ja-pa** [comment]
Np Thank you

**Pull request merged**
