### PR TITLE
gnutls: Update to 3.7.4

### PR DESCRIPTION
**Pull request by graysky2**
Bump to latest upstream release.  Rebased existing patches.

Signed-off-by: John Audia <graysky@archlinux.us>

Maintainer: @cotequeiroz @stintel @neheb

### CODE REVIEW

**Comment by neheb** [comment]
@stintel needs the final say I think. He reverted my last version bump because of some compilation issue he had locally.

**Comment by stintel** [comment]
```
Package libgnutls is missing dependencies for the following libraries:
libzstd.so.1
```

**Comment by stintel** [comment]
In general a lot of nastiness going on during build aside from the final failure due to missing zstd dependency:
[compile.txt](https://github.com/openwrt/packages/files/8313413/compile.txt)

```
bash: line 1: /home/stijn/Development/OpenWrt/openwrt/staging_dir/hostpkg/bin/autopoint: No such file or directory
```

```
./configure: line 28095: gt_TYPE_WCHAR_T: command not found
./configure: line 28096: gt_TYPE_WCHAR_T: command not found
```

```
/home/stijn/Development/OpenWrt/openwrt/staging_dir/toolchain-aarch64_cortex-a72_gcc-11.2.0_musl/lib/gcc/aarch64-openwrt-linux-musl/11.2.0/../../../../aarch64-openwrt-linux-musl/bin/ar terminated with signal 13 [Broken pipe]
/home/stijn/Development/OpenWrt/openwrt/staging_dir/toolchain-aarch64_cortex-a72_gcc-11.2.0_musl/lib/gcc/aarch64-openwrt-linux-musl/11.2.0/../../../../aarch64-openwrt-linux-musl/bin/ar terminated with signal 13 [Broken pipe]
```

**Comment by neheb** [comment]
autopoint becomes avaible with gnutext-full/host. I doubt it's needed.

That are warning is strange. Does it go away with PKG_BUILD_PARALLEL:=0?

**Comment by stintel** [comment]
Apparently there is also host leakage when building for x86:

```
/home/stijn/Development/OpenWrt/openwrt/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.2.0/../../../../x86_64-openwrt-linux-musl/bin/ld: /lib64/libz.so.1: undefined reference to `__errno_location@GLIBC_2.2.5'
```

**Review by stintel — CHANGES_REQUESTED** [review]
Multiple issues, see previous comments.

**Comment by stintel** [comment]
@nmav any ideas to fix the host lib leakage?

**Comment by stintel** [comment]
> That ar warning is strange. Does it go away with PKG_BUILD_PARALLEL:=0?

It does not.

**Comment by stintel** [comment]
FYI: trying some things in https://github.com/stintel/openwrt-packages/commits/gnutls

**Comment by stintel** [comment]
My gnutls branch seems to build fine now. @graysky2 can you pull in those changes and update this PR?

**Comment by graysky2** [comment]
Done, should I squash this into a single commit?

**Comment by stintel** [comment]
Thanks, like this is great. Squashing should be avoided in this case. I have to run now, will look into the next set of failures later.

**Comment by breakings** [comment]
find /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/gnutls-3.7.4/ipkg-aarch64_cortex-a53/libgnutls -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package libgnutls is missing dependencies for the following libraries:
libz.so.1

**Comment by graysky2** [comment]
@breakings -not sure about the syntax, but based on `rsync`'s MAKEFILE, I just pushed a commit.

**Comment by graysky2** [comment]
That wasn't right :D

**Comment by stintel** [comment]
I would probably just disable zlib, analog to zstfd.

**Comment by graysky2** [comment]
@stintel - do you mind pushing a commit achieving that?

**Comment by stintel** [comment]
> @stintel - do you mind pushing a commit achieving that?

Updated my gnutls branch.

**Comment by stintel** [comment]
@breakings does it work for you now?

**Comment by breakings** [comment]
> @breakings does it work for you now?

OK It works

**Review by stintel — APPROVED** [review]
Approving as I previously requested changes, but since part of the commits are made by me it would be good if someone else reviews and approves this before merging.

**Review by nmav — APPROVED** [review]

**Comment by nmav** [comment]
LGTM, thank you for driving this

**Comment by stintel** [comment]
@graysky2 I fixed a few typos in the commit message, can you pick 1f0a79b76e430bd5016b666fe3218cbfd89f1ab0? After that this should be good to go.

@nmav thanks for review!

**Pull request merged**
