### PR TITLE
[OpenWrt 19.07] python3: Update to version 3.7.5

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainers: @commodo , @jefferyto 
Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master

Description:

Python3: Updated to version [3.7.5](https://www.python.org/downloads/release/python-375/)
setuptools: Updated to version 41.2.0
pip: Updated to version 19.2.3

Refreshed patches

Removed patches:

1.  **patch is no longer applying due to refactor:**
- from PR #https://github.com/openwrt/packages/pull/7931, there was added a patch **017_lib2to3_fix_pyc_search.patch** into this repository, but it was not sent to Python developers. It is question, if it is still necessary. Let's remove it and see what it does? Let's have one patch less! 

2. **backported patches:** 

- `025-bpo-37461-Fix-infinite-loop-in-parsing-of-specially-.patch` ( Added in PR # https://github.com/openwrt/packages/pull/10109 )
- `026-3.7-bpo-37764-Fix-infinite-loop-when-parsing-unstruc.patch` ( Added in PR # https://github.com/openwrt/packages/pull/10109 )
- `027-bpo-38243-xmlrpc.server-Escape-the-server_title-GH-1.patch` (Added in PR # https://github.com/openwrt/packages/pull/10109 )
- `028-bpo-34155-Dont-parse-domains-containing-GH-13079.patch` ( Added in PR # https://github.com/openwrt/packages/pull/10151 )

### CODE REVIEW

**Comment by commodo** [comment]
why not go directly to Python 3.8?
i've been working on this last week;
still need to re-test some things; some patches needed to be reworked, and I also want to see if we can get rid of some older ones;

**Comment by commodo** [comment]
> why not go directly to Python 3.8?
> i've been working on this last week;
> still need to re-test some things; some patches needed to be reworked, and I also want to see if we can get rid of some older ones;

i forgot to add; this patch could go into 19.07; i think it would be a good idea;
the jump to 3.8 seems a bit big; upgrading it took a bit more time than just bumping 3.7.x series

**Comment by BKPepe** [comment]
I was not aware that you are working on 3.8, but I just wanted to be safe and have it included in master and in openwrt-19.07 (doing a cherry-pick) to have more time before jumping it to 3.8, but it's a question if we would like to have three different Python versions in OpenWrt or just two (3.6 and 3.8). It will be a little bit difficult to maintain it, but users might want to have it. On the other hand, some projects can already be preparing their work on unreleased 19.07 and they are used to Python 3.7.

So for now, I will change this PR to openwrt-19.07.

**Comment by commodo** [comment]
I always felt that master could/should have the latest version of packages.
And the released branches would have some older version [what was newest at the time].

Supporting 3 versions of Python3 may not be that big of-a-deal.
OpenWrt 18.06 is getting old anyway and 3.6 is what-is there.
Anyway, people will always want to backport stuff from master in a release from 2-3+ years ago, even though that is a bit silly.

OpenWrt 19.07 [I feel] should stick with 3.7.
3.8 is too new to predict issues we'd get.
So I would not add 3.8 in 19.07 now; maybe in 2-3 months I would feel more comfortable.

**Comment by BKPepe** [comment]
I agree with you guys, but I am just a little bit careful about updating it into Python 3.8. It was released only a few days ago. Some Python packages are being tested against 3.7 and there can be some incompatibility, so some things can be broken, so I would wait a while, however, I'm fine with that. We can see what is broken and let developers know about it to fix it.

**Comment by jefferyto** [comment]
I think the standard advice for users is to not use master because it can break at any time... Sometimes we need to break it so users will take us seriously :joy:

**Pull request merged**
