### PR TITLE
ariang: dep rework

### PR DESCRIPTION
**Pull request by Ansuel**
Permit to remove uhttpd dep if nginx package is selected.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Same comment as in the LuCI repo, this change will effectively alter the default for all repo users as nginx is always enabled on the buildbots.

**Comment by Ansuel** [comment]
is this what you mean with meta package?

**Comment by hnyman** [comment]
I would leave the existing package name intact and just add the new -nginx variant. (same as luci, luci-openssl etc.)

You can also avoid duplicating the install section, as they are identical.
This should work:
```
Package/ariang-nginx/install = $(Package/ariang/install)
```
See example:
https://github.com/openwrt/openwrt/blob/master/package/network/services/hostapd/Makefile#L587
https://github.com/openwrt/openwrt/blob/master/package/libs/ustream-ssl/Makefile#L66

**Comment by Ansuel** [comment]
didn't know about the equal stuff thx! Was searching for something like that...

**Comment by hnyman** [comment]
You should further avoid duplication. 
define common parts of the package first as default, then reference that from both ariang and ariang-nginx definitions.

Again libustream can serve as example.
https://github.com/openwrt/openwrt/blob/master/package/libs/ustream-ssl/Makefile#L23


(and you might shorten the description at the same time.)

**Comment by Ansuel** [comment]
can't understand how the ariang-nginx should unselect the uhttpd dep using ustream makefile as example... (i need to create 2 subpackage to have different dep)

**Comment by hnyman** [comment]
I mean something like:

```
define Package/ariang/default
  SECTION:=net
  CATEGORY:=Network
  SUBMENU:=Download Manager
  DEPENDS:=+aria2
  TITLE:=AriaNg webui
  URL:=https://github.com/mayswind/AriaNg
  PKGARCH:=all
endef

define Package/ariang
  $(Package/ariang/default)
  DEPENDS += +uhttpd
  TITLE += for uhttpd webserver
endef

define Package/ariang-nginx
  $(Package/ariang/default)
  DEPENDS += +nginx
  TITLE += for nginx webserver
endef
```

**Comment by Ansuel** [comment]
```
define Package/ariang
  $(Package/ariang/default)
  DEPENDS += +uhttpd
  TITLE += for uhttpd webserver
endef
```
i'm stupid... didn't think about this way....

**Comment by Ansuel** [comment]
aand what about description ?

**Comment by hnyman** [comment]
> aand what about description ?

I already edited my example above right after sending the first version...
I think that it can be copied, too. You had left the text the same, so just equal.

**Pull request merged**
