### PR TITLE
[openwrt-21.02] treewide: Run refresh on all packages

### PR DESCRIPTION
**Pull request by jefferyto**
This is #14646 cherry-picked for openwrt-21.02. Without this, cherry-picking future commits from master into openwrt-21.02 can lead to unnecessary merge conflicts.

Also, I imagine the dirty patches CI check will also apply to openwrt-21.02 (when the CI is up and running).

Ping @neheb @lipnitsk 

Not sure if my sign-off should be included in the commit message - let me know if I should remove it.

### CODE REVIEW

**Comment by commodo** [comment]
this refresh thing, looks like a job for a CI job :P

**Comment by aparcar** [comment]
I'm working on the 21.02 pipeline, should work in a bit.

**Comment by neheb** [comment]
I'll merge this as another user complained. @G-M0N3Y-2503

**Comment by jefferyto** [comment]
Thanks - @neheb just curious, is there a reason why you were so eager to refresh all patches on master but not openwrt-21.02?

**Pull request merged**
