### PR TITLE
python-pyasn1: Update to 0.4.4

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com

Maintainer: @jefferyto @commodo

### CODE REVIEW

**Comment by commodo** [comment]
LGTM
Thanks for the update.
Sorry for the delay [vacation].

**Comment by dibdot** [comment]
Sorry to ask: the failed travis check is expected?

**Comment by commodo** [comment]
Good point.

In the past Python package builds have failed intermittently.
I don't know why; and I haven't yet digged too much into it; locally it usually builds, but in Travis CI it sometimes [not always] fails.

Then, I would check buildbot (https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/ ) and it would also pass there. [ even after the merge ]

So, clearly there is something funky/weird with the Travis CI integration.

I think we can try to make some time to check.
Maybe it's the build cache that's the problem.
I can try to look, but I can't make promises about it.

**Comment by dibdot** [comment]
let's merge it and we will see in buildbot logs - thanks.

**Comment by cshoredaniel** [comment]
@dibdot @commodo Actually I wonder if Travis CI is failing for Python due to rate-limiting or such on PyPi? (Not likely, but I'd be curious to know ... I did notice the usual error is that the test download succeeds but for the build the download fails).

**Comment by commodo** [comment]
I don't think it's rate-limiting.
More like Travis CI behind-the-scenes-black-magic

**Comment by commodo** [comment]
I can't get it to fail in my setup.
I tried to hack the travis_do script, to build pyasn1.

Maybe the solution for the main packages repo is to clear the cache every now-n-then.
Basically, just go to https://travis-ci.org/openwrt/packages/caches  [you need access to go there] and clear all the caches.
They will get re-generated, so that should be fine.

**Pull request merged**
