### PR TITLE
xinetd: fix bad printf formats

### PR DESCRIPTION
**Pull request by neheb**
Easier to use the proper C macro.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @feckert 
Compile tested: ppc64

### CODE REVIEW

**Comment by feckert** [comment]
LGTM
Should we send this to the upstream project?

**Comment by neheb** [comment]
Isn't it dead upstream?

**Comment by BKPepe** [comment]
Still it should be send to upstream.

**Comment by neheb** [comment]
Upstream's last update was in 2016 with pending PRs. I don't think there's a point in trying to upstream.

**Comment by BKPepe** [comment]
Well, atleast while sending to upstream, it is clear who authored it, why the change is required and so on. Then any GNU/Linux distribution can use it or maybe dealing with it, so it is always good idea to send it there even they are not active. Anyone can review it.

**Comment by neheb** [comment]
meh alright: https://github.com/xinetd-org/xinetd/pull/35

**Pull request merged**
