### PR TITLE
node: #14983 NODEJS_ICU_SMALL is default

### LINKED ISSUE #14983: node: Can we please make CONFIG_NODEJS_ICU_SMALL=y the default?
Looks like node package has no internationalisation support by default.

Is it possible that we can get the ICU small flag set by default? Surely this adds little overhead (and it's not that anyone running node JS should be doing so on a resource limited system anyhow).

Thx

### PR DESCRIPTION
**Pull request by raintonr**
Fixes #14983

### CODE REVIEW

**Comment by ja-pa** [comment]
cc @nxhack

**Comment by nxhack** [comment]
icu none
```
7,235,926  node_v14.16.0-1_arm_cortex-a15_neon-vfpv4.ipk
```
icu small
```
9,700,147 node_v14.16.0-1_arm_cortex-a15_neon-vfpv4.ipk
```

> Is it possible that we can get the ICU small flag set by default? Surely this adds little overhead (and it's not that anyone running node JS should be doing so on a resource limited system anyhow).

As you pointed out, it's not really a problem in environments that run node.js.

I agree with this change.

Please PKG_RELEASE++

**Comment by BKPepe** [comment]
@raintonr Can you please update PKG_RELEASE and change the commit message? It should start with prefix, I mean with the package name.

**Comment by raintonr** [comment]
> @raintonr Can you please update PKG_RELEASE and change the commit message? It should start with prefix, I mean with the package name.

Yeah, that actually makes sense. Have done that now. Have updated the commit messages after discovering you really meant it should start `node:`

That said, now the tests seem to dislike my branch due to all this. Sometimes I really don't like git :(

**Comment by BKPepe** [comment]
Well, of course, you don't like things, if you don't know what to do with them or how to do it properly or how it should be done.  That's understandable. One or two day course with git and it would be much better trust me! :+1: 

Honestly, I don't know if you manage to create 9 commits and 4 of them merge.  

AFAIK, there two ways how to fix it.

1. Checkout to the master branch (it is better not yours as it can be outdated, checkout to remote's branch as shown below is possible), create a new feature branch. Then cherry-pick commits, which you need from the previous branch or create new ones. That's up to you. Delete the branch, which is not in good shape. Rename the feature branch to the same branch named exactly the same as in this PR and force push it. 

2. Rebase your current feature branch on top of the master branch. You should add remote, fetch the remote, then rebase it.
By using commands:
```
git remote add upstream git@github.com:openwrt/packages.git
git fetch upstream
git pull upstream master --rebase
```

If there are conflicts, they need to be solved.

Hope it helps! Don't forget to do your changes in one commit (in this case).

**Comment by raintonr** [comment]
Sorry to have inconvenienced you by trying to improve this project.

It would honestly be quicker if someone with the correct access would just make the 2 line edit required to fix #14983. Could you please do that?

Thx.

**Comment by raintonr** [comment]
> Honestly, I don't know if you manage to create 9 commits and 4 of them merge.

Here is the explanation:

When @nxhack said, "Please PKG_RELEASE++" I did know know that was a statement aimed at me. I haven't worked on this project before so this cryptic statement meant nothing to me. I'm not a project insider, but does that mean I should be abused? Guess some people think so, which is pretty offensive.

Anyhow, so I created a commit for that change, no worries, right? Ah, wait...

Now @BKPepe elaborated on what @nxhack meant and explained that the rules here mean that commit messages should start with "prefix" (they really should have said, "package name followed by colon", ie: `node:` in this case). I've always included the issue number at first but OK, as that's required by the project I had to now update my commits to include this in the message.

Then I had to signoff because... well... personally I don't see the point of this but project rules dictate I have to, so I do it.

When I try and push each of these changes Git complains with:

```
error: failed to push some refs to 'github.com:raintonr/packages.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

So how to fix this? Well, `git pull` of course. Which is perfectly acceptable to me, but seems this project's rules don't like (leads to a `Pull request should not include merge commits` error).

I don't know why these rules exist in this project, and really, it's not my place to question the design here. All I know is there are just 2 lines changed in this file and that is sufficient to fix #14983 but I am very disheartened by the abuse I have received here and just hope other contributors receive better treatment.

**Pull request closed without merging**
