### PR TITLE
new package: noip

### PR DESCRIPTION
**Pull request by smoofra**
This is the client program for noip.com, which is a dynamic dns provider.

Pull Request V2:

  * added a patch to eliminate use of pgrep

  * fix mangled makefile rule

Signed-off-by: Lawrence D'Anna <larry@elder-gods.org>

### CODE REVIEW

**Comment by champtar** [comment]
hi @smoofra,
can you describe shortly what noip does that ddns-scripts doesn't?
also your commit should start with "noip: ..."

**Comment by smoofra** [comment]
Fixed the commit message.

It doesn't look like ddns-scripts supports noip.com.

**Comment by champtar** [comment]
ddns scripts do support noip.com (in theory)
https://github.com/openwrt/packages/blob/master/net/ddns-scripts/Makefile#L65
you have to install ddns-scripts_no-ip_com package

**Comment by smoofra** [comment]
Huh.   So it does.    I guess this isn't needed then.

**Comment by champtar** [comment]
Maybe your package is smaller, or support more advanced feature or ...
If not i think you can close this one.
Thanks for your work anyway

**Comment by smoofra** [comment]
nope, the other one is better.   I just didn't' know it existed.  closing.

**Pull request closed without merging**
