### PR TITLE
i2pd: Fix compilation without deprecated OpenSSL 1.0.2 APIs

### PR DESCRIPTION
**Pull request by neheb**
Just one header was missing.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lucize 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
That's one bizarre CircleCI failure. I guess due to Python? @commodo

**Comment by commodo** [comment]
yep, it's python3;
my bad;

i forgot to do a dirclean when working on this

**Comment by commodo** [comment]
there's PR #7849 for this

**Comment by thess** [comment]
@commodo - If you think the CI build issue is fixed by a new check-in, then rebase this to pick it up and buildpr will run again with the updated branch.

**Comment by neheb** [comment]
Rebased and force-pushed.

**Comment by lucize** [comment]
me as maintainer here is a typo, but I'll test dovecot in this weekend if someone will not merge that by then

**Comment by neheb** [comment]
Ah sorry about that. Similar username icon I guess.

@yangfl

**Comment by yangfl** [comment]
What is the purpose of this change? Could you attach a fragment of warning/error message in your commit?

**Comment by neheb** [comment]
@yangfl A bunch of implicit function warnings.

Normally bn.h is included with ssl.h. With deprecated APIs enabled that is.

**Comment by neheb** [comment]
https://gist.github.com/neheb/d8005ea2fe94fcb6699014467a5bfccc

**Comment by neheb** [comment]
Oh that's nasty. I get more errors with 1.1.0. I will update the patch.

https://gist.github.com/neheb/81e1d7c55fd8d3c5556892999e393b50

**Comment by neheb** [comment]
Rebased and updated.

**Comment by neheb** [comment]
Found a few more problems. All fixed and submitted upstream: https://github.com/PurpleI2P/i2pd/pull/1278

**Comment by r4sas** [comment]
As @neheb said:
>Just one header was missing.

Can you tell if the no-chacha and no-poly1305 options are really used in OpenSSL 1.1+ by default in OpenWRT?

**Comment by neheb** [comment]
So the actual change to 1.1 is still in pull request form: https://github.com/openwrt/openwrt/pull/965

ChaCha20 and Poly1305 are enabled by default with the ability to disable them.

**Comment by yangfl** [comment]
Since these changes have already been merged by upstream, I'd like to wait for the next release.
Of course, if you're really in a hurry, these changes are good, but I already have a pr for i2pd #7749, maybe I should pick up your commit into my pr.

**Comment by neheb** [comment]
Your call.

**Comment by neheb** [comment]
Closing as this is fixed in another way.

**Pull request closed without merging**
