### PR TITLE
mdk3: new package

### PR DESCRIPTION
**Pull request by psyborg55**
Maintainer: @psyborg55
Compile tested: ramips, miwifi-mini, r49395
Run tested: ramips, miwifi-mini, r49395

Description:

Add mdk3 back to packages with required patches for compiling.

Signed-off-by: Tomislav Požega pozega.tomislav@gmail.com

### CODE REVIEW

**Comment by diizzyy** [comment]
Please use upstream repo, http://git.kali.org/gitweb/?p=packages/mdk3.git;a=summary and adjust PKG_VERSION, PKG_RELEASE and package url accordingly.

**Comment by diizzyy** [comment]
@psyborg55 
Can you please have a look at this or close the pull request if there's no interest?

**Comment by psyborg55** [comment]
i don't see what's the point in using git version as it hasn't been updated for 18 months

**Comment by diizzyy** [comment]
Best practice is to use upstream repo
Also, relying on a mirror as source is a bad idea in general.

**Pull request closed without merging**
