### PR TITLE
prepare for iconv stub removal

### PR DESCRIPTION
**Pull request by neheb**
these packages are too annoying to fix properly. So just use libc iconv for them.

### CODE REVIEW

**Comment by neheb** [comment]
Two packages left are irqbalance and php8. The latter @mhei has a fix already.

**Comment by Ansuel** [comment]
Typo in the title
s/prepate/prepare/

Il Sab 9 Lug 2022, 10:31 Rosen Penev ***@***.***> ha scritto:

**Comment by neheb** [comment]
That's just a github typo :P

**Comment by neheb** [comment]
looks like I need to fix libextractor properly...

**Pull request merged**
