### PR TITLE
multimedia/minidlna: Update to latest commit

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @medaved
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: ath79, WNDR3800, r9439+2-fe90e48c39 (Maxim Storchak)

Description:
Update minidlna to latest commit
Cherry pick commits from https://github.com/xavery/minidlna

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
I've been meaning test this myself but I haven't gotten around to make test setup but it should be fine. If anyone has time please test. In the end this should probably be replaced by Gerbera.
Also, SSL cert for SF is broken and the only way that I could find getting the source code was to use git :-/

**Comment by diizzyy** [comment]
@mstorchak
Since you seem to use minidlna, can you give this a try?

**Comment by mstorchak** [comment]
Compile tested: ath79, WNDR3800, r9439+2-fe90e48c39
Run tested: ath79, WNDR3800, r9439+2-fe90e48c39. Works as expected.

**Comment by mstorchak** [comment]
Some patches are out of sync:
```
Applying ./patches/001-dont-build-po-files.patch using plaintext:
patching file Makefile.am
patching file configure.ac
Hunk #1 succeeded at 647 (offset 3 lines).

Applying ./patches/002-mark_all_instances_of_magic_container_s_as_const.patch using plaintext:
patching file containers.c
Hunk #1 succeeded at 25 (offset -25 lines).
Hunk #2 succeeded at 124 (offset -25 lines).
Hunk #3 succeeded at 154 (offset -25 lines).
patching file containers.h
Hunk #1 succeeded at 30 (offset -8 lines).
patching file scanner.c
Hunk #1 succeeded at 587 with fuzz 2 (offset 21 lines).
patching file upnpsoap.c

Applying ./patches/003-wrap_container_definitions_into_a_structure.patch using plaintext:
patching file containers.c
Hunk #1 succeeded at 23 with fuzz 1.
patching file containers.h
patching file scanner.c
Hunk #2 succeeded at 553 with fuzz 2.
```

**Comment by diizzyy** [comment]
Thanks, I'll try to get around updating those during the weekend

**Comment by diizzyy** [comment]
@mstorchak 
Done

**Comment by diizzyy** [comment]
@hnyman 
Can we merge this one?

**Comment by thess** [comment]
Needs a new **Maintainer** - @diizzyy ?
Merging... Thanks

**Comment by diizzyy** [comment]
Seeing that minidlna is pretty much dead upstream the next (?) move would be to deprecate it and move to https://github.com/gerbera/gerbera . Haven't checked memory usage etc but I would expect it to be slightly higher than minidlna.

**Comment by TimelessNL** [comment]
> 
> 
> Seeing that minidlna is pretty much dead upstream the next (?) move would be to deprecate it and move to https://github.com/gerbera/gerbera . Haven't checked memory usage etc but I would expect it to be slightly higher than minidlna.

It seems that most of the makefile work for Gerbera is already done by @Smartsmurf in his [personal repo](https://github.com/Smartsmurf/smartpackages). It's very recent as well, so maybe he will take the effort to create a pull-request sometime. Which would be nice 👍, so If you read this @Smartsmurf please consider :)

**Comment by diizzyy** [comment]
@thess 
I use it very rarely so I don't think I'm suitable

**Comment by Smartsmurf** [comment]
@TimelessNL 
I would be happy to contribute. What is the best approach to do so?
Btw, gerbera needs 3 libs, that are not part of OWRT atm. One potential collision with "libupnp" I worked around by naming it "libupnp-1.8", which is suitable for my personal repo, but I wonder what should be done in the offical one.

**Comment by diizzyy** [comment]
Start by doing pull requests for the required libraries (if any), llibupnp is already at 1.8 btw
https://github.com/openwrt/packages/blob/master/libs/libupnp/Makefile
Do not add OpenWrt as copyright, use your own name or drop the line completely and use the latest releases (tarballs preferably if available otherwise codeload).

**Comment by TimelessNL** [comment]
@Smartsmurf Great! If I may, I can also create those pull requests and put you in as maintainer. Since I'm new to Gerbera and don't have any experience with it yet. But would like to switch from MiniDLNA since it does not support m3u8 playlist streaming.

**Comment by TimelessNL** [comment]
I'm trying to refactor the Makefiles from Smartsmurf. But I'm unsure about what to do with libduktape's python dependency.

Right now the makefile call's /usr/bin/python directly. Which does not seem to be preferable right? Maybe someone can advice me on this?

**Comment by diizzyy** [comment]
You can skip it for now as it's only optional for Gerbera

**Comment by Smartsmurf** [comment]
libduktape is just optional. However it requires python just at compile time. No need for python on target.

At the moment I am moving from my libupnp to the official libupnp. Then I think it should be mature enough to raise pull request.

**Comment by TimelessNL** [comment]
Mmh... I see, so duktape uses python in some kind of cmake/automake fashion? Wonder where it is used for and what optional features will be disabled when libduktape is not found. Maybe leave it as a future problem :)

**Comment by jefferyto** [comment]
@Smartsmurf @TimelessNL I believe you can include:

```
PKG_BUILD_DEPENDS:=python/host
```

in the libduktape Makefile to ensure Python is available.

**Pull request merged**
