### PR TITLE
tdb: fix typo

### PR DESCRIPTION
**Pull request by ryzhovau**
Maintainer: @pfzim, @cotequeiroz, @neheb.
Compile tested: Clean Debian 10 host, Entware repo.
Run tested: Entware, mipsel feed

Description: `DEPNEDS` removed. There's no code changes, so `PKG_RELEASE` not bumped.

### CODE REVIEW

**Comment by cotequeiroz** [comment]
There needs to be a `PKG_RELEASE` bump:  there's no code change, but the package's `control` file will be changed to include the "new" dependency.
Do you want to add a commit setting `PKG_BUILD_DEPENDS:=python/host`  to see if `buildpr` (and perhaps the bots) can build it?

**Comment by neheb** [comment]
The package needs to be patched for python3. It's from the same codebase as Samba and libtalloc.

**Comment by ryzhovau** [comment]
> The package needs to be patched for python3

Tried with no success, too old sources. I know it's violating [Python 3 transition](https://github.com/openwrt/packages/issues/8893). So, what's the best way in this case? Fix typo and leave the rest problem as is for awhile?

> There needs to be a PKG_RELEASE bump: there's no code change, but the package's control file will be changed to include the "new" dependency.

@cotequeiroz, control file stays unchanged, you may check existing package, still I bump `PKG_RELEASE` as you wish.

**Comment by ryzhovau** [comment]
The newer tdb releases uses python3 by default, so I'm closing this for now. 

`fdm` (the only one with (`tdb` dependency) package linked against newer `tdb` seems working, at least it starts at MIPS target with no errors as well as `tdbtool` and other internal binaries.

**Pull request closed without merging**
