### PR TITLE
lua-sha2: google code is not longer working - update to github repository 

### PR DESCRIPTION
**Pull request by vavrecan**

### CODE REVIEW

**Comment by hnyman** [comment]
cc  maintainer @lgierth

**Comment by vavrecan** [comment]
@lgierth can you please check this out? repository was not updated for quite time

**Comment by champtar** [comment]
Nack, we need a fix commit, not master

**Comment by vavrecan** [comment]
yup, best would if  lgierth would make release branch in his repo

**Comment by jow-** [comment]
Please merge #2821 instead. The github repo is an identical vopy so I reused the same commit hash.

**Comment by lgierth** [comment]
Thanks for taking care of this @jow- 

I'll try to find out if there's a continued repo somewhere (apart from my copy).

**Pull request closed without merging**
