### PR TITLE
ddns-scripts: Update mythic-beasts URL so that fully qualified hostname can be passed

### PR DESCRIPTION
**Pull request by antxxxx**
Mythic beasts have updated their API so that a fully qualified host name can be passed in to update a DNS entry - details at https://www.mythic-beasts.com/support/api/primary and https://www.mythic-beasts.com/support/domains/dynamic/openwrt
This updates the config settings for mythic-beasts to reflect this

### CODE REVIEW

**Comment by chris5560** [comment]
Could you please increase PKG_RELEASE in Makefile to reflect changes.
The host is called dnsapi4.mythic-beasts.com so if looks like IPv6 support is also available.
Could you please check and if so please also add to services_ipv6
Many thanks

**Comment by antxxxx** [comment]
The services at dnsapi4.mythic-beasts.com and dnsapi6.mythic-beasts.com provide the same functionality - the only difference is one is only reachable via an ipv4 network and one is only reachable on an ipv6 network.
However you can update A records (for ipv4) and AAAA records (for ipv6) using their API on either host so I have added a record to services_ipv6 that updates the AAAA record by calling dnsapi6.mythic-beasts.com figuring if you were updating an ipv6 host then you have ipv6 connectivity and so can reach dnsapi6.mythic-beasts.com

**Comment by chris5560** [comment]
From my point of view OK to merge
Many Thanks
Christian

**Comment by chris5560** [comment]
@antxxxx 
Your pull request is still pending because the title is missing "ddns-scripts: " in front
and you did not sign your work

**Comment by antxxxx** [comment]
I have changed the title and added a commit saying signed off.
I have noticed that https://github.com/openwrt/packages/pull/2634 has also increased PKG_RELEASE to 2 - do you want me to increase the version to 3 now?

**Comment by chris5560** [comment]
Yes please
Many thanks

**Comment by hnyman** [comment]
And you should use git rebase to squash the commits into one commit, which has the proper signed-off-by line.

**Comment by antxxxx** [comment]
Thank you for your patience in helping me get this sorted. Next time I will make sure I read the contributing docs before creating a pull request

Is it OK now?

**Pull request merged**
