### PR TITLE
vnstat: fix musl compatibility

### PR DESCRIPTION
**Pull request by papaj0e**
Signed-off-by: Peter Ivanov <pivanov@hotmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
thanks!

**Comment by papaj0e** [comment]
Hopefully its fine this time :+1:

**Comment by thess** [comment]
Thanks from me too

**Comment by karlp** [comment]
Filed upstream as https://github.com/vergoh/vnstat/issues/21

**Comment by karlp** [comment]
This has now been committed fixed upstream, see https://github.com/vergoh/vnstat/commit/964d7cd62b8626d51bf7ce06564aa9bd1d2b4d4c

**Pull request merged**
