### PR TITLE
grilo: update to 0.3.10 and build with meson

### PR DESCRIPTION
**Pull request by flyn-org**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64 master

Description:
Thank you for https://github.com/openwrt/packages/pull/10043!

### CODE REVIEW

**Comment by neheb** [comment]
That PKG_BUILD_DEPENDS is disgusting. It should be part of meson.mk I think.

ping @dhewg

**Comment by dhewg** [comment]
Hehe, it's not that bad :P

I think I tried setting it automatically in `meson.mk`, and there was a reason for not doing so. The details elude me atm, but iirc it was related to the `.mk` include files. Something like `PKG_BUILD_DEPENDS` needs to be set before including `package.mk` but `meson.mk` has to be included after that?

But anyway, it seems to be standard as is? See `git grep PKG_BUILD_DEPENDS`, e.g. there's `scons` in it too. Vs. `git ls-files \*.mk|xargs fgrep PKG_BUILD_DEPENDS`

**Comment by neheb** [comment]
Seems this doesn't pass CircleCI. Error log: https://5919-20307838-gh.circle-artifacts.com/0/home/build/build_dir/logs/package/feeds/packages/grilo-plugins/compile.txt

**Comment by dhewg** [comment]
That might be a meson issue, I asked here: https://github.com/mesonbuild/meson/issues/821
In the meantime, commenting out `subdir('po')` should be sufficient to fix the build failure.

**Comment by neheb** [comment]
ping @flyn-org

**Comment by neheb** [comment]
ping @flyn-org

**Comment by flyn-org** [comment]
@dhewg, I pushed with a patch that removes "subdir('po')" from meson.build, but the build still seems to fail on the OpenWrt build host.

**Comment by neheb** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'itstool'

**Comment by neheb** [comment]
@jefferyto do you happen to know anything about this error?

**Comment by jefferyto** [comment]
From the stack trace, itstool is [called](https://github.com/mesonbuild/meson/blob/0.52.1/mesonbuild/scripts/yelphelper.py#L58) from `merge_translations()` in yelphelper.py, which in turn is [called](https://github.com/mesonbuild/meson/blob/0.52.1/mesonbuild/scripts/yelphelper.py#L130) from `run()` in the same file.

`merge_translations()` is called only if `langs` is not empty, and `run()` will [populate](https://github.com/mesonbuild/meson/blob/0.52.1/mesonbuild/scripts/yelphelper.py#L115-L116) `langs` from a LINGUAS file (via `read_linguas()`).

Aside from the po directory, the help directory also has a [LINGUAS](https://gitlab.gnome.org/GNOME/grilo-plugins/blob/grilo-plugins-0.3.10/help/LINGUAS) file, so I would try also removing `subdir('help')` from meson.build.

(I would suggest removing `subdir('tests')` as well, since there is no point building tests if you don't intend to run them.)

**Comment by neheb** [comment]
@flyn-org please update as suggested by @jefferyto . Also please remove the src directory. Those autoconf files are no longer used.

**Comment by flyn-org** [comment]
@neheb: build system succeeds now. Thank you, @dhewg and @jefferyto!

**Pull request merged**
