### PR TITLE
dockerd: fix typo in config for no_proxy

### PR DESCRIPTION
**Pull request by joez**
Maintainer: @G-M0N3Y-2503 @1715173329 
Compile tested: x86_64 / master @ 2024-09-13
Run tested: x86_64 / master @ 2024-09-13

Description:
This is a quick fix for the typo in my previous PR #24927, the "http_proxy" here should be "no_proxy"
Sorry for my carelessness

### CODE REVIEW

**Comment by 1715173329** [comment]
Please increase PKG_RELEASE.

**Comment by joez** [comment]
> Please increase PKG_RELEASE.

According to https://openwrt.org/docs/guide-developer/packages#buildpackage_variables

> Increment it when PKG_VERSION stays the same, but when there are functional changes to the installed artifacts.

There is no functional change in this PR, so I think PKG_RELEASE needn't to be increased. Correct me if I am wrong.

**Comment by 1715173329** [comment]
current practice expects increasing PKG_RELEASE when the ipk content is just changed.

**Comment by joez** [comment]
> current practice expects increasing PKG_RELEASE when the ipk content is just changed.

OK, updated

**Pull request merged**
