### PR TITLE
python-*: Update package data

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me / @commodo 
Compile tested: armvirt-32, 2019-02-19 snapshot sdk
Run tested: none

Description:
This updates the Python 2 and 3 versions of each package to share the same title field. (For packages that only had this change, their `PKG_RELEASE` were not incremented.)

This also updates the package title, url and source urls, where necessary.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
ack from me;

[ generally ]
@hnyman or someone else 
should we make the CI more flexible ?
it complains with `Commit subject line MUST start with '<package name>: ' (python-*: Update package data)` 
which is semi-valid ; in the sense that it's not a '<package name>`, but it is a bulk change

**Comment by hnyman** [comment]
> should we make the CI more flexible ?

@champtar and @thess have been the ones active with CircleCI

But I agree with you that the strict commit title verification test in CircleCI is a bit problematic if that prevents running the actual compilation test.

**Comment by commodo** [comment]
Could we split that into a parallel job/task ?
One that checks commits/comments and let the one that runs compilation ?

**Comment by jefferyto** [comment]
Oops... I've amended the commit message to get CircleCI going again.

I agree about making the commit message check more flexible. Perhaps it would help if we had an agreed syntax for bulk updates?

**Comment by jefferyto** [comment]
I took out the updates for python-pyopenssl and python-service-identity, as those depend on python-cryptography and it isn't compiling right now.

**Pull request merged**
