### PR TITLE
qtbase: add package

### PR DESCRIPTION
**Pull request by yangfl**
Signed-off-by: David Yang <mmyangfl@gmail.com>

Maintainer: me
Compile tested: 19.07 arm

### CODE REVIEW

**Comment by BKPepe** [comment]
Hello @yangfl,

I see that qt{4,5} including your package qt5base, which you are trying to add are present in the [video feed](https://github.com/openwrt/video/tree/master/frameworks) under openwrt organization. 

Because of that, I am closing it.

**Comment by yangfl** [comment]
@BKPepe Thanks for mentioning. But this package of qt5base contains only non-gui libraries and is meant for other programs (qbittorrent). Is that OK to add other packages depending on qt into packages feed without adding qt?

**Comment by BKPepe** [comment]
Then you can try to improve the package there or discuss with the maintainer what's the proper solution for it. We can not add packages here, which will depend on external feeds. However, I can see that in the video feed is [something](https://github.com/openwrt/video/blob/1f37050afa6e8a60c490bfc470f866070ada4aee/frameworks/qt5base/Makefile#L108) related to GUI, but I didn't check if it suits your case because it does not make sense to have two similar packages that do the same and will be named differently.

**Comment by mirko** [comment]
I'm not willing to have qt5base in the packages feed *and* qt5base in the video feed.
I'm willing to discuss moving the qt5base package into the packages feed but let's please agree on one ticket to discuss that.

**Pull request closed without merging**
