### PR TITLE
radsecproxy: bump to 1.7.1

### PR DESCRIPTION
**Pull request by cotequeiroz**
Version 1.7.1-rc1 brings compatibility with both openssl 1.0.2 and 1.1.0.  This is a release candidate, not the final version.  Some patches from upstream/master were applied, and another one to remove deprecated API in openssl 1.1.

I have sent the deprecated API patch upstream.  

This is not stable yet, but it may be worth to test it.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

Maintainer: @tohojo 
Compile tested: brcm47xx/ramips/x86_64, openwrt master

### CODE REVIEW

**Comment by cotequeiroz** [comment]
The patch has just been merged upstream.

**Comment by cotequeiroz** [comment]
Hi
My main goal is to upgrade openssl to v. 1.1.0.  Major advantages are the implementation of chacha20-poly1305, ed 25519 curve, and it is supposed to be API compatible with the next major release, which will have TLS 1.3.
It brings major API changes, which breaks compatibility with most packages.  So we have two ends that need to move--openssl package in one end, and the imcopatible packages in the other. I just don't want to have one end wait for the other to move, and everything remain still. 
It is not my intention, however to force these changes, and I apologize if I seem "pushy". This is not going to be in 18.06. As soon as you think this package is good to go, we upgrade. RC or final, it's your call, and if you want me to withdraw this PR, let me know.
As for the high number of patches, it makes it easier to trace their origins.  We can flatten them before merging, if you're OK with them.
Cheers,
Eneas

**Comment by tohojo** [comment]
Eneas Queiroz <notifications@github.com> writes:

> My main goal is to upgrade openssl to v. 1.1.0.

Right, well if radsecproxy becomes a blocker for that before 1.7.1 is
released, sure, we can merge an -rc. But if it isn't, I'd rather wait :)

> As for the high number of patches, it makes it easier to trace their
> origins.  We can flatten them before merging, if you're OK with them.

Ah, no, didn't mean the number of patches. I agree that keeping a 1-to-1
relation to upstream commits is better.

Just that having an -rc with patches would indicate that, well, maybe
there's a reason why 1.7.1 is not ready yet, and maybe we should hold
off on inflicting it on users ;)

-Toke

**Comment by tohojo** [comment]
Looks good, thanks!

**Pull request merged**
