### PR TITLE
[19.07] less: update ALTERNATIVES

### PR DESCRIPTION
**Pull request by zhanhb**
Avoid conflict with busybox

Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>
(cherry picked from commit d866393)

Maintainer: @Zokormazo @BKPepe 
Compile tested: None
Run tested: None

Description: Apply PR #12467 on branch `openwrt-19.07`

### CODE REVIEW

**Comment by BKPepe** [comment]
Compile and run tested. Otherwise NACK.

**Comment by zhanhb** [comment]
I test the commit on branch master. It should work as expected on branch openwrt-19 too.

**Comment by BKPepe** [comment]
> I test the commit on branch master. It should work as expected on branch openwrt-19 too.

That's kind of a little bit different what I can find in this PR:
https://github.com/openwrt/packages/pull/12467

**Comment by zhanhb** [comment]
The difference is https://github.com/openwrt/packages/commit/4834f60f6ffddd5a6e8298472d177166774ec8fc

**Pull request merged**
