### PR TITLE
simple-adblock: config update file fix

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 19.07.4
Run tested: mvebu, WRT3200ACM, 18.06.8, config update, restart/reload/dl

Description:
This contains the following fixes in order of importance:
1. config-update script was updated to reflect change from http to https-only for winhelp2002.mvps.org. Every user which has config auto-update enabled will receive this fix.
2. config-update URL is customizable. 
3. PC-correct terms and new README URL in the Makefile.
4. README has been updated to refer to the new README location.
5. test.sh has been introduced.

Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by stangri** [comment]
I would appreciate help understanding why the build is failing? Could it be because of the newline at the end of test.sh?

**Comment by aparcar** [comment]
@stangri Is it possible the version command is simply not there?

```
Syntax: /etc/init.d/simple-adblock [command]

Available commands:
	start	Start the service
	stop	Stop the service
	restart	Restart the service
	reload	Reload configuration files (or restart if service does not implement reload)
	enable	Enable service autostart
	disable	Disable service autostart
	enabled	Check if service is started on boot
	running	Check if service is running
	status	Service status
	check	Checks if specified domain is found in current block-list
	dl	Force-downloads all enabled block-list
	sizes	Displays the file-sizes of enabled block-lists
	show	Shows the service last-run status
```

**Comment by stangri** [comment]
Thanks, I'll check again, but I thought I've amended the commit with the necessary code.

**Comment by stangri** [comment]
@aparcar I appreciate the second pair of eyes, pushed the wrong file before. ;)

**Review by aparcar — APPROVED** [review]

**Comment by dibdot** [comment]
@stangri What's the purpose of the introduced 'test.sh'? I can't find any reference in the Makefile yet!?

**Comment by stangri** [comment]
> @stangri What's the purpose of the introduced 'test.sh'? I can't find any reference in the Makefile yet!?

@dibdot It's for CI testing as I gathered from Paul's comment on one of the previous PRs: https://github.com/openwrt/packages/pull/13457#issuecomment-696390011.

**Comment by aparcar** [comment]
Also [here](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#continuous-integration)

**Comment by dibdot** [comment]
ah thanks, I didn't realize that

**Pull request merged**
