### PR TITLE
bzr: New package

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer (to be): me
Compile tested: armvirt 32/64, 2019-03-18 snapshot sdk
Run tested: armvirt 32/64, 2019-03-18 snapshot (`bzr version; bzr branch lp:bzr`)

Description:
From the readme:
Bazaar (bzr) is a decentralized revision control system, designed to be easy for developers and end users alike. Bazaar is part of the GNU project to develop a complete free operating system, and a project of Canonical.

This is latest (last?) released version (2.7.0), patched up to the development version (2.8.0dev1), as there isn't a downloadable tarball for trunk. As development has stopped in 2017, the trunk version may never be officially released. (Debian/Ubuntu also packages the trunk version as 2.7.0.)

This also includes a host package definition for use by other packages.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
lgtm

**Comment by diizzyy** [comment]
Please don't add software that's dead upstream.

If you want bzr support for whatever reason please make a package for breezy instead.
https://www.breezy-vcs.org/

**Comment by jefferyto** [comment]
@diizzyy The software may be dead upstream, but there are still projects that use bzr.

I'm trying to fix #8210, but due to your prompting, I will try fixing upstream. I'm going to leave this PR open as well.

**Comment by jefferyto** [comment]
Actually it's indirect dependencies of prometheus that would need to be updated, it would be much easier to support `bzr` (or breezy).

**Comment by jefferyto** [comment]
To fix #8210, any breezy package would need to symlink `brz` to `bzr` (since Go is looking for `bzr`). I'm not a big fan of one package "taking over" another (software) package's namespace... Would still prefer if this PR is merged.

**Comment by diizzyy** [comment]
That's fine as we've never packaged bzr at least within at least 1 year or so.

**Comment by neheb** [comment]
As far as prometheus is concerned, this seems to remove the bzr dependency from there: https://github.com/prometheus/prometheus/pull/5378

**Comment by jefferyto** [comment]
@neheb fantastic news :joy:

**Comment by jefferyto** [comment]
Closing.

**Pull request closed without merging**
