### PR TITLE
Shorewall: Bump to 5.2.8

### PR DESCRIPTION
**Pull request by wvdakker**
Maintainer: wvdakker@wilsoft.nl
Compile tested: xrx200, P2812-F1, trunk
Run tested: xrx200, P2812-F1, run/config

Description:
New upstream release

### CODE REVIEW

**Comment by neheb** [comment]
build failure is due to iproute2 failing to compile. Unfortunately, nobody is merging the version update.

**Comment by wvdakker** [comment]
Perhaps its me, I couldnt find any PR or issues on iproute2. iproute2 is the latest version there is.
So the problem is upstream? Also there I couldnt find any issues realated to this.

**Comment by neheb** [comment]
It's only with uClibc-ng. So it's fine.

**Comment by wvdakker** [comment]
Thanks!

**Pull request merged**
