### PR TITLE
stunnel: bring back stunnel

### PR DESCRIPTION
**Pull request by mhaas**
All details in commit!

### CODE REVIEW

**Comment by sbyx** [comment]
thanks for the package. is there any reason you are depending on libpthread even though --with-threads is set to fork? also please try to avoid too many commits and rather squash them into one.

**Comment by mhaas** [comment]
@sbyx Any advice how I can squash the commits into one? git reset --hard?

**Comment by sbyx** [comment]
You can follow e.g. this guide in your local branch:
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

and then do a forced push. This should update your pull request automatically.

**Comment by mhaas** [comment]
Done, thanks.

I am not sure if -fstack-protector/ssp is handled correctly if it is enabled in the OpenWrt build options, though.

**Comment by mhaas** [comment]
On second thought, perhaps I should add -s and -g to drop root privileges. Is it better to do that in the init script or should I provide a custom config file?

**Comment by sbyx** [comment]
whatever you prefer. init script is okay usually.

**Comment by mhaas** [comment]
Okay. I added setuid calls etc to the example.conf. Stunnel 5 does not accept these on the command line anymore.

I've also added an example config section. Otherwise, stunnel won't start.

I think we're good to go.

**Comment by champtar** [comment]
@mhaas, can you remove ```[packages] ``` in the commit title

**Comment by mhaas** [comment]
@champtar Done!

**Comment by champtar** [comment]
it compiles, so lets give it a try
Thanks @mhaas

**Pull request merged**
