### PR TITLE
[21.02] xfrpc: add xfrpc to 21.02

### PR DESCRIPTION
**Pull request by liudf0716**
add xfrpc to 21.02

Signed-off-by: Dengfeng Liu <liudf0716@gmail.com>

### CODE REVIEW

**Comment by do66** [comment]
remark!!!

**Comment by BKPepe** [comment]
I am not quite sure, if we should add new packages to the old stable version.

**Comment by 1715173329** [comment]
> I am not quite sure, if we should add new packages to the old stable version.

Anyway, we've done this many times, right? From my side, I don't mind one more "exception".
xfrpc is not a library and no package would pick it, so it should not break anything in tree.

**Comment by liudf0716** [comment]
@1715173329 Firstly, thank you for supporting the adoption of the XFRC package. 
@BKPepe 
As @1715173329 mentioned, XFRC is a standalone application. It's old version has been ported to the 21.02 branch by someone else https://github.com/liudf0716/xfrpc/issues/34 , for the sake of maintaining the project, I'm submitting the PR.

**Comment by do66** [comment]
I have a ipkvm，it use xfrpc，the openwrt-ver is 21.02，xfrpc can update new version？

**Comment by 1715173329** [comment]
i will merge this in 2 days if there's no further objection.

**Comment by BKPepe** [comment]
@dibdot, @diizzyy , @hnyman , @neheb any thoughts about this?

**Comment by dibdot** [comment]
@BKPepe Personally, I wouldn't put new packages into this old stable branch - even though we've done it before.

**Comment by liudf0716** [comment]
@dibdot Hi dibdot, I would like to say a few words about why it should be merged. I think openwrt community should attract more people to use it and improve it. In fact, as product's feature, it's upgrade is really very slow, many people have no ability to upgrade they product once they use it and get used to it. but for community's health development, we need more users' response to improve our product. If we discard them, they will discard us.

**Comment by 1715173329** [comment]
lgtm

**Comment by liudf0716** [comment]
@1715173329 thanks

**Pull request merged**
