### PR TITLE
ksmbd updates for 19.07

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @Andy2244 

keeping this here until a new release is to be cut. A really nasty file bug crept in the 3.3.4 release: https://github.com/cifsd-team/cifsd/issues/498

ping @hauke

### CODE REVIEW

**Comment by erdoukki** [comment]
Needed also for master !

thanks for the PR

**Comment by neheb** [comment]
https://github.com/openwrt/packages/commit/851b9b252fc5f5fdd541fd3a18ab393bdac9a6e8 https://github.com/openwrt/packages/commit/7a1a8f3659cf79237fba6394fbea42755af38a52

**Comment by erdoukki** [comment]
Thanks !

**Comment by neheb** [comment]
@Andy2244 what do you think about using ksmbd.control to handle the termination instead of the init script?

**Comment by neheb** [comment]
@Andy2244 bad news. latest version is 5.4 and above only. Can you add the fix from https://github.com/cifsd-team/cifsd/issues/507 in the init script for master so it can be backported here?

**Comment by Andy2244** [comment]
> 
> 
> @Andy2244 bad news. latest version is 5.4 and above only. Can you add the fix from [cifsd-team/cifsd#507](https://github.com/cifsd-team/cifsd/issues/507) in the init script for master so it can be backported here?

Sure if i'm back from Easter-holidays.

**Comment by Neustradamus** [comment]
@neheb: Thanks for the update!

**Comment by neheb** [comment]
Forgot this can't be updated past 3.3.7. kernel minimum is 5.4 now.

**Comment by BKPepe** [comment]
Based on a recent conversation on IRC channel ``#openwrt-adm``, there should be released OpenWrt 19.07.8 somehow soon. They were talking about next week, so we should merge it a few days early so the situation with [the ksmbd and it's dependency](https://openwrt.org/releases/19.07/notes-19.07.7#regressions) will not happen anymore.

**Comment by Neustradamus** [comment]
@neheb: Can you look for a 3.4.0 update?

**Comment by neheb** [comment]
Not for 19.07. newer versions of ksmbd require kernel 5.4.

**Comment by Neustradamus** [comment]
Yes for 21.02...

**Comment by hauke** [comment]
@neheb @BKPepe  I would like to do an 19.07.8 today, if this should go in could you merge it and also test it please. I can also shift the tagging to tomorrow.

**Comment by hauke** [comment]
Update merged for the next release.

**Comment by Neustradamus** [comment]
Thanks to @neheb and @hauke.

**Pull request merged**
