### PR TITLE
sstp-client: updated to version 1.0.10

### PR DESCRIPTION
**Pull request by fededim**
Signed-off-by: Federico Di Marco <fededim@gmail.com>

### CODE REVIEW

**Comment by fededim** [comment]
I have just checked the snapshots directory and the package sstp-client is not there...any problems during compilation ?

https://downloads.openwrt.org/snapshots/trunk/arm64/generic/packages/packages/

**Comment by sbyx** [comment]
See http://buildbot.openwrt.org:8010/broken_packages/arm64/sstp-client/compile.txt

**Comment by fededim** [comment]
Hmmm very strange error: unknown type name 'uint8_t' as if a basic include file is missing (#include <stdint.h>)...however on my ar7xx toolchain the compilation is fine (ar7xx has still to be compiled by openwrt build servers) I'll check as soon as I can

**Comment by fededim** [comment]
I RE-CLONED openwrt git database in another subdirectory (openwrt2), launched MAKE to recompile everything (including toolchain), INTERRUPTED the make just after it had finished building the package sstp-client flawlessly on ar71xx (from openwrt build server the log compilation fails also on ar71xx http://buildbot.openwrt.org:8010/broken_packages/ar71xx/sstp-client/compile.txt)

https://vid.me/qex6

Anyone has any idea about this issue ? I am not a linux expert

**Pull request merged**
