### PR TITLE
[19.07]minidlna: Added support RMVB

### PR DESCRIPTION
**Pull request by VergLsm**
Maintainer: me
Compile tested: sunxi 19.07 sdk
Run tested: sunxi 19.07

Description:
Hi,
It seems that the original project no longer accepts pull requests, but I think it is not difficult to support RMVB files

### CODE REVIEW

**Comment by neheb** [comment]
I'm fine with this.

**Comment by VergLsm** [comment]
@neheb Should I commit on the master branch?

**Comment by neheb** [comment]
Of course.

**Comment by VergLsm** [comment]
Do you mean I don't have to reopen a new pull request?

**Comment by neheb** [comment]
Yes, do open a new one. I will merge both.

**Pull request closed without merging**
