### PR TITLE
grilo-plugins: update to 0.3.5

### PR DESCRIPTION
**Pull request by MikePetullo**
Signed-off-by: W. Michael Petullo mike@flyn.org
Maintainer: me
Compile tested: AR7xxx, Mikrotik devices with NAND/NOR flash, LEDE master b153dbf0

Description:
grilo-plugins: update to 0.3.5

### CODE REVIEW

**Comment by mhei** [comment]
I did a local compile test by selecting randomly two plugins with menuconfig, but the compilation failed with:

<pre>...
checking for xgettext... /srv/openwrt/lede-source.git/staging_dir/hostpkg/bin/xgettext
checking for msgmerge... /srv/openwrt/lede-source.git/staging_dir/hostpkg/bin/msgmerge
checking for msgfmt... /srv/openwrt/lede-source.git/staging_dir/hostpkg/bin/msgfmt
checking for gmsgfmt... /srv/openwrt/lede-source.git/staging_dir/hostpkg/bin/msgfmt
checking for perl... /srv/openwrt/lede-source.git/staging_dir/host/bin/perl
checking for perl >= 5.8.1... 5.22.1
checking for XML::Parser... ok
checking for itstool... no
configure: error: itstool not found
</pre>

@MikePetullo: any ideas?

**Comment by MikePetullo** [comment]
I tried to pull the itstool and xmllint checks from the configure script, but Travis still seems to complain.

**Comment by champtar** [comment]
Hi @MikePetullo 
Something else than grilo-plugins is failing to build (likely a dependency),
I'll try to have a look tomorrow

**Comment by mhei** [comment]
I can confirm that with your new patch my local test build compiles fine.

**Pull request merged**
