### PR TITLE
Host python changes

### PR DESCRIPTION
**Pull request by jefferyto**
This changes the prefix for host Python to address the issue raised in https://github.com/openwrt/packages/pull/2360#issuecomment-192148541

### CODE REVIEW

**Comment by commodo** [comment]
rest is fine from me

**Comment by commodo** [comment]
On another note ; @jefferyto would you like to take ownership of the Python packages from me (python, python-setuptools and python-pip) ?
I'm a bit swamped with other stuff, and it looks like I'm mostly getting in the way of other Python packages.

And I'm no longer using Python on OpenWRT as I used to.
It's fine if you don't want to take ownership :)

**Comment by jefferyto** [comment]
Re: ownership. Thanks for asking @commodo :smile:

I'm not sure if I have the necessary experience or free time to maintain the main Python packages right now... I'm moonlighting as a Python dev at the moment because I wanted to get obfsproxy running on my router. Perhaps I can continue submitting patches with you overseeing for a little while longer, and we can come back to this topic if it works out?

**Comment by commodo** [comment]
sure; fine from my side

**Pull request merged**
