### PR TITLE
adguardhome: Update adguardhome 0.108.0-b5

### PR DESCRIPTION
**Pull request by jamesmacwhite**
Signed-off-by: James White <james@jmwhite.co.uk>

Maintainer: @dobo90 @alaviss 
Compile tested: In progress
Run tested: In progress

Description:

Since the Go 1.18 update in #18147, this breaks the adguardhome package in 22.03 and master due to requiring Go 1.17 to successfully build.

There is no easy way to resolve this, but having the 0.108 beta in snapshot and maybe 22.03 may be the solution in the interim, otherwise both of these branches will not have the package available at all, and several posts on the community forum suggest this has been discovered by users.

I'm making this PR for the CI test, while also compile testing the 0.108.0b5 package with OpenWrt build root using Go 1.18 to see if it's feasible. I believe that Go 1.18 should work, but I need to confirm.

I know one of the issues for Go 1.18 with the 0.107 releases is the bundled quic-go which is shown in the failogs does not support 1.18, but looking at the AdGuardHome source there has been Go 1.18 support commits made to the latest source, but not sure if it's part of the latest beta release, so I'm making this as a draft PR to see how the CI's cope.

### CODE REVIEW

**Comment by alaviss** [comment]
As an alternative, we can backport this commit to the stable version: https://github.com/AdguardTeam/AdGuardHome/commit/8455940b5951579b0694f390af933fcd3665240e

**Comment by jamesmacwhite** [comment]
@alaviss That's an option, I'm not too keen on a beta release in the branch to be honest, would we need to create a patch file to apply this, given it's not present in any of the 0.107.x releases currently?

It does look like 0.108 can be built with Go 1.18 so that's good when the next stable is 0.108.

**Comment by alaviss** [comment]
> would we need to create a patch file to apply this, given it's not present in any of the 0.107.x releases currently?

We can use this handy github feature to do it: https://github.com/AdguardTeam/AdGuardHome/commit/8455940b5951579b0694f390af933fcd3665240e.patch

This is assuming that the patch works on 0.107.5.

**Comment by jamesmacwhite** [comment]
@alaviss Handy indeed, happy to test it against the 0.107.5 release. If it does work, then that's likely the better option but not entirely sure if any other Go specific issues with 1.17 vs 1.18 will arise, but the faillogs suggest that quic-go is the issue.

If it doesn't work, do you think we should consider having 0.108 b5 in master and openwrt-22.03 as a temporarily solution?

**Comment by jamesmacwhite** [comment]
Applying that patch to the 0.107.5 source unfortunately fails on part of it:

> Applying ./patches/000-quic-go-1.18-fix.patch using plaintext:
patching file go.mod
Hunk #1 succeeded at 16 with fuzz 2.
Hunk #2 FAILED at 46.
1 out of 2 hunks FAILED -- saving rejects to file go.mod.rej
patching file go.sum
Hunk #1 succeeded at 137 (offset -11 lines).
Hunk #2 succeeded at 148 (offset -11 lines).
Patch failed!  Please fix ./patches/000-quic-go-1.18-fix.patch!
make[2]: *** [Makefile:82: /home/jameswhite/Projects/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/adguardhome-0.107.5/.prepared_5d6c737850d8ed01863603c5cbca08d7_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[2]: Leaving directory '/home/jameswhite/Projects/openwrt/feeds/packages/net/adguardhome'
time: package/feeds/packages/adguardhome/compile#0.27#0.00#0.21
    ERROR: package/feeds/packages/adguardhome failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/adguardhome/compile] Error 1
make[1]: Leaving directory '/home/jameswhite/Projects/openwrt'
make: *** [/home/jameswhite/Projects/openwrt/include/toplevel.mk:230: package/adguardhome/compile] Error 2

**Comment by alaviss** [comment]
Can you try this patch?

```diff
diff --git a/go.mod b/go.mod
index 4ff78f47..627ae389 100644
--- a/go.mod
+++ b/go.mod
@@ -16,7 +16,7 @@ require (
 	github.com/google/renameio v1.0.1
 	github.com/insomniacslk/dhcp v0.0.0-20210310193751-cfd4d47082c2
 	github.com/kardianos/service v1.2.0
-	github.com/lucas-clemente/quic-go v0.24.0
+	github.com/lucas-clemente/quic-go v0.25.0
 	github.com/mdlayher/ethernet v0.0.0-20190606142754-0394541c37b7
 	github.com/mdlayher/netlink v1.4.0
 	github.com/mdlayher/raw v0.0.0-20210412142147-51b895745faf
diff --git a/go.sum b/go.sum
index eba4f6f9..8b58cb8b 100644
--- a/go.sum
+++ b/go.sum
@@ -139,6 +139,8 @@ github.com/kr/text v0.2.0 h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=
 github.com/kr/text v0.2.0/go.mod h1:eLer722TekiGuMkidMxC/pM04lWEeraHUUmBw8l2grE=
 github.com/lucas-clemente/quic-go v0.24.0 h1:ToR7SIIEdrgOhgVTHvPgdVRJfgVy+N0wQAagH7L4d5g=
 github.com/lucas-clemente/quic-go v0.24.0/go.mod h1:paZuzjXCE5mj6sikVLMvqXk8lJV2AsqtJ6bDhjEfxx0=
+github.com/lucas-clemente/quic-go v0.25.0 h1:K+X9Gvd7JXsOHtU0N2icZ2Nw3rx82uBej3mP4CLgibc=
+github.com/lucas-clemente/quic-go v0.25.0/go.mod h1:YtzP8bxRVCBlO77yRanE264+fY/T2U9ZlW1AaHOsMOg=
 github.com/lunixbochs/vtclean v1.0.0/go.mod h1:pHhQNgMf3btfWnGBVipUOjRYhoOsdGqdm/+2c2E2WMI=
 github.com/mailru/easyjson v0.0.0-20190312143242-1de009706dbe/go.mod h1:C1wdFJiN94OJF2b5HbByQZoLdCWB1Yqtg26g4irojpc=
 github.com/marten-seemann/qpack v0.2.1/go.mod h1:F7Gl5L1jIgN1D11ucXefiuJS9UMVP2opoCp2jDKb7wc=
@@ -147,6 +149,8 @@ github.com/marten-seemann/qtls-go1-16 v0.1.4 h1:xbHbOGGhrenVtII6Co8akhLEdrawwB2i
 github.com/marten-seemann/qtls-go1-16 v0.1.4/go.mod h1:gNpI2Ol+lRS3WwSOtIUUtRwZEQMXjYK+dQSBFbethAk=
 github.com/marten-seemann/qtls-go1-17 v0.1.0 h1:P9ggrs5xtwiqXv/FHNwntmuLMNq3KaSIG93AtAZ48xk=
 github.com/marten-seemann/qtls-go1-17 v0.1.0/go.mod h1:fz4HIxByo+LlWcreM4CZOYNuz3taBQ8rN2X6FqvaWo8=
+github.com/marten-seemann/qtls-go1-18 v0.1.0-beta.1 h1:EnzzN9fPUkUck/1CuY1FlzBaIYMoiBsdwTNmNGkwUUM=
+github.com/marten-seemann/qtls-go1-18 v0.1.0-beta.1/go.mod h1:PUhIQk19LoFt2174H4+an8TYvWOGjb/hHwphBeaDHwI=
 github.com/matttproud/golang_protobuf_extensions v1.0.1/go.mod h1:D8He9yQNgCq6Z5Ld7szi9bcBfOoFv/3dc6xSMkL2PC0=
 github.com/mdlayher/ethernet v0.0.0-20190606142754-0394541c37b7 h1:lez6TS6aAau+8wXUP3G9I3TGlmPFEq2CTxBaRqY6AGE=
 github.com/mdlayher/ethernet v0.0.0-20190606142754-0394541c37b7/go.mod h1:U6ZQobyTjI/tJyq2HG+i/dfSoFUt8/aZCM+GKtmFk/Y=
```

I generated this by running

```
go get github.com/lucas-clemente/quic-go@v0.25.0
```

then get the git diff

**Comment by jamesmacwhite** [comment]
@alaviss That patch does apply cleanly, doing a compile test to see if it can build 0.107.5 with Go 1.18.

**Comment by jamesmacwhite** [comment]
@alaviss Seems to build OK, will close this PR in favour of the newer one with the patch, along with letting the CIs build the package to confirm.

**Pull request closed without merging**
