### PR TITLE
Use STAGING_DIR_HOSTPKG where appropriate

### PR DESCRIPTION
**Pull request by NeoRaider**
Maintainers: various
Compile tested: Host builds of all affected packages have been tested and are unchanged. Some packages (libmraa, libuqm) failed to build without these patches, which is also unchanged.

Description:

As both LEDE and OpenWrt have STAGING_DIR_HOSTPKG now, we can start to rely on it. See 73b7f55424de52d8179a9ad808252fe3bf8dcc9d for more information on STAGING_DIR_HOSTPKG.

STAGING_DIR_HOSTPKG won't actually be changed before the first LEDE release (it is equivalent to $(STAGING_DIR)/host), so this simple search/replace cleanup is safe to apply. Doing this cleanup now will be useful for the Gluon project (an OpenWrt/LEDE based firmware framework) for experimenting with modifying STAGING_DIR_HOSTPKG before doing this in the LEDE upstream.

Also fixes a typo in the dbus Makefile ("STAGIND_DIR").

### CODE REVIEW

**Comment by mhei** [comment]
For the php7 part:
Acked-by: Michael Heimpold <mhei@heimpold.de>

**Comment by thess** [comment]
LGTM...

**Comment by luizluca** [comment]
ruby: I cannot test/compile in the following days but as long as HOST_BUILD_PREFIX is equals to STAGING_DIR_HOSTPKG or target/ruby compile in a clean staging tree, ACK

**Comment by jefferyto** [comment]
LGTM

**Pull request merged**
