### PR TITLE
net-snmp: Update to 5.8.0

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @stintel 
Compile tested: mvebu

### CODE REVIEW

**Comment by neheb** [comment]
Note that https://github.com/openwrt/packages/pull/5821 and https://github.com/openwrt/packages/pull/5584 are still open.

**Comment by karlp** [comment]
Just so it's clear, this has been compile tested _only_ is that right?  you removed the line from the template about where you'd been run testing it.

**Comment by neheb** [comment]
Correct

**Comment by stintel** [comment]
9251f51084366f3905eb2608d946574f2372a42d

**Pull request closed without merging**
