### PR TITLE
domoticz: Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @stintel 
Compile tested: powerpc8540

### CODE REVIEW

**Comment by diizzyy** [comment]
Submit this upstream instead?

**Comment by stintel** [comment]
0xx prefix is for upstream backports. Is this an upstream backport? If yes, please include the full patch including author, subject and commit message. If not, please submit it upstream and prefix with 1xx.

**Comment by neheb** [comment]
Renamed. Upstream submission would require more work as there is code not compiled for OpenWrt.

**Comment by neheb** [comment]
@stintel upstreamed

**Pull request merged**
