### PR TITLE
openwisp-monitoring: add missing PKG_VERSION for APK

### PR DESCRIPTION
**Pull request by okraits**
The 'PKG_VERSION' string was missing and only 'PKG_SOURCE_VERSION' string was used.

Maintainer: @nemesifier 
ping @aparcar

### CODE REVIEW

**Review by nemesifier — APPROVED** [review]

**Comment by okraits** [comment]
@aparcar The builds fail with `Package HASH check failed`. I don't understand why. Does this refer to `PKG_MIRROR_HASH`? But that wasn't changed for other packages either.

**Comment by aparcar** [comment]
The created archive contains a folder with the package name and version. Since you changed the version, the package hash changed. Set it to `97ae00b37518919079d894622c664d330bbf0cb0ee1b68c84991b459c1a087ee` and things should work.

**Comment by okraits** [comment]
@aparcar Thanks for the hint. Where can I see the created archive? The makefile should be fine now, right?

**Comment by aparcar** [comment]
LGTM

**Comment by okraits** [comment]
Where can I see the created archive? To get the new hash value

**Comment by aparcar** [comment]
`make package/<PACKAGE>/{download,check} FIXUP=1` does the magic

**Comment by okraits** [comment]
@nemesifier @aparcar Please merge if it looks fine and when you have the time.

**Comment by nemesifier** [comment]
Thank you very much @okraits @feckert @aparcar :pray:

**Comment by okraits** [comment]
Thank you @aparcar for the guidance!

**Pull request merged**
