### PR TITLE
net/vnstat: Make data directory an uci option

### PR DESCRIPTION
**Pull request by dfc-d**
Being able to alter the config for the data directory via LuCI
would be useful, therefore add UCI option to data set datadir

Signed-off-by: Daniel Dickinson openwrt@daniel.thecshore.com

### CODE REVIEW

**Comment by dfc-d** [comment]
@jow- 
Any objections to this commit?

**Comment by jow-** [comment]
Hmm. Not sure if writing into `vnstat.conf` on every service start is desired behaviour (or is busybox' `sed` clever enough to not modify a file if no substitution occured?)

No real objection from my side though some might perceive writing into non-uci configs due to uci settings a no-go

**Comment by dfc-d** [comment]
On Fri, 2016-05-27 at 09:02 -0700, Jo-Philipp Wich wrote:
> Hmm. Not sure if writing into vnstat.conf on every service start is
> desired behaviour (or is busybox' sed clever enough to not modify a
> file if no substitution occured?)
> 
Did I miss the check for 'what is the current setting'?  I thought I had
that in there (if I got it right, the change should only occur if has
not already occurred as vnstat.conf is a conffile in /etc is preserved
across sysupgrade and reboots).

Regards,

Daniel

**Comment by dfc-d** [comment]
if [ -n "$datadir" ]; then
			if [ "$lib" != "$datadir" ]; then

The code to change /etc/vnstat.conf is only triggered on this condition, which is to say only if datadir is not the same as what is configured in /etc/vnstat.conf.

**Comment by dfc-d** [comment]
Any further comments?  As mentioned it does in fact only write the config file when there is a change.

**Comment by dfc-d** [comment]
@jow- 
Any more comments or okay to merge?

**Comment by dfc-d** [comment]
@jow- ping?

**Comment by cshoredaniel** [comment]
Sorry, thought I was given access to this repo; was luci.  Would it be possible to get access to this repo and merge this commit (and others per guidelines; basically wait long enough for busy people to respond with objections, merges should be straightforward or tested, don't merge at will (use reasonable judgment), etc.

**Comment by dfc-d** [comment]
going to reopen without writing into flash

**Pull request closed without merging**
