### PR TITLE
gnupg: add PKG_CPE_ID

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add PKG_CPE_ID:=cpe:/a:gnupg:gnupg to allow scanning for CVEs.

### CODE REVIEW

**Comment by neheb** [comment]
why not fold in the other gnupg PR?

**Comment by PolynomialDivision** [comment]
> why not fold in the other gnupg PR?

That other was a version bump and that is security related. So I thought I would do two seperate realted PRs. Should I change it?

**Comment by neheb** [comment]
Might as well. I don't think such a change deserves its own PR.

**Comment by PolynomialDivision** [comment]
Okay, I added it now to the other PR.

**Pull request closed without merging**
