### PR TITLE
transmission: Update to 2.93 + fixes

### PR DESCRIPTION
**Pull request by neheb**
Some DNS rebind issues were discovered in transmission's RPC support. This requires port 9091 to be open WAN side at least. DNS rebinding protection also has to be disabled in DNSMasq, which is enabled by default. Also some memory leaks were fixed.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

compile-tested on ramips.

### CODE REVIEW

**Comment by neheb** [comment]
This is not ready. Other issues have come up.

**Comment by hnyman** [comment]
you should update also PKG_MIRROR_HASH

**Comment by neheb** [comment]
Commit is ready. @champtar or whoever please pull.

**Comment by hnyman** [comment]
@neheb 
> Commit is ready. @champtar or whoever please pull.

Hmm. It was not that ready. The patches do not apply correctly: the first patch has offset, while second patch does not apply at all.

I will revert the commit, and you need to refresh the patches properly, and do a new pull request.

```
Applying ./patches/020-use-internal-miniupnp.patch using plaintext: 
patching file configure.ac
Hunk #1 succeeded at 378 (offset -8 lines).

Applying ./patches/040-fix-for-mbedtls.patch using plaintext: 
patching file configure.ac
Hunk #1 FAILED at 154.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
Patch failed!  Please fix ./patches/040-fix-for-mbedtls.patch!
Makefile:199: recipe for target '/data/bowl-builder/arm_cortex-a15_neon-vfpv4/build/sdk/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/transmission-openssl/transmission-2.93/.prepared_223d6de1800dc68ae585c0f2a9151f01_18f1e190c5d53547fed41a3eaa76e9e9' failed
make[3]: *** [/data/bowl-builder/arm_cortex-a15_neon-vfpv4/build/sdk/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/transmission-openssl/transmission-2.93/.prepared_223d6de1800dc68ae585c0f2a9151f01_18f1e190c5d53547fed41a3eaa76e9e9] Error 1
```
Same was apparently also visible in the travis output, but I didn't check that as you sounded so confident.

**Comment by neheb** [comment]
Fixed

**Pull request merged**
