### PR TITLE
dcwifi: Update component versions

### PR DESCRIPTION
**Pull request by csonsino**
update package versions and hashes
remove bzero patches
remove uclibc++ patch

Signed-off-by: Carey Sonsino <careys@edgewaterwireless.com>
Signed-off-by: Carey Sonsino <csonsino@gmail.com>

Maintainer: me / @csonsino
Compile tested: Atheros AR7xxx/AR9xxx - Atheros AR7161 rev 2, Netgear WNDR3800, OpenWrt master
Run tested: Atheros AR7xxx/AR9xxx - Atheros AR7161 rev 2, Netgear WNDR3800, Configured the Dual Channel Wi-Fi daemon, connected a Raspberry Pi client, and verified functionality

Description:
Use the new versions of all dcwifi components (dcstad, dcwapd, libdcwproto, libdcwsocket, macremapper, mrmctl)

### CODE REVIEW

**Comment by neheb** [comment]
I've been asked on IRC if you can remove the dcwifi directory and move all of the packages to their respective directories (libs, net, kernel).

**Comment by csonsino** [comment]
> I've been asked on IRC if you can remove the dcwifi directory and move all of the packages to their respective directories (libs, net, kernel).

That makes sense.  Are these the preferred locations?
```
kernel/macremapper
libs/libdcwproto
libs/libdcwsocket
net/dcstad
net/dcwapd
net/mrmctl
```

**Comment by csonsino** [comment]
I think that `mrmctl` could go under `utils` instead of `net`, but it's up to you.

**Comment by neheb** [comment]
mrmctl is currently listed in Utilities. It should be listed in Network.

Network is the right place for it. It controls a network module.

**Comment by neheb** [comment]
I would also like the patches to apply cleanly and not have warnings like such: https://downloads.openwrt.org/snapshots/faillogs/mipsel_74kc/packages/macremapper/compile.txt . Note the offset.

(The actual compile error is an SDK bug. I have no idea how to fix.)

**Comment by csonsino** [comment]
> ok I found a fix now: [x-wrt/packages@16bbe24](https://github.com/x-wrt/packages/commit/16bbe248a9f67ba9b2bd9420ed6e1cb605a45121)

@ptpt52 I would like to get this fixed, but I'm not sure about the etiquette of stealing someone's fix/commit credit :)  I'll gladly do the PR work if you can't be bothered, just let me know.

**Comment by ptpt52** [comment]
@csonsino that is ok

**Pull request merged**
