### PR TITLE
wsdd2: fix install warning on compile

### PR DESCRIPTION
**Pull request by Ansuel**
Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Andy2244** [comment]
There is a PR template for a reason and whats the actual problem/warning?

**Comment by Ansuel** [comment]
This
```
Enabling urandom_seed
Enabling urngd
Enabling uwsgi
./etc/init.d/wsdd2: line 12: /lib/functions/network.sh: No such file or directory
Enabling wsdd2
Enabling zram
sed -i "s/Installed-Time: .*/Installed-Time: 1578404656/" /home/ansuel/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu/usr/lib/opkg/status
rm -rf /home/ansuel/openwrt/build_dir/target-a
```

**Comment by Andy2244** [comment]
Yet there should be a `/lib/functions/network.sh` otherwise the script wont work correctly?

So not sure why moving the include help's?

**Comment by Ansuel** [comment]
Nope! That's on installation stage...  When compiling a new image, the buildroot enables all the init.d (that use procd)  And in that stage we are not on the device but on the pc compiling the image.. 

Other package also include the network.sh in the start function to remove this error.

**Comment by Andy2244** [comment]
> That's on installation stage... When compiling a new image, the buildroot enables all the init.d (that use procd) And in that stage we are not on the device but on the pc compiling the image..

That's weird, isn't this what `$(STAGING_DIR_ROOT)` is for?

PS: I'm fine with the change, just confused on why this even happens?
Maybe also consider fixing `wifidogx.init, fwknopd.init` while you are at this.

**Comment by Ansuel** [comment]
Well on the init we call absolute path (/lib/)
We can't add the staging in the init since it will brake when executed on
the normal router.

Il Mar 7 Gen 2020, 20:27 Andy Walsh <notifications@github.com> ha scritto:

**Comment by Andy2244** [comment]
> Well on the init we call absolute path (/lib/) We can't add the staging in the init since it will brake when executed on the normal router.

Sure but can the install/check not do a chroot?
I mean whatever, its a minor change, so just go ahead merge it.

**Comment by Ansuel** [comment]
Will fix the other should I make another pr?

Il Mar 7 Gen 2020, 20:36 Andy Walsh <notifications@github.com> ha scritto:

**Comment by Andy2244** [comment]
> Will fix the other should I make another pr?

I guess so and fill in the maintainer @ line, otherwise they wont get a ping.

**Pull request merged**
