### PR TITLE
wifischeduler: turns WiFi on and off according to a schedule

### PR DESCRIPTION
**Pull request by newkit**
Maintainer: @newkit
Compile tested: ar71x,tplink wdr3600, openwrt OpenWrt Designated Driver r49395 
Run tested:ar71x,tplink wdr3600, openwrt OpenWrt Designated Driver r49395  

Description:
Turns WiFi on and off according to a schedule on an openwrt router
You can create user-defined events when to enable or disable WiFi.
See README.md for a detailed description.

Signed-off-by: Nils Koenig <<mailUNDERSCOREopenwrt@newkDOTit>

### CODE REVIEW

**Comment by diizzyy** [comment]
Shouldn't this go into Network category rather than utils?

**Comment by bobafetthotmail** [comment]
Thanks for summoning me.  :+1: 
Yes, it fits better in CATEGORY:=Network (and the source should go in /net folder), with SUBMENU:=wireless (so it joins other wifi-specific tools already there).

I also echo the "you need to unobfuscate the email".

**Comment by newkit** [comment]
@diizzyy and @bobafetthotmail 
I made the changes you requested

**Comment by bobafetthotmail** [comment]
For the signed-off-by you need to change the original commit (not just the github PR message), adding a new commit on top does not fix that.

you need to
git clone your repo or go in your local repository
git checkout <branch-name-of-this-patch> 
git --amend 

to fix last commit.

Then when it is correct in the local repo you **git push -f** to force the change upload to the github repo, and it will appear here too.

see here https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend/

**Comment by hnyman** [comment]
As you have the two commits in separate branch, it is really easy to squash them together with "git rebase" editing the new combined commit message at the same time, and then "git push -f" to Github to overwrite the original commits in this PR. 

Detailed advice can be found from https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by newkit** [comment]
Thanks for your comments, squashed all in one commit, sorry I didn't do that in the first place.

**Comment by hnyman** [comment]
I have still two questions about the "prpl license". I haven't ran into it earlier, I think.

Out of curiosity, why it? After a quick browse I did not find any other package here with that identified and it is not listed in the SPDX list, neither here nor upstream at SPDX.

And does the full license text really need to be both in Makefile and in a separate LICENSE file? You could just have PKG_LICENSE_FILES variable in Makefile that references to the actual LICENSE file. (It is also rather atypical to include the full license text in scripts that get copied into the final package to the router)

**Comment by newkit** [comment]
@hnyman 
The license comes from the Prpl Foundation https://prplfoundation.org/ 
And it's their requirement that this license is used.
Wheather this has to be in each and every file might be negotiable, but if the license does not end up on the router it self, whats the point? The enduser does not see/know under which license the code is. And maybe it's atypical with OpenWRT but I know a bunch of projects where every file is "licensed". Do you think thats a problem?

Do I have to add the prpl license to the SPDX list?

**Comment by thess** [comment]
@newkit - I believe the license you have quoted is actually the ISC license here:

https://spdx.org/licenses/ISC.html
https://opensource.org/licenses/ISC

**Comment by newkit** [comment]
@hnyman  
Thank you very much for merging.

@thess 
I think your right, looks like the same license. 

Would it make sense then, to set in the future
`PKG_LICENSE:=ISC`
and leave the LICENSE file in place?

Since this feature also has a GUI which is in a PR
https://github.com/openwrt/luci/pull/847
it would be awesome to see it merged, too ;-)

**Pull request merged**
