### PR TITLE
chore: Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by BKPepe** [comment]
- Test Formalities / Test Formalities (pull_request)  fails for you.
Would you mind to fix it?

**Comment by naveensrinivasan** [comment]
> * Test Formalities / Test Formalities (pull_request)  fails for you.
>   Would you mind to fix it?

Can I do that in a future PR? Thanks

**Comment by BKPepe** [comment]
No. ``Signed-off-by`` is required to all commits, which we have in OpenWrt repositories.

**Comment by BKPepe** [comment]
Kind reminder, or else I will close this pull request within a few days.

**Comment by naveensrinivasan** [comment]
> Kind reminder, or else I will close this pull request within a few days.

I don't have time now. Apologies for not getting back sooner.

**Comment by BKPepe** [comment]
And you have time for response, that's interesting because both things take the same amount of time.
```
git commit --amend -s
git push -f
```

Closing. If you will have time in the future, which I doubt (TBH), then re-open this pull request or create a new one.

**Pull request closed without merging**
