### PR TITLE
tcpreplay: bump to version 4.5.1 + add test.sh script

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: x86  https://github.com/openwrt/openwrt/commit/d92c42f46990db232c163e20a05c7443d9efd2e1
Run tested:  x86  https://github.com/openwrt/openwrt/commit/d92c42f46990db232c163e20a05c7443d9efd2e1

### CODE REVIEW

**Comment by commodo** [comment]
oh... so it looks like ARM builds don't implement some ethtool commands:
```
Fatal Error: Error: eth0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented
Problem or incorrect version for 'tcpreplay'
```

**Comment by BKPepe** [comment]
Yeah, it is the same error which @pprindeville spotted in this PR https://github.com/openwrt/packages/pull/29799

The issue still persists, though.
```bash
tcpreplay: Use generic tests
WARNING: opening /ci/packages.adb: UNTRUSTED signature
tcpreplay: [pass] File /usr/bin/tcpreplay is executable
tcpreplay: [warn] Version check (/usr/bin/tcpreplay)
tcpreplay: First 10 lines of the last output:
  
  Fatal Error: Error: eth0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Not a tty
tcpreplay: [pass] Binary /usr/bin/tcpreplay does not contain any hardcoded build paths
tcpreplay: [pass] Binary /usr/bin/tcpreplay is stripped
tcpreplay: [pass] All linked libraries for /usr/bin/tcpreplay are present
tcpreplay: [skip] Version check override
tcpreplay: No executables in the package provided version 4.5.2
tcpreplay: Generic tests failed
```

```bash
tcpreplay-all: Generic tests passed
tcpreplay-all: Use the package-specific test.sh
tcpbridge version: 4.5.2 (build git:v4.5.2)
Copyright 2013-2025 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Compiled against libdnet: 1.16.1
Compiled against libpcap: 1.10.6
64 bit packet counters: enabled
Verbose printing via tcpdump: disabled
Injection method: PF_PACKET send()
tcpbridge version: 4.5.2 (build git:v4.5.2)
tcpliveplay version: 4.5.2 (build git:v4.5.2)
Copyright 2012 by Yazan Siam <tcpliveplay@gmail.com>
Compiled against libdnet: 1.16.1
Compiled against libpcap: 1.10.6
64 bit packet counters: enabled
Verbose printing via tcpdump: disabled
Injection method: PF_PACKET send()
tcpliveplay version: 4.5.2 (build git:v4.5.2)

Fatal Error: Error: eth0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Not a tty
Problem or incorrect version for 'tcpreplay'
tcpreplay-all: Test failed
WARNING: opening /ci/packages.adb: UNTRUSTED signature
```

**Comment by BKPepe** [comment]
Hehe, bot appeared to the merged PR from 2 yrs ago. Thats not exactly right, I would say. 😆

**Comment by commodo** [comment]
```
  Fatal Error: Error: eth0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Not a tty
tcpreplay: [pass] Binary /usr/bin/tcpreplay does not contain any hardcoded build paths
```

IIRC: this should be fixed somehow in the QEMU image of aarch64? 
@GeorgeSapkin  any hints?

**Pull request merged**
