### PR TITLE
dmapd: update to 0.0.83

### PR DESCRIPTION
**Pull request by flyn-org**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64 master bba6646b
Description:

### CODE REVIEW

**Comment by neheb** [comment]
license info should be updated.

PKG_BUILD_PARALLEL:=1 would be good.

**Comment by flyn-org** [comment]
Updated PKG_LICENSE and enabled parallel build.

**Comment by neheb** [comment]
This is the failure: https://5604-20307838-gh.circle-artifacts.com/0/home/build/build_dir/logs/package/feeds/packages/libdmapsharing/compile.txt

It looks like libdmapsharing needs 
```
PKG_BUILD_DEPENDS::=glib2/host
```

**Comment by neheb** [comment]
I openned https://github.com/openwrt/packages/pull/10239 for this.

BUILD_DEPENDS is not needed here.

**Comment by flyn-org** [comment]
Okay, I removed BUILD_DEPENDS again and force pushed.

**Comment by flyn-org** [comment]
Hmm ... CI test failed.

**Comment by neheb** [comment]
Needs https://github.com/openwrt/packages/pull/10239

**Comment by flyn-org** [comment]
Sorry, I thought I was checking on that job! I got mixed up.

**Comment by neheb** [comment]
Merged. Please rebase against current master.

**Comment by flyn-org** [comment]
Rebased. Looks good.

**Comment by flyn-org** [comment]
Thank you!

**Pull request merged**
