### PR TITLE
seafile: Depends on EOL and CVE-ridden Django 1.5, therefore remove

### PR DESCRIPTION
**Pull request by dfc-d**
Django 1.5 is EOL and has a number of CVE's.  PIL also has a major CVE.
seafile-seahub (without which there is not point to the other seafile packages)
depends on Django 1.5, and, through Djblets 0.6 (old djblets is required because
of old Django) depends on PIL.

Therefore until seafile gets updated to newer Django, remove seafile from packages feed.

We also remove deprecated libevhtp-1.1 for which seafile is the only consumer, as
well as libsearpc which is seafile-specific library.

Signed-off-by: Daniel Dickinson <openwrt@daniel.thecshore.com>

### CODE REVIEW

**Comment by dfc-d** [comment]
Also note that seafile upstream doesn't seem to have a lot of activity so an update is not likely coming soon.

**Comment by champtar** [comment]
Hi @dfc-d,
I'm in favor of getting rid of unsafe and unmaintained software,
but some people can "need" it, so can you open a PR on https://github.com/openwrt/packages-abandoned

**Comment by dfc-d** [comment]
Ok, matching PR on abandoned created.

**Comment by dfc-d** [comment]
It was really kind of a squirrelly package to begin with (esp. the whole business of not doing proper packages for it's dependencies and doing a whole set of downloads / easy_installs as part of the build of seahub. It also was never properly cross-compiling (seafile-server for instance actually has native code that was getting compiled for host arch).

**Comment by dfc-d** [comment]
Anyone going to remove a package that never properly cross-compiled in the first place, has a rather questionable download/build of dependencies, and those dependencies have known CVE's against them (e.g. Django, PIL through djblets).

**Comment by kissg1988** [comment]
@dfc-d As the maintainer of seafile packages, I'm really grateful for your comments while I feel pretty disappointed about seeing several days (weeks?) of my hard work thrown away without noticing me or simply asking about my plans to upgrade the packages to the latest upstream version. I know I've been inactive for quite some time but I have my reasons. Sorry about it.

I'd like to have a few comments, please:

* The latest version of Seafile server (5.1.1) has been [released](https://github.com/haiwen/ccnet/releases/tag/v5.1.1-server) 21 days ago and the 5.x branch is still under active development. While the 4.x branch is not very active these days, the project itself is not dead. I don't see any reason to drop these packages as many people might need them and would be glad to see them upgraded one day... :)
* The 5.x branch uses django 1.8 LTS which is supported until April 2018 (at least)
* PIL and djblets is not required for the 5.x branch of Seafile
* Not sure what native code you mean but I'll take extra care about that while packaging the latest version
* I've never been a "hardcore packager" nor a professional software developer and packaging seafile (and its dependencies) was my first contribution to the openwrt project. Sorry if my work looked squirrely, I'll do my best to create more professional package definitions in the future.
* The reason I used easy_install to fetch python dependencies was to meet version requirements without affecting packages globally installed. While this is not very elegant, I didn't want to use the latest versions of the dependencies and see how well they perform. I hate bugs and unexpected behaviour more than anyone else. :)
* libevhtp 1.1 is a requirement for Seafile. While the latest version works, too, it used to have [compatibility issues](https://github.com/openwrt/packages/pull/1368) with the 4.1 branch of seafile. I'm going to make some tests to see how the 5.x branch performs with the latest version of libevhtp.

A few months ago I tried upgrading the packages to the latest version but I got stuck as quite a few things have changed between the 4.x and the 5.x branch. My plan is to create brand new package definitions for the 5.x branch in case there is interest to accommodate my work. Is there?

**Comment by dfc-d** [comment]
I'm top-posting because there is not need for inline for this one.

I'm just a user, so don't think my comments come from the devs.  I was
alarmed by the state of the seafile package because of the CVE on django
as well as discovering not-cross-compiled code.

If you're willing to make the effort to fix it up, I'll help as I can.
I had just seen this as a drive-by that was in a bad state.

Regards,

Daniel

**Comment by hnyman** [comment]
Well, seafile packages are broken at moment for all(?) platforms, so either the package should be fixed or it should be removed.

Example
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/
At least the ccnet component fails to build at at moment, breaking the whole package family:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/seafile-ccnet/compile.txt

**Comment by kissg1988** [comment]
I believe it's ok to remove the packages from the repo until the latest version gets packaged. I wouldn't bother fixing the old version as it's pretty outdated and has several issues hard or impossible to fix (like depending on an EOL version of django).

I've already started creating packages for the 5.1 branch and its dependencies, will create PRs as soon as I have a working version available.

**Comment by dfc-d** [comment]
I suggest you package the versions of the libraries you need, rather
than latest version of the libraries.  As long as no other package isn't
using them this isn't an issue because there is no benefit to randomly
updating python libraries just because it's not the latest version.

TBH packaging python-dependant packages is a major headache for distos
because Python's solution to the version dependency problem is
virtualenv, but that's not usually suitable for distributions.  If you
could rely on major versions being backwards-compatible it'd be okay,
but unfortunately the python community doesn't seem to think it's
important to worry about that sort of thing.

It seems that too many developers view distributions as a pain they
don't want to deal with, rather than providing the impetus to have LTS
versions and having period stable releases (the continuous delivery
concept sounds great but IMO is far too prone to being Continuous
Brokeness because Continuous Integration, like all 'we'll test out all
bugs' theories it misses the reality that no test suite is perfect, and
sooner or later bad things will happen in an actual deployment.  At
least with a proper QA cycle (i.e. both automated and non-automated
testing) and better something deployed that's only gotten bug fixes for
quite some time, you have a better chance of avoiding unpleasantness.

But the industy is all all about first-to-market and my view is unpopular.

Regards,

Daniel

**Comment by kissg1988** [comment]
@dfc-d Thanks for your kind and honest comments.

I've finished packaging seafile server 5.1.1 for the 15.05 branch, it's working like a charm now. Turned out it has no strict version requirement on its python dependencies, all deps have been packaged properly and are the latest versions available (except django which is at the 1.8 branch but being an LTS release, it's still fine). There was a serious bug in the code causing the seaf-server binary segfaulting on some platforms which has been [fixed](https://github.com/haiwen/seafile/pull/1609), too.

I'm about to make some tests against the development branch, will create PRs for my changes soon.

**Comment by dfc-d** [comment]
That's awesome!  I was actually disappointed when I looked on their site
a while back when I originally was interested in seafile and thought
they were dead because I didn't see any recent activity although
apparently I must just have missed it, unless it's a case of coming back
to life after a hiatus (Before I did the removal PR I actually had done
some fixups for the old version, and had packaged the dependencies,
until I found out the state things were in and the the version Django
was EOL and had CVEs from someone else).

Regards,

Daniel

**Pull request closed without merging**
