### PR TITLE
Improvements for Travis (use different target and update Ubuntu image)

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainers: @champtar , @lynxis , @yousong 

Description:
Target ar71xx is deprecated and removed in the master branch and makes SDK
not available anymore. Travis fails because of that.
It was superseded by target ath79. These devices have 4 MB flash and/or 32 MB RAM.

Build log: https://travis-ci.org/github/BKPepe/packages/builds/699273897?utm_medium=notification&utm_source=email

However, ath79 is being used by CircleCI if you have it configured for
your repository and if you are contributing to this repository. It
is not good to have two CI for the same target. Let's use mvebu.

Tested with youtube-dl package: https://travis-ci.org/github/BKPepe/packages/builds/699295449

### CODE REVIEW

**Comment by champtar** [comment]
As Travis is not used anymore, you might be one of the only users -> LGTM

**Comment by neheb** [comment]
One thing that keeps happening is packages get merged and break under interesting platforms. Namely the ARMv5 stuff, powerpc, and 64-bit ARM.

**Comment by BKPepe** [comment]
I can use powerpc or 64-bit ARM CPU for my use case as well. I will change that.

**Comment by BKPepe** [comment]
V1 → V2:
As suggested by, I changed mvebu to powerpc.
Build is currently running with youtube-dl. Hopefully, this time it won't be killed as previous build. 
https://travis-ci.org/github/BKPepe/packages/builds/699658979

If it fails, I will try to use different package and look at it further.

**Comment by neheb** [comment]
Surprising that it fails on OpenSSL.

**Comment by BKPepe** [comment]
V2 → V3:
- Use the latest Ubuntu version 
- Build config validation: fix 1 warning and 1 info message
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing os, using the default linux
```

> Surprising that it fails on OpenSSL.

Need to investigate it, why it fails on Travis. In the meantime, I tested it with different package e.g. python-more-itertools and the build passed. So, it is still improvement than having it broken at all.

cortex-a9-vpfv3-d16: https://travis-ci.org/github/BKPepe/packages/jobs/700176238#L2585
powerpc: https://travis-ci.org/github/BKPepe/packages/jobs/700186076#L2634

**Comment by BKPepe** [comment]
> Surprising that it fails on OpenSSL.

Interesting. I tried it with v3, where I updated Ubuntu and youtube-dl is now compiled.
Proof: https://travis-ci.org/github/BKPepe/packages/builds/700215464#L2656

Who knows, why it failed on older version of Ubuntu, but I think we care that it is working now, right?

**Comment by neheb** [comment]
¯\_(ツ)_/¯

You seem to be the only one using Travis.

**Comment by BKPepe** [comment]
The same happens for OpenWrt 19.07 branch.
Log: https://travis-ci.org/github/BKPepe/packages/builds/703961514

I will cherry-pick it within 2-3 hours to see if there are some objections.

**Pull request merged**
