### PR TITLE
Add System-NS.com as service for ddns

### PR DESCRIPTION
**Pull request by Tikhevich**
Add System-NS.com as service for ddns

### CODE REVIEW

**Comment by sbyx** [comment]
Please read and follow our guidelines: 
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
especially paragraph 3.

**Comment by Tikhevich** [comment]
Updated commit comment.

**Comment by sbyx** [comment]
thanks. @commodo okay with you?

**Comment by commodo** [comment]
I think there's a confusion here ?
I don't maintain anything related to DNS (or DDNS).

If related to `python-dns`, we should include @Shulyaka  ( Denis Shulyaka <Shulyaka@gmail.com> )

**Comment by Shulyaka** [comment]
I think it relates to ddns-scripts ( @chris5560 ). It has nothing to do with python or python-dns.

**Comment by sbyx** [comment]
Yeah sorry confusion on my side was intended to @chris5560

**Comment by chris5560** [comment]
@Tikhevich 
did System-NS also support IPv6 ? If yes please also update service_ipv6 file and please increase the PKG_RELEASE in Makefile so the change is recognised by the system as update.
Thanks Christian

**Comment by champtar** [comment]
ping @Tikhevich

**Comment by Tikhevich** [comment]
Yes, we support IPv6. I will update that file (service_ipv6 file) @chris5560 @champtar

**Comment by champtar** [comment]
hi @Tikhevich,
still waiting for your update

**Comment by champtar** [comment]
hi @Tikhevich,
This doesn't apply anymore, so i'm closing this PR.
Don't hesitate to reopen it / open a new one with all needed updates

**Pull request closed without merging**
