### PR TITLE
mdnsresponder: update to 2200.100.94.0.2

### PR DESCRIPTION
**Pull request by neheb**
The IETF fork is unmaintained. In addition, the versioning is incompatible with apk.

Maintainer: 

ping @flyn-org @stintel

### CODE REVIEW

**Comment by flyn-org** [comment]
Where did the new patches come from? Did you write them, or did they come from another source? Have the been proposed upstream?

**Comment by neheb** [comment]
They come from before your update to IETF104.

**Comment by flyn-org** [comment]
Oh, I get it. I think this will be fine once the checks pass. Do you need to refresh the patches?

**Comment by neheb** [comment]
Yeah one of them. I'll do that soon.

**Comment by neheb** [comment]
@flyn-org Updated to latest version instead. Also, in https://github.com/openwrt/packages/commit/68b093d00b1584e6820c33f21f1e9ff4ab234e42 , you removed all patches. I added back two of them.

**Comment by flyn-org** [comment]
Looks good. Recommend merge.

**Comment by neheb** [comment]
I'm looking at OpenEmbedded right now. They have a bunch of patches for mDNSResponder, some of which overlap with 100-linux_fixes.patch. Might make more sense to port them here.

**Pull request merged**
