### PR TITLE
httping: import from oldpackages and upgrade to version 2.5

### PR DESCRIPTION
**Pull request by marcin1j**
Maintainer: me
Compile tested: ar71xx, mipsel_24kc
Run tested: NetGear WNDR3700v2 (ar71xx), Nexx WT-3020 (mipsel_24kc)
Description:
Package version upgraded to 2.5 with patches:
- Fixed compiler warnings
- Fixed miscalculated response time
- Reduced binary size by stripping unused code

### CODE REVIEW

**Comment by diizzyy** [comment]
In what scenario is this needed on a router?

**Comment by zorun** [comment]
- why are you removing the `strip` command?
- where does the `003-fix_response_time.patch` patch come from?  Is it submitted upstream?  Is it specific to OpenWRT/LEDE?

Otherwise looks good to me!

**Comment by marcin1j** [comment]
@zorun 
The patch `001-no_strip.patch` comes from an old package feed. To me it seems unnecessary.
As for `003-fix_response_time.patch`, it's not been submitted upstream. It's necessary only for MUSL, which ignores tz parameter of `gettimeofday`.  Nevertheless `timezone` structure  is obsolete and should not be used.

@diizzyy 
This package is needed to track connectivity on traffic-restricted network. I use it with mwan3.

**Comment by hnyman** [comment]
> The patch 001-no_strip.patch comes from an old package feed. To me it seems unnecessary.

To me the patch looks quite sensible. It patches the upstream Makefile by removing the package-specific stripping from that, as it is unnecessary: stripping is built-in into the Openwrt/LEDE make system and is performed later in the build process (unstripped file available for gdb debugging, stripped one installed and included in .ipk).

**Comment by feckert** [comment]
@marcin1j if we want to merge the mwan3 PR #4629. This PR should be merged first with the outstanding changes.

**Pull request merged**
