### PR TITLE
wget: fix nossl variant in 1.17

### PR DESCRIPTION
**Pull request by hnyman**
wget-nossl variant for wget 1.17 is broken in upstream.

Copy a patch from upstream mailing list to fix compilation.
http://lists.gnu.org/archive/html/bug-wget/2015-11/msg00074.html

I also filed a bug upstream before nonticing that post in upstream mailing list:
https://savannah.gnu.org/bugs/index.php?46537

I have compiled and tested both full wget and wget-nossl for ar71xx/WNDR3700.

wget version was bumped to 1.17 by #2001 

Cc to maintainer: @mstorchak

### CODE REVIEW

**Comment by mstorchak** [comment]
Ack.
Thank you @hnyman

**Comment by hnyman** [comment]
@mstorchak 
Ok with you, if I push the upstream fix for re-enabling compilation without ipv6?

That configuration choice is not offered in the Openwrt wget menuconfig, but likely some people will try also that. The upstream commit fixes things for them: http://git.savannah.gnu.org/cgit/wget.git/commit/?id=2cfcadf5e6d5c444765aa460915ae27109a8dbce
( this is fallout from the same upstream commit that broke the nossl in general :-(

I tested both ssl and nossl variants. Disabling ipv6 broke compilation, and the upstream commit fixed it.

Will be interesting to see if there will be a wget 1.17.1 release rather soon.

**Comment by mstorchak** [comment]
Sure, go ahead.

**Comment by hnyman** [comment]
I pushed a fix for the --disable-ipv6 issue

**Comment by hnyman** [comment]
Just documenting here that the upstream patch that I used for 100-fix-nossl-117-from-upstream.patch
 has been today committed upstream:
http://git.savannah.gnu.org/cgit/wget.git/commit/?id=ad5a28352883f661f390ff320fb2130cc6a6d443

So, after the next version bump to either 1.17.1 or 1.18, both patches (no-SSL and no-ipv6)  will be unnecessary.

**Comment by mstorchak** [comment]
@hnyman , got it, thank you!

**Pull request merged**
