### PR TITLE
libs/libmicrohttpd update to 1.0.1

### PR DESCRIPTION
**Pull request by jen1-sys**
libs/libmicrohttpd update to 1.0.1

### CODE REVIEW

**Comment by Neustradamus** [comment]
@Karlson2k: Have you seen this PR?
What do you think?

**Comment by Karlson2k** [comment]
I'm not subsribed to this repo, so I haven't seen this PR.
The version bump is OK. The new version has been widely deployed and well-tested.

However, I see some problmes with OpenWRT package. I'll make a separate PR.

**Comment by Neustradamus** [comment]
@Karlson2k: Thanks for your comment and your PR :)
- https://github.com/openwrt/packages/pull/25208

**Comment by neheb** [comment]
Merged.

**Comment by Neustradamus** [comment]
Thanks to @jen1-sys for this PR and @neheb for merging!

Merged commit:
- https://github.com/openwrt/packages/commit/7a8ec328b1c9630ee2a461dd569c9b5edea15fa3

**Pull request closed without merging**
