### PR TITLE
travelmate: create login script for Bayern WLAN

### PR DESCRIPTION
**Pull request by 0x6368**
Added login script for the bayern wlan. This is very similar to the vodafone hotspot, however, it does not require credentials and logs in with the profile id _6_

Maintainer: me / @dibdot
Compile tested: gl.inet GL-MT300N-V2, OpenWrt 22.03.5
Run tested: gl.inet GL-MT300N-V2, OpenWrt 22.03.5

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
please, prefix commit message with `travelmate: [...]`

**Comment by dibdot** [comment]
@0x6368 
Please rework this PR:
- change the PR/Commit title as already mentioned
- change the header/description in your login script
- bump the 'PKG_RELEASE' in the package makefile

Thanks!

**Comment by 0x6368** [comment]
@dibdot Done!

**Comment by dibdot** [comment]
@0x6368 Sorry, still not there ... a few nitpicks:

- as already mentioned, please raise the `PKG_RELEASE` (and not the `PKG_VERSION!)`
- Please remove my copyright line in the login script and replace it with your credentials

**Comment by BKPepe** [comment]
@0x6368 kind reminder to look into it

**Comment by 0x6368** [comment]
@dibdot Done

**Comment by dibdot** [comment]
@0x6368 changes looks OK now - thanks! Finally please tidy up /squash your commits in your feature branch.

**Comment by dibdot** [comment]
no more feedback - close this incomplete PR.

**Pull request closed without merging**
