### PR TITLE
python3: split python3-urllib from python3-light

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/b7f2adbdd3ed76e9c844b99d0171c9bfe5809cba  x86
Run tested: https://github.com/openwrt/openwrt/commit/b7f2adbdd3ed76e9c844b99d0171c9bfe5809cba  x86

------------------------------------------------------

This is the result of this discussion:
  https://github.com/openwrt/packages/issues/8285

`urllib.request` requires the `email` module/lib, which was part of
python3-light.
This change moves the Lib/urllib folder from the python3-light into it's
own package, making it lighter. At least this way, users that want `urllib`
(on top of `python3-light`) will be forced to install it via opkg and this
will make sure `python3-email` gets installed as well.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
Fixes #8285 

@leonardpitzu

**Comment by diizzyy** [comment]
Awesome, thanks

**Comment by leonardpitzu** [comment]
@commodo seems to be working so you can close the issue. thanks for making this happen!

**Comment by commodo** [comment]
This should close automatically once this is merged.

**Pull request merged**
