### PR TITLE
sane-backends: import from oldpackages

### PR DESCRIPTION
**Pull request by luizluca**
Changes since oldpackages:
- cups dependency was completely removed
  * This also happened in sane trunk version
- small musl patch
- fix for segfault when using sane-test backend
- removed link to extra libraries in libsane (used for preload backends)
- sane-libs and sane-backends merged and exploded into
  individual packages for each backend:
  * libsane for sane library (which backends should dep on)
  * sane-daemon for saned daemon
  * sane-xxx for sane backend for xxx
  ** each backend has its own custom dep libraries
  * sane-backends-all (with no files) that deps on all backends

Now it is possible to use SANE with much less FS space (KB instead of MB).

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

I tested it with x86 using test backend without problem.

### CODE REVIEW

**Comment by luizluca** [comment]
Guys, any objections?

**Comment by plntyk** [comment]
There is a compile issue with format security

fedora has adopeted a fix from upstream:
http://pkgs.fedoraproject.org/cgit/sane-backends.git/tree/
	sane-backends-1.0.24-format-security.patch

**Comment by plntyk** [comment]
Build error on a full build (target omap):
    checking for _portaccess... no
    ....
    *** qcam backend requires ioperm and portaccess functions - disabling

cannot stat '.../build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.11_eabi/sane-backends-1.0.24/ipkg-install/usr/lib/sane/libsane-qcam.so.*

**Comment by luizluca** [comment]
I'm on it. Thanks @plntyk

**Comment by luizluca** [comment]
@plntyk ,

I already fixed the problems you listed. However, I faced

**Comment by luizluca** [comment]
@plntyk, I've added the patch you mentioned.

Also, I modified qcam package to depend on TARGET_x86||TARGET_x86_64. It would never work with archs that does not provide inb/outb (musl provides them only for i386/x32/x86_64).

I don't have an omap to runtime test it but, at least, it compiles fine now.

**Pull request merged**
