### PR TITLE
utils/f2fs-tools: Remove from tree

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @lperkov 
Compile tested: N/A
Run tested: N/A

Description:
Already in LEDE tree so this is redundant.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@hnyman

**Comment by diizzyy** [comment]
@hauke 
Ping?

**Comment by KanjiMonster** [comment]
But it isn't in OpenWrt's base packages, so wouldn't this break OpenWrt? Is there an appropriate PR that adds it to OpenWrt?

**Comment by diizzyy** [comment]
@KanjiMonster 
Can't find it anywhere referenced in the OpenWrt tree (f2fs-tools) but perhaps I'm bad at using grep.

**Comment by stintel** [comment]
Going to accept this PR, as there isn't a single target in OpenWrt that uses f2fs. Next to that, since we agreed to use the LEDE codebase when merging LEDE and OpenWrt, in combination with all the security vulnerabilities found in the last few years, the only sensible thing to do if you still run OpenWrt is to move to LEDE. For those reasons we should treat the OpenWrt git tree as obsolete, and not bother too much keeping things here "compatible" with it.

**Comment by stintel** [comment]
Oops, wrong button.

**Pull request merged**
