### PR TITLE
minidlna: Update to latest upstream (2016-09-29)

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @medaved 
Compile tested: Kirkwood, iomega iConnect, LEDE trunk
Run tested: Kirkwood, iomega iConnect, LEDE trunk

Description:
Updated to latest commit upstream as the latest tagged version didn't get
a tarball release at all. Includes various fixes and also support for
never versions of ffmpeg.

Also added a sorting patch for Panasonic TVs.
Source: https://github.com/yanbe/minidlna/commit/c8245740c3a8699cfe7d7e5aa0d427b931018ad5

Various improvements to package Makefile.
Source/Template: https://github.com/wongsyrone/packages-1/blob/c389dcdc020e1d199570f01f36b781a290aa5356/multimedia/minidlna/Makefile

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@antonlacon @thess 
Please review and give input, I probably did something stupid ;-)

**Comment by diizzyy** [comment]
@antonlacon 
Can you please have a look at this?

**Comment by kdarbyshirebryant** [comment]
Runs on ar71xx Archer C7 v2

**Comment by diizzyy** [comment]
Also on kirkwood, iOmega iConnect

**Comment by diizzyy** [comment]
@hnyman 
Ok to Merge?

**Pull request merged**
