### PR TITLE
[openwrt-22.03] golang: Update to 1.18.1

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me
Compile tested: none (cherry picked from #18147 and #18305)
Run tested: none

Description:
This cherry-picks the 3 commits from master to update Go in the 22.03 branch to 1.18.1.

### CODE REVIEW

**Comment by jamesmacwhite** [comment]
@jefferyto Can we hold merging until we get the following packages updated in 22.03 first because they've all had Go 1.18 compatibility updates recently to master and need backporting

* AdGuard Home
* ~~ooniprobe~~ (merged in 22.03)
* syncthing

**Comment by jefferyto** [comment]
I don't see a strong reason to wait since 22.03 isn't out yet (and probably won't be soon) and fixes for those packages will be merged soon, but I'll let others decide when to merge this PR.

Btw I'm not the maintainer of those other packages, I just decided to help out this time because 1.18 broke their builds.

**Comment by jamesmacwhite** [comment]
@jefferyto No worries, it was more just getting ahead of causing package failogs for anyone building images using 22.03. I think there were about 5 Go packages that were broken, therefore it was just flagging them in a single place to prevent the same issue happening again.

**Comment by jefferyto** [comment]
@jamesmacwhite Thanks for helping out with these Go packages :smile:

**Comment by jamesmacwhite** [comment]
@jefferyto No worries, I think all the version bumps have been merged in 22.03 so it should be OK, I'll check the 22.03 faillogs in 24 hours to see if anything Go 1.18 crops up.

**Pull request merged**
