### PR TITLE
[openwrt-19.07] golang: Update to 1.12.6

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me
Compile tested: none (#9248 was compile tested)
Run tested: none

Description:
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
#9250 should fix the build error.

**Comment by hnyman** [comment]
#9250 has been merged. 
Can you rebase this PR to pick up that change and to enable a re-run of the CircleCI test.

**Comment by jefferyto** [comment]
@hnyman Done :joy:

**Comment by hnyman** [comment]
Well, it worked ok.
Nice to know that circleci is now usable also with 19.07

**Pull request merged**
