### PR TITLE
mii-tool: fix variable being declared too early

### LINKED ISSUE #3249: mii-tool - bad compile (if not possible - bad path to dir/files) -  @Borromini
@Borromini
make -j8 BUILD_LOG=1

cat [sources]/logs/package/feeds/packages/mii-tool/compile.txt:
```
bash: ./configure.sh: No such file or directory
Makefile:53: recipe for target '/home/sj/Pulpit/Projekty/WNDR4700-LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/mii-tool-2016-07-10-115f1af2494ded1fcd21c8419d5e289bc4df380f/.configured_yyyyyyy' failed
make[3]: *** [/home/sj/Pulpit/Projekty/WNDR4700-LEDE/build_dir/target-powerpc_464fp_musl-1.1.15/mii-tool-2016-07-10-115f1af2494ded1fcd21c8419d5e289bc4df380f/.configured_yyyyyyy] Error 127
```
in short - the source is extracted to the directory [sources]/build_dir/target-xxx/mii-tool-2016-07-10-  : testing, commissioning (and run compile) of files in the source program is done in the [sources]/build_dir/target-xxx/mii-tool-2016-07- 10-115f1af2494ded1fcd21c8419d5e289bc.
It seems obvious syntax error in the file https://github.com/openwrt/packages/blob/master/net/mii-tool/Makefile.

### PR DESCRIPTION
**Pull request by Borromini**
PKG_SOURCE_SUBDIR was being declared too early which broke the build. Fixes #3249

Signed-off-by: Stijn Segers <francesco.borromini@inventati.org>

### CODE REVIEW

**Comment by hnyman** [comment]
mii-tool is still failing at both LEDE and Openwrt buildbot.
e.g.
http://buildbot.openwrt.org:8010/broken_packages/oxnas/mii-tool/compile.txt
https://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/mii-tool/compile.txt

My hunch is that the reason is using variables before they are declared. Specifically, the Makefile uses $(PKG_SOURCE_VERSION) before that has been declared.

You might test using normal := for all variable assignations, but making sure that the variables are defined before the first usage.
``` PKG_SOURCE_VERSION:=115f1af2494ded1fcd21c8419d5e289bc4df380f ``` should likely be before ``` 
PKG_VERSION=2016-07-10-$(PKG_SOURCE_VERSION) ``` in the Makefile.

**Comment by Borromini** [comment]
@hnyman it works fine here and I had @diizzyy test it too. Maybe stale download cache?

**Comment by hnyman** [comment]
>  Maybe stale download cache?

Like I said, both Openwrt and LEDE buildbots fail to build it. It is officially broken then...

**Comment by mhei** [comment]
Bah... the source archive (http://sources.lede-project.org/mii-tool-2016-07-10-115f1af2494ded1fcd21c8419d5e289bc4df380f.tar.gz) contains the wrong directory, so after unpacking the sources are not where expected...

**Comment by hnyman** [comment]
Thanks, now it seems to get built (at least on LEDE, where the package has already been compiled for the first platforms. Openwrt buildbot will take longer.)  

Borromini's guess about a stale download cache was correct after all.

**Comment by Borromini** [comment]
Thanks @hnyman. The variables being declared with = instead of =: apparently should make sure that it works, even if they're in the wrong order.

@mhei thanks for spotting the redundant config stuff and adding the license.

**Pull request merged**
