### PR TITLE
owipcalc/maccalc: import from base

### PR DESCRIPTION
**Pull request by adschm**
These two tools look like they belong here.

jow has already approved the move of owipcalc, and maccalc does not have a maintainer at all.

Since I posted the patches for removal only today (Friday), I'd at least wait one day until Saturday for the unlikely case somebody vetos.

### CODE REVIEW

**Comment by adschm** [comment]
Don't know whether net or utils is appropriate here, in base they are in network/utils ...

**Comment by adschm** [comment]
Patches for base removal:

https://patchwork.ozlabs.org/project/openwrt/list/?series=225845

**Comment by neheb** [comment]
net

**Review by neheb — APPROVED** [review]

**Comment by adschm** [comment]
@neheb Thanks, please merge now.

**Pull request merged**
