### PR TITLE
python-ldap: added python-ldap package

### PR DESCRIPTION
**Pull request by the-alien**

### CODE REVIEW

**Comment by mhei** [comment]
The following should be changed before merging:
- squash the two into only one commit
- please use PKG_MAINTAINER instead of the MAINTAINER field in the package declaration
- remove PKG_CAT
- provide license information

**Comment by the-alien** [comment]
OK, done

**Comment by thess** [comment]
PKG_MAINTAINER variable should be outside the macro definition (top-level with other PKG_xxx vars) Also, please sign off your commit.

**Comment by the-alien** [comment]
Oh, I should have known.
The example in OpenWRT wiki seems to be a little bit outdated.
Anyway, now I've tried to put this in conformance with other guys' contributions.

**Comment by sbyx** [comment]
thanks.

**Pull request merged**
