### PR TITLE
prometheus: bump to 2.15.2

### PR DESCRIPTION
**Pull request by aparcar**
Maintainer: me
Compile tested: x86_64, mipsel64le
Run tested: x86/64

Description:

Bump to 2.15.2

Also remove fsnotify patch as compiling without it worked for mipsel64le

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by neheb** [comment]
Seems this has a problem: https://downloads.openwrt.org/snapshots/faillogs/mipsel_mips32/packages/prometheus/compile.txt

codeload hash changed once again.

**Comment by aparcar** [comment]
Attached is the old tarball
[prometheus-2.15.2.tar.gz](https://github.com/openwrt/packages/files/4182815/prometheus-2.15.2.tar.gz)

**Comment by aparcar** [comment]
Actually I can't reproduce the compile error you posted @neheb 
I still receive a tarball from codeload with the checksum I posted, and it seem to be the one stored on source.openwrt.org as well

**Comment by neheb** [comment]
Hrm same locally:

```
42cc464ffcede82d077be10e0b5cf6eff6bf62ed2b85cc5cb4ae9be73b7ed245  v2.15.2
42cc464ffcede82d077be10e0b5cf6eff6bf62ed2b85cc5cb4ae9be73b7ed245  Downloads/prometheus-2.15.2.tar.gz
```

Maybe some curl issue.

**Pull request merged**
