### PR TITLE
mc: update to 4.8.26

### PR DESCRIPTION
**Pull request by neheb**
Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dibdot

### CODE REVIEW

**Comment by neheb** [comment]
Works on glibc but fails on musl. Strange.

**Comment by dibdot** [comment]
This mc release looks quite shaky ... at least during my build tests I needed this upstream patch (https://github.com/MidnightCommander/mc/commit/25bc8a64d9d4ee1672d6319a26e5628d5cf1ac1a) for a successful compile. Even then this build freezes during runtime ... I stopped digging here.

**Comment by neheb** [comment]
That's unfortunate.

**Comment by dibdot** [comment]
I'll test your patchset later this week and come back to you. Thanks!

**Comment by dibdot** [comment]
@neheb Your utils/mc/patches/010-subshell.patch does not apply cleanly - please fix this.
Anyway, after manually applying your patchset it runs successfully on x86 target (apu2) ... so it's OK for me.

Thanks!

**Pull request merged**
