### PR TITLE
[22.03] mariadb: Update to version 10.6.15

### PR DESCRIPTION
**Pull request by miska**
Maintainer: me
Compile tested: mvebu, Turris Omnia, Turris OS 7.0 ~ OpenWrt 22.03
Run tested: mvebu, Turris Omnia, Turris OS 7.0 ~ OpenWrt 22.03, runs and can connect to it and do basic select statements

Description:

For list of changes, see:

* https://mariadb.com/kb/en/mariadb-10-6-15-release-notes/
* https://mariadb.com/kb/en/mariadb-10-6-14-release-notes/
* https://mariadb.com/kb/en/mariadb-10-6-13-release-notes/
* https://mariadb.com/kb/en/mariadb-10-6-12-release-notes/
* https://mariadb.com/kb/en/mariadb-10-6-11-release-notes/

### CODE REVIEW

**Comment by BKPepe** [comment]
I see CI is failing for you. Patches have some offsets and they need to be refreshed.

**Comment by miska** [comment]
Patches refreshed

**Comment by BKPepe** [comment]
Squash commits, please. Don't need to have two commits for one usual update.

**Comment by miska** [comment]
Here you go

**Comment by BKPepe** [comment]
Not relevant to your changes, but run testing fails:
```
/ci/utils/mariadb/test.sh: .: line 4: '': not found
```

Let's merge this anyway and fix it later.

**Pull request merged**
