### PR TITLE
emailrelay: added configuration options

### PR DESCRIPTION
**Pull request by fededim**
- moved from net to mail category
- removed no-ssl package and added ssl support as configuration option (default enabled)
- added configuration option to support extended logging (default disabled)
- disabled build of test tools
- added LEDE compatibility (support for openssl without SSL3)

Signed-off-by: Federico Di Marco <fededim@gmail.com>

### CODE REVIEW

**Comment by yousong** [comment]
Hi, Federico

Build variants are used to provide built binaries with different features selected at compile-time, usually for the purposes of saving spaces by trimming out some functions.  Dropping a variant has the effect of dropping support for a working package which may surprise existing users of `emailrelay-nossl`.  So you may want to think again about this.

Another thing is that you may want to add the newly introduced config symbols to `PKG_CONFIG_DEPENDS` so that the package will be rebuilt on config changes.

Package dnsmasq in base repo is a good example of the above points.

**Comment by fededim** [comment]
Well I do not see any problem on no-ssl package, if someone needs it he can compile it by himself, the only thing it changes is that openwrt build server will not generate it anymore. Let's see the size of the built packages (example ar7xxx arch)

emailrelay-nossl_1.9-2_ar71xx.ipk	296774	15-Sep-2016 02:21
emailrelay_1.9-2_ar71xx.ipk	300223	15-Sep-2016 02:20

They differ only of 4K so I do not see any problem in installing OpenSSL version than NoSSL either from disk space and needed RAM since probably the two executables and shared libraries differ by the same order of KB (we are nit-picking).
In 2016 I can not even think of a router installation without OpenSSL library, since it's used by a lot of common packages (webservers, vpn, wget) and IMHO nobody uses no ssl version to save disk space or to run it in its low end router (I would not trust to use a low end router as a mail server). It simply does not make sense, that's why I removed it. I had inserted it just to experiment with build variants, and because someone asked at the time I ported the package. Summing up for me the changes are fine.

**Comment by yousong** [comment]
> I had inserted it just to experiment with build variants, and because someone asked at the time I ported the package. Summing up for me the changes are fine.

Well, your package, your call.  But personally I'd like to wait a for while (1 week at least) before merging such changes as it may surprise existing users.

**Comment by fededim** [comment]
Ok, no problem.

**Comment by yousong** [comment]
In the meantime, please consider adding the newly introduced config symbols to `PKG_CONFIG_DEPENDS`, so that the build system will rebuild the code on config change.

**Comment by yousong** [comment]
I just tried building emailrelay with default config and it fails because it requires ssl3 support from openssl which is disabled by default.  So emailrelay now depends on at least config symbol `OPENSSL_WITH_SSL3`

The error message

```
g++-uc -DHAVE_CONFIG_H -I. -I../.. -I../../lib/gcc5.4 -I../../src/glib   -I/home/yousong/git-repo/lede/staging_dir/target-mips_24kc_musl-1.1.15/usr/include -I/home/yousong/git-repo/lede/staging_dir/target-mips_24kc_musl-1.1.15/include -I/home/yousong/git-repo/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/usr/include -I/home/yousong/git-repo/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/yousong/git-repo/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include   -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/yousong/git-repo/lede/build_dir/target-mips_24kc_musl-1.1.15/emailrelay-1.9:emailrelay-1.9 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -fno-rtti -MT gssl_openssl.o -MD -MP -MF .deps/gssl_openssl.Tpo -c -o gssl_openssl.o gssl_openssl.cpp
gssl_openssl.cpp: In constructor 'GSsl::Context::Context(const string&, unsigned int)':
gssl_openssl.cpp:296:40: error: 'SSLv3_method' was not declared in this scope
   m_ssl_ctx = SSL_CTX_new(SSLv3_method()) ;
                                        ^
make[6]: *** [gssl_openssl.o] Error 1
```

**Comment by fededim** [comment]
At the time of the changes (last week) everything compiled fine and I also checked that the correct configure options were passed. Nevertheless I'll check it again.

**Comment by fededim** [comment]
Tried again, everything is fine (tested without and with ssl3 support, see screenshot, the package size with ssl3 is far less probably due to removal of the debug support from email relay - it's default configuration). Can you give me your .config file ?

**WITHOUT SSL 3 SUPPORT**

compile@LupinIII-LINUX:~/openwrt$ ls
bin          build_dir    config     dl    emailrelay  feeds.conf.default   include    key-build.pub  Makefile  README    scripts      target  toolchain
BSDmakefile  compile.log  Config.in  docs  feeds       feeds.conf.default~  key-build  LICENSE        package   rules.mk  staging_dir  tmp     tools
compile@LupinIII-LINUX:~/openwrt$ git pull
remote: Counting objects: 451, done.
remote: Total 451 (delta 212), reused 212 (delta 212), pack-reused 239
Receiving objects: 100% (451/451), 61.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (318/318), completed with 42 local objects.
From git://github.com/openwrt/openwrt
   5ce38c4..b136759  master     -> origin/master
   cb4f071..d6b3ca2  chaos_calmer -> origin/chaos_calmer
Updating 5ce38c4..b136759
Fast-forward
 package/devel/perf/Makefile                                                                               |  1 +
 package/devel/perf/musl-compat.h                                                                          | 17 -----------------
 package/devel/strace/Makefile                                                                             |  6 +++---
 package/network/utils/xtables-addons/Makefile                                                             |  7 +++----
 package/network/utils/xtables-addons/patches/001-build-fix-configure-compatiblity-with-POSIX-shells.patch | 51 ---------------------------------------------------
 package/network/utils/xtables-addons/patches/002-fix-kernel-version-detection.patch                       | 12 ++++++------
 6 files changed, 13 insertions(+), 81 deletions(-)
 delete mode 100644 package/network/utils/xtables-addons/patches/001-build-fix-configure-compatiblity-with-POSIX-shells.patch
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ make package/emailrelay/clean
Collecting package info: done
 make[1] package/emailrelay/clean
 make[2] -C feeds/packages/mail/emailrelay clean
compile@LupinIII-LINUX:~/openwrt$ make package/emailrelay/compild
^Cmake[1]: *** wait: No child processes.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: *** wait: No child processes.  Stop.
make: *** [package/emailrelay/compild] Interrupt

compile@LupinIII-LINUX:~/openwrt$ make package/emailrelay/compile
 make[1] package/emailrelay/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C package/libs/ocf-crypto-headers compile
 make[2] -C package/libs/zlib compile
 make[2] -C package/libs/openssl compile
 make[2] -C package/libs/uclibc++ compile
 make[2] -C feeds/packages/mail/emailrelay compile
compile@LupinIII-LINUX:~/openwrt$ ls -la bin/ar71xx/packages/packages/
total 932
drwxr-xr-x  2 compile compile   4096 set 26 09:40 .
drwxr-xr-x 10 compile compile   4096 set 18 13:40 ..
-rw-r--r--  1 compile compile  42966 set 18 15:50 davfs2_1.5.4-2_ar71xx.ipk
-rw-r--r--  1 compile compile 329028 set 26 09:40 emailrelay_1.9-3_ar71xx.ipk
-rw-r--r--  1 compile compile 416158 set 18 15:57 lftp_4.7.3-1_ar71xx.ipk
-rw-r--r--  1 compile compile  46479 set 18 15:44 libexpat_2.1.0-3_ar71xx.ipk
-rw-r--r--  1 compile compile  56266 set 18 15:49 libneon_0.30.0-1_ar71xx.ipk
-rw-r--r--  1 compile compile    830 set 18 13:40 Packages
-rw-r--r--  1 compile compile    533 set 18 13:40 Packages.gz
-rw-r--r--  1 compile compile    151 set 18 13:40 Packages.sig
-rw-r--r--  1 compile compile  29255 set 18 15:53 sstp-client_1.0.10-2_ar71xx.ipk
compile@LupinIII-LINUX:~/openwrt$ 

**WITH SSL 3 SUPPORT**

compile@LupinIII-LINUX:~/openwrt$ make menuconfig
configuration written to .config		

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ make package/emailrelay/clean
 make[1] package/emailrelay/clean
 make[2] -C feeds/packages/mail/emailrelay clean
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ make package/emailrelay/compile
 make[1] package/emailrelay/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C package/libs/ocf-crypto-headers compile
 make[2] -C package/libs/zlib compile
 make[2] -C package/libs/openssl compile
 make[2] -C package/libs/uclibc++ compile
 make[2] -C feeds/packages/mail/emailrelay compile
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ 
compile@LupinIII-LINUX:~/openwrt$ ls -la bin/ar71xx/
Display all 391 possibilities? (y or n)
compile@LupinIII-LINUX:~/openwrt$ ls -la bin/ar71xx/packages/packages/
total 904
drwxr-xr-x  2 compile compile   4096 set 26 10:39 .
drwxr-xr-x 10 compile compile   4096 set 18 13:40 ..
-rw-r--r--  1 compile compile  42966 set 18 15:50 davfs2_1.5.4-2_ar71xx.ipk
-rw-r--r--  1 compile compile 300362 set 26 10:39 emailrelay_1.9-3_ar71xx.ipk
-rw-r--r--  1 compile compile 416158 set 18 15:57 lftp_4.7.3-1_ar71xx.ipk
-rw-r--r--  1 compile compile  46479 set 18 15:44 libexpat_2.1.0-3_ar71xx.ipk
-rw-r--r--  1 compile compile  56266 set 18 15:49 libneon_0.30.0-1_ar71xx.ipk
-rw-r--r--  1 compile compile    830 set 18 13:40 Packages
-rw-r--r--  1 compile compile    533 set 18 13:40 Packages.gz
-rw-r--r--  1 compile compile    151 set 18 13:40 Packages.sig
-rw-r--r--  1 compile compile  29255 set 18 15:53 sstp-client_1.0.10-2_ar71xx.ipk
compile@LupinIII-LINUX:~/openwrt$ 


screenshot 26

**Comment by yousong** [comment]
There is a minor flaw in the naming of stamp file for openssl configure stage.  I will take care of that later.

Setting that aside at the moment, ssl3 is required because 
ssl3 is required because `src/gssl/gssl_openssl.c` needs `SSLv3_method()` which will only be available if ssl3 is enabled.

My config is very simple
```
CONFIG_TARGET_malta=y
CONFIG_TARGET_malta_be=y
CONFIG_TARGET_malta_be_Default=y
CONFIG_TARGET_emailrelay=y
```

**Comment by yousong** [comment]
There is a minor flaw in the naming of stamp file for openssl configure stage.  I will take care of that later.  You can check the content of `staging_dir/target_xxx/usr/include/openssl/opensslconf.h` to see if `OPENSSL_NO_SSL3_METHOD` is present there.

Setting that aside at the moment, ssl3 is required because 
ssl3 is required because `src/gssl/gssl_openssl.c` needs `SSLv3_method()` which will only be available if ssl3 is enabled.

Below are the basic config

```
CONFIG_TARGET_malta=y
CONFIG_TARGET_malta_be=y
CONFIG_TARGET_malta_be_Default=y
CONFIG_TARGET_emailrelay=y
```

Steps to reproduce are also simple

```
# save the above config as .config
make defconfig
make package/openssl/clean
make package/emailrelay/compile V=s
```

**Comment by yousong** [comment]
While at it, please also consider disable building tests to save some computing resources and partly because it seems that the build can sometimes fail with

```
make[5]: Entering directory `/home/yousong/git-repo/lede/build_dir/target-mips_24kc_musl-1.1.15/emailrelay-1.9/test'
g++-uc -DHAVE_CONFIG_H -I. -I.. -I../lib/gcc5.4 -I../src/glib -I../src/gssl -I../src/gnet -DG_SPOOLDIR=\"/var/spool/emailrelay\"  -I/home/yousong/git-repo/lede/staging_dir/target-mips_24kc_musl-1.1.15/usr/include -I/home/yousong/git-repo/lede/staging_dir/target-mips_24kc_musl-1.1.15/include -I/home/yousong/git-repo/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/usr/include -I/home/yousong/git-repo/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify -I/home/yousong/git-repo/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include   -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /home/yousong/git-repo/lede/build_dir/target-mips_24kc_musl-1.1.15/emailrelay-1.9:emailrelay-1.9 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -fno-rtti -MT emailrelay_test_scanner.o -MD -MP -MF .deps/emailrelay_test_scanner.Tpo -c -o emailrelay_test_scanner.o emailrelay_test_scanner.cpp
mv -f .deps/emailrelay_test_scanner.Tpo .deps/emailrelay_test_scanner.Po
make[5]: *** No rule to make target `../src/gssl/libgssl.a', needed by `emailrelay-test-scanner'.  Stop.
```

**Comment by fededim** [comment]
The code which is failing is this:

`GSsl::Context::Context( const std::string & pem_file , unsigned int flags )
{
	if( (flags&3U) == 2U )
		m_ssl_ctx = SSL_CTX_new(SSLv23_method()) ;
	else if( (flags&3U) == 3U )
		m_ssl_ctx = SSL_CTX_new(SSLv3_method()) ;
	else
		m_ssl_ctx = SSL_CTX_new(TLSv1_method()) ;

	if( m_ssl_ctx == NULL )
		throw Error( "SSL_CTX_new" , ERR_get_error() ) ;

	if( flags&4U )
	{
		// ask for certificates but dont actually verify them
		SSL_CTX_set_verify( m_ssl_ctx , SSL_VERIFY_PEER , verify_callback_always_pass ) ;
	}
	if( (flags&8U) && !pem_file.empty() )
	{
		// ask for certificates and make sure they verify
		SSL_CTX_set_verify( m_ssl_ctx , SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT , NULL ) ;
		check( SSL_CTX_load_verify_locations( m_ssl_ctx , NULL , 
			G::Path(pem_file).dirname().str().c_str() ) , "load_verify_locations" ) ;
	}

	init( pem_file ) ;
}`

There is a reference to SSLv3_method which I do not know know if it is included in the defines and the linked library when SSLv3 support is not selected (maybe there's an empty stub ?). I also forced "make package/openssl/clean" to be sure that OpenSSL is recompiled, but on my system I swear it does compile fine.

**Comment by hnyman** [comment]
I think that the discussion reflects a difference between Openwrt and LEDE. In LEDE the openssl Makefile was tidied a while ago by removing the ssl3_method (as ssl3 itself is disabled). Based on the git commands above @fededim is building from the Openwrt repo, not LEDE.

Openwrt has not updated the openssl since May, while LEDE has continued to update to the newest versions etc.
https://github.com/openwrt/openwrt/commits/master/package/libs/openssl
https://git.lede-project.org/?p=source.git;a=history;f=package/libs/openssl;hb=HEAD

See especially https://git.lede-project.org/?p=source.git;a=commitdiff;h=41da31ac2ca2306e9cff070f650f6012af753517

**Comment by fededim** [comment]
No, there is no such OPENSSL_NO_SSL3_METHOD in my opensslconf.h. Any idea why ?

**Comment by yousong** [comment]
Because OpenWrt and LEDE splits in the case of openssl config.  Well, finally we reached this point ;) ;(

https://github.com/openwrt/openwrt/blob/dbd05b03205fb3405adbe32031fb7c99a7af02a8/package/libs/openssl/Makefile#L116
https://github.com/lede-project/source/blob/175fbe4d4ec4978ff1341f24ce3811d673c91a85/package/libs/openssl/Makefile#L121

**Comment by fededim** [comment]
Ok this explains what is happening, but I am not involved in LEDE in any way and I confirm that I am building on classic Openwrt. In any there's no problem I'll add OPENSSL_WITH_SSL3 dependency for compatibility.

**Comment by fededim** [comment]
Well yousong if you would have explained me immediately we would have reached it sooner :)

**Comment by fededim** [comment]
Just to know what's the syntax for specifying multiple dependencies on a build configuration option ? 

Tried with space, but gives syntax error

config EMAILRELAY_SSL 
   bool "Enable support for OpenSSL"
   depends on PACKAGE_emailrelay CONFIG_OPENSSL_WITH_SSL3

**Comment by yousong** [comment]
> Well yousong if you had told me immediately we would have reached it sooner :)

Well, I mean the point when the effect of repo split accumulated to an extent and caused trouble in the other parts of the ecosystem.  Will it come a day that we need to detect variants of base system to accommodate those differences?  Certainly we do not like it.

As for the syntax, the following should work (remove `EMAILRELAY_SSL` from the `DEPENDS` definition)

```
define Package/emailrelay/config
if PACKAGE_emailrelay
config EMAILRELAY_SUPPORT_VERBOSE_DBG
	bool "Enable support for extended logging"
	default n
	help
	  Enables support for extended logging (must also be explicitely enabled by using command line switch --debug when starting emailrelay)

config EMAILRELAY_SSL
	bool "Enable support for OpenSSL"
	default y
	select PACKAGE_libopenssl
	select OPENSSL_WITH_SSL3
	help
	  Builds the package with OpenSSL support (SSMTP is supported).
endif
endef
```

Just in case, while at it there are two items that can be improved

1. `PKG_CONFIG_DEPENDS` support so that the build system will clean and do a new build on config change
2. Disable building tests with `--disable-testing` configure option

**Comment by hnyman** [comment]
I am no config expert, but I wonder if this last change does not cause the buildbot to always build libopenssl with ssl3 enabled, although it should be disabled by default. (My logic goes like this: buildbot builds all packages, so emailrelay gets selected, and its default config has SSL enabled causing OPENSSL_WITH_SSL3 to get selected.)

At least in my own .config selecting emailrelay patched with this PR, caused CONFIG_OPENSSL_WITH_SSL3=y

Then I tested with empty .config and selected "build all packages" and SSL3 support got again activated for Openssl.

Testing the same with the unpatched emailrelay code leaves SSL3 support out from Openssl.


PS.
> (I don't know if Lede is a branch of openwrt repository or another new repository and where it's hosted).

LEDE is an Openwrt fork where most of the development activity seems to be nowadays. Old Openwrt repo is pretty quiet (as most of active core developers left for LEDE).

**Comment by fededim** [comment]
Well I understand the problem, but yousong told me that the change was to be made in this way and now just after making the changes someone might feel duped because their work has to be thrown out due to your consideration. Just maybe think a little more if this could happen with other packages which use by default ssl v3 methods and if an empty stub is better...otherwise two options: disabled ssl support by default in emailrelay or patch code.

**Comment by yousong** [comment]
Not an SSL/TLS expert, yet, but it looks like people are trying to deprecate ssl protocols.  Another option would be patching upstream emailrelay `configure.ac` script to detect openssl conf and compile accordingly.  Given the fact that openssl builds of various confs may exist, this will also benefit other users of emailrelay.  My two cents.

**Comment by hnyman** [comment]
Openssl's SSLv3 feature has been turned off by default already in 2014 by https://github.com/openwrt/openwrt/commit/b5a50ff4e29def7b0228e3453a540daae7c8088e

This proposed emailrelay change would effectively unturn that explicit decision for all buildbot & release builds. As this package would be built, Openssl would be built with sslv3. A single package's default build should not change another package's global default settings (especially when it is rather core library).

Simplest solution might be to leave the nossl version as the default (that is built by buildbot and for releases) and leave the ssl version (that requires sslv3 / sslv3-method) optional. That optional version might then select the OPENSSL_WITH_SSL3 config option, so that when somebody changes emailrelay options in his .config to compile it with SSL, he would also compile Openssl for himself with the required options (supporting SSLv3).

**Comment by fededim** [comment]
Ok patching sources and configure.ac could be fine, but what's the syntax for checking if in libopenssl the OPENSSL_NO_SSL3 define exists and if so add a local "define" (like gcc -D<variable>) ? I do not know anything about configure.ac files, if someone could help I would be grateful.

**Comment by fededim** [comment]
Done through Makefile instead of configure.ac. You should be able to merge now.

**Comment by hnyman** [comment]
Thanks. Looks much better now.

**Comment by fededim** [comment]
Still waiting to know which would have been the best way to patch configure.ac for checking ssl3 support in openssl (probably using AC_CHECK_LIB defining a variabile with compile flags [-DSSL3_SUPPORT] and passing it always to CXXFLAGS)...in emailrelay however libopenssl is not checked inside configure.ac but in another file acinclude.m4 (it seems it tries to compile a small c program to check for openssl library)

dnl with-openssl
dnl
dnl Sets SSL_LIBS and "if OPENSSL" in makefiles.
dnl
AC_DEFUN([WITH_OPENSSL],
if test "$with_openssl" != "no"
then
[AC_CACHE_CHECK([for openssl],[aclocal_cv_openssl],
[
	AC_COMPILE_IFELSE([AC_LANG_PROGRAM(
		[[#include <openssl/ssl.h>]],
		[[SSL_CTX * p = 0 ; return 1;]])],
		aclocal_cv_openssl=yes,
		aclocal_cv_openssl=no )
])
    if test "$aclocal_cv_openssl" = "yes"
	then
		SSL_LIBS="-lssl -lcrypto"
		aclocal_ssl="openssl"
	else
		if test "$with_openssl" = "yes"
		then
			AC_MSG_WARN([ignoring --with-openssl: check config.log and try setting CFLAGS])
		fi
		SSL_LIBS=""
		aclocal_ssl="none"
	fi
else
	SSL_LIBS=""
	aclocal_ssl="none"
fi
AC_SUBST(SSL_LIBS)
AM_CONDITIONAL(OPENSSL,test x$aclocal_ssl = xopenssl)
])

**Pull request merged**
