### PR TITLE
samba4: update to 4.9.7

### PR DESCRIPTION
**Pull request by Andy2244**
Maintainer: me
Compile tested: arm (snapshots)
Run tested: arm

Description:
* update to 4.9.7
* add write_list, read_list UCI support

### CODE REVIEW

**Comment by Andy2244** [comment]
Lol, fastest merge ever!

**Comment by diizzyy** [comment]
https://www.youtube.com/watch?v=-yNhl8wT3Pc :-)

**Comment by wongsyrone** [comment]
@Andy2244 Any plan to upgrade to 4.10.2?

**Comment by Andy2244** [comment]
> 
> 
> @Andy2244 Any plan to upgrade to 4.10.2?

Yes, but atm i get a hard to debug/fix openwrt related bug, at the WAF configure stage. For some strange reason the "test simple-c program" step fails. I need more time to manually replicate this step and figure out weather the actual build via gcc fails or if its a WAF/python3 error that checks the results.

**Comment by wongsyrone** [comment]
> test simple-c program

host compiler might get invoked instead of the cross compiler

**Comment by Andy2244** [comment]
> host compiler might get invoked instead of the cross compiler

Nah i checked the config.log files already and also the invoked gcc line for the step, everything looks fine, yet i get a crash.

**Comment by Andy2244** [comment]
@wongsyrone ok here #8944 is the problematic one.

**Pull request merged**
