### PR TITLE
frr: add missing build options

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Maintainer: me 
Tested ramips

### CODE REVIEW

**Comment by kunxiang1** [comment]
Still have the same error

`
login as: root
root@192.168.1.1's password:
Server refused to set environment variables


BusyBox v1.31.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r11503-10bcf1e
 -----------------------------------------------------
root@OpenWrt:~# vtysh
Bus error
root@OpenWrt:~# /etc/init.d/frr start
Bus error
Failed to start watchfrr!
root@OpenWrt:~# watchfrr
Bus error
root@OpenWrt:~#
`

**Comment by lucize** [comment]
can you try the new commit ?
image

**Comment by lucize** [comment]
@neheb this should be good now, without this, mips complained with 

```
can't find matching LO16 reloc against `.data.mtypes' for R_MIPS16_GOT16 at 0x4d88 in section `.text'
```

**Comment by kunxiang1** [comment]
It's work fine now
```
Server refused to set environment variables


BusyBox v1.31.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r11525-1ea22e4
 -----------------------------------------------------
root@OpenWrt:~# vtysh
% Can't open configuration file /etc/frr/vtysh.conf due to 'No such file or directory'.

Hello, this is FRRouting (version 7.2).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

OpenWrt# quit
root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.152 #0 SMP Thu Nov 14 00:38:01 2019 mips GNU/Linux
root@OpenWrt:~#

```

**Pull request merged**
