### PR TITLE
aria2: update to last commit

### PR DESCRIPTION
**Pull request by Ansuel**
Switch to github repo and update to last commit

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@kuoruan

**Comment by Ansuel** [comment]
Actually i didn't check if it does have any problem with compiling or not...

Need to inspect why.... think we need to add autoreconf for pkg  fixup

**Comment by kuoruan** [comment]
I think we should use release version

**Comment by hnyman** [comment]
Is there any major reason to switch to git commits between releases? 
Last update of the package has been three weeks ago, so this is not stale.
In general, it is better to stick to the releases.

**Comment by hnyman** [comment]
no reasoning given, and the maintainer did not like the proposal. Let's close it

**Pull request closed without merging**
