### PR TITLE
mwan3: Remove check_quality options from default config

### PR DESCRIPTION
**Pull request by jamesmacwhite**
Signed-off-by: James White <james@jmwhite.co.uk>

Maintainer: @feckert 
Compile tested: N/A
Run tested: N/A

Description:

As per https://github.com/openwrt/packages/issues/13211. This removes the check_quality options from the default configuration shipping with mwan3. Because the default configuration doesn't have `check_quality` enabled, they aren't doing anything and can safely fallback to the defaults unless enabled by the user.

### CODE REVIEW

**Comment by feckert** [comment]
I would like to have first https://github.com/openwrt/packages/pull/13169 merged. After that we could bump the PKG_RELEASE number and merge this.

**Comment by jamesmacwhite** [comment]
@feckert No worries. I'll leave it open for now

**Comment by jamesmacwhite** [comment]
@feckert Wondering if it's also worth removing some of the other options, keeping the default interface definitions basic, I don't know if there is any benefit from setting these outside of their default for most configurations?

* `reliability` - 2 (Default: 1)
* `count` - 1 (Default: 1)
* `timeout` - 2 (Default: 4)
* `interval` - 5 (Default: 10)
* `down` - 3 (Default: 5)
* `up` -  (Default: 5)

It seems `count` is redundant as it's the same, `reliability` is different for the the `wan` example, which I guess you could argue as it's often the primary interface, the rest do different but should we cut down the default options?

We could have a comment at the top of the example configuration file with?

```
# Full documentation of options available: 
# https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3#mwan3_configuration

**Comment by jamesmacwhite** [comment]
I noticed there are some additional options that are mismatched between LuCI and mwan3track, so I opened a PR for that here: https://github.com/openwrt/luci/pull/4429

**Comment by feckert** [comment]
This is already in [P/R](https://github.com/openwrt/packages/pull/13169/commits/6083251740bf89d7c6c53b06d7e3f6397743c7ed) staged so we could close them.

**Pull request closed without merging**
