### PR TITLE
procps-ng: use alternatives to coexist with busybox applets

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: @kissg1988 
Compile tested: mips_24kc, qemu malta, lede master (r4072-fa3649d97e)
Run tested: qemu malta

### CODE REVIEW

**Comment by yousong** [comment]
Please note that this alternatives feature is at the moment not available in OpenWrt yet.

**Comment by yousong** [comment]
oops, looks like it will break procps-ng on OpenWrt.   I will see what I can do with OpenWrt compatibility...

**Comment by champtar** [comment]
@yousong any updates?

**Comment by yousong** [comment]
No, I am waiting for the official retirement of OpenWrt repo ;)

**Comment by psyborg55** [comment]
what you're trying to do here looks completely wrong: i've just checked my openwrt buildroot and these procps-ng apps already coexist with busybox versions. since the problems only happens in lede you should find a different solution or make a separate package tree for lede

**Comment by yousong** [comment]
Thanks for telling me this, but I am not convinced that the change is completely wrong.  Since you have done the check and to be more helpful saving other people's time, please provide/share the comparison of installation locations of busybox components that will cause conflict with LEDE, but not OpenWrt's old repo.

Forking another packages repo is not an option right now.  It will hurt the current ongoing re-merge efforts

**Comment by yousong** [comment]
Merge as now the repo merge has completed.  Thanks for the patience.

**Pull request merged**
