### PR TITLE
boost: Bump to version 1.78.0

### PR DESCRIPTION
**Pull request by ClaymorePT**
**Maintainer:** @ClaymorePT 
**Compile tested:** BCM27xx/Raspberry Pi 4B (64 bits)
**Run tested:** N/A

**Description:**
This commit updates boost to version 1.78.0
More info about Boost 1.78.0 can be found at the [usual place](https://www.boost.org/users/history/version_1_78_0.html).

No new libraries have been added.

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

### CODE REVIEW

**Comment by ClaymorePT** [comment]
@neheb It seems that x86_64 test is failing due to an unrelated issue with boost.
Nothing else to do from my side. Please review.

**Comment by neheb** [comment]
this seems to break https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/pdns-recursor/compile.txt

**Comment by ClaymorePT** [comment]
@neheb I'll take a look. Thanks for reporting!

**Comment by ClaymorePT** [comment]
@neheb to be honest, I have no idea why this is happening. There was an update to Boost.Context from 1.77 to 1.78 which could be related with the issue (https://github.com/boostorg/context/commit/6edc8184a7136de4603a6f903d9b9b864ca9cf57) but to be honest, I do not understand why would this prevent pdns-recursor from failing the configuration phase.

I'm seeing multiple undefined references such as `undefined reference to `jump_fcontext'` similar to what we resolved in https://github.com/openwrt/packages/issues/9493 but I'm a bit confused about what could be the problem. The assembly for mips N64 is there. 

I'll need to allocate more time to understand this.

**Comment by neheb** [comment]
The assembly is there but not in the actual library:

```
mangix@ryzen ~/d/openwrt (mangix) [1|1]> strings staging_dir/target-mips64_mips64r2_64_musl/usr/lib/libboost_context.so.1.77.0 | grep fcon
make_fcontext
jump_fcontext
ontop_fcontext
jump_fcontext
ontop_fcontext
make_fcontext
mangix@ryzen ~/d/openwrt (mangix)> strings staging_dir/target-mips64el_mips64r2_64_musl/usr/lib/libboost_context.so.1.78.0 | grep fcon
```

**Comment by ClaymorePT** [comment]
Hmm, weird. Let me check that out then.

**Comment by neheb** [comment]
Yeah I think it's mips1 that's the problem:

```
 Performing configuration checks
   16
   15     - default address-model    : 64-bit [1]
   14     - default architecture     : mips1 [1]
   13 error: No best alternative for libs/context/build/asm_sources

```

**Comment by ClaymorePT** [comment]
It seems that the issue might be located in the boost.build system. Boost.Context was update and the mips archs were unified into just mips.

Boost.Build was not updated accordingly and because of that, it is building boost.context using the previous default value for architecture `mips1`. This seems to be causing Boost.Context to not select the assembly containing the functions.

There was a PR with an update for Boost.Build (https://github.com/boostorg/build/pull/731) but it seems that it was closed before being merged.

**Comment by ClaymorePT** [comment]
Dammit @neheb . You beat me for 2 minutes :)

**Comment by ClaymorePT** [comment]
This PR could be what we need -> https://github.com/bfgroup/b2/pull/58

**Comment by neheb** [comment]
```
--- a/boostcpp.jam
+++ b/boostcpp.jam
@@ -634,7 +634,7 @@ rule address-model ( )
     return <conditional>@boostcpp.deduce-address-model ;
 }

-local deducable-architectures = arm mips1 power riscv s390x sparc x86 combined ;
+local deducable-architectures = arm mips power riscv s390x sparc x86 combined ;
 feature.feature deduced-architecture : $(deducable-architectures) : propagated optional composite hidden ;
 for a in $(deducable-architectures)
 {
@@ -645,10 +645,10 @@ rule deduce-architecture ( properties * )
 {
     local result ;
     local filtered = [ toolset-properties $(properties) ] ;
-    local names = arm mips1 power riscv s390x sparc x86 combined ;
+    local names = arm mips power riscv s390x sparc x86 combined ;
     local idx = [ configure.find-builds "default architecture" : $(filtered)
         : /boost/architecture//arm
-        : /boost/architecture//mips1
+        : /boost/architecture//mips
         : /boost/architecture//power
         : /boost/architecture//riscv
         : /boost/architecture//s390x
diff --git a/libs/config/checks/architecture/Jamfile.jam b/libs/config/checks/architecture/Jamfile.jam
index 2ba54f9ad..f96488611 100644
--- a/libs/config/checks/architecture/Jamfile.jam
+++ b/libs/config/checks/architecture/Jamfile.jam
@@ -18,7 +18,7 @@ obj 64 : 64.cpp ;

 obj arm      : arm.cpp ;
 obj combined : combined.cpp ;
-obj mips1    : mips1.cpp ;
+obj mips     : mips1.cpp ;
 obj power    : power.cpp ;
 obj riscv    : riscv.cpp ;
 obj sparc    : sparc.cpp ;
```

worked for me

**Pull request merged**
