### PR TITLE
mail/{msmtp,postfix}: Add provides sendmail-command

### PR DESCRIPTION
**Pull request by dfc-d**
For mail programs that supply a sendmail command,
add PROVIDES sendmail-command so that programs
which depend on having sendmail can depend on
sendmail-command without forcing the user to
use a particular sendmail provider.

Signed-off-by: Daniel Dickinson <lede@daniel.thecshore.com>

### CODE REVIEW

**Comment by yousong** [comment]
The patch is useful.  It will be better if there is a follow-up commit to convert existing packages like mdadm in base and bogofilter in packages feeds to use this sendmail depends.  Also maybe the new provides name can be simply `sendmail` without causing ambiguity.

**Comment by dfc-d** [comment]
I'm happy to do a follow up if this is accepted.

The reason for sendmail-command vs. sendmail was in cast someone decides to add the actual sendmail package (not sure how likely that is, for it to be a consideration).

**Comment by dfc-d** [comment]
Is this okay to commit or is general feeling to rename as 'sendmail' vs. 'sendmail-command'?

**Comment by yousong** [comment]
I am fine with the current `sendmail-command`, but I think there is no need to hurry and prefer possible follow-up commits for packages in this repo also happen in this pr to make it more complete.

Notifying respective maintainers just in case.  @psycho-nico , @Shulyaka , @dibdot

**Comment by dibdot** [comment]
To be honest, I didn't know the 'provides' statement up to now. What's the benefit vs. something like this?

`#!/bin/sh
ln -sf ssmtp $${IPKG_INSTROOT}/usr/sbin/sendmail`

**Comment by dfc-d** [comment]
On Mon, 2016-06-20 at 20:31 -0700, dibdot wrote:
> To be honest, I didn't know the 'provides' statement up to now. What's
> the benefit vs. something like this?
> 
> #!/bin/sh
> ln -sf ssmtp $${IPKG_INSTROOT}/usr/sbin/sendmail
> 
1) Fails to conflict on /usr/sbin/sendmail with other providers and
makes which program is acting as sendmail depends on what order packages
get installed (if more than one provider installed), instead of being
prevented without deliberate --force-overwrite.
2) trunk devs have indicated that they don't like symlink mangling to
deal with alternatives (you'd have to ask them why though, I don't know
that, only their disklike of it).
3) In general having packages overwrite what another package does
without an explicit --force-overwrite is bad packaging practice (at
least some other distros (e.g. debian) explicity forbid it).

**Comment by dibdot** [comment]
Thanks for the explanation.
Cosenquently I should remove this symlink, too? I would prepare a PR without the symlink and a provides statement "sendmail" - only for ssmtp of course. OK?

**Comment by dfc-d** [comment]
Makes sense to me!  I'll update this PR for the other packages.

**Comment by dfc-d** [comment]
Not that the symlink is not removed entirely - it is moved into /install where it can conflict.

**Comment by dfc-d** [comment]
I've removed ssmtp part of patch since maintainer plans on update that package. 
I've also split the postfix and msmtp patches
I've also added making symlink to sendmail part of /install instead of postrm/postinst mangling (which is not liked by trunk devs, and some other reason explained in commit message).
I'v also added a patch for bogofilter to depend on sendmail-command.
I haven't seen any other packages with a *local* MTA is *required* (although there are packages that can use/benefit from such, including mdadm and nut).

**Comment by dibdot** [comment]
#2888

**Comment by dibdot** [comment]
@dfc-d the new symlink in your msmtp patch looks wrong to me. You'll try to create a symlink into the 'host' file system, it will brake buildroot environments.

**Comment by dfc-d** [comment]
Fixed error in sendmail symlink (missed $(1) to install to target instead of host) thanks @dibdot

**Comment by dfc-d** [comment]
Updated title to URFC since I've made changes that I haven't tested yet.

**Comment by dfc-d** [comment]
On Wed, 2016-06-22 at 21:05 -0700, dibdot wrote:
> @dfc-d the new symlink in your msmtp patch looks wrong to me. You'll
> try to create a symlink into the 'host' file system, it will brake
> buildroot environments.
> 
Thanks for the catch! 
>

**Comment by dfc-d** [comment]
Used successfully.

**Comment by dfc-d** [comment]
Any further comments on this?

**Comment by champtar** [comment]
I've merged a commit to remove PROVIDES from transmission, because PROVIDES is broken in some case, so this need to be fully tested

**Comment by dfc-d** [comment]
On Mon, 2016-07-04 at 00:18 -0700, champtar wrote:
> I've merged a commit to remove PROVIDES from transmission, because
> PROVIDES is broken in some case, so this need to be fully tested

There is an openwrt ticket for this:

The issue is that openwrt's opkg doesn't recognize 'provides'
dependencies as being satisfied unless prior to the opkg command to
install the package depending on a provider, a provider is already
installed.  With ImageBuilder this can arranged by supplying the
provider package before the dependent package in the packages list
supplied by the user, but there is no way to achieve this with a pure
menuconfig/make build.

I had forgotten that issue (there is an openwrt ticket for it, but not
LEDE one).  I guess this patch will have to be delayed until I'm able
to spend the time to get the upstream version of opkg into a form where
it can actually be used by openwrt (Yocto's version is to big in it's
stock form).

Regards,

Daniel

**Comment by dfc-d** [comment]
Closing until PROVIDES fixed.

**Comment by Shulyaka** [comment]
Hi @champtar,

I tried to find any reference to this opkg bug to check if it is still open, but failed. I am also unable to find the commit that removes PROVIDES from transmission to find some info there. Could you point me to the right direction please? May be it's time to reopen this pull request if the PROVIDES is fixed.

Best regards,
Denis Shulyaka

**Pull request closed without merging**
