### PR TITLE
libulfius: update to 2.6.9

### PR DESCRIPTION
**Pull request by lnslbrty**
Signed-off-by: Toni Uhlig <matzeton@googlemail.com>

Maintainer: me
Compile tested: x86_64, OpenWrt SNAPSHOT, r13575+9-d64d5ed142
Run tested: x86_64, OpenWrt SNAPSHOT, r13575+9-d64d5ed142

Description:

### CODE REVIEW

**Comment by neheb** [comment]
@aparcar Actions need fixing I think.

**Comment by aparcar** [comment]
@neheb I reworked the package selection logic, please rebase this PR and see if it works.

**Comment by lnslbrty** [comment]
Someone has any clue why it fails on the CI?
I had no issues at all bulding it locally.
(Sorry, can't view the big fat build logfile from my smartphone without getting eye cancer.)

**Comment by neheb** [comment]
@lnslbrty issue with the CI. Note that CircleCI builds it fine.

**Comment by aparcar** [comment]
CI should be fixed now.

**Pull request merged**
