### PR TITLE
findutils: Add missing header

### PR DESCRIPTION
**Pull request by neheb**
New version of musl no longer internally includes this header.

Fixed up LICENSE information.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @cshoredaniel 
Compile tested: armeb

### CODE REVIEW

**Comment by neheb** [comment]
https://downloads.openwrt.org/snapshots/faillogs/mipsel_74kc/packages/findutils/compile.txt

**Comment by cshoredaniel** [comment]
Have you run-tested?

**Comment by neheb** [comment]
No. This just adds a missing header as a consequence of the musl version update.

**Comment by cshoredaniel** [comment]
I afraid I've seen too many time this kind of 'simple' change is part of a larger change that results in failure to operate properly and will NAK until I, you, or someone else, get chance to run test.

**Comment by neheb** [comment]
Fair enough. This will remain broken on the buildbots.

**Comment by cshoredaniel** [comment]
Will be run testing today or tomorrow, but please also separate LICENSE change from new patch/fix.

**Comment by cshoredaniel** [comment]
It's too soon to apply this change: With the latest snapshot SDK, compile fails with your patch applied:

```
ccache_cc  -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/daniel/Build/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/findutils-4.6.0:findutils-4.6.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro   -L/home/daniel/Build/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64/staging_dir/target-mips_24kc_musl/usr/lib -L/home/daniel/Build/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64/staging_dir/target-mips_24kc_musl/lib -L/home/daniel/Build/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/usr/lib -L/home/daniel/Build/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib -znow -zrelro  -o find ftsfind.o ./libfindtools.a ../lib/libfind.a ../gl/lib/libgnulib.a       -lm -lm
/home/daniel/Build/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/bin/../lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: ../gl/lib/libgnulib.a(mountlist.o): in function `read_file_system_list':
mountlist.c:(.text+0x1d6): undefined reference to `makedev'
collect2: error: ld returned 1 exit status
make[7]: *** [Makefile:1810: find] Error 1
```
I verified mountlist.c had the fix.  Did you do a clean build?  I used fresh SDK (not sure how the check above passed...seems to be some difference between local build and CircleCI).  Since it's a linker error not compiler error, it looks like the function is actually not in an available library with the current SDK.

**Comment by neheb** [comment]
That's the error this patch fixes...

I just verified again. Fails without, succeeds with. Something's wrong on your end.

**Comment by cshoredaniel** [comment]
How did you build?  With SDK, or all-in-one build?  It may matter.  Or 
ccache could be this issue, which I will investigate. And the error you 
fix is not that one -- at least that patch wouldn't.  The issue you fix 
is a compile error, the error I get is a *link* error.

Regards,

Daniel

**Comment by neheb** [comment]
The buildbot log I posted is also a linker error...

This is exactly the error that this patch fixes.

**Comment by cshoredaniel** [comment]
Did you ever experience the error yourself?  i.e. before 'fixing' did you have a reproducible test case?  I have removed ~/.ccache AND removed my extracted SDK dir, and re-extracted the SDK I downloaded around midnight EST5EDT (05:00 UTC), and am still getting the exact same error.  And I verified the patched file has the the patch.

I do not believe you actually fixed the issue, because the issue is a **linker** error and you are giving a **compiler** solution AND with a FRESH checkout and no ccache (i.e. nothing old) the error is produced again on a local build.  Please reproduce the error on your system and verify the fix actually fixes the error once you've seen the error on your own builds.

**Comment by cshoredaniel** [comment]
Also, have you tried ath79?  I see you tested armeb -- perhaps there is a an arch-specific issue at work here.

**Comment by neheb** [comment]
I give up.

**Comment by cshoredaniel** [comment]
Hmmm....something weird going on here...the package feed from my repo isn't properly checked out by feeds install...
I may owe you an apology.  Digging deeper.

**Comment by cshoredaniel** [comment]
The second build (with fresh SDK) didn't actually have the patch due to feeds issue, so I'm rebuilding with a fresh extract again, and we'll see how that goes.

**Comment by cshoredaniel** [comment]
I've looked further back in the build log, and found the failure message from the compilation -- the last message is not error that's actually relevant to solving the issue.  I'm surprised the build did abort at that point; would have to dig into the Makefiles to see what allowed the build to continue despite the compilation failure, but it's probably more effort than it's worth.
So the error I listed is a linker error, but you are right the underlying issue is a compiler error.

**Comment by cshoredaniel** [comment]
After much and pain and angst I noticed the package feed from my local repo was pointing at the wrong branch (without your patch applied) for the second build.  Build is in progress for the third time.  So build #1 ccache was an issue (I was experimenting with using it--I think I'll call that a fail on the grounds of complicating rebuilds of different version; might be okay for production builds). build #2 was a wrong branch.  
Therefore my apologies.  I think build #3 ought to succeed, and I can actually run test.

**Comment by cshoredaniel** [comment]
You're weak on providing evidence, I must say -- if you'd shown the further back compilation error, that would have been a stronger argument than "well it works for me".

**Comment by cshoredaniel** [comment]
Ok, did a quick smoke/run-test of updatedb, locate, find, and xargs.  Things are looking okay, so once you separate LICENSE changes from the patch, I'll ACK.
Apologies for any consternation due to local build issues.

**Comment by neheb** [comment]
Done

**Comment by cshoredaniel** [comment]
ACK.  Thanks.  Sorry for the confusion etc.

**Pull request merged**
