### PR TITLE
sstp-client: updated to 1.0.12

### PR DESCRIPTION
**Pull request by fededim**
softethervpn: updated to 4.25-9656

Signed-off-by: Federico Di Marco <fededim@gmail.com>

### CODE REVIEW

**Comment by fededim** [comment]
Now it should work

**Comment by hnyman** [comment]
You won't find those until the packages get fixed...

See faillogs:
https://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/softethervpn/

```
ccache gcc -L./src/readline -D'add_history(x)' -D'readline(x)=""' -DNDEBUG -DVPN_SPEED -DUNIX -DUNIX_LINUX -DCPU_64 -D_REENTRANT -DREENTRANT -D_THREAD_SAFE -D_THREADSAFE -DTHREAD_SAFE -DTHREADSAFE -D_FILE_OFFSET_BITS=64 -I./src/ -I./src/Cedar/ -I./src/Mayaqua/ -O2 -fsigned-char -m64 -c src/Mayaqua/Encrypt.c -o tmp/objs/Mayaqua/Encrypt.o
src/Mayaqua/Encrypt.c:127:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
src/makefiles/linux_64bit.mak:77: recipe for target 'tmp/objs/Mayaqua/Encrypt.o' failed
make[4]: *** [tmp/objs/Mayaqua/Encrypt.o] Error 1
```

https://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/softethervpn/host-compile.txt

etc.

**Comment by fededim** [comment]
On Lede compilation is fine https://downloads.lede-project.org/snapshots/packages/mipsel_24kc/packages/


softethervpn_4.25-9656-1_mipsel_24kc.ipk | 3595.0 KB | Mon Mar 12 01:57:55 2018
-- | -- | --

**Comment by hnyman** [comment]
It has been compiled successfully only for a few targets.
Seems to fail for most targets.

I haven't looked if that is due to specific buildslave, big-endian/little-endian things

**Comment by fededim** [comment]
Yep, you are right, it works only on some...ok I'll have a look into it. The error states missing ssl.h, how could it relate to big-endian/little-endian things ?

**Comment by hnyman** [comment]
No specific reason. I just highlighted some typical causes for some targets failing and others building ok.

**Comment by solipse** [comment]
@fededim @hnyman @Andy2244 
Hello.
And no one tried to compile softethervpn with LibreSSL, or is it impossible in Linux?

**Comment by Andy2244** [comment]
@solipse Not me, but can give it a shoot over the holidays. It depends on the cmake logic and how it detects the ssl headers/libs in the case of LibreSSL.

**Comment by solipse** [comment]
@Andy2244 thanks for the answer
Perhaps this can solve the problem of building on different architectures, but maybe not.

**Pull request merged**
