### PR TITLE
fwknop: respect global SSP settings

### PR DESCRIPTION
**Pull request by ryzhovau**
One-line variant of https://github.com/openwrt/packages/pull/1175

### CODE REVIEW

**Comment by oneru** [comment]
What is the problem behavior without this patch, and is it limited to fwknop?

**Comment by ryzhovau** [comment]
When `libssp` is available, `fwknop(d)` will be linked against it, but it's not listed in dependencies.
I've made another commit to make `libssp` dependency optional.

**Comment by oneru** [comment]
See package-defaults.mk in the main openwrt project. When ssp is enabled, it makes all packages depend on libssp. This was a better option than adding the optional dep to each package

**Comment by ryzhovau** [comment]
So, if it's better to close pull request, no problem.
I fall into this issue with my external toolchain, containing `libssp`, when `CONFIG_SSP_SUPPORT` wasn't set.

**Comment by oneru** [comment]
You might create a bug report on https://dev.openwrt.org/ It could be that there should be an ssp option in the use external toolchain submenu of menuconfig. I'm not sure of the best solution.

**Comment by ryzhovau** [comment]
> I'm not sure of the best solution.

Me too. Also, there is too few are using external toolchain. 
Closing for now.

**Pull request closed without merging**
