### PR TITLE
rtl_433: update to 20.02

### PR DESCRIPTION
**Pull request by neheb**
Added patch to fix compilation.

Added PKG_BUILD_PARALLEL for faster compilation.

Fixed license information.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @TimelessNL 
Compile tested: ath79

### CODE REVIEW

**Comment by TimelessNL** [comment]
**Thanks**,
Do you have a rtl_sdr compatible dongle to test the upgrade on?

I'm asking this because I've tested the 19.08 release on a bcm2710 target some weeks ago, and was unable to receive anything. After downgrading librtlsdr and using libusb-1.0 from the OpenWrt 18.06 branch it started to receive data. That's why I've not updated the package yet.

Also I had to add `TARGET_CFLAGS += -Wno-error=format-security` which I don't see in your commit.

**Comment by neheb** [comment]
That's what the extra patch fixes.

I do not have the hardware to test this.

**Comment by neheb** [comment]
Got rid of the patch.

**Comment by TimelessNL** [comment]
Ok I've run some excessive tests and found that my specific sensor is just broken in rtl_433 since it seems to have many protocol similarities with a new soil moisture sensor and therefor conflicts and is not properly decoded. I've tested some other sensors I had laying around and they all worked fine.

So I have no problem that this request is merged. 👍

**Comment by TimelessNL** [comment]
@BKPepe `needs run-testing` is done and succeeded.

**Comment by neheb** [comment]
> > Got rid of the patch.
> 
> Mention that in your commit description and then it can be merged.

My comment was for a format patch. But I mentioned removing the other one anyway.

**Comment by ouinouin** [comment]
@neheb ,
i m just trying RTL433 on my router, and despite saying the packaged version is 20.02 it seems not being the case.
in the 20.02; therie is about 150 deconders, and the list while running rtl_433 show only 99.
another point is the 20.02 should support influxdb as an output, but it seems not being the case.
I checked the tarball fetched by the makefile and it looks correct , maybe some flags somewhere in the compilation system ? 
where to look for the compilation options used by openwrt ?
regards.

**Pull request merged**
