### PR TITLE
ddns-scripts: new ddns service - FreeDNS.42.pl

### PR DESCRIPTION
**Pull request by michallipka**
Maintainer: Christian Schoenebeck <christian.schoenebeck@gmail.com>
Compile tested: arch:arm, OpenWRT/LEDE version: 17.01
Run tested:  arch:arm, OpenWRT/LEDE version: 17.01, tests done

Description:
**- this script needs curl - don't know how enforce this (if needed of course)**
- new ddns script for polish service FreeDNS.42.pl where you can host your own domains
- changes in other files are exact copy of no-ip integration - label change only

Signed-off-by: Michal Lipka <michal@sysadmin.care>

### CODE REVIEW

**Comment by chris5560** [comment]
To add additional dependency on curl you need to set your DEPENDS to
    DEPENDS:=ddns-scripts +curl

(see: define Package/ddns-scripts_cloudflare.com-v4)

In addition please increase PKG_RELEASE inside Makefile
!!! Attention !!! please wait on #6103 to be merged, because also increasing PKG_RELEASE

**Comment by michallipka** [comment]
I increased PKG_RELEASE to 8 as #6103 increased it to 7 so merge that first.

**Comment by michallipka** [comment]
@chris5560 will you merge with those 2 failing checks or should I change something (and what?)

**Comment by hnyman** [comment]
closed with 269b4ce218

**Pull request closed without merging**
