### PR TITLE
jool: Backport two fixes for newer kernels.

### PR DESCRIPTION
**Pull request by D-Albers**
The first is needed for 4.14 (maybe the relevant parts got backported and
the second is for when OpenWrt migrates to 4.19.

Signed-off-by: Rosen Penev <rosenp@gmail.com>
(cherry picked from commit 4f28139a3cf897cdf7d8bb9a48fdd5c0f490b0e0)

Maintainer: @danrl 
Compile tested: ar71xx, OpenWRT 18.06

Description: Backport the necessary patches from master to 18.06

~~

### CODE REVIEW

**Comment by diizzyy** [comment]
18.XX wont migrate to 4.19

**Comment by D-Albers** [comment]
Is jool using the kernel of the build system and not from target?
I'm getting the following error on debian unstable with a 4.19.0 kernel.

> make -j1  V=s package/jool/compile
> make[1]: Entering directory '/opt/openwrt/18.06'
> make[2]: Entering directory '/opt/openwrt/18.06/package/libs/toolchain'
> echo "libc" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
> echo "libgcc" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
> echo "libpthread" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
> make[2]: Leaving directory '/opt/openwrt/18.06/package/libs/toolchain'
> time: package/libs/toolchain/compile#0.16#0.07#0.22
> make[2]: Entering directory '/opt/openwrt/18.06/package/firmware/linux-firmware'
> make[2]: Leaving directory '/opt/openwrt/18.06/package/firmware/linux-firmware'
> time: package/firmware/linux-firmware/compile#2.83#1.17#3.80
> make[2]: Entering directory '/opt/openwrt/18.06/package/firmware/prism54-firmware'
> make[2]: Leaving directory '/opt/openwrt/18.06/package/firmware/prism54-firmware'
> time: package/firmware/prism54-firmware/compile#0.17#0.07#0.22
> make[2]: Entering directory '/opt/openwrt/18.06/package/kernel/linux'
> echo "kernel" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> WARNING: kmod-crypto-hw-ccp is not available in the kernel config - generating empty package
> WARNING: kmod-crypto-hw-geode is not available in the kernel config - generating empty package
> WARNING: kmod-crypto-hw-padlock is not available in the kernel config - generating empty package
> WARNING: kmod-crypto-hw-talitos is not available in the kernel config - generating empty package
> WARNING: kmod-crypto-pcompress is not available in the kernel config - generating empty package
> WARNING: kmod-hwmon-pwmfan is not available in the kernel config - generating empty package
> echo "kmod-lib-crc-ccitt" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> WARNING: kmod-ixgbevf is not available in the kernel config - generating empty package
> WARNING: kmod-of-mdio is not available in the kernel config - generating empty package
> echo "kmod-nf-reject" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nf-reject6" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nf-ipt" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nf-ipt6" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-ipt-core" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nf-conntrack" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nf-conntrack6" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nf-nat" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-ipt-conntrack" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-ipt-nat" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> WARNING: kmod-ipt-ulog is not available in the kernel config - generating empty package
> echo "kmod-ip6tables" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-slhc" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-ppp" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-pppox" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-pppoe" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-nls-base" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> WARNING: kmod-gpio-dev is not available in the kernel config - generating empty package
> WARNING: kmod-gpio-mcp23s08 is not available in the kernel config - generating empty package
> WARNING: kmod-bmp085 is not available in the kernel config - generating empty package
> WARNING: kmod-bmp085-i2c is not available in the kernel config - generating empty package
> WARNING: kmod-bmp085-spi is not available in the kernel config - generating empty package
> WARNING: kmod-w83627hf-wdt is not available in the kernel config - generating empty package
> WARNING: kmod-itco-wdt is not available in the kernel config - generating empty package
> WARNING: kmod-it87-wdt is not available in the kernel config - generating empty package
> echo "kmod-usb-core" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-usb-ledtrig-usbport" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-usb-ehci" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> echo "kmod-usb2" >> /opt/openwrt/18.06/staging_dir/target-mips_24kc_musl/pkginfo/linux.default.install
> WARNING: kmod-net-prism54 is not available in the kernel config - generating empty package
> WARNING: kmod-leds-nu801 is not available in the kernel config - generating empty package
> WARNING: kmod-leds-rb750 is not available in the kernel config - generating empty package
> make[2]: Leaving directory '/opt/openwrt/18.06/package/kernel/linux'
> time: package/kernel/linux/compile#3.78#0.55#4.33
> make[2]: Entering directory '/opt/openwrt/18.06/package/libs/libnl'
> make[2]: Leaving directory '/opt/openwrt/18.06/package/libs/libnl'
> time: package/libs/libnl/compile#0.19#0.08#0.24
> make[2]: Entering directory '/opt/openwrt/18.06/package/network/utils/ethtool'
> make[2]: Nothing to be done for 'compile'.
> make[2]: Leaving directory '/opt/openwrt/18.06/package/network/utils/ethtool'
> time: package/network/utils/ethtool/compile#0.13#0.04#0.16
> make[2]: Entering directory '/opt/openwrt/18.06/package/libs/argp-standalone'
> make[2]: Leaving directory '/opt/openwrt/18.06/package/libs/argp-standalone'
> time: package/libs/argp-standalone/compile#0.14#0.07#0.20
> make[2]: Entering directory '/opt/openwrt/18.06/feeds/packages/net/jool'
> rm -f /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built
> touch /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built_check
> make -C "/opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.146" KERNEL_DIR="/opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.146" ARCH="mips" CROSS_COMPILE="mips-openwrt-linux-musl-" SUBDIRS="/opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful" V="s" modules
> make[3]: Entering directory '/opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.146'
>   CC [M]  /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o
> /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c: In function 'inet6_hash_frag':
> /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: error: 'INETFRAGS_HASHSZ' undeclared (first use in this function); did you mean 'INET_FRAG_LAST_IN'?
>   return c & (INETFRAGS_HASHSZ - 1);
>               ^~~~~~~~~~~~~~~~
>               INET_FRAG_LAST_IN
> /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
> /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.c:97:1: warning: control reaches end of non-void function [-Wreturn-type]
>  }
>  ^
> make[4]: *** [scripts/Makefile.build:305: /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful/fragment_db.o] Error 1
> make[3]: *** [Makefile:1528: _module_/opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/mod/stateful] Error 2
> make[3]: Leaving directory '/opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/linux-4.9.146'
> make[2]: *** [Makefile:116: /opt/openwrt/18.06/build_dir/target-mips_24kc_musl/linux-ar71xx_generic/jool-9dfaf22e49f7905d94af9b73f9bee22c26d7dd4a/.built] Error 2
> make[2]: Leaving directory '/opt/openwrt/18.06/feeds/packages/net/jool'
> time: package/feeds/packages/jool/compile#1.66#0.70#2.10
> make[1]: *** [package/Makefile:109: package/feeds/packages/jool/compile] Error 2
> make[1]: Leaving directory '/opt/openwrt/18.06'
> make: *** [/opt/openwrt/18.06/include/toplevel.mk:218: package/jool/compile] Fehler

**Comment by diizzyy** [comment]
@D-Albers 
It shouldn't use any other kernel except the one used in the toolchain, anything else is a bug and needs to be fixed.

**Comment by Leo-PL** [comment]
Also fails to build for me at Debian stable.
Also planned to create PR for this, 
@neheb @hnyman Builds for 18.06 branch fail without this patch.

**Comment by neheb** [comment]
As the initial author of the commit, I have no problem with this.

**Comment by Leo-PL** [comment]
Maybe this error shows up only after clean build is done. I recall that from my past experience

**Comment by SvenRoederer** [comment]
as noted in PR #8274 this error only comes up, when our buildbots running with CONFIG_AUTOREMOVE and CONFIG_BUILDBOT set to yes. without this, the build passes on the same machines.
So it might be a thing of starting with a clean build.

**Comment by SvenRoederer** [comment]
I just had our firmware built from scratch.

* OpenWrt18.06 (https://github.com/openwrt/openwrt/commit/a02809f61bf9fda0387d37bd05d0bcfe8397e25d) with jool (having **both patches applied**) based on recent packages-branch (https://github.com/openwrt/packages/commit/799c409d37719780b365fc0f65675ed7a3a561c4): **compiles fine**
* OpenWrt18.06 (https://github.com/openwrt/openwrt/commit/a02809f61bf9fda0387d37bd05d0bcfe8397e25d) with jool (having **only 1st patch applied**) based on recent packages-branch (https://github.com/openwrt/packages/commit/799c409d37719780b365fc0f65675ed7a3a561c4): **compiles fine** (https://buildbot.berlin.freifunk.net/builders/ramips-mt7620/builds/1154)
* OpenWrt18.06 (https://github.com/openwrt/openwrt/commit/a02809f61bf9fda0387d37bd05d0bcfe8397e25d) with jool **as in packages-branch**: **fails to compile**

@diizzyy What do you think about only having the 1st- patch added to 18.06?

**Comment by diizzyy** [comment]
@SvenRoederer 
I have no issues with it, just pointing out the fact that 4.19 for 18.X wont happen. :-)

**Comment by SvenRoederer** [comment]
@D-Albers please see https://github.com/openwrt/packages/commit/0d337e9d7186cb072a37f097ec653764f1f22a75 ; seems @danrl is not willing to maintain this package anymore

@NeoRaider , @neheb  as you committed here also, what do you think on merging this?

**Comment by neheb** [comment]
No problems here. I have no commit access so I can't do anything.

**Comment by D-Albers** [comment]
But what is the real problem at the moment?

The package seems to pull parts of the kernel of the build system and not from the target system. This seems to trigger also the problem with the 18.xx branch on build systems with an "up to date" kernel.

Are the patches really fixing the problem?

**Comment by neheb** [comment]
Yes. Look at the patches.

The second patch causing build failure makes no sense as it only adjusts a function name to not conflict with one present in 4.19.

**Comment by Leo-PL** [comment]
@D-Albers I'd update the PR to contain only 1st fix then, maybe @hnyman could merge the fix then.

**Comment by hnyman** [comment]
Yeah, it can be merged to fix the current failures, but like discussed above, it makes no sense to fix kernels that will never get into 18.06

(But like also discussed above, there may be some fundamental cross-compile problems somewhere in the jool compile process as the build host kernel version apparently affects things, at least in some cases.)

**Comment by neheb** [comment]
@hnyman A quick grep of 18.06 shows a mixture of 4.9 and 4.14. First patch is needed for 4.14.

@SvenRoederer that doesn't make sense. the second patch only renames a local function to not conflict with a similar one introduced upstream. can you get a make V=s log?

**Comment by neheb** [comment]
merging this as is. I misread @SvenRoederer 's comment. This is perfectly fine.

**Pull request merged**
