### PR TITLE
kea: update to 2.6.0

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: @rosysong
Compile tested: x86_64, generic HEAD (274b18d105)
Run tested: same, installed on test router

Description:

Update to 2.6.0 (STABLE)

Includes support for static classless routes.

cc: @stintel

### CODE REVIEW

**Comment by neheb** [comment]
I wonder if it's worth it to replace that god awful awk line with

```
conf_name=$(basename -- "${kea_config_file}")
conf_name="${conf_name%.*}"
```

**Comment by nmeyerhans** [comment]
This PR should probably flag the package maintainers as reviewers, but it doesn't seem to. Can you fix that?

Changes look good to me in general, except +1 to @nehab's suggestion about the awk change.

**Comment by hnyman** [comment]
both rosysong and hbl0307106015 should be dropped from package maintainers, as they have not been active (at all) for some 5 years.

**Review by stintel — APPROVED** [review]
While I agree the awk looks ugly and could be improved, this is not related to the bump, so LGTM.

My suggestion: merge this PR as is, submit improvement for conf_name upstream and then backport this patch in another PR.

**Comment by pprindeville** [comment]
> While I agree the awk looks ugly and could be improved, this is not related to the bump, so LGTM.
> 
> My suggestion: merge this PR as is, submit improvement for conf_name upstream and then backport this patch in another PR.

Sorry, just saw this.  I had updated the patch to include a fix that I submitted upstream as well:

https://github.com/isc-projects/kea/pull/142/commits

**Comment by pprindeville** [comment]
While I have everyone's attention, I have a question... I've taken the `init.d` script from `isc-dhcp` and converted it to generate a `kea.json` file... And it also has integrated support for priming `bind` with dynamic DNS updates driven by DHCP leases, as well as pushing static `MX`, `SRV`, and `CNAME` records synthesized from the `config` blocks.

How should I rewrite the `files/kea.init` to support this?  I guess I should also rewrite the script to use `kea-dhcp-ddns` instead of `rndc` and `nsupdate` calls.

**Comment by pprindeville** [comment]
@neheb @nmeyerhans Can you please approve and merge?  It's got support for classless-ipv4-routes which is nice.  Finally got added back in May.

**Pull request merged**
