### PR TITLE
Update to newest release and add basic uci support, and optional gpg …

### PR DESCRIPTION
**Pull request by oneru**
…support

Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>

### CODE REVIEW

**Comment by oneru** [comment]
This adds initial uci support for the luci module that will hopefully be put together this weekend. Feedback or corrections welcome.

**Comment by jmccrohan** [comment]
Hi @oneru,

It is good practice to prefix the commit message with the package you are affecting. For example:
```
fwknop: Update to newest release

Add basic UCI support
Add optional GPG support

Signed-off-by: Jonathan Bennett jbennett@incomsystems.biz
```

**Comment by oneru** [comment]
@jmccrohan That's sensible. I'll try to remember for the future.

**Comment by jmccrohan** [comment]
@oneru If you like, you can fix up the commit message and force push to your master branch. This will auto update the pull request and I'll merge it then.

Thanks,
Jon

**Comment by oneru** [comment]
@jmccrohan That appears to have fixed up the commit message. Thanks,

~Jonathan

**Comment by jmccrohan** [comment]
@oneru Merged. Thanks for your work!

**Pull request merged**
