### PR TITLE
reaver: Don't use PKG_USE_MIPS16:=0

### PR DESCRIPTION
**Pull request by neheb**
The initial error is gone with the latest GCC. Reaver does not use inline
assembly anymore.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @yousong 
Compile tested: ramips

### CODE REVIEW

**Comment by yousong** [comment]
Reaver as a utility with heavy use of cryptographic operations should have way better performance when mips16 is not used.  Compared to runtime memory footprint, I think performance is more important.

**Comment by neheb** [comment]
Ah. I thought this used OpenSSL.

**Comment by diizzyy** [comment]
Did you run-time test before submitting?

**Comment by neheb** [comment]
wash crashes upon receiving a packet with a bad FCS. I don't think this is a result of this PR.

In any case, I don't feel like testing this any longer.

**Pull request closed without merging**
