### PR TITLE
net/dnscrypt-proxy: update to 1.9.4

### PR DESCRIPTION
**Pull request by damianorenfer**
Maintainer: me
Compile tested: LEDE snapshot
Run tested: x86_64 on APU2C2

Description: simple package update

### CODE REVIEW

**Comment by anomeome** [comment]
I'm failing on the MD5 sum of the downloaded file from all mirrors.

**Comment by damianorenfer** [comment]
Is your OpenWrt build system / SDK up to date?

**Comment by anomeome** [comment]
Yes, everything is up to date. Just noticed that with 4 different download attempts, it generated 4 different hash values. I will do it manually and see if I can find out where it is going wrong.

**Comment by anomeome** [comment]
Okay, don't know what that was about. I had done a dirclean just yesterday and had not seen anything that would warrant same today. Something borked in my toolchain from yesterdays build I guess, sorry for the noise.

**Pull request merged**
