### PR TITLE
transmission: Fix tracker issue with some firewalls

### PR DESCRIPTION
**Pull request by neheb**
Some firewalls mandate a minimum size of 4k for SYN packets, which
transmission does not do by default. Upstream issue here:

https://github.com/transmission/transmission/issues/964

Cleanup:

Got rid of transmission-cli. -cli is deprecated and replaced by -remote.

Fixed license info.

Removed two unnecessary patches.

Ran shell script through shellcheck.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: me
Compile tested: mvebu

Possibly related: https://github.com/openwrt/packages/issues/9487

@patrakov can you test?

### CODE REVIEW

**Comment by neheb** [comment]
Before anyone asks, I tried to convert to CMake. Filesize went up massively. It seems CMake statically links everything.

**Comment by mstorchak** [comment]
I personally have no objections on removal of -cli, but it's a cmdline bittorrent client, see https://github.com/transmission/transmission/blob/5a5fe7d7fe22e78af82c6cf8b32ed6894813e932/cli/transmission-cli.1#L41, and -remote is a remote control for -daemon, it can't download torrents by itself.

**Comment by mstorchak** [comment]
Also, -create, -edit and -show might still be useful tools (again, this is not my case).

**Comment by patrakov** [comment]
As far as I can see, the only change that could, in theory, be relevant to #9487 is about the sysctl. I applied it to my local system, ran `sysctl -p /etc/sysctl.d/20-transmission.conf`, restarted Transmission, and added a torrent file for Endless OS. Result: issue #9487 is still there.

**Comment by neheb** [comment]
@mstorchak https://github.com/transmission/transmission/commit/950387ab5a443629598f93c057f41150707866ab

**Comment by neheb** [comment]
Added back -cli. Maybe when 3.0 hits I'll remove it.

**Pull request merged**
