### PR TITLE
zerotier: update to version 1.2.8

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>

Maintainer: me
Compile tested: v17.01.4, ramips-mt7620, nexx wt3020
Run tested: software starts and connects to server

Description:
A simple version update.

### CODE REVIEW

**Comment by mwarning** [comment]
testing in progress

**Comment by diizzyy** [comment]
Hmm... Could you possibly use codeload instead?
https://github.com/openwrt/packages/commit/3bf0e64655933235404dc57541433fe520001e36

Does -flto and/or -gc-sections reduce the overall size?
https://github.com/openwrt/openwrt/commit/3e93df07071e79bb8cf1d8fb7fd1539c87bdc3a4

**Comment by mwarning** [comment]
@diizzyy I will give it a try tomorrow.

**Comment by mwarning** [comment]
@diizzyy I tried this, but without success:
```
PKG_VERSION:=1.2.8
PKG_SOURCE_URL=https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/$(PKG_VERSION)
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
```
Using the links directly is working:
```
wget https://codeload.github.com/mstorsjo/fdk-aac/tar.gz/v0.1.6
wget https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/1.2.8
```
Can you help me here?

**Comment by mwarning** [comment]
I tried the additional compiler/linker options. It shaved 4KB from the package (390KB vs 394KB). Is it worth the effort?

**Comment by mwarning** [comment]
Anyway, what does the '?' in PKG_SOURCE_URL?

**Comment by mwarning** [comment]
@diizzyy I chose PKG_RELEASE 2 because I had a release with package number 1 already: https://github.com/mwarning/zerotier-openwrt/releases/tag/v1.2.8_1

**Pull request merged**
