### PR TITLE
stunnel: Update to 5.36, use pthreads and SSP.

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @mhaas

Compile tested: ar71xx, mikrotik 750gl, r1122
Run tested: ar71xx, mikrotik 750gl, r1122

Description:

Updates stunnel to 5.36, changes it from using forking to pthreads and
enables SSP linking.

Regarding pthreads vs forking, http://blog.haproxy.com/2011/09/16/benchmarking_ssl_performance/
SSP is short for Stack Smashing Protector and you can read about it here: http://wiki.osdev.org/Stack_Smashing_Protector

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
All stunnel pull reqs (from others) have been setting for months and the maintainer doesn't seem to be interested. Who should I ping about this?

**Comment by diizzyy** [comment]
Hi, I'm fine with taking over. 
As for pthreads, it's included in musl nowdays which both OpenWRT and LEDE have switched to so no overhead.

**Comment by diizzyy** [comment]
@thess Ok?

**Comment by thess** [comment]
Fine with me - change the PKG_MAINTAINER to be you, rebase (squash) the commit and amend the comment to add that fact. I'll merge it if no-one objects.

**Comment by diizzyy** [comment]
That should be good now.

**Pull request merged**
