### PR TITLE
python3: Update to 3.11.3, refresh/redo patches

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me
Compile tested: armvirt-32/armvirt-64/malta-be/x86-generic/x86-64, 2023-05-15 snapshot sdk
Run tested: armvirt-32/armvirt-64/malta-be/x86-generic/x86-64 (qemu), 2023-05-15 snapshot

Description:
* **[python3: Remove --without-pymalloc](https://github.com/openwrt/packages/pull/21030/commits/61f1a970e829b750036d4f0a5ef1d479f148abc2)**

  `--without-pymalloc` was added in https://github.com/openwrt/packages/commit/7bf1ae65a89e380ce20ef5ab13b1a7276d6f7047 because leaving it enabled added an "m" flag/suffix to file names.

  This flag/suffix was [removed in Python 3.8][A1], so disabling pymalloc is no longer necessary.

  [A1]: https://docs.python.org/3.8/whatsnew/3.8.html#build-and-c-api-changes

* **[python3: Fix \_\_pycache\_\_ files included in python3-light](https://github.com/openwrt/packages/pull/21030/commits/4d7693e22f781a758f569e746f7c11b3b0de1b86)**

  003-do-not-run-distutils-tests.patch was removed in https://github.com/openwrt/packages/commit/4e05541782edeb06b51d691dadf52648df24c940. This patch stopped `make install` from, among other things, running compileall.

  When this patch was removed, `make install` ran compileall as normal and created bytecode files in \_\_pycache\_\_ directories. These files were then packaged in python3-light.

  This adds a patch to stop compileall from being run during `make install`.

  Fixes: https://github.com/openwrt/packages/commit/4e05541782edeb06b51d691dadf52648df24c940 ("python3: bump to version 3.10.0")

* **[python3: Fix readelf program name not replaced in _sysconfigdata.py](https://github.com/openwrt/packages/pull/21030/commits/840247e390cfe87b62aecc9a2eff2836d6b35c55)**

  The Makefile lines to add `READELF` to `TARGET_CONFIGURE_OPTS` was removed in https://github.com/openwrt/packages/commit/4e05541782edeb06b51d691dadf52648df24c940.

  Without setting `READELF`, configure finds the symlink to `$(TARGET_CROSS)readelf` (e.g. `arm-openwrt-linux-readelf`) instead of `$(TARGET_CROSS)readelf` (e.g. `arm-openwrt-linux-muslgnueabi-readelf`).

  This leads to the symlink name being saved to _sysconfigdata.py, and so the readelf name is not replaced correctly (in `Py3Package/python3-base/install`).

  This restores the removed Makefile lines.

  Fixes: https://github.com/openwrt/packages/commit/4e05541782edeb06b51d691dadf52648df24c940 ("python3: bump to version 3.10.0")

* **[python3: Fix race condition when doing parallel builds](https://github.com/openwrt/packages/pull/21030/commits/c244106c7aaec1c6a211c2589049c5a3b5ab5c2a)**

  When doing parallel builds, host Python can install the python3 symlink before the Python standard library is installed completely.

  When this occurs, it is possible for other packages to detect the python3 symlink and try to use host Python before it is fully installed.

  This adds a patch to make `commoninstall` (where the standard library is installed) a prerequisite of `bininstall` (where the python3 symlink is installed), so that `commoninstall` is fully completed before `bininstall` begins.

  Patch has been submitted upstream: https://github.com/python/cpython/pull/104693

  Fixes: https://github.com/openwrt/packages/issues/19241

* **[python3: Fix multiarch/local paths added when building host Python](https://github.com/openwrt/packages/pull/21030/commits/9abd97457888c9b26562aad422d4f1db3bd3eff5)**

  By default, the Python build process will add /usr/local/{lib,include}, and multiarch paths (e.g. /usr/{lib,include}/x86_64-linux-gnu) if building on Debian/Ubuntu, to its library and includes paths.

  006-remove-multi-arch-and-local-paths.patch was added in https://github.com/openwrt/packages/commit/84202f17e1aac6faf66b8d186f7c5c62b6f72ffb to stop the Python build process from adding these paths.

  006-remove-multi-arch-and-local-paths.patch was removed in https://github.com/openwrt/packages/commit/48277ec9158151763239461c6f60808e38a99c2f.

  006-do-not-add-multiarch-paths-when-cross-compiling.patch was added in https://github.com/openwrt/packages/commit/0c8b0b0bf727a57b0138a1425d2f32786dddd146 to stop the Python build process from adding these paths for target Python.

  These paths are still added by the Python build process when building host Python.

  This replaces the cross-compiling-only patch with the original patch, renamed slightly and adapted for Python 3.10.

  Fixes: https://github.com/openwrt/packages/commit/48277ec9158151763239461c6f60808e38a99c2f ("python3: bump to version 3.8")

* **[python3: Fix uuid module not compiled for host Python](https://github.com/openwrt/packages/pull/21030/commits/4f68711d222d754d4558fb1bca1e4361c624b5b3)**

  This adds `$(STAGING_DIR_HOST)/include/e2fsprogs` to `HOST_CFLAGS` and `HOST_CPPFLAGS` so that configure can find uuid/uuid.h.

* **[python3: Fix hashlib module not compiled for host Python](https://github.com/openwrt/packages/pull/21030/commits/81835e1a3beb2f0ae231ea88e7d2c44c1f2341ff)**

  026-openssl-feature-flags.patch and 028-host-python-support-ssl-with-libressl.patch were removed in https://github.com/openwrt/packages/commit/4ecd9d67e90651a8e93760bf0b5771f7057c74a8 to [fix the ssl module after libressl was upgraded to 3.7.0][B1].

  However, the cause of the ssl module build failure was only 028-host-python-support-ssl-with-libressl.patch.

  Removing 026-openssl-feature-flags.patch caused a build failure for the hashlib module.

  This restores 026-openssl-feature-flags.patch with an [updated version of the patch from OpenBSD][B2].

  [B1]: https://github.com/openwrt/packages/issues/20107
  [B2]: https://github.com/openbsd/ports/blob/26a04435bf2a09dcbe22b718bfee08997617a906/lang/python/3.10/patches/patch-Modules__hashopenssl_c

  Fixes: https://github.com/openwrt/packages/commit/4ecd9d67e90651a8e93760bf0b5771f7057c74a8 ("python3: fix ssl support by removing libressl patches")

* **[python3: Update to 3.11.3, refresh/redo patches](https://github.com/openwrt/packages/pull/21030/commits/df2d06a35d1497195bc51ee3c3672df89c82bee1)**

  * Removed patches:

    * 001-enable-zlib.patch: zlib module should be enabled automatically

    * 007-distutils-do-not-adjust-path.patch: Not necessary since we process shebang lines for all scripts (in python3-package.mk)

    * 030-bpo-43112-detect-musl-as-a-separate-SOABI-GH-24502.patch: Already merged

  * Move configure vars from config.site back into Makefile

    Centralizing all build information into one file makes it easier to maintain

  * No longer set `ac_cv_header_uuid_h=yes` as configure should detect libuuid

  * Order configure args by `enable-`/`disable-`/`with-`/`without-`, then alphabetically

  * Set `ac_cv_working_openssl_hashlib=yes` for host configure to bypass the OpenSSL API tests with LibreSSL

  * Use the default `Host/Compile` recipe instead of picking out specific targets to make

### CODE REVIEW

**Comment by jefferyto** [comment]
Changes:
* Added commit to fix readelf program name not replaced in _sysconfigdata.py
* Updated commit message with note about removing `ac_cv_header_uuid_h=yes`

**Comment by jefferyto** [comment]
Changes:
* Use default `Host/Compile`
* Rebased on master

**Comment by jefferyto** [comment]
Changes:
* Added commit to fix #19241 (python3: Fix race condition when doing parallel builds)

Just to add: fixes are in separate commits so that they can be cherry-picked into 22.03 when I do the python3 package update after this PR.

**Comment by jefferyto** [comment]
Changes:
* Updated commit message for "python3: Fix race condition when doing parallel builds" to mention that the patch has been submitted upstream

**Review by commodo — APPROVED** [review]

**Comment by jefferyto** [comment]
Marking this PR as draft as I think I need to fit in one more fix...

I believe there is a Python/libressl issue that is causing the hashlib module to not build for host Python (when building from full buildroot, not sdk), which is causing poetry-core to fail to build, causing the issue mentioned in #20994

**Comment by jefferyto** [comment]
Changes:
* Renamed patch in "python3: Fix race condition when doing parallel builds"
* Added commit "python3: Fix hashlib module not compiled for host Python"
* Added setting `ac_cv_working_openssl_hashlib=yes` in `HOST_CONFIGURE_VARS` (python3: Update to 3.11.3, refresh/redo patches) and added note for this change in commit message
* Rebased on master

**Comment by 1715173329** [comment]
hmmm the poetry module still seems broken when compiling from source.

build log:
```
cd "/home/builder/oprk-master/build_dir/target-aarch64_generic_musl/pypi/dnspython-2.3.0" && CC="aarch64-openwrt-linux-musl-gcc" CCSHARED="aarch64-openwrt-linux-musl-gcc -DPIC -fPIC" CXX="aarch64-openwrt-linux-musl-g++" LD="aarch64-openwrt-linux-musl-gcc" LDSHARED="aarch64-openwrt-linux-musl-gcc -shared" CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/builder/oprk-master/build_dir/target-aarch64_generic_musl/pypi/dnspython-2.3.0=dnspython-2.3.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CPPFLAGS="-I/home/builder/oprk-master/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/usr/include -I/home/builder/oprk-master/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/include/fortify -I/home/builder/oprk-master/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/include -I/home/builder/oprk-master/staging_dir/target-aarch64_generic_musl/usr/include/python3.11" LDFLAGS="-L/home/builder/oprk-master/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/usr/lib -L/home/builder/oprk-master/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/lib -znow -zrelro -lpython3.11" _PYTHON_HOST_PLATFORM="linux-aarch64" PYTHONPATH="/home/builder/oprk-master/staging_dir/target-aarch64_generic_musl/usr/lib/python3.11:/home/builder/oprk-master/staging_dir/target-aarch64_generic_musl//usr/lib/python3.11/site-packages:/home/builder/oprk-master/build_dir/target-aarch64_generic_musl/pypi/dnspython-2.3.0/ipkg-install//usr/lib/python3.11/site-packages" PYTHONDONTWRITEBYTECODE=1 _python_sysroot="/home/builder/oprk-master/staging_dir/target-aarch64_generic_musl" _python_prefix="/usr" _python_exec_prefix="/usr"    /home/builder/oprk-master/staging_dir/hostpkg/bin/python3.11  -m build --no-isolation --outdir "/home/builder/oprk-master/build_dir/target-aarch64_generic_musl/pypi/dnspython-2.3.0/"/openwrt-build --wheel   "/home/builder/oprk-master/build_dir/target-aarch64_generic_musl/pypi/dnspython-2.3.0/" 
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/home/builder/oprk-master/staging_dir/hostpkg/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/builder/oprk-master/staging_dir/hostpkg/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/builder/oprk-master/staging_dir/target-aarch64_generic_musl/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'

ERROR Backend 'poetry.core.masonry.api' is not available.
make[2]: *** [Makefile:45: /home/builder/oprk-master/build_dir/target-aarch64_generic_musl/pypi/dnspython-2.3.0/.built] Error 1
make[2]: Leaving directory '/home/builder/oprk-master/feeds/packages/lang/python/python-dns'
time: package/feeds/packages/python-dns/compile#0.38#0.05#1.31
    ERROR: package/feeds/packages/python-dns failed to build.
make[1]: *** [package/Makefile:120: package/feeds/packages/python-dns/compile] Error 1
make[1]: Leaving directory '/home/builder/oprk-master'
make: *** [/home/builder/oprk-master/include/toplevel.mk:231: package/python-dns/compile] Error 2
```

base rev: 1c074ac9172e0f472d2049c5272ff84218384c75
packages rev: 574d43fca627bdaee03f43a1be10ba35dd9dd26d
config:
```
CONFIG_TARGET_rockchip=y
CONFIG_TARGET_rockchip_armv8=y
CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r2s=y
CONFIG_LINUX_6_1=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_IDEA=y
CONFIG_OPENSSL_WITH_MDC2=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SEED=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENSSL_WITH_WHIRLPOOL=y
CONFIG_PACKAGE_libbz2=y
CONFIG_PACKAGE_libffi=y
CONFIG_PACKAGE_libgdbm=y
CONFIG_PACKAGE_liblzma=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libpython3=y
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_libsqlite3=y
CONFIG_PACKAGE_python3=y
CONFIG_PACKAGE_python3-asyncio=y
CONFIG_PACKAGE_python3-base=y
CONFIG_PACKAGE_python3-cgi=y
CONFIG_PACKAGE_python3-cgitb=y
CONFIG_PACKAGE_python3-codecs=y
CONFIG_PACKAGE_python3-ctypes=y
CONFIG_PACKAGE_python3-dbm=y
CONFIG_PACKAGE_python3-decimal=y
CONFIG_PACKAGE_python3-distutils=y
CONFIG_PACKAGE_python3-dns=y
CONFIG_PACKAGE_python3-email=y
CONFIG_PACKAGE_python3-light=y
CONFIG_PACKAGE_python3-logging=y
CONFIG_PACKAGE_python3-lzma=y
CONFIG_PACKAGE_python3-multiprocessing=y
CONFIG_PACKAGE_python3-ncurses=y
CONFIG_PACKAGE_python3-openssl=y
CONFIG_PACKAGE_python3-pydoc=y
CONFIG_PACKAGE_python3-readline=y
CONFIG_PACKAGE_python3-sqlite3=y
CONFIG_PACKAGE_python3-unittest=y
CONFIG_PACKAGE_python3-urllib=y
CONFIG_PACKAGE_python3-uuid=y
CONFIG_PACKAGE_python3-xml=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_zlib=y
CONFIG_SQLITE3_COLUMN_METADATA=y
CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
CONFIG_SQLITE3_FTS3=y
CONFIG_SQLITE3_FTS4=y
CONFIG_SQLITE3_FTS5=y
CONFIG_SQLITE3_RTREE=y
CONFIG_TESTING_KERNEL=y
```

**Comment by jefferyto** [comment]
> hmmm the poetry module still seems broken when compiling from source.

Yes the fix is https://github.com/openwrt/openwrt/pull/12710. I have also sent it to the mailing list now: https://patchwork.ozlabs.org/project/openwrt/patch/20230531135834.2150795-1-jeffery.to@gmail.com/

If it's still not merged in a week or so I'll do a special case fix for Python packages, but this is really a general issue.

**Comment by 1715173329** [comment]
Thank you for the fix! And sorry I asked a stupid question (didn't check the existing issues first...)

**Pull request merged**
