### PR TITLE
openblas: enable ARM-specific optimizations

### PR DESCRIPTION
**Pull request by krant**
Maintainer: @commodo 
Run tested: arm_cortex-a9+neon, Linksys WRT3200ACM, master branch

### CODE REVIEW

**Comment by commodo** [comment]
PKG_RELEASE:=1 needs a bump

rest looks good

**Comment by BKPepe** [comment]
Commit description is missing - why do we need to have this change, what was the reason, how this is improvement, etc.

**Comment by krant** [comment]
@commodo nice catch, done

**Comment by krant** [comment]
@BKPepe look at the summary - it's all there

**Comment by commodo** [comment]
> @BKPepe look at the summary - it's all there

so a commit description is nice to have :)
as a general overview of that the change does;

OpenBLAS has per-processor (well, per-family processor) optimizations in assembly;
but they need to be enabled specifically;
i did not bother to do it for each family;
when people want them, they can enable them (like in this patchset)

**Comment by krant** [comment]
@commodo thanks for being constructive. Commit has been updated.

**Review by BKPepe — APPROVED** [review]

**Pull request merged**
