### PR TITLE
net/subversion: update to 1.9.5

### PR DESCRIPTION
**Pull request by val-kulkov**
Maintainer: Val Kulkov <val.kulkov@gmail.com> replaces Donald Rumata <donald.rumata@gmail.com>
Compile tested: ar17xx
Run tested: ar71xx

Description: update subversion from 1.9.4 to 1.9.5

Signed-off-by: Val Kulkov <val.kulkov@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
It is otherwise ok, but the commit title should not be just "description:".  Please amend it.

The title should be something like "subversion: update to 1.9.5"

**Comment by val-kulkov** [comment]
@hnyman : I am not completely sure that I understood your suggestion. I merged the "Description:" line with the line that followed. Now there is only one line, "Description: update subversion from 1.9.4 to 1.9.5", and I hope that this is what you wanted me to do.

I thought that the "Description:" is a subheading, and the long description of the commit is supposed to follow as multiline comment after the "Description:" subheading. I thought that the title of the commit is the one that already appears at the very top, in this case: "net/subversion: update to 1.9.5".

Please let me know if any further edits are necessary. Thank you.

**Comment by hnyman** [comment]
> Now there is only one line, "Description: update subversion from 1.9.4 to 1.9.5",

That sounds correct. The first line of the commit message is the title that is visible in the commit log:
https://github.com/openwrt/packages/commits/master

But I still see just the old "Description:" here. 
You need to push your new commit here to make us others see it. (You likely have it now just in your local repo)

Use ``` git push -f ``` to overwrite the current (previous) commit here.

**Comment by val-kulkov** [comment]
@hnyman : you are right, I made a silly mistake in the commit message itself. All fixed now. Thank you for your patience!

**Pull request merged**
