### PR TITLE
nginx: Add support for NJS module

### PR DESCRIPTION
**Pull request by Ansuel**
Add support for NJS module. Various patch are required to make this
module correctly compile with the required library mainly related on
detecting config flags.

In doing this, improve feature patch on nginx core.

It's not needed to bump PKG_RELEASE as we are not changing anything in the main package and just introducing a new module.

### CODE REVIEW

**Comment by Ansuel** [comment]
@QAQBytes please test

**Comment by Ansuel** [comment]
@neheb Do you have any idea why somehow the libxslt is not getting included? Can't find a way to repro this correctly...

**Comment by rockdrilla** [comment]
@Ansuel you may try out defining env variable `NJS_LIBXSLT=NO` to build NJS without XML support at all which is fine for disk-constrained environments - no libxml2, no libicu and so on.

**Comment by Ansuel** [comment]
@rockdrilla that is an idea and yes I can consider that. But still it's strange.

**Comment by Ansuel** [comment]
Curious if it's a limitation of CI... lets see how it goes on buildbot and I will revert if nginx is broken.

**Comment by hnyman** [comment]
> lets see how it goes on buildbot and I will revert if nginx is broken.

It is broken in buildbot.

E.g. https://downloads.openwrt.org/snapshots/faillogs/mips_mips32/packages/nginx/full/compile.txt

```
checking for zlib library ... found
checking for libxslt ... not found
checking for libxslt in /usr/local/ ... not found
checking for libxslt in /usr/pkg/ ... not found
checking for libxslt in /opt/local/ ... not found

./configure: error: the HTTP XSLT module requires the libxml2/libxslt
libraries. You can either do not enable the module or install the libraries.
```

**Comment by Ansuel** [comment]
I know I need to check if I manage to repro (still no idea how this is broken only in CI and Buildbot) or revert it...

**Comment by 534002646** [comment]
> 我知道我需要检查我是否能够重现（仍然不知道这是如何在 CI 和 Buildbot 中被破坏的）或者恢复它......

Thank you for your efforts, please how long will it take to use this module？

**Comment by 534002646** [comment]
> I know I need to check if I manage to repro (still no idea how this is broken only in CI and Buildbot) or revert it...

Thank you for your efforts, please how long will it take to use this module

**Pull request merged**
