### PR TITLE
adblock: update 1.5.2

### PR DESCRIPTION
**Pull request by dibdot**
Maintainer: me
Compile tested: no
Run tested: yes, LEDE r1270

Description:
* turris omnia compatibility fix (#3340)

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by gendouhydeist** [comment]
Just updated today and I got an error getting empty downloads.

`root@lede:~# adblock-update.sh
adblock[8373] info : domain adblock processing started (1.5.2, r2024, 28.10.2016 12:06:14)
adblock[8373] info : Restricted mode enabled
adblock[8373] info : backup/restore will be disabled
adblock[8373] info : => processing source 'adaway'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'blacklist'
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'disconnect'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'dshield'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'feodo'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'hphosts'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'malware'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'malwarelist'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'openphish'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'palevo'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'ransomware'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'securemecca'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'spam404'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'sysctl'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'whocares'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'winspy'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'winhelp'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'yoyo'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
adblock[8373] info : => processing source 'zeus'
adblock[8373] info :    no online timestamp
adblock[8373] info :    empty source download, skipped
ls: /tmp/dnsmasq.d/adb_list*: No such file or directory
adblock[8373] info : block lists with overall 0 domains are still valid, no update required
adblock[8373] info : firewall statistics (IPv4/IPv6): 0%/0% of all packets in prerouting chain are ad related & blocked
adblock[8373] info : domain adblock processing finished successfully (1.5.2, r2024, 28.10.2016 12:06:17)`

**Comment by dibdot** [comment]
Which download utility did you use? Probably you're still trying to use uclient-fetch ... and your setup seems somewhat broken. Please use the normal wget package (with ssl support!) instead.

**Comment by gendouhydeist** [comment]
root@lede:~# opkg list-installed | grep wget
wget - 1.18-2

I've just check the buildroot as well it was there also.
This build was from the latest trunk.

**Comment by dibdot** [comment]
OK, what does 'which wget' return?

**Comment by dibdot** [comment]
please check if adblock 1.5.3 works for you - thanks!

**Pull request merged**
