### PR TITLE
collectd: update to 5.12.0

### PR DESCRIPTION
**Pull request by hnyman**
Update collectd to version 5.12.0.
* refresh patches
* remove upstreamed patch (920-...)

Maintainer: me 
Compile tested: master, ipq806x/R7800
Run tested: master, ipq806x/R7800

Description:
Normal version update, nothing really special.

(Doing update via PR to test the new github actions based testing.)

### CODE REVIEW

**Comment by hnyman** [comment]
CircleCI spotted an error at the netlink module:

Reference to upstream bug & PR: 
https://github.com/collectd/collectd/pull/3569/files

**Comment by hnyman** [comment]
@aparcar 
Surprisingly, CircleCI spotted and actual error in the netlink module's code, while the Github actions based test pass.

Sure, collectd has one of the most complex package structures with lots of selectable add-on module packages and lots of dependencies, and the failure is related to an optional module not select by default. 
But why does CircleCI find it while the new Github actions do not ?

**Comment by aparcar** [comment]
@hnyman for the last 6 days the Docker containers [weren't updated](https://gitlab.com/openwrt/docker/-/pipelines) due to [failing packge builds](https://downloads.openwrt.org/snapshots/faillogs//x86_64/base/). I'm guessing the GitLab CI uses an outdated container which wasn't affected by the problem introduced in the last 6 days. My guess is the reason tools like `e2fsprogs` fail is the same as for `collectd`. I'm trying to find the problem in `openwrt.git`.

**Comment by hnyman** [comment]
Hmm. I think that it might be the opposite here.

There is a genuine problem in one optional module,. Simple C error of an undefined error code. I can produce that also locally. I will patch that away with the upstream PR's patch.

Circleci found the problem, while the new stuff happily overlooked that. And that is my worry. (The fakeroot and related build system stuff is separate, as this is simple C error)

**Comment by aparcar** [comment]
I found the error! I initially set the GitHub action `IGNORE_ERRORS` to default to ignore errors, just like the buildbot does. Overwriting that via "" doesn't work, as then the default kicks in. Now it doesn't ignore anything unless actively set.

Please rebase this PR to see if the new CI now detects the error.

**Comment by hnyman** [comment]
@aparcar 
Looks like your fix to the new testing works ok:
The test builds properly failed and I received a summary error message by email:

```
Run failed for collectd512 (cb5cd0e)

Repository: openwrt/packages
Workflow: Test Build
Duration: 13 minutes and 11.0 seconds
Finished: 2020-09-07 14:42:20 UTC

View results: https://github.com/openwrt/packages/actions/runs/243175031

Jobs:
  * aarch64_generic build failed (1 annotation)
  * arc_arc700 build failed (1 annotation)
  * arm_cortex-a15_neon-vfpv4 build failed (1 annotation)
  * arm_cortex-a9_neon build failed (1 annotation)
  * arm_cortex-a9_vfpv3-d16 build failed (1 annotation)
  * i386_pentium4 build failed (1 annotation)
  * mips_24kc build failed (1 annotation)
  * powerpc_464fp build failed (1 annotation)
  * powerpc_8540 build failed (1 annotation)
  * x86_64 build failed (1 annotation)

-- 
You are receiving this because this workflow ran on your branch.
```

I will next apply the upstream fix, and will see if the testing is happy with that.

**Comment by hnyman** [comment]
@aparcar 
Sadly I was maybe too eager to be happy earlier.
Now the reverse happens:  circleCI properly passes the build, while the new testing mysteriously fails due to libcxx things:
```
2020-09-07T15:14:59.0090480Z make -C /home/build/openwrt/package/libs/libcxx prepare
2020-09-07T15:14:59.0114181Z make[4]: *** /home/build/openwrt/package/libs/libcxx: No such file or directory.  Stop.
2020-09-07T15:14:59.0119520Z make[3]: *** [Makefile:75: /home/build/openwrt/build_dir/target-aarch64_generic_musl/libcxxabi-10.0.0.src/.prepared_60d7c964ddc63086705846cc1e842cb2_18f1e190c5d53547fed41a3eaa76e9e9] Error 2
2020-09-07T15:14:59.0119954Z make[3]: Leaving directory '/home/build/openwrt/feeds/base/package/libs/libcxxabi'
2020-09-07T15:14:59.0122990Z time: package/feeds/base/libcxxabi/compile#0.25#0.06#0.87
2020-09-07T15:14:59.0133158Z make[2]: *** [package/Makefile:113: package/feeds/base/libcxxabi/compile] Error 2
2020-09-07T15:14:59.0133561Z make[2]: *** Waiting for unfinished jobs....
```

image


I will merge this collectd PR, as the libcxx things look strange. That is probably what you referenced a few messages ago with "the problem introduced in the last 6 days".  

(Ps. To me it looks like the util-linux fix related to libmagic should fix many packages including "uuid" which then caused quite many others to fail. Once the buildbots do phase2 packages round with updated phase1 SDK, things will stablilize to a large extent. (Like already with aarch64_generic etc., but even there the libcxx remains in faillogs))

**Pull request merged**
