### PR TITLE
python-packages: initial version 1.0

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: me / @yousong
Compile tested: (x86/64, LEDE)
Run tested: (qemu-system-x86_64 2.6.1)

Description:

The following text is taken from package README.md

> This package allows users to package python modules without creating package
> Makefiles for each individual package and their dependencies.  It provides a
> way making packaging python packages faster and may also help the process of
> developing Makefiles for new python packages
> 
> This is a raw DEVEL only package.  It may entail a lot of implementation
> details and you may need to resolve target dependencies and package details
> on your own
> 
> - Third party python packages may depend on features not included in e.g.
>   python-light
> - Some python modules may require host install of another module to progress,
>   e.g. target cryptography requires host cffi
> - Some python modules have external C library dependencies, e.g. pyOpenSSL
>   requires openssl libs
> - Some packages may have an autoconf configure script whose arguments we
>   cannot control with pip and has to be passed (hacked) by overriding some
>   environment variables
> 
> ## How it works
> 
> 1. Install host modules required for building target modules
> 2. Install each target module to separate directories
> 3. Install another copy of modules for cleanup purposes to make list of
>    installed files to be removed from target modules installed in step 2
> 
> Why should it be so
> 
> 1. Installing target cryptography requires host installation of cffi module
> 2. cryptography requires setuptools and pip will install its own copy with
>    --ignore-installed.  When PACKAGE_python-setuptools is also selected, opkg
>    will complain of data file clashes if it was not removed here.

### CODE REVIEW

**Comment by yousong** [comment]
Ping current maintainer of python and python-pip ;) @commodo

**Comment by yousong** [comment]
Thanks @commodo 

Changes v2 <- v1

 - add `--no-compile` to install option of pip to avoid packing up `.pyc` made by host python

**Comment by hnyman** [comment]
I think that the PKG_RELEASE should be increased for the existing python stuff that is modified. At the first glance at least python-pip is modified and also the main python, right?

**Comment by yousong** [comment]
Hi @hnyman , I think `PKG_RELEASE` does not need to change in this case as the diff is expected to cause NO change in the final content of relevant packages.

**Comment by yousong** [comment]
v3 <- v2

 - A few wording changes

**Comment by yousong** [comment]
v4 <- v3

 - Fix typo on version pycrypto in README.md from 2.7.1 to 2.7a1

I am going to do the merge a while later if there are no further comments ;)

**Pull request merged**
