### PR TITLE
crtmpserver: Updated deprecated patch to include 1.0.2

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @heil 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
Build failure is unrelated to this pull request. It's related to the previous.

Fix is on the OpenWrt mailing list.

**Comment by cshoredaniel** [comment]
+run tested

**Comment by neheb** [comment]
On this one I will say no. It's a package from 2012 with probably very few users if any. @diizzyy has called for deletion as there are other solutions. See: https://github.com/openwrt/packages/pull/7512#issuecomment-448754154

**Comment by cshoredaniel** [comment]
Another one that should be marked abandoned or something other than tainting the way the rest of repo is treated.

**Comment by neheb** [comment]
Closing as this is no longer valid.

**Pull request closed without merging**
