### PR TITLE
stubby: remove libidn2 and libunwind dependencies

### PR DESCRIPTION
**Pull request by neheb**
There's no good way to get rid of these, so just delete the cmake files.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jonathanunderwood 
Compile tested: ath79

ping @rsalvaterra

### CODE REVIEW

**Comment by rsalvaterra** [comment]
Ah, this is the annoying issue you mentioned, right?

**Comment by rsalvaterra** [comment]
Looks good to me. Run-tested on the Redmi AC2100. Thanks!

**Comment by jonathanunderwood** [comment]
@neheb this is entirely the wrong way to fix this issue. There are legitimate reasons for building against shared libs here. See the GetDNS Makefile for the correct way to handle this specific issue.

**Comment by jonathanunderwood** [comment]
Note: no package maintainer approval, once again, @neheb , with the result that an incorrect fix has been merged.

**Comment by jow-** [comment]
> PRs welcome.

Normally I would agree but merging allegedly wrong stuff into a foreign package without the maintainers consent and then stating "PRs welcome" when the maintainer complains is just not the right way to go about it. You're essentially forcing other people to invest time in solving issues that you introduced. That is just wrong.

**Comment by neheb** [comment]
Sure. Mistake on my part.

**Pull request merged**
