### PR TITLE
Enable collectd nut plugin for 15.05

### PR DESCRIPTION
**Pull request by dwmw2**

### CODE REVIEW

**Comment by sbyx** [comment]
@cyanidium please review.

**Comment by cyanidium** [comment]
Thanks for tagging me, I'm looking at it now. We should at least bump PKG_RELEASE for this, but I want to play around with InstallDev before we merge. I'm not opposed to the idea of building --with-dev, but the way it's written appears to install the dev files all the time, which would be unnecessary bloat for most people. If collectd needs the dev files at runtime then I would prefer to use another config switch.

I'll get smart of InstallDev and have another look.

**Comment by dwmw2** [comment]
Hm, I thought it only installed the dev files in the local buildroot, not on the target system itself? Should we worry about that as 'bloat'?

**Comment by cyanidium** [comment]
It does exactly what you described, so there's no bloat. I just wasn't familiar with how InstallDev worked, which probably explains why it wasn't in the package from the start.

**Comment by dwmw2** [comment]
Thanks. My other outstanding question is about the init scripts. In the AA days, the init script for nut would generate ups.conf and upsd.users files in tmpfs automatically from the uci config. Now that no longer works and we have to have a writeable root file system. Was that a deliberate change, or just an artifact of the old nut package dying off with the old package repository, and then being added anew to git?

**Comment by cyanidium** [comment]
I did look at the old init script when I ported the package across, but with overlayfs you can modify the standard config files in the /etc/nut folder anyway and since 99% of the support available for nut is using those files I would prefer to keep the universal solution. I would be happy to maintain a UCI implementation if someone submitted a pull request, but it would need documentation as well as code and should still allow universal config files to be used. In the meantime I'll add it to my TODO list, but it's not a priority for me at the moment.

**Comment by sbyx** [comment]
I'm closing this then. Please reopen / comment if this shall be applied anyway.

**Comment by dwmw2** [comment]
Oops, didn't mean to delete it. There's one commit left, to actually enable the collectd nut plugin.

As for the nut config — I can certainly live with having to edit the config file manually. I just wanted to check if the uci config was removed on purpose, or if it was purely an accident.

**Comment by dwmw2** [comment]
Hm, wait. The pull request for master was #1801 — that just needs the one commit to enable the collectd nut plugin, from https://github.com/dwmw2/packages/commits/master

This one is for 15.05. The nut dev headers still aren't enabled there.

**Pull request closed without merging**
