### PR TITLE
python-yaml: bump to version 6.0

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @BKPepe 
Compile tested: x86 https://github.com/openwrt/commit/49f615022c921189ff4566b8b2bfdbf97a2a8787
Run tested: n/a

---------------------------------------

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
I'm surprised about the build failure here:
```
 building 'yaml._yaml' extension
arm-openwrt-linux-muslgnueabi-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/Python-3.9.7=Python-3.9.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/Python-3.9.7=Python-3.9.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fno-inline -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/Python-3.9.7=Python-3.9.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fno-inline -I/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/usr/include -I/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/include/fortify -I/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/pypi/PyYAML-6.0=PyYAML-6.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/usr/include -I/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/include/fortify -I/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/include -I/home/build/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/include/python3.9 -fPIC -I/home/build/openwrt/staging_dir/hostpkg/include/python3.9 -c yaml/_yaml.c -o build/temp.linux-arm-3.9/yaml/_yaml.o
cc1: fatal error: yaml/_yaml.c: No such file or directory
compilation terminated.
```

I think I tried with Python 3.10 and it worked.
Will try with 3.9.7 locally.

**Comment by jefferyto** [comment]
The previous version included a pre-generated _yaml.c file in the release tarball, the current version does not. If you add

```make
HOST_PYTHON3_PACKAGE_BUILD_DEPENDS:=Cython
```

it should work.

**Comment by commodo** [comment]
Changelog v1 -> v2:
* added `HOST_PYTHON3_PACKAGE_BUILD_DEPENDS:=Cython`

**Comment by egorenar** [comment]
Having issues with python3-yaml after this update on ARM:

```
/usr/lib/libpython3.10.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

**Comment by commodo** [comment]
ack
will fix

**Comment by john-tho** [comment]
Did we ever get around to reproducing and fixing that host library linked error?
I may have run into it also. Arch Linux build host. arm cortex a7 target.
Last 15 lines of python-yaml compile log:
```sh
cythoning yaml/_yaml.pyx to yaml/_yaml.c
/mnt/pool_ssd/code/openwrt/staging_dir/hostpkg/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/PyYAML-6.0/yaml/_yaml.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'yaml._yaml' extension
creating build/temp.linux-arm-3.10
creating build/temp.linux-arm-3.10/yaml
arm-openwrt-linux-muslgnueabi-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/Python-3.10.5=Python-3.10.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/Python-3.10.5=Python-3.10.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/Python-3.10.5=Python-3.10.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/include -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include/fortify -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/PyYAML-6.0=PyYAML-6.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/include -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include/fortify -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include -I/mnt/pool_ssd/code/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/include/python3.10 -fPIC -I/mnt/pool_ssd/code/openwrt/staging_dir/hostpkg/include/python3.10 -c yaml/_yaml.c -o build/temp.linux-arm-3.10/yaml/_yaml.o
cc1: note: someone does not honour COPTS correctly, passed 4 times
arm-openwrt-linux-muslgnueabi-gcc -shared -L/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/lib -L/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/lib -znow -zrelro -lpython3.10 -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/PyYAML-6.0=PyYAML-6.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/include -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include/fortify -I/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include -I/mnt/pool_ssd/code/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/include/python3.10 build/temp.linux-arm-3.10/yaml/_yaml.o -L/usr/lib -lyaml -o build/lib.linux-arm-3.10/yaml/_yaml.cpython-310.so
/usr/lib/libpython3.10.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
error: command '/mnt/pool_ssd/code/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc' failed with exit code 1
make[2]: *** [Makefile:50: /mnt/pool_ssd/code/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/PyYAML-6.0/.built] Error 1
make[2]: Leaving directory '/mnt/pool_ssd/code/openwrt/feeds/packages/lang/python/python-yaml'
time: package/feeds/packages/python-yaml/compile#4.73#0.31#5.00
```
```sh
./scripts/diffconfig.sh | grep yaml
CONFIG_PACKAGE_libyaml=y
CONFIG_PACKAGE_python3-yaml=y
```

**Comment by commodo** [comment]
A bit late.
But this looks like it's no longer happening on master.

Probably fixed with  https://github.com/openwrt/packages/pull/22551#event-10812764993

**Pull request merged**
