### PR TITLE
dnscrypt-proxy: Changed 'Provider Key' for securedns to current value

### PR DESCRIPTION
**Pull request by cbz**
Signed-off-by: Chris E <cbz@pobox.com>

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: mips_24kc / 19.07.02
Run tested: mips_24kc / 19.07.02

Description:

Changed key in resolver file for securedns.eu to match current value on https://securedns.eu/

### CODE REVIEW

**Comment by BKPepe** [comment]
You should send the pull request to upstream (https://github.com/dyne/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv#L102) first, because there it needs to be improved, too.

**Comment by cbz** [comment]
Given that the upstream hasn't been accepting changes since Jan 2018, this is an example of the best being the enemy of the good.

**Comment by BKPepe** [comment]
Honestly, I don't know, why you don't want to send it to upstream. The dnscrypt-proxy does not plan any new features and it should be maintained. I see the latest commit from August 2019 and there is a good change to have it fixed not just in OpenWrt, but for anyone, who is using dnscrypt-proxy from source code. Instead of arguing about it here, it could be done.

**Comment by cbz** [comment]
Did you actually take a look at the upstream? Because I did. The upstream's last change was 8 months ago, and the project build has been failing for almost as long.  They last accepted a change to the resolvers file 2 years ago, which is why people have been forking it and updating their private copies.

They have two outstanding pull requests dating to November 2019 and March 2018, I don't think they are likely to respond particularly quickly.

**Comment by cbz** [comment]
Look at this issue - https://github.com/dyne/dnscrypt-proxy/issues/15 - they aren't updating their CSV file any longer because the focus has moved to dnscrypt-proxy2

**Pull request merged**
