### PR TITLE
wireguard: bump to release 0.0.20171005

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Maintainer: me

Bump to latest release snapshot.

Tested on: ar71xx Archer c7 v2

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by zx2c4** [comment]
This looks good to me.

Can we merge it?

**Comment by ldir-EDB0** [comment]
@hnyman Ideally (meaning *MUST*) this bump should go into 17.01 as well.  What would you need for that to happen cleanly (as this PR won't apply directly to that branch) Would you like another PR for 17.01?  Or do you apply all the intervening wireguard bumps so that this one applies cleanly?

Cheers,

Kevin

PS: Is it worth me having commit access to look after wireguard in future?

**Comment by hnyman** [comment]
> this bump should go into 17.01 as well. What would you need for that to happen cleanly (as this PR won't apply directly to that branch) Would you like another PR for 17.01?

Yes, please author a PR against 17.01 branch

**Comment by ldir-EDB0** [comment]
Will do so later today :-)

**Comment by zorun** [comment]
@ldir-EDB0 see https://github.com/openwrt/packages/issues/4564#issuecomment-313922541 (it would break backwards compatibility for the config, which is generally frown upon for a stable branch)

**Comment by ldir-EDB0** [comment]
Ok, I won't do the PR.  I'm not sure what guarantees should be offered with regard to pre-release software and 'stable' with regard to backwards compatibility.

**Comment by zx2c4** [comment]
It doesn't matter. That old highly experimental snapshot is broken, a
massive hindrance, and should not be used by anybody. There is no reason or
stickler policy that's good enough to warrant not bumping that. Kevin - you
absolutely should do the PR and not be distracted by worthless pedantry.

On Oct 7, 2017 14:37, "zorun" <notifications@github.com> wrote:

@ldir-EDB0 <https://github.com/ldir-edb0> see #4564 (comment)
<https://github.com/openwrt/packages/issues/4564#issuecomment-313922541>
(it would break backwards compatibility for the config, which is generally
frown upon for a stable branch)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openwrt/packages/pull/4906#issuecomment-334932214>, or mute
the thread

**Pull request merged**
