### PR TITLE
lighttpd: update to lighttpd 1.4.69 release hash - backport to openwrt 22.03

### PR DESCRIPTION
**Pull request by gstrauss**
Maintainer: @flyn-org
Compile tested: arm_cortex-a9 OpenWrt master

Description:

update to lighttpd 1.4.69 release hash (from lighttpd 1.4.67)
includes backport of security bugfix to 22.03

Note: the commits are all straight cherry-picks of openwrt lighttpd commits on master.

Signed-off-by: Glenn Strauss [gstrauss@gluelogic.com](mailto:gstrauss@gluelogic.com)

### CODE REVIEW

**Comment by gstrauss** [comment]
@flyn-org @BKPepe All CI checks have passed for backport of lighttpd 1.4.69 to openwrt 22.03.  Please review.  Thank you.

**Review by BKPepe — APPROVED** [review]

**Comment by gstrauss** [comment]
Thanks @BKPepe   To improve backwards compatibility with existing use, I may remove the change which removes modules now built-in to lighttpd, continuing to provide dummy packages.

**Comment by BKPepe** [comment]
For 22.03, I think it is ok to leave this as it is. I will merge it in a few hours to let @flyn-org know about it.

**Comment by gstrauss** [comment]
I just double-checked.  The packages are not removed in these patches.  They are still provided, even though some are not used at runtime.

I had confused myself because I have already prepared a future patch (not yet released to master) which removes the unused packages.

**Pull request merged**
