### PR TITLE
sound/espeak: Remove from tree

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @psycho-nico 
Compile tested: No
Run tested: No

Description:
espeak is since long dead and has been superseded by espeak-ng.
It also produces barely recognizable output so if someone
wants a speech synthesizer please port espeak-ng and/or
use svox.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@thess @hnyman

**Comment by diizzyy** [comment]
Sample: http://espeak.sourceforge.net/samples.html

**Comment by thess** [comment]
It's really up to @psycho-nico to decide, but for me...
I think packaging and submitting _espeak-ng_ would be a good first step before removing this. "it's old and I don't like it" is not a good enough reason to just toss it out. Failing that, we do have _svox_ in the repo at a 4X size cost.

**Comment by diizzyy** [comment]
This is constantly an issue, someone wants to keep X for ages just for the sake of it. espeak is abandoned upstream and I hardly think that it's acceptable quality in 2017 given the samples above but as always lets keep things just for the sake of it.

**Comment by diizzyy** [comment]
Let's reopen this...

**Comment by diizzyy** [comment]
Lost interest in cleanups...

**Pull request closed without merging**
