### PR TITLE
nginx-util: do not use fallthrough attribute

### PR DESCRIPTION
**Pull request by peter-stadler**
Maintainer: me
Compile tested: x86_64, x86_64 qemu, master
Run tested: x86_64, x86_64 qemu, master, run tests

Description: fix compile warning/error (issue #15653)

### CODE REVIEW

**Comment by ptpt52** [comment]
looks like a wrong fix

**Comment by peter-stadler** [comment]
Do you know a better method? Else: It should work, duplicating the code instead of falling through ...

**Comment by ptpt52** [comment]
Please try this:
````
diff --git a/net/nginx-util/src/nginx-ssl-util.hpp b/net/nginx-util/src/nginx-ssl-util.hpp
index 4f12925db..fac8a3030 100644
--- a/net/nginx-util/src/nginx-ssl-util.hpp
+++ b/net/nginx-util/src/nginx-ssl-util.hpp
@@ -166,8 +166,10 @@ static constexpr auto _escape = _Line{
         std::string ret{};
         for (char c : strptr) {
             switch (c) {
-                case '^': ret += '\\'; [[fallthrough]];
-                case '_': [[fallthrough]];
+                case '^': ret += '\\';
+                         [[fallthrough]];
+                case '_':
+                         [[fallthrough]];
                 case '-': ret += c; break;
                 default:
                     if ((isalpha(c) != 0) || (isdigit(c) != 0)) {
````

**Comment by ptpt52** [comment]
try this:
````
diff --git a/net/nginx-util/src/nginx-ssl-util.hpp b/net/nginx-util/src/nginx-ssl-util.hpp
index 4f12925db..b52346b7f 100644
--- a/net/nginx-util/src/nginx-ssl-util.hpp
+++ b/net/nginx-util/src/nginx-ssl-util.hpp
@@ -166,8 +166,10 @@ static constexpr auto _escape = _Line{
         std::string ret{};
         for (char c : strptr) {
             switch (c) {
-                case '^': ret += '\\'; [[fallthrough]];
-                case '_': [[fallthrough]];
+                case '^': ret += '\\';
+                         /* fallthrough */
+                case '_':
+                         /* fallthrough */
                 case '-': ret += c; break;
                 default:
                     if ((isalpha(c) != 0) || (isdigit(c) != 0)) {
````

do not use ``[[fallthrough]]``

**Comment by ptpt52** [comment]
or more simple:
```
diff --git a/net/nginx-util/src/nginx-ssl-util.hpp b/net/nginx-util/src/nginx-ssl-util.hpp
index 4f12925db..4484b3550 100644
--- a/net/nginx-util/src/nginx-ssl-util.hpp
+++ b/net/nginx-util/src/nginx-ssl-util.hpp
@@ -166,8 +166,8 @@ static constexpr auto _escape = _Line{
         std::string ret{};
         for (char c : strptr) {
             switch (c) {
-                case '^': ret += '\\'; [[fallthrough]];
-                case '_': [[fallthrough]];
+                case '^': ret += '\\'; /* fallthrough */
+                case '_': /* fallthrough */
                 case '-': ret += c; break;
                 default:
                     if ((isalpha(c) != 0) || (isdigit(c) != 0)) {
```

**Comment by peter-stadler** [comment]
I changed it, thank you :-)
Do you happen to know why the `[[fallthrough]];` attribute is not working anymore?

**Comment by ptpt52** [comment]
it is likely
```
fallthrough;
```
work?

https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html

https://stackoverflow.com/questions/45349079/how-to-use-attribute-fallthrough-correctly-in-gcc

**Comment by peter-stadler** [comment]
I thought about the [c++17 standard attribute](https://en.cppreference.com/w/cpp/language/attributes/fallthrough) not the legacy one, but it is not that important ...

**Comment by peter-stadler** [comment]
I am not sure if the comment `/* fallthrough */` would work with gcc 10, so I copy the `ret += c; break;` instead of falling through.

(The command `fallthrough;` would work, too, but AFAIK it is not standard c++ and clang-tidy is not recognizing it. So I hesitate using it here.)

**Pull request merged**
