### PR TITLE
postgresql: update to version 16.3

### PR DESCRIPTION
**Pull request by dangowrt**
Maintainer: me
Compile tested: aarch64/cortex-a53
Run tested: -

Description:
## Switch to new major version 16.
Use meson to build for target, however, old autotools-style configure is needed to clean the source directory before being able to run meson, and host build of the timezone compiler ('zic') also still requires using the old build system.

See also https://www.postgresql.org/docs/16/release-16.html

### CODE REVIEW

**Comment by Ra2-IFV** [comment]
You sure you successfully compiled it?

**Comment by dangowrt** [comment]
Yes, it builds fine for me locally, Github CI fails with
```
2024-06-05T10:12:53.4129577Z flex: fatal internal error, exec of /builder/shared-workdir/build/staging_dir/host/bin/m4 failed
```
No idea why.

**Comment by Ra2-IFV** [comment]
how do you build the package?

On July 2, 2024 7:57:32 PM UTC, Daniel Golle ***@***.***> wrote:
>Yes, it builds fine for me locally, Github CI fails with
>```
>2024-06-05T10:12:53.4129577Z flex: fatal internal error, exec of /builder/shared-workdir/build/staging_dir/host/bin/m4 failed
>```
>No idea why.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/packages/pull/24327#issuecomment-2204275836
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hnyman** [comment]
Postgresql currently fails in buildbot, breaking lots of other packages .

Example
https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/postgresql/compile.txt

```
[243/1619] Generating src/fe_utils/psqlscan with a custom command
FAILED: src/fe_utils/psqlscan.c 
/builder/shared-workdir/build/sdk/staging_dir/host/bin/python3 ../src/tools/pgflex --builddir . --srcdir .. --privatedir src/fe_utils/psqlscan.c.p --flex /builder/shared-workdir/build/sdk/staging_dir/host/bin/flex --perl /builder/shared-workdir/build/sdk/staging_dir/host/bin/perl -i ../src/fe_utils/psqlscan.l -o src/fe_utils/psqlscan.c --no-backup --fix-warnings -- -Cfe -p -p
flex: fatal internal error, exec of /builder/shared-workdir/build/staging_dir/host/bin/m4 failed
[244/1619] Compiling C object src/interfaces/libpq/libpq.so.5.16.p/pqexpbuffer.c.o
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:264: /builder/shared-
```

Flex referencing to m4 ?  

Unless the version upgrade gets fixed, it might need to be reverted.

**Comment by ghoffman9** [comment]
long list of build failures:
``There are currently package build failures for SNAPSHOT arm_cortex-a15_neon-vfpv4:                        
 Feed: packages                                                                                          
   apache                     Sun Jul  7 04:45:34 2024 - not installed                                   
   apr-util                   Sun Jul  7 04:10:57 2024 - not installed                                   
   basicstation               Sun Jul  7 02:41:57 2024 - not installed                                   
   collectd                   Sun Jul  7 04:44:25 2024 - package installed locally, cannot upgrade       
   elektra                    Sun Jul  7 04:15:43 2024 - not installed                                   
   exim                       Sun Jul  7 04:19:38 2024 - not installed                                   
   freeradius3                Sun Jul  7 04:16:11 2024 - not installed                                   
   gnunet                     Sun Jul  7 04:48:02 2024 - not installed                                   
   kadnode                    Sun Jul  7 01:45:41 2024 - not installed                                   
   libdbi-drivers             Sun Jul  7 04:00:22 2024 - not installed                                   
   libpqxx                    Sun Jul  7 04:01:04 2024 - not installed                                   
   libuhttpd                  Sun Jul  7 02:58:55 2024 - not installed                                   
   lighttpd                   Sun Jul  7 04:23:02 2024 - not installed                                   
   luasql                     Sun Jul  7 04:01:16 2024 - not installed                                   
   micropython                Sun Jul  7 01:50:09 2024 - not installed                                   
   pdns                       Sun Jul  7 05:02:54 2024 - not installed                                   
   php8                       Sun Jul  7 05:08:49 2024 - not installed                                   
   php8-pecl-dio              Sun Jul  7 05:10:18 2024 - not installed                                   
   php8-pecl-http             Sun Jul  7 05:10:32 2024 - not installed                                   
   php8-pecl-imagick          Sun Jul  7 05:10:20 2024 - not installed                                   
   php8-pecl-krb5             Sun Jul  7 05:10:21 2024 - not installed                                   
   php8-pecl-mcrypt           Sun Jul  7 05:10:21 2024 - not installed                                   
   php8-pecl-raphf            Sun Jul  7 05:10:19 2024 - not installed                                   
   php8-pecl-redis            Sun Jul  7 05:10:22 2024 - not installed                                   
   php8-pecl-xdebug           Sun Jul  7 05:10:23 2024 - not installed                                   
   postgresql                 Sun Jul  7 03:55:13 2024 - not installed                                   
   psqlodbc                   Sun Jul  7 04:32:23 2024 - not installed                                   
   python-psycopg2            Sun Jul  7 04:39:05 2024 - not installed                                   
   schroot                    Sun Jul  7 04:41:34 2024 - not installed                                   
   shadowsocks-libev          Sun Jul  7 03:08:32 2024 - not installed                                   
   transmission               Sun Jul  7 03:57:56 2024 - not installed                                   
   ulogd                      Sun Jul  7 04:03:10 2024 - not installed                                   
   umurmur                    Sun Jul  7 03:11:34 2024 - not installed                                   
   xr_usb_serial_common       Sun Jul  7 02:16:57 2024 - not installed                                   
   zabbix                     Sun Jul  7 05:10:37 2024 - not installed                                   `
`

**Comment by hnyman** [comment]
postgresql upgrade reverted with 3dbefd299a , as absence of postgresql broken dozens of other packages in buildbot.

**Pull request merged**
