### PR TITLE
libssh2: Add variants for mbed TLS and OpenSSL

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @jslachta 
Compile tested: armvirt-64/malta-be, 2020-03-19 snapshot sdk
Run tested: **none** (how should I run test this?)

Description:
This removes the config option and adds variants for mbed TLS and OpenSSL so that both versions can be built at the same time.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I left `PKG_RELEASE` unchanged since this removes the libssh2 package and adds libssh2-mbedtls and libssh2-openssl - let me know if I should increment it anyway.

Also, `Build/InstallDev` (from cmake.mk) will run for both variants... The installed headers should be the same but the libraries and libssh2.pc file will be different, depending on which variant's `Build/InstallDev` was run last. How should this be resolved (if this is an issue)?

**Comment by micmac1** [comment]
The pc file being different is an issue. I would say it's a show stopper if left without a solution.

**Comment by jefferyto** [comment]
Here's the diff of the two .pc files:

```diff
--- libssh2-mbedtls/libssh2-1.9.0/ipkg-install/usr/lib/pkgconfig/libssh2.pc     2020-03-22 03:18:38.000000000 +0800
+++ libssh2-openssl/libssh2-1.9.0/ipkg-install/usr/lib/pkgconfig/libssh2.pc     2020-03-22 03:18:52.000000000 +0800
@@ -11,7 +11,7 @@ Name: libssh2
 URL: https://www.libssh2.org/
 Description: The SSH library
 Version: 1.9.0
-Requires.private: zlib
-Libs: -L${libdir} -lssh2 -lmbedcrypto
-Libs.private: -lmbedcrypto
+Requires.private: libssl,libcrypto,zlib
+Libs: -L${libdir} -lssh2 
+Libs.private: 
 Cflags: -I${includedir}
```

I'm not sure the different `-l` flags will actually affect other packages, unless they can also link to both mbed TLS or OpenSSL.

Still, I think there are more general questions about package variants:

* If both variants are compiled, should the default variant (`mbedtls` in this case) take precedence over the other (`openssl`) for `Build/InstallDev`?
* If only the `openssl` variant is compiled, should its `Build/InstallDev` also be run?
* Should this be generalized for all packages with variants?

I haven't thought deeply enough about variants and the build system to have any answers yet :joy:

**Comment by micmac1** [comment]
Maybe look at other variant libs in the repos. How did they solve it?

**Comment by jefferyto** [comment]
Perhaps a better question would be, has any other package thought about these questions.

For all packages I found where variants (I believe) affect the compiled library, none except [ffmpeg](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/multimedia/ffmpeg/Makefile#L715-L737) take variants into account during `Build/InstallDev`:

* libs
  * [avahi](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/avahi/Makefile#L311) (not sure if variants affect lib/pc file output)
  * [libarchive](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/libarchive/Makefile#L94)
  * [libmicrohttpd](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/libmicrohttpd/Makefile#L71)
  * [libshout](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/libshout/Makefile#L99)
  * [poco](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/poco/Makefile#L98)
  * [xmlrpc-c](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/xmlrpc-c/Makefile#L125) (though one of the variants is marked `@BROKEN`)
  * [zmq](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/libs/zmq/Makefile#L77)
* net
  * [mosquitto](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/net/mosquitto/Makefile#L191)
  * [unbound](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/net/unbound/Makefile#L187)
* sound
  * [pulseaudio](https://github.com/openwrt/packages/blob/f31a9349ead21acc6fc1c4274f59e40abaf31f2b/sound/pulseaudio/Makefile#L141)

For ffmpeg, while I think the selection logic can be improved, there is a clear ranking in terms of which variant to install (full > mini > custom or audio-dec). I don't think the preference is as clear for cases like no-ssl vs ssl or mbedtls vs openssl.

**Comment by diizzyy** [comment]
Is there a practial use case forthis change apart from adding complexity? 
The only user as far as I can tell is mc which pulls in glib2 and a few other "rather" large packages.

**Comment by jefferyto** [comment]
@diizzyy #11605

**Comment by diizzyy** [comment]
@jefferyto 
Ahh, I see. Thanks.

So we more or less need to make sure the said libraries/applications doesn't (perferably(?)) use the "wrong" SSH lib before committing this PR?

**Comment by jefferyto** [comment]
nmap-full depends on libssh2 and libopenssl. With the crypto backend option defaulting to mbedTLS, the libssh2 package built by buildbots depends on libmbedtls. This means if a regular user (i.e. someone that doesn't compile their own packages) installs nmap-full, they will need to install both mbedTLS and OpenSSL libraries. This is not optimal.

This change is to build both mbedTLS and OpenSSL variants of libssh2, so that this regular user can install nmap-full and libssh2-openssl, and thus only have to install the OpenSSL library. (This user can also opt to install libssh2-mbedtls. I do not know if there are any issues with using nmap-full and libssh2-mbedtls as I only did very limited run-testing in #11605.)

The InstallDev issue I raised in the comments here is a secondary issue that is not specific to libssh2; I'm not even sure if it is a real issue that needs to be addressed.

**Comment by micmac1** [comment]
> nmap-full depends on libssh2 and libopenssl. With the crypto backend
> option defaulting to mbedTLS, the libssh2 package built by buildbots
> depends on libmbedtls. This means if a regular user (i.e. someone that
> doesn't compile their own packages) installs nmap-full, they will need
> to install both mbedTLS and OpenSSL libraries. This is not optimal.

OK, so this is not a technical issue. This is about the preference of
not having to install a 2nd ssl/tls lib. And about not having to compile
libssh2 manually with the preferred ssl/tls lib.

> The InstallDev issue I raised in the comments here is a secondary
> issue that is not specific to libssh2; I'm not even sure if it is a
> real issue that needs to be addressed.

It being not specific to libssh2 doesn't make it go away. Maybe other
maintainers not doing what is proposed here is a hint that it's a bad
idea.

The pc files of the variants are different. That would be a problem.
That would also be a problem because both variants would install their
pc file into the exact same location, overwriting the other variants
file.

This headache would need to be addressed by your pull request. But I
think you don't want to deal with this headache, and neither does
anybody else.

But adding variant builds is not the only possible answer to your
personal preference problem. I can imagine the libssh2 package's default
of mbedtls being changed to libopenssl. The only packages in the tree
depending on libssh2 are:

aria2: defaults to OpenSSL
nmap: defaults to OpenSSL
mc: doesn't not link to ssl/tls lib on its own

So changing the libssh2 default from mbedtls to OpenSSL seems to me like
the sane approach here, considering that the packages linking to it
prefer the latter. This would also avoid the headache mentioned above.

**Comment by jefferyto** [comment]
> It being not specific to libssh2 doesn't make it go away.

I never said not being specific to libssh2 makes it go away. I said I'm not sure it is a real problem.

> Maybe other
> maintainers not doing what is proposed here is a hint that it's a bad
> idea.

I don't see any solutions being proposed here that other maintainers can adopt wholesale.

> The pc files of the variants are different. That would be a problem.
> That would also be a problem because both variants would install their
> pc file into the exact same location, overwriting the other variants
> file.

If you have a solution to this general issue, I would be happy to help implement it.

> This headache would need to be addressed by your pull request. But I
> think you don't want to deal with this headache, and neither does
> anybody else.

Please don't assume you know what I think.

I think if this is a real issue, it is a general issue that affects multiple packages and needs to be solved in a general way.

This PR being blocked by a general issue, and expecting a general solution before accepting this PR, is counterproductive.

If I didn't want to solve this issue, I wouldn't have raised it in the first place.

I'll come out and say it: I don't know how this general problem should be solved. Perhaps you can help to solve it, instead of only assuming my intentions.

> But adding variant builds is not the only possible answer to your
> personal preference problem.

This is not my "personal preference" problem. I don't even use nmap. Again, please stop assuming you know what I think.

> I can imagine the libssh2 package's default
> of mbedtls being changed to libopenssl. The only packages in the tree
> depending on libssh2 are:
>
> aria2: defaults to OpenSSL
> nmap: defaults to OpenSSL
> mc: doesn't not link to ssl/tls lib on its own
>
> So changing the libssh2 default from mbedtls to OpenSSL seems to me like
> the sane approach here, considering that the packages linking to it
> prefer the latter. This would also avoid the headache mentioned above.

This is one solution. Please open a PR for it if you wish. This however only avoids the general problem of InstallDev with variants, this does not solve it. I am going to assume, like me, you are also interested in addressing this issue for the wider OpenWrt community.

**Comment by jefferyto** [comment]
> OK, so this is not a technical issue. This is about the preference of
not having to install a 2nd ssl/tls lib. And about not having to compile
libssh2 manually with the preferred ssl/tls lib.

OpenWrt is a distro for routers, yes? Routers have limited disk space, is this still correct?

We don't expect end users to have to compile their own packages, yes? This is why we provide pre-built packages in the form of package feeds, yes?

We care about all issues, yes? Not just technical ones, yes?

**Comment by micmac1** [comment]
I don't think you can demand of anybody else to fix your pull request like you just demanded from me. Also I am not going to raise a pull request for the default-change for you. I was suggesting this change (the default change, from mbedtls to openssl) to prevent the headache. It was quite a constructive feedback I think.

And what you describe as a "general issue" (that is, how to handle variants of libraries properly) I never considered a problem, because I don't think there's a need for library variants. Well, at least I never encountered it so far.

You have a good day, sir!

**Comment by jslachta** [comment]
Hi.

I am sorry for the silence. I had to think about it.

I understand that having limitless variants has its benefits. But it looks overcomplicated to me.

There are following issues with this package =>
- current state: The possibility of choosing the crypto engine is a floating dependency. Each package that uses libssh2 must count on this conditional indirect dependency. So whenever libssh2 package maintainer changes his mind, then all package maintainers must update their dependency set. Is that correct? I suppose not.
- package-variants: the issue of pkgconfig file is a show stopper.

I suppose we should do it this way:

1. (cheapest variant) - keep the package in the current state
2. **Remove Config.in, remove conditional dependencies, keep the crypto engine dependency set to libmbedtls. The size of mbedtls is just around ~170KiB. This size is acceptable even if you want to have both libs installed (openssl and libmbedtls). 4 MB Flash size is a history, since OpenWrt 19.07.**
3. Reside all variants to separate, independent packages.

Please vote. I choose the second variant.

**Comment by jefferyto** [comment]
luci-ssl depends on libustream-mbedtls, luci-ssl-openssl depends on libustream-openssl. There are mbedtls and openssl variants of openvpn. I guess I'm the only one that likes to install openssl variants and never touch mbedtls.

There is no need to hold a vote. I'd rather continue spending my time trying to fix the "pkgconfig file issue" than fighting for this one library that I don't care much about.

**Pull request closed without merging**
