### PR TITLE
taskwarror: Update to 2.5.1

### PR DESCRIPTION
**Pull request by neheb**
Makefile adjustments for consistency.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lperkov ??
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
CircleCI failing again?

**Comment by thess** [comment]
My bad - I'll fix,,,

**Comment by thess** [comment]
grep compatibility error - rebase, push -f
should be OK now

**Comment by neheb** [comment]
different issue now

**Comment by thess** [comment]
Seems like while we were chatting, the SDK updated from gcc-7.3 to gcc-7.4 and the SDK download failed... Wait 1 while I update the script. Need to figure out a better way to track such updates.

**Comment by thess** [comment]
OK - try again. Sigh...

**Comment by neheb** [comment]
All's well now.

**Comment by neheb** [comment]
@hnyman This is ready. Maintainer had long been absent.

**Comment by diizzyy** [comment]
@neheb 
Remove maintainer and it's good to go.

**Comment by neheb** [comment]
Done

**Comment by diizzyy** [comment]
@hnyman @thess 
Please merge

**Comment by BKPepe** [comment]
Is there any reason, why it isn't merged, yet?

**Comment by hnyman** [comment]
> Is there any reason, why it isn't merged, yet?

No indication of any run-testing...

So far it looks like a combination of version update, compiler option change & maintainer removal without run-testing.  Likely there is no problem, but would be nice to get that confirmed with some testing.

(Apparently in #8084 ja-pa has also run-tested the version upgrade, but without the linker flag change.)

It is great that neheb is active on package updates, but it would be nice to get some confirmation about the actual working of the package after the proposed update. This goes from 2.4.x to 2.5.x.  (CircleCI will confirm the compiling with ar71xx, so there is that automatic compile-testing in any case, but CircleCI does not try running it.) 

So, if anybody has actually tried the result of the PR, please confirm that.

**Comment by BKPepe** [comment]
Thank you for the explanation. I have tested it.

Compiled tested: cortexa53, Turris MOX, OpenWrt 18.06.02
Run tested: cortexa53, Turris MOX, OpenWrt 18.06.02

Proof of run tested: 

screenshot from 2019-02-13 19-33-49
screenshot from 2019-02-13 19-32-42

**Pull request merged**
