### PR TITLE
libyang: update to 1.0.130

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Maintainer: @mislavn 
Tested: mips, aarch64
Run tested against frr

### CODE REVIEW

**Comment by BKPepe** [comment]
Wouldn't it be better to use the latest version 1.0.130?

**Comment by lucize** [comment]
I've tested that also, and made the pr, but changed my mind, I am thinking also of 1.0.130 as lib is 1.6.7 vs 1.4 in this case

**Comment by neheb** [comment]
I have a feeling the other depending packages will break. Have those been tested?

**Comment by lucize** [comment]
Should work, I'll test them

**Comment by lucize** [comment]
the other packages have not been updated in a while, if they work with 1.0.rcX they should work with 1.0.130 as the api was changed from older libyang 0.X long ago

**Comment by neheb** [comment]
OK.

**Comment by neheb** [comment]
This did indeed break https://downloads.openwrt.org/snapshots/faillogs/mipsel_74kc/packages/sysrepo/compile.txt

**Comment by lucize** [comment]
I'll see about updating all the related packages to the master

**Comment by lucize** [comment]
@neheb should I add one PR with 2 commits ? libyang needs a change for sysrepo to work

**Comment by neheb** [comment]
Sure

**Pull request merged**
