### PR TITLE
node: update to v12.15.0

### PR DESCRIPTION
**Pull request by nxhack**
Maintainer: @blogic @ianchi
Compile tested: head r11167-273a6cb, mips mips64 mipsel mips64el arm aarch64 x86_64 i386
Run tested: mips mips64 mipsel mips64el arm aarch64 x86_64 i386

Description:
~~[Draft] do not merge~~
Update to ~~v12.11.1~~ ~~v12.12.0~~ ~~v12.13.0~~ ~~v12.13.1~~ ~~v12.14.0~~ ~~v12.14.1~~ v12.15.0
Support Python3 : https://github.com/openwrt/packages/issues/8893
Preparing to deprecate nosnapshot builds.

Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>

### CODE REVIEW

**Comment by nxhack** [comment]
no multilib...

**Comment by neheb** [comment]
Interestingly, neither do the buildbots. Meaning only 64-bit targets will get node.

**Comment by nxhack** [comment]
When building a 32-bit target, we will need to compile the ia32 executable. (gcc-multilib, g++-multilib package)

https://github.com/nodejs/node/issues/27838#issuecomment-495309864

**Comment by nxhack** [comment]
Now ready to review and marge.

Note: Requires GCC/G++ Multilib on host system to build 32-bit target

**Comment by neheb** [comment]
Hrm. That would make it unavailable since the buildbots lack multilib.

Guess the buildbots need to be fixed first...

**Comment by neheb** [comment]
Probably a good idea to add https://github.com/nodejs/node/commit/4e119202512c16abdc9e97b87bae73cc6353b575 to patches.

No idea if it applies cleanly.

**Comment by nxhack** [comment]
@neheb 
> Probably a good idea to add nodejs/node@4e11920 to patches.

wait for a while because it will be merged in v12.15.0.

**Comment by neheb** [comment]
Let's see what happens...

**Comment by mabachel** [comment]
> Now ready to review and marge.
> 
> Note: Requires GCC/G++ Multilib on host system to build 32-bit target


> Hrm. That would make it unavailable since the buildbots lack multilib.
> 
> Guess the buildbots need to be fixed first...

Hi,
I have a current version of master installed on my Netgear R7800 (arm_cortex-a15_neon-vfpv4) but the node package is not available for download from https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/packages/ because I guess the buildbot cannot build it for a 32-bit target.
With the upcoming release on the horizon I am wondering if someone is working on this.

Node should be available for 32-bit targets on the next major release shouldn't it?

Thanks.

**Comment by neheb** [comment]
Seems like no. Coordination for fixing the buildbots seems to be a mess.

**Comment by mabachel** [comment]
I opened up a [topic on the forum](https://forum.openwrt.org/t/buildbot-multilib-support-node-for-32-bit-targets-on-next-major-release/65758) to reach a broader audience..

**Pull request merged**
