### PR TITLE
zmq: Fix compilation for c++ stdlib

### PR DESCRIPTION
**Pull request by ammubhave**
Compilation for the zmq lib is broken for c++ stdlib  in openwrt since the
patches add uclibc++ specific header includes.
This diffs changes the patches to only include these headers, and other changes conditioned
on if we are actually using uclibc++.

Signed-off-by: Amol Bhave <ambhave@fb.com>

Tested: master; for NBG6817 and Generic ATH79. Compiled successfully with both uclibc++ and stdlib

### CODE REVIEW

**Comment by neheb** [comment]
Oh goodie. Looks like I didn't cause this. Then again, few use glibc with OpenWrt. I would assume there are more problems than this package.

We should look into upstreaming these patches.

**Comment by neheb** [comment]
Please bump PKG_RELEASE as this changes the code.

**Comment by neheb** [comment]
Note: This is also reproducible if you change the default libc++ with libstdcpp under Global build settings.

**Comment by neheb** [comment]
I just tested with uClibc++ and libstdcpp. Patch 100 is completely unnecessary. Please remove.

**Comment by ammubhave** [comment]
removed patch 100 and verified that zmq compilation still succeeds.
I'll submit a PR for upstream as well then.

**Comment by ammubhave** [comment]
never mind (https://github.com/zeromq/libzmq/pull/3481), you beat me to it :)

**Pull request merged**
