### PR TITLE
net-snmp: Upstep to 5.7.3

### PR DESCRIPTION
**Pull request by dedeckeh**
Maintainer: @jow- 
Compile tested: brcm63xx
Run tested: brcm63xx

Description:

Upstep to 5.7.3; remove patches 130-debian-extramibs and 800-format-security
as upstream integrated/fixed
Fix libnl dependency in package Makefile

Signed-off-by: Hans Dedecker dedeckeh@gmail.com

### CODE REVIEW

**Comment by hnyman** [comment]
@jow-  
Any comments?

**Comment by karlp** [comment]
I'd really like to get agentx support standard too, if we're going to make changes.

**Comment by dedeckeh** [comment]
@karlp I'm happy to add agentx support if the PR upstep to 5.7.3 is  accepted

**Comment by hnyman** [comment]
@dedeckeh 
There has been no reaction for @jow- to this PR.
Maybe you should add yourself as the Maintainer as you have interest for this package.

**Comment by stintel** [comment]
@dedeckeh the only MIB in 130-debian-extramibs that was added upstream seems to be BRIDGE-MIB.txt. Dropping this patch entirely would drop following MIBS:
BGP4-MIB.txt
GNOME-SMI.txt
OSPF-MIB.txt
OSPF-TRAP-MIB.txt
RIPv2-MIB.txt
SOURCE-ROUTING-MIB.txt

Can you fix this?

And am I the only one who wonders what "upstep" means? I'm not a native English speaker, but it seems incorrect to me.

**Comment by jow-** [comment]
@dedeckeh @stintel - feeld free to take over this package. I initially ported it as prereq for collectd iirc but have no direct interest in it.

**Pull request closed without merging**
