### PR TITLE
libtool-bin: switch to xz tarball

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @xypron 

Description:

Switch to xz tarball

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by xypron** [comment]
@diizzyy 
The commit message does not explain why we should change to an xz tarball.

Regards

Heinrich Schuchardt

**Comment by xypron** [comment]
@diizzyy
 
package/libs/libtool/Makefile of Lede uses

    PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz

We should not download the same archive twice with different compression algorithm.

The xz file is smaller than the gz file. So maybe you want to submit a parallel patch to Lede and OpenWrt/OpenWrt for the libtool package.

Regards

Heinrich Schuchardt

**Comment by diizzyy** [comment]
@xypron 
tools/libtool is already converted, I did overlook package/libs/libtool and will submit a pull request shortly. Thanks for caching that one.

**Comment by diizzyy** [comment]
*sigh* I shouldn't do this while being half asleep...
https://github.com/lede-project/source/pull/396

Best regards
Daniel

**Comment by xypron** [comment]
@diizzyy 

    Acked-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

**Pull request merged**
