### PR TITLE
zerotier: keep configuration file on update

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>

Maintainer: me
Compile tested: OpenWrt master
Run tested: Nexx wt3020

Description: Keep the configuration file when the package is updated.

### CODE REVIEW

**Comment by neheb** [comment]
I think PKG_RELEASE should be bumped.

**Comment by mwarning** [comment]
done

**Comment by neheb** [comment]
Change

```
PKG_LICENSE:=GPL-3.0
```

to

```
PKG_LICENSE:=GPL-3.0-or-later
```

Place PKG_MAINTAINER above it.

Add ```PKG_LICENSE_FILES:=LICENSE.txt``` below PKG_LICENSE

Place that block below the PKG_SOURCE one. See https://github.com/openwrt/packages/blob/master/libs/fbthrift/Makefile for an example

**Comment by mwarning** [comment]
@neheb next try :)

**Comment by neheb** [comment]
Get rid of MAINTAINER below. PKG_MAINTAINER handles it.

**Comment by neheb** [comment]
Replacing ```TARGET_LDFLAGS += -Wl,--gc-sections``` with ```TARGET_LDFLAGS += -Wl,--gc-sections,--as-needed``` could make it smaller. Have not tested.

**Comment by mwarning** [comment]
updated - that TARGET_LDFLAGS change will be added to my personal repository until it can be tested.

**Comment by unquietwiki** [comment]
@mwarning @neheb Hey hey. I wanted to get an idea when it'd be safe to update routers I'm using with this. 16.04.5? Or roll my own with the master branch?

**Comment by mwarning** [comment]
The configuration has not changed, so I assume an update is fine.

**Pull request merged**
