### PR TITLE
gcc: add GCC 14.2

### PR DESCRIPTION
**Pull request by rsalvaterra**
Deleted (upstreamed):

- 020-Include-safe-ctype.h-after-C-standard-headers-to-avo.patch [1]
- 021-libcc1-fix-vector-include.patch [2]

All other patches automatically rebased.

[1] https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=9970b576b7e4ae337af1268395ff221348c4b34a
[2] https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=5213047b1d50af63dfabb5e5649821a6cb157e33

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by rsalvaterra** [comment]
Build-tested:
- mediatek/filogic (Banana Pi R3)

**Comment by trippleflux** [comment]
Would you take a look at net-snmp, for other packages seems quite simple for gcc 14 compilation supports,
but I am stuck with net-snmp 

Already added : 
```
TARGET_CFLAGS += $(FPIC) -w
```

But still stopped at  : 
```
mibgroup/ieee802dot11.c: In function 'var_ieee802dot11':
mibgroup/ieee802dot11.c:353:8: error: implicit declaration of function 'header_generic' [-Wimplicit-function-declaration]
  353 |   if ( header_generic ( vp, name, length, exact,var_len,write_method )
      |        ^~~~~~~~~~~~~~
mibgroup/ieee802dot11.c: In function 'load80211Structs':
mibgroup/ieee802dot11.c:3985:15: error: implicit declaration of function 'if_nametoindex' [-Wimplicit-function-declaration]
 3985 |     ifIndex = if_nametoindex ( ifName );
      |               ^~~~~~~~~~~~~~
mibgroup/ieee802dot11.c: In function 'addList':
mibgroup/ieee802dot11.c:4705:8: error: assignment to 'struct <anonymous> *' from incompatible pointer type 'struct <anonymous> *' [-Wincompatible-pointer-types]
 4705 |   list = ( LIST_HEAD ( , avNode ) * ) l;            // NOTE: don't know how to get
      |        ^
mibgroup/ieee802dot11.c: In function 'flushList':
mibgroup/ieee802dot11.c:4789:8: error: assignment to 'struct <anonymous> *' from incompatible pointer type 'struct <anonymous> *' [-Wincompatible-pointer-types]
 4789 |   list = ( LIST_HEAD ( , avNode ) * ) l;    // NOTE: don't know how to get
      |        ^
make[4]: *** [Makefile:101: mibgroup/ieee802dot11.lo] Error 1
```

**Comment by neheb** [comment]
Second patch needs to be removed.

**Comment by rsalvaterra** [comment]
> Second patch needs to be removed.

Done, sorry for the delay, got a bit sidetracked. Pull updated for 14.2 too.

**Pull request merged**
