### PR TITLE
seafile-seahub: add pytz to PKG_BUILD_DEPENDS

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @kissg1988  
Compile tested: mipsel_74kc, openwrt master

Description:
This is a workaround for a failure by the buildbots to build this package.  I can't reproduce the problem locally, so I'm hoping this does the trick.
Travis would fail to build it as well, so my guess is that if travis succeeds, the bots might do as well.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by neheb** [comment]
bad commit title.

**Comment by cotequeiroz** [comment]
This did not work anyway.  I'm closing for now.

**Comment by neheb** [comment]
If you're going to work on this, I have a package bump for it: https://github.com/neheb/packages/commit/d80474b6e658efb4ef2334992fd8a15f14f11dcc

Same issue though.

**Comment by cotequeiroz** [comment]
The problem may not be in this package, though.  If you want to upgrade, go ahead; if not, I can pick up your commits when I reopen this.

**Comment by neheb** [comment]
Feel free. I have not pushed this because of the pytz issue.

**Comment by cotequeiroz** [comment]
@neheb 
I'm reopening this just to test the fix I made in pytz.  Please open the PRs.  The seafile-* packages need to be kept with the same version.  Notice they have a "version" dependency between them. I imagine you have the commits ready for all of them.

**Comment by neheb** [comment]
@cotequeiroz yes. The reason I have not posted them is because of the pytz issue. I can't runtime the rest. ccnet does not depend on the rest though.

**Comment by neheb** [comment]
@cotequeiroz I've narrowed the issue down to Django. Downgrading to 1.10 works. Will investigate some more.

**Pull request closed without merging**
