### PR TITLE
adblock: release 4.0.0

### PR DESCRIPTION
**Pull request by dibdot**
Maintainer: me / @dibdot 
Compile tested: x86_64
Run tested: apu2, raspi4, turris mox
Pre-tested by many forum users, see here: https://forum.openwrt.org/t/adblock-4-pre-releases/57101

Description:
* new package dependencies: coreultis-sort and
  a download util with SSL support
* focus on speed (multicore-support) to handle quite big lists
* include 38 pre-configured blocklist sources in a compressed
  json file (/etc/adblock/adblock.sources.gz)
* dynamic SafeSearch support for google, bing, duckduckgo,
  yandex, youtube and pixabay (CNAME (bind) & IP (dnsmaq, unbound))
* DNS backend autodetection
* Download Utility autodetection
* Report Interface autodetection
* Easy cron wrapper to set an adblock related auto-timer for
  automatic blocklist updates
* raw domain/blocklist support (e.g. for dnscrypt support)
* re-add restrictive Jaillist support
* rework online doc
* Complete LuCI rewrite (migrated to client side JS), separate PR in luci repo

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by neheb** [comment]
2 other questions:

any testing with kresd?

Has it been ran through spellcheck? I’m away ATM so I can’t verify.

**Comment by dibdot** [comment]
Yes, I've tested this version with kresd on branch hbd (5.1.x) with turris mox and turris omnia.
And yes, I've quickly doublechecked with shellcheck ... there are still some remaining/harmless warnings which are wrong or pretty useless (IMHO).

**Comment by dibdot** [comment]
@neheb I've change the gzip compression level on the building host

**Comment by hnyman** [comment]
@dibdot 
One suggestion for 4.0.1: 
Please stop declaring  ` unrecoverable adblock config error `   just because there are "source" config sections.
 https://github.com/openwrt/packages/blob/master/net/adblock/files/adblock.sh#L126

That effectively prevents using the same config for master and 19.07 builds. The actual config changes are otherwise minor, I think. Some options have change section etc., but there is nothing preventing having e.g. "adb_maxqueue" on two sections for different builds.

But declaring unrecoverable error in master 4.0.0 just because there are unused "source" sections, seems overkill, as those unused sections should be harmless. But those sections are still needed for adblock in 19.07.  

I constantly jump between master and 19.07 due to my community builds, so I ran into this problem rather quickly.

Or are you thinking of backporting adblock 4 soon to 19.07?

**Comment by dibdot** [comment]
This affects "only" builders like you. ;-)
I would suggest to include a default 4.0 adblock.opkg config to your builds ... than adblock 4 will fix this error automatically ... and adblock 3.8.x don't care.

**Comment by hnyman** [comment]
Yeah, this only concerns us schitzos who frequently use various OpenWrt versions.

Thanks for the idea about adblock-opkg. Including that file just on my personal router's /etc/config will fix the transition from 19.07 to master, and I will maybe handle the the master -->19.07 transition manually.

**Pull request merged**
