### PR TITLE
stubby: quote address value in config

### LINKED ISSUE #17421: stubby: error in generated config
Maintainer: @neheb, @jonathanunderwood
Environment: Netgear WNDR3700 v4, OpenWrt 21.02.1 r16325-88151b8303

Description:

If resolver IP address ends with `:`, e.g. `2a09::`, the generated YAML has invalid syntax. Address value should be quoted to prevent this.

```
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: [17:28:32.754798] STUBBY: Stubby version: Stubby 0.4.0
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: Scanner error: mapping values are not allowed in this context at line 24, column 24
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: Could not parse config file # Autogenerated configuration from uci data
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: resolution_type: GETDNS_RESOLUTION_STUB
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: round_robin_upstreams: 1
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: appdata_dir: "/var/lib/stubby"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: trust_anchors_backoff_time: 2500
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: tls_query_padding_blocksize: 128
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: edns_client_subnet_private: 1
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: idle_timeout: 10000
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: listen_addresses:
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - 127.0.0.1@5453
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - 0::1@5453
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: dns_transport_list:
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - GETDNS_TRANSPORT_TLS
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: upstream_recursive_servers:
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 2606:4700:4700::1111
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "cloudflare-dns.com"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 2606:4700:4700::1001
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "cloudflare-dns.com"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 1.1.1.1
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "cloudflare-dns.com"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 1.0.0.1
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "cloudflare-dns.com"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 2a09::
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "dot.sb"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 2a11::
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "dot.sb"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 185.222.222.222
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "dot.sb"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:   - address_data: 45.11.45.11
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]:     tls_auth_name: "dot.sb"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: , "Generic error"
Wed Dec 22 21:28:32 2021 daemon.err stubby[9135]: Could not parse config file "/var/etc/stubby/stubby.yml": Generic error
```

### PR DESCRIPTION
**Pull request by mikhirev**
fixes #17421

Maintainer: @neheb, @jonathanunderwood

### CODE REVIEW

**Comment by neheb** [comment]
missing signed-off-by.

**Comment by mikhirev** [comment]
> missing signed-off-by.

I'm sorry, fixed.

**Comment by jonathanunderwood** [comment]
LGTM (but note: I am no longer maintaining the stubby package, #15853).

**Comment by BKPepe** [comment]
It requires to bump `PKG_RELEASE` in the `Makefile`.

**Comment by mikhirev** [comment]
> It requires to bump `PKG_RELEASE` in the `Makefile`.

Done.

**Comment by BKPepe** [comment]
Let's merge it. The CI failure is not relevant to this PR.

**Pull request merged**
