### PR TITLE
shadowsocks-libev: ss-rules: Add 'auto-merge' flag to avoid conflicts

### PR DESCRIPTION
**Pull request by crzidea**
Signed-off-by: Li Xin <i@crzidea.com>

Maintainer: @yousong 
Compile tested: ramips/mt7621 OpenWrt 22.03.2
Run tested: ramips/mt7621 OpenWrt 22.03.2
Description:

Need `auto-merge` flag to solve CIDR elements conflicts, example:
http://git.netfilter.org/nftables/commit/?id=30f667920601d01107398cbb85da45fdb1237212

### CODE REVIEW

**Comment by 1715173329** [comment]
Ping @yousong

**Comment by yousong** [comment]
I remember last time I checked it, `auto-merge` will cause the set refusing to accept plain ip addresses, e.g. `8.8.8.8` vs. `8.8.8.8/32`.  Is it still the case?

**Comment by crzidea** [comment]
> I remember last time I checked it, `auto-merge` will cause the set refusing to accept plain ip addresses, e.g. `8.8.8.8` vs. `8.8.8.8/32`. Is it still the case?

I have checked again, it does not cause the issue now. Below is just an evidence, just used nft to list the working ruleset, and `192.168.2.254` is working together with `auto-merge`:
```
# nft -a list ruleset | head
table inet fw4 { # handle 1
	set ss_rules_src_bypass { # handle 52
		type ipv4_addr
		flags interval
		auto-merge
		elements = { 192.168.2.50, 192.168.2.53,
			     192.168.2.254 }
	}

	set ss_rules6_src_bypass { # handle 53
```

**Comment by yousong** [comment]
@crzidea The new commit likely will fail the ci check for lacking Signed-off-by signature.  Consider just squashing them into a single commit.  Thank you.

**Comment by yousong** [comment]
Hi @crzidea , I squashed the two commits and the change is now at https://github.com/openwrt/packages/commit/8966f49f9a715e07527580c50ac29ae560447670 .  Thank you for your contribution.

**Comment by crzidea** [comment]
@yousong When will it be merged to 22.03? I noticed that the latest openwrt 22.03.5 is still with shadowsocks-libev-ss-rules 3.3.5-7.

**Comment by yousong** [comment]
> @yousong When will it be merged to 22.03? I noticed that the latest openwrt 22.03.5 is still with shadowsocks-libev-ss-rules 3.3.5-7.

I just did the cherry-pick.  Consider giving it a try ;)

**Comment by crzidea** [comment]
> > @yousong When will it be merged to 22.03? I noticed that the latest openwrt 22.03.5 is still with shadowsocks-libev-ss-rules 3.3.5-7.
> 
> I just did the cherry-pick. Consider giving it a try ;)

Still not on 22.03. Did you pushed to the branch openwrt-22.03? I checked [here](https://github.com/crzidea/openwrt-packages/blob/openwrt-22.03/net/shadowsocks-libev/files/ss-rules/set.uc).

**Comment by crzidea** [comment]
> > > @yousong When will it be merged to 22.03? I noticed that the latest openwrt 22.03.5 is still with shadowsocks-libev-ss-rules 3.3.5-7.
> > 
> > 
> > I just did the cherry-pick. Consider giving it a try ;)
> 
> Still not on 22.03. Did you pushed to the branch openwrt-22.03? I checked [here](https://github.com/crzidea/openwrt-packages/blob/openwrt-22.03/net/shadowsocks-libev/files/ss-rules/set.uc) and [here](https://openwrt.org/packages/pkgdata/shadowsocks-libev-ss-rules).

I see it is 3.3.5-8 now [here](https://openwrt.org/packages/pkgdata/shadowsocks-libev-ss-rules).

**Pull request closed without merging**
