### PR TITLE
crowdsec-firewall-bouncer: new upstream release version 0.0.26

### PR DESCRIPTION
**Pull request by ne20002**
Signed-off-by: S. Brusch <ne20002@gmx.ch>

Maintainer: Kerma Gérald <gandalf@gk2.net>
Run tested: ipq40xx/generic, Fritzbox 4040, Openwrt 22.03.5

Update crowdsec-firewall-bouncer to latest upstream release version 0.0.26
This is the backport/update for OpenWrt 22.03

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @erdoukki

**Comment by BKPepe** [comment]
Backport to the stable release should be use by cherry picking.

**Comment by ne20002** [comment]
@BKPepe 
If cherry picking is requierd I need to make new PR (no clue how to update an existing one with such a change).
As this is just a hash value update, is it really required?

**Comment by 1715173329** [comment]
It's not that strictly required but it would be nice to do so...

Simply checkout your local openwrt-22.03 branch, then run:
```
git reset --hard HEAD^
git cherry-pick -x 05bc30fbb2636e8ef12326847f07cc3d788dbf4a
git push -f
```

**Comment by ne20002** [comment]
Thx. Will do this evening after work.

**Comment by ne20002** [comment]
I messed it up. :(

**Pull request closed without merging**
