### PR TITLE
protobuf: Update to 3.6.1

### PR DESCRIPTION
**Pull request by neheb**
Added upstream patch to fix compilation.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @kenkeys 
Compile tested: ramips

### CODE REVIEW

**Comment by diizzyy** [comment]
@neheb 
Again, please state **clearly** what you've done or haven't done.
No runtime testing at all?

**Comment by neheb** [comment]
This is a library. I only recently started using mosh with it (not available here as the user submitting the pull request got pissed).

**Comment by neheb** [comment]
ping @kenkeys

**Comment by neheb** [comment]
Updated to 3.7.1. Current versions fails on a few targets: https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/protobuf/compile.txt

**Comment by neheb** [comment]
ping @kenkeys

**Comment by neheb** [comment]
Going to merge this. This has been tested on mvebu using mosh (not available here). Current version is failing on the buildbots: https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/protobuf/compile.txt

Hopefully this fixes it.

**Pull request merged**
