### PR TITLE
keepalived: add procd init format and UCI config parsing

### PR DESCRIPTION
**Pull request by commodo**
@psycho-nico 

As per PR https://github.com/openwrt/packages/pull/2069
The request was to split the package upgrade away from the UCI and procd changes.

This PR adds only those procd and UCI changes + the change to `alt_config_file` file, as discussed on that PR.
Later we can do a PR for upgrading keepalived.

Signed-off-by: Alexandru Ardelean ardeleanalex@gmail.com

### CODE REVIEW

**Comment by champtar** [comment]
ping @psycho-nico

**Comment by hnyman** [comment]
@commodo 
Looks like the current maintainer is not interested, any more. 
Care to take over maintainership?

**Comment by commodo** [comment]
Same reply as here: https://github.com/openwrt/packages/pull/2340#issuecomment-269856790

**Comment by commodo** [comment]
How should we proceed ?
Do I add myself in a PR ?
Shall I merge both PRs ?

As a note ; we've updated keepalived stuff internally [based on stuff that we found wrong] ; so some changes may be needed to this and the other PR.
So, I could re-spin a more complete PR, with all changes

**Comment by hnyman** [comment]
Whatever is easiest for you. One combined PR would be fine.

(but if the existing PRs are ok, let's merge them and then you can add one more where you take over maintainership and fix things.)

**Comment by commodo** [comment]
I'll combine them.
Thanks

**Comment by commodo** [comment]
superseded by https://github.com/openwrt/packages/pull/3727

**Pull request closed without merging**
