### PR TITLE
transmission-web-control: update to 1.6.1

### PR DESCRIPTION
**Pull request by JohnyXXX**
Maintainer: @ysc3839 
Compile tested: ARMv7, Netgear R7800, OpenWrt 21.02.0
Run tested: ARMv7, Netgear R7800, OpenWrt 21.02.0

Description: updating to the current release

### CODE REVIEW

**Comment by ysc3839** [comment]
LGTM, thanks!
Also I recommend you test the latest master branch of transmission-web-control. If nothing wrong with it, update to master instead of a release. Since that project hardly make a release, the latest release may contain bugs.

**Comment by JohnyXXX** [comment]
Made an update to the master branch. Did a successful test on my router.

**Comment by BKPepe** [comment]
Squash your changes to one single commit. You created 5 commits for just one change.

**Comment by JohnyXXX** [comment]
I will create a new PR

**Pull request closed without merging**
