### PR TITLE
smstools3: Update to 3.1.21

### PR DESCRIPTION
**Pull request by haraldg**
* bump to new upstream version
* remove some local patches that were merged upstream

Signed-off-by: Harald Geyer <harald@ccbib.org>

Maintainer: @erdoukki 
Compile tested: arm/mxs OpenWRT cabb0c506526fe468e4aa985086e50c440192122
Run tested: see above, using E1750 as modem

Description:

### CODE REVIEW

**Comment by hnyman** [comment]
@erdoukki 
any comments?

@haraldg 
You might update the Makefile to use sha256-based PKG_HASH field instead of old PKG_MD5SUM

**Comment by haraldg** [comment]
@hnyman 
I will do update you suggested. Also tried to contract @erdoukki via e-mail but didn't get a reply either for two weeks now. Do you think it is reasonable if I claim maintainership of the package in the updated PR?

**Comment by hnyman** [comment]
First "polite" step might be to add yourself as the second maintainer of the package.

**Comment by haraldg** [comment]
I have decided to do more updates (porting the init script to procd, etc) so closing this PR. I will open a new one when I'm ready. However I won't add myself as second maintainer: I don't want to be on a team with somebody who doesn't respond to my mails at all.

**Pull request closed without merging**
