### PR TITLE
Remove inadyn, portaudio and espeak from repo

### PR DESCRIPTION
**Pull request by diizzyy**
All these packages are missing maintainer(s) and no offers has been made to pick these up or even PRs to fix packages that fails to compile (espeak) or update.

### CODE REVIEW

**Comment by karlp** [comment]
As before, I see no reason to drop packages that are simply without maintainers.  BY all means drop a package without a maintainer that doesn't compile.

**Comment by thess** [comment]
How about packages which you (@diizzyy) used to be maintainer of (like tio, etc.) and which now no longer have one? Are these any different than absent maintainers?

**Comment by diizzyy** [comment]
@thess 
Yes, they're up to date (to my knowledge). As I said before, I'm not interested in being listed as a maintainer  but feel free to remove those if you want.

**Comment by diizzyy** [comment]
@karlp 
While I agree in general these doesn't really serve any purpose, being heavily outdated and/or doesn't build.

**Comment by thess** [comment]
Which ones don't build?  I'll see if there are any easy fixes. If not, I'll remove it. Otherwise, leave as-is.

**Comment by diizzyy** [comment]
Why do you want to packages that clearly abandoned upstream?
https://sourceforge.net/p/espeak/code/391/tree/trunk/

http://downloads.lede-project.org/snapshots/faillogs/mipsel_24kc/packages/espeak/compile.txt

**Comment by thess** [comment]
Will be closing this PR - need to resolve item 3 below

1. Fixed **espeak** builds via: #6907 (I want to keep lthis - it works) and therefore...
2. Updated **portaudio** to latest release via: #6908 (It does appear to be an active project).
3. **inadyn** was your package - why do you think it needs to be removed??

**Comment by diizzyy** [comment]
Since there were concerns about the lack of maintainers I figured that we could remove inadyn as nobody has stepped up and offered maintainership or actively updated it. I also asked @neheb which bumped it if he had any concerns with it being removed. I have no objections to keep it in there's a desire to do so.

**Pull request closed without merging**
