### PR TITLE
ntpdate: use uci configured servers instead of static list

### PR DESCRIPTION
**Pull request by karlp**
If we're going to have a list of ntp servers, we should at least respect
them.

Signed-off-by: Karl Palsson <karlp@etactica.com>

Maintainer: @tripolar 
We've carried this patch for years, just remembered it and wondered why we'd never submitted it upstream again.

### CODE REVIEW

**Comment by tripolar** [comment]
this patch doesn't check if the value is set and just sets it

take a look at https://github.com/openwrt/packages/blob/cf4f87f002a459f784262216158691674a993e24/net/ntpd/files/ntpd.init#L21

**Comment by neheb** [comment]
ping @karlp

**Comment by karlp** [comment]
ok, do you want to keep the static default list and use it if nothing's found in UCI?

**Comment by tripolar** [comment]
good idea

**Comment by karlp** [comment]
ok, updated.

**Comment by karlp** [comment]
Any further feedback? I can merge this myself after, say, July 3 if there's nothing further?

**Comment by mhei** [comment]
One drawback is, that it's not possible to disable ntpdate per uci. However, this was not possible before and it seems that nobody cared to far... so I think, just go ahead and merge it (I also think that 2-3 days additional comment time is enough here...)

**Comment by karlp** [comment]
@mhei in that case, you just don't install ntpdate.  And yes, very much out of scope of this commit IMO :)

**Comment by neheb** [comment]
This needs a PKG_RELEASE bump.

**Comment by karlp** [comment]
Anyone object to me putting this in 19.07 too?

**Comment by neheb** [comment]
No

**Comment by karlp** [comment]
will push it to 19.07 (as well) in a week or so when I'mback in the office again.

**Comment by karlp** [comment]
landed in 19.07 via 09609c73a55a21959 now too

**Pull request closed without merging**
