### PR TITLE
prometheus/collectd: adapt dependencies for the dsl collector 

### PR DESCRIPTION
**Pull request by dhewg**
This depends on https://github.com/openwrt/openwrt/pull/10586

It simplifies and cleans up the dependencies of consumers of the dsl ubus stats.

Maintainers: @champtar @jow- @hnyman 
I tested prometheus, but not collectd, so cc @jekkos @feckert

### CODE REVIEW

**Comment by feckert** [comment]
I have not tested it now. But I see nothing that would speak against it. I assume the ubus json format has not changed between vr9 and vr11

**Comment by jekkos** [comment]
I'm using the collectd already with vr11, so I already did this change locally otherwise I was not able to select the packages. It works so good to go.

**Comment by jekkos** [comment]
Actually I replaced vrx200 with this `@(TARGET_lantiq_xrx200||TARGET_ipq40xx)`

**Comment by feckert** [comment]
> Actually I replaced `@TARGET_lantiq_xrx200` with `@(TARGET_lantiq_xrx200||TARGET_ipq40xx)`
I like that better. Now you can see right away in the source for which targets this applies.

**Comment by dhewg** [comment]
Yeah, I had that too at first, but there're way more ipq40xx boards than those with a dsl chip.
With the patches here, the package is only selectable when the dsl daemon is available, which makes more sense to me.

**Comment by feckert** [comment]
@dhewg @jekkos Well then let's do it like this

**Comment by dhewg** [comment]
The PR this depends on has been merged, so this can go in too now. Thanks!

**Pull request merged**
