### PR TITLE
monit: update to the latest release

### PR DESCRIPTION
**Pull request by val-kulkov**
Maintainer: @champtar 
Compile tested: x86_64, OpenWrt SNAPSHOT r10713-796ad2f7ef
Run tested: x86_64, OpenWrt SNAPSHOT r10713-796ad2f7ef, IPv6 works fine (monit's ping6 is successful)

Description:

Remove SSL patch that has been made obsolete by upstream updates.

Update monit package to the latest release: v5.26.0. This release supports TLSv1.3 and fixes a few bugs and vulnerabilities.

Signed-off-by: Val Kulkov <val.kulkov@gmail.com>

### CODE REVIEW

**Comment by champtar** [comment]
Hi @val-kulkov 
Do we really need to patch configure / configure.ac ? can't we define `ac_cv_ipv6` or ... ?

**Comment by val-kulkov** [comment]
@champtar : I was getting "checking for IPv6... no" messages until I patched both configure and configure.ac. I chose to patch both, taking the easiest route. To be honest, I have little desire or time to dig deeply into the internals of monit's autoconfiguration scripts. Most likely it will require the amount of time that I simply do not have at present. Having said that, I would be happy to see someone clean up the autoconfiguration scripts and possibly even suggest a patch upstream.

**Comment by champtar** [comment]
see #9805

**Comment by champtar** [comment]
@val-kulkov please rebase (and remove your patch)

**Comment by val-kulkov** [comment]
@champtar : thanks for #9805. I have updated this PR, please review.

**Pull request merged**
