### PR TITLE
gpsd: Update init script

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @psidhu
Compile tested: armvirt-32, 2019-02-07 snapshot sdk
Run tested: none

Description:
This replaces the use of `uci_validate_section()` with `uci_load_validate()`, which removes the need to declare local variables for every config option.

This also adds a `service_triggers()` function and removes some unnecessary curly brackets.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I tried run-testing this, but as I don't have a GPS receiver, I only got as far as procd telling me the daemon crashed too many times.

**Comment by neheb** [comment]
ping @p-wassi

**Comment by karlp** [comment]
the service triggers sure, but removing {} ? why? this is just churn for the sake of it, and it's not even a good practice.

**Comment by jefferyto** [comment]
On devices with limited storage, every extra byte counts.

**Comment by neheb** [comment]
This looks fine to me. Merging.

**Pull request merged**
