### PR TITLE
tor: depend on libseccomp if KERNEL_SECCOMP is set

### PR DESCRIPTION
**Pull request by dangowrt**
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by champtar** [comment]
@hauke

**Comment by speedyb0y** [comment]
Shouldn't it be in the inverse way?
Make an option CONFIG_TOR_LIBSECCOMP..
Then make libseccomp depend on KERNEL_SECCOMP.

This way, configuring TOR will force the libseccomp, and libseccomp will force the kernel's support.
Instead of assuming the user wants every package to be compiled with seccomp just because he/she enabled it in the kernel...

**Comment by dangowrt** [comment]
@speedyb0y That's excatly what the +KERNEL_SECCOMP:libseccomp dependency does: Making tor depend on libseccomp if KERNEL_SECCOMP is enabled.

**Comment by speedyb0y** [comment]
Will it force the user to compile TOR using SECCOMP if it is enabled in the Kernel, or will let the user 
choose it if and only if it is enabled on the kernel?

(Development policy: if it is possible to run TOR without that enabled, let the user decide, even if that would be a bad idea)

Sorry for my bad english and for annoying you on a really little thing lol

**Comment by hauke** [comment]
SECCOMP only works on x86, amd64 and arm in tor. My plan is to deactivate SECCOMP in #1219  for now. I would like a patch which makes seccomp work on mips or a patch which activates it on supported targets when KERNEL_SECCOMP was set.

**Pull request closed without merging**
