### PR TITLE
django: bump to version 3.0.6

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/58bec0d172  x86
Run tested: https://github.com/openwrt/openwrt/commit/58bec0d172 x86

-------------------------------------------------------------

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
@peter-stadler 
would you be interested in being a co-maintainer on this package?
you seem to be interested in it a bit more than me;

**Comment by peter-stadler** [comment]
Thank you, I am happy if I can help. Although I am not as experienced and you are doing a great job, I see that it is a lot of work and I think I can take care of some parts. So I would be happy co-maintaining this package :-)

**Comment by commodo** [comment]
> Thank you, I am happy if I can help. Although I am not as experienced and you are doing a great job, I see that it is a lot of work and I think I can take care of some parts. So I would be happy co-maintaining this package :-)

Well, you'll see overtime, that maintaining some packages is not a big effort.
Django usually isn't.
But in my case I have plenty of python packages I maintain, and I feel like I should probably distribute them.

Now, in the past I would try to ask someone to completely take over a package, but that doesn't work.
What seems to work, is to propose a co-maintainer role, and see about maybe withdrawing at a later point in time.
I feel that I should say this now, so that things are clearer.
Naturally, this can happy in a few months, a few years. Let's see.
But I don't want to abandon packages just like that.

**Comment by commodo** [comment]
Changelog v1 -> v2:
* add `Peter Stadler <peter.stadler@student.uibk.ac.at>` as co-maintainer;

**Comment by peter-stadler** [comment]
This is good for me.

**Pull request merged**
