### PR TITLE
znc: update to 1.8.2

### PR DESCRIPTION
**Pull request by neheb**
Switch to CMake + Ninja to fix parallel compilation.

Switched PKG_BUILD_DIR to use PKG_INSTALL_DIR for easier readability.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @KanjiMonster 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
```
FAILED: modules/CMakeFiles/module_sample.dir/sample.cpp.o 
/home/build/build_dir/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/bin/mips-openwrt-linux-musl-g++ -Dmodule_sample_EXPORTS -Dznc_export_lib_EXPORTS -Iinclude -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -ffile-prefix-map=/home/build/build_dir/build_dir/target-mips_24kc_musl/znc-1.8.2=znc-1.8.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fPIC -fvisibility=hidden -include znc/zncconfig.h -std=c++11 -MD -MT modules/CMakeFiles/module_sample.dir/sample.cpp.o -MF modules/CMakeFiles/module_sample.dir/sample.cpp.o.d -o modules/CMakeFiles/module_sample.dir/sample.cpp.o -c modules/sample.cpp
mips-openwrt-linux-musl-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[38/145] Building CXX object modules/CMakeFiles/module_simple_away.dir/simple_away.cpp.o
FAILED: modules/CMakeFiles/module_simple_away.dir/simple_away.cpp.o 
/home/build/build_dir/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/bin/mips-openwrt-linux-musl-g++ -Dmodule_simple_away_EXPORTS -Dznc_export_lib_EXPORTS -Iinclude -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -ffile-prefix-map=/home/build/build_dir/build_dir/target-mips_24kc_musl/znc-1.8.2=znc-1.8.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fPIC -fvisibility=hidden -include znc/zncconfig.h -std=c++11 -MD -MT modules/CMakeFiles/module_simple_away.dir/simple_away.cpp.o -MF modules/CMakeFiles/module_simple_away.dir/simple_away.cpp.o.d -o modules/CMakeFiles/module_simple_away.dir/simple_away.cpp.o -c modules/simple_away.cpp
mips-openwrt-linux-musl-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
/home/build/build_dir/include/toplevel.mk:221: recipe for target 'package/znc/compile' failed
make: *** [package/znc/compile] Hangup
package/Makefile:112: recipe for target 'package/feeds/packages/znc/compile' failed
make[1]: *** [package/feeds/packages/znc/compile] Hangup
```

RAM problem on CircleCI.

**Comment by nmschulte** [comment]
@neheb Is it likely to see this (or any znc update) for the 19.x line?

**Comment by neheb** [comment]
Probably not. Why?

**Comment by nmschulte** [comment]
> Probably not. Why?

v21.02 is struggling on my hardware. Porting this to v19.07 seemed pretty straight forward so I figured to ask, but I don't know what becomes of the 19.07 line.

**Comment by neheb** [comment]
It'll soon be EOL

**Pull request merged**
