### PR TITLE
giflib: append package gif2rgb

### PR DESCRIPTION
**Pull request by AuroraRAS**
convert GIF to 24-bit RGB pixel triples or vice-versa.

Maintainer: me / @thess Ted Hess <thess@kitschensync.net>
Compile tested: (Atheros AR7161 rev 2, all, OpenWrt 18.06.4 r7808-ef686b7292)
Run tested: (Atheros AR7161 rev 2, NETGEAR WNDR3800, OpenWrt 18.06.4 r7808-ef686b7292, tests done)

Description: append package: gif2rgb

### CODE REVIEW

**Comment by neheb** [comment]
bump PKG_RELEASE please. Better yet, do a full package update (current version is 5.2.1).

**Comment by AuroraRAS** [comment]
> bump PKG_RELEASE please. Better yet, do a full package update (current version is 5.2.1).

I was trying bump version to 5.1.9 and 5.2.1, but I got this:
`
Package giflib is missing dependencies for the following libraries:
libc.so.6
`
look like something big changed with the library since 5.1.5, the old patches is no longer appropriate in there. Unfortunately, I don't know how to write a new patch in this case, maybe other contributors will help solve this problem in the future.

**Comment by neheb** [comment]
That error happens when compiling a package with the host compiler instead of the cross compiler.

I looked at it. Turns out the Makefile can be quite simplified as they got rid of the configure script.

Another thing: you're adding a single utility to its own package. Wouldn't it be better to make a package like giflib-utils with all of them?

Also see: https://github.com/neheb/packages/commit/35b6ba9d2948a08a4689cb36aaf324288ffdeb13

**Comment by AuroraRAS** [comment]
> That error happens when compiling a package with the host compiler instead of the cross compiler.
> 
> I looked at it. Turns out the Makefile can be quite simplified as they got rid of the configure script.
> 
> Another thing: you're adding a single utility to its own package. Wouldn't it be better to make a package like giflib-utils with all of them?
> 
> Also see: [neheb@0d6428f](https://github.com/neheb/packages/commit/0d6428f46e02a2fe103a2b6975120fa1a5c4cbed)

you right, giflib-utils is a better package. buildpr refuses me to use merge commits in request, maybe you should push your contribution firstly?

**Comment by neheb** [comment]
Well, I mentioned it so you could test. I don't think I use giflib. Anyway, I'll open a new pull request with similar changes.

**Comment by AuroraRAS** [comment]
> Well, I mentioned it so you could test. I don't think I use giflib. Anyway, I'll open a new pull request with similar changes.

Test passed.
env: Atheros AR7161 rev 2, NETGEAR WNDR3800, OpenWrt 18.06.4 r7808-ef686b7292

**Pull request closed without merging**
