### PR TITLE
apr-util: clean up reverse depends (and fix subversion dep)

### PR DESCRIPTION
**Pull request by micmac1**
subversion maintainer: @val-kulkov 
apr-util and apache maintainers: @heil & me
Compile tested: ath79 master
Run tested: ath79 19.07, tested subversion-client (checking out svn://svn.code.sf.net/p/pcapsipdump/code/trunk) as well as apache web server

Description:
Hi Val et al,

Currently packaging of subversion fails like this:

```
Package subversion-libs is missing dependencies for the following libraries:
libgdbm.so.6
liblber-2.4.so.2
libldap-2.4.so.2
libsqlite3.so.0
```

This is due to recent apr-util updates, where more functionality were added (mostly modular). libgdbm gets linked in automatically by apr-util users when libaprutil-dbm-gdbm is built. sqlite3 is no longer a dep of apr-util, so this needs to be added to subversion package.

The other libs (ldap, libiconv, expat) are not required by apr-util users (exception would be apache, but that works out fine). I've copied patches from Debian into apr-util that sort out apu-1-config to prevent the unnecessary rdepends.

Thanks!
Seb

### CODE REVIEW

**Comment by micmac1** [comment]
Hi all,

I checked the [Debian patches](https://sources.debian.org/src/apr-util/1.6.1-4/debian/patches/) again and realized that they have another patch which also turns off the DBM libs by default. So I added that as well. Now the cringy libgdbm depend isn't there anymore for apr-util users (unless explicitly requested).

This means that for subversion we only need to add the dep on libsqlite3.

Build and run-tested again on ath79 with both apache and subversion-client.

Kind regards,
Seb

**Comment by val-kulkov** [comment]
@micmac1 : were the updates to apr-util that broke subversion introduced before OpenWrt 19.07 was fixed or after? If they were introduced before, then we may have to backport your PR to 19.07 because subversion in 19.07 is probably broken.

I have not had a chance to look into this yet, but hope to get some time this weekend unless someone else checks this and fixes outstanding issues (if any).

**Comment by micmac1** [comment]
>@micmac1 : were the updates to apr-util that broke subversion
>introduced before OpenWrt 19.07 was fixed or after? If they were
>introduced before, then we may have to backport your PR to 19.07
>because subversion in 19.07 is probably broken.

Hi Val, the changes were introduced a few days ago, long time after 19.07 was branched. They added module support to apr-util, which is why the dependency on libsqlite3 wandered from libaprutil to libabrutil-dbd-sqlite3.

>I have not had a chance to look into this yet, but hope to get some
>time this weekend unless someone else checks this and fixes outstanding
>issues (if any).

Regarding 19.07. We're talking about backporting the changes to 19.07 in the not too distant future, in #10898 (see the few comments at the bottom). Because right now the apache webserver in 19.07 is still broken. In case we do we will ping you again, because in that case we would need to backport the subversion dependency fix as well.

**Comment by micmac1** [comment]
>Merged #11024 into master.

Thanks!

**Comment by val-kulkov** [comment]
> Regarding 19.07. We're talking about backporting the changes to 19.07 in the not too distant future, in #10898 (see the few comments at the bottom). Because right now the apache webserver in 19.07 is still broken. In case we do we will ping you again, because in that case we would need to backport the subversion dependency fix as well.

Gotcha, thanks for the update!

**Pull request merged**
