### PR TITLE
libpng: switch to CMake

### PR DESCRIPTION
**Pull request by neheb**
Allows simplification of the Makefile.

Remove no more needed patch.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jow- 
Compile tested: ath79

Setting this as a draft until I can test ARM NEON, Aarch64, and powerpc compilation.

### CODE REVIEW

**Comment by neheb** [comment]
Only powerpc is failing it seems. Disabled SIMD there.

**Comment by nobk** [comment]
target-mipsel_24kc_musl build error
```
[ 96%] Linking C executable pngfix
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_avg4_msa'
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_sub3_msa'
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_sub4_msa'
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_up_msa'
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_avg3_msa'
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_paeth3_msa'
/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libpng16.so.16.37.0: undefined reference to `png_read_filter_row_paeth4_msa'
collect2: error: ld returned 1 exit status
make[6]: *** [CMakeFiles/pngfix.dir/build.make:103: pngfix] Error 1
make[6]: Leaving directory '/build/openwrt/build_dir/target-mipsel_24kc_musl/libpng-1.6.37'
make[5]: *** [CMakeFiles/Makefile2:293: CMakeFiles/pngfix.dir/all] Error 2
make[5]: Leaving directory '/build/openwrt/build_dir/target-mipsel_24kc_musl/libpng-1.6.37'
make[4]: *** [Makefile:158: all] Error 2
make[4]: Leaving directory '/build/openwrt/build_dir/target-mipsel_24kc_musl/libpng-1.6.37'
make[3]: *** [Makefile:71: /build/openwrt/build_dir/target-mipsel_24kc_musl/libpng-1.6.37/.built] Error 2
make[3]: Leaving directory '/build/openwrt/feeds/packages/libs/libpng'
time: package/feeds/packages/libpng/compile#9.48#0.54#10.98
make[2]: *** [package/Makefile:113: package/feeds/packages/libpng/compile] Error 2
make[2]: Leaving directory '/build/openwrt'
make[1]: *** [package/Makefile:107: /build/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/build/openwrt'
make: *** [/build/openwrt/include/toplevel.mk:224: world] Error 2

```

**Comment by neheb** [comment]
Weird. I'll try to reproduce.

**Comment by nobk** [comment]
```
scripts/diffconfig.sh
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_mqmaker_witi=y

```

**Comment by neheb** [comment]
Hmmm sounds like it fails with mipsel but not MIPS. Weird.

**Comment by neheb** [comment]
Reproduced and fixed: https://github.com/openwrt/packages/pull/12719

**Pull request merged**
