### PR TITLE
ddns-scripts: various fixes

### LINKED ISSUE #7745: ddns-scripts: setup TTL with cloudflare api
Maintainer: @chris5560  (find it by checking history of the package Makefile)
Environment: OpenWrt 18.06

Description:
According to [Cloudflare's Documentation](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record), an dns record update without parameter `ttl` will have the TTL value of "automatic", It makes this record's TTL value grows over time, which is not suitable for a DDNS domain. For me, the TTL value has grow to 300 after updated one day before. It should be set to the minimum 120 seconds for the best experience, IMHO.

Previously I use zzzz.io which has a constant 60 seconds TTL but it will be shutdown on 2019 Q1, sadly.

### LINKED ISSUE #8971: ddns-scripts: error on startup
Maintainer: @\<github-user>
Environment: ddns-scripts - 2.7.8-1

Description: When using a read-only filesystem there is an error on startup of ddns, because in the file "dynamic_dns_functions.sh" in the function "get_service_data" there is the command "mkfifo pipe_$$" which causes the error. Moving the pipe to a temporary filesystem will solve this problem.

### PR DESCRIPTION
**Pull request by dibdot**
Maintainer: -
Compile tested: -
Run tested: -

Description:
* use '$ddns_rundir' in 'get_service_data' for pipe creation, fix #8971
* add missing local variables in 'get_service_data'
* change DNS server verification with drill in 'verify_host_port', fix/supersed #8935
* remove needless cat calls in 'verify_host_port'
* set cloudfare TTL to min. 120 seconds, fix #7745
* bump/align package version number

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by dibdot** [comment]
Please note: The changes are completely untested - I don't use this package. It would be nice if one or more users could test this.

Thanks!

**Comment by neheb** [comment]
Probably worthwhile to check with shellcheck. From a quick glance I see plenty of errors.

**Comment by dibdot** [comment]
> From a quick glance I see plenty of errors.

Maybe a little more specific would help ... anyway, feel free to close this one. It was just a "try-fix" of some of the problems of this unmaintained package.

**Comment by neheb** [comment]
Given that it's unmaintained, are there maintained alternatives here?

**Comment by dibdot** [comment]
@neheb I've rebased this PR and I did a minimal runtime test with noip.com. I think this is save to apply to master.

**Comment by neheb** [comment]
Works for me.

**Pull request merged**
