### PR TITLE
aria2: fix "Illegal instruction" crash on ar71xx

### PR DESCRIPTION
**Pull request by tripolar**
Signed-off-by: Peter Wagner <tripolar@gmx.at>

Maintainer: kuoruan@gmail.com
Compile tested: ar71xx
Run tested: ar71xx

Description: 
the lto optimization leads to an "Illegal instruction" crash on ar71xx

### CODE REVIEW

**Comment by tripolar** [comment]
@kaloz

**Comment by dengqf6** [comment]
Have you tried `PKG_USE_MIPS16=0` instead? It's likely to break things

**Comment by dengqf6** [comment]
Just tested with `PKG_USE_MIPS16=0` on my ar71xx, it ran without issues

**Comment by tripolar** [comment]
> Just tested with `PKG_USE_MIPS16=0` on my ar71xx, it ran without issues

fixed the crash too, i updated the PR

**Comment by cshoredaniel** [comment]
@neheb have you been getting stuff like: http://lists.infradead.org/pipermail/openwrt-devel/2019-January/015399.html

**Comment by neheb** [comment]
@cshoresaniel no.

I will look into this failure. I have a feeling it's due to missing declarations or some other warning.

**Pull request merged**
