### PR TITLE
hd-idle: Update to 1.05

### PR DESCRIPTION
**Pull request by neheb**
This is only a bugfix release for a huge amount of drives. This software seems to be abandoned. Might as well update to latest.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: Lim Guo Wei <limguowei@gmail.com> (@gwlim)
Compile tested: mvebu (LEDE trunk)

I don't think this needs a maintainer anymore.

### CODE REVIEW

**Comment by champtar** [comment]
Ping @gwlim
Hi @neheb 
The idea of maintainer is to know that we at least have 1 active user of the soft and that it's working

**Comment by diizzyy** [comment]
Perhaps it's better to drop it in that case since hdparm also does this?

**Comment by jow-** [comment]
@diizzyy hd-idle is a service, periodically trying to spin down drives while hdparm is a one shot command.

**Comment by diizzyy** [comment]
Using -B -S switches for hdparm would do the same thing without the need to a daemon/spawning process. This application seems to be mainly designed for IDE devices in USB-cases and we can probably count those users on one hand? All according to the authors website http://hd-idle.sourceforge.net/ I think we can safely assume that only supporting APM-capable devices is good enough?

**Comment by jow-** [comment]
I am a user of IDE disks in an USB case connected to my LEDE device.

**Comment by thess** [comment]
Also, it has been know to work on some USB<->SATA chipsets when hdparm does not. I say keep them both. (Merging...)

**Comment by gwlim** [comment]
The problem I have with HD-IDLE is that it is obselete
A lot of new harddisk drives already comes with sleep mode to comply with Energy Efficient ratings.
Even if harddisk drives do not have this the Newer USB to SATA Controllers do.
This is really only applicable for very old HDDs

**Comment by diizzyy** [comment]
@gwlim 
I agreed but as you can tell by the reasoning above :)

**Pull request merged**
