### PR TITLE
xtables-addons: Update to 3.19

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: @jow- 
Compile tested: x86_64, generic, HEAD (236c3ea730)
Run tested: same, installed on production edge router

Description:

Update to 3.19

### CODE REVIEW

**Comment by pprindeville** [comment]
3.13 is now more than 14 months old at this point.

**Comment by aparcar** [comment]
Looks good to me but Jo is the maintainer, you could ask if you can take over?

**Comment by pprindeville** [comment]
> Looks good to me but Jo is the maintainer, you could ask if you can take over?

With the transition to `firewall4` and `nft`, how pertinent will this remain?

**Comment by pprindeville** [comment]
@jow- Can I please get a determination on this?

**Comment by neheb** [comment]
Funny. I made https://github.com/openwrt/packages/pull/18226

I would cherry pick that last commit.

**Comment by pprindeville** [comment]
Superseded by PR #18226.

**Pull request closed without merging**
