### PR TITLE
nginx: bump version and fix bug 

### LINKED ISSUE #11610: nginx: can't handle large firmware to upgrade
Maintainer: @Ansuel 
Environment: OpenWrt master

Description:
When I upload a large firmware to upgrade, the UI stuck at 100% and there was an error in system log
```
daemon.err nginx[5127]: 2020/03/21 00:53:40 [error] 5154#0: *117 client intended to send too large body: 18382143 bytes, client: 10.0.0.2, server: _lan, request: "POST /cgi-bin/cgi-upload?1584723219331 HTTP/1.1", host: "10.0.0.1", referrer: "https://10.0.0.1/cgi-bin/luci/admin/system/flash"
```

### PR DESCRIPTION
**Pull request by Ansuel**
This fix #11610 by increasing max client body size
in nginx conf.
Bump nginx to latest version.

@hnyman 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by dengqf6** [comment]
FYI 1.17.9 is available

**Comment by Ansuel** [comment]
ok i will update then...

**Comment by Beaverfffan** [comment]
Can you increase max client body size to a bigger size?Now many router rom can be larger than 128m

**Comment by Beaverfffan** [comment]
with only docker installed,the firmware have been 90m.near 128m limit

**Pull request merged**
