### PR TITLE
nut: fix cgi/gd setup

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @cshoredaniel 
Compile tested: master/ath79
Run tested: N/A

Description:
Hi all,

Saw the issue report. I don't use nut, so no run-testing from me :)

Regards,
Seb

### CODE REVIEW

**Comment by neheb** [comment]
Weird. master works just fine for me. I’ll look inti this.

**Comment by neheb** [comment]
Ah I see instead of fixing the package directly you're passing pkg-config parameters in the Makefile.

I guess that's cleaner.

I noticed that there's C++ being compiled. Any idea what that's about?

My OpenSSL patch also needs refreshing. There's an off by 1 warning.

**Comment by micmac1** [comment]
Will check tonight.

**Comment by cshoredaniel** [comment]
On my to do list.  Thanks.

**Comment by stintel** [comment]
This fixes https://github.com/openwrt/packages/issues/10641

**Comment by micmac1** [comment]
Hi @neheb 

c++ is used for libnutclient which isn't packaged. Didn't find a configure switch do turn it off.

Refreshed the OpenSSL patch and added nut-web-cgi pkg to PKG_CONFIG_DEPENDS.

Kind regards,
Seb

P.S.: Didn't see you updated your comments and mentioned the OpenSSL patch. Let me add that, too.

**Comment by micmac1** [comment]
Done now.

**Comment by neheb** [comment]
Hmm? What happened to the second patch?

**Comment by micmac1** [comment]
It's in the first.

**Comment by neheb** [comment]
Ah ok

**Comment by neheb** [comment]
I just merged a libgd pkgconfig fix. Is this still needed?

**Comment by micmac1** [comment]
Well the patch 010-libgd-pkgconfig.patch is still wrong. As mentioned in the first commit message the test doesn't add up. And on 2nd look the CFLAGS line below it is missing an equal sign as well.

You could fix the patch. But why use a patch when we can fix via configure args. That's my opinion at least.

Kind regards,
Seb

**Comment by cshoredaniel** [comment]
I agree with @micmac1 -- I'd rather use what works without patching than have an patch that I don't see any reason to consider 'better' than using configure arguments.

**Comment by cshoredaniel** [comment]
Will try to get to this next week.

**Comment by cshoredaniel** [comment]
FYI I've finally got some time to work on this starting now, and over the next few days.

**Comment by cshoredaniel** [comment]
Ok, I've run-tested this on x86-64 (three VMS, one each for CGI, Monitor and Server).  NUT is working well (logread on the other hand was hanging for some reason, but there is not reason to believe that is connected to NUT).  The server used the dummy-ups driver and was accessible by the monitor and CGI instances, which correctly access the server (and CGI serves up it's info properly as well).

@neheb @hnyman So I'm good for this to be merged.

**Comment by hnyman** [comment]
> (logread on the other hand was hanging for some reason, but there is not reason to believe that is connected to NUT).

Yep, not connected. 
logread is hanging due to a bad ubus version bump yesterday. See the developer mailing list for discussion on that. 
@ynezz has already a fix for some of the symptoms, but the fix is not yet merged.

**Pull request merged**
