### PR TITLE
transmission: Backport 2.93 to LEDE 17.01

### PR DESCRIPTION
**Pull request by neheb**
A lot of fixes are in here. Should be useful for the .5 release.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: me
Compile tested: mvebu

### CODE REVIEW

**Comment by karlp** [comment]
This also 
* changes the maintainer
* changes default config
* changes the way it's built
* probably more

None of that is even mentioned in the commit note here, and if you're considering pushing things to stable branches those sorts of things should at the very least be _explained_

**Comment by neheb** [comment]
1: Irrelevant
2: Fairly irrelevant. config needs to be changed due to new transmission policies.
3: It goes from git to release. No real difference, except that the git version should have never been in the tree.

**Comment by mwarning** [comment]
@neheb I assume you have copied the current package from master to the lede-17.01 branch only?

**Comment by neheb** [comment]
@mwarning it's equivalent to https://github.com/openwrt/packages/pull/5879 for 17.01

It was requested that 2.93 be backported as it has a security fix.

**Comment by neheb** [comment]
Irrelevant now

**Pull request closed without merging**
