### PR TITLE
[19.07] vpn-policy-routing: update to 0.3.5-1

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: me
Compile tested: x86_64, Sophos SG-105, 21.02.0-rc3
Run tested: x86_64, Sophos SG-105, 21.02.0-rc3, start/stop

Description:
support for 21.02.0-rc2 and up
support for reloading a single interface on ifup/ifupdate
rename config file
updated shellcheck compatibility
remove obsolete create/remove_lock
interface processing optimizations to speed up reloads
drop dependency on curl in user scripts
uniform styling of functions

Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by BKPepe** [comment]
Why this is going into OpenWrt 19.07? It should receive bug fixes, security issues and so on. Your feature "support for 21.02.0-rc2 and up" does not seems to be necessary to be included in 19.07.

**Comment by stangri** [comment]
> Why this is going into OpenWrt 19.07? It should receive bug fixes, security issues and so on. Your feature "support for 21.02.0-rc2 and up" does not seems to be necessary to be included in 19.07.

While the support for 21.02.0-rc2 is not relevant for 19.07, the rest of the updates are and I'd prefer to have the single code base for the package across all branches. Also, I don't see the reason to deprive 19.07 users of the new features.

If buildbots are still running for 19.07, what's the harm of merging this? I've had feature PRs merged into stable before without any issues.

**Comment by wulfy23** [comment]
https://github.com/openwrt/packages/pull/11800#issue-400482956

**Comment by stangri** [comment]
@jow- @aparcar @neheb could you please advise if this can still be merged despite the two platforms build fail or if I need to do something to rectify it? Is there any way I can cause a rebuild without force-pushing a meaningless change?

PS. Even tho I've got the merge rights for luci pretty quickly, I've been asking for merge rights for packages for over a year now, can someone please explain to me what the process is and what should I do get things moving?

**Comment by BKPepe** [comment]
> While the support for 21.02.0-rc2 is not relevant for 19.07, the rest of the updates are and I'd prefer to have the single code base for the package across all branches. Also, I don't see the reason to deprive 19.07 users of the new features.

I just want to avoid a situation that happened in the past, when you need to release a bugfix release quickly because it was not tested properly. Bugs slips, that's ok, but you are asking the wrong question. Why OpenWrt 19.07 does not receive new features at all? Because it receives bugfixes, hotfixes that appear to make it stable for others. You are introducing so many changes about your package, which can be unstable. That's the same reasoning, why new devices are not supported in OpenWrt 19.07 release.  We had the same conversation in your last PR https://github.com/openwrt/packages/pull/15817

**Comment by stangri** [comment]
As @wulfy23 pointed out, non-bug fixing PRs still get merged into 19.07, including mine (except for this and last commits). This has been the case for [18.06](https://github.com/pulls?q=is%3Apr+author%3Astangri+sort%3Acreated-asc+in%3Atitle+18.06) and [19.07](https://github.com/pulls?q=is%3Apr+author%3Astangri+sort%3Acreated-asc+in%3Atitle+19.07) alike.

If you're concerned about the quality of the code/testing, I don't mind if the release PRs are merged let's say a month after the master/dev branch PRs are merged.

**Comment by BKPepe** [comment]
It is not good to reference one and half-year-old PR when there was no branch-off for OpenWrt 21.02. You pointed out the link for 19.07, and I looked at three pages, there, and I see that you created so many PRs against 19.07 even if it is stable. 

This means that your software changes a lot, so there is no possibility to have the stable version and if you want to have some `security fixes`, `bugfixes`, then do it as a patch and backport it. There is no wrong about it similarly, how it is done in OpenWrt 19.07. What if you introduce any API compatibility change?

I can see it same as **LTS x stable** versions e.g., subversion does it.

As you said, the same version should not go simultaneously to other branches as well. I don't mind releasing it so often if it is tested and maintained.

**Comment by wulfy23** [comment]
when ideals trump pragmatism we have a serious problem. applying sane principles inconsistently wreaks of hypocrisy...derived from maintainer staffing issues? give the man commit and let him learn from some mistakes instead of walk away from the project after waiting 6 weeks to have a PR that addresses bugs caused by upstream commits...

1. long term contributor
2. active contributor
3. quality functional packages

has no right to be treated in this manner...

**Comment by aparcar** [comment]
@stangri based on @neheb feedback I added you to the committers.

> has no right to be treated in this manner...

OpenWrt is managed by volunteers, it's not like an evil council which decides to treat people poorly but a bunch of people trying to maintain a complex project, please keep that in mind.

**Comment by aparcar** [comment]
Please follow the "trickle down" approach suggested by others. If it survives the development branch for a week, create a PR for the pre-release, give it another week to backport to stable. To keep things simple please only open backport PRs once the development commit worked out fine.

I've done some hasty backports in the past which turned out to be flawed in some corner cases and thereby made a fool of myself, just trying to prevent this happening to you :)

**Pull request closed without merging**
