### PR TITLE
usbip: Switch usb.ids location to match usbutils

### PR DESCRIPTION
**Pull request by neheb**
It's versioned and therefore easier to update.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @nunojpg 
Compile tested: ramips

### CODE REVIEW

**Comment by diizzyy** [comment]
This seems like a rather wasteful solution?
Just depend on the usbutils package and install a symbolic link, doing so will save about ~150kbyte (roughly estimated). The best solution would be to break out the database as a separate package in the end however.

**Comment by neheb** [comment]
It is duplicated yes.

Adding a new package is probably beyond the scope of this pull request.

**Comment by diizzyy** [comment]
Instead of adding another copy of it, please depend on usbutils for now?

**Comment by nunojpg** [comment]
I got lost in the comments. So basically this is a improvement, but in the future I should apply @diizzyy idea.

**Pull request merged**
