### PR TITLE
sqm-scripts: Update Makefile

### PR DESCRIPTION
**Pull request by DocMAX**
remove +kmod-sched-cake-virtual

### CODE REVIEW

**Comment by feckert** [comment]
Please sign off your commit and add a valid header for your commit message.
For example:
`sqm-scripts: remove kmod-sched-cake-virtual dependency`

**Comment by hnyman** [comment]
What are your reasons for this proposal of removing cake dependency?

I do not see very likely that the cake dependency would be removed from SQM.


cc @tohojo @ldir-EDB0

**Comment by tohojo** [comment]
Yeah, what @hnyman said - what's the rationale for this?

**Comment by DocMAX** [comment]
Create index file './feeds/telephony.index'
WARNING: Makefile 'package/feeds/packages/sqm-scripts/Makefile' has a dependency on 'kmod-sched-cake-virtual', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.

**Comment by hnyman** [comment]
> WARNING: Makefile 'package/feeds/packages/sqm-scripts/Makefile' has a dependency on 'kmod-sched-cake-virtual', which does not exist

You should not reveice that warning, as the SQM scripts only contains that dependency in master, where the new kmod-sched-cake-virtual also exists.

You should only receive that if you
* have dirty, unupdated repo
* try to use master packages with 19.07 OpenWrt

**Comment by DocMAX** [comment]
you are right. i have a dirty tree. sorry, closed.

**Pull request closed without merging**
