### PR TITLE
[18.06]git: fix cross compilation on macOS

### PR DESCRIPTION
**Pull request by jpc**
Maintainer: @tripolar
Compile & run tested: OpenWRT 18.06 target-aarch64_cortex-a53_musl NanoPi Neo Core 2

Based on: http://lists.busybox.net/pipermail/buildroot/2016-May/161696.html

Signed-off-by: Mauro Condarelli <mc5686@mclink.it>
Signed-off-by: Jakub Piotr Cłapa <jpc@loee.pl>

### CODE REVIEW

**Comment by jpc** [comment]
Is this something that may be merged into 18.06 or should I resubmit against master?

**Comment by neheb** [comment]
Yes, submit against master first.

**Comment by BKPepe** [comment]
ping @jpc

**Comment by neheb** [comment]
Merging since this is just a host compile fix.

**Pull request merged**
