### PR TITLE
Massive perl update

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @pprindeville @Naoir

### CODE REVIEW

**Comment by BKPepe** [comment]
Needs to be run tested.

**Comment by neheb** [comment]
I meant to post this as a draft. Oh well.

**Comment by DittelHome** [comment]
Perl-device-usb and perl-inline got problems
ttps://downloads.openwrt.org/releases/faillogs-18.06/mips_24kc/packages/

**Comment by neheb** [comment]
I've tried fixing those previously. I'm out of ideas.

**Comment by BKPepe** [comment]
Was it run tested?

**Comment by neheb** [comment]
Just compile. I don’t want this to sit here and rot.

**Pull request merged**
