### PR TITLE
haproxy: Update patches for HAProxy v2.0.8 + migrate to procd

### PR DESCRIPTION
**Pull request by gladiac1337**
Maintainer: Thomas Heil <heil@terminal-consulting.de>, Christian Lachner <gladiac@gmail.com>
Compile tested: mips, ipq806x, x86
Run tested: ipq806x (r7800)

Description: Update HAProxy to v2.0.8
- Add new patches (see https://www.haproxy.org/bugs/bugs-2.0.8.html)
- Migrated init-script to procd.
- Removed the old hotplug script as it is unnecessary and caused long boot-times for r7800 and possibly others.

### CODE REVIEW

**Comment by yousong** [comment]
This can break things if it's neither wan nor lan it's waiting for.

How about converting into using procd and waiting on `interface.update` event with `procd_add_raw_trigger`

**Comment by gladiac1337** [comment]
Alright, I already had "looking into procd" on my todo list - I will migrate to it in the coming days.

**Comment by karlp** [comment]
@gladiac1337 you left irc far too quickly for feedback this morning!  For your stop/reload service actions, use the procd signal methods instead of pid files: 
```
reload_service() {
         procd_send_signal service_name [instance_name] [signal]
}
```
Details on https://openwrt.org/docs/guide-developer/procd-init-scripts

**Comment by karlp** [comment]
I'm not sure why you need a raw trigger either.  Surely procd_add_interface_trigger should be sufficient?

**Comment by gladiac1337** [comment]
@yousong @karlp I just force-pushed the new init. Also, I got rid of the hotplug-script as it is totally unnecessary.

**Pull request merged**
