### PR TITLE
Fix for seg-fault when "large packet" is captured

### PR DESCRIPTION
**Pull request by polachz**
Maintainer: @mmaraya
Compile tested: Turris Omnia, ARM (but problem is generic)
Run tested: Turris Omnia, ARM (but problem is generic)

Description:

The tool port-mirroring can't handle correctly captured packets with packet size > 2048. For example it occurs when generic receive offloading assembles several packets together.

* In TEE capturing mode, it caused Segmentation Fault because fixed buffer with size 2048 is used for re-send captured packet and no check if data fit the buffer is provided, then code writes behind the buffer border.
* In TZSP mode packet is stripped on 2000 bytes by size check but no crash occurs.

I have prepared a patch for the 1.4.2 version (see attachment) , used in Turris Omnia, and OpenWRT. This patch checks packet size and realloc the buffer if necessary. Of course here is question how pcap re-inject modified packet back to capturing interface (from brief check i do not see any big issues in wireshark capture), but anyway the patch solves the Seg Fault problem

### CODE REVIEW

**Comment by karlp** [comment]
Please change the commit header to include the package name

**Comment by diizzyy** [comment]
I'd rather see this go upstream and PKG_RELEASE should be bumped

**Comment by polachz** [comment]
> 
> 
> I'd rather see this go upstream and PKG_RELEASE should be bumped

What I can do with this PACKAGE version, please ?

**Comment by diizzyy** [comment]
Just change PKG_RELEASE to 2

**Comment by neheb** [comment]
@polachz please rebase against current master and bump PKG_RELEASE.

**Comment by diizzyy** [comment]
Closing due to timeout, upstream is at 1.4.4

**Pull request closed without merging**
