### PR TITLE
upmpdcli/libupnpp: Update to latest versions, refresh patch

### PR DESCRIPTION
**Pull request by thess**
upmpdcli: Version 1.1.3
libupnpp: Version 0.14

@ignisf - OK?

Signed-off-by: Ted Hess <thess@kitschensync.net>

### CODE REVIEW

**Comment by ignisf** [comment]
Hi, @thess, this looks fine for a version bump, however I'm not sure it's enough to have the Radio feature @schmurtzm mentioned.

From the changelog: 

> Implement an OpenHome Radio source for playing Internet radio streams (**needs Python**).

https://github.com/medoc92/upmpdcli/blob/master/src/ohradio.cxx#L230 seems to be calling out a python script.

Do the files from this directory https://github.com/medoc92/upmpdcli/tree/master/rdpl2stream get installed? They should probably be installed in a manner similar to the SongCast web interface with a python dependency.

**Comment by thess** [comment]
As soon as Python becomes a dependency, we will probably have other issues. I will look into making an option to include the python parts dependent on the selection of Python (or vice-versa). The default needs to be a thin client.

**Comment by ignisf** [comment]
You think having it define like [that](https://github.com/thess/OpenWrt-packages/blob/84bc16198f1da1460e988a0d63266dd94f814818/sound/upmpdcli/Config.in#L9-L17) might cause issues?

**Comment by thess** [comment]
It looks like everything you mention builds and is installed correctly including the Python depedencies. My remark about Python was not correct in this case since it is already handled as part of the SongCast web server option (I missed that before - sorry).

If you have no objection, I'll merge this and perhaps @schmurtzm can check it out.

**Comment by ignisf** [comment]
:+1:

**Comment by thess** [comment]
@schmurtzm - I'm afraid you will need to build this package in the CC trunk yourself. If that is too much, perhaps someone can help you with your sound driver issues. Have you submitted a bug-report on it somewhere?

The main reason for an error such as you are seeing is usually the wrong libc (uLibC / Musl, etc) is present or a missing load module. It's very unlikely that packages built on the current trunk will run on CC.

**Comment by schmurtzm** [comment]
OK, I have used an external USB sound card to make my tests. 

Compiled successfully, it works. But I don't find how to add python2 ,so there's no radios.

```
src/httpfs.cxx:205::Failed reading /usr/share/upmpdcli/icon.png : open/stat: errno: 2 : No such file or directory
src/ohradio.cxx:67::OHRadio: python2 not found, no radio service will be created
```

With my USB sound card the sound is bad 1time/2  but it comes from MPD. May be there is some tuning to do on MPD or soundcard to have good sound each time I start a track.
By the way MPR ver 0.19.15 (2016/04/30) is available ;)

**Comment by thess** [comment]
I will look at this over the weekend. In the future, please open an issue rather than just tacking you remarks onto a closed PR - TIA

**Comment by thess** [comment]
@schmurtzm - followup on your issue(s).  Final

1. The missing icon file is wrongly installed as upmpdcli.png. For now rename it to icon.png. I will update the package shortly.

2. Missing Python - try installing it (python2 should be linked to python2.7)

3.  I don't think updating MPD will resolve your sound problem(s). Test with aplay?

**Pull request merged**
