### PR TITLE
gitolite: Update to 3.6.8

### PR DESCRIPTION
**Pull request by neheb**
Switched to codeload to simplify the Makefile.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @cshoredaniel 
Compile tested: ipq806x

### CODE REVIEW

**Comment by cshoredaniel** [comment]
@neheb NAK: https://github.com/openwrt/packages/pull/6659 already takes care of update and a couple of other things, and for codeload I haven't seen a discussion of this as desired course of action.  That kind of change, especially since you're clearly doing it for many packages ought to be discussed on openwrt-devel and and issues in the openwrt/packages github before trying to go in through the back door.

**Comment by neheb** [comment]
Ah didn't see the other PR.

**Comment by cshoredaniel** [comment]
@neheb Hey looks like folks are perfectly fine with codeload in packages feed, so if you feel inclined to update this package I won't NAK codeload.

**Comment by neheb** [comment]
It's fine.

**Pull request closed without merging**
