### PR TITLE
gpsd: bump to 3.23

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @psidhu (no maintainer given in scons' Makefile)
Compile tested: 21.02 SDK ath79
Run tested: 21.02 rc4 ath79. I installed the packages and ran gpsd (with "-F" argument) and also gpsdctl. But that's really it, I don't have a gps receiver to test with.

Description:
Version bump with fix for issue #16272 

Kind regards,
Seb

### CODE REVIEW

**Comment by micmac1** [comment]
Updated commit message twice.

**Comment by neheb** [comment]
ping @jefferyto

**Comment by neheb** [comment]
What's wrong with scons btw?

**Comment by neheb** [comment]
Please run

```
shfmt -w -sr -s files/gpsd.init
```

this may or may not become a requirement. See https://github.com/openwrt/openwrt/pull/4300

**Comment by micmac1** [comment]
> What's wrong with scons btw?

Currently it depends only on "lots-of-luck". It has the shebang set to python in $(STAGING_DIR_HOST), which doesn't exist. So the build host will likely run scons with the host's python (that's what happened here on Debian). But if the host python doesn't have python distutils installed it'll fail:

```
ModuleNotFoundError: No module named 'distutils.util':
  File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/gpsd-3.23/SConstruct", line 67:
    variant_dir=variantdir,
  File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/lib/scons/SCons/Script/SConscript.py", line 661:
    return method(*args, **kw)
  File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/lib/scons/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/lib/scons/SCons/Script/SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/gpsd-3.23/gpsd-3.23/SConscript", line 12:
    import distutils.util   # for distutils.util.strtobool()
```

Using python3/host cleans this up.

**Comment by micmac1** [comment]
> Please run
> 
> ```
> shfmt -w -sr -s files/gpsd.init
> ```
> 
> this may or may not become a requirement. See [openwrt/openwrt#4300](https://github.com/openwrt/openwrt/pull/4300)

I don't have the tool "shfmt". Debian doesn't seem to have a package for it.

**Comment by neheb** [comment]
> > What's wrong with scons btw?
> 
> Currently it depends only on "lots-of-luck". It has the shebang set to python in $(STAGING_DIR_HOST), which doesn't exist. So the build host will likely run scons with the host's python (that's what happened here on Debian). But if the host python doesn't have python distutils installed it'll fail:
> 
> ```
> ModuleNotFoundError: No module named 'distutils.util':
>   File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/gpsd-3.23/SConstruct", line 67:
>     variant_dir=variantdir,
>   File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/lib/scons/SCons/Script/SConscript.py", line 661:
>     return method(*args, **kw)
>   File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/lib/scons/SCons/Script/SConscript.py", line 598:
>     return _SConscript(self.fs, *files, **subst_kw)
>   File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/lib/scons/SCons/Script/SConscript.py", line 287:
>     exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
>   File "/home/sk/tmp/sdk/openwrt-sdk-21.02.0-rc4-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/gpsd-3.23/gpsd-3.23/SConscript", line 12:
>     import distutils.util   # for distutils.util.strtobool()
> ```
> 
> Using python3/host cleans this up.

Right, there are a bunch of distutils patches here in order to avoid such breakage.

**Comment by neheb** [comment]
> > Please run
> > ```
> > shfmt -w -sr -s files/gpsd.init
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this may or may not become a requirement. See [openwrt/openwrt#4300](https://github.com/openwrt/openwrt/pull/4300)
> 
> I don't have the tool "shfmt". Debian doesn't seem to have a package for it.

Hrm unfortunate. Looks like those plans will be halted.

**Comment by jefferyto** [comment]
> It has the shebang set to python in $(STAGING_DIR_HOST), which doesn't exist.

`python` should always exist in `$(STAGING_DIR_HOST)/bin` (and a symlink to build-host Python), it is a [pre-build requirement](https://github.com/openwrt/openwrt/blob/master/include/prereq-build.mk#L159). If it doesn't exist then your build root has other issues.

> But if the host python doesn't have python distutils installed it'll fail:

This is the purpose of 0001-no-distutils-import.patch, to remove the need for distutils. If you change 0001-no-distutils-import.patch by:

* Patching SConscript instead of SConstruct
* Patch out [`import distutils.util`](https://gitlab.com/gpsd/gpsd/-/blob/release-3.23/SConscript#L12) and the one use of [`distutils.util.strtobool()`](https://gitlab.com/gpsd/gpsd/-/blob/release-3.23/SConscript#L1326-1327) (I think you can just do `config.env['manbuild'] = 0` to disable building documentation)

then it should work.

**Comment by micmac1** [comment]
> > It has the shebang set to python in $(STAGING_DIR_HOST), which doesn't exist.
> 
> `python` should always exist in `$(STAGING_DIR_HOST)/bin` (and a symlink to build-host Python),

Actually no, it does not :)

> it is a [pre-build requirement](https://github.com/openwrt/openwrt/blob/master/include/prereq-build.mk#L159). If it doesn't exist then your build root has other issues.
>

While Python is a requirement, distutils isn't explicitly named to be fair (except for Debian which I use, evidently I didn't check this wiki page to the fullest, my bad).
 
> > But if the host python doesn't have python distutils installed it'll fail:
> 
> This is the purpose of 0001-no-distutils-import.patch, to remove the need for distutils.

Yes, but on the other hand we point the scons shebang to an Openwrt-provided python (although the shebang is currently broken). The author must've thought this is good idea. And more importantly, we have a working python host package that provides everything required, in the same repository even. Fourteen packages already depend on it/use it. So why shouldn't scons.

> If you change 0001-no-distutils-import.patch by:
> 
>     * Patching SConscript instead of SConstruct
> 
>     * Patch out [`import distutils.util`](https://gitlab.com/gpsd/gpsd/-/blob/release-3.23/SConscript#L12) and the one use of [`distutils.util.strtobool()`](https://gitlab.com/gpsd/gpsd/-/blob/release-3.23/SConscript#L1326-1327) (I think you can just do `config.env['manbuild'] = 0` to disable building documentation)
> 
> 
> then it should work.

Why bother putting your time into maintaining a patch that is a crutch when you can take advantage of a feature that is already in OpenWrt.

This is my opinion on the matter.

Kind regards,
Seb

**Comment by jefferyto** [comment]
> Actually no, it does not :)

Your build root is broken - I strongly suggest you do a fresh checkout of the main repo / redownload the SDK. Once you do any build-related command (e.g. `./scripts/feed update -a`), the python/python3 symlinks in `staging_dir/host/bin` will point to your build host / system Python.

> While Python is a requirement, distutils isn't explicitly named to be fair (except for Debian which I use, evidently I didn't check this wiki page to the fullest, my bad).

distutils is a standard part of a Python installation, every Python program can expect to have it be available. It is Debian that decided to create a non-standard, "minimal" Python (python3-minimal) for their default install.

> Why bother putting your time into maintaining a patch that is a crutch when you can take advantage of a feature that is already in OpenWrt.

As one of the Python maintainers here, nothing would make me happier than to have every other package use host Python (`python3/host`) instead of system Python. In this case though, I favour system Python because building host Python takes a non-trivial amount of time. Instead of one person spending the time to maintain this patch (which btw I have already done the work of figuring out what needs to be updated), every person building any package that depends on scons has to pay the time cost of building host Python.

**Comment by micmac1** [comment]
Looks like our opinions differ.

Anyway, if this is the general consensus feel free to close this PR.

Kind regards,
Seb

**Comment by dhewg** [comment]
quick & dirty
```
diff --git a/include/prereq-build.mk b/include/prereq-build.mk
--- a/include/prereq-build.mk
+++ b/include/prereq-build.mk
@@ -170,6 +170,10 @@ $(eval $(call SetupHostCommand,python3,Please install Python >= 3.6, \
    python3.6 -V 2>&1 | grep 'Python 3', \
    python3 -V 2>&1 | grep -E 'Python 3\.[6-9]\.?'))
 
+$(eval $(call TestHostCommand,python3-distutils, \
+   Please install the Python3 distutils module, \
+   $(STAGING_DIR_HOST)/bin/python3 -c 'import distutils'))
+
 $(eval $(call SetupHostCommand,git,Please install Git (git-core) >= 1.7.12.2, \
    git --exec-path | xargs -I % -- grep -q -- --recursive %/git-submodule))
 
```

**Comment by jefferyto** [comment]
@dhewg you can try submitting a patch to the main repo, but AFAIK nothing there depends on distutils so there may be a lack of interest.

**Comment by dhewg** [comment]
Done, let's see:
http://patchwork.ozlabs.org/project/openwrt/patch/20210810102217.22013-1-a.heider@gmail.com/

**Comment by dhewg** [comment]
The patch landed on master, so scons can keep building with the host python

**Comment by micmac1** [comment]
scons commit removed, gpsd commit updated.

**Comment by micmac1** [comment]
Looks like the CI host doesn't have distutils installed. I'd type a big smiley face now, but I won't.

**Comment by dhewg** [comment]
Hehe, don't worry, the irony doesn't escape us ;)
No clue about the CI setup here though

**Comment by jefferyto** [comment]
@dhewg you may also want your patch to be applied to the openwrt-21.02 branch. I assume this change (gpsd 3.23) will be cherry picked into openwrt-21.02 at some point.

**Comment by dhewg** [comment]
@micmac1 the CI setup should now have distutils available, maybe rebase and force push to retry?

**Comment by micmac1** [comment]
Hi @dhewg 

Good job on your part. Thanks!

**Comment by dhewg** [comment]
Oh, I merely reported it on irc. Glad to see it resolved ;)

**Comment by dhewg** [comment]
@jefferyto is that going to happen? I'm not sure if a "maybe" is enough to get this cherry-picked?

**Comment by jefferyto** [comment]
@dhewg The openwrt-21.02 branch still has [gpsd 3.21](https://github.com/openwrt/packages/blob/openwrt-21.02/utils/gpsd/Makefile#L11) which has a [serious issue](https://lwn.net/Articles/865044/) that will be triggered in October. This PR (gpsd 3.23) has the bug fix.

Either this PR will need to be cherry picked into openwrt-21.02 or the package in that branch will need to be upgraded/fixed some other way. I assume @micmac1 will take action soon as they opened this PR and the original issue here (#16272).

With the distutils "issue" resolved in master, I assume new packages/PRs here will no longer include distutils workarounds for Debian going forward. Since 21.02 has still not been released, I also assume people will want these new packages/PRs to apply to the openwrt-21.02 branch as well.

**Pull request merged**
