### PR TITLE
miniupnpc: Update to 2.1.20190408

### PR DESCRIPTION
**Pull request by neheb**
Switched to CMake.

Added PKG_LICENSE information

Rearranged some stuff for consistency between packages.

Added some linked flags for smaller size. Saves around 500 bytes on MIPS.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @sbyx ???
Compile tested: ramips
Run tested: GnuBee PC1 with Transmission

### CODE REVIEW

**Comment by diizzyy** [comment]
Patches submitted upstream?

**Comment by neheb** [comment]
The first is OpenWrt specific. The second is ??? The third can be upstreamed.

**Comment by diizzyy** [comment]
Please submit the third upstream, LGTM otherwise

**Comment by neheb** [comment]
https://github.com/miniupnp/miniupnp/pull/366

**Pull request merged**
