### PR TITLE
ddns-scripts: Change protocols of afraid.org urls to HTTPS.

### PR DESCRIPTION
**Pull request by gram25gwh**
Signed-off-by: Kwonjin Jeong <gram25gwh@gmail.com>

Maintainer: @chris5560
Compile tested: ar71xx-generic, TP-Link Archer C7 AC1750(KR), 19.07.0-rc1
Run tested: ar71xx-generic, TP-Link Archer C7 AC1750(KR), 19.07.0-rc1

Description:
Use HTTPS protocol of updating urls for afraid.org to protect the password.

### CODE REVIEW

**Comment by neheb** [comment]
Needs a PKG_RELEASE bump.

**Comment by gram25gwh** [comment]
> Needs a PKG_RELEASE bump.

I didn't bump the version since I'm not a package maintainer of net/ddns-scripts and it's the first contribution for me.
I'll add the bump commit soon if that's no problem.

**Comment by gram25gwh** [comment]
> Needs a PKG_RELEASE bump.

Done and all checks have passed.

**Comment by tigerw** [comment]
Unfortunately this seems to have broken my updater on a default 18.06.2 install?

    uclient-fetch Error: '1'
    /bin/uclient-fetch: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.

**Comment by neheb** [comment]
Just install libustream-ssl

**Pull request merged**
