### PR TITLE
libs/glib2: cleanup

### PR DESCRIPTION
**Pull request by yegorich**
Maintainer: @tripolar
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: only compile tested

Description: clean up package recipe and patches.

* remove the obsolete option `force_posix_threads`
* remove an already upstreamed patch
* remove pcre2 fallback workaround

### CODE REVIEW

**Comment by neheb** [comment]
it seems static pcre2 was fixed as well. Please remove the fallback from host build.

**Comment by yegorich** [comment]
Done.

**Comment by yegorich** [comment]
Looks like we will be able to get rid of the packaging patch in 2.82.x: https://gitlab.gnome.org/GNOME/glib/-/commit/38faeca62ebd5be89b1ec3e6c530e499ce2d7240

**Comment by yegorich** [comment]
@neheb what particular MIPS target should I take to reproduce the failure that led to the `006-c99.patch` patch?

**Comment by neheb** [comment]
That patch was a small size improvement I believe.

**Comment by yegorich** [comment]
OK. I see.

**Pull request merged**
