### PR TITLE
unbound: Update to 1.20.0

### PR DESCRIPTION
**Pull request by Ra2-IFV**
Maintainer: @EricLuehrsen
Compile tested: aarch64 generic 5be9a8790c62a6dca7a4547cd306f54d9bb812d9
Run tested: aarch64 generic 5be9a8790c62a6dca7a4547cd306f54d9bb812d9

Description:
Previous faulty PR: https://github.com/openwrt/packages/pull/24364

### CODE REVIEW

**Comment by Ra2-IFV** [comment]
Should I merge master branch🤔

**Comment by 1715173329** [comment]
these changes should be done in a single commit.

> Should I merge master branch🤔

1. Not required if there's no conflict.
2. Do rebase, not merge.

**Comment by 1715173329** [comment]
1. These changes should be done in a single commit
2. If you removed patch(es), please explain why in commit message.

**Comment by Ra2-IFV** [comment]
Commit rebased and updated.
Thanks, thanks again for your guidance. There are lots of things to learn more than the contributing guide ;)

**Comment by hardfalcon** [comment]
Why does this PR contain a change to `utils/lvm2/patches/900-support-gcc14.patch`?

**Comment by Ra2-IFV** [comment]
Removed the wrong file.
Another tip: do not always use `git add .`, use `git status` more often :(

**Pull request merged**
