### PR TITLE
node: use default host install prefix

### PR DESCRIPTION
**Pull request by NeoRaider**
Maintainer: @blogic
Compile tested: LEDE r1737
Run tested: Affects host builds only, modules using host npm build fine.

I could probably just merge this... oh well, let's make sure all maintainers see that I'm touching their packages.

### CODE REVIEW

**Comment by nxhack** [comment]
I think, need to add

`include $(INCLUDE_DIR)/host-build.mk`

**Comment by NeoRaider** [comment]
Indeed, this will be necessary, thanks for finding this issue. I'll update the PR accordingly.

**Comment by NeoRaider** [comment]
Updated. I've decided to avoid the additional include and just removed the absolute path, the host bin directories are in PATH anyways.

**Comment by nxhack** [comment]
Is it means uses cross-compile host's npm?

**Comment by NeoRaider** [comment]
LEDE and OpenWrt add `$(STAGING_DIR_HOST)/bin` and `$(STAGING_DIR)/host/bin` to the front of the path for package builds so they are preferred. As the packages have `node/host` as build depends, there will be our version of npm in `$(HOST_BUILD_PREFIX)/bin` (which is equivalent to `$(STAGING_DIR)/host/bin` at the moment), and we will always use the correct version.

**Comment by nxhack** [comment]
roger!

**Pull request merged**
