### PR TITLE
zabbix: update to 5.0 LTS

### PR DESCRIPTION
**Pull request by ttocsr**
Updated to 5.0 LTS version.

Removed 120-uclibc-res.patch
Frontend moved from frontend to ui
zabbix-proxy added libevent dependencie

Compile tested: aarch64 cortex-a53
Run tested: aarch64 cortex-a53

Signed-off-by: Scott Roberts <ttocsr@gmail.com>

### CODE REVIEW

**Comment by champtar** [comment]
Nice, I started in ##12293, but never got time to test it
You just need to refresh the patches `make package/zabbix/refresh V=s`

**Comment by champtar** [comment]
Can you squash the 2 commits ?

**Comment by ttocsr** [comment]
Thanks, should be all fixed up.
I should mention I tested with musl and glibc.

**Comment by cdaher78** [comment]
I'm having some issues to make Zabbix Proxy service to work.

**_Package: zabbix-proxy 5.0.1-2
OpenWrt SNAPSHOT r14955-a4d52522c7 on Raspberry Pi 4_**
 
Does it work with Sqlite3 or it only work with Postgres or MySQL?
It seems it doesn't create the db on /tmp. 
Do I have to create it by myself or it creates automatically? Is there a schema to import?

**zabbix_proxy.log**

  1596:20201126:131909.024 Starting Zabbix Proxy (active) [RPB-ROUTER]. Zabbix 5.0.1 (revision c2a0b03480).
  1596:20201126:131909.025 **** Enabled features ****
  1596:20201126:131909.025 SNMP monitoring:        NO
  1596:20201126:131909.025 IPMI monitoring:        NO
  1596:20201126:131909.025 Web monitoring:         NO
  1596:20201126:131909.025 VMware monitoring:      NO
  1596:20201126:131909.025 ODBC:                   NO
  1596:20201126:131909.025 SSH support:            NO
  1596:20201126:131909.025 IPv6 support:          YES
  1596:20201126:131909.025 TLS support:            NO
  1596:20201126:131909.025 **************************
  1596:20201126:131909.026 using configuration file: /etc/zabbix_proxy.conf
  1596:20201126:131909.026 In zbx_load_modules()
  1596:20201126:131909.026 End of zbx_load_modules():SUCCEED
  1596:20201126:131909.027 In init_database_cache()
  1596:20201126:131909.027 In zbx_mem_create() param:'HistoryCacheSize' size:16777216
  1596:20201126:131909.027 valid user addresses: [0x7fba029168, 0x7fbb028ff0] total size: 16776840
  1596:20201126:131909.027 End of zbx_mem_create()
  1596:20201126:131909.027 In zbx_mem_create() param:'HistoryIndexCacheSize' size:4194304
  1596:20201126:131909.027 valid user addresses: [0x7fb9c29178, 0x7fba028ff0] total size: 4193912
  1596:20201126:131909.027 End of zbx_mem_create()
  1596:20201126:131909.028 End of init_database_cache()
  1596:20201126:131909.028 In init_configuration_cache() size:8388608
  1596:20201126:131909.028 In zbx_mem_create() param:'CacheSize' size:8388608
  1596:20201126:131909.028 valid user addresses: [0x7fb9429168, 0x7fb9c28ff0] total size: 8388232
  1596:20201126:131909.028 End of zbx_mem_create()
  1596:20201126:131909.029 End of init_configuration_cache()
  1596:20201126:131909.029 In init_selfmon_collector()
  1596:20201126:131909.029 init_selfmon_collector() size:8792
  1596:20201126:131909.029 End of init_selfmon_collector() collector:0x7fbb1f7000
  1596:20201126:131909.030 In zbx_db_get_database_type()
  1596:20201126:131909.030 In DBconnect() flag:0
  1596:20201126:131909.031 [Z3001] connection to database '/tmp/zabbix_proxy' failed: [0] could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused

**file /etc/init.d/zabbix_proxy**

```
#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/usr/sbin/zabbix_proxy
CONFIG=/etc/zabbix_proxy.conf
PID=/tmp/zabbix_proxy.pid

start_service() {
        # Sometimes the proxy config was installed in /etc/zabbix/zabbix_proxy.conf
        [ -f /etc/zabbix/zabbix_proxy.conf ] && mv /etc/zabbix/zabbix_proxy.conf ${CONFIG}

        [ -f ${CONFIG} ] || return 1

        procd_open_instance
        procd_set_param command ${PROG} -c ${CONFIG} -f
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
```

**Pull request merged**
