### PR TITLE
ieee8021xclient: fix depends

### PR DESCRIPTION
**Pull request by zxlhhyccc**
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by feckert** [comment]
Please sign of your work and add also a valid commit message.
Unfortunately, I don't see the difference in the change. Maybe you could write what you are doing and what the problem is.

**Comment by hnyman** [comment]
> Unfortunately, I don't see the difference in the change. Maybe you could write what you are doing and what the problem is.

I will answer to that...

The problem is this, visible in master buildroot:

```
perus@ub2104:/Openwrt$ make defconfig
WARNING: Makefile 'package/feeds/packages/ieee8021xclient/Makefile' has a dependency on 'wpa_supplicant', which does not exist
```

The proposed fix is to correct the package spelling:
There is no wpa_supplicant, while there is wpa-supplicant.

Reference to the original PR #15983, discussion #16525  and the first faulty fix #16527

However, the proposed fix apparently creates a circular dependency...  (possibly due to the CONFLICTS statements in the hostapd Makefile)

```
perus@ub2104:/Openwrt$ make defconfig
tmp/.config-package.in:114611:error: recursive dependency detected!
tmp/.config-package.in:114611:	symbol PACKAGE_wpa-supplicant is selected by PACKAGE_wpa-supplicant-mesh-openssl
tmp/.config-package.in:114665:	symbol PACKAGE_wpa-supplicant-mesh-openssl depends on PACKAGE_wpa-supplicant
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```

Ps. the package Makefile is missing PKG_VERSION. Not sure if that is really needed, but I have never before seen a package where the only version is `$(AUTORELEASE)`

**Comment by ptpt52** [comment]
it seems this changes cause more issue?
```
Collecting package info: done
tmp/.config-package.in:128215:error: recursive dependency detected!
tmp/.config-package.in:128215:	symbol PACKAGE_wpa-supplicant is selected by PACKAGE_wpa-supplicant-mesh-openssl
tmp/.config-package.in:128269:	symbol PACKAGE_wpa-supplicant-mesh-openssl depends on PACKAGE_wpa-supplicant
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```

**Comment by neg2led** [comment]
Yup, recursive dependency.

Issue here is that you can't just depend on `wpa-supplicant=y` because that's not actually always provided, and even when it is sometimes it's `=m`

Current output we get in tmp/.config-package.in contains this:
```
config PACKAGE_ieee8021xclient
    tristate "ieee8021xclient....................... Wired 802.1x client config support"
    default y if DEFAULT_ieee8021xclient
    default m if ALL
    select PACKAGE_hostapd-utils
    select PACKAGE_libpthread if USE_GLIBC
    select PACKAGE_libc
    depends on PACKAGE_hostapd||PACKAGE_hostapd-basic||PACKAGE_hostapd-basic-openssl||PACKAGE_hostapd-basic-wolfssl||PACKAGE_hostapd-mini||PACKAGE_hostapd-openssl||PACKAGE_hostapd-wolfssl||PACKAGE_wpad||PACKAGE_wpad-mesh-openssl||PACKAGE_wpad-mesh-wolfssl||PACKAGE_wpad-basic||PACKAGE_wpad-basic-openssl||PACKAGE_wpad-basic-wolfssl||PACKAGE_wpad-mini||PACKAGE_wpad-openssl||PACKAGE_wpad-wolfssl
    select PACKAGE_librt if USE_GLIBC
    help
        Wired 802.1x client config support in /etc/config/network.
        David Yang <mmyangfl@gmail.com>
```

Which... does not work great. 

It seems changing to `DEPENDS:= @(PACKAGE_wpa_supplicant||PACKAGE_wpad)` will accomplish what we want to accomplish, without causing recursive dependencies? Having the `+` in there causes it to try and select the wpa-supplicant package when selected, which isn't really something you can do with so many options for supplicant provider.

(for that matter, why are we using wpa-supplicant for _wired_ 802.1x auth? I'm sure there's a good reason, but...)

TBH, if this is dependent on `wpad` or `wpa-supplicant`, it feels like this would do better to be folded into the main hostapd makefile, where the `DEPENDS:=@$(subst $(space),||,$(foreach pkg,$(SUPPLICANT_PROVIDERS),PACKAGE_$(pkg)))` macro (used for wpa-cli for example) could be used.

Buuuut I am not familiar enough with the idiosyncrasies of the OpenWRT build system (or what the actual dependencies are here) so I may be entirely wrong?

**Comment by nelgin** [comment]
Any update on this? it looks like it was broken more than a week ago. I just did a pull and trying to compile and, obviously, it's broken still. 

Thanks.

**Comment by yoyojacky** [comment]
hi there, I have same issue too. 
I am trying to build openwrt on my Raspberry Pi 4 CM4 module as a router, and i have already clone the latest version of openwrt via github.
* Hardware: Raspberry Pi  4 Computer module lite.
* my compile os is : Raspbian GNU/Linux 10 (buster)
* my kernel version is : Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
* GCC version: gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
after install the compile environment packages, I executed following commands:
```
git clone --depth=1 https://github.com/openwrt/openwrt
cd openwrt/
./scripts/feeds update -a
./scripts/feeds install -a
```
but encount this error message:
```
pi@raspberrypi:~/openwrt/openwrt $ ./scripts/feeds update -a
Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git' ...
Already up to date.
Updating feed 'luci' from 'https://git.openwrt.org/project/luci.git' ...
Already up to date.
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
Already up to date.
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
Already up to date.
Create index file './feeds/packages.index'
Create index file './feeds/luci.index'
Create index file './feeds/routing.index'
Create index file './feeds/telephony.index'
pi@raspberrypi:~/openwrt/openwrt $ ./scripts/feeds install -a
WARNING: Makefile 'package/feeds/packages/ieee8021xclient/Makefile' has a dependency on 'wpa_supplicant', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
```
and i am trying to ignore it , and i ran:
```
make menuconfig 
make V=s -j1
```
it shows this error message:
```
Configuring kmod-spi-dev.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency wpa_supplicant for ieee8021xclient
 * pkg_hash_fetch_best_installation_candidate: Packages for ieee8021xclient found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package ieee8021xclient.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/pi/openwrt/openwrt'
make[1]: *** [package/Makefile:111: /home/pi/openwrt/openwrt/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/pi/openwrt/openwrt'
make: *** [/home/pi/openwrt/openwrt/include/toplevel.mk:230: world] Error 2
```
How can i sovle this problem ? i have already installed wpasupplicant package but no luck.  
BTW, I've tried remove the `ieee8021xclient` from feeds/packages folder, and remove `tmp`  folder and `make clean all` and then execute :
```
git pull
./scripts/feeds update -a
./scripts/feeds install -a
```
the `Warning` message appears again, and it could not compile successfully anymore, Could you please figure it out?

**Comment by neg2led** [comment]
Short-term, you can just edit `<repo>/feeds/packages/net/ieee8021xclient/Makefile` and change

```
DEPENDS:=+wpa_supplicant
```
to
```
DEPENDS:=+wpad
```
(essentially manually reverting #16527)

**Comment by hnyman** [comment]
> It seems changing to DEPENDS:= @(PACKAGE_wpa_supplicant||PACKAGE_wpad) will accomplish what we want to accomplish, without causing recursive dependencies? Having the + in there causes it to try and select the wpa-supplicant package when selected, which isn't really something you can do with so many options for supplicant provider.

This sounds like the best idea so far.
(Assuming that the hyphen mistake in package name is corrected. wpa-supplicant

**Comment by yoyojacky** [comment]
> hi there, I have same issue too.
> I am trying to build openwrt on my Raspberry Pi 4 CM4 module as a router, and i have already clone the latest version of openwrt via github.
> 
> * Hardware: Raspberry Pi  4 Computer module lite.
> * my compile os is : Raspbian GNU/Linux 10 (buster)
> * my kernel version is : Linux raspberrypi 5.10.17-v7l+ [vnstat: fix musl compatibility #1414](https://github.com/openwrt/packages/pull/1414) SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
> * GCC version: gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
>   after install the compile environment packages, I executed following commands:
> 
> ```
> git clone --depth=1 https://github.com/openwrt/openwrt
> cd openwrt/
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> ```
> 
> but encount this error message:
> 
> ```
> pi@raspberrypi:~/openwrt/openwrt $ ./scripts/feeds update -a
> Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git' ...
> Already up to date.
> Updating feed 'luci' from 'https://git.openwrt.org/project/luci.git' ...
> Already up to date.
> Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
> Already up to date.
> Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
> Already up to date.
> Create index file './feeds/packages.index'
> Create index file './feeds/luci.index'
> Create index file './feeds/routing.index'
> Create index file './feeds/telephony.index'
> pi@raspberrypi:~/openwrt/openwrt $ ./scripts/feeds install -a
> WARNING: Makefile 'package/feeds/packages/ieee8021xclient/Makefile' has a dependency on 'wpa_supplicant', which does not exist
> Installing all packages from feed packages.
> Installing all packages from feed luci.
> Installing all packages from feed routing.
> Installing all packages from feed telephony.
> ```
> 
> and i am trying to ignore it , and i ran:
> 
> ```
> make menuconfig 
> make V=s -j1
> ```
> 
> it shows this error message:
> 
> ```
> Configuring kmod-spi-dev.
> Collected errors:
>  * pkg_hash_check_unresolved: cannot find dependency wpa_supplicant for ieee8021xclient
>  * pkg_hash_fetch_best_installation_candidate: Packages for ieee8021xclient found, but incompatible with the architectures configured
>  * opkg_install_cmd: Cannot install package ieee8021xclient.
> make[2]: *** [package/Makefile:70: package/install] Error 255
> make[2]: Leaving directory '/home/pi/openwrt/openwrt'
> make[1]: *** [package/Makefile:111: /home/pi/openwrt/openwrt/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_install] Error 2
> make[1]: Leaving directory '/home/pi/openwrt/openwrt'
> make: *** [/home/pi/openwrt/openwrt/include/toplevel.mk:230: world] Error 2
> ```
> 
> How can i sovle this problem ? i have already installed wpasupplicant package but no luck.
> BTW, I've tried remove the `ieee8021xclient` from feeds/packages folder, and remove `tmp` folder and `make clean all` and then execute :
> 
> ```
> git pull
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> ```
> 
> the `Warning` message appears again, and it could not compile successfully anymore, Could you please figure it out?

I figure it out, modify ieee8021xclient's makefile from `wpa_supplicant` to `wpa-supplicant` will solve this problem.

**Comment by azgh** [comment]
I had the same problem with compiling for nano pi R2S.
```WARNING: Makefile 'package/feeds/packages/ieee8021xclient/Makefile' has a dependency on 'wpa_supplicant', which does not exist
```

**Comment by neg2led** [comment]
OK, I've opened another PR (#16640) which has the necessary (temporary?) patch fix discussed above. Apply it to your local tree if you need a temporary fix for this issue.

**Comment by neheb** [comment]
Different solution was chosen.

**Comment by nelgin** [comment]
Whatever was done has now broken the build in a different way.

nigel@wibble:~/openwrt$ make menuconfig
tmp/.config-package.in:126453:error: recursive dependency detected!
tmp/.config-package.in:126453:  symbol PACKAGE_wpa-supplicant is selected by PACKAGE_wpa-supplicant-mesh-openssl
tmp/.config-package.in:126507:  symbol PACKAGE_wpa-supplicant-mesh-openssl depends on PACKAGE_wpa-supplicant
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

I'll probably open a new report on that.

**Comment by neheb** [comment]
That's unrelated to this PR.

**Pull request closed without merging**
