### PR TITLE
collectd: update to version 5.7.1

### PR DESCRIPTION
**Pull request by hnyman**
@jow- @cshoredaniel 

I have updated collectd (for LuCI statistics from 5.5.3 to 5.7.1)

The version update itself goes easily and all plugins compile with 5.7.1, but the network encryption feature that was added by @cshoredaniel with https://github.com/openwrt/packages/commit/ad7147839cdf8ea84d094693d007357df7bd00c4 proves problematic. Something has changed between 5.5.3 and 5.7.1 and I could not get it compiled/linked without changes to the Makefile.

For that reason I have included two commits, one for the version update itself, and another containing the modification for the encryption feature. After that modification all plugins compile with/without the encryption selected. 

The encryption option is a bit strange as it is defined on the collectd package top level, but it should only affect the network plugin (where is has had a dependency for libgcrypt).

I have not used the encrypted network feature myself, but hopefully Daniel could test it and see it the change works also for you. I am wondering if my change is overkill, as it adds a libgcrypt dependency and LDFLAGS option to the collectd itself in case the encryption is selected.

Compile-tested all plugins with ipq806x, typical plugins also with ar71xx.
Run-tested 10 usual plugins ( Conntrack, Processor, CPU Frequency, Entropy, Interfaces, Wireless, System, Load, Memory, Ping, Thermal)

    Update collectd to version 5.7.1
    
    * replace 003-remove-werror.patch with configure option
    * remove 200-fix-git-describe-error.patch that is now unnecessary
       (as the "git describe" is only run if inside a git repo)
    * reformat other patches due to whitespace changes
       (they have run some code beautifier...)
    * add new plugins to the list as disabled
    
    * correct download & homepage links
    * add myself as the second maintainer

### CODE REVIEW

**Comment by hnyman** [comment]
@cshoredaniel 
Any chance that you might test the network encryption thing here?

> I have not used the encrypted network feature myself, but hopefully Daniel could test it and see it the change works also for you. I am wondering if my change is overkill, as it adds a libgcrypt dependency and LDFLAGS option to the collectd itself in case the encryption is selected.

**Comment by cshoredaniel** [comment]
@hnyman I will work on it; I've barely been on the computer over the past 2-3 weeks but I will try to work on this this week.

**Comment by cshoredaniel** [comment]
Actually let's remove the encryption option for now; I'd briefly used it but then stopped using collectd for a while and when I started using it again I never did the networking of data again (TBH I'm not all that huge a fan of collectd's network plugin for transferring statistics data; nor really of the rrd backend, but just haven't gotten interested enough to work on a better replacement (e.g. centralized nosql-type database and larger chunks of data instead of a constant stream of little data).

**Comment by hnyman** [comment]
@jow- 
Any objections?

I updated the PR with a third commit that removes the encrypted network plugin functionality that was added a few months ago. I propose to leave all three commits, so that the history and the last working encrypted config can be seen more easily in future in case that functionality is returned at some point.

Compile-tested all plugins with ipq806x and ar71xx.
Run-tested 10 usual plugins ( Conntrack, Processor, CPU Frequency, Entropy, Interfaces, Wireless, System, Load, Memory, Ping, Thermal)

**Comment by jow-** [comment]
@hnyman - fine with me

**Pull request merged**
