### PR TITLE
libartnet: Remove

### PR DESCRIPTION
**Pull request by neheb**
This package fails compilation as it errors on a false strncpy length
parameter under GCC9.

This package is also unmaintained as well as dead upstream. Instead of
keeping it on life support, kill it.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @FriedZombie

### CODE REVIEW

**Comment by neheb** [comment]
Forgot to mention that nothing uses this.

**Comment by feckert** [comment]
@neheb should we not move deprecated and unmaintained package into the https://github.com/openwrt/packages-abandoned?

**Comment by neheb** [comment]
Yes of course.

**Comment by neheb** [comment]
Placed in abandoned. Removing.

**Pull request merged**
