### PR TITLE
libevdev: bump to 1.6.0

### PR DESCRIPTION
**Pull request by eduardoabinader**
Maintainer: @danwrt 
Compile tested: ar71x
Run tested: ar71x

Description:

### CODE REVIEW

**Comment by hnyman** [comment]
cc @dangowrt

**Comment by eduardoabinader** [comment]
any news? @hnyman @champtar

**Comment by hnyman** [comment]
Well, I would have hoped that @dangowrt would have reacted.

**Comment by dangowrt** [comment]
Thanks! and sorry for the delay...

**Pull request merged**
