### PR TITLE
nano: Update to 2.8.6

### PR DESCRIPTION
**Pull request by jp-bennett**
Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>

Maintainer: me
Compile/Run tested: Lede x86_64 kvm

### CODE REVIEW

**Comment by jp-bennett** [comment]
The fails on the CI test are extremely minor.  I can re-work the pull if needed.

**Comment by champtar** [comment]
Hi @jp-bennett,
Please do rework the commit, the checks are just enforcing the contributing guidelines

**Comment by jp-bennett** [comment]
@champtar I've amended the commit to take care of those issues.  Should be ready to pull.

**Comment by champtar** [comment]
thanks

**Pull request merged**
