### PR TITLE
 libupnp: downgrade to 1.8.6

### PR DESCRIPTION
**Pull request by neheb**
The newer libupnp is causing problems with libupnpp. While the latter has
migraded to using a different library, it still has support for older
libupnp. Keep using it.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
fails in the same way as libcxx. Surprising.

**Comment by neheb** [comment]
Decided to downgrade libupnp instead.

Amusingly, newer versions of libupnpp do not compile even with this.

**Comment by karlp** [comment]
*laughs*  This is the sort of thing that happens when you compile test only :)

**Comment by neheb** [comment]
The issue was a compilation one though.

**Pull request merged**
