### PR TITLE
python-egenix-mx-base: Makefile polishing

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @dtrefilo-Quest
Compile tested: cortexa53, Turris MOX, OpenWrt master
Run tested: cortexa53, Turris MOX, OpenWrt master

Description:
- more Makefile polishing than in https://github.com/openwrt/packages/pull/9478

### CODE REVIEW

**Comment by neheb** [comment]
Honestly in the last one, the eglibc thing caught my eye. I didn't look much further.

As you said, Python 2 will be EOL soon. I wouldn't spend much time on it.

**Comment by jefferyto** [comment]
If this package will be transitioned to Python 3 then these changes may make it easier :man_shrugging: 

One minor thing I would add: the SPDX identifier for the [eGenix.com Public License](https://spdx.org/licenses/eGenix.html) is just `eGenix`.

Otherwise LGTM :+1:

**Comment by BKPepe** [comment]
Thanks. I thought that it was corrected in the previous PR, but it was not, so now it's should be. ;-)

**Comment by cotequeiroz** [comment]
> 
> 
> Thanks. I thought that it was corrected in the previous PR, but it was not, so now it's should be. ;-)

That just proves @neheb was having a bad day yesterday. :rofl:

**Pull request merged**
