### PR TITLE
travelmate: Add h-reward hotel wifi autologin

### PR DESCRIPTION
**Pull request by Forceu**
Signed-off-by: Marc Bulling @forceu

Maintainer: @dibdot
Compile tested: GL.iNet GL-MT3000 ARMv8 OpenWrt 23.05.0-rc3
Run tested: GL.iNet GL-MT3000 ARMv8 OpenWrt 23.05.0-rc3

Description: Add autologin for Deutsche Hospitality hotels (e.g. Steigenberger)

Original PR was #22704, but I had too many problems editing the commits to meet the requirements

### CODE REVIEW

**Comment by dibdot** [comment]
Even if it's a bit tiring: we need a sign-off with your correct email address, otherwise we can't accept your change. See https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md for reference.

**Comment by Forceu** [comment]
Okay, now it should be correct

**Comment by dibdot** [comment]
Houston we have a lift off - many thanks!

**Comment by dibdot** [comment]
@Forceu Sorry, but the formal test still fails. See the test log for details.

**Comment by dibdot** [comment]
Perfect - thank you for your contribution & your patience!

**Pull request merged**
