### PR TITLE
Call killall with the -s parameter

### PR DESCRIPTION
**Pull request by baierjan**
Some versions of killall do support the killall -SIGNAL syntax and
have only -s SIGNAL which should be supported everywhere.

The problem exists with killall (PSmisc) 23.3 on latest TurrisOS 5.2

Maintainer: @stangri, @teknoraver, @aparcar 

Description: Fixing issue in other packages as suggested in #16381

### CODE REVIEW

**Comment by champtar** [comment]
Thanks @baierjan 
Do you mind putting the description in each commit ?

**Comment by stangri** [comment]
Thanks, LGTM.

**Review by stangri — APPROVED** [review]

**Review by aparcar — APPROVED** [review]

**Comment by champtar** [comment]
@baierjan you forgot to bump PKG_RELEASE

**Comment by baierjan** [comment]
> @baierjan you forgot to bump PKG_RELEASE

Argh, right, the very same mistake as last time... Apparently, I am too much used to a build system automation to do that..

It should be fixed, @champtar

**Pull request merged**
