### PR TITLE
clamav: avoid host pickup of libxml2

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @ratkaj @lucize 
Compile tested: arm, WRT3200ACM, openwrt master
Run tested: arm, WRT3200ACM, openwrt master, run `freshclam`, and `clamscan /sbin/logread` (it took almost one hour to run both)

Description:
If libxml2 is installed in the host, then the host library is used and compilation fails: 
```
libtool: link: arm-openwrt-linux-muslgnueabi-gcc -shared  -fPIC -DPIC  .libs/libclamav_la-matcher-ac.o .libs/libclamav_la-matcher-bm.o .libs/libclamav_la-matcher-hash.o .libs/libclamav_la-matcher.o .libs/libclamav_la-others.o .libs/libclamav_la-readdb.o .libs/libclamav_la-cvd.o .libs/libclamav_la-dsig.o .libs/libclamav_la-scanners.o .libs/libclamav_la-textdet.o .libs/libclamav_la-filetypes.o .libs/libclamav_la-rtf.o .libs/libclamav_la-blob.o .libs/libclamav_la-mbox.o .libs/libclamav_la-message.o .libs/libclamav_la-table.o .libs/libclamav_la-text.o .libs/libclamav_la-ole2_extract.o .libs/libclamav_la-vba_extract.o .libs/libclamav_la-msexpand.o .libs/libclamav_la-pe.o .libs/libclamav_la-pe_icons.o .libs/libclamav_la-disasm.o .libs/libclamav_la-upx.o .libs/libclamav_la-htmlnorm.o .libs/libclamav_la-libmspack.o .libs/libclamav_la-rebuildpe.o .libs/libclamav_la-petite.o .libs/libclamav_la-wwunpack.o .libs/libclamav_la-unsp.o .libs/libclamav_la-aspack.o .libs/libclamav_la-packlibs.o .libs/libclamav_la-fsg.o .libs/libclamav_la-mew.o .libs/libclamav_la-upack.o .libs/libclamav_la-line.o .libs/libclamav_la-untar.o .libs/libclamav_la-unzip.o .libs/libclamav_la-ooxml.o .libs/libclamav_la-inflate64.o .libs/libclamav_la-special.o .libs/libclamav_la-binhex.o .libs/libclamav_la-is_tar.o .libs/libclamav_la-tnef.o .libs/libclamav_la-autoit.o .libs/libclamav_la-unarj.o .libs/libclamav_la-bzlib.o .libs/libclamav_la-nulsft.o .libs/libclamav_la-infblock.o .libs/libclamav_la-pdf.o .libs/libclamav_la-pdfng.o .libs/libclamav_la-pdfdecode.o .libs/libclamav_la-spin.o .libs/libclamav_la-yc.o .libs/libclamav_la-elf.o .libs/libclamav_la-sis.o .libs/libclamav_la-uuencode.o .libs/libclamav_la-phishcheck.o .libs/libclamav_la-phish_domaincheck_db.o .libs/libclamav_la-phish_whitelist.o .libs/libclamav_la-regex_list.o .libs/libclamav_la-regex_suffix.o .libs/libclamav_la-entconv.o .libs/libclamav_la-hashtab.o .libs/libclamav_la-dconf.o .libs/libclamav_la-lzma_iface.o .libs/libclamav_la-7z_iface.o .libs/libclamav_la-7zAlloc.o .libs/libclamav_la-7zBuf.o .libs/libclamav_la-7zBuf2.o .libs/libclamav_la-7zCrc.o .libs/libclamav_la-7zDec.o .libs/libclamav_la-7zFile.o .libs/libclamav_la-7zIn.o .libs/libclamav_la-7zStream.o .libs/libclamav_la-Bcj2.o .libs/libclamav_la-Bra.o .libs/libclamav_la-Bra86.o .libs/libclamav_la-Lzma2Dec.o .libs/libclamav_la-LzmaDec.o .libs/libclamav_la-Ppmd7.o .libs/libclamav_la-Ppmd7Dec.o .libs/libclamav_la-Xz.o .libs/libclamav_la-XzCrc64.o .libs/libclamav_la-XzDec.o .libs/libclamav_la-XzIn.o .libs/libclamav_la-Delta.o .libs/libclamav_la-BraIA64.o .libs/libclamav_la-CpuArch.o .libs/libclamav_la-7zCrcOpt.o .libs/libclamav_la-explode.o .libs/libclamav_la-textnorm.o .libs/libclamav_la-dlp.o .libs/libclamav_la-js-norm.o .libs/libclamav_la-uniq.o .libs/libclamav_la-version.o .libs/libclamav_la-mpool.o .libs/libclamav_la-filtering.o .libs/libclamav_la-fmap.o .libs/libclamav_la-perflogging.o .libs/libclamav_la-bytecode.o .libs/libclamav_la-bytecode_vm.o .libs/libclamav_la-cpio.o .libs/libclamav_la-macho.o .libs/libclamav_la-ishield.o .libs/libclamav_la-bytecode_api.o .libs/libclamav_la-bytecode_api_decl.o .libs/libclamav_la-cache.o .libs/libclamav_la-bytecode_detect.o .libs/libclamav_la-events.o .libs/libclamav_la-adc.o .libs/libclamav_la-dmg.o .libs/libclamav_la-xar.o .libs/libclamav_la-xdp.o .libs/libclamav_la-mbr.o .libs/libclamav_la-gpt.o .libs/libclamav_la-apm.o .libs/libclamav_la-prtn_intxn.o .libs/libclamav_la-json_api.o .libs/libclamav_la-xz_iface.o .libs/libclamav_la-sf_base64decode.o .libs/libclamav_la-hfsplus.o .libs/libclamav_la-swf.o .libs/libclamav_la-jpeg.o .libs/libclamav_la-png.o .libs/libclamav_la-iso9660.o .libs/libclamav_la-arc4.o .libs/libclamav_la-rijndael.o .libs/libclamav_la-crtmgr.o .libs/libclamav_la-asn1.o .libs/libclamav_la-fpu.o .libs/libclamav_la-stats.o .libs/libclamav_la-www.o .libs/libclamav_la-stats_json.o .libs/libclamav_la-hostid.o .libs/libclamav_la-openioc.o .libs/libclamav_la-msdoc.o .libs/libclamav_la-matcher-pcre.o .libs/libclamav_la-regex_pcre.o .libs/libclamav_la-msxml.o .libs/libclamav_la-msxml_parser.o .libs/libclamav_la-tiff.o .libs/libclamav_la-hwp.o .libs/libclamav_la-lzwdec.o .libs/libclamav_la-matcher-byte-comp.o .libs/libclamav_la-yara_arena.o .libs/libclamav_la-yara_compiler.o .libs/libclamav_la-yara_exec.o .libs/libclamav_la-yara_hash.o .libs/libclamav_la-yara_grammar.o .libs/libclamav_la-yara_lexer.o .libs/libclamav_la-yara_parser.o .libs/libclamav_la-fp_add.o .libs/libclamav_la-fp_add_d.o .libs/libclamav_la-fp_addmod.o .libs/libclamav_la-fp_cmp.o .libs/libclamav_la-fp_cmp_d.o .libs/libclamav_la-fp_cmp_mag.o .libs/libclamav_la-fp_sub.o .libs/libclamav_la-fp_sub_d.o .libs/libclamav_la-fp_submod.o .libs/libclamav_la-s_fp_add.o .libs/libclamav_la-s_fp_sub.o .libs/libclamav_la-fp_radix_size.o .libs/libclamav_la-fp_read_radix.o .libs/libclamav_la-fp_read_signed_bin.o .libs/libclamav_la-fp_read_unsigned_bin.o .libs/libclamav_la-fp_reverse.o .libs/libclamav_la-fp_s_rmap.o .libs/libclamav_la-fp_signed_bin_size.o .libs/libclamav_la-fp_to_signed_bin.o .libs/libclamav_la-fp_to_unsigned_bin.o .libs/libclamav_la-fp_toradix.o .libs/libclamav_la-fp_toradix_n.o .libs/libclamav_la-fp_unsigned_bin_size.o .libs/libclamav_la-fp_cnt_lsb.o .libs/libclamav_la-fp_count_bits.o .libs/libclamav_la-fp_div_2.o .libs/libclamav_la-fp_div_2d.o .libs/libclamav_la-fp_lshd.o .libs/libclamav_la-fp_mod_2d.o .libs/libclamav_la-fp_rshd.o .libs/libclamav_la-fp_div.o .libs/libclamav_la-fp_div_d.o .libs/libclamav_la-fp_mod.o .libs/libclamav_la-fp_mod_d.o .libs/libclamav_la-fp_2expt.o .libs/libclamav_la-fp_exptmod.o .libs/libclamav_la-fp_ident.o .libs/libclamav_la-fp_set.o .libs/libclamav_la-fp_montgomery_calc_normalization.o .libs/libclamav_la-fp_montgomery_reduce.o .libs/libclamav_la-fp_montgomery_setup.o .libs/libclamav_la-fp_mul.o .libs/libclamav_la-fp_mul_comba.o .libs/libclamav_la-fp_mul_2.o .libs/libclamav_la-fp_mul_2d.o .libs/libclamav_la-fp_mul_comba_12.o .libs/libclamav_la-fp_mul_comba_17.o .libs/libclamav_la-fp_mul_comba_20.o .libs/libclamav_la-fp_mul_comba_24.o .libs/libclamav_la-fp_mul_comba_28.o .libs/libclamav_la-fp_mul_comba_3.o .libs/libclamav_la-fp_mul_comba_32.o .libs/libclamav_la-fp_mul_comba_4.o .libs/libclamav_la-fp_mul_comba_48.o .libs/libclamav_la-fp_mul_comba_6.o .libs/libclamav_la-fp_mul_comba_64.o .libs/libclamav_la-fp_mul_comba_7.o .libs/libclamav_la-fp_mul_comba_8.o .libs/libclamav_la-fp_mul_comba_9.o .libs/libclamav_la-fp_mul_comba_small_set.o .libs/libclamav_la-fp_mul_d.o .libs/libclamav_la-fp_mulmod.o .libs/libclamav_la-fp_invmod.o .libs/libclamav_la-fp_sqr.o .libs/libclamav_la-fp_sqr_comba_12.o .libs/libclamav_la-fp_sqr_comba_17.o .libs/libclamav_la-fp_sqr_comba_20.o .libs/libclamav_la-fp_sqr_comba_24.o .libs/libclamav_la-fp_sqr_comba_28.o .libs/libclamav_la-fp_sqr_comba_3.o .libs/libclamav_la-fp_sqr_comba_32.o .libs/libclamav_la-fp_sqr_comba_4.o .libs/libclamav_la-fp_sqr_comba_48.o .libs/libclamav_la-fp_sqr_comba_6.o .libs/libclamav_la-fp_sqr_comba_64.o .libs/libclamav_la-fp_sqr_comba_7.o .libs/libclamav_la-fp_sqr_comba_8.o .libs/libclamav_la-fp_sqr_comba_9.o .libs/libclamav_la-fp_sqr_comba_generic.o .libs/libclamav_la-fp_sqr_comba_small_set.o .libs/libclamav_la-fp_sqrmod.o .libs/libclamavS.o -Wl,--whole-archive ./.libs/libclamav_nocxx.a ./.libs/libclamav_internal_utils.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/home/equeiroz/src/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/clamav-0.101.2/libclamav/.libs -L/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr//lib -lxml2 -L/usr/lib64 -ldl -L/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib -L/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/lib -L/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/usr/lib -L/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/lib -lltdl /home/equeiroz/src/openwrt/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/clamav-0.101.2/libclamav/.libs/libclammspack.so -lfts -lssl -lcrypto -lz -ljson-c -lpcre2-8 -lpthread -lm  -Os -mfloat-abi=hard -fstack-protector -Wl,-z -Wl,now -Wl,-z -Wl,relro -Wl,--version-script -Wl,../libclamav/libclamav.map -Wl,--gc-sections -Wl,--as-needed   -Wl,-soname -Wl,libclamav.so.9 -o .libs/libclamav.so.9.0.2
/usr/lib64/libdl.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make[7]: *** [Makefile:1515: libclamav.la] Error 1
```
Here are relevant `configure` output showing where the problem is:
```
checking for sysctlbyname... no
/usr
checking xml2-config version... 2.9.9
-I/usr/include/libxml2
-lxml2 -L/usr/lib64 -lz -lm -ldl
checking for xmlreader.h in /usr... found
CPPFLAGS: -I/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include -I/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/include -I/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/usr/include -I/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/include/fortify -I/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/include  -I/usr/include/libxml2
LD_FLAGS: -L/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/lib -L/home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/lib -L/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/usr/lib -L/home/equeiroz/src/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-7.4.0_musl_eabi/lib -znow -zrelro -Wl,--gc-sections,--as-needed -lfts  -lxml2 -L/usr/lib64 -lz -lm -ldl
checking for xmlTextReaderRead in -lxml2... yes
configure: Compiling and linking with libxml2 from /usr
```
```
configure: Summary of detected features follows
              OS          : linux-gnu
              pthreads    : yes (-lpthread)
configure: Summary of miscellaneous features
              check       : no (disabled)
              fanotify    : yes
              fdpassing   : 0
              IPv6        : yes
configure: Summary of optional tools
              clamdtop    :  (disabled)
              milter      : yes
              clamsubmit  : yes (libjson-c-dev found at /home/equeiroz/src/openwrt/staging_dir/target-a
rm_cortex-a9+vfpv3_musl_eabi/usr/), libcurl-devel found at /home/equeiroz/src/openwrt/staging_dir/targe
t-arm_cortex-a9+vfpv3_musl_eabi/usr/)
configure: Summary of engine performance features
              release mode: yes
              llvm        : no (7.1.0), from /usr/lib/llvm/7/bin/llvm-config () (auto)
              mempool     : yes
configure: Summary of engine detection features
              bzip2       : ok (disabled)
              zlib        : /home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/
              unrar       : yes
              preclass    : yes (libjson-c-dev found at /home/equeiroz/src/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/)
              pcre        : /usr
              libmspack   : yes (Internal)
              libxml2     : yes, from /usr
              yara        : yes
              fts         : yes (libc)
```

Notice it picks up more libs from host, but they do not cause failures, at least not here.

An alternative workaround that avoids the need to run `autoreconf` is to add `ac_cv_lib_xml2_xmlTextReaderRead=no` to `CONFIGURE_VARS`.  Since I submitted the patch upstream https://github.com/Cisco-Talos/clamav-devel/pull/103, I think applying the patch will make an easier transition when the bug is fixed upstream.

Not increasing `PKG_RELEASE` since it does not alter the final package if the host does not have libxml2; if the host does have libxml2, then it just fails.

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
**Edited to add run-test**

### CODE REVIEW

**Comment by neheb** [comment]
My experience with PKG_FIXUP:=autoreconf is that it changes .ipk size.

**Comment by cotequeiroz** [comment]
I rechecked, and you are correct.  I had probably done my previous check with my alternate fix.  It changes comments in the `lib*.la` files (they should probably not be in the final package anyway).  I don't think it warrants an increase in PKG_RELEASE for it.
```diff
diff --git a/clamav-0.101.2.orig/ipkg-arm_cortex-a9_vfpv3/clamav/CONTROL/control b/clamav-0.101.2/ipkg-arm_cortex-a9_vfpv3/clamav/CONTROL/control
index 85af2a7e70..94791dcd40 100644
--- a/clamav-0.101.2.orig/ipkg-arm_cortex-a9_vfpv3/clamav/CONTROL/control
+++ b/clamav-0.101.2/ipkg-arm_cortex-a9_vfpv3/clamav/CONTROL/control
@@ -8,6 +8,6 @@ LicenseFiles: COPYING*
 Section: net
 Maintainer: Marko Ratkaj <marko.ratkaj@sartura.hr> Lucian Cristian <lucian.cristian@gmail.com>
 Architecture: arm_cortex-a9_vfpv3
-Installed-Size: 1167496
+Installed-Size: 1167492
 Description:  ClamAV is an open source antivirus engine for detecting trojans,
  viruses, malware & other malicious threats.
```
```diff
-# Generated by libtool (GNU libtool) 2.4.6
+# Generated by libtool (GNU libtool) 2.4
```
```diff
-# Linker flags that cannot go in dependency_libs.
+# Linker flags that can not go in dependency_libs.
```
OTOH, I can just take this opportunity to take out `*.la`, `*.so`, and `pkgconfig`.  Suggestions?

**Comment by lucize** [comment]
from my part, do as you like!

**Comment by neheb** [comment]
Please rebase against current master to fix the buildbot.

**Comment by cotequeiroz** [comment]
I've run-tested this with my WRT3200ACM, but it appears to have definition database issues, since the memory usage is huge.  It uses over 300MB of RAM to update definitions with `freshclam`, and i takes 630MB and 38 minutes to scan `/sbin/logread`: 
```
----------- SCAN SUMMARY -----------
Known viruses: 6269854
Engine version: 0.101.1
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 0.01 MB
Data read: 0.01 MB (ratio 1.00:1)
Time: 2331.030 sec (38 m 51 s)
        Command being timed: "clamscan --debug --verbose /sbin/logread"
        User time (seconds): 239.32
        System time (seconds): 6.36
        Percent of CPU this job got: 10%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 38m 52.45s
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1165040
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 256996
        Minor (reclaiming a frame) page faults: 795238
        Voluntary context switches: 266055
        Involuntary context switches: 20157
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
I've tested with the current snapshot version (as opposed to a build of my own) and it behaves the same way.

**Comment by lucize** [comment]
@cotequeiroz if you use only main signatures it will work faster, it can't work on low memory system by design, if you run clamd it will scan quickly once the definitions are in memory, every clamscan command will first read definition database and then scan the file so is not the recommended way

**Comment by cotequeiroz** [comment]
I just wasn't expecting that.  If this is the way it should be, then it's OK.

**Pull request merged**
