### PR TITLE
[openwrt-22.03] zerotier: update to 1.10.2

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>

Maintainer: me
Compile tested: ramips/mt7620, (Nexx wt3020)
Run tested: ZeroTier starts and is responsive (zeriotier-cli)

### CODE REVIEW

**Comment by duckdegen** [comment]
Bumping this. Can it please be merged?

**Comment by olfway** [comment]
Also, 1.10.2 is out
https://github.com/zerotier/ZeroTierOne/blob/master/RELEASE-NOTES.md#2022-11-01----version-1102

**Comment by mwarning** [comment]
This MR has been updated.

**Comment by 1715173329** [comment]
Merged, thanks!

**Comment by 1715173329** [comment]
Hi @mwarning, could you please make a PR for 21.02 branch too?

**Comment by mwarning** [comment]
@1715173329 https://github.com/openwrt/packages/pull/19898 (still needs testing)

**Pull request merged**
