### PR TITLE
simple-adblock: better start/stop/reload/uninstall

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin <stangri@melmac.net>

Maintainer: me
Compile tested: mvebu, Linksys WRT3200ACM, 17.01.4
Run tested: ipq806x, Linksys EA8500, 17.01.4 

Description:
 - Better start/stop/reload logic
 - Correctly start/stop/reload from Web UI
 - Updated README
 - Correctly remove cache/temporary file on service uninstall
 - ```check``` command to check string for entries in blacklist

### CODE REVIEW

**Comment by dibdot** [comment]
Hi Stan, is it intended that a full stop doesn't clean the cache file as well?

**Comment by stangri** [comment]
Dirk,
Yes, it is an intended behavior, so that when the service is started again it uses the already existing cache file.

**Comment by dibdot** [comment]
Thanks, first commit merged ever ... ;-)
@hnyman @thess  I've no merging rights for luci repo, therefore please take care separate luci commit. Thanks!

**Comment by thess** [comment]
@dibdot - you should have luci access now

**Pull request merged**
