### PR TITLE
openssh: Add SSH keys to conffiles

### PR DESCRIPTION
**Pull request by neheb**
This is already done for dropbear, so might as well do it for OpenSSH as well.

### CODE REVIEW

**Comment by xypron** [comment]
It is a very bad idea to distribute the same key to all openwrt systems.
The keys have to be different on all systems. Otherwise communication is not secure.
So generation of the keys should be part of the postinstall script.

**Comment by champtar** [comment]
@neheb why not keep the whole dir?

**Comment by champtar** [comment]
ping @neheb

**Comment by neheb** [comment]
hmmm? doesn't this keep the whole dir?

**Comment by champtar** [comment]
@neheb can you tests
```
define Package/openssh-server/conffiles
/etc/ssh/
endef
```

**Comment by neheb** [comment]
that conflicts with ssh_conf, no?

**Comment by champtar** [comment]
@neheb there is no conflicts when you ask multiples times to keep the same file (looking at the code)
see https://github.com/openwrt/openwrt/blob/master/package/base-files/files/sbin/sysupgrade#L104

**Comment by neheb** [comment]
But why should that be kept for openssh-server when all that is wanted is to keep openssh-server conffiles?

**Comment by diizzyy** [comment]
I think what neheb is says makes sense in terms of "pollution".
@champtar 
Are we missing something obvious?

**Comment by mionica** [comment]
ssh moduli also stays there, if installed; no point in backing up a file provided by a package, particularly since we're talking ~540K
I'd go with
/etc/ssh/ssh*_config
/etc/ssh/ssh_host_*key
/etc/ssh/ssh_host_*key.pub

**Comment by champtar** [comment]
@tripolar please ack/nack

**Comment by tripolar** [comment]
applied a slightly modified version in a8b55048c0df27f9ecef31bca6d6e0d9e64edfaa

**Comment by pprindeville** [comment]
Why is this closed?

**Comment by pprindeville** [comment]
Different question: if we release a new version with a modified `/etc/ssh/sshd_config` that addresses a CVT, wouldn't we want that to get picked up?

**Pull request closed without merging**
