### PR TITLE
aircrack-ng: Update to 1.5.2

### PR DESCRIPTION
**Pull request by jbenden**
Maintainer: Rick Farina zerochaos@gentoo.org @ZeroChaos-
Compile tested: mips_24kc_musl for GL-AR150 with master openwrt

Description:
Updates the aircrack-ng tool to the latest shipping version.

### CODE REVIEW

**Comment by neheb** [comment]
Quick.

Out of curiosity, do you know why compilation with uclibc++ fails? That single cpp file increases size by 350kb of the resulting package.

It seems to error with mips-openwrt-linux-musl-g++: error: 1.4": No such file or directory , which I can't figure out.

This is the patch: https://gist.github.com/neheb/5f4ddcfa370952808dca4842f5bd3dc5

**Comment by jbenden** [comment]
I posted a note on the Gist itself.

**Comment by neheb** [comment]
That makes sense. Looks like that needs fixing first.

**Comment by jbenden** [comment]
Sorry on the multiple releases; should be calm now...

**Comment by neheb** [comment]
Note: I just found this build failure: https://downloads.openwrt.org/snapshots/faillogs/powerpc_8540/packages/aircrack-ng/compile.txt

**Comment by jbenden** [comment]
We don't do PPC/PPCLE auto-detection well, not a heavily supported platform; due to lack of this equipment. I'll note this bug report and try to patch in the next release.

Until then would you like a patch file to solve this platform's problem? Or can it be marked broken on this specific build?

**Comment by neheb** [comment]
I don't have any equipment. The fact that nobody has reported this indicated nobody else does either. Marking it as BROKEN is probably fine.

**Comment by jbenden** [comment]
It looks like it failed because soft-floating is enabled. Is it possible to enable HW version? I'm not sure of the better way of handling this, nor on adding a BROKEN entry for this platform. Could I have some assistance on marking it broken for this platform, or for enabling HW floating point? Thanks!

**Comment by neheb** [comment]
In the meantime, can you change the DEPENDS to depend on libstdcpp instead of statically linking it?

**Comment by jbenden** [comment]
@neheb Would you mind trying the attached patch against that PPC machine?
[ppc-vsx.txt](https://github.com/openwrt/packages/files/2838069/ppc-vsx.txt)

**Comment by neheb** [comment]
I don’t have one. It can be tested with a PPC SDK like this one: https://downloads.openwrt.org/snapshots/targets/mpc85xx/p2020/openwrt-sdk-mpc85xx-p2020_gcc-7.4.0_musl.Linux-x86_64.tar.xz

**Comment by jbenden** [comment]
Thanks! I was able to successfully build, with the patch; although, with a number of warnings.

This patch should be present in the next release of aircrack-ng.

**Pull request merged**
