### PR TITLE
dnscrypt-proxy: add support for -E/--ephemeral-keys option.

### PR DESCRIPTION
**Pull request by adam2104**
Signed-off-by: Adam Gensler <openwrt@a.gnslr.us>

### CODE REVIEW

**Comment by sbyx** [comment]
From the commit title/message alone, it's hard to see what package is affected. Can you please change your commit title to include the package name as prefix?

**Comment by adam2104** [comment]
Sorry about that, I've updated the commit message.

**Comment by thess** [comment]
@damianorenfer - Please review

**Comment by damianorenfer** [comment]
Looks good, Thanks.

**Pull request merged**
