### PR TITLE
tcpreplay: update to 4.2.3

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/lede-project/source/commit/2db05cd199999d9a3670e5287d067bdab0431f1a  ar71xx
Run tested: N/A

Description:

update to version 4.2.3

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
You could remove the old PKG_MD5SUM next time (as you already have the current PKG_HASH).

**Comment by commodo** [comment]
well, it's mostly for people that want to use the package all the way back to 15.05 
any idea if the PKG_HASH works in that version too ? 
[ please answer only if you know from the top of your head ; i mean, if you have to look through source to answer, i would not want you to go through that trouble ]

**Comment by hnyman** [comment]
No, PKG_HASH  does not work in 15.05.

But in general, the master branch packages should not be used in 15.05. If some body wants to do that, they may should patch their buildroot to make PKG_HASH to work there. (It is a few simple changes).

**Comment by commodo** [comment]
ack

**Pull request merged**
