### PR TITLE
libimobiledevice packages updated to git

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: nobody
Compile tested: ath79

Description:
Sparked by https://github.com/openwrt/packages/pull/5635 , I updated the packages. I don't use iDevices on my OpenWrt so I can't test it properly.

@michyprima can you test this?

### CODE REVIEW

**Comment by michyprima** [comment]
I will but my openwrt device is not in my hands at the moment. I will let you know when I get it back but it may require from 2 weeks to a month. is that okay?

**Comment by diizzyy** [comment]
Yes, that's fine

**Comment by neheb** [comment]
No problem

**Comment by akirahaku** [comment]
Tested. Works fine.  [usbmuxd line 47](https://github.com/openwrt/packages/pull/8518/commits/e2a2b3f7767812619e8f37df2d09478bc4a82559#diff-57245efe69e67fdfcc491d052fa1e78fR47) need remove to proper handle iOS 7 and above trust dialog. 

<details>
<summary>output from `usbmuxd -vv -f` </summary>
root@OpenWrt:/tmp/ipks# usbmuxd -vv -f
[13:23:46.121][3] usbmuxd v1.1.1 starting up
[13:23:46.121][4] Creating socket
[13:23:46.121][5] initialized config_dir to /var/lib/lockdown
[13:23:46.121][5] client_init
[13:23:46.122][5] device_init
[13:23:46.122][4] Initializing USB
[13:23:46.122][5] usb_init for linux / libusb 1.0
[13:23:46.124][4] Registering for libusb hotplug events
[13:23:46.124][4] Found new device with v/p 05ac:12a8 at 1-9
[13:23:46.125][4] Found interface 1 with endpoints 04/85 for device 1-9
[13:23:46.125][4] Using wMaxPacketSize=512 for device 1-9
[13:23:46.125][4] USB Speed is 480 MBit/s for device 1-9
[13:23:46.126][4] 1 device detected
[13:23:46.126][3] Initialization complete
[13:23:46.126][4] Got lang ID 1033 for device 1-9
[13:23:46.127][4] Got serial '66e9800a3c386bfc30f2addb8fc12d9705b28266' for device 1-9
[13:23:46.127][3] Connecting to new device on location 0x10009 as ID 1
[13:23:46.127][5] All 3 RX loops started successfully
[13:23:46.127][3] Connected to v2.0 device 1 on location 0x10009 with serial number 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:46.128][4] preflight_worker_handle_device_add: Starting preflight on device 66e9800a3c386bfc30f2addb8fc12d9705b28266...
[13:23:46.129][4] New client on fd 13 (self)
[13:23:46.130][5] Client command in fd 13 len 512 ver 1 msg 8 tag 1
[13:23:46.130][5] Client 13 connection request to device 1 port 62078
[13:23:46.130][5] [OUT] dev=1 sport=1 dport=62078 seq=0 ack=0 flags=0x2 window=131072[512] len=0
[13:23:46.132][5] [IN] dev=1 sport=62078 dport=1 seq=0 ack=1 flags=0x12 window=131072[512] len=0
[13:23:46.132][5] [OUT] dev=1 sport=1 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=0
[13:23:46.132][5] send_pkt fd 13 tag 1 msg 8 payload_length 278
[13:23:46.133][5] Client 13 switching to CONNECTED state
[13:23:46.133][5] [OUT] dev=1 sport=1 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=284
[13:23:46.135][5] [IN] dev=1 sport=62078 dport=1 seq=1 ack=285 flags=0x10 window=131072[512] len=301
[13:23:46.135][5] [OUT] dev=1 sport=1 dport=62078 seq=285 ack=1 flags=0x10 window=131072[512] len=0
[13:23:46.135][4] preflight_worker_handle_device_add: Device 66e9800a3c386bfc30f2addb8fc12d9705b28266 is not paired with this host.
[13:23:46.136][5] [OUT] dev=1 sport=1 dport=62078 seq=285 ack=302 flags=0x10 window=131072[512] len=332
[13:23:46.137][5] [IN] dev=1 sport=62078 dport=1 seq=302 ack=617 flags=0x10 window=131072[512] len=329
[13:23:46.138][5] [OUT] dev=1 sport=1 dport=62078 seq=617 ack=302 flags=0x10 window=131072[512] len=0
[13:23:46.138][4] preflight_worker_handle_device_add: Found ProductVersion 12.2 device 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:46.138][5] reading key SystemBUID from config_file /var/lib/lockdown/SystemConfiguration.plist
[13:23:46.138][5] got SystemBUID 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:46.138][5] using 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A as SystemBUID
[13:23:46.138][5] lockdownd_set_untrusted_host_buid: Setting UntrustedHostBUID to 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:46.138][5] [OUT] dev=1 sport=1 dport=62078 seq=617 ack=631 flags=0x10 window=131072[512] len=408
[13:23:46.140][5] [IN] dev=1 sport=62078 dport=1 seq=631 ack=1025 flags=0x10 window=131072[512] len=364
[13:23:46.140][5] [OUT] dev=1 sport=1 dport=62078 seq=1025 ack=631 flags=0x10 window=131072[512] len=0
[13:23:46.141][5] [OUT] dev=1 sport=1 dport=62078 seq=1025 ack=995 flags=0x10 window=131072[512] len=333
[13:23:46.153][5] [IN] dev=1 sport=62078 dport=1 seq=995 ack=1358 flags=0x10 window=131072[512] len=918
[13:23:46.154][5] [OUT] dev=1 sport=1 dport=62078 seq=1358 ack=995 flags=0x10 window=131072[512] len=0
[13:23:46.184][5] Sending ACK due to expired timeout (3266882 -> 3266913)
[13:23:46.184][5] [OUT] dev=1 sport=1 dport=62078 seq=1358 ack=1913 flags=0x10 window=131072[512] len=0
[13:23:46.639][4] New client on fd 15 (self)
[13:23:46.639][5] Client command in fd 15 len 421 ver 1 msg 8 tag 2
[13:23:46.640][5] reading key SystemBUID from config_file /var/lib/lockdown/SystemConfiguration.plist
[13:23:46.640][5] got SystemBUID 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:46.640][5] using 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A as SystemBUID
[13:23:46.640][5] send_pkt fd 15 tag 2 msg 8 payload_length 260
[13:23:46.640][4] Client 15 connection closed
[13:23:46.640][4] Disconnecting client fd 15
[13:23:46.640][5] [OUT] dev=1 sport=1 dport=62078 seq=1358 ack=1913 flags=0x10 window=131072[512] len=329
[13:23:46.642][5] [IN] dev=1 sport=62078 dport=1 seq=1913 ack=1687 flags=0x10 window=131072[512] len=339
[13:23:46.642][5] [OUT] dev=1 sport=1 dport=62078 seq=1687 ack=1913 flags=0x10 window=131072[512] len=0
[13:23:46.643][5] [OUT] dev=1 sport=1 dport=62078 seq=1687 ack=2252 flags=0x10 window=131072[512] len=4851
[13:23:46.658][5] [IN] dev=1 sport=62078 dport=1 seq=2252 ack=6538 flags=0x10 window=131072[512] len=4
[13:23:46.658][5] [OUT] dev=1 sport=1 dport=62078 seq=6538 ack=2252 flags=0x10 window=131072[512] len=0
[13:23:46.658][5] [IN] dev=1 sport=62078 dport=1 seq=2256 ack=6538 flags=0x10 window=131072[512] len=285
[13:23:46.658][5] [OUT] dev=1 sport=1 dport=62078 seq=6538 ack=2252 flags=0x10 window=131072[512] len=0
[13:23:46.659][5] [OUT] dev=1 sport=1 dport=62078 seq=6538 ack=2541 flags=0x10 window=131072[512] len=370
[13:23:46.662][5] [IN] dev=1 sport=62078 dport=1 seq=2541 ack=6908 flags=0x10 window=131072[512] len=4
[13:23:46.663][5] [OUT] dev=1 sport=1 dport=62078 seq=6908 ack=2541 flags=0x10 window=131072[512] len=0
[13:23:46.663][5] [IN] dev=1 sport=62078 dport=1 seq=2545 ack=6908 flags=0x10 window=131072[512] len=365
[13:23:46.663][5] [OUT] dev=1 sport=1 dport=62078 seq=6908 ack=2541 flags=0x10 window=131072[512] len=0
[13:23:46.663][4] New client on fd 15 (self)
[13:23:46.663][5] Client command in fd 15 len 512 ver 1 msg 8 tag 3
[13:23:46.663][5] Client 15 connection request to device 1 port 62057
[13:23:46.663][5] [OUT] dev=1 sport=2 dport=62057 seq=0 ack=0 flags=0x2 window=131072[512] len=0
[13:23:46.664][5] [IN] dev=1 sport=62057 dport=2 seq=0 ack=1 flags=0x12 window=131072[512] len=0
[13:23:46.664][5] [OUT] dev=1 sport=2 dport=62057 seq=1 ack=1 flags=0x10 window=131072[512] len=0
[13:23:46.664][5] send_pkt fd 15 tag 3 msg 8 payload_length 278
[13:23:46.665][5] Client 15 switching to CONNECTED state
[13:23:46.665][5] connection_teardown dev 1 sport 1 dport 62078
[13:23:46.665][5] [OUT] dev=1 sport=1 dport=62078 seq=6908 ack=2910 flags=0x4 window=131072[512] len=0
[13:23:46.665][4] preflight_worker_handle_device_add: Waiting for user to trust this computer on device 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:46.665][4] Disconnecting client fd 13
[13:23:46.665][5] client_device_add: id 1, location 0x10009, serial 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:46.665][5] [OUT] dev=1 sport=2 dport=62057 seq=1 ack=1 flags=0x10 window=131072[512] len=653
[13:23:51.098][4] Device 1-9 RX aborted due to error or disconnect
[13:23:51.098][4] Device 1-9 RX aborted due to error or disconnect
[13:23:51.098][4] Device 1-9 RX aborted due to error or disconnect
[13:23:51.099][3] Removed device 1 on location 0x10009
[13:23:51.099][5] connection_teardown dev 1 sport 2 dport 62057
[13:23:51.099][4] Disconnecting client fd 15
[13:23:51.099][5] client_device_remove: id 1
[13:23:51.665][4] preflight_worker_handle_device_add: Finished waiting for notification from device 66e9800a3c386bfc30f2addb8fc12d9705b28266, is_device_connected 0
[13:23:54.111][4] Found new device with v/p 05ac:12a8 at 1-10
[13:23:54.113][4] Setting configuration for device 1-10, from 1 to 4
[13:23:54.125][4] Found interface 1 with endpoints 04/85 for device 1-10
[13:23:54.125][4] Using wMaxPacketSize=512 for device 1-10
[13:23:54.125][4] USB Speed is 480 MBit/s for device 1-10
[13:23:54.126][4] Got lang ID 1033 for device 1-10
[13:23:54.126][4] Got serial '66e9800a3c386bfc30f2addb8fc12d9705b28266' for device 1-10
[13:23:54.126][3] Connecting to new device on location 0x1000a as ID 2
[13:23:54.126][5] All 3 RX loops started successfully
[13:23:54.126][3] Connected to v2.0 device 2 on location 0x1000a with serial number 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:54.127][4] preflight_worker_handle_device_add: Starting preflight on device 66e9800a3c386bfc30f2addb8fc12d9705b28266...
[13:23:54.127][4] New client on fd 13 (self)
[13:23:54.127][5] Client command in fd 13 len 512 ver 1 msg 8 tag 4
[13:23:54.127][5] Client 13 connection request to device 2 port 62078
[13:23:54.127][5] [OUT] dev=2 sport=1 dport=62078 seq=0 ack=0 flags=0x2 window=131072[512] len=0
[13:23:54.128][5] [IN] dev=2 sport=62078 dport=1 seq=0 ack=1 flags=0x12 window=131072[512] len=0
[13:23:54.128][5] [OUT] dev=2 sport=1 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=0
[13:23:54.128][5] send_pkt fd 13 tag 4 msg 8 payload_length 278
[13:23:54.129][5] Client 13 switching to CONNECTED state
[13:23:54.129][5] [OUT] dev=2 sport=1 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=284
[13:23:54.149][5] [IN] dev=2 sport=62078 dport=1 seq=1 ack=285 flags=0x10 window=131072[512] len=301
[13:23:54.149][5] [OUT] dev=2 sport=1 dport=62078 seq=285 ack=1 flags=0x10 window=131072[512] len=0
[13:23:54.149][4] preflight_worker_handle_device_add: Device 66e9800a3c386bfc30f2addb8fc12d9705b28266 is not paired with this host.
[13:23:54.149][5] [OUT] dev=2 sport=1 dport=62078 seq=285 ack=302 flags=0x10 window=131072[512] len=332
[13:23:54.152][5] [IN] dev=2 sport=62078 dport=1 seq=302 ack=617 flags=0x10 window=131072[512] len=4
[13:23:54.152][5] [OUT] dev=2 sport=1 dport=62078 seq=617 ack=302 flags=0x10 window=131072[512] len=0
[13:23:54.152][5] [IN] dev=2 sport=62078 dport=1 seq=306 ack=617 flags=0x10 window=131072[512] len=325
[13:23:54.152][5] [OUT] dev=2 sport=1 dport=62078 seq=617 ack=302 flags=0x10 window=131072[512] len=0
[13:23:54.153][4] preflight_worker_handle_device_add: Found ProductVersion 12.2 device 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:54.153][5] reading key SystemBUID from config_file /var/lib/lockdown/SystemConfiguration.plist
[13:23:54.153][5] got SystemBUID 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:54.153][5] using 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A as SystemBUID
[13:23:54.153][5] lockdownd_set_untrusted_host_buid: Setting UntrustedHostBUID to 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:54.153][5] [OUT] dev=2 sport=1 dport=62078 seq=617 ack=631 flags=0x10 window=131072[512] len=408
[13:23:54.171][5] [IN] dev=2 sport=62078 dport=1 seq=631 ack=1025 flags=0x10 window=131072[512] len=4
[13:23:54.171][5] [OUT] dev=2 sport=1 dport=62078 seq=1025 ack=631 flags=0x10 window=131072[512] len=0
[13:23:54.171][5] [IN] dev=2 sport=62078 dport=1 seq=635 ack=1025 flags=0x10 window=131072[512] len=360
[13:23:54.171][5] [OUT] dev=2 sport=1 dport=62078 seq=1025 ack=631 flags=0x10 window=131072[512] len=0
[13:23:54.172][5] [OUT] dev=2 sport=1 dport=62078 seq=1025 ack=995 flags=0x10 window=131072[512] len=333
[13:23:54.182][5] [IN] dev=2 sport=62078 dport=1 seq=995 ack=1358 flags=0x10 window=131072[512] len=918
[13:23:54.182][5] [OUT] dev=2 sport=1 dport=62078 seq=1358 ack=995 flags=0x10 window=131072[512] len=0
[13:23:54.213][5] Sending ACK due to expired timeout (3274911 -> 3274942)
[13:23:54.213][5] [OUT] dev=2 sport=1 dport=62078 seq=1358 ack=1913 flags=0x10 window=131072[512] len=0
[13:23:54.860][4] New client on fd 16 (self)
[13:23:54.860][5] Client command in fd 16 len 421 ver 1 msg 8 tag 5
[13:23:54.861][5] reading key SystemBUID from config_file /var/lib/lockdown/SystemConfiguration.plist
[13:23:54.861][5] got SystemBUID 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:54.861][5] using 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A as SystemBUID
[13:23:54.861][5] send_pkt fd 16 tag 5 msg 8 payload_length 260
[13:23:54.861][4] Client 16 connection closed
[13:23:54.861][4] Disconnecting client fd 16
[13:23:54.861][5] [OUT] dev=2 sport=1 dport=62078 seq=1358 ack=1913 flags=0x10 window=131072[512] len=329
[13:23:54.864][5] [IN] dev=2 sport=62078 dport=1 seq=1913 ack=1687 flags=0x10 window=131072[512] len=4
[13:23:54.864][5] [OUT] dev=2 sport=1 dport=62078 seq=1687 ack=1913 flags=0x10 window=131072[512] len=0
[13:23:54.864][5] [IN] dev=2 sport=62078 dport=1 seq=1917 ack=1687 flags=0x10 window=131072[512] len=335
[13:23:54.864][5] [OUT] dev=2 sport=1 dport=62078 seq=1687 ack=1917 flags=0x10 window=131072[512] len=0
[13:23:54.864][5] [OUT] dev=2 sport=1 dport=62078 seq=1687 ack=2252 flags=0x10 window=131072[512] len=4851
[13:23:54.881][5] [IN] dev=2 sport=62078 dport=1 seq=2252 ack=6538 flags=0x10 window=131072[512] len=4
[13:23:54.881][5] [OUT] dev=2 sport=1 dport=62078 seq=6538 ack=2252 flags=0x10 window=131072[512] len=0
[13:23:54.881][5] [IN] dev=2 sport=62078 dport=1 seq=2256 ack=6538 flags=0x10 window=131072[512] len=296
[13:23:54.881][5] [OUT] dev=2 sport=1 dport=62078 seq=6538 ack=2256 flags=0x10 window=131072[512] len=0
[13:23:54.881][5] [OUT] dev=2 sport=1 dport=62078 seq=6538 ack=2552 flags=0x10 window=131072[512] len=370
[13:23:54.886][5] [IN] dev=2 sport=62078 dport=1 seq=2552 ack=6908 flags=0x10 window=131072[512] len=4
[13:23:54.886][5] [OUT] dev=2 sport=1 dport=62078 seq=6908 ack=2552 flags=0x10 window=131072[512] len=0
[13:23:54.886][5] [IN] dev=2 sport=62078 dport=1 seq=2556 ack=6908 flags=0x10 window=131072[512] len=365
[13:23:54.886][5] [OUT] dev=2 sport=1 dport=62078 seq=6908 ack=2556 flags=0x10 window=131072[512] len=0
[13:23:54.886][4] New client on fd 16 (self)
[13:23:54.886][5] Client command in fd 16 len 512 ver 1 msg 8 tag 6
[13:23:54.887][5] Client 16 connection request to device 2 port 62060
[13:23:54.887][5] [OUT] dev=2 sport=2 dport=62060 seq=0 ack=0 flags=0x2 window=131072[512] len=0
[13:23:54.887][5] [IN] dev=2 sport=62060 dport=2 seq=0 ack=1 flags=0x12 window=131072[512] len=0
[13:23:54.887][5] [OUT] dev=2 sport=2 dport=62060 seq=1 ack=1 flags=0x10 window=131072[512] len=0
[13:23:54.887][5] send_pkt fd 16 tag 6 msg 8 payload_length 278
[13:23:54.887][5] Client 16 switching to CONNECTED state
[13:23:54.887][5] connection_teardown dev 2 sport 1 dport 62078
[13:23:54.887][5] [OUT] dev=2 sport=1 dport=62078 seq=6908 ack=2921 flags=0x4 window=131072[512] len=0
[13:23:54.888][4] Disconnecting client fd 13
[13:23:54.888][4] preflight_worker_handle_device_add: Waiting for user to trust this computer on device 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:54.888][5] [OUT] dev=2 sport=2 dport=62060 seq=1 ack=1 flags=0x10 window=131072[512] len=653
[13:23:54.888][5] client_device_add: id 2, location 0x1000a, serial 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:23:58.357][5] [IN] dev=2 sport=62060 dport=2 seq=1 ack=654 flags=0x10 window=131072[512] len=322
[13:23:58.358][5] [OUT] dev=2 sport=2 dport=62060 seq=654 ack=1 flags=0x10 window=131072[512] len=0
[13:23:58.358][4] np_callback: user trusted this computer on device 66e9800a3c386bfc30f2addb8fc12d9705b28266, pairing now
[13:23:58.358][4] New client on fd 13 (self)
[13:23:58.359][5] Client command in fd 13 len 512 ver 1 msg 8 tag 7
[13:23:58.359][5] Client 13 connection request to device 2 port 62078
[13:23:58.359][5] [OUT] dev=2 sport=3 dport=62078 seq=0 ack=0 flags=0x2 window=131072[512] len=0
[13:23:58.360][5] [IN] dev=2 sport=62078 dport=3 seq=0 ack=1 flags=0x12 window=131072[512] len=0
[13:23:58.360][5] [OUT] dev=2 sport=3 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=0
[13:23:58.360][5] send_pkt fd 13 tag 7 msg 8 payload_length 278
[13:23:58.361][5] Client 13 switching to CONNECTED state
[13:23:58.361][5] [OUT] dev=2 sport=3 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=333
[13:23:58.367][5] [IN] dev=2 sport=62078 dport=3 seq=1 ack=334 flags=0x10 window=131072[512] len=4
[13:23:58.367][5] [OUT] dev=2 sport=3 dport=62078 seq=334 ack=1 flags=0x10 window=131072[512] len=0
[13:23:58.368][5] [IN] dev=2 sport=62078 dport=3 seq=5 ack=334 flags=0x10 window=131072[512] len=914
[13:23:58.368][5] [OUT] dev=2 sport=3 dport=62078 seq=334 ack=1 flags=0x10 window=131072[512] len=0
[13:23:58.389][5] Sending ACK due to expired timeout (3279087 -> 3279118)
[13:23:58.389][5] [OUT] dev=2 sport=2 dport=62060 seq=654 ack=323 flags=0x10 window=131072[512] len=0
[13:23:58.399][5] Sending ACK due to expired timeout (3279097 -> 3279128)
[13:23:58.399][5] [OUT] dev=2 sport=3 dport=62078 seq=334 ack=919 flags=0x10 window=131072[512] len=0
[13:23:59.069][4] New client on fd 18 (self)
[13:23:59.069][5] Client command in fd 18 len 421 ver 1 msg 8 tag 8
[13:23:59.070][5] reading key SystemBUID from config_file /var/lib/lockdown/SystemConfiguration.plist
[13:23:59.070][5] got SystemBUID 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:23:59.070][5] using 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A as SystemBUID
[13:23:59.070][5] send_pkt fd 18 tag 8 msg 8 payload_length 260
[13:23:59.070][4] Client 18 connection closed
[13:23:59.070][4] Disconnecting client fd 18
[13:23:59.070][5] [OUT] dev=2 sport=3 dport=62078 seq=334 ack=919 flags=0x10 window=131072[512] len=329
[13:23:59.071][5] [IN] dev=2 sport=62078 dport=3 seq=919 ack=663 flags=0x10 window=131072[512] len=339
[13:23:59.071][5] [OUT] dev=2 sport=3 dport=62078 seq=663 ack=919 flags=0x10 window=131072[512] len=0
[13:23:59.071][5] [OUT] dev=2 sport=3 dport=62078 seq=663 ack=1258 flags=0x10 window=131072[512] len=4851
[13:23:59.230][5] [IN] dev=2 sport=62078 dport=3 seq=1258 ack=5514 flags=0x10 window=131072[512] len=4
[13:23:59.230][5] [OUT] dev=2 sport=3 dport=62078 seq=5514 ack=1258 flags=0x10 window=131072[512] len=0
[13:23:59.230][5] [IN] dev=2 sport=62078 dport=3 seq=1262 ack=5514 flags=0x10 window=131072[512] len=316
[13:23:59.230][5] [OUT] dev=2 sport=3 dport=62078 seq=5514 ack=1258 flags=0x10 window=131072[512] len=0
[13:23:59.231][4] New client on fd 18 (self)
[13:23:59.232][5] Client command in fd 18 len 9802 ver 1 msg 8 tag 9
[13:23:59.234][5] client_device_paired: id 2
[13:23:59.235][5] send_pkt fd 18 tag 9 msg 8 payload_length 278
[13:23:59.235][4] Client 18 connection closed
[13:23:59.235][4] Disconnecting client fd 18
[13:23:59.235][5] connection_teardown dev 2 sport 3 dport 62078
[13:23:59.236][5] [OUT] dev=2 sport=3 dport=62078 seq=5514 ack=1578 flags=0x4 window=131072[512] len=0
[13:23:59.236][4] Disconnecting client fd 13
[13:24:01.456][4] Device 1-10 RX aborted due to error or disconnect
[13:24:01.456][4] Device 1-10 RX aborted due to error or disconnect
[13:24:01.457][4] Device 1-10 RX aborted due to error or disconnect
[13:24:01.457][3] Removed device 2 on location 0x1000a
[13:24:01.457][5] connection_teardown dev 2 sport 2 dport 62060
[13:24:01.457][4] Disconnecting client fd 16
[13:24:01.457][5] client_device_remove: id 2
[13:24:01.888][4] preflight_worker_handle_device_add: Finished waiting for notification from device 66e9800a3c386bfc30f2addb8fc12d9705b28266, is_device_connected 0
[13:24:05.130][4] Found new device with v/p 05ac:12a8 at 1-11
[13:24:05.132][4] Setting configuration for device 1-11, from 1 to 4
[13:24:06.302][4] Found interface 1 with endpoints 04/85 for device 1-11
[13:24:06.302][4] Using wMaxPacketSize=512 for device 1-11
[13:24:06.303][4] USB Speed is 480 MBit/s for device 1-11
[13:24:06.303][4] Got lang ID 1033 for device 1-11
[13:24:06.303][4] Got serial '66e9800a3c386bfc30f2addb8fc12d9705b28266' for device 1-11
[13:24:06.304][3] Connecting to new device on location 0x1000b as ID 3
[13:24:06.304][5] All 3 RX loops started successfully
[13:24:06.304][3] Connected to v2.0 device 3 on location 0x1000b with serial number 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:24:06.304][4] preflight_worker_handle_device_add: Starting preflight on device 66e9800a3c386bfc30f2addb8fc12d9705b28266...
[13:24:06.305][4] New client on fd 13 (self)
[13:24:06.305][5] Client command in fd 13 len 512 ver 1 msg 8 tag 10
[13:24:06.305][5] Client 13 connection request to device 3 port 62078
[13:24:06.305][5] [OUT] dev=3 sport=1 dport=62078 seq=0 ack=0 flags=0x2 window=131072[512] len=0
[13:24:06.306][5] [IN] dev=3 sport=62078 dport=1 seq=0 ack=1 flags=0x12 window=131072[512] len=0
[13:24:06.306][5] [OUT] dev=3 sport=1 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=0
[13:24:06.307][5] send_pkt fd 13 tag 10 msg 8 payload_length 278
[13:24:06.307][5] Client 13 switching to CONNECTED state
[13:24:06.308][5] [OUT] dev=3 sport=1 dport=62078 seq=1 ack=1 flags=0x10 window=131072[512] len=284
[13:24:06.309][5] [IN] dev=3 sport=62078 dport=1 seq=1 ack=285 flags=0x10 window=131072[512] len=4
[13:24:06.310][5] [OUT] dev=3 sport=1 dport=62078 seq=285 ack=1 flags=0x10 window=131072[512] len=0
[13:24:06.310][5] [IN] dev=3 sport=62078 dport=1 seq=5 ack=285 flags=0x10 window=131072[512] len=297
[13:24:06.310][5] [OUT] dev=3 sport=1 dport=62078 seq=285 ack=1 flags=0x10 window=131072[512] len=0
[13:24:06.311][5] reading key HostID from config_file /var/lib/lockdown/66e9800a3c386bfc30f2addb8fc12d9705b28266.plist
[13:24:06.311][4] New client on fd 17 (self)
[13:24:06.312][5] Client command in fd 17 len 421 ver 1 msg 8 tag 11
[13:24:06.312][5] reading key SystemBUID from config_file /var/lib/lockdown/SystemConfiguration.plist
[13:24:06.312][5] got SystemBUID 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A
[13:24:06.312][5] using 48FC3BCE-ADA1-FB3C-3752-F3DBC18D6C7A as SystemBUID
[13:24:06.312][5] send_pkt fd 17 tag 11 msg 8 payload_length 260
[13:24:06.313][4] Client 17 connection closed
[13:24:06.313][4] Disconnecting client fd 17
[13:24:06.313][5] [OUT] dev=3 sport=1 dport=62078 seq=285 ack=302 flags=0x10 window=131072[512] len=439
[13:24:06.321][5] [IN] dev=3 sport=62078 dport=1 seq=302 ack=724 flags=0x10 window=131072[512] len=4
[13:24:06.321][5] [OUT] dev=3 sport=1 dport=62078 seq=724 ack=302 flags=0x10 window=131072[512] len=0
[13:24:06.321][5] [IN] dev=3 sport=62078 dport=1 seq=306 ack=724 flags=0x10 window=131072[512] len=354
[13:24:06.322][5] [OUT] dev=3 sport=1 dport=62078 seq=724 ack=302 flags=0x10 window=131072[512] len=0
[13:24:06.322][4] New client on fd 17 (self)
[13:24:06.323][5] Client command in fd 17 len 511 ver 1 msg 8 tag 12
[13:24:06.324][5] send_pkt fd 17 tag 12 msg 8 payload_length 13138
[13:24:06.328][4] Client 17 connection closed
[13:24:06.328][4] Disconnecting client fd 17
[13:24:06.353][5] Sending ACK due to expired timeout (3287051 -> 3287082)
[13:24:06.353][5] [OUT] dev=3 sport=1 dport=62078 seq=724 ack=660 flags=0x10 window=131072[512] len=0
[13:24:07.519][5] [OUT] dev=3 sport=1 dport=62078 seq=724 ack=660 flags=0x10 window=131072[512] len=293
[13:24:07.563][5] [IN] dev=3 sport=62078 dport=1 seq=660 ack=1017 flags=0x10 window=131072[512] len=90
[13:24:07.564][5] [OUT] dev=3 sport=1 dport=62078 seq=1017 ack=660 flags=0x10 window=131072[512] len=0
[13:24:07.564][5] [IN] dev=3 sport=62078 dport=1 seq=750 ack=1017 flags=0x10 window=131072[512] len=1096
[13:24:07.564][5] [OUT] dev=3 sport=1 dport=62078 seq=1017 ack=660 flags=0x10 window=131072[512] len=0
[13:24:07.591][5] [OUT] dev=3 sport=1 dport=62078 seq=1017 ack=1846 flags=0x10 window=131072[512] len=1068
[13:24:07.601][5] [IN] dev=3 sport=62078 dport=1 seq=1846 ack=2085 flags=0x10 window=131072[512] len=6
[13:24:07.601][5] [OUT] dev=3 sport=1 dport=62078 seq=2085 ack=1846 flags=0x10 window=131072[512] len=0
[13:24:07.601][5] [IN] dev=3 sport=62078 dport=1 seq=1852 ack=2085 flags=0x10 window=131072[512] len=45
[13:24:07.601][5] [OUT] dev=3 sport=1 dport=62078 seq=2085 ack=1846 flags=0x10 window=131072[512] len=0
[13:24:07.602][4] preflight_worker_handle_device_add: StartSession success for device 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:24:07.602][4] preflight_worker_handle_device_add: Finished preflight on device 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:24:07.602][5] client_device_add: id 3, location 0x1000b, serial 66e9800a3c386bfc30f2addb8fc12d9705b28266
[13:24:07.602][5] [OUT] dev=3 sport=1 dport=62078 seq=2085 ack=1897 flags=0x10 window=131072[512] len=33
[13:24:07.602][5] [OUT] dev=3 sport=1 dport=62078 seq=2118 ack=1897 flags=0x10 window=131072[512] len=388
[13:24:07.602][5] [IN] dev=3 sport=62078 dport=1 seq=1897 ack=2506 flags=0x10 window=131072[512] len=33
[13:24:07.603][5] [OUT] dev=3 sport=1 dport=62078 seq=2506 ack=1897 flags=0x10 window=131072[512] len=0
[13:24:07.603][5] [IN] dev=3 sport=62078 dport=1 seq=1930 ack=2506 flags=0x10 window=131072[512] len=267
[13:24:07.603][5] [OUT] dev=3 sport=1 dport=62078 seq=2506 ack=1897 flags=0x10 window=131072[512] len=0
[13:24:07.603][5] [OUT] dev=3 sport=1 dport=62078 seq=2506 ack=2197 flags=0x10 window=131072[512] len=31
[13:24:07.604][5] [IN] dev=3 sport=62078 dport=1 seq=2197 ack=2537 flags=0x10 window=131072[512] len=31
[13:24:07.604][5] [OUT] dev=3 sport=1 dport=62078 seq=2537 ack=2197 flags=0x10 window=131072[512] len=0
[13:24:07.604][5] connection_teardown dev 3 sport 1 dport 62078
[13:24:07.604][5] [OUT] dev=3 sport=1 dport=62078 seq=2537 ack=2228 flags=0x4 window=131072[512] len=0
[13:24:07.604][4] Disconnecting client fd 13
^C[13:24:19.075][3] Caught signal 2, exiting
[13:24:19.075][4] Event processing interrupted
[13:24:19.075][3] usbmuxd shutting down
[13:24:19.075][5] device_kill_connections
[13:24:19.176][5] usb_shutdown
[13:24:19.176][3] Removed device 3 on location 0x1000b
[13:24:19.176][5] client_device_remove: id 3
[13:24:19.176][5] usb_disconnect: cancelling RX xfer 0x7fa3822130
[13:24:19.176][5] usb_disconnect: cancelling RX xfer 0x7fa3872610
[13:24:19.176][5] usb_disconnect: cancelling RX xfer 0x7fa3872750
[13:24:19.176][5] Device 1-11 RX transfer cancelled
[13:24:19.176][5] Device 1-11 RX transfer cancelled
[13:24:19.176][5] Device 1-11 RX transfer cancelled
[13:24:19.177][5] device_shutdown
[13:24:19.178][5] client_shutdown
[13:24:19.178][3] Shutdown complete
</details>

Please let me know if further testing needed.

**Comment by neheb** [comment]
Removed the disable-preflight parameter.

**Pull request merged**
