### PR TITLE
perl: switch to 5.30.0

### PR DESCRIPTION
**Pull request by httpstorm**
The current version of perl 5.28.1 cannot be compiled on macOS 11,
because hints/darwin.sh checks only for version 10.*, and fails on 11.*
The check is fixed in 302-macos_11_support.patch, but only allows building
of perl using a single worker due to some sort of a race condition.
If multiple workers are used, the build fails with missing Errno.pm.
The race condition is corrected in perl 5.30.0 up to 5.32.0.
This patch switches to 5.30.0 to overcome the race condition,
and modifies darwin.sh to add support for building on macOS 11.
Unfortunately this is not a complete patch, beucase at the current
state, the build still fails:
`make package/feeds/packages/perl/host/compile V=sc`
OK

make package/feeds/packages/perl/compile V=sc
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: input file: /Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/bin/perl5.30.0 is not a Mach-O file
Cannot update /Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/bin/perl5.30.0 dependency paths
make[3]: *** [makefile:445: install-all] Error 1
make[3]: Leaving directory '/Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0'
make[2]: *** [Makefile:152: /Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/.built] Error 2
```

Another symptom is that with
5.30.0 build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/bin
contains only perl5.30.0, while with the original 5.28.1 it contains many executables.

More research is needed to find the cause of this error. Perhaps
the rest of the perl components also need to be updated. This commit
should only be used as a starting point for moving towards perl 5.30.0
or preferably the latest 5.32.0, and should not be accepted before the
above issues are resolved.

Maintainer: @pprindeville
Compile tested: OpenWrt 3f1109bf2af2cf4977689a33ea481afaaac8dc98
Target System: Marvell EBU Armada
Subtarget: Marvell Armada 37x/38x/XP
Target Profile: Linksys WRT3200ACM

### CODE REVIEW

**Comment by neheb** [comment]
It errors with:

```
 (cd /home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/lib/perl5/5.30 && rsync --relative -rlHp --itemize-changes --exclude=\*.pod --exclude=.packlist  --prune-empty-dirs arybase.pm auto/arybase /home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-arm_cortex-a9_vfpv3-d16/perlbase-arybase/usr/lib/perl5/5.30)
rsync: link_stat "/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/lib/perl5/5.30/arybase.pm" failed: No such file or directory (2)
rsync: link_stat "/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/lib/perl5/5.30/auto/arybase" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
```

**Comment by httpstorm** [comment]
@neheb Hello Rosen!
Yes I told you it has build errors. I was hoping that someone with better experience than me will help fixing them or at least provide me with a hint what to try.

**Comment by pprindeville** [comment]
I recommend asking on `perl5-porters@perl.org`.  I get excellent advice there.

**Comment by httpstorm** [comment]
@pprindeville, @neheb 
I have resolved all errors in my new pull-request: `perl: fix build errors on macOS` https://github.com/openwrt/packages/pull/14676

**Pull request closed without merging**
