### PR TITLE
boost: Remove utime usage

### PR DESCRIPTION
**Pull request by neheb**
Optionally fixes compilation with uClibc-ng.

Organized patches properly. The second uClibc-ng patch was named wrong.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ClaymorePT 
Compile tested: arc700

### CODE REVIEW

**Comment by karlp** [comment]
Where's the upstream ticket for remvoing utime?

**Comment by neheb** [comment]
https://github.com/boostorg/filesystem/pull/115

A slightly different commit was merged. I will replace my patch with that one.

**Comment by neheb** [comment]
Switched to upstream commit.

**Comment by diizzyy** [comment]
Rather than sprinkling random patches all over the tree, submit upstream and wait rather than doing quick fixes. uClibc-ng isn't really a priority at all at this point.

**Comment by ClaymorePT** [comment]
I agree with Daniel. It is preferable if such core changes come from
upstream.

A quarta, 31/07/2019, 23:55, Daniel Engberg <notifications@github.com>
escreveu:

**Comment by neheb** [comment]
The patch is an upstream backport...

**Comment by ClaymorePT** [comment]
Yes, I understood that but can't we just wait for the next release of
Boost? It's due in two weeks.

A quinta, 1/08/2019, 00:16, Rosen Penev <notifications@github.com> escreveu:

**Comment by neheb** [comment]
No real difference to me.

**Comment by diizzyy** [comment]
Merged upstream https://github.com/boostorg/filesystem/commit/83b989ecee478be083db8dc0cc7a5387615bd3cb

**Pull request closed without merging**
