### PR TITLE
owut: add new package

### PR DESCRIPTION
**Pull request by efahl**
owut (OpenWrt Update Tool) is a command line program that gathers information from the various openwrt.org build sites and reports status on various aspects of builds and package availability. It also shows many details about your current configuration and installed packages, allowing it to create, download, verify and install new images containing the user-installed packages.

It is written completely in 'ucode', allowing for user customization on the installed device, without the need for compilers and linkers.

Documentation is available at https://github.com/efahl/owut 
Forum thread at https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035

Maintainer: me @efahl
Compile tested: x86 generic SNAPSHOT
Run tested: x86 generic SNAPSHOT

### CODE REVIEW

**Comment by stangri** [comment]
@efahl sorry, for somebody who may not be up-to-date, can you elaborate a little on how it's different from `auc`?

**Comment by efahl** [comment]
It is basically auc++.  It has most (all?) of auc's features, but adds a whole slew of extra options for the build.  Additionally, it contains several diagnostics that auc does not, so it allows you to check various things that would cause a build breakage before you request a build (usually packages not building, sometimes base build not yet complete).  Jump on over to that forum thread, lots more detail there...

**Comment by stangri** [comment]
> It is basically auc++. It has most (all?) of auc's features, but adds a whole slew of extra options for the build.

Why not replace auc with this code then?

**Comment by efahl** [comment]
> Why not replace auc with this code then?

I suppose ultimately it might do that, but it needs some maturity first.  Plus the dependency on `ucode-mod-uclient`, which is only available in SNAPSHOT, means it can't be backported until that package is also backported.

**Comment by stangri** [comment]
> > Why not replace auc with this code then?
> 
> I suppose ultimately it might do that, but it needs some maturity first. Plus the dependency on `ucode-mod-uclient`, which is only available in SNAPSHOT, means it can't be backported until that package is also backported.

Maybe it's worth considering replacing auc with this code in snapshot and keeping old auc in the 23.05 tree. That that this code will get exposure/testing on snapshot and then trickle down into the new release branch when it's forked. Just my 2c.

**Comment by BKPepe** [comment]
> It is basically auc++. It has most (all?) of auc's features

cc: @aparcar and maybe @dangowrt , these two could be interested in it as well

**Comment by dangowrt** [comment]
Absolutely lovely, rewriting auc in ucode has been on my ToDo list for too long and I can remove it there now.
There are a few things which will currently make harder to replace auc in all use-cases it serves, but they should be easy to address:

1. Please don't rely on https://firmware-selector.openwrt.org/config.js. There are people who run their own instances of the update server, even forks of our distro do that. You should only rely on the (configurable) asu URL. If anything is not there or cannot be inferred from there, please talk with @aparcar to amend asu accordingly.

2. Please use ubus call rpc-sys packagelist to get the list of installed packages. Parsing the opkg list on disk is not so cool, also because we are going to switch from opkg to APK very soon and it would be nice to keep the updater agnostic.

3. Lets make an API instead of scarping `failures.html`. The idea is totally cool, but have in mind that this is an updater client -- it may be run on an outdated system which has not been updated for a long time, and depending on ethereal html content is likely to break over time. While some people update their systems daily, others only do that every couple of years or if they see a real need. Both has to work fine.

4. You should validate the core version as well as package versions returned by the server before proceeding to install. The user has confirmed a certain action, and you need to make sure that this is the action you are going to perform. It is unfortunately not so uncommon that the versions requested and versions delivered don't match, in that case you should abort with an error.

5. It'd be cool to have a way to tell `upgrade` command to remain within the currently running branch. Ie. only update from 24.08.0 to 24.08.1, but don't jump to 25.04.0. Similarly if 23.05-SNAPSHOT is currently running, only upgrade to a more recent 23.05-SNAPSHOT build but refrain from jumping to main-branch SNAPSHOT build.

Generally the code looks clean and nice. Some ToDo here and there (like [owut#L1635](https://github.com/efahl/owut/blob/main/files/owut#L1635)), some unreachable code (`if (false) { ... }`) which should be cleaned up before we bother the general public with this, but that's obvious I guess. Maybe we can move all settings to attended-sysupgrade UCI config file instead of having another one just for owut?

**Comment by efahl** [comment]
Most of the sources of data came from first trying to use what's on sysupgrade, then failing over to downloads or firmware-selector when the data there was missing, or out-of-date frequently.  For example, the `version_code` on sysupgrade lags behind downloads by hours or sometimes days, hence my grabbing it from downloads.

Back in Sept (or whenever it was) when Paul made his call to arms about ASU server, I got a local instance of ASU running and never could get it to complete it's metadata collection phase, it always hung and required a cold-restart.  I still haven't figured out if it's timeouts (which I've increased several times) or quotas/throttling or ???  I'm in California, so the route to the downloads site is pretty long, which is why I tried longer timeouts first.

My plan was, when I get owut sort of settled, I'd circle back and see if I can resolve those issue and from there I can suggest extensions to ASU metadata to provide owut with One Stop Shopping, get it all from ASU...

>     1. Please don't rely on https://firmware-selector.openwrt.org/config.js.

Right, I only use it to get the "default_version" right now, experimented with it for the available versions due to its more exhaustive list, but went back to sysupgrade API overview for that same reason (we don't want to tell people that 19.07 is still available for upgrades).

>     2. Please use ubus call rpc-sys packagelist to get the list of installed packages. 

Much of what owut is doing depends on a lot of the properties about packages that rpc-sys doesn't provide: the depends and provides lists, specifically (and secondarily the "essential" flag).  

The evolution of what became `owut list` was initially to answer the question "what packages did I install on my router?".  This requires knowing 1) what the default packages are, and 2) what the "top-level" packages are (i.e., those that have no dependents), and differencing those two sets.  In order to figure out the top-level set, you need the dependency tree, hence my parsing of the package database.  (The opkg/status parser was substantially lifted from the rpc-sys code...)

> Parsing the opkg list on disk is not so cool, also because we are going to switch from opkg to APK very soon and it would be nice to keep the updater agnostic.

I've been looking at/thinking about APK (both the raw data file, equivalent to opkg's status file, and the API in libapk) for about a month (installed Alpine on one of my laptops so I could have a "native" experience with it).  The raw ASCII file is very simple and is substantially similar to the opkg status file, so if we have that, it makes selecting pretty easy.  On the other hand, I was thinking it would be nicer to have a `ucode-mod-pkg-mgr` based on libapk, but with as you say, an agnostic interface.  That would move a whacking big chunk of owut into a general purpose module (all of those `what_depends` and `what_provides`, all of the ABI machinations and so on...).  Or, if such an API were an rpc-sys call collection, we could use them in LuCI and that would be maybe even better.


>     3. Lets make an API instead of scarping `failures.html`.

👍🏼 You can guess how I feel about the current scheme from my comments on the hacky code.

This feature came from a bunch of forum posts of the form "hey, this package disappeared, what's up?" and "I ran auc and it's saying 'invalid package specification' or some such thing".  The html was the only place I could find that had current info regarding what was going on.

>     4. You should validate the core version as well as package versions returned by the server before proceeding to install.

Ah, I complete missed that one, thanks.
 
>     5. It'd be cool to have a way to tell `upgrade` command to remain within the currently running branch. Ie. only update from 24.08.0 to 24.08.1, but don't jump to 25.04.0. Similarly if 23.05-SNAPSHOT is currently running, only upgrade to a more recent 23.05-SNAPSHOT build but refrain from jumping to main-branch SNAPSHOT build.

Yeah, like `auc`'s -b option.  Should be easy enough, just scan through the available versions lists for the last one published.  I'm thinking `--version-to` takes `23.05.3` for that specific release and drop the dot to `23.05` for "lastest on this branch".  Make them be specific if they want to jump to/between snapshots...

> Generally the code looks clean and nice. Some ToDo here and there (like [owut#L1635](https://github.com/efahl/owut/blob/main/files/owut#L1635)), some unreachable code (`if (false) { ... }`) which should be cleaned up before we bother the general public with this, but that's obvious I guess.

Oh, yeah, there's tons of junk in there that needs to be gutted out the whole `_test` function is just there so I can answer and re-answer questions I have without churning the code too much.

> Maybe we can move all settings to attended-sysupgrade UCI config file instead of having another one just for owut?

Sure, that would be very simple in `owut` itself due to the way I've implemented the config file with the argument parser.  If you've got

**Comment by efahl** [comment]
> There is **no target-wide rule** about the image type. On mvebu, for example, some boards (with SPI memory) use uImage and hence the files are simply called `squashfs-sysupgrade.bin`, other boards use whole-disk sdcard images. It depends on what the vendor firmware implemented also. So I don't think it makes much sense to try to be smart about this in the updater client and track this for each target (which won't work) or even board.

Yeah, hence my "BUG" notation at that line you reference...

This feature was to address all those forum posts about "I installed OpenWrt a year ago and can't figure out which image I used", and the more bold "I bricked my router because I upgraded using the wrong image."  I wanted to be able to just say, "Run `owut check` and you'll get more info than you dreamed possible".

This sort of thing happens at least weekly, and maybe more frequently, and reconstructing the full image name is quite painful (hence this bug!).  Maybe we should extend board.json to contain the original image name, it would address a lot of issues for 30-40 bytes of storage.

**Comment by dangowrt** [comment]
> Maybe we should extend board.json to contain the original image name, it would address a lot of issues for 30-40 bytes of storage.

The big question is just how this information would find it's way into `board.json`...

**Comment by dangowrt** [comment]
> For example, the `version_code` on sysupgrade lags behind downloads by hours or sometimes days, hence my grabbing it from downloads.

@aparcar wanted to resolve this (and maybe even did?) via adding a web-hook to the ImageBuilder. Another trivial solution would be to include a pointer to the download server in `json/v1/overview.json`, so then you could grab `version.buildinfo` and `profiles.json` from there.

> 2) what the "top-level" packages are (i.e., those that have no dependents),

With `opkg` there is the `user` flag for that, and the rpc-sys API handles this depending on whether the `all` parameter is set true (then all packages are returned) or false (then only user-selected packages are returned). The default package set is (as of today) not stored anywhere on the image. Imho you don't need full dependency resolution to answer that question, the LuCI app and auc also manage without that.
With `apk` there is also the list of all installed packages (and versions) as well as the `world` file, which (similar to gentoo) records all user-selected dependency atoms. So it's a bit more expressive because the user may decide to install a specific version, or limit the to-be-installed version, both is not possible with opkg and currently also cannot be expressed in rpc-sys API...

> Or, if such an API were an rpc-sys call collection, we could use them in LuCI and that would be maybe even better.

Lets do that, lets extend the `rpc-sys` API to cover all needs of LuCI and various updater clients written in different languages, ...

**Comment by efahl** [comment]
> Just tried this on Puzzle M902 device, and it failed with

Should be fixed in https://github.com/efahl/owut/commit/677d240281a5ccb515a90af96676a7b3f352139d

I made the assumption that a given device won't have both a "sysupgrade" and "sdcard" image.  We all know about assumptions...

**Comment by efahl** [comment]
> Imho you don't need full dependency resolution to answer that question, the LuCI app and auc also manage without that.

Right, just set `diff_packages=true` in the json blob and supply all the packages, which solves the "build me an image case", but owut tries to satisfy a couple of other use cases:

1) Generation of a "just what I installed" package list for Firmware Selector, imagebuilder and source build .config files (that's what the `owut list --format xxx` variants produce).

2) To support the `--remove` option, which cleans the installed list of unneeded dependencies, so they don't become new top-level packages.  (E.g., a naive `--remove` of just `luci`, without doing recursive dependency removal, results in `luci-light` and `luci-app-opkg` suddenly become "top-level".)

**Comment by dangowrt** [comment]
> I made the assumption that a given device won't have both a "sysupgrade" and "sdcard" image. We all know about assumptions...

I totally agree that such heuristics are never beautiful. When writing `auc` I studied all targets and boards and come up with the logic you find there: First try `sysupgrade` image, if that doesn't exist, try `combined`, then `sdcard`. In that order of it worked for all boards.

**Comment by dangowrt** [comment]
> 1. Generation of a "just what I installed" package list for Firmware Selector, imagebuilder and source build .config files (that's what the `owut list --format xxx` variants produce).

Maybe I don't understand, but `ubus call rpc-sys packagelist '{"all": false}'` should be exactly that. Only the deliberately selected packages, ie. the default package set plus what ever the user added, exactly identical to what you see in Firmware Selector when you edit the list of packages.

> 2\. To support the `--remove` option, which cleans the installed list of unneeded dependencies, so they don't become new top-level packages.  (E.g., a naive `--remove` of just `luci`, without doing recursive dependency removal, results in `luci-light` and `luci-app-opkg` suddenly become "top-level".)

If you decide which package is "top-level" by dependency tracking, then this is true. However, there is the "user" flag in the opkg status (and `/etc/apk/world` when building with APK). That already got the answer to this question, without any need dependency tracking. It is true that for images generated with the buildroot (ie. packages selected in menuconfig) this information is lost. However, images created by ImageBuilder it works fine.

**Comment by efahl** [comment]
Just added a missing dependency to the makefile and updated hash to head, in case anyone is using it for testing...

**Comment by jow-** [comment]
You can eliminate the ucode-mod-math dependency entirely by reimplementing `math.isnan()` as `const isnan = (x) => x != x`

**Comment by efahl** [comment]
> You can eliminate the ucode-mod-math dependency entirely by reimplementing `math.isnan()` as `const isnan = (x) => x != x`

Thanks, done.  Pushed new makefile so testers can pick it up...

**Comment by efahl** [comment]
Addressed a slew of @dangowrt's comments above; Makefile contains updated versions and hashes.

Still need to deal with html scraping, a bit of validation and cleaning out test code.

**Pull request merged**
