### PR TITLE
mwan3: Add missing IPs to wanb

### PR DESCRIPTION
**Pull request by damadmai**
Maintainer: Florian Eckert @feckert
Compile tested: not needed
Run tested: x86_64

Description:
Only two of the four IPs defined for wan are found in wanb, adding it so it is the same.

### CODE REVIEW

**Comment by damadmai** [comment]
option reliability '2' is two, for wan but '1' for wanb. Is this intended?

**Comment by neheb** [comment]
This needs a PKG_RELEASE bump.

**Comment by damadmai** [comment]
It did the PKG_RELEASE bump, anything else missing?

**Comment by feckert** [comment]
Sorry I forgot.
Thanks merged :+1:

**Pull request merged**
