### PR TITLE
LoRa: Add package lora-packet-forwarder

### PR DESCRIPTION
**Pull request by xueliu**
Signed-off-by: Xue Liu <liuxuenetmail@gmail.com>

Maintainer:  Xue Liu [liuxuenetmail@gmail.com](mailto:liuxuenetmail@gmail.com)
Compile tested: (RPi 2B LEDE snapshots 01.03.2019)
Run tested: (RPi 2B + im880a LEDE snapshots 01.03.2019)

Description:

This PR adds new packages for:

https://github.com/Lora-net/packet_forwarder

with my personal patches.

It dependes on #6808

### CODE REVIEW

**Comment by brainstorm** [comment]
@xueliu I found this `global_conf.json` script and autogenerated gateway configs from TTN that will help us a lot in packaging this: https://github.com/TheThingsNetwork/gateway-conf

I'm adding it to my PicoGW packages, I think it would make sense if you add it too... or perhaps we could create an independent package that wraps it up for both of us? Something line `lora-ttn-gateway-configs` and put it as a dependency for our packet forwarder packages?

**Comment by brainstorm** [comment]
Looking through your PR, I think I might just drop my PR and stick with yours (good job with the UCI integration and all)... not sure if the SPI vs USB support is easily patchable. If that's the case, it'll be the best thing to do (instead of keeping 4 different packages, be done with just 2).

**Comment by brainstorm** [comment]
I went ahead and compared both codebases and they differ a bit on the start/init sequence, so it might not be worth the effort to patch/PR both codebases together on a second thought:

https://github.com/Lora-net/picoGW_hal/blob/master/libloragw/src/loragw_hal.c#L825
https://github.com/Lora-net/lora_gateway/blob/a955619271b5d0a46d32e08150acfbc1eed183b7/libloragw/src/loragw_hal.c#L696

**Comment by xueliu** [comment]
> @xueliu I found this `global_conf.json` script and autogenerated gateway configs from TTN that will help us a lot in packaging this: https://github.com/TheThingsNetwork/gateway-conf
> 
> I'm adding it to my PicoGW packages, I think it would make sense if you add it too... or perhaps we could create an independent package that wraps it up for both of us? Something line `lora-ttn-gateway-configs` and put it as a dependency for our packet forwarder packages?
> 
> That way it would make it easier to not repeat ourselves and reuse that package for our respective installations?

We can make a package to hold json files in https://github.com/TheThingsNetwork/gateway-conf. But the problem is how to dynamic switch different json files.

**Comment by brainstorm** [comment]
> We can make a package to hold json files in https://github.com/TheThingsNetwork/gateway-conf. But the problem is how to dynamic switch different json files.

That's exactly right, I think that your approach with the https://github.com/xueliu/lora-feed is the way to go.

**Comment by neheb** [comment]
```
Commit subject line MUST start with '<package name>: ' ( LoRa: Add package packet-forwarder)
```

Should be lora-packet-forwarder: Add

**Comment by aparcar** [comment]
@xueliu Hi do you mind I rebase this & adopt the commit message?

**Comment by aparcar** [comment]
Work continues here https://github.com/openwrt/packages/pull/13379

**Pull request closed without merging**
