### PR TITLE
LuaRocks: Add new package

### PR DESCRIPTION
**Pull request by amrhassan**

### CODE REVIEW

**Comment by thess** [comment]
Please read and comply with: https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

* No signed-off-by in commit message
* Update Copyright to be current
* Add PKG_LICENSE info
* Commit comment should be something like - "LuaRocks: Add new package"
* PKG_BUILD_DIR is unnecessary here
* Overriding Build/Compile and Build/Configure with default is unnecessary

**Comment by amrhassan** [comment]
@thess Changes made. I need to override Build/Compile though because I'm calling a non-default Make target.

**Comment by thess** [comment]
Ah, I missed the extra arg to build/compile/default.

One last request -- It's been 2015 for almost 2 months now, please update the OpenWrt Copyright (bullet 2 above).TIA

**Comment by amrhassan** [comment]
@thess Copyright notice updated.

I'm actually not sure about where to place it, since it's technically a package for an executable that is a package manager for a specific language, and its source code is actually useful enough to be used as a library sometimes. I've moved it to lang to be consistent with the CATEGORY. If you have a different opinion please let me know.

**Comment by thess** [comment]
I guess the category is a bit ambiguous (language or utility) Since It is closely connected to a language (lua) I just thought that would be the best place.

Thanks for your submissions, etc.

**Pull request merged**
