### PR TITLE
apr + apr-util: cleanups + add drivers

### LINKED ISSUE #10886: apr-util: Build apr-util dbd/crypto/ldap as modules
Maintainer @heil

Description:

The apr-util library is currently built as a monolithic library, with some modules included, and some modules removed.

Ideally apr-util should be built with modules such as apr_dbd_mysql, apr_crypto_openssl and apr_ldap in modular packages.

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @heil 
Compile tested: ath79 + arc770 on 19.07
Run tested: ath79 master, run-tested with apache/httpd

Description:
Hi all,

This resolves #10886 and #10884

Kind regards,
Seb

### CODE REVIEW

**Comment by minfrin** [comment]
I split out the apr part of this PR into https://github.com/openwrt/packages/pull/10921.

I have a separate PR for apr-util that I am combining with yours, to follow.

**Comment by micmac1** [comment]
> I split out the apr part of this PR into https://github.com/openwrt/packages/pull/10921.
>
> I have a separate PR for apr-util that I am combining with yours, to follow.

:) I think you just want to include updates for the scripts, right? In
that case we can just wait for the next apr/apr-util releases and then
drop the sed scripts.

I'm just saying, might not be worth the while.

**Comment by minfrin** [comment]
This PR has been included in https://github.com/openwrt/packages/pull/10924, which makes it possible to build third party Apache modules.

**Comment by tru7** [comment]
thank you very much for your work. For the first time since many months I again have a working apache daemon on snapshot. I used your work on micmac1:apr-master and micmac1:apache-master to build the packages and quickly and sucessfully tested standard webserver and also proxy modules (on ath79 / mips_24kc)
I wonder why installing the feed for apr, apr-util and apache didn't also resolved the dependencies for all libraries. I had to manually include some like libxml2 and I still have to add support for ldap and pgsql.

**Comment by micmac1** [comment]
> thank you very much for your work. For the first time since many months I again have a working apache daemon on snapshot. I used your work on micmac1:apr-master and micmac1:apache-master to build the packages and quickly and sucessfully tested standard webserver and also proxy modules (on ath79 / mips_24kc)

Thanks for testing! Glad to hear that proxy-mode no longer segfaults.

> I wonder why installing the feed for apr, apr-util and apache didn't also resolved the dependencies for all libraries. I had to manually include some like libxml2 and I still have to add support for ldap and pgsql.

I'm not completely sure how you put the changes into your local repo, so not really any idea from my side :)

**Comment by tru7** [comment]
well I just cloned your repo locally and made the feeds for apr, apr-util and apache in my buildroot look exactly the same. then I run scripts/feeds install and make menuconfig and finally run make package/x/compile.

**Comment by minfrin** [comment]
> :) I think you just want to include updates for the scripts, right? In
> that case we can just wait for the next apr/apr-util releases and
> then drop the sed scripts.

> I'm just saying, might not be worth the while.

I have some external modules to build, and I need to get that working.

Someone has committed and released a breaking change to apr v1.7 that causes apr compile to fail in openwrt. There is another change in the yet-to-be-released apr-util v1.7 that prevents its release, and it looks that that will need to be reverted before a release is possible. httpd should be reasonably straightforward.

I would rather see this work committed as is and be available for people to use now, rather than wait for apr and httpd to make releases. As soon as those releases are made, each patch can be trivially removed by whoever is doing the update.

**Comment by micmac1** [comment]
Added odbc and gdbm (dbm) drivers to last commit.

**Pull request merged**
