### PR TITLE
dawn: fix reboot

### PR DESCRIPTION
**Pull request by PolynomialDivision**
DAWN has a race condition with umdns that prevents dawn from surviving a reboot.

Increase procd start and stop of dawn to 100.

Fixes:
https://github.com/berlin-open-wireless-lab/DAWN/issues/56

### CODE REVIEW

**Comment by jow-** [comment]
100 is not a valid value. Since START / STOP values are lexically ordered, `100 < 20`. The highest legal order index is 99.

**Comment by PolynomialDivision** [comment]
> 100 is not a valid value. Since START / STOP values are lexically ordered, `100 < 20`. The highest legal order index is 99.

Whups. Thanks! I tested before doing the PR and it worked.

**Comment by neheb** [comment]
ping @dibdot 

I remember 95 being the max. I could be wrong though.

**Comment by PolynomialDivision** [comment]
> ping @dibdot
> 
> I remember 95 being the max. I could be wrong though.

There is `S99bootcount`and `S99urandom_seed` ;)

**Comment by neheb** [comment]
There is also S95done.

**Comment by dibdot** [comment]
< 95 is only a (reasonable) recommendation, the S95done script should be the last one in the boot order (calling rc.local) - but it is no technical limit.

Anyway, with the delayed call you will probably only make the error less likely to occur.

**Comment by PolynomialDivision** [comment]
> Anyway, with the delayed call you will probably only make the error less likely to occur.

Okay, I will fix that differently. ;) But I will set it to +1 of umdns?

**Comment by dibdot** [comment]
everything > 80 and < 95 sounds reasonable ... :relaxed:

**Comment by PolynomialDivision** [comment]
> everything > 80 and < 95 sounds reasonable ... relaxed

Weird. If I set it to `99` it works. If I set it < 95, I can not create a usock: `usock: Network unreachable`...
I'm unsure how to handle that. Maybe I just respawn after waiting for some time?

**Comment by PolynomialDivision** [comment]
Thanks for all the hints. I added uloop timer that tries to bind a usock to the given port and restarts every second. 

I still think about adding `procd_add_interface_trigger`:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/network/services/igmpproxy/files/igmpproxy.init;h=c4af43068145de4121e3ae98184e5c191ee00b3b;hb=HEAD#l62

Or a respawn trigger. I don't know what happens if I can not subscribe to the uloop? :/ But that never happend.

**Comment by dibdot** [comment]
Maybe it's useful to add a special boot function to wait for umdns, e.g.:

```
boot()
{
     ubus -t 5 wait_for umdns
}

```

**Comment by PolynomialDivision** [comment]
@dibdot If I add that, my daemon won't start at all after reboot? Do I have to call from the `boot` hook(?) the `start_service` function?

**Comment by dibdot** [comment]
In "my" init scripts I call the service function like that:

```
[...]
rc_procd start_service
```

**Comment by PolynomialDivision** [comment]
> In "my" init scripts I call the service function like that (within the boot function):
> 
> ```
> [...]
> rc_procd start_service
> ```

that works. :) can I somehow wait for network becoming ready?

**Comment by dibdot** [comment]
In travelmate I use this:
```
boot()
{
	local iface="$(uci_get travelmate global trm_iface)"

	ubus -t 30 wait_for network.wireless network.interface."${iface:-"trm_wwan"}" 2>/dev/null
	rc_procd start_service
}
```
Other than that you can use Interface trigger, as examples see unbound or adblock, which only register such triggers during boot.

**Comment by PolynomialDivision** [comment]
Thanks! I already thought about interface trigger.
Your solution does not work for me? I deleted my wan interface and combined everything in a layer 2 network...

I'm fine with my solution:
```
wait_for_network()
{
	ubus -t 15 wait_for network.interface.$1
}

boot()
{
	ubus -t 5 wait_for umdns 2>/dev/null
	config_load network
	config_foreach wait_for_network interface
	rc_procd start_service
}
```
After that the network is definitely ready. :D
In future I will add reload triggers, but I'm afraid I could destroy behavior of my controller.

**Comment by dibdot** [comment]
OK, ready to merge?

**Comment by PolynomialDivision** [comment]
> OK, ready to merge?

Oh, 1sec, I will make this consistent with `2>/dev/null`.

**Comment by PolynomialDivision** [comment]
@dibdot Please merge. :)

Thanks for all your help!!! :)

**Pull request merged**
