### PR TITLE
dovecot: Fix deprecated API patch

### PR DESCRIPTION
**Pull request by neheb**
Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lucize 
Compile tested: ath79

### CODE REVIEW

**Comment by lucize** [comment]
LGTM
but unrelated
`configure: error: Can't build with GSSAPI support: krb5-config not found
`

**Comment by neheb** [comment]
Needs a host build probably. I'll look later.

**Comment by lucize** [comment]
it's just a script, the file is there, but maybe it looks for it elsewhere

**Comment by neheb** [comment]
Initial look:

Pass ac_cv_prog_KRB5CONFIG to the proper path.

**Pull request merged**
