### PR TITLE
openconnect: allow specify --protocol from config

### PR DESCRIPTION
**Pull request by mayli**
Maintainer: @nmav
Compile tested: x86_64, master
Run tested: x86_64, master, connect to globalprotect vpn with OTP

Description:

openconnect v8.10 supports 4 VPN protocols

  --protocol=anyconnect  Compatible with Cisco AnyConnect SSL VPN, as well as ocserv (default)
  --protocol=nc          Compatible with Juniper Network Connect
  --protocol=gp          Compatible with Palo Alto Networks (PAN) GlobalProtect SSL VPN
  --protocol=pulse       Compatible with Pulse Connect Secure SSL VPN

This patch allows user to specify protocol use the new "vpn_protocol"
option and deprecate the old option "juniper" which seems to be missing in
the current openconnect client.

Signed-off-by: Mengyang Li <mayli.he@gmail.com>

### CODE REVIEW

**Comment by nmav** [comment]
LGTM, the failures seem unrelated with the change. You'll also need to bump the the release version in Makefile

**Comment by nmav** [comment]
I'd also recommend an equivalent change in luci openconnect

**Comment by mayli** [comment]
Got it, will update luci once this patch get merged.

**Comment by nmav** [comment]
Merged manually. Thank you!

**Pull request closed without merging**
