### PR TITLE
JSON4Lua: Add new package

### PR DESCRIPTION
**Pull request by amrhassan**

### CODE REVIEW

**Comment by thess** [comment]
Please read and comply with: https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

* No signed-off-by in commit message
* Update Copyright to be current
* Add PKG_LICENSE info
* Commit comment should be something like - "JSON4Lua: Add new package"
* PKG_BUILD_DIR is unnecessary here

**Comment by amrhassan** [comment]
@thess Compliance changes made.

**Comment by amrhassan** [comment]
@thess Copyright notice updated.

**Comment by thess** [comment]
Thanks

**Pull request merged**
