### PR TITLE
krb5: Bump to v1.14.2

### PR DESCRIPTION
**Pull request by Xotic750**
Added John's changes (https://github.com/openwrt/packages/pull/2777) to remove errors and rebased the patch.

Signed-off-by: Graham Fairweather <xotic750@gmail.com>

### CODE REVIEW

**Comment by champtar** [comment]
@Xotic750 it's John, not Jow ... please fix

**Comment by champtar** [comment]
@MikePetullo

**Comment by champtar** [comment]
@Xotic750 i've merged #2777, please rebase

**Comment by Xotic750** [comment]
@champtar Done.

**Comment by champtar** [comment]
merged in https://github.com/openwrt/packages/commit/7088374279c28f2e2b9a4aa0c99c424fa423ab45

**Pull request closed without merging**
