### PR TITLE
https-dns-proxy: update to 2021-02-27

### PR DESCRIPTION
**Pull request by neheb**
Switch to building with Ninja for faster compilation.

Added patch fixing ninja compilation.

Minor cleanups.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @stangri 
Compile tested: ath79

### CODE REVIEW

**Comment by stangri** [comment]
Hello @neheb thanks for this update!

Could you please bring back the `PKG_VERSION`, I realize it's a duplicate entry, however without it, the compiled package version looks like this:

```sh
SG-105 in ~ # opkg list-installed https-dns-proxy
https-dns-proxy - 2021-02-26-33c6a0dd-1
```

And depending on the git stamp might be harder to upgrade (if needed) if only `PKG_RELEASE` is bumped.

**Comment by stangri** [comment]
I've compiled for x86_64 but it keeps crashing:

```
6:10:18 https-dns-proxy[14552]: [F] 1616627418.692080 src/https_client.c:95 CURLOPT_HTTP_VERSION error 1: Error
16:10:18 procd: Instance https-dns-proxy::instance2 s in a crash loop 6 crashes, 0 seconds since last crash
16:10:18 https-dns-proxy[14553]: [F] 1616627418.692795 src/https_client.c:95 CURLOPT_HTTP_VERSION error 1: Error
16:10:18 procd: Instance https-dns-proxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
```

**Comment by neheb** [comment]
Strange. If you remove the patch and move back to normal CMake, does it work?

**Comment by stangri** [comment]
> Strange. If you remove the patch and move back to normal CMake, does it work?

Might be a snapshot issue. Can you give me a few days to test?

**Comment by neheb** [comment]
Sure.

**Comment by stangri** [comment]
I've tried fresh 21.02-SNAPSHOT install with freshly installed 21.02-SNAPSHOT SDK for x86-64 and compiled (cmake and no patches) files and I keep getting the same curl error. Because WFH and being busy on evenings and throughout this weekend, I'm not sure I'll be able to spend any more time on that.

I'm sure it works, but the fact that I couldn't make the new code work on my x86-64 system is concerning. Do you know anyone else with the access to the x86-64 system to test?

**Comment by neheb** [comment]
```
 make[1]: *** No rule to make target 'package/freeswitch-lang-ru/download'.  Stop.
```

Newly introduced CI bug. Don't worry about it.

**Comment by weyou** [comment]
> I've tried fresh 21.02-SNAPSHOT install with freshly installed 21.02-SNAPSHOT SDK for x86-64 and compiled (cmake and no patches) files and I keep getting the same curl error. Because WFH and being busy on evenings and throughout this weekend, I'm not sure I'll be able to spend any more time on that.
> 
> I'm sure it works, but the fact that I couldn't make the new code work on my x86-64 system is concerning. Do you know anyone else with the access to the x86-64 system to test?

Do you get the solution for this? 
I encounter the same issue in WRT1900ACv2(Arm platform) with openwrt 19.07.7. I compiled the latest commit of [https-dns-proxy ](https://github.com/aarond10/https_dns_proxy/commit/dfbf521c69fd9e96ee9e72670ddb2a49d8f12bdc) but got:
```
/usr/sbin/https-dns-proxy -r https://dns.google/dns-query -a 127.0.0.1 -p 5053 -b 8.8.8.8,8.8.4.4 -u nobody -g nogroup -4 -vvv
[I] 1619334621.775519 main.c:194 Built Feb 15 2021 15:22:37.
[I] 1619334621.775622 main.c:195 System c-ares: 1.15.0
[I] 1619334621.775759 main.c:196 System libcurl: libcurl/7.66.0 mbedTLS/2.16.10
[I] 1619334621.775945 dns_server.c:50 Listening on 127.0.0.1:5053
[D] 1619334621.776039 logging.c:38 starting periodic log flush timer
[I] 1619334621.776258 main.c:255 DNS polling initialized for 'dns.google'
[D] 1619334621.808754 main.c:160 Received new DNS server IP '8.8.8.8,8.8.4.4'
[D] 1619334621.808902 dns_poller.c:77 DNS poll interval changed from 5 -> 120
[D] 1619334629.685428 main.c:94 Received request for id: d5e9, len: 55
[D] 1619334629.685492 https_client.c:93 Requesting HTTP/1.1: 0

[F] 1619334629.685507 https_client.c:97 CURLOPT_HTTP_VERSION error 1: Error
```

**Pull request closed without merging**
