### PR TITLE
python: add rpath for host Python extension modules

### PR DESCRIPTION
**Pull request by jefferyto**
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
This is an attempt to to fix python-cryptography failing to build at buildbot, most recently mentioned at https://github.com/openwrt/packages/pull/2456#issuecomment-193980435

I say "attempt" because I haven't been able to replicate the issue, on either my main Ubuntu machine or on a Debian virtual machine (although libffi is installed by default in both host systems and most like being used by the build process). If there is a way to replicate the failed build locally, please let me know.

**Comment by commodo** [comment]
stupid question: did you try building for arm64 or adm5120 ?
I don't which build configurations have these architectures.

I'll try to spin up a build VM and try it out too.
Maybe I'll have an idea about it. Or maybe I'll be able to reproduce.

**Comment by jefferyto** [comment]
I usually build for ar71xx as my devices are on that platform. I don't think the problem is platform-specific though, it's failing for multiple platforms.

**Comment by commodo** [comment]
Ah.
I would not desconsider the platform.
I've had Python break only on x86 on OpenWRT at some point.

Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Jeffery To <notifications@github.com> </div><div>Date:12/03/2016  21:39  (GMT+02:00) </div><div>To: openwrt/packages <packages@noreply.github.com> </div><div>Cc: Alexandru Ardelean <ardeleanalex@gmail.com> </div><div>Subject: Re: [packages] python: add rpath for host Python extension modules
  (#2489) </div><div>
</div>I usually build for ar71xx as my devices are on that platform. I don't think the problem is platform-specific though, it's failing for multiple platforms.

**Comment by commodo** [comment]
I've managed to reproduce it on a Debian Wheezy 64 bit VM while building an ARM64 image (I think ARMv8 multi-something was the target I chose).
I'll look into it more in-depth tomorrow.

**Comment by commodo** [comment]
I haven't had time to look too much into this today.
I got busy repartitioning an Android tablet I have around the house; seems that's voodoo work, just to increase the Internal Memory partition so that the tablet becomes more usable.

<anyway, back to this>
What I did get to see is that the setup.py script seems to try to load the cff_backed.so shared lib.
I think this was obvious from the build logs too ; I just only looked at it closer now.

I don't have a good idea of where this should be fixed yet.
But my presumption would be to patch python-cryptography maybe somehow to avoid running some setup.py logic during cross-compilation.
Maybe python-cryptography could use a bit more logic to make it more cross-compiler friendly.

Seems that it also fails on ar71xx (at least on buildbot):
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/python-cryptography/compile.txt

If you want, I could probably send you my VM to work on.
I'll try to make some more time next week to look at it (no promises, since it's a work week)

**Comment by jefferyto** [comment]
The issue isn't specific to python-cryptography; it affects any Python program that uses python-cffi on the host. (Actually I think the problem is more general than that, but allow me to explain...)

python-cryptography uses the OpenSSL shared libraries (`libssl.so`, `libcrypto.so`), and since those are C libraries, it uses python-cffi as a bridge. It uses python-cffi in [API level, out-of-line mode](https://cffi.readthedocs.org/en/latest/overview.html#real-example-api-level-out-of-line) and integrated inside `setup.py`, which compiles extension modules (e.g. `_openssl.so`) for the target system. (BTW this is also the best approach for OpenWrt because it moves all preparation/compilation work to the host build system, rather than leaving it to the target, often low-powered, system at runtime.)

To do this preparation/compilation work, python-cffi loads `_cffi_backend.so`, an extension module it compiled as part of its own setup process. This extension module uses libffi, and so when it is loaded, the dynamic loader (`ld-linux.so`) tries to load `libffi.so`. The error message `libffi.so.6: cannot open shared object file: No such file or directory` is the loader saying it can't find libffi.

libffi is a host prerequisite for python-cffi and is installed in `$(STAGING_DIR)/host/lib`, but this directory isn't part of the host system's shared library search path. python-cryptography will build successfully in a local buildroot if the host system already had libffi installed (as is the case with my systems); if you run `ldd _cffi_module.so` on the command-line, you can see where the dynamic loader found `libffi.so.6`.

Shared libraries can include one or more paths to where its dependencies can be found (the so-called `rpath`), and this change adds `$(STAGING_DIR)/host/lib` to `_cffi_backend.so`'s `rpath`. (Running `ldd` with the new `_cffi_backend.so` shows that it now loads the correct `libffi.so.6`.)

Actually, this change adds the `rpath` to all modules compiled as a result of a host Python program, because the problem (`$(STAGING_DIR)/host/lib` not part of the system's shared library search path) isn't specific to python-cffi. In fact, this problem isn't specific to Python at all, but other host programs seem to have ways to work around it. (For instance, the host binaries from gettext-full have an `rpath` set when necessary, as seen by the output of `readelf -d msgcat`.)

I'm not an expert in this stuff so I could be wrong (probably best to assume I am). In particular, what is happening on buildbot is conjecture, since I can't replicate the error. If your VM isn't too large, I'd be happy to download it and give it a try. Are you sure though the error you get is the same as the one in the buildbot logs (`libffi.so.6: cannot open shared object file: No such file or directory`)?

**Comment by hnyman** [comment]
It seems to be pretty clear that the buildhost environment has impact:

I checked from all platforms' "broken packages" directories the success of python-cryptography and then checked which buildslave had done that specific build (last successful build of a platform)

It seems to me that 
* buildslave2, foch and subsignal build successfully python-cryptography
* faraday, gb10, gb15 and wyrding fail to build  python-cryptography

That supports the idea that the python environment at the host has major impact.

And correspondingly, the target cross-compilation platfrom does not have that much impact:
ar71xx, ar71xx.nand and ar71xx.mikrotik share the code otherwise except the flash memory and/or wifi drivers etc. Still, in the last build run ar71xx and ar71xx.nand failed with python-cryptography, while ar71xx.mikrotik built python-cryptography.

I will merge the change. Let's see what happens.

**Comment by jefferyto** [comment]
Thanks @hnyman - I will keep my fingers crossed.

**Comment by hnyman** [comment]
Looks like the fix works. So far I have noticed no build failures at buildbot for any python package. (except for python-ldap for ar7, which is probably something platform-specific, as it builds ok for other platforms)

**Comment by jefferyto** [comment]
Great :smile: (looks like python-ldap is failing for brcm47xx as well though)

Also, python-cffi is failing to build for netlogic and octeon - I'll open a separate issue to track this.

**Pull request merged**
