### PR TITLE
Update Makefile style in cotequeiroz-maintained packages

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: me
Compile tested: mvebu, WRT3200ACM, openwrt master
Run tested: none

Description:
I'm updating the Makefiles in packages that I maintain to follow the style in current python packages.  Basically, I am:
- removing the copyright that I incorrectly assigned to openwrt
- adjusting titles so that they display correctly when running `make menuconfig`
- adding `PKG_LICENSE_FILES`
- correcting a copy&paste blunder in python-qrcode
- changing the order of variables to keep Makefile style consistent

I am not certain if this:
1. is best done in separate commits as I'm currently doing;
2. if that's commit pollution and so I should squash them; or 
3. if I should keep them in my private branch, and then update them here only when a more useful change occur.  

In the latter case, I will just do python-qrcode to fix the `PKG_BUILD_DIR` blunder.

Ping @commodo

### CODE REVIEW

**Comment by BKPepe** [comment]
Don't miss also @jefferyto for review. It's really good to move PKG_UNPACK under those two includes! :-) I would prefer to bump PKG_RELEASE, but it's up to you. As the changes will be applied only for new installations and when you bump PKG_VERSION or PKG_RELEASE next time.

**Comment by cotequeiroz** [comment]
@BKPepe I've increased `PKG_RELEASE` if the title changed, as that's part of the package metadata; if not, I left it put, as there's no change in package whatsoever.

**Comment by jefferyto** [comment]
@BKPepe I was hoping for a quiet break :joy:

**Comment by neheb** [comment]
Failing buildbot

**Comment by cotequeiroz** [comment]
I saw that, it was while downloading the SDK.  I was hoping to save some compilation effort, but I knew it would be somewhat uncomfortable.  Now, I've re-run the build and it passed.

**Pull request merged**
