### PR TITLE
【22.03】apfree-wifidog: update to 7.08.2035

### PR DESCRIPTION
**Pull request by liudf0716**
Maintainer: @liudf0716
Compile tested: x86_64
Run tested: x86_64

Description:
   
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.08.2035

Dengfeng Liu <liudf0716@gmail.com>

### CODE REVIEW

**Comment by BKPepe** [comment]
Why does this need to go to OpenWrt 22.03 branch? Despite the fact that I can not see any fixes related to security vulnerabilities, the OpenWrt 22.03 branch is End of Life.

**Comment by liudf0716** [comment]
> Why does this need to go to OpenWrt 22.03 branch? Despite the fact that I can not see any fixes related to security vulnerabilities, the OpenWrt 22.03 branch is End of Life.

Sorry I dont know 22.03 branch is End of life

**Comment by 1715173329** [comment]
At least it fixed a memory leak. It's fine as the maintainer is willing to do this.

**Comment by liudf0716** [comment]
@1715173329 Thank you for your understanding. I accept the community's decision to discontinue support for the end-of-life branch.

**Pull request closed without merging**
