### PR TITLE
yggdrasil: bump to 0.4.0

### PR DESCRIPTION
**Pull request by zhoreeq**
Maintainer: @wfleurant 
Compile tested: aarch64, Raspberry Pi 3B+, OpenWRT trunk
Run tested:  aarch64, Raspberry Pi 3B+, OpenWRT trunk

Description:

- Bump yggdrasil-go version to v0.4.0
- Update ygguci tool for compatibility with the new yggdrasil-go version
- Yggdrasil's config file is now generated in a separate command before running the daemon

### CODE REVIEW

**Comment by zhoreeq** [comment]
@wfleurant can you approve? Also there's luci update https://github.com/openwrt/luci/pull/5193

**Comment by wfleurant** [comment]
not today, i will try to sync with you next week.
this is essentially the planned network fork, and removal of tunnelled networking support.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rektide** [comment]
Resolves #16064

**Comment by BKPepe** [comment]
I think we should not accept email address users.noreply.github.com in the `Signed-off-by`. What do you think @neheb?

**Review by BKPepe — CHANGES_REQUESTED** [review]
PR title, commit subject says update to version 0.4.0, but the changes in the commit includes more than that. Split your one commit in two commits or describe in the commit description. That's up to you. Fix the e-mail address in the `Signed-off-by`.

**Comment by zhoreeq** [comment]
> PR title, commit subject says update to version 0.4.0, but the changes in the commit includes more than that. Split your one commit in two commits or describe in the commit description. That's up to you. Fix the e-mail address in the `Signed-off-by`.

Sure, I'll add a more verbose description. I always used this email for contributions to this repo, is there a new rule?

**Review by wfleurant — APPROVED** [review]

**Comment by wfleurant** [comment]
There is plenty of feedback to make this happen.  
Thanks for working on this @zhoreeq

**Comment by wulfy23** [comment]
does anyone test this on master?

ifname @ uci-defaults is legacy my friends...

**Comment by zhoreeq** [comment]
@wulfy23  I've tested it on master, it works fine. What should be used instead?

**Comment by wfleurant** [comment]
> does anyone test this on master?
> 
> ifname @ uci-defaults is legacy my friends...

Yes, it's it's in the yggdrasil uci-defaults file, called on install. thanks for pointing this out.

**Pull request merged**
