### PR TITLE
gkrellmd: Adopt from oldpackages repo, Update to 2.3.10

### PR DESCRIPTION
**Pull request by pnd10**
Adopt the package from the oldpackages repo at https://git.archive.openwrt.org/packages.git
Update to version 2.3.10 (released Nov 2016)
Update source URL
Depend only on GLib2, not glib1.2

Signed-off-by: Peter Denison <openwrt@marshadder.org>
Maintainer: Peter Denison <openwrt@marshadder.org>
Compile tested: mips_24kc, TL-WDR3600, snapshot-694f0bb5af
Run tested: mips_24kc, TL-WDR3600, snapshot-694f0bb5af, default config tested

Description:
Gkrellmd listens for connections from gkrellm clients. When a gkrellm client connects to a gkrellmd server, data from various system monitors are supplied to the client for display.

### CODE REVIEW

**Comment by pnd10** [comment]
In my local tree, the compile works - since i can't change the make invocation to use '-j1 V=s' on the CI server, I don't know how I can work out why it is failing for the CI build.

**Comment by champtar** [comment]
@pnd10 can you rebase on master, to try your commits with CircleCI

**Comment by pnd10** [comment]
@champtar Ah, yes. I had rebased onto master for the main repo, but not in packages. I will try that presently

**Comment by pnd10** [comment]
Hmmm. Now I don't understand - CircleCI build passed, TravisCI failed
I am going to need some help to fix this...

**Comment by champtar** [comment]
@pnd10 we have a lot of issue with Travis, that is why I'm trying to switch to CircleCI
don't worry about Travis

**Comment by pnd10** [comment]
Fair enough. Can this go in then now, since it passes the CircleCI check? It's pretty self-contained.

**Pull request merged**
