### PR TITLE
erlang: upgrade opt 22.3

### PR DESCRIPTION
**Pull request by peterwillcn**
Signed-off-by: Xiaobo Tian <peterwillcn@gmail.com>

Description: uprade erlang opt 22.3

### CODE REVIEW

**Comment by hnyman** [comment]
cc maintainer: @cretingame

**Comment by hnyman** [comment]
@peterwillcn 

A few comments:
* automatic testing fails:
```
=== Leaving application public_key
make[6]: Leaving directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/otp_src_22.3/lib/public_key'
make[6]: Entering directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/otp_src_22.3/lib/ssl'
=== Entering application ssl
make[7]: Entering directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/otp_src_22.3/lib/ssl/src'
make[7]: *** No rule to make target '../../../bootstrap/lib/kernel/include/logger.hrl', needed by '../ebin/dtls_connection.beam'.  Stop.
make[7]: Leaving directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/otp_src_22.3/lib/ssl/src'
/home/build/build_dir/build_dir/target-mips_24kc_musl/otp_src_22.3/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[6]: *** [opt] Error 2
make[6]: Leaving directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/otp_src_22.3/lib/ssl'
```
Is there any explanation for that?

If you want to add yourself as maintainer, the maintainer list should be comma separate list of mail addresses (for inclusion in mail tools), so please add a comma between.

**Comment by peterwillcn** [comment]
Give up 😢

**Comment by garazdawi** [comment]
This build error has been fixed for OTP-23 and it does not happen if you build from the git tag instead of using the downloadable archive from erlang.org.

**Pull request closed without merging**
