### PR TITLE
freeradius3: fixup

### PR DESCRIPTION
**Pull request by esaaprillia**
Maintainer:
Compile tested: 
Run tested: 

Description:

refresh patch

### CODE REVIEW

**Comment by esaaprillia** [comment]
@neheb

**Comment by BKPepe** [comment]
This is not fixup, when you are adding new packages.

**Comment by esaaprillia** [comment]
> This is not fixup, when you are adding new packages.

what commit message should I add?

https://github.com/openwrt/packages/pull/24617

**Comment by BKPepe** [comment]
@neheb This should not be merged. The commit subject is wrong, description is missing. This is not definitely fixup as it brings new subpackages, etc.

**Comment by esaaprillia** [comment]
@neheb 

can you please fix this problem by adding

```
ac_cv_header_readline_h=no
ac_cv_header_readline_readline_h=no
ac_cv_header_readline_history_h=no
```
same problem when i build freeradius4

**Pull request merged**
