### PR TITLE
podman: several improvements and add selinux variant

### PR DESCRIPTION
**Pull request by oskarirauta**
Maintainer: Daniel Golle / @dangowrt
Compile tested: x86_64, xeon powered server, OpenWRT snapshot (recent)
Run tested: x86_64, xeon powered server, OpenWRT snapshot (recent)

Description:

- Added selinux support as a variant
- Init script for socket
- Updated containers.conf
- preselected overlay as storage driver
- changed maintainer from Daniel to me as per request.
- Changes requested by Daniel Golle

Source code has remained same and no patches provided this time.
Replaces pull request #15310

Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

### CODE REVIEW

**Comment by dangowrt** [comment]
Please do not open a new PR instead of rebase and force-push in future. Apart from that, this looks very good, just add a bit more commit description (like I suggested in your previous PR).

**Comment by oskarirauta** [comment]
> Please do not open a new PR instead of rebase and force-push in future. Apart from that, this looks very good, just add a bit more commit description (like I suggested in your previous PR).

Now it should be exactly as requested..

**Comment by dangowrt** [comment]
Did you maybe forget to `git add` your changes in `storage.conf`? Because you mention that in the commit description but I can't see any changes there...

**Comment by oskarirauta** [comment]
It uses sed to replace when installing.I wanted to retain original source as is.

Lähetetty iPhonesta

**Comment by dangowrt** [comment]
> It uses sed to replace when installing.I wanted to retain original source as is.

Ah ok, I missed that. Absolutely ok, of course :)

**Review by dangowrt — APPROVED** [review]

**Pull request merged**
