### PR TITLE
frr: update to 7.5

### PR DESCRIPTION
**Pull request by neheb**
Remove upstream patches.

Refresh the other ones.

Use upstream tarball instead of codeload.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lucize 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
Note that the current version of frr has some problems with newer OSes: https://downloads.openwrt.org/snapshots/faillogs/aarch64_generic/packages/frr/host-compile.txt

This version works though.

**Comment by lucize** [comment]
I'm reluctant about this version because I can't start multiple ospf instances and need to bisect where the problem started
also I would like to use latest stable 7.5 git code based on date because of how the updates are released on stable versions (none)

**Comment by neheb** [comment]
Do you know which commit fixes the issue I linked to?

**Comment by lucize** [comment]
odd, python was a very old problem, I guess you could look in the history of configure.ac for something meaningful in the commit message

**Comment by neheb** [comment]
I can't see anything useful.

In any case, would be great if you could look. frr currently does not build on the buildbots.

**Comment by lucize** [comment]
I would like to use the latest 7.5 commit and revert the commits that fails to start ospf multiple instances, should I propose a new PR ? I addressed the commit upstream

**Comment by neheb** [comment]
Sure.

**Pull request closed without merging**
