### PR TITLE
unbound: fix local cnames

### PR DESCRIPTION
**Pull request by tobiaswaldvogel**
Maintainer: Eric Luehrsen <ericluehrsen@gmail.com>
Compile tested: rockchip, friendlyarm_nanopi-r4s, r26933+4-d40f9ad48f
Run tested: rockchip, friendlyarm_nanopi-r4s, r26933+4-d40f9ad48f, serveral cnames added in Luci and verified with dig that the cname and the a RR are returned

Description: For cnames with a local data target the A RR is not resolved and missing in the response. Most applications don't send another query and fail. E.g. navigation with Chrome to a local cname fails. This patch places these entries in a rpz zone instead. With this the cname is returned together with the correspnding A RR record, as expected.

### CODE REVIEW

**Comment by 1715173329** [comment]
cc @EricLuehrsen

**Comment by EricLuehrsen** [comment]
What is the goal here? Root issue behind CNAME is Unbound is a recursive search DNS server, not authoritative server. This may hack through this one issue. Something like NSD should be the authoritative server for a more complete solution. example unbound discussion: https://lists.nlnetlabs.nl/pipermail/unbound-users/2009-October/000901.html

**Review by EricLuehrsen — APPROVED** [review]
The RPZ feature is okay. It is as if Unbound made an XFR request to an authoritative server. It could cause Unbound to use more memory and CPU load. I guess we keep an eye out for complaints.

**Comment by tobiaswaldvogel** [comment]
Thanks for approving it.
I'm using several local CNAMEs with this now since several weeks and I also carefully observed the process statistics with luci-statistics without any issues so far. So I'm quite confident there won't be any. Anyway I'm also happy to jump in if any issues would show up.

**Pull request merged**
