### PR TITLE
libvpx: update to 1.5.0

### PR DESCRIPTION
**Pull request by luizluca**
Also inc gst1-plugins-good and toxcore release in order
to avoid package upgrade problems.

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

Is it ok @MikePetullo and @dangowrt?

### CODE REVIEW

**Comment by acinonyx** [comment]
I don't think you should increase the release number of all the packages that depend on a lib when you upgrade it.

**Comment by luizluca** [comment]
@acinonyx , I discussed this in the previous update https://github.com/openwrt/packages/pull/1119#issuecomment-89804502

According to @thess, dependent packages should have their release bumped. If this has changed, I can get rid of the bumps easily.

**Comment by mhei** [comment]
The release number on dependent packages should only change (increase), when the library update introduces ABI incompatibilities.

**Comment by acinonyx** [comment]
Ok, @luizluca. I've left a comment in [#1119](https://github.com/openwrt/packages/pull/1119#issuecomment-204693359)

**Comment by acinonyx** [comment]
@mhei there is the ABI_VERSION variable which will (supposedly) rebuild any dependencies when the version changes. Doesn't this work for you?

**Comment by luizluca** [comment]
@mhei , this version do breaks ABI (and API).

@acinonyx ABI_VERSION is new for me. However, it seems that it was introduced to avoid build breakage for fast changing packages. It avoids the need of a make clean. However, it is not considered by opkg.

If the release bump targets build problems only, ABI_VERSION seems to be enough. I'll wait the answer for your ABI_VERSION question.

**Comment by acinonyx** [comment]
@thess any comment?

**Comment by thess** [comment]
OK - I'll bite.

PKG_RELEASE usually needs to be updated is anytime the binary contents of that package changes - It is a new package.

Anytime a package changes in a manner that will cause another package to fail (install or behave badly) because of its changes, the dependent package should also be re-packaged for a new install/ugrade. The only way to insure this happens is to bump PKG_RELEASE in the dependent package. For example, in the previous update of libvpx, (https://github.com/openwrt/packages/pull/1119#issuecomment-89804502), the shareable lib name changed and the linked dependency would not execute without being rebuilt - hence the bump to PKG_RELEASE in the gst plugin. Perhaps this could have been avoided by creating a link to the new libvpx.so.

I don't know if ABI_VERSION can solve these package dependencies. Could you explain its usage?

**Comment by luizluca** [comment]
@thess , when a package change its ABI_VERSION, it forces the rebuild of those packages that requires it.

The good side is that a full build (but not clean) will be always consistent as gst1-plugins-good-1.6.2-1 will be rebuild and will be compatible with the new libvpx. The bad side is that any previously build gst1-plugins-good would still share the same version of the new gst1-plugins-good build but it will be binary different and incompatible with the new libvpx.

If a user asks to upgrade all packages and the _old_ gst1-plugins-good-1.6.2-1 was already installed, it will get a broken system. If the release is bumped instead, it will appear in a "opkg list-upgradable". It is user duty to check for upgrades.

For snapshots release, I guess it is not expected to have an "upgradable system" that will not break at some point. If so, maybe "opkg upgrade" should not be considered a problem and ABI_VERSION is enough.

For stable release, updates are only for bugfixes/security issues. They are already rare and an update in some dependent package that also break ABI will be even rarer. In this case, it would be necessary to bump every dependent package. ABI_VERSION, in this case, is not enough.

@thess, what would be needed for master branch? Keep "opkg upgrade" working or only avoid inconsistent builds?

BTW, I'll add ABI_VERSION anyway. I just need to know if I keep or remove the release changes.

**Comment by luizluca** [comment]
Just to ping again:

@thess, @MikePetullo and @dangowrt, do we have any decision on the matter?

**Comment by thess** [comment]
Fine with me - I find dependencies to be far from foolproof. At best they keep things from being totally wrong and builds working. At worst they are just hints.

**Comment by luizluca** [comment]
Thanks @thess and @dangowrt , I'll remove the extra release bumps and add ABI_VERSION.

**Pull request merged**
