### PR TITLE
radvd: import from old packages and update to version 1.15

### PR DESCRIPTION
**Pull request by qshenx**
- import from old packages
 - update radvd from version 1.9.1 to 1.15 to fix issue ticket #19948
     ( https://dev.openwrt.org/ticket/19948 )

Reopen a pull request without cups which @psycho-nico is already working. 
Origin: #1454

### CODE REVIEW

**Comment by champtar** [comment]
hi @qshenx,
Signed-off-by must contain your real name, same for PKG_MAINTAINER

also openwrt now use 6relayd, just curious what do you need in radvd?
http://wiki.openwrt.org/doc/uci/network6#router_advertisement_dhcpv61

**Comment by sbyx** [comment]
Well odhcpd is not really fine tunable so radvd might make sense for some. No objection there.

**Comment by champtar** [comment]
ping @qshenx 
please update your commit

**Comment by jow-** [comment]
Contributor went MIA

**Comment by wltjr** [comment]
I modified the Makefile it had some funky paths, /opt. But I have working version of the package. Not sure if we can get this back into tree or not. I can see about submitting a PR. I do prefer radvd and would like to see this package back in openwrt. I can see about maintaining it if need be.

**Comment by aparcar** [comment]
I'd like to use Mobile IPv6 and odhcpd doesn't seem to support it. If I update this package is there any chance for merging?

**Comment by wltjr** [comment]
@aparcar I need to update the [package in my repo](https://github.com/Obsidian-StudiosInc/openwrt-feed/tree/master/packages/radvd) it again but I still use this myself. I never got a response on adding this back into openwrt. I suspect for most they do not need the features of radvd.

**Comment by aparcar** [comment]
Well if you don't mind please add it!

**Comment by wltjr** [comment]
@aparcar lets file a new issue requesting such. I will go ahead and so such and reference this issue.

**Pull request closed without merging**
