### PR TITLE
java deps requirement

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: @danak6jq 
Compile tested: LEDE r2608
Run tested: LEDE armvirt, running Java helloworld.

Description:

Lacking proper dependency spec and host java support from buildbot machines, java related packages like classpath and rxtx are all failing to pass the configure stage [1,2]

This pr tries to add 2 things to address the issue

 - Provide virtual package `jvm` from `jamvm` and let others depend on it
 - Add `prereq` target for java libraries requiring working java compiler and java virtual machine

However, we still need buildbots' support of java to successfully build these java packages.  I am not sure how we are supposed to moving that forward.

The other thing is that it seems to me the current prereq check is done only when explicitly requested.  I am currently working on letting `configure` depend on `prereq` when building packages.  I guess this is going to introduce another minor split between OpenWrt/LEDE though...

 [1] http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/classpath/compile.txt
 [2] http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/rxtx/compile.txt

### CODE REVIEW

**Comment by danak6jq** [comment]
Thank you for pursuing LEDE build of the Java bits; my apologies for not originally creating the dependencies _from_ classpath and rxtx on jamvm; jamvm _does_ depend on classpath. I vaguely recall inheriting the package Makefiles from the old package repo and just tweaking them (and perpetuating typos/errors in them).

Thanks again and please let me know if I can help in any way. I haven't been doing LEDE builds but am willing to do so.

**Comment by yousong** [comment]
Hi, @danak6jq , please consider posting an email to lede-dev or openwrt-devel list for information about how to add host java support to the buildbots.  Otherwise, these packages will fail to ship out as opkg available packages.

**Comment by hauke** [comment]
Please send a mail to the lede-dev and the openwrt-dev mailing list before this patch gets merged. In general these patches are looking good. These checks are correct, but it could be that this wlll break the complete build bot and the build will not start before these requirements are fulfilled, which is currently not the case on many build bots.

**Comment by danak6jq** [comment]
I'll join the lede-dev list today and mail to both regarding buildbot requirements. Basically just need to install openjdk  - but I'll get to this today. Thank you again!

**Comment by champtar** [comment]
@yousong @danak6jq any news?

**Comment by yousong** [comment]
I am closing this for now as the issue has no prospect of to be fixed in the near future

**Pull request closed without merging**
