### PR TITLE
collectd: update to 5.9.0

### PR DESCRIPTION
**Pull request by hnyman**
Maintainer: me  and @jow- 

Update collectd to version 5.9.0

* remove backported upstream patches (sensors, modbus)
* remove lua patch that has been been implemented upstream
  (See collectd PR 3144) 
* refresh patches and accommodate into upstream path changes
* place the 'stations' datatype for iwinfo in alpbetically correct place in types.db
* add libmnl dependency to 'processes' plugin required for the new Linux process Delay Accounting capability. (Alternatively the capability & requirement might be patched away
   in Makefile.am, HAVE_LIBTASKSTATS from collectd_4ea7a572)
* new plugins (disabled): ampq1, gpu_nvidia, pcie_errors, write_stackdriver, write_syslog

compile-tested: ar71xx/WNDR3700 (all plugins)
run-tested: ar71xx/WNDR3700 (selected plugins)

### CODE REVIEW

**Comment by hnyman** [comment]
@feckert 
You might verify the lua changes. Based on your ack on collectd PR 3144 ( and actions in 3139), I think that your own patch here might now be unnecessary. Right?

> remove lua patch that has been been implemented upstream (See collectd PR 3144)


@dangowrt 
Heads up that I removed all your recent modbus patch backports that are included in the 3.9.0

**Comment by neheb** [comment]
This is failing on mosquitto

```
util_mosq.c:32:43: error: missing binary operator before token "("
 #  if defined(__GLIBC__) && __GLIBC_PREREQ(2, 25)
                                           ^
util_mosq.c: In function 'util__random_bytes':
util_mosq.c:328:43: error: missing binary operator before token "("
 #elif defined(__GLIBC__) && __GLIBC_PREREQ(2, 25)
                                           ^
Makefile:213: recipe for target 'util_mosq.o' failed
make[4]: *** [util_mosq.o] Error 1
make[4]: Leaving directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/mosquitto-nossl/mosquitto-1.6.2/lib'
Makefile:26: recipe for target 'mosquitto' failed
make[3]: *** [mosquitto] Error 2
make[3]: Leaving directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/mosquitto-nossl/mosquitto-1.6.2'
Makefile:237: recipe for target '/home/build/build_dir/build_dir/target-mips_24kc_musl/mosquitto-nossl/mosquitto-1.6.2/.built' failed
make[2]: *** [/home/build/build_dir/build_dir/target-mips_24kc_musl/mosquitto-nossl/mosquitto-1.6.2/.built] Error 2
make[2]: Leaving directory '/home/build/openwrt_packages/net/mosquitto'
```

ping @karlp

**Comment by hnyman** [comment]
@neheb  @karlp 

Seems unrelated to collectd.

> This is failing on mosquitto

You mean, on mosquitto when glibc is used?
Luckily it does not hurt the normal musl usage...

References in mosquitto: 
https://github.com/eclipse/mosquitto/issues/1242 
https://github.com/eclipse/mosquitto/issues/1291 and 
https://github.com/eclipse/mosquitto/commit/d05bd958813b7ead344f66653ce9b13b00e67595

Original cause: 
https://github.com/eclipse/mosquitto/commit/1a3eaeabcee8a44ec6692e1a2977d48654332783#diff-1839d1965d6ea596aff4fbbf7599d29a

**Comment by neheb** [comment]
Seems to be on musl: http://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/packages/mosquitto/nossl/compile.txt

**Comment by dengqf6** [comment]
Works fine for me

**Comment by feckert** [comment]
Sorry for the delay was on vacation.
@hnyman From my side LGTM

**Pull request merged**
