### PR TITLE
scapy: update to 2.4.2 and make use of Python 3

### PR DESCRIPTION
**Pull request by MikePetullo**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64
Run tested: x86_64

Description:

### CODE REVIEW

**Comment by neheb** [comment]
There's been discussion on deprecating python 2 as it is EOL at the end of the year. It's not mandatory yet but if possible, might as well be done early.

**Comment by diizzyy** [comment]
This should indeed be migrated to python3

**Comment by MikePetullo** [comment]
@neheb, I migrated the package to Python 3 and force pushed here.

**Comment by MikePetullo** [comment]
@jefferyto, I fixed the Makefile to refer to PYTHON3_PKG_DIR. Thank you!

**Pull request merged**
