### PR TITLE
libcoap: Pass endian flags down to target

### PR DESCRIPTION
**Pull request by karlp**
Fixes github issue #1856

Signed-off-by: Karl Palsson <karlp@tweak.net.au>

(NOTE! this is untested!

### CODE REVIEW

**Comment by sbyx** [comment]
@toxxin please review

**Comment by toxxin** [comment]
That's perfect! Thank you @karlp for patch! Unfortunately I can't test it right now. Only x86 arch(

**Comment by yousong** [comment]
Hi, I found accidentally in libcoap-4.1.1 from sf.net that there is a `AC_C_BIGENDIAN` there in `configure.in` which is missing in the github version (https://github.com/obgm/libcoap/blob/develop/configure.ac).  Maybe that should be the root cause?

**Comment by karlp** [comment]
@yousong are you tracking that upstream?

**Comment by yousong** [comment]
Hi @karlp , I am not tracking this libcoap upstream project.  It's just that I am watching this libcoap package since a previous thread about it in openwrt-devel list (https://lists.openwrt.org/pipermail/openwrt-devel/2015-August/034908.html).

Hi @toxxin , since you are the package maintainer and quite likely a user of this package, you may want to sync a patch you deem proper to that upstream project.

**Comment by toxxin** [comment]
Hi @yousong! Sure! I'm sorry for the delay! Just sent pull request to upstream. I'll update openwrt package as soon as they fix this bug.

**Pull request merged**
