### PR TITLE
ooniprobe: Update to 3.16.5

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: @ja-pa 
Compile tested: CI (immortalwrt/packages#527)
Run tested: CI (immortalwrt/packages#527)

Description:
Fix build with Go 1.19. #19652

### CODE REVIEW

**Comment by BKPepe** [comment]
From my point of view, having something tested inside CI is just additional or, let's say, something nice to have, but that still can not replace the indication of run testing this on real device. The ``test.sh`` just ensures you that your application does not segfault immediately once issuing ``--help/--version``, but that does not mean that it works with the old setup.

**Comment by 1715173329** [comment]
I don't use this package, so can't do a real test and also don't know how to do it. This PR just makes it compile.

Ping @ValdikSS would you mind testing it?

**Comment by ValdikSS** [comment]
> Ping @ValdikSS would you mind testing it?

Sorry, I don't have access to my laptop in this and next week. Try to run it. If it runs, then it is probably fine.

**Comment by 1715173329** [comment]
> Sorry, I don't have access to my laptop in this and next week. Try to run it. If it runs, then it is probably fine.

No problem, thank you!

**Comment by 1715173329** [comment]
emmmm... it does run... but looks like in this package there're lots of unrelated stuffs, even includes sample binaries... are they really necessary?
https://github.com/ooni/probe-cli/tree/master/internal/tutorial/measurex

**Pull request merged**
