### PR TITLE
libsearpc: Update to 3.1.0

### PR DESCRIPTION
**Pull request by neheb**
Switch to codeload for simplicity. Rearranged Makefile a bit for consistency between Makefiles.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @kissg1988 
Compile tested: mvebu

### CODE REVIEW

**Comment by kissg1988** [comment]
@neheb I'm not sure if it's safe to update the version here. As per Seafile build documentation, the tag "v3.0-latest" should be used:

https://manual.seafile.com/build_seafile/linux.html

Also, please make sure to update the deps in https://github.com/openwrt/packages/blob/448051b95fb5acb2eb181c4d7eeeec11cb8fc9f7/net/seafile-ccnet/Makefile#L37 in case the version string is changed to avoid dependency issues upon installing the packages related to Seafile.

Note that the build documentation says that Seafile no longer depends on ccnet from version 6.2 and up. It's not actually an issue to keep the dependency but it might worth removing the dependency on seafile-ccnet 
https://github.com/openwrt/packages/blob/448051b95fb5acb2eb181c4d7eeeec11cb8fc9f7/net/seafile-server/Makefile#L37 and adding libsearpc, instead.

Unfortunately, I have no Linux machine around to work on this and test the changes so your help would be much appreciated on this.

**Comment by neheb** [comment]
Sounds bogus TBH. The version was probably the latest when the documentation was written.

I will do a few tests to see any negative impact.

**Comment by neheb** [comment]
@kissg1988 I tested this. seafile-ccnet still works.

Arch Linux uses 3.1.0 and 6.3.4 for libsearpc and seafile-server respectively and it seems to work there as well. I'll work on updating later.

**Comment by hnyman** [comment]
Good to merge?

**Comment by kissg1988** [comment]
@neheb I believe it's safe to update, then.
@hnyman Yes, please do so. Thank you!

**Pull request merged**
