### PR TITLE
frr: drop elfutils/host dependency

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: @lucize 
Compile tested: NA
Run tested: NA

### CODE REVIEW

**Comment by stintel** [comment]
@jefferyto  7b7265293f953c71a65099ecbdbfbaf5f14bf4f8 seems to break things?

**Comment by jefferyto** [comment]
Yes 😅

**Comment by lucize** [comment]
on my build system debian 10, I'm unable to build anything that needs elfutils, so atm can't say anything about this.
elfutils is not installed by atp on the system

**Comment by lucize** [comment]
with latest elfutils this works

tested x86

**Pull request merged**
