### PR TITLE
zerotier: fix typo

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: adam-qomodo

Maintainer: me

Description: Fixes a typo in a message

### CODE REVIEW

**Comment by mwarning** [comment]
@adam-qomodo fyi

**Comment by BKPepe** [comment]
> Signed-off-by: adam-qomodo

I don't think this is correct. 

Even though, this still requires to bump ``PKG_RELEASE``.

**Comment by BKPepe** [comment]
Still my comment applies.

**Comment by mwarning** [comment]
@BKPepe I guess now it is fine

**Comment by 1715173329** [comment]
Please bump `PKG_RELEASE` in `net/zerotier/Makefile` to 2.

**Comment by mwarning** [comment]
@1715173329 thanks for the heads up. I forgot to add that file and did not notice. :)

**Pull request merged**
