### PR TITLE
ipfs-http-client: add missing libatomic dependency

### PR DESCRIPTION
**Pull request by neheb**
Small change to pass OpenWrt CXXFLAGS to the Makefile.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @LLE8 
Compile tested: arc770

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/ipfs-http-client/compile.txt

### CODE REVIEW

**Comment by neheb** [comment]
Changed standard to C++14 as it results in a slightly smaller size.

Disabled parallel building as it completely breaks.

**Comment by neheb** [comment]
When I converted this to use cmake size went down from 62206 to 54337 bytes

**Comment by neheb** [comment]
```
diff --git a/libs/ipfs-http-client/Makefile b/libs/ipfs-http-client/Makefile
index 07d996166..c4d313f54 100644
--- a/libs/ipfs-http-client/Makefile
+++ b/libs/ipfs-http-client/Makefile
@@ -17,10 +17,11 @@ PKG_SOURCE_DATE:=2019-11-05
 PKG_SOURCE_VERSION:=763e59ad698f3e3846f85df11e01c18ef3fbc401
 PKG_MIRROR_HASH:=a2b5721faf0d43ddb4a892245ef382666149c83f3f97e558e1a6acf2402fb9fd
 
-PKG_BUILD_PARALLEL:=0
+PKG_BUILD_PARALLEL:=1
 PKG_BUILD_DEPENDS:=nlohmannjson
 
 include $(INCLUDE_DIR)/package.mk
+include $(INCLUDE_DIR)/cmake.mk
 
 define Package/ipfs-http-client/Default/description
   IPFS (the InterPlanetary File System) is the Distributed Web.
@@ -54,12 +55,8 @@ define Package/ipfs-http-client-tests/description
   This package contains library tests.
 endef
 
-define Build/InstallDev
-	$(INSTALL_DIR) $(1)/usr/include
-	$(INSTALL_DIR) $(1)/usr/lib
-	$(CP) $(PKG_BUILD_DIR)/include/* $(1)/usr/include
-	$(CP) $(PKG_BUILD_DIR)/libipfs-http-client.a $(1)/usr/lib
-endef
+CMAKE_OPTIONS += \
+	-DBUILD_SHARED_LIBS=ON
 
 define Package/libipfs-http-client/install
 	$(INSTALL_DIR) $(1)/usr/lib
```

**Comment by LLE8** [comment]
> When I converted this to use cmake size went down from 62206 to 54337 bytes

Why?

**Comment by neheb** [comment]
No idea. Maybe the Makefile does overzealous linking. Maybe it’s not passing CFLAGS properly.

**Comment by LLE8** [comment]
Debian Buster, gcc version 8.3.0
Fragments of cmake-generated builfiles:
CMakeFiles/ipfs-http-client.dir/build.make
```
/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/ipfs-http-client.dir/src/client.cc.o -c /home/user1/cpp-ipfs-http-client/src/client.cc
/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/ipfs-http-client.dir/src/http/transport-curl.cc.o -c /home/user1/cpp-ipfs-http-client/src/http/transport-curl.cc
```
CMakeFiles/ipfs-http-client.dir/flags.make
```
CXX_FLAGS =  -Wall -Wpedantic -Wextra -Werror -fPIC   -std=gnu++11
CXX_DEFINES = -Dipfs_http_client_EXPORTS
CXX_INCLUDES = -I/usr/include/x86_64-linux-gnu -I/home/user1/cpp-ipfs-http-client/include
```
CMakeFiles/ipfs-http-client.dir/link.txt
```
/usr/bin/c++ -fPIC  -Wall -Wpedantic -Wextra -Werror  -shared -Wl,-soname,libipfs-http-client.so.0 -o libipfs-http-client.so.0.4.0 CMakeFiles/ipfs-http-client.dir/src/client.cc.o CMakeFiles/ipfs-http-client.dir/src/http/transport-curl.cc.o -lcurl
```

**Comment by neheb** [comment]
AFAIK CMake overwrites the Makefile. So it’s a moot point.

You’re also comparing a host build with a target build.

**Comment by LLE8** [comment]
Yes, cmake creates its own complex Makefile, which includes many attached files in separate directories for each target (build.make, flags.make, link.txt, ......). They are difficult to read.

**Comment by neheb** [comment]
locally: 

```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_archs_gcc-9.2.0_uClibc/bin/arc-openwrt-linux-uclibc-g++
CXX_FLAGS = -Os -pipe -matomic -mcpu=archs -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/mangix/devstuff/openwrt/build_dir/target-arc_archs_uClibc/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wall -Wpedantic -Wextra -Werror -DNDEBUG -fPIC   -std=gnu++11

CXX_DEFINES = -Dipfs_http_client_EXPORTS

CXX_INCLUDES = -I/home/mangix/devstuff/openwrt/build_dir/target-arc_archs_uClibc/ipfs-http-client-2019-11-05-763e59ad/include 
```

```
/home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_archs_gcc-9.2.0_uClibc/bin/arc-openwrt-linux-uclibc-g++ -fPIC -Os -pipe -matomic -mcpu=archs -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/mangix/devstuff/openwrt/build_dir/target-arc_archs_uClibc/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wall -Wpedantic -Wextra -Werror -DNDEBUG -L/home/mangix/devstuff/openwrt/staging_dir/target-arc_archs_uClibc/usr/lib -L/home/mangix/devstuff/openwrt/staging_dir/target-arc_archs_uClibc/lib -L/home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_archs_gcc-9.2.0_uClibc/usr/lib -L/home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_archs_gcc-9.2.0_uClibc/lib -znow -zrelro -Wl,-Bsymbolic-functions -shared -Wl,-soname,libipfs-http-client.so.0 -o libipfs-http-client.so.0.4.0 CMakeFiles/ipfs-http-client.dir/src/client.cc.o CMakeFiles/ipfs-http-client.dir/src/http/transport-curl.cc.o  -lcurl 
```

Anyway, why do you insist on your own Makefile which also does not support parallel compilation?

**Comment by LLE8** [comment]
I am not sure about libatomic dependency.
Openwrt current, TL-MR3020 v3
`make clean`
`make --jobs 8`
At next step packages libipfs-http-client and ipfs-http-client-tests were selected, but libatomic was not selected.
```
user1@black2:~/openwrt_current$ egrep -i -E "atom|ipfs" .config
# CONFIG_PACKAGE_libatomic is not set
CONFIG_PACKAGE_libipfs-http-client=m
CONFIG_PACKAGE_ipfs-http-client-tests=m
```
` make package/ipfs-http-client/compile V=s`
Fragmet of console output:
```
Applying ./patches/001-add-srv-addr.patch using plaintext:
patching file test/block.cc
patching file test/config.cc
patching file test/dht.cc
patching file test/error.cc
patching file test/files.cc
patching file test/generic.cc
patching file test/key.cc
patching file test/name.cc
patching file test/object.cc
patching file test/pin.cc
patching file test/swarm.cc
touch /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.prepared_e23f993f01b3d0b5a64777f336616bf0_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.configured_*
rm -f /home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/stamp/.ipfs-http-client_installed
(cd /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/./; if [ -x ./configure ]; then find /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/ -name config.guess | xargs -r chmod u+w; find /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/ -name config.guess | xargs -r -n1 cp --remove-destination /home/user1/openwrt_current/scripts/config.guess; find /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/ -name config.sub | xargs -r chmod u+w; find /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/ -name config.sub | xargs -r -n1 cp --remove-destination /home/user1/openwrt_current/scripts/config.sub; AR="mipsel-openwrt-linux-musl-gcc-ar" AS="mipsel-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -ffile-prefix-map=/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mipsel-openwrt-linux-musl-ld NM="mipsel-openwrt-linux-musl-gcc-nm" CC="mipsel-openwrt-linux-musl-gcc" GCC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" RANLIB="mipsel-openwrt-linux-musl-gcc-ranlib" STRIP=mipsel-openwrt-linux-musl-strip OBJCOPY=mipsel-openwrt-linux-musl-objcopy OBJDUMP=mipsel-openwrt-linux-musl-objdump SIZE=mipsel-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/usr/include -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/usr/include -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/include/fortify -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/include " LDFLAGS="-L/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/usr/lib -L/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/lib -L/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/usr/lib -L/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/lib -znow -zrelro "   ./configure --target=mipsel-openwrt-linux --host=mipsel-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.built
touch /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.built_check
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/usr/include -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/usr/include -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/include/fortify -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/usr/include -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/usr/include -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/include/fortify -I/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/include " LDFLAGS="-L/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/usr/lib -L/home/user1/openwrt_current/staging_dir/target-mipsel_24kc_musl/lib -L/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/usr/lib -L/home/user1/openwrt_current/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/lib -znow -zrelro " make -j1 -C /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/. AR="mipsel-openwrt-linux-musl-gcc-ar" AS="mipsel-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -ffile-prefix-map=/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad=ipfs-http-client-2019-11-05-763e59ad -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mipsel-openwrt-linux-musl-ld NM="mipsel-openwrt-linux-musl-gcc-nm" CC="mipsel-openwrt-linux-musl-gcc" GCC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" RANLIB="mipsel-openwrt-linux-musl-gcc-ranlib" STRIP=mipsel-openwrt-linux-musl-strip OBJCOPY=mipsel-openwrt-linux-musl-objcopy OBJDUMP=mipsel-openwrt-linux-musl-objdump SIZE=mipsel-openwrt-linux-musl-size CROSS="mipsel-openwrt-linux-musl-" ARCH="mipsel" ;
make[3]: Entering directory '/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad'
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include -fPIC -o src/client.o -c src/client.cc
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include -fPIC -o src/http/transport-curl.o -c src/http/transport-curl.cc
mipsel-openwrt-linux-musl-gcc-ar rc libipfs-http-client.a src/client.o src/http/transport-curl.o
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include -shared -Wl,-soname,libipfs-http-client.so.0 -o libipfs-http-client.so.0.4.0 src/client.o src/http/transport-curl.o
ln -sf libipfs-http-client.so.0.4.0 libipfs-http-client.so.0
ln -sf libipfs-http-client.so.0 libipfs-http-client.so
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/block.cc -L. -lipfs-http-client -lcurl -o test/ipfs-block
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/dht.cc -L. -lipfs-http-client -lcurl -o test/ipfs-dht
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/files.cc -L. -lipfs-http-client -lcurl -o test/ipfs-files
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/key.cc -L. -lipfs-http-client -lcurl -o test/ipfs-key
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/object.cc -L. -lipfs-http-client -lcurl -o test/ipfs-object
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/swarm.cc -L. -lipfs-http-client -lcurl -o test/ipfs-swarm
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/config.cc -L. -lipfs-http-client -lcurl -o test/ipfs-config
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/generic.cc -L. -lipfs-http-client -lcurl -o test/ipfs-generic
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/name.cc -L. -lipfs-http-client -lcurl -o test/ipfs-name
mipsel-openwrt-linux-musl-g++ -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include test/pin.cc -L. -lipfs-http-client -lcurl -o test/ipfs-pin
mipsel-openwrt-linux-musl-g++ -std=c++11 -I./include -L. test/demo.cpp -lipfs-http-client -lcurl -o test/ipfs-demo
make[3]: Leaving directory '/home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad'
touch /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.built
rm -rf /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.pkgdir/libipfs-http-client.installed /home/user1/openwrt_current/build_dir/target-mipsel_24kc_musl/ipfs-http-client-2019-11-05-763e59ad/.pkgdir/libipfs-http-client
```

```
user1@black2:~/openwrt_current$ ls -l bin/packages/mipsel_24kc/packages/
total 308
-rw-r--r-- 1 user1 user1 230449 Feb  4 15:57 ipfs-http-client-tests_2019-11-05-763e59ad-1_mipsel_24kc.ipk
-rw-r--r-- 1 user1 user1  64741 Feb  4 15:57 libipfs-http-client_2019-11-05-763e59ad-1_mipsel_24kc.ipk
-rw-r--r-- 1 user1 user1   1171 Feb  4 16:02 Packages
-rw-r--r-- 1 user1 user1    499 Feb  4 16:02 Packages.gz
-rw-r--r-- 1 user1 user1   1480 Feb  4 16:02 Packages.manifest
-rw-r--r-- 1 user1 user1    150 Feb  4 16:02 Packages.sig
```

**Comment by LLE8** [comment]
To fix parallel building try 
in srcMakefile
change 
`$(addprefix test/,$(TESTPROGS)):test/ipfs-%:test/%.cc   include/ipfs/client.h include/ipfs/test/utils.h  libipfs-http-client.a`
to
`$(addprefix test/,$(TESTPROGS)):test/ipfs-%:test/%.cc   include/ipfs/client.h include/ipfs/test/utils.h  lib`
and change
`test/ipfs-demo: test/demo.cpp`
to
'test/ipfs-demo: test/demo.cpp lib`

**Comment by LLE8** [comment]
My TP-Link TL-MR3020 v3
```
user1@black2:~/openwrt_current$ grep atom .config
# CONFIG_PACKAGE_libatomic is not set
user1@black2:~/openwrt_current$ find ./build_dir/target-mipsel_24kc_musl/ -name "libatomic*"
./build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc/lib/libatomic.a
user1@black2:~/openwrt_current$ find ./staging_dir/target-mipsel_24kc_musl/  -name "libatomic*"
./staging_dir/target-mipsel_24kc_musl/root-ramips/lib/libatomic.a
```

**Comment by neheb** [comment]
libatomic is not needed with all platforms.

**Comment by neheb** [comment]
Updated this. Removed the NIH Makefile. Fixing this requires conditional linking to libatomic.

**Comment by LLE8** [comment]
As I could understand, for my target TL-MR3020 libatomic is a part of toolchain 
```
user1@black2:~/openwrt_current$ file ./staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/lib/libatomic.so.1.2.0    ./staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/lib/libatomic.so.1.2.0: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, not stripped
user1@black2:~/openwrt_current$ file ./build_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/gcc-8.3.0-final/mipsel-openwrt-linux-musl/libatomic/.libs/libatomic.so.1.2.0
./build_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/gcc-8.3.0-final/mipsel-openwrt-linux-musl/libatomic/.libs/libatomic.so.1.2.0: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, not stripped
```
What about your target?

**Comment by LLE8** [comment]
What about BUILDONLY:=1 in nlohmannjson package? Will it be documented? Or is it not really supported?

My NIH Makefile works with explicit PKG_BUILD_PARALLEL:=1 with two simple small fixes, but i don't insist on my own Makefile:
```
user1@black2:~/openwrt_current$ cat  feeds/packages/libs/ipfs-http-client/src/Makefile
#
# IPFS C++ HTTP API client library
#
VER_MAJOR:=0
VER_MINOR:=4
VER_PATCH:=0
VERSION:=$(VER_MAJOR).$(VER_MINOR).$(VER_PATCH)

HEADERS := include/ipfs/client.h include/ipfs/http/transport-curl.h include/ipfs/http/transport.h
TESTPROGS := ipfs-block ipfs-dht ipfs-files ipfs-key ipfs-object ipfs-swarm ipfs-config ipfs-generic ipfs-name ipfs-pin
CXXFLAGS := -Wall -Wpedantic -Wextra -Werror -Os -std=gnu++11 -I./include

.PHONY: testprogs lib all clean

all: lib testprogs test/ipfs-demo

lib: libipfs-http-client.a libipfs-http-client.so.$(VERSION)

libipfs-http-client.a: src/client.o src/http/transport-curl.o
        $(AR) rc libipfs-http-client.a src/client.o src/http/transport-curl.o

libipfs-http-client.so.$(VERSION): src/client.o src/http/transport-curl.o
        $(CXX) $(CXXFLAGS) -shared -Wl,-soname,libipfs-http-client.so.$(VER_MAJOR) -o libipfs-http-client.so.$(VERSION) src/client.o src/http/transport-curl.o
        ln -sf libipfs-http-client.so.$(VERSION) libipfs-http-client.so.$(VER_MAJOR)
        ln -sf libipfs-http-client.so.$(VER_MAJOR) libipfs-http-client.so

testprogs: $(addprefix test/,$(TESTPROGS))

# _bugfix_next_line_ $(addprefix test/,$(TESTPROGS)):test/ipfs-%:test/%.cc   include/ipfs/client.h include/ipfs/test/utils.h  libipfs-http-client.a
$(addprefix test/,$(TESTPROGS)):test/ipfs-%:test/%.cc   include/ipfs/client.h include/ipfs/test/utils.h  lib
        $(CXX) $(CXXFLAGS) $< -L. -lipfs-http-client -lcurl -o $@

src/client.o: src/client.cc $(HEADERS)
        $(CXX) $(CXXFLAGS) -fPIC -o src/client.o -c src/client.cc

src/http/transport-curl.o: src/http/transport-curl.cc $(HEADERS) include/ipfs/test/utils.h
        $(CXX) $(CXXFLAGS) -fPIC -o src/http/transport-curl.o -c src/http/transport-curl.cc

# _bugfix_next_line_ test/ipfs-demo: test/demo.cpp
test/ipfs-demo: test/demo.cpp lib
        $(CXX) -std=c++11 -I./include -L. test/demo.cpp -lipfs-http-client -lcurl -o test/ipfs-demo
#       $(CXX) -std=c++11 -I./include -L. -Wl,-rpath,. test/demo.cpp  -lipfs-http-client -lcurl -o test/ipfs-demo
#       $(CXX) -std=c++11 -I./include test/demo.cpp ./libipfs-http-client.a -lcurl -o test/ipfs-demo

clean:
        $(RM) src/client.o src/http/transport-curl.o libipfs-http-client.a libipfs-http-client.so* $(addprefix test/,$(TESTPROGS)) test/ipfs-demo
```

**Comment by LLE8** [comment]
For target TL-MR3020 v3 package builds normally with cmake and unconditionally added +libatomic dependaency.
`  DEPENDS:= +libcurl +libstdcpp +libatomic`

**Pull request merged**
