### PR TITLE
python packages: upgrade to newer versions

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/0317fc3658eb55596c72647f2e6c68bf06bf36ff x86
Run tested: https://github.com/openwrt/openwrt/commit/0317fc3658eb55596c72647f2e6c68bf06bf36ff x86

Description:

This commit series updates a series of packages I maintain or co-maintain.
Run-tested on x86 VM.

The more important change in this small series is ` python-cryptography: bump to version 2.3.1 ` which came via request #6967 

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
Personally, I like the pypi.io URLs because they're short and elegant.
But sure.

**Comment by commodo** [comment]
Changelog v1 -> v2:
* changed URLs to `files.pythonhosted.org `

**Comment by neheb** [comment]
@commodo there's a stray tarball in the root directory.

**Comment by commodo** [comment]
I recommend adding my name on a list next to the computer; the list title should be 
```
Don't trust these guys when reviewing: 
1. commodo - Alexandru Ardelean
```

At least I know I would number one at something :)

**Pull request merged**
