### PR TITLE
Fix acme-challenge ./well-known check / webroot detection

### PR DESCRIPTION
**Pull request by nos1609**
fixes webroot to be defined as 
_currentRoot='/www'
instead of being interpreted as
_currentRoot='"/www"'

 ( ipq806x, EA8500, LEDE Reboot (SNAPSHOT, r4099-4c3953b)
luci-app-acme - 1.6-1
acme - 1.6-1)

### CODE REVIEW

**Comment by hnyman** [comment]
cc to maintainer:  @tohojo

**Comment by tohojo** [comment]
Ah, good catch. Could you include a package revision bump in the commit, please?

**Comment by hnyman** [comment]
Tohojo meant that you should also increase the package's version in Makefile. As the fetched acme source remains same, you should increase PKG_RELEASE from 1 to 2.

**Comment by nos1609** [comment]
@hnyman @tohojo fixed

**Comment by tohojo** [comment]
Yup, that's better, thanks. Your commits lack a signed-off-by tag, though. See https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork

Please add that, and while you're add it, I'd prefer if you squashed the two commits into one.

**Comment by nos1609** [comment]
@tohojo sorry, but I'm not a power git user, and I can't find the functionnality on the github website.

**Comment by tohojo** [comment]
Not sure you can do it on github. Basically, on the command line you would do:

```
git reset HEAD^
git commit -a --amend
# (edit commit message to add Signed-off-by tag)
git push --force
```

**Comment by hnyman** [comment]
Editing files via Github GUI does not allow squashing etc.

Basically the easy path is to abandon this PR and create a new branch, new commit (with proper sign-off) and a new PR.

**Comment by tohojo** [comment]
Huh, you can edit files via the github GUI now? TIL. :)

**Comment by nos1609** [comment]
@tohojo I thought github was meant for that, to leverage beginners, not only for hosting purposes...
I'm not a coder, so sometimes I try helping others with things I am using myself. I use acme as I am using Let's Encrypt since its beta stage on my website and quite used to with the set up procedure. But I'm not so handy with GIT itself. I'am more a GUI-man ;)
@hnyman sorry if I did it wrong, gonna create issues next time

**Comment by tohojo** [comment]
Well, it makes sense. Just a somewhat new feature. That, or I've been living under a rock; but I prefer the first explanation ;)

As for squashing your commits, I can do that on merge. But the signed-off-by line is needed; I think it's fine if you add it here in a comment; then I'll copy it to the commit message...

**Comment by hnyman** [comment]
> Just a somewhat new feature. 

Actually, it has been around several years, but we "normal" git powerusers ignore it as it is not that obvious to edit files directly in Github GUI...

The functionality "pen icon" is available for any file in the file view:
editfile

**Comment by tohojo** [comment]
Hannu Nyman <notifications@github.com> writes:

>  Just a somewhat new feature.
>
> Actually, it has been around several years, but we "normal" git
> powerusers ignore it as it is not that obvious to edit files directly
> in Github GUI...

Huh, guess I have been living under a rock, then. Damn :P

> The functionality "pen icon" is available for any file in the file
> view:

Yeah, found that now that I knew to look for it :)

-Toke

**Comment by tohojo** [comment]
Cool, thanks :)

**Pull request merged**
