### PR TITLE
[23.05]sane-backends: update to 1.3.1

### PR DESCRIPTION
**Pull request by Saxon-Sun**

### CODE REVIEW

**Comment by 1715173329** [comment]
so is it run tested? cc maintainer @luizluca

**Comment by luizluca** [comment]
> so is it run tested? cc maintainer @luizluca 

It seems to be the backport from main/master into 23.05. Normally we don't expect major updates in the stable branch. Is there anything missing/broken that motivated this PR?

I am still the maintainer but I'm looking for a new maintainer or, at least, comaintainer/tester as I don't have a scanner to test it anymore. Did you tested it in real hw? It is also important for the main/master commit.

**Comment by Saxon-Sun** [comment]
I will be testing it in the coming weeks to see if there are any issues with the scanner.    @1715173329 @luizluca

**Comment by 1715173329** [comment]
> It seems to be the backport from main/master into 23.05. Normally we don't expect major updates in the stable branch.

I'm not against it personally as this package is not widely dependend, if users have a _fair_ reason.

Anyway you are the maintainer and it's up to you ;)

**Comment by BKPepe** [comment]
I agree with @luizluca . Closing.

**Pull request closed without merging**
