### PR TITLE
Cleanup: avoid reuse of $(PKG_NAME)

### PR DESCRIPTION
**Pull request by stintel**
For consistency, use full name instead of $(PKG_NAME) in define and eval lines for all packages.
I've seen reviews that asked to do this before, and I am asking the same during reviews now. To avoid this in the future, fix this treewide so when people use existing packages as example, we will not have to request this change anymore.

This makes all packages consistent with both LEDE and OpenWrt base repositories (check with ``git grep PKG_NAME| egrep -i 'define|call|eval'``).

There is one exception for PHP pecl packages, where ``PKG_NAME:=php7-pecl-$(PECL_NAME)``. Do we want to change these, too?

### CODE REVIEW

**Comment by karlp** [comment]
I've got no objections as long as you add this rule to the documentation for both https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md and https://wiki.openwrt.org/doc/devel/packages

**Comment by stintel** [comment]
@karlp done

**Comment by dibdot** [comment]
@stintel maybe it would be a good idea to cc: the package maintainers?

To be honest, I do not fully understand the motivation for this change. 
Readability? Not really in my opinion ... it's much easier to check the package name in the header of the makefile and re-use it afterwards than to check the writing n times within the same makefile.
What about "PKG_SOURCE"? Why we still re-use "PKG_NAME" at this place?

Anyway, not really important issues, so feel free to proceed if this is useful.

**Comment by stintel** [comment]
Mostly for consistency really. It doesn't make sense we have defines/evals/.. with $(PKG_NAME) in tree, but request to change PRs when they copy the behaviour. It's confusing to contributors. The examples in the wiki don't use $(PKG_NAME) and not a single package in both the OpenWrt and LEDE tree do it either.

We should always aim for consistency, and this commit will hopefully avoid people copying it in new packages, which in turn should result in less changes requested. So less work for both reviewers and contributors.

**Comment by stintel** [comment]
PKG_* being the exception, as it is used like that in include/*.

**Comment by thess** [comment]
+1 from me (FWIW)

**Comment by jow-** [comment]
LGTM

**Comment by yousong** [comment]
+1

**Pull request merged**
