### PR TITLE
sshtunnel: Add support for "ProxyCommand" [v5] 

### PR DESCRIPTION
**Pull request by stokito**
Maintainer: @nunojpg
Compile tested: master, VirtualBox 
Run tested: master, VirtualBox, TurrisOS. Both OpenSSH and Dropbear

Description:
The PR replaces #20163.

It turned out that instead of generation of a temp file we can use `procd_append_param command -o "ProxyCommand=$ProxyCommand"` that will make a trick with quoting.

The replacing of placeholders `%h` and `%p` is not needed because it's done by ssh client itself.

Additionally I made the code simpler and faster.

@lars18th please review

### CODE REVIEW

**Comment by nunojpg** [comment]
The commits title is sshtunne, the last letter is missing.
There are signed-off-by lines with a fake e-mail address.

**Comment by stokito** [comment]
Sorry, fixed.
Email address of @lars18th  is not fake but a private
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

It's legit and you can send a message to the address.

**Comment by stokito** [comment]
I forgot to remove the CompressLevel from config. Fixed now

**Comment by nunojpg** [comment]
> Sorry, fixed. Email address of @lars18th is not fake but a private https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address
> 
> It's legit and you can send a message to the address.

No.

**Comment by stokito** [comment]
Can you please elaborate on this? Because my email can be just a fake but my sign-off will considered legal while if a real email hidden behind github makes it not legal? From copyright perspective you don't even have to specify your name (c) and anyway your work is considered yours.

**Comment by nunojpg** [comment]
A DNS lookup tells you immediately the domain doesn't have MX records. It's really beside the point to explain how the internet works. 
This is about basic due diligence. Of course in many other cases the signed-off-by line can be false, but I have no way of determining. In this PR it is obvious it is fake, so it's a easy one.

**Comment by stokito** [comment]
It's not fake, it's pseudonym. As you see in the GitHub it shows Lars as the coauthor. Technically speaking it's not out business how the authors emails looks like

**Comment by nunojpg** [comment]
https://openwrt.org/submitting-patches#sign_your_work
`all commits must contain Signed-off-by: My Name <my@email.address> where you write your real name and real email address, in accordance with [Section 11 of the Linux Kernel patches guide](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416)`

Only the core team can change the rules, this is not place to make legal arguments to a maintainer. We have to enforce them.

**Pull request closed without merging**
