### PR TITLE
[17.01] Change links from git://github.com to https://github.com

### PR DESCRIPTION
**Pull request by krombel**
I got into troubles to be behind a proxy and my build then fails
because it cannot connect to git://github.com urls

To avoid such problems for others I think it is useful to replace
them for the whole repo. This changes make it work for me again.

Signed-off-by: Matthias Kesler <krombel@krombel.de>

### CODE REVIEW

**Comment by luizluca** [comment]
I do suffer from the same problem.
These kind of changes normally have a "treewide:" prefix in commit message.
@thess, @hnyman, something for you.

FYI, the opposite of this commit was already NAKed at #1704.

If accepted, It would also be nice if travis could check and enforce https://github.com from now on.

**Comment by hnyman** [comment]
Is this intentionally done for the soon-to-be-retired old stable branch 17.01?

Not for current 18.06 or master?

**Comment by krombel** [comment]
I created the patch for 17.01 as the build env (gluon in my case) is based on this branch.
I wanted to fix this scenario so this was the result of that

**Comment by neheb** [comment]
@krombel please rebase

**Comment by neheb** [comment]
I am going to merge this. Looking at current master. there are six packages that use the git:// URL. 5 of them can be switched to HTTPS. The outlier is not in this pull request.

Given how minor this fix is, it should cause no immediate issues.

**Pull request merged**
