### PR TITLE
samba4: switch to waf cross-answer files

### PR DESCRIPTION
**Pull request by Andy2244**
Maintainer: me
Compile tested: arm/mips/powerpc/mips64/x86 (master)
Run tested: arm

Description:
* switch waf build to cross-answer files
* remove samba4 helper package qemu-userspace
* move timemachine related vfs modules to default vfs option _(vfs_catia vfs_streams_xattr)_

@yousong Here you go, after building and comparing all targets only minor differences exist per arch atm and none per cpu, so i guess my fear of cross-answer was rather unfounded. 😈

### CODE REVIEW

**Comment by Andy2244** [comment]
@diizzyy Is there a way to extract the `cross-answers.txt` file from the travis build_dir? I have no clue what settings are missing, since it compiles fine for me locally?

**Comment by xabolcs** [comment]
**Offtopic**
@Andy2244  would you mind to write down (into wiki page, blog post, etc...) the detailed steps of generating and maintaining the answer-files for all the targets?
Thanks!

I hoped that the `cross-execute` method lives a little bit longer. 😊

**Comment by Andy2244** [comment]
@xabolcs Sure will do if i figure out why travis complains about missing cross-answer settings and if this is a general problem or just travis related.

The problem was that while i was trying to fix the cross-execute buildbot failing targets, i had to add more and more qemu related fixes. I also assumed that cross-answer files might be different per cpu_type, yet they hardly differ per arch. You can check this branch for what i had to-do to compile it for most targets using cross-execute: https://github.com/Andy2244/openwrt-extra/tree/samba4-waf-cross-execute/samba4

**Comment by yousong** [comment]
Hello @Andy2244 , it looks like buildroot only needs to maintain a single 41-lines of answer cache for all arches.  Can we reuse that and maybe make it a template if tweaks are really needed in the future?

Please also split the change on qemu-userspace in a separate commit.  Thank you.

Here are some stats when I played with the cache file in this pull request

```
07416c0450d3b4fc43aaf358135fc826  aarch64.txt
1d5b642833834669d4f9054f3ecbb466  arc.txt
0098c486dda20260078dfd9ea7dc1d74  armeb.txt
0098c486dda20260078dfd9ea7dc1d74  arm.txt
0098c486dda20260078dfd9ea7dc1d74  i386.txt
884cb8ea4a00eea6678718d1e3acc87c  mips64el.txt
884cb8ea4a00eea6678718d1e3acc87c  mips64.txt
bf8623fb1584dfd0766f2b14637c045c  mipsel.txt
bf8623fb1584dfd0766f2b14637c045c  mips.txt
bb7fd5326836e869f830186b04985b63  powerpc.txt
07416c0450d3b4fc43aaf358135fc826  x86_64.txt
```

A simple script
```
as=(aarch64.txt  arc.txt  armeb.txt  arm.txt  i386.txt  mips64el.txt  mips64.txt  mipsel.txt  mips.txt  powerpc.txt  x86_64.txt)

#set -ex
for i in `seq 0 $((${#as[@]} - 2))`; do
        echo "############# diff -uprN ${as[i]} ${as[$((i+1))]}"
        diff -uprN "${as[i]}" "${as[$((i+1))]}"
done
```

**Comment by yousong** [comment]
@Andy2244 Maybe it's not the file missing, it's just that the answer file is not *complete*

**Comment by Andy2244** [comment]
@yousong Don't see why, i have to rebuild all main arch targets anyway so whats the harm in having a few more txt files?

Yes travis notes that some settings are missing, yet locally all works for like 10 targets i tested, so i'm a bit lost here without the actual cross-answer.txt file from travis or someone else having the same issue.

**Comment by yousong** [comment]
@Andy2244 It's just that I thought it's being too troublesome to maintain in its current form.  But it's your call ;)

**Comment by diizzyy** [comment]
Being a bit late, why are we switching?

@Andy2244 
To my knowledge the only data you can get out of Travis is the log file provided, it shouldn't be too hard to replicate Travis in a VM however even if it's a bit inefficient rather than having the ability to make Travis upload logs.

**Pull request merged**
