### PR TITLE
libinput: update to 1.15.5

### PR DESCRIPTION
**Pull request by neheb**
Converted to meson for speed.

Removed all patches. They are not necessary.

Mino0r cleanups.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dangowrt 
Compile tested: ath79

### CODE REVIEW

**Comment by BKPepe** [comment]
Why those patches are no longer necessary? You need to describe it in the commit message. Nobody knows that until looking into those patches.

This also requires to do run-testing due to transition to meson. There is a typo in the commit message.

**Comment by neheb** [comment]
I don't think run testing is applicable here. Nothing uses this.

**Comment by lucize** [comment]
this is used for xorg

**Comment by BKPepe** [comment]
In that case, please move it to [video](https://github.com/openwrt/video) feed.

**Comment by neheb** [comment]
I'll merge this for now.

I think all of these should be removed/moved in a big PR.

**Pull request merged**
