### PR TITLE
lua-openssl: Make version apk compatible

### PR DESCRIPTION
**Pull request by hnyman**
Make version compatible with apk.

Maintainer: @amnonpaz 
Compile tested: mediatek/filogic MT6000

### CODE REVIEW

**Comment by neheb** [comment]
This thing fails on me with GCC14. I haven't investigated.

**Comment by amnonpaz** [comment]
How does this change supports apk? Why should the mirror hash change if the version hasn't changed?

**Comment by neheb** [comment]
The version changes from 0.8.5-1 to 0.8.5.1

**Comment by hnyman** [comment]
Like neheb already said, package's version number format in OpenWrt changes slightly, so that it is compatible with the semantic versioning rules in the new APK package manager that is replacing opkg.

The version number change also affects via changing path the exact contents of the packed file of source code from git checkout.

**Pull request merged**
