### PR TITLE
[18.06] youtube-dl: update to version 2019.8.2

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: me
Compile tested: Xiaomi Mi WiFi R3G, ramips, mt7621, OpenWrt 18.06.02
Run tested: will be done on Monday as I have the router at work

Description:
- Update to version [2019.7.2](https://github.com/ytdl-org/youtube-dl/releases/tag/2019.07.02)
- Backport the Makefile from branches 'master' and 'openwrt-19.07'
It means that now it will be created as Python package
Fixes: https://github.com/openwrt/packages/issues/9307

### CODE REVIEW

**Comment by neheb** [comment]
I have no problems with this PR.

fail logs for 18.06 are at https://downloads.openwrt.org/releases/faillogs/

Yes that URL still points to 18.06 failures. The infrastructure has not been updated to segregate the stable branches.

**Comment by BKPepe** [comment]
I'd rather test it otherwise we will end up with the same situation like nfs, when maintainer doesn't care about it.

**Comment by BKPepe** [comment]
Updated to version 2019.7.16.
Compile tested: Xiaomi Mi WiFi R3G, ramips, mt7621, OpenWrt 18.06.02
Run tested: Xiaomi Mi WiFi R3G, ramips, mt7621, OpenWrt 18.06.02 with https://github.com/openwrt/packages/pull/9513, which is required

**Comment by BKPepe** [comment]
Updated to 2019.8.2. Compile and tested on Xiaomi Mi WiFi R3G, ramips, mt7621, OpenWrt OpenWrt 18.06.4

**Pull request merged**
