### PR TITLE
Update list for eurodns.com

### PR DESCRIPTION
**Pull request by larieu**
Added support for EuroDNS ( EuroDynDNS)

Maintainer: Laurentiiu Tanase

Compile tested: (put here arch, model, OpenWrt version)
Raspberry Pi 4 Model B Rev 1.5
ARMv8 Processor rev 3
bcm27xx/bcm2711
OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8

Run tested: (put here arch, model, OpenWrt version, tests done)
Raspberry Pi 4 Model B Rev 1.5
ARMv8 Processor rev 3
bcm27xx/bcm2711
OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8

Description:
added support for Dynamic DNS according to
https://www.eurodns.com/dynamic-dns-documentation

### CODE REVIEW

**Comment by feckert** [comment]
The pullrequest is not complete. Please have a look at the other pullrequest, that have already be merged into this repository. 

- Fill in the pullrequest description https://github.com/openwrt/packages/pull/22436#issue-1948980898 with the correct values
- Add a `Sigend-off-by` with your correct full name and a valid email addresse (Not that one from github)
- Add the missing json file to your commit. Adding only `eurodns.com` to the list file is not correct and will not work.
- Update the commit message with the `ddns-scripts` prefix, so we can see witch package does the commit change.
- Update the PKG_RELEASE number in the `ddns-scripts` Makefile

**Comment by larieu** [comment]
My name ... is simple
I have updated whatever I was able to understand

I can see another error about <package name>
I have no idea how to add that
can you point me to what to write at the package name?

**Comment by feckert** [comment]
This is not correct. You update the Pullrequest. Not the [commit](https://github.com/openwrt/packages/pull/22436/commits/ba81e75394dd84e1d868be1b77bd5f7a4f8010e0). As I said, have a look at the other pullrequest and commit in this repository.

**Comment by larieu** [comment]
I am not able to find the place where I can change the commit 
I'm trying to find it but no luck

**Comment by BKPepe** [comment]
Closing, because it is too hard to use e.g. Google to get any help or ask somewhere else.

**Pull request closed without merging**
