### PR TITLE
Bump gcc to version 7.4.0, Add config options

### PR DESCRIPTION
**Pull request by noblepepper**
Maintainer: me / @noblepepper
Compile tested: mips (8devices Carambola2), arm (8devices Jalapeno)
Run tested: mips (8devices Carambola2) compiles hello world in c c++, links dynamically or statically
Description: Bump gcc to version 7.4.0, Add config options
for coping libc.a, libpthread.a and libstdc++ to target.
Add config option to eliminate need for -lstdc++ and -lgcc_pic
switches when linking statically.

### CODE REVIEW

**Comment by neheb** [comment]
Prefix commit title with gcc:

**Comment by noblepepper** [comment]
@Neheb - Automated checks beat you to it!

This should fix:
https://github.com/openwrt/packages/issues/7252
https://github.com/openwrt/packages/issues/8236 
https://forum.openwrt.org/t/toolchain-bug-cant-compile-c-program-with-exceptions-statically/18459 (on target building only not cross compiling)

I have similar package ready for 18.06 (gcc 7.3.0) is a pull request for it also acceptable?

**Comment by neheb** [comment]
I'd rather not do a massive backport.

I'd also add ```@!arc``` to the dependencies. ARC support was added in GCC8.

**Comment by noblepepper** [comment]
@!arc added



Just a note for anyone that wants gcc 7.3.0 all that needs to be done is:
change PKG_VERSION in the Makefile
copy 
020-PR-libstdc-81797-Add-.NOTPARALLEL-to-include-Makefil.patch
100-PR-rtl-optimization-83496.patch
from the toolchain gcc patches to the package patches directory

**Comment by flyn-org** [comment]
@noblepepper: I think I found a misspelling in the configuration menu item "Include static libptread on target".

Should be libpt*h*read.

**Pull request merged**
