### PR TITLE
net/coova-chili: update default firewall setup

### PR DESCRIPTION
**Pull request by aleksander0m**
Remove the obsolete firewall configuration as the legacy firewall
package was removed in a901329781eae4716c21d3d8f70a18501d9f2352.

And at the same time, define in the configuration the correct paths
for the firewall rules, installed as /etc/chilli/{up|down}.sh

Signed-off-by: Aleksander Morgado <aleksander@aleksander.es>

### CODE REVIEW

**Comment by diizzyy** [comment]
@thess @hnyman 
Please merge

**Comment by aport** [comment]
If the firewall is restarted, will rules added by the up script disappear? I think it might be good to still have a firewall hook here.

**Comment by neheb** [comment]
Maintainer approved. Merging.

**Comment by hnyman** [comment]
@neheb 

> Maintainer approved. Merging.

Where did you see the maintainer approval?  (from Kaloz???)

Please also bump the PKG_RELEASE, as the shipped item changes.

**Comment by neheb** [comment]
Right after the kaloz line. @teslamint is the new maintainer according to: https://github.com/openwrt/packages/blob/master/net/coova-chilli/Makefile#L12

I also bumped the PKG_RELEASE after.

**Comment by hnyman** [comment]
Funny. 
I checked the commit in the PR and followed that to the old Makefile (in the authors repo), and as that file is old and non-rebased, I saw the old maintainer definition there. 
My bad :-(

**Comment by teslamint** [comment]
@hnyman no worries. My bad I overlooked PKG_RELEASE is not bumped.

**Comment by neheb** [comment]
Buildbot fails on this. Why do I get the feeling this was not properly tested...

**Comment by ynezz** [comment]
> Buildbot fails on this. Why do I get the feeling this was not properly tested...

What's the build failure? I quite don't see how the changes in this commit could cause build failures.

**Comment by neheb** [comment]
the Makefile tries to install the deleted file.

**Comment by teslamint** [comment]
Yes, need to remove this line. https://github.com/openwrt/packages/blob/79ef85aa8c212586a0934fecc299205b8df66d01/net/coova-chilli/Makefile#L146

**Comment by ynezz** [comment]
> the Makefile tries to install the deleted file.

Ah, bummer. I didn't noticed it on the first sight as well. BTW I don't follow this repository quite often, but I vaguely remember some nice integration with Travis CI (?), which was build testing the PRs. Any idea why it was disabled?

**Comment by teslamint** [comment]
> > the Makefile tries to install the deleted file.
> 
> Ah, bummer. I didn't noticed it on the first sight as well. BTW I don't follow this repository quite often, but I vaguely remember some nice integration with Travis CI (?), which was build testing the PRs. Any idea why it was disabled?

GitHub Services are deprecated and should migrate to GitHub Apps. https://developer.github.com/changes/2018-04-25-github-services-deprecation/

**Comment by neheb** [comment]
Well, according to Travis, it built successfully: https://travis-ci.org/openwrt/packages/builds/284628504?utm_source=github_status&utm_medium=notification so :man_shrugging:

**Comment by ynezz** [comment]
> Well, according to Travis, it built successfully:

Because it seems, that Travis didn't tried to build the package `No new or modified packages found!` ?

**Comment by teslamint** [comment]
> > Well, according to Travis, it built successfully:
> 
> Because it seems, that Travis didn't tried to build the package `No new or modified packages found!` ?

maybe because PKG_RELEASE is not bumped up, so it skips the build?

**Comment by ynezz** [comment]
> GitHub Services are deprecated and should migrate to GitHub Apps. 

It seems, that the real reason is, that this PR was created (October 201) before the CircleCI integration was added to this repository (February 2019) and probably CircleCI isn't checking the PRs which was introduced before the integration.

**Comment by teslamint** [comment]
> > GitHub Services are deprecated and should migrate to GitHub Apps.
> 
> It seems, that the real reason is, that this PR was created (October 2017) before the CircleCI integration was added to this repository (February 2019) and probably CircleCI isn't checking the PRs which was introduced before the integration.

So is there any way to test this PR on CircleCI?

**Comment by ynezz** [comment]
> maybe because PKG_RELEASE is not bumped up, so it skips the build?

Yeah it seems, that it needs modified Makefile in order to rebuild the packages https://github.com/openwrt/packages/blob/master/.travis_do.sh#L99 which makes me wonder if that assumption is correct, as I'm wondering what changes in the packages doesn't need Makefile touches, at least the PKG_RELEASE bump.

**Comment by neheb** [comment]
@teslamint not after being merged. prior to being merged, it would need to be rebased against master.

I don't think this is a problem with CircleCI but I could be wrong.

**Comment by ynezz** [comment]
> So is there any way to test this PR on CircleCI?

I don't have this deep knowledge about GitHub/CircleCI integration and available options, maybe it could be somehow configured oon CircleCI, otherwise the PR would probably may just need to be closed and reopened in order to get registered in CircleCI, or rebased on current master and pushed to this PR branch.

**Comment by teslamint** [comment]
> > So is there any way to test this PR on CircleCI?
> 
> I don't have this deep knowledge about GitHub/CircleCI integration and available options, maybe it could be somehow configured oon CircleCI, otherwise the PR would probably may just need to be closed and reopened in order to get registered in CircleCI, or rebased on current master and pushed to this PR branch.

Or maybe it's better to create the new PR than reopen the old PR.

**Comment by hnyman** [comment]
Closing and opening the PR does not help.

CircleCI and travis test builds take the config from the PR's source code repo as seen by the PR (the moment of the PR branch branching). So, getting the current checks to be done, the PR branch should be rebased to the HEAD of master, and then force-pushed to update the PR.

**Comment by teslamint** [comment]
Okay, I'll create new PR then.

**Pull request merged**
