### PR TITLE
libxs: Moddable SDK XS JavaScript Engine Library

### PR DESCRIPTION
**Pull request by bfriedkin**
Signed-off-by: Brian Friedkin <brian@moddable.tech>

Maintainer: Brian Friedkin / @bfriedkin
Compile tested: (arm_cortex-a9_vfpv3, LINKSYS WRT1900ACS, 18.06.02)
Compile tested: (mips_24kc,GL-AR300M, 18.06.02)
Compile tested: (mipsel_24kc,GL-MT300N-V2, 18.06.02)
Compile tested: (aarch64_cortex-a53, Raspberry Pi 3 Model B+, 18.06.02)
Run tested: (arm_cortex-a9_vfpv3, LINKSYS WRT1900ACS, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)
Run tested: (mips_24kc,GL-AR300M, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)
Run tested: (mipsel_24kc,GL-MT300N-V2, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)
Run tested: (aarch64_cortex-a53, Raspberry Pi 3 Model B+, 18.06.02, Moddable SDK JavaScript example apps, including, but not limited to: basic hello world, sockets, secure sockets, net, and new JavaScript example apps that wrap OpenWrt libraries and features including: bmon, opkg, iwinfo, leds, uci, initscripts)

Description:

This pull request is for a Moddable SDK port of the XS JavaScript engine library to OpenWrt. XS is the JavaScript engine at the core of Moddable applications and tools, designed to run efficiently on resource constrained SoC and microcontroller platforms. This Makefile builds libxs, which is a shared library that contains the XS JavaScript engine. Using the Moddable SDK and XS on OpenWrt allows developers to build and deploy applications written in JavaScript to OpenWrt router and device targets.

https://www.moddable.com

### CODE REVIEW

**Comment by bfriedkin** [comment]
Hello -

Any suggestions for why this PR is failing the **buildpr** check would be appreciated. It looks like the failure is in the build host setup, which should be external to my PR.

Regards,
Brian

**Comment by neheb** [comment]
Just rebase to current master

**Comment by bfriedkin** [comment]
Hello -

Apologies for the trouble here. I tried to rebase two different ways:

```
git checkout libxs
git merge master
```

and

```
git checkout master
git pull --rebase
git checkout libxs
git fetch origin
git merge origin/master
```

Then committed a small change to my Makefile. Unfortunately I am still failing the **buildpr** step.

Could you please share the exact Git commands required to make this work?

Thanks you!

Regards,
Brian

**Comment by neheb** [comment]
I use

```
git fetch origin
git rebase origin/master
git push --force XXX
```

**Comment by bfriedkin** [comment]
@neheb -

Thank you for the reply. I tried the following when committing a simple update to my Makefile:

```
git checkout libxs
git fetch origin
git rebase origin/master
git push origin libxs -f
```

The rebase always says that both my master and libxs branches are up-to-date. Unfortunately same failure above. Should I start over with a new pull request? I have multiple "Compile tested" and "Run tested" sections in my original commit. Could that be leading to problems?

Regards,
Brian

**Comment by neheb** [comment]
https://github.com/bfriedkin/packages/tree/libxs

This branch is 3 commits ahead, 274 commits behind openwrt:master. 

I think you have the remotes messed up.

origin for me is: https://github.com/openwrt/packages
neheb for me is: git@github.com:neheb/packages.git

so for me it would be

```
git checkout libxs
git fetch origin
git rebase origin/master
git push --force neheb
```

**Pull request closed without merging**
