### PR TITLE
mailman: Update to 2.1.29

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @Shulyaka 
Compile tested: ipq806x

### CODE REVIEW

**Comment by neheb** [comment]
Failure is due to Python 2.7 on my end. Paging @commodo 

https://gist.github.com/neheb/e2b492d048a9d424ae8e128b210921dc

**Comment by commodo** [comment]
That looks like something did not build correctly with respect to target-side OpenSSL.
Not sure why.
Will take a look.

**Comment by commodo** [comment]
btw: which target is that in the build log ?

**Comment by neheb** [comment]
ipq806x.

Actually it might have something to do with me disabling deprecated APIs on OpenSSL...

**Comment by commodo** [comment]
Ok.
Could you try re-enabling them ?
FWIW: Python 2.7.15 is old, but it will still stay around for the foreseeable future. I don't know what updates they would consider for it for APIs and stuff. I think the interest for Python is to get everyone to switch to Python 3.X (which coincidentally is at 3.7 now).

**Comment by neheb** [comment]
Tested again. It compiles fine locally. Meaning it's probably the usual Travis python stuff.

@dibdot @hnyman any chance of merge? Maintainer approved.

**Pull request merged**
