### PR TITLE
softethervpn: update to latest release and rework makefile

### PR DESCRIPTION
**Pull request by Ansuel**
This package install both server client and bridge app... This is useless if someone needs to run only the server on the device. Split the package in 3 subpackage and a base package that contains file needed by all 3. This also upgrade the package to latest release to fix some bug and memory leak.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@hnyman can you review this?

**Comment by neheb** [comment]
I have a change that solves the problem of deprecated OpenSSL API usage. I never pushed it as some parts are hackish. Maybe I should rebase against this...

**Comment by Ansuel** [comment]
I would like to bump this to GitHub repo but they switched to cmake makefile and ./configure fail on
Ncurse detection ( even if selected as dep...) Any idea about that?

**Comment by fededim** [comment]
Ok changes are fine for me

**Pull request merged**
