### PR TITLE
netatalk: drop package

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: n/a
Run tested: n/a

----------------------------------------------------------------

Link to abandoned packages PR: https://github.com/openwrt/packages-abandoned/pull/18

AppleShare products have been unused for a while now (since Mac OS 9.2.2)
around 2002.
So, there should be fewer users requiring this package.

Last update of netatalk was in December 2018. Not sure if newer updates
will be created.

It's time to cut the cord on our end and move it to the abandoned packages.

Info: https://en.wikipedia.org/wiki/AppleShare

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by mstorchak** [comment]
Why removing a package if it still works?

**Comment by commodo** [comment]
> Why removing a package if it still works?

well, this mostly has to do with me not wanting to maintain it anymore;
it was my decision as a maintainer to drop it, and not keep it around;
i also don't [just] want to remove myself as a maintainer and leave the package un-maintained :)
the whole idea in the packages feed is that all package should have at least one maintainer listed; to avoid packages being abandoned, but still present in the packages feed;

but, since you raised your voice here, this is good;
feel free to revert these 2 PRs and add yourself as a maintainer :)

**Comment by commodo** [comment]
> > Why removing a package if it still works?
> 
> well, this mostly has to do with me not wanting to maintain it anymore;
> it was my decision as a maintainer to drop it, and not keep it around;
> i also don't [just] want to remove myself as a maintainer and leave the package un-maintained :)
> the whole idea in the packages feed is that all package should have at least one maintainer listed; to avoid packages being abandoned, but still present in the packages feed;
> 
> but, since you raised your voice here, this is good;
> feel free to revert these 2 PRs and add yourself as a maintainer :)

ping;
so, my intent isn't to upset anyone;
i'm mostly trying to simplify my life a bit here :)
i.e. i don't want to bring this package back [and maintain it], but i am fine if someone else does it;

**Comment by mstorchak** [comment]
@commodo , I apologize for the delay - got distracted and then forgot to reply in time.
No worries, I'll check how much I depend on netatalk and consider maintainership if it appears that this is the only option for TimeMachine backups for me.

**Comment by aparcar** [comment]
ugh, bummer. How to use remote time machine backups in 2022?

**Comment by neheb** [comment]
thought samba could handle that.

**Comment by aparcar** [comment]
Great thank you

**Comment by Chapoly1305** [comment]
@commodo  thank you for the effort. As one of many user of using netatalk on home router, I found the news recently and I really appreciate for your commitment. Hopefully we can see this project enrolls the mainline later.

**Comment by commodo** [comment]
> @commodo thank you for the effort. As one of many user of using netatalk on home router, I found the news recently and I really appreciate for your commitment. Hopefully we can see this project enrolls the mainline later.

Well, you can jump in to take it over :)

One reason (from me) to drop it, was to also allow for someone else to take it over.

**Comment by APCCV** [comment]
@commodo well, it may be me.

It looks like I will need netatalk for a while (MacOS 10.13 and earlier cannot use TimeMachine to a SMB share). I was also surprised when I did not see the package around anymore.

I got netatalk 3.1.18-3 to build for ipq806x. It seems to work; one old Mac is TimeMachining to it now.

How do I take over? Put in a PR for it to go back in?

**Comment by Neustradamus** [comment]
For the history:

Netatalk 3.1.7 (not merged):
- https://github.com/openwrt/packages/pull/1550

Netatalk 3.1.9:
- https://github.com/openwrt/packages/pull/3135

Netatalk 3.1.11:
- https://github.com/openwrt/packages/pull/4402

Netatalk 3.1.12:
- https://github.com/openwrt/packages/pull/7850

Netatalk 3.1.13:
- https://github.com/openwrt/packages/pull/18687
- Backport: https://github.com/openwrt/packages/pull/18696

Netatalk 3.1.18 (not merged):
- https://github.com/openwrt/packages/pull/24206
- https://github.com/openwrt/packages/pull/24249

Netatalk 3.2.0:
- https://github.com/openwrt/packages/pull/24257

Netatalk 3.2.5:
- https://github.com/openwrt/packages/pull/24762

Netatalk 4.0.2 (not merged):
- https://github.com/openwrt/packages/pull/25195

Netatalk 4.0.4:
- Master: https://github.com/openwrt/packages/pull/25200 + https://github.com/openwrt/packages/pull/25251
- 24.10 backport: https://github.com/openwrt/packages/pull/25246 + https://github.com/openwrt/packages/pull/25260

**Comment by APCCV** [comment]
> For the history:

That shows how something that could have been done with three PRs by someone that knew what they were doing, took 4x more.

It’s done. Next release will have netatalk and AppleTalk.

@Neustradamus, do you use this thing? Asking as It’s always good to know you’re not alone in this world. Any details you can share how you use netatalk on openwrt? Anything in particular to enable? Next release I’ll try get a skinny package and a couple of more functionally rich ones in place… which means next commit I push is probably going to take some churn.

**Pull request merged**
