### PR TITLE
net-tools: add route utility

### PR DESCRIPTION
**Pull request by sch-m**
Maintainer: @neheb @mhei 
Compile tested: x86_64, APU3, latest master
Run tested: x86_64, APU3, latest master

Description:
Extend (and rename) the existing mii-tool package to also support
the net-tools route command.

This may be needed if you want to support other address families than
inet/inet6 like x.25.

### CODE REVIEW

**Comment by neheb** [comment]
@Borromini is listed as a maintainer.

**Comment by Borromini** [comment]
@sch-m That looks alright me, although you're probably pulling a more recent check-out, so PKG_SOURCE_DATE should be modified as well, as well as PKG_RELEASE reset to 1 AFAIK (even more so because you're renaming the package and as such it makes no sense to increment the latter).

@neheb Can you comment on that?

**Comment by sch-m** [comment]
@Borromini PKG_SOURCE_VERSION is unchanged, so I don't have to change the PKG_SOURCE_DATE.

**Comment by neheb** [comment]
I think he's suggesting to update the version.

This PR otherwise looks fine to me.

**Comment by Borromini** [comment]
@sch-m You're right, sorry. Was looking at the wrong hash. Would you mind bumping the version as well in your PR?

**Comment by sch-m** [comment]
@Borromini OK, I'll look at it again after my Christmas vacation. Merry Christmas!

**Comment by sch-m** [comment]
@neheb @Borromini I've updated this PR to also bump to the latest version.

**Comment by Borromini** [comment]
LGTM. @neheb Can you merge this or should I do something?

Been a while since I did anything in the package repo, am a bit rusty :).

**Pull request merged**
