### PR TITLE
crtmpserver: Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Switched to codeload to simplify the Makefile.

Removed the website as it is no longer valid.

Renamed .diff file to .patch

Minor cleanups.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @heil 
Compile tested: ar71xx

### CODE REVIEW

**Comment by diizzyy** [comment]
Since it seems pretty much unmaintained perhaps it's worth considering removing this package and redirect users to use nginx and the rtmp module instead?

**Comment by neheb** [comment]
I have no qualms with removing the package. I do not use it myself.

**Comment by neheb** [comment]
Added uclibcxx support. For those that use this package, it's smaller now.

**Comment by neheb** [comment]
Yay. The first package that gives me an excuse to bump uclibc++.

**Comment by diizzyy** [comment]
@heil 
Please back this out, it depends on http://lists.infradead.org/pipermail/openwrt-devel/2018-December/015303.html which isn't accepted (yet at least)

**Comment by neheb** [comment]
Changing CXX_DEPENDS to libstdcpp is enough to fix it for right now but yes.

**Comment by cshoredaniel** [comment]
@neheb hence the need for a least smoke testing <sigh>

**Comment by diizzyy** [comment]
@cshoredaniel 
To be fair, he did actually mention it and the PR checks didn't say all green

**Comment by cshoredaniel** [comment]
Sorry, missed it on this one.  Catching up on notifications.

**Pull request merged**
