### PR TITLE
hidapi: update to 0.12.0

### PR DESCRIPTION
**Pull request by neheb**
Switch to cmake.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @paulfertser 
Compile tested: mips24

### CODE REVIEW

**Comment by neheb** [comment]
and find_package(Iconv) is broken again. What a surprise...

**Comment by neheb** [comment]
Added a basic meson build. Took care to match the cmake build.

**Comment by neheb** [comment]
@dhewg does PKG_INSTALL do anything with meson packages?

**Comment by neheb** [comment]
@paulfertser updated based on upstream feedback.

**Comment by dhewg** [comment]
> @dhewg does PKG_INSTALL do anything with meson packages?

I don't think so. Looking at it again:
if PKG_INSTALL is set, Build/Install will default to Build/Install/Default.
cmake provides Build/Install/Default and sets PKG_INSTALL so that it gets used.
meson provides Build/Install/Meson and sets Build/Install to default to it, so there's no need for PKG_INSTALL.

It's inconsistent, may be that could be cleaned up. But I don't recall if there was a specific reason to not go the cmake route.

**Comment by neheb** [comment]
Yeah I removed it: https://github.com/openwrt/packages/commit/df5d7245b9f888b21e2c9c02fd002c606e9c7c6e

**Pull request merged**
