### PR TITLE
mariadb: fix dependency cascade

### PR DESCRIPTION
**Pull request by p4u**
Maintainer: @micmac1 

Description:

Fix https://github.com/openwrt/packages/issues/8200

### CODE REVIEW

**Comment by micmac1** [comment]
NACK, this is intentional, to keep the menu in utils/databases clean. It doesn't have any impact on the packages themselves.

**Comment by micmac1** [comment]
That's not correct, you just need mariadb-server as a dep. Your package will work as expected.

Building is a different subject. You need to make the proper selections. But in that regard there is no difference to other packages that work the same way.

On another note, I fail to see the reason to add the server as a dependency. Except if your package is a plugin _for_ the server. The server package does not provide any shared library.

**Comment by p4u** [comment]
Any package requiring the MariaDB SQL daemon will depend on "mariadb-server" AFAIK. 

I don't get what you mean by "Building is a different subject". That's all about it, building. If a package cannot be build it cannot be installed....

**Let me give you a use case example of what am I saying.**

So, in case I want to make a new package named "llmp" which means "linux+lighttpd+mysql+php". I would create a metapackage which will have as dependency "mariadb-server" (among others).

When I try to build this package (in my BuildRoot) it will crash cause "mariadb-server" dependency cannot be satisfied, it requires (in addition) "mariadb-base" and "mariadb-server-base". So (after reading all the Makefiles to understand this dependency cascade) my "llamp" package will end up depending on three packages: "mariadb-base", "mariadb-server-base" and "mariadb-server" (amont others).

IMO it does not make any sense and it's not intuitive at all.

Usuarlly you use this kind of dependencies for something like "plugins", so only if the main package is selected it makes sense to select plugins. For instance "mariadb-server-plugin-locales" should have "mariadb-server" as dependency (without '+'). Here it is clear that som third party package that depends on "mariadb-server-plugin-locales" must also depend on "mariadb-server".

I don't want to give you any kind of lesson, not my intention. Just trying to let you understand my concerns by examples. Can you point out another package following the same dependency relation?

**Comment by micmac1** [comment]
In your DEPENDS just put "mariadb-server" instead of "+mariadb-server". Yes, you need to select the server in menuconfig before your meta package appears. The compiled package will then have a normal dependency on mariadb-server. No need to add mariadb-common or mariadb-server-base to DEPENDS.

The reason why I chose the depends they way they are is that I do not want to clutter the utils/databases menu. And in all fairness, there is not a single package depending on the client nor the server in-tree.

**Pull request closed without merging**
