### PR TITLE
elektra: Fix compilation with uClibc-ng

### PR DESCRIPTION
**Pull request by neheb**
Add patch that checks for libiconv instead of iconv. nls.mk handles this.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @haraldg 
Compile tested: arc700

### CODE REVIEW

**Comment by haraldg** [comment]
It seems this patch breaks MUSL builds. Also it sems this is not strictly openwrt specific, so it probably should be fixed upstream too.

@markus2330 any thoughts on supporting uClibc-ng upstream?

**Comment by neheb** [comment]
I modified the Makefile a little bit to get more output. This is what I get now:

```
make[6]: Entering directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21'
[ 27%] Building C object src/plugins/filecheck/CMakeFiles/elektra-filecheck.dir/filecheck.c.o
cd /home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21/src/plugins/filecheck && /home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_arc700_gcc-9.1.0_uClibc/bin/arc-openwrt-linux-uclibc-gcc -DHAVE_KDBCONFIG_H -DPLUGIN_SHORT_NAME=filecheck -DREADME=readme_filecheck.c -Delektra_filecheck_EXPORTS -I/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21/src/include -I/include -I/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21/src/plugins/filecheck  -Os -pipe -matomic -mcpu=arc700 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21=elektra-0.8.21 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -std=gnu99  -Wno-deprecated-declarations  -Wstrict-prototypes  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wsign-compare -Wfloat-equal -DNDEBUG -fPIC   -o CMakeFiles/elektra-filecheck.dir/filecheck.c.o   -c /home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21/src/plugins/filecheck/filecheck.c
/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/elektra-0.8.21/src/plugins/filecheck/filecheck.c:17:10: fatal error: iconv.h: No such file or directory
   17 | #include <iconv.h>
      |          ^~~~~~~~~
compilation terminated.
src/plugins/filecheck/CMakeFiles/elektra-filecheck.dir/build.make:65: recipe for target 'src/plugins/filecheck/CMakeFiles/elektra-filecheck.dir/filecheck.c.o' failed
make[6]: *** [src/plugins/filecheck/CMakeFiles/elektra-filecheck.dir/filecheck.c.o] Error 1
```

Even though I'm passing -DICONV_INCLUDE_DIR and -DICONV_LIBRARY , it seems it's not being used by the filecheck plugin, which it needs.

**Comment by markus2330** [comment]
I do not understand this patch. [check_function_exists](https://cmake.org/cmake/help/v3.0/module/CheckFunctionExists.html) checks if the function, passed as first parameter, exists. I do not know a function called libiconv and it is also not used within Elektra's source code.

If you have troubles compiling Elektra, it is best if you [create an issue upstream](https://issues.libelektra.org/new). Make sure that you append the relevant parts of CMakeError.log and CMakeOutput.log. See https://github.com/ElektraInitiative/libelektra/issues/2790 for a nicely done bug report about a similar problem.

> any thoughts on supporting uClibc-ng upstream?

There is currently nobody working on it but we happily take patches to support more systems.

**Comment by neheb** [comment]
It's similar to this patch: https://github.com/openwrt/packages/blob/master/utils/uvcdynctrl/patches/010-iconv.patch

libiconv (including the stub) redefines the functions with lib prefixes to differentiate between the libc variant and its own.

It seems nls.mk was missing in the Makefile. It's working now. Will push a new version soon.

**Comment by neheb** [comment]
Seems there's an SDK problem...

**Comment by neheb** [comment]
It passes building now.

**Comment by markus2330** [comment]
The new patch seems to be only related to packaging (not relevant for upstream).

**Pull request merged**
