### PR TITLE
New package: python-gattlib for Bluetooth LE

### PR DESCRIPTION
**Pull request by attila-lendvai**
the package compiles, but when i tried to run my little test, it segfaults. i'm creating this pull request for others to find it who may decide to pick up the slack.

i'm not planning to use it, python is too heavy on my target.

### CODE REVIEW

**Comment by sbyx** [comment]
@commodo please review.

**Comment by sbyx** [comment]
Okay, since there are no objections: Please add a PKG_LICENSE and PKG_MAINTAINER tag to your pygattlib package and we are good to go. I agree with karlp's comment though.

**Comment by attila-lendvai** [comment]
FTR, the cross-compile fix has been pushed already separately: https://github.com/openwrt/packages/pull/1811

i've rebased the PR to reflect this, but i'm not planning to use this package and i'm not regularly compiling openwrt myself, so someone interested please pick up the slack.

**Comment by sbyx** [comment]
Thanks, however we still need a PKG_MAINTAINER and a PKG_LICENSE tag before merging. See https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by champtar** [comment]
As no one want to be PKG_MAINTAINER of python-gattlib, closing this

**Pull request closed without merging**
