### PR TITLE
strongswan: put package items into own submenu

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>
Maintainer: @stintel 

Description:
Strongswan occupies around 100 items in menu Netwok/VPN.
A submenu in Network would make Network/VPN less crowded.

### CODE REVIEW

**Comment by mwarning** [comment]
@stintel let me know your option. :-)

**Comment by stintel** [comment]
I definitely prefer to keep strongSwan under the VPN submenu. Not sure if it's possible to make a "strongSwan" submenu in the VPN submenu...

**Comment by mwarning** [comment]
@stintel I would prefer a submenu under VPN. But I have not been able to do that.
@jow Do you know if this is possible?

**Comment by cotequeiroz** [comment]
I think I have some suggestions that may do what you intend here.  Leave `SUBMENU:=VPN`, and add
```
  MENU:=1
```
inside `define Package/strongswan`. Change `DEPENDS:= +strongswan` to `DEPENDS:= strongswan` everywhere. 
That will create a menu for strongswan inside the VPN submenu, with all of the dependent packages there.

Also, since there are not many configuration options, instead of opening yet another menu, I'd change
```
menu "Configuration"
	depends on PACKAGE_strongswan
```
in `Configure.in` to:
```
if PACKAGE_strongswan
comment Configuration
```
Add a final `comment Packages` to separate them from the Configuration, before changing `endmenu` to `endif`.

**Comment by mwarning** [comment]
@cotequeiroz like this? https://github.com/openwrt/packages/pull/8512

**Comment by mwarning** [comment]
let's close this one in favor of #8512

**Pull request closed without merging**
