### PR TITLE
[23.05] ksmbd-tools: update to 3.5.1 and swap to tagged as master

### PR DESCRIPTION
**Pull request by pesa1234**
update ksmbd-tools to 3.5.1 and update download link to prepare for apk

Maintainer: nobody
Should fix https://github.com/openwrt/packages/issues/23771

### CODE REVIEW

**Comment by BKPepe** [comment]
Why would you like to include "fix for apk" in OpenWrt 23.05 when the apk is not even in the master branch, yet? I really doubt that it will be backported to OpenWrt 23.05.

**Comment by pesa1234** [comment]
> Why would you like to include "fix for apk" in OpenWrt 23.05 when the apk is not even in the master branch, yet? I really doubt that it will be backported to OpenWrt 23.05.

Thanks for your support, I would like to swap to tagged release as master branch, in my opinion, more easier to mantain.

Thanks again guys, I'll do all of my best to learn as fast as possible.

**Comment by pesa1234** [comment]
updated 030-glib.patch to fix compiling

**Comment by neheb** [comment]
@pesa1234 these are normally done with git cherry-pick -x

**Comment by pesa1234** [comment]
> @pesa1234 these are normally done with git cherry-pick -x

Ok, sorry I didn't know. Feel free to close this, can you do that?

Thanks

**Comment by neheb** [comment]
I'll handle it, sure.

**Comment by pesa1234** [comment]
> I'll handle it, sure.

Thank you, I close this, thanks again

Andrea

**Comment by neheb** [comment]
Done.

**Pull request closed without merging**
