### PR TITLE
python-chardet,cryptography: bump versions

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @jefferyto (for python-cryptography)
Compile tested: x86 https://github.com/openwrt/openwrt/commit/cdc8d4b46f0811292fffc6094acd81e854b5f4a5
Run tested: x86 https://github.com/openwrt/openwrt/commit/cdc8d4b46f0811292fffc6094acd81e854b5f4a5

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
I'd run make package/python-x/refresh for both to reduce the diff.

**Comment by commodo** [comment]
so, for `python-cryptography` [which only has patches] i generated them via git format-patch
but i can reduce them;

**Comment by neheb** [comment]
No I mean git format-patch adds extra stuff to the diff. quilt removes it.

**Comment by commodo** [comment]
> No I mean git format-patch adds extra stuff to the diff. quilt removes it.

i know; but i don't mind the extra stuff;
i also don't mind removing it

**Comment by neheb** [comment]
OK. I thought you were referring to the patches themselves. I rebased them upstream based on master there. It seems much of that PR was merged.

**Comment by commodo** [comment]
> OK. I thought you were referring to the patches themselves. I rebased them upstream based on master there. It seems much of that PR was merged.

are those patches ok for 3.3.1?
or are they for 3.4.1/master?

**Comment by neheb** [comment]
https://github.com/pyca/cryptography/commit/d8c6c1eef3c277ff02ec6f3a57ae4a07b0d4e34c was merged after 3.3.1 looks like.

**Comment by commodo** [comment]
Changelog v1 -> v2:
* ran `make package/python-cryptography/refresh`

**Review by jefferyto — APPROVED** [review]
LGTM - thanks!

**Comment by neheb** [comment]
make package/python-cryptography/refresh was not ran at all.

**Comment by neheb** [comment]
I tested this locally. It seems some APIs are missing defines. I fixed here: https://github.com/neheb/packages/commit/44b45e51b3d68d29974bc44e256e72cfe07a2689

I ran with -Werror=implicit-function-declaration to make sure I caught all of them.

**Comment by commodo** [comment]
> make package/python-cryptography/refresh was not ran at all.

i thought i did; though TBH, I was multi-tasking quite a bit yesterday, so who know? ¯\_(ツ)_/¯
i pulled your commit for the cryptography upgrade;

**Pull request merged**
