### PR TITLE
https-dns-proxy: update to 2021-11-22-1

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: me
Compile tested: x86_64, Sophos SG-135, 21.02.1
Run tested: x86_64, Sophos SG-135, 21.02.1, start, resolve domain, stop

Description:
* update to 2021-11-22 upstream source
* update patch file
* update init script to preserve manual entries
	(fixes https://github.com/stangri/source.openwrt.melmac.net/issues/149)
* update init script service_triggers

Signed-off-by: Stan Grishin <stangri@melmac.ca>

### CODE REVIEW

**Comment by stangri** [comment]
@BKPepe upstream switched to building release by default, please test on Turris to confirm it still builds fine.

**Comment by BKPepe** [comment]
Hey, okay, I will do it! While I will take a look, should I check it also against openwrt-21.02/openwrt-19.07 branches? Do you want to test something specific during run testing, or is the compile test just fine?

**Comment by stangri** [comment]
> Hey, okay, I will do it! While I will take a look, should I check it also against openwrt-21.02/openwrt-19.07 branches? Do you want to test something specific during run testing, or is the compile test just fine?

My plan was to cherry-pick it for 21.02 only. The reason I asked for feedback for Turris is that I vaguely remember it being the reason for @champtar making the patch in the first place, as it wasn't building properly without the patch with some Turris security setting.

**Comment by BKPepe** [comment]
Compile tested for:
- Turris MOX, mvebu/cortexa53, OpenWrt master
- Turris MOX, mvebu/cortexa53, OpenWrt 21.02.1

**Pull request merged**
