### PR TITLE
[21.02] unbound: update version to 1.13.2 and backport fix

### PR DESCRIPTION
**Pull request by Ansuel**
Backport version update to 1.13.2 and some fixes to prevent log spam when ipv6 connection drops.

### CODE REVIEW

**Comment by champtar** [comment]
@Ansuel can you use `git cherry-pick -x` ?

**Comment by EricLuehrsen** [comment]
@Ansuel thanks. looks good.

**Comment by Ansuel** [comment]
@champtar is correct now?

**Comment by champtar** [comment]
Perfect thanks !

**Pull request merged**
