### PR TITLE
apparmor: fix packaging

### PR DESCRIPTION
**Pull request by CodeFetch**
Removes the BUILDONLY flag as otherwise no packages will be created.

@oskarirauta

### CODE REVIEW

**Comment by neheb** [comment]
```
Commit sha: 6e5880b, Author: Vincent Wiemann, Committer: GitHub; Expected "Vincent Wiemann vincent.wiemann@ironai.com", but got "Vincent Wiemann me@bibbl.com".
```

**Comment by CodeFetch** [comment]
@neheb Thanks for the hint! One more reason to not use Github's web interface for committing.

**Comment by BKPepe** [comment]
Where is approve from maintaner? :eyes:

**Comment by CodeFetch** [comment]
@BKPepe This was a point of discussion right from the beginning. https://github.com/openwrt/packages/pull/15643#discussion_r644097179

We have tested it and no packages will be created with the BUILDONLY flag set and the files are missing in rootfs. @oskarirauta said that something did not work, but I can't confirm that. The BUILDONLY flag is used for packages which are only used as build dependencies. It's wrong to use it here.

**Comment by BKPepe** [comment]
Well, don't take it wrong, but what's the point of being maintainer if he didn't approve it and it is merged no matter what? 1 or 2 days from my point of view are not enough to review the things! 

Based on your comment, I could see that we don't need to have maintainers at all and that's why they are leaving like https://github.com/openwrt/packages/pull/15853

**Pull request merged**
