### PR TITLE
debootstrap: update to version 1.0.87

### PR DESCRIPTION
**Pull request by dosvald**
Maintainer: @dangowrt 
Compile tested: mvebu on OpenWrt trunk
Run tested: mvebu, OpenWrt trunk

Signed-off-by: Denis Osvald <denis.osvald@sartura.hr>

### CODE REVIEW

**Comment by dosvald** [comment]
Also, since Debian doesn't keep old versions around, and to keep this package readily buildable even when version is not bumped in time, maybe consider using Debian's anonvcs https://anonscm.debian.org/git/d-i/debootstrap.git/ , or an even better source?

**Comment by hnyman** [comment]
@dangowrt 
Good to merge? Looks like a simple version bump.

**Comment by diizzyy** [comment]
@dangowrt 
Ping?

**Comment by dangowrt** [comment]
overlooked that one, sorry.

**Pull request merged**
