### PR TITLE
sane-backends: rebind printers to usblp after scan

### PR DESCRIPTION
**Pull request by luizluca**
While scanning, sane unbinds usb device from usblp module. This
patch creates a saned wrapper that keep track of all usb devices
binded to usblp before saned is launched and rebind them back
if not still bound after saned exits.

This workaround is only effective if saned is launched by a super
daemon like xinetd as it needs to exit after scan job finish. If
not, printing will not be available while saned service is running.

Write access to /sys/bus/usb/drivers/usblp/bind is required. So,
normally it would require root access.

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

Maintainer: me
Compile tested: ar71xx, arc_arc700, arm_xscale, x86, x86_64 (although there is no change in binaries)
Run tested: ar71xx

Description:

There is a conflict between user-mode USB drivers (SANE, CUPS) and usblp (used by p910nd). When saned runs while usblp is loaded, it unbinds the USB device (removing device /dev/usb/lp*) from the kernel driver. However, once saned exists, usblp does not reclaim it back. This way, p910nd cannot print after someone has scanned.

The previous workaround approach for this problem is to create a saned wrapper that unloads usblp module and reload it after saned exits. However, removing usblp will stop any printer from working during the scanning, even those not used by SANE. Also, some saned uses might not even touch the printer, like in listing devices. And besides, unloading/loading modules is a critical operation.

This patch also creates a wrapper but, instead of removing the module, it keeps track of every USB device attached to the driver before saned runs. If any of those are not bound to a driver after saned exists, it rebinds it to usblp.

It does need root access (or, at least write access to /sys/bus/usb/drivers/usblp/bind). If someone wants to run saned with a different user/group, it is possible that some hotplug magic would be enough to assign write access to saned user/group.

@cshoredaniel , would you please take a look if this alternative approach is enough for your needs. Feel free to suggests improvements, specially if it helps others run saned as a non-root user.

Another alternative approach would be to patch saned code. saned claims and release USB device, even detecting when kernel driver is using it:

```
Tue Apr 30 02:01:51 2019 daemon.info saned[18698]: io/hpmud/musb.c 427: Found interface conf=0, iface=1, altset=0, index=1
Tue Apr 30 02:01:51 2019 daemon.info saned[18698]: io/hpmud/musb.c 389: Active kernel driver on interface=1 ret=1
Tue Apr 30 02:01:51 2019 daemon.info saned[18698]: io/hpmud/musb.c 393: Detaching kernel driver on interface=1 ret=0
Tue Apr 30 02:01:51 2019 daemon.info saned[18698]: io/hpmud/musb.c 535: claimed 7/1/2 interface
Tue Apr 30 02:01:51 2019 kern.info kernel: [ 6048.284813] usblp0: removed
Tue Apr 30 02:01:51 2019 daemon.info saned[18698]: io/hpmud/musb.c 780: read actual device_id successfully fd=1 len=270
Tue Apr 30 02:01:51 2019 daemon.info saned[18698]: io/hpmud/musb.c 561: released 7/1/2 interface
```
Maybe it could give the device back to the kernel driver after it has finished with it.

@neheb, I'm mentioning you as you took a look at the previous PR from @cshoredaniel.

Superseeds #8057

### CODE REVIEW

**Comment by neheb** [comment]
Please bump PKG_REVISION as this changes behavior.

Also, please run these scripts against shellcheck.

**Comment by cshoredaniel** [comment]
@luizluca Hey just noticed this...will try to test.

**Comment by luizluca** [comment]
> Please bump PKG_REVISION as this changes behavior.

Just did. Thanks.

> Also, please run these scripts against shellcheck.

It blamed some things that wasn't really a real problem. I was only working with directories in sysfs that are safe (no space/glob/etc). Anyway, I changed the code to pass shellcheck.

**Comment by cshoredaniel** [comment]
Ok, so I have confirmed that if you use the same user for saned (e.g. 'lp') (through xinetd.d/sane-port and adding ```procd_add_param user lp```  to /etc/init.d/p910nd, then
the following two hotplug scriptlets will set the appropriate permissions so that saned and p910nd can successfully run as user/group 'lp' and have the usblp rebinding work:

/etc/hotplug.d/20-hplip
```
#!/bin/sh

# Copyright (C) 2009 OpenWrt.org


case "$ACTION" in
        add)
                # You have to figure out your PRODUCT id. Uncomment the line below,                                                                          
                # attach and detach your HP USB printer to find your id in /tmp/hplip.test.                                                                  
                # It will look like "Found 3f0/1717/100 on /proc/bus/usb/002/009"                                                                            
                # Replace 3f0/1717/100 below with your id.
                #
                # echo "Found $PRODUCT on $DEVICE" > /tmp/hplip.test

                # [ "$PRODUCT" = "3f0/1717/100" ] && chown nobody $DEVICE && chmod 666 $DEVICE                                                               
                [ "$PRODUCT" = "3f0/2a12/100" ] && chgrp lp /dev/$DEVNAME && chmod 660 /dev/$DEVNAME                                                         
                ;;
        remove)
                # device is gone
                ;;
esac
```
and /etc/hotplug.d/usbmisc/20-usblp
```
#!/bin/sh

case "$ACTION" in               
        add)     
                [ "$DEVNAME" = "usb/lp0" ] && {                                               
                        chmod 660 /dev/$DEVNAME                                               
                        chgrp lp /dev/$DEVNAME                                                
                        chmod 220 /sys/bus/usb/drivers/usblp/bind                                                                                            
                        chgrp lp /sys/bus/usb/drivers/usblp/bind                                                                                             
                }                                                                                                                                            
                ;;                                                                            
        remove)                                                                               
                # device is gone                                                              
                ;;                                                                            
esac
```

**Comment by luizluca** [comment]
@cshoredaniel , I created an alternative approach for hotplug https://github.com/luizluca/openwrt-packages/blob/d50e4f92f89b0a3bdfe65b092916af15434641af/utils/sane-backends/files/etc/hotplug.d/usb/20-saned

It is still WIP. It also replaces hplip hotplug.

I also granted /dev/usb/lp* access as in your script, but I don't think saned really needs it. Are you doing that for p910nd?

I tested creating a saned group. Maybe it's better to use lp group as you did (but saned user). However, this group should be shipped by default or by p910nd, not by sane-backends.

Have you tried to PR p910nd support as non-root? A very reduced version of my hotplug script would  provide read/write-access to /dev/usb/lp*. Besides that, it just need to add USERID in Makefile (in order to create a user/group) and update init/config.

**Comment by cshoredaniel** [comment]
@luizluca I will test when I get a chance.  Yes it is for p910nd that I grant /dev/usb/lp* access (I use lp group use for both saned and p910nd to avoid permissions issues).  I have not yet done a PR for p910nd but I guess I should.  I have a hotplug scriptlet that goes in /etc/hotplug.d/usbmisc and is really quite simple (I simply assume that all usblp devices should be owner:group lp and, which makes life easy).  I'll work on that too.

**Comment by luizluca** [comment]
@cshoredaniel , it is simple to apply to every single usmisc device. However, it is overkill.

You should filter to only apply it to those devices that have print usb class (0x07). You might need to read sysfs properties as I guess usbmisc does not include usb class info in env vars.

If you use usb event instead of usbmisc, it could be something like this (not tested):

```
[ "$ACTION" = "add" ] || exit 0
[ "$DEVTYPE" = "usb_interface" ] || exit 0
[ "${INTERFACE%%/*}" = 7 ] || exit 0

LP_GROUP=lp
grep -q -E "^$LP_GROUP:" /etc/group || exit 0

uevents="$uevents /sys$DEVPATH/usbmisc/*/uevent"
[ -r "$uevent" ] &&
devname=$(grep -E ^DEVNAME= "$uevent") &&
lpdev="/dev/${devname#*=}"

chgrp $LP_GROUP "$lpdev"
chmod g+rw "$lpdev"
```

The usbmisc version might even be simpler (and better as it avoids the use of wildcards). You can search sysfs for usb interface in order to do the proper filter. It might be something like "device/bInterfaceClass" or "device/bInterfaceSubClass"

**Comment by cshoredaniel** [comment]
Oh in usbmisc I test for usblp* device -- so it's not all usbmisc devices just printers.  No need for sysfs etc.  Let me see if I can pull it up from the device right now:
```
#!/bin/sh

case "$ACTION" in
        add)
                case "$DEVNAME" in
                usb/lp*)
                        chmod 660 /dev/$DEVNAME
                        chgrp lp /dev/$DEVNAME
                        chmod 220 /sys/bus/usb/drivers/usblp/bind
                        chgrp lp /sys/bus/usb/drivers/usblp/bind
                        ;;
                *)
                        ;;
               esac
                ;;
        remove)
                # device is gone
                ;;
esac

**Comment by cshoredaniel** [comment]
I've provided some updates in https://github.com/luizluca/openwrt-packages/pull/3 and I've (finally) created the non-root p910nd PR (https://github.com/openwrt/packages/pull/9583).

**Comment by luizluca** [comment]
> I've provided some updates in [luizluca#3](https://github.com/luizluca/openwrt-packages/pull/3) and I've (finally) created the non-root p910nd PR (#9583).

That's great. Let's see how that goes and then rebase the non-root saned on that.

**Comment by cshoredaniel** [comment]
@luizluca I've noticed that on reboot (but not on initial plugin of the device) that the hp all-in-one I have only does a "bind" not "add" for the "usb_interface" hotplug event.
e.g. here are all the events that occur for me during boot:
```
add usb_device /devices/platform/ahb/1b000000.usb/usb1
add usb_device /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.3
add usb_device /devices/platform/ahb/1b000000.usb/usb1/1-1
add usb_device /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.2
bind usb_interface /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.3/1-1.3:1.1
bind usb_interface /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.2/1-1.2:1.0
```
Since 20-saned is checking for an "add" on "usb_interface" during boot the /dev/bus/usb/xxx/xxx device doesn't get the saned group chown.
I'm working on a patch.

**Pull request merged**
