### PR TITLE
nextdns: Update to version 1.43.3

### PR DESCRIPTION
**Pull request by rs**
Update to version 1.43.3

### CODE REVIEW

**Comment by castillofrancodamian** [comment]
IPs 45.90.28.46 and 45.90.30.46 are offline.

**Comment by rs** [comment]
That would be surprising. Can you please provide a traceroute to both?

**Comment by rs** [comment]
May I ask how these IPs are related to this PR? The software in this PR does not require them to function.

**Comment by castillofrancodamian** [comment]
It has already been solved. Probably servers down.

**Comment by 1715173329** [comment]
so you created 4 releases within 24 hours? These PR-s like #24032 #24040 should be closed?

**Pull request merged**
