### PR TITLE
Add an issue template

### PR DESCRIPTION
**Pull request by yousong**
So that maintainers can receive at least one notification at the issue
creation time ;)

You can open an issue at my repo (https://github.com/yousong/packages) for a preview.

### CODE REVIEW

**Comment by yousong** [comment]
@openwrt/package-maintainers

**Comment by hnyman** [comment]
One typo:  wraping  -->  wrapping

You might maybe mention a link to to Luci repo, so that Luci issues get reported there.

**Comment by thess** [comment]
This is just a suggestion - Instead of putting a bunch of directions, pointers and requests at the head of each form (that some folks don't delete), could we perhaps have document like CONTRIBUTING.md (or appending to it) in the repo and merely put a single line at the top of each form referencing the instructions. There would be a lot less clutter to delete and it would be OK if is wasn't.

I do like the forms - keep it up.

**Comment by champtar** [comment]
@thess if someone don't delete the directions, it means they didn't read them, so they will not read the "REPORTING.md" either

**Comment by hnyman** [comment]
The people who report "bad" issues do not likely follow links to reporting advice. For that reason I like the current rather verbose form templates that directly guide the issue opener to input some useful info. 

Yes, some people do not remove the template's advice text from the issue, but I find that as a smaller problem than a vague issue report without details.

**Comment by thess** [comment]
@champtar - exactly what I mean

@hnyman - OK leave them. It was a suggestion.

**Pull request merged**
