### PR TITLE
flashrom-glibc: fix to compile with glibc on mips

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @Noltari  
Compile tested: (mipsel-musl, mips74kc-musl, mips74kc-glibc)
Run tested: none

Do not include sys/io.h with glibc on mips.
Removed a patch that's apparently not needed, which also included sys/io.h.
Added flag to allow deprecated declarations so package will compile as is.

On mips, glibc doesn't have sys/io.h.  I've checked what musl does in sys/io.h: it defines two functions in mips version of sys/io.h: iopl and ioperm using 'syscall'.
What I've done was to define these functions using syscall, just like musl does, and adapted the
conditions to include <sys/io.h> in hwaccess.h.  

There was a patch to include <sys/io.h> in flash.h, but I found no calls to anything defined (I've checked amd64's version of sys/io.h as well) there outside of hwaccess.c, which already includes hwaccess.h.  So there is no apparent need to patch flash.h.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by hnyman** [comment]
sounds partially similar as #6049 from @jow-

**Comment by cotequeiroz** [comment]
@hnyman  I had to add the -Wno-error to Makefile just to allow compilation.  #6049 actually fixes the issue.  
The main purpose of this PR is that the pacakge doesn't compile on mips when using glibc.

I have finished compiling the whole tree on mips with glibc, and ran across several glitches such as this one; mostly relating to the need to explicitly link with -lbsd, and listing libbsd as dependency.  Should I open more PRs, or is the combination mips/glibc not worth accommodating?

**Comment by hnyman** [comment]
#6049 has been merger, so the no-error change is likely unnecessary.

**Comment by cotequeiroz** [comment]
I messed up my commits and couldn't reopen this with the correct commit, so I've reopened this #6058

**Pull request closed without merging**
