### PR TITLE
libwebsockets: add full variant with libuv, plugins, CGI

### PR DESCRIPTION
**Pull request by dosvald**
Maintainer: @karlp
Compile tested: OpenWRT trunk on mvebu
Run tested: OpenWRT trunk on mvebu

### CODE REVIEW

**Comment by diizzyy** [comment]
While at it, perhaps bump it to 2.0.3 or 2.1.0?
The tarballs are not usable?

**Comment by dosvald** [comment]
> While at it, perhaps bump it to 2.0.3 or 2.1.0?
Both of those have an ABI bump so I think this should be done separately.

> The tarballs are not usable?
Please elaborate?

**Comment by diizzyy** [comment]
https://github.com/warmcat/libwebsockets/releases
Tarballs are preferred over git

I figured since you were a user of this port and made additions to it you could also do a quick runtime test of an newer version. There are quite many ports that are falling behind upstream which is why I asked in the first place. As far as any package update would go, a separate commit under the same PR would be fine.

**Comment by diizzyy** [comment]
Nice, please keep xz instead of gz however.

**Comment by dosvald** [comment]
Upstream doesn't provide xz unfortunately.

**Comment by diizzyy** [comment]
Ahh, you changed to tarball. My bad, all is fine then!

**Comment by dosvald** [comment]
@karlp  have you had a chance to look at this?

**Comment by karlp** [comment]
Not yet, been particularly busy recently. It's on my list though. It's my only current outstanding lede/openwrt related task right now if that helps :)

**Pull request merged**
