### PR TITLE
autossh: Update to 1.4g

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @bk138 
Compile tested: ramips

### CODE REVIEW

**Comment by BKPepe** [comment]
Would you please update URLs to HTTPS? They're using [HSTS](https://www.ssllabs.com/ssltest/analyze.html?d=www.harding.motd.ca). 

Did you try to run it?

**Comment by neheb** [comment]
Fixed.

**Comment by bk138** [comment]
Same here, looks good to me, but no testing on my side as I'm travelling.

**Comment by neheb** [comment]
It's a bugfix for the previous release, so should be fine.

**Pull request merged**
