### PR TITLE
openfortivpn: version bump to 1.15.0 and assorted improvements

### PR DESCRIPTION
**Pull request by aaronjg**
Maintainer: @lucize 
Compile tested: openwrt-sdk-19.07.4-ipq806x-generic_gcc-7.5.0_musl_eabi.Linux-x86_64
Run tested: 19.07.4-ipq806x

- remove patch that has been included upstream
- remove dependence on resolveip
- remove hotplug script that is handled by "proto_add_host_dependency"
- use openfortivpn default tunnel ip if none specified
- add status checking with uclient-fetch

Signed-off-by: Aaron Goodman <aaronjg@stanford.edu>

### CODE REVIEW

**Comment by lucize** [comment]
LGTM

**Comment by feckert** [comment]
@aaronjg Please change the space to tabs

**Comment by aaronjg** [comment]
@feckert I just tabified the netifd and wrapper scripts

**Comment by aaronjg** [comment]
also fixed shellcheck warnings

**Comment by feckert** [comment]
LGTM
@lucize could you please do another check if this works for you?
I have no openfortivpn setup

**Comment by lucize** [comment]
LGTM

**Pull request merged**
