### PR TITLE
open-plc-utils: remove build timestamp

### PR DESCRIPTION
**Pull request by lynxis**
Maintainer: @ffainelli
Compile tested: x86

Build timestamps prevent reproducible builds [0].

[0] https://reproducible-builds.org/docs/timestamps/

Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

### CODE REVIEW

**Comment by lynxis** [comment]
ping @ffainelli

**Comment by ffainelli** [comment]
LGTM, can you also submit this patch to the upstream open-plc-utils repository?

**Comment by lynxis** [comment]
@ffainelli already did. https://github.com/qca/open-plc-utils/pull/114
I've added a newline to the company field as @mhei pointed out.

**Comment by lynxis** [comment]
@thess can you merge it?

**Comment by thess** [comment]
@ffainelli is certainly an active member. I'd wait at least 7 days.
I think you have some others pending we should push with apologies and revert if requested,

**Comment by ffainelli** [comment]
Merged (still on vacation).

**Pull request merged**
