### PR TITLE
noddos: bump to v0.5.5

### PR DESCRIPTION
**Pull request by StevenHessing**
Signed-off-by: Steven Hessing <steven.hessing@gmail.com>

Maintainer: Steven Hessing / @StevenHessing
Compile tested: (mvebu / ipq806x, Linksys WRT1200AC / TPLink Archer 2600, 17.01.3 / 17.01.4)
Run tested: (Linksys WRT1200AC 17.01.3 / TPLink Archer 2600 17.01.4, service up and running for a day)

Description:

New features:
* Use yaml for the noddos configuration file
* Add support for SsdpDeviceType and MdnsHostname
* Further reduce logging by making debug logging for main event loop optional (disabled by default)
* (OpenWRT/LEDE) Automatic interface detection
* (OpenWRT/LEDE) Automatic installation of cronjob

Bug fixes:
* [#39](https://github.com/noddos/noddos/issues/39) DnsQueryCache expired too soon
* [#34](https://github.com/noddos/noddos/issues/34) DnsCache.json expiration incorrect

Instructions:
* Users of previous versions have to manually copy configuration settings made to noddos.conf to noddos.yml
* OpenWRT/LEDE Users: if you install noddos manually, you now also have to download and install the libyaml-cpp package.

### CODE REVIEW

**Comment by hnyman** [comment]
You should separate the introduction of a new package to its own commit.

And have you thought, how the versioning of the new package will go in future?
Having "Openwrt" as the version tag looks strange.

**Comment by StevenHessing** [comment]
Thanks for the feedback! 

With two different PRs, the PR for noddos will the fail the build check if I don't include libyaml-cpp bits. So what I could do is create one PR for just libyaml-cpp and one for noddos + libyaml-cpp but I'd have to keep those to PRs aligned if I make any changes to the libyaml-cpp Makefile, which is not great. In the PR introducing noddos, I originally had a separate PR for libtins but later combined them to get it merged so that same approach I took here.

The git repo for libyaml-cpp doesn't define any releases so I forked the repo and created my own release. If libyaml-cpp ever publishes a release we can switch the source repo and adopt their versioning.  Introducing release numbering in the forked branch could create confusion if the upstream branch introduces versioned releases. What I could do is rename the release in the forked branch to openwrt-1.0 to make clear this is a release dedicated to OpenWRT. 

For both issues, please advice what you think the best solution is and I'll change the PR accordingly

**Comment by hnyman** [comment]
> So what I could do is create one PR for just libyaml-cpp and one for noddos + libyaml-cpp but I'd have to keep those to PRs aligned if I make any changes to the libyaml-cpp Makefile, which is not great. 

One PR with two commits.

> The git repo for libyaml-cpp doesn't define any releases so I forked the repo and created my own release. If libyaml-cpp ever publishes a release we can switch the source repo and adopt their versioning. 

Better approach would be to fetch a git commit from their repo, and name it as version 2017-11-01-hash version. 

There are actually automatic macros for git based packages. See odhcpd for example. Only definitions are git source commit, source version date (and mirror hash):
 https://github.com/lede-project/source/blob/master/package/network/services/odhcpd/Makefile
```
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL=$(LEDE_GIT)/project/odhcpd.git
PKG_SOURCE_DATE:=2017-09-16
PKG_SOURCE_VERSION:=f0bce9cdd0f2d0e21e0d64cb7b653521d18040e2
PKG_MIRROR_HASH:=c008f339eca7ff24158535ed4be2319164b5f970e06f64fce18ef772358b44a8
```

**Comment by StevenHessing** [comment]
Makefile libyaml-cpp updated as per guidance and split up the changes in to two commits.

**Pull request merged**
