### PR TITLE
treewide: refresh hashes after move to use ZSTD as default

### PR DESCRIPTION
**Pull request by robimarko**
With the recent move to using ZSTD as the default compression format for packaging git repo clones we must refresh all of the hashes for the packages feed as well.

### CODE REVIEW

**Comment by hnyman** [comment]
@robimarko 
I re-triggered the CI, as some new SDKs were already done by buildbot.
The basic zstd hash check seemed to work for many packages, but CI stumbled into a dirty patch in ttymidi-sysex. 

I refreshed that patch with fce37314, so if you want to retry the CI, you should rebase your PR branch.

**Comment by neheb** [comment]
Needs a rebase.

**Comment by hnyman** [comment]
@robimarko 
Although there is now a need for a new rebase (due to a later libmad commit), I think that no new CI round needs to be waited. The old CI progressed quite far and compilation success is not actually needed: PR is only about hash check success.

Meanwhile the phase2 packages buildbot has created lots of .zst archives to sources.openwrt.org, so there are live examples of the download results. The hashes of those files seem to match the values set in this PR, so this looks ok.

I think that we should just remove the conflict and merge the commit to avoid unnecessary repeated upstream checkouts/downloads by buildbot.

**Comment by robimarko** [comment]
@hnyman Conflict resolved, I am OK with merging this.

**Pull request merged**
