### PR TITLE
python: fix HostPython again

### PR DESCRIPTION
**Pull request by commodo**
Tested on python-setuptools.
Fixes https://github.com/openwrt/packages/issues/2113

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Hopefully this fixed also all the other broken python modules.
Buildbot was not happy about the last "fix".
http://buildbot.openwrt.org:8010/broken_packages/malta/

**Comment by hnyman** [comment]
Looks like other python packages now compile, but python-ldap does not like the recent changes.
E.g.
http://buildbot.openwrt.org:8010/broken_packages/mcs814x/python-ldap/compile.txt
```
running install
Checking .pth file support in /store/buildbot/slave/mcs814x/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/python-ldap-2.4.20/ipkg-install/usr/lib/python2.7/site-packages/
/store/buildbot/slave/mcs814x/build/staging_dir/host/bin/python2 -E -c pass
TEST FAILED: /store/buildbot/slave/mcs814x/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/python-ldap-2.4.20/ipkg-install/usr/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /store/buildbot/slave/mcs814x/build/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/python-ldap-2.4.20/ipkg-install/usr/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''
```
@commodo  @the-alien

**Comment by commodo** [comment]
Will look into it.

**Comment by the-alien** [comment]
Fast looking through the patch revealed a typo:
`exort PYTHONPATH:=$(PYTHONPATH);`

**Comment by commodo** [comment]
yep; found it too;
not a good week for me ;
i'm a goof factory

**Comment by commodo** [comment]
is there a way to enable all packages to build ?
like a single master switch (or something) ?

**Comment by plntyk** [comment]
yes adding to your .config template: CONFIG_ALL=y

or in menuconfig under Global build options -> Select all userspace packages by default

**Comment by dfc-d** [comment]
Yes, you have to enable CONFIG_ALL in your .config and then erase 
everything from PACKAGE_dnsmasq down (so the default takes).

Assuming you're talking about from the base build and/or are building 
the SDK - once you have and SDK I'm not sure if there is a safe way to 
enable CONFIG_ALL.

Regards,

Daniel

**Pull request merged**
