### PR TITLE
postfix: less overlayfs rewrites

### PR DESCRIPTION
**Pull request by Shulyaka**
Fix for #4620

Signed-off-by: Denis Shulyaka <Shulyaka@gmail.com>

-------------------------------

Maintainer: me
Compile tested: LEDE revision 4787e19, ar7xxx
Run tested: LEDE Reboot (HEAD, r2032+3), ar7xxx

### CODE REVIEW

**Comment by hnyman** [comment]
You should increase PKG_RELEASE

**Comment by Shulyaka** [comment]
Yes, you're right. Changed it to 3 to be after #4663

**Comment by Shulyaka** [comment]
Ah, I guess I should rebase this pull request on top of #4663 to avoid merge conflicts?

**Comment by hnyman** [comment]
I merged #4663 
You can either rebase this, (or drop the version bump from this, as these will get merged so near each other)

**Comment by Shulyaka** [comment]
let me do a separate pull request for this

**Pull request closed without merging**
