### PR TITLE
libnatpmp: Switch to CMake

### PR DESCRIPTION
**Pull request by neheb**
Allows simplifying the Makefile. CMake patch is from upstream.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @hauke 
Compile tested: arc700

### CODE REVIEW

**Comment by diizzyy** [comment]
...or just use the latest commit?
https://github.com/miniupnp/libnatpmp/commits/master

**Comment by neheb** [comment]
From a quick look at the commits, there's nothing really useful. Just Makefile changes for Windows and whatnot.

**Comment by neheb** [comment]
As agreed on IRC, I have annexed this package.

**Comment by karlp** [comment]
If the cmake patch is from upstream, can we get their patchfile with the context?

**Comment by neheb** [comment]
It's multiple patches. I took the one from master.

**Comment by diizzyy** [comment]
Which is why I suggested tracking the branch to keep it simple... :-)

**Comment by neheb** [comment]
What's silly is that https://github.com/miniupnp/libnatpmp does not match the tarball. Here's what happened:

Original libnatpmp code(1) get forked(2) in 2012.

latest release from 2015 uses the original codebase.

https://github.com/miniupnp/libnatpmp uses a forked codebase from 2012 with the VERSION file still saying 2012.

The fork adds Java support. Not interesting here as only two packages use libnatpmp. NAT-PMP is mainly useful on macOS anyway.

**Pull request merged**
