### PR TITLE
wget: update to 1.21.3

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
https://lists.gnu.org/archive/html/info-gnu/2022-02/msg00017.html

Signed-off-by: Nick Hainke <vincent@systemli.org>

Maintainer: @tripolar 
Compile tested: CI
Run tested: no

### CODE REVIEW

**Comment by BKPepe** [comment]
Somehow CI does not like your change. :) This needs to be run tested anyway.

**Comment by zdz2019** [comment]
Should the patch be removed?

**Comment by hnyman** [comment]
@PolynomialDivision 

The patch does not apply.
Please test the PR.

```
Applying patch 100-fix-hsts-time.patch
patching file src/hsts.c
Hunk #2 FAILED at 293.
1 out of 3 hunks FAILED -- rejects in file src/hsts.c
Patch 100-fix-hsts-time.patch does not apply (enforce with -f)
make[2]: *** [Makefile:108: /home/build/openwrt/build_dir/target-arc_archs_glibc/wget-ssl/wget-1.21.3/.quilt_checked] Error 1
```

**Comment by PolynomialDivision** [comment]
Forgot to git add the deletion of the file. Already described that in the commit title. ^^

**Comment by BKPepe** [comment]
```
find /omnia-master/build/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/wget-nossl/wget-1.21.3/ipkg-arm_cortex-a9_vfpv3-d16/wget-nossl -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package wget-nossl is missing dependencies for the following libraries:
libnettle.so.8
make[2]: *** [Makefile:118: /omnia-master/build/bin/packages/arm_cortex-a9_vfpv3-d16/packages/wget-nossl_1.21.3-1_arm_cortex-a9_vfpv3-d16.ipk] Error 1
```

**Comment by hnyman** [comment]
Probably a fallout from https://git.savannah.gnu.org/cgit/wget.git/commit/?h=v1.21.3&id=a24e67e239ef949cc77a4c4e5a0beb703026a296

**Comment by hnyman** [comment]
I filed a bug at upstream about the NTML & nettle detection: https://savannah.gnu.org/bugs/?63431

I tried yesterday to debug the issue, but arrived at a conclusion that upstream has defined a logic where the presence of nettle forces NTLM support although the user has explicitly disabled it in configure options.  I did not yet figure out a patch, but let's see what upstream thinks.

(@BKPepe reverted this local version bump a month ago, so this is just about figuring out a solution for re-implementing the version bump)

**Pull request merged**
