### PR TITLE
evtest: Switch to tarballs

### PR DESCRIPTION
**Pull request by neheb**
Simpler. Should also fix uscan.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @psidhu 
Compile tested: ipq806x

Did not bump the release number as it is the same compiled code.

### CODE REVIEW

**Comment by psidhu** [comment]
what's wrong with uscan?

**Comment by neheb** [comment]
It tracks the git revision and not the version

**Comment by neheb** [comment]
@any problems?

**Comment by psidhu** [comment]
@neheb Nope, I just compile tested and it looks okay to me.

@hnyman

**Pull request merged**
