### PR TITLE
simple-adblock: initial version

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: Stan Grishin / @stangri
Compile tested: ipq806x, Linksys EA8500, LEDE 17.01 snapshot r3006
Run tested: ipq806x, Linksys EA8500, LEDE 17.01 snapshot r3006

Description:
simple adblock -- provides dnsmasq-based adblocking with just one file (PROCD-based init script).

Background:
I started working on it before @dibdot published his robust adblocking, it is different being a bit simpler and still serving transparent pixel instead of just NXDOMAIN for http connections.
I'd like to investigate feasibility of having it included in official feed.

### CODE REVIEW

**Comment by hnyman** [comment]
Some initial commits:

* you need to squash the three simple-adblock commits together.
* forcing +libustream-cyassl dependency by default looks strange. That is a non-standard SSL lib. 
  Does the default libustream-mbedtls not work?  (the default dep will be used by the buildbot, so the downloaded package will use that. Likely the default should be mbedtls, which is the default for LuCI-ssl)

**Comment by stangri** [comment]
Thank you @hnyman! Squashed/fixed commits.
You're right about libustream-mbedtls. I confused it (as non-working) with non-existent now libustream-polarssl.
I've tried to list dependencies with logical operators in them https://github.com/stangri/packages/blob/aed7e54ed962b8dc14fee7cb54177fcca5028b98/net/simple-adblock/Makefile#L20 as either of currently available libustream libraries should work, as well as wget+libopenssl, but got syntax errors. Any idea how to fix that? I've googled and looked at various packages makefiles for about an hour and gave up.

**Comment by hnyman** [comment]
> I've tried to list dependencies with logical operators in them here as either of currently available libustream libraries should work, as well as wget+libopenssl, but got syntax errors. Any idea how to fix that? 

No easy way.
The different libustream-XXX packages are mutually exclusive, so only one of them can be installed. Different users have different SSL libs selected due to other packages, so the user likely does not start from black state.

There are several options, none of which is perfect:
* leave the dependency away, just document the requirements, and possibly check those at startup. That is what Dibdot's adblock does now, I think. If you browse Dibdot's adblock's history, you can see that after trying various complicated strategies to sniff the download tool in use, if now defaults to using wget, but user can manually set options to use other tools.
* select (with +) libustream-mbedtls as that is the default SSL used with luci-ssl (and mbedtls is used as default e.g. for curl and px5g). Everything is simple and buildbot compiles a version that suits most of the of people.  If somebody want to change it, he needs to edit the package Makefile and recompile
   * You can additionally create a config menu like curl, so that changing SSL lib in menuconfig is easy. And there is one variant as default (mbedtls). See https://github.com/lede-project/source/blob/master/package/network/utils/curl/Makefile and https://github.com/lede-project/source/blob/master/package/network/utils/curl/Config.in  But that is maybe overkill.

Regarding dependencies in general:
Symbol "+" actively selects the dependent package. So having multiples items with + selects them all, and using || to "or" the selections does not work with "+".  ("||" would work if you do not use "+", but that would then hide the package completely until the user has a matching ustreamssl lib selected. ) The current system does not enable you to say "select any one of them. Curl's config menu item approach is the closest that you can reach.

**Comment by stangri** [comment]
Thank you for your elaborate reply Hannu. If there's no way to use OR for '+' dependencies I think the best imperfect option would be to leave dependencies as they are indicated now: +uclient-fetch +libustream-mbedtls.

For majority of users it would either use or install the default lib, for people with alternative libustream libraries it would error out, but still be possible to force-install the package without dependencies (I can elaborate on that in the README if it becomes an issue) and the script would still work.

I've looked at Dirk's adblock Makefile of course, it doesn't list any dependencies at all.

Please advise if there're any other issues I need to address before PR can be accepted.

**Comment by dibdot** [comment]
Hi Stan, I've looked over your sources - just a few remarks:

- you are using 'uci -P /var/state' state variables to get IP/IPv6 addresses - these state variables are deprecated, do not rely on them. Better use functions in /lib/functions/network.sh
- you enable IPv6 support whenever you found a local IPv6 address. This looks wrong to me, you should check for an IPv6 wan address
- to my knowledge the IPv6 NAT kernel module is not loaded by default, you should check for that or add an package dependency
- you are using a hadrcoded 'br-lan' interface in your dns rulesets
- your uhttpd instance is not limited to your pixelserver ip, is this intended?

Hope this helps!
Dirk

**Comment by stangri** [comment]
Dirk, thank you for fantastic feedback, let me clean up the code, I'll post back when I do (might take me some time).

**Comment by stangri** [comment]
Dirk, I've sent you an e-mail wrt IPv6 DNS hijacking and iptables rules. In the mean time I've addressed your concerns in the latest (squashed) commit.

**Comment by dibdot** [comment]
Stan,
to be honest I've got lost with your latest changes ... during your different commits you finally switched to (an already existing) NXDOMAIN solution. What's the (actual) purpose of this package? From user perspective we've a working adblock solutions by privoxy, by dnsmasq (NXDOMAIN), IP based (I don't know) ... maybe you should consider this before adding an additional one ... 

Just my 2 cents.

**Comment by stangri** [comment]
Dirk, I appreciate all the feedback and advice, both here and via e-mail.
While your existing adblock is very robust in its ability to process pretty much any blocklist with the special rules, there're still a few things which make simple-adblock different (even with the switch to nxdomain thanks to your advice):
- Fully uci & luci-compatible
  - you can whitelist individual domain with uci & luci
  - you can add URL for a file with whitelisted domains with uci & luci
  - you can add blacklisted individual domain with uci & luci
  - you can add URL for a file with blacklisted hosts/domains with uci & luci
- Additional whitelisting option thru URL to a list of domains
- Much easier to add simple blacklisted hosts/domains file
- Stores all blacklisted domains in single file eliminating duplicates across multiple sources
- Uses no special processing on hosts/domains lists ==> faster
- Uses 2 (well, 3, but one is tiny) sed commands instead of looping grep ==> faster
- Relies on/installs default LEDE/DD packages required
- Just a single uci-dependent init script which is easier to hack (should someone want to)

I share your concern for additional package, but I believe that's enough difference from the user prospective to warrant one. While some of the things above can be added to your adblock, since it's fundamentally different I don't think all of them can. And I do apologize for the PR being all over the place with multiple commits -- first time and I got some limited time to work on it and see if it can make to the feed before 17.01 release, so I was in a bit of a hurry. :(

**Comment by chris5560** [comment]
@stangri

I didn't look into source and functionality. So no comments on this.
But I see a problem in providing base package AND luci-app inside packages tree.
I suggest to publish luci-app in openwrt/luci and the base package here at openwrt/packages.
Publishing luci-app inside openwrt/luci gives everybody the chance to create local language support for your application.

**Comment by stangri** [comment]
@chris5560 Thank you Christian, I was thrown off by presence of some other luci-app packages in this tree, but have now separated luci-app-simple-adblock.

**Comment by stangri** [comment]
Well, there're 3 or 4 mdns packages now, they all essentially do the same thing, why not have two adblock packages? ;)

**Pull request merged**
