### PR TITLE
travis_do.sh: Switch to mirror

### PR DESCRIPTION
**Pull request by diizzyy**
Offload the infrastructure by using a mirror and that's overall faster

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@champtar

**Comment by hnyman** [comment]
@diizzyy 
Isn't it better to use the project's own download server for the testing?
There aren't that many pull requests by day that the download amount would be much.

**Comment by diizzyy** [comment]
@hnyman 
My reasoning is that it's the primarily source for mirrors, most packages are pulled from the same host and being already slower than at least some of the mirrors it makes sense trying redirect as much traffic as possible. Preferably it would be better of we had some kind of load balancer in place but I'm not sure if opkg etc would like that.

**Comment by thess** [comment]
@diizzyy - I'm afraid I agree with @hnyman. There just isn't enough traffic to be worrying about this level of need (Fredkin's Paradox, etc.). It would be good idea however, to script backup mirrors in case the primary project repository is temporarily unavailable.

:-1:

**Comment by diizzyy** [comment]
Sure, let's bog it down even further than necessary....

**Pull request closed without merging**
