### PR TITLE
btrfs-progs: Update to 4.19

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: me
Compile tested: mvebu

### CODE REVIEW

**Comment by neheb** [comment]
This breaks on big endian MIPS because of some kind of linking error. No idea how to fix this.

**Comment by neheb** [comment]
Found the issue. This is ready.

**Comment by diizzyy** [comment]
Where does the patch originate from? Submitted upstream?

**Comment by neheb** [comment]
@diizzyy https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg81979.html

**Comment by diizzyy** [comment]
Great! Please mention such info.

**Comment by neheb** [comment]
Patches were sent after (or during) the pull request was updated. Will mention next time.

**Pull request merged**
