### PR TITLE
apinger: Update to latest git revision

### PR DESCRIPTION
**Pull request by neheb**
This project seems abandoned. Updated to latest version.

Also cleaned up the Makefile quite a bit.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @samm-git 
Compile tested: powerpc8540

### CODE REVIEW

**Comment by neheb** [comment]
It seems PKG_BUILD_PARALLEL is not correct. It causes occasional build failures like: https://downloads.openwrt.org/snapshots/faillogs/mipsel_74kc/packages/apinger/compile.txt

**Comment by samm-git** [comment]
Is there any real need to use latest git compared to latest release? I am using apinger in some of my projects and never had an issue with it

**Comment by neheb** [comment]
From a quick look, the only difference is that one of the patches was upstreamed.

The version parameter was not correct. It was using a git version anyway.

**Comment by samm-git** [comment]
So i am ok with that )

**Pull request merged**
