### PR TITLE
net/luci-app-*: move luci apps to luci repo

### PR DESCRIPTION
**Pull request by danrl**
Maintainer:
- @tohojo 
- Marko Ratkaj (github name unknown, pls add if you know)

Compile tested: x86_64
Run tested: there is nothing to run :)

Description:
This is a long-needed clean-up.
These applications are not gone! They live in the
luci repo now, where all their friends already are.

Signed-off-by: Dan Luedtke <mail@danrl.com>

### CODE REVIEW

**Comment by tohojo** [comment]
See comments on the related pull requests :)

**Comment by hnyman** [comment]
I merged the move of these four apps.

mwan3-luci should probably be moved, too.

@jow- might give @tohojo push access to the LuCI repo due to the BCP38 app. Maybe then the SQM app can be moved at some point ;-)

**Comment by danrl** [comment]
`mwan3-luci`: Didn't know about that one. I'll give it a try later. Thanks for merging!

**Comment by hnyman** [comment]
and we should likely cherry-pick the change for at least lede-17.01 branch, but I think that it should be done only after the 17.01.0 release. Let's not rock the boat now ;-)

Not sure about the old CC 15.05 branch for-15.05. Maybe not worthwhile.

**Comment by hnyman** [comment]
> mwan3-luci: Didn't know about that one.

Well, do a search for "luci" in Makefiles here and you will find several apps still left here...

https://github.com/openwrt/packages/search?l=Makefile&q=luci

acme, lxc, cshark, mwan3  (plus the sqm already discussed)

**Pull request merged**
