### PR TITLE
nginx: update nginx and brotli

### PR DESCRIPTION
**Pull request by tiagogaspar8**
Maintainer: Thomas Heil <heil@terminal-consulting.de>, Ansuel Smith <ansuelsmth@gmail.com>
Compile tested: Xiaomi AX3600 on the latest main
Run tested: Xiaomi AX3600 on the latest main

Description:
Update nginx to the latest version which brings mainly fixes to HTTP/3 (QUIC).

While at it update brotli to the latest version.

### CODE REVIEW

**Comment by 1715173329** [comment]
Cc maintainer @Ansuel

**Comment by tiagogaspar8** [comment]
I would also like to move nginx to pcre2, is it Ok if I add it to this pull request?

**Comment by Ansuel** [comment]
Nginx with pcre2 is problematic for the lua module. I have to check a few
thing

Il Dom 10 Set 2023, 18:29 Tiago Gaspar ***@***.***> ha
scritto:

**Comment by tiagogaspar8** [comment]
Ok, what about this pr? Can it get merged?

**Pull request merged**
