### PR TITLE
ddns-scripts: update to version 2.2.0-1

### PR DESCRIPTION
**Pull request by chris5560**
- added IPv4 100.64/10 (RFC 6598) and 169.254/16 (RFC 5735) to the range of default blocked IP's.
- added option "bind_network" to force GNU Wget or cURL to use specific network/interface for communication
- modified Makefile/Config.in to support to minimize package size
- added "domains.google.com" as IPv4 DDNS provider #822

Signed-off-by: Christian Schoenebeck <<christian.schoenebeck@gmail.com>>

### CODE REVIEW

**Comment by hnyman** [comment]
I think that you have not yet fixed the "extra \n" that are visible in system log.
https://github.com/chris5560/openwrt-packages/blob/master/net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_functions.sh#L1019
````
Sat Jan 31 17:50:48 2015 user.warn ddns-scripts[2605]: myddns_ipv4: PID '2605' exit WITH ERROR '1' at 2015-01-31 17:50\n
````
That \n is included in some write_log calls, but not in all.

If \n is needed for the separate log file /tmp/log/ddns/myddns_ipv4.log, you might add that \n when actually writing to that file inside write_log.

This is pure cosmetics, but I thought to remind you as you said in December that you would remove those in the next update. https://github.com/openwrt/packages/pull/608#commitcomment-8908356

**Comment by champtar** [comment]
hi @chris5560,
can you provide some ddns-scripts ipk size (with the various options)?
(i'm not sure this is worth it to have that much config option)

**Comment by chris5560** [comment]
hi @hnyman 
sorry I lost one line somewhere, added to this pull.

hi @champtar,
ls -l reports for the final ipk file:
80287 max inkl. all samples
79610 default settings
44646 without comments and samples
11116 without comments and provider scripts

**Comment by hnyman** [comment]
I hadn't realized that this package has grown so much in size.
In BB 14.07 the old ddns-scripts ipk is 7901 bytes for ar71xx
In trunk snapshots the size is 80122 bytes, over 10x that much.

ddns-scripts_1.0.0-23_all.ipk                   --   29-Sep-2014 08:54 --               7901
ddns-scripts_2.1.0-5_all.ipk                    --   31-Jan-2015 02:03 --              80122

It looks like e.g. the cloudflare feature (default =y) includes a listing of all top level domains globally... About 9900 lines of text. Is that really needed by default for all users of this package?

Similarly, the scripts contain quite much # comments in a quite verbose way. You are providing an option to remove those comments, but I think that actually the best would be to have shorter essential comments in the scripts by default, and then the long "manual" would be here in the sources (in a README file etc. that does not get installed into the final *.ipk) and/or in the wiki.

You might also consider splitting e.g. the cloudflare feature into a separate package (ddns-cloudflare) that would require this main package. Then it could be installed by those who need it.

**Comment by champtar** [comment]
i'm also in favour of package instead of build time config,
and a separated, not installed manual (when you are configuring ddns, you have internet access)

**Comment by chris5560** [comment]
Thanks for your ideas. Will do some rework and send new pull request the next days.

**Comment by hnyman** [comment]
I use this old pull request to give one additional comment:
If the ddns service is installed and the configuration is left at defaults, you typically get this error message in Luci in the overview page:
    Old version of ddns-scripts installed - install update here

I have the newest version of both ddns-scripts and luci app, but the detection logic seems to misdiagnose things.

````
root@OpenWrt:/etc/config# opkg list-installed | grep ddns
ddns-scripts - 2.1.0-5
luci-app-ddns - 2.1.1-0
root@OpenWrt:/etc/config# cat /etc/config/ddns
#
# Please read ddns.sample
# or http://wiki.openwrt.org/doc/uci/ddns
#
config ddns "global"
        option date_format "%F %R"
#       option run_dir "/var/run/ddns"
#       option log_dir "/var/log/ddns"
        option log_lines "250"
        option allow_local_ip "0"


config service "myddns_ipv4"
        option service_name     "example.org"
        option domain           "yourhost.example.com"
        option username         "your_username"
        option password         "your_password"
        option interface        "wan"
        option ip_source        "network"
        option ip_network       "wan"

config service "myddns_ipv6"
        option update_url       "http://[USERNAME]:[PASSWORD]@your.provider.net/nic/update?hostname=[DOMAIN]&myip=[IP]"
        option domain           "yourhost.example.com"
        option username         "your_username"
        option password         "your_password"
        option use_ipv6         "1"
        option interface        "wan6"
        option ip_source        "network"
        option ip_network       "wan6"

````

**Comment by chris5560** [comment]
Thanks for information.
There is a "timing" issue between javascript and lua that gives not back data. From the past there is detected if no data then show "software update needed".
luci-app-patch prepared but 1st I want to finish ddns-scripts changes and test together with luci-app patch.

**Pull request closed without merging**
