### PR TITLE
uwsgi: add package with modules (currently cgi and python plugin) [RFC]

### PR DESCRIPTION
**Pull request by peter-stadler**
Maintainer: Ansuel Smith <ansuelsmth@gmail.com>
Compile tested: MIPS 74K, Asus RT-N16, master snapshot
Run tested: MIPS 74K, Asus RT-N16, master snapshot, minimal app using uwsgi-python-plugin:
```
cat <<EOF >foobar.py
def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return [b"Hello World"]
EOF
uwsgi --plugin /usr/lib/uwsgi/python_plugin.so --http-socket 127.0.0.1:9031 --wsgi-file foobar.py &
wget http://127.0.0.1:9031/; rm index.html foobar.py; fg 
```

Description: This package is a modular build of uwsgi. 

It superseeds the uwsgi-cgi package by splitting off the syslog and the cgi plugin. So luci on nginx could use uwsgi-cgi-plugin instead of uwsgi-cgi, see my [other PR for nginx-luci and nginx-ssl-luci](https://github.com/openwrt/luci/pull/2981). 

Additional there is the python plugin that would be needed for etesync: See my [other PR for etesync-server](https://github.com/openwrt/packages/pull/9865), too, that will depend on uwsgi-python-plugin.

More plugins can be enabled if another package will use them.

**Edit:** Right now my other PRs refer to the old version, I will update them afterwards.

**Edit 2:** For now, include luci-support using the syslog plugin by default, and remove the uwsgi-cgi package entirely.

### CODE REVIEW

**Comment by peter-stadler** [comment]
I did update this PR to follow the changes of uwsgi-cgi. I will update the other two PRs later.

**Comment by peter-stadler** [comment]
(Fixed the dependencies for uwsgi-python3-plugin: it needs python3-light not python3-base.)

**Comment by peter-stadler** [comment]
Should I add a CONFLICTS:=uwsgi-cgi and how to make it clear that it would supersede it?

**Comment by peter-stadler** [comment]
(nothing changed)

**Comment by neheb** [comment]
ping @Ansuel

**Comment by Ansuel** [comment]
it's all good but we need to first update dependency of luci or we will create package with missing dependency. 
(luci on nginx depend on uwsgi-cgi and this commits renames it to uwsgi-plugins-cgi)

**Comment by Ansuel** [comment]
@peter-stadler i think this should be squashed and also add the drop of the uwsgi-cgi package

**Comment by Ansuel** [comment]
@peter-stadler by testing this i have this error 
unable to find logger syslog

so i think it should be compiled with syslog support by default ?

**Comment by peter-stadler** [comment]
The syslog plugin is installed by default, in the `define Package/uwsgi/install` there is
`$(INSTALL_BIN) $(PKG_BUILD_DIR)/syslog_plugin.so $(1)/usr/lib/uwsgi/`
But, it has to be loaded by `plugin = syslog` in the ini file.

Should the plugin be embedded in the binary `/usr/sbin/uwsgi`?

**Comment by Ansuel** [comment]
i think yes...

I don't know why but uwsgi complains if the emperor is loaded with no request plugin (with only the syslog plugin loaded) 

So yes, I think we should embed the plugin

**Comment by peter-stadler** [comment]
Squashed the comits and: 
* removed uwsgi-cgi package
* included luci-support
* embeded the syslog plugin into the uwsgi binary
But, the warning is still there: The emperor has no request plugin intentionally.

Do we need yaml (I did remove it for now)?

**Comment by Ansuel** [comment]
LGTM but we need to wait for the nginx commit to be ready

**Comment by peter-stadler** [comment]
Got rid of the warning by not using the syslog plugin at all, procd allows to log the output to stderr …
I made another commit for comparing it easily and would squash it if you think it would be a good idea.

**Comment by Ansuel** [comment]
Does logto option affect also output from the application itself ? 

This output would be usefull 

`uwsgi-emperor: luci: accepted login on / for root from 192.168.3.12`

**Comment by peter-stadler** [comment]
Yes, it effects it, I will look into a log-route.

**Comment by peter-stadler** [comment]
Should work now: All messages that contain "luci:" are logged in the webui vassal :-)

**Comment by Ansuel** [comment]
i notice that the package gets recompiled every time...

**Comment by peter-stadler** [comment]
Hmm, I am not sure that I understand you right: For me, it is recompiled iff it changed.

**Comment by Ansuel** [comment]
On my buildsystem with no changes if I recall package/uwsgi/compile it does
rerun the config phase

Il Mar 12 Nov 2019, 16:31 peter-stadler <notifications@github.com> ha
scritto:

**Comment by peter-stadler** [comment]
Cannot reproduce that. With the current version a second invocation of `make package/uwsgi/compile V=s` gives me the output:
```
WARNING: Makefile 'package/feeds/packages/nginx/Makefile' has a dependency on 'uwsgi-cgi', which does not exist
[...]
make[2]: Entering directory '$TOPDIR/packages/net/uwsgi'
echo "uwsgi" >> $TOPDIR/openwrt/staging_dir/target-mipsel_74kc_musl/pkginfo/uwsgi.default.install
echo "uwsgi-logfile-plugin" >> $TOPDIR/openwrt/staging_dir/target-mipsel_74kc_musl/pkginfo/uwsgi.default.install
echo "uwsgi-syslog-plugin" >> $TOPDIR/openwrt/staging_dir/target-mipsel_74kc_musl/pkginfo/uwsgi.default.install
echo "uwsgi-cgi-plugin" >> $TOPDIR/openwrt/staging_dir/target-mipsel_74kc_musl/pkginfo/uwsgi.default.install
echo "uwsgi-python3-plugin" >> $TOPDIR/openwrt/staging_dir/target-mipsel_74kc_musl/pkginfo/uwsgi.default.install
echo "uwsgi-cgi-luci-support" >> $TOPDIR/openwrt/staging_dir/target-mipsel_74kc_musl/pkginfo/uwsgi.default.install
make[2]: Leaving directory '$TOPDIR/packages/net/uwsgi'
time: package/feeds/packages/uwsgi/compile#0.16#0.06#0.34
make[1]: Leaving directory '$TOPDIR/openwrt'
```

**Comment by peter-stadler** [comment]
Tested it now quite a bit in RAM using a clean [SDK](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-ath79-generic_gcc-7.4.0_musl.Linux-x86_64.tar.xz) running `make package/uwsgi/compile -j1 V=sc`
1. time: all is build newly
2. time: something parts are rebuild, 1.3 MB log messages
3. time: nothing is rebuild, 18 KB log
4. time: nothing is rebuild, 18 KB log (the same as before beside the make times)

I am getting similar results for `make package/python3/compile -j1 V=sc` on the freshly uncompressed SDK.

**Comment by peter-stadler** [comment]
@Ansuel: I think I found it, had to add a `+` to `DEPENDS:=uwsgi`, sorry I overlooked that.

Since we are replacing `uwsgi-cgi`, should we call the plugin `uwsgi-cgi` instead of `uwsgi-cgi-plugin` then? So we can avoid changing the `DEPENDS:=+uwsgi-cgi` in the `Package/nginx-mod-luci/default` at the same time ...

**Comment by peter-stadler** [comment]
Hmm, tried it again now, it has the same behaviour as before ... I am not sure that I see something abnormal here since python3 alone behaves similarly as uwsgi. Could you test it again and point to me, where I could look?

**Comment by Ansuel** [comment]
@peter-stadler new on this? Can we merge this without breaking existing nginx and luci ? 
Think this is the best approach

**Comment by peter-stadler** [comment]
This could be merged if we change the `DEPENDS:=+uwsgi-cgi` in the `Package/nginx-mod-luci/default`, too. I will change the PR accordingly ...

**Comment by peter-stadler** [comment]
I cannot login, also in the upstream version: Nginx reports `403 Forbidden` after `luci: accepted login on / for root` ...

**Comment by Ansuel** [comment]
Does nginx run as root? Needed for ubus request

**Comment by peter-stadler** [comment]
The default is that only the master (not the worker) run as root. It does not help if I change the worker to run as root :-/

**Comment by peter-stadler** [comment]
The Nginx log is essentially:
```
POST /cgi-bin/luci -> 302 
GET /cgi-bin/luci/ -> 403
GET /cgi-bin/luci/admin/translations/en?v=git-19.363.83297-18c6096 -> 403
```

**Comment by peter-stadler** [comment]
Ok, I have the same problem on a clean install with luci only (default without Nginx) ...

**Comment by Ansuel** [comment]
So it's not caused but this and nginx

Il Mar 31 Dic 2019, 15:38 peter-stadler <notifications@github.com> ha
scritto:

**Comment by peter-stadler** [comment]
Yes, I suspect the problem lies somewhere in the changes for using ubus … Do you know how to debug and/or report it?

**Comment by peter-stadler** [comment]
Hmm, wait: It is working in a new browser session.

**Comment by Ansuel** [comment]
I notice that sometimes there is a problem with cacha... that block login to the ui...

**Comment by peter-stadler** [comment]
With a clean cache it hangs with the message `Session expired`. The relevant log lines are for Nginx that is hanging:
```
GET /ubus/?1577805288828 -> 400
POST /ubus/?1577805288966 -> 200
POST /ubus/?1577805288978 -> 200
```
And for uhttpd that is working (using Nginx to proxy_pass to uhttpd):
```
GET /ubus/?1577805659919 -> 404
POST /cgi-bin/luci/admin/ubus?1577805659971 -> 200
```

**Comment by Ansuel** [comment]
Did you test with a clean browser?

**Comment by peter-stadler** [comment]
Tested with a incognito/private browsing session in chrome/firefox and with a reboot of the virtual machine of the router (openwrt-x86-64-combined-ext4.img)

**Comment by peter-stadler** [comment]
I left out the static parts that are loaded in the same way in both cases.Tested it now also with a Guest window in Chrome -> The same.

**Comment by peter-stadler** [comment]
Hmm, did now a reinstall of the virtual machine and it is working.

**Comment by peter-stadler** [comment]
Nevermind, it was in an open browser window. After opening a new incognito window, I get the same error as before.

**Comment by peter-stadler** [comment]
So the Nginx version is working, when using the cached files of the uhttpd version and there is one more quirk on a clean install:
`opkg install luci && opkg install luci-nginx`
Then it works in a new incognito window; Nginx logs:
```
error.log: bind() to 0.0.0.0:80 failed (98: Address in use)
access.log: GET /cgi-bin/luci/ -> 403
access.log: … (static files)
error.log: "/www/ubus/index.html" is not found
access.log: GET /ubus/?1577805659919 -> 404
access.log: … (static files)
access.log: POST /cgi-bin/luci/admin/ubus?1577805659971 -> 200
```
It still works after opening a new incognito window; Nginx logs additionally:
```
access.log: GET /cgi-bin/luci/ -> 403
access.log: … (static files)
error.log: "/www/ubus/index.html" is not found
access.log: GET /ubus/?1577805659919 -> 404
access.log: … (static files)
access.log: POST /cgi-bin/luci/admin/ubus?1577805659971 -> 200
```
It fails when opening a new incognito window after _restarting_ Nginx; It adds the following lines to the access.log (nothing to the error.log):
```
GET /cgi-bin/luci/ -> 403
… (static files)
GET /ubus/?1577805288828 -> 400
… (static files)
POST /ubus/?1577805288966 -> 200
POST /ubus/?1577805288978 -> 200
```

**Comment by peter-stadler** [comment]
We could get a similar log by using `location /cgi-bin/luci/admin/ubus` in /etc/nginx/luci_uwsgi.conf The difference is then only in the size of the last response (to `POST /ubus/?1577805288966 -> 200`) it is 79 and should be 235. 

I will leave it for this year and wish you a good start into the new year.

**Comment by Ansuel** [comment]
> So the Nginx version is working, when using the cached files of the uhttpd version and there is one more quirk on a clean install:
> `opkg update && opkg install luci && opkg install luci-nginx`
> Then it works in a new incognito window; Nginx logs:
> 
> ```
> error.log: bind() to 0.0.0.0:80 failed (98: Address in use)
> access.log: GET /cgi-bin/luci/ -> 403
> access.log: … (static files)
> error.log: "/www/ubus/index.html" is not found
> access.log: GET /ubus/?1577805659919 -> 404
> access.log: … (static files)
> access.log: POST /cgi-bin/luci/admin/ubus?1577805659971 -> 200
> ```
> 
> It still works after opening a new incognito window; Nginx logs additionally:
> 
> ```
> access.log: GET /cgi-bin/luci/ -> 403
> access.log: … (static files)
> error.log: "/www/ubus/index.html" is not found
> access.log: GET /ubus/?1577805659919 -> 404
> access.log: … (static files)
> access.log: POST /cgi-bin/luci/admin/ubus?1577805659971 -> 200
> ```
> 
> It fails when opening a new incognito window after _restarting_ Nginx; It adds the following lines to the access.log (nothing to the error.log):
> 
> ```
> GET /cgi-bin/luci/ -> 403
> … (static files)
> GET /ubus/?1577805288828 -> 400
> … (static files)
> POST /ubus/?1577805288966 -> 200
> POST /ubus/?1577805288978 -> 200
> ```

i can't get where is the problem in the last log... 

the error 400 is intended (used by luci to check if /ubus can be used) 
/cgi-bin/luci/admin/ubus
/ubus use the uhttpd ubus integrated module or the nginx ubus integrated module

is just the lua page that use the ubus lua lib

**Comment by peter-stadler** [comment]
It hangs with the message `Session expired` in the browser window. The problem is not shown in the log, maybe if the ubus module in Nginx would be more verbose … Nevertheless it is working if we omit the whole `location /ubus` section :-)

**Comment by Ansuel** [comment]
I tested with latest commit and nginx + /ubus works correctly o.O

**Comment by Ansuel** [comment]
Anyway there is a dependency recursion problem... make the uwsgi package dependent of the sub package
(+uwsgi -> uwsgi)

**Comment by peter-stadler** [comment]
I still have the problem. Can you reproduce it?
1. Start [x86_64.img](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-combined-ext4.img.gz) in qemu:
```
#!/bin/sh

IMG="/home/pst/projects/openwrt-pst/openwrt-x86-64-combined-ext4.img"
QEMU="qemu-system-x86_64 -enable-kvm -nographic -m 1G -M q35 \
-drive file=$IMG,id=d0,if=none,bus=0,unit=0 -device ide-hd,drive=d0,bus=ide.0"
MSG="NB: The network needs a minute! tests: ifconfig; nslookup openwrt.org"
if [ $UID -gt 0 ] 
then
    echo To enable LAN and ssh from host run it as root: sudo $0
    $QEMU
else 
    echo Started as root, enabling LAN, connect to it via: ssh root@192.168.1.1
    echo $MSG
    LAN=openwrtx64tap0
    # create tap interface which will be connected to OpenWrt LAN NIC
    ip tuntap add mode tap $LAN && \
    ip link set dev $LAN up && \
    # configure interface with static ip to avoid overlapping routes                         
    ip addr add 192.168.1.123/24 dev $LAN && \
    $QEMU \
        -device virtio-net-pci,netdev=lan \
        -netdev tap,id=lan,ifname=$LAN,script=no,downscript=no \
        -device virtio-net-pci,netdev=wan \
        -netdev user,id=wan 
    # cleanup. delete tap interface created earlier
    ip addr flush dev $LAN
    ip link set dev $LAN down
    ip tuntap del mode tap dev $LAN
fi
```
2. Run `opkg update && opkg install luci-nginx && service nginx restart` in it.
3. Open a incognito window at `http://192.168.1.1/cgi-bin/luci/`
I get a message 'Session expired' that repeats when clicking on `To login...` (the same in Firefox).

**Comment by peter-stadler** [comment]
If I am using DEPENDS:=uwsgi instead of +uwsgi, then e.g. luci-nginx is not shown in make menuconfig ...

**Comment by peter-stadler** [comment]
I did fix the dependencies, changing also the DEPENDS for nginx-mod-luci/default. Thank you :-)

**Comment by Ansuel** [comment]
made a PR.  https://github.com/openwrt/packages/pull/10923 
This is ready to merge.

**Comment by peter-stadler** [comment]
Ah, I see. Sorry I forgot about that change. It is working.
I rebased this PR, tested it and consider it ready to merge :-)

**Comment by Ansuel** [comment]
mh can you remove the nginx changes ?

**Comment by peter-stadler** [comment]
Done that, I will make another small PR for Nginx.

**Comment by Ansuel** [comment]
do we really need that?

**Comment by peter-stadler** [comment]
I think else it will not be shown in make menuconfig. Or how should I change the uwsgi DEPENDS?

**Comment by peter-stadler** [comment]
The draft would be at #10925

**Comment by Ansuel** [comment]
Tested now and yes we need uwsgi in the nginx support package... as we need to change it anyway... At this point better make a mini pr also for nginx and rename the support package here to a better name. Sorry for all the mess.

After this and the mini pr get merged we can start working on nginx draft pr. Is it good for you?

**Comment by peter-stadler** [comment]
This is perfect :-)

**Comment by peter-stadler** [comment]
The above draft PR is a mini PR that can be merged after this one. I changed the name to uwsgi-luci-support ...

**Comment by peter-stadler** [comment]
I could also update the Nginx version later on if you think that would be better. And if you have another name for the uwsgi-luci-support I would change that, too ...

**Comment by Ansuel** [comment]
@hnyman good to merge
@peter-stadler convert this to a pr https://github.com/openwrt/packages/pull/10925 so it can be merged

**Pull request merged**
