### PR TITLE
libupnp: Update to 1.6.25

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @thess 
Compile tested: ipq806x

### CODE REVIEW

**Comment by thess** [comment]
-  I don't think removing PKG_FIXUP is a good idea here
- Mention addition of PKG_BUILD_PARALLEL in commit
- Good idea to remove OpenWrt copyright line

**Comment by neheb** [comment]
Why is removing FIXUP a bad idea?

**Comment by thess** [comment]
To quote our own doc:

> Some/many packages that think autotools is a good idea end up needing “fixes” to work around autotools “accidentally” knowing better and using host tools instead of the build environment tools. OpenWrt defines some PKG_FIXUP rules to help work around this.

In short - I don't trust the pre-generated ```configure```, etc. included in most source packages.

**Comment by neheb** [comment]
Fixed.

**Comment by thess** [comment]
Thanks...

**Pull request merged**
