### PR TITLE
p910nd: restart daemon even if no driver file is needed

### PR DESCRIPTION
**Pull request by systemcrash**
Not all USB printers need a blob loading; restart the daemon independently of driver loading.

Closes openwrt/packages#23588

Maintainer: me
Compile tested: 23.05.2 
Run tested: ath79

### CODE REVIEW

**Comment by BKPepe** [comment]
@loss-and-quick Could we get your ``Tested-by`` here, please?

**Comment by loss-and-quick** [comment]
> @loss-and-quick Could we get your `Tested-by` here, please?

Yeah

**Review by loss-and-quick — APPROVED** [review]
It is solving the issue

**Comment by systemcrash** [comment]
> > @loss-and-quick Could we get your `Tested-by` here, please?
> 
> Yeah, I tested this patch and the problem is now solved

I'm not certain but I think @BKPepe wants your full `Tested-by: Name <email@>` so I can add it to the commit.

**Comment by loss-and-quick** [comment]
> I'm not certain but I think @BKPepe wants your full `Tested-by: Name <email@>` so I can add it to the commit.

Huh, missunderstood
`Tested by`: minicx <minicx@disroot.org>

**Comment by systemcrash** [comment]
OK. Done.

**Comment by systemcrash** [comment]
Please merge - I can then fix a cherry pick PR
@BKPepe

**Pull request merged**
