### PR TITLE
mjpg-streamer: Update to latest version from github/jacksonliam repository.

### PR DESCRIPTION
**Pull request by thess**
Maintainer: me / @roger- 
Compile tested: AR71xx & IXP4xx
Run tested: OpenWrt root on WNDR4300/NSLU2

Description:

Add additional plugins for RTSP, UDP, etc.

Signed-off-by: Ted Hess <thess@kitschensync.net>

### CODE REVIEW

**Comment by roger-** [comment]
Thanks Tedd, looks good.  

Would be nice to get some of these patches merged upstream, but progress stalled: https://github.com/jacksonliam/mjpg-streamer/pull/55

**Comment by thess** [comment]
I think most of what is necessary is already merged into the @jacksonliam repo.

FWIW - I have been running his git version continuously on an Raspbian RPi3 using **input_uvc** (USB camera) for a number of months now without any issues.

**Comment by jacksonliam** [comment]
I couldn't merge all the patches because there were bits that didn't make sense or I had questions about the implementations which no-one answered. I guess the original patch submitters would be tricky to track down and probably wouldn't remember anyway!

I didn't see any changes that looked like it fixed anything serious in the patch set, but if you switch to my fork and users notice regressions I'd be happy to help getting them fixed.

**Comment by roger-** [comment]
Thanks @jacksonliam

@thess: perhaps some of the remaining patches that no one’s too clear on are unnecessary?

**Comment by thess** [comment]
Ready to merge
Please use 'repo issues' to report problems.

**Pull request merged**
