### PR TITLE
aria2: Fix aria2.init start issue

### PR DESCRIPTION
**Pull request by Narakuku**
Maintainer: me
Compile tested: (Linux MIPS, OpenWrt 21.02.1)
Run tested: (Linux MIPS, OpenWrt 21.02.1)

Description:
Merge from #18270

### CODE REVIEW

**Comment by Narakuku** [comment]
> why is this on 22.03?

Well, I found it on 21 and I can see noone has updated it on 22, is there a problem to have this change on 22?

**Comment by Narakuku** [comment]
Looks like I need to close this one and fix my “Signed-off-by” 😅

**Comment by neheb** [comment]
This is not a backport?

**Comment by Narakuku** [comment]
> This is not a backport?

It is a backporting, that’s why I thought someone needs to fix it on 22 as well, the flaw is in the init script.
Or perhaps I have misunderstood, once master branch is merged, 22 will be fixed automatically?

**Comment by ysonmezer** [comment]
Hi,
i am amateur user
how to use your fix in openwrt
please explain

**Comment by Narakuku** [comment]
@ysonmezer 
Go to the /etc/init.d/aria2 
Change this line

> procd_add_jail_mount "$config_file"

To

> procd_add_jail_mount "$ca_certificate" "$certificate" "$rpc_certificate" "$rpc_private_key"

**Comment by ysonmezer** [comment]
Thanks a lot for your quick reply. I'm trying right away

**Comment by ysonmezer** [comment]
you are big. thank you very much. worked

**Comment by neheb** [comment]
@Narakuku the way the workflow works is: X gets merged to master. X then gets cherry picked(git cherry-pick -x) to one of the other branches.

**Comment by ysonmezer** [comment]
thank you

**Comment by Narakuku** [comment]
> @Narakuku the way the workflow works is: X gets merged to master. X then gets cherry picked(git cherry-pick -x) to one of the other branches.

Thanks for explaining, never gets to understand it before. 👍

**Comment by ysonmezer** [comment]
I've been tiring you out, but now I've run into another problem.
I get a log message talking about granting write permission for user aria2
Sun Sep 11 23:03:14 2022 daemon.info aria2: Aria2 will run with user 'aria2'.
Sun Sep 11 23:03:14 2022 daemon.info aria2: Please make sure user 'aria2' has write access to download dir: /mnt/sda1/!!!YeniGelen
Sun Sep 11 23:03:14 2022 daemon.info aria2c[2261]: jail: jail (2404) exited with exit: 7
Sun Sep 11 23:03:14 2022 daemon.info aria2c[3116]: jail: exec-ing /usr/bin/aria2c

**Comment by Narakuku** [comment]
@ysonmezer 
chmod 777 /mnt/sda1/YeniGelen

**Comment by ysonmezer** [comment]
Thank you.

**Comment by stangri** [comment]
@Narakuku like @neheb explained, you need to send this PR for the master branch and then it can be cherry-picked for release.

**Comment by Narakuku** [comment]
> @Narakuku like @neheb explained, you need to send this PR for the master branch and then it can be cherry-picked for release.

#18270 

Hello I already did it a long time ago, but I can see it is still not merged/cherry-picked to 22. 👆

**Comment by stangri** [comment]
@Narakuku thank you, I've picked these changes up for 22.03 in https://github.com/openwrt/packages/pull/19350, I'll merge it when the Ci is done runing the checks.

**Comment by chinattw** [comment]
> @ysonmezer Go to the /etc/init.d/aria2 Change this line
> 
> > procd_add_jail_mount "$config_file"
> 
> To
> 
> > procd_add_jail_mount "$ca_certificate" "$certificate" "$rpc_certificate" "$rpc_private_key"

---------------------------------
is ok, thanks

**Pull request merged**
