### PR TITLE
net/dansguardian: Remove from tree

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @lperkov 
Compile tested: N/A
Run tested: N/A

Description:
Dansguardian hasn't seen a release in over 5 years and been deprecated
upstream. We're just doing a disservice providing software that isn't
supported. If functionality is needed please use e2guardian instead (in tree).

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@lperkov 
ping?

**Comment by diizzyy** [comment]
@champtar @hnyman 
Can we drop this?

**Comment by champtar** [comment]
Hi @diizzyy 

I'm in favor of dropping `dansguardian` as `e2guardian` is in tree (but not up to date :( ), but I would really like @lperkov to give his ack first

**Comment by diizzyy** [comment]
@champtar 
I honestly think we're well beyond reasonable time for reply and should just go ahead. As stated before, we're not doing anyone any favours...

**Comment by champtar** [comment]
Worst case we can add it back

**Pull request merged**
