### PR TITLE
vim: Add host build to install xxd

### PR DESCRIPTION
**Pull request by neheb**
Packages such as ttyd and device-observatory need this.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ratkaj 
Compile tested: ramips, mvebu Ubuntu 18.04
Run tested: N/A

Description:
https://downloads.openwrt.org/snapshots/faillogs/i386_pentium4/packages/device-observatory/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/i386_pentium4/packages/ttyd/compile.txt

Reproducible locally by deleting xxd.

### CODE REVIEW

**Comment by neheb** [comment]
ping @mwarning @tsl0922

**Comment by neheb** [comment]
Simplified the fix.

Note: STAGING_DIR_HOSTPKG/usr is a wrong path to use when installing packages.

**Comment by mwarning** [comment]
@neheb awesome, I had my own try at this problem yesterday even, but did not succeed.

**Comment by BKPepe** [comment]
Can we cherry-pick it to OpenWrt 18.06?
The issue is [still there](https://downloads.openwrt.org/releases/faillogs-18.06/mipsel_24kc/packages/ttyd/compile.txt) present and I have noticed [this thread](https://forum.openwrt.org/t/ttyd-not-found-in-list-of-packages/43218) on OpenWrt forum

**Comment by rinaldi6109** [comment]
> 
> 
> Can we cherry-pick it to OpenWrt 18.06?
> The issue is [still there](https://downloads.openwrt.org/releases/faillogs-18.06/mipsel_24kc/packages/ttyd/compile.txt) present and I have noticed [this thread](https://forum.openwrt.org/t/ttyd-not-found-in-list-of-packages/43218) on OpenWrt forum

I also ask this.

**Comment by neheb** [comment]
I'm in favor.

**Comment by cotequeiroz** [comment]
OK, #9821 should do it.

**Pull request merged**
