### PR TITLE
gsocket: upstream update to 1.4.39

### PR DESCRIPTION
**Pull request by SkyperTHC**
Signed-off-by: Ralf Kaiser <skyper@thc.org>

Maintainer: Ralf Kaiser @SkyperTHC
Compile tested: mips_24kc, Openwrt 22.03.0-rc4
Run tested: mips_24kc

Description:
  Global Socket allows two workstations on different private networks to
  communicate with each other. Through firewalls and through NAT - like
  there is no firewall.

  The TCP connection is secured with AES-256 and using OpenSSL's SRP
  protocol (RFC 5054). It does not require a PKI and has forward
  secrecy and (optional) TOR support.

  The gsocket tools derive temporary session keys and IDs and connect
  two TCP pipes through the Global Socket Relay Network (GSRN). This is
  done regardless and independent of the local IP Address or geographical
  location.

  The session keys (secrets) never leave the workstation. The GSRN sees only
  the encrypted traffic.

  The workhorse is 'gs-netcat' which opens a ssh-like interactive PTY
  command shell to a remote workstation (which resides on a private and
  remote network and/or behind a firewall).

### CODE REVIEW

**Comment by feckert** [comment]
Please remove the merge commit in your pullrequest. https://github.com/openwrt/packages/pull/20089/commits/ca7c702bdc2fc8e5152f48e3dbea7df35acbcbef

**Comment by SkyperTHC** [comment]
Hello,

I dont know how to do that. Can you tell me what command you like me to run
or if there is an easy button on Github.com to do what you want?

skyper

**Comment by 1715173329** [comment]
git fetch https://github.com/openwrt/packages master
git rebase FETCH_HEAD

**Comment by SkyperTHC** [comment]
git fetch https://github.com/openwrt/packages master
From https://github.com/openwrt/packages
 * branch                master     -> FETCH_HEAD

git rebase FETCH_HEAD
Auto-merging net/gsocket/Makefile
CONFLICT (add/add): Merge conflict in net/gsocket/Makefile
error: could not apply 93ed644d8... gsocket: upstream update to 1.4.39
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git
rebase --abort".
Could not apply 93ed644d8... gsocket: upstream update to 1.4.39

(HERE: Resolved the merge conflict manually. Then followed git's
recommendations.).

git rebase FETCH_HEAD
fatal: It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
        git rebase (--continue | --abort | --skip)
If that is not the case, please
        rm -fr ".git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

 git rebase --continue

[detached HEAD 0cf8d20bf] gsocket: upstream update to 1.4.39
 1 file changed, 3 insertions(+), 2 deletions(-)
Successfully rebased and updated refs/heads/master.

git push
To github.com:SkyperTHC/packages.git
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'github.com:SkyperTHC/packages.git'
hint: You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.

 git pull
From github.com:SkyperTHC/packages
   93ed644d8..ca7c702bd  master     -> origin/master

git push
To github.com:SkyperTHC/packages.git
   ca7c702bd..4244c7b21  master -> master

**Comment by 1715173329** [comment]
You need redo your work based on the current master tree.

git fetch https://github.com/openwrt/packages master
git reset --hard FETCH_HEAD

Then apply your update to the Makefile and commit it.

Read https://git-scm.com/docs

**Comment by neheb** [comment]
Needs a rebase.

**Comment by BKPepe** [comment]
Rebased.

**Pull request merged**
