### PR TITLE
zabbix: Bump to latest version

### PR DESCRIPTION
**Pull request by Rixerx**
This upgrade zabbix to the newest version. Changing SQLite for PostgreSQL, because of dropping SQLite support for server/frontend.
More info:https://www.zabbix.com/documentation/3.4/manual/installation/upgrade_notes_340#dropping_sqlite_support_for_serverfrontend
In addition added required dependencies.
More info:https://www.zabbix.com/documentation/3.4/manual/installation/requirements

Signed-off-by: Krystian Kozak <krystian.kozak20@gmail.com>

Maintainer: @champtar 

Compile tested: (brcm2708, Raspberry Pi 3 model B, OpenWrt r7088-0777a3e773)
Run tested: (brcm2708, Raspberry Pi 3 model B, OpenWrt r7088-0777a3e773)

### CODE REVIEW

**Comment by champtar** [comment]
Hi @Rixerx 
Are you using the server/proxy/frontend part on OpenWrt?
I'm not, and I wonder if anyone is ...

**Comment by Rixerx** [comment]
Probably you are right. But in the near future this may change due to better components. Maybe someone on the x86 platform uses the server/proxy/frontend part.

**Comment by hnyman** [comment]
@champtar 
ok with you now?

**Comment by champtar** [comment]
@Rixerx I trust you fully

**Pull request merged**
