### PR TITLE
transmission: update to version 4.0.1

### PR DESCRIPTION
**Pull request by dangowrt**
Maintainer: me
Compile tested: arm_cortex-a7+neon-vfpv4
Run tested: arm_cortex-a7+neon-vfpv4 (mediatek/mt7623, bananapi-r2)

Description:
Update transmission to new major release 4.0.1 which switches to CMake-based build.
Add 3rd-party libraries to avoid embedding (which also simply doesn't work and breaks the build).

### CODE REVIEW

**Comment by zdz2019** [comment]
Attempt to compile fails.

/home/test/mt7621/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/libevent-2.1.so && :
/home/test/mt7621/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: warning: libiconv.so.2, needed by /home/test/mt7621/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/libpsl.so, not found (try using -rpath or -rpath-link)
/home/test/mt7621/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: warning: libintl.so.8, needed by /home/test/mt7621/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib/libidn2.so.0, not found (try using -rpath or -rpath-link)

**Comment by neheb** [comment]
NLS.mk is needed, yes

**Comment by zdz2019** [comment]
> NLS.mk is needed, yes

After the modification, the compilation is successful, but it cannot run normally, and the x86 test is also unable to run.

get these log errors: 
user.notice transmission: Starting with 4040322000 virt mem
daemon.info transmission-daemon[10354]: jail: exec-ing /usr/bin/transmission-daemon
daemon.info transmission-daemon[10354]: jail: jail (10357) exited with signal: 31

**Comment by dangowrt** [comment]
@zdz2019 Please share you configuration so I can try to reproduce why it doesn't work for you. I've tried 32-bit ARM and x86_64, both now work fine for me, but obviously depends a lot on configuration. I assume Transmission 3.00 works fine for you with the same configuration, right?

**Comment by zdz2019** [comment]
> @zdz2019 Please share you configuration so I can try to reproduce why it doesn't work for you. I've tried 32-bit ARM and x86_64, both now work fine for me, but obviously depends a lot on configuration. I assume Transmission 3.00 works fine for you with the same configuration, right?

Sorry! I forgot to switch the branch, used the 21.02 branch.

**Comment by Gingernut1978** [comment]
@dangowrt 

Had transmission from master working without issues. After updating to your pr I get a t404 ransmission web not found.

I didn't change any config going from master to pr

image

**Comment by dangowrt** [comment]
@Gingernut197 Thank you for trying and reporting this problem!
This is because the web root directory has changes from `/usr/share/transmission/web` to `/usr/share/transmission/public_html` and I forgot to reflect that change in the init script. Should be fixed now.

**Comment by Gingernut1978** [comment]
@dangowrt Working perfect, thanks.

Compile tested: aarch64_cortex-a53
Run tested: aarch64_cortex-a53 (Mediatek-mt7622, Totolink A8000RU)

**Pull request merged**
