### PR TITLE
[21.02] fail2ban: initial package and fix

### PR DESCRIPTION
**Pull request by erdoukki**
fail2ban v0.11.2 package for OpenWrt 21.02

Maintainer: Kerma Gérald / @erdoukki / gandalf@gk2.net
Compile tested: (aarch64_cortex-a53, espressobin board, OpenWrt master/19.07/21.02)
Run tested: (aarch64_cortex-a53, espressobin board, OpenWrt master/19.07/21.02)

Description:
fail2ban: initial package and fix for 21.02 cherry-picked

https://github.com/openwrt/packages/pull/15098 (e267803346aad6fd1ab3e8d02f2ee0d97748fc7a)
https://github.com/openwrt/packages/pull/16554 (a4f24a353e540c111b0139c72866f6382fb6b581)

@jefferyto @neheb

### CODE REVIEW

**Comment by champtar** [comment]
When cherry-picking, can you use `git cherry-pick -x` ?

**Comment by erdoukki** [comment]
Sure !
It is my first attempt...
Do you need I made a new PR with ?

**Comment by erdoukki** [comment]
> When cherry-picking, can you use `git cherry-pick -x` ?

Done, thanks...

**Comment by champtar** [comment]
Perfect, thanks!
just waiting for CI and merging

**Comment by erdoukki** [comment]
Thanks

**Pull request merged**
