### PR TITLE
expat: update to 2.5.0

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @thess

### CODE REVIEW

**Comment by diizzyy** [comment]
Release tarball is also offered on GitHub
https://github.com/libexpat/libexpat/releases/tag/R_2_5_0

**Comment by neheb** [comment]
Nasty part here is the URL is https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.xz

need to find some way to underscorify the version number.

**Comment by 1715173329** [comment]
`$(subst .,_,$(PKG_VERSION))` should be okay.

**Comment by neheb** [comment]
The standard is to use tarballs when possible. git tarballs whether GitHub or OpenWrt ones have historically had issues with changing hashes.

**Comment by 1715173329** [comment]
> The standard is to use tarballs when possible.

Got it.

> git tarballs whether GitHub or OpenWrt ones have historically had issues with changing hashes.

Hummm... But this package uses sourceforge releases?

**Comment by neheb** [comment]
Right. The tarball @diizzyy mentioned is the same one as the sourceforge one. The goal is to have mirrors in case sourceforge is not available.

**Comment by 1715173329** [comment]
Okay I understood, thanks!
`subst` should be fine in this case.

**Comment by BKPepe** [comment]
In your commit description, you should mention that you added a mirror otherwise, you are doing more changes than necessary. Also, it would help if you mentioned [CVE fix](https://www.xml.com/news/2022-10-expat-250/) in the commit description.

**Pull request merged**
