### PR TITLE
dovecot: update to 2.3.1

### PR DESCRIPTION
**Pull request by MikePetullo**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64, master 4fdc6ca3
Run tested: x86_64, master 4fdc6ca3

Description:
dovecot: update to 2.3.1

### CODE REVIEW

**Comment by hnyman** [comment]
@lucize seems to be listed as the maintainer. 
You might add yourself @MikePetullo as the second maintainer to package.

**Comment by diizzyy** [comment]
Switch to https for tarball download?

**Comment by MikePetullo** [comment]
I just modified the Makefile to use HTTPS.

**Comment by hnyman** [comment]
@MikePetullo 

Buildbot finds libsodium. You may need disable its detection in package configuration.


http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/dovecot/compile.txt

```
Package dovecot is missing dependencies for the following libraries:
libsodium.so.23
Makefile:154: recipe for target '/var/lib/buildbot/slaves/weimar/mips_24kc/build/sdk/bin/packages/mips_24kc/packages/dovecot_2.3.1-1_mips_24kc.ipk' failed
```

http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a15_neon-vfpv4/packages/dovecot/compile.txt

**Comment by lucize** [comment]
sorry for late input, I didn't wanted to bump the version until 2.3.2 because libsodium was specified not to work and also didn't had time to test

**Comment by MikePetullo** [comment]
See pull #6303.

**Pull request merged**
