### PR TITLE
ksmbd-tools: update to 3.4.4

### PR DESCRIPTION
**Pull request by Dr-Escher**
match kmod version

### CODE REVIEW

**Review by BKPepe — CHANGES_REQUESTED** [review]
There is missing your's Signed-off-by. There is no indicated that this commit was cherry-picked from newer branches. For that, you can use ``git cherry-pick -x hash`` or add on your own to the commit message.

**Comment by 1715173329** [comment]
Why? See commit fbcaa8bce87f3a45605b80aae0024f9d68388e4f.

**Comment by BKPepe** [comment]
In that case, closing.

**Comment by 1715173329** [comment]
@BKPepe Looks like there's something not right. See #18303, maybe @neheb made it wrong?
(I'm not really using this package.)

**Comment by 1715173329** [comment]
@BKPepe #18303 maybe there's something wrong?
(btw I'm not really using this package.)

**Comment by Dr-Escher** [comment]
> @BKPepe #18303 maybe there's something wrong? (btw I'm not really using this package.)

Yes, please see https://github.com/openwrt/openwrt/issues/9639#issuecomment-1106182954

**Pull request closed without merging**
