### PR TITLE
Migrate pyload, ossp-js, tesseract and leptonica to new packages feed

### PR DESCRIPTION
**Pull request by currywurst76**
Migrate
 * net/pyload
 * libs/ossp-js
 * libs/leptonica
 * utils/tesseract

### CODE REVIEW

**Comment by thess** [comment]
@currywurst76 - Overall these look good (I haven't tested them yet).

A couple of minor changes are needed (please amend)
* Each commit message should be prefixed with the package name (required for all commits)
* Not all your commits have __signed-off-by__  (also mandatory)
* PKG_LICENSE & PKG_LICENSE_FILES tags in Makefile required.

**Comment by currywurst76** [comment]
No idea how to add the signed-off-by to the other commits. Also it's unclear for me what to pug into PKG_LICENSE & PKG_LICENSE_FILES.

**Comment by sbyx** [comment]
@currywurst76:
See here for all the details including list of licenses etc. https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
PKG_LICENSE_FILES should be optional but its simply the name of the license file (e.g. LICENSE or COPYING) in the source-archive.

As for changing the commit titles (adding package-names) and adding sign-off by you can use: git rebase -i

**Comment by currywurst76** [comment]
I'm working on it

**Comment by currywurst76** [comment]
I'll try again.

**Pull request closed without merging**
