### PR TITLE
fontconfig: update to 2.13.94

### PR DESCRIPTION
**Pull request by neheb**
Remove upstreamed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer:
Compile tested: ath79

### CODE REVIEW

**Comment by hnyman** [comment]
Fontconfig fails for me with ipq806x/R7800 after this PR has been merged.
Reverting this PR makes the compilation to succeed again. 

Build log with fault:
```
perus@ub2104:/Openwrt/r7800$ cat logs/package/feeds/packages/fontconfig/compile.txt 
The Meson build system
Version: 0.59.1
Source dir: /Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94
Build dir: /Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/openwrt-build
Build type: cross build
WARNING: Unknown options: "build.libdir, build.prefix, build.sbindir"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: fontconfig
Project version: 2.13.94
C compiler for the host machine: arm-openwrt-linux-muslgnueabi-gcc (gcc 11.2.0 "arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 11.2.0 r17566-96e05e2e36) 11.2.0")
C linker for the host machine: arm-openwrt-linux-muslgnueabi-gcc ld.bfd 2.37
C compiler for the build machine: gcc (gcc 10.3.0 "gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0")
C linker for the build machine: gcc ld.bfd 2.36.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: generic
Target machine cpu family: arm
Target machine cpu: generic
Found pkg-config: /Openwrt/r7800/staging_dir/host/bin/pkg-config (1.8.0)
Run-time dependency freetype2 found: YES 24.0.18
Run-time dependency expat found: YES 2.4.1
Program python3 found: YES (/Openwrt/r7800/staging_dir/host/bin/python)
Has header "dirent.h" : YES 
Has header "fcntl.h" : YES 
Has header "stdlib.h" : YES 
Has header "string.h" : YES 
Has header "unistd.h" : YES 
Has header "sys/statvfs.h" : YES 
Has header "sys/vfs.h" : YES 
Has header "sys/statfs.h" : YES 
Has header "sys/param.h" : YES 
Has header "sys/mount.h" : YES 
Checking for function "link" : YES 
Checking for function "mkstemp" : YES 
Checking for function "mkostemp" : YES 
Checking for function "_mktemp_s" : NO 
Checking for function "mkdtemp" : YES 
Checking for function "getopt" : YES 
Checking for function "getopt_long" : YES 
Checking for function "getprogname" : NO 
Checking for function "getexecname" : NO 
Checking for function "rand" : YES 
Checking for function "random" : YES 
Checking for function "lrand48" : YES 
Checking for function "random_r" : NO 
Checking for function "rand_r" : YES 
Checking for function "readlink" : YES 
Checking for function "fstatvfs" : YES 
Checking for function "fstatfs" : YES 
Checking for function "lstat" : YES 
Checking for function "mmap" : YES 
Checking for function "vprintf" : YES 
Checking for function "FT_Get_BDF_Property" with dependency freetype2: YES 
Checking for function "FT_Get_PS_Font_Info" with dependency freetype2: YES 
Checking for function "FT_Has_PS_Glyph_Names" with dependency freetype2: YES 
Checking for function "FT_Get_X11_Font_Format" with dependency freetype2: YES 
Checking for function "FT_Done_MM_Var" with dependency freetype2: YES 
Header <fcntl.h> has symbol "posix_fadvise" : YES 
Checking whether type "struct statvfs" has member "f_basetype" : NO 
Checking whether type "struct statvfs" has member "f_fstypename" : NO 
Checking whether type "struct statfs" has member "f_flags" : NO 
Checking whether type "struct statfs" has member "f_fstypename" : NO 
Checking whether type "struct dirent" has member "d_type" : YES 
Checking for size of "void *" : 4
Checking for alignment of "void *" : 4
Checking for alignment of "double" : 8
Checking if "Intel atomics" links: YES 
Checking if "Solaris atomic ops" links: NO 
Run-time dependency threads found: YES
Program gperf found: YES (/Openwrt/r7800/staging_dir/hostpkg/bin/gperf)
Program sh found: YES (/usr/bin/sh)
WARNING: Project targeting '>= 0.56.0' but tried to use feature deprecated since '0.55.0': ExternalProgram.path. use ExternalProgram.full_path() instead
Message: gperf len type is size_t
Checking for type "uint64_t" : YES 
Checking for type "int32_t" : YES 
Checking for type "uintptr_t" : YES 
Checking for type "intptr_t" : YES 
Program fc-case.py found: YES (/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/fc-case/fc-case.py)
Program fc-lang.py found: YES (/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/fc-lang/fc-lang.py)
Program link_confs.py found: YES (/Openwrt/r7800/staging_dir/host/bin/python /Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/conf.d/link_confs.py)
Program write-35-lang-normalize-conf.py found: YES (/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/conf.d/write-35-lang-normalize-conf.py)
Configuring README using configuration
Program xgettext skipped: feature nls disabled
Configuring config.h using configuration
Configuring fonts.conf using configuration
WARNING: Project targeting '>= 0.53' but tried to use feature introduced in '0.54.0': list_sep arg in summary.
Build targets in project: 17
WARNING: Project specifies a minimum meson_version '>= 0.56.0' but uses features which were added in newer versions:
 * 0.54.0: {'list_sep arg in summary'}
WARNING: Deprecated features used:
 * 0.55.0: {'ExternalProgram.path'}

fontconfig 2.13.94

  General
    Documentation: NO
    NLS          : NO
    Tests        : NO
    Tools        : YES

Option buildtype is: plain [default: debugoptimized]
Found ninja-1.10.2 at /Openwrt/r7800/staging_dir/host/bin/ninja
ninja: Entering directory `/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/openwrt-build'
[1/55] Generating fccase.h with a custom command
[2/55] Generating alias_headers with a custom command
[3/55] Generating ft_alias_headers with a custom command
[4/55] Generating 35-lang-normalize.conf with a custom command
[5/55] Generating fcobjshash.gperf with a custom command
[6/55] Generating fcobjshash.h with a custom command
[7/55] Compiling C object fc-cat/fc-cat.p/fc-cat.c.o
[8/55] Compiling C object fc-cache/fc-cache.p/fc-cache.c.o
[9/55] Compiling C object fc-conflist/fc-conflist.p/fc-conflist.c.o
[10/55] Compiling C object fc-list/fc-list.p/fc-list.c.o
[11/55] Compiling C object fc-match/fc-match.p/fc-match.c.o
[12/55] Compiling C object fc-query/fc-query.p/fc-query.c.o
[13/55] Compiling C object fc-pattern/fc-pattern.p/fc-pattern.c.o
[14/55] Compiling C object fc-scan/fc-scan.p/fc-scan.c.o
[15/55] Compiling C object fc-validate/fc-validate.p/fc-validate.c.o
[16/55] Generating fclang.h with a custom command
[17/55] Compiling C object src/libfontconfig.so.1.12.0.p/fccompat.c.o
[18/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcatomic.c.o
[19/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcdir.c.o
[20/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcdefault.c.o
[21/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcformat.c.o
[22/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcdbg.c.o
[23/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcfs.c.o
[24/55] Compiling C object src/libfontconfig.so.1.12.0.p/fccharset.c.o
[25/55] Compiling C object src/libfontconfig.so.1.12.0.p/fccache.c.o
[26/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcptrlist.c.o
[27/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcfreetype.c.o
[28/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcmatrix.c.o
[29/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcinit.c.o
[30/55] Compiling C object src/libfontconfig.so.1.12.0.p/fchash.c.o
[31/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcrange.c.o
[32/55] Compiling C object src/libfontconfig.so.1.12.0.p/fclist.c.o
[33/55] Compiling C object src/libfontconfig.so.1.12.0.p/fccfg.c.o
[34/55] Compiling C object src/libfontconfig.so.1.12.0.p/fclang.c.o
[35/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcobjs.c.o
FAILED: src/libfontconfig.so.1.12.0.p/fcobjs.c.o 
arm-openwrt-linux-muslgnueabi-gcc -Isrc/libfontconfig.so.1.12.0.p -Isrc -I../src -I. -I.. -Ifc-lang -Ifc-case -I/Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/freetype2 -I/Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include -I/Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/libpng16 -I/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.2.0_musl_eabi/usr/include -I/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.2.0_musl_eabi/include/fortify -I/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.2.0_musl_eabi/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -DHAVE_CONFIG_H -Os -pipe -g3 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94=fontconfig-2.13.94 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -pthread -MD -MQ src/libfontconfig.so.1.12.0.p/fcobjs.c.o -MF src/libfontconfig.so.1.12.0.p/fcobjs.c.o.d -o src/libfontconfig.so.1.12.0.p/fcobjs.c.o -c ../src/fcobjs.c
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:1: warning: "__STDC__" redefined
    1 | #define __STDC__ 1
      | 
<built-in>: note: this is the location of the previous definition
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:2: warning: "__STDC_VERSION__" redefined
    2 | #define __STDC_VERSION__ 201710L
      | 
<built-in>: note: this is the location of the previous definition
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:3: warning: "__STDC_UTF_16__" redefined
    3 | #define __STDC_UTF_16__ 1
      | 
<built-in>: note: this is the location of the previous definition
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:4: warning: "__STDC_UTF_32__" redefined
    4 | #define __STDC_UTF_32__ 1
      | 
<built-in>: note: this is the location of the previous definition
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:5: warning: "__STDC_HOSTED__" redefined
    5 | #define __STDC_HOSTED__ 1
      | 
<built-in>: note: this is the location of the previous definition
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:468: warning: "__STDC_ISO_10646__" redefined
  468 | #define __STDC_ISO_10646__ 201206L
      | 
In file included from <command-line>:
/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.2.0_musl_eabi/include/stdc-predef.h:4: note: this is the location of the previous definition
    4 | #define __STDC_ISO_10646__ 201206L
      | 
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:469: warning: "__STDC_IEC_559__" redefined
  469 | #define __STDC_IEC_559__ 1
      | 
In file included from <command-line>:
/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.2.0_musl_eabi/include/stdc-predef.h:7: note: this is the location of the previous definition
    7 | #define __STDC_IEC_559__ 1
      | 
In file included from ../src/fcobjs.c:33:
src/fcobjshash.gperf:642:7: error: stray '#' in program
src/fcobjshash.gperf:1:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before numeric constant
    1 | #define __STDC__ 1
      |                  ^
src/fcobjshash.gperf:642:15: note: in expansion of macro '__STDC__'
src/fcobjshash.gperf:654:16: error: stray '#' in program
../src/fcobjs.c:31:1: warning: 'FcObjectTypeLookup' used but never defined
   31 | FcObjectTypeLookup (register const char *str, register FC_GPERF_SIZE_T len);
      | ^~~~~~~~~~~~~~~~~~
[36/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcweight.c.o
[37/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcmatch.c.o
[38/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcname.c.o
[39/55] Compiling C object src/libfontconfig.so.1.12.0.p/fcpat.c.o
ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:69: /Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/fontconfig-2.13.94/.built] Error 1
time: package/feeds/packages/fontconfig/compile#7.03#1.16#4.09
```

**Comment by neheb** [comment]
src/fcobjshash.gperf:642

What surrounds that?

**Comment by hnyman** [comment]
Surrounds where? 

This seems to be meson/ninja build, and detailed logs and build intermediates seems to be no openwrt-build/ dir?
(I have never debugged ninja builds)

Below that dir is a new "src" where also fcobjshash.gperf is located, but is has only 540 lines...

I will send the logs to you by mail.

**Comment by neheb** [comment]
the actual file.

**Comment by hnyman** [comment]
I sent you the whole failing fontconfig build_dir by email, so that you can look at it more easily. There both the source and the build intermediates.

I am not familiar with meson/ninja debugging, but as far as I can see, the "src/fcobjshash.gperf" is some kind of meson/ninja build intermediate artefact inside "openwrt-build/src".

In the normal src/ there is only a short fcobjs.c and fcobjs.h
Line 33 includes fcobjhash.h, but that file is really short.

in meson.build there is a recipe:

fcobjshash_gperf = custom_target('fcobjshash.gperf',
  input: 'fcobjshash.gperf.h',
  output: 'fcobjshash.gperf',
  command: [python3, files('cutout.py')[0], '@INPUT@', '@OUTPUT@', '@BUILD_ROOT@', cpp],
  build_by_default: true,
)

fcobjshash_h = custom_target('fcobjshash.h',
  input: fcobjshash_gperf,
  output: 'fcobjshash.h',
  command: [gperf, '--pic', '-m', '100', '@INPUT@', '--output-file', '@OUTPUT@']
)

**Comment by neheb** [comment]
sure. can you find that file and send it?

**Comment by hnyman** [comment]
I sent it to your gmail already yesterday. 

Just sent the tar.gz again.

**Comment by hnyman** [comment]
says blocked.gif

**Comment by neheb** [comment]
I looked at your file. There's some substitution error or something. Your file has a bunch of defines in there that are missing from mine. Here's the diff: https://gist.github.com/neheb/da7acce2c7a003ee3ef16accb5a68783

I also looked at openwrt-build/fcobjshash.h . Similar error. I have no idea what's happening. I'll look some more later.

**Comment by neheb** [comment]
OK my conclusion is something is broken with your setup. look at meson-log.txt. That output is present all over the place where it should not be.

**Comment by hnyman** [comment]
Interesting, because I have no modifications for tools or toolchain. Normal OpenWrt build env on top of Ubuntu 21.04.

**Comment by neheb** [comment]
That output looks the same as

```
gcc -dM -E - < /dev/null
```

But it gets outputted even when it should not be. Like...this is bogus:

```
Code:

        #ifdef __has_include
         #if !__has_include("dirent.h")
          #error "Header 'dirent.h' could not be found"
         #endif
        #else
         #include <dirent.h>
        #endif
Compiler stdout:
 #define __STDC__ 1
#define __STDC_VERSION__ 201710L
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC_HOSTED__ 1
#define __GNUC__ 11
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 0
#define __VERSION__ "11.2.0"
#define __ATOMIC_RELAXED 0
#define __ATOMIC_SEQ_CST 5
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_RELEASE 3
#define __ATOMIC_ACQ_REL 4
```

That c file should not create that output.

**Comment by hnyman** [comment]
I will probably rebuild the whole tools & toolchain once again. (I rebuilt tools a week ago, and toolchain after the gcc 11 & musl changes)

But the strange thing is that reverting this PR makes the compilation of the previous package version succeed ok. So I am hesitant to say that my build env is be wrong. Possibly something has changed in the fontconfig sources or meson config, so that the problem manifests in certain conditions.

**Comment by neheb** [comment]
Yeah I have no idea what the issue could be. It's strange that there's -dM output without it being set anywhere.

**Comment by hnyman** [comment]
There are several fontconfig meson changes between .93 and .94.
E.g.
* https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/ae9ac2a1bfb6fa800b99791b6fc36711dd0c1fbc
  "meson: fix cross-compilation issues with gperf header file preprocessing"

* https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/dba3287bf5dcb2ba0b716749a9a15e7ad43a91f4
  "meson: fix subproject build regression"

**Comment by neheb** [comment]
You'd have to test reverting these commits. I can't reproduce.

**Comment by hnyman** [comment]
I triangulated the failure point with upstream commits:

FAIL (both patches intact)
PKG_SOURCE_VERSION:=ae9ac2a1bfb6fa800b99791b6fc36711dd0c1fbc
PKG_SOURCE_DATE:=2021-02-15

Success (both patches intact)
PKG_SOURCE_VERSION:=7bfbaecf819a8b1630dfc8f56126e31f985d5fb3
PKG_SOURCE_DATE:=2021-02-14

So, the culprit is the upstream commit (mentioned above):
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/ae9ac2a1bfb6fa800b99791b6fc36711dd0c1fbc
`meson: fix cross-compilation issues with gperf header file preprocessing`

I first thought that it would be the meson.build change in that commit ae9ac2a1  (which has later already been reverted/modified by dba3287b), but patching that did nor help.

So, it might actually the cutout.py part, where `host_cargs` are passed and subprocess results are piped to stdout???

`ret = subprocess.run(cpp + host_cargs + [args[0].input], stdout=subprocess.PIPE, check=True)`

I will continue testing.

**Comment by neheb** [comment]
I guess something is weird with Ubuntu 21.04. I can't reproduce on Fedora 34. Buildbots running Debian 10 also seem to be fine.

**Comment by hnyman** [comment]
I will author a PR for the fix. Ubuntu is a viable buildhost, and the failure can be avoided.

(Ps. It sounds strange that that one single module would fail while 34 others had already been compiled ok)

**Pull request merged**
