### PR TITLE
net-snmp: Enable pass_persist support for snmpd in Makefile

### PR DESCRIPTION
**Pull request by ionum**

### CODE REVIEW

**Comment by sbyx** [comment]
Please read and follow: https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by ionum** [comment]
@sbyx please specify your problem with my pull request. Your comment is not very useful.

**Comment by sbyx** [comment]
> Commits in your pull-requests should:
> 
> Have a useful description prefixed with the package name
> (E.g.: "foopkg: Add libzot dependency")
> Include Signed-off-by in the comment
> (See https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork)

**Comment by ionum** [comment]
Thanks for your fast answer.

Do i need to sign-off my work, if i only change an option within the 
makefile? if, yes same rules in github?


Am 2015-03-15 11:06, schrieb Steven Barth:

**Comment by ionum** [comment]
@champtar: do you merge?

**Comment by echampet** [comment]
Nope, it's @jow- call.

**Pull request merged**
