### PR TITLE
smcroute: Keep config file /etc/smcroute.conf on sysupgrade

### PR DESCRIPTION
**Pull request by tobiaswaldvogel**
This time implemented the proper way

Signed-off-by: Tobias Waldvogel <tobias.waldvogel@gmail.com>

Maintainer: Moritz Warning <moritzwarning@web.de>
Compile tested: Atheros AR7xxx/AR9xxx / TP-LINK Archer C7 v2 / r13013+9
Run tested: Atheros AR7xxx/AR9xxx / TP-LINK Archer C7 v2 / r13013+9

Description: smcroute: keep config file /etc/smcroute.conf on sysupgrade

### CODE REVIEW

**Comment by lucize** [comment]
hi, next time don't close the PR, you can add changes, squash them using `git rebase -i HEAD~<N>` and git push --force

**Comment by tobiaswaldvogel** [comment]
Thanks for the info I will keep this in mind for the next time

**Comment by BKPepe** [comment]
Maintainer is @mwarning. If he approves it, it can be merged.

**Comment by hnyman** [comment]
The PR needs work:

There is already a faulty conffiles declaration on lines 37-39. It has tab indentation, which is wrong for conffiles section.

Instead of adding a new conffiles section to lines 54-56, the old one should be corrected by removing the tab indentation.

https://github.com/openwrt/packages/blob/master/net/smcroute/Makefile#L38

Please amend your commit (and then git force push to update the PR branch and this PR).

**Comment by tobiaswaldvogel** [comment]
That's quite embarrassing. How could I possibly have missed the existing conf section?
Thanks for the comment. I reworked it and just removed the faulty tab

**Comment by mwarning** [comment]
@tobiaswaldvogel don't worry, I did not see the the existing section at first, too. :)

Anyway, the commit looks good and can be merged. Thanks everyone!

**Pull request merged**
