### PR TITLE
atop: add new package

### PR DESCRIPTION
**Pull request by lnslbrty**
Maintainer: Toni Uhlig matzeton@googlemail.com
Compile tested: x86_64, debian-stable, OpenWrt SNAPSHOT r6687+2-d13c7acd9e
Run tested: mvebu, linksys3200ac, OpenWrt SNAPSHOT r6687+2-d13c7acd9e

Description:
An advanced interactive monitor for Linux-systems to view the load on system- level and process-level.

### CODE REVIEW

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/5386/files - I can add you as maintainer if you want? 
* You cannot assign copyright to OpenWrt unless you're affiliated, please use your own or omit
* No license entries
* +libc +libgcc aren't needed as deps
* Why extra cflags?
* LDFLAGS doesn't need to get redefined
* Regardig the patch, why is it needed? Source?

**Comment by lnslbrty** [comment]
> -#5386 - I can add you as maintainer if you want?

Yes, please.

> - You cannot assign copyright to OpenWrt unless you're affiliated, please use your own or omit

done
> - No license entries

done
> - +libc +libgcc aren't needed as deps

done
> - Why extra cflags?

- -Wno-misleading-indentation: inconsistent indentation
- -Wno-unused-const-variable: all compile units use a rcsid (only relevant for *BSD AFAIK)
- -Wno-format-truncation: dont print warnings from snprintf truncations

> - LDFLAGS doesn't need to get redefined

done
> - Regardig the patch, why is it needed? Source?

The patch fixes the (snprintf-)truncations because some buffers were not big enough. But this is what the upstream dev's wanted. So the patch is not required.
> - Do you plan on porting the kernel module?

I dont need the netatop kmod for personal use. If someone wants the module in OpenWrt, I will do my best porting it.

**Comment by diizzyy** [comment]
Please give the kernel module a try, it greatly improves atop.

**Comment by lnslbrty** [comment]
done, see #6046

**Pull request merged**
