### PR TITLE
i2pd: Update to 2.28.0

### PR DESCRIPTION
**Pull request by yangfl**
Maintainer: me
Compile tested/Run tested: @LLE8 https://github.com/PurpleI2P/i2pd/issues/345#issuecomment-527158568

### CODE REVIEW

**Comment by LLE8** [comment]
Please add in i2pd.conf 
log = syslog
loglevel = error
ntcp = false
profiles = false
addressbook = false

**Comment by yangfl** [comment]
> log = syslog
loglevel = error

Maybe...

> ntcp = false

Why?

> profiles = false
addressbook = false

Why??? This will force i2pd to reseed on every start, which sometimes is not possible without the help of proxies.

**Comment by LLE8** [comment]
ntcp = false because @orignal says he plans to disable by default and remove ntcp later.
There are high cpu usage problem with ntcp. Ntcp2 is replacement of ntcp, as i understand.  Ntcp2 enabled by default now.
https://github.com/PurpleI2P/i2pd/issues/1275#issuecomment-493586431

**Comment by LLE8** [comment]
profiles = false  and  addressbook = false because there not enough space on typical openwrt device to store all thousands tiny files in /var/lib/i2pd/peerProfiles and  /var/lib/i2pd/addressbook
see screenshot, this is after 24 hours uptime
https://github.com/PurpleI2P/i2pd/issues/345#issuecomment-452771143
Note, that /var/lib is tmpfs in RAM, which is usually 64 or 128 MB.

**Comment by LLE8** [comment]
Please add in i2pd.conf
notransit = true
floodfill = false
because usually openwrt device has slow cpu and low memory

**Comment by yangfl** [comment]
floodfill and floodfill are default to false, no need to change

**Comment by LLE8** [comment]
Transit tunnels enabled by default
https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Config.cpp
`("notransit", bool_switch()->default_value(false),                "Router will not accept transit tunnels at startup (default: disabled)")`
`("floodfill", bool_switch()->default_value(false), "Router will be floodfill (default: disabled)")`

**Comment by LLE8** [comment]
My OpenWrt i2pd.conf, read the explanatory comments.
I think, its simpler to have in the  package its own custom i2pd.conf, based on original i2pd.conf, but not patch for original i2pd.conf. 
```
## in openwrt most of config files are in /etc without extra subdirs, as i understand
tunconf = /etc/i2pd_tunnels.conf
tunnelsdir = /etc/i2pd_tunnels.d
## note, that if pidfile can not be created, i2pd immediately exits silently without any log messages, bug
pidfile = /var/run/i2pd.pid
## by default this is small ring buffer in ram, run logread to view logs
log = syslog
## the buffer is small
loglevel = error
## date and time in logs
logclftime = true
## in procd the service itself should run in the foreground, see https://openwrt.org/docs/guide-developer/procd-init-scripts
daemon = false
ipv4 = true
## bugs, ipv6 doesn't work in i2pd
ipv6 = false
## change network interface according to your device configuration, this interface name is only for my tl-mr3020v3
ifname = br-lan
## will be removed in future releases and high cpu usage bug now, ntcp2 is replacement
ntcp = false
## many home routers have only private address on their wan interface
nat = true
## you may change it as you need
bandwidth = O
## slow cpu, low ram
notransit = true
floodfill = false
## you may change listen addresses according to your lan configuration
[http]
address = 127.0.0.1
port = 7070
[httpproxy]
address = 127.0.0.1
port = 4444
[socksproxy]
address = 127.0.0.1
port = 4447
[sam]
enabled = true
[reseed]
verify = true
## tmpfs in ram, low ram 
[persist]
profiles = false
addressbook = false
```

**Comment by yangfl** [comment]
I think it's better to ship the original conf to ensure the same management experience on different systems.

And, I still in huge doubt of disabling certain features just to save resources. As I've explained before, i2pd is AES bound software, anyone trying to run i2pd in a *ordinary* mips router should expect 100% CPU usage. These tunings are useless unless dramatic usage drop can be seen.

**Comment by LLE8** [comment]
>  i2pd is AES bound software
Many vds-hosters do not support AES on their VDS, but i2pd works fine on these VDS

**Comment by hnyman** [comment]
ok to merge?

**Comment by yangfl** [comment]
I think so.
I'd like to know if there are more comments or suggestions on the configure file, but let us do a regular update first.

**Pull request merged**
