### PR TITLE
stunnel: update version to 5.55

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: me
Compile tested: lantiq_xrx200 and x86_64, APU3, OpenWrt master
Run tested: x86_64, APU3, Openwrt master, start with default config

Description:
Update version to 5.55
Fix shell check warnings

### CODE REVIEW

**Comment by neheb** [comment]
Can you take a look at the init script?  shellcheck is throwing this little gem at line 320: https://github.com/koalaman/shellcheck/wiki/SC2129

**Comment by feckert** [comment]
@jefferyto Could have a look on some shellcheck warnings?

> In net/stunnel/files/stunnel.init line 340:
> 	[ -z "$alt_config_file" ] || [ -n "$CONF_FILE_CREATED" ] || {
>               ^-- SC2154: alt_config_file is referenced but not assigned.
> 
> 
> In net/stunnel/files/stunnel.init line 352:
> 	[ -z "$setuid" ] || chown "$setuid" "$pid_dir"
>               ^-- SC2154: setuid is referenced but not assigned.
> 
> 
> In net/stunnel/files/stunnel.init line 353:
> 	[ -z "$setgid" ] || chown ":$setgid" "$pid_dir"
>               ^-- SC2154: setgid is referenced but not assigned.
> 
> 
> In net/stunnel/files/stunnel.init line 366:
> 	[ "$enabled" = 1 ] || return 0
>            ^-- SC2154: enabled is referenced but not assigned.

I am not sure how to handle that? The changed where add by your commit 
https://github.com/openwrt/packages/commit/8bb3eba3c22f81488f6702ca0c31eeae0441aec0#diff-c163cd9e3e2551e71f64b1af9e11ee81

**Comment by jefferyto** [comment]
@feckert Those variables are set by `uci_load_validate()`, but still accessible to the scope for those statements. And even if they were not set, the tests still work because an unset variable is "equal" to the empty string.

I guess if you really want to pass shellcheck, you can "set" the variables like:

```sh
enabled=${enabled:-}
```

which will set `enabled` to itself if it is set, or to the empty string if it is not set.

**Comment by neheb** [comment]
I don't think shellcheck can look deep enough so see that they are set there.

**Comment by feckert** [comment]
I will merge this now. And leave the shell check warnings as it is.
Because this works as expected.

**Pull request merged**
