### PR TITLE
shadowsocks-libev:update shadowsocks-libev ,sync github.com/shadowsocks

### PR DESCRIPTION
**Pull request by GrayYip**
shadowsocks-libev:update shadowsocks-libev

sync github.com/shadowsocks

Signed-off-by: GrayYip <yjr0821@hotmail.com>

Please double check that your commits:
- all start with "<package name>: "
- all contain signed-off-by
- are linked to your github account (you see your logo in front of them) 

Please also read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

Thanks for your contribution
Please remove this text (before ---) and fill the following template
-------------------------------

Maintainer: me / @<github-user>
Compile tested: (put here arch, model, OpenWRT/LEDE version)
Run tested: (put here arch, model, OpenWRT/LEDE version, tests done)

Description:

### CODE REVIEW

**Comment by yousong** [comment]
Hi @GrayYip , removal of `shadowsocks-client/` should be in a separate commit with detailed text explaining why the change should happen...

Hi @aa65535 , @zhao-gang , please review and comment.

**Comment by GrayYip** [comment]
hi @yousong ,  the new `shadowsocks-libev` include `shadowsocks-client & server` .  so ... I remove shadowsocks-client.
P.S.:this's my first push patch to github. :)

**Comment by GrayYip** [comment]
我这英语说的有点尴尬，23333

**Comment by hnyman** [comment]
I don't quite understand what you are trying to do here, as you have now mixed sqm-scripts and luci-app-sqm to this Pull Request.

In general, you should always author from PRs froma branch in stead of master, so that your other changes do not get mixed.

**Comment by yousong** [comment]
Please give https://github.com/openwrt/packages/pull/4513 a try and see if it can suit your needs

**Pull request closed without merging**
