### PR TITLE
prometheus-node-exporter-lua: add new metrics

### PR DESCRIPTION
**Pull request by aparcar**
Maintainer: Christian Simon / @simonswine
Compile tested: LEDE 17.01.4, x86/64
Run tested: LEDE 17.01.4, x86/64

Description:

sync with latest source [1]

new metrics: wifi_clients, nat_sessions

[1] https://github.com/openwrt-exporter/openwrt_exporter

Signed-off-by: Paul Spooren <spooren@informatik.uni-leipzig.de>

### CODE REVIEW

**Comment by champtar** [comment]
Hi @aparcar,
Can you have a look at #5128 
I would like to get it merged but none of the user responded to me

**Comment by aparcar** [comment]
Well looks good to me but I'm no lua dev. Maybe you could become the new maintainer for the package?

**Comment by aparcar** [comment]
Well looks good to me but I'm no lua dev. Maybe you could become the new maintainer for the package?

**Comment by aparcar** [comment]
@champtar ping

**Comment by simonswine** [comment]
Sorry for my really late response. Feel free to notify me/tag me here till I respond...

As said in #5128, I would love the modularization to merge into the upstream repo. Then we can merge this back into here or even better make sure we just use this as a remote reference. (Not too sure how to do this, I guess there should be plenty of examples in here)


WDJT @champtar @aparcar?

**Comment by aparcar** [comment]
@simonswine @champtar I'd close this PR and open a new one where we use it as a remote package.

**Comment by aparcar** [comment]
closed due to https://github.com/openwrt/packages/pull/5128

**Pull request closed without merging**
