### PR TITLE
strongswan: fix sharing of ipsec section variables

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me, @Thermi
Compile tested: x86_64, generic, HEAD (507257778c)
Run tested: same, installed on production firewall

Description:

Variables set in config_ipsec() need to be shared with do_postamble()
function, so change scoping to parent (prepare_env()).

Also, remove unused settings like "remote_sourceip", "reqid", and
"packet_marker".

### CODE REVIEW

**Comment by zhoulizhengithub** [comment]
> 维护者：我，@Thermi
> 编译测试：x86_64，通用，HEAD (507257778c)
> 运行测试：相同，安装在生产防火墙上
> 
> 描述：
> 
> config_ipsec() 中设置的变量需要与 do_postamble()
> 函数共享，因此将范围更改为父级 (prepare_env())。
> 
> 此外，删除未使用的设置，如“remote_sourceip”、“reqid”和
> “packet_marker”。

 Strongswan is deprecating the ipsec CLI;  migrate to swanctl.
So I used the IPSec cli / etc / ipsec.conf and / etc / ipsec.secrets
How to migrate to swantl. Can you write me an example? I am a novice user rookie, I need your help, thank you!
How to start IPSec connection with swantl
The file needs to be changed


# generated by /etc/init.d/ipsec
version 2
config setup
conn route1
   keyexchange=ikev1
   left=%any
   right=x.x.x.x
   leftsubnet=192.168.188.0/24
   leftauth=psk
   rightauth=psk
   rightsubnet=10.0.0.0/24
   auto=start
   dpddelay = 30s
   dpdtimeout = 30s
   margintime = 20m
   dpdaction = restart
   closeaction = restart
   esp=3des-sha1
   ike=3des-md5-modp1024
   type=tunnel
conn route2
   keyexchange=ikev1
   left=%any
   right=x.x.x.x
   leftsubnet=192.168.188.0/24
   leftauth=psk
   rightauth=psk
   rightsubnet=192.168.0.0/24
   auto=start
   dpddelay = 30s
   dpdtimeout = 30s
   margintime = 20m
   dpdaction = restart
   closeaction = restart
   esp=3des-md5-modp768
   ike=3des-md5-modp768
   type=tunnel

**Comment by zhoulizhengithub** [comment]
> Maintainer: me, @Thermi
> Compile tested: x86_64, generic, HEAD (507257778c)
> Run tested: same, installed on production firewall
> 
> Description:
> 
> Variables set in config_ipsec() need to be shared with do_postamble()
> function, so change scoping to parent (prepare_env()).
> 
> Also, remove unused settings like "remote_sourceip", "reqid", and
> "packet_marker".



 Strongswan is deprecating the ipsec CLI;  migrate to swanctl.
So I used the IPSec cli / etc / ipsec.conf and / etc / ipsec.secrets
How to migrate to swantl. Can you write me an example? I am a novice user rookie, I need your help, thank you!
How to start IPSec connection with swantl
The file needs to be changed



# generated by /etc/init.d/ipsec
version 2
config setup
conn route1
   keyexchange=ikev1
   left=%any
   right=x.x.x.x
   leftsubnet=192.168.188.0/24
   leftauth=psk
   rightauth=psk
   rightsubnet=10.0.0.0/24
   auto=start
   dpddelay = 30s
   dpdtimeout = 30s
   margintime = 20m
   dpdaction = restart
   closeaction = restart
   esp=3des-sha1
   ike=3des-md5-modp1024
   type=tunnel
conn route2
   keyexchange=ikev1
   left=%any
   right=x.x.x.x
   leftsubnet=192.168.188.0/24
   leftauth=psk
   rightauth=psk
   rightsubnet=192.168.0.0/24
   auto=start
   dpddelay = 30s
   dpdtimeout = 30s
   margintime = 20m
   dpdaction = restart
   closeaction = restart
   esp=3des-md5-modp768
   ike=3des-md5-modp768
   type=tunnel
conn route3
   keyexchange=ikev1
   left=%any
   right=x.x.x.x
   leftsubnet=10.3.208.0/24
   leftauth=psk
   rightauth=psk
   dpddelay = 30s
   dpdtimeout = 30s
   margintime = 20m
   dpdaction = restart
   closeaction = restart
   rightsubnet=172.16.0.0/18
   auto=start
   esp=aes128-sha1-modp1536
   ike=aes128-sha1-modp1536
   lifetime=1800
   ikelifetime=28800
   type=tunnel

**Comment by Thermi** [comment]
Depends on if you used UCI for configuring this, or if you did it manually. If you did it in UCI, then use the new variables and specify the parameters that way. The rest should be taken care of by the swanctl init script.

If you wrote it manually, either you read the manual for swanctl yourself and use it to specify the connections and secrets that way, or you[ try my ipsec2swanctl.py script from my GL](https://gitlab.com/Thermi/ipsec2swanctl).

**Comment by pprindeville** [comment]
@zhoulizhengithub Please don't use Git for soliciting help.  If there's an issue, file it in Github.

If you need help, use the mailing list or IRC.

**Comment by zhoulizhengithub** [comment]
> Maintainer: me, @Thermi
> Compile tested: x86_64, generic, HEAD (507257778c)
> Run tested: same, installed on production firewall
> 
> Description:
> 
> Variables set in config_ipsec() need to be shared with do_postamble()
> function, so change scoping to parent (prepare_env()).
> 
> Also, remove unused settings like "remote_sourceip", "reqid", and
> "packet_marker".

d# swanctl --initiate --child gwgw

Can this kernel error be fixed

[KNL] received netlink error: No such file or directory (2)
[KNL] unable to add SAD entry with SPI c6af2b4d (FAILED)
[KNL] received netlink error: No such file or directory (2)
[KNL] unable to add SAD entry with SPI c9f565c4 (FAILED)
[IKE] unable to install inbound and outbound IPsec SA (SAD) in kernel
initiate failed: establishing CHILD_SA 'gwgw' failed

**Comment by zhoulizhengithub** [comment]
> Maintainer: me, @Thermi
> Compile tested: x86_64, generic, HEAD (507257778c)
> Run tested: same, installed on production firewall
> 
> Description:
> 
> Variables set in config_ipsec() need to be shared with do_postamble()
> function, so change scoping to parent (prepare_env()).
> 
> Also, remove unused settings like "remote_sourceip", "reqid", and
> "packet_marker".


Can this kernel error be fixed

 swanctl --initiate --child gwgw
[IKE] initiating Main Mode IKE_SA gwgw[20] to 183.6.139.26
[ENC] generating ID_PROT request 0 [ SA V V V V V ]
[NET] sending packet: from 192.168.188.228[500] to 183.6.139.26[500] (176 bytes)
[NET] received packet: from 183.6.139.26[500] to 192.168.188.228[500] (156 bytes)
[ENC] parsed ID_PROT response 0 [ SA V V V V ]
[IKE] received XAuth vendor ID
[IKE] received DPD vendor ID
[IKE] received FRAGMENTATION vendor ID
[IKE] received NAT-T (RFC 3947) vendor ID
[CFG] selected proposal: IKE:3DES_CBC/HMAC_MD5_96/PRF_HMAC_MD5/MODP_768
[ENC] generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
[NET] sending packet: from 192.168.188.228[500] to 183.6.139.26[500] (204 bytes)
[NET] received packet: from 183.6.139.26[500] to 192.168.188.228[500] (204 bytes)
[ENC] parsed ID_PROT response 0 [ KE No NAT-D NAT-D ]
[IKE] local host is behind NAT, sending keep alives
[ENC] generating ID_PROT request 0 [ ID HASH ]
[NET] sending packet: from 192.168.188.228[4500] to 183.6.139.26[4500] (68 bytes)
[NET] received packet: from 183.6.139.26[4500] to 192.168.188.228[4500] (68 bytes)
[ENC] parsed ID_PROT response 0 [ ID HASH ]
[IKE] IKE_SA gwgw[20] established between 192.168.188.228[183.6.139.26]...183.6.139.26[183.6.139.26]
[IKE] scheduling rekeying in 13984s
[IKE] maximum IKE_SA lifetime 15424s
[ENC] generating QUICK_MODE request 3615948666 [ HASH SA No KE ID ID ]
[NET] sending packet: from 192.168.188.228[4500] to 183.6.139.26[4500] (276 bytes)
[NET] received packet: from 183.6.139.26[4500] to 192.168.188.228[4500] (276 bytes)
[ENC] parsed QUICK_MODE response 3615948666 [ HASH SA No KE ID ID ]
[CFG] selected proposal: ESP:3DES_CBC/HMAC_MD5_96/MODP_768/NO_EXT_SEQ
[KNL] received netlink error: No such file or directory (2)
[KNL] unable to add SAD entry with SPI c6af2b4d (FAILED)
[KNL] received netlink error: No such file or directory (2)
[KNL] unable to add SAD entry with SPI c9f565c4 (FAILED)
[IKE] unable to install inbound and outbound IPsec SA (SAD) in kernel
initiate failed: establishing CHILD_SA 'gwgw' failed

**Comment by Thermi** [comment]
Open a new issue, you git.

**Pull request merged**
