### PR TITLE
dmapd: update to 0.0.79

### PR DESCRIPTION
**Pull request by MikePetullo**
Signed-off-by: W. Michael Petullo mike@flyn.org

Maintainer: me
Compile tested: x86_64 master
Run tested: x86_64 master

Description:
dmapd: Update to 0.0.78

Depends on pull #8037.

### CODE REVIEW

**Comment by neheb** [comment]
Hrm interesting.

While I was testing https://github.com/openwrt/packages/pull/7675 , I noticed that dmapd also needs a dependency on gst1playback as it uses uridecodebin.

There also needs to be a dependency on some other gst plugin as I kept getting

```
dmapd: WARNING: Could not read metadata from file
```

**Comment by MikePetullo** [comment]
These are all meant to be soft dependencies. Users should install the GStreamer plugins required to support the file types they wish to support. This approach allows the use of dmapd on hardware with very small disks.

**Comment by neheb** [comment]
So playback is not required? IIRC, dmapd just crashes without playback.

**Comment by neheb** [comment]
Just remembered, the init script needs updating.

**Comment by MikePetullo** [comment]
Playback is not required. Playback allows the dmapd daemon itself to play audio while being controlled by a remote which uses DACP. A much more common use is to stream the audio from dmapd to a client using DAAP.

I will investigate the requirement regarding pull request #7675 once that pull request is merged.

I would be happy to add the init script work to this pull request. Can you provide details or a patch?

**Comment by neheb** [comment]
Just tested: seems accurate.

```
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (process:5155): GLib-GObject-CRITICAL **: 19:03:30.252: Object class AVRender doesn't implement property 'volume' from interface 'DmapControlPlayer'
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (process:5155): GLib-GObject-CRITICAL **: 19:03:30.260: Object class AVRender doesn't implement property 'shuffle-state' from interface 'DmapControlPlayer'
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (process:5155): GLib-GObject-CRITICAL **: 19:03:30.260: Object class AVRender doesn't implement property 'repeat-state' from interface 'DmapControlPlayer'
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (process:5155): GLib-GObject-CRITICAL **: 19:03:30.260: Object class AVRender doesn't implement property 'playing-time' from interface 'DmapControlPlayer'
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (process:5155): GLib-GObject-CRITICAL **: 19:03:30.261: Object class AVRender doesn't implement property 'play-state' from interface 'DmapControlPlayer'
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (process:5155): GLib-WARNING **: 19:03:30.262: A group named "gst" is already part of this GOptionContext
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]:
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: (dmapd:5155): GLib-GObject-CRITICAL **: 19:03:30.311: Object class DmapdDmapAvRecord doesn't implement property 'songalbumid' from interface 'DmapAvRecord'
Fri Jan 25 19:03:30 2019 daemon.err dmapd[5155]: dmapd: WARNING: Couldn't create 'uridecodebin' element
```

with the last one being spammed until the end of the library. Adding all of the plugins including playback causes

```
dmapd: WARNING: Could not read metadata from file
```
but slowly. Maybe it's hashing or something. All of the files are FLAC files. Maybe the gst1-plugins-base package is broken.

https://github.com/openwrt/packages/pull/7675 needs maintainer approval. I've verified that it works.

The init script has a bunch of hardcoded paths that don't seem to be valid. Paths that can be specified in /etc/dmapd.conf

Maybe a long term solution would be to make it configurable through UCI and pass all the settings to the command line. dmapd --help indicates most or all of the .conf settings can be set there.

**Comment by MikePetullo** [comment]
Pushed a new release which will continue to build after we apply pull request #7675.

**Comment by neheb** [comment]
Great.

**Pull request merged**
