### PR TITLE
libndpi: Add PKG_BUILD_DEPENDS to fix compilation

### PR DESCRIPTION
**Pull request by neheb**
I just tested it and it seems to work.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @hbl0307106015
Compile tested: mvebu

### CODE REVIEW

**Comment by neheb** [comment]
Local compile worked but buildbots are failing with the same error. Hmmmm.....

**Comment by champtar** [comment]
@neheb if you have time to reporduce it in the CircleCI container, it might just be a missing dependency
https://github.com/openwrt/packages/blob/master/.circleci/config.yml
Else I'll try to have a look this weekend

**Comment by hnyman** [comment]
Both Travis and circleci are happy with the most recent commit.
Let's try merging this fix.

**Comment by neheb** [comment]
Yeah I fixed it. Forgot to announce.

**Pull request merged**
