### PR TITLE
jamvm: remove unneeded host build, and the package itself

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @danak6jq
Compile tested: N/A
Run tested: N/A

Description:
Host build was added in 2972cc98e ("Add host build") because classpath required a host java vm.  Now that classpath is gone, host build can be removed as well.

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
The entire package can be removed honestly. Nothing depends on it.

**Comment by danak6jq** [comment]
I picked-up maintaining the jamvm package back when I was using it for a now-defunct project. Upstream jamvm and classpath both appear frozen at a relatively old Java revision - perhaps even abandoned. I'd have no issue removing the package and holding a virtual wake.

**Comment by cotequeiroz** [comment]
> The entire package can be removed honestly. Nothing depends on it.

I agree, this is useless without classpath, which has been removed.  Shall I close this, then?

**Comment by neheb** [comment]
Or update

**Comment by hnyman** [comment]
We do not have much java stuff here, and almost all of that (like the removed classpath) has been broken in the buildbots. So let's remove this.

Could you change the PR by adding a second commit that removes the package?

(Then we would have left the reasoning for the host build removing into git history, in case somebody wants to revive the package later)

**Comment by neheb** [comment]
Did you throw this in packages-abandoned?

**Comment by cotequeiroz** [comment]
Yes, I did:  https://github.com/openwrt/packages-abandoned/commit/5b5aa33dfc6c2cfdf43c2e22467156faf98e87c0.

**Pull request merged**
