### PR TITLE
 mutt: bump to 1.12.2

### PR DESCRIPTION
**Pull request by philenotfound**
Signed-off-by: Phil Eichinger phil@zankapfel.net

Maintainer: me
Compile tested: (ar71xx, TL-WDR4300, 18.06.2)
Run tested: (ar71xx, TL-WDR4300, 18.06.2)

### CODE REVIEW

**Comment by hnyman** [comment]
Fails in automatic testing, but at the first glance I can't figure out why that commit title seems faulty.

**Comment by champtar** [comment]
On my phone, but maybe the line start with a space

**Comment by hnyman** [comment]
> maybe the line start with a space

Might be a good guess:
 https://github.com/openwrt/packages/commit/adfc5ab33ccf7cf79647530b95f43091fdb78abc.patch
shows "`Subject: [PATCH]  mutt: bump to 1.12.2`" with double space between "[PATCH]" and "mutt", (although it gets edited out from diplay even here in the PR discussion.)

**Comment by philenotfound** [comment]
Thanks, I was also overlooking the extra space.

**Comment by hnyman** [comment]
That fixed it.

Any reason to skip backporting 1.12.1 and 1.12.2 to the 19.07 branch?

**Comment by philenotfound** [comment]
Not really, but I haven't tried compiling it against openssl 1.1.x yet.
I would prefer knowing beforehand, so I'll test it first.
Should I open another PR afterwards?

**Comment by hnyman** [comment]
Opening a new PR for 19.07 would be great.  

(Ps. here in master it is openssl 1.1.1d, which has also been recently backported to the stable 19.07 branch, so I am not sure what would be difference. 
In any case, 19.07 has always the same or older openssl than here in master)

**Pull request merged**
