### PR TITLE
arp-scan: update to latest 1.9.8 

### PR DESCRIPTION
**Pull request by Gingernut1978**
Maintainer: Sergey Urushkin <urusha.v1.0@gmail.com>

Compile tested: mediatek:mt7622
Run tested: mediatek:mt7622

Signed-off-by: Andrew Sim <andrewsimz@gmail.com>

### CODE REVIEW

**Comment by feckert** [comment]
Why do we not use a stable version? The latest is https://github.com/royhills/arp-scan/tree/1.9.8

**Comment by Gingernut1978** [comment]
No objection

**Comment by feckert** [comment]
Thank you for the update.
But if we take the stable version, then we should also leave the URL and not use git.

**Comment by Gingernut1978** [comment]
> Thank you for the update. But if we take the stable version, then we should also leave the URL and not use git.

But I couldn't find a recent stable release, stable 1.9.8 release is from 2013. There is also a 1.9.9 stable but it's also from 2013. 

The link you posted was a tag afaik. 

I'm quite new to this.

**Comment by feckert** [comment]
If you enter this command `wget https://codeload.github.com/royhills/arp-scan/tar.gz/1.9.8` then you are downloading the version to the directory with the file name `1.9.8`. And with command `sha256sum 1.9.8 ` you are calculating the hash of the downloaded tar.gz.

Now you only have to update the `PKG_VERSION:=1.9.7` to` PKG_VERSION:=1.9.8` and the `PKG_HASH:=` value from the sha256sum command.

Changing this values is enough to update arp-scan to an new version

**Comment by Gingernut1978** [comment]
Understood, thanks.

**Comment by Gingernut1978** [comment]
Done

**Pull request merged**
