### PR TITLE
syslog-ng: listen not globally but just locally

### PR DESCRIPTION
**Pull request by traud**
Beside that, listen not only on IPv4 but also on IPv6 = Dual Stack.

### CODE REVIEW

**Comment by traud** [comment]
This issue was found downstream in the Turris OS project from NIC.cz. There, the package _syslog-ng_ is installed out of the box. The project allows a **Host Computer** scenario in which the OpenWRT installation is not a router but just a client within the network. With such a device, no ports (except those for administration) should be open/listening. _syslog-ng_ was found via `netstat -tulpen`. 

Because I am not aware how a **Router** scenario would benefit from a globally listening [syslog](https://en.wikipedia.org/wiki/Syslog) server either, I propose this change upstream, here in the OpenWRT repositories.

**Comment by BKPepe** [comment]
Hi @traud,

Thank you for your contribution. As the maintainer of the package syslog-ng in OpenWrt, I'd like you to do two things:

- [Sign off your work](https://openwrt.org/submitting-patches#sign_your_work), which is required to pass the `DCO` check and it is also required by `buildpr`.
- Increase the number of `PKG_RELEASE` in the Makefile of syslog-ng.
If you don't increase it, it will be just applied for new installations and existing installation will require to do `opkg install syslog-ng --force-reinstall`. More details can be found about it in [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md).

Based on your commit changes, I found that this row was untouched for almost 3 years. It comes from this commit  https://github.com/openwrt/packages/commit/ef0fef50fb32b6b05deaffade7b5c9bcfdc9a70c . Good finding! I agree it should be improved in all OpenWrt versions.

**Comment by traud** [comment]
> Sign off your work

Upps. I understood this was just for those adding a new package. I did not find a section for patchers like me in the CONTRIBUTING.md. Furthermore, I thought, the verification done by the GitHub Web IDE does this, too. But it does not. Mhm. Now, I have a problem. From the Web IDE, I cannot squash. I guess, you cannot squash for me, can you? In that case, I have to setup a git on one of my computers.

> comes from commit ef0fef5

Well, it is even [older…](https://dev.archive.openwrt.org/changeset/17298.html) at that time, OpenWRT was not IPv6 savvy. However, I wonder why nobody saw that _localhost_ thing; perhaps because that package here is optional in OpenWRT (and out-of-the-box in Turris OS). Mhm.

**Comment by BKPepe** [comment]
I would like to apologize, I can not squash commits for you to pass `DCO` and `buildpr` checks.

**Comment by BKPepe** [comment]
Cherry-picked into `openwrt-19.07` branch: https://github.com/openwrt/packages/commit/da2071507d9b93d0b4253cb17f8ec32d08bda007

**Comment by traud** [comment]
> [this change] should be also included in OpenWrt 18.06

Who does this: Is anything needed/requested from my side?

**Pull request merged**
