### PR TITLE
ddns-scripts: Added nsupdate.info - a free service.

### PR DESCRIPTION
**Pull request by the-solipsist**
This update seeks to add nsupdate.info, a free DDNS service based on open source code: https://github.com/nsupdate-info/nsupdate.info

### CODE REVIEW

**Comment by hnyman** [comment]
@chris5560

**Comment by chris5560** [comment]
@the-solipsist

No Pull description
No Sign-Off

No change on PKG-RELEASE of Makefile

NO implementation for IPv6 - looking on updateURL there should be one.
What is the answer on successful update or no change ?

**Comment by the-solipsist** [comment]
Thanks for the comments.

1. Added pull description.
2. I don't know how to do a sign-off from the Github web interface.
3. What changes do I need to make on PKG-RELEASE?  Guidance would be appreciated.
4. nsupdate.info supports IPv6: https://nsupdateinfo.readthedocs.org/en/latest/intro.html?highlight=v6. Should I open a new pull request for the changes to services_ipv6?
5. It uses RFC 2136 as the backend protocol, so I'm guessing the responses are as dictated in that RFC.

**Comment by chris5560** [comment]
Please have a look into
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork

https://github.com/openwrt/packages/blob/master/net/ddns-scripts/Makefile

RFC 2136 describe the backend communication not the one between ddns-clients and the service.
But digging inside their documentation I found out, that they are using "dyndns2 api" so the answer on success is "good" or "nochg".
So please append "good|nochg" behind update url.
Look into services/services_ipv6 file for samples.

You might need to recreate your commits because services/services_ipv6 files were changed last weekend.
Or I can prepare commit and pull for you.

**Comment by champtar** [comment]
@the-solipsist @chris5560 any updates

**Comment by chris5560** [comment]
I will look on it the next days and create a new update.
I want to add some more services anyway.

**Comment by champtar** [comment]
ok, closing this then

**Pull request closed without merging**
