### PR TITLE
ddns-scripts: Update afraid.org update URL

### PR DESCRIPTION
**Pull request by mizhgan**
---

Maintainer: @chris5560 

Compile tested: it`s just text config

Run tested: it`s just text config

Description:

Since it was wrong.

### CODE REVIEW

**Comment by hnyman** [comment]
DDNS maintainer is @chris5560

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/issues/2445
This got shotdown last time because more or less of the reason that we've been doing it all along so why bother changing it to the correct way...

**Comment by yousong** [comment]
Last time (a few weeks ago) I checked the update link on website of freedns.afraid.org, it was the current form of link (some base64-encoded key instead of username/password) and I remembered it worked fine, though the domain is poisoned in my area ;(

Apart from config compatibility concerns, I myself prefer the sort-of random keyed url over storing/transferring plaintext username/password.

**Comment by mizhgan** [comment]
Sorry for misunderstanding, of course he is.

2016-10-24 19:33 GMT+03:00 Hannu Nyman <notifications@github.com>:

**Comment by chris5560** [comment]
@diizzyy @yousong
If you confirm that the changed url will work, I'm fine with it.
As long as secure http is available I see no problem using "plaintext" account details.

@mizhgan
Could you please increase PKG_RELEASE inside Makefile and sign your work.
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by chris5560** [comment]
@mizhgan

Could you please provide a documentation link on afraid.org's web pages to me or pdf accessible without afraid.org account because last time we changed the url there was a great shout in the community and it was rolled back.
Thanks for your support.

**Comment by diizzyy** [comment]
The great shout was one person who couldn't differentiate between an "API-key" and login credentials. I even suggested that you made the correct behavior default and changed the current (wrong one) as legacy.

**Comment by yousong** [comment]
@mizhgan , the current `update_url` is not wrong.  It's just that the `[PASSWORD]` field should be a base64 encoded key provided by afraid.org (it's different for each domain), not your afraid.org site login password.  If you really want the alternative url be available, I would recommend add it under another service name, something like `afraid.org-basicauth`, but I doubt that will make the situation better...

**Comment by yousong** [comment]
Close this as it is "not-a-issue" the pr tries to fix and there is also no further progress for more than one month.

**Pull request closed without merging**
