### PR TITLE
ooniprobe: update to version 3.0.7

### PR DESCRIPTION
**Pull request by ja-pa**
maintainer: me
Compile tested: Turris Omnia (TOS6), OpenWrt master
Run tested: Turris Omnia (TOS6), OpenWrt master

Description:
This PR updates ooniprobe to version 3.0.7. This version uses probe-engine 0.17 therefore measurement-kit is no longer needed and the measurement-kit package is removed.

### CODE REVIEW

**Comment by BKPepe** [comment]
In ooniprobe [changelog](https://github.com/ooni/probe-cli/releases/tag/v3.0.7), I found the details that it uses probe-engine 0.17, but looking into its [changelog](https://github.com/ooni/probe-engine/releases/tag/v0.17.0) there isn't anything that measurement-kit is no longer required. Do you know something when it is stated?

**Comment by ja-pa** [comment]
It was probably only mentioned in [probe-engine v0.16.0](https://github.com/ooni/probe-engine/releases/tag/v0.16.0)

>  We don't depend on Measurement Kit anymore

**Review by BKPepe — APPROVED** [review]

**Comment by neheb** [comment]
Please open a PR in https://github.com/openwrt/packages-abandoned with measurement-kit.

**Comment by ja-pa** [comment]
> Please open a PR in https://github.com/openwrt/packages-abandoned with measurement-kit.

Done https://github.com/openwrt/packages-abandoned/pull/16

**Comment by neheb** [comment]
https://downloads.openwrt.org/snapshots/faillogs/aarch64_generic/packages/ooniprobe/compile.txt

**Pull request merged**
