### PR TITLE
boost: Package Version Update (1.73.0)

### PR DESCRIPTION
**Pull request by ClaymorePT**
Maintainer: @ClaymorePT 
Compile tested: BCM2711 - Raspberry Pi 4B
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

This commit updates Boost to version 1.73.0
In this release, there are two new libraries
 - Nowide [[2]] - Standard library functions with UTF-8 API on Windows, from Artyom Beilis.
 - Static String [[3]] - A dynamically resizable string of characters with compile-time fixed capacity and contiguous embedded storage, from Vinnie Falco and Krystian Stasiowski.

More info about Boost 1.73.0 can be found at the usual place [[1]].

[1]: https://www.boost.org/users/history/version_1_73_0.html
[2]: https://www.boost.org/libs/nowide/
[3]: https://www.boost.org/libs/static_string/

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
This broke:

https://downloads.openwrt.org/snapshots/faillogs/mipsel_74kc/packages/domoticz/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/mipsel_74kc/packages/pdns/compile.txt

**Comment by neheb** [comment]
Ugh a bind problem. This probably needs this fix: https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-bind.html

**Comment by ClaymorePT** [comment]
@neheb I'm a bit confused. Those issues seem to be defects from those specific packages which are not be ready to be built using for Boost 1.73.0. Which side do you believe it should be patched?

**Comment by neheb** [comment]
Packages

**Pull request merged**
