### PR TITLE
python-jsonschema: Update to 4.19.1, add new dependencies

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @jmarcet, me (new dependencies)
Compile tested: armsr-armv7, 2023-10-11 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-11 snapshot

Description:

### CODE REVIEW

**Comment by jefferyto** [comment]
The riscv64 CI error is really weird... at first when building with `-j "$(nproc)"`:

```
2023-10-15T16:10:34.3500391Z     ERROR: package/feeds/packages_ci/python3 failed to build.
```

Then when building again with `-j 1` python3 builds with no errors, then later while building maturin:

```
2023-10-15T16:21:30.5238940Z running build_ext
2023-10-15T16:21:30.5239250Z running build_rust
2023-10-15T16:21:30.5260429Z rustc: error while loading shared libraries: /builder/staging_dir/target-riscv64_riscv64_musl/host/bin/../lib/librustc_driver-d0a8930e4a37ddb4.so: file too short
2023-10-15T16:21:30.5272901Z error: can't find Rust compiler
```

even though rust/host had compiled with no errors earlier (before the python3 build error).

I've built this locally with the risc64 sdk with no errors. I have no idea what's going on with the CI :sweat:

**Comment by jefferyto** [comment]
What happened was the build container/runner ran out of disk space. python3 failed to build:

```
if test libpython3.11.so.1.0 != libpython3.11.so; then \
	riscv64-openwrt-linux-musl-gcc -shared -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -L/builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6 -L/builder/staging_dir/target-riscv64_riscv64_musl/usr/lib -L/builder/staging_dir/target-riscv64_riscv64_musl/lib -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -L/builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6 -L/builder/staging_dir/target-riscv64_riscv64_musl/usr/lib -L/builder/staging_dir/target-riscv64_riscv64_musl/lib -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g  -Wl,-hlibpython3.11.so.1.0 -o libpython3.11.so.1.0 Modules/getbuildinfo.o Parser/token.o  Parser/pegen.o Parser/pegen_errors.o Parser/action_helpers.o Parser/parser.o Parser/string_parser.o Parser/peg_api.o Parser/myreadline.o Parser/tokenizer.o Objects/abstract.o Objects/accu.o Objects/boolobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/bytesobject.o Objects/call.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genericaliasobject.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/interpreteridobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/odictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/namespaceobject.o Objects/object.o Objects/obmalloc.o Objects/picklebufobject.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/unicodeobject.o Objects/unicodectype.o Objects/unionobject.o Objects/weakrefobject.o Python/_warnings.o Python/Python-ast.o Python/Python-tokenize.o Python/asdl.o Python/ast.o Python/ast_opt.o Python/ast_unparse.o Python/bltinmodule.o Python/ceval.o Python/codecs.o Python/compile.o Python/context.o Python/dynamic_annotations.o Python/errors.o Python/frame.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/hamt.o Python/hashtable.o Python/import.o Python/importdl.o Python/initconfig.o Python/marshal.o Python/modsupport.o Python/mysnprintf.o Python/mystrtoul.o Python/pathconfig.o Python/preconfig.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pyhash.o Python/pylifecycle.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/pytime.o Python/bootstrap_hash.o Python/specialize.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/thread.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/pystrhex.o Python/dtoa.o Python/formatter_unicode.o Python/fileutils.o Python/suggestions.o Python/dynload_shlib.o     Modules/config.o Modules/main.o Modules/gcmodule.o Modules/atexitmodule.o  Modules/faulthandler.o  Modules/posixmodule.o  Modules/signalmodule.o  Modules/_tracemalloc.o  Modules/_codecsmodule.o  Modules/_collectionsmodule.o  Modules/errnomodule.o  Modules/_io/_iomodule.o Modules/_io/iobase.o Modules/_io/fileio.o Modules/_io/bytesio.o Modules/_io/bufferedio.o Modules/_io/textio.o Modules/_io/stringio.o  Modules/itertoolsmodule.o  Modules/_sre/sre.o  Modules/_threadmodule.o  Modules/timemodule.o  Modules/_weakref.o  Modules/_abc.o  Modules/_functoolsmodule.o  Modules/_localemodule.o  Modules/_operator.o  Modules/_stat.o  Modules/symtablemodule.o  Modules/pwdmodule.o  Modules/xxsubtype.o Python/deepfreeze/deepfreeze.o Modules/getpath.o Python/frozen.o                        -ldl  -lpthread  -lm; \
	ln -f libpython3.11.so.1.0 libpython3.11.so; \
else \
	riscv64-openwrt-linux-musl-gcc -shared -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -L/builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6 -L/builder/staging_dir/target-riscv64_riscv64_musl/usr/lib -L/builder/staging_dir/target-riscv64_riscv64_musl/lib -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -L/builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6 -L/builder/staging_dir/target-riscv64_riscv64_musl/usr/lib -L/builder/staging_dir/target-riscv64_riscv64_musl/lib -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g  -o libpython3.11.so Modules/getbuildinfo.o Parser/token.o  Parser/pegen.o Parser/pegen_errors.o Parser/action_helpers.o Parser/parser.o Parser/string_parser.o Parser/peg_api.o Parser/myreadline.o Parser/tokenizer.o Objects/abstract.o Objects/accu.o Objects/boolobject.o Objects/bytes_methods.o Objects/bytearrayobject.o Objects/bytesobject.o Objects/call.o Objects/capsule.o Objects/cellobject.o Objects/classobject.o Objects/codeobject.o Objects/complexobject.o Objects/descrobject.o Objects/enumobject.o Objects/exceptions.o Objects/genericaliasobject.o Objects/genobject.o Objects/fileobject.o Objects/floatobject.o Objects/frameobject.o Objects/funcobject.o Objects/interpreteridobject.o Objects/iterobject.o Objects/listobject.o Objects/longobject.o Objects/dictobject.o Objects/odictobject.o Objects/memoryobject.o Objects/methodobject.o Objects/moduleobject.o Objects/namespaceobject.o Objects/object.o Objects/obmalloc.o Objects/picklebufobject.o Objects/rangeobject.o Objects/setobject.o Objects/sliceobject.o Objects/structseq.o Objects/tupleobject.o Objects/typeobject.o Objects/unicodeobject.o Objects/unicodectype.o Objects/unionobject.o Objects/weakrefobject.o Python/_warnings.o Python/Python-ast.o Python/Python-tokenize.o Python/asdl.o Python/ast.o Python/ast_opt.o Python/ast_unparse.o Python/bltinmodule.o Python/ceval.o Python/codecs.o Python/compile.o Python/context.o Python/dynamic_annotations.o Python/errors.o Python/frame.o Python/frozenmain.o Python/future.o Python/getargs.o Python/getcompiler.o Python/getcopyright.o Python/getplatform.o Python/getversion.o Python/hamt.o Python/hashtable.o Python/import.o Python/importdl.o Python/initconfig.o Python/marshal.o Python/modsupport.o Python/mysnprintf.o Python/mystrtoul.o Python/pathconfig.o Python/preconfig.o Python/pyarena.o Python/pyctype.o Python/pyfpe.o Python/pyhash.o Python/pylifecycle.o Python/pymath.o Python/pystate.o Python/pythonrun.o Python/pytime.o Python/bootstrap_hash.o Python/specialize.o Python/structmember.o Python/symtable.o Python/sysmodule.o Python/thread.o Python/traceback.o Python/getopt.o Python/pystrcmp.o Python/pystrtod.o Python/pystrhex.o Python/dtoa.o Python/formatter_unicode.o Python/fileutils.o Python/suggestions.o Python/dynload_shlib.o     Modules/config.o Modules/main.o Modules/gcmodule.o Modules/atexitmodule.o  Modules/faulthandler.o  Modules/posixmodule.o  Modules/signalmodule.o  Modules/_tracemalloc.o  Modules/_codecsmodule.o  Modules/_collectionsmodule.o  Modules/errnomodule.o  Modules/_io/_iomodule.o Modules/_io/iobase.o Modules/_io/fileio.o Modules/_io/bytesio.o Modules/_io/bufferedio.o Modules/_io/textio.o Modules/_io/stringio.o  Modules/itertoolsmodule.o  Modules/_sre/sre.o  Modules/_threadmodule.o  Modules/timemodule.o  Modules/_weakref.o  Modules/_abc.o  Modules/_functoolsmodule.o  Modules/_localemodule.o  Modules/_operator.o  Modules/_stat.o  Modules/symtablemodule.o  Modules/pwdmodule.o  Modules/xxsubtype.o Python/deepfreeze/deepfreeze.o Modules/getpath.o Python/frozen.o                        -ldl  -lpthread  -lm; \
fi
/builder/tmp/ccK9WhsQ.s: Assembler messages:
/builder/tmp/ccK9WhsQ.s: Fatal error: can't write 3928 bytes to section .debug_info of /builder/tmp/cc0aOR9D.lto.o: 'No space left on device'
/builder/tmp/ccK9WhsQ.s: Fatal error: /builder/tmp/cc0aOR9D.lto.o: No such file or directory
lto-wrapper: fatal error: /builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/bin/riscv64-openwrt-linux-musl-gcc returned 1 exit status
compilation terminated.
/builder/staging_dir/toolchain-riscv64_riscv64_gcc-12.3.0_musl/bin/../lib/gcc/riscv64-openwrt-linux-musl/12.3.0/../../../../riscv64-openwrt-linux-musl/bin/ld.bfd: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ln: failed to access 'libpython3.11.so.1.0': No such file or directory
make[4]: *** [Makefile:883: libpython3.11.so] Error 1
make[4]: Leaving directory '/builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6'
make[3]: *** [Makefile:780: profile-opt] Error 2
make[3]: Leaving directory '/builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6'
make[2]: *** [Makefile:364: /builder/build_dir/target-riscv64_riscv64_musl/Python-3.11.6/.built] Error 2
time: package/feeds/packages_ci/python3/compile#1096.16#58.04#1544.92
```

rust/host also failed but didn't exit with an error value:

```
install: installing component 'build-manifest'

    build manifest installed.

install: creating uninstall script at /builder/staging_dir/target-riscv64_riscv64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'rustc'
cp: error writing '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/libLLVM-17-rust-1.73.0-stable.so': No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
cp: error writing '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/librustc_driver-d0a8930e4a37ddb4.so': No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
cp: error writing '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/libstd-f9c6b20723dd3eae.so': No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
cp: error writing '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/libtest-6cdc49e9b1b6eaa1.so': No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
./install.sh: line 20: echo: write error: No space left on device
mkdir: cannot create directory '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/rustlib/etc': No space left on device
./install.sh: line 20: echo: write error: No space left on device
install: error: directory creation failed. see logs at '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/rustlib/install.log'
./install.sh: line 20: echo: write error: No space left on device
install: creating uninstall script at /builder/staging_dir/target-riscv64_riscv64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'rust-std-riscv64gc-unknown-linux-musl'
mkdir: cannot create directory '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/rustlib/riscv64gc-unknown-linux-musl': No space left on device
install: error: directory creation failed. see logs at '/builder/staging_dir/target-riscv64_riscv64_musl/host/lib/rustlib/install.log'
time: package/feeds/packages_ci/rust/host-compile#7389.10#294.83#5780.07
```

I have done a [CI run](https://github.com/jefferyto/openwrt-packages/actions/runs/6556538233) of this PR with a custom sdk action that has `AUTOREMOVE` enabled and it succeeded.

**Comment by jefferyto** [comment]
Updates:
* Rebased on current master

**Comment by jefferyto** [comment]
@1715173329 @BKPepe this is ready to be merged :pray:

**Comment by 1715173329** [comment]
> @1715173329 @BKPepe this is ready to be merged 🙏

iirc you have commit access right? Just go ahead ;)

**Review by 1715173329 — APPROVED** [review]

**Pull request merged**
