### PR TITLE
python3-bottle: update to version 0.12.16

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @lperkov 
cc Python maintainers: @jefferyto and @commodo
___
Compile tested: mvebu (cortex-a9_vfpv3) , Turris Omnia, OpenWrt master
Run tested: mvebu (cortex-a9_vfpv3) , Turris Omnia, OpenWrt SNAPSHOT, r9420-c17a68c
together with test "Hello World"
Screenshot from 2019-03-13 17-09-08
Screenshot from 2019-03-13 17-09-36

Description:

- use Py3Package for installation
- update to version 0.12.16 (as included also in Commit message added CPE ID and LICENSE file)

### CODE REVIEW

**Comment by neheb** [comment]
A note: this is unmaintained. You may want to consider taking over maintainership.

**Comment by BKPepe** [comment]
I'm already a maintainer of a few Python packages, so why not. This package will be quite challenging for me, but let's do it! At least I will learn something new about bottlepy. :-)

**Comment by jefferyto** [comment]
LGTM - thanks!

**Comment by commodo** [comment]
LGTM

[LGTM](https://i.pinimg.com/564x/2d/8e/1a/2d8e1a76aba2d7a9e2eeb63f9344463f.jpg)

**Pull request merged**
