### PR TITLE
unbound: update to 1.7.0 and add domain control options

### PR DESCRIPTION
**Pull request by EricLuehrsen**
Maintainer: me
Tested: OpenWrt master / TL-Archer-C7v2
Description:
- Add domain_forward to permit designated domains to forward instead
  of recurse as listed in resolve.conf.auto from DHCP WAN client
- Update rebind_protection and add rebind_interface to protect IP6
  GLA locally just like RFC 1918 protection
- Rename trigger to trigger_interface with backwards compatability
- Update odhcpd script for efficiency handling many clients
- LuCI at https://github.com/openwrt/luci/pull/1692

### CODE REVIEW

**Comment by dibdot** [comment]
@EricLuehrsen just a question/proposal: maybe it makes sense to enhance the "unbound & odhcpd" documentation section regarding DHCPv4 and odhcpd full version!?

**Comment by dibdot** [comment]
@EricLuehrsen Just tested this update and it didn't work for me (unbound plus odhcpd), after reboot I receive the following error:

```
Mon Mar 19 18:25:28 2018 daemon.warn odhcpd[2178]: received DHCPV4_MSG_DISCOVER from 60:be:b5:29:a2:4e
Mon Mar 19 18:25:28 2018 daemon.warn odhcpd[2178]: sending DHCPV4_MSG_OFFER to 60:be:b5:29:a2:4e - 192.168.254.128
Mon Mar 19 18:25:28 2018 daemon.warn odhcpd[2178]: received DHCPV4_MSG_REQUEST from 60:be:b5:29:a2:4e
Mon Mar 19 18:25:28 2018 daemon.warn odhcpd[2178]: sending DHCPV4_MSG_ACK to 60:be:b5:29:a2:4e - 192.168.254.128
Mon Mar 19 18:25:28 2018 daemon.err unbound: [3146:0] error: error parsing local-data at 42 'android-559cb36cdc2d71c3.lan. 120 IN AAAA fd5d:f25a:bd61:62be:b5ff:fe29:a24e': Conversion error, ip6 addr expected
Mon Mar 19 18:25:28 2018 daemon.err unbound: [3146:0] error: error parsing local-data at 42 'android-559cb36cdc2d71c3.lan. 120 IN AAAA fd5d:f25a:bd61:62be:b5ff:fe29:a24e': Conversion error, ip6 addr expected
Mon Mar 19 18:25:28 2018 daemon.info hostapd: wlan1: STA 94:e9:79:d0:37:41 IEEE 802.11: authenticated
Mon Mar 19 18:25:28 2018 daemon.info hostapd: wlan1: STA 94:e9:79:d0:37:41 IEEE 802.11: associated (aid 1)
Mon Mar 19 18:25:28 2018 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 94:e9:79:d0:37:41
Mon Mar 19 18:25:28 2018 daemon.info hostapd: wlan1: STA 94:e9:79:d0:37:41 RADIUS: starting accounting session D1EFDDE1E2BE63EF
Mon Mar 19 18:25:28 2018 daemon.info hostapd: wlan1: STA 94:e9:79:d0:37:41 WPA: pairwise key handshake completed (RSN)
Mon Mar 19 18:25:30 2018 daemon.info unbound: [3146:0] info: service stopped (unbound 1.7.0).

```
If you need more logs or further testing please contact me by mail - thanks!

**Comment by EricLuehrsen** [comment]
Yes. Thanks for reminding me of odhcpd packaging changes.

Could you give me the ULA prefix alone (/64) for your interface? I can infer it from the log, but it is a back check for my sanity. The SLAAC infer part of the DHCP script had a bug where it only accepted [fd00::]/16 for ULA, and its fixed to accept [fd00::]-[fdff::]. The SLAAC formation bug was always there, but normally not exposed to most users. You can work around this by disabling `dhcp4_slaac6` for now.

**Comment by cliobrando** [comment]
Hi, same problem here.
I looked into /etc/config/network for the ULA prefix:
config globals 'globals'
option ula_prefix 'fd39:e78e:203b::/48'

Hope it helps.

**Pull request merged**
