### PR TITLE
perl: update to 5.26.1

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me / @Naoir 
Compile tested: x86_64, generic, LEDE HEAD (61048c9)
Run tested: same

Built an image, and installed it with `sysupgrade`.

Description:

Updates to 5.26.1, fixing several CVE's in 5.24.1.

Note: because we build Perl using miniperl and not full-blown Perl, we need patchset 910 (which won't be accepted upstream since it's only applicable to us).

### CODE REVIEW

**Comment by pprindeville** [comment]
This has been tested on x86_64.  Need help with settings for `files/arm.config`, `files/armeb.config`, `files/i486.config`, etc.

**Comment by pprindeville** [comment]
Is it reasonable to have (for instance) `base.config` do:

```
d_double_style_cray='undef'
d_double_style_ibm='undef'
d_double_style_ieee='define'
d_double_style_vax='undef'
d_long_double_style_ieee='undef'
d_long_double_style_ieee_doubledouble='undef'
d_long_double_style_ieee_extended='undef'
d_long_double_style_ieee_std='undef'
d_long_double_style_vax='undef'
```

and then have `x86_64.config` do:

```
d_double_style_ieee='define'
d_long_double_style_ieee='define'
d_long_double_style_ieee_extended='define'
```

just to keep things simple?

**Comment by pprindeville** [comment]
@champtar, @michailf, @hnyman, @cshoredaniel, @jow-: since you all have had recent commits on Perl (and hence experience with it), I figured you might be able to give good review advice.

There are several CVE's against Perl that 5.26.1 addresses, so this is urgent.  Thanks

**Comment by jow-** [comment]
It makes sense to define the double settings like you proposed. Regarding the arm / armeb compilations, did you try the LEDE armvirt target?

**Comment by pprindeville** [comment]
> Regarding the arm / armeb compilations, did you try the LEDE armvirt target?

@jow- To test the compilation, or to build and boot an image under Qemu or whatever?

**Comment by pprindeville** [comment]
Almost forgot... things like turning on gai_sterror support... do I need to check for MUSL 1.14 vs. 1.15 vs. 1.16 or did they all have them?  Should I add a requirement that if we do have MUSL, it's 1.16 or later?

**Comment by diizzyy** [comment]
Just add a check so it works with the 17.X branch imho

**Comment by stintel** [comment]
Maybe explicitly list the CVEs in the commit message?

**Comment by pprindeville** [comment]
> Regarding the arm / armeb compilations, did you try the LEDE armvirt target?

@jow- Built armvirt target with no issues.

> Maybe explicitly list the CVEs in the commit message?

@stintel: Added.

> Just add a check so it works with the 17.X branch (if needed), that should be enough.

@diizzyy: Building on lede-17.01 branch with no issues.

If I wanted to build an ARM image and try it under libvirt emulation, what are the details?  Would I use `arm64` or `armvirt` with the `realview-eb-mpcore` or `realview-pbx-a9` Qemu models?

**Comment by pprindeville** [comment]
Merging shortly.  If I can figure out how to configure virsh for an `ARM` target and build a matching image for that, I will do so.

**Comment by diizzyy** [comment]
@pprindeville 
You're asking the wrong guy, no experience at all with qemu and aarch64.

**Pull request merged**
