### PR TITLE
lighttpd: LUA dependencies for couple of plugins

### PR DESCRIPTION
**Pull request by ryzhovau**
lighttpd is configured to use LUA for some plugins, see `CONFIGURE_ARGS += ... --with+lua`
Please, add this depencies for `magnet` and `cml` plugins.

### CODE REVIEW

**Comment by thess** [comment]
@MikePetullo -- please review

**Comment by ryzhovau** [comment]
Done.
Sorry for the mess.

**Comment by champtar** [comment]
hi @ryzhovau,
please squash all your commits concerning lighttpd, and remove commits about msmtp

**Comment by champtar** [comment]
@MikePetullo, can you take a look at the ligthttpd modifications

**Comment by MikePetullo** [comment]
This does not look unreasonable, but I need to wait for the final, clean commit per champtar before I do a final review.

**Comment by ryzhovau** [comment]
Made a clean patches, see https://github.com/openwrt/packages/pull/1169

**Pull request closed without merging**
