### PR TITLE
keepalived: depends on file package

### LINKED ISSUE #9819: keepalived: depends on "file" package due to libmagic
Maintainer: Florian Eckert <fe@dev.tdt.de>
Environment: keepalived - 2.0.10-1 , turris omnia 

Description:
keepalived is trying to open /usr/share/misc/magic.mgc , if not found then sigabrt
The magic.mgc is part of "file" package

```
# cat /usr/lib/opkg/info/file.list 
/usr/share/misc/magic
/usr/share/misc/magic.mgc
/usr/bin/file
```

```
[pid 25966] chdir("/etc/keepalived")    = 0
[pid 25966] readv(9, [{"", 0}, {"global_defs {\n   notification_em"..., 1024}], 2) = 1024
[pid 25966] clock_gettime(CLOCK_MONOTONIC, {4840, 441718101}) = 0
[pid 25966] clock_gettime(CLOCK_MONOTONIC, {4840, 441867872}) = 0
[pid 25966] clock_gettime(CLOCK_MONOTONIC, {4840, 442000241}) = 0
[pid 25966] clock_gettime(CLOCK_MONOTONIC, {4840, 442127370}) = 0
[pid 25966] readv(9, [{"", 0}, {" priority 95\n    advert_int 1\n  "..., 1024}], 2) = 408
[pid 25966] clock_gettime(CLOCK_MONOTONIC, {4840, 442554520}) = 0
[pid 25966] readv(9, [{"", 0}, {" priority 95\n    advert_int 1\n  "..., 1024}], 2) = 0
[pid 25966] close(9)                    = 0
[pid 25966] fchdir(10)                  = 0
[pid 25966] close(10)                   = 0
[pid 25966] clock_gettime(CLOCK_MONOTONIC, {4840, 443064437}) = 0
[pid 25966] stat64("/root/.magic.mgc", 0xbeef45a0) = -1 ENOENT (No such file or directory)
[pid 25966] stat64("/root/.magic", 0xbeef45a0) = -1 ENOENT (No such file or directory)
[pid 25966] open("/usr/share/misc/magic.mgc", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
[pid 25966] rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [HUP INT USR1 USR2 TERM], 8) = 0
[pid 25966] gettid()                    = 25966
[pid 25966] tkill(25966, SIGABRT)       = 0
[pid 25966] rt_sigprocmask(SIG_SETMASK, [HUP INT USR1 USR2 TERM], NULL, 8) = 0
[pid 25966] --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=25966, si_uid=0} ---
[pid 25966] rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
[pid 25966] --- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0xb6f76094} ---
[pid 25966] +++ killed by SIGILL +++
<... epoll_pwait resumed> {{EPOLLIN, {u32=3067453264, u64=3067453264}}}, 2, -1, NULL, 8) = 1
clock_gettime(CLOCK_MONOTONIC, {4840, 444547622}) = 0
read(6, "\21\0\0\0\0\0\0\0\2\0\0\0ne\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGILL}], WNOHANG, NULL) = 25966
clock_gettime(CLOCK_REALTIME, {1566671684, 786075500}) = 0
getpid()                                = 25964
sendto(3, "<30>Aug 24 18:34:44 Keepalived[2"..., 78, 0, NULL, 0) = 78
wait4(-1, 0xbeef469c, WNOHANG, NULL)    = -1 ECHILD (No child process)
read(6, 0xbeef46d0, 128)                = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_REALTIME, {1566671684, 786579376}) = 0
getpid()                                = 25964
sendto(3, "<25>Aug 24 18:34:44 Keepalived[2"..., 79, 0, NULL, 0) = 79
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [HUP INT USR1 USR2 TERM CHLD], 8) = 0
gettid()                                = 25964
tkill(25964, SIGTERM)                   = 0
rt_sigprocmask(SIG_SETMASK, [HUP INT USR1 USR2 TERM CHLD], NULL, 8) = 0
timerfd_settime(5, 0, {it_interval={0, 0}, it_value={2147483647, 0}}, NULL) = 0

```

### PR DESCRIPTION
**Pull request by petzah**
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:
 fixes #9819

### CODE REVIEW

**Comment by neheb** [comment]
ping @feckert

**Comment by feckert** [comment]
I do not have seen this error on my build.
@petzah For what does **keepalived** needs this file?
Can you put that in the commit message, please?

**Comment by petzah** [comment]
@feckert
Please check if your build is compiled against libmagic
```
root@omnia:~# ldd /usr/sbin/keepalived 
	/lib/ld-musl-armhf.so.1 (0xb6edd000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb6d27000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb6cce000)
	libmagic.so.1 => /usr/lib/libmagic.so.1 (0xb6ca3000) <==========
	libip4tc.so.0 => /usr/lib/libip4tc.so.0 (0xb6c8d000)
	libip6tc.so.0 => /usr/lib/libip6tc.so.0 (0xb6c77000)
	libxtables.so.12 => /usr/lib/libxtables.so.12 (0xb6c5c000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6c41000)
	libc.so => /lib/ld-musl-armhf.so.1 (0xb6edd000)
	libz.so.1 => /usr/lib/libz.so.1 (0xb6c1e000)
```
It is being used to check security of the scripts which are executed by keepalived.

https://github.com/acassen/keepalived/blob/master/lib/keepalived_magic.h#L32

**Comment by feckert** [comment]
Yes it is build against libmagic.

> root@APU3:~# ldd /usr/sbin/keepalived 
>         /lib/ld-musl-x86_64.so.1 (0x7f473bd80000)
>         libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x7f473baab000)
>         libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x7f473ba31000)
>         libnl-genl-3.so.200 => /usr/lib/libnl-genl-3.so.200 (0x7f473ba28000)
>         libnl-3.so.200 => /usr/lib/libnl-3.so.200 (0x7f473ba0d000)
>         libmagic.so.1 => /usr/lib/libmagic.so.1 (0x7f473b9ed000)
>         libip4tc.so.2 => /usr/lib/libip4tc.so.2 (0x7f473b9e4000)
>         libip6tc.so.2 => /usr/lib/libip6tc.so.2 (0x7f473b9db000)
>         libxtables.so.12 => /usr/lib/libxtables.so.12 (0x7f473b9cd000)
>         libipset.so.13 => /usr/lib/libipset.so.13 (0x7f473b9a0000)
>         libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f473b98c000)
>         libc.so => /lib/ld-musl-x86_64.so.1 (0x7f473bd80000)
>         libz.so.1 => /usr/lib/libz.so.1 (0x7f473b978000)
>         libmnl.so.0 => /usr/lib/libmnl.so.0 (0x7f473b971000)

But I do not get an error at runtime and build time. In the make file there is a dependency for libmagic.
Please see https://github.com/openwrt/packages/blob/master/net/keepalived/Makefile#L63
So I think it is not necessary to depend on file.

**Comment by petzah** [comment]
Ok, must be something else, closing this PR

**Pull request closed without merging**
