### PR TITLE
xfrpc: update to 1.05.561

### PR DESCRIPTION
**Pull request by liudf0716**
Maintainer: @liudf0716 
Compile tested: x86_64, OpenWrt SNAPSHOT r16218+3397-662ceebc4c
Run tested: x86_64, OpenWrt 21.02.2 r16495-bf0c965af0

Description:

support tcp mux feature and default to turn on it

Signed-off-by: Dengfeng Liu <liudf0716@gmail.com>

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
This commit also contains a fix?

**Comment by liudf0716** [comment]
@PolynomialDivision yes. 
in file xfrpc.init, xfrpc should be xfrp instead of xfrpc

**Comment by PolynomialDivision** [comment]
Please put that into a seperate commit with a description and leave it the same PR.

**Comment by liudf0716** [comment]
@PolynomialDivision  u mean I should commit twice?
one commit to fix that bug and the other commit to update xfrpc version and the two commits compose of this PR ?

**Comment by PolynomialDivision** [comment]
lgtm. thanks.

**Comment by liudf0716** [comment]
@PolynomialDivision thanks

**Pull request merged**
