### PR TITLE
net: Fix typos (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by chris5560** [comment]
"net/provioxy" and "net/radicale"
It's ok for me
Thanks

**Comment by stweil** [comment]
> net/provioxy

net/privoxy

**Comment by yousong** [comment]
ack for `net/pppossh`

**Comment by hnyman** [comment]
Let's merge this.
Almost all changes are to comments, a few are to degug/error message strings.
But as far as I see there is no change to any actual code.
Let's see what happens.

**Pull request merged**
