### PR TITLE
ipsec-tools: racoon uci integration

### PR DESCRIPTION
**Pull request by aTanW**
Signed-Off-By: Vitaly Protsko <villy@sft.ru>
---
 b/net/ipsec-tools/Makefile            |   16 -
 b/net/ipsec-tools/files/functions.sh  |  134 ++++++++++
 b/net/ipsec-tools/files/p1client-down |   29 ++
 b/net/ipsec-tools/files/p1client-up   |   29 ++
 b/net/ipsec-tools/files/racoon        |  100 +++++++
 b/net/ipsec-tools/files/racoon.init   |  449 +++++++++++++++++++++++++++++++++-
 b/net/ipsec-tools/files/vpnctl        |   19 +
 net/ipsec-tools/files/racoon.conf     |   36 --
 8 files changed, 759 insertions(+), 53 deletions(-)

### CODE REVIEW

**Comment by champtar** [comment]
@nmeyerhans

**Comment by aTanW** [comment]
So, no changes within more then month?
Will it be done sometime?

**Comment by thess** [comment]
ping @nmeyerhans

**Comment by aTanW** [comment]
Can it be merged without check? 3.5 months too long to wait for each package upgrade.
Such checks are slowing down progress. :)

**Pull request merged**
