### PR TITLE
node: Update to 8.14.1

### PR DESCRIPTION
**Pull request by neheb**
Mainly CVE fixes.

Added a patch to fix compilation without deprecated OpenSSL APIs.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @blogic  @ianchi 
Compile tested: ar71xx

### CODE REVIEW

**Comment by nxhack** [comment]
LGTM

**Comment by cotequeiroz** [comment]
Consider adding the changes from #7653

**Comment by diizzyy** [comment]
I think this should be merged on top of #7653

**Comment by cotequeiroz** [comment]
OK

**Comment by neheb** [comment]
I think this is what was meant?

**Comment by neheb** [comment]
Updated to 8.14.1

Two bug fixes apparently:

    assert:
        revert breaking change (Ruben Bridgewater) #24786
    http2:
        fix sequence of error/close events (Gerhard Stoebich) #24789

**Pull request merged**
