### PR TITLE
python3-dbus: new package

### PR DESCRIPTION
**Pull request by oskarirauta**
Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

Maintainer: Oskari Rauta / @oskarirauta 
Compile tested: x86_64, xeon powered server, recent OpenWRT snapshot
Run tested: x86_64, xeon powered server, recent OpenWRT snapshot

Description:
libdbus1 bindings for python

### CODE REVIEW

**Comment by neheb** [comment]
make package/python3-dbus/refresh

**Comment by oskarirauta** [comment]
> make package/python3-dbus/refresh

What does this do? I re-created my patch to remove whitespace, and it just reverts my patch to what it was, even if I change it's filename, it's reverted again. If I remove $topdir/tmp, it reverts, where does this come from?

**Comment by neheb** [comment]
Correction:

make package/python3-dbus/{clean,refresh}

refresh runs quilt, which is a requirement here.

**Comment by oskarirauta** [comment]
But why are my changes to it reverted? And how?

**Comment by neheb** [comment]
Because quilt refreshes the file to remove fuzz.

**Comment by oskarirauta** [comment]
Where does it get the "original version" from that it refreshes to so I can force it to see my fix?

**Comment by neheb** [comment]
From the patches directory...

I told you to run make package/python3-dbus/{clean,refresh} . When replacing the patch in the patches directory, the old version can remain in the build directory.

**Comment by oskarirauta** [comment]
Everytime I refresh, my 001-whitespace goes bye bye, and 002 reverts to original 002, even though I have changed it.

**Comment by oskarirauta** [comment]
Actually, not this package. I'll fix python3-readline first that has similar situation, can we take this conversation there?

I'll review this one later..

**Comment by neheb** [comment]
```
--- a/lang/python/python3-dbus/patches/001-keep-configuration.patch
+++ b/lang/python/python3-dbus/patches/001-keep-configuration.patch
@@ -1,5 +1,5 @@
---- a/setup.py.orig    2021-04-06 23:04:09.523470957 +0300
-+++ b/setup.py 2021-04-06 23:05:50.476718109 +0300
+--- a/setup.py
++++ b/setup.py
 @@ -25,10 +25,10 @@
  # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  # DEALINGS IN THE SOFTWARE.
@@ -13,7 +13,7 @@
  import os
  import subprocess
  import sys
-@@ -47,27 +47,16 @@
+@@ -47,27 +47,16 @@ class Build(Distribution().get_command_c
      def run(self):
          srcdir = os.getcwd()
          builddir = os.path.join(srcdir, self.build_temp)
```

is your fixed patch.

**Comment by oskarirauta** [comment]
> ...
> is your fixed patch.

Thanks, noticed that too.. Fixing it soon..

**Comment by oskarirauta** [comment]
@neheb - sorry, need assistance with git again, it seems that I rebased to previous commit which was knot-resolver...
Tried to git rebase/master and then force pushed - that way I got knot-resolver out of commit, but still there's issue that commit message was originating from knot-resolver, so I amend replaced it and STILL there's one more issue, formality test fails sine there's still sign of wrong sign-off as mine isn't fine now...

**Comment by oskarirauta** [comment]
And patch is dirty again. make package/python3-dbus/refresh results:
`
if [ -s "/usr/src/openwrt/build_dir/target-x86_64_musl/pypi/dbus-python-1.2.16/patches/series" ]; then (cd "/usr/src/openwrt/build_dir/target-x86_64_musl/pypi/dbus-python-1.2.16"; if quilt --quiltrc=- next >/dev/null 2>&1; then quilt --quiltrc=- push -a; else quilt --quiltrc=- top >/dev/null 2>&1; fi ); fi
Applying patch 001-keep-configuration.patch
patching file setup.py

Now at patch 001-keep-configuration.patch
touch "/usr/src/openwrt/build_dir/target-x86_64_musl/pypi/dbus-python-1.2.16/.quilt_checked"
Applying patch 001-keep-configuration.patch
patching file setup.py

Now at patch 001-keep-configuration.patch
Patch 001-keep-configuration.patch is unchanged
mkdir -p ./patches
rm -f ./patches/* 2>/dev/null >/dev/null
'/usr/src/openwrt/build_dir/target-x86_64_musl/pypi/dbus-python-1.2.16/patches/001-keep-configuration.patch' -> './patches/001-keep-configuration.patch'
make[2]: Leaving directory '/usr/src/openwrt/feeds/packages2/lang/python3-dbus'
time: package/feeds/packages2/python3-dbus/refresh#0.96#0.60#1.36
make[1]: Leaving directory '/usr/src/openwrt'
`

So no issues there. @dangowrt - little help here? I have 1 more python related package that AppArmor is dependant..

**Comment by oskarirauta** [comment]
Better to once again create a new PR after all :(

**Pull request closed without merging**
