### PR TITLE
htop: update to 3.1.0

### PR DESCRIPTION
**Pull request by hnyman**
Update htop to version 3.1.0

* Adjust Makefile configuration options to update
   (affinity, sensors)
* Backport post-release fix for old automake versions (like ours)
    Fixes: https://github.com/htop-dev/htop/issues/803
    PR: https://github.com/htop-dev/htop/issues/810
* Switch to PKG_RELEASE autorelease in Makefile

Maintainer:  @champtar 
Run tested: ipq806x/R7800, mt7622/RT3200

### CODE REVIEW

**Comment by hnyman** [comment]
@champtar 
Any objections?

**Comment by champtar** [comment]
Sorry forgot about it, thanks for the update !

**Comment by anomeome** [comment]
Needed?

```
Package htop is missing dependencies for the following libraries:
libnl-3.so.200
libnl-genl-3.so.200
make[3]: *** [Makefile:83: /home/kc/wrtpac/source/bin/targets/mvebu/cortexa9/packages/htop_3.1.0-1_arm_cortex-a9_vfpv3.ipk] Error 1
make[3]: Leaving directory '/home/kc/wrtpac/source/feeds/packages/admin/htop'

```

**Comment by champtar** [comment]
I'll have a look later today or tomorrow to fix that

**Comment by champtar** [comment]
(on my phone) Need --disable-delayacct, but also --disable-unwind, and --disable-sensors when not enabled (they changed some conf to 'check' by default)

**Pull request merged**
