### PR TITLE
geth: Update to 1.8.13

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: ???

### CODE REVIEW

**Comment by hnyman** [comment]
cc @mislavn

**Comment by karlp** [comment]
This is a ~new package with a fairly responsive maintainer so far, is there any particular reason you need to "help them" keep this package up to date?  You've included no test information to verify that the new version works, do you use this package or just doing "bleeding edge just because" changes?

**Comment by karlp** [comment]
Comiit message makes no mention of what's changed, or links to any changelog either.

**Comment by mislavn** [comment]
I actually already tested the package and forgot to make the pull request.

**Pull request merged**
