### PR TITLE
Cloudflare v4: Update ddns record, not overwrite it

### PR DESCRIPTION
**Pull request by patryk**
- changed PUT to PATCH: updates existing record with new data, not overwrites it with default values
- changed brand name CloudFlare -> Cloudflare
- removed explicit proxied setting, keeps Orange/Gray cloud unchanged

### CODE REVIEW

**Comment by Ansuel** [comment]
why remove proxied settings ?

**Comment by patryk** [comment]
Because some people may want it, some don't. Removing proxied here and changing HTTP method to PATCH will preserve whatever they have set already in UI.

**Comment by Ansuel** [comment]
> Because some people may want it, some don't. 

Then you should permit the user to chose...

think you should modify the script with 2 variant, one with proxied setting enabled, one with disabled (set proxied disabled by default) 
What you think?

**Comment by patryk** [comment]
The best way would be to make proxied optional and only send if set. But for some strange reason when I do edit in Luci it barks at me that:
`Basic Settings - Optional Parameter: missing / required`

Maybe I'm missing something?

**Comment by patryk** [comment]
Made updates you requested. Hope everything is good now.

**Comment by Ansuel** [comment]
anyway @hnyman  good for me... 

i checked the code and the proxy option is already optional (set that value empty should produce no error...)  That error refer to the Optional input tab that should already be fixed... (Old luci-app-ddns package?)

**Comment by patryk** [comment]
I'm using Turris OS, which should have it's scripts from here: https://gitlab.labs.nic.cz/turris/turris-os-packages/tree/test/net/ddns-scripts

**Comment by Ansuel** [comment]
i was talking about luci-app-ddns

**Comment by patryk** [comment]
Ah, sorry! luci-app-ddns is at 2.4.8-1.

**Comment by Ansuel** [comment]
well we are at 2.4.9-5

**Comment by patryk** [comment]
Updated 'proxied' parameter to be boolean, not a string.

**Comment by hnyman** [comment]
cc @chris5560

**Pull request closed without merging**
