### PR TITLE
package/wireguard bump version to 0.0.20161216

### PR DESCRIPTION
**Pull request by viisauksena**
package/wireguard bump version to 0.0.20161216
Signed-off-by: Jens Viisauksena github_patch@viisauksena.de

### CODE REVIEW

**Comment by zorun** [comment]
@hnyman Please do not merge changes without an ACK or NACK from the maintainer (me, in this case)

This version has a known endianness issue, see https://lists.zx2c4.com/pipermail/wireguard/2016-December/000782.html and #3664 

I was waiting for the new release before updating the OpenWRT package.

**Comment by hnyman** [comment]
Sorry, I overlooked that viisauseksena was not the maintainer.

Should that merge be reverted? (As there is a known issue.)

**Comment by zorun** [comment]
Yes please, I don't know when the new version will be released.

**Comment by hnyman** [comment]
I reverted it with #3671

**Comment by viisauksena** [comment]
this is one of the "released" versions, since wireguard use snapshot for "milestones" - we have done so with all the other versions before, i build this version here and tested it succesfully on 2 tp-link router models

**Pull request merged**
