### PR TITLE
madplay: import from old packages feed

### PR DESCRIPTION
**Pull request by probonopd**
https://dev.openwrt.org/ticket/18713

### CODE REVIEW

**Comment by thess** [comment]
Ancient and venerable player -- looks good except your commits need  Signed-off-by tags. No need to sign-off PR.

**Comment by probonopd** [comment]
How do i retroactively add the Signed-off-by tags to the 2 commits?

**Comment by thess** [comment]
You could do it simply while rebasing/squashing interactively the 2 commits into 1.

Ex: git rebase -i HEAD~2

Then add signed-off tag with an editor. 'git commit --amend' can also be used. If you have your git profile setup for sign-off, use -s with commits.

**Comment by thess** [comment]
Sorry, one more request -- Your commit comments do not start with the package name (missed that before) and it would be really good if you could rebase this into a single commit.

**Comment by thess** [comment]
Thanks for you patience

**Comment by thess** [comment]
@sbyx -- please remove madplay from oldpackages.

**Comment by probonopd** [comment]
Thanks for helping me with my first package submission.

**Pull request merged**
