### PR TITLE
lighttpd: update to lighttpd 1.4.60 release hash

### PR DESCRIPTION
**Pull request by gstrauss**
Maintainer: @flyn-org
Compile tested: i386 OpenWrt master

Description:
lighttpd: update to lighttpd 1.4.60 release hash
also remove patches incorporated upstream into lighttpd 1.4.60

Signed-off-by: Glenn Strauss <gstrauss@gluelogic.com>

### CODE REVIEW

**Comment by gstrauss** [comment]
I am not sure why this failed on x86_64 so early in the process (well before lighttpd compilation).  Please resubmit the pipeline to see if this is a transient error.  Thanks. 
```
make[3]: Entering directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12'
make -C /home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.70 M=/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12 ARCH=x86 CROSS_COMPILE=x86_64-openwrt-linux-musl- modules
make[4]: Entering directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.70'
make[5]: *** No rule to make target '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12/ioctl.o', needed by '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12/cryptodev.o'.  Stop.
make[4]: Leaving directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.70'
make[4]: *** [Makefile:1822: /home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12] Error 2
make[3]: *** [Makefile:27: build] Error 2
make[3]: Leaving directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12'
make[2]: *** [Makefile:61: /home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/cryptodev-linux-cryptodev-linux-1.12/.built] Error 2
make[2]: Leaving directory '/home/build/openwrt/feeds/base/package/kernel/cryptodev-linux'
time: package/feeds/base/cryptodev-linux/compile#0.94#0.42#1.30
    ERROR: package/feeds/base/cryptodev-linux failed to build.
make[1]: *** [package/Makefile:116: package/feeds/base/cryptodev-linux/compile] Error 1
```

**Comment by flyn-org** [comment]
I am happy with this, assuming we can identify the cause of the build error. @neheb, I think I have seen the error @gstrauss encountered above before. Is this a build-system artifact? Really glad to see @gstrauss here---happy to see patches upstreamed so efficiently!

**Comment by neheb** [comment]
That error is with cryptodev. Please ignore.

**Comment by gstrauss** [comment]
@neheb PR is ready for you.  Builds pass except for x86_64 cryptodev

@flyn-org should I submit lighttpd-1.4.60 to update the openwrt-21.02 branch? older branches? (of course, doing so after waiting a few weeks for lighttpd 1.4.60 to settle)

If not, may I submit a smaller set of patches backported from lighttpd 1.4.60 to lighttpd 1.4.59 for openwrt-21.02?  I put together a short list of useful patches in https://salsa.debian.org/debian/lighttpd/-/merge_requests/36 though that merge request will probably be withdrawn and re-filed against a different Debian branch.

(BTW, openwrt-19.07 has lighttpd 1.4.54 and is missing important fixes in 1.4.55)

**Comment by flyn-org** [comment]
I would like to see packages of the latest upstream lighttpd version for OpenWrt 19.07 and 21.02 if you are up for it. @neheb, does this sound reasonable? I recall someone once objecting to an update for the non-master OpenWrt versions that was not a security update or bugfix. I would have thought we would want to keep things moving as long as configuration file formats don't change.

**Comment by gstrauss** [comment]
lighttpd 1.4.55 is a very safe upgrade from lighttpd 1.4.54, and lighttpd 1.4.55 contains more than a handful of important bugfixes.  Upgrading from lighttpd 1.4.54 to lighttpd 1.4.55 is much preferred to pulling 10+ patches to backport to lighttpd 1.4.54.  I think we should target lighttpd 1.4.55 to 19.07, and I'll try to put together a PR for 19.07 with lighttpd 1.4.55 in the next few days.

lighttpd 1.4.56 made major changes to mod_openssl, using more modern openssl interfaces, and while these changes fixed some long-standing issues, there were a few reports of (mostly backwards) configurations which broke.

lighttpd 1.4.59 enables HTTP/2 by default, and that might surprise some people running older versions of lighttpd, but 21.02 is already running lighttpd 1.4.59.

lighttpd 1.4.60 improves and tunes HTTP/2 support, and so I highly recommend it as an upgrade for 21.02.  However, since lighttpd 1.4.60 was just released, I will hold off on a PR for 21.02 for a few weeks.

**Pull request merged**
