### PR TITLE
bonding: allow xmit_hash_policy in 802.3ad mode

### PR DESCRIPTION
**Pull request by LGA1150**
Maintainer: @he-ma 
Compile tested: WRT1900AC
Run tested: WRT1900AC

Description:
Allow the transmit hash policy to be changed in 802.3ad mode.

thx @elvisimprsntr

### CODE REVIEW

**Comment by he-ma** [comment]
Thank you, you are right. This is an error and needs to be fixed in the LuCI proto handler, too (I'll do it later)
Please update the PKG_RELEASE in Makefile, too.

**Comment by LGA1150** [comment]
Done

**Comment by he-ma** [comment]
@neheb 
Would you please merge this PR.
Thank you

**Comment by BKPepe** [comment]
In the OP there is mentioned that compile and run test will be done. Is it except CI? Real testing on the real device would be nice.

**Comment by LGA1150** [comment]
Run test done by @elvisimprsntr

**Comment by elvisimprsntr** [comment]
> In the OP there is mentioned that compile and run test will be done. Is it except CI? Real testing on the real device would be nice.

Test done, but still have to manually add xmit_hash_policy to /etc/conf/network file.  

LuCi does not yet have option

**Comment by he-ma** [comment]
PR for the bugfixed 'Transmit Hash Policy' assignment to corresponding bonding policies:
https://github.com/openwrt/luci/pull/5201

**Comment by he-ma** [comment]
@neheb 
Thank you for merging.

**Pull request merged**
