### PR TITLE
squashfs-tools: pull newer version from git repo

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: LEDE v17.01.3 powerpc64
Run tested: LEDE v17.01.3 powerpc64

-----------------------------------------------------

squashfs-tools does not provide tar-balls.
It looks like a good time to pull a newer version
that obsoletes a few accepted patches.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
I think that you need to update also PKG_MIRROR_HASH

**Comment by commodo** [comment]
@hnyman 
can you tell me how to calculate that hash ?
it's not obvious to me yet, and i figured it would be quicker to ask

**Comment by hnyman** [comment]
One way is to look at the Travis output:

> WARNING: PKG_MIRROR_HASH does not match squashfs-tools-4.3-5be5d61e5e5a93911256b5f2106e50da0ca81e8d.tar.gz hash eac1bc559708dc8656fe7d099ffc9e9374ae0cfb9a12d180a9c0c28acb0adf11

Or a manual hash calculation with sha256 from your own download dir should also produce the same.

**Comment by commodo** [comment]
ohhhh
is that what PKG_MIRROR_HASH is
i thought for some reason it's something more complicated that PKG_HASH

will update
thanks

**Comment by commodo** [comment]
all green ;
thanks for the hint @hnyman

**Comment by zorun** [comment]
@commodo there is some documentation here: https://wiki.openwrt.org/doc/devel/packages#use_source_repository

**Comment by commodo** [comment]
thanks for the hint :)

**Pull request merged**
