### PR TITLE
net-snmp: backport signal patch

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation with uClibc-ng.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @stintel 
Compile tested: ath79

Seems to be causing long range build failures.

https://downloads.openwrt.org/snapshots/faillogs/arc_archs/packages/net-snmp/compile.txt

### CODE REVIEW

**Comment by stintel** [comment]
Runtime tested missing.

**Comment by neheb** [comment]
I don't have a UPS to test with.

In any case, this is just a compilation fix.

**Comment by neheb** [comment]
New buildbots are happy.

**Comment by stintel** [comment]
Can you please not merge things when you were asked for a runtime test by the maintainer?

**Comment by neheb** [comment]
Normally I would agree, but this is only a compilation fix. It only changes the timer from using signal() to clock_gettime. There's no functionality change.

**Pull request merged**
