### PR TITLE
strongswan: Fix PSKs when using multiple connections

### LINKED ISSUE #19757: strongswan multiple connections with PSK
Maintainer: @pprindeville
Environment: (mipsel_24kc, model, 22.03)

Description:

Actually there are 2 bugs in swanctl.init when using multiple connections with PSK auth (because of this 2 bugs in some scenarios you can only get one working connection at the time (because all defined PSKs are "overwritten" by the last PSK- not literally, they are just ignored by strongswan, because it matches one PSK and uses only this one ):

1) local_identifier and remote_identifier from /etc/config/ipsec are ignored - they don`t show in (/var/swanctl/swanctl.conf) secrets section, because this code uses undefined local_id and remote_id instead of them (probably something old) :

```
		if [ -n "$local_id" ]; then
			swanctl_xappend2 "id1 = $local_id"
			if [ -n "$remote_id" ]; then
				swanctl_xappend2 "id2 = $remote_id"
			fi
		fi
```

2) when using multiple connections in /etc/config/ipsec, multiple NOT unique secret sections are created in /var/swanctl/swanctl.conf. According to strongswan documentation they should be unique: "Each IKE PSK is defined in a unique section having the ike prefix."
This is caused by hardcoded section name "ike":

```
		swanctl_xappend0 "secrets {"
		swanctl_xappend1 "ike {"
		swanctl_xappend2 "secret = $pre_shared_key"
```

we could make it unieque by using the connection name in the ike section like this:

```
		swanctl_xappend0 "secrets {"
		swanctl_xappend1 "ike-$config_name {"
		swanctl_xappend2 "secret = $pre_shared_key"

```

### PR DESCRIPTION
**Pull request by krux2222**
Maintainer: @pprindeville, @Thermi 
Compile tested: N/A
Run tested: N/A

Description:

Fixes issue #19757

### CODE REVIEW

**Comment by krux2222** [comment]
@BKPepe could you enable workflows again? I`ve fixed formalities, commit should pass the tests now

**Comment by krux2222** [comment]
@pprindeville, @Thermi could you review this quick fix?

**Comment by Thermi** [comment]
Looks good

**Comment by pprindeville** [comment]
I need confirmation that there's been a build and some unit testing...

**Pull request closed without merging**
