### PR TITLE
libs/libpng: Add more symlinks

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @jow-
Compile tested: ramips, MQMaker WiTi board, LEDE trunk
Run tested: Not done

Description:
Sprinkle more symlinks for compatibility

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by pprindeville** [comment]
I just cherry-picked this fix and built it:

```
$ ls -l build_dir/target-x86_64_westmere_musl_powercode-bmu/libpng-1.6.29/ipkg-xeon/libpng/usr/lib/
total 172
lrwxrwxrwx 1 philipp philipp     19 Apr 16 12:10 libpng16.so -> libpng16.so.16.28.0*
lrwxrwxrwx 1 philipp philipp     19 Apr 16 12:10 libpng16.so.16 -> libpng16.so.16.28.0*
-rwxr-xr-x 1 philipp philipp 172035 Apr 16 12:10 libpng16.so.16.28.0*
lrwxrwxrwx 1 philipp philipp     11 Apr 16 12:10 libpng.so -> libpng16.so*
$ 
```

but we still need the headers to go into `usr/include/libpng/` and not `usr/include/libpng16`.

**Comment by val-kulkov** [comment]
Found this PR after submitting mine a few minutes ago that addresses the same issue.

@diizzyy : I have no objections over your way of addressing the missing symlinks issue. However, you may want to make your version of Makefile shorter by using the {,16} syntax. Saves the space and reduces the likelihood of typos.

@pprindeville : there should be no need to create usr/include/libpng in addition to usr/include/libpng16. usr/bin/libpng-config provides this information:

`includedir="${prefix}/include/libpng16"`

and that should be enough. I was able to successfully compile php7-mod-gd that depends on libpng after making changes to libpng's Makefile as detailed in my PR#4269.

To those with merge privileges: I do not care which PR gets accepted into the trunk, this one or PR#4269.

**Comment by diizzyy** [comment]
@pprindeville 
Better now?

**Comment by pprindeville** [comment]
> I was able to successfully compile php7-mod-gd that depends on libpng after making changes to libpng's Makefile as detailed in my #4269.

@val-kulkov I was not able to get things to build with either PR #4269 or #4266 without https://github.com/openwrt/packages/pull/4263/files#diff-39ad31447c6af3d75f02289823a9116f being present.

**Comment by diizzyy** [comment]
https://svnweb.freebsd.org/ports/head/graphics/png/pkg-plist?revision=436720&view=markup
Let's just mimick what FreeBSD does and all will be fine :-)

**Comment by pprindeville** [comment]
> Let's just mimick what FreeBSD does and all will be fine :-)

So you'd need to put `pnglibconf.h` into $(STAGING_DIR)/usr/include as a symlink to `libpng16/pnglibconf.h` if I've understood...

But, equally curious... why isn't the pkgconfig file being used by PHP?

**Comment by hnyman** [comment]
Let's try this one.

**Comment by pprindeville** [comment]
> Let's try this one.

Works for me, thanks!

**Pull request merged**
