### PR TITLE
squeezelite: add new package(s)

### PR DESCRIPTION
**Pull request by squeezewrt**
Squeezelite (https://code.google.com/p/squeezelite/)
is a small headless squeezebox emulator for linux using alsa audio output.
It is aimed at supporting high quality audio including usb dac based output
at multiple sample rates including 44.1/48/88.2/96/176.4/192k/352.8/384kHz

About a half of year I use squeezelite running in TL-MR3220 (32Mb RAM and 4Mb Flash) as network music player in my home audio system. It plays without distortions and data losses high-bitrate (24bit/192KHz) audio over Ethernet or WiFi. 
My topic about this on the Hi-fi forum (in Russian): http://hi-fidelity-forum.com/forum/thread-107334.html

There are 3 packages in this pull request:
sound/squeezelite: an executable with startup script and default config file
sound/luci-app-squeezelite: LuCI application to configure squeezelite
utils/lirc: from oldpackages with minimal changes

Signed-off-by: Andrew Kazakov <squeezewrt.ak@gmail.com>

### CODE REVIEW

**Comment by sbyx** [comment]
Thanks a lot for the PR. I have 2 comments.
1. Please put the PKG_LICENSE and PKG_MAINTAINER in the top-level of the makefile where PKG_NAME and friends are.
2. The version of lirc you want to add is from 2010. Is there any specific reason you did not update it?

**Comment by squeezewrt** [comment]
1'st sorry about my bad English!
Regarding to your comments:
1) PKG_LICENSE and PKG_MAINTAINER are moved closer to PKG_NAME in all 3 makefiles
2) I was unable to upgrade to the actual LIRC version due to compilation errors. Makefile changes necessary, but LIRC poorly documented (as for me). Maybe I'll get to it later.

**Comment by thess** [comment]
@squeezewrt - Thanks for this submission. I would be very interested in getting squeezelite integrated into the OpenWrt packages. My initial concern is this should really be 2 or 3 independent submissions - it will be easier to work with. You do need to cleanup the commit messsages and squash/rebase your latest updates appropriately.

* lirc (lircd & liblirc) should be a separate submission and updated to the latest version. This is something I could help you with (we could decide on the package maintainer later)
* squeezelite has some config issues I noted. In particular you requre ffmeg-mini always and have made FLAC, MP3, AAC & OGG optional.I think ffmpeg (which is only used by squeezelite for WMA and ALAC) should also be optional. Also note that ALAC support is __not__ in ffmpeg-mini config.
*  squeezelite PKG_BUILD_DEPENDS options should be made as actual DEPENDS by config options. There is no need to build them if not selected.
* Just my opinion - The luci app could be a proper luci package/submission to the luci repo (https;//github.com/openwrt/luci)  to make use of translation and source compression if built withing the luci framework.

Now to go off and spin-up a Logitech Media Server and give it a try soon.

**Comment by squeezewrt** [comment]
**@thess** - Do I understand (my english is very bad), what do you propose to close this PR and create 3 new, separately for the squeezelite in packages, luci-app-squeezelite in luci and lirc in packages?

**Comment by thess** [comment]
Yes, that is essentially what I proposed that YOU do if you wish to be the maintainer. However, I am willing to do some of the work on lirc to get it updated.

**Comment by squeezewrt** [comment]
**@thess**
OK, I close this PR

**Pull request closed without merging**
