### PR TITLE
uacme: Add support custom CAs and TLS-ALPN-01 challenge

### PR DESCRIPTION
**Pull request by mundschenk-at**
Maintainer: @lucize
Run tested: with Step-CA

Description:
Adds support for using a custom CA with `uacme` (e.g. a private Step-CA deployed on the local network), as well as the `TLS-ALPN-01` challenge type. The patch was originally described in https://forum.openwrt.org/t/custom-ca-for-ssl-certificates/160156/3.

These modifications assume the following extra keys in the `acme` section:
```
    option acme_url <CA_DIRECTORY_URL>
    option acme_staging_url <CA_DIRECTORY_URL>
```
as well as an additional key in the specific `certificate` section:
```
    option tls 1
``` 
to enable `TLS-ALPN-01`

This is not really ideal, I think the challenge type should be an explicit key combining all the different modes, but I didn't want to change the OpenWrt default too much.

In addition to those changes, I've also added a `ualpn` to `rc.local` and set up `uhttpd` to only listen on the localhost interface:
```
ualpn -c 127.0.0.1@443 -d -b <my_lan_ip>@443 -P 0
```
The important part is `-P 0` to disable the proxy protocol, `uhttpd` does not like it.

### CODE REVIEW

**Comment by lucize** [comment]
LGTM

**Review by systemcrash — APPROVED** [review]

**Comment by 1715173329** [comment]
> mundschenk-at@users.noreply.github.com

Please use your real email address instead of "noreply".

**Comment by mundschenk-at** [comment]
> Please use your real email address instead of "noreply".

For the sign-off you mean?

**Comment by 1715173329** [comment]
> For the sign-off you mean?

Yes, please update your git settings, fyi:
https://openwrt.org/submitting-patches#submission_guidelines

**Comment by mundschenk-at** [comment]
@1715173329 I've updated the commit (hopefully correctly this time).

**Review by 1715173329 — APPROVED** [review]
lgtm, thanks!

**Comment by mundschenk-at** [comment]
Mhm, not sure what's the deal with those failed docker builds - can't have anything to do with the package.

**Comment by 1715173329** [comment]
> Mhm, not sure what's the deal with those failed docker builds

They're known broken.

**Comment by 1715173329** [comment]
Merged, thank you!

**Pull request merged**
