### PR TITLE
python,python3,pip,setuptools: unify pip & setuptools under python,python3

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/lede-project/source/commit/0e22d6377569cea4ba00b81d6ec64a1582a2cea4 x86_64
Run tested: https://github.com/lede-project/source/commit/0e22d6377569cea4ba00b81d6ec64a1582a2cea4 x86_64

Description:

The culmination of a few weeks of work.

`python, python-setuptools, python-pip` : are all now under `python`
`python3, python3-setuptools, python3-pip` : are all now under `python3`

For me, as a maintainer, this means that I have to update just 2 Makefiles, which will reduce my work-load a bit.
I'm also hoping that the bundled pip & setuptools that come with Python/Python3 are a bit more robust, since they are a bit more tested.

All-in-all, this patch also upgrades pip from 8.1.2 to 9.0.1  and python setuptools from 27.2.0 to 28.8.0.
Admittedly, not the latest versions, but ¯\_(ツ)_/¯

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
need to check something first

**Comment by commodo** [comment]
all good

**Comment by commodo** [comment]
hmmm ; 
so, on build bot it's not as pretty as it was on my local machine/test
will try to reproduce locally and come back

**Comment by commodo** [comment]
@hnyman 
I'm puzzled ; 
buildbot fails on x86_64 : http://downloads.lede-project.org/snapshots/faillogs/x86_64/packages/python/

Does not seem to fail on other platforms.

I tried on OpenSUSE Leap & Debian 8.7 
It builds fine for me ; target x86_64

Any ideas ?
Or is buildbot faulting now ?

**Comment by hnyman** [comment]
You might wait one more day with the buildbot. The LEDE buildbot has been rather unstable the last 2-3 days, although now it seems to have stabilized to a large extent. There were large changes to buildbot logic plus simultaneous changes to the Makefiles. And the two-phase logic of the buidbot system make it a rather slow process to get all changes trickled down to the phase2 package build (as the changes need to get compiled in the phase1 SDK step first, so that that SDK can be used in phase2).

**Comment by commodo** [comment]
w00h00
win ; they're gone now

**Pull request merged**
