### PR TITLE
python-zipp: remove myself as maintainer

### PR DESCRIPTION
**Pull request by aparcar**
Remove myself as maintainer, I'm happy that somebody else takes care.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by BKPepe** [comment]
Commit message is wrong.

**Comment by aparcar** [comment]
@BKPepe I change the commit message, if your point was something else, please point it out.

**Comment by BKPepe** [comment]
Yes, now it is better. Thanks.

**Comment by aparcar** [comment]
Thanks for your feedback. I'll merge this tomorrow if nobody objects.

**Pull request merged**
