### PR TITLE
quasselc: Update to latest commit

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @TC01 
Compile tested: mvebu

### CODE REVIEW

**Comment by diizzyy** [comment]
You can also use codeload

**Comment by neheb** [comment]
This is not a tagged release.

**Comment by diizzyy** [comment]
You can still use codeload though if you want

**Comment by neheb** [comment]
Yeah sure why not. Added some minor adjustments as well.

**Comment by neheb** [comment]
I just realized quassel-irssi is using this as a submodule. It might make sense to get rid of this package.

**Comment by TC01** [comment]
Hey, thanks for looking at this. I admit I haven't really had the time to stay on top of quassel-irssi in openwrt. Do I need to do to something to sign off on PRs?

I unbundled quasselc here because I unbundled it in Fedora, too (where I am also the maintainer)-- in theory, other software could have wanted to use libquasselc. In practice, that hasn't happened, and the upstream project isn't super active anyway so... re-bundling this with quassel-irssi may make sense.

**Comment by neheb** [comment]
Ehhh no. LGTM or whatever works.

Does other software in Fedora use quasselc?

**Comment by TC01** [comment]
No, it's just standard [policy](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries) to try and unbundle where possible.

**Comment by neheb** [comment]
@hnyman As the irssi variant is now using the bundled version, this package is obsolete. CircleCI can't handle package removal seems like.

**Comment by neheb** [comment]
Since this package doesn't want to get removed, I updated it instead, as was originally done.

Rebased against current master as well.

**Comment by cshoredaniel** [comment]
@neheb for this sort of package I don't have complaints about less than fully tested updates because otherwise it's just bitrot -- with maintainers who aren't as active as you'd like (but who do participate) I think more patience ought to be in play.  Life happens to maintainers and I know I'd be rather annoyed if I was on vacation or a couple weeks and found out that packages had non-urgent stuff pushed, especially if it wasn't something I'd haved acked as-is.

**Comment by neheb** [comment]
Maintainer previously ACKed this.

Upstream is basically dead. Only one package uses this.

**Comment by cshoredaniel** [comment]
@neheb er, I was agreeing with you on this sort of package, given the lack of appetite for removal even when it's pretty obvious it's warranted (IMO).

**Comment by BKPepe** [comment]
Hmm, ok.

**Comment by BKPepe** [comment]
Guys, okay. Its pretty obvious to remove it. Time changed, things happened. Let's get rid of it. I will prepare PR.

**Pull request merged**
