### PR TITLE
[23.05]powertop: update to 2.15

### PR DESCRIPTION
**Pull request by p-w-p**
Maintainer: @lucize
Compile tested: all supported targets
Run tested: armv8, snapshot/23.05

Description:
PowerTOP v2.15 release mainly focuses on bug fixes and patching compatibility issues. Also, adds support to multiple platforms.
Removed obsolete patch as upstream has fixed.https://github.com/fenrus75/powertop/commit/9ef1559a1582f23d599c149601c3a8e06809296c

### CODE REVIEW

**Comment by neheb** [comment]
Use git cherry-pick -x instead.

**Comment by p-w-p** [comment]
> Use git cherry-pick -x instead.

I have a question. Regarding the master branch using tar.zst and the 23.05 branch using tar.gz, if the hashes are inconsistent, how should I use cherry-pick? Should I cherry-pick first and then commit once more to fix the hash?

**Comment by neheb** [comment]
ah I forgot about that. nvm then.

**Comment by 1715173329** [comment]
> I have a question. Regarding the master branch using tar.zst and the 23.05 branch using tar.gz, if the hashes are inconsistent, how should I use cherry-pick? Should I cherry-pick first and then commit once more to fix the hash?

Like this commit: 4702db28655b3dda786f9673918de9d6c145f79, you can add a comment for it.

Of course it's okay to leave it as-is.

**Comment by p-w-p** [comment]
> > I have a question. Regarding the master branch using tar.zst and the 23.05 branch using tar.gz, if the hashes are inconsistent, how should I use cherry-pick? Should I cherry-pick first and then commit once more to fix the hash?
> 
> Like this commit: [4702db2](https://github.com/openwrt/packages/commit/4702db28655b3dda786f9673918de9d6c145f798), you can add a comment for it.
> 
> Of course it's okay to leave it as-is.

I am deeply grateful for your assistance. Thanks. :D

**Pull request merged**
