### PR TITLE
btrfs-progs: Update to 4.13.3

### PR DESCRIPTION
**Pull request by neheb**
Tested on ramips (mt7621)

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Is this repo meant to be compatible with OpenWRT or LEDE? I ask since the single patch in the code is unnecessary since Musl 1.1.15.

**Comment by neheb** [comment]
One other question. Since this package seems to lack a maintainer, any objections to putting my name on here?

**Comment by champtar** [comment]
Hi @neheb 
You are more than welcome to become the maintainer of this package
The soon to come remerge will keep LEDE for master, so working with LEDE is enough for me

**Comment by neheb** [comment]
Cool. deleted the patches directory and added myself as maintainer.

**Pull request merged**
