### PR TITLE
[19.07] Softethervpn5: update to 5.01.9674

### PR DESCRIPTION
**Pull request by Andy2244**
Maintainer: me
Compile tested: arm (19.07)
Run tested: arm/qemu (19.07)

Description:
* update to 5.01.9674

### CODE REVIEW

**Comment by neheb** [comment]
I assume you want it backported?

**Comment by Andy2244** [comment]
> 
> 
> I assume you want it backported?

What? Yes its for 19.07

**Comment by neheb** [comment]
Doesn't seem master has this.

**Comment by neheb** [comment]
Never mind. https://github.com/openwrt/packages/commit/9c756cf618d501baaf309e1054024a546d123bb1 mentions the wrong version.

**Comment by Andy2244** [comment]
ups my fault on this PR

**Pull request merged**
