### PR TITLE
libmicrohttpd: Update to 0.9.62

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lynxis 
Compile tested: ramips

### CODE REVIEW

**Comment by diizzyy** [comment]
The Makefile needs a bit more love, I have a more polished one in the works please wait a few days as I'd like to runtest this change.

**Comment by diizzyy** [comment]
https://github.com/diizzyy/packages/commit/c2c4054d21cbb4fe4bdf792effe7c1ea313d6b52
I'm aware of that the default non ssl version will "break" a few packages but it's more consistent than the other way around (including naming) and can be easily fixed for package that depends on libmicrohttpd.

**Comment by diizzyy** [comment]
@hnyman 
Please back this out, it's not tested and we have reported failures depending on applications depending libmicrohttpd. https://github.com/openwrt/packages/issues/7473
I'd rather see such issues resolved and tested before changing libs.

**Comment by hnyman** [comment]
Sure I can back it out, if that new version is problematic.  
42700544f

**Pull request merged**
