### PR TITLE
python-packages: Disable parallel build when host pip is needed

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: multiple (ping @commodo)
Compile tested: armvirt-64, 2020-06-29 snapshot sdk
Run tested: none

Description:
This adds `PKG_BUILD_PARALLEL:=0` to packages that depend on host Python packages (`HOST_PYTHON3_PACKAGE_BUILD_DEPENDS`), because installing packages with multiple concurrent pip processes can lead to [errors or unexpected results][1].

This also:

* Move `HOST_PYTHON3_PACKAGE_BUILD_DEPENDS` definitions to before python3-package.mk is included

* Update Python folder readme to include `PKG_BUILD_PARALLEL:=0`

[1]: https://github.com/pypa/pip/issues/2361

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I believe this fixes #12557; the log seems to indicate that both bcrypt and cryptography packages are installing host cffi at the same time and both trying to delete the same file. I have not been able to reproduce the error though and the issue reporter has not responded.

Also apologies to @commodo - I know this conflicts with #12590. I'm not sure when that PR may be merged so I thought I would go ahead and submit this one.

**Comment by feckert** [comment]
@jefferyto could this also fix https://github.com/openwrt/packages/issues/12617 ?

**Comment by jefferyto** [comment]
@feckert I don't think so - python-attrs doesn't use `HOST_PYTHON3_PACKAGE_BUILD_DEPENDS` and you have already tried adding `PKG_BUILD_PARALLEL:=0`.

**Comment by commodo** [comment]
i can't think of another easy fix for this

**Pull request merged**
