### PR TITLE
backport ModemManager and dependencies to 19.07

### PR DESCRIPTION
**Pull request by nickberry17**
Maintainer: me 
Compile tested: ath79 CF-E5, 19.07
Run tested: ath79 CF-E5 19.07. Installed and ran basic functions. 

Description:
Add ModemManager, libmbim and libqmi to packages in 19.07 as per https://forum.openwrt.org/t/modem-manager-dependency/52490/7

mmcli output on running system
```

BusyBox v1.30.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 19.07.0, r10860-a3ffeb413b
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:~# mmcli
error: no actions specified
root@OpenWrt:~# mmcli -m 0
  -----------------------------
  General  |         dbus path: /org/freedesktop/ModemManager1/Modem/0
           |         device id: <redacted>
  -----------------------------
  Hardware |      manufacturer: Sierra Wireless, Incorporated
           |             model: MC7430
           | firmware revision: SWI9X30C_02.24.05.06 r7040 CARMD-EV-FRMWR2 2017/05/19 06:23:09
           |    carrier config: default
           |      h/w revision: 1.0
           |         supported: gsm-umts, lte
           |           current: gsm-umts, lte
           |      equipment id: <redacted>
  -----------------------------
  System   |            device: /sys/devices/platform/ahb/1b000000.usb/usb1/1-1
           |           drivers: qmi_wwan
           |            plugin: Sierra
           |      primary port: cdc-wdm0
           |             ports: cdc-wdm0 (qmi), wwan0 (net)
  -----------------------------
  Numbers  |               own: <redacted>
  -----------------------------
  Status   |              lock: sim-pin2
           |    unlock retries: sim-pin (3), sim-pin2 (3), sim-puk (10), sim-puk2 (10)
           |             state: disabled
           |       power state: on
           |    signal quality: 0% (cached)
  -----------------------------
  Modes    |         supported: allowed: 3g; preferred: none
           |                    allowed: 4g; preferred: none
           |                    allowed: 3g, 4g; preferred: 3g
           |                    allowed: 3g, 4g; preferred: 4g
           |           current: allowed: 3g, 4g; preferred: 4g
  -----------------------------
  Bands    |         supported: utran-1, utran-6, utran-5, utran-8, utran-9, eutran-1, 
           |                    eutran-3, eutran-5, eutran-7, eutran-8, eutran-18, eutran-19, 
           |                    eutran-21, eutran-28, eutran-38, eutran-39, eutran-40, eutran-41, 
           |                    utran-19
           |           current: utran-1, utran-6, utran-5, utran-8, utran-9, eutran-1, 
           |                    eutran-3, eutran-5, eutran-7, eutran-8, eutran-18, eutran-19, 
           |                    eutran-21, eutran-28, eutran-38, eutran-39, eutran-40, eutran-41, 
           |                    utran-19
  -----------------------------
  IP       |         supported: ipv4, ipv6, ipv4v6
  -----------------------------
  3GPP     |              imei: <redacted>
  -----------------------------
  SIM      |         dbus path: /org/freedesktop/ModemManager1/SIM/0
root@OpenWrt:~# 
```

### CODE REVIEW

**Comment by hnyman** [comment]
Is this intended?

```
perus@ub1910:/Openwrt/r7800-1907$ make defconfig
WARNING: Makefile 'package/feeds/packages/modemmanager/Makefile' has a build dependency on 'libxslt/host', which does not exist
#
# configuration written to .config
#
```

Some dependencies are still probably missing.

**Comment by neheb** [comment]
Fixed.

**Comment by manjuprajna** [comment]
@nickberry17 need to backport luci-app-modemmanager too,before it was deleted because no modemmanager package available.

**Comment by poranje** [comment]
Op 29 jan. 2020, om 06:12 heeft manjuprajna <notifications@github.com> het volgende geschreven:
> 
> @nickberry17 need to backport luci-app-modemmanager too,before it was deleted because no modemmanager package available.
Wouldn't that be luci-proto-modemmanager ?

**Pull request merged**
