### PR TITLE
boost: reorganize menus, fix some build dependencies and ABI selections

### PR DESCRIPTION
**Pull request by thess**
Add meta-package with all libraries when CONFIG_ALL selected.

The primary goal was to make the top-level library config menu be a little less cluttered. Sorry that the diff is so messy. I had to do some major makefile reorg to streamline it.

@ClaymorePT - Please review.

### CODE REVIEW

**Comment by ClaymorePT** [comment]
Well, it compiled :+1: 
Yes, now it is much better organized. Thanks for the effort. I learned a few things about the openwrt package organization, from your code!

From what I can tell, it's good to go.

**Comment by ClaymorePT** [comment]
Btw, my next step is to provide to boost, the proper support for ICU.
Boost.Locale can be compiled using iconv, but ICU is recommended. I did not found ICU support in OpenWRT package tree, so it means that I will have to give it a try and port it.

**Comment by thess** [comment]
iconv is widely used in OpenWrt. There are 2 versions (mini and full) used by many packages so it is usually present if you are building with nls. ICU is pretty heavy weight, but then, so is boost.

Just my 2-cents.

**Comment by ClaymorePT** [comment]
Thanks for the info.
I think the best approach is, to provide a simple configuration selector
for Boost.Locale for the user, in order to choose which one should be used.
But for what I can tell from the ICU docs, ICU does not support mips or arm
architectures. I will have to test this.

On 3 March 2015 at 13:10, Ted Hess <notifications@github.com> wrote:

> iconv is widely used in OpenWrt. There are 2 versions (mini and full) used
> by many packages so it is usually present if you are building with nls. ICU
> is pretty heavy weight, but then, so is boost.
>
> Just my 2-cents.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openwrt/packages/pull/976#issuecomment-76942131>.
>



-- 

Carlos Miguel Ferreira
Researcher at Telecommunications Institute
Aveiro - Portugal
Work E-mail - cmf@av.it.pt
Skype & GTalk -> carlosmf.pt@gmail.com
LinkedIn -> http://www.linkedin.com/in/carlosmferreira

**Pull request merged**
