### PR TITLE
rtklib: update to 2.4.3 b34 (latest) version 

### PR DESCRIPTION
**Pull request by Lankaster**
Maintainer: Nuno Goncalves <nunojpg@gmail.com>
Compile tested: MT76x8, Onion Omega 2, openwrt 21.02
Run tested: MT76x8, Onion Omega 2, openwrt 21.02

Description:
update to 4.14.11; fix patches

### CODE REVIEW

**Comment by neheb** [comment]
Rebase PR against master please.

**Comment by Lankaster** [comment]
Maintainer: Nuno Goncalves nunojpg@gmail.com
Compile tested: MT76x8, Onion Omega 2, openwrt master
Run tested: MT76x8, Onion Omega 2, openwrt master

Description:
update to 2.4.3; fix patches, rebased to master

**Comment by neheb** [comment]
```
make package/rtklib/{clean,refresh}
```

**Comment by Lankaster** [comment]
Sorry. Fixed now

**Comment by neheb** [comment]
ping @nunojpg

**Pull request merged**
