### PR TITLE
boost: Add zstd as a dependency to boost-iostream

### PR DESCRIPTION
**Pull request by ammubhave**
Depends on PR #7126

With this change:
https://github.com/boostorg/iostreams/commit/eb03aa43b9373137a51775ab63867152ff72fa00
boost iostreams supports zstd compression. If the zstd package is  built
before boost, then the packaging step complains that libzstd.so is not
packaged.

Compile/Run Tested:
PR #7876 used to fail CI without this, now it passes.
libfolly from the PR compiles.

Signed-off-by: Amol Bhave <ambhave@fb.com>

### CODE REVIEW

**Comment by neheb** [comment]
ping @ClaymorePT

**Comment by ClaymorePT** [comment]
I'll do it as soon as possible.

**Comment by ClaymorePT** [comment]
@ammubhave Your push request is modifying an old version of the Makefile. The current one is at revision 2. 

But don't worry. I'll create an updated version and issue a Push Request today. 
I'm sorry to have only picked this now, since your push request is from the 5th of January. 
Next time, feel free to send me an e-mail or mention me on your Push Request, otherwise I will not be notified.

**Comment by ClaymorePT** [comment]
@ammubhave  I noticed that your PR https://github.com/openwrt/packages/pull/7126 adds support for zstd. 
Once that process is complete, please make sure you are updating the latest version of boost Makefile. 
This PR is using an old version of the Makefile.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/7126 has been added. Merging.

@ClaymorePT I don't believe this PR has any influence over the version of Boost.

**Comment by ClaymorePT** [comment]
@neheb I ment the revision value. He did no bumped the revision value.

**Comment by neheb** [comment]
Ah OK

**Comment by diizzyy** [comment]
Instead of adding it on top just because why not make it optional?

**Comment by ClaymorePT** [comment]
@diizzyy What do you mean by "make it optional"? Are you refering to having zstd as a selection option?

**Comment by diizzyy** [comment]
Yes

**Comment by ClaymorePT** [comment]
Yes, it's a good suggestion. I will add it to my ToDo list.

**Pull request merged**
