### PR TITLE
boost: Updates package to version 1.79.0

### PR DESCRIPTION
**Pull request by ClaymorePT**
Maintainer:  @ClaymorePT  
Compile tested: BCM47xx/Generic - OpenWRT development SDK
Run tested: N/A

Description:
This commit updates boost to version 1.79.0
There are no new libraries in this version

### CODE REVIEW

**Comment by neheb** [comment]
make package/boost/{clean,refresh}

**Comment by ClaymorePT** [comment]
@neheb yeah... I seem to forget about the refresh part every time I submit an update. Thanks for point that out.

Btw, [the OpenWRT Document about the patches](https://openwrt.org/docs/guide-developer/toolchain/use-patches-with-buildsystem) does not contain that part. Just an FYI.

**Comment by ClaymorePT** [comment]
@neheb There seems to be something wrong with Python 3 in arc_archs target

```
2022-04-26T23:26:47.1583941Z 	_PYTHON_PROJECT_BASE=/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4 _PYTHON_HOST_PLATFORM=linux-arc PYTHONPATH=/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/build/lib.linux-arc-3.10:./Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata python3.10 -m lib2to3.pgen2.driver /home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/ipkg-install/usr/lib/python3.10/lib2to3/PatternGrammar.txt
2022-04-26T23:26:47.1908660Z Traceback (most recent call last):
2022-04-26T23:26:47.1909414Z   File "/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/Lib/runpy.py", line 196, in _run_module_as_main
2022-04-26T23:26:47.1909871Z     return _run_code(code, main_globals, None,
2022-04-26T23:26:47.1910439Z   File "/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/Lib/runpy.py", line 86, in _run_code
2022-04-26T23:26:47.1910809Z     exec(code, run_globals)
2022-04-26T23:26:47.1911386Z   File "/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/Lib/lib2to3/pgen2/driver.py", line 26, in <module>
2022-04-26T23:26:47.1911834Z     from . import grammar, parse, token, tokenize, pgen
2022-04-26T23:26:47.1912431Z   File "/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/Lib/lib2to3/pgen2/grammar.py", line 16, in <module>
2022-04-26T23:26:47.1912817Z     import pickle
2022-04-26T23:26:47.1913332Z   File "/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/Lib/pickle.py", line 33, in <module>
2022-04-26T23:26:47.1913719Z     from struct import pack, unpack
2022-04-26T23:26:47.1914254Z   File "/home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/Lib/struct.py", line 13, in <module>
2022-04-26T23:26:47.1914625Z     from _struct import *
2022-04-26T23:26:47.1915421Z ImportError: /home/build/openwrt/build_dir/target-arc_archs_glibc/Python-3.10.4/build/lib.linux-arc-3.10/_struct.cpython-310.so: wrong ELF class: ELFCLASS32
```

**Comment by neheb** [comment]
let's ignore it.

**Comment by MoetaYuko** [comment]
Well, the python error finally leads to a build error of this package:
```
2022-04-29T03:15:18.8968168Z touch /tmp/tmp.SFBxkZGQtf/build_dir/target-arc_archs_glibc/boost_1_79_0/.built
2022-04-29T03:15:18.9052665Z mkdir -p /tmp/tmp.SFBxkZGQtf/bin/targets/archs38/generic-glibc/packages /tmp/tmp.SFBxkZGQtf/build_dir/target-arc_archs_glibc/boost_1_79_0/ipkg-arc_archs/boost-system/CONTROL /tmp/tmp.SFBxkZGQtf/staging_dir/target-arc_archs_glibc/pkginfo
2022-04-29T03:15:18.9081531Z install -d -m0755 /tmp/tmp.SFBxkZGQtf/build_dir/target-arc_archs_glibc/boost_1_79_0/ipkg-arc_archs/boost-system/usr/lib
2022-04-29T03:15:18.9111659Z cp -fpR /tmp/tmp.SFBxkZGQtf/build_dir/target-arc_archs_glibc/boost_1_79_0/ipkg-install/lib/libboost_system*.so* /tmp/tmp.SFBxkZGQtf/build_dir/target-arc_archs_glibc/boost_1_79_0/ipkg-arc_archs/boost-system/usr/lib/
2022-04-29T03:15:18.9139084Z cp: cannot stat '/tmp/tmp.SFBxkZGQtf/build_dir/target-arc_archs_glibc/boost_1_79_0/ipkg-install/lib/libboost_system*.so*': No such file or directory
2022-04-29T03:15:18.9140275Z make[3]: *** [Makefile:504: /tmp/tmp.SFBxkZGQtf/bin/packages/arc_archs/packages/boost-system_1.79.0-3_arc_archs.ipk] Error 1
2022-04-29T03:15:18.9148004Z make[3]: Leaving directory '/home/runner/cache/feeds/packages/libs/boost'
2022-04-29T03:15:18.9149496Z time: package/feeds/packages/boost/compile#169.15#19.38#148.56
2022-04-29T03:15:18.9151362Z     ERROR: package/feeds/packages/boost failed to build.
2022-04-29T03:15:18.9154966Z make[2]: *** [package/Makefile:116: package/feeds/packages/boost/compile] Error 1
2022-04-29T03:15:18.9157744Z make[2]: Leaving directory '/tmp/tmp.SFBxkZGQtf'
2022-04-29T03:15:18.9160599Z make[1]: *** [package/Makefile:110: /tmp/tmp.SFBxkZGQtf/staging_dir/target-arc_archs_glibc/stamp/.package_compile] Error 2
2022-04-29T03:15:18.9163331Z make[1]: Leaving directory '/tmp/tmp.SFBxkZGQtf'
2022-04-29T03:15:18.9167785Z make: *** [/tmp/tmp.SFBxkZGQtf/include/toplevel.mk:223: world] Error 2
2022-04-29T03:15:18.9195319Z ##[error]Process completed with exit code 2.
```

**Comment by neheb** [comment]
I'm curious. Do you actually use ARC?

**Comment by MoetaYuko** [comment]
No, but I run a CI to build some downstream packages for all arches.

**Comment by jefferyto** [comment]
I'm not sure boost is compiling correctly for mips/mipsel/mips64 targets either - pdns-recursor has been failing with this (from https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/pdns-recursor/compile.txt):

```
checking for the toolset name used by Boost for mips-openwrt-linux-musl-g++ -std=c++17... configure: WARNING: could not figure out which toolset name to use for mips-openwrt-linux-musl-g++ -std=c++17

checking boost/context/fiber.hpp usability... yes
checking boost/context/fiber.hpp presence... yes
checking for boost/context/fiber.hpp... yes
checking for the Boost context library... no
checking for getcontext... no
checking for makecontext... no
checking for swapcontext... no
checking what context library to use for MTasker... configure: error: neither boost::context nor System V ucontexts available
make[3]: *** [Makefile:70: /builder/shared-workdir/build/sdk/build_dir/target-mips_24kc_musl/pdns-recursor-4.6.2/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
time: package/feeds/packages/pdns-recursor/compile#43.81#10.67#78.19
```

**Comment by jefferyto** [comment]
This PR removed 030-mips1.patch but upstream has not merged this change yet (I believe https://github.com/boostorg/boost/pull/540 is the upstream PR). Why was this patch removed? And the other patches removed in this PR, are they still necessary?

**Comment by ClaymorePT** [comment]
@jefferyto Yeah, sorry about that. I checked that patch 020 (musl fix) was no longer needed as it was merged upstream but then I also removed the other ones because I screwed up when checking if the patches were applied, after they were applied and not before.

Please revert this PR and I will submit a new proper one ASAP.

**Comment by ClaymorePT** [comment]
@jefferyto It seems that there was a PR applied for the mips issue ( https://github.com/boostorg/log/pull/155 ) but it seems incomplete compared to what we currently have in OpenWRT.

I will update our patch so that it applies successfully.

**Pull request merged**
