### PR TITLE
powertop: update to 2.15

### PR DESCRIPTION
**Pull request by p-w-p**
Maintainer: @lucize 
Compile tested: all supported targets
Run tested: armv8, snapshot/23.05

Description:
PowerTOP v2.15 release mainly focuses on bug fixes and patching compatibility issues. Also, adds support to multiple platforms.
Removed obsolete patch as upstream has fixed.https://github.com/fenrus75/powertop/commit/9ef1559a1582f23d599c149601c3a8e06809296c

### CODE REVIEW

**Comment by 1715173329** [comment]
these changes should be done in a single commit.

**Comment by p-w-p** [comment]
> these changes should be done in a single commit.

Done~

**Comment by 1715173329** [comment]
If you removed patch(es), please explain why in commit messags.
Is it upstreamed, is it implemented another way, or whatever.

**Comment by p-w-p** [comment]
> If you removed patch(es), please explain why in commit messags. Is it upstreamed, is it implemented another way, or whatever.

Done. Thanks again for the hint!

**Pull request merged**
