### PR TITLE
sendmail: Add OpenSSL 1.1 support

### PR DESCRIPTION
**Pull request by neheb**
First two patches are backports from upstream. Third fixes compilation
without deprecated APIs, which is OpenWrt specific.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @val-kulkov 
Compile tested: ar71xx

### CODE REVIEW

**Comment by val-kulkov** [comment]
The first two patches are not backports from upstream. The upstream has taken a completely different approach to support OpenSSL 1.1: see snapshots of Sendmail 8.16.* at ftp://ftp.sendmail.org/pub/sendmail/snapshots/. Rather, it appears that the first two patches were cherry-picked from ArchLinux' Arch User Repository.

As of now, openwrt/packages trunk uses OpenSSL 1.0.2p. Although the suggested patches do not appear to break compilation of sendmail with OpenSSL 1.0.2p, there is no evidence that the suggested patches will indeed enable support of OpenSSL 1.1 in sendmail, as claimed. The approach that was successful in ArchLinux may not necessarily be successful in OpenWRT.

Until there is evidence that the suggested patches indeed enable sendmail's OpenSSL 1.1 support in OpenWRT, I am against merging this PR.

**Comment by neheb** [comment]
Just checked. The tls.c file from 8.16 has more changes than just OpenSSL 1.1 compatibility. I checked to see what Debian is using and it's a patch from one of their OpenSSL maintainers. Would you be open to using that? I haven't been able to find a git or svn repository for sendmail to do a clean backport.

I've tested compilation with https://github.com/openwrt/openwrt/pull/965 . Most distributions have deprecated APIs enabled but we can disable them in OpenWrt for a size reduction.

**Comment by val-kulkov** [comment]
If sendmail compiles successfully with OpenSSL 1.1 per openwrt/openwrt#965, I can take it as evidence that the suggested patches enable support of OpenSSL 1.1.

I would recommend adding comments to the patch files making it clear that their purpose is to enable OpenSSL 1.1 support in sendmail 8.15 only and that the release of sendmail 8.16 would render them unnecessary. This way, whoever undertakes to backport sendmail 8.16 to OpenWRT will have fewer things to worry about.

Re naming the patch files. I am not sure that "2xx - kernel build / config / header patches" is an appropriate category in this case. Please review the "Naming Patches" section in [Working with patches in the build system](https://openwrt.org/docs/guide-developer/build-system/use-patches-with-buildsystem).

Lastly, I would suggest renaming patch files to *-openssl-1.1.patch and *-openssl-1.1-ecdhe.patch to avoid a possible [mis]understanding that the patches relate specifically to OpenSSL version 1.1.1 and not to 1.1.*.

**Comment by neheb** [comment]
The naming shown there applies to the openwrt repository and more specifically, the kernel patches. I don't think this applies to packages.

Both patches apply to 1.1.0 and above. There are no API changes between both versions. Only feature additions.

Speaking of patches, I'm liking the Debian one the more I look at it. I will do several tests and update the pull request.

**Comment by neheb** [comment]
@val-kulkov Switched to the debian patch, which seems cleaner. Also edited the commit description. Please review.

**Comment by cotequeiroz** [comment]
@neheb 
Are you interested in adding this commit 0612cb86d718530ef499ea2cabb2c23701c2b0e3 ?  You may use it here as your own (I'm not sure how graceful DCO is with using a different sign-off line).

**Comment by val-kulkov** [comment]
@cotequeiroz : let me try commit 0612cb8 on my system. In any event, replacing ld with gcc so that libmilter.so can be successfully compiled with glibc is a separate issue that should be dealt with in a separate commit/PR IMO.

**Comment by cotequeiroz** [comment]
Definitely a separate commit.  If testing goes well with both, you may do them here.  In case of any bugs being introduce by either, the separate commits will separate the matter enough.
The only reason I mentioned it here is to not have to wait for one to be merged before opening another PR.
If you rather deal with them separately, or if any issues arise, toss this commit, and I'll open a new PR.
Cheers

**Comment by neheb** [comment]
AFAIK, the LD change should have no change in binary output and thus does not deserve a release bump. If it does, it's probably useful to keep release bumps minimal.

**Comment by cotequeiroz** [comment]
It changes when compiled with glibc.

**Comment by neheb** [comment]
Rebased and added commit.

**Comment by val-kulkov** [comment]
Confirming successful compilation of libmilter.so and sendmail executable with openwrt/openwrt#965 applied and CONFIG_OPENSSL_USE_VERSION_1_1_1=y. Compiled and run-tested on x86_64.

@neheb : at the top of each patch file you proposed, please add a note to remove patch when backporting sendmail 8.16 which already contains code to support OpenSSL 1.1.*. Something like "this patch is not necessary for sendmail 8.16; remove before attempting to backport sendmail 8.16". With these comments added, you have my unwavering support on this PR.

@cotequeiroz : replacing ld with gcc apparently produces the same executables with musl. With that, I am fine with this change especially if you say that it fixes a problem when compiling against glibc libraries.

**Comment by neheb** [comment]
Added comments.

**Pull request merged**
