### PR TITLE
MariaDB: version bump to 10.1.33

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: me
Compile tested: mips24kc
Run tested: N/A

Description:
A bit of cleaning up and a version bump that addresses some CVEs. Maintenance.

Can anybody please commit this, maybe @hnyman or @jow-?

Thanks in advance!

Kind regards,
Seb

### CODE REVIEW

**Comment by diizzyy** [comment]
You need at least a runtime test, this applies to everyone.

**Comment by diizzyy** [comment]
micmac1, out of curiosity... what 24kc hardware runs mariadb? ;-)

**Comment by micmac1** [comment]
Hi Daniel,

I  got a DLink here. I'm on the balcony right now but I think the model is called DIR-825 C1.

Regards,
Seb

**Comment by micmac1** [comment]
Hi again @diizzyy 

Yes, it's indeed a D-Link DIR-825 rev. C1.

I had to add a USB stick to provide extra space and also some swap. I haven't found a configuration that makes it work without that. Anyway, it runs.

```
root@hank2:/tmp# /etc/init.d/mysqld start
root@hank2:/tmp# ps w|grep mysq
 3552 root      206m S    /usr/bin/mysqld
 3585 root      1184 S    grep mysq
root@hank2:/tmp# free
             total       used       free     shared    buffers     cached
Mem:        125640      98908      26732      14648        876      24820
-/+ buffers/cache:      73212      52428
Swap:      1048572      30860    1017712
root@hank2:/tmp# cat /tmp/sysinfo/model 
D-Link DIR-825 rev. C1
root@hank2:/tmp#
```

If you start it manually this is what that looks like:

```
root@hank2:/tmp# mysqld 
2018-05-13 10:27:09 2012785808 [Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
2018-05-13 10:27:09 2012785808 [Note] mysqld (mysqld 10.1.33-MariaDB) starting as process 3642 ...
2018-05-13 10:27:09 2012785808 [Warning] Buffered warning: option 'max_connections': unsigned value 2 adjusted to 10

2018-05-13 10:27:09 2012785808 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2018-05-13 10:27:09 2012785808 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-05-13 10:27:09 2012785808 [Note] InnoDB: The InnoDB memory heap is disabled
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-13 10:27:09 2012785808 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Compressed tables use zlib 1.2.11
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Using generic crc32 instructions
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Initializing buffer pool, size = 20.0M
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Completed initialization of buffer pool
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Highest supported file format is Barracuda.
2018-05-13 10:27:09 2012785808 [Note] InnoDB: 128 rollback segment(s) are active.
2018-05-13 10:27:09 2012785808 [Note] InnoDB: Waiting for purge to start
2018-05-13 10:27:09 2012785808 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.39-83.1 started; log sequence number 1616757
2018-05-13 10:27:10 1818168608 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-05-13 10:27:10 2012785808 [Note] Server socket created on IP: '127.0.0.1'.
2018-05-13 10:27:10 2012785808 [Note] Reading of all Master_info entries succeded
2018-05-13 10:27:10 2012785808 [Note] Added new Master_info '' to hash table
2018-05-13 10:27:10 2012785808 [Note] mysqld: ready for connections.
Version: '10.1.33-MariaDB'  socket: '/var/run/mysqld.sock'  port: 3306  Source distribution
2018-05-13 10:30:02 1817066784 [Note] mysqld: Normal shutdown
2018-05-13 10:30:02 1817066784 [Note] Event Scheduler: Purging the queue. 0 events
2018-05-13 10:30:02 1818438944 [Note] InnoDB: FTS optimize thread exiting.
2018-05-13 10:30:02 1817066784 [Note] InnoDB: Starting shutdown...
2018-05-13 10:30:03 1817066784 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
2018-05-13 10:30:04 1817066784 [Note] InnoDB: Shutdown completed; log sequence number 1616767
2018-05-13 10:30:04 1817066784 [Note] mysqld: Shutdown complete

root@hank2:/tmp#
```

Kind regards,
Seb

**Comment by diizzyy** [comment]
Oh, I see
Could you add a few mirrors to offload main site (put it last)? This are from the download page btw.

```
http://mirror.netcologne.de/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
http://mirror.lstn.net/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
http://ams2.mirrors.digitalocean.com/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
```

LGTM otherwise

**Comment by micmac1** [comment]
Am May 13, 2018 8:51:42 AM UTC schrieb Daniel Engberg <notifications@github.com>:
>Oh, I see
>Could you add a few mirrors to offload main site (put it last)? This
>are from the download page btw.
>
>```
>http://mirror.netcologne.de/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
>http://mirror.lstn.net/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
>http://ams2.mirrors.digitalocean.com/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
>http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/$(PKG_NAME)-$(PKG_VERSION)/source/
>```
>
>LGTM otherwise
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/packages/pull/6044#issuecomment-388611482

Man, I really wanted to go out on the motorcycle today ;-) Give me a minute.

**Comment by micmac1** [comment]
Hi @diizzyy 

Added the mirrors. I skipped the DO mirror as it doesn't do SSL.

Regards,
Seb

**Pull request merged**
