### PR TITLE
Rrdtool1: Improve logarithmic y-axis labelling

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Maintainer: @jow- 

Improve logarithmic y-axis labelling & fix a libpng compile indentation warning

### CODE REVIEW

**Comment by hnyman** [comment]
The log scale labelling fix makes the cake stats somewhat nicer. Thanks.

**Comment by jow-** [comment]
Haven't look in detail yet but two thoughts:

- It would be great if we somehow could reuse the number format logic for the Y-axis values, but no idea how complex that would be
- The misleading indent patch seems to change functionality in subtle ways - not sure if not always zeroing the pointer introduces any unwanted side effects. I'd prefer not patching it.

**Comment by ldir-EDB0** [comment]
Dropped the 2nd commit

**Comment by hnyman** [comment]
Just for fun I tried to figure out from ancient upstream sources if the "misleading" change was intended or not, but could not do that. :-(

The libpng source code has at that time been on CVS or SVN(?), and the current git logs show changes inadequately based on tar imports of source archives.

The code has been inserted there in 2000 by version 1.0.8rc1 in a way that suggests that the omission of brackets was erroneous:
https://github.com/glennrp/libpng/commit/4766a244b23f951a64b7d7514f6b495debfa5a98#diff-f8e1a6856690a0d19f32b34bf321b7be

However, the code disappears by 1.4.0beta24 in year 2008. Both lines are removed at that time...
https://github.com/glennrp/libpng/commit/895a9c97e2ea19b51bcfd6f26d2f51ab31041b12#diff-f8e1a6856690a0d19f32b34bf321b7be

Can't make head or tail of that, but might be best to leave it as it is, like jow suggests. The current code has not hurt us in the last decade ;-)

**Comment by ldir-EDB0** [comment]
I tried to do the same thing but you had more success than me.

I've had the occasional 'sigsegv' from rrdtool whilst working on the sqm related graphs, I've not seen any since my libpng tweak, but then I've got slightly better at generating the graphs.  I'll carry the patch locally and see if anything falls out.

**Comment by ldir-EDB0** [comment]
ping

**Pull request merged**
