### PR TITLE
Pull request python package collection

### PR DESCRIPTION
**Pull request by dfc-d**
This is the redo of the python packages I've create for incorporating into seahub builds

### CODE REVIEW

**Comment by commodo** [comment]
For the `python` part: from me it's an ACK.

**Comment by dfc-d** [comment]
Removed Django 1.5 and things that depend on it from PR due to 1.5 EOL and having CVE's.

**Comment by commodo** [comment]
ack from me for the python package parts

**Comment by dfc-d** [comment]
Hi, I've been working on the collection a little (which I will split into individual PR's or where there is a dependency chain.  I've discovered two things in the process:

Djblets (even latest 0.9) is only experimentally supporting Django 1.8 and still recommends 1.6 (unfortunately based on a Magia Linux post with the same error I message I get, it seems a not so recent XSS security fix for Djblets broke Django 1.7 (and likely is the same reason Django 1.8 fails).
Conclusion: Djblets is another out-of-date bit of software that I'm not going to add.

Second note:  Django recommends install bcrypt, however I discovered two problems with that:  First of all bcrypt is not cross-compilable due to using of CFFI during build process (which means running native code, but that doesn't work when you're cross-compiling; and you can't even using host python CFFI because the CFFI needs to work with the built package which would be the wrong arch).  Secondly bcrypt hardcodes x86 specific setup stuff.

So even though Django 1.8 recommends bcrypt it's not a option for OpenWrt.

**Comment by dfc-d** [comment]
I've separated the PR into seperate requests.

**Pull request closed without merging**
