### PR TITLE
libupnpp and upmpdcli

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @ignisf

### CODE REVIEW

**Comment by ignisf** [comment]
Hello, thank you for the PR. While there, would you be willing to bump the Python dependency to point to Python 3?

**Comment by diizzyy** [comment]
Needs a run-time test before merging.

**Comment by neheb** [comment]
Where's the Python dependency?

**Comment by ignisf** [comment]
https://github.com/neheb/packages/blob/738dc796ca4a6b9273ff9d2ff4884040c4528e63/sound/upmpdcli/Config.in#L13

**Comment by neheb** [comment]
Done

**Comment by ignisf** [comment]
lgtm thanks

**Comment by jefferyto** [comment]
The Python dependency is unchanged? https://github.com/openwrt/packages/blob/97bada594b6aa212c9fe04e155021ec3080cd988/sound/upmpdcli/Config.in#L13

**Comment by neheb** [comment]
Fixed.

**Comment by jefferyto** [comment]
Thanks! (The change is fa005f434ecef0ac2539155c90b1609d26ddf996.)

**Pull request merged**
