### PR TITLE
ariang: update to 1.1.0

### PR DESCRIPTION
**Pull request by dengqf6**
Maintainer: @Ansuel 
Compile tested: mvebu
Run tested: mvebu

Description:
Update AriaNg to latest release 1.1.0

### CODE REVIEW

**Comment by neheb** [comment]
Why PKG_VERSION? It is set by the other variables: https://github.com/openwrt/openwrt/blob/master/include/download.mk#L15

**Comment by Ansuel** [comment]
Good for me

Il Lun 29 Apr 2019, 08:04 Rosen Penev <notifications@github.com> ha scritto:

**Comment by dengqf6** [comment]
Removed PKG_SOURCE_DATE

**Comment by neheb** [comment]
I took a look again. PKG_SOURCE_VERSION can be set to PKG_VERSION since it is tagged.

**Comment by dengqf6** [comment]
It's not tagged in the daily build repo

**Comment by neheb** [comment]
Fair enough. Merging.

**Comment by ysc3839** [comment]
@neheb It's daily build, why we need a version number?

**Comment by neheb** [comment]
Didn't look at this closely enough. The versioning should be reverted, yes.

**Comment by dengqf6** [comment]
@ysc3839
The daily build repo is used just for convenience. It's tagged in main repo

**Comment by neheb** [comment]
It is, but this does not match the released version.

**Pull request merged**
