### PR TITLE
spi-tools: Update to 0.8.4

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @blogic 
Compile tested: ath79

### CODE REVIEW

**Comment by BKPepe** [comment]
In your commit, you are doing more changes than just update. Can you please include it in your commit message?

**Comment by neheb** [comment]
Added.

**Comment by feckert** [comment]
@neheb 
Since your change I get the following errors one my build.
```
make[3]: Entering directory '/home/feckert/workspace/lede/LDM-master-64/build/openwrt/build_dir/target-x86_64_musl/spi-tools-0.8.4'
Making all in src
make[4]: Entering directory '/home/feckert/workspace/lede/LDM-master-64/build/openwrt/build_dir/target-x86_64_musl/spi-tools-0.8.4/src'
make  all-am
make[5]: Entering directory '/home/feckert/workspace/lede/LDM-master-64/build/openwrt/build_dir/target-x86_64_musl/spi-tools-0.8.4/src'
x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I.   -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/usr/include -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include/fortify -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include   -O0  -MT spi-config.o -MD -MP -MF .deps/spi-config.Tpo -c -o spi-config.o spi-config.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mv -f .deps/spi-config.Tpo .deps/spi-config.Po
x86_64-openwrt-linux-musl-gcc  -O0   -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/lib -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/usr/lib -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib -fpic -specs=/home/feckert/workspace/lede/LDM-master-64/build/openwrt/include/hardened-ld-pie.specs -znow -zrelro  -o spi-config spi-config.o
/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: spi-config.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

Can you help me there?

**Comment by neheb** [comment]
I'm guessing you're compiling with PKG_ASLR_PIE. I'd set it to 0.

**Comment by feckert** [comment]
@neheb thanks that fixed my problem.
Should we not then add PKG_ASLR_PIE:=0 into spi-tools config Makefile?

**Pull request merged**
