### PR TITLE
ddns-scripts: Added duckdns.org service

### PR DESCRIPTION
**Pull request by marcogiovinazzi**
[duckdns.org](https://www.duckdns.org) service as in https://www.duckdns.org/install.jsp#openwrt and https://wiki.openwrt.org/doc/howto/ddns.client/duckdns

Signed-off-by: Marco Giovinazzi <marco.giovinazzi@comodojo.org>

### CODE REVIEW

**Comment by hnyman** [comment]
You should include the sign-off line in the commit message itself.
(you can amend the existing commit. If you need advice, read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests )

cc to maintainer: @chris5560

**Comment by chris5560** [comment]
@marcogiovinazzi
Thanks for you update.

If it's easy for you to update your commit (not only the pull) then
could you please add "OK" to the end of the line because 
this is the positive answer duckdns is sending if update was successful.
ddns-scripts can optional check the answers from ddns provider if update was successful.

So it should look like:
"duckdns.org"	"http://www.duckdns.org/update?domains=[USERNAME]&token=[PASSWORD]&ip=[IP]"	"OK"

It's not required to update but nice to have.

So if you have problems to update your commit, simply edit your pull and "Sign-off".
If "Sign-off" is done it could be merged.

Christian

**Comment by marcogiovinazzi** [comment]
I added "OK" to the service line and amended the commit to include the Sign-off. 

Thanks @chris5560 and @hnyman for your suggestions!

**Comment by chris5560** [comment]
@hnyman
From my side it looks OK. Could you please merge.
I only allowed to merge in luci tree.
Thanks
Christian

**Pull request merged**
