### PR TITLE
shadow-su: fix issue with controlling terminal - issue #1521

### PR DESCRIPTION
**Pull request by pjoe**
This fixed the su issue #1521 for me :)

### CODE REVIEW

**Comment by thess** [comment]
Need to bump PKG_RELEASE and update copyright. The package name is 'shadow' not 'shadow-su'

**Comment by pjoe** [comment]
@thess: Tried to make those changes to PKG_RELEASE and copyright. I'm pretty new to OpenWrt, so still learning :)

**Comment by sbyx** [comment]
Please reopen the pull-request against the master branch (and not for-15.05) and add Signed-off-by tags to your commit messages.

**Comment by pjoe** [comment]
Done in PR #1532

**Pull request closed without merging**
