### PR TITLE
samba4: add package samba-4.8

### PR DESCRIPTION
**Pull request by Andy2244**
Signed-off-by: Andy Walsh <andy.walsh44+github@gmail.com>

Maintainer: me
Compile tested: arm/mvebu, mipsel/pistachio, master (aa66aa0)
Run tested: arm/mvebu, master (aa66aa0)

Description:
This is my samba 4.8 package, its a basic fileserver version with vfs support and some extra options to configure what should be build/packaged. I may enable ad-dc, ads and printer support later, if the initial tests, reviews go well.
_I also have a updated luci-ui package ready for the extra options._

PS: Lets see what travis-ci finds out. 
_The e2fsprogs com_err issue should also be fixed first._

### CODE REVIEW

**Comment by hnyman** [comment]
Some comments after initial view:

* should the package PKG_NAME be called samba4 as all later definitions talk about samba4?
* why do you not include PKG_CONFIG_DEPENDS on CONFIG_SAMBA4_SERVER although you use that conditional in the install definition?  PKG_CONFIG_DEPENDS should include all those config options that should trigger a full rebuild.
* description contains lots of advertising speech (copied from their website?) You might truncate some of that
* I see no need to conditionalise conffiles via a config symbol. If those files are present, those should be preserved in any case

**Comment by Andy2244** [comment]
> should the package PKG_NAME be called samba4 as all later definitions talk about samba4?

Still confused on this:

> PKG_NAME - The name of the package, as seen via menuconfig and ipkg

Which is simply not true, it uses the `define Package/samba4`.
I have gone with the logic that `PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)` is used as standard so "basename" -"version", which in this case would be "samba"-"4.8"?
If this is wrong i can change this, np.

> PKG_CONFIG_DEPENDS should include all those config options that should trigger a full rebuild.

docu notes:
> PKG_CONFIG_DEPENDS - specifies which config options influence the build configuration and should 
trigger a rerun of Build/Configure on change

It specifically notes Build/Configure, so i only added those options that actually change the .configure process and not the build/install step? Need some clarification here.

> description contains lots of advertising speech (copied from their website?) You might truncate some of that

got me, will shorten it

> I see no need to conditionalise conffiles via a config symbol. If those files are present, those should be preserved in any case

They are only part of the server, but sure can remove the condition.

> you should squash your commits into one in any case

can you give me the git command, last time i tried this i messed up my pull request

**Comment by hnyman** [comment]
> can you give me the git command, last time i tried this i messed up my pull request

Normal git stuff. 
Some advice at:
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

Likely: 
git rebase -i HEAD~2
<edit commit picking, pick one, squash the other>
git log   (to verify the squashing)
git push -f   (to update the PR branch forcibly)

**Comment by Andy2244** [comment]
Oki merged the requests, seems easy enough. Yet i can't get any usefully information out of the travis log and why this time it failed?

**Comment by Andy2244** [comment]
Temp closing this, i think i can get ad-dc/windbind support ready for the initial makefile, but need some more time to puzzle out all the parts.

**Pull request closed without merging**
