### PR TITLE
Update ser2net and gensio

### PR DESCRIPTION
**Pull request by yegorich**
Maintainer: @WereCatf
Compile tested: TI OMAP am335x
Run tested: TI OMAP am335x

Description: update ser2net and gensio

Remove upstreamed patches.

### CODE REVIEW

**Comment by mhei** [comment]
Buildbots are failing, please have a look, e.g.
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9/packages/gensio/compile.txt

**Comment by yegorich** [comment]
Can the difference be nornal build against SDK build?

**Comment by mhei** [comment]
For reference:  https://github.com/openwrt/packages/pull/22701#issuecomment-1821871731
The patch `0001-Ensure-that-ax_python_devel_found-is-defined.patch` was not exactly the same which was upstreamed, a single line differs:
```
--- a/configure.ac
+++ b/configure.ac
@@ -2002,6 +2002,7 @@ if test "x$trypython" = "xyes"; then
       PYTHON_CPPFLAGS="$pythoncflags"
    fi
    AX_PYTHON_DEVEL([], [true])
+   ax_python_devel_found=yes
 else
    ax_python_devel_found=no
 fi
```
I guess adding this as patch again makes the buildbots happy, but I still don't understand whats going on under the hood.

**Comment by yegorich** [comment]
This sounds quite complicated. Will you submit a patch as you've already some experience with autoconf stuff?

I hope that @cminyard will switch to meson as discussed [here](https://github.com/cminyard/gensio/issues/61).

**Comment by cminyard** [comment]
> This sounds quite complicated. Will you submit a patch as you've already some experience with autoconf stuff?
> 
> I hope that @cminyard will switch to meson as discussed [here](https://github.com/cminyard/gensio/issues/61).

I have not tried meson, but I tried cmake, and cmake, IMHO, is more complicated to make complicated things work.  I was always fighting with it.  For simple things, it's easy, but so is autotools.  Unless I get a huge amount of free time in the near future, any sort of switch is not going to happen :(.

**Comment by cminyard** [comment]
> The other thing you can do, I guess is run configure like:
```
ax_python_devel_found=y ./configure
```

Or you can export it in the environment before calling configure.

**Comment by mhei** [comment]
> Yeah, this is wrong. AX_PYTHON_DEVEL, at least the most current version, sets ax_python_devel_found. Forcing it to "yes" kind of defeats the purpose of the macro.

All true. But in our special case here, we know what we are doing™ since we have control about the build environment either. But it would still be an ugly workaround, I totally agree.

> I'm guessing that your build system is replacing ax_python_devel.m4 with an older version. Can you move to the newer version, or not replace the macros in m4?

This is my assumption, too. But I did not yet found time to dig into this, i.e. _where_ and _why_ this might be replaced and/or why the version number in the file (which is included in your package) is not respected.

**Comment by mhei** [comment]
@yegorich: I'm still not able to reproduce the behavior on my local machine. And I cannot remember anymore, whether I had it reproducible last year. I could just create the patch and PR, then we can merge it and have a look, whether buildbots become happy?

**Comment by mhei** [comment]
Created PR https://github.com/openwrt/packages/pull/24081

**Comment by yegorich** [comment]
@mhei great. Thanks.

I still couldn't reproduced it either.

**Pull request merged**
