### PR TITLE
redsocks: updates to latest source and gcc build options

### PR DESCRIPTION
**Pull request by thess**
Proposed - upgrade to latest version in source repo. Most notable change was to the GCC compile options in source Makefile which may address problem reported in #1338.

I have been unable to reproduce these build failures reported in any version. Compile tested on Ubuntu (14.04 & 15.10) only.

@morgenroth - please review

### CODE REVIEW

**Comment by thess** [comment]
@morgenroth - If no objections, I'll merge this. It appears not be tested by anyone with the problem but at least it is up-to-date.

**Comment by taeasy** [comment]
the problem...


make[2]: Entering directory `/home/main/ar71xx/feeds/packages/net/redsocks'
. /home/main/ar71xx/include/shell.sh; xzcat /home/main/ar71xx/dl/redsocks-0.4-20150907.tar.xz | tar -C /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/.. -xf - 

Applying ./patches/0006-fix_default_config_location.patch using plaintext: 
patching file main.c
touch /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/.prepared_c33188826fc6db4ac2539a012f4f27f7
rm -f /home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.redsocks_installed
(cd /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/./; if [ -x ./configure ]; then find /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/ -name config.guess | xargs -r chmod u+w; find /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/ -name config.guess | xargs -r -n1 cp --remove-destination /home/main/ar71xx/scripts/config.guess; find /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/ -name config.sub | xargs -r chmod u+w; find /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/ -name config.sub | xargs -r -n1 cp --remove-destination /home/main/ar71xx/scripts/config.sub; AR="mips-openwrt-linux-uclibc-gcc-ar" AS="mips-openwrt-linux-uclibc-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float" LD=mips-openwrt-linux-uclibc-ld NM="mips-openwrt-linux-uclibc-gcc-nm" CC="mips-openwrt-linux-uclibc-gcc" GCC="mips-openwrt-linux-uclibc-gcc" CXX="mips-openwrt-linux-uclibc-g++" RANLIB="mips-openwrt-linux-uclibc-gcc-ranlib" STRIP=mips-openwrt-linux-uclibc-strip OBJCOPY=mips-openwrt-linux-uclibc-objcopy OBJDUMP=mips-openwrt-linux-uclibc-objdump SIZE=mips-openwrt-linux-uclibc-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 " CPPFLAGS="-I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib "   ./configure --target=mips-openwrt-linux --host=mips-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   ; fi; )
rm -f /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/.configured_*
touch /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/.configured_yyyyyyyy
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16  -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16  -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib " make -j1 -C /home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/. AR="mips-openwrt-linux-uclibc-gcc-ar" AS="mips-openwrt-linux-uclibc-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float" LD=mips-openwrt-linux-uclibc-ld NM="mips-openwrt-linux-uclibc-gcc-nm" CC="mips-openwrt-linux-uclibc-gcc" GCC="mips-openwrt-linux-uclibc-gcc" CXX="mips-openwrt-linux-uclibc-g++" RANLIB="mips-openwrt-linux-uclibc-gcc-ranlib" STRIP=mips-openwrt-linux-uclibc-strip OBJCOPY=mips-openwrt-linux-uclibc-objcopy OBJDUMP=mips-openwrt-linux-uclibc-objdump SIZE=mips-openwrt-linux-uclibc-size CROSS="mips-openwrt-linux-uclibc-" ARCH="mips" ;
make[3]: Entering directory `/home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907'
mkdir -p gen
touch gen/.build
rm -f gen/version.c.tmp
echo '/* this file is auto-generated during build */' > gen/version.c.tmp
echo '#include "../version.h"' >> gen/version.c.tmp
echo 'const char* redsocks_version = ' >> gen/version.c.tmp
if [ -d .git ]; then \
		echo '"redsocks.git/'`git describe --tags`'"'; \
		if [ `git status --porcelain | grep -v -c '^??'` != 0 ]; then \
			echo '"-unclean"'; \
		fi \
	else \
		echo '"redsocks/0.4"'; \
	fi >> gen/version.c.tmp
echo ';' >> gen/version.c.tmp
mv -f gen/version.c.tmp gen/version.c
gcc -MM parser.c main.c redsocks.c log.c http-connect.c socks4.c socks5.c http-relay.c base.c base64.c md5.c http-auth.c utils.c redudp.c dnstc.c gen/version.c 2>/dev/null >.depend || \
	( \
		for I in base.h base64.h dnstc.h http-auth.h libc-compat.h libevent-compat.h list.h log.h main.h md5.h parser.h redsocks.h redudp.h socks5.h utils.h version.h; do \
			export ${I//[-.]/_}_DEPS="`sed '/^\#[ \t]*include \?"\(.*\)".*/!d;s//\1/' $I`"; \
		done; \
		echo -n >.depend; \
		for SRC in parser.c main.c redsocks.c log.c http-connect.c socks4.c socks5.c http-relay.c base.c base64.c md5.c http-auth.c utils.c redudp.c dnstc.c gen/version.c; do \
			echo -n "${SRC%.c}.o: " >>.depend; \
			export SRC_DEPS="`sed '/\#[ \t]*include \?"\(.*\)".*/!d;s//\1/' $SRC | sort`"; \
			while true; do \
				export SRC_DEPS_OLD="$SRC_DEPS"; \
				export SRC_DEEP_DEPS=""; \
				for HDR in $SRC_DEPS; do \
					eval export SRC_DEEP_DEPS="\"$SRC_DEEP_DEPS \$${HDR//[-.]/_}_DEPS\""; \
				done; \
				export SRC_DEPS="`echo $SRC_DEPS $SRC_DEEP_DEPS | sed 's/  */\n/g' | sort -u`"; \
				test "$SRC_DEPS" = "$SRC_DEPS_OLD" && break; \
			done; \
			echo $SRC $SRC_DEPS >>.depend; \
		done; \
	)
make[3]: Leaving directory `/home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907'
make[3]: Entering directory `/home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907'
mips-openwrt-linux-uclibc-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16  -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/ar71xx/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include  -g -O2 -std=c99 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall   -c -o parser.o parser.c
In file included from parser.c:29:0:
utils.h:51:41: warning: 'struct evbuffer' declared inside parameter list [enabled by default]
 char *redsocks_evbuffer_readline(struct evbuffer *buf);
                                         ^
utils.h:51:41: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
utils.h:52:65: error: unknown type name 'evbuffercb'
 struct bufferevent* red_connect_relay(struct sockaddr_in *addr, evbuffercb writecb, everrorcb errorcb, void *cbarg);
                                                                 ^
utils.h:52:85: error: unknown type name 'everrorcb'
 struct bufferevent* red_connect_relay(struct sockaddr_in *addr, evbuffercb writecb, everrorcb errorcb, void *cbarg);
                                                                                     ^
make[3]: *** [parser.o] Error 1
make[3]: Leaving directory `/home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907'
make[2]: *** [/home/main/ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/redsocks-0.4-20150907/.built] Error 2
make[2]: Leaving directory `/home/main/ar71xx/feeds/packages/net/redsocks'
make[1]: *** [package/feeds/packages/redsocks/compile] Error 2
make[1]: Leaving directory `/home/main/ar71xx'
make: *** [package/redsocks/compile] Error 2
main@debian:~/ar71xx$

**Comment by thess** [comment]
@taeasy -- see my comment at the end of #1338

Remove __libev__ from your build and redsocks will compile OK. I may just go ahead and mark libev `@BROKEN`. I need to see if there any dependencies on libev (it used to be in the Management repo)

@sbyx - what do you think?

**Comment by sbyx** [comment]
We should probably try to get rid of libev if possible.

**Comment by thess** [comment]
It looks like kamailio in telephony uses it and libevent2 ! @jslachta - any help here?

**Comment by lperkov** [comment]
@sbyx no libev users in management feed

**Comment by ninechung** [comment]
@thess plz, help me...
`make[3]: Entering directory '/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-mipsel_24kc_musl/redsocks2/redsocks2-0.60'
mipsel-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-mipsel_24kc_musl/redsocks2//redsocks2-0.60:redsocks2-0.60 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/staging_dir/target-mipsel_24kc_musl/usr/include -I/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/staging_dir/target-mipsel_24kc_musl/include -I/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/usr/include -I/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify -I/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include  -fPIC -O3  -std=gnu99 -Wall   -c -o parser.o parser.c
In file included from parser.c:29:0:
utils.h:6:10: fatal error: event.h: No such file or directory
 #include <event.h>
          ^~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'parser.o' failed
make[3]: *** [parser.o] Error 1
make[3]: Leaving directory '/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-mipsel_24kc_musl/redsocks2/redsocks2-0.60'
Makefile:55: recipe for target '/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-mipsel_24kc_musl/redsocks2//redsocks2-0.60/.built' failed
make[2]: *** [/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-mipsel_24kc_musl/redsocks2//redsocks2-0.60/.built] Error 2
make[2]: Leaving directory '/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/package/redsocks2'
Command exited with non-zero status 2
time: package/redsocks2/compile#0.20#0.07#0.23
package/Makefile:107: recipe for target 'package/redsocks2/compile' failed
make[1]: *** [package/redsocks2/compile] Error 2
make[1]: Leaving directory '/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64'
/root/openwrt-sdk-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/include/toplevel.mk:209: recipe for target 'package/redsocks2/compile' failed
make: *** [package/redsocks2/compile] Error 2
`

**Pull request merged**
