### PR TITLE
xtables-addons: bump to 3.24, fix build errors since b2d1eb7

### PR DESCRIPTION
**Pull request by httpstorm**
Use `kmalloc` and remove conflicting `#include <stdarg.h>`, to fix the following build warnings treated as errors since https://github.com/openwrt/openwrt/commit/b2d1eb717b6597e0145c98fc5f9f88a7dc219513

```
error: ISO C90 forbids variable length array 'buf' [-Werror=vla]
error: "va_start" redefined [-Werror]
error: "va_arg" redefined [-Werror]
error: "va_copy" redefined [-Werror]
getstr(s)==NULL is always false
```

Maintainer: @jow-
Compile tested: WRT3200ACM

@Ansuel @aparcar @neheb @pprindeville

### CODE REVIEW

**Comment by Ansuel** [comment]
Kmalloc is wrong please take my patch.

**Comment by httpstorm** [comment]
@aparcar 
Thanks. I'm on it...

**Comment by Ansuel** [comment]
mhhh you had a different solution for va_list ? you stropped the include?

**Comment by httpstorm** [comment]
@aparcar 
> mhhh you had a different solution for va_list ? you stropped the include?

Yes, I think it's better to remove the include. It was the most simple solution. Especially considering that `stdarg.h` is included from two places. Trouble is one place includes the linux version, and the other includes the version from the mvebu compiler, so that's the source of conflict. My change removes the second. The other way would be far more complicated to impossible.
If you like I can remove the include and add my self as contributor? In my patch I also edit the original patches, to keep it simple and less code. Would you prefer two patches: fix and bump, or one that does both?

**Comment by Ansuel** [comment]
@httpstorm think you are using the wrong tag... anyway
can you provide the patch? I don't really like mine with the define so i would like to see your solution! (and ideally also apply that to broadcom-wl

**Comment by rmandrad** [comment]
note that I am also having this issue (c90 .. -Werror=vla)  on a non-mvebu device(ipq807x) ... happy to test the fix when available

**Comment by httpstorm** [comment]
@aparcar 
Below is a link to my first version of the patch. I will restore it, but change to `kcmalloc` as you advised, and keep your comments. Note that I am an embedded-kernel engineer. I created my own nano RTOS, where all API is safe in any context including RAW ISR. So while I know about the limitations in kernel-mode, my experience with Linux kernel is poor. Please analyse the patch carefully after I update this PR. I'll post back in 30-60 minutes.
https://github.com/httpstorm/openwrt.packages/commit/bd3f0de0944042f7ecbd82887bc6ecccc8655e5a

BTW is this LUA code still in use or is it legacy? I remember at some point I saw that JavaScript is used. I do not see a package called `xtables-addons` installed on my router, and I am not sure how to test the changes. I use `xtables` for the tarpit, as this wasn't available in `nft`.

**Comment by httpstorm** [comment]
@Ansuel 
I'm ready. Successful build and flash on WRT3200ACM. Please review my changes!

@ptpt52 
> I am not sure but if this code run in softirq context, GFP_ATOMIC flag should be used in kcalloc

I'm not sure either in what context `byte_array_to_string` is used. Considering it is exported in a table to be called from LUA, I would assume it isn't called from an interrupt handler, rather from user space. I wonder if this code is used at all, please check my previous comment.

**Comment by Ansuel** [comment]
@httpstorm i checked... when the string is pushed LUA operates under lock but not before so ATOMIC can't be used i think..

**Comment by httpstorm** [comment]
@Ansuel 
> and ideally also apply that to broadcom-wl
Please explain!

**Comment by Ansuel** [comment]
@httpstorm would you hate me if I ask you to split this? Tell me if it's problematic for. (and we can skip this) 
The commit is OK with the change, but I would split the package bump from the fixes part

Also I would add in credits me in co developed tag?

**Comment by httpstorm** [comment]
@Ansuel 
From what I see here
https://www.unix.com/man-page/suse/9/KCALLOC/

- GFP_KERNEL - Allocate normal kernel ram. May sleep.
- GFP_ATOMIC - Allocation will not sleep. May use emergency pools. For example, use this inside interrupt handlers.

**Comment by httpstorm** [comment]
@Ansuel 
> @httpstorm would you hate me if I ask you to split this? Tell me if it's problematic for. (and we can skip this)
> The commit is OK with the change, but I would split the package bump from the fixes part

Ha hah, I promise I won't! 😀 I was curious which way is better. My first implementation actually had fix + bump.
Then I merged them, because I had a bump commit with empty body. A couple of refreshes should do the job.

> Also I would add in credits me in co developed tag?
ok, I'm still learning about these rules.

**Comment by Ansuel** [comment]
> ok, I'm still learning about these rules.

thing is confusing since 3 guys proposed a very similar fix and the patch got merged by multiple author ahahah

**Comment by Ansuel** [comment]
@httpstorm since you are rebasing Fixes tag right above the co-developed-by tag (no new line between them)

**Comment by httpstorm** [comment]
@Ansuel 
I'm ready. It was nice working with you! 🍻 I see you merged it just as I was installing the firmware for a final test. What about the `broadcom-wl`?

BTW how can I become part of the OpenWRT team? I like creating fixes every now and then, and for the most part it's pretty easy to get them accepted, since the people here are friendly and guide me to create good PRs. A couple of days ago however one of my fixes introduced an issue, so I prepared an urgent fix, but since I have no write access, to took a day to merge it. At that moment I wish I had write access to resolve it faster. I also see that even people with write access generally allow a couple of days so that others can check their work before they merge it. Nice practice.

**Pull request merged**
