### PR TITLE
gcc : adding missing patches to perform native build on ar71xx devices

### PR DESCRIPTION
**Pull request by artynet**
<devel/gcc>

Maintainer: @noblepepper 
Compile tested: ar71xx/generic, LEDE trunk @f500799
Run tested: ar71xx/generic, LEDE trunk @f500799

Description:

adding missing patches to perform native build on ar71xx/generic platform and devices

Signed-off-by: Arturo Rinaldi arty.net2@gmail.com

### CODE REVIEW

**Comment by noblepepper** [comment]
Have you build tested on ramips & mvebu? It will be awhile before I have time to, if you have it would save time.

**Comment by artynet** [comment]
Hello @noblepepper,

I'll give it a try but I am pretty overwhelmed with my current tasks at the moment and I will be for the next two days. Anyway, I can only test the build since I don't usually work with **ramips** on **mvebu** boards.

The first three patches basically complete the current toolchain series while the last one is needed to actually perform the build since it avoids the **sysdt** error.

Best, Arturo

**Comment by artynet** [comment]
Hello @noblepepper,

build achieved on ramips and mvebu as well ! Please take a look here https://goo.gl/rdzOmv :

01-gcc_5.4.0-2_mipsel_24kc.ipk
02-gcc_5.4.0-2_mips_24kc.ipk
03-gcc_5.4.0-2_arm_cortex-a9_vfpv3.ipk

01 : build achieved on mipsel (ramips) with the applied patches
02 : build achieved on mips (ar71xx) with the latest versions of the libraries and dropping 003-mpfr-longlong-mips.patch
03 : build achieved on arm_cortex-a9_vfpv3 (mvebu) with the applied patches

in addition to this, this is my patch to definitely drop the mpfr patch :

```patch
diff --git a/devel/gcc/Makefile b/devel/gcc/Makefile
index f8f754ff30..37bee31b28 100644
--- a/devel/gcc/Makefile
+++ b/devel/gcc/Makefile
@@ -9,7 +9,7 @@ include $(TOPDIR)/rules.mk
 
 PKG_NAME:=gcc
 PKG_VERSION:=5.4.0
-PKG_RELEASE:=2
+PKG_RELEASE:=3
 PKG_SOURCE_URL:=@GNU/gcc/gcc-$(PKG_VERSION)
 PKG_MD5SUM:=4c626ac2a83ef30dfb9260e6f59c2b30
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
@@ -49,30 +49,30 @@ define Package/gcc/description
 	build a native toolchain for compiling on target
 endef
 
-GMPSRC=gmp-4.3.2
+GMPSRC=gmp-6.1.2
 
 define Download/gmp
   URL:=ftp://gcc.gnu.org/pub/gcc/infrastructure/
   FILE:=$(GMPSRC).tar.bz2
-  MD5SUM:=dd60683d7057917e34630b4a787932e8
+  MD5SUM:=8ddbb26dc3bd4e2302984debba1406a5
 endef
 $(eval $(call Download,gmp))
 
-MPCSRC=mpc-0.8.1
+MPCSRC=mpc-1.0.3
 
 define Download/mpc
   URL:=ftp://gcc.gnu.org/pub/gcc/infrastructure/
   FILE:=$(MPCSRC).tar.gz
-  MD5SUM:=5b34aa804d514cc295414a963aedb6bf
+  MD5SUM:=d6a1d5f8ddea3abd2cc3e98f58352d26
 endef
 $(eval $(call Download,mpc))
 
-MPFRSRC=mpfr-2.4.2
+MPFRSRC=mpfr-3.1.5
 
 define Download/mpfr
   URL:=ftp://gcc.gnu.org/pub/gcc/infrastructure/
   FILE:=$(MPFRSRC).tar.bz2
-  MD5SUM:=89e59fe665e2b3ad44a6789f40b059a0
+  MD5SUM:=b1d23a55588e3b2a13e3be66bc69fd8d
 endef
 $(eval $(call Download,mpfr))
 
@@ -86,10 +86,6 @@ define Build/Prepare
 	tar -C $(PKG_BUILD_DIR) -xvjf $(DL_DIR)/$(MPFRSRC).tar.bz2
 	ln -sf $(PKG_BUILD_DIR)/$(MPFRSRC) $(PKG_BUILD_DIR)/mpfr
 	$(Build/Patch)
-#	poor man's fix for `none-openwrt-linux' not recognized when building with musl
-	cp $(PKG_BUILD_DIR)/config.sub $(PKG_BUILD_DIR)/mpfr/
-	cp $(PKG_BUILD_DIR)/config.sub $(PKG_BUILD_DIR)/gmp/
-	cp $(PKG_BUILD_DIR)/config.sub $(PKG_BUILD_DIR)/mpc/
 endef
 
 
diff --git a/devel/gcc/patches/003-mpfr-longlong-mips.patch b/devel/gcc/patches/003-mpfr-longlong-mips.patch
deleted file mode 100644
index 0ab9fe5032..0000000000
--- a/devel/gcc/patches/003-mpfr-longlong-mips.patch
+++ /dev/null
@@ -1,38 +0,0 @@
-diff -Naurd mpfr-2.4.2-a/mpfr-longlong.h mpfr-2.4.2-b/mpfr-longlong.h
---- -a/mpfr-2.4.2/mpfr-longlong.h	2009-11-30 02:43:08.000000000 +0000
-+++ -b/mpfr-2.4.2/mpfr-longlong.h	2009-12-18 12:04:29.000000000 +0000
-@@ -1011,7 +1011,15 @@
- #endif /* __m88000__ */
- 
- #if defined (__mips) && W_TYPE_SIZE == 32
--#if __GNUC__ > 2 || __GNUC_MINOR__ >= 7
-+#if (__GNUC__ >= 5) || (__GNUC__ >= 4 && __GNUC_MINOR__ >= 4)
-+#define umul_ppmm(w1, w0, u, v) \
-+  do {									\
-+    UDItype _r;							\
-+    _r = (UDItype) u * v;						\
-+    (w1) = _r >> 32;							\
-+    (w0) = (USItype) _r;						\
-+  } while (0)
-+#elif __GNUC__ > 2 || __GNUC_MINOR__ >= 7
- #define umul_ppmm(w1, w0, u, v) \
-   __asm__ ("multu %2,%3" : "=l" (w0), "=h" (w1) : "d" (u), "d" (v))
- #else
-@@ -1024,7 +1032,16 @@
- #endif /* __mips */
- 
- #if (defined (__mips) && __mips >= 3) && W_TYPE_SIZE == 64
--#if __GNUC__ > 2 || __GNUC_MINOR__ >= 7
-+#if (__GNUC__ >= 5) || (__GNUC__ >= 4 && __GNUC_MINOR__ >= 4)
-+typedef unsigned int UTItype __attribute__ ((mode (TI)));
-+#define umul_ppmm(w1, w0, u, v) \
-+  do {									\
-+    UTItype _r;							\
-+    _r = (UTItype) u * v;						\
-+    (w1) = _r >> 64;							\
-+    (w0) = (UDItype) _r;						\
-+  } while (0)
-+#elif __GNUC__ > 2 || __GNUC_MINOR__ >= 7
- #define umul_ppmm(w1, w0, u, v) \
-   __asm__ ("dmultu %2,%3" : "=l" (w0), "=h" (w1) : "d" (u), "d" (v))
- #else

```

Best, Arturo

**Comment by noblepepper** [comment]
Apologies for the silence, I've been concerned with other things as well. Hopefully will have more time to spend on this now. 

Just downloaded your files, they will definitely save me some time. I will test on ramips, I don't have mvebu platform either. I'll ping recyclebin99 who did testing on mvebu before.

Thanks for your patience!

**Comment by artynet** [comment]
no big deal @noblepepper ! Happy to give this contribution....please take all the time you need ! In the meanwhile I'll test my new gcc build ;)

Best, Arturo

**Comment by artynet** [comment]
hello @noblepepper, any updates on this ? Any news from recyclebin99 as well ?

Arturo

**Comment by artynet** [comment]
I think we should be set now @champtar, please let me know....

**Comment by champtar** [comment]
@artynet waiting for ack/nack from @noblepepper now

**Comment by artynet** [comment]
ok, great to know @champtar

**Comment by champtar** [comment]
ping @noblepepper

**Comment by artynet** [comment]
@champtar I think I should change the commit description removing the blank space before the colon

**Pull request closed without merging**
