### PR TITLE
new package for jamvm, classpath: review request

### PR DESCRIPTION
**Pull request by danak6jq**
I've created this fork to both move classpath and jamvm into the 'new' packages GIT as well as update to the latest versions of both projects (JamVM 2.0.0, GNU Classpath 0.99)

Further, I've included patches for classpath-0.99 that address the floating-point toString() memory leak described here that is not yet addressed in the master classpath project:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=29263

This pull request is for an initial review of the proposed changes; I'm new to this development community; please forgive me if I am not following the correct process :-) 

I have built both MIPS and ARM variants of OpenWRT incorporating these proposed changes, and am currently running the packages produced by these changes on several Carambola2-based systems.

If, in fact, I've included enough of the correct meta-data and this can be pulled up into the master, that would be great, too.

Thank you for the help,
Dana
Signed-off-by: Dana H. Myers <k6jq@comcast.net>

### CODE REVIEW

**Comment by danak6jq** [comment]
Note that this proposed changeset would benefit from a rebase, though I don't yet know how to do that directly on github.com :-)

**Comment by mhei** [comment]
This already looks good, only a few things I would suggest:
- please split this single PR into two PRs, one each for (migrated) package
- please squash all commits for one package into a single commit
- some minor cosmetic changes, mostly whitespace, e.g. in MAINTAINER line

I think you have to do the rebase manually, I don't think this is possible with GitHub. You have commited your changes within the 'master' branch of your forked packages repo. Things would be easier, if you create a working branch while developing, then submit the PR based on this working branch. When the PR is merged, you can simply delete this working branch.

**Comment by danak6jq** [comment]
I admit my git-fu isn't very strong; I believe the easiest thing for me is to start fresh with a new packages-master, and re-integrate the changes as suggested. 

Thanks for the help - I'll get this right :-)

**Comment by danak6jq** [comment]
I will re-submit the proper pull requests once the repo fork is correct. Thanks!

**Pull request closed without merging**
