### PR TITLE
miniupnpd: Update package to 2.3.6

### PR DESCRIPTION
**Pull request by Self-Hosting-Group**
and change title to term used in LuCi

Maintainer:
Compile tested: not tested on OpenWrt
Run tested: not tested on OpenWrt

### CODE REVIEW

**Comment by 1715173329** [comment]
> but since the old name is still accepted, no change was made in the PR.

Please follow upstream change and migrate to new config name.

**Comment by BKPepe** [comment]
Also, make sure that it is compile and run tested for OpenWrt.

**Comment by BKPepe** [comment]
Ehh... for me it seems like the title is the same. Why do we need to have this change? Since, there is no commit description, it is not clear. I am in favor to close this PR.

**Comment by stangri** [comment]
> @stangri: Thank you for your reply. PR updated. Can we possibly do the PR without the configuration change (as backword compatible) and do it in a later PR (including LuCi)? I am waiting for some more upstream changes.

That's up to maintainer, I just provided (hopefully helpful) feedback.

**Comment by BKPepe** [comment]
CI is still failing for you. Would you mind to fix it?

**Pull request merged**
