### PR TITLE
zerotier: update to 1.8.1

### PR DESCRIPTION
**Pull request by oskarirauta**
Release notes:

1.8.0
 - Upgrade json.hpp dependency to version 3.10.2
 - Check if DNS servers need to be applied on macOS
 - Set MAC address before bringing up Linux TAP link
 - Stop binding to temporary IPv6 addresses
 - Fix for mistakenly using v6 source addresses for v4 routes on some platforms
 - Fix for MacOS MTU capping issue on feth devices
 - Implement a workaround for one potential source of a "coma" bug, which can occur if buggy NATs/routers stop allowing the service to communicate on a given port. ZeroTier now reassigns a new secondary port if it's offline for a while unless a secondary port is manually specified in local.conf. Working around crummy buggy routers is an ongoing effort.
 - A completely rewritten desktop UI for Mac and Windows!

1.8.1
 - Fix an issue that could cause clobbering of MacOS IP route settings on restart.
 - Added additional hardening against address impersonation on networks (also in 1.6.6).
 - MacOS IPv6 no longer binds to temporary addresses as these can cause interruptions if they expire.
 - Remove support for REALLY ancient 1.1.6 or earlier network controllers.
 - Fix numerous UI issues from 1.8.0 (never fully released).

Changed GIT as source and added $(AUTORELEASE)

Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

Maintainer: Moritz Warning / @mwarning
Compile tested: x86_64, pc, recent snapshot
Run tested: x86_64, pc, recent snapshot

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
You further add autorelease and change to git as source. Maybe also say that in commit message. :)

**Comment by mwarning** [comment]
thank you, looks good, LGTM

**Comment by oskarirauta** [comment]
> You further add autorelease and change to git as source. Maybe also say that in commit message. :)

done

**Comment by oskarirauta** [comment]
> thank you, looks good, LGTM

works great too. With previous versions, sometimes all nodes were not connectable between some others. This has not failed ever since after upgrading.

**Comment by PolynomialDivision** [comment]
thanks. will merge after ci finishes.

**Pull request merged**
