### PR TITLE
libwebsockets: fix compilation with newer GCC

### PR DESCRIPTION
**Pull request by neheb**
Errors on uninitialized variable. No idea why only on powerpc64.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @karlp 
Compile tested: powerpc64

ping @stintel

### CODE REVIEW

**Comment by karlp** [comment]
has this been filed upstream?  Otherwise looks fine, certainly harmless.  disabling werror is probably saner for downstream builds, but whatever

**Comment by neheb** [comment]
Probably. I didn't look into disabling Werror as this is a really simple fix.

Still interesting that I only got this error with @stintel 's special powerpc64 config.

**Comment by neheb** [comment]
Anyway, upstream PR: https://github.com/warmcat/libwebsockets/pull/2551

**Comment by neheb** [comment]
Upstream fixed it differently. Backported.

**Pull request merged**
