### PR TITLE
ntpd: package bump

### PR DESCRIPTION
**Pull request by systemcrash**
Maintainer: Peter Wagner <tripolar@gmx.at> / @tripolar

### CODE REVIEW

**Comment by 1715173329** [comment]
CI says:

> Applying patch 0001-libntp-Do-not-use-PTHREAD_STACK_MIN-on-glibc.patch
> patching file libntp/work_thread.c
> Hunk #1 FAILED at 41.
> 1 out of 1 hunk FAILED -- rejects in file libntp/work_thread.c

Please check.
Please also mention typo fixes to README in commit message.

**Comment by systemcrash** [comment]
Dropped the patch. FYI: https://bugs.ntp.org/show_bug.cgi?id=3741

**Comment by systemcrash** [comment]
Some of the other tests seem to complain about an unrelated crypto thing for other platforms. e.g. powerpc -> cryptodev. Unrelated.

**Comment by 1715173329** [comment]
> Some of the other tests seem to complain about an unrelated crypto thing for other platforms. e.g. powerpc -> cryptodev. Unrelated.

Yep, runtime containers, and cryptodev on ppc are known broken.

**Comment by systemcrash** [comment]
Run tested fine on x86_64:
```
root@OpenWrt:/tmp# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
stepping	: 10
...


opkg install ./ntpd_4.2.8p17-1_x86_64.ipk
Upgrading ntpd on root from 4.2.8p15-4 to 4.2.8p17-1...
Configuring ntpd.
root@OpenWrt:/tmp# /etc/init.d/ntpd status
running

ntpd -?
ntpd - NTP daemon program - Ver. 4.2.8p17
Usage:  ntpd [ -<flag> [<val>] | --<name>[{=| }<val>] ]... \
		[ <server1> ... <serverN> ]
...
```

**Comment by systemcrash** [comment]
This can go in safely now

**Review by 1715173329 — APPROVED** [review]

**Pull request merged**
