### PR TITLE
collectd: Support config of mqtt plugin

### PR DESCRIPTION
**Pull request by akosiaris**
Maintainer: me
Compile tested: No
Run tested: aarch64, openwrt-22.03 branch git-22.245.77528-487e58a, stop/start/restart populating various configuration values. 

Description:

mqtt plugin is already built and shipped in
collectd-mod-mqtt, however it is not possible to configure it via uci currently, instead having to rely on populating the config file manually.

Add support by adding 2 functions, `process_mqtt()` and `process_mqtt_block()`. First one just enables/disables the plugin. The second one, in the spirit of the curl plugin, adds support for populating multiple `<Publish>` and `<Subscribe>` blocks under `<Plugin mqtt>` with support for some parameters. Those are:

* blocktype. Publish or Subscribe. Mandatory
* name. The name of the block. Mandatory
* Host. Mandatory
* Port. Optional
* User. Optional
* Password. Optional
* ClientId. Optional
* QoS. Optional
* Prefix. Optional
* Retain. Optional
* StoreRates. Optional
* CleanSession. Optional
* Topic. Optional

### CODE REVIEW

**Comment by BKPepe** [comment]
You should increase ``PKG_RELEASE`` in the Makefile.

**Comment by akosiaris** [comment]
Error seems unrelated with my change. Across all archs what I see is (example is x86_64)

```
make[5]: Entering directory '/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.98'
  MODPOST /home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/Module.symvers
ERROR: modpost: "DSL_BSP_Showtime" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_KernelIoctls" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_DriverHandleDelete" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_EventCBRegister" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_EventCBUnregister" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_AdslLedInit" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_MemoryDebugAccess" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_DriverHandleGet" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_SendCMV" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_FWDownload" [/home/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
```

**Comment by McGiverGim** [comment]
I think you forgot to add "Host" as parameter in the list published in the first message of the Conversation. I have seen it's in the code.
As curiosity, are you planning to add the mqtt configuration to the statistics Luci app?

**Comment by akosiaris** [comment]
> You should increase `PKG_RELEASE` in the Makefile.

Thanks for the pointer. Done

> I think you forgot to add "Host" as parameter in the list published in the first message of the Conversation. I have seen it's in the code. 

Nice catch, thanks. Fixed.

> As curiosity, are you planning to add the mqtt configuration to the statistics Luci app?

That wasn't in my plans, to be honest. I could have a look and see how easy it is though.

**Comment by McGiverGim** [comment]
> That wasn't in my plans, to be honest. I could have a look and see how easy it is though.

I've done a little experiment with this, but I'm not able to compile your package so I will wait until this is merged to see if it works.

**Comment by McGiverGim** [comment]
@akosiaris if you want to try, look at the latest commit on this branch: https://github.com/McGiverGim/luci/tree/add_mqtt_statistics

You only need to add the two files to the corresponding path in your router `/www/luci-static/resources/view/statistics/plugins` and `/usr/share/luci/statistics/plugins/` and do a `service uhttpd restart`. 

Is the first time I play with luci, so maybe is a better way to do this. All seems to work except the validation of mandatory fields, I don't know why. I only tested that this modifies the `luci_statistics` config file because I'm not able to build your package.

**Comment by feckert** [comment]
LGTM
Please update PKG_RELEASE number by one https://github.com/openwrt/packages/blob/master/utils/collectd/Makefile#L12

**Comment by akosiaris** [comment]
> LGTM Please update PKG_RELEASE number by one https://github.com/openwrt/packages/blob/master/utils/collectd/Makefile#L12

I was under the impression I already had but I apparently was wrong. Thanks for catching that! Fixed.

**Comment by feckert** [comment]
LGTM
Thanks meged!

**Comment by akosiaris** [comment]
My thanks as well!

**Comment by McGiverGim** [comment]
@akosiaris I know this is an old PR, but, it's working? I'm trying to use it, to try later to add the LuCi UI page, but after adding the config to the luci_statistics file, with uci commands (as expected), reloading the service produces this error:
```
root@router-comedor:/etc/config# service luci_statistics reload
Type error: (null) is not iterable
In section(), file /usr/libexec/stat-genconfig, line 253, byte 76:
  called from anonymous function (/usr/libexec/stat-genconfig:284:17)

 `            params = config_generic(config, ...plugins[plugin], plugin == 'collectd');`
  Near here --------------------------------------------------------------------------^
```
This is my config:
```
config statistics 'collectd_mqtt'
        option enable '1'

config mqtt_block
        option blocktype 'Publish'
        option name 'name'
        option Host 'host'
        option User 'mqtt'
        option Password 'pass'
```
I've observed that the error is produced simply enabling it, the `mqtt_block` is indiferent.

I think you based your code in cURL plugin. I've seen some code for cURL directly in the `stat-genconfig` but there's no code for Mqtt.
Do you know what is happening? Maybe I've done something wrong?

**Comment by McGiverGim** [comment]
@akosiaris I've seen that the error is caused by my code that adds the UI. Removing it, the error disappears but it seems that the plugin does not load. I will keep investigating, but it seems a problem on my side.

**Comment by akosiaris** [comment]
Thanks for the follow up @McGiverGim!

**Pull request merged**
