### PR TITLE
bossa: fix fpic compilation

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Fixes: #17287 ("bossa: recompile with -fPIC")

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@BKPepe Could you test again?

**Comment by BKPepe** [comment]
Thanks, it seems that I was able to compile it, but I didn't do a run test so far.

**Comment by PolynomialDivision** [comment]
> Thanks, it seems that I was able to compile it, but I didn't do a run test so far.

Can you just merge, then you did a run-test?

**Comment by PolynomialDivision** [comment]
Run-tested on mips24kc. :) Works.

**Pull request merged**
