### PR TITLE
iperf3/python-iperf3: add python-iperf3 and necessary libs

### PR DESCRIPTION
**Pull request by PolynomialDivision**
```
iperf3: add shared libiperf library and link iperf3 dynamically

Add library for creating own functions with iperf3 functionality.
Example: https://github.com/esnet/iperf/blob/master/examples/mis.c
This library is needed by python3-iperf3.

Build iperf3 binary with dynamically linked libiperf3. However, still
build iperf3-ssl as static binary due to a lack of shipping two libiperf
versions.
```

```
python3-iperf3: add iperf3 python wrapper

This wrapper gives us an easy to use api for using iperf3 in python.
```

Maintainer: @nbd168 
Compile tested: belkin rt3200
Run tested: belkin rt3200

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
We grow in size by around `((64203+842)-51306)/1024=13 KiB`

Statically linked:
```
51306	iperf3_3.11-1_aarch64_cortex-a53.ipk
```

Shared:
```
64203	iperf3_3.11-1_aarch64_cortex-a53.ipk
842	libiperf3_3.11-1_aarch64_cortex-a53.ipk
````

**Comment by PolynomialDivision** [comment]
ping @neheb ? ;)

**Comment by anomeome** [comment]
```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libiperf3 for iperf3
 * pkg_hash_fetch_best_installation_candidate: Packages for iperf3 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package iperf3.

```
on target mvebu from a make clean

**Comment by PolynomialDivision** [comment]
Can you try with a fresh git clone?

**Comment by anomeome** [comment]
Not sure what that is expected to achieve, I have not done a clone in years. At any rate, I did the extreme nuke option of _make dirclean_, suspecting perhaps a _dried muffin remnant_ in _staging_, same result. Do not think this is something in my tree, but anything be possible.

**Comment by neheb** [comment]
Yeah this was not tested. Great...

**Comment by PolynomialDivision** [comment]
@anomeome I was just confused because there was no fail-log under: https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a8_vfpv3/packages/

Let me test everything again.

**Comment by neheb** [comment]
```
Hi,

commit "ae48be8e2157bc7c352b3b6d30c026fafdae4867 / iperf3: add shared libiperf library and link iperf3 dynamically" is wrong. The install rule for libiperf3 overrides the rule for iperf3. Iperf3 itself will not be installed.

diff --git a/net/iperf3/Makefile b/net/iperf3/Makefile
index db3b6e432..a5f465f99 100644
--- a/net/iperf3/Makefile
+++ b/net/iperf3/Makefile
@@ -97,7 +97,7 @@ define Package/iperf3-ssl/install
        $(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/iperf3 $(1)/usr/bin/
  endef

-define Package/iperf3/install
+define Package/libiperf3/install
        $(INSTALL_DIR) $(1)/usr/lib
        $(CP) $(PKG_INSTALL_DIR)/usr/lib/libiperf.so.* $(1)/usr/lib
  endef

Regards,
Hartmut
```

**Comment by PolynomialDivision** [comment]
Thanks! Just also saw it. Sorry, something messed up when I did this PR. I lost the changes and had to redo them and than this typo happened.

**Comment by hnyman** [comment]
@PolynomialDivision 
Out of curiosity: you mention "run-tested with RT3200", but apparently you had tested something else than the actual PR changes????

It makes sense to transfer the tested commits directly to the PR branch, or the tested code via diff & patch, instead of trying to write the same by hand again.

**Comment by PolynomialDivision** [comment]
I normally symlink the packages repository into my openwrt toolchain. However, I had two commits in one PR. I made the first iperf3 commit and than messed something up while doing the python3-iperf3 commit. However, the python3 package was still working fine, because the iperf3 package installed the library instead of the iperf3 binary. I should have tested the iperf3 package again.

**Pull request merged**
