### PR TITLE
treewide: compile with tools/meson

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dhewg 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
sounds like SDK is not updated yet.

**Comment by dhewg** [comment]
LGTM,

Random note: In include/meson.mk there's a leftover comment: `# HOST_BUILD_DEPENDS:=meson/host`.
Not worth a patch by itself, but let's remove than with the next meson bump?

**Comment by neheb** [comment]
Yeah good point.

**Comment by neheb** [comment]
```
ERROR: package/feeds/base/gettext-full failed to build.
```

gettext-full can kick rocks.

**Pull request merged**
