### PR TITLE
libaio: Update to 0.3.111

### PR DESCRIPTION
**Pull request by neheb**
Switched to new upstream at pagure.io.

Refreshed debian patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @sbyx 
Compile tested: ipq806x

### CODE REVIEW

**Comment by diizzyy** [comment]
I'd like this one run tested on a few platforms before bumping

**Comment by neheb** [comment]
Why?

**Comment by diizzyy** [comment]
There seems to be quite a bit of a difference between distros regarding this library.

Arch/Alpine/ --> No patches
Debian --> Several
Fedora --> https://src.fedoraproject.org/rpms/libaio/blob/master/f/libaio-install-to-destdir-slash-usr.patch
etc

**Comment by neheb** [comment]
Arch is x86 only.

Fedora is x86/ARM.

Debian, like OpenWrt runs on many different platforms.

The Debian patches are for these other platforms.

**Comment by diizzyy** [comment]
Both OpenEmbedded and Yocto runs on a lot of different platforms, compare that to Debian which makes me wonder if they're all really needed
https://git.hadrons.org/cgit/debian/pkgs/libaio.git/tree/debian/patches

**Comment by neheb** [comment]
I just took a look at the OpenEmbedded patches. 00_arches.patch is a heavily modified version of the debian one with support for PA-RISC, which OpenWrt does not support AFAIK. I also don't like their syscall changes. No other platform in libaio has hacks like those. Sounds specific to older kernel versions honestly.

As far as the Debian patches go, 002 can go as I don't think OpenWrt supports Renesas SH CPUs. 004 looks like a compatibility fix for glibc. The rest belong. They have a higher chance of being upstreamed anyway.

**Comment by neheb** [comment]
Added a dependency on KERNEL_AIO. Instead of manually doing so for every package, it makes much more sense to put the dependency here. It's needed for it to work properly. Otherwise errors such as these pop up: https://forum.openwrt.org/t/lvm2-in-18-06-1/19807/3

**Comment by neheb** [comment]
In the interest of seeing this get merged, I have added myself as maintainer. @hnyman please pull.

**Comment by hnyman** [comment]
This seems to create a recursive dependency.
I will revert this.

```
perus@ub1810:/Openwrt/r7800$ make defconfig
tmp/.config-package.in:34513:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:34513:	symbol PACKAGE_libaio is selected by PACKAGE_tgt
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:93551:	symbol PACKAGE_tgt depends on KERNEL_AIO
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
config/Config-kernel.in:195:	symbol KERNEL_AIO is selected by PACKAGE_libaio
#
# configuration written to .config
#
```

There should probably be just `DEPENDS:=@KERNEL_AIO`
instead of `DEPENDS:=+@KERNEL_AIO`

Forcing a kernel symbol from a package does not really work (espacilly in buildbot, where kernel is compiled in phase1 separately from packages in phase2 buildbt.

**Comment by neheb** [comment]
I haven’t tested that before, just lvm2 and fio.

My understanding is that AIO is enabled in release versions but not when building snapshot builds. I will look into this.

**Comment by hnyman** [comment]
> My understanding is that AIO is enabled in release versions but not when building snapshot builds. 

Never heard of that. If you look at the release .configs (as config.seed in the download dir), there is nothing else than adding LuCI and disabling some kernel debugging. But no special kernel options are set. There is no fundamental difference between snapshot and release kernel options.

Having a requirement of a non-standard kernel option is actually pretty nasty requirement for a package. The phase1 buildbot does not know about that (and we would not like to set that kernel option globally in any case), so the phase2 package buildbot does never see that option set in the SDK.

My take is that the buildbot will never build the package, but the normal approach is to just depend on `@KERNEL_AIO`, so that the private builder needs to first set the KERNEL_AIO option, and only then he can see the libaio package.

Ps. the really interesting part is the link to to the forum: https://forum.openwrt.org/t/lvm2-in-18-06-1/19807/5 . I have not even tried to look into AIO options in generic & target configs, but your observation there looks strange.

**Comment by hnyman** [comment]
>  If what you say is true, ...

In any case, 17.01, 18.06 and master snapshots and releases have been built in the two-phase buildbot, so the kernel and core packages get built first in phase1, and all stuff from the packages feed repo is unknown to that phase1 kernel buildbot.

It is naturally possible that `@KERNEL_AIO` is selected all the time, so that your "+" is quite unnecessary.

Like I said above, I have not even tried to look into it. I just reacted to the created circular dependency by this PR.

**Comment by diizzyy** [comment]
Honestly, don't merge PRs that hasn't been run tested and calling yourself a maintainer doesn't give you "blanket approval".

**Comment by neheb** [comment]
This has been run tested for the past 4 months with both LVM2 and fio. tgt was not a factor in my testing.

**Pull request merged**
