### PR TITLE
openvpn: add OpenVPN option disable-dco

### PR DESCRIPTION
**Pull request by sch-m**
Maintainer: @AuthorReflex
Compile tested: x86_64, latest master
Run tested: x86_64, latest master

Description:

You maybe want to disable the DCO support, so let's add this option.

### CODE REVIEW

**Comment by systemcrash** [comment]
@neheb @feckert @AuthorReflex @BKPepe

**Comment by BKPepe** [comment]
Hey @systemcrash , there is no need to ping everyone about this. If you want to review it, then please do it. We do have more than 250 pull requests opened and there is appreciated help as always. You can raise discussion about lack of reviewers at development list or at OpenWrt forum, which could be helpful.

Things take time. It applies to everything and please keep in mind that we (I mean me) is doing this in my free time and I am not payed for this)

**Review by systemcrash — APPROVED** [review]

**Comment by neheb** [comment]
needs a rebase I think.

**Comment by systemcrash** [comment]
> needs a rebase I think.

Look fine from here.

**Comment by neheb** [comment]
PKG_RELEASE needs bumping AFAIK. I merged a commit that did so.

**Comment by sch-m** [comment]
> PKG_RELEASE needs bumping AFAIK. I merged a commit that did so.

I've rebased this PR, but PKG_RELEASE is still the same.

**Comment by systemcrash** [comment]
> > PKG_RELEASE needs bumping AFAIK. I merged a commit that did so.
> 
> I've rebased this PR, but PKG_RELEASE is still the same.

And that's likely why tests fail. Did you rebase on main?

**Comment by sch-m** [comment]
> > > PKG_RELEASE needs bumping AFAIK. I merged a commit that did so.
> > 
> > 
> > I've rebased this PR, but PKG_RELEASE is still the same.
> 
> And that's likely why tests fail. Did you rebase on main?

I can't see any problem. The PKG_RELEASE is `4` at the moment and my commit will change it to `5`:
https://github.com/openwrt/packages/blob/master/net/openvpn/Makefile#L13

**Comment by systemcrash** [comment]
OK. I see the problem now. 

#23272 only adds the fix to 23, which seems to be in master already. 

@neheb : it looks safe to merge this (this is for openvpn 2.6, #23272 was for openvpn 2.5)

**Pull request merged**
