### PR TITLE
ariang: add new package

### PR DESCRIPTION
**Pull request by Ansuel**
Maintainer: me 
Compile tested: r7800 ipq8065 trunk
Run tested: r7800 ipq8065 trunk

Description: Modern webui for aria2 package

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@dangowrt can we add this?

**Comment by dibdot** [comment]
No dependency to uhttpd package? Not tested yet, just wondering.

**Comment by Ansuel** [comment]
As it's a webui I think it's wrong to tie this to only uhttpd... If someone wants to install another for example nginx with the uhttpd dep, can't install also this package... If you think I should add it... It's ok for me...

**Comment by dibdot** [comment]
Well, a web frontend without installed web server makes no sense as well. Maybe you could add the uhttpd dependency by default and make further web server options configurable in your package!? Anyway just a suggestion ... and please add aria2c as dependency, too.

Thanks!

**Comment by Ansuel** [comment]
@dibdot ok for me... will add this 2 dep

**Comment by Ansuel** [comment]
MERGE PLS

**Comment by dibdot** [comment]
Did you test your latest changes? The dependency "aria2c" is unfortunately wrong. Though the client called "aria2c", the package name is "aria2" - so please change this. Meanwhile I've tested your package and the Aria2 Status is always reported as "Not connected" in AriaNg - is this expected?

**Comment by Ansuel** [comment]
@dibdot as webui-aria2 you need to first set aria2 to enable rpc 
if you want i can give you a configuration sample

**Pull request merged**
