### PR TITLE
circleci: Add 19.07 GPG/usign public keys, verify keys

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @thess, @champtar 
Compile tested: N/A
Run tested: N/A

Description:
This also updates the user id comments for GPG keys and untrusted comments for usign keys.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
I know that is just an incremental update to the existing procedure but maybe it makes sense to hardcode the sha256 digests of they keys you download here, or verify them after the curl command using something like 

```
echo 'b1d09457cfbc36fccfe18382d65c54a2ade3e7fd3902da490a53aa517b512755 */home/build/usign/f94b9dd6febac963' | sha256sum
```

**Comment by jefferyto** [comment]
@jow- Sounds good - should the gpg keys also be verified?

**Comment by jow-** [comment]
Either that or compare the resulting fingerprints against hardcoded expected ones.

**Comment by jefferyto** [comment]
I tried verifying signatures with a key that doesn't have ultimate trust. It succeeded (exit value 0) but it displayed a warning saying the key isn't trusted. So I think verifying the imported key is still useful.

**Comment by jefferyto** [comment]
@aparcar It [looks like](https://hub.docker.com/r/openwrtorg/packages-cci/tags) you've been managing the Docker packages-cci images? Would you mind tagging v1.0.5?

**Comment by aparcar** [comment]
Done

**Pull request merged**
