### PR TITLE
wifischedule: respect global enable during startup

### PR DESCRIPTION
**Pull request by raenye**
(combined into #22974)

### CODE REVIEW

**Comment by BKPepe** [comment]
You need to bump ``PKG_RELEASE`` in the Makefile.

**Comment by raenye** [comment]
Thanks @BKPepe, I'm just not sure how to deal with two concurrent PRs to the same package.

Maybe I should submit a single PR for both changes? (fix the two related bugs together)

**Comment by 1715173329** [comment]
> Thanks @BKPepe, I'm just not sure how to deal with two concurrent PRs to the same package (the other is #22974).
> 
> Maybe I should submit a single PR for both changes? (fix the two related bugs together)

Yes, to the same package, it's okay.

**Comment by raenye** [comment]
Done; please see #22974.

**Pull request closed without merging**
