### PR TITLE
cpupower: add new package

### PR DESCRIPTION
**Pull request by graysky2**
Linux kernel userspace tool to examine and to tune power saving related features of the processor

### CODE REVIEW

**Comment by graysky2** [comment]
@BKPepe - Somehow when I pulled master/rebased for my force push, it pulled into hundreds of commits.  I couldn't recover from that.

https://github.com/openwrt/packages/pull/21533

**Comment by graysky2** [comment]
Does anyone have some insights into why this is failing?
```
% i=cpupower
% make package/$i/{clean,compile} package/index V=s 
...
rm -f /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79/.built
touch /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79/.built_check
(cd /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79; 	make CC="x86_64-openwrt-linux-musl-gcc" CFLAGS="-march=znver3 -O3 -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79=cpupower-6.1.79 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LDFLAGS="-L/scratch/union/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/lib -L/scratch/union/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro" DESTDIR=fake install-tools)
make[3]: Entering directory '/scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79'
grep: ../../../Makefile: No such file or directory
grep: ../../../Makefile: No such file or directory
grep: ../../../Makefile: No such file or directory
grep: ../../../Makefile: No such file or directory
Makefile:98: ../../scripts/Makefile.arch: No such file or directory
make[3]: *** No rule to make target '../../scripts/Makefile.arch'.  Stop.
make[3]: Leaving directory '/scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79'
make[2]: *** [Makefile:58: /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79/.built] Error 2
make[2]: Leaving directory '/scratch/union/feeds/packages/utils/cpupower'
time: package/feeds/packages/cpupower/compile#0.19#0.12#0.30
    ERROR: package/feeds/packages/cpupower failed to build.
make[1]: *** [package/Makefile:128: package/feeds/packages/cpupower/compile] Error 1
make[1]: Leaving directory '/scratch/union'
make: *** [/scratch/union/include/toplevel.mk:233: package/cpupower/compile] Error 2
```

It seems to be running up to line [45 in the Makefile](https://github.com/openwrt/packages/pull/22488/files#diff-5b3441cbc2b8de75aa278f2284de41691778f22317c61766a75b61b699278fcdR45) but something is then running `grep` to a non-existent file.

**Comment by graysky2** [comment]
@BKPepe @1715173329 @jefferyto - does anyone have some insights into why this is failing?
```
% i=cpupower
% make package/$i/{clean,compile} package/index V=s 
...
rm -f /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79/.built
touch /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79/.built_check
(cd /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79; 	make CC="x86_64-openwrt-linux-musl-gcc" CFLAGS="-march=znver3 -O3 -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79=cpupower-6.1.79 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LDFLAGS="-L/scratch/union/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/lib -L/scratch/union/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro" DESTDIR=fake install-tools)
make[3]: Entering directory '/scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79'
grep: ../../../Makefile: No such file or directory
grep: ../../../Makefile: No such file or directory
grep: ../../../Makefile: No such file or directory
grep: ../../../Makefile: No such file or directory
Makefile:98: ../../scripts/Makefile.arch: No such file or directory
make[3]: *** No rule to make target '../../scripts/Makefile.arch'.  Stop.
make[3]: Leaving directory '/scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79'
make[2]: *** [Makefile:58: /scratch/union/build_dir/target-x86_64_musl/linux-x86_64/cpupower-6.1.79/.built] Error 2
make[2]: Leaving directory '/scratch/union/feeds/packages/utils/cpupower'
time: package/feeds/packages/cpupower/compile#0.19#0.12#0.30
    ERROR: package/feeds/packages/cpupower failed to build.
make[1]: *** [package/Makefile:128: package/feeds/packages/cpupower/compile] Error 1
make[1]: Leaving directory '/scratch/union'
make: *** [/scratch/union/include/toplevel.mk:233: package/cpupower/compile] Error 2
```

It seems to be running up to line [45 in the Makefile](https://github.com/openwrt/packages/pull/22488/files#diff-5b3441cbc2b8de75aa278f2284de41691778f22317c61766a75b61b699278fcdR45) but something is then running `grep` to a non-existent file.

**Comment by 1715173329** [comment]
> It seems to be running up to line [45 in the Makefile](https://github.com/openwrt/packages/pull/22488/files#diff-5b3441cbc2b8de75aa278f2284de41691778f22317c61766a75b61b699278fcdR45) but something is then running `grep` to a non-existent file.

Yes, it's looking for kernel's integrated makefiles.
You need to fix up it to get rid of those stuffs or just create a new Makefile for it.

**Comment by graysky2** [comment]
@1715173329 - can you point me to an example package I can use as a model?

**Comment by graysky2** [comment]
This Makefile builds but when I go to test the compiled executable, I get:
```
# cpupower frequency-info                  
zsh: command not found: cpupower
```

**Comment by feckert** [comment]
@graysky2 I have now had a closer look at this.
It looks like the cross compiler is not used.
You have to patch the kernel make file in `<linux-source>/tools/power/cpupower/Makefile`. So it is using the CROSS compiler
```
--- a/tools/power/cpupower/Makefile
+++ b/tools/power/cpupower/Makefile
@@ -85,7 +85,7 @@ INSTALL_SCRIPT = ${INSTALL} -m 644
 # If you are running a cross compiler, you may want to set this
 # to something more interesting, like "arm-linux-".  If you want
 # to compile vs uClibc, that can be done here as well.
-CROSS = #/usr/i386-linux-uclibc/usr/bin/i386-uclibc-
+# CROSS = #/usr/i386-linux-uclibc/usr/bin/i386-uclibc-
 CC = $(CROSS)gcc
 LD = $(CROSS)gcc
 AR = $(CROSS)ar
```
And you also have to change the openwrt Makefile as follows, so it is using the CROSS compiler

```
--- a/utils/cpupower/Makefile
+++ b/utils/cpupower/Makefile
@@ -25,7 +25,7 @@ endef
 
 MAKE_FLAGS = \
             ARCH="$(LINUX_KARCH)" \
-            CROSS_COMPILE="$(TARGET_CROSS)" \
+            CROSS="$(TARGET_CROSS)" \
             CC="$(TARGET_CC)" \
             CFLAGS="$(TARGET_CFLAGS/ -fhonour-copts/) $(TARGET_CPPFLAGS)" \
             LDFLAGS="$(TARGET_LDFLAGS)"
```

Now it compiles but I get a link error:
`/home/feckert/workspace/openwrt/LDM-master-lgm/build/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/12.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld.bfd: ./utils/helpers/amd.o: relocation R_X86_64_32 against '.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE`

But maybe my analysis will help you. You'll have to see the rest. I have to do something different now.

**Comment by graysky2** [comment]
@feckert - thank you very much... I am afraid the linking error is beyond me. @neheb any ideas?

**Comment by neheb** [comment]
```
 msgfmt: No such file or directory
```
That's gettext/host

You're better off patching Makefile.am and getting rid of po in SUBDIRS.

**Comment by graysky2** [comment]
Any insights into why this is failing?  The `Makefile` is modeled after

**Pull request closed without merging**
