### PR TITLE
p910nd: Change start init sequence to 99

### PR DESCRIPTION
**Pull request by FrancYescO**
Delay startup of p910nd to give devices more time to enumerate
Fixes issue #4752

Tested on mir3g
Signed-off-by: Francesco M <francyesc0@hotmail.it>

### CODE REVIEW

**Comment by FrancYescO** [comment]
@diizzyy as you can see is just impossible for me to pass hte checks:
putting FrancYescO as commiter name will pass DCO but will fail travis as is not a full name, putting a full name DCO will ask me to put the nickname 💣

**Comment by yousong** [comment]
@FrancYescO Probably because the git commit was "From: FrancYescO <a@b>" which is different from in the signed-of-by line.

You may also want to enable `procd_set_param respawn` so that the daemon process have a chance to be brought up again automatically by procd

**Comment by yousong** [comment]
Please also bump PKG_RELEASE

**Comment by FrancYescO** [comment]
Should be okay now.

**Comment by diizzyy** [comment]
You're back on 3 commits instead of one ;-)

**Comment by diizzyy** [comment]
Please squash it too

**Comment by diizzyy** [comment]
Please fix the commit msg
```
git commit --amend 
git push --force
```
..and you're all set :-)

**Comment by FrancYescO** [comment]
it's okay?

**Comment by diizzyy** [comment]
Full name (requirement for commit), looks fine otherwise

**Comment by FrancYescO** [comment]
🍻?

**Comment by neheb** [comment]
ACK

ping @pkerling

**Comment by yousong** [comment]
Thank you.

**Pull request merged**
