### PR TITLE
Re-add djbdns, ucspi-tcp and daemontools

### PR DESCRIPTION
**Pull request by dermoth**
This is continuation of PR #4573 which was apparently closed implicitly on a rebase. You can either use this pr or close it and reopen the previous one.

Maintainer: Thomas Guyot-Sionnest <tguyot@gmail.com> (dermoth)
Compile tested: arm_cortex-a9_vfpv3 (OpenWRT 18.06.1-mvebu-cortexa9_gcc-7.3.0 SDK)
Run tested: OpenWRT 18.06.1-mvebu-cortexa9_gcc (WRT3200ACM), tested dnscache running from daemontools)

Description:

I'm upgrading my router from an older OpenWRT build, originally to Lede Reboot (17.01.2 r3435-65eec8bd5f) and now OpenWRT 18.06.1. My setup is tightly integrated with dnscache so I re-added djbdns and its dependencies to the packages stream so I could build/install them.

### CODE REVIEW

**Comment by diizzyy** [comment]
I don't see how adding more or less deprecated software is going to benefit anyone as we alerady have counterparts in the tree?

**Comment by dermoth** [comment]
I fixed some copyright notices, something I never did from the previous PR... we should close either one of them, I managed to reopen the old one (my mistake) - both are the same head commit, just different branch names.

As for your comment, I'm not sure what equivalent you have. I have to admit I haven't looked much but I want a simplistic *recursive* nameserver. I trust djbdns so I've come to use it in the past, and re-added the packages when I realized they were gone after a router upgrade.

I will maintain them for as long as I'm using OpenWRT and I have no plan to move away from them. If you don't merge them I'll just keep building them on my own though.

Regards

**Comment by diizzyy** [comment]
Dnsmasq falls into that category otherwise you also have unbound. While we all love certain tools it's also time to let go of things as they get outdated and/or more or less considered abandoned. 

See https://wiki.gentoo.org/wiki/Djbdns bottom for instance.
Debian went as far as forking their own version: https://packages.debian.org/sid/dbndns

DNS is one of the services you actually want up to date
Also, knot resolver (https://www.knot-resolver.cz/) might be of interest if you want to import something else that's active upstream.

If you want to continue using djbdns I'm not going to object but chances are slim to none given the current status of djbdns that it'll get merged in the end.

**Comment by dermoth** [comment]
Ok, got it. in any case i'll maintain djbdns until I have an alternate working solution.

Regarding Dnsmasq, I use it too, but it's only a forwarder - mine forwards to dnscache, also providing IPv6 support that is unfortunately lacking in djbdns... Having my own resolver cache is significantly faster than using external ones, even my ISP's. I also like to be in control of dns name resolution and I definitively don't trust my ISP to be running the latest security patches.

I remember very well the CVS mentioned at the bottom of the page, which iirc didn't came very long after other attacks vectors on all major DNS resolvers using weak port/id randomization (djbdns was already using strong random ports and id's so it wasn't affected). This one made the problem **much** worse by allowing to poison a cache using negative queries, so instead of having once try per TTL interval you could flood the cache until you got a match. It's a DNS design flaw rather than a software flaw, but the patch should probably be added. I'll look into it, update the PR if it's still open... whichever way you go as I said I'll keep maintaining my packages.

Regards

**Comment by diizzyy** [comment]
@thess @karlp @champtar @hnyman 
Please have a look at this

**Comment by dermoth** [comment]
Actually I mixed up CVE's - the one mentioned in the gentoo bug is imho pretty moot - the attacker must have had *legitimate control* of the zone, and then before the TTL for the SOA expires he can extend the zone't ttl for his expired NS entry provided of course he has a way to generate traffic from the target network **and** the cache doesn't get cleaned up (restart or eviction).

The other CVE's for dnscache are all patched in the current code imported from old feeds.

**Comment by diizzyy** [comment]
@dermoth 
I think you can close this due the upstream being dead and we already have alternatives that are active upstream in tree.

**Comment by diizzyy** [comment]
It's a no for me, opinions?
@neheb @thess @BKPepe @hnyman @BKPepe

**Comment by neheb** [comment]
This seems very niche to me.

**Comment by BKPepe** [comment]
I don't mind to have it in OpenWrt repository if it is being developed, maintained or at least being requested by users. We can not be sure, if there are no security issues and so on as the latest release is from 2008. Even I don't like doing it, I think we shouldn't merge this package. It's not personal or anything, but as it was mentioned there are others alternatives, which are developed.

**Comment by yousong** [comment]
> I don't mind to have it in OpenWrt repository if it is being developed, maintained or at least being requested by users. We can not be sure, if there are no security issues and so on as the latest release is from 2008. Even I don't like doing it, I think we shouldn't merge djbdns. It's not personal or anything, but as it was mentioned there are others alternatives, which are developed.

I'd like to note that being old or feature freeze is not actually a bad thing in these cases.  I only have experience with daemontools and I think it's finely designed, high quality, solid software I can depend on for a vendor-independent standalone deployment.  The other 2 projects are also from the same author, DJ Bernstein.  Of course I do not know him privately, but I think he is actually someone who can make good things and be proud of them.

That said, I think packages merged into OpenWrt repo should fit into the way OpenWrt works.  In this case, they should use procd to manage processes.

**Comment by diizzyy** [comment]
@yousong 
The issue is that since upstream is dead it's very hard to track vulns etc and I'm very sure you'll find some in ~10+y old software.

**Comment by yousong** [comment]
> The issue is that since upstream is dead it's very hard to track vulns etc and I'm very sure you'll find some in ~10+y old software.

The fact at the moment is that they are good for now and even though being feature freeze for all these years, there are still people wanting to use them.  That's something.

Against something good whose bad is yet to happen and even if happened can be fixed is something we should not do.  It kills possibility.

**Comment by diizzyy** [comment]
Erm no, upstream is dead so it's far from a voluntary feature freeze. You can find numerous of patches floating around but with no upstream repo they're scattered all over the place.

**Comment by yousong** [comment]
@diizzyy we can talk like this forever to no avail ;( or to death ;)

Enough points presented for my part, I'd like to propose that we allow packages be part of OpenWrt system as long as there are still users willing to use and take care of them.  More clauses can be added to that "as long as" condition to make it more tight, specific and impeccable, but you get the point

**Comment by yousong** [comment]
Close now for lack of response.

@dermoth , feel free to push updates and maybe email me back if I missed it.  Thank you.

**Comment by dermoth** [comment]
Sorry I should've replied earlier - I moved to unbound - I agree this was obsolete but before finding unbound I could find no interesting alternatives...

**Pull request closed without merging**
