### PR TITLE
strongswan: update to 5.5.1, preserve /etc/strongswan.d, take over maintainership

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: @sbyx 
Compile tested for octeon
Run tested on octeon running LEDE r1954

### CODE REVIEW

**Comment by thess** [comment]
Hi @stintel -

It seems that @sbyx has been MIA for a while now. If either you or @dedeckeh would like to take over as maintainer of this package and verify some of the open PRs for it, I will gladly help merge them.

**Comment by stintel** [comment]
@thess sure, but I don't have commit access on this repo. Where can I request this?

**Comment by stintel** [comment]
@sbyx OK for you if I take maintainership of strongswan?

**Comment by sbyx** [comment]
Sure. That's why I granted you access ;)

**Pull request merged**
