### PR TITLE
quassel-irssi: fix compilation error with new version of irssi

### PR DESCRIPTION
**Pull request by Ansuel**
Add patch fixing compilation error with new version of irssi where the renamed some functions.

Fixes: #22384

### CODE REVIEW

**Comment by BKPepe** [comment]
Hmm, shouldn't we rather remove this package? I checked opened issues in the upstream repository of quassel-irsi and found this one: https://github.com/phhusson/quassel-irssi/issues/36

**Comment by neheb** [comment]
Relevant: https://github.com/openwrt/packages/pull/7454

**Comment by Ansuel** [comment]
@BKPepe well ok for me to drop but wonder if we can find a single user that would still use this???

**Comment by BKPepe** [comment]
So, the conclusion is that if we find only one single user, who use this package then it is ok to have this package in our repositories? Hmm, I dont like it. Its dead in upatream. No features will be developed, its not maintained anymore. If someone is using it, then he/she can compile it locally or rather switch to different package. There is no point that we will be maintaining dead projects. We don't even have people for that.

**Pull request merged**
