### PR TITLE
minidlna: update to latest master

### PR DESCRIPTION
**Pull request by neheb**
Removed inactive maintainer.

Cleaned up Makefile to remove old options.

Switched to PKG_INSTALL for consistency.

Fixed license info.

Removed '' from enabled for consistency.

Ran init script through shellcheck. Batched config file writes.

Switched it to use procd. The -S parameter changes it to foreground. It
stands for systemd.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody
Compile tested: ath79, malta
Run tested: malta

### CODE REVIEW

**Comment by neheb** [comment]
This needs testing. Specifically the new procd init script.

The -S parameter may or may not break log_file functionality.

There are also these two issues:

https://github.com/openwrt/packages/issues/5463
https://github.com/openwrt/packages/issues/10357

That start parameter probably needs to be increased/

**Comment by craibuc** [comment]
@neheb #11004 did NOT fix issue #10357.

**Comment by neheb** [comment]
I suggest testing with strace. I have no idea why it crashes. Could be a GCC -Os bug for all I know.

**Comment by neheb** [comment]
Just tested this. Works fine.

The pictures are completely messed up, but that's probably because of libjpeg-turbo. The MIPS ASM in it is probably broken.

**Comment by neheb** [comment]
A small note: this change disables the log_dir functionality. It's all done in syslog now:

https://sourceforge.net/p/minidlna/git/ci/master/tree/minidlna.c#l1014

**Comment by neheb** [comment]
@diizzyy I noticed you added a patch from elsewhere as upstream seems not to actively merge patches. Should we merge more?

**Comment by neheb** [comment]
So the reason for the garbage quality images is that minidlna defaults to 160 width and height...

Gerbera does not do this. Should this be patched?

**Comment by diizzyy** [comment]
Merge more? As for the patches, pretty sure they're needed for backwards compatibility regarding the database but I haven't looked closely at it. At the time minidlna seemed dead upstrea but on the other hand it's only a handful of commits ahead so they'll probably still apply.

**Comment by neheb** [comment]
I meant this https://github.com/xavery/minidlna/

There are some useful commits there, such as

https://github.com/xavery/minidlna/commit/eb473817d73b8740f27955f93950029fdfc9d73e
https://github.com/xavery/minidlna/commit/972fb2bbfdb7118551da45c5828c9e74be581fc4
https://github.com/xavery/minidlna/commit/aae49f0f80e73d1b52f23b89b0d314e9b9f89425

**Comment by neheb** [comment]
I've decided to give up on this. I'll merge my fixes as they are.

The crashing on file addition was something I managed to do once and never again. This needs debugging with gdb. This requires unstripped binaries and gdb. I can offer such a thing but I can't really debug it on my end.

This project also seems to be a dead end. It seems many of the users are coming from the Turris environment where size is not an issue(for that reason I wonder why the Turris people decided to use OpenWrt but that's neither here nor there).

Gerbera seems to be a better alternative to miniDLNA. It's also actively developed. I use it on my NAS. It works well. It should be introduced here. Maybe @ryzhovau or the entware team can do so.

**Comment by ryzhovau** [comment]
@neheb, @diizzyy, thanks for your work anyway, `minidlna` crashing on some (broken?) files was always been a pain for part of users. Looks like it's a mature project indeed and no any changes expected here, so leave it as is.

`gerbera` was a quite fragile when it was forked from `mediatomb` and requires to wipe out database if stopped unexpected, it won't start again otherwise. I don't know how it's handled for now.

**Pull request merged**
