### PR TITLE
Added package nut-web-cgi

### PR DESCRIPTION
**Pull request by demorfi**

### CODE REVIEW

**Comment by champtar** [comment]
hi @demorfi,
please read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md,
you at least need to sign off your commit

**Comment by sbyx** [comment]
@demorfi in addition to what champtar mentioned, you have an awful lot of unrelated whitespace issues.

**Comment by demorfi** [comment]
hi

@champtar 
Added only option --with-cgi application is compiled as an additional package.
This not add package separate from the package nut. Explain in detail the problem.

@sbyx 
It did Geany automatically when you save. Why use empty tabs?

**Comment by cyanidium** [comment]
I'm looking at another nut update for collectd at the moment, I'll look at this one too.

**Pull request closed without merging**
