### PR TITLE
owipcalc: separate in client and lib

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Separate owipcalc in client and lib part. Owipcalc brings a lot of nice functionality with it, e.g. parsing and calculating prefixes.

Maintainer: @jow- 
Compile tested: Trunk
Run tested: TP-Link TL-WDR4300 v1 (Trunk)

Moved from: https://github.com/openwrt/openwrt/pull/3804

### CODE REVIEW

**Comment by adschm** [comment]
Maintainer is "jow-", not "jow" ...

**Comment by PolynomialDivision** [comment]
Anything new on this?

**Comment by neheb** [comment]
I think you can merge.

**Comment by PolynomialDivision** [comment]
> I think you can merge.

I runtested again on WDR4300 and everything works. I will merge. :)

**Comment by adschm** [comment]
@PolynomialDivision If you have access here anyway, maybe consider to take over maintainership for this package.

Note: I'm kind of a stranger to packages repo, so maybe this is a stupid suggestion. If you consider it, maybe just discuss with @neheb and @jow- ...

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision If you have access here anyway, maybe consider to take over maintainership for this package.

If @jow- is fine, I could take care of maintainership.

**Pull request merged**
