### PR TITLE
[openwrt-22.03] v2rayA: Update to 1.5.7

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: me
Compile tested: mediatek/mt7622
Run tested: rdmi ax6s

Description:
- Backported from #18351

### CODE REVIEW

**Comment by 1715173329** [comment]
Looks like the docker image of openwrt rootfs is still outdated.

**Comment by 1715173329** [comment]
Well is it possible to merge this firstly? The test container is still outdated...

**Comment by jefferyto** [comment]
I think this is okay to merge.

**Comment by 1715173329** [comment]
Thanks so much!

**Pull request merged**
