### PR TITLE
AriaNg: Update to 1.3.7

### PR DESCRIPTION
**Pull request by laipeng668**
Maintainer: @Ansuel (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:
https://github.com/mayswind/AriaNg/releases

AriaNg 1.3.7 Change Log

1. Each task list page supports independent display order
2. Rpc dropdown list on larger screen would be shown larger
3. Other bug fix and user interface optimization

This version works well on my aarch64_generic platform router.
This upgrade has not changed much, the file names and quantities have not changed.
Snipaste_2024-10-25_06-33-10

### CODE REVIEW

**Comment by 1715173329** [comment]
> Author name (Roc.Lai) need to be your real name 'firstname lastname'

s/./ /

**Comment by laipeng668** [comment]
> > Author name (Roc.Lai) need to be your real name 'firstname lastname'
> 
> s/./ /

I've changed my name to Roc Lai. Is that corret?

**Comment by 1715173329** [comment]
> I've changed my name to Roc Lai. Is that corret?

Yes.

**Comment by 1715173329** [comment]
Cc maintainer @Ansuel

**Comment by laipeng668** [comment]
> Cc maintainer @Ansuel

all set

**Comment by 1715173329** [comment]
I guess you forget to push updates ;)

**Comment by laipeng668** [comment]
> I guess you forget to push updates ;)

I created it on the webpage. I can't find the "push updates" button. Let me restart a new one.

**Comment by laipeng668** [comment]
https://github.com/openwrt/packages/pull/25201

**Pull request closed without merging**
