### PR TITLE
opencv: remove

### PR DESCRIPTION
**Pull request by neheb**
This package is unmaintained. It also seems to be unused.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody

### CODE REVIEW

**Comment by neheb** [comment]
@flyn-org gst-plugins-bad has an option to use this. What do you think?

**Comment by diizzyy** [comment]
Drop it

**Comment by neheb** [comment]
Removing.

**Comment by kofec** [comment]
WARNING: Makefile 'package/feeds/telephony/freeswitch-stable/Makefile' has a dependency on 'opencv', which does not exist

**Comment by neheb** [comment]
That must be fixed in the telephony repository. The opencv module for freeswitch is marked as BROKEN anyway.

**Comment by hnyman** [comment]
Fixed in https://github.com/openwrt/telephony/pull/511

Note that having it marked BROKEN does not yet eliminate the dependency check in the config process. As there was still one package "using" opencv in the telephony feed, this removal here triggered the warning in the config process.

**Pull request merged**
