### PR TITLE
conserver: remove deprecated usleep

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @bmork 
Compile tested: ath79

### CODE REVIEW

**Comment by bmork** [comment]
Has this been submitted upstream?  Upstream is quite responsive.  I do not understand why this should be a distro specific patch.  We definitely do not want to keep it around forever.  So either it is accepted upstream or it is dropped.  And there is nothing here requiring immediate action, so this can wait for the next upstream relase.

**Comment by neheb** [comment]
https://github.com/bstansell/conserver/pull/52

Upstream seems dead from what I see.

**Comment by bmork** [comment]
Thanks.  Upstream tends to do batch processing, which is fine. And the release frequency matches the number of changes.  So you may have to wait for a while before a submisison is processed and pushed out.  I really do not see that as a problem wrt this pacth, which AFAIU does not solve any real issue for anyone.

**Comment by neheb** [comment]
Seems like this was merged. This fixes compilation with a non-default configuration of uClibc-ng.

**Pull request closed without merging**
