### PR TITLE
Openwrt 18.06

### PR DESCRIPTION
**Pull request by rajeshdhoot**
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by pprindeville** [comment]
Please cherry-pick PR #7270 (b0e7363).

**Comment by champtar** [comment]
@pprindeville easiest thing to do is to open a PR ;)
I'll add CircleCI to 18.06 branch soon

**Comment by champtar** [comment]
@pprindeville config added

**Comment by pprindeville** [comment]
Fixed with cherry-pick.

**Pull request closed without merging**
