### PR TITLE
keepalived: use old keepalived.conf by default

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: N/A
Run tested: N/A

Description:
Fixes https://github.com/openwrt/packages/issues/3756
Reported by @stintel

When merging, please merge before merging https://github.com/openwrt/packages/issues/3756
I did not increase the PKG_RELEASE on this PR.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by stintel** [comment]
Can you rewrite the subject so that it's not line-wrapped by github?

**Comment by commodo** [comment]
sure

**Comment by commodo** [comment]
done ;

**Comment by stintel** [comment]
Thanks!

**Comment by commodo** [comment]
question ; any idea if i needed to bump the PKG_RELEASE on this ?
or will the build system pick this up in time [from prev PR https://github.com/openwrt/packages/pull/3758 ] ?

**Comment by stintel** [comment]
I don't think it matters much, if the user already had keepalived with UCI support installed, he already ran in the problem and likely fixed it already. Updating then would not overwrite /etc/config/keepalived anyway.

**Pull request merged**
