### PR TITLE
Linuxptp: add mirror hash and fix build

### PR DESCRIPTION
**Pull request by hauke**
Maintainer: @wodu
Compile tested: lantiq, lede master
Run tested: no

linuxptp: add mirror sha256sum
    
This makes LEDE download it from the mirror instead of cloning it every time.
------------------------------------------------------------
linuxptp: fix libc functionality check in incdefs.sh
    
The checks in the incdefs.sh script do not fully work when cross
compiling. It probably checks the hosts libc. Just provide the settings
manually, as our musl at least supports all these features.

### CODE REVIEW

**Comment by hauke** [comment]
I fixed it now

**Comment by diizzyy** [comment]
Why are we even pulling it off git when there's a tarball?
Also, please switch it to xz instead of bz2 if you intent to keep git download.

**Comment by diizzyy** [comment]
@hnyman 
Merge?

**Comment by hnyman** [comment]
> @hnyman
> Merge?

The PR has been opened by another committer ( @hauke  ), and I usually leave the PRs from other committers to their own care.

**Pull request merged**
