### PR TITLE
procps-ng: add terminfo dependency

### PR DESCRIPTION
**Pull request by kissg1988**
Fixes build error caused by [1d8015afd269100702feb083dcad57e7bd632390](https://git.openwrt.org/?p=openwrt.git;a=commit;h=1d8015afd269100702feb083dcad57e7bd632390).

### CODE REVIEW

**Comment by jow-** [comment]
This change seems bogus. The terminfo package just provides a bunch of terminal description files, how would it fix the compilation?

**Comment by kissg1988** [comment]
Without this fix, the build fails with the error:
```
  CC       slabtop.o
  CCLD     slabtop
/home/nb/openwrt-build/openwrt-trunk/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/lib/gcc/mips-openwrt-linux-musl/5.3.0/../../../../mips-openwrt-linux-musl/bin/ld: slabtop.o: undefined reference to symbol 'stdscr'
/home/nb/openwrt-build/openwrt-trunk/staging_dir/target-mips_34kc_musl-1.1.14/usr/lib/libtinfow.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
With the additional LDFLAG and dependency added, the build completes successfully.

Shall I fix this some other way?

**Comment by jow-** [comment]
I overlooked the TARGET_LDFLAGS change. I think this is alone is enough, no need for the additional dependency.

**Comment by kissg1988** [comment]
Agreed, terminfo is a dependency of libncruses, no need to depend on it explicitly. Change commited and added to PR.

**Comment by nbd168** [comment]
The ncurses tinfo library split was reverted in LEDE and OpenWrt and replaced with a less intrusive fix. This change is no longer necessary.

**Pull request closed without merging**
