### PR TITLE
nfdump: fix compilation with PKG_ASLR

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @flyn-org 
Compile tested: ath79

### CODE REVIEW

**Comment by flyn-org** [comment]
Looks fine. I will try to address this with upstream when I have time.

**Comment by neheb** [comment]
The actual issue is that OpenWrt CFLAGS are not being passed because of this line. This is also a bugfix in disguise.

**Comment by flyn-org** [comment]
Yes, let's merge.

**Comment by flyn-org** [comment]
See https://github.com/phaag/nfdump/issues/304.

**Pull request merged**
