### PR TITLE
build,travis: limit git depth to 1 level

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @lynxis 
Compile tested: N/A
Run tested: N/A

------------------------------------------------------

It's just a minor optimization of the build.
No need to clone up to 50 revisions back (travis default)

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by lynxis** [comment]
looks good. thanks.
(sorry, I can't merged it)

**Comment by champtar** [comment]
@commodo is it 1 commit before the PR, or 1 commit?
There are some commands on ```$TRAVIS_COMMIT_RANGE```, can you confirm that it will not break that ?

**Comment by lynxis** [comment]
@champtar I thought the same, take a look here https://github.com/lynxis/packages/pull/7

**Comment by champtar** [comment]
```No new or modified packages found!``` in the second travis run
so we need depth > nb commit in the PR I think

**Comment by lynxis** [comment]
@champtar I think that's correct. my PR got:

- this commit
- libmicrohttpd downgrade
- libmicrohttpd revert downgrade

It's correct, that nothing changes except the .travis. between upstream and the PR. I'll do another test.

- this commit
- libmicrohttpd downgrade
- some README changes

it should then test libmicrohttpd.

**Comment by lynxis** [comment]
@champtar still looks good. https://github.com/lynxis/packages/pull/7 it noticed the libmicrohttpd changes.

**Comment by champtar** [comment]
Thanks @lynxis

**Comment by champtar** [comment]
BTW, it works because there is
```
git fetch origin +refs/pull/<pullreqnumber>/merge
git checkout -qf FETCH_HEAD
```

**Comment by commodo** [comment]
@champtar @lynxis 
thanks for handling this
i am just coming back from the weekend

**Pull request merged**
