### PR TITLE
dnstap: add new package

### PR DESCRIPTION
**Pull request by ja-pa**
Maintainer: me
Compile tested: Turris Omnia (TOS5), OpenWrt master
Run tested: Turris Omnia (TOS5), OpenWrt master

Description:
This PR adds dnstap utility. The dnstap command-line tool can read, write, and decode dnstap data from a running name server or a previously-saved file. (see https://dnstap.info/Examples/)

Related to https://github.com/openwrt/packages/pull/13298

### CODE REVIEW

**Comment by aparcar** [comment]
Please rebase to let the CI build it

**Comment by ja-pa** [comment]
Rebased

**Review by jefferyto — APPROVED** [review]
LGTM - thanks!

**Comment by jefferyto** [comment]
The new CI tests passed but no *.ipk artifacts were saved... @aparcar perhaps you can take a look?

**Comment by aparcar** [comment]
Please one more rebase, CI should be fixed in the current master branch.

**Comment by jefferyto** [comment]
Oops, apologies for the noise - I wasn't aware it was already fixed.

**Comment by ja-pa** [comment]
Rebased

**Pull request merged**
