### PR TITLE
shadowsocks-libev: configure bypass/forward by domain names

### PR DESCRIPTION
**Pull request by amezin**
Maintainer: @yousong 
Compile tested: ipq806x (nbg6817), OpenWrt git master
Run tested: ipq806x (nbg6817), OpenWrt git master

Description:

- Add `dst_domains_bypass` and `dst_domains_forward` to `ss_rules` config section.

- Generate a configuration file for dnsmasq in `/var/dnsmasq.d/` when `/etc/init.d/shadowsocks-libev` starts.

Dnsmasq will add resolved IPs for domains from `dst_domains_bypass` and `dst_domains_forward` lists to `ss_rules[6]_dst_{forward,bypass}` ipsets.

Inspired by vpn-policy-routing (@stangri ).

Corresponding changes for luci app are pending.

Some edge cases:

- dnsmasq-full is required for this to work (ipsets support is disabled in other variants). There is no check for ipset support of the running dnsmasq yet.

- When `/etc/init.d/shadowsocks-libev` reloads, it clears ipsets. dnsmasq won't add resolved addresses back until it receives a DNS request for them again (and browsers will cache DNS resolution results, Shift+Reload is required on firefox)

### CODE REVIEW

**Comment by yousong** [comment]
I prefer not doing this in ss-rules.  Dnsmasq already supports uci option `ipset` for this and as said in the ss-rules docs, those ipset names are expected to be stable to be used by external programs.

> ss-rules uses kernel ipset mechanism for storing addresses/networks. Those ipsets are also part of the API and can be populated by other programs, e.g. dnsmasq with builtin ipset support. For more details please read output of ss-rules --help

In case it may also interest others, I also have a smalls script for configuring dnsmasq to use specified dns/ipset for set of domains: https://github.com/yousong/gists/blob/master/openwrt/dns-ipset/README.md

**Comment by amezin** [comment]
I need this PR because I want a UI in Luci where I can configure what domains to forward and/or what domains to pass through.
Maybe I can achieve the same thing by extending luci UI for dnsmasq (UI for configuring ipsets). But right now I'm not sure how it should look like. Also for that the user will need to know ipset names, which aren't visible anywhere in Luci right now.

**Comment by yousong** [comment]
> I need this PR because I want a UI in Luci where I can configure what domains to forward and/or what domains to pass through.
> 
> Maybe I can achieve the same thing by extending luci UI for dnsmasq (UI for configuring ipsets). But right now I'm not sure how it should look like. Also for that the user will need to know ipset names, which aren't visible anywhere in Luci right now.

These are all about ui, be it cui or gui.  It's dnsmasq or other specific resolvers' configuration that are not in the realm of shadowsocks-libev.  Fiddling other programs's data and status this way can be fragile.  We can have all kinds of quick scripting for our own convenience at hand, but I am afraid it's bad practice to wringle dnsmasq and shadowsocks-libev together this way.

> 
> > I prefer not doing this in ss-rules.
> 
> BTW, I ended up adding the code to `net/shadowsocks-libev/files/shadowsocks-libev.init`, not `ss-rules` itself.

True.  My concern is that shadowsocks-libev should not be tasked with writting dnsmasq config file.

**Comment by amezin** [comment]
Do you have any idea how Luci GUI for bypass/forward by domain could be implemented without messing with dnsmasq config from shadowsocks-libev (i. e. a solution that looks acceptable to you)?

**Comment by yousong** [comment]
> Do you have any idea how Luci GUI for bypass/forward by domain could be implemented without messing with dnsmasq config from shadowsocks-libev (i. e. a solution that looks acceptable to you)?

LuCI's dnsmasq integration should support editing `ipset` uci option list, with existing  
 ipsets of suitable types listed as choices.  At luci-app-shadowsocks-libev where those ip lists are configured, we can explain a bit about how it works and refer to the dnsmasq ipset editing page.

**Pull request closed without merging**
