### PR TITLE
treewide: run "make check FIXUP=1"

### PR DESCRIPTION
**Pull request by champtar**
replace MD5SUM with HASH, add PKG_MIRROR_HASH

@openwrt/package-maintainers is it ok with everyone ?

### CODE REVIEW

**Comment by champtar** [comment]
(I've canceled the build)

**Comment by jslachta** [comment]
@champtar ACK

**Comment by karlp** [comment]
Can someone document what PKG_MIRROR_HASH is meant to be for?  It's not on https://wiki.openwrt.org/doc/devel/packages and nothing in https://lede-project.org/docs/guide-developer/start has package documentation.

**Comment by thess** [comment]
ACK from me.

As part of any doc effort, please add a note about svn lossage using PKG_MIRROR_HASH and what to do about it. I'm not sure about my last workaround - manually staging the mirror copy.

**Comment by hnyman** [comment]
Looks like a good cleanup operation ;-)

I think that it would be better to merge it rather quickly, before you run into more conflicts (in addition of the current three conflicts) and before other new PRs run into conflict of these changes...

**Comment by champtar** [comment]
Ok, I will rebase and merge tonight

**Comment by champtar** [comment]
commited as https://github.com/openwrt/packages/commit/4006865ae81b20b1793ae2a07db20235fefd2c71
I haven't added PKG_MIRROR_HASH when PKG_SOURCE_PROTO:=svn

**Comment by karlp** [comment]
I see the documentation hasn't been updated by anyone yet to explain the purpose of this field, so I guess you're excited about doing this again in the future?  _I_ still don't even know what PKG_MIRROR_HASH is for.

**Comment by stintel** [comment]
PKG_MIRROR_HASH is like PKG_HASH but for snapshots taken from git, for example. A tarball is automatically created for those snapshots. E.g. for [odhcpd: odhcpd-2017-08-16-94e65ee0.tar.xz](https://git.lede-project.org/?p=source.git;a=blob;f=package/network/services/odhcpd/Makefile;h=9c59fb648a43f969a69a755dc7505c5b5e05c322;hb=HEAD#l17) is automatically mirrored, and PKG_MIRROR_HASH contains its checksum.

```
stijn@taz ~/Development/LEDE/source $ sha256sum dl/odhcpd-2017-08-16-94e65ee0.tar.xz
cb3d1e42f87bfd1eb78e27ae6a59e34302db11a6e6c119962c1c02b2f51ddaef  dl/odhcpd-2017-08-16-94e65ee0.tar.xz
```

**Comment by zorun** [comment]
@karlp unfortunately, documentation is a weak point for OpenWrt/LEDE, and the wiki format does not really help.

Here is an attempt at documenting this, please proof-read: https://wiki.openwrt.org/doc/devel/packages#buildpackage_variables and https://wiki.openwrt.org/doc/devel/packages#use_source_repository

Fun fact: I thought this `PKG_MIRROR_HASH` was brand new, but in fact it dates back from 2011!

**Comment by karlp** [comment]
@zorun looks good to me, and I think I now finally understand it's purpose :)
@zorun do you have any suggestion _other_ than the wiki?  I find the wiki to be superb for it, given that it lets more people edit.  The core problem I've found is that no-one outside a core group actually _knows_ how something works, and it can't be documented until that happens.

**Pull request closed without merging**
