### PR TITLE
AriaNg: Update to 1.3.7

### PR DESCRIPTION
**Pull request by laipeng668**
Maintainer: @Ansuel (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:
https://github.com/mayswind/AriaNg/releases

AriaNg 1.3.7 Change Log

1. Each task list page supports independent display order
2. Rpc dropdown list on larger screen would be shown larger
3. Other bug fix and user interface optimization

This version works well on my aarch64_generic platform router.
This upgrade has not changed much, the file names and quantities have not changed.

379956614-84603ba7-4df7-467f-b78c-9221dd067fdf

### CODE REVIEW

**Comment by 1715173329** [comment]
Please do rebase if you *really* want to keep your commit up-to-date, not add merge commit.

**Comment by laipeng668** [comment]
> Please do rebase if you _really_ want to keep your commit up-to-date, not add merge commit.

Get it. I'm so sorry. I'm a newbie.
What shoud I do now? or just don't do anything?

**Comment by Ansuel** [comment]
@laipeng668 assuming you used git and not github webui 

You need to add a commit description
Drop the merge commit do do this

git rebase -i HEAD~2

A text edito opens... read the legend

would should change the view to
reword HASH
drop HASH

To edit the first commit and add a commit description and drop the merge commit.

on saving and closing the text editor, a new text editor should open with the commit to edit... Save and close to finish editing your commit.


After that you can just rebase your commit on the packages master.
i usually use
git remote add upstream https://github.com/openwrt
git fetch upstream
git rebase upstream/master

And then you can force push 
git push -f

**Comment by laipeng668** [comment]
> @laipeng668 assuming you used git and not github webui
> 
> You need to add a commit description Drop the merge commit do do this
> 
> ```
> git rebase -i HEAD~2
> ```
> 
> A text edito opens... read the legend
> 
> ```
> would should change the view to
> reword HASH
> drop HASH
> ```
> 
> To edit the first commit and add a commit description and drop the merge commit.
> 
> on saving and closing the text editor, a new text editor should open with the commit to edit... Save and close to finish editing your commit.
> 
> After that you can just rebase your commit on the packages master. i usually use
> 
> ```
> git remote add upstream https://github.com/openwrt
> git fetch upstream
> git rebase upstream/master
> ```
> 
> And then you can force push
> 
> ```
> git push -f
> ```

Thank you so much! I will try it later.

**Comment by laipeng668** [comment]
> @laipeng668 assuming you used git and not github webui
> 
> You need to add a commit description Drop the merge commit do do this
> 
> ```
> git rebase -i HEAD~2
> ```
> 
> A text edito opens... read the legend
> 
> ```
> would should change the view to
> reword HASH
> drop HASH
> ```
> 
> To edit the first commit and add a commit description and drop the merge commit.
> 
> on saving and closing the text editor, a new text editor should open with the commit to edit... Save and close to finish editing your commit.
> 
> After that you can just rebase your commit on the packages master. i usually use
> 
> ```
> git remote add upstream https://github.com/openwrt
> git fetch upstream
> git rebase upstream/master
> ```
> 
> And then you can force push
> 
> ```
> git push -f
> ```

By following your instrucions, it seems to be ok right now. Thx again!

**Comment by Ansuel** [comment]
@laipeng668 Hi very good. Only one missing thing. You are missing a commit description.

After the commit title you must add a description of the commit.

The format is the following

```
TITLE

DESCRIPTION

Signed-off-by:...
```

Please add a description, even if it's a repetition of the title :D 

Also maybe I would change AriaNg to ariang:

**Comment by laipeng668** [comment]
> @laipeng668 Hi very good. Only one missing thing. You are missing a commit description.
> 
> After the commit title you must add a description of the commit.
> 
> The format is the following
> 
> ```
> TITLE
> 
> DESCRIPTION
> 
> Signed-off-by:...
> ```
> 
> Please add a description, even if it's a repetition of the title :D
> 
> Also maybe I would change AriaNg to ariang:

I have just added a commit description and changed AriaNg to ariang. Thank you for your help. That is very kind of you!
Snipaste_2024-10-27_10-52-05

**Comment by Ansuel** [comment]
@laipeng668 if in the future happens to send other commit please check here for the right format for a good commit title and description

**Pull request merged**
