### PR TITLE
miredo: add miredo.conf conffile

### PR DESCRIPTION
**Pull request by ValdikSS**
Keep miredo.conf modified configuration upon upgrades

Signed-off-by: ValdikSS ValdikSS <iam@valdikss.org.ru>

Maintainer: @neheb

### CODE REVIEW

**Comment by neheb** [comment]
Need a PKG_RELEASE bump.

**Comment by ValdikSS** [comment]
> Need a PKG_RELEASE bump.

Done.

**Comment by hnyman** [comment]
This should first go into the development master, not into the stable release branch 22.03

**Comment by ValdikSS** [comment]
@hnyman 
> This should first go into the development master, not into the stable release branch 22.03

Done.

**Comment by ValdikSS** [comment]
@hnyman sorry, unrelated question: I have several pull requests, all of them are for 22.03. Should I change them all to master?

**Comment by BKPepe** [comment]
You might keep them and create pull request to the master first or you can switch them and then ask for cherry-picking it.

**Comment by ValdikSS** [comment]
> You might keep them and create pull request to the master first or you can switch them and then ask for cherry-picking it.

Please cherry-pick it to 22.03. Should I do that with another pull request or somebody will do that themselves?

**Comment by hnyman** [comment]
cherry-picked ;-)

**Pull request merged**
