### PR TITLE
zabbix: fix minor typos in comments

### PR DESCRIPTION
**Pull request by richlv**

### CODE REVIEW

**Comment by champtar** [comment]
hi @richlv,
even if it's minor fix,
please follow https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md,
ie start your commit with "zabbix:" and sign-off-by

**Comment by sbyx** [comment]
I guess we should close this in a week or so if there is no reaction.

**Comment by richlv** [comment]
sorry, too many things happening at the same time...
but https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork says "no pseudonyms", so i'll probably allow somebody else to fix the typos this time :)

**Comment by sbyx** [comment]
oh well closing this then.

**Pull request closed without merging**
