### PR TITLE
lang/python/README.md: add note about use in other packages feeds

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @jefferyto 
Compile tested: N/A
Run tested: N/A

---------------------------------------------

By popular demand, via:
   https://github.com/openwrt/packages/issues/8892#issuecomment-489992926

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by pmelange** [comment]
@commodo @jefferyto 

I have recently come across the following code snippet in https://github.com/freifunk-berlin/firmware-packages/pull/188/commits/35d3d700637746d9121a004ad29dbac276a53dd3 which I find quite interesting.  It allows the name of the feed to be anything.  Perhaps something similar could be used for external python feeds.

```
LUCIMKFILE:=$(wildcard $(TOPDIR)/feeds/*/luci.mk)

# verify that there is only one single file returned
ifneq (1,$(words $(LUCIMKFILE)))
ifeq (0,$(words $(LUCIMKFILE)))
$(error did not find luci.mk in any feed)
else
$(error found multiple luci.mk files in the feeds)
endif
else
#$(info found luci.mk at $(LUCIMKFILE))
endif

include $(LUCIMKFILE)
```

In this case, it is for LuCI.  But such functionality could be used by python or even better added as a function to $(TOPDIR)/rules.mk to pull in any mk-file.

**Comment by commodo** [comment]
hmm ; it could work
i'll take a look

thanks
alex

**Comment by jefferyto** [comment]
@pmelange If you can't assume the feed is called `packages`, why can you assume `luci.mk` or whatever makefile you are looking for is the actual makefile you are looking for?

**Comment by commodo** [comment]
the idea in itself is ok;
because we would recommend `PYTHON_PACKAGE:=$(wildcard $(TOPDIR)/feeds/*/python-package.mk)`

people should know the name of `python-package.mk` at least;

ideally, people wanting to use `python-package.mk` should also know where to get it from, since they are setting up their own package feeds locally ;

the best I can think (here) to do is to document this option now;

we can probably propose (later) a new function in OpenWrt core; something like: 
```
define include_feeds_mk
__FEED_MKFILE:=$(wildcard  $(TOPDIR)/feeds/$(1))

# verify that there is only one single file returned
ifneq (1,$(words $(__FEED_MKFILE)))
ifeq (0,$(words $(__FEED_MKFILE)))
$(error did not find luci.mk in any feed)
else
$(error found multiple luci.mk files in the feeds)
endif
else
#$(info found luci.mk at $(__FEED_MKFILE))
endif
endef
```

and then do either:
`$(call  include_feeds_mk, */python-package.mk)`
or
`$(call include_feeds_mk,packages/lang/python/python-package.mk)`

the only benefit of `include_feeds_mk` over simple `include $(TOPDIR)/feeds/*/python-package.mk` is the verification that there are no more than 1 mk files

i can see the overall benefit of doing `include_feeds_mk`, but i also feel it's tailored to handle the corner-case of having `python-package.mk` in other feeds

**Comment by jefferyto** [comment]
Including a function like `include_feeds_mk` can make this corner case easier, but I don't see a way to guarantee the right file is found (unless there is a cryptographic signature to verify or something like that). There is nothing that stops another feed from having a different file named `python-package.mk` (and in the same location).

I think the safer option is to insist the packages feed is called "packages" or "bad things will happen" :joy:

**Comment by pmelange** [comment]
> and then do either:
> `$(call include_feeds_mk, */python-package.mk)`
> or
> `$(call include_feeds_mk,packages/lang/python/python-package.mk)`

I guess that in the case of python-package.mk the call would be ```$(call include_feeds_mk,lang/python/python-package.mk)``` since the wildcard globs the different feed names.  This would change the routine to 

```
define include_feeds_mk
__FEED_MKFILE:=$(wildcard  $(TOPDIR)/feeds/*/$(1))

# verify that there is only one single file returned
ifneq (1,$(words $(__FEED_MKFILE)))
ifeq (0,$(words $(__FEED_MKFILE)))
$(error did not find $(1) in any feed)
else
$(error found multiple $(1) files in the feeds)
endif
else
#$(info found $(1) at $(__FEED_MKFILE))
endif
endef
```

> I think the safer option is to insist the packages feed is called "packages" or "bad things will happen"

True, I just thought I would post this mostly as "food for thought".  Maybe something will come of it, maybe not.

**Comment by commodo** [comment]
So, the only convergence point here, is that we can document this (in lang/python/README.md) as an option for others that might like this flexibility.

**Comment by jefferyto** [comment]
I'm fine with adding this to the readme.

**Pull request merged**
