### PR TITLE
collectd: remove the patch scaling ping_droprate from 0-1 to 0-100

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: @jow- @hnyman 
Compile tested: n/a
Run tested: n/a

Description:

Upstream project's behaviour of reporting this data source in range 0-1
is used by at least CentOS 7 collectd 5.8.1, very likely the same
behaviour is also in widely use by other distributions.

The change is important for providing consistent experience across
collectd deployments on different environments

Ref: https://github.com/collectd/collectd/pull/3244
Signed-off-by: Yousong Zhou <yszhou4tech@gmail.com>

### CODE REVIEW

**Comment by yousong** [comment]
v2 <- v1 Prepend a commit to let procd log stderr output

**Comment by feckert** [comment]
LGTM

**Comment by hnyman** [comment]
LuCI may require modifications, as the droprate graph does not make sense otherwise. Or at least it did not make sense with the collectd version 4.10.8 at the time when I authored the patch in 2012.

https://git.openwrt.org/?p=openwrt/svn-archive/packages.git;a=commit;h=e4f3fd213b4460f298ab46f9eec1c63bc9fbcaac

**Comment by yousong** [comment]
Thanks for the heads-up.

I opened a pull request to again scale up the metric values to range 0-100.  I am going to test how it will look like in the weekend.

One thing I am not sure is whether types.db also needs to be patched.

**Comment by yousong** [comment]
v3 <- v2

 - Insert to commit to use uname for fetching default Hostname
 - Bump PKG_RELEASE only once at the end.

**Comment by yousong** [comment]
Thank you for the comments!

**Pull request merged**
