### PR TITLE
【23.05】 apfree-wifidog: update to 7.08.2035

### PR DESCRIPTION
**Pull request by liudf0716**
Maintainer: @liudf0716
Compile tested: x86_64
Run tested: x86_64

Description:
   
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.08.2035

Dengfeng Liu <liudf0716@gmail.com>

### CODE REVIEW

**Comment by 1715173329** [comment]
Please use `git cherry-pick -x` to backport commits from master branch.

**Comment by liudf0716** [comment]
> Please use `git cherry-pick -x` to backport commits from master branch.

sorry forget it.

**Comment by stangri** [comment]
> Please use `git cherry-pick -x` to backport commits from master branch.

Would it not fail due to the snapshots using different archive, hence different hash? Has that been fixed?

**Comment by 1715173329** [comment]
> Would it not fail due to the snapshots using different archive, hence different hash? Has that been fixed?

Well there's nothing to "fix".
Anyway this package uses codeload instead of local git tarball, so it's not affected.

**Pull request merged**
