### PR TITLE
ariang: install its nginx server part in the /etc/nginx/conf.d directory [RFC]

### PR DESCRIPTION
**Pull request by peter-stadler**
Maintainer: Ansuel Smith <ansuelsmth@gmail.com>
Compile tested: MIPS 74K, Asus RT-N16, master snapshot
Run tested: MIPS 74K, Asus RT-N16, master snapshot, open http://ariang.lan/ariang/ in browser

Description: 
In dhcp create the domain ariang.lan that points to the ip of the router. Use the /etc/nginx/conf.d directory to install the server part of ariang-nginx (this is based on my other [PR for nginx](https://github.com/openwrt/packages/pull/9859)). The app will be available at http://ariang.lan/ariang/. Should we better use https with a self-signed certificate?

**Edit:** I did update this PR to follow the changes in the meantime.

### CODE REVIEW

**Comment by peter-stadler** [comment]
Following the commits for nginx.

**Comment by Ansuel** [comment]
Why the dhcp server entries?

**Comment by peter-stadler** [comment]
We have two possibilities for nginx, I am using the first one here:
1. Every applications uses its own `server { … }` part in the nginx.conf: They need a valid `server_name` to be reachable. I am creating the `ariang.lan` name with _dhcp_ as a default here.
2. All applications share the same `server { … }` part in the nginx.conf (we move the `include conf.d/*.conf;` line into this part; the included files cannot have a own `server { … }` part): Then we have to distinguish the other applications by the URI after the (sub-)domain part, and the applications need to be changed accordingly. That makes it more difficult for other applications to use nginx, and we cannot change only the dns of a subdomain if we want transfer an application at one point to another system (server). 

I am not sure what if there is not a better solution, compare also point 4. of my [comment for the etesync-server](https://github.com/openwrt/packages/pull/9865#issue-312331196):
> Use a real domain instead of etesync.lan as servername to make it reachable.  I am not sure how to interact with the nginx configuration (right now it is based on my other [PR for nginx](https://github.com/openwrt/packages/pull/9859)). Do you have any suggestions? Would it help to make it available via uci? Or would that be a bad idea or difficult?

**Comment by peter-stadler** [comment]
(synced another change from nginx)

**Comment by Ansuel** [comment]
Well... to make nginx configurable in uci i think the only way is make a script that check options on the uci files and generate the nginx file accordingly (like we do for samba, unbound or other package) 

The only problem is that nginx have at least 4 different part to configure so it's really a big mess... IMHO too much to consider... 

Still dubious about ariang.lan domain.. Can't we just create multiple server config section without specifying the address? 
Also i think that call 192.168.1.1/ariang doesn't work in this type of configuration.. am i wrong?

**Comment by peter-stadler** [comment]
192.168.1.1/ariang will not work, that needs a `location /ariang { … }` part in the specific `server { … }` part that nginx recognizes as the default_server (The would go in the direction of 2.).

Multiple `server { … }` parts without `server_name` gives not what we want: only one would be the default_server that would have to handle all the requests. Nginx selects the server by domain name and port.

Actually, we would have a third possibility by using different ports. But I think that would be the least desirable one.

**Comment by Ansuel** [comment]
Problem is that on user side is less logic to access ariang ( for example ) with a dedicated address instead of router_addess/ariang 

One solution would be specific names for include file

For example:

In server with localhost address we put
 `include conf.d/local/*.conf` for everything that needs to run in the shared { ... } server 


For everything else we keep the `conf.d/*.conf` string

**Comment by peter-stadler** [comment]
You are right. Right now I have the idea to create a `conf.d/lan.conf` with the right IP and IP6.
```
server {
    listen LANIP:80 default_server;
    listen [LANIP6]:80 default_server;
    include conf.d/*.lan;
}
```
This should be recreated on every change of the IP/IP6. How we get them?

Different applications can decide wether to put a `location` in `conf.d/app.lan` or to put a `server` in `conf.d/app.conf`.

**Comment by Ansuel** [comment]
A Little tricky (think a readme in conf.d to explain this would be good)

Anyway I think that to make the inclusion of lan entries in the local server easier we should put

In nginx the local server { ... } with include conf.d/lan/*.conf 

And outside it include conf.d/*.conf

Sorry if it's not that clear but I'm writing by phone... Will make an example with a real conf asap

**Comment by peter-stadler** [comment]
We could call the following script on all IPv4/IPv6 changes, but how?
```
mkdir -p /etc/nginx/conf.d/lan
LANIP4=$(ifconfig br-lan | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
LANIP6=$(ifconfig br-lan | grep 'Scope:Link' | cut -d/ -f1 | awk '{ print $3}')
cat <<EOF >/etc/nginx/conf.d/lan.conf
# This file is recreated automatically on all IP/IP6 changes.
server { 
    listen $LANIP4:80 default_server; 
    listen [$LANIP6]:80 default_server; 
    include conf.d/lan/*.conf;
}
EOF
```

**Comment by Ansuel** [comment]
Can't understand why we need to specify the IP
To make it accessible only from Lan?

Il Mar 29 Ott 2019, 14:28 peter-stadler <notifications@github.com> ha
scritto:

**Comment by peter-stadler** [comment]
Yes, else it would act as default_server for all IPs on the specified port (80) and we cannot expose only some of them to the internet.

**Comment by Ansuel** [comment]
Think we should put this script in init.d and set procd to reload nginx on changes to network... 
Pretty bad as nginx will get restarted with EVERY change to network config file... 

Pretty hard to solve this

**Comment by peter-stadler** [comment]
Assuming that we move `luci_uwsgi.conf` to `conf.d/luci.locations`, we can include that in an additional `conf.d/DOMAIN.conf` like:
```
server {
        listen 80;
        listen [::]:80;
        server_name DOMAIN;
        # include conf.d/other_sites_under_this_domain.locations;
        # ...
        include conf.d/luci.locations;
        # ...
        # include conf.d/other_sites_under_this_domain.locations;
}
```
or with ssl:
```
server {    
        listen 443 ssl; # http2                                                           
        listen [::]:443 ssl;  # http2
        server_name DOMAIN; 
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_tickets off;
        ssl_certificate DOMAIN.cer;
        ssl_certificate_key DOMAIN.key;
        # include conf.d/other_sites_under_this_domain.locations;
        # ...
        include conf.d/luci.locations;
        # ...
        # include conf.d/other_sites_under_this_domain.locations;
}
```

**Comment by peter-stadler** [comment]
The following init file (re-)creates a temporary lan conf file `/var/nginx_lan.conf` on changes of the lan interface and restarts nginx if needed, i.e., exactly when its content changes (cf. `pgrep nginx`):
```
#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=80

USE_PROCD=1

LAN_CONF="/var/nginx_lan.conf"

create_lan_conf() {
    local LISTEN
    for IP in $(ifstatus lan | grep '"address"' | cut -d'"' -f4);
    do
        # if IPv4:
        echo $IP \
        | grep -q '^\([12]\?[1-9]\?[0-9].\)\{0,3\}[12]\?[1-9]\?[0-9]$' \
        && LISTEN="listen $IP default_server;\n            $LISTEN"
        # if IPv6:
        echo $IP \
        | grep -q '^\([0-9a-f]\{1,4\}\|:\)\(:[0-9a-f]\{0,4\}\)\{1,7\}$' \
        && LISTEN="listen [$IP] default_server;\n            $LISTEN"
    done
    printf "# This file is re-created if Nginx starts or a LAN address changes.
        server {
            $LISTEN
            include '/etc/nginx/conf.d/*.locations';
        }
    " > "$LAN_CONF"
}

start_service() {
    [ -d "/var/log/nginx" ] || mkdir -p "/var/log/nginx"
    [ -d "/var/lib/nginx" ] || mkdir -p "/var/lib/nginx"
    create_lan_conf

    procd_open_instance
    procd_set_param command "/usr/sbin/nginx" -c "/etc/nginx/nginx.conf" \
        -g 'daemon off;'
    procd_set_param file "/etc/nginx/nginx.conf" "/etc/nginx/conf.d/*.conf" \
        "/etc/nginx/conf.d/*.locations" "$LAN_CONF"
    procd_set_param respawn
    procd_add_reload_interface_trigger "lan"
    procd_close_instance
}
```

**Comment by Ansuel** [comment]
Looks good.. we should test this with luci if it does cause any problem but should be ok....

**Comment by peter-stadler** [comment]
Adopting to the [proposal for nginx](https://github.com/openwrt/packages/pull/9859#issuecomment-548277978).

**Comment by peter-stadler** [comment]
(closed in favour of #11238)

**Pull request closed without merging**
