### PR TITLE
net-snmp: move to PCRE2 library

### PR DESCRIPTION
**Pull request by Ansuel**
Add upstream patch adding support for pcre2 and update dependency to require libpcre2 instead of libpcre.

--without-pcre is now needed to exclude support for pcre and only require pcre2.

Maintainer: @stintel

### CODE REVIEW

**Comment by Ansuel** [comment]
Bumping the package is waaay too much effort and it seems there are some strange compilation error. For now we just backport. Also the current release doesn't include pcre2 support so we would have to patch the source anyway.

**Comment by stintel** [comment]
```
Package libnetsnmp is missing dependencies for the following libraries:
libpcre.so.1
```

I guess I need to disable libpcre but ideally it would not pick it up at all.

**Comment by Ansuel** [comment]
@stintel it's funny net-snmp requiring the library... i have to do some magic or check the backport patch.

**Comment by Ansuel** [comment]
@stintel ok fixed... it's just that they made the config args a bit confusing.... patch 201 was clear and we need to set explicit support for pcre2 or pcre is still used by default. (and having funny situation with linking both library)

**Comment by BKPepe** [comment]
Is it okay to cherry-pick it to OpenWrt 23.05 branch?

**Comment by stintel** [comment]
> Is it okay to cherry-pick it to OpenWrt 23.05 branch?

No objections.

**Pull request merged**
