### PR TITLE
collectd: add additional config option

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @hnyman 
Compile tested: only script chanes
Run tested: x86_64, APU3, OpenWrt master

Description:

- Add new memory config values
- Add new cpu config values

### CODE REVIEW

**Comment by neheb** [comment]
This is failing on nut. The libgd conversion to CMake broke it.

```
checking for gd version via gdlib-config... none found
checking for gd include flags... 
checking for gd library flags... -L/usr/X11R6/lib -lgd -lpng -lz -ljpeg -lfreetype -lm -lXpm -lX11
checking for gd.h... yes
checking for gdfontmb.h... yes
checking for library containing gdImagePng... no
configure: error: libgd not found, required for CGI build
```

I backported the patch that adds support but it's still failing.

**Comment by neheb** [comment]
Depends on: https://github.com/openwrt/packages/pull/9986

**Comment by hnyman** [comment]
Neheb, at the first glance I see no connection between this PR and nut.
(That nut related stuff fails, is a separate thing.)

**Comment by neheb** [comment]
There absolutely is.

Check on CircleCI the Artifacts section. 

Under  
home/
    build/
        build_dir/
            bin/
            logs/
                package/
                    feeds/
                        base/
                        packages/

nut shows up.

**Comment by hnyman** [comment]
Sure, circleci fails because there is a nut plugin in collectd that requires stuff from nut, but the change by this PR has no actual relation to nut.

It is completely separate issue from this PR that a libgd change broke nut a few days ago, which then broke other dependent packages that require nut, like collectd. Circleci just compiles the whole collectd and notices that it is broken as nut is broken.

Hopefully the already merged nut fix does fix things.

**Comment by neheb** [comment]
Needs to be rebased against master to pass. Or just merge since it will succeed anyway...

**Pull request merged**
