### PR TITLE
json-glib: update to 1.6.2

### PR DESCRIPTION
**Pull request by micmac1**
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

Maintainer: me
Compile tested: ath79 on master and 19.07
Run tested: ath79 on 19.07, using rtpengine, making some calls through kamailio/asterisk
Description: version bump

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
lgtm

**Comment by PolynomialDivision** [comment]
Why is the installation always to `libjson-glib-1.0`?

**Comment by PolynomialDivision** [comment]
> Why is the installation always to `libjson-glib-1.0`?

Okay even on my hostsystem it is still `libjson-glib-1.0`. So lgtm. ;)

**Comment by micmac1** [comment]
I don't understand your question. Care to rephrase?

**Comment by PolynomialDivision** [comment]
I mistakenly thought that the order name reflected the version. So I thought it should be `libjson-glib-1.6` instead of `libjson-glib-1.0`.

**Pull request merged**
