### PR TITLE
frr: update to 7.2

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Maintainer: me
Tested: x86

With this, quagga can pe deprecated, I tracked down the problems with inactive routes (seems that is still being worked on)
this is WIP because ~~release links are faulty and they will be fixed and also~~ waiting for the VTI interfaces final fix, but based on my tests everything is fine

### CODE REVIEW

**Comment by lucize** [comment]
reworked makefile to add support for OpenSSL
@neheb @diizzyy is the presented ideea in postinstall script a viable solution so we can drop quagga from tree ?

**Comment by diizzyy** [comment]
LGTM

**Comment by lucize** [comment]
@neheb can we have this on 19.07, from my test seems to be stable and a better option to quagga

**Comment by kunxiang1** [comment]
Hello, when I update to 7.2, the following error occurs, my architecture is ramips, mt7621

`BusyBox v1.30.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 19.07-SNAPSHOT, r10658-502c4a8
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:~# vtysh
-ash: vtysh: not found
root@OpenWrt:~# /etc/init.d/frr start
Bus error
Failed to start watchfrr!
root@OpenWrt:/# watchfrr
Bus error
root@OpenWrt:/#`

**Comment by lucize** [comment]
I think vtysh is needed for loading frr.conf but I have a mt7621 and I'll verify

**Comment by neheb** [comment]
@lucize note that neither quagga not frr are available on 19.07 currently.

**Comment by kunxiang1** [comment]
I flashed the SNAPSHOT version today, which is the same error message.

login as: root
root@192.168.1.1's password:
Server refused to set environment variables


BusyBox v1.31.1 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r11469-db09335
 -----------------------------------------------------
root@OpenWrt:~# vtysh
-ash: vtysh: not found
root@OpenWrt:~# watchfrr
Bus error
root@OpenWrt:~# /etc/init.d/frr start
Bus error
Failed to start watchfrr!
root@OpenWrt:~#

**Comment by lucize** [comment]
I've tested the snapshot with 7.2 and can confirm the problem, I'll try with master frr and see if I can find the offending commit

**Comment by lucize** [comment]
7.3 dev is working

**Comment by kunxiang1** [comment]
Thanks, wait for your update.

**Comment by lucize** [comment]
please confirm me that vtysh is not available, I think that I packed it wrong in the Makefile rework

**Comment by lucize** [comment]
vtysh is missing but is not the problem..

**Comment by kunxiang1** [comment]
Yes, I didn't see vthsh
`root@OpenWrt:~# cd /usr/sbin
root@OpenWrt:/usr/sbin# ls
adjtimex              fabricd               iptables-save         odhcp6c               plainrsa-gen          ubicrc32              vrrpd
aliddns               frrcommon.sh          isisd                 odhcpd                pppd                  ubidetach             watchfrr
babeld                hostapd               iw                    odhcpd-update         racoon                ubiformat             watchfrr.sh
bfdd                  igmpproxy             ldpd                  opennhrp              racoonctl             ubimkvol              wpa_supplicant
bgpd                  ip6tables             nhrpd                 opennhrpctl           rate.awk              ubinfo                wpad
brctl                 ip6tables-restore     nlbw                  opkg-key              ripd                  ubinize               xtables-legacy-multi
chroot                ip6tables-save        nlbwmon               ospf6d                ripngd                ubirename             zebra
crond                 ipsec                 ntpclient             ospfd                 setkey                ubirmvol
dnsmasq               ipset                 ntpd                  pbrd                  staticd               ubirsvol
dropbear              iptables              ntpd-hotplug          pdnsd                 ubiattach             ubiupdatevol
eigrpd                iptables-restore      ocserv                pimd                  ubiblock              uhttpd
root@OpenWrt:/usr/sbin#

`

**Comment by lucize** [comment]
found the problem, added a new PR

**Comment by kunxiang1** [comment]
I downloaded the patch and recompiled it. Found that vtysh's makefile has a depends +mores, I don't know what it is, the compiler does not pass, I deleted it directly.Compiled

**Comment by lucize** [comment]
more is used instead of cat in vtysh pager, it's available on snapshot

**Comment by kunxiang1** [comment]
Ok, thank you, I recompile with snapshot

**Comment by lucize** [comment]
maybe you need to run make menuconfig so more will be selected

**Comment by kunxiang1** [comment]
Yes, I re-make menuconfig and choose it. and I ‘ll try to run it late find out it is working properly or not

**Pull request merged**
