### PR TITLE
python: disable with-ensurepip option for host build

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: LEDE trunk
Run tested: none

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@commodo @jefferyto 
The python ecosystem looks complicated. After the latest change at least python-enum34 fails for some targets (with some buildslaves?) in buildbot. E.g.
https://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/python-enum34/compile.txt
```
Traceback (most recent call last):
  File "./setup.py", line 3, in <module>
    import setuptools
ImportError: No module named setuptools
```

**Comment by commodo** [comment]
hmm ; alright ; i will try to drop the python-setuptools + python-pip packages and enforce the ones that come with Python
that way, this should be addressed once for all ; it will take me some time

**Comment by jefferyto** [comment]
The python-enum34 error is because enum34 1.1.3 added a dependency to setuptools, which I didn't notice when I updated the Makefile for 1.1.6. I'll update it shortly.

Whether we should use the built-in setuptools/pip or the package versions for host, I don't have a strong opinion (for now anyway).

**Comment by commodo** [comment]
to me it's more of lazyness aspect: rather than maintaining 6 packages, it's just 2 ; which makes updating way easier ; also, `python` [the maintainers] would take care of any compat issues with setuptools & pip

**Comment by jefferyto** [comment]
Would we still have separate packages for setuptools and pip for target devices?.

**Comment by commodo** [comment]
yep ; they would technically be packaged as other python built-in packages

**Comment by jefferyto** [comment]
FWIW Debian/Ubuntu and Fedora appear to package setuptools and pip from source rather than use the built-in versions. Doesn't mean we must do the same, but I wonder why they made that decision. (Maybe it's easier to patch the source?)

**Pull request merged**
