### PR TITLE
mutt: bring back from oldpackages

### PR DESCRIPTION
**Pull request by philenotfound**
* import from oldpackagesg
* bump version and update hash
* update patch to new version
* add PKG_LICENSE, PKG_LICENSE_FILES, PKG_MAINTAINER

### CODE REVIEW

**Comment by hnyman** [comment]
Your commit message lacks the "signed-off-by" line.
Please amend the commit message to included that.

You have the commit in a separate mutt branch, so it is easy to amend.
Advice in https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by philenotfound** [comment]
Fixed

**Comment by hnyman** [comment]
@philenotfound 

I tested installing the package after merging the new commit and there is now complaint about a missing dependency for libncurses:
```
Package mutt is missing dependencies for the following libraries:
libncurses.so.5
Makefile:53: recipe for target '/Openwrt/trunk/bin/ar71xx/packages/packages/mutt_1.5.24-1_ar71xx.ipk' failed
```
I tested a few days ago compiling the package, but the error did not surface then :-(

Please check the dependencies.

**Comment by philenotfound** [comment]
That's strange, it already has +libncursesw as a dependency

How do you build it exactly?

**Comment by hnyman** [comment]
The error seems a bit elusive. Buildbot has now built the package for malta platform, so the package seems to pass validation at builtbot.

I made a clean minimal test build with just the device selection (ar71xx / WNDR3700) and the mutt package. No other packages selected, so there are just the defaults like ubus, procd etc.

Diffconfig: https://gist.github.com/hnyman/ece652c065c193c31bf8#file-1_normal-diffconfig
That generates build error as ncurses.h headers are not found:
https://gist.github.com/hnyman/ece652c065c193c31bf8#file-1_compile-log

I then manually added also "libncurses" to config via menuconfig (which selection also adds "terminfo") , ran make clean and then built successfully:
diffconfig: https://gist.github.com/hnyman/ece652c065c193c31bf8#file-2_libncurses_y-diffconfig
build log (first ~300 lines): https://gist.github.com/hnyman/ece652c065c193c31bf8#file-2_compile-log

Comparison shows that the configuration does not find ncurses.h unless libncurses is included in the build config:
```
86,88c86,88
< checking ncursesw/ncurses.h usability... no
< checking ncursesw/ncurses.h presence... no
< checking for ncursesw/ncurses.h... no
---
> checking ncursesw/ncurses.h usability... yes
> checking ncursesw/ncurses.h presence... yes
> checking for ncursesw/ncurses.h... yes
323,328c323,345
< In file included from imap_private.h:24:0,
<                  from auth.c:28:
< ../mutt_curses.h:52:21: fatal error: curses.h: No such file or directory
< compilation terminated.
< Makefile:397: recipe for target 'auth.o' failed
< make[6]: *** [auth.o] Error 1
```

But strangely, I did not get the same "missing dependencies" error as yesterday. Yesterday I updated feeds (after the merge) and ran "make package/mutt/install V=s".

**Comment by thess** [comment]
I saw this discussion last week and forgot to comment.

FWIW - I ran into a similar problem with another package and resolved it by adding
> PKG_BUILD_DEPENDS += libncurses

In addition to the DEPENDS:=+libncursesw

This did resolve the random build failures when libncurses was not selected.

**Comment by hnyman** [comment]
I came to similar conclusion that there is some dependency missing when I looked at my logs a few days ago. Or the libncursesw include headers are installed to a directory which is overlooked by pkg_config, libtool etc. Or something similar.

libncursesw was originally added by https://dev.openwrt.org/changeset/22669/ and it depended on libncurses at that point.
However, 3 years ago the dependency was removed by https://dev.openwrt.org/changeset/31861/ by @nbd168 

I guess that in 95% of cases the user has included some other package causing the presence of libncurses, and the need for an additional dependency at libncursesw never surfaces. But testing with a minimal config (just a basic device + one package depending on libncursesw) may bring the need into surface.

This may well be a combination of Openwrt's libtool, pkg_config and the respective package's configure scripts. But a need for additional PKG_BUILD_DEPENDS at each package using libncursesw seems inefficient. It would be great to be able to fix libncursesw itself.

**Comment by thess** [comment]
Sorry to hijack this thread - perhaps this conversation needs to move elsewhere.

Did a bit more drilling down into this one today - It seems there are packages (zile and others) that won't build anywhere unless libncurses headers are installed. That is when the (n)curses.h files are in the .../include directory and not in the .../include/ncursesw/ directory. Even after fixing the package's auto-magic configure (m4 files) to look in the right place, the OpenWrt include files for ncursesw do not work. curses.h has:
> `#include <ncurses_dll.h>`

which fails in configure and builds.  It should be:
> `#include <ncursesw/ncurses.h>`

which is how it is at least on my Ubuntu/Debian environments when libncursesw5-dev is installed.

So at the least, we need to fix libncursesw headers to work and also those broken packages which don't configure correctly.

**Pull request merged**
