### PR TITLE
strongswan: update to version 5.9.3

### PR DESCRIPTION
**Pull request by Thermi**
Maintainer: me, @pprindeville
Compile tested: Not yet. Let's see.
Run tested: same

Description:

Update to latest release 5.9.3.

### CODE REVIEW

**Comment by neheb** [comment]
Need to run mak package/strongswan/{clean,refresh}

**Comment by Thermi** [comment]
Commands fail because there is no such target.

**Comment by neheb** [comment]
make package/strongswan/{clean,refresh} works fine locally.

Here's the commit with that applied: https://github.com/neheb/packages/commit/8124e01b1026205daf2ad21c5c8408465fa3ccb2

**Comment by Thermi** [comment]
Great. Here, running the commands eventually succeeds after feeds were updated, but there is no difference in the source tree.

**Comment by neheb** [comment]
Right. but the CI demands cleaned patches.

**Comment by Thermi** [comment]
What are cleaned patches exactly? Patches that apply without fuzz?

**Comment by neheb** [comment]
The CI check basically runs all patches through quilt. If they differ, it errors.

Most "issues" here deal with diff entries.

**Comment by Thermi** [comment]
Thank you. I figured out the problem. "packages" was in the wrong directory. Duh.

**Pull request merged**
