### PR TITLE
protobuf-c Update Makefile

### PR DESCRIPTION
**Pull request by ppaulojr**
Maintainer: @jsiverskog @jow-

Compile tested: ramips, mt7620, current commit
Run tested:  ramips, mt7620, current commit

Description:
Fixes https://github.com/openwrt/packages/issues/4155

### CODE REVIEW

**Comment by jsiverskog** [comment]
There are several references to libprotobuf-c in other makefiles, which most likely will fail if this is accepted.

**Comment by ppaulojr** [comment]
I agree but it seems that the other option is to have a folder `libprotobuf-c` instead of `protobuf-c`

**Comment by diizzyy** [comment]
...or you do a treewide sweep

**Comment by hnyman** [comment]
It makes no sense to change the package name, as it might break other packages using this one.
And there is no necessity to have the package name to match the directory name.

Like I commented in your issue, both LEDE and Openwrt buildbots build the package quite normally and I just tested it myself. Built ok.

**Pull request closed without merging**
