### PR TITLE
wifischedule: updated to 1.0.5-1

### PR DESCRIPTION
**Pull request by newkit**
- Fixed _get_wireless_interfaces, thanks to @Trekky12
- Check schedule during router startup

Fixes: https://github.com/newkit/wifischedule/pull/9
Maintainer: @newkit
Tested: TP-Link WDR3600 with OpenWRT 23.05

Signed-off-by: Nils Koenig openwrt@newk.it

### CODE REVIEW

**Comment by newkit** [comment]
@jefferyto Couldn't do a proper rebase, but this new PR should be fine, wdyt?

**Comment by jefferyto** [comment]
Missing angle brackets (`<>`) around your email address in the Signed-off-by line.

**Comment by newkit** [comment]
🙈

**Comment by newkit** [comment]
@jefferyto Would you be able to merge or who should I ping about that?

**Pull request merged**
