### PR TITLE
Krb5 fixes

### PR DESCRIPTION
**Pull request by paulfertser**
@MikePetullo , can you please notify upstream of this cross-compiling issue?

### CODE REVIEW

**Comment by MikePetullo** [comment]
About notifying upstream: I sent a report to the Kerberos folks soon after I wrote the patch. Please see http://krbdev.mit.edu/rt/Ticket/History.html?id=8151.

**Comment by paulfertser** [comment]
Hello Mike,

I meant notifying them about https://github.com/paulfertser/packages/commit/1bd4bc86319bdfe9291dc61872267c354e4b1997 (the cross-compiling issue that I fixed).

Do you need any additional clarifications or testing from me for this "github pullrequest" to be merged?

**Comment by MikePetullo** [comment]
I am a little confused as to what the precise problem is.

configure.in contains:

for t_dir in /var/tmp /usr/tmp /var/usr/tmp /tmp ; do
        test -d $t_dir || continue
        krb5_cv_sys_rcdir=$t_dir
        break
done

Later, rc_io.c contains:

#ifdef RCTMPDIR
            dir = RCTMPDIR;
#else
            dir = "/tmp";
#endif

Are you suggesting that the Kerberos build process does not identify /tmp as the only temporary directory present? If so, this seems to indicate a bug, that is, things would not seem to work out the way the Kerberos developers intended. If you have seen evidence of this, then I would suggest that you yourself report the bug upstream, since you have collected the evidence. I could add a comment as the OpenWrt maintainer if you think that would help.

I think we can merge commit db3c710e immediately.

I think commit 1bd4bc86 requires a little more description, and it also seems to conflate two issues: (1) /tmp not properly identified (?) and (2) do not remove libcom_err.so*.

**Comment by paulfertser** [comment]
The specific problem I'm talking about is that "for t_dir in /var/tmp /usr/tmp /var/usr/tmp /tmp ; do" shouldn't be attempted at all ever in case it's cross-compiled. I discovered it because the system I used for compilation had /var/tmp and so the resulting binaries ended up trying to create kerberos cache in /var/tmp which doesn't exist on OpenWrt.

I agree my commit mixes two issues up, if you say so, I'll split it up, no problem with that. BTW, why was libcom_err removed, what was the reasoning behind that? In my case it was clearly required.

**Comment by paulfertser** [comment]
Just to clarify: the ./configure process searches for the first available directory and only that is used in the resulting binaries, it's not a list, it's just a single directory in the end. And if /var/tmp happens to be present on the host system, it'll get selected.

Regarding bugreporting upstream, I didn't yet try it just because I'm lazy, thought you have all the procedure (bugzilla account, project rules etc) handy and it's easy to do for you. If you suppose I'm better suited for that, ok, I'll bugreport myself.

**Comment by MikePetullo** [comment]
Now I see the problem. By cross-compiling, the configure script with find /var/tmp on the host machine, even though it does not exist on the target machine. I will allow you to submit the bug if you don't mind. As far as breaking up the commits, I suggest that you do that because that is generally what has been asked of me when I submit pull requests.

**Comment by MikePetullo** [comment]
See also paulferster's report at https://krbdev.mit.edu/rt/Ticket/Display.html?id=8254.

**Comment by paulfertser** [comment]
http://patchwork.ozlabs.org/patch/523812/

**Comment by sbyx** [comment]
/var/tmp fix has been accepted. I'm closing this now since it doesn't apply anymore as well. Please reopen if any issues remain.

**Pull request closed without merging**
