### PR TITLE
less: update to 563, move binary to /usr/libexec

### PR DESCRIPTION
**Pull request by zhanhb**
Maintainer: @neheb @Zokormazo 
Compile tested: ath79/nand
Run tested: ath79/nand

### CODE REVIEW

**Comment by BKPepe** [comment]
In the commit message there isn't why it was moved from /usr/bin to /usr/libexec. :/

**Comment by BKPepe** [comment]
Can you please next time mention release notes or at least add in your PR description link for them?

**Comment by zhanhb** [comment]
Title of commit https://github.com/openwrt/packages/pull/14176/commits/7ec279ad3e8c97901afbdbc46ebe7e37b8a8137a is  `less: move binary of alternatives to /usr/libexec` whose length is 49.
 
The description of the PR updated.

**Comment by BKPepe** [comment]
> Title of commit 7ec279a is less: move binary of alternatives to /usr/libexec whose length is 49.

My question was rather why? That should be described in the commit message to have some history and know why someone does things and what was their reason.

**Comment by zhanhb** [comment]
I'll do that the next time.

**Pull request merged**
