### PR TITLE
meson: use ninja from tools

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @dhewg 
Compile tested: ath79

### CODE REVIEW

**Comment by dhewg** [comment]
LGTM, thanks!

**Comment by dhewg** [comment]
The targets don't configure/build though

**Comment by neheb** [comment]
Something wrong with the first commit.

Anyway, I've tested this patchset with all packages. Everything compiles.

**Comment by cotequeiroz** [comment]
I'll give this a spin right now.  It may take me a while to report back, though.

**Comment by neheb** [comment]
looks like the issue was an old SDK lacking ninja.

**Comment by neheb** [comment]
This is missing all the BUILD_PARALLEL stuff I think.

**Pull request merged**
