### PR TITLE
uwsgi: recreate uwsgi-python3-plugin after upgrading python

### PR DESCRIPTION
**Pull request by peter-stadler**
Maintainer: @Ansuel 
Compile tested: x86_64, x86_64 qemu, master
Run tested: x86_64, x86_64 qemu, master, run etesync-server

Description: Create new version of uwsgi-python3-plugin that is linked to libpython3.9 instead of 3.8.

### CODE REVIEW

**Comment by Ansuel** [comment]
Any idea how to prevent this in the future? Wonder if the python module suffer of the same problem.

**Comment by peter-stadler** [comment]
Hmm, not really; the only solution I have in mind, is to version it (uwsgi-python38-plugin and uwsgi-python39-plugin), but I am not sure if this is a good thing. I will look if I find another solution ...

**Comment by Ansuel** [comment]
A hint should be how the python module handle the version.

**Comment by neheb** [comment]
Interesting buildbot failure...

I don't experience it locally but @pprindeville does.

ping @jefferyto

**Comment by neheb** [comment]
Please rebase to remove those red checkmarks.

**Comment by peter-stadler** [comment]
Rebased, thank you for the fix :-)

I am not sure if we need this change: in the package system `uwsgi` is already rebuild using python3.9. It was just not updated on my system because it had the same version number, but I successfully reinstalled the other python3-packages (maybe their version numbers were increased unrelated to the direct upgrade of python3) ...

**Comment by jefferyto** [comment]
I think this issue still exists for most/all Python packages, although it would only affect master and not release branches, since release branches will stay on the same 3.x version of Python.

Python-dependent packages may be rebuilt by buildbots, but opkg on users' systems will not know to reinstall them after a Python upgrade like 3.8 to 3.9. In this case it is a change from libpython3.8 to libpython3.9, but even for "plain" Python packages, their install path changes from `/usr/lib/python3.8/site-packages` to `/usr/lib/python3.9/site-packages`.

I think this may be a good case for adding `ABI_VERSION` to the python3 package (not sure how to have other "plain" Python packages hook into this value though). @commodo any thoughts?

**Comment by commodo** [comment]
ABI_VERSION in Python3 sounds like a good idea
it can be parametrized from `PYTHON3_VERSION_MAJOR` & `PYTHON3_VERSION_MINOR`

**Comment by neheb** [comment]
Sounds like this can be closed?

**Comment by commodo** [comment]
if ABI_VERSION will fix this, then sure;
let me open a PR on that; i forgot about this

**Comment by commodo** [comment]
created PR;
no idea how to proceed from here;
merge the other PR and check back here?

i can see that i would forget about this PR [again] :p

**Comment by pprindeville** [comment]
> I don't experience it locally but @pprindeville does.

@neheb I do?

**Comment by neheb** [comment]
AFAIK it was some issue that is now fixed. I don't remember the details.

**Comment by peter-stadler** [comment]
I am closing this PR as the other one will solve it in the right and broader way (it is not merged, so technically the problem is still open, but I think it is enough to have one PR for it) ...

**Comment by jefferyto** [comment]
Now that #14237 is merged, perhaps it would help to have uwsgi-python3-plugin depend on libpython3?

**Pull request closed without merging**
