### PR TITLE
watchcat: fix broken ping invocation for no-address-family configuration

### PR DESCRIPTION
**Pull request by jtkohl**
Fix for issue #19010

Signed-off-by: John Kohl <jtk.git@bostonpog.org>

Maintainer: @roger-
Compile tested: ramips , 22.03.0-latest
Run tested: ramips, 22.03.0-latest
recent commiters: @rozhuk-im @neheb and @nickberry17

### CODE REVIEW

**Comment by jtkohl** [comment]
same code as PR #19059 but with updated signed-off-by and commit messages to pass test formalities
@kofec @neheb @mistepien

**Comment by jtkohl** [comment]
I'm hoping this will get accepted before 22.03.0 closes, so that it doesn't ship with the busted version.

**Comment by feckert** [comment]
This is not the best solution. But if it works, then let's merge it.

**Comment by feckert** [comment]
Pushed to openwrt-22.03 with https://github.com/openwrt/packages/commit/81601471e078995e8486917e6a37113fbd65a66b

**Pull request merged**
