### PR TITLE
keepalived: update version to 2.0.19

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: me
Compile tested: x86_64, APU3, OpenWrt master
Run tested: x86_64, APU3

Description:
Update to new version 2.0.19

```

keepalived --version
Keepalived v2.0.19 (10/17,2019), git commit reboot-11348-gdb12f25c05

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.79
Running on Linux 4.19.78 #0 SMP Wed Oct 16 09:18:23 2019

configure options: --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls --with-init=SYSV --disable-nftables --enable-sha1 --disable-libipset-dynamic build_alias=x86_64-pc-linux-gnu host_alias=x86_64-openwrt-linux target_alias=x86_64-openwrt-linux PKG_CONFIG=/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/host/bin/pkg-config PKG_CONFIG_PATH=/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/lib/pkgconfig:/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/share/pkgconfig PKG_CONFIG_LIBDIR=/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/lib/pkgconfig:/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/share/pkgconfig CC=x86_64-openwrt-linux-musl-gcc CFLAGS=-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/feckert/workspace/lede/LDM-master-64/build/openwrt/build_dir/target-x86_64_musl/keepalived-2.0.19=keepalived-2.0.19 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.79  LDFLAGS=-L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/lib -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/usr/lib -L/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib -znow -zrelro  CPPFLAGS=-I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/target-x86_64_musl/include -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/usr/include -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include/fortify -I/home/feckert/workspace/lede/LDM-master-64/build/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include

Config options:  LIBIPTC LIBIPSET LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC NET_LINUX_IF_H_COLLISION NETINET_LINUX_IF_ETHER_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

### CODE REVIEW

**Comment by camelcamro** [comment]
did i missed any thing ?
tried newest version openwrt trunk + keepalived...
but now getting:

# /usr/sbin/keepalived -n -C -l -f /tmp/keepalived.conf
Sun Nov  3 18:02:22 2019: Starting Keepalived v2.0.19 (10/19,2019)
Sun Nov  3 18:02:22 2019: Running on Linux 4.14.151 #0 SMP Fri Nov 1 20:19:40 2019 (built for Linux 4.14.151)
Sun Nov  3 18:02:22 2019: Command line: '/usr/sbin/keepalived' '-n' '-C' '-l' '-f' '/tmp/keepalived.conf'
Sun Nov  3 18:02:22 2019: Opening file '/tmp/keepalived.conf'.
Sun Nov  3 18:02:22 2019: track_process not available - is CONFIG_PROC_EVENTS enabled in kernel config?
Sun Nov  3 18:02:22 2019: pidfile_write : Cannot open /run/keepalived.pid pidfile
Sun Nov  3 18:02:22 2019: Stopped Keepalived v2.0.19 (10/19,2019)

kernel config wrong for ZBT-3526 ?

**Comment by feckert** [comment]
@camelcamro thanks for the feedback.
In fact i have the same problems on my lantiq_xrx200 platform (did not tested this before)
On x86_64 everything works as expected!
I will take a look at this what causes this issue in the next days.
Thanks

**Comment by feckert** [comment]
I have also found the following issue on github in the keepalived repo
https://github.com/acassen/keepalived/issues/1119

**Comment by camelcamro** [comment]
WAIT ... fu** ....
i guess it is another problem ....
openwrt is having (on mt7620 and mt7621 images the run dir in  /var/run ....

see the logs:
Mon Nov  4 09:51:14 2019 daemon.info Keepalived[2067]: Starting Keepalived v2.0.19 (10/19,2019)
Mon Nov  4 09:51:14 2019 daemon.info Keepalived[2067]: Running on Linux 4.14.151 #0 SMP Fri Nov 1 20:19:40 2019 (built for Linux 4.14.151)
Mon Nov  4 09:51:14 2019 daemon.info Keepalived[2067]: Command line: '/usr/sbin/keepalived' '-n' '-f' '/tmp/keepalived.conf'
Mon Nov  4 09:51:14 2019 daemon.info Keepalived[2067]: Opening file '/tmp/keepalived.conf'.
Mon Nov  4 09:51:14 2019 daemon.info Keepalived[2067]: track_process not available - is CONFIG_PROC_EVENTS enabled in kernel config?
Mon Nov  4 09:51:14 2019 daemon.info **Keepalived[2067]: pidfile_write : Cannot open /run/keepalived.pid pidfile**
Mon Nov  4 09:51:14 2019 daemon.info Keepalived[2067]: Stopped Keepalived v2.0.19 (10/19,2019)
Mon Nov  4 09:51:14 2019 daemon.info procd: Instance keepalived::instance1 s in a crash loop 7 crashes, 1 seconds since last crash


pls test it again, and before ... create a folder in root: 
mkdir /run

then test again, i guess as i have seen that "CONFIG_PROC_EVENTS" stuff seems to be only a cosmetic message in logs ....
the real problem was to create the PID files ....
seems to be working for me,

pls test

this is only a workaround, why the PID file refers to /run/....  and not anymore to /var/run ... don't know

**Pull request merged**
