### PR TITLE
gphoto2 and libgphoto2: add package

### PR DESCRIPTION
**Pull request by DocLM**
Maintainer: me / @DocLM
Compile tested: (ramips, mt7688, LEDE 17.01.0)
Run tested: (ramips, mt7688, LEDE 17.01.0)

Description:
Add libgphoto2 with modular camlibs and gphoto2 packages

### CODE REVIEW

**Comment by diizzyy** [comment]
Where does the 2012 copyright originate?

**Comment by DocLM** [comment]
I took as a base an old openwrt package from [here](https://dev.openwrt.org/browser/packages/libs/libgphoto2/Makefile) and I did not notice it.
Now fixed.

**Comment by diizzyy** [comment]
Uhm... Technically you should keep the old one and add your own since you're not affiliated with OpenWrt. Also, add origin/source in commit msg(s).

**Comment by DocLM** [comment]
@diizzyy Something like that?

**Comment by diizzyy** [comment]
Better,
"Source: OpenWrt repo, rev 38415 /  32296" is good enough as reference (use the correct rev for each package).

**Comment by DocLM** [comment]
@diizzyy commits updated

**Comment by diizzyy** [comment]
LGTM

**Pull request merged**
