### PR TITLE
keepalived: add uci support

### PR DESCRIPTION
**Pull request by fjamarquez**
Maintainer: @scrpi, @feckert
Compile tested: ath79
Run tested:  check that several options are parsed correctly to keepalived.conf  and that the keepalived daemon is started 
properly.

Description:

These two commits fix the uci support for the package keepalived, allowing its configuration through uci system.

**fix uci support commit:**

> This commit fix three issues in keepalived.init script:
>     
>     1: Modify the position of config_foreach_wrapper() function because
>        the previous functions are called inside it
>     2: Add config_foreach to read the alt_config_file value correctly
>     3: Rename globals section to global_defs

**add uci support for track_bfd configuration commit:**

> Allow the configuration of track_bfd for vrrp instance throught uci. 
> Use the function bfd_instance() to parse the bfd_instance section to keepalived.conf file

### CODE REVIEW

**Comment by feckert** [comment]
Could you please first fix indention we use `tabs`? It looks good at first glance

**Comment by feckert** [comment]
> ok, I think that tabs indention is correct now

Yes its ok now

**To your first commit:**
As I understand it, there is a named `globals` section and there I can specify an alternative configuration in keepalived syntax without using the openwrt uci.
If we do this now as described with your chagne, then I now have several anonymous `globla_defs` section. But I can only use one alternative native keepalived config.

Can you please explain to me what the point is behind this?

**Comment by fjamarquez** [comment]
The `alt_config_file`  (defined in `global_defs` section) parameter defines a configuration file in keepalived format to be used as configuration file instead of the uci configuration (ex. /etc/keepalived/keepalived.conf). With the current init file, that parameter is not used and leaves the final file empty. With the modification, if that parameter is defined, the configuration of the indicated file is applied. 

As I understand it, either the uci configuration or the alternative configuration of the file defined in the `alt_config_file` variable should be applied, but not both at the same time.

**Comment by feckert** [comment]
> As I understand it, either the uci configuration or the alternative configuration of the file defined in the alt_config_file variable should be applied, but not both at the same time.

Yes exactly

But this should work with the current code as I can see.
If the named section `globals` is found in the keepalived uci config, then the `alt_config_file` option is read and a link is set to this file and the function returns and the daemon starts.
```
config globals 'globals'
    option alt_config_file '/etc/keepalived.conf'
```

https://github.com/openwrt/packages/blob/master/net/keepalived/files/keepalived.init#L501

**Comment by fjamarquez** [comment]
That's right, I'm very sorry. I have tested everything again with a full firmware with the latest changes and it worked correctly. I guess in the previous test I missed some library and it didn't parse the configuration properly. I delete the first commit and leave only the second one that includes the tracking configuration with BFD in the uci.

**Comment by feckert** [comment]
Thanks merged!!

**Pull request merged**
