### PR TITLE
emailrelay: update to 2.2

### PR DESCRIPTION
**Pull request by neheb**
Remove upstreamed patch.

Switch to AUTORELEASE for simplicity.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @fededim 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
what a joke of an error. emailrelay doesn't even use vsnprintf.

**Comment by fededim** [comment]
I checked the compilation log, yet it does not say why the compilation of emailrelay fails (no V=s option). I checked the changed files, the problem is autorelease right ? You only removed a patch and updated to a new version.

**Comment by neheb** [comment]
```
 arm-openwrt-linux-muslgnueabi-g++  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -ffile-prefix-map=/home/build/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/emailrelay-2.2=emailrelay-2.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ffunction-sections -fdata-sections -flto -Wl,--gc-sections,--as-needed   -L/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-8.4.0_musl_eabi/usr/lib -L/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-8.4.0_musl_eabi/lib -znow -zrelro  -o emailrelay main.o commandline.o configuration.o legal.o output.o run.o libmain.a ../../src/gpop/libgpop.a ../../src/gsmtp/libgsmtp.a ../../src/gauth/libgauth.a ../../src/gnet/libgnet.a ../../src/gssl/libgssl.a ../../src/glib/libglib.a  -lssl -lcrypto  
/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-8.4.0_musl_eabi/arm-openwrt-linux-muslgnueabi/include/c++/8.4.0/ext/string_conversions.h: In function '__to_xstring.constprop':
/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-8.4.0_musl_eabi/include/fortify/stdio.h:70:28: error: inlining failed in call to always_inline 'vsnprintf': function body can be overwritten at link time
 _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
                            ^
/home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-8.4.0_musl_eabi/arm-openwrt-linux-muslgnueabi/include/c++/8.4.0/ext/string_conversions.h:111:32: note: called from here
       const int __len = __convf(__s, __n, __fmt, __args);
                                ^
lto-wrapper: fatal error: /home/build/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-8.4.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-g++ returned 1 exit status
compilation terminated.
```

I don't use fortify-headers locally.

And again, vsnprintf is not even used in the codebase.

**Comment by neheb** [comment]
I think I know of a way to fix this.

**Comment by neheb** [comment]
GCC8 and 9 fail but 10 succeeds. Great...

**Pull request merged**
