### PR TITLE
zabbix: update to 4.0.16

### PR DESCRIPTION
**Pull request by Rixerx**
Updated to 4.0.15 LTS version.

Compile tested: Yes, lantiq
Run tested: No

Signed-off-by: Krystian Kozak <krystian.kozak20@gmail.com>

Maintainer: @champtar

### CODE REVIEW

**Comment by champtar** [comment]
Thanks @Rixerx
Do you plan to run test it ?

**Comment by Rixerx** [comment]
@champtar Unfortunately, I don't have enought time to check this. If it is necessary, I will try to run it at the end of the week.

**Comment by Rixerx** [comment]
Compile tested: Yes, lantiq
Run tested: Yes, lantiq

**Comment by Rixerx** [comment]
@champtar 

Bumped to 4.0.16 LTS version.

Compile tested: Yes, x86_64 (VirtualBox)
Run tested: Yes, x86_64 (VirtualBox)

**Comment by champtar** [comment]
Thanks @Rixerx, thanks @hnyman

**Pull request merged**
