### PR TITLE
stm32flash: Update to 0.5

### PR DESCRIPTION
**Pull request by neheb**
Fix URL to use SF macro.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @equinox0815 
Compile tested: mvebu

### CODE REVIEW

**Comment by equinox0815** [comment]
LGTM

**Comment by mhei** [comment]
v0.5 is rather old already and there are a lot of newer STM32 CPUs which are not yet supported in this release, but in git repo. What do you think about upgrading to a git reference instead of last release ball?

**Comment by neheb** [comment]
I'd rather add them as patches.

**Comment by hnyman** [comment]
Lets merge this first, and you can then add the new stuff separately

**Pull request merged**
