### PR TITLE
python-idna,pillow: bump versions

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @jefferyto 
Compile tested: x86 https://github.com/openwrt/openwrt/commit/6773bee107
Run tested: x86 https://github.com/openwrt/openwrt/commit/6773bee107

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
Thanks - a new version of idna was just released (about 10 minutes ago lol), would you mind bumping it up to 3.1?

**Comment by commodo** [comment]
> Thanks - a new version of idna was just released (about 10 minutes ago lol), would you mind bumping it up to 3.1?

funny :)
will update

**Comment by commodo** [comment]
Changelog v1 -> v2:
* bump idna 3.0 -> 3.1

**Comment by jefferyto** [comment]
Thanks again!

**Pull request merged**
