### PR TITLE
ffmpeg: add support for libx264 and libmp3lame

### PR DESCRIPTION
**Pull request by ianchi**
also enable fpu if on hard float

Signed-off-by: Adrian Panella <ianchi74@outlook.com>

### CODE REVIEW

**Comment by thess** [comment]
These changes don't look right for all 3 ffmpeg configurations AND all architectures. We certainly don't want libx264 (or mp3-lame) in the mini config. They are also need to be optional for 'custom'.

I will accept this as a request for x264 and mp3-lame as options for __custom__ and inclusion in __full__ variants and add it to my "todo". Support for hard-float is possible, however support for SIMD (NEON, SSE, etc.) and inline-asm may be more difficult for all platforms. These changes need to be tested in full builds on ALL architectures before I can update ffmpeg with extended instruction support. Also on my future "todo" list is moving to ffmpeg 3 which affects several other packages.

**Comment by ianchi** [comment]
Hi @thess, you are right.
I've modified the change to apply only to Full and Custom, adding also the corresponding Config options.
Regarding the optimizations I added them conditionally on the ARCH and CPU type.
For now only ARM (the one I can test), so this doesn't conflict with other targets. Then as more targets are tested their specific optimizations can be enabled. And as features are checked, it shouldn't break arm targets without fpu.

**Comment by champtar** [comment]
@ianchi you pushed an unrelated commits (apcupsd)

**Comment by ianchi** [comment]
rebased to clean commits

**Comment by thess** [comment]
@ianchi - take a look at #3006 (hopefully fixed package dependencies) 

OK?

**Comment by thess** [comment]
Superceded by #3006

**Comment by ianchi** [comment]
@thess sorry for the late comments, I was out of town.

Everything seems to be ok with your changes in #3006 the only thing I don't get is why you set
"--disable-inline-asm" for all architectures.

In ARM it was working well with the asm optimizations, and I added a default to disable it for every other arch (as I can't test it).

**Comment by thess** [comment]
Simply, I didn't have time to test on all ARM variants. It would be nice to have as much inline-asm on as many architectures as possible.

**Pull request closed without merging**
