### PR TITLE
netdata: Update to 1.13.0

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: N/A
Compile tested: ramips, MqMaker WiTi board, OpenWrt master
Run tested: ramips, MqMaker WiTi board, OpenWrt master

Description:
Update netdata to 1.13.0

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@BKPepe

**Comment by karlp** [comment]
links to the chhangelog or changes of interest to openwrt would be nice.  for instance 1.13 moved to cmake (which you're not using her), removed all bash plugins, (only go and python now) which might impact a lot of users on openwrt too.

**Comment by diizzyy** [comment]
We haven't done it in the past and it has worked fine but if you want a link sure, I'll do that.
1.13 didn't move to CMake, it has been available much earlier than that. I have a vague memory if it being broken earlier and/or doing something strange using the OpenWrt toolchain but I can have a look at it again afterwards.

Some bash plugins are still left, like fping for instance but I'm not sure what you're suggesting. opkg doesn't have some kind of message service to my knowledge.

**Comment by BKPepe** [comment]
Compile tested: mipsel_24kc, ramips - mt7621, Xiaomi Mi WiFi R3G, OpenWrt 18.06.02
Run tested: mipsel_24kc, ramips - mt7621, Xiaomi Mi WiFi R3G, OpenWrt 18.06.02

image

___

LGTM! :-)

**Pull request merged**
