### PR TITLE
libextractor: remove ffmpeg plugin

### PR DESCRIPTION
**Pull request by neheb**
FFmpeg has patented functionality.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dangowrt 
Compile tested: ath79

### CODE REVIEW

**Comment by dangowrt** [comment]
FFmpeg *may* contain patented functionality if compiled with it. It doesn't need to. Nor do the header files used by libextractor use any patented functionality.
I don't see why we should remove the ffmpeg plugin entirely (if one doesn't want to install ffmpeg he can just install libextractor without that plugin).

**Comment by neheb** [comment]
I asked on the ffmpeg IRC channel before. ffmpeg developers have a different opinion:

```
mangix@armbiaan ~/i/Freenode> cat "#ffmpeg.log" | grep -i patented
15:20 < mangix> oh fun question: does ffmpeg offer a way to disable patented AAC functionality?
15:33 <@cehoyos> mangix: Just to make sure, even with --disable-all we assume that (a lot of) "patented" algorithms are still compiled
```

I can make this change dependent on BUILD_PATENTED if desired.

**Comment by diizzyy** [comment]
I don't see any need to cripple software just for the sake if it.

**Comment by neheb** [comment]
Note that BUILD_PATENTED is default. Again, it's fairly easy to make this conditional.

**Comment by karlp** [comment]
@neheb Please link to where you have a project agreement or even a discussion on these sweeping changes to remove patented sw.

**Comment by neheb** [comment]
Reworked to use CONFIG_BUILD_PATENTED.

**Comment by neheb** [comment]
Please don't merge until there's a decision here: http://lists.openwrt.org/pipermail/openwrt-devel/2020-August/030629.html

**Comment by neheb** [comment]
The minimal discussion indicates that this should be merged.

**Pull request merged**
