### PR TITLE
pciutils: update to 3.8.0

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Maintainer: me
Tested x86

### CODE REVIEW

**Comment by neheb** [comment]
Given that a separate pciids list is used, does it make sense to get rid of update-pciids?

**Comment by BKPepe** [comment]
I wonder why do we need so many patches for pciutils and nobody bothered to take a look at them, upstream them and we are still rebasing them. I would just throw them away!

**Comment by BKPepe** [comment]
ping @lucize

**Comment by lucize** [comment]
hopefully this weekend

**Comment by lucize** [comment]
removed pci ids related things

**Pull request merged**
