### PR TITLE
lcd4linux: Switch to git

### PR DESCRIPTION
**Pull request by neheb**
Cleaned up Makefile to be more similar to others.

Fixed PKG_MAINTAINER having wrong place.

Added PKG_BUILD_PARALLEL for faster compilation.

Added LICENSE information.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jmccrohan 
Compile tested: arc700

### CODE REVIEW

**Comment by feckert** [comment]
@neheb Thanks for moving this to github.
As I can see the project is dead!
No response from the developer since years!
Only @jmccrohan response to my messages but he is not the main developer.
So the github clone from @jmccrohan is unofficial.
But lcd4linux is used anyway.
In my Repository on github https://github.com/feckert/lcd4linux/tree/pr/feature
I have also added some commits from the community (mailinglist) which are not merged into the upstream project because the development has stopped. 
Up to now I always patch this commits on top of the openwrt packages on my own build, because I am using some new plugins which where added by the commits.
Maybe we could add this patches to openwrt?
If so I will to this  and clean up this commits.

**Comment by neheb** [comment]
Sure. There are currently two packages in the tree using svn. This is one of them.

Worthwhile forks that I saw:

https://github.com/helldoc/lcd4linux
https://github.com/netfun2000/lcd4linux

Maybe they have something useful. I don't use this package so I don't really know.

**Comment by neheb** [comment]
@feckert if I switch to your fork, can I add you as Maintainer?

**Comment by feckert** [comment]
What is with @jmccrohan did you @neheb talked to him? 
Does he not want to maintain this package anymore?
If not i would take it.

**Comment by neheb** [comment]
I have not. This has been here for almost a month with no activity.

**Comment by dangowrt** [comment]
Please consider packaging lcd4linux with support for serdisplib since this is now packaged https://github.com/openwrt/packages/commit/bf033c622a0cf1139ea46842c4cb67c603c1ac7b . I tried this in a local build and so far it worked fine

**Comment by feckert** [comment]
@neheb @dangowrt @jmccrohan @helldoc @netfun2000 I am not sure what we should do now! I am using **lcd4linux** because I have a display on my device (router) for some reason (enable/disable wlan, see some status infos, reboot, factory reset ...) I think this is a cool project, and a nice feature, but the project is **DEAD**. No further commits in the last 3 Years. And also no response from the creator of this project. I think the project should move to github with issue tracking wiki and pullrequest. But I don't want to take over the project without the consent of the founders. I am only a user and I am not familiar with the code right now to provide support. Another project @OpenPLi using lcd4linux too.

**Comment by feckert** [comment]
@neheb nobody respons to my message :-(
It's ok for me that you add me as maintainer and change the url to my fork.
I will then collect the patches lying around in github and update the version. Let's see what happens.

**Comment by neheb** [comment]
Pushed. Also removed two useless patches.

Some of the other ones might be useless as well.

**Comment by feckert** [comment]
@neheb I have just seen that you have set HEAD to my branch pr/feature in openwrt. The commits I made there are not really summarized. And I also didn't appreciate the authors who implemented these features!

**Comment by neheb** [comment]
There's time to fix this before release 20!

**Comment by feckert** [comment]
@neheb I hope I don't forget then.

**Pull request merged**
