### PR TITLE
zerotier: update to 1.10.4

### PR DESCRIPTION
**Pull request by mwarning**
Maintainer: me
Compile tested: ramips/mt7620, Nexx wt3020, OpenWrt master
Run tested: ramips/mt7620, Nexx wt3020, OpenWrt master
Tested: ZeroTier starts

Description:
Minor changes: https://github.com/zerotier/ZeroTierOne/blob/dev/RELEASE-NOTES.md

### CODE REVIEW

**Comment by mwarning** [comment]
ZT 1.10.4 was also tested here: https://github.com/openwrt/packages/pull/20652#issuecomment-1465338273

**Comment by castillofrancodamian** [comment]
https://github.com/openwrt/packages/pull/20642

**Comment by mwarning** [comment]
@KA2107 thank you for the heads up. 1.10.6 was not containing anything of value for Linux.

**Comment by m-zheng** [comment]
@mwarning According to the release notes, ZeroTier 1.12.0 has a 10-30% speed improvement on Linux. Would you consider updating it?

**Comment by mwarning** [comment]
@m-zheng yes, but there are some compiling issues that need to be fixed.

**Comment by mwarning** [comment]
for ZT 1.12.1 https://github.com/openwrt/packages/pull/21936

**Pull request merged**
