### PR TITLE
gnutls: update to 3.7.0

### PR DESCRIPTION
**Pull request by neheb**
Added autoreconf to fix bad linking under Arch Linux.

Added patch to fix compilation with autoreconf.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @nmav 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
ping @NoTengoBattery

**Comment by NoTengoBattery** [comment]
Thank you, I will test tomorrow in my environment and report to you as soon as I can.

**Review by nmav — APPROVED** [review]

**Comment by nmav** [comment]
Thank you for taking the time. The change in the m4 macros is ugly but I could not see any better solution either.

**Comment by NoTengoBattery** [comment]
> Thank you for taking the time.

Thanks to you. This seems to fix the libnettle issue, but the issue with other packages still present. Anyway, applying a small patch to them may solve the issue locally, I would like to see it fixed upstream. This is beyond your scope, thought, but it will help the other maintainers to pinpoint and fix the issue.

**Pull request merged**
