### PR TITLE
sshtunnel: switch to procd

### PR DESCRIPTION
**Pull request by kzyapkov**
`-L`, `-R` and `-D` work fine on a first glance. I haven't tested `tun` device forwarding, but the resulting `ssh` command should be the same as with the previous version.

@nunojpg please take a look, thanks!

### CODE REVIEW

**Comment by nunojpg** [comment]
Ok, this is great. I was planning to take care of this eventually to get rid of all the extra shell processes, but I'm glad you did it! I'm taking a look and if there is no major change required I'll commit it. Thanks, really!

**Comment by kzyapkov** [comment]
I rewrote the commit with a minor update in `validate_tunnelW_section`, maybe I should've pushed another one. Oh well ...

I'm glad I can help :)

**Comment by nunojpg** [comment]
https://github.com/nunojpg/packages/commit/267a829ac1e42675cedf65aede468c655fc18e00

**Comment by nunojpg** [comment]
I did some bugfixes, moved some custom validation to the uci feature, and some style changes. Could you take a look and see if it is OK for you?

**Comment by kzyapkov** [comment]
Thanks for fixing this up!

Just one concern -- it seems `validate_data` only applies its validation logic if the option is present. So you can define tunnels with missing ports which validate fine, then `ssh` bails. Maybe I'm testing this wrong, or missing the point?

I'm adding your changes and Signed-off-by in the mean time.

**Comment by nunojpg** [comment]
I don't really know, I'm testing that later.

If that is the case, we only need to test if the option is present and not the values, since this would be already validated.

**Comment by nunojpg** [comment]
Could you please take a look at my branch for a few changes?

**Comment by kzyapkov** [comment]
Integrated, squashed. Thanks!

**Pull request merged**
