### PR TITLE
picocom: Update to 3.1

### PR DESCRIPTION
**Pull request by neheb**
Switched to new upstream.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @sbyx 
Compile tested: ipq806x

### CODE REVIEW

**Comment by neheb** [comment]
Travis is failing with mips-openwrt-linux-musl-ld: warning: cannot find entry symbol __start; defaulting to 0000000000400130 . I have no idea about this.

**Comment by diizzyy** [comment]
I didn't get that error but I remember in the past when I tried to upgrade picocom to 3.X that it didn't compile however I didn't spend too much time on trying to fix it. Instead I added tio which also is nicer (IMHO), at least for my usage. :-)

**Comment by neheb** [comment]
It broke after 2.0. Version 2.1 starts failing. I think this is the offending commit: https://github.com/npat-efault/picocom/commit/bc9ab1fdf52a1980055949f34a4dd6434e6ec9c8#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by diizzyy** [comment]
Hmm.. might be

You also want to have this patch I guess
https://git.busybox.net/buildroot/tree/package/picocom/0001-Compile-with-libc-s-without-cispeed-cospeed.patch

**Comment by diizzyy** [comment]
@neheb 
Can you post the full verbose log?

**Pull request merged**
