### PR TITLE
Remove two packages: quassel and quassel-irssi

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @TC01 
Compile and run tested: N/A

Description:
Drop two packages, which are dead. No longer maintained.

Superseeds: https://github.com/openwrt/packages/pull/22605
And also relevant https://github.com/openwrt/packages/pull/7454

### CODE REVIEW

**Comment by Ansuel** [comment]
Ok for me... but what about 23.xx ? should we backport?

**Comment by BKPepe** [comment]
Yup, for sure!

**Review by neheb — APPROVED** [review]

**Comment by diizzyy** [comment]
Upstream is still active?

**Comment by Ansuel** [comment]
@diizzyy the irssi seems dead... quasselc same... (this is not about quassel that can't be compiled on openwrt as it does require heavy qt framework... quasselc is a different thing and was a neat project to have a c program that implemented quassel api in pure c...)

I would move these 2 package in abbandoned... maybe someone might be still intersted in them? (I would also merge my patch that fix the compilation just for extra bonus)

**Review by 1715173329 — APPROVED** [review]

**Review by neheb — APPROVED** [review]

**Comment by BKPepe** [comment]
> I would move these 2 package in abbandoned... maybe someone might be still intersted in them? (I would also merge my patch that fix the compilation just for extra bonus)

So, lets merge your fix, I will rebase it and afterwards merge this PR and move this to abandoned repository.

**Pull request merged**
