### PR TITLE
apache: update to 2.4.48

### PR DESCRIPTION
**Pull request by neheb**
Use AUTORELEASE for simplicity.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @heil
Compile tested: ath79

### CODE REVIEW

**Comment by BKPepe** [comment]
This needs to be run tested.

**Comment by BKPepe** [comment]
In the commit message, there is lack that it is a security update and that it fixes multiple CVEs according to https://httpd.apache.org/security/vulnerabilities_24.html

**Comment by BKPepe** [comment]
Then it should be included in OpenWrt 21.02 and 19.07 as well.

**Review by BKPepe — CHANGES_REQUESTED** [review]
Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt 21.02 RC3
Run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt 21.02 RC3
Update from 2.4.26 to 2.4.48. :+1: 
____

Before merging this, please improve the commit message as I said. Also, you refreshed the patch and you didn't said it in the commit.

**Comment by neheb** [comment]
To be fair, refreshing the patch is necessary as otherwise CI will not pass :)

**Comment by neheb** [comment]
If backporting to 19.07 is needed, AUTORELEASE can't be used. I'll fix when I get access to my buildbot again.

**Comment by neheb** [comment]
Adjusted commit message.

**Review by BKPepe — APPROVED** [review]
Thanks! Now it looks much better. 👍

**Pull request merged**
