### PR TITLE
coremark: bump to 2021-11-17

### PR DESCRIPTION
**Pull request by abajk**
Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>

Maintainer: @gwlim @kongfl888
Compile tested: (lantiq/xrx200, BT Home Hub 5A, snapshot)
Run tested: (lantiq/xrx200, BT Home Hub 5A, snapshot)

Description: update to the latest version.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Why did you add `PKG_MAINTAINER:=Lim Guo Wei <limguowei@gmail.com>` and not yourself as maintainer?
https://github.com/openwrt/packages/commit/6a5878e4a0475d9e7bd51679fc16456c344fa999#diff-9b98f279e064d9fc4edf0f0a20d9a23ef9b84465542b045c50c69146c3aac17eR20

**Comment by abajk** [comment]
Originally, gwlim tried to add coremark to openwrt packages. Some time after that I found his [PR](https://github.com/openwrt/packages/pull/6916) and addressed all the comments.

**Comment by PolynomialDivision** [comment]
Can you add yourself as maintainer, since you do all the commits and so on?

**Comment by abajk** [comment]
@PolynomialDivision Done.

**Comment by PolynomialDivision** [comment]
I will merge since the actual maintainer does not ack and is not responding. thanks.

**Pull request merged**
