### PR TITLE
python-mysqlclient: drop package

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: n/a
Run tested: n/a

------------------------------------------------------------

The main user for this package was Seafile.
In the meantime, Seafile switch to PyMySQL.
    https://pypi.org/project/PyMySQL/

PyMySQL seems to be a replacement for python-mysqlclient, and while it may
not be fully compatible with the MySQL API, it may be that those APIs
wouldn't be used.

This change drops this package.
If there is enough usage/reason to bring it back, we can.

For python-mysqlclient, the tag-line/description is:
```
This is a fork of MySQLdb1.

This project adds Python 3 support and bug fixes. I hope this fork is
merged back to MySQLdb1 like distribute was merged back to setuptools.
```

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
ping @jefferyto

**Comment by commodo** [comment]
ping @BKPepe is this a package used on Turris?

**Comment by BKPepe** [comment]
@commodo That's appreciated! I'm glad that you asked.
No no. By default we don't have it preinstalled on Turris routers, theoretically, there could be someone who is using it, but I don't have such numbers.

**Comment by commodo** [comment]
> @commodo That's appreciated! I'm glad that you asked.
> No no. By default we don't have it preinstalled on Turris routers, theoretically, there could be someone who is using it, but I don't have such numbers.

yeah,  i also don't have much info on who-uses-what;
i mostly want to simplify/reduce my workload;
but i use the argument of trying to unclog the build-system of packages that aren't used much

**Comment by neheb** [comment]
Please open a PR at https://github.com/openwrt/packages-abandoned

**Comment by commodo** [comment]
> Please open a PR at https://github.com/openwrt/packages-abandoned

https://github.com/openwrt/packages-abandoned/pull/15

thanks :)

**Pull request merged**
