### PR TITLE
perl: use LDFLAGS for binary

### PR DESCRIPTION
**Pull request by ryzhovau**
`lddlflags` is [used for shared libraries only](http://perldoc.perl.org/Config.html#l). This PR adds `LDFLAGS` for perl binary.

### CODE REVIEW

**Comment by champtar** [comment]
ping @Naoir

**Comment by diizzyy** [comment]
@ryzhovau 
Is this an issue on your end or just a logical error?

**Comment by ryzhovau** [comment]
Two-both.

There's no sense to [define](https://github.com/openwrt/packages/blob/master/lang/perl/Makefile#L99) `owrt:ldflags` if it's not used.

Also, it was cause a bug [on my side](https://github.com/Entware-ng/entware-packages/tree/master/lang/perl) where libraries are in `/opt/lib` folder.

**Comment by hnyman** [comment]
You might need to rebase this.

@pprindeville 
Does this looks sensible for you?

**Comment by pprindeville** [comment]
> Does this looks sensible for you?

What's the difference between `lddlflags` and `ldflags`?  The former is only used for generating .so's?

Looking at the Makefile, I see:

```
define Build/Configure
        $(PERL_CMD) files/perlconfig.pl -Dowrt:target_cc='$(TARGET_CC)' \
                                        -Dowrt:gccversion=$(CONFIG_GCC_VERSION) \
                                        -Dowrt:target_cross='$(TARGET_CROSS)' \
                                        -Dowrt:cflags='$(TARGET_CFLAGS_PERL) $(TARGET_CPPFLAGS_PERL)' \
                                        -Dowrt:ldflags='-rdynamic $(TARGET_LDFLAGS)' \
```

note the `-rdynamic`.  Should we delete that here, and instead do:

```
ldflags='$owrt:ldflags'
...
lddlflags="-shared -rdynamic $owrt:ldflags"
```

to have better separation of static/dynamic linkage?

**Comment by ryzhovau** [comment]
"Rebased" via Github WebUI. This PR looks exactly as in Entware-project. Feel free to add/remove `-rdynamic` or other flags for your needs or decline this PR.

**Comment by pprindeville** [comment]
> Feel free to add/remove -rdynamic or other flags for your needs or decline this PR.

I can't make changes because I'm not a committer, but I am a maintainer.

Please make the above suggested change, test, verify, and I'll approve for commit.

**Comment by pprindeville** [comment]
> Please make the above suggested change, test, verify, and I'll approve for commit.

So what's going on with this PR?

**Comment by ryzhovau** [comment]
Just found a bug which I reproduced in my LEDE-based project. You still can make any decision as a maintainer, so it's up to you.

So, if you'll reject this PR - no problem.

**Comment by ryzhovau** [comment]
No means no.

**Comment by pprindeville** [comment]
> No means no.

@ryzhovau what's the context?

**Comment by ryzhovau** [comment]
I see no sense to keep this PR open if it not needed by anyone, sorry.

**Comment by pprindeville** [comment]
I've asked that changes me made, but they didn't happen so I'll make the changes myself.

**Comment by diizzyy** [comment]
@pprindeville 
We can close this then?

**Comment by pprindeville** [comment]
> We can close this then?

@diizzyy Yes, this was fixed with commit d58ac19.

**Pull request closed without merging**
