### PR TITLE
boost: replace zstd dependency with libzstd

### PR DESCRIPTION
**Pull request by neheb**
libzstd is the correct one.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ClaymorePT

### CODE REVIEW

**Comment by ClaymorePT** [comment]
@neheb Do we care that it failed in so many test-builds?

Btw, thanks for doing this! When did this change happened?

**Comment by neheb** [comment]
@ClaymorePT I'd ignore them. This is not an issue on the buildbots. Just the CI.

zstd was added right before libfolly and friends were (which are now removed).

**Comment by neheb** [comment]
@aparcar I potentially found the issue with the CI:

```
2020-09-18T21:17:17.4521588Z ERROR: please fix feeds/packages_ci/lang/perl-parse-yapp/Makefile - see logs/feeds/packages_ci/lang/perl-parse-yapp/dump.txt for details
```

```
Build-Depends/host: perl/host
Build-Types: host

Package: perl-parse-yapp
Submenu: Perl
Version: 1.21-1
Depends: +libc +USE_GLIBC:librt +USE_GLIBC:libpthread perl +perlbase-essential +perlbase-test
Conflicts: 
Menu-Depends: 
Provides: 
Section: lang
Category: Languages
Repository: base
Title: Yet Another Parser Parser For Perl
Maintainer: Andy Walsh <andy.walsh44+github@gmail.com>
Source: Parse-Yapp-1.21.tar.gz
License: GPL-1.0-or-later Artistic-1.0-Perl
Type: ipkg
Description: Yet Another Parser Parser For Perl
http://search.cpan.org/dist/Parse-Yapp/
Andy Walsh <andy.walsh44+github@gmail.com>
@@

Makefile:27: /home/build/openwrt/feeds/packages/lang/perl/perlmod.mk: No such file or directory
make[1]: *** No rule to make target '/home/build/openwrt/feeds/packages/lang/perl/perlmod.mk'.  Stop.
```

**Comment by neheb** [comment]
Interesting build failure: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/boost/compile.txt

**Pull request merged**
