### PR TITLE
treewide: Change .*GPL.*+ licenses to SPDX compatible identifier

### PR DESCRIPTION
**Pull request by ecsv**
@neheb 

The CONTRIBUTING.md requests an (or multiple) SPDX identifier for GPL licenses. But a lot of packages did use a different, non-SPDX style with a "+" at the end instead of "-or-later".

---

There are 215 packages which still have unknown information. Meaning here that it is unknown whether the package is some GPL license -only or -or-later. Just got this number with:

    git grep 'PKG_LICENSE[[:space:]]*:\?=.*GPL\(v\|-\)\?[0-9]\.[0-9]\([^-]\|$\)' -- '*Makefile'

But there are 4 files which should be checked separately because they use a completely different style (without X.Y):

    git grep 'PKG_LICENSE[[:space:]]*:\?=.*GPL\(v\|-\)\?[0-9][^\.]' -- '*Makefile'

The most interesting looking here is the GPL2-2.0 from net/bwm-ng/Makefile

### CODE REVIEW

**Comment by neheb** [comment]
Build failure:

```
configure: error: glib-compile-schemas not found.
Makefile:267: recipe for target '/home/build/build_dir/build_dir/target-mips_24kc_musl/pulseaudio-noavahi/pulseaudio-12.2/.configured_a17fb5ef857664f03cd0ce37cc5ea591' failed
make[2]: *** [/home/build/build_dir/build_dir/target-mips_24kc_musl/pulseaudio-noavahi/pulseaudio-12.2/.configured_a17fb5ef857664f03cd0ce37cc5ea591] Error 1
make[2]: Leaving directory '/home/build/openwrt_packages/sound/pulseaudio'
time: package/feeds/packages/pulseaudio/noavahi/compile#21.49#7.20#32.18
package/Makefile:111: recipe for target 'package/feeds/packages/pulseaudio/compile' failed
make[1]: *** [package/feeds/packages/pulseaudio/compile] Error 2
make[1]: Leaving directory '/home/build/build_dir'
/home/build/build_dir/include/toplevel.mk:209: recipe for target 'package/pulseaudio/compile' failed
make: *** [package/pulseaudio/compile] Error 2
```

A missing dependency on glib2/host. Most likely broke because of this: https://github.com/openwrt/packages/commit/170ef79393aabc7cfbe3cd4625dc01f0fcc25221

In any case, license changes cause a change to the ipk and should have PKG_RELEASE bumped.

**Comment by neheb** [comment]
Also discovered:

perl-uri changed URLs. Now here: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-1.76.tar.gz

perl-www changed URLs: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.39.tar.gz

mac-telnet tarball has a wrong hash on the OpenWrt mirrors: Hash of the downloaded file does not match (file: 8cc90f9abb48b99d32afb1d9c3295ea549134e8949d5166136e47cab426ff9d7, requested: 13429f1a870121cdbbfb687e0581967904798000eca1f8f9c1e9dc87dee5669b) - deleting download. ping @jow- 

rp-pppoe changed URLs: https://dianne.skoll.ca/projects/rp-pppoe/

hub-ctrl has a wrong hash: Hash of the downloaded file does not match (file: b13e2eb2ef90f33fbed8aced09efd61ca0e10de94ab3b3f4a147d367e2a4e712, requested: 98ffd9ead07d6208acf7f713dc6574877d4967bdfb47bf70444ec9d44399faaa) - deleting download. ping @probonopd

**Comment by ecsv** [comment]
@neheb Thanks for the hint, I have now increased the PKG_RELEASE

**Comment by neheb** [comment]
Needs a rebase.

**Comment by ecsv** [comment]
@neheb Rebased again

**Pull request merged**
