### PR TITLE
v4l2rtspserver: Update to 0.1.1

### PR DESCRIPTION
**Pull request by neheb**
Switched to using versioned releases.

Removed md5 usage and went full sha256.

Various other adjustments.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @roger- 
Compile tested: ramips

I tried to get this to compile with uclibc++ but failed. I will take the issue to upstream.

### CODE REVIEW

**Comment by neheb** [comment]
I succeeded in getting it to compile with uclibc++. The last patch was the missing key (linking error).

**Comment by cshoredaniel** [comment]
+run testing please

**Comment by roger-** [comment]
Thanks for the update!

I can't run test this myself, so someone please do so.

Have you tried pushing those patches upstream?

**Comment by neheb** [comment]
I'd rather track stable releases. I can switch if you really want.

**Comment by roger-** [comment]
I don't see a problem with switching since the only significant changes since the last release seems to be your patches.

**Comment by neheb** [comment]
Fixed a small issue that prevented Os from being passed. Size from 324214 to 324015

**Comment by neheb** [comment]
Hrm LTO drops it down to 293397. Could be worth it.

**Comment by roger-** [comment]
Run testing?

**Pull request merged**
