### PR TITLE
e2guardian: Remove

### PR DESCRIPTION
**Pull request by neheb**
This has been unmaintained since at least 2016 and is woefully out of
date.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @lperkov

### CODE REVIEW

**Comment by neheb** [comment]
Imported into packages-abandoned.

**Comment by ptpt52** [comment]
@neheb 
but `luci/applications/luci-app-e2guardian` still depends on `e2guardian`

**Comment by neheb** [comment]
Yeah. Looks like I was a bit hasty.

**Comment by hnyman** [comment]
I removed the dangling LuCI app.

**Pull request merged**
