### PR TITLE
fdm: bump to latest version

### PR DESCRIPTION
**Pull request by pfzim**
Maintainer: Dmitry V. Zimin / @pfzim
Compile tested: ar7xxx/ar9xxx
Run tested: not tested

### CODE REVIEW

**Comment by champtar** [comment]
Hi @pfzim 
please rebase and squash into 1 commit

**Comment by pfzim** [comment]
Done!

**Comment by champtar** [comment]
Hi @pfzim,
you haven't rebased on latest commit
```
git pull --rebase
fixing the conflict
git add mail/fdm/Makefile
git rebase --continue
git push -f
```

**Comment by pfzim** [comment]
@champtar, Thanks for help

**Pull request merged**
