### PR TITLE
[openwrt-21.02] python3: Add readline to dependency finder script

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me, @commodo 
Compile tested: none (cherry picked from #15856)
Run tested: N/A

Description:
Signed-off-by: Jeffery To <jeffery.to@gmail.com>
(cherry picked from commit 1eeeba60d8cffc2f655c1ecbb277ca6734ac46b7)

### CODE REVIEW

**Comment by commodo** [comment]
just noticed here;
would this require a `PKG_RELEASE` bump?

not sure either

**Review by commodo — APPROVED** [review]

**Comment by commodo** [comment]
ah;
here we can rely on this  https://github.com/openwrt/packages/pull/15857 ?

**Comment by jefferyto** [comment]
> would this require a `PKG_RELEASE` bump?

This script isn't included in any package so I don't think bumping `PKG_RELEASE` is necessary.

**Comment by commodo** [comment]
> > would this require a `PKG_RELEASE` bump?
> 
> This script isn't included in any package so I don't think bumping `PKG_RELEASE` is necessary.

ack

**Pull request merged**
