### PR TITLE
libgpg-error: update to 1.46

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @flyn-org

### CODE REVIEW

**Comment by flyn-org** [comment]
Looks fine. Recommend merge. Thank you!

**Comment by hnyman** [comment]
@neheb 

Was there a reason to remove the Build/InstallDev steps?
Those were removed without any explanation in the commit message.

Now the libgcrypt compilation fails for me:

```
checking whether a -O flag munging is requested... yes
checking whether a instrumentation (-fprofile, -fsanitize) munging is requested... yes
checking whether to enable AMD64 as(1) feature detection... yes
checking for gpg-error-config... /Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/bin/gpg-error-config
checking for gpgrt-config... /Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/host/bin/gpgrt-config
./configure: line 14658: /Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/bin/gpg-error-config: No such file or directory
./configure: line 14670: test: : integer expression expected
./configure: line 14673: test: : integer expression expected
checking for GPG Error - version >= 1.27... no
configure: error: libgpg-error is needed.
                See ftp://ftp.gnupg.org/gcrypt/libgpg-error/ .
make[3]: *** [Makefile:75: /Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/libgcrypt-1.10.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
```

**Comment by neheb** [comment]
Yeah. They’re no longer present. There’s now a gpg-error binary, which does not seem to be a replacement for gpg-error-config

**Comment by neheb** [comment]
Maybe this is the upstream fix. Not sure: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=commit;h=12b3bc5a0d9c453d02ae229aadfee82808c10220

**Pull request merged**
