### PR TITLE
libmicrohttpd: Revert to Named no-ssl Version

### PR DESCRIPTION
**Pull request by bluewavenet**
Maintainer: Alexander Couzens lynxis@fe80.eu

Compile Tested: Snapshot SDK

Run Tested: target - ath79, hardware - gl-ar300m16, package - nodogsplash v3.2.1 and nodogsplash v3.3.1-beta, Openwrt Snapshot.

Description: Fix for issue #8180  - Any package with a dependency on the non-ssl version of libmicrohttpd ends up with the ssl version along with libgcrypt, libgnutls, .. This fix reverts the no-ssl version name from libmicrohttpd back to libmicrohttpd-no-ssl as it was in previous versions.
The two package names will now be libmicrohttpd-no-ssl and libmicrohttpd-ssl.

Signed-off-by: Rob White `<rob@blue-wave.net>`

### CODE REVIEW

**Comment by bluewavenet** [comment]
@hnyman @lynxis @mwarning @diizzyy @neheb

**Comment by neheb** [comment]
@lynxis is the maintainer.

**Comment by diizzyy** [comment]
Please use git push --force instead of opening a new PR
No objects however I'd rather see opkg being fixed.

**Comment by diizzyy** [comment]
Sorry, wrong button >_<

**Comment by bluewavenet** [comment]
@diizzyy 
I am limited to using github on my mobile for a day or two and need to get this fixed.
Have you ever tried doing a PR on an Android phone?  A frustrating experience :-D

**Comment by bluewavenet** [comment]
@hnyman 
The addition of the CONFLICTS lines creates a recursive dependency error, the two variants do conflict.
Am I not understanding something here?

**Comment by bluewavenet** [comment]
@hnyman @lynxis @mwarning @diizzyy @neheb
I think this is ready to go. Test built on SDK and works as it should.

**Comment by neheb** [comment]
ping @jow- 

From a quick glance the second commit should be enough, no?

**Comment by neheb** [comment]
got confirmation from IRC that this is OK. Hopefully nothing breaks.

**Comment by diizzyy** [comment]
At least name it consistently, all other packages are named nossl

**Comment by bluewavenet** [comment]
@diizzyy 
I would agree with you except it was originally no-ssl and still is in 18.06. Keeping it as no-ssl will at least make backporting without breaking things a lot easier. 

Thanks for everyone's help on this.

**Comment by cotequeiroz** [comment]
Apparently this is causing recursive dependencies when packages depend on libmicrohttpd.  The addition of `CONFLICTS` causes the addition of `depends on m || (PACKAGE_libmicrohttpd-no-ssl != y)` to `config PACKAGE_libmicrohttpd-ssl`.  That means `libmicrohttp-ssl` now depends on `libmicrohttd-no-ssl`.  When some other package selects plain `libmicrohttpd`, `select PACKAGE_libmicrohttpd-no-ssl if !PACKAGE_libmicrohttpd-ssl` gets added to that package's dependency.  That line means now thtat `libmicrohttp-no-ssl` depends on `libmicrohttp-ssl` and you have a recursive dependency.  Removing the `CONFLICTS` line will avoid this, as is done for example, for the `ustream-ssl` variants.

**Comment by bluewavenet** [comment]
@cotequeiroz 
I think we are maybe fighting bugs in opkg.
However I have tested this and as long as the dependent package names the version that it requires, it gets it. ie libmicrohttpd-ssl or libmicrohttpd-no-ssl.
If a dependent package calls a dependency only on libmicrohttpd, which one should it get?
Which packages are you aware of that have this problem?

**Comment by hnyman** [comment]
> Which packages are you aware of that have this problem?

https://github.com/openwrt/packages/search?q=libmicrohttpd&unscoped_q=libmicrohttpd

Seems to be 7 packages in this repo that depend on microhttpd. 
Two (motion, gnunet) specify the ssl version and should be ok
Five have an unspecified dependency:
netwhere, device-observatory, upmpdcli, czmq, ola

* Of those, at least device-observatory seems to be picky (#8068) and apparently wants the no-ssl version. There may also be packages in other repos, like in openwrt-routing which also seems to need no-ssl based on https://github.com/openwrt-routing/packages/pull/445 . As no-ssl is the default variant, both of those may already be happy with the current situation.

* netwhere and ola have older Makefiles from 2018, so they likely expect "libmicrohttpd" to mean the ssl version like before the version rename by @diizzyy in Jan 2019.

* not sure about upmpdcli, as @diizzyy has added the libmicrohttpd  dependency on the same timeframe as the libmicrohttpd variant rename was done

I have not tested any of the packages, but this was just determination by the Makefile histories and PRs.

**Comment by bluewavenet** [comment]
@hnyman 
nodogsplash was dependent on libmicrohttpd-no-ssl, then changed in January to libmicrohttpd, but this caused the full libmicrohttpd-ssl and its dependent gnutls packages to be installed. 
There is a PR for nogogsplash waiting to be merged that reverts to libmicrohttpd-no-ssl.

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/8047#issuecomment-458286910

**Comment by mwarning** [comment]
@hnyman device-observatory should not care about ssl or not.

**Comment by bluewavenet** [comment]
@diizzyy @hnyman @cotequeiroz 
After #8047, some packages requiring the no-ssl version may have had their makefile updated (nodogsplash did for example). These packages would have then had the -ssl version installed regardless (bug in opkg?).

It would be much cleaner to revert those packages now, rather than trying to work around the issue.

There is no ambiguity and it makes much more sense if packages actually specify which version they need, in my opinion anyway.

Removing the CONFLICTS line may well stop the recursive dependency error, but it does not fix the underlying problem of those packages not currently specifying the version required.

**Comment by hnyman** [comment]
Sure, the CONFLICTS thing is different thing that the ambiguity of some packages about the exact version they would need. 

But like mwarning says above, some packages also indifferent about the variant and should work with both. Then the user could select either variant.)

Recursive dependencies should be removed, so removing the CONFLICTS sounds ok to me.

**Comment by jow-** [comment]
If two packages / flavors / variants specify PROVIDES:=foo, then both are, by definition, able to satisfy a "foo" dependency. Starting to hardcode random variants in dependent packages not only makes no sense, it will also completely defy the purpose of PROVIDES and make packages mutually exclusive to each other (e.g. if pkgA depends on libX-nossl while pkgB depends on libX-ssl, then it becomes impossible to install pkgA and pkgB at the same time).

Apart from that, specifying `CONFLICTS` for flavors having the same `PROVIDES` is superfluous as the build system will take care of generating Kconfig that prevents concurrent `<*>` selection of both providers.

On the opkg metadata level, it is also not possible to install both providers at the same time.

**Comment by cotequeiroz** [comment]
This happens way before `opkg` enters the stage.  It blows up in `menuconfig`, where they are detected.  Its input file is generated by `package-metadata.pl`.  The opkg metadata is generated when the final ipk file is built.  I'm working on improving the buildsystem to handle at least some of (I should say say python) the recursive dependencies problems.  I have made some comments in #8535.

It seems we can't have two different names, have a `PROVIDES` and `CONFLICTS`, and be a dependency at the same time.  The result is as I explained earlier.

I've searched for examples:
- `hostapd` uses `PROVIDES` and `CONFLICTS`, but is not depended by anyone.

- `libffmpeg` (`-{full,audio-dec,mini,custom}`) uses `PROVIDES` and is a dependency, but does not use `CONFLICTS`.

- ucert uses `PROVIDES`, `CONFLICTS`, and is a dependency of `auc`.  This seems to be the best example.

I would like to mimic `ucert`, but we need to make sure the results are as expected.

**Comment by cotequeiroz** [comment]
One thing that may be of concern, since this is a library, is that `InstallDev` may be installing the version with ssl dependencies in `staging_dir`.  This would cause missing dependency problems.  I haven't checked what happens here.

**Comment by bluewavenet** [comment]
@jow- @hnyman @cotequeiroz @diizzyy et al
In summary, we remove the CONFLICTS?

**Comment by neheb** [comment]
I checked ucert. Adjusting libmicrohttpd that way seems to get rid of the warnings. No idea on opkg behavior.

**Comment by bluewavenet** [comment]
@neheb Sorry, missed you off the list :-)

**Comment by cotequeiroz** [comment]
If we want a quick fix, I'd either remove `CONFLICTS`.  Even though I'm looking into the build system, I'm in no way as familiar with it as @jow-, so if he says `CONFLICTS` are superfluous, we might as well follow.

I'm not too worried about opkg.  If it picks a bad variant, one can always uninstall, install the right variant first, then try again.

We must make sure we don't end up breaking dependent packages because `InstallDev` installs ssl-dependent libraries, and packages will fail to build because of missing dependencies to some `.so`.  I won't be able to test that today or tomorrow.  
I imagine that if you were to build only the ssl-version, then dependent packages will fail because `libgnutls`, for example, will not show up as a dependency of `libmicrohttpd`, but only of `libmicrohttpd-ssl`.  It means one must build the nossl version and use it in staging_dir even if it is not selected to be built.  I'm not sure the buildsystem does it this way.

**Comment by diizzyy** [comment]
All packages that depends on libmicrohttpd depends on (-nossl), at least that was the intention.

To summarize:
* You can't use ```PROVIDES``` for package B to provide package A if package A already exists under the same name.
* ```CONFLICTS`` doesn't resolve potential "race" conditions about dependencies

So from what I can tell what ```CONFLICTS``` does is outputting a warning before actually installs files that  A conflicts with already installed package B instead of failing to install because file XXX already exists? I assume that opkg will quit if it finds files that already exists during installation?

**Comment by cotequeiroz** [comment]
>     * You can't use `PROVIDES` for package B to provide package A if package A already exists under the same name.

Yes, you can.  `ucert` and `hostapd` do that.

> 
>     * ```CONFLICTS`` doesn't resolve potential "race" conditions about dependencies
> 
> 
> So from what I can tell what `CONFLICTS` does is outputting a warning before actually installs files that A conflicts with already installed package B instead of failing to install because file XXX already exists? I assume that opkg will quit if it finds files that already exists during installation?

`opkg` will fail to install a package that wants to overwrite another package's file.  I think `CONFLICTS` will not let it even try.

**Comment by diizzyy** [comment]
@cotequeiroz 
Well, that's the issue right now after my change. (See issue report)?

@cotequeiroz 
Yeah, it's just a safeguard as I don't think opkg can't revert halfway in?

**Comment by neheb** [comment]
I can open up my changes for discussion if you guys want.

**Comment by cotequeiroz** [comment]
@diizzyy I see your point about an `opkg` bug.  One can, however, circumvent it by installing `libmicrohttpd` first, or even that fails?

**Comment by jow-** [comment]
> Yes, you can. ucert and hostapd do that.

It is strongly discouraged though as existing opkg limitations make it impossible to actually choose the wanted provider at install time when one of the discrete providers shares the same name with the virtual provided package. Depending on feed availability, cli flags and the way packages are ordered during opkg install, the outcome is entirely undefined.

Usually you can force a specific provider of a virtual package by mentioning it at opkg install time, e.g. 
`opkg install pkgX-nossl pkgA` will force the installation of `pkgX-nossl` when `pkgA` depends on the virtual `pkgX`. This fails however when one of the providers is called `pkgX` as well.

**Comment by bluewavenet** [comment]
Clearly there are issues elsewhere.

But let's not loose track of the original issue here:
If the no-ssl version is named "libmicrohttpd" then a package with "libmicrohttpd" as a dependency actually gets "libmicrohttpd-ssl" installed.
This PR fixes this by naming the two variants "libmicrohttpd-no-ssl" and "libmicrohttpd-ssl" (the original names prior to #8047).

This works as long as packages declare their dependencies by using the correct variant name.
Both variants have PROVIDES = libmicrohttpd
This means that if EITHER is installed first the package dependencies will be satisfied.

eg nodogsplash has a dependency of libmicrohttpd-no-ssl, but if libmicrohttpd-ssl is installed first then the nodogsplash dependency is satisfied.

So removing the CONFLICTS here will let us move on with this at least.... ;-)

**Comment by diizzyy** [comment]
So either way we can't safeguard everything...
I'd prefer for not installing SSL-libs and friends by default so perhaps make packages that need ssl depend on -ssl and only link libmicrohttpd-nossl to libmicrohttpd?

**Comment by bluewavenet** [comment]
See PR #8739

**Pull request merged**
