### PR TITLE
simple-adblock: boot-up optimization

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin <stangri@melmac.net>

Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.4
Run tested: mvebu, WRT3200ACM, 18.06.4

Description: prevent multiple restarts on boot-up

### CODE REVIEW

**Comment by neheb** [comment]
Shellcheck throws several warnings. Including some bashisms:

Line 783:
                                if [ "$action" == "restart" ]; then
                                               ^-- SC2039: In POSIX sh, == in place of = is undefined.

I also see:

                        echo -e -n "Error: parsing '${1}'.\\n" >> "${jsonFile}.error"
                             ^-- SC2039: In POSIX sh, echo flags are undefined.

echo can be replaced with printf for -e and -n.

**Comment by stangri** [comment]
Rosen,

I have 2039 disabled, as OpenWrt default shell (ash) support everything I use.

However, I agree it's nice to be POSIX compliant. I can easily get rid of `==` and echo flags, can you recommend what should I do for string replacements (`${a/$b/$c}`)? I use them extensively (and they were used in a previous version too). Dash's `tr -s` doesn't work same way in ash.

**Comment by neheb** [comment]
It seems you deleted your comment. My answer is that I'd ignore string replacement warnings. busybox supports it.

**Comment by stangri** [comment]
> It seems you deleted your comment. My answer is that I'd ignore string replacement warnings. busybox supports it.

echo flags and `==` are also supported in busybox.

I think this should be merged as is, I'll remove echo flags and `==` in the next PR.

**Comment by neheb** [comment]
Fair enough.

**Pull request merged**
