### PR TITLE
ddns-scripts: mydns.ip to mydns.jp

### PR DESCRIPTION
**Pull request by AdorableJiang**
The provider is `mydns.jp` not `mydns.ip` which is wrong and misleading.

### CODE REVIEW

**Comment by jefferyto** [comment]
I think you should increment `PKG_RELEASE` instead of `PKG_VERSION`.

**Comment by AdorableJiang** [comment]
> I think you should increment `PKG_RELEASE` instead of `PKG_VERSION`.

Fixed.

**Comment by jefferyto** [comment]
Would it be possible to squash the commits?

**Comment by AdorableJiang** [comment]
I believe we are all set now.

**Review by jefferyto — APPROVED** [review]
Thanks!

**Pull request merged**
