### PR TITLE
perl: update version 5.40.0

### PR DESCRIPTION
**Pull request by esaaprillia**
Maintainer: @pprindeville @Naoir 

Compile tested: aarch64
Run tested: aarch64

Description:

https://metacpan.org/release/HAARG/perl-5.40.0

remove bytes_heavy.pl
https://github.com/Perl/perl5/pull/22047

perl update version 5.40.0

refresh patch

### CODE REVIEW

**Comment by pprindeville** [comment]
This is coredumping in a call to `mmap()` early on start:

```
root@OpenWrt:~# strace perl -V
execve("/usr/bin/perl", ["perl", "-V"], 0x7ffc303437f8 /* 16 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7fbd84a03b28) = 0
set_tid_address(0x7fbd84a03fa0)         = 29411
brk(NULL)                               = 0x1850000
brk(0x1852000)                          = 0x1852000
mmap(0x1850000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1850000
open("/usr/lib/perl5/5.40/CORE/libperl.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0555, st_size=11330640, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 3919872, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd845c6000
mmap(0x7fbd84611000, 1695744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x4b000) = 0x7fbd84611000
mmap(0x7fbd847af000, 1810432, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x1e9000) = 0x7fbd847af000
mmap(0x7fbd84969000, 106496, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x3a3000) = 0x7fbd84969000
mmap(0x7fbd8497d000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbd8497d000
close(3)                                = 0
open("/usr/lib/perl5/5.40/CORE/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld-musl-x86_64.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=99928, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 106496, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd845ac000
mmap(0x7fbd845b0000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x4000) = 0x7fbd845b0000
mmap(0x7fbd845c1000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x15000) = 0x7fbd845c1000
mmap(0x7fbd845c4000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x17000) = 0x7fbd845c4000
close(3)                                = 0
mprotect(0x7fbd84969000, 73728, PROT_READ) = 0
mprotect(0x7fbd84a00000, 4096, PROT_READ) = 0
mprotect(0x7fbd845c4000, 4096, PROT_READ) = 0
mprotect(0x403000, 4096, PROT_READ)     = 0
rt_sigaction(SIGFPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd849d0a93}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845ab000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845aa000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a9000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a5000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a4000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a3000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a1000
getuid()                                = 0
geteuid()                               = 0
getgid()                                = 0
getegid()                               = 0
open("/dev/urandom", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
read(3, "\211\245h\374", 4)             = 4
close(3)                                = 0
getuid()                                = 0
geteuid()                               = 0
getgid()                                = 0
getegid()                               = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd8459f000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd8459b000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd84597000
open("/dev/urandom", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "\327t\215\356", 4)             = 4
close(3)                                = 0
mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd8458e000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5c8} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by esaaprillia** [comment]
> This is coredumping in a call to `mmap()` early on start:
> 
> ```
> root@OpenWrt:~# strace perl -V
> execve("/usr/bin/perl", ["perl", "-V"], 0x7ffc303437f8 /* 16 vars */) = 0
> arch_prctl(ARCH_SET_FS, 0x7fbd84a03b28) = 0
> set_tid_address(0x7fbd84a03fa0)         = 29411
> brk(NULL)                               = 0x1850000
> brk(0x1852000)                          = 0x1852000
> mmap(0x1850000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1850000
> open("/usr/lib/perl5/5.40/CORE/libperl.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
> fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
> fstat(3, {st_mode=S_IFREG|0555, st_size=11330640, ...}) = 0
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
> mmap(NULL, 3919872, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd845c6000
> mmap(0x7fbd84611000, 1695744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x4b000) = 0x7fbd84611000
> mmap(0x7fbd847af000, 1810432, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x1e9000) = 0x7fbd847af000
> mmap(0x7fbd84969000, 106496, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x3a3000) = 0x7fbd84969000
> mmap(0x7fbd8497d000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbd8497d000
> close(3)                                = 0
> open("/usr/lib/perl5/5.40/CORE/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/etc/ld-musl-x86_64.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
> fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
> fstat(3, {st_mode=S_IFREG|0644, st_size=99928, ...}) = 0
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
> mmap(NULL, 106496, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbd845ac000
> mmap(0x7fbd845b0000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x4000) = 0x7fbd845b0000
> mmap(0x7fbd845c1000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x15000) = 0x7fbd845c1000
> mmap(0x7fbd845c4000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x17000) = 0x7fbd845c4000
> close(3)                                = 0
> mprotect(0x7fbd84969000, 73728, PROT_READ) = 0
> mprotect(0x7fbd84a00000, 4096, PROT_READ) = 0
> mprotect(0x7fbd845c4000, 4096, PROT_READ) = 0
> mprotect(0x403000, 4096, PROT_READ)     = 0
> rt_sigaction(SIGFPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fbd849d0a93}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845ab000
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845aa000
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a9000
> mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a5000
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a4000
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a3000
> mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a1000
> getuid()                                = 0
> geteuid()                               = 0
> getgid()                                = 0
> getegid()                               = 0
> open("/dev/urandom", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
> fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
> fcntl(3, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
> read(3, "\211\245h\374", 4)             = 4
> close(3)                                = 0
> getuid()                                = 0
> geteuid()                               = 0
> getgid()                                = 0
> getegid()                               = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd845a0000
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd8459f000
> mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd8459b000
> mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd84597000
> open("/dev/urandom", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
> fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
> read(3, "\327t\215\356", 4)             = 4
> close(3)                                = 0
> mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbd8458e000
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5c8} ---
> +++ killed by SIGSEGV +++
> Segmentation fault
> ```
> 
> This is on `HEAD` (`7bffb3f72b`) on `x86_64/generic`

are you getting this problem in perl-5.38.0/5.38.2 or is this problem in perl-5.40.0?

**Comment by pprindeville** [comment]
I reverted this commit, rebuilt, and things are working again.

**Comment by esaaprillia** [comment]
maybe we need to make changes in perl.

https://github.com/openwrt/packages/compare/master...egorenar:openwrt-packages:perl

**Comment by esaaprillia** [comment]
@pprindeville 
You didn't mention the version of Perl you are currently using.

**Comment by pprindeville** [comment]
> @pprindeville You didn't mention the version of Perl you are currently using.

Reverting put me at 5.38.2

**Comment by pprindeville** [comment]
> maybe we need to make changes in perl.
> 
> [master...egorenar:openwrt-packages:perl](https://github.com/openwrt/packages/compare/master...egorenar:openwrt-packages:perl)

Meaning what?

**Comment by esaaprillia** [comment]
> > maybe we need to make changes in perl.
> > [master...egorenar:openwrt-packages:perl](https://github.com/openwrt/packages/compare/master...egorenar:openwrt-packages:perl)
> 
> Meaning what?

https://github.com/openwrt/packages/issues/24512

**Comment by pprindeville** [comment]
> > > maybe we need to make changes in perl.
> > > [master...egorenar:openwrt-packages:perl](https://github.com/openwrt/packages/compare/master...egorenar:openwrt-packages:perl)
> > 
> > 
> > Meaning what?
> 
> #24512

Seems unrelated.

**Comment by esaaprillia** [comment]
@pprindeville 

```
root@OpenWrt:~# perl -v
This is perl 5, version 40, subversion 0 (v5.40.0) built for aarch64-linux-musl
Copyright 1987-2024, Larry Wall
Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.
Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.
root@OpenWrt:~# strace perl -V
-bash: strace: command not found
root@OpenWrt:~#
```

**Pull request merged**
