### PR TITLE
added some oldpackages

### PR DESCRIPTION
**Pull request by FireCulex**
wanted to use some oldpackages through github in my build. Peerguardian latest version plus cflag correction for musl.

### CODE REVIEW

**Comment by hnyman** [comment]
* You have not signed-off the commits.
* Additionally, the packages do not have a PKG_MAINTAINER. You need to declare yourself as the maintainer, if you want these packages to be added to the repo.
* Packages do not include PKG_LICENSE info.
* You should squash the two "fix" commits to the commits introducing the package. 

Read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by FireCulex** [comment]
It sounds complicated.

These were already in the oldpackages, I simply cut and paste and got some
of them to work with the trunk version and shared how I did it.

Good luck!

Matthew M. Dean
PGP: FDD7 B56E 9E07 5A9A 48EA 6254 DCAA 4E4D 3D73 55D5

**Comment by jow-** [comment]
But thats exactly what we don't want. No drive-by style code drops which end up being unmaintained the second they're committed. I'm closing this PR - feel free to redo another one id you intend to maintain one or more packages.

**Comment by FireCulex** [comment]
No worries, in the future I won't do further pull requests and utilize a
private repo. There is no motivation for me to becoming a maintainer, just
sounds like more work for me without incentive. My mistake.

Matthew M. Dean
PGP: FDD7 B56E 9E07 5A9A 48EA 6254 DCAA 4E4D 3D73 55D5

**Comment by karlp** [comment]
So, you're going to _maintain_ a private repo, but you don't want to maintain anything?

**Comment by FireCulex** [comment]
I only do it like once a year. It took me 5 minutes to go dev.openwrt.org
cut and paste some existing oldpackages I needed, maybe updated to the
latest version and verified they worked. Got denied for not doing it
"right" and accused of "drive by" coding.

Not interested.

Matthew M. Dean
PGP: FDD7 B56E 9E07 5A9A 48EA 6254 DCAA 4E4D 3D73 55D5

**Comment by jow-** [comment]
That is fine, no need to discuss this further.

**Pull request closed without merging**
