### PR TITLE
squashfs-tools: bump to version 4.4

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/d8bde3687a23742d1072be1a55f3b44ae29438ae
Run tested: x86 https://github.com/openwrt/openwrt/commit/d8bde3687a23742d1072be1a55f3b44ae29438ae

-------------------------------------------------

Also adds support for ZSTD compression:
  https://facebook.github.io/zstd/

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
CI failure seems to be:
```
Updating feed 'base' from 'https://github.com/openwrt/openwrt.git;master' ...
Cloning into './feeds/base'...
The authenticity of host 'github.com (140.82.114.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by hnyman** [comment]
I triggered a re-run, and CircleCI notices a hash error:
```
make[1]: Entering directory '/home/build/build_dir'
make[2]: Entering directory '/home/build/openwrt_packages/utils/squashfs-tools'
WARNING: PKG_MIRROR_HASH does not match squashfs-tools-4.4-52eb4c279cd283ed9802dd1ceb686560b22ffb67.tar.gz hash 0a40a9085e290807fe703e27a2a50bd849859b7085fc8a3327270fc1938cfff2
make[2]: Leaving directory '/home/build/openwrt_packages/utils/squashfs-tools'
time: package/feeds/packages/squashfs-tools/check#0.01#0.00#0.02
make[1]: Leaving directory '/home/build/build_dir'
=> Package HASH check failed

Exited with code exit status 1
```

**Comment by commodo** [comment]
> I triggered a re-run, and CircleCI notices a hash error:
> 
> ```
> make[1]: Entering directory '/home/build/build_dir'
> make[2]: Entering directory '/home/build/openwrt_packages/utils/squashfs-tools'
> WARNING: PKG_MIRROR_HASH does not match squashfs-tools-4.4-52eb4c279cd283ed9802dd1ceb686560b22ffb67.tar.gz hash 0a40a9085e290807fe703e27a2a50bd849859b7085fc8a3327270fc1938cfff2
> make[2]: Leaving directory '/home/build/openwrt_packages/utils/squashfs-tools'
> time: package/feeds/packages/squashfs-tools/check#0.01#0.00#0.02
> make[1]: Leaving directory '/home/build/build_dir'
> => Package HASH check failed
> 
> Exited with code exit status 1
> ```

i was afraid of that;
and i tried to pay attention to it;
not sure what i did wrong;
i am thinking maybe i'll switch this to tar-balls; i'll see about it

**Comment by commodo** [comment]
Changelog v1 -> v2:
* updated PKG_LICENSE  to `GPL-2.0-only`
* converted to tarball download from Github
* converted MAINTAINER -> PKG_MAINTAINER

**Pull request merged**
