### PR TITLE
smcroute: update to 2.5.4

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>

Maintainer: me
Compile tested: ath79/generic, OpenWrt master
Run tested: not tested

### CODE REVIEW

**Comment by alexeys85** [comment]
Starting from version 2.5.3 or may be earlier I noticed error in log:
`Failed enabling PIM IGMPMSG_WRONGVIF, ignoring: Protocol not available`
but everything works fine.

**Comment by alexeys85** [comment]
Fixed it by enabling PIMSM support in kernel.

**Comment by mwarning** [comment]
@alexeys85 thank you for testing. I wonder if it makes sense to enable PIMSM. But if everything works, then it should be fine.

**Comment by alexeys85** [comment]
Well, WRONGVIF messages allows to log multicast packets coming in on wrong VIF, not sure everyone needs this functionality.

**Comment by mwarning** [comment]
well, in that case let's get this merged.

**Comment by PolynomialDivision** [comment]
So I can merge?

**Comment by mwarning** [comment]
@PolynomialDivision lgtm

**Pull request merged**
