### PR TITLE
Sysrepo release 0.7.4

### PR DESCRIPTION
**Pull request by mamidzic**
Maintainer: @mislavn
Compile tested: Broadcom 27xx RPi2 32-bit / Broadcom 27xx RPi3 64-bit / x86_64 docker, openwrt master
Run tested: Broadcom 27xx RPi3 64-bit / x86_64 docker, openwrt master

Description:

Updated the Sysrepo/Netopeer2 packages with the latest release of Sysrepo, Libyang, Libnetconf2 and Netopeer2. The update was done because of the sysrepo relase 0.7.4. The release introduced changes listed here: https://github.com/sysrepo/sysrepo/releases

In libyang, an unnecessary patch was removed and Makefile updated to work with new dir structure

In netopeer2, also removed an unnecessary patch and updated the cmake-build patch to work with the changes. Updated the 'netopeer2-server.default' file to install newly required modules.

In sysrepo package, updated the 'libsysrepo.default' file to install newly required modules and enable newly required features

### CODE REVIEW

**Comment by diizzyy** [comment]
Is it possible to use codeload instead?
https://github.com/openwrt/packages/blob/83c2603c1db8125a4be6dfc66528a2e4db4e30dd/sound/fdk-aac/Makefile#L15

**Comment by mislavn** [comment]
Hi @diizzyy 

some of the packages don't use git tag's, so is it an issue if we use `PKG_SOURCE_VERSION` with codeload?

**Comment by diizzyy** [comment]
Not directly but you can also refer to commits
https://github.com/openwrt/packages/pull/6010/files#diff-93a681dc930689e08c33cee51a9aad1bR17

**Comment by mislavn** [comment]
In that case we would like to merge this pull request as it is and talk to the project owners of the packages and persuade them into using git tag's for the next release.

**Pull request merged**
