### PR TITLE
perl: version modules and non-base packages

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me / @Naoir 
Compile tested: x86_64, generic, HEAD (5f5d812)
Run tested: same

Built `perl`, `perl-cgi`, `perl-html-tagset`, `perl-html-parser`, `perl-text-csv_xs`, and `perl-xml-parser`.  Copied to production machine, and force reinstalled.

Reran `iptgeoip` scripts.  Validated iptables after running `/etc/firewall.user` script which made heavy use of geoip tables (built and managed with Perl).

Description:

### CODE REVIEW

**Comment by pprindeville** [comment]
@champtar Can you please have a look at https://travis-ci.org/openwrt/packages/builds/415611173?utm_source=github_status&utm_medium=notification?

**Comment by hnyman** [comment]
No objections from me. 
Looks perl packages specific things, and if this solves the problem of tirggering needed subpackages, then great.  (The only similar thing is maybe the python/python3 universe of packages here.)

**Comment by pprindeville** [comment]
@hnyman Can you mark the review approved, please?

**Comment by pprindeville** [comment]
Cherry-picked to 18.06.

**Comment by tofurky** [comment]
hi @pprindeville ,
i use a few out-of-tree perl modules in a local package feed. with the newly added relative `include ../perl/perlver.mk` i get an error when doing various operations on my feed:
```
...
Collecting package info: done
Collecting target info: done
Updating feed 'aquos' from '/home/matt/devel/openwrt/aquos' ...
Create index file './feeds/aquos.index' 
ERROR: please fix feeds/aquos/lang/perl-io-multiplex/Makefile - see logs/feeds/aquos/lang/perl-io-multiplex/dump.txt for details
ERROR: please fix feeds/aquos/lang/perl-net-cidr/Makefile - see logs/feeds/aquos/lang/perl-net-cidr/dump.txt for details
ERROR: please fix feeds/aquos/lang/perl-net-dns/Makefile - see logs/feeds/aquos/lang/perl-net-dns/dump.txt for details
ERROR: please fix feeds/aquos/lang/perl-net-ip/Makefile - see logs/feeds/aquos/lang/perl-net-ip/dump.txt for details
ERROR: please fix feeds/aquos/lang/perl-net-server/Makefile - see logs/feeds/aquos/lang/perl-net-server/dump.txt for details
Collecting package info: done
Collecting target info: done
...
```
the dump.txt files show that it is not finding perlver.mk:
```
/home/matt/devel/openwrt/openwrt/feeds/packages/lang/perl/perlmod.mk:4: ../perl/perlver.mk: No such file or directory

Package: perl-io-multiplex
Submenu: Perl
Version: 1.13+perl-1
Depends: +libc +GCC_LIBSSP:libssp +USE_GLIBC:librt +USE_GLIBC:libpthread +perl +perlbase-essential +perlbase-io
Conflicts: 
Menu-Depends: 
Provides: 
Section: lang
Category: Languages
Repository: aquos
Title: Manage IO on many file handles
Maintainer: matt <matt@aquos.lan>
Source: IO-Multiplex-1.13.tar.gz
License: GPLv1+ 
Type: ipkg
Description: Manage IO on many file handles
http://search.cpan.org/~markov/IO-Multiplex-1.13/lib/IO/Multiplex.pm
matt <matt@aquos.lan>
@@

gmake[2]: *** No rule to make target '../perl/perlver.mk'.  Stop.
```

taking an example from packages/lang/golang/*.mk, the following quick patch seems to fix it:

```
diff --git a/lang/perl/perlmod.mk b/lang/perl/perlmod.mk
index d00a8c4..8a95099 100644
--- a/lang/perl/perlmod.mk
+++ b/lang/perl/perlmod.mk
@@ -1,7 +1,11 @@
 # This makefile simplifies perl module builds.
 #
 
-include ../perl/perlver.mk
+ifeq ($(origin PERL_INCLUDE_DIR),undefined)
+  PERL_INCLUDE_DIR:=$(dir $(lastword $(MAKEFILE_LIST)))
+endif
+
+include $(PERL_INCLUDE_DIR)/perlver.mk
 
 ifneq ($(PKG_NAME),perl)

```

do you think that works? maybe the other instances of include should be replaced with `include $(PERL_INCLUDE_PATH)/example_include.mk` too.

thanks for helping to maintain this! if you want, i can open a separate issue for this.

**Comment by pprindeville** [comment]
See this [thread](
https://github.com/openwrt/packages/pull/6767#issuecomment-413630978) and make your case to @jow-.

**Pull request merged**
