### PR TITLE
python-service-identity: new package

### PR DESCRIPTION
**Pull request by jefferyto**
From the README:

service_identity aspires to give you all the tools you need for
verifying whether a certificate is valid for the intended purposes.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
This depends on python-attrs (#2517) and python-pyasn1-modules (#2039).

(An earlier version of this package (14.0.0) depended on python-characteristic (#2037) instead of python-attrs.)

**Comment by yousong** [comment]
Looks like this does not compile at the moment, can you have a look please.
```
Traceback (most recent call last):
  File "./setup.py", line 335, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/setuptools/dist.py", line 271, in __init__
    _Distribution.__init__(self,attrs)
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/setuptools/dist.py", line 326, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 161, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
    exec(code, glob, glob)
  File "src/_cffi_src/build_openssl.py", line 86, in <module>
    extra_link_args=extra_link_args(compiler_type()),
  File "./src/_cffi_src/utils.py", line 64, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "./src/_cffi_src/utils.py", line 72, in build_ffi
    ffi = FFI()
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
make[2]: *** [/home/yousong/git-repo/trunk-openwrt/build_dir/target-mips_24kc_musl-1.1.14/cryptography-1.3.1/.built] Error 1
make[2]: Leaving directory `/home/yousong/git-repo/trunk-openwrt/feeds/packages/lang/python-cryptography'
make[1]: *** [package/feeds/packages/python-cryptography/compile] Error 2
make[1]: Leaving directory `/home/yousong/git-repo/trunk-openwrt'
Build failed - please re-run with -j1 to see the real error message
make: *** [package/python-service-identity/compile] Error 1
```

**Comment by jefferyto** [comment]
That looks like an error that #2489 fixed (or at least should have). But even if you do a dirclean then rebuild, libffi currently fails to build for (some, if not all) mips targets (#2511). I've switch to x86 for now.

**Comment by yousong** [comment]
From the following content I guess it libffi was built without error with malta (mips_24kc)

```
➜  ~/git-repo/trunk-openwrt git:(master) find staging_dir/target-mips_24kc_musl-1.1.14/ -name 'libffi.so*'
staging_dir/target-mips_24kc_musl-1.1.14/root-malta/usr/lib/libffi.so.6
staging_dir/target-mips_24kc_musl-1.1.14/root-malta/usr/lib/libffi.so.6.0.1
staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/libffi.so
staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/libffi.so.6
staging_dir/target-mips_24kc_musl-1.1.14/usr/lib/libffi.so.6.0.1
staging_dir/target-mips_24kc_musl-1.1.14/host/lib/libffi.so
staging_dir/target-mips_24kc_musl-1.1.14/host/lib/libffi.so.6
staging_dir/target-mips_24kc_musl-1.1.14/host/lib/libffi.so.6.0.1
```

**Comment by jefferyto** [comment]
Will try building for malta.

**Comment by yousong** [comment]
```
CONFIG_TARGET_malta=y
CONFIG_TARGET_malta_be=y
CONFIG_TARGET_malta_be_Default=y

CONFIG_PACKAGE_python-service-identity=y
```
should be enough for this case.

```
make defconfig
make package/python-service-identity/compile V=s -j32
```

**Comment by yousong** [comment]
Looks like we also need to use `RPATH` mechanism when building host python.  `_cffi_backend.so` depended on `libffi.so.6` which the loader had no clue.

```
➜  ~/git-repo/trunk-openwrt git:(master) /home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/host/bin/python2.7  -c 'from cffi import FFI; FFI()'                                                                                Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/host/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
➜  ~/git-repo/trunk-openwrt git:(master) LD_LIBRARY_PATH=/home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/host/lib/ /home/yousong/git-repo/trunk-openwrt/staging_dir/target-mips_24kc_musl-1.1.14/host/bin/python2.7  -c 'from cffi import FFI; FFI()'
➜  ~/git-repo/trunk-openwrt git:(master)
```

**Comment by jefferyto** [comment]
Already done (11d1b213) :smile:

Can you try rebuilding after a `make clean`? I've rebuilt for malta and it works for me.

**Comment by yousong** [comment]
Yes, it compiles now.  Thank you.  btw.  I had to `rm -rf build_dir/target-xxx/host` because `make clean` alone does not trigger the rebuild of host packages.

**Comment by jefferyto** [comment]
Hmm, my `make clean` wipes out the whole of `build_dir/target-xxx` for the current target... Maybe something is off with my buildroot.

Thanks for taking the time to review all of these Python packages. I can't imagine a more boring task :laughing:

**Pull request merged**
