### PR TITLE
slrn: Add package

### PR DESCRIPTION
**Pull request by nikil**
Maintainer: me
Compile tested: ar71xx, x86_64
Run tested: x86_64

Description: threaded text-mode news reader

This requires #3587 and #3588 to be merged.

Signed-off-by: Nikil Mehta <nikil.mehta@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
I think this application has too much of a niche usage, the only application (or similar to it) that uses usenet and may have some sort of larger audience is couchpotato however no really the same usage... ;-)

**Comment by rotoroute** [comment]
@diizzyy No, this not niche usage.  Is like mutt for usenet.  For reading text, not download binaries.

Very popular softwares, almost all distribution have it.  Please merge?

**Comment by diizzyy** [comment]
It is, and we have limited resources too :-/

**Comment by diizzyy** [comment]
@thess @hnyman 
Close as not accepted?

**Comment by thess** [comment]
Old PR being closed for lack of interest.

**Comment by karlp** [comment]
was there anythign _wrong_ with it?  other than having dependencies that were nicely put in another PR?

Presumably they're jsut carrying it locally and trusting that we'll dig the pile of PRs eventaully.  The PR as is looks perfectly fine.

**Comment by thess** [comment]
I closed it due to its age. Feel free to pick this up and merge it + dependencies if you want. No objections from me. Something over 2yrs old with no apparent interest should be at least re-submitted to pick up latest CI test builds.

**Comment by karlp** [comment]
Indeed, there's nothing obviously wrong with them, but theyneed the submitter to come back again for sure, I'm not merging them as is either :)

**Pull request closed without merging**
