### PR TITLE
perl: don't build in parallel

### LINKED ISSUE #8238: perl: spurious build failures on openwrt-18.06 branch
Maintainer: @pprindeville
Environment: 
- Build Host: Debian 9.8 (x86_64)
- Build Target: brcm2708-bcm2710, mpc85xx-generic
- OpenWrt https://github.com/openwrt/openwrt/commit/62feabecd8a84cfe0d6a5aa3bad2720dbf328370
- packages.git https://github.com/openwrt/packages/commit/d05b98c6c86da58db5cbda3c945007be09583609

Description:
I'm regularly building OpenWrt 18.06 through the Gluon mesh framework. Building Perl spuriously fails every once in a while. I managed to capture a build log this time.

brcm2708-bcm2710: https://gist.github.com/mweinelt/50691b00d47dd1cb6107d1c183182f02
mpc85xx-generic: https://gist.github.com/mweinelt/1925156fbca42559f5dae24c7c1dc234

### PR DESCRIPTION
**Pull request by mweinelt**
Parallel builds cause spurious build failures with high core counts.

Closes: #8238
Signed-off-by: Martin Weinelt <hexa@darmstadt.ccc.de>

Maintainer: @pprindeville 
Compile tested: (put here arch, model, OpenWrt version) multiple (18.06, 19.07, 21.02)
Run tested: (put here arch, model, OpenWrt version, tests done) multiple (18.06, 19.07, 21.02)

I have been using this patchset for >1y.

Description: Fixes #8238

### CODE REVIEW

**Review by pprindeville — CHANGES_REQUESTED** [review]
You'd need to change the `PKG_RELEASE` as well.

**Comment by mweinelt** [comment]
Bumped release to 6.

**Comment by mweinelt** [comment]
Rebased.

**Comment by mweinelt** [comment]
Not sure how the test failures are related.

**Comment by pprindeville** [comment]
> Parallel builds cause spurious build failures with high core counts.

@mweinelt By the way, what constitutes "high core counts"?  Because I have an 6-core VM that I routinely build on, and I've never seen this...

**Comment by mweinelt** [comment]
My build host has 32C/64T.

**Comment by blocktrron** [comment]
@pprindeville As I'm also facing this from time to time - any objections against merging?

**Comment by pprindeville** [comment]
I'd rather reduce the parallelism that set it to one.

What about capping the number of jobs?

**Comment by karlp** [comment]
Has anyone tried following this up with perl upstream? it seems like something they'd want to be fixing too?

**Comment by pprindeville** [comment]
> Has anyone tried following this up with perl upstream? it seems like something they'd want to be fixing too?

Indeed.

**Comment by lemoer** [comment]
What is the state here? Is there anything going to happen?

**Comment by pprindeville** [comment]
> What is the state here? Is there anything going to happen?

Wanting to know what's been communicated upstream.

Also, please investigate the build failures.

**Comment by Rondom** [comment]
I have investigated the failure and came up with the following: #23602

**Comment by mweinelt** [comment]
Superseded by #23602.

**Comment by pprindeville** [comment]
Sorry for the delay. Been busy with satellite stuff.

**Pull request closed without merging**
