### PR TITLE
gerbera: update to 1.5.0

### PR DESCRIPTION
**Pull request by neheb**
This is a fairly massive update that adds new dependencies.

Switched the CMAKE_OPTIONS to use ON/OFF as is done elsewhere.

Added a patch fixing compilation with libiconv-stub/full.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody
Compile tested: arc700

### CODE REVIEW

**Comment by neheb** [comment]
Just remembered, this needs libupnp 12.1 as well...

I'll combine the PRs.

**Comment by neheb** [comment]
Just tried this on a CentOS7 VM. Seems I need to use GCC9 to compile this...

**Comment by neheb** [comment]
This cannot be compiled with GCC7 and hence cannot be backported to 19.07. Not unless hackery is used to change all instances/usage of std::filesystem to std::experimental::filesystem. @BKPepe

**Comment by neheb** [comment]
Ran tested on malta. Seems to run.

Added a debug option to log to syslog.

**Comment by neheb** [comment]
libupnp 12.1 compiles with mpd and u2pnpd (the other depending packages). This is ready to go.

**Comment by BKPepe** [comment]
> This cannot be compiled with GCC7 and hence cannot be backported to 19.07. Not unless hackery is used to change all instances/usage of std::filesystem to std::experimental::filesystem. @BKPepe

Thanks for letting me know about that. I will cherry-pick the version 1.4.0 to OpenWrt 19.07 and this one I will let on you, if you want to backport it or not and fix the issues, which you found.
I think that gerbera can be a good alternative to minidlna and would be bad to wait for this package to OpenWrt 20.xx as minidlna is not working properly for someone.

**Comment by neheb** [comment]
It would be better to let upstream know that GCC7 support is desired. Well, I don't think they care TBH. I'm sure they'll move to C++20 once everything is finalized with GCC. They move quite fast...

Having said that, GCC8 is available with 19.07. Since you guys run your own buildbot, you could backport it there are turn on GCC8. It seems 19.07 is using an older version of GCC8. Might want to backport the update.

My feeling regarding minidlna is that musl's implementation of some functions breaks minidlna and causes crashing. If so, the real problem is in mindlna relying on broken glibc behavior. I don't care enough for minidlna given how inactive upstream is.

I had a talk with @jow- on IRC about minidlna. The huge size of gerbera and the lack of a luci app makes it unsuitable as a replacement on certain devices.

I will also note that pugixml and spdlog are built as shared libraries, which is not default. I think I should switch them to be static. LTO will help slim them down further...

**Comment by BKPepe** [comment]
@neheb: These details are useful. Thanks for your reply!

**Pull request merged**
