### PR TITLE
python3-flask: update to version 1.0.3

### PR DESCRIPTION
**Pull request by ja-pa**
Maintainer: @dangowrt 
Compile tested: Turris Omnia (TOS4), OpenWrt master
Run tested: Turris Omnia (TOS4), OpenWrt master

Description:
Update Flask to version 1.0.3  Part of update is also small Makefile cleanup.

Tested with Hello world example http://flask.pocoo.org/docs/1.0/quickstart/

Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>

### CODE REVIEW

**Comment by BKPepe** [comment]
@ja-pa: Thanks for doing the suggested changes which I wanted. Now it looks even better.
When the build is pass, I will merge it.

**Comment by BKPepe** [comment]
@dangowrt any objections?

**Comment by dangowrt** [comment]
@ja-pa Would you like to take over maintainership for this package?

**Comment by ja-pa** [comment]
@dangowrt Ok, I'm using it so it's no problem. Should I add myself as another maintainer or do you want to get rid of maintainership entirely?

**Pull request merged**
