### PR TITLE
perl: update to version 5.38.0

### PR DESCRIPTION
**Pull request by predators46**
Maintainer: @Naoir @pprindeville
Compile tested: armsr, riscv64
Run tested: armv8

removed some sources to download perl. I believe I only need one source to download perl at https://www.cpan.org/src/5.0. I see some Linux distributions use that source to download.
change the position of PKG_MAINTAINER to make it neater and prettier

perform a patch refresh
removes some patches that have been applied in perl-5.38.0 as well as patches that are no longer used in perl-5.38.0

added one patch https://github.com/Perl/perl5/commit/ba6e2c38aafc23cf114f3ba0d0ff3baead34328b this fixes the issue ```regcomp*.c, regexec.c - fixup regex engine build under -Uusedl```

provided updates and synchronized libc.config base.config version.config to perl-5.38.0
removed deprecated arybase in perl-5.29.4

### CODE REVIEW

**Comment by predators46** [comment]
sorry if I do a pull request and I close it again, that's all I do so that Perl builds successfully. hope this works to update perl

**Review by BKPepe — CHANGES_REQUESTED** [review]
So many changes e.g. removed so many sources to download perl and it is not mentioned in the commit description. It says usual update, which is not true, though. :) There are many changes.

**Review by esaaprillia — APPROVED** [review]

**Review by predators46 — COMMENTED** [review]
removed some sources to download perl. I believe I only need one source to download perl at https://www.cpan.org/src/5.0. I see some Linux distributions use that source to download.
change the position of PKG_MAINTAINER to make it neater and prettier

perform a patch refresh
removes some patches that have been applied in perl-5.38.0 as well as patches that are no longer used in perl-5.38.0

added one patch https://github.com/Perl/perl5/commit/ba6e2c38aafc23cf114f3ba0d0ff3baead34328b this fixes the issue ```regcomp*.c, regexec.c - fixup regex engine build under -Uusedl```

provided updates and synchronized libc.config base.config version.config to perl-5.38.0
removed deprecated arybase in perl-5.29.4

**Comment by BKPepe** [comment]
You need to copy&paste it to commit description. It is still blank.

**Pull request merged**
