### PR TITLE
https-dns-proxy: support for force DNS/DNS hijacking

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: me
Compile tested: ramips, er-x, 19.07.6
Run tested:  ramips, er-x, 19.07.6, start/stop/dns hijack

Description: This introduces support for DNS Hijacking. 

Signed-off-by: Stan Grishin <stangri@melmac.net>

PS. Please grant merge rights.

### CODE REVIEW

**Comment by 1715173329** [comment]
However, in my option, both hijacking and force hijacking shouldn't be enabled by default.

**Comment by stangri** [comment]
> However, in my option, both hijacking and force hijacking shouldn't be enabled by default.

Could you please clarify what do you mean by "both hijacking and force hijacking"? 

I saw a post on the forum recently where someone had to manually configure DNS hijacking after installing the https-dns-proxy and the luci app and realized that this package lacks the force dns feature. My thinking is that if people are running DoH proxy on their router, they would probably want to route all DNS requests thru it, hence force DNS being enabled by default.

**Comment by 1715173329** [comment]
> Could you please clarify what do you mean by "both hijacking and force hijacking"?

Apologize, I didn't look at them carefully.
Hijacking I meant, is updating dnsmasq config (upstream servers).
And, in my option, could it be better if we move the firewall settings to dnsmasq? This would be useful.

> I saw a post on the forum recently where someone had to manually configure DNS hijacking

Okay, but not all users wanna this. Could we just make it optional, and disable it by default? Then if someone needs this, they could enable it themself.

Also, in the init:
```bash
config_get dnsmasqConfig	'config' 'update_dnsmasq_config' '*'
```
This means hijacking cannot be disabled, though someone make it as none but it still means all.

**Comment by stangri** [comment]
> Hijacking I meant, is updating dnsmasq config (upstream servers).
It's been like that for quite some time, I don't think changing the default behaviour now would be practical. 

> And, in my option, could it be better if we move the firewall settings to dnsmasq? This would be useful.
Please elaborate. Do you suggest making DNS hijacking PROCD firewall setup a part of the dnsmasq init-script and exposing this setting in luci?

> Okay, but not all users wanna this. Could we just make it optional, and disable it by default? Then if someone needs this, they could enable it themself.
If users largly have no problem with dnsmasq auto-update, what's the argument for making dns hijacking disabled by default? I strongly believe that people setting up DoH proxy on their router wish to have DNS requests from all their devices processed by DoH proxy, hence the defaults I'm suggesting. Can you quantify "not all users wanna this" to change my mind?

> Also, in the init:
> 
> ```shell
> config_get dnsmasqConfig	'config' 'update_dnsmasq_config' '*'
> ```
> 
> This means hijacking cannot be disabled, though someone make it as none but it still means all.

It's covered in README and the luci-app handles it properly, to disable it you need to set value to `'-'`.

**Comment by 1715173329** [comment]
> Do you suggest making DNS hijacking PROCD firewall setup a part of the dnsmasq init-script and exposing this setting in luci?

Yes, but PROCD is not forced.

**Comment by stangri** [comment]
> > Do you suggest making DNS hijacking PROCD firewall setup a part of the dnsmasq init-script and exposing this setting in luci?
> 
> Yes, but PROCD is not forced.

Before I subimtted this PR, I've tested two different packages having this same PROCD firewall data and there was no issue with that. If at some point, dnsmasq has the same implemented, it will not affect this package. I do agree it's a great idea to have dns hijacking implemented in openwrt's dnsmasq packages tho. I also agree that if it's implemented in dnsmasq itself, it should be disabled by default. In this package, I believe it should be enabled by default.

**Comment by 1715173329** [comment]
> If at some point, dnsmasq has the same DNS hijacking functionality implemented, it should not affect this package. I do agree it's a great idea to have DNS hijacking implemented in openwrt's dnsmasq packages tho. I also agree that if it's implemented in dnsmasq itself, it should be disabled by default. In this package, I believe it should be enabled by default.

However, it's up to you, but it would be great if we have this function in DNSMasq.

**Comment by stangri** [comment]
> > If at some point, dnsmasq has the same DNS hijacking functionality implemented, it should not affect this package. I do agree it's a great idea to have DNS hijacking implemented in openwrt's dnsmasq packages tho. I also agree that if it's implemented in dnsmasq itself, it should be disabled by default. In this package, I believe it should be enabled by default.
> 
> However, it's up to you, but it would be great if we have this function in DNSMasq.

Sure, I can also have a look at implementing the same in DNSMASQ. This can be merged then?

**Comment by 1715173329** [comment]
> Sure, I can also have a look at implementing the same in DNSMASQ.

Great, thanks so much!

> This can be merged then?

Ping @neheb.

**Comment by stangri** [comment]
@neheb, could you please cherry-pick this for 21.02? Or should I send a separate PR?

**Comment by neheb** [comment]
Send a PR. I can't spend time on the packages feed until I rebuild my NAS...

**Comment by stangri** [comment]
> Now all requests are intercepted. What for?

To force router's (encrypted) resolution on LAN.

**Pull request merged**
