### PR TITLE
python3-asgiref: update to version 3.3.0

### PR DESCRIPTION
**Pull request by peter-stadler**
Maintainer: me
Compile tested: x86_64, x86_64 qemu, master
Run tested: x86_64, x86_64 qemu, master, run etesync-server

Description: update to newest version

### CODE REVIEW

**Comment by BKPepe** [comment]
I miss here a link for changelog. Update to newest version is not helpful.

**Comment by peter-stadler** [comment]
I see: https://github.com/django/asgiref/blob/master/CHANGELOG.txt

**Comment by peter-stadler** [comment]
Do you know why the tests are failing (I cannot get their log): Should I change something or is this a known problem?

**Comment by BKPepe** [comment]
This fails for almost any PRs. It should be an issue with SDK. Hopefully, it will get sorted out soon.

More details: https://github.com/openwrt/packages/pull/13703#issuecomment-711341236

**Comment by peter-stadler** [comment]
Thank you for explaining.

**Pull request merged**
