### PR TITLE
boost: fix compilation error under SPARC

### PR DESCRIPTION
**Pull request by neheb**
Missing braces.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ClaymorePT 
Compile tested: SPARC

### CODE REVIEW

**Comment by neheb** [comment]
No idea where this is to be upstreamed. boost has a lot of git repos.

**Comment by ClaymorePT** [comment]
@neheb [Boost.Predef  library](https://github.com/boostorg/predef/)

**Comment by ClaymorePT** [comment]
Btw @neheb this issue was already fixed upstream -> https://github.com/boostorg/predef/pull/118

**Comment by ClaymorePT** [comment]
And I'm okay with this change, btw :) Go ahead and merge it.

**Comment by neheb** [comment]
Cool. It can be removed later.

**Pull request merged**
