### PR TITLE
unbound: update to 1.5.10

### PR DESCRIPTION
**Pull request by Borromini**
Maintainer: @hansmi 

Compile tested: ar71xx and x86/64
Run tested: not yet but trivial update.

Description: This updates unbound to 1.5.10; adjusts the config patch as well.

Signed-off-by: Stijn Segers <francesco.borromini@inventati.org>

### CODE REVIEW

**Comment by EricLuehrsen** [comment]
@Borromini - Upstream publishes SHA256, and perhaps this release we should also switch to PKG_SHA256SUM macro (vs. MD5).

@hansmi - I have been running 1.5.10 on my own router. It compiles and runs for C.C. (ar71xx) with no obvious signs of trouble.

**Comment by hansmi** [comment]
@EricLuehrsen Last time I checked the OpenWrt build system only supported MD5. That may have changed, though. Please put the change to SHA256 into a separate change, however.

@Borromini The configuration changes definitely change behaviour (binding against any interface vs. only localhost; limiting `outgoing-range`) and are largely unrelated to the version bump. Please note that I've submitted a separate pull request (#3348) to change the package maintainer to @EricLuehrsen.

**Comment by EricLuehrsen** [comment]
When I look at the patch between "example.conf" and "unbound.conf," I only see the differences based on the upstream "example.conf" but no _material_ changes to installed "unbound.conf." Do I see this with the wrong perspective?

**Comment by Borromini** [comment]
@EricLuehrsen my build failed on the example config patch so that's what I updated.  I assume you already had some patches lined up yourself? If those are more complete, I can close my PR. Let me know.

As for switching to SHA*, I think we can safely switch to SHA1 or SHA256, both OpenWrt and LEDE should support other checksums than MD5 in the Makefile now. And the Unbound project provides both SHA* checksums by default.

**Comment by EricLuehrsen** [comment]
@borromini. okay. I checked it and the github history appears correct. Please just confirm that your only change was out of tree rebase to "example.conf.in 1.5.10" and you didnt sneak in material changes.

I am working on a different patch for "example.conf.in" to reduce this problem in the future, but it needs to be a seperate change following this.

SHA is not part of script "download.pl" during "package/[package]/download" target yet as best as I can see.

**Comment by Borromini** [comment]
@EricLuehrsen yes indeed that's all I changed. However, as hansmi pointed out, maybe we should change the default config if upstream does so too?

As for the checksums: if memory serves me right, you could just use the SHA1SUM or SHA256SUM in the  `pkg_md5sum` value, and the buildroot would figure out the type of hash itself. But I cannot test that at the moment. I do recall an instance where I tried building a package from trunk on CC and the `pkg_md5sum` looked weird and turned out to be sha256 or something else (definitely not md5).

**Comment by zorun** [comment]
You can simple use a SHA256 checksum in `PKG_MD5SUM`, see https://wiki.openwrt.org/doc/devel/packages?s[]=sha256#buildpackage_variables

**Comment by Borromini** [comment]
Thanks zorun. @EricLuehrsen - please don't merge this yet, it still breaks on some whitespacing mess. I'm looking into what went wrong...

**Comment by Borromini** [comment]
OK. There is a tab left on line 174 in the upstream file, and that's breaking things. I tried to fix that, but I'm stuck...

Patch is here:

<script src="https://gist.github.com/Borromini/13f1006400739b4ec8f11a20fe9b21ec.js"></script>

**Comment by hansmi** [comment]
@Borromini You're definitely changing the configuration installed into `/etc/unbound` to bind against `0.0.0.0` (see `001-conf.patch`). This is not a change coming from upstream because your commit makes the changes.

**Comment by Borromini** [comment]
@hansmi - I am not doing anything of the sort. What my pull request does is bump to 1.5.10 and adjust the already existing `0001-conf.patch`. Binding against `0.0.0.0` is already there in the 1.5.9 package.

**Comment by hansmi** [comment]
@Borromini I'm very sorry. I got confused by GitHub's highlighting for patches in commits. :-(

**Comment by hnyman** [comment]
@EricLuehrsen 
Is this ok to merge, then?

**Comment by EricLuehrsen** [comment]
@Borromini. I dont see the white space issue myself. This pull seems ok. Please confirm resolution.

**Comment by Borromini** [comment]
@EricLuehrsen If you could test package compilation with the patch applied, that would be great, but for me it breaks at compile time. I'm at work atm and unable to test now.

Out of tree compilation is `make package/unbound/clean && make package/unbound/compile V=s` (just reiterating in case).

**Comment by hnyman** [comment]
I got bored and tested it ;-) 
It breaks in the prepare step (applying the patch from our repo). Apparently the existing patch 001-conf.patch needs further changes.
```
perus@u1610:/Openwrt/lede$ make package/unbound/prepare V=s
make[1]: Entering directory '/Openwrt/lede'
...
Applying ./patches/001-conf.patch using plaintext: 
patching file doc/example.conf.in
Hunk #6 FAILED at 179.
1 out of 10 hunks FAILED -- saving rejects to file doc/example.conf.in.rej
```
Failing part:
```
perus@u1610:/Openwrt/lede$ cat build_dir/target-mips_24kc_musl-1.1.15/unbound-1.5.10/doc/example.conf.in.rej 
--- doc/example.conf.in
+++ doc/example.conf.in
@@ -179,9 +190,11 @@ server:
 	# the number of slabs must be a power of 2.
 	# more slabs reduce lock contention, but fragment memory usage.
 	# infra-cache-slabs: 4
+	infra-cache-slabs: 1
 
 	# the maximum number of hosts that are cached (roundtrip, EDNS, lame).
 	# infra-cache-numhosts: 10000
+	infra-cache-numhosts: 200
 
 	# define a number of tags here, use with local-zone, access-control.
 	# repeat the define-tag statement to add additional tags.
```
But you are right, there is something strange. It looks like a tab is now needed for the "empty" line after the added ``` infra-cache-numhosts: 200 ``` line. Possibly the file has been changed upstream between 1.5.9 and 1.5.10. But so far I have been unable to figure out the needed change.

While testing it, I noticed that the patch 001-conf.patch has never been refreshed for 1.5.9, either... That causes some initial fluff for the patch, although the needed changes seem to be only line numbers.

**Comment by hnyman** [comment]
I got it:
you need to modify the patch to explicitly remove the previous empty line and add new lint containing tab:
```
@@ -77,19 +75,19 @@ index ff90e3b..5c20fdf 100644
        # the maximum number of hosts that are cached (roundtrip, EDNS, lame).
        # infra-cache-numhosts: 10000
 +      infra-cache-numhosts: 200
- 
-       # Enable IPv4, "yes" or "no".
-       # do-ip4: yes
-@@ -188,6 +201,8 @@ server:
+       
+       # define a number of tags here, use with local-zone, access-control.
+       # repeat the define-tag statement to add additional tags.
```
But as it is a patch modifying a patch, editing is tricky. Lines are "- space" and "+ space tab".

I have successfully compiled all unbound 1.5.10 packages for ar71x (mips_24kc) after the fix. 

I will push the PR and the needed fix from my own tree.

**Comment by Borromini** [comment]
@hnyman Thanks for double checking, I have been trying to work around that whitespace as well, but it didn't want to cooperate :(. Thanks for your help!

**Comment by hnyman** [comment]
closed via https://github.com/openwrt/packages/commit/56891725c1988c80c0ed9be6911786e921cd1c8c and https://github.com/openwrt/packages/commit/524e19171cbd0abc3bcc0087f4ef39fcf733e294

**Comment by EricLuehrsen** [comment]
@hnyman thanks. I would have spent way too long finding and then patching the patch (of another patch?) I'll sumbit a bug upstream. Professional documentation should be consistent.

**Pull request closed without merging**
