### PR TITLE
ola: update to 0.10.1

### PR DESCRIPTION
**Pull request by bk138**
Signed-off-by: Christian Beier <dontmind@freeshell.org>

### CODE REVIEW

**Comment by hnyman** [comment]
Ola still fails to compile at buildbot due to missing dependencies. (it did that before the version update and still does.)
You should check the package's dependencies.

Example from today:
http://buildbot.openwrt.org:8010/broken_packages/mvebu/ola/compile.txt
```
Package ola is missing dependencies for the following libraries:
libavahi-client.so.3
libavahi-common.so.3
libdns_sd.so
liblo.so.7
make[2]: *** [/store/buildbot/slave/mvebu/build/bin/mvebu/packages/packages/ola_0.10.1-1_mvebu.ipk] Error 1
```
 First three are avahi-related, while the last one is probably a separate issue.

**Comment by bk138** [comment]
It built fine using openwrt-trunk buildroot. How can I check for buildbot issues like that in advance? Can you point me at the docs?

**Comment by jow-** [comment]
@bk138 you can likely only trigger the issue if you a build with all existing packages enabled. The only way to avoid this kind of issue is to prevent any automatic detection in ./configure. Disable any feature which you're not using/packaging, even if it is autodetected as "disabled" on your development system.

It seems that OLA does not provide a clean switch to disable avahi support, it relies on rather broken autoconfig logic to detect support. It is likely best to patch configure.ac, remove any avahi detection logic and build OLA with PKG_FIXUP:=autoreconf

**Comment by hnyman** [comment]
To complement Jow's answer with an example:
a rather similar issue was a few weeks ago with gnupg. It compiled ok at the development system, but failed at buildbot (and in my own buildroot) due to the presence of "curl" in the build. Configure detected libcurl, and gnupg built support for that, but there was no dependency declared. Discussion can be found at: https://github.com/openwrt/packages/pull/2204#issuecomment-181930415

**Comment by bk138** [comment]
I've made DNS-SD optional at build time and file an upstream PR https://github.com/OpenLightingProject/ola/pull/1061. The liblo dep is indeed a separate issue. I'll take   care of this once above PR got merged.

**Comment by peternewman** [comment]
Liblo is for OSC in case you weren't aware.

**Comment by bk138** [comment]
Please see https://github.com/openwrt/packages/pull/2518

**Pull request merged**
