### PR TITLE
ddns-scripts: Fix for wildcard subdomain 

### PR DESCRIPTION
**Pull request by looi**
Maintainer: @feckert
Compile tested: mvebu, master
Run tested: mvebu, master: Tested with cloudflare wildcard subdomain, it works

Description:

Fixes ddns-scripts so it will be able to update a wildcard subdomain.

Alternative to https://github.com/openwrt/packages/pull/14737

### CODE REVIEW

**Comment by feckert** [comment]
The changes look ok.
But could you please update the commit header with `ddns-scripts: <your message> `and also could you please Signed-off-by your work with a valid email address.

**Comment by looi** [comment]
> The changes look ok.
> But could you please update the commit header with `ddns-scripts: <your message> `and also could you please Signed-off-by your work with a valid email address.

Done, I have tried to do this

**Comment by feckert** [comment]
Thanks merged!

**Comment by looi** [comment]
Thanks!

**Comment by ldir-EDB0** [comment]
Unfortunately this appears to break domains with '-' in them eg. darbyshire-bryant.me.uk 

+ sanitize_variable domain '[@a-zA-Z0-9._-*]' 
+ local '__VAR=domain'
+ eval '__VALUE=$domain'
+ __VALUE=darbyshire-bryant.me.uk
+ local '__ALLOWED=[@a-zA-Z0-9._-*]'
+ local '__REJECT='
+ '[' -n '[@a-zA-Z0-9._-*]' ]
+ '[' -z - ]
+ write_log 12 'sanitize on domain found characters outside allowed subset'

It appears to leave a rogue '-' in what should be the 'null' string test.

**Comment by ldir-EDB0** [comment]
I think the order should be [@a-zA-Z0-9._*-]  That makes it work for me, but maybe I've broken wildcard domains instead :-)

**Comment by feckert** [comment]
@looi could you please verify if the change suggested by @ldir-EDB0 also works for your setup?
So we make both of you happy

**Comment by looi** [comment]
Yeah, it works. I have created https://github.com/openwrt/packages/pull/15664 if it's helpful

**Comment by feckert** [comment]
Fix with https://github.com/openwrt/packages/commit/9e2aad3fde6b1a9c4c0080c2c7434ab41f0b36ce

**Pull request merged**
