### PR TITLE
ksmbd stuff: update to 3.4.1

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @Andy2244 
Compile tested: ath79

ping @Vladdrako @egorenar  @fda77 @ptpt52

### CODE REVIEW

**Comment by ptpt52** [comment]
but it is not reasonable to make depends on nfsd
we could patch the kernel to select the CONFIG_OID_REGISTRY independently

https://github.com/x-wrt/x-wrt/blob/master/target/linux/generic/hack-5.4/999-tristate-hack.patch

**Comment by neheb** [comment]
In the buildbot case, all the kmods are selected as M and thus the kernel config enables all that's needed.

**Comment by Vladdrako** [comment]
@neheb Compiled succssesfully.

**Comment by egorenar** [comment]
Compiled for Netgear XR700 OpenWrt SNAPSHOT r17341-94e252da3f4d.

**Comment by egorenar** [comment]
I did some quick tests on my router, seems to work just fine :+1:

**Comment by ptpt52** [comment]
> In the buildbot case, all the kmods are selected as M and thus the kernel config enables all that's needed.

but it is not acceptable to make it depends on nfsd.

**Comment by egorenar** [comment]
> > In the buildbot case, all the kmods are selected as M and thus the kernel config enables all that's needed.
> 
> but it is not acceptable to make it depends on nfsd.
good point, weird dependency for samba

**Comment by neheb** [comment]
Right. I can't see a way to get it to compile without various hacks.

**Comment by ptpt52** [comment]
ether put the ksmbd to kernel source tree or patch the kernel Kconfig to export symbol like CONFIG_OID_REGISTRY

**Comment by neheb** [comment]
ping @hauke

**Comment by Neustradamus** [comment]
@neheb: Can you look for 3.4.2?
- 19.07.x/21.02.x/master?

Thanks in advance

**Comment by neheb** [comment]
no.

**Comment by Neustradamus** [comment]
@neheb: Why? :/

**Comment by neheb** [comment]
Because kernel modules cannot be freely updated for released versions.

**Pull request merged**
