### PR TITLE
prometheus-node-exporter-lua: Added entropy.lua.

### PR DESCRIPTION
**Pull request by jpds**
Maintainer: @champtar

### CODE REVIEW

**Comment by champtar** [comment]
Hi @jpds 
you need to bump PKG_VERSION, also please squash in 1 commit

**Comment by PolynomialDivision** [comment]
The commit prefix has to be `prometheus-node-exporter-lua`?

**Comment by champtar** [comment]
@jpds can you fix the commit title as pointed by @PolynomialDivision ?

**Comment by jpds** [comment]
@champtar Already pushed (`prometheus-collectors` referred to the original directory changed).

**Pull request merged**
