### PR TITLE
mwan3: ipv6-compatible default conf

### PR DESCRIPTION
**Pull request by luizluca**
Considering that ipv6 NPT/NAT/NETMAP is done manually by user,
mwan3 can balance ipv6 interfaces as it does with ipv4.

Interface wan2 was renamed to wanb as wan2, wan3, ... will eventually
colide with OpenWrt with default wan6 interface when more than 6
interfaces are in use.

New interfaces, members for wan6 and wanb6 where created, both disabled
by default. Policies where adapted as well.

The option "family" is set respectively in each interface. When missing,
mwan3 assumes ipv4, that will fail when interface is IPv6 only.

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

Maintainer: @feckert
Compile tested: OpenWrt SNAPSHOT r6587-ac593d895a x86
Run tested: OpenWrt SNAPSHOT r6587-ac593d895a x86, tested tracking status and active rules (but not real balancing)

Description:

I opted for a wanb instead of wan2 because wan26 will be funny and wan2, wan3, wan4... will catch wan6. However, I'll fully open for suggestions.

I do use wan_telcom1, wan_telcom2 in production, removing wan_ prefix in member and rule sections. However, it is simply not compatible with OpenWrt wan/wan6.

### CODE REVIEW

**Comment by luizluca** [comment]
Fixes #5761

**Comment by feckert** [comment]
I have not tested it because i have no ipv6 provider.
But it looks as I can say good to me.
It could be merged.

**Comment by hnyman** [comment]
There should be a bump in PKG_RELEASE or PKG_VERSION

**Comment by luizluca** [comment]
Bumped PKG_RELEASE.

I was avoiding to change version/release yet because there was another open PR (dc746a55a1d4e7f73a3e7df63978a4a1948dbbe5) for wman3 (but now I see it did not bumped release/version).

If the new interface suggested name (wanb) is fine, it is ready to merge.

**Comment by bluewavenet** [comment]
Do'h I missed this. It breaks a current WAN WAN2 configuration if an upgrade is done.
Not a terrible issue and it does prevent the ip4 wan6 clash with existing ip6 wan6 issue, not that it would be likely. So better late than never I agree that using a letter suffix is a good idea ;-)

**Pull request merged**
