### PR TITLE
fcgi: Update to 2.4.2

### PR DESCRIPTION
**Pull request by neheb**
Removed most patches as they are no longer needed.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jsiverskog 
Compile tested: ramips, ath79, both uclibc++ and libstdcpp

### CODE REVIEW

**Comment by jsiverskog** [comment]
:+1:

**Comment by diizzyy** [comment]
Uhm... The ```110-no_examples.patch```isn't be removed, and this should be runtime tested.

**Comment by neheb** [comment]
> Uhm... The `110-no_examples.patch` shouldn't be removed, and this should be runtime tested.

patching something like that out if for if/when it breaks compilation, no?

**Comment by diizzyy** [comment]
That's a completely different story than "Removed most patches as they are no longer needed."

**Comment by neheb** [comment]
How so? The examples are not used by the package.

**Comment by diizzyy** [comment]
no longer needed implies that functionality has been integrated rather than breaks compilation.

**Comment by neheb** [comment]
Reworded.

**Comment by diizzyy** [comment]
LGTM, will need run-time testing before merging however.

**Comment by neheb** [comment]
This is a library that doesn't seem to be used by anything based on a quick grep.

**Comment by neheb** [comment]
Merging. The other patch has been submitted upstream: https://github.com/FastCGI-Archives/fcgi2/pull/20/commits/ce76018f0541fd9a538bde651f82b83cd565ef91

**Comment by diizzyy** [comment]
@neheb 
Again, please stop merging untested stuff

**Pull request merged**
