### PR TITLE
rust: Update to 1.71.0

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: @lu-zero 
Compile tested: rockchip/armv8
Run tested: NanoPi R2S

Description:
- Merged PR #21544 with @jefferyto's suggestion
- rust: Update to 1.71.0

Cc: @brocaar

### CODE REVIEW

**Comment by lu-zero** [comment]
Thank you :)

**Comment by brocaar** [comment]
Thanks for merging in my PR into this PR :-)

**Comment by brocaar** [comment]
@1715173329 Once this has been merged into `master`, will it be merged into the `openwrt-23.05` branch too?

**Comment by 1715173329** [comment]
Sure ;)

**Pull request merged**
