### PR TITLE
imagemagick: update to 7.1.1-27

### PR DESCRIPTION
**Pull request by krant**
Maintainer: @val-kulkov 
Run tested: ARMv7, Linksys WRT3200ACM, master branch

Description:
- Use official source URL
- Add libstdcpp dependency
- Don't set configure options which are matching default values

### CODE REVIEW

**Comment by val-kulkov** [comment]
Looks good to me, assuming that the default config includes the support for jpeg and png.

**Comment by krant** [comment]
> assuming that the default config includes the support for jpeg and png.

they are - since `libpng` and `libjpeg` are indicated as dependencies, package configure finds them and enables the support.

**Comment by val-kulkov** [comment]
Sounds good. @krant : if you want to assume maintainership for imagemagick, please point PKG_MAINTAINER to yourself, I'd be fine with that.

**Comment by krant** [comment]
@val-kulkov thanks, PKG_MAINTAINER has been updated

@BKPepe run test has been successful

**Pull request merged**
