### PR TITLE
[for-15.05] libqrencode: import from old packages

### PR DESCRIPTION
**Pull request by oneru**
Update to latest release
add qrencode package which contains the qrencode binary
Remove libpng dependancy
Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>

### CODE REVIEW

**Comment by oneru** [comment]
I'll figure git out eventually. I think I got it right this time.

**Comment by sbyx** [comment]
Sorry, we usually do not add new packages to release branches. is there a good reason why this should go into the release?

**Comment by oneru** [comment]
@sbyx I know, the timing is unfortunate. We have a really cool feature in the luci-app-fwknopd project, that is, importing keys to the android client via qr code. It's the headline feature for the fwknop/openwrt integration.  The work has been done since before the 15.05 rc1 announce, just filtering through the process of getting pulled in. Also, import from old packages isn't quite the same as a brand new package.

**Comment by sbyx** [comment]
Well it's a new package in this feed. Anyway, guess we can make an exception.

**Comment by oneru** [comment]
@sbyx Thank you.

**Pull request merged**
