### PR TITLE
unbound: update to 1.6.0

### PR DESCRIPTION
**Pull request by EricLuehrsen**
Maintainer: me
Compile tested: OpenWrt 15.05.1 (CC)
Run tested: ar71xx TL-WDR3600v1
Description:
Unbound 1.6.0 is out. It has some resource thrift which is nice. A few options are better for exposure in UCI. It is tested but lets see how it goes for a weekend. If there are no objections, then I will mark this okay to merge Mon Dec 19.

### CODE REVIEW

**Comment by Borromini** [comment]
Eric, I have noticed the README.md mentions `list dhcp_option 'dns-server,0.0.0.0`but dns-server will break dnsmasq (at least it does on LEDE; I assume it does so on OpenWrt as well though).

If behaviour on OpenWrt is similar then it should  be replaced with `list dhcp_option '6,0.0.0.0`.

**Comment by EricLuehrsen** [comment]
You need be careful with syntax. Common numbered options have verbal `options:<name>` for clarity. So `6,0.0.0.0` is `option:dns-server,0.0.0.0` and it translates in UCI to full command/conf option:
`--dhcp-option=option:dns-server,0.0.0.0`

**Comment by Borromini** [comment]
Ah... I see now. I did indeed not add `option:`

Another question: I have a few setups with guest networks, separate subnet (10.0.1.x instead of 10.0.0.x). Can I stick with what UCI offers here or do I need to edit the Unbound configuration itself like before? Is there a way to have them coexist - UCI settings and a modified unbound.conf?

**Comment by EricLuehrsen** [comment]
Yes. It is robust to VLAN and guest WiFi. Unbound will bind to the wild card address/interface. It respond to queries only on respective subnets (optional local service). It will pull all local network host names from dnsmasq (optional link).

**Comment by Borromini** [comment]
Confirmed working here. Don't know if there's anything specific you need tested?

**Comment by EricLuehrsen** [comment]
Ready to merge.

@Borromini, nothing specific to test. Extra eyes reviewing scripts is much appreciated. Thanks.

**Comment by EricLuehrsen** [comment]
@hnyman, Ready to merge.

@Borromini, nothing specific to test. Extra eyes reviewing scripts is much appreciated. Thanks.

**Pull request merged**
