### PR TITLE
libev: update to 4.24

### PR DESCRIPTION
**Pull request by dengqf6**
Maintainer: @karlp 
Compile tested: ar71xx, ramips, mvebu
Run tested: ar71xx, ramips, mvebu

Signed-off-by: Deng Qingfang <dengqf6@mail2.sysu.edu.cn>

### CODE REVIEW

**Comment by diizzyy** [comment]
@karlp 
Ping

**Comment by dengqf6** [comment]
@karlp 
It didn't recognize my signed-off-by

**Comment by thess** [comment]
You need to set your "author" name in your git repository as required to match the Signed-off-by. You can fix this for all future commits by ```git config user.name "Deng Qingfang"``` or globally for all repositories add the ```--global``` option. If you want to fixup your current PR, then use ```git commit --amend --author="Deng Qingfang <dengqf6@mail2.sysu.edu.cn>"``` and force push an update.

**Comment by dengqf6** [comment]
Updated, seems OK.

**Comment by dengqf6** [comment]
@karlp @thess Can this be merged now?

**Comment by karlp** [comment]
thanks @yousong and thanks @dengqf6  for pinging on the update, I missed it.

(If you want to take over this package, be my guest)

**Pull request merged**
