### PR TITLE
glib2: revert latest changes to get back to working version 2.74.0

### PR DESCRIPTION
**Pull request by feckert**
Maintainer:  @neheb
Compile tested: lantiq_xrx200 and x86_64
Run tested: x86_64, APU3 with modemmanager

Description:
* revert latest changes to get back to working version 2.74.0
* do not set default meson options
* Update to  latest version 2.74.7 in series 2.74.x and refresh patches

### CODE REVIEW

**Comment by yegorich** [comment]
Is version 2.80.0 better in this regard?

**Comment by feckert** [comment]
@yegorich Difficult to say. I haven't tried it yet. In principle, we should update. But if, for example, the modem manager no longer works, as this was the case on last update try, then we could not update the glib2.

**Comment by feckert** [comment]
@yegorich thanks for the testing the upgrade to the latest glib2.
@aleksander0m Maybe you could help us and give us a hint in the right direction why does ModemManager could not register to the dbus with the latest glib2 version 2.80.x?

**Comment by yegorich** [comment]
I opened the related issue: https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/849

**Comment by yegorich** [comment]
@feckert could you test my PR: https://github.com/openwrt/packages/pull/23951

Looks like the problem is the default runtime_dir introduced in https://gitlab.gnome.org/GNOME/glib/-/commit/30995f9dd7c24314c362a3e30102b89196bcef84

**Pull request merged**
