### PR TITLE
conmon: update to 2.0.29

### PR DESCRIPTION
**Pull request by oskarirauta**
Signed-off-by: Oskari Rauta <oskari.rauta@gmail.com>

Maintainer: Daniel Golle / @dangowrt
Compile tested: x86_64, recent git
Run tested: x86_64, recent git

Description:
Updated to version 2.0.29 and added me as maintainer as previously requested by @dangowrt

Patch I earlierly provided is now removed as it has been merged to conmon's code.

### CODE REVIEW

**Comment by dangowrt** [comment]
Please go ahead, I'm not with my computer right now, so I can't merge myself.

**Comment by dangowrt** [comment]
On Tue, Jun 08, 2021 at 01:06:28PM -0700, Oskari Rauta wrote:
> > Please go ahead, I'm not with my computer right now, so I can't merge myself.
> 
> 
> 
> > Please go ahead, I'm not with my computer right now, so I can't merge myself.
> 
> I am not authorized.

What I meant to express is that you have my ACK to takeover
maintainership.

Maybe someone else can merge this for now?

**Comment by BKPepe** [comment]
I wanted to merge this, but the patch was removed and it is not mentioned in the commit message either in PR description.

**Comment by oskarirauta** [comment]
Yes, I submitted same patch also to author of conmon and it was Merged to conmon. This was discussed and notified in my previous pr to conmon that this patch is no longer required in next release of conmon. Content of patch is included as-is, but with patch that was merged in conmon's tree like I previously announced.

**Comment by oskarirauta** [comment]
@BKPepe @dangowrt 

Time for review..?

**Comment by BKPepe** [comment]
Still my thoughts are valid for commit message, where it is mandatory, though. You are doing more changes then you are saying in the commit message, though.

**Comment by oskarirauta** [comment]
@BKPepe commit message updated.

**Comment by BKPepe** [comment]
Once the CI pass, I will merge it.

**Comment by oskarirauta** [comment]
> Once the CI pass, I will merge it.

Great. Thanks.

**Comment by oskarirauta** [comment]
Maybe check #15804 next?
It's kinda related to same subject...

After that, all components used by podman would be once again up-to-date.

**Pull request merged**
