### PR TITLE
CI: remove CircleCI for now

### PR DESCRIPTION
**Pull request by aparcar**
The GitHub CI offers currently more architecture and the Signed-of-by
test is covered via the DOC CI test. In case GitHub ever changes
policies, we can simply switch back.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by neheb** [comment]
ping @openwrt/package-maintainers

**Comment by champtar** [comment]
Ok for me, I like Microsoft paying for our CI ;)
On another note, some arch are failing

**Comment by neheb** [comment]
I think related to https://github.com/openwrt/packages/commit/d964a3ba92f028880a37a918ec335524c7b904df

**Comment by neheb** [comment]
I feel like there's a different way to disable CircleCI...

**Comment by aparcar** [comment]
Maybe some admin has to disable it

**Comment by BKPepe** [comment]
Wouldn't it be sufficient just to disable CircleCI for this repository, so anyone who has forked this repository might be using it?

**Comment by aparcar** [comment]
@BKPepe Yes good point, I think we have the same situation with travis. My only "fear" is that people see these script and except them to be up 2 date, which I'll not take care of.

**Comment by neheb** [comment]
Seems CircleCI is no longer active.

I suggest we keep this here just in case. It's hidden anyway.

**Comment by BKPepe** [comment]
> @BKPepe  My only "fear" is that people see these script and except them to be up 2 date, which I'll not take care of.

The issue was that if you enabled CircleCI for your forked repository and then you submitted PR against the packages repository then the check was gone in pull request. Otherwise, CircleCI was better than Travis for us, though.

**Comment by yousong** [comment]
> Seems CircleCI is no longer active.

@neheb , how is that?  is it about the circleci company?

**Comment by neheb** [comment]
No I mean some PRs are not getting CircleCI. Not sure what's going on.

**Comment by neheb** [comment]
Let's close this. I believe CircleCI gets disabled in a different way.

**Comment by pprindeville** [comment]
Also see issue #14921 about `strongswan` on `x86_64` being consistently failed.

**Comment by aparcar** [comment]
CircleCI doesn't cover backport pull requests (it just fails) and all checks (and more) are migrated over to GitHub CI. Still objections to keep it?

**Comment by neheb** [comment]
I'm fine with removal.

**Comment by champtar** [comment]
I just tried to unconfigure CircleCI as much as possible for this repo, not sure it changed anything
Circle CI is still used by telephony repo, if someone can migrate telephony to Github CI then we can completely remove Circle CI from the org configuration once and for all

**Comment by jslachta** [comment]
@champtar, I am fine with removal CircleCI from telephony repository.

**Comment by neheb** [comment]
Is this obsolete?

**Comment by aparcar** [comment]
Afaik yes.

**Comment by champtar** [comment]
CircleCi is removed from OpenWrt org now, and everything it was doing is now done by GitHub actions.
If anyone is using CircleCI on their fork, can you explain your use case ?

**Comment by aparcar** [comment]
Please go ahead

**Pull request merged**
