### PR TITLE
docker: fix openwrt modprobe warning

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @G-M0N3Y-2503 @yousong
Compile tested: x86_64, APU3, OpenWrt master
Run tested: x86_64, APU3, OpenWrt master, checked if warnings still present -> NO

Description:
Fix openwrt modprobe loading

### CODE REVIEW

**Comment by jow-** [comment]
I think this patch is incomplete as OpenWrt's ubox modprobe does not actually handle multiple module arguments.

Instead of patching Docker, I think it would make more sense to add `-v` and `-a` flag support as no-ops to ubox kmodload and give it the ability to handle multiple modules.

This would also benefit other existing software that wants to use modprobe.

**Comment by G-M0N3Y-2503** [comment]
My golang isn't super strong but wouldn't `utils/docker-ce/patches/202-kmodloader.patch`, `utils/docker-ce/patches/203-kmodloader.patch` and `utils/docker-ce/patches/204-kmodloader.patch` also need to be ported to `utils/libnetwork/patches/` as that builds the actual executable?

**Comment by feckert** [comment]
> My golang isn't super strong but wouldn't `utils/docker-ce/patches/202-kmodloader.patch`, `utils/docker-ce/patches/203-kmodloader.patch` and `utils/docker-ce/patches/204-kmodloader.patch` also need to be ported to `utils/libnetwork/patches/` as that builds the actual executable?

Sorry I do not understand this?

> Instead of patching Docker, I think it would make more sense to add `-v` and `-a` flag support as no-ops to ubox kmodload and give it the ability to handle multiple modules.
> 

I have to see how to teach this to the kmodload of ubox.

> This would also benefit other existing software that wants to use modprobe.

Yes this would be nice.

Thanks for the hint

**Comment by G-M0N3Y-2503** [comment]
> > My golang isn't super strong but wouldn't `utils/docker-ce/patches/202-kmodloader.patch`, `utils/docker-ce/patches/203-kmodloader.patch` and `utils/docker-ce/patches/204-kmodloader.patch` also need to be ported to `utils/libnetwork/patches/` as that builds the actual executable?
> 
> @G-M0N3Y-2503 Sorry I do not understand this?
> 

Unless I'm mistaken, the vendor folder in GoLang is an interface for the dependencies, whereas the binary output is created within the dependency. In this case, for the actual changes to make it into the executables the patches, you've put in `components/engine/vendor/github.com/docker/libnetwork/` also need to be applied to the libnetwork package. You have already done this for the `ns/init_linux.go` patch but the ones for `iptables/iptables.go`, `drivers/bridge/bridge.go` and `ipvs/netlink.go` are missing.

That being said, I agree with what @jow- suggested, so doing that will make this unnecessary.

**Comment by feckert** [comment]
Thanks for the feedback. If I find the time I will update the openwrt modprobe(kmodolader) with your suggestions.

**Pull request closed without merging**
