### PR TITLE
collectd: enable lua support

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @hnyman @jow- 
Compile tested: xrx200 and x86_64(APU3), master
Run tested: lantiq_xrx200 and x86_64(APU3), master, 

Description:
This will enable the lua support for collectd.
The new package name is collectd-mod-lua

### CODE REVIEW

**Comment by feckert** [comment]
I have fixed the issue i have during runtime. The library **-llua** must be added to the LDFLAGS during **configure**. Everything is now working as expected. I am not sure if there is a better way to add this to the LDFLAGS. Please let me know.

**Comment by feckert** [comment]
There was also a problem with the collectd-mod-lua plugin. If you want to use more then one lua script this was not possible. https://github.com/collectd/collectd/pull/2379 
I have used the patch from BSD to get this fixed.
http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/collectd/patches/patch-src_lua.c?annotate=1.1

**Comment by feckert** [comment]
This is related to the pull request #8311

**Comment by hnyman** [comment]
Also here with this collectd - lua - uci thing, it is better that @jow- looks at it.

**Comment by feckert** [comment]
No comments so I will merge in the next days.

**Pull request merged**
