### PR TITLE
bluez: Update to 5.49

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @psycho-nico @nxhack  @Noltari @hauke 
Compile tested:
mvebu, Linksys WRT3200ACM, OpenWrt master
ramips, D-Link DIR-860L, OpenWrt master
Run tested:
mvebu, Linksys WRT3200ACM, OpenWrt master
ramips, D-Link DIR-860L, OpenWrt master

Description:
Update bluez to 5.49
Fix issue https://github.com/openwrt/packages/issues/1497
Fix issue https://github.com/openwrt/packages/issues/1503
Cherry pick patches from Alpine Linux repo
Apply --gc-sections, saves about 500kbyte
Drop audio.conf (not needed and deprecated)
Remove bluetooth.dbus as upstream supplies a working copy

Based on patch provided by Johnny Vogels
https://github.com/openwrt/packages/pull/5937

Source:
https://git.alpinelinux.org/cgit/aports/commit/main/bluez/fix-endianness.patch?id=1c6991b32a22be2c905cc1709be1376c4e79e451
https://git.alpinelinux.org/cgit/aports/commit/main/bluez/bluez-5.40-obexd_without_systemd-1.patch?id=980b2d04ae4339594701b33cf9460757c989c94c

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@PolarSolvent

**Comment by diizzyy** [comment]
My test setup might be a bit wonky so please test if trusted devices are actually persistent.

**Comment by PolarSolvent** [comment]
Tested on ar71xx gl-inet board with CSR usb bluetooth dongle and this seems to work fine across reboots and no dbus permission errors.

**Comment by diizzyy** [comment]
Thanks for trying it out!

**Comment by hnyman** [comment]
@psycho-nico 
Any objections for merging this?

**Comment by diizzyy** [comment]
Thanks!

**Pull request merged**
