### PR TITLE
usbip: remove upstreamed patch

### PR DESCRIPTION
**Pull request by juppin**
Maintainer: Nuno Goncalves <nunojpg@gmail.com>
Compile tested: ath79, tp link wdr4300, master

Description:

This upstream commit fixes the build error on musl libc:

#### Catched kernel versions:
Current OpenWRT Kernel Version: 4.14.50
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/tools/usb/usbip?h=v4.14.50&id=4309a1e0d1c39b5ad082e421d003085d38d20595

Current OpenWRT Kernel Version:  4.9.109
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/tools/usb/usbip?h=v4.9.109&id=c485b111e69c76a39d5535c0d53050635f0e3314

#### Not catched kernel versions:

Current OpenWRT Kernel Version: 4.4.121
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/tools/usb/usbip?h=v4.4.138&id=6638091f1b1623db8b2338ef5a5f26d9ec870444

Current OpenWRT Kernel Version: 3.18.71
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/tools/usb/usbip?h=v3.18.113&id=9ed1f97d068c9eb4ba302cdc93b5a0c6d1f37960

All targets that are not on 4.9 or 4.14 are source-only targets.
So remove the upstearmed and not working patch file.

Signed-off-by: Johann Neuhauser <johann@it-neuhauser.de>

### CODE REVIEW

**Comment by karlp** [comment]
This will only work for the targets that are on 4.14.50 or later.  There's still targets on 4.9 (such as ar71xx for instance)

**Comment by juppin** [comment]
Don't thought about that...
But it's backported too and 4.9 is already on 4.9.109 which include this:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/tools/usb/usbip?h=v4.9.109&id=c485b111e69c76a39d5535c0d53050635f0e3314

**Comment by diizzyy** [comment]
There are also targets that still use 3.18 or 4.4 so perhaps it's worth adding ```DEPENDS:= .... @(LINUX_4_9||LINUX_4_14)```?

**Comment by juppin** [comment]
There is no target with 4.4 but adm8668, au1000, adm5120, xburst, ppc40x, mcs814x and ppc44x did use 3.18.

Thought that all devices that are not on 4.9 or 4.14 are dropped???
Otherwise i will add the solution of @diizzyy

**Comment by diizzyy** [comment]
oxnas and zynq --> 4.4
https://github.com/openwrt/openwrt/commit/f6a067a6995c521c90499170b667908dbf9eab7e

**Comment by diizzyy** [comment]
True, used an old tree :-/

**Comment by juppin** [comment]
This commit is in all four kernel versions included but the used version in openwrt of 3.18 and 4.4 are not uptodate so they did not include this commit!
I´ve updated the pr message above...

**Comment by cotequeiroz** [comment]
I have PR open #6062  that deals with this a little differently.  I added `DSIGCLD=SIGCHLD` to CFLAGS, so previous versions would still work without the patch.

**Pull request closed without merging**
