### PR TITLE
openssh: bump to 9.9p1

### PR DESCRIPTION
**Pull request by graysky2**
Release notes: https://www.openssh.com/txt/release-9.9
Added upstream patch to fix build[1]
    
1. https://github.com/openssh/openssh-portable/commit/76a618d2842c34c16cd21a4efc7230e2f459008d.patch

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

Maintainer: @SibrenVasse, @tripolar

### CODE REVIEW

**Comment by BKPepe** [comment]
> Had to remove the configure option --disable-wtmp to get it to build.

Have you reach upstream to look at it? For me, it looks like, wtmp will be enabled by default. I dont think that we want that.  🤷  Enabling smth by default, it means that there is going to be size difference and if you enabled it, you need to know smth more about wtmp.

**Comment by SibrenVasse** [comment]
You can fix the compilation with --disable-utmp with [this patch](https://raw.githubusercontent.com/SibrenVasse/packages/998893acdc132dd1e2afa5bb825cfb86a8f91cef/net/openssh/patches/010-musl-btmp.patch) 
https://github.com/SibrenVasse/packages/pull/30

**Comment by graysky2** [comment]
Thanks @SibrenVasse - your patch fixes the build and everything works as expected on my x86/64 test box.

**Comment by BKPepe** [comment]
Do you have any build log related to the issue, which you experienced? Isn't it same as https://github.com/openssh/openssh-portable/pull/504 ? Sorry for such questions, but all of this, should be part of the patch, which you adds and also, it should be solved in upstream not in downstream, though.

**Comment by BKPepe** [comment]
I can see that it was solved in upstream: https://github.com/openssh/openssh-portable/commit/76a618d2842c34c16cd21a4efc7230e2f459008d

Could you replace your patch with the upstream one, please? 
https://github.com/openssh/openssh-portable/commit/76a618d2842c34c16cd21a4efc7230e2f459008d.patch

**Comment by graysky2** [comment]
Thanks @BKPepe - patch added and refreshed.

**Review by BKPepe — APPROVED** [review]

**Pull request merged**
