### PR TITLE
ddns-scripts: suppress curl output for route53

### PR DESCRIPTION
**Pull request by pacohope**
Maintainer: me / Signed-off-by: Florian Eckert <fe@dev.tdt.de> (?)
Compile tested: ipq806x/generic OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.093.57104-ce20b4a
Run tested: ipq806x/generic OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.093.57104-ce20b4a

Description:

My first attempt at a PR, please be gentle. I was troubleshooting Route53 ddns stuff today and running this script by hand with the `-v 2` option. When it gets to line 83 and invokes `curl` the progress bar output comes out, and I don't think that's ever useful. These two options mean that `curl` doesn't produce any output unless there are errors.

Signed-off-by: Paco Hope <github@filter.paco.to>

### CODE REVIEW

**Comment by feckert** [comment]
* Please change your commit header to `ddns-scripts: supress output for route53`
* Add some additional information to the [commit](https://github.com/openwrt/packages/pull/21986/commits/c83e90d25240ce95fb40fd005e6839f2164c404b) body why do we need this
* Add your Signed-off-by to the commit and not to the pullrequest. The commit goes into the repo and not the description of the pullrequest

**Comment by pacohope** [comment]
Ok. I have done 2 things: I did a rebase against the master branch, which shows up as part of my PR. Hopefully that's not a problem. I also amended the commit to include a better description and the signed-off header in the commit. If I've made it worse instead of better, I can always just cancel this PR and start fresh.

**Comment by pprindeville** [comment]
Please squash/fixup to a single commit.

**Comment by pacohope** [comment]
i clearly need to do this differently. Sorry for cluttering your inboxes. I'm gonna start clean and try again.

**Pull request closed without merging**
