### PR TITLE
xtables-addons: fix build on 4.19 for xt_DNETMAP and xt_pknock

### PR DESCRIPTION
**Pull request by dengqf6**
Maintainer: @dedeckeh @pprindeville 
Compile tested: mvebu

Description:
Backport 2 commits to fix build on 4.19:
https://github.com/nawawi/xtables-addons/commit/3ea761a1ed338241fbc79bef8e433307e108b6cd
https://github.com/nawawi/xtables-addons/commit/2b76b68c65c97fc11409088c3c30993324df8500

### CODE REVIEW

**Comment by dedeckeh** [comment]
I prefer to backport the patches from upstream by making a patch of the relevant upstream commits via git format-patch rather than squashing the commits into one patch file. This will preserve the original commit title and description (if present) and will make it easier in the future to recognize the patches as upstream backports

**Comment by dengqf6** [comment]
Done

**Comment by dedeckeh** [comment]
Still I prefer to keep the commit title as patch name; now you changed them to fix-k4.15-build and fix-k4.18-build

**Comment by dengqf6** [comment]
So I should name these patches `002-build-support-for-Linux-4.15.patch` and `003-build-add-support-for-Linux-4.18.patch`. Is that right?

**Comment by dedeckeh** [comment]
Yes as obtained by doing git format-patch -o . 2b76b68 -1 and git format-patch 3ea761a -o . -1 in the xtables-addons git repo

**Comment by dengqf6** [comment]
Done

**Comment by dedeckeh** [comment]
Merged; thx

**Pull request merged**
