### PR TITLE
gstreamer1: Update to 1.14.4

### PR DESCRIPTION
**Pull request by neheb**
Disabled a bunch more stuff through the configure script. Refreshed
patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @thess @MikePetullo 
Compile tested: mvebu

I'm not sure patches 2 and 3 are needed. I compiled a build without them. Thoughts?

### CODE REVIEW

**Comment by neheb** [comment]
Rebased

**Comment by thess** [comment]
Get these puppies to build with CircleCI and I'll consider it.

**Comment by neheb** [comment]
@thess Done. I also added an OpenSSL patch to get rid of deprecated warnings.

**Comment by neheb** [comment]
Submitted upstream: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/merge_requests/38

**Pull request merged**
