### PR TITLE
libx264: create package

### PR DESCRIPTION
**Pull request by ianchi**
libx264: create package

Signed-off-by: Adrian Panella <ianchi74@outlook.com>

### CODE REVIEW

**Comment by luizluca** [comment]
Should it add "DEPENDS:=@BUILD_PATENTED"?

@ianchi , I noticed you closed previous PR. You could simply push force over your previous branch. There is no need to redo it next time.

**Comment by ianchi** [comment]
I'm not sure of the limits of BUILD_PATENTED.
x264 does have a GPL license and also a commercial one. Besides there is the underlying issue with AVC royalties.
To be on the safe side I will add it.

I'll try the push force this time. I don't have much experience with GIT, so thanks for the advice.

**Comment by ianchi** [comment]
updated

**Comment by thess** [comment]
Thanks for the package

**Pull request merged**
