### PR TITLE
netdata: Update to 1.3.0

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @nitroshift
Compile tested: ramips, D-Link DIR-860L B1, LEDE e9c517772cee8af63b4ef173a28152645a4e1b05
Run tested: ramips, D-Link DIR-860L B1, LEDE e9c517772cee8af63b4ef173a28152645a4e1b05

Description:

Update netdata to version 1.3.0

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by nitroshift** [comment]
It compiles OK on mvebu platform (Linksys WRT1900AC v1 - Mamba) with kernel 4.4.20, but it fails to run on this platform. Suggest to drop the update and close this pull request until a fix is found.

**Comment by diizzyy** [comment]
You need to be more verbose, it runs fine on ar71xx (LEDE).
https://github.com/openwrt/openwrt/blob/master/include/kernel-version.mk
https://github.com/lede-project/source/blob/master/include/kernel-version.mk
Neither of these use 4.4.20 so please use a stock checkout instead of non upstream changes.

**Comment by nitroshift** [comment]
This is what I see when I try to start netdata:

FATAL: netdata: Cannot cd to directory '/var/cache/netdata' # : Invalid argument
INFO: netdata: Called: netdata_cleanup_and_exit()
INFO: netdata: Saving database...
INFO: netdata: NetData exiting. Bye bye...

v.1.2.0 doesn't have that issue.

**Comment by diizzyy** [comment]
Default config doesn't work ootb, closing

**Pull request closed without merging**
