### PR TITLE
[19.07] ksmbd(-tools): update to 3.3.4

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @Andy2244 

ping @ynezz @hauke as this is a kernel module, it need to be merged right before a new release is cut. The current version has several bugs including some big endian ones.

### CODE REVIEW

**Comment by Andy2244** [comment]
yeah would be nice to get this finally in stable, so we have the stable ABI on next release.

**Comment by zorun** [comment]
Just to be clear, once this is merged, it will break all previous 19.07.X versions, right?

**Comment by neheb** [comment]
I believe so.

**Comment by Andy2244** [comment]
> Just to be clear, once this is merged, it will break all previous 19.07.X versions, right?

Kinda, if a user updates a older 19.07.x version of the ksmbd-tools to the new version, while still having the old kernel module.
This means the current kmod in 19.07.x is not ABI compatible to this 3.3.x+ userspace tools package.

**Comment by neheb** [comment]
Set to ready. I assume .7 will be released soon.

**Comment by hauke** [comment]
Thank you for the change. I agreed with @neheb  to merge this before tagging 19.07.7

**Pull request merged**
