### PR TITLE
v4l-utils: add libudev-zero dependency

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: @thess
Compile tested: OpenWrt master r17331-4d81f08771 on x86/64
Run tested: NA

Description:
When libudev-zero is enabled, v4l-utils links against it, and the
package build fails due to a missing dependency:

Package v4l-utils is missing dependencies for the following libraries:
libudev.so.1

As disabling udev doesn't seem to be supported in v4l-utils, simply add
the dependency to fix the build.

### CODE REVIEW

**Comment by neheb** [comment]
Sounds wrong. There's a patch to disable it: https://github.com/openwrt/packages/blob/59771bde0ceff2a3b84b1ee7d119948d18da6e65/libs/libv4l/patches/010-remove-libudev-check.patch

Strange that it's not working.

**Comment by stintel** [comment]
Honestly I rather add the dependency and drop a patch that obviously isn't working and probably wasn't submitted upstream either.

**Comment by neheb** [comment]
The patch was to deal with host libudev leaking into the build. Now that there's libudev-zero, might as well add the dependency and remove that patch.

**Comment by neheb** [comment]
Actually that patch was introduced when OpenWrt was still using pkg-config. I don't think it's needed now that OpenWrt uses pkgconf.

**Comment by thess** [comment]
I think that adding the dependency and dropping the `010-remove-libudev-check.patch` is the right direction. If we are to include `libudev` here, we could also add back the **dvbv5** library and utils to the package as well as the associated "dev" components - maybe as an option?

**Comment by stintel** [comment]
> I think that adding the dependency and dropping the `010-remove-libudev-check.patch` is the right direction. If we are to include `libudev` here, we could also add back the **dvbv5** library and utils to the package as well as the associated "dev" components - maybe as an option?

I don't think **dvbv5** and utils are related to this PR. This PR is just about fixing a build problem.

**Comment by neheb** [comment]
Sure. Can you also remove the udev patch?

**Comment by thess** [comment]
LGTM - Thanks.

**Pull request merged**
