### PR TITLE
borgbackup: fix missing depends

### LINKED ISSUE #20441: borgbackup: missing modules on Linksys WRT1200AC (armv7l) with OpenWrt 22.03.0
Maintainer: @julienmalik 
Environment: armv7l, Linksys WRT1200AC, openwrt 22.03.0

Description:
I've installed the package borgbackup via Luci on my router, but when I run the borg command afterwards I'm receiving the following errors:

```
root@router:~# borg
Traceback (most recent call last):
  File "/usr/bin/borg", line 10, in <module>
    from importlib.metadata import distribution
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 6, in <module>
ModuleNotFoundError: No module named 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 15, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

Any suggestions what I need to do to make it work?

Thanks in advance!

### PR DESCRIPTION
**Pull request by julienmalik**
Maintainer: me
Compile tested: no
Run tested: yes (x86 docker)

Description:

Fixes #20441
Workaround for #20462 

```
  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r22000-6bc675c0be
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# opkg update
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/5.15.91-1-b0eafca757efb883a35dbbcaf514bbc8/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/5.15.91-1-b0eafca757efb883a35dbbcaf514bbc8/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.sig
Signature check passed.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# opkg install borgbackup
Installing borgbackup (1.2.3-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/borgbackup_1.2.3-1_x86_64.ipk
Installing zlib (1.2.13-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/zlib_1.2.13-1_x86_64.ipk
Installing libpython3-3.10 (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libpython3-3.10_3.10.7-3_x86_64.ipk
Installing python3-base (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-base_3.10.7-3_x86_64.ipk
Installing libffi (3.4.2-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libffi_3.4.2-2_x86_64.ipk
Installing libbz2-1.0 (1.0.8-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libbz2-1.0_1.0.8-1_x86_64.ipk
Installing python3-light (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-light_3.10.7-3_x86_64.ipk
Installing libstdcpp6 (12.2.0-4) to root...
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/libstdcpp6_12.2.0-4_x86_64.ipk
Installing python3-msgpack (1.0.2-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-msgpack_1.0.2-1_x86_64.ipk
Installing python3-attrs (21.4.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-attrs_21.4.0-1_x86_64.ipk
Installing python3-async-generator (1.10-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-async-generator_1.10-1_x86_64.ipk
Installing python3-ply (3.11-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-ply_3.11-2_x86_64.ipk
Installing python3-pycparser (2.21-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-pycparser_2.21-1_x86_64.ipk
Installing python3-cffi (1.15.0-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-cffi_1.15.0-2_x86_64.ipk
Installing python3-exceptiongroup (1.1.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-exceptiongroup_1.1.0-1_x86_64.ipk
Installing python3-codecs (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-codecs_3.10.7-3_x86_64.ipk
Installing python3-idna (3.3-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-idna_3.3-2_x86_64.ipk
Installing python3-outcome (1.2.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-outcome_1.2.0-1_x86_64.ipk
Installing python3-sniffio (1.3.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-sniffio_1.3.0-1_x86_64.ipk
Installing python3-sortedcontainers (2.4.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-sortedcontainers_2.4.0-1_x86_64.ipk
Installing python3-trio (0.22.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-trio_0.22.0-1_x86_64.ipk
Installing kmod-fuse (5.15.91-1) to root...
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/5.15.91-1-b0eafca757efb883a35dbbcaf514bbc8/kmod-fuse_5.15.91-1_x86_64.ipk
Installing libfuse3-3 (3.10.5-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libfuse3-3_3.10.5-2_x86_64.ipk
Installing python3-pyfuse3 (3.2.2-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-pyfuse3_3.2.2-1_x86_64.ipk
Installing libattr (2.5.1-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libattr_2.5.1-1_x86_64.ipk
Installing libacl (2.3.1-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libacl_2.3.1-1_x86_64.ipk
Installing libopenssl1.1 (1.1.1s-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libopenssl1.1_1.1.1s-2_x86_64.ipk
Installing liblz4-1 (1.9.4-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/liblz4-1_1.9.4-1_x86_64.ipk
Installing libzstd (1.5.2-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libzstd_1.5.2-2_x86_64.ipk
Installing libxxhash (0.8.1-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libxxhash_0.8.1-1_x86_64.ipk
Configuring zlib.
Configuring libpython3-3.10.
Configuring python3-base.
Configuring libffi.
Configuring libbz2-1.0.
Configuring python3-light.
Configuring python3-attrs.
Configuring python3-async-generator.
Configuring python3-ply.
Configuring python3-pycparser.
Configuring python3-cffi.
Configuring python3-exceptiongroup.
Configuring python3-codecs.
Configuring python3-idna.
Configuring python3-outcome.
Configuring python3-sniffio.
Configuring python3-sortedcontainers.
Configuring python3-trio.
Configuring libxxhash.
Configuring libattr.
Configuring libacl.
Configuring libzstd.
Configuring liblz4-1.
Configuring libstdcpp6.
Configuring python3-msgpack.
Configuring kmod-fuse.
Configuring libfuse3-3.
Configuring python3-pyfuse3.
Configuring libopenssl1.1.
Configuring borgbackup.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# borg --help
Traceback (most recent call last):
  File "/usr/bin/borg", line 10, in <module>
    from importlib.metadata import distribution
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 6, in <module>
ModuleNotFoundError: No module named 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 15, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
root@x86-master:/# opkg install python3-email
Installing python3-email (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-email_3.10.7-3_x86_64.ipk
Configuring python3-email.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# borg --help
Traceback (most recent call last):
  File "/usr/bin/borg", line 10, in <module>
    from importlib.metadata import distribution
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 7, in <module>
  File "/usr/lib/python3.10/pathlib.py", line 14, in <module>
ModuleNotFoundError: No module named 'urllib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 15, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
root@x86-master:/# opkg install python3-urllib
Installing python3-urllib (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-urllib_3.10.7-3_x86_64.ipk
Configuring python3-urllib.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# borg --help
Traceback (most recent call last):
  File "/usr/bin/borg", line 33, in <module>
    sys.exit(load_entry_point('borgbackup==1.2.3', 'console_scripts', 'borg')())
  File "/usr/bin/borg", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/borg/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
root@x86-master:/# opkg install python3-packaging
Installing python3-packaging (20.9-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-packaging_20.9-1_x86_64.ipk
Installing python3-pyparsing (2.4.7-2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-pyparsing_2.4.7-2_x86_64.ipk
Installing python3-six (1.16.0-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-six_1.16.0-1_x86_64.ipk
Installing python3-logging (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-logging_3.10.7-3_x86_64.ipk
Installing python3-distutils (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-distutils_3.10.7-3_x86_64.ipk
Configuring python3-pyparsing.
Configuring python3-distutils.
Configuring python3-six.
Configuring python3-logging.
Configuring python3-packaging.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# borg --help
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 38, in <module>
  File "/usr/lib/python3.10/site-packages/borg/helpers/__init__.py", line 13, in <module>
  File "/usr/lib/python3.10/site-packages/borg/helpers/manifest.py", line 15, in <module>
  File "/usr/lib/python3.10/site-packages/borg/helpers/parseformat.py", line 10, in <module>
ModuleNotFoundError: No module named 'uuid'
root@x86-master:/# opkg install python3-uuid
Installing python3-uuid (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-uuid_3.10.7-3_x86_64.ipk
Configuring python3-uuid.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# borg --help
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 87, in <module>
  File "/usr/lib/python3.10/site-packages/borg/selftest.py", line 22, in <module>
ModuleNotFoundError: No module named 'unittest'
root@x86-master:/# opkg install python3-unittest
Installing python3-unittest (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-unittest_3.10.7-3_x86_64.ipk
Configuring python3-unittest.
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# 
root@x86-master:/# borg --help
usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p] [--iec] [--log-json] [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
            [--remote-ratelimit RATE] [--upload-ratelimit RATE] [--remote-buffer UPLOAD_BUFFER] [--upload-buffer UPLOAD_BUFFER] [--consider-part-files] [--debug-profile FILE] [--rsh RSH]
            <command> ...

Borg - Deduplicated Backups

options:
  -V, --version         show version number and exit

Common options:
  -h, --help            show this help message and exit
  --critical            work on log level CRITICAL
  --error               work on log level ERROR
  --warning             work on log level WARNING (default)
  --info, -v, --verbose
                        work on log level INFO
  --debug               enable debug output, work on log level DEBUG
  --debug-topic TOPIC   enable TOPIC debugging (can be specified multiple times). The logger path is borg.debug.<TOPIC> if TOPIC is not fully qualified.
  -p, --progress        show progress information
  --iec                 format using IEC units (1KiB = 1024B)
  --log-json            Output one JSON object per log line instead of formatted text.
  --lock-wait SECONDS   wait at most SECONDS for acquiring a repository/cache lock (default: 1).
  --bypass-lock         Bypass locking mechanism
  --show-version        show/log the borg version
  --show-rc             show/log the return code (rc)
  --umask M             set umask to M (local only, default: 0077)
  --remote-path PATH    use PATH as borg executable on the remote (default: "borg")
  --remote-ratelimit RATE
                        deprecated, use ``--upload-ratelimit`` instead
  --upload-ratelimit RATE
                        set network upload rate limit in kiByte/s (default: 0=unlimited)
  --remote-buffer UPLOAD_BUFFER
                        deprecated, use ``--upload-buffer`` instead
  --upload-buffer UPLOAD_BUFFER
                        set network upload buffer size in MiB. (default: 0=no buffer)
  --consider-part-files
                        treat part files like normal files (e.g. to list/extract them)
  --debug-profile FILE  Write execution profile in Borg format into FILE. For local use a Python-compatible file can be generated by suffixing FILE with ".pyprof".
  --rsh RSH             Use this command to connect to the 'borg serve' process (default: 'ssh')

required arguments:
  <command>
    benchmark           benchmark command
    break-lock          break repository and cache locks
    check               verify repository
    compact             compact segment files / free space in repo
    config              get and set configuration values
    create              create backup
    debug               debugging command (not intended for normal use)
    delete              delete archive
    diff                find differences in archive contents
    export-tar          create tarball from archive
    extract             extract archive contents
    info                show repository or archive information
    init                initialize empty repository
    key                 manage repository key
    list                list archive or repository contents
    mount               mount repository
    prune               prune archives
    recreate            Re-create archives
    rename              rename archive
    serve               start repository server process
    umount              umount repository
    upgrade             upgrade repository format
    with-lock           run user command with lock held
    import-tar          Create a backup archive from a tarball
root@x86-master:/# 
```

### CODE REVIEW

**Comment by julienmalik** [comment]
Hi I believe this PR is ready.

Same error on the powerpc build as I had on https://github.com/openwrt/packages/pull/20265

**Comment by julienmalik** [comment]
@BKPepe  anything more I can do to get this PR merged ?

Thanks

**Comment by BKPepe** [comment]
I don't think that from your side there is anything to do, but I just need more time to look at it as I was quite busy these days... Hopefully, I will be able to look at it soon, no later than on Tuesday.

**Comment by asdil12** [comment]
Just ran into this issue - so: bump ;)

**Comment by BKPepe** [comment]
While running ``stdlib`` as described here https://github.com/openwrt/packages/blob/392a68e24774294590abf9c08ea1832f2cee190d/lang/python/README.md , I see that suggesed dependencies for bogbackup are:

- python3-codecs
- python3-logging
- python3-lzma
- python3-readline

For testsuite, it requires ``python3-unittest``, which should not be necessary to have by default for run testing, right?

**Comment by julienmalik** [comment]
Good catch thanks, I ignored this useful tool.
Verified in upstream source code that they indeed are direct dependencies.

**Comment by BKPepe** [comment]
There should be some commit description if it would be up to me.

**Comment by julienmalik** [comment]
More lengthy commit description added

**Comment by 1715173329** [comment]
@BKPepe I guess this should be backported to the 22.03 branch ;)

**Comment by BKPepe** [comment]
Yeah, it should. However, I did not do it, yet. Anyone can create PR

Dne st 12. 4. 2023 20:10 uživatel Tianling Shen ***@***.***>
napsal:

**Comment by 1715173329** [comment]
Well if you don't mind I can cherry-pick it later

**Comment by 1715173329** [comment]
235acacf0 borgbackup: bump to 1.2.4
31f36e5b2 borgbackup: add missing dependencies

**Pull request merged**
