### PR TITLE
build,travis: allow dash in package name

### PR DESCRIPTION
**Pull request by aparcar**

### CODE REVIEW

**Comment by dangowrt** [comment]
@lynxis

**Comment by champtar** [comment]
Hi @aparcar,
can you remove the ```\```

**Comment by aparcar** [comment]
@champtar done

**Comment by champtar** [comment]
Thanks

**Comment by pprindeville** [comment]
Aren't you supposed to make `-` the first character in the class for PCRE's?

**Comment by jow-** [comment]
@pprindeville - last position works too, but it must not appear between two chars in order to avoid it getting interpreted as range.

**Comment by pprindeville** [comment]
Okay. I was going by the Perl Best Practices.

**Pull request merged**
