### PR TITLE
python,python3: Add PYTHON_PKG_SETUP_DIR

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @commodo 
Compile tested: armvirt-32, 2019-02-20 snapshot sdk
Run tested: none

Description:
This adds a variable (`PYTHON_PKG_SETUP_DIR` / `PYTHON3_PKG_SETUP_DIR`) that allows a Python package Makefile to control the directory where `setup.py` is called (as part of `PyBuild/Compile/Default` / `Py3Build/Compile/Default`).

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
I also have a work-in-progress on this on this.
Since the #8244  discussion.

I wanted to do more testing before pushing more changes [related to this].

See here https://github.com/commodo/packages/commits/python-build-args

I was thinking of doing things similarly, with one small difference `PYTHON_PKG_SETUP_DIR:=` -> `PYTHON_PKG_SETUP_DIR ?= `
And doing commit https://github.com/commodo/packages/commit/cbbb3765263c77b44958f2c4036a3dc2d4227820 

So,  ack from my side for this :)

Could you also include https://github.com/commodo/packages/commit/cbbb3765263c77b44958f2c4036a3dc2d4227820   ?

**Comment by jefferyto** [comment]
If you have more changes you'd like to make, this can wait until you're ready and merge it all at once :smile:

**Comment by commodo** [comment]
ok
no more changes from me;

can you include patch https://github.com/commodo/packages/commit/cbbb3765263c77b44958f2c4036a3dc2d4227820  in here as well ?
you can also re-author it ; doesn't matter much to me :)

ack for this from my side

**Comment by commodo** [comment]
@hnyman 
this patch is fine from my side & can be merged

i'll add the other patch in an upcoming PR
it's not a blocker for this PR

thanks
Alex

**Comment by jefferyto** [comment]
@commodo Sorry been busy today. I’ll amend my commit and pull in yours as well, later tonight :joy:

@hnyman Please hold for a bit :laughing:

**Comment by jefferyto** [comment]
Done!

**Pull request merged**
