### PR TITLE
Emailrelay: enabled support for debug logging in order to have better log for investigating crashes

### PR DESCRIPTION
**Pull request by fededim**
Signed-off-by: Federico Di Marco <fededim@gmail.com>

### CODE REVIEW

**Comment by fededim** [comment]
The debug logging must explicitely be enabled by a command line switch of emailrelay (by default it's not), so this change is fine (it's just compilation support for debug logging)

**Comment by yousong** [comment]
I will give a NAK if this is only for debug purposes only.  Otherwise, please consider giving a size comparison before and after the change.

**Comment by fededim** [comment]
Yes, as I stated it's only for debug purposes or better for ENABLING better debugging (it enables the software to log more, the only drawback could be a lesser execution speed, but we are nit-picking here). I regarded this a useful change since it enables to better troubleshoot any problem arising while using the software (it crashes on some arch as stated in #https://github.com/openwrt/packages/issues/2401). If you are not willing to merge please close this pr.

**Comment by yousong** [comment]
Sorry for the delay, just back from holiday.

I would suggest adding a default off config option for enabling debug build of emailrelay, something like `CONFIG_EMAILRELAY_DEBUG` inside `Package/emailrelay/config`.

The reason is that there is no separate builds such as DEBUG or RELEASE in the current OpenWrt/LEDE world.  All builds are supposed to be ready for release purposes by default.   And the build infrastructure seems to be too scarce to produce packages just for debug purposes

**Comment by fededim** [comment]
Like "Adding configuration options" section in https://wiki.openwrt.org/doc/devel/packages ? Seems perfect to me.

**Comment by fededim** [comment]
I am closing this, I'll reopen a new one.

**Comment by fededim** [comment]
New PR with the change https://github.com/openwrt/packages/pull/3184

**Pull request closed without merging**
