### PR TITLE
micropython: Update to 1.22.2

### PR DESCRIPTION
**Pull request by nzmichaelh**
Update both micropython and micropython-lib.

Maintainer: @jefferyto 
Compile tested: rockchip_armv8 HEAD
Run tested: rockchip_armv8 HEAD. Ran and confirmed that it entered the REPL

Description:

Bump the micropython version to pick up the new asyncio SSL support.

### CODE REVIEW

**Comment by neheb** [comment]
Need to rebase

**Comment by feckert** [comment]
Superseded by https://github.com/openwrt/packages/pull/24664/files

**Comment by Neustradamus** [comment]
Replaces by:
- https://github.com/openwrt/packages/pull/24102
- https://github.com/openwrt/packages/pull/24664
- https://github.com/openwrt/packages/pull/25184

**Comment by Neustradamus** [comment]
Replaced by:
- https://github.com/openwrt/packages/pull/24102
- https://github.com/openwrt/packages/pull/24664
- https://github.com/openwrt/packages/pull/25184

Linked to:
- https://github.com/micropython/micropython/issues/14447

**Pull request closed without merging**
