### PR TITLE
Updated kismet and libnfc MAINTAINER

### PR DESCRIPTION
**Pull request by sourceindex**

### CODE REVIEW

**Comment by champtar** [comment]
Hi @sourceindex, your (last?) commits should start with the package name.
do you know anyone willing to take maintainership of this 2 packages

**Comment by sourceindex** [comment]
Hi, no i don know anyone.

Quoting champtar <notifications@github.com>:

**Comment by thess** [comment]
Unless someone volunteers to be the package maintainer and update the packages to versions more recent, I think this should be moved to the oldpackages repo.

**Comment by padre-lacroix** [comment]
I'll take kismet as the maintainer.
It will probably take me 2-3 weeks to get it done.

**Comment by padre-lacroix** [comment]
Of course, I'll get the latest version!

**Comment by padre-lacroix** [comment]
Work is progressing for kismet: I fixed the problem in issue #2978 in the 2013 package and got it to compile fine.  I am moving now to  the latest version of Kismet (July 2016).

**Comment by thess** [comment]
Closing this...
kismet - new MAINTAINER #3029 
libnfc - moved to packages-abandoned

**Pull request closed without merging**
