### PR TITLE
netatalk: bump to version 3.1.12

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/213c0e78fa   x86_64
Run tested: https://github.com/openwrt/openwrt/commit/213c0e78fa   x86_64

-----------------------------------------------------------------

This change upgrades the package to version 3.1.12.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
this build was tested on a clean checkout ;
this was done because of the `PKG_BUILD_DEPENDS:=libevent2` removal; i wasn't sure if removing this was fine or not

**Comment by commodo** [comment]
hmm; i wonder what went wrong locally, when i tested;
i'll re-add it

**Comment by commodo** [comment]
changelog v1->v2:
* added libevent2 back to PKG_BUILD_DEPENDS

**Comment by Neustradamus** [comment]
Updated by:
- https://github.com/openwrt/packages/pull/18687
- Backport: https://github.com/openwrt/packages/pull/18696

**Pull request merged**
