### PR TITLE
pciutils: Use MIPS16

### PR DESCRIPTION
**Pull request by neheb**
There's no real computation going on. Slims the package slightly.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @Noltari 
Compile tested: ramips

### CODE REVIEW

**Comment by diizzyy** [comment]
If you're going to micro-optimize packages at least bother to provide relevant data and do run-testing otherwise it's just adding to the pile of incomplete submissions.

**Comment by neheb** [comment]
Run tested on a TP-LINK WR-1043N.

**Comment by hnyman** [comment]
MIPS16 was explicitly disabled for this package in 2016 (but no real explanation given by @sbyx in 9f7ec5c8 )

In general, MIPS16 was disabled for quite many packages, as it caused hard-to-debug trouble for them. 

But has something changed since then, so that it would be safe to enable MIPS16 again for this pciutils?

**Comment by neheb** [comment]
mips16 failures change with every GCC version.

In my experience, they happen because of inline asm being used.

It doesn't look like pciutils uses any.

**Comment by diizzyy** [comment]
Can you please stop doing this, at least two persons have requested that you do run-testing which you ignored and went ahead merging anyway.

**Comment by neheb** [comment]
> 
> 
> Run tested on a TP-LINK WR-1043N.

**Comment by diizzyy** [comment]
@neheb 
I apologize, please update the commit message next time.

**Pull request merged**
