### PR TITLE
openldap: udpate to 2.6.0

### PR DESCRIPTION
**Pull request by flyn-org**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64
Run tested: x86_64

Description:

### CODE REVIEW

**Comment by feckert** [comment]
Can you look at this again the CI complains about the patchset not being able to apply it cleanly there.

**Comment by flyn-org** [comment]
I am now getting the following error:
```
libtool: Version mismatch error.  This is libtool 2.4.2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again.
```
I have tried a few incantations of PKG_FIXUP, but I have not figured out what is wrong yet. @neheb, might you know what is going wrong?

**Comment by neheb** [comment]
I'm assuming this is on Arch Linux or some derivative?

**Comment by flyn-org** [comment]
I am building on Fedora 35, and the buildbots seem to be generating the same error. Is that what you are asking?

**Comment by neheb** [comment]
maybe use PKG_REMOVE_FILES to get rid of some automake stuff.

**Comment by neheb** [comment]
PKG_REMOVE_FILES defaults to removing only aclocal.m4. No clue if that should be added here. autotools is arcanery to me.

doing a git grep in this repo shows

```
libs/cyrus-sasl/Makefile:PKG_REMOVE_FILES:=aclocal.m4 saslauthd/aclocal.m4 config/libtool.m4
libs/flac/Makefile:PKG_REMOVE_FILES:=autogen.sh aclocal.m4
libs/libatasmart/Makefile:PKG_REMOVE_FILES:=autogen.sh
libs/libndpi/Makefile:PKG_REMOVE_FILES:=autogen.sh
net/apinger/Makefile:PKG_REMOVE_FILES:=autogen.sh
net/bind/Makefile:PKG_REMOVE_FILES:=aclocal.m4 libtool.m4
net/httptunnel/Makefile:PKG_REMOVE_FILES:=autogen.sh
net/ksmbd-tools/Makefile:PKG_REMOVE_FILES:=autogen.sh
net/openssh/Makefile:PKG_REMOVE_FILES:=
net/rpcbind/Makefile:PKG_REMOVE_FILES:=autogen.sh aclocal.m4
utils/collectd/Makefile:PKG_REMOVE_FILES:=aclocal.m4 libltdl/aclocal.m4
utils/irqbalance/Makefile:PKG_REMOVE_FILES:=autogen.sh
```

No idea if that helps here.

**Comment by flyn-org** [comment]
@neheb and @feckert, that was a doozy, but I think I figured it out.

**Pull request merged**
