### PR TITLE
adblock: update 1.1.16

### PR DESCRIPTION
**Pull request by dibdot**
* new config option 'adb_restricted' to disable updates of the adblock
    config file during runtime (no flash writes, disabled by default)
* new update function, to apply latest configuration changes if needed (/etc/init.d/adblock cfgup)
* fix dns redirect rule
* various optimizations

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by hnyman** [comment]
Hmm. 
I noticed an issue when preparing the Luci app for the new option: Updating seem to function ok via console, but fails from luci due to "source download failed".

```
root@lede:/etc/config# /etc/init.d/adblock restart
adblock[17468] info : all adblock related services stopped
adblock[17643] info : domain adblock processing started (1.1.16, r489, 03.06.2016 17:06:37)
adblock[17643] info : backup/restore will be disabled
adblock[17643] info : created volatile IPv4 firewall ruleset
adblock[17643] info : created volatile IPv6 firewall ruleset
adblock[17643] info : created volatile uhttpd instance
adblock[17643] info : => processing adblock source 'adaway'
adblock[17643] info :    source download finished (410 entries)
adblock[17643] info :    domain merging finished
adblock[17643] info : => processing adblock source 'disconnect'
adblock[17643] info :    source download finished (5711 entries)
adblock[17643] info :    domain merging finished
adblock[17643] info : => processing adblock source 'yoyo'
adblock[17643] info :    source download finished (2395 entries)
adblock[17643] info :    domain merging finished
adblock[17643] info : remove duplicates in separate adblock lists
adblock[17643] info : adblock lists with overall 6123 domains loaded
adblock[17643] info : firewall statistics (IPv4/IPv6): 0/0 ad related packets blocked
adblock[17643] info : domain adblock processing finished successfully (1.1.16, r489, 03.06.2016 17:06:49)
```
Luci:
```
Fri Jun  3 17:07:09 2016 user.notice adblock[18014] info : all adblock related services stopped
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : domain adblock processing started (1.1.16, r489, 03.06.2016 17:07:10)
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : backup/restore will be disabled
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : created volatile IPv4 firewall ruleset
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : created volatile IPv6 firewall ruleset
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : created volatile uhttpd instance
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'adaway'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'disconnect'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'palevo'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'yoyo'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : adblock lists with overall 0 domains are still valid, no update required
Fri Jun  3 17:07:11 2016 user.notice adblock[18211] info : firewall statistics (IPv4/IPv6): 0/0 ad related packets blocked
Fri Jun  3 17:07:11 2016 user.notice adblock[18211] info : domain adblock processing finished successfully (1.1.16, r489, 03.06.2016 17:07:10)
```

**Comment by dibdot** [comment]
Ok, maybe released to early ... I'll try to fix that later this evening, sorry!
Am 03.06.2016 4:11 nachm. schrieb Hannu Nyman <notifications@github.com>:Hmm. 
I noticed an issue when preparing the Luci app for the new option: Updating seem to function ok via console, but fails from luci due to "source download failed".

root@lede:/etc/config# /etc/init.d/adblock restart
adblock[17468] info : all adblock related services stopped
adblock[17643] info : domain adblock processing started (1.1.16, r489, 03.06.2016 17:06:37)
adblock[17643] info : backup/restore will be disabled
adblock[17643] info : created volatile IPv4 firewall ruleset
adblock[17643] info : created volatile IPv6 firewall ruleset
adblock[17643] info : created volatile uhttpd instance
adblock[17643] info : => processing adblock source 'adaway'
adblock[17643] info :    source download finished (410 entries)
adblock[17643] info :    domain merging finished
adblock[17643] info : => processing adblock source 'disconnect'
adblock[17643] info :    source download finished (5711 entries)
adblock[17643] info :    domain merging finished
adblock[17643] info : => processing adblock source 'yoyo'
adblock[17643] info :    source download finished (2395 entries)
adblock[17643] info :    domain merging finished
adblock[17643] info : remove duplicates in separate adblock lists
adblock[17643] info : adblock lists with overall 6123 domains loaded
adblock[17643] info : firewall statistics (IPv4/IPv6): 0/0 ad related packets blocked
adblock[17643] info : domain adblock processing finished successfully (1.1.16, r489, 03.06.2016 17:06:49)


Luci:

Fri Jun  3 17:07:09 2016 user.notice adblock[18014] info : all adblock related services stopped
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : domain adblock processing started (1.1.16, r489, 03.06.2016 17:07:10)
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : backup/restore will be disabled
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : created volatile IPv4 firewall ruleset
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : created volatile IPv6 firewall ruleset
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : created volatile uhttpd instance
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'adaway'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'disconnect'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'palevo'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : => processing adblock source 'yoyo'
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    no online timestamp received, current date will be used
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info :    source download failed
Fri Jun  3 17:07:10 2016 user.notice adblock[18211] info : adblock lists with overall 0 domains are still valid, no update required
Fri Jun  3 17:07:11 2016 user.notice adblock[18211] info : firewall statistics (IPv4/IPv6): 0/0 ad related packets blocked
Fri Jun  3 17:07:11 2016 user.notice adblock[18211] info : domain adblock processing finished successfully (1.1.16, r489, 03.06.2016 17:07:10)

**Comment by dibdot** [comment]
Hannu,
this issue is unrelated to 1.1.16. The search path in LuCI is other than in a console session:
'which wget' in console delivers the correct binary '/usr/bin/wget'
'which wget' in LuCI environment delivers the wrong path 'bin/wget' which points to uclient-fetch

I can hardcoded that stuff again, but I'm sure this should be fixed in LuCI.

**Comment by hnyman** [comment]
@jow- 
Any ideas how to fix?

> this issue is unrelated to 1.1.16. The search path in LuCI is other than in a console session:
> 'which wget' in console delivers the correct binary '/usr/bin/wget'
> 'which wget' in LuCI environment delivers the wrong path '/bin/wget' which points to uclient-fetch

Is the wrong path coming into Luci from uhttpd?
maybe from here:
http://git.openwrt.org/?p=project/uhttpd.git;a=blob;f=main.c;h=fb2766576e8f84890dac44a9208cfaad3add0769;hb=HEAD#l180

    conf.cgi_path = "/sbin:/usr/sbin:/bin:/usr/bin";

That path should maybe be changed to match the current default path

**Comment by hnyman** [comment]
@dibdot 
I think that you should hardcode the wget path back, as the same path problem inside uhttpd is also in CC15.05 and Openwrt DD trunk. Even if uhttpd is fixed in the active LEDE (and Openwrt?) trunks, the CC15.05.1 users would still get the wrong path in Luci.

And yes, the problem lies with the path definition in uhttpd. I patched uhttpd to use the current default path and adblock can be restarted from Luci again ;-)
```
...
Fri Jun  3 20:13:27 2016 user.notice adblock[4508] info :    source download failed
Fri Jun  3 20:13:27 2016 user.notice adblock[4508] info : => processing adblock source 'disconnect'
Fri Jun  3 20:13:27 2016 user.notice adblock[4508] info :    no online timestamp received, current date will be used
Fri Jun  3 20:13:27 2016 user.notice adblock[4508] info :    source download failed
...
After patching the path and recompiling uhttpd:
...
Fri Jun  3 20:16:16 2016 user.notice adblock[5084] info : domain adblock processing started (1.1.15, r469, 03.06.2016 20:16:16)
Fri Jun  3 20:16:16 2016 user.notice adblock[5084] info : backup/restore will be disabled
Fri Jun  3 20:16:16 2016 user.notice adblock[5084] info : created volatile uhttpd instance
Fri Jun  3 20:16:16 2016 user.notice adblock[5084] info : => processing adblock source 'adaway'
Fri Jun  3 20:16:17 2016 user.notice adblock[5084] info :    source download finished (410 entries)
Fri Jun  3 20:16:18 2016 user.notice adblock[5084] info :    domain merging finished
Fri Jun  3 20:16:18 2016 user.notice adblock[5084] info : => processing adblock source 'disconnect'
Fri Jun  3 20:16:20 2016 user.notice adblock[5084] info :    source download finished (5711 entries)
...
```
Patch that I used for uhttpd:
```
perus@ub1604:/Openwrt/lede$ cat package/network/services/uhttpd/patches/100-fix-path.patch 
--- a/main.c
+++ b/main.c
@@ -177,7 +177,7 @@
 	conf.max_connections = 100;
 	conf.realm = "Protected Area";
 	conf.cgi_prefix = "/cgi-bin";
-	conf.cgi_path = "/sbin:/usr/sbin:/bin:/usr/bin";
+	conf.cgi_path = "/usr/sbin:/usr/bin:/sbin:/bin";
 	INIT_LIST_HEAD(&conf.cgi_alias);
 }
 
```

**Comment by dibdot** [comment]
#2809 fixed this issue

**Comment by hnyman** [comment]
Thanks for the fix. Adblock should now work normaly

But I think that devs should fix uhttpd, too. 
Having a different path passed from there will lead to unexpected things. The same default path has been applied to most of the places in the last few months, but hidden places where path is defined for apps & scripts still pop up :-(

http://git.openwrt.org/?p=project/uhttpd.git;a=blob;f=main.c;h=fb2766576e8f84890dac44a9208cfaad3add0769;hb=HEAD#l180

**Pull request merged**
