### PR TITLE
net/vnstat: Update to 1.18

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @jow- 
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

Description:
Update vnstat to 1.18

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by hnyman** [comment]
@jow-

**Comment by xdarklight** [comment]
Compile tested: lantiq, BT HomeHub 5A, OpenWrt master
Run tested: lantiq, BT HomeHub 5A, OpenWrt master

Tested-by: Martin Blumenstingl <martin.blumenstingl@googlemail.com>

**Comment by diizzyy** [comment]
@hnyman 
I think we can commit due to maintainer timeout, we should also probably look at the other vnstat related PRs that hasn't been committed too.

**Comment by diizzyy** [comment]
@jow- 
Ping?

**Pull request merged**
