### PR TITLE
znc: run as user znc & use procd

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Maintainer: @KanjiMonster
Compile tested: ar71xx, Archer C7 v2, LEDE r2158
Run tested: ar71xx, Archer C7 v2, LEDE r2158

Create & run znc as a specific user rather than nobody.  Converted to
use procd, removing dependencies on znc's 'droproot' module & 'su'

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

---

v3 - subtle tweaks to userid
       STOP removed

### CODE REVIEW

**Comment by KanjiMonster** [comment]
Thanks for giving it a second try. I was already thinking of pulling it in anyway.

> START moved to 99

Could you give a short explanation why?

**Comment by kdarbyshirebryant** [comment]
I'll try :-)  The thinking was that we should let everything settle and get set up before starting what I consider to be a lower priority service.  I sought guidance on IRC regarding preferred start/stop slots...and the answer was pretty much that it's a bun fight and sort of do what you please.  And then there's "it felt wrong starting znc before S98sysntpd".

**Comment by hnyman** [comment]
I think that originally "s95done" has been intended to be the last script there, as it e.g. runs /etc/rc.local, but the competition to be "the absolutely last" has pushed several scripts past that. I think that in any case this should be before that.

**Comment by kdarbyshirebryant** [comment]
Let me not add to the general melee of chaosness then and put it back where it was :-)  It wasn't causing any harm.

**Pull request merged**
