### PR TITLE
tcpreplay: update to version 4.2.5

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: LEDE v17.01.3, powerpc64
Run tested: LEDE v17.01.3, powerpc64

I had a ppc64 build around, and was more comfortable to test with that.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
```
The command "./.travis_do.sh download_sdk" failed and exited with 1 during .
```

**Comment by champtar** [comment]
Hi @commodo 
you can restart Travis by closing/reopening the PR, or by pushing a new commit

**Comment by commodo** [comment]
@champtar 
thanks for the tip ; i'll remember that  :)
i knew about the commit push, but i did not think of re-opening of the PR

**Comment by hnyman** [comment]
@champtar 
There may be something wrong with Travis checks for signing keys. All new PRs seem to cause Travis to fail SDK signature check, like above or in e.g. https://travis-ci.org/openwrt/packages/builds/288669780?utm_source=github_status&utm_medium=notification

**Comment by champtar** [comment]
Hi @hnyman 
real bug was SDK filename changed recently (https://github.com/openwrt/packages/commit/211f446d8d34f0954618cbdc67c587d13c517db7)
I also commited the keys into the repo so we never timeout again on `gpg --recv` (https://github.com/openwrt/packages/commit/867a5c91a113669a0ac190259e6323731393d9a4)

**Pull request merged**
