### PR TITLE
net/luci-app-acme: remove application

### PR DESCRIPTION
**Pull request by danrl**
Moved over to the LuCI repository.

Signed-off-by: Dan Luedtke <mail@danrl.com>

### CODE REVIEW

**Comment by danrl** [comment]
Depends on https://github.com/openwrt/luci/pull/1028

**Comment by champtar** [comment]
Closing this as there are conflicts right now
@danrl maybe some coordination with @tohojo ...

**Comment by danrl** [comment]
:( My motivation to do cleanups on cleanups is not the highest. I think it is in the package maintainers interest to have it in the right place, which is the packages repository. It has been five months(!) since the PR!  Not gonna do other people's homework.

Despite that, people so not seem to care much. So we might as well just live with some packages cluttered in space where they do not really belong.

**Comment by tohojo** [comment]
Having things "in the right place" is all well and good, but for packages like this where the luci and package sources are distributed together, splitting them just creates more work and potential for the two getting out of sync... I believe we've had this discussion before over the sqm-scripts package.

As for the 5 months wait, if you'd tagged me in the original pull request I would have been happy to NAK this five months ago... ;)

**Pull request closed without merging**
