### PR TITLE
Update libedit and Knot DNS

### PR DESCRIPTION
**Pull request by salzmdan**
Maintainer: @salzmdan
Compile tested: mpc85xx, OpenWRT 14.07
Run tested: mpc85xx, OpenWRT 14.07

Description:
 - Update libedit
 - Update Knot DNS

### CODE REVIEW

**Comment by champtar** [comment]
hi @salzmdan 
can you tests this PR (at least compile tests) with latest OpenWRT or LEDE
I'm asking because a lot of changes happened since 14.07, including switching from uclibc to musl

**Comment by salzmdan** [comment]
My fault, the system I use is OpenWRT 15.05.

**Comment by champtar** [comment]
Hi @salzmdan 
15.05 use uclibc, latest trunk use musl libc, can you at least test compile with latest trunk (OpenWRT or LEDE)
also please update your first message

**Comment by hnyman** [comment]
I compile-tested these with LEDE.

**Comment by salzmdan** [comment]
Thanks

**Pull request merged**
