### PR TITLE
node-mozilla-iot-gateway: Remove package

### PR DESCRIPTION
**Pull request by mrstegeman**
As the WebThings Gateway moves into a full-fledged router
distribution, it no longer makes sense to have this as a
standalone package, as it now modifies system-wide settings.

References #9629
References mozilla-iot/gateway#2060
References https://gitlab.labs.nic.cz/turris/turris-os-packages/issues/452

Signed-off-by: Michael Stegeman <michael@stegeman.me>

### CODE REVIEW

**Comment by neheb** [comment]
Open a pull request here as well: https://github.com/openwrt/packages-abandoned

**Comment by neheb** [comment]
ping @artynet @ratkaj

**Comment by mrstegeman** [comment]
> Open a pull request here as well: https://github.com/openwrt/packages-abandoned

Done: openwrt/packages-abandoned#5

**Comment by mrstegeman** [comment]
@ratkaj was on contract from Mozilla when he created and maintained the package. That contract has since lapsed.

**Comment by neheb** [comment]
Merging. Can you also make a pull request against the 19.07 branch? It doesn't make sense to have this in the next release.

**Comment by mrstegeman** [comment]
Done: #9680

**Pull request merged**
