### PR TITLE
[22.03] strongswan: backport fixes from 23.05

### PR DESCRIPTION
**Pull request by muzikr**
Maintainer: @pprindeville
Compile tested: mvebu, Turris Omnia, Turris OS 7 = OpenWrt 22.03
Run tested: mvebu, Turris Omnia, Turris OS 7 = OpenWrt 22.03, it runs

Description:
User complained about the error caused by non-existing reference to swanctl_append4. I was able to reproduce it and after noticing the second fix I reproduced also managed to reproduce it. After applying the fixes from 23.05 everything worked. 
Reference to our forum:
- https://forum.turris.cz/t/turris-os-7-0-is-in-rc/19755/20

### CODE REVIEW

**Comment by BKPepe** [comment]
ping @Thermi about this

**Comment by BKPepe** [comment]
Kind reminder guys. :)

**Comment by BKPepe** [comment]
@pprindeville , @Thermi any objections before I will merge this?

**Review by pprindeville — CHANGES_REQUESTED** [review]
Needs to pick up one more commit and I'll approve and merge it.  See previous comment.

**Pull request merged**
