### PR TITLE
Libmicrohttpd: add build variant for ssl + no-ssl + build parallel

### PR DESCRIPTION
**Pull request by lynxis**

### CODE REVIEW

**Comment by lynxis** [comment]
@friedzombie @dangowrt

**Comment by lynxis** [comment]
nodogsplash v2 would use the no-ssl package, because it's a lot smaller than a ssl.

**Comment by dangowrt** [comment]
I believe this is feasible, however, there are some issues with your patch.
Please review the inline-comments for https://github.com/lynxis/packages/commit/e6d6e574001f59acb64ef2673c4b62f5b7661366 and re-submit.

**Comment by champtar** [comment]
@friedzombie @dangowrt

**Comment by champtar** [comment]
@lynxis it's still OK to merge?

**Comment by lynxis** [comment]
sure.

**Comment by lynxis** [comment]
sorry. got confused by the upper merged symbol.

**Pull request merged**
