### PR TITLE
gnupg: update to 2.2.39

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update to latest LTS version.

Maintainer: @dangowrt 
Compile tested: tbd
Run tested: tbd

### CODE REVIEW

**Comment by dangowrt** [comment]
Please squash the *update to ...* commits into a single one, imho in this case there is no useful extra information added in the intermediate version steps.

**Comment by PolynomialDivision** [comment]
Done

**Comment by neheb** [comment]
I see two commits.

**Comment by PolynomialDivision** [comment]
The second adds a pkg-cpe-id.

**Pull request merged**
