### PR TITLE
[21.02] nextdns: Update to version 1.38.0

### PR DESCRIPTION
**Pull request by rs**
Update to version 1.38.0

### CODE REVIEW

**Comment by BKPepe** [comment]
From CI:
```
Testing package nextdns in version 1.[38](https://github.com/openwrt/packages/actions/runs/3481012407/jobs/5821551353#step:12:39).0 from nextdns
Installing nextdns (1.38.0-1) to root...
system not supported
Collected errors:
 * pkg_run_script: package "nextdns" postinst script returned status 2.
 * opkg_configure: nextdns.postinst returned 2.
Configuring nextdns.
No test.sh script available
Removing package nextdns from root...
system not supported
Collected errors:
 * pkg_run_script: package "nextdns" prerm script returned status 1.
```

There is something wrong with the postinst sand prerm scripts. Unfortunately, you removed PR template, which says that it was compile and run tested.

**Comment by 1715173329** [comment]
ping @rs

**Comment by 1715173329** [comment]
#19315 hmmm interesting

**Comment by rs** [comment]
Yes this was a recent change. Does it cause issues?

**Comment by 1715173329** [comment]
> Yes this was a recent change. Does it cause issues?

No, 21.02 lacks this change. But why it says "system not supported"

**Comment by rs** [comment]
This would come from init system detection. Is there anything changed that would make the following condition true: https://github.com/nextdns/nextdns/blob/4991133ed6f6b0c8a6e55fb932a0c67b4c1de42d/host/service/procd/service.go#L22 ?

**Comment by 1715173329** [comment]
> This would come from init system detection. Is there anything changed that would make the following condition true: https://github.com/nextdns/nextdns/blob/4991133ed6f6b0c8a6e55fb932a0c67b4c1de42d/host/service/procd/service.go#L22 ?

Thanks for the clarification. In docker pid 1 is `sh` so it fails, but will work on real system.

btw, please remember to create PRs for the 22.03 branch.

**Comment by rs** [comment]
Next release will get 22.03

**Pull request merged**
