### PR TITLE
https-dns-proxy:  Version bump to latest git version.

### PR DESCRIPTION
**Pull request by aarond10**
Signed-off-by: Aaron Drew <aarond10@gmail.com>

Maintainer: Aaron Drew <aarond10@gmail.com>
Compile tested: MIPS, Archer C7

### CODE REVIEW

**Comment by dibdot** [comment]
@aarond10 Please update your PR (after merging #6853) - thanks.

**Comment by aarond10** [comment]
Done. Sorry about the delay!

**Comment by dibdot** [comment]
You don't change the PKG_VERSION in your latest PR, is that intended?

**Comment by aarond10** [comment]
Whoops! Sorry. Try now.

**Comment by dibdot** [comment]
Thanks!

**Comment by dibdot** [comment]
This PR still tries to update an older source: current PKG_RELEASE is "3", should be "1" after your version bump.

**Comment by aarond10** [comment]
Sorry. Lots of rushed commit --amend's of late. ;(

**Comment by dibdot** [comment]
Still conflicting source - maybe you should start with a fresh checkout ...

**Comment by aarond10** [comment]
OK. I'm not sure what I've done here. pull, fix merge, update, .. I'll just
abandon this and try again. Apologies.

**Pull request closed without merging**
