### PR TITLE
Python pip cleanups

### PR DESCRIPTION
**Pull request by commodo**
Reduce some bloat by removing some Windows binaries; maybe a bigger effort would be in order to reduce bloat; will plan for later.
Fix conflicts with python-setuptools; thanks @Xuefer <xuefer@gmail.com> for reporting

Note: please merge this after PR https://github.com/openwrt/packages/pull/740

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by sbyx** [comment]
@commodo I'm seeing a bit of fallout from your changes.

If you have some time could you please have a look at:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/seafile-seahub/compile.txt
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/python-pip/compile.txt
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/python-mysql/compile.txt

**Comment by commodo** [comment]
will check asap;
it's weird I did not see it locally;
I guess a full clean-build would be in order to try

**Comment by xuefer** [comment]
that's why one shouldn't copy files directly into staging directory, your
staging_directory is a little bit messed up now. please don't go back to
copy directly and you'll find it is required to use my method

**Comment by commodo** [comment]
Created PR https://github.com/openwrt/packages/pull/754
The root cause is the Host Python.
The issue with the Host Python: seems the `_ctypes.so` module does not get built properly for the Python binary in the host-side, so `python-setuptools` does not get built properly.

Also, this change  https://github.com/openwrt/packages/commit/16f53ee9c84eb553ae125bcfc0e6a45650085634   was incorrectly done by me when I copied it from Xuefer.

I'll address the Host Python `_ctypes.so` issue later.
For now this PR fixes `python-setuptools` such that it installs.

**Comment by xuefer** [comment]
do you have any solution to keep using $(1) or $(2) in InstallDev? it's
rule breaker without $(1) or $(2) IMHO
>
>

**Comment by commodo** [comment]
well,
I do have a plan; I was thinking of starting a discussion on this.
I guess now is a good time as any other.

1. One idea is to drop python-setuptools && python-pip packages in favour of the embedded `pip` that's in Python. (since 2.7.9 it's also in Python; https://pip.pypa.io/en/latest/installing.html#pip-included-with-python ); the idea is to use that `pip` version; that way, only 1 package needs to be maintained (Python).
2. If I don't do 1. then I will do another cleanup when I upgrade python-setuptools && python-pip. Seems the versioning of these packages has changed

I did notice that there's a package that uses `python-setuptools` during the build.
I think that we could use the embedded `pip` module in Python the same as the python-setuptools or python-pip package.

**Pull request merged**
