### PR TITLE
ksmbd-tools: update to 3.5.1

### PR DESCRIPTION
**Pull request by neheb**
Various fixes for ksmbd, most notably a visibility fix for the latest ksmbd code.

ping @sppmasterspp

### CODE REVIEW

**Comment by pesa1234** [comment]
Thanks

**Comment by sppmasterspp** [comment]
Yes, recompiled this morning with latest changes and all is OK.
The issue is fixed. Thanks a lot guys.

**Comment by termomaks** [comment]
> Thanks, I have also made a beauty change on luci-app-ksmbd to load correct version

Just want to ask if this is the beauty change You've made?
image

**Comment by sppmasterspp** [comment]
> Thanks, I have also made a beauty change on luci-app-ksmbd to load correct version

Just want to ask if this is the beauty change You've made to luci?
image

**Comment by pesa1234** [comment]
Yes, to solve 3.5.1/?

**Comment by sppmasterspp** [comment]
> Yes, to solve 3.5.1/?

Probably `luci-app-ksmbd | git-24.009.38584-9b56e2d` doesn't include the latest changes yet?

**Comment by pesa1234** [comment]
> > Yes, to solve 3.5.1/?
> 
> Probably `luci-app-ksmbd | git-24.009.38584-9b56e2d` doesn't include the latest changes yet?

Yes, still not merged.

**Pull request merged**
