### PR TITLE
[openwrt-23.05] easyloggingpp: Add package

### PR DESCRIPTION
**Pull request by VolkerChristian**
Maintainer: [me@vchrist.at](mailto:me@vchrist.at)
Compile tested: OpenWRT-23.05-rc2, arm_cortex-a7_neon-vfpv4, mips_24kc
Run tested: arm_cortex-a7_neon-vfpv4 (Linksys MR8300), mips_24kc (tplink_archer-a7), OpenWrt 23.05-rc2)

Description:
Easylogging++ is single header efficient logging library for C++ applications. It is extremely powerful, highly extendable and configurable to user's requirements.

### CODE REVIEW

**Comment by 1715173329** [comment]
Please use `git cherry-pick -x <commit hash>` to backport changes from the master branch. The same applies to your other PR-s.

**Comment by VolkerChristian** [comment]
> Please use `git cherry-pick -x <commit hash>` to backport changes from the master branch. The same applies to your other PR-s.

@1715173329: Thank you for the hint. This absolutely make sense!
This is the first time I am contributing to OpenWRT and I am learning by reading and doing. So this will not happen anymore!
I also updated my other PRs. I hope they are OK now!

Kind regards
Volker

**Comment by 1715173329** [comment]
Thank you for quick response.
Please keep the last line which is appended by `-x` argument: `(cherry picked from commit 123456)`
so we can track these commits (from master branch to stable branch).

**Comment by VolkerChristian** [comment]
So, now the commit messages also contain the line "cherry picked from commit *". Thank you again!

**Comment by BKPepe** [comment]
Great! :) Merged.

**Pull request merged**
