### PR TITLE
nbd: bump to 3.16.2

### PR DESCRIPTION
**Pull request by marcin1j**
Maintainer: me
Compile tested: ar71xx, TP-LINK TL-WR842, r5104
Run tested: ar71xx, TP-LINK TL-WR842, r5104 (tested nbd-server and nbd-client)

Description:
Upgrade nbd to version 3.16.2.

### CODE REVIEW

**Comment by hnyman** [comment]
Looks like buildbot finds a missing dependency.
http://downloads.lede-project.org/snapshots/faillogs/mips_24kc/packages/nbd/compile.txt
```
Package nbd is missing dependencies for the following libraries:
libgnutls.so.30
Makefile:71: recipe for target '/build/lede-snapshots/mips_24kc/build/sdk/bin/packages/mips_24kc/packages/nbd_3.16.2-1_mips_24kc.ipk' failed
```
If gnutls is not needed for the package's functionality, please look into the package's configure options and disable gnutls usage

**Comment by marcin1j** [comment]
Gnutls is not needed. I'll check and fix this. Am I correct that it's necessary to open a new pull request to merge above-mentioned fix?

**Comment by hnyman** [comment]
Yes, you need to open a new PR. 

(alternatively, it might be also possible to push a second commit into this branch, but I should then manually pick it as a patch and push separately.)

**Comment by marcin1j** [comment]
@hnyman I've opened PR #5014

**Pull request merged**
