### PR TITLE
snort3: new package

### PR DESCRIPTION
**Pull request by MikePetullo**
Maintainer: me
Compile tested: x86_64
Run tested: x86_64

Description:
snort3: new package

### CODE REVIEW

**Comment by diizzyy** [comment]
@MikePetullo 
Can you do a rebase of this? I'd like to see a clean run before merging

**Comment by MikePetullo** [comment]
@diizzyy, I pushed again after pulling in the libdaq 2.2.2 merge.

From what I can tell, the build failure from CircleCI has something to do with building luajit on the build host. See below and the mention of cdefs.h in https://wiki.musl-libc.org/faq.html. I do not have the same problem when I build on my computer.

/home/build/build_dir/scripts/ipkg-build -c -o 0 -g 0 /home/build/build_dir/build_dir/target-mips_24kc_musl/linux-firmware-2018-12-16-211de167/ipkg-mips_24kc/ath10k-firmware-qca6174 /home/build/build_dir/bin/packages/mips_24kc/base
In file included from /usr/include/limits.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:168,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:34,
                 from host/minilua.c:33:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
Makefile:691: recipe for target 'host/minilua.o' failed
make[4]: *** [host/minilua.o] Error 1
make[4]: Leaving directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/LuaJIT-2.1.0-beta3/src'

**Comment by neheb** [comment]
That issue has to do with missing 32-bit libraries on the build host. It won't be built properly.

**Comment by neheb** [comment]
Merging. This will show up as a failure in the buildbot, but that's inevitable. At least until the buildbots get 32-bit gcc libraries installed.

**Pull request merged**
