### PR TITLE
knxd: follow new respository

### PR DESCRIPTION
**Pull request by tru7**
Signed-off-by: Othmar Truniger <github@truniger.ch>

### CODE REVIEW

**Comment by mhei** [comment]
Please use https URLs for fetching the sources, using git could result in stalling the buildbots as there might be a new SSH host key which needs to be accepted (manually).

While at, I think we could streamline the Makefile a little bit:
- Build/Prepare seems to do nothing special, can we just remove it?
- Build/Configure can also be omitted when using CONFIGURE_ARGS
- there are also variable EXTRA_CPPFLAGS and EXTRA_LDFLAGS, when using these you can streamline Build/Compile I guess
- `rm -f ...` followed by `ln -s ...` can be simplified to `ln -sf ...` ?

Does the commit id you refered to compiles for you? I checked out it on my host system and have problems to bootstrap the project. So I wonder whether cross compiling will succeed... (might be a problem with my ancient Kubuntu system...)

**Comment by tru7** [comment]
Thank you for your suggestions. I'm not a very experienced maintainer. About 6 years ago I just took a copy of the Makefile and built the package like that for knxd's predecessor eibd without significant changes. When knxd was forked from eibd and because openwrt/packages allows an easy way to add new packages I decided to place my first pull request which got accepted after about the third attempt.
Yes it compiles without problems on my Ubuntu 14.04.2. knxd is work in progress and I will pull new requests from time to time. How about merging this id and I will incorporate your valid suggestions for the next release?

**Comment by mhei** [comment]
Fine with me. I think I could also create a "RFC PR" with my suggested changes.

**Comment by tru7** [comment]
Thanks for merging. Good idea with the RFC, maybe add it to the wiki as special hints. I checked your suggestions with examples of other Makefiles and I basically already have my things together for next version.

**Pull request merged**
