### PR TITLE
mdio-tools: Add package plus kernel module

### PR DESCRIPTION
**Pull request by dmascord**
mdio is a low-level Linux debug tool for communicating with devices attached an MDIO bus. It improves on existing tools in this space in a few important ways:

MDIO buses are directly addressable. Previous solutions relied on at least one Ethernet PHY on the bus being attached to a net device, which is typically not the case when the device is an Ethernet switch for example.
Complex operations can be performed atomically. The old API only supported a single read or write of a single register. mdio sends byte code to the mdio-netlink kernel module that can perform multiple operations, store intermediate values, loop etc. As a result, things like read/mask/write operations and accesses to paged PHYs can be performed safely.

Signed-off-by: Damien Mascord <tusker@tusker.org>

Maintainer: me
Compile tested: ipq806x, Extreme Networks WS-AP3935i-ROW, r17102-aaf4e45f25
Run tested:  ipq806x, Extreme Networks WS-AP3935i-ROW, r17102-aaf4e45f25, mdio bus gpio-0

Description:
As above.  Used to identify what phy connections are actually ethernet devices, which is necessary when the factory DTS is not available.

This is dependent on https://github.com/openwrt/openwrt/pull/4358 for 5.4.x

### CODE REVIEW

**Comment by mhei** [comment]
Hm, quickly run-tested on a Duckbill (mxs platform):
```
root@OpenWrt:/# uname -a
Linux OpenWrt 5.10.46 #0 Fri Jul 2 19:50:12 2021 armv5tejl GNU/Linux
root@OpenWrt:/# mdio
Segmentation fault
root@OpenWrt:/# lsmod
fat                    65536  1 vfat
leds_gpio              16384  0
ledtrig_activity       16384  0
ledtrig_oneshot        16384  0
ledtrig_transient      16384  0
mdio_netlink           16384  0
nls_cp437              16384  0
nls_iso8859_1          16384  0
nls_utf8               16384  0
realtek                16384  0
snd                    49152  8 snd_rawmidi,snd_seq_device,snd_pcm_oss,snd_mixer_oss,snd_hwdep,snd_compress,snd_pcm,snd_timer
snd_compress           20480  0
snd_hwdep              16384  0
snd_mixer_oss          24576  1 snd_pcm_oss
snd_pcm                81920  2 snd_pcm_oss,snd_compress
snd_pcm_oss            45056  0
snd_rawmidi            28672  0
snd_seq_device         16384  1 snd_rawmidi
snd_timer              28672  1 snd_pcm
soundcore              16384  1 snd
tun                    40960  0
vfat                   20480  0
root@OpenWrt:/# strace mdio
execve("/usr/bin/mdio", ["mdio"], 0xbec85e90 /* 8 vars */) = 0
set_tls(0xb6f4a5d8)                     = 0
set_tid_address(0xb6f4b18c)             = 1399
open("/etc/ld-musl-arm.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libmnl.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libmnl.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libmnl.so.0", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0755, st_size=13588, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0p\26\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 81920, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6eae000
mmap2(0xb6ec0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0xb6ec0000
close(3)                                = 0
open("/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=50452, ...}) = 0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0XF\0\0004\0\0\0"..., 936) = 936
mmap2(NULL, 118784, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e91000
mmap2(0xb6eac000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xb000) = 0xb6eac000
close(3)                                = 0
mprotect(0xb6ec0000, 4096, PROT_READ)   = 0
mprotect(0xb6eac000, 4096, PROT_READ)   = 0
mprotect(0x23000, 4096, PROT_READ)      = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
fork()                                  = 1400
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(1400, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 1400
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1400, si_uid=0, si_status=0, si_utime=1, si_stime=1} ---
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x124062} ---
+++ killed by SIGSEGV +++
Segmentation fault
root@OpenWrt:/#
```
Do you see, what I've missed?

**Comment by dmascord** [comment]
Let me try some run tests on some other hardware, and I will get back to you

**Comment by dmascord** [comment]
Testing on mvebu:

```
root@wrt1900:~# mdio
Usage: mdio [OBJ] OP

Operations:

  bus [BUS]
    If BUS is specified, scan the bus and show all attached PHYs.
    If BUS is omitted, list all buses on the system. Uses glob(3)
    matching to locate bus, i.e. "fixed*" would typically match
    against "fixed-0".

  help
    Show this usage message.

  OBJ dump [RANGE]
    Dump multiple registers from OBJ. If no range is specified, dump 64
    registers or until the end of the device, whichever comes first.

  OBJ raw REG [VAL[/MASK]]
    Raw register access. Without VAL, REG is read. An unmasked VAL will
    do a single write to REG. A masked VAL will perform a read/mask/write
    sequence.

Objects:

  phy BUS PORT[:DEV]
    Operate on standard PHY attached to BUS using either Clause 22 (PORT)
    or Clause 45 (PORT:DEV) addressing.

    REG: u5|u16 (Clause 22, Clause 45)
    VAL: u16

  mvls BUS ID
    Operate on Marvell LinkStreet (mv88e6xxx) device attached to BUS
    using address ID. If ID is 0, single-chip addressing is used; all
    other IDs use multi-chip addressing.

    REG: u5|"global1"|"global2" u5
    VAL: u16

  xrs BUS ID
    Operate of Arrow/Flexibilis XRS700x device attached to BUS using
    address ID.

    REG: u32 (Stride of 2, only even registers are valid)
    VAL: u16
root@wrt1900:~# mdio bus
f1072004.mdio-mii
fixed-0
mv88e6xxx-1
root@wrt1900:~#
```

**Comment by dmascord** [comment]
Let me test on 5.10.x on mvebu next

**Comment by dmascord** [comment]
OK, works the same on mvebu on 5.10.x:
root@wrt1900:~# uname -a
Linux wrt1900 5.10.46 #0 SMP Thu Jul 15 05:15:43 2021 armv7l GNU/Linux
root@wrt1900:~# mdio
Usage: mdio [OBJ] OP

Operations:

  bus [BUS]
    If BUS is specified, scan the bus and show all attached PHYs.
    If BUS is omitted, list all buses on the system. Uses glob(3)
    matching to locate bus, i.e. "fixed*" would typically match
    against "fixed-0".

  help
    Show this usage message.

  OBJ dump [RANGE]
    Dump multiple registers from OBJ. If no range is specified, dump 64
    registers or until the end of the device, whichever comes first.

  OBJ raw REG [VAL[/MASK]]
    Raw register access. Without VAL, REG is read. An unmasked VAL will
    do a single write to REG. A masked VAL will perform a read/mask/write
    sequence.

Objects:

  phy BUS PORT[:DEV]
    Operate on standard PHY attached to BUS using either Clause 22 (PORT)
    or Clause 45 (PORT:DEV) addressing.

    REG: u5|u16 (Clause 22, Clause 45)
    VAL: u16

  mvls BUS ID
    Operate on Marvell LinkStreet (mv88e6xxx) device attached to BUS
    using address ID. If ID is 0, single-chip addressing is used; all
    other IDs use multi-chip addressing.

    REG: u5|"global1"|"global2" u5
    VAL: u16

  xrs BUS ID
    Operate of Arrow/Flexibilis XRS700x device attached to BUS using
    address ID.

    REG: u32 (Stride of 2, only even registers are valid)
    VAL: u16
root@wrt1900:~# mdio bus
f1072004.mdio-mii
fixed-0
mv88e6xxx-1

**Comment by dmascord** [comment]
That looks like the fork to modprobe fails... could you try with commenting out the mdio_modprobe() in main.c ?

**Comment by mhei** [comment]
Yes, will try to dig into this today evening... did not found time yet to do...

**Comment by mhei** [comment]
Odd, I copied sources to my target embedded board and did a native build on target platform. The so generated binary works well. So, seems to be an issue with my OpenWrt build system, or a cross-compile issue (specific to my platform)... will more investigate...

**Comment by mhei** [comment]
I tried to track this down, and it seems that `memset` in `mnl_nlmsg_put_extra_header` fails. Not yet sure why...

**Comment by dmascord** [comment]
Could it be related to "libmnl: fix valgrind warnings about padding - Patchwork" http://patchwork.ozlabs.org/project/netfilter-devel/patch/20120418113327.3d26501b@nehalam.linuxnetplumber.net/

**Comment by mhei** [comment]
I added the following lines in mdio_init before mnl_nlmsg_put_extra_header:

printf("nlh->nlmsg_len   (%08x): 0x%x\n",          (int)&nlh->nlmsg_len,   nlh->nlmsg_len);
printf("nlh->nlmsg_type  (%08x): 0x%hx, 0x%04x\n", (int)&nlh->nlmsg_type,  nlh->nlmsg_type, GENL_ID_CTRL);
printf("nlh->nlmsg_flags (%08x): 0x%hx, 0x%04x\n", (int)&nlh->nlmsg_flags, nlh->nlmsg_flags, NLM_F_REQUEST | NLM_F_ACK);
printf("nlh->nlmsg_seq   (%08x): 0x%x\n",          (int)&nlh->nlmsg_seq,   nlh->nlmsg_seq);
printf("nlh->nlmsg_pid   (%08x): 0x%x\n",          (int)&nlh->nlmsg_pid,   nlh->nlmsg_pid);

Output when running on target:
nlh->nlmsg_len   (00025062): 0x100000
nlh->nlmsg_type  (00025066): 0x5, 0x0010
nlh->nlmsg_flags (00025068): 0x0, 0x0005
nlh->nlmsg_seq   (0002506a): 0x0
nlh->nlmsg_pid   (0002506e): 0x0

Not the expected behavior. Adding alignment attribute to buf variable
solves this problem, then the output is:

nlh->nlmsg_len   (00025064): 0x10
nlh->nlmsg_type  (00025068): 0x10, 0x0010
nlh->nlmsg_flags (0002506a): 0x5, 0x0005
nlh->nlmsg_seq   (0002506c): 0x0
nlh->nlmsg_pid   (00025070): 0x0

I filed a PR in upstream project.

**Comment by mhei** [comment]
Regarding the above, I'd wait a little bit for upstream comments on the PR: if it is merged, please update this PR with new commit id.
In your updated PR here, I think the mirror hash is still wrong: when the build systems downloads from git and created a tar ball, then on my machine then hash is:
```
$ sha256sum dl/mdio-tools-2021-07-02-9f989622.tar.xz
110cdccbdd4427b626e155c2ca77bd6cdd85deb60b6dd86d910bab2a8aaede3c  dl/mdio-tools-2021-07-02-9f989622.tar.xz
```

And a minor nitpick: in mdio-netlink/Makefile there seems to be surplus empty lines and end of file, please remove.

Other than that, it looks good and we could approve running the CI workflows.

**Comment by dmascord** [comment]
Hi,

Looks like #4358 is committed already, could we progress on this now ?

Cheers,

Damien

**Comment by AiyionPrime** [comment]
Hitting a builderror, any idea, what I'm doing wrong?
https://bpa.st/JAVQ

**Comment by dmascord** [comment]
Need to grab latest master to get commit 8e10b0181cf63f969705db6054ab0c16331069cf

**Comment by AiyionPrime** [comment]
Outdated master it was; indeed.

**Comment by AiyionPrime** [comment]
Just wanted to follow up: I successfully built this on yesterdays master and used the tool.

**Pull request merged**
