### PR TITLE
Docker: Update to 23.0.1

### PR DESCRIPTION
**Pull request by G-M0N3Y-2503**
Maintainer: me @G-M0N3Y-2503
Compile tested: x86_x64, QEMU/KVM, master
Run tested: x86_x64, QEMU/KVM, master

Description:
Updated docker to v23.0.1 and required dependencies

### CODE REVIEW

**Comment by trippleflux** [comment]
@G-M0N3Y-2503 
Thanks but getting : 
```
INFO[2023-03-04T20:01:21.539836721+07:00] [core] [Channel #7] Channel Connectivity change to IDLE  module=grpc
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.9 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))

[1]+  Done(1)                    dockerd
```

Perhaps related but I have updated my iptables package with the following [PR](https://github.com/openwrt/openwrt/pull/12106).

**Comment by G-M0N3Y-2503** [comment]
> @G-M0N3Y-2503 Thanks but getting :
> 
> ```
> INFO[2023-03-04T20:01:21.539836721+07:00] [core] [Channel #7] Channel Connectivity change to IDLE  module=grpc
> failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.9 (nf_tables): Chain 'MASQUERADE' does not exist
> Try `iptables -h' or 'iptables --help' for more information.
>  (exit status 2))
> 
> [1]+  Done(1)                    dockerd
> ```
> 
> Perhaps related but I have updated my iptables package with the following [PR](https://github.com/openwrt/openwrt/pull/12106).
> 
> On x86_64

I was able to do basic tests with fw3 and fw4 (without networking on fw4). 
perhaps it is related to the changes in that PR.

**Comment by zdz2019** [comment]
please add a line:
$(INSTALL_BIN) $(PKG_BUILD_DIR)/bundles/binary-daemon/docker-proxy $(1)/usr/bin/

**Comment by trippleflux** [comment]
@zdz2019 

Hmm, still getting the same error : 
```

INFO[2023-03-05T19:13:30.984237913+07:00] [core] [Channel #7] Channel Connectivity change to IDLE  module=grpc
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.9 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))

[1]+  Done(1)                    dockerd
```

Is there any specific workflow for docker-proxy?

**Comment by zdz2019** [comment]
> @zdz2019
> 
> Hmm, still getting the same error :
> 
> ```
> 
> INFO[2023-03-05T19:13:30.984237913+07:00] [core] [Channel #7] Channel Connectivity change to IDLE  module=grpc
> failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.9 (nf_tables): Chain 'MASQUERADE' does not exist
> Try `iptables -h' or 'iptables --help' for more information.
>  (exit status 2))
> 
> [1]+  Done(1)                    dockerd
> ```
> 
> Is there any specific workflow for docker-proxy?

docker-proxy is called automatically, I think the problem is with the iptables version.
I use iptables 1.8.7 to test fine.

**Comment by G-M0N3Y-2503** [comment]
> @zdz2019
> 
> Hmm, still getting the same error :
> 
> ```
> 
> INFO[2023-03-05T19:13:30.984237913+07:00] [core] [Channel #7] Channel Connectivity change to IDLE  module=grpc
> failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.9 (nf_tables): Chain 'MASQUERADE' does not exist
> Try `iptables -h' or 'iptables --help' for more information.
>  (exit status 2))
> 
> [1]+  Done(1)                    dockerd
> ```
> 
> Is there any specific workflow for docker-proxy?

If I were to guess, I'l think that removing [this patch](https://github.com/openwrt/openwrt/pull/12106/files#diff-5567644d1866b3e72b9870732733f604944dec1e7b791c6b4915e94e35d92b67) is making the MASQUERADE target to fail loading.
If you aren't using fw3 or aren't using iptables anyway, you can just disable iptables support with the `iptables` option in the config for now.

**Comment by trippleflux** [comment]
@G-M0N3Y-2503 

You are referring into [060-libxtables-unexport-init_extensions-declarations.patch](https://github.com/openwrt/openwrt/pull/12106/files#diff-5567644d1866b3e72b9870732733f604944dec1e7b791c6b4915e94e35d92b67) ?

does luci's dockerman is also using iptables?

**Comment by trippleflux** [comment]
@G-M0N3Y-2503 
Confirmed, still working on iptables 1.8.8

But luci's dockerman is not working for overview page : 
```
/usr/lib/lua/luci/ucodebridge.lua:14: /usr/lib/lua/luci/model/cbi/dockerman/overview.lua:53: bad argument #1 to 'ipairs' (table expected, got nil)

In h(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:14)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function [arrow function] (/usr/share/ucode/luci/dispatcher.uc:794:4)
  called from function render ([C])
  called from function render_action (/usr/share/ucode/luci/dispatcher.uc:768:24)
  called from function run_action (/usr/share/ucode/luci/dispatcher.uc:795:4)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:998:48)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^
```

**Comment by 1715173329** [comment]
mips build failed.. is it by design or a bug?

**Comment by G-M0N3Y-2503** [comment]
> mips build failed.. is it by design or a bug?

It seems that buildkit doesn't really support mips yet, So I'll have to figure out how to disable mips for now.

**Pull request merged**
