### PR TITLE
nft-qos: Update init script

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @rosysong 
Compile tested: armvirt-32, 2019-02-12 snapshot sdk
Run tested: none

Description:
This replaces the use of `uci_validate_section()` with `uci_load_validate()`, which removes the need to declare local variables for every config option.

This also adds a validate section to `service_triggers()`, and fixes some variable name typos in `qosdef_init_static()`.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I tried run-testing this (using the default config), but other than seeing no error messages, I didn't get any other feedback.

**Comment by rosysong** [comment]
I think you'd better have a run test for this.

**Comment by rosysong** [comment]
@jefferyto did you test all the functionalities including static/dynamic/priority/hotplug(monitor/dynamic) ?

**Comment by jefferyto** [comment]
As I mentioned, I only tested this using the default config (and saw no error messages). I assume this doesn't cover all of the functionality of the script/package.

`uci_validate_section()` doesn't just validate the config data; it also assigns that data to script variables. (This is why you didn't need to call `config_get()` to load that data.) `uci_load_validate()` wraps `uci_validate_section()` and automatically declares the variables as local so the calling script doesn't have to.

Regarding the static qos variables, the config options (in files/nft-qos.config) are `static_unit_dl`, `static_unit_ul`, `static_rate_dl`, and `static_rate_ul`. The validation data passed to `uci_validate_section()` is for `static_unit_dl`, `static_unit_ul`, etc.. Therefore, `uci_validate_section()` assigns these values to variables named `static_unit_dl`, `static_unit_ul`, etc.

The variables `qosdef_init_static()` used previously (`unit_dl`, `unit_ul`, `rate_dl`, and `rate_ul`) would not have any values assigned to them by `uci_validate_section()`. If this is not correct, please let me know and I will look into it further.

**Comment by rosysong** [comment]
@jefferyto  @jow-  ACK! Tested on ar71xx, wr818

**Pull request merged**
