### PR TITLE
protobuf: Update version to 2.6.1

### PR DESCRIPTION
**Pull request by guillaume-d**
- Unbroke MIPS support which got entirely lost since the upgrade from 2.4.1:
  now all ISAs should work (MIPS1 would need kernel emulation though, untested)
- Fixed host installation which was broken on all targets
- Updated source origin to github and related variables
- Kept mipseb patch exception and MIPS16:=0 exclusion (needed for BB and CC compilation)

For rationale and earlier patch history please refer to OpenWrt-Devel's "protobuf broken in BB" thread starting at: https://lists.openwrt.org/pipermail/openwrt-devel/2014-November/thread.html#29108 and continued in Mai 2015.

Only tested on a ZyXEL NBG6716 router which is MIPS32 (MIPS74Kc), ar71xx target.

Signed-off-by: Guillaume Déflache <guillaume.deflache@ibwag.com>

### CODE REVIEW

**Comment by thess** [comment]
* Please supply missing PKG_LICENSE and PKG_LICENSE_FILES info.
* Copyright needs updating.
* If you are the PKG_MAINTAINER, please add that info too

**Comment by guillaume-d** [comment]
I am not the PKG_MAINTAINER (else I would know, right? :grin:)
Should this equal to the already filled-in MAINTAINER in the Package/protobuf Makefile macro?

**Comment by sbyx** [comment]
thanks, usually either MAINTAINER or PKG_MAINTAINER should be set. protobuf has the former, though I think it might be outdated.

**Comment by guillaume-d** [comment]
Thanks sbyx and thess! :+1:

Shall I generate a separate pull request for the master branch?

**Comment by sbyx** [comment]
Grml I missed that this for 15.05 please do pull-requests against master only. This situation is a bit awkward now (15.05 being newer than master). I will fix it I guess.

**Comment by jow-** [comment]
reset --hard HEAD^ + force push maybe?

**Comment by sbyx** [comment]
Cherry-picked them now, guess thats fine.

**Comment by guillaume-d** [comment]
Hum, sorry for the confusion, I tried to motivate other people to test it here: https://lists.openwrt.org/pipermail/openwrt-devel/2015-May/033159.html

**Pull request merged**
