### PR TITLE
domoticz: backport #15884

### PR DESCRIPTION
**Pull request by innovate-invent**
Maintainer: @neheb 
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:
I was hoping a CI system would test this for me, not really sure what I am doing.

### CODE REVIEW

**Comment by innovate-invent** [comment]
@neheb Can I get another workflow approval?

**Comment by neheb** [comment]
I'm not merging this.

Add the minizip update to 3.0 instead of creating a new commit to remove the obsolete patch.

**Comment by innovate-invent** [comment]
@neheb hows this?

**Comment by neheb** [comment]
better. but the first commit looks useless.

**Comment by innovate-invent** [comment]
I am not clear why this failed:
https://github.com/openwrt/packages/blob/openwrt-21.02/utils/telldus-core/patches/900-openwrt_fixes_cmake.patch exists and should have been applied, but it is never mentioned in the log.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ARGP_LIBRARY
  linked by target "tdadmin" in directory /home/build/openwrt/build_dir/target-arc_archs_glibc/telldus-core-2.1.2/tdadmin
```

**Comment by neheb** [comment]
@innovate-invent issue is that PKG_BUILD_DEPENDS doesn't seem to work right. I'll merge after the jsoncpp commit is removed.

**Comment by innovate-invent** [comment]
@neheb removed, was included from the original PR and not sure why commit message mentions domoticz.

**Comment by innovate-invent** [comment]
@neheb thanks! do you mind telling me how to access the official build? or when will it be updated in the public repo?
I assume it will appear here: https://downloads.openwrt.org/releases/packages-21.02/mips_24kc/packages/

**Pull request merged**
