### PR TITLE
bluez-alsa: Add to repo

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: 
Compile tested:
mvebu, Linksys WRT3200ACM, OpenWrt master
ramips, D-Link DIR-860L, OpenWrt master
Run tested:
mvebu, Linksys WRT3200ACM, OpenWrt master
ramips, D-Link DIR-860L, OpenWrt master

Description:
Add bluez-alsa to repo

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Something I had in my local repo that someone might want to pick up.

It does work but there are some issues:
* bluealsa sometimes crashes/hangs during teardown of stream
The script doesn't respawn bluealsa, when that happens /var/run/bluealsa needs to be deleted before you can launch bluealsa again. Reported upstream https://github.com/Arkq/bluez-alsa/issues/107
* There should be some kind of asound.conf configuration making the usage much more friendly

**Comment by thess** [comment]
Probably should say - "_Waiting for **a** Maintainer_"

**Comment by diizzyy** [comment]
fwiw, Travis fails because it defaults to ar71xx which indirectly is marked as broken as it's still on Linux 4.9.

**Comment by diizzyy** [comment]
I'll keep it in my own repo

**Comment by xabolcs** [comment]
> I'll keep it in my own repo

Thanks!

**Comment by xabolcs** [comment]
Sorry for being noob.

Where could I find this in `make menuconfig` (my target is `ath79/ar-300m`)?

After checking out that branch and symlinked that specific dir into `package/bluez-alsa`, the ` make package/bluez-alsa/compile` command works (but does nothing: `make[2]: Nothing to be done for 'compile'.`).

**Comment by diizzyy** [comment]
I'd just clone the repo somewhere and and copy ```sound/bluez-alsa``` it into ```./feeds/packages/sound``` (you still need to refresh your index file and install it) or just grab the commits and apply them in your working repo.

```
cd feeds/packages
wget https://github.com/diizzyy/packages/commit/5f593dbf37606082728f46c0a6e29942d5e0c24b.patch
wget https://github.com/diizzyy/packages/commit/b4c90d3ae1eac6d93d12bd1ada887345ea3b39a5.patch
git am 5f593dbf37606082728f46c0a6e29942d5e0c24b.patch
git am b4c90d3ae1eac6d93d12bd1ada887345ea3b39a5.patch
rm *.patch
cd ../..
./scripts/feeds update -i
./scripts/feeds install -a
```

**Comment by xabolcs** [comment]
Thank you for responding so quickly.
I cloned and copied, refreshed and installed, but I'm still unable to find the package (to build an installable ipk) in `make menuconfig`.

No `blue-alsa` in `Sound`:
```
 .config - OpenWrt Configuration
 > Sound ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ┌───────────────────────────────────────────────────── Sound ─────────────────────────────────────────────────────┐
  │  Arrow keys navigate the menu.  <Enter> selects submenus ---> (or empty submenus ----).  Highlighted letters    │
  │  are hotkeys.  Pressing <Y> includes, <N> excludes, <M> modularizes features.  Press <Esc><Esc> to exit, <?>    │
  │  for Help, </> for Search.  Legend: [*] built-in  [ ] excluded  <M> module  < > module capable                  │
  │                                                                                                                 │
  │ ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐ │
  │ │                   < > alsa-utils............ ALSA (Advanced Linux Sound Architecture) utilities             │ │
  │ │                   < > alsa-utils-seq.................................. ALSA sequencer utilities             │ │
  │ │                   < > alsa-utils-tests.......... ALSA utilities test data (adds ~1.3M to image)             │ │
  │ │                   < > espeak................................................ Speech synthesizer             │ │
  │ │                   < > faad2............................. Freeware Advanced Audio Decoder player             │ │
  │ │                   < > forked-daapd........... iTunes (DAAP) server for Apple Remote and AirPlay             │ │
  │ │                   < > ices..................... ices client for Icecast media streaming servers             │ │
  │ │                   <*> keene....................................... Keene USBFMT control program             │ │
  │ │                   < > lame................................................................ lame  ----       │ │
  │ │                   < > lame-lib........................................................ lame-lib             │ │
  │ └───────────────────┴(+)──────────────────────────────────────────────────────────────────────────────────────┘ │
  ├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
  │                            <Select>    < Exit >    < Help >    < Save >    < Load >                             │
  └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘



```

Missing also from `Utilities`:
```
 .config - OpenWrt Configuration
 > Utilities ──────────────────────────────────────────────────────────────────────────────────────────────────────────
  ┌─────────────────────────────────────────────────── Utilities ───────────────────────────────────────────────────┐
  │  Arrow keys navigate the menu.  <Enter> selects submenus ---> (or empty submenus ----).  Highlighted letters    │
  │  are hotkeys.  Pressing <Y> includes, <N> excludes, <M> modularizes features.  Press <Esc><Esc> to exit, <?>    │
  │  for Help, </> for Search.  Legend: [*] built-in  [ ] excluded  <M> module  < > module capable                  │
  │                                                                                                                 │
  │ ┌───────────────────^(-)──────────────────────────────────────────────────────────────────────────────────────┐ │
  │ │                   < > bandwidthd-php........ PHP files to graph bandwidthd data from postgresql             │ │
  │ │                   < > bandwidthd-sqlite....................... Bandwidthd (with sqlite enabled)             │ │
  │ │                   < > banhostlist.................................. List of advertising domains             │ │
  │ │                   < > bc............................... Arbitrary precision calculator language             │ │
  │ │                   < > bluelog..................................... Bluetooth scanner and logger             │ │
  │ │                   < > bluez-daemon............................................ Bluetooth daemon             │ │
  │ │                   < > bluez-examples............................. Bluetooth python example apps             │ │
  │ │                   < > bluez-utils.......................................... Bluetooth utilities             │ │
  │ │                   < > bonniexx............... Bonnie++ - hard drive bottleneck testing program.             │ │
  │ │                   < > bsdiff.................................................. Binary diff tool             │ │
  │ └───────────────────┴(+)──────────────────────────────────────────────────────────────────────────────────────┘ │
  ├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
  │                            <Select>    < Exit >    < Help >    < Save >    < Load >                             │
  └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


```

**Comment by diizzyy** [comment]
```
make menuconfig
Global build settings  --->
[*] Compile with support for patented functionality
```
Is that enabled?

**Comment by xabolcs** [comment]
Nope! It wasn't!

Thanks!

Sorry for the noise!

**Comment by raphikWasHere** [comment]
@ diizzyy. Thanks for sharing your efforts. Nowadays OpenWrt wears a v.5.4 kernel. Bluez-Alsa seems to work fine on bcm63xx machines. [This](https://foro.seguridadwireless.net/openwrt/der-router-als-bluetooth-lautsprecher/) maight be of service.

**Comment by liuning263** [comment]
hello
Can Bluez-Alsa be updated
I tried to install the latest version of Bluez-Alsa, but it failed.
Compiling error:

```
make[3]: Entering directory '/work/liuning/test/sdk_op1907_fip1x_32m/feeds/packages/sound/bluez-alsa'
rm -rf /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa.installed /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa
mkdir -p /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa
install -d -m0755 /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/etc/alsa/conf.d/
cp -fpR /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/src/asound/20-bluealsa.conf /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/etc/alsa/conf.d/
install -d -m0755 /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/usr/lib/alsa-lib
cp -fpR /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/src/asound/.libs/libasound_module_*_bluealsa.so /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/usr/lib/alsa-lib
install -d -m0755 /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/usr/bin
install -m0755 /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/src/bluealsa /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/usr/bin/
install -m0755 /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/utils/bluealsa-aplay /work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa/usr/bin/
install: cannot stat '/work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/utils/bluealsa-aplay': No such file or directory
Makefile:52: recipe for target '/work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa.installed' failed
make[3]: *** [/work/liuning/test/sdk_op1907_fip1x_32m/build_dir/target-mipsel_24kc_musl/bluez-alsa-82fdaea/.pkgdir/bluez-alsa.installed] Error 1
make[3]: Leaving directory '/work/liuning/test/sdk_op1907_fip1x_32m/feeds/packages/sound/bluez-alsa'
time: package/feeds/packages/bluez-alsa/compile#0.03#0.01#0.15
package/Makefile:111: recipe for target 'package/feeds/packages/bluez-alsa/compile' failed
make[2]: *** [package/feeds/packages/bluez-alsa/compile] Error 2
```

Maybe updating Bluez-Alsa will help, thank you very much

**Comment by diizzyy** [comment]
@raphikWasHere @liuning263 
I'm sorry for the late reply. I'm no longer using OpenWrt for anything multimedia related purposes and I have no interest in pursuing this any further.

The build itself is very straightforward (and still probably is), you most likely only need to update PKG_SOURCE section and DEPENDS to get it going again. You will need to port additional libraries to get aptx-support going though.

**Pull request closed without merging**
