### PR TITLE
tinyproxy: add DisableViaHeader option

### PR DESCRIPTION
**Pull request by Dystopian**
Maintainer: @jow-
Run tested: mipsel_24kc, ASUS RT-AX53U, OpenWrt 23.05.0-rc1

Description:
This PR makes the same thing as #16390. Also see #1656.

### CODE REVIEW

**Comment by jow-** [comment]
Please update the PKG_RELEASE number in the Makefile

**Comment by jefferyto** [comment]
A real name is required for `Signed-off-by`, see [Sign your work](https://openwrt.org/submitting-patches#sign_your_work).

**Comment by Dystopian** [comment]
> A real name is required for `Signed-off-by`, see [Sign your work](https://openwrt.org/submitting-patches#sign_your_work).

I'm sorry, I can't. Could you please just publish this 2-line patch with your sign?

**Comment by BKPepe** [comment]
I am afraid that it is not possible.

**Pull request closed without merging**
