### PR TITLE
uwsgi-cgi: General cleanup

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer: @Ansuel 
Compile tested: ramips, WiTi Board, OpenWrt master
Run tested: ramips, WiTi Board, OpenWrt master

Description:
* Remove stray LICENSE file added to repo
* Use codeload instead of git
* Add proper (as close as possible) SPDX license
* Drop OpenSSL, PCRE and Libxml2 as dependencies
  Makes it more suitable alternative for small flash devices
* Drop /etc/uwsgi as there's only one config file
* Remove stray /etc/nginx directory
* Reorganize configuration file
* Convert init.d script to use procd
* Hardset 3 threads and processes, seems like a good tradeoff
  between performance and memory usage instead of doing
  auto scaling based on amout of cpu cores/threads

Non-scientific benchmark (tm)
ramips, mt7621, WiTi Board 16/256M

1. 3 threads, 6 processes
2. 2 threads, 2 processes
3. 3 threads, 3 processes

- LuCI Main page

1.48s
1.72s
1.64s

- Status --> Firewall

6.24s
6.39s
6.40s

- Status --> Kernel log

266ms
256ms
251ms

- Network --> Firewall

936ms
1.08s
1.07s

- Network --> Wireless

1.39s
1.42s
1.40s

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
I did try using LTO and -ffunction-sections -fdata-sections however neither made any difference on final binary size.

**Comment by Ansuel** [comment]
think we should at least add some flag to enable ssl and pcre with a custom build 

also i didn't use procd cause i didn't fine a way to handle custom stop and reload command....

uwsgi have a master process and subprocess that gets restored if killed... 

so to actually stop uwsgi you need to stop the process in the pid file (created by uwsgi) 

same thing with reload... better use the reload command instead of kill it...

**Comment by diizzyy** [comment]
From what I understand, SSL only gets used if you configure a TCP connection/socket which we don't. I'm not really sure where PCRE gets used, at least it's not something we make use of. If needed we can make a variant or whatever later on.

Stopping and restarting works fine, at least on my box. I'm not following what the issue might be.
https://wiki.openwrt.org/inbox/procd-init-scripts#signalling_a_service if you want to override it

Also, fixing the typo for strict mode made uwsgi error out on these lines which seems to be stray by looking at the documentation or at least not valid for the current configuration file.

```
uwsgi_modifier1 = 9
-fork-socket=True
```

**Comment by Ansuel** [comment]
uwsgi_modifier should be used when uwsgi act as http server (so we can drop this...)

fork-socket can be droped... doesn't exist... my bad...

**Comment by diizzyy** [comment]
Also, forgot to mention. This also fixes a compilation error where it picks up zlib (if available) as it's hardcoded to be included if found. Only used for logging which is of little/no interest for now at least.

**Comment by diizzyy** [comment]
So you're ok with merging this?
Right now it's only used for LuCI so we can add variants later on if needed asI mentioned above.

**Comment by Ansuel** [comment]
If you tested this and all works well with Luci... It's ok to merge for me

**Comment by diizzyy** [comment]
It works fine as far as I can tell but if you can give it a try it would be great :-)

**Comment by Ansuel** [comment]
Building an image now ;)

**Comment by Ansuel** [comment]
compiled and all looks good...

anyway i think we can also drop pcre-jit as pcre is no longer available

**Comment by diizzyy** [comment]
Drop it where? :-)

**Comment by Ansuel** [comment]
I'm stupid.... i still have the old config file on my router... 

@hnyman good to merge for me

**Pull request merged**
