### PR TITLE
knxd: use procd, add uci options, add multicast route

### PR DESCRIPTION
**Pull request by stargieg**
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>

### CODE REVIEW

**Comment by mhei** [comment]
@tru7, please review this PR and ACK or NAK.
(The first two commits looks good as of my point of view, for the third one, I would prefer a comment of the networking/core guys, whether this approach is the best one. @sbyx or @ffainelli, would be great if you could spent a look.)

**Comment by tru7** [comment]
@mhei, thanks for asking. These commits extend the runtime environment where @stargieg is obviously more knowledgeable than me with my simle startup script. I don't know the details about procd and uci. I'm not perfectly happy with every detail, e.g. the logfile should be named knxd.log not eibd.log.
In his environment he wants to support the valid multicast mode, the address is correct and I guess a route is needed on a router to restrict it to lan only.
PKG_RELEASE should have been increased to indicate a new package version based on same source code. But I guess that's not very important as upstream is work in progress and I expect more commits in the near future.
So a ACK from my side.

**Comment by mhei** [comment]
Then I propose, that @stargieg changes the logfile name and bumps the PKG_RELEASE. We should be correct in our workflow.

The "problem" with the multicast address is, that on a router, the default route usually points to the wan interface, that means, all multicast traffic generated on the router itself is leaving the router on the "wrong" interface. One approach is to add this route explicitly, as done here. But my feeling is, that there might be a better approach for this, e.g. which handles all multicast addresses and not only the special one for knx.
(On a simple network device with only a LAN connection/interface, this all is no problem)

**Comment by stargieg** [comment]
Hi
I'm working on LuCI Frontend for knxd and linknx (With an esf file import filter).
openwrt - knxd - luci
https://github.com/stargieg/packages-automation/tree/master/luci-app-knxd

I can write a button that generates the UCI Multicast configuration for an selected interface.
Than we don't Patch 3 "knxd: add 224.0.23.12 route via lan"

Why did you need the old log file name? I disable logging in production mode.

**Comment by tru7** [comment]
@stargieg I just said "the logfile should be named knxd.log not eibd.log". BTW, the pid file should be named knxd.pid.
A LuCI frontend is a very nice idea.

**Comment by stargieg** [comment]
Oh I see. My fail. :-(
Can we close this Pull Request. I make new. Without Patch 3 and with logfile name knxd.log and bumps the PKG_RELEASE.

**Comment by mhei** [comment]
No need to create a new PR, simply use git rebase with -i, then drop the last patch and squash the changes into patch 1 or 2.

**Comment by mhei** [comment]
I cherry-picked the patches, squashed them and added SoB/Acked-by lines. Hope, that's ok with you both. Thanks.

**Comment by tru7** [comment]
@mhei perfect, thank you for your extra effort.

**Pull request closed without merging**
