### PR TITLE
libmbim and libqmi: fix compiles on build bots

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @nickberry17 
Compile tested: ath79 master
Run tested: N/A, don't have modem, maybe maintainer or @feckert can runtest
Description:
This fixes compile issue observed on build bots, mentioned in #10217. Once this gets merged you can think about merging the change proposed in the mentioned PR.

Kind regards,
Seb

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
you got two commits there, please merge them

**Comment by micmac1** [comment]
Why? They're for different packages.

**Comment by bobafetthotmail** [comment]
ah no sorry nevermind, misread the names

**Comment by feckert** [comment]
> you got two commits there, please merge them

Why? This are two different packages.
I think it is ok to have two commits.

**Comment by feckert** [comment]
@nik632 did test the change see https://github.com/openwrt/packages/pull/10217#issuecomment-547152701
So I think we could merge this.

**Comment by bobafetthotmail** [comment]
recompiling with his patch works fine, on OpenSUSE Tumbleweed

(I was not having this issue before but it is not breaking anything either, so I'd say it's ok).

When you merge this, my PR (referenced above) should be able to pass the integration check and we can merge that too.

**Comment by micmac1** [comment]
You'd need #10362 as well (because MM is not compiling on the bots neither, even without these two libs).

**Pull request merged**
