### PR TITLE
xl2tpd: refactor for more resilience.

### PR DESCRIPTION
**Pull request by yousong**
- The refreshed 2xx patches are already sent as a pull request to xelerence xl2tpd project [1].
- Netifd version containing the no_proto_task change is already merged [2] but not yet available in OpenWrt trunk.

[1] https://github.com/xelerance/xl2tpd/pull/60
[2] http://git.openwrt.org/?p=project/netifd.git;a=commitdiff;h=a7e508b71c1cf3ee9d401510d298195067fba8e5

### CODE REVIEW

**Comment by dangowrt** [comment]
Looks good, I'll give it a test-run and will merge it after that.

**Comment by yousong** [comment]
Thanks, Daniel.  Please do note that it depends on changes contained only in the current tip branch of netifd.

**Comment by dangowrt** [comment]
Merged by cherry-picking.
@nbd168: still awaiting http://patchwork.ozlabs.org/patch/475961/

**Comment by dangowrt** [comment]
Thanks for the good work!

**Pull request closed without merging**
