### PR TITLE
adblock: update 3.8.15

### PR DESCRIPTION
**Pull request by dibdot**
Maintainer: me / @dibdot
Compile tested: -
Run tested: -, minor config change only

Description:
* remove 'reg_cz' list (abandoned)
* add 'notracking' list (provided by @rcarmo)

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by rcarmo** [comment]
Forgot to mention on the other comment: the matching domains list I was referring to is at https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt.

**Comment by dibdot** [comment]
Thanks for the hint, I've switched to the domains-only file.

**Comment by rcarmo** [comment]
Actually, they are designed to be used jointly. See https://github.com/notracking/hosts-blocklists/wiki/Install-dnsmasq for more info.

**Comment by rcarmo** [comment]
Oh, forget it. I see that you used the combined dnscrypt-proxy file,

**Pull request merged**
