### PR TITLE
Add DDNS provider servercow.de

### PR DESCRIPTION
**Pull request by jummo**
Maintainer: jummo4@yahoo.de
Compile tested: -
Run tested: x86-64 22.03

Description:
Add ddns provider servercow.de.
Description of usage at https://cp.servercow.de/plugin/support_manager/knowledgebase/view/46/dns-update-through-fritzbox-router/

### CODE REVIEW

**Comment by BKPepe** [comment]
How many merge commits do you need in one your PR? There are already 6 commits in this PR and 3 of them are useless and other 2 should be squashed into one.

**Comment by jummo** [comment]
> How many merge commits do you need in one your PR? There are already 6 commits in this PR and 3 of them are useless and other 2 should be squashed into one.

Sorry Josef, I'm doing it for the first time.
Should I close this pull request and start over with a new one?
Or is there an easy way to fix the current one?

**Comment by BKPepe** [comment]
You can do that in the current one, no need to open a new one.

**Comment by jummo** [comment]
Closing

**Pull request closed without merging**
