### PR TITLE
 transmission: allow select cryptographic library

### PR DESCRIPTION
**Pull request by obsy**

### CODE REVIEW

**Comment by hnyman** [comment]
Could you please git squash the commits into one commit (with the signed-off-by line).
There should be no merge commits inside the PR.

**Comment by dangowrt** [comment]
imho it'd be better to use build variants instead of selecting the crypto library at build-time.
See https://github.com/openwrt/packages/blob/master/net/umurmur/Makefile

**Comment by obsy** [comment]
One problem: all binaries depends on this, final packages will be

transmission-client-openssl
transmission-client-polarssl
transmission-remote-openssl
transmission-remote-polarssl
transmission-daemon-openssl
transmission-daemon-polarssl
transmission-web

It is ok?

**Comment by dangowrt** [comment]
Yes, this is what I thought it should look like.

**Comment by hnyman** [comment]
@obsy 
One hint: use a feature branch for pull requests. That makes updating pull requests simple, as you can overwrite your previous commits with ease.

**Pull request closed without merging**
