### PR TITLE
Mass unmaintained/unused package removal

### PR DESCRIPTION
**Pull request by neheb**
ping @openwrt/package-maintainers 

Some of these should probably not be removed.

These are mostly libraries.

### CODE REVIEW

**Comment by BKPepe** [comment]
czmq should not be removed

**Comment by neheb** [comment]
OK

**Comment by hnyman** [comment]
Ok from my side. The amount of semi-abandoned packages without real usage has grown too much.

**Comment by neheb** [comment]
ping @ammubhave @inindev @danak6jq @Wedmer @dangowrt @ejurgensen @amir-sabbaghi @yegorich @changeway @roger- @commodo

**Comment by commodo** [comment]
for libzdb: fine from my side

**Comment by Wedmer** [comment]
Fftw3 is maintained but there's no real usage for now. So it can be moved/removed from repository.

**Comment by yegorich** [comment]
Are there any problems with libsoc? We use it in our OpenWrt BSPs.

**Comment by cotequeiroz** [comment]
While checking #11795, I've stumbled upon libre2 being pulled in as a dependency of dnsdist.
If you were to add another package, I would suggest running something like this to check for a missed dependency:
```sh
#!/bin/sh
PACKAGES_RE='\(fbzmq\|fbthrift\|libwangle\|librsocket-cpp\|libre2\|libsigar\|libgflags\|libfizz\|libfolly\|avro\|rxtx\|classpath\|fcgi\|fftw3\|glpk\|gperf\|libavl\|libglog\|libsoc\|libstrophe\|libuvc\|libzdb\)'
grep -v "${PACKAGES_RE}\(/host/\)\?/compile +" tmp/.packagedeps \
    | grep "compile +=.*${PACKAGES_RE}" | grep --color "${PACKAGES_RE}"
```
Don't worry, I've ran it through shellcheck 😜 .

**Comment by neheb** [comment]
> Are there any problems with libsoc? We use it in our OpenWrt BSPs.

Not particularly. This is a draft PR meant to gauge which packages to remove.

Spring cleaning is needed every now and then.

**Comment by neheb** [comment]
> While checking #11795, I've stumbled upon libre2 being pulled in as a dependency of dnsdist.
I'll remove it from here.
> If you were to add another package, I would suggest running something like this to check for a missed dependency:
> 
> ```shell
> #!/bin/sh
> PACKAGES_RE='\(fbzmq\|fbthrift\|libwangle\|librsocket-cpp\|libre2\|libsigar\|libgflags\|libfizz\|libfolly\|avro\|rxtx\|classpath\|fcgi\|fftw3\|glpk\|gperf\|libavl\|libglog\|libsoc\|libstrophe\|libuvc\|libzdb\)'
> grep -v "${PACKAGES_RE}\(/host/\)\?/compile +" tmp/.packagedeps \
>     | grep "compile +=.*${PACKAGES_RE}" | grep --color "${PACKAGES_RE}"
Good to know. Oddly enough, I don't use a POSIX shell.
> ```
> 
> Don't worry, I've ran it through shellcheck stuck_out_tongue_winking_eye .
Well, I can't say that's relevant here :P

**Comment by ejurgensen** [comment]
Ok to remove libavl and gperf. Thought I had already removed libavl, but I guess not.

**Comment by danak6jq** [comment]
I have no objection to the removal of rxtx and classpath (or any of the other packages).

**Comment by amir-sabbaghi** [comment]
If no package depends on libglog, then it's ok to remove it.

**Comment by roger-** [comment]
I don’t recall why libuvc was added, so probably ok to remove.

**Comment by changeway** [comment]
libstrophe is still maintained. I use this XMPP lib in my TR-069 application. As I know, some VoIP application also need this XMPP lib. These application are proprietary package. It is fine to remove on my side, but I have no idea about any other proprietary package still need this XMPP lib.

**Comment by neheb** [comment]
Added back libstrophe and libsoc. Maintainers claim they are not abandoned.

**Comment by neheb** [comment]
Removed libcanfestival. ping @toxxin 

Anyone have any suggestions?

**Comment by diizzyy** [comment]
```
ipv6/tayga - Abandoned upstream (use jool instead which is in tree)
net/chaosvpn - Why was this committed in the first place?
sound/espeak - Abandoned upstream (superseded by espeak-ng)
sound/svox - Hasn't been touched in ages and very outdated
```

**Comment by neheb** [comment]
ping @daniel-santos

**Comment by mhei** [comment]
ACK for libcanfestival removal.

**Comment by toxxin** [comment]
libcanfestival: it's fine from my side. We can remove it.

**Comment by neheb** [comment]
Removed tayga. ping @oskar456

**Comment by oskar456** [comment]
> Removed tayga. ping @oskar456

Please don't as long as it compiles. Upstream is not dead, it's just _stable_. Jool can be tricky to set up properly in some network setups because it's kernel-side and there's no proper integration with netifd.

**Comment by neheb** [comment]
OK

**Comment by daniel-santos** [comment]
> ping @daniel-santos

Thank you very kindly for the ping!  I would like to keep classpath.  Does this need a maintainer?  Sadly, some twisted client has required us to port OpenJDK (for an mt7602a cpu!), but I would still very much like to keep classpath please and thank you.

**Comment by hnyman** [comment]
classpath does not compile in buildbot, as there is no java support in buildbot.
So, the whole package is problematic from that perspective.

**Comment by danak6jq** [comment]
I updated classpath and jamvm over 5 years ago to support a project I am no longer involved with. Upstream jamvm has not changed in almost 6 years, with language support frozen at Java 8.
Upstream classpath has not changed in 8 years, with language support frozen at Java 7.
(My project was specifically compiled at v1.5).

jamvm depends on classpath; if classpath is removed, jamvm should be as well.
I am no longer in a position to actively maintain either of these packages.

**Comment by danak6jq** [comment]
> Thank you very kindly for the ping! I would like to keep classpath. Does this need a maintainer? Sadly, some twisted client has required us to port OpenJDK (for an mt7602a cpu!), but I would still very much like to keep classpath please and thank you.

@daniel-santos I would be delighted if you would take up maintaining classpath.

**Comment by neheb** [comment]
@diizzyy what about inadyn?

**Comment by diizzyy** [comment]
Still maintained upstream but I have no interest in it.

**Comment by neheb** [comment]
I ask since you wanted to remove it at one point.

**Comment by diizzyy** [comment]
Indeed, as I don't think we should provide (very) outdated software due to security concerns.

**Comment by danak6jq** [comment]
@flyn-org you may be interested in the discussion of classpath, rxtx (and jamvm). Possibly you and @daniel-santos could play "rock, paper, scissors" over maintaining these :-)

**Comment by diizzyy** [comment]
@oskar456 
...right, there are several patches floating around dating multiple years.
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-proxy/tayga/files
https://src.fedoraproject.org/rpms/tayga/tree/master
https://salsa.debian.org/debian/tayga/-/tree/debian/master/debian%2Fpatches
VyOS also lists it as unmaintained
https://phabricator.vyos.net/T160

**Comment by neheb** [comment]
Packages removed and thrown in the abandoned repo.

If anyone wants a package back, please import from https://github.com/openwrt/packages-abandoned and make a pull request.

**Pull request merged**
