### PR TITLE
squid: update to 4.0.7

### PR DESCRIPTION
**Pull request by urusha**

### CODE REVIEW

**Comment by urusha** [comment]
So, it's squid update:
- squid depends on libatomic
- squid doesn't have configure option --enable-ssl (from 3.5 actually)
- ssl_crtd renamed to security_file_certgen
- some lines from cross_compile.patch removed upstream
- mime.conf fixed upstream

Just ignore commits about arp-scan, it's here by mistake.

Please, review.

**Comment by hnyman** [comment]
Invalid.
* Contains two unrelated arp-scan commits.
* The two squid commits do not have signed-off-by lines.

You should "squash" the four commits into one and sign off that commit. You have the changes in a feature branch, so the pull request can be updated easily. Follow the advice in https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#advice-on-pull-requests

CC to maintainer: @lperkov

**Comment by urusha** [comment]
Fixed...

**Comment by lperkov** [comment]
NACK. squid 4 is still beta. Lets stick to the production 3.5.x

If you want to bump to latest 3.5.15 feel free to do that.

**Pull request closed without merging**
