### PR TITLE
Add missing python3-bleak dependency

### PR DESCRIPTION
**Pull request by QuintinHill**
Maintainer: me
Compile tested: fairly trivial will rely on CI for this.
Run tested: ath79 wndr3700v4 manual installed dependency

Description: fix up of 64fa106.

### CODE REVIEW

**Comment by QuintinHill** [comment]
CI errors are:  unable to download https://downloads.openwrt.org/snapshots/packages/mips_24kc/telephony/Packages.gz and similar.

**Review by BKPepe — CHANGES_REQUESTED** [review]
1. Adding new dependencies requires to bump PKG_VERSION.
2. Avoid vague commit subjects as updating it to the latest version, of course... you are updating it each time to the latest version, which is quite obvious. This just bloats the commit history and once you will dig it in the past, then it would be really hard, so please be more specific and concrete on this one. There isnt anything wrong to said: "update to version X.Y.Z". 
3. Also, it would be handy if you can add changelog (link is just fine) to the commit description as well.

**Comment by QuintinHill** [comment]
@BKPepe sorry about those omissions.  Corrected now! Thank you very much for the review.

**Comment by jefferyto** [comment]
Can you add a `Fixes:` tag to the commit message for python-bleak, referencing https://github.com/openwrt/packages/commit/64fa106b0711a28732495b9cd334cfd6dfad9683? See https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-changes (near the bottom of that section).

**Comment by BKPepe** [comment]
Oh yeah, @jefferyto has very good idea, please do that. Maybe if I am thinking more, could be interesting to know why the missing dependency is required now, which Python package requires it, etc.

**Comment by QuintinHill** [comment]
Updated.

**Comment by QuintinHill** [comment]
@BKPepe /@jefferyto these should all be addressed including a link to the bleak commit that added the dependency requirement.

**Comment by QuintinHill** [comment]
Also note @predators46 has tested the python3-dbus-fast change in https://github.com/openwrt/packages/pull/22965.

**Comment by predators46** [comment]
> Also note @predators46 has tested the python3-dbus-fast change in #22965.

I don't see this. if you want to update python-dbus-fast i will close update python-dbus-fast if needed

**Comment by QuintinHill** [comment]
I don't mind which commit goes in (but mine does have the changelog in the commit message at the request of reviewers)!

**Pull request merged**
