### PR TITLE
fail2ban: fix 2to3 error

### PR DESCRIPTION
**Pull request by erdoukki**
Maintainer: me / @erdoukki 
Run tested: (untested)
Compile tested: (arch=MVEBU EspressoBin, host=Linux Mint x64)

Description:
2to3 support has been removed in setuptools since version 58.0.0.

Upstream issue/fix:
[BR]: build fails against setuptools 58+ fail2ban/fail2ban#3098
fail2ban/fail2ban@5ac303d

Fix openwrt/packages#17311

To install/build for python3 from source, it is necessary to convert to py3 codebase before setup
(invoke 2to3 or ./fail2ban-2to3 firstly).
> ./fail2ban-2to3
> python3 setup.py build

Signed-off-by: Kerma Gérald <gandalf@gk2.net>

### CODE REVIEW

**Comment by BKPepe** [comment]
Hmm… It makes me wonder.

Why you didn't use [the upstream commit](https://github.com/fail2ban/fail2ban/commit/21d94ff178192116eb5288190d78dd4630534a7b.patch), it was not working for you?

**Comment by erdoukki** [comment]
> Why you didn't use [the upstream commit](https://github.com/fail2ban/fail2ban/commit/5ac303df8a171f748330d4c645ccbf1c2c7f3497.patch), it was not working for you?

Because it simply do the opposite we need.
This patch removes the needed flag we need to use with the latest release and the latest python setuptools.
The upstream master hasnone year bug fixes and enhancment

**Comment by erdoukki** [comment]
New error now:
```
***   File "/usr/lib/python3.10/site-packages/fail2ban/server/ipdns.py", line 312
    					mask = ~(0xFFFFFFFFL >> cidr)
    					                  ^
SyntaxError: invalid hexadecimal literal
```
Reported here: https://github.com/fail2ban/fail2ban/issues/2959

**Comment by erdoukki** [comment]
We need to execute ./fail2ban-2to3 in the configure step, before the install...
Is there any Python3 expert I could ask help for ?

**Comment by erdoukki** [comment]
Locally resolved like : 
https://github.com/fail2ban/fail2ban/issues/2959#issuecomment-791681678
`apt install 2to3 python3-lib2to3 python3-toolz`

But I cannot add it in my Makefile nor in the buildroot...

It was already the problem in the first PR https://github.com/openwrt/packages/issues/15099

**Comment by erdoukki** [comment]
> (invoke 2to3 or ./fail2ban-2to3 firstly).

Th problem is the necessary call of the ./fail2ban-2to3 command before the python build

**Comment by erdoukki** [comment]
@BKPepe 
It may be compile correctly now.

Can you give a try, please ?

**Comment by BKPepe** [comment]
I already told you that it is better to think twice before writing multiple comments in a row as you make it long, leading to any misunderstanding. Take your time. There is no need to rush. There is an edit button if you prefer. 

Well, you made more changes than it is described in the commit subject and its description. 

1. Why you change python3-light dependency into python3?
2. For the file `lib2to3.txt`, which you created, there is a folder for these files called `host-pip-requirements`.
Feel free more to check this [README](https://github.com/openwrt/packages/blob/master/lang/python/README.md). I'd prefer if you stick to the standard instead of reinventing the wheel.
3. Patch(es) should be properly numbered and have a clear name.

TBH, I don't like the changes you made, but I think there should be a better way to handle this. For now, I don't have much time to look at the issues you are dealing with. Hopefully, at the end of the week, it will be better.

**Comment by erdoukki** [comment]
> Why you change python3-light dependency into python3?

Reffer to README python3, must be python3-light only for few or less than 3 lib !


> For the file `lib2to3.txt`, which you created, there is a folder for these files called `host-pip-requirements`.
> Feel free more to check this [README](https://github.com/openwrt/packages/blob/master/lang/python/README.md). I'd prefer if you stick to the standard instead of reinventing the wheel.

The sample codes use the same way...
The README never talk of requirement !

> Patch(es) should be properly numbered and have a clear name.

In facts it's true, and this patch may be also useless...

> TBH, I don't like the changes you made, but I think there should be a better way to handle this. For now, I don't have much time to look at the issues you are dealing with. Hopefully, at the end of the week, it will be better.

For me I do not like the tone you always take in our exchanges !
What's the problem with you ?
Did the TURRIS become a MASTER on OpenWrt and make ITS own COMPANY RULES been required !!!
I made this fix for be pleasant, and also without any help, on a tricky tweak...

> I already told you that it is better to think twice before writing multiple comments in a row as you make it long, leading to any misunderstanding. Take your time. There is no need to rush. There is an edit button if you prefer.

Sorry again to be so dumb !

**Comment by erdoukki** [comment]
It will be a very little effort to enhance the work...
It was a huge effort to find a way to fix...

Perfection is not of this world, I think !?

**Pull request closed without merging**
