### PR TITLE
softflowd: update softflowd.init do use procd

### PR DESCRIPTION
**Pull request by semik**
Maintainer: @rvandegrift
Run tested: chaos_calmer 1.3.2 @ TP-LINK TL-WR1043ND v2
Description: update softflowd.init do use procd
Signed-off-by: Jan Tomášek <jan@tomasek.cz>

### CODE REVIEW

**Comment by champtar** [comment]
@semik 
you need to signoff your commit, make it start with "softflowd: ...", and to bump PKG_RELEASE

**Comment by semik** [comment]
@champtar this is my first attempt for contribution, thanks for 
feedback. I hoppe both issues are fixed now.

-- 
-----------------------
Jan Tomasek aka Semik
http://www.tomasek.cz/

**Comment by champtar** [comment]
You now have 2 commits, you need to squash them into 1

**Comment by champtar** [comment]
Hi @semik 
if you can amend your commit once more (remove first line and typo do->to)
@rvandegrift please review

**Comment by semik** [comment]
Hi @champtar thanks for you patience and help. Edit done.

**Comment by champtar** [comment]
Thanks @semik, commit now looks good, waiting for maintainer

**Comment by rvandegrift** [comment]
This looks good to me.

**Pull request merged**
