### PR TITLE
openocd: use release tar.bz2 instead of git

### PR DESCRIPTION
**Pull request by lynxis**
Maintainer: @paulfertser
Compile tested: lantiq

The release tar does not contain the `guess-rev.sh`.
If it's not existent the configure scripts uses different
variables which removes the build timestamp.
Fixes reproducible builds.

Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

### CODE REVIEW

**Comment by paulfertser** [comment]
OpenOCD releases happen relatively rarely and so it might be beneficial to be able to easily package intermediate versions. I guess we can return to git after those builds will be made reproducible upstream.
Thank you for the patch,
Acked-by: Paul Fercer <fercerpav@gmail.com>

**Comment by paulfertser** [comment]
Alexander, would you suggest removing build timestamp altogether or would it be better if OpenOCD honoured SOURCE_DATE_EPOCH when present?

**Comment by lynxis** [comment]
@paulfertser I'm not sure what's the best solution. I prefer removing the timestamp instead using SOURCE_DATE_EPOCH.

**Comment by lynxis** [comment]
can someone merge this? @thess maybe?
@paulfertser  if you want update again here is a small patch to the Makefile, which doesn the same. But as long we're using a release, I think it's better to use the release tarball.

<code>
diff --git a/utils/openocd/Makefile b/utils/openocd/Makefile
index 338c5d91..684bac21 100644
--- a/utils/openocd/Makefile
+++ b/utils/openocd/Makefile
@@ -62,6 +62,11 @@ CONFIGURE_ARGS += \
        --enable-dummy \
        --enable-sysfsgpio
 
+define Build/Prepare
+       $(call Build/Prepare/Default)
+       rm $(PKG_BUILD_DIR)/guess-rev.sh
+endef
+
 define Build/Compile
         +$(MAKE_VARS) \
         $(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR)/$(MAKE_PATH)
</code>

**Pull request merged**
