### PR TITLE
perl: fix build failure in GCC10

### PR DESCRIPTION
**Pull request by xinxijishuwyq**
Signed-off-by: Ken Wong <xinxijishuwyq@gmail.com>

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by xinxijishuwyq** [comment]
I used the perl source code in this project (openwrt official) to add the patch, put it in openwrt 19.07 mod by Lean and compiled successfully under the latest version of archlinux.

**Comment by neheb** [comment]
ping @pprindeville

**Comment by pprindeville** [comment]
Please fix the initial comment.

**Comment by neheb** [comment]
Tested on Fedora 32. All perl host packages failed to compile without this.

**Comment by xinxijishuwyq** [comment]
> Tested on Fedora 32. All perl host packages failed to compile without this.


In arch Linux there is the same problem.

**Comment by xinxijishuwyq** [comment]
> I'm not seeing specific handling for `10.*` anywhere... and I don't like the idea of having it default unless it can be shown that this is the right thing to do.


In fact, I don't know how it works. I just made reference to other people's patches. And, it's work in my test environment.

https://github.com/Perl/perl5/pull/17295/files

https://bugs.gentoo.org/attachment.cgi?id=612830

**Comment by zacharyrs** [comment]
At a glance, it looks like the issue was a lack of specificity in the switch cases.
Basically the case checks for version 1 matched version 10, whereas now they keep the period to distinguish between `x.y` and `x0.y`.

That is, prior code was like:
```
case "$gccversion" in
1*)
```

Is now:
```
case "$gccversion" in
1.*)
```

**Comment by zacharyrs** [comment]
@pprindeville - I'm pretty clueless about the right way, but I think this is one of those cases it makes sense.

**Comment by xinxijishuwyq** [comment]
#12262

**Comment by pprindeville** [comment]
> Please fix the initial comment.

@xinxijishuwyq Waiting on this. You can click on "..." on the top right side of the comment box and select "edit" to make changes.

**Comment by ynezz** [comment]
Superseded by https://github.com/openwrt/packages/pull/12391

**Pull request closed without merging**
