### PR TITLE
ripgrep: regex enabled grep

### PR DESCRIPTION
**Pull request by Grommish**
Ripgrep recursively searches directories for a regex pattern while respecting your gitignore

Requires rust-lang (https://github.com/openwrt/packages/pull/13916)

Signed-off-by: Donald Hoskins <grommish@gmail.com>

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

Ripgrep is a rust-lang regex-enabled recursive grep that respects gitignore.

### CODE REVIEW

**Comment by neg2led** [comment]
Tested-By: Andrew Powers-Holmes <aholmes@omnom.net>

on a Cavium CN6640-SNIC10E (Octeon II NIC which is not officially supported yet, and may never be, but does work)

**Comment by Grommish** [comment]
This updated to use the new Rust and LLVM integrations.

This also removes `jemalloc` calls for ripgrep, as the jemalloc that ships with ripgrep causes issues when cross-compiling.

**Comment by Grommish** [comment]
```
root@OpenWrt:~# rg --version
ripgrep 13.0.0 (rev 3a1c4cc8ab)
-SIMD -AVX (compiled)
root@OpenWrt:~# rg
error: The following required arguments were not provided:
    <PATTERN>

USAGE:

    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] -e PATTERN ... [PATH ...]
    rg [OPTIONS] -f PATTERNFILE ... [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN
    rg [OPTIONS] --help
    rg [OPTIONS] --version

For more information try --help

root@OpenWrt:~#
```

**Comment by BKPepe** [comment]
Closing, OP is inactive.

**Pull request closed without merging**
