### PR TITLE
mpd: switch to using libnpupnp

### PR DESCRIPTION
**Pull request by neheb**
Removed iconv const patch. After discussing with upstream. it turns out
that libiconv-full in OpenWrt is broken.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody
Compile tested: ath79
Run tested: TPLink Archer C7 v2

Runtime testing has revealed some unfortunate things.

1: UPnP is slow. I tried with both libupnp and libnpupnp. The issue might be with my copy of gerbera. Gerbera goes into 100% CPU usage. foobar2000 works perfectly though... ping @medoc92

2: mp4 playback is totally broken. That is, only ffmpeg can play it. The faad plugin can only play raw aac streams. It might make sense to completely remove it. Then again, I do remember a user that was using faad to play radio streams.

### CODE REVIEW

**Comment by neheb** [comment]
@aparcar what are these errors?

**Comment by aparcar** [comment]
@neheb I added runtime tests which try to install a package and if exists, install it. Seems like `mpd` isn't easily installable?

**Comment by medoc92** [comment]
@neheb maybe try to start gerbera with debug logging enabled (I think that it's --debug but really not sure) to see what it is doing ?

**Comment by neheb** [comment]
Meh that's unfortunate.

**Comment by medoc92** [comment]
I tested the mpd upnp plugin with both minimserver and the upmpdcli media server (all on linux amd64), and I don't see any particular issues. I did not test with gerbera, because I can't build it on my Ubuntu bionic system.

**Comment by neheb** [comment]
I think it's because I'm running Gerbera on a slow ARM based system with ~13k entries. MPD I guess times out.

**Pull request merged**
