### PR TITLE
yggdrasil: use Golang buildroot appropriately, actually fix #8457

### LINKED ISSUE #8457: yggdrasil: why is MIPS FPU emulator a dependency?
@wfleurant @aparcar 
If I recall right, current version of Golang compiler already supports softfp.
Besides that, there is mips24kf, which has an FPU.

### PR DESCRIPTION
**Pull request by dengqf6**
Description:
This supersedes #8465
No longer needs FPU emulator now

Maintainer: @wfleurant @aparcar 
Compile tested: ramips
Run tested: ramips

### CODE REVIEW

**Comment by jefferyto** [comment]
You beat me to it :joy: A few comments:

* Need to increment `PKG_RELEASE`
* Suggest adding `PKG_USE_MIPS16:=0`
* Can add:

  ```
  GO_PKG_LDFLAGS_X:= \
    github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.buildName=yggdrasil-openwrt \
    github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.buildVersion=$(PKG_VERSION)
  ```

**Comment by dengqf6** [comment]
Done

**Comment by aparcar** [comment]
LGTM, should I merge this?

**Comment by jefferyto** [comment]
LGTM :+1:

**Pull request merged**
