### PR TITLE
grilo-plugins: remove XML::Parser build dependency

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @MikePetullo 
Compile tested: ramips, mipsel_74kc, openwrt master
Run tested: N/A

Description:
This is causing buildbot failure:
```
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
Makefile:95: recipe for target '/home/build/build_dir/build_dir/target-mips_24kc_musl/grilo-plugins-0.3.7/.configured_a17fb5ef857664f03cd0ce37cc5ea591' failed
```
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by cotequeiroz** [comment]
@thess 
This turned up a bit more difficult than anticipated, (to just patch that one-liner), and I ended up not using `PKG_FIXUP=autoreconf`:

1. `configure` is already being patched; 

2. `configure.ac` is calling some gnome macros `GNOME_COMPILE_WARNINGS` and `GNOME_MAINTAINER_MODE_DEFINES`; I suspect they are not strictly needed, but they do change compiler flags, and some unused  `configure` options.  We may end up disabling too much.

The effect of changing that one line is strictly reflected in the `configure` script patch (that macro was locally defined).

**Comment by thess** [comment]
I think we've been chasing the wrong problem here with XML::Parser. It is not that it isn't present but that autotools are not finding our host packaged version in the build tree. I just recently noticed that build errors mentioning that XML::Parser was not found are due to a compatibility problem with the `intltool` script `intltool-update` and recent Perl versions. You will notice an error/warning like the following preceding the "not found" message.
```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^(.*)\${ <-- HERE ?(
[A-Z_]+)}?(.*)$/ at /opt/openwrt/staging_dir/hostpkg/bin/intltool-update line 1065.

```
Fixing this syntax error in the `intltool` package seems to resolve this ambiguity. Packages dependent on XML::Parser (ibsoup, grillo, etc) build OK then on systems which do not have XML::Parser available locally.

I'm working on an update to `libs/intltool` which should resolve some of these issues.

**Comment by thess** [comment]
Not yet - Turns out it was only part of the problem. Fix is not complete. However, intltool fix is now checked in: https://github.com/openwrt/packages/commit/5c823596dd4f51969425b7a39f9b3c2730aa4e72

**Comment by cotequeiroz** [comment]
@thess, I've made the changes you proposed.  I need to squash this, but it was not clear to me which way I should go: Patching configure, or running autoreconf.

**Comment by thess** [comment]
autoreconf - configure.ac works here.

**Pull request merged**
