### PR TITLE
treewide: adapter service extra command to new api

### PR DESCRIPTION
**Pull request by zhanhb**
Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>

Maintainer: 
Compile tested: Not tested
Run tested: ath79/nand(Only package apfree-wifidog, haproxy, nginx, openvswitch, radicale, tinc, vpnbypass, vpn-policy-routing, wifidog tested)

### CODE REVIEW

**Comment by aparcar** [comment]
Are these all affected packages or are there some missing?

**Comment by zhanhb** [comment]
I search the keyword `EXTRA_COMMANDS`. There's no other packages match this keyword.

**Comment by feckert** [comment]
I have already staged a P/R for this https://github.com/openwrt/packages/pull/13798

**Comment by feckert** [comment]
@zhanhb thanks

**Pull request closed without merging**
