### PR TITLE
freetype: Update to 2.9.1

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @val-kulkov 
Compile tested: mvebu

### CODE REVIEW

**Comment by diizzyy** [comment]
Perhaps worth dropping bz2 dep?
https://www.freetype.org/freetype2/docs/reference/ft2-bzip2.html

**Comment by neheb** [comment]
Seems good. OpenWrt to my knowledge does not need the XOrg fonts. I'd love to hear @val-kulkov 's opinion before proceeding.

**Comment by val-kulkov** [comment]
Reviewing this, need some more time pls.

**Comment by val-kulkov** [comment]
@neheb : removing support bzip2 compressed fonts did not break font rendering with php7-mod-gd on my test bcm53xx system, so individually I am okay with removing bzip2 font support and the dependency on libbz2. Of course, we can never be sure that such removal won't annoy other people. I hope that Matplotlib users do not require bzip2-compressed fonts:
https://github.com/k13132/openwrt-packages/blob/master/packages/python3-matplotlib/Makefile

Please change "with-bzip2=yes" to "with-bzip2=no", remove libbz2 from DEPENDS: declaration and squash commits into one. Thank you.

**Comment by neheb** [comment]
done

**Pull request merged**
