### PR TITLE
django-postoffice: bump to version 3.4.1

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/4a61a88f9006f70444e00699f76551c75f73c14e x86
Run tested: https://github.com/openwrt/openwrt/commit/4a61a88f9006f70444e00699f76551c75f73c14e x86

----------------------------------

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
https://github.com/openwrt/packages/pull/11985#issuecomment-620503850

Perhaps I should have left comments in the Makefiles describing the version restrictions :joy:

**Comment by commodo** [comment]
right;
i keep forgetting;
i get the emails and i just do it sometimes;

i am getting a bit annoyed by this seafile;
in a way, i am also waiting for you to get frustrated with it, so that it can be dropped :p
i am not actively trying to frustrate you though;

**Comment by commodo** [comment]
while related on this;
are you taking care of the seafile upgrade?

i was gonna plan for it; but if you started it, then i won't do it;

**Comment by jefferyto** [comment]
> in a way, i am also waiting for you to get frustrated with it, so that it can be dropped :p

You may be waiting a while :laughing: 

> are you taking care of the seafile upgrade?

I'll get to it in the next day or two.

**Pull request closed without merging**
