### PR TITLE
Revert "sane-backends: import from oldpackages"

### PR DESCRIPTION
**Pull request by luizluca**
Reverts openwrt/packages#1724

### CODE REVIEW

**Comment by luizluca** [comment]
Fixes #1777

**Comment by champtar** [comment]
Hi @luizluca, 
Please put all informations (like the fixes xyz and a small summary) in the commit message next time.
It's better if we are able to understand commit "offline" (just with git log)

**Comment by luizluca** [comment]
OK @champtar . I did it using birthing interface. I missed some details.

**Comment by hnyman** [comment]
some cleanup might be needed, as the revert-1724-sane feature branch currently exists in the main packages repo at github, right next to for-15.05 and for-14.07 ...
https://github.com/openwrt/packages/tree/revert-1724-sane

**Comment by luizluca** [comment]
@hnyman. Done!

**Pull request merged**
