### PR TITLE
mwan3-luci: update to 1.4-5

### PR DESCRIPTION
**Pull request by psyborg55**
Maintainer: @arfett 
Compile tested: ramips, xiaomi mini, r49946
Run tested: ramips, xiaomi mini, r49946

Description: Bump to 1.4-5. Added new page for wifi configuration edit, similar how the current network configuration page works.
Also enabled collecting of wifi configuration in troubleshooting page.

Signed-of-by: Tomislav Požega pozega.tomislav@gmail.com

### CODE REVIEW

**Comment by arfett** [comment]
I'll take a look tonight

**Comment by arfett** [comment]
I haven't tested this but it looks good. If you and others see value to it I'm okay with this being merged.

psyborg55, could you test something for me? I don't have an OpenWrt capable device handy right now to test this on...

Can you see if there are multiple lines with "username", "password", and "key" in the network and wifi configs if the current code replaces them all? Do we need to make it a global sed for that to happen? If it catches them all the way it is now great but if not could you adjust that and also make the same request for the network config file while you're at it?

Current:
sed -e 's/.*username.*/	USERNAME HIDDEN/' -e 's/.*password.*/	PASSWORD HIDDEN/' -e 's/.*key.*/	KEY HIDDEN/'

Global:
sed -e 's/.*username.*/	USERNAME HIDDEN/g' -e 's/.*password.*/	PASSWORD HIDDEN/g' -e 's/.*key.*/	KEY HIDDEN/g'

**Comment by champtar** [comment]
Hi @psyborg55 
you need to rebase your commit before someone merge it

**Comment by psyborg55** [comment]
do you mean include all changes in one patch? @arfett i'll check it

**Comment by champtar** [comment]
@psyborg55, yes, i meant squash everything in one commit

**Comment by psyborg55** [comment]
i've tried replacing 

Current:
sed -e 's/.username./ USERNAME HIDDEN/' -e 's/.password./ PASSWORD HIDDEN/' -e 's/.key./ KEY HIDDEN/'

with 

Global:
sed -e 's/.username./ USERNAME HIDDEN/g' -e 's/.password./ PASSWORD HIDDEN/g' -e 's/.key./ KEY HIDDEN/g'

and noticed no changes in output data. here is troubleshooting copy with global sed, not sure what you referred to mentioning network and wifi config files but checking these two also returns expected result.

>     Software versions : 
>     
>     OpenWrt - OpenWrt Designated Driver 49946
>     LuCI - git-16.280.54886-e06c60a
>     
>     mwan3 - 2.0-3
>     mwan3-luci - 1.4-4
>     
>     Output of "cat /etc/config/mwan3" : 
>     
>     config interface 'wan'
>     	option enabled '1'
>     	list track_ip '8.8.4.4'
>     	list track_ip '8.8.8.8'
>     	list track_ip '208.67.222.222'
>     	list track_ip '208.67.220.220'
>     	option reliability '2'
>     	option count '1'
>     	option timeout '2'
>     	option interval '5'
>     	option down '3'
>     	option up '8'
>     
>     config interface 'wan2'
>     	option enabled '0'
>     	list track_ip '8.8.8.8'
>     	list track_ip '208.67.220.220'
>     	option reliability '1'
>     	option count '1'
>     	option timeout '2'
>     	option interval '5'
>     	option down '3'
>     	option up '8'
>     
>     config member 'wan_m1_w3'
>     	option interface 'wan'
>     	option metric '1'
>     	option weight '3'
>     
>     config member 'wan_m2_w3'
>     	option interface 'wan'
>     	option metric '2'
>     	option weight '3'
>     
>     config member 'wan2_m1_w2'
>     	option interface 'wan2'
>     	option metric '1'
>     	option weight '2'
>     
>     config member 'wan2_m2_w2'
>     	option interface 'wan2'
>     	option metric '2'
>     	option weight '2'
>     
>     config policy 'wan_only'
>     	list use_member 'wan_m1_w3'
>     
>     config policy 'wan2_only'
>     	list use_member 'wan2_m1_w2'
>     
>     config policy 'balanced'
>     	list use_member 'wan_m1_w3'
>     	list use_member 'wan2_m1_w2'
>     
>     config policy 'wan_wan2'
>     	list use_member 'wan_m1_w3'
>     	list use_member 'wan2_m2_w2'
>     
>     config policy 'wan2_wan'
>     	list use_member 'wan_m2_w3'
>     	list use_member 'wan2_m1_w2'
>     
>     config rule 'https'
>     	option sticky '1'
>     	option dest_port '443'
>     	option proto 'tcp'
>     	option use_policy 'balanced'
>     
>     config rule 'default_rule'
>     	option dest_ip '0.0.0.0/0'
>     	option use_policy 'balanced'
>     
>     Output of "cat /etc/config/network" : 
>     
>     config interface 'loopback'
>     	option ifname 'lo'
>     	option proto 'static'
>     	option ipaddr '127.0.0.1'
>     	option netmask '255.0.0.0'
>     
>     config globals 'globals'
>     	option ula_prefix 'fd6a:5576:4fae::/48'
>     
>     config interface 'lan'
>     	option type 'bridge'
>     	option ifname 'eth1'
>     	option proto 'static'
>     	option ipaddr '192.168.1.1'
>     	option netmask '255.255.255.0'
>     	option ip6assign '60'
>     
>     config interface 'wan'
>     	option _orig_ifname 'eth0'
>     	option _orig_bridge 'false'
>     	option proto 'l2tp'
>     	option server '44.25.142.13'
>     	USERNAME HIDDEN
>     	PASSWORD HIDDEN
>     
>     config interface 'wan6'
>     	option ifname 'eth0'
>     	option proto 'dhcpv6'
>     
>     Output of "cat /etc/config/wireless" : 
>     
>     config wifi-device 'radio0'
>     	option type 'mac80211'
>     	option channel '11'
>     	option hwmode '11g'
>     	option path 'platform/ar933x_wmac'
>     	option htmode 'HT20'
>     	option disabled '1'
>     	option txpower '18'
>     	option country 'US'
>     
>     config wifi-iface
>     	option device 'radio0'
>     	option network 'lan'
>     	option mode 'ap'
>     	option ssid 'OpenWrt'
>     	option encryption 'psk2+ccmp'
>     	KEY HIDDEN
>     
>     Output of "ifconfig" : 
>     
>     br-lan    Link encap:Ethernet  HWaddr E4:95:6E:40:6C:AE  
>               inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
>               UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>               RX packets:1565 errors:0 dropped:0 overruns:0 frame:0
>               TX packets:1542 errors:0 dropped:0 overruns:0 carrier:0
>               collisions:0 txqueuelen:1000 
>               RX bytes:132438 (129.3 KiB)  TX bytes:395781 (386.5 KiB)
>     
>     eth0      Link encap:Ethernet  HWaddr E4:95:6E:40:6C:AE  
>               UP BROADCAST MULTICAST  MTU:1500  Metric:1
>               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>               collisions:0 txqueuelen:1000 
>               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
>               Interrupt:4 
>     
>     eth1      Link encap:Ethernet  HWaddr E4:95:6E:40:6C:AE  
>               UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>               RX packets:1569 errors:0 dropped:0 overruns:0 frame:0
>               TX packets:1547 errors:0 dropped:0 overruns:0 carrier:0
>               collisions:0 txqueuelen:1000 
>               RX bytes:154588 (150.9 KiB)  TX bytes:396011 (386.7 KiB)
>               Interrupt:5 
>     
>     lo        Link encap:Local Loopback  
>               inet addr:127.0.0.1  Mask:255.0.0.0
>               UP LOOPBACK RUNNING  MTU:65536  Metric:1
>               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>               collisions:0 txqueuelen:1 
>               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
>     
>     Output of "route -n" : 
>     
>     Kernel IP routing table
>     Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
>     192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
>     
>     Output of "ip rule show" : 
>     
>     0:	from all lookup local 
>     32766:	from all lookup main 
>     32767:	from all lookup default
>     
>     Output of "ip route list table 1-250" : 
>     
>     No data found
>     
>     Firewall default output policy (must be ACCEPT) : 
>     
>     ACCEPT
>     
>     Output of "iptables -L -t mangle -v -n" : 
>     
>     Chain PREROUTING (policy ACCEPT 1568 packets, 124K bytes)
>      pkts bytes target     prot opt in     out     source               destination         
>     
>     Chain INPUT (policy ACCEPT 1567 packets, 124K bytes)
>      pkts bytes target     prot opt in     out     source               destination         
>     
>     Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
>      pkts bytes target     prot opt in     out     source               destination         
>         0     0 TCPMSS     tcp  --  *      eth0    0.0.0.0/0            0.0.0.0/0            ID:66773300 tcp flags:0x06/0x02 /* wan (mtu_fix) */ TCPMSS >     clamp to PMTU
>     
>     Chain OUTPUT (policy ACCEPT 1540 packets, 374K bytes)
>      pkts bytes target     prot opt in     out     source               destination         
>     
>     Chain POSTROUTING (policy ACCEPT 1540 packets, 374K bytes)
>      pkts bytes target     prot opt in     out     source               destination

**Comment by arfett** [comment]
In that output there is only ONE instance of "USERNAME HIDDEN", "PASSWORD HIDDEN" and "KEY HIDDEN"

I was wondering if there were more instances would they all get hidden?

**Comment by psyborg55** [comment]
i have 2 l2tp connections running and 10 virtual APs and all user/pass/key data are hidden without global sed. now i tried adding another interface and VAP on ar933x device used for testing with global sed and also all sensitive data is marked as hidden in troubleshooting page. so it looks to me there is no difference if using sed with or without global variable being set.

**Comment by arfett** [comment]
Sounds good to me then. Thanks for checking to be sure.

**Comment by psyborg55** [comment]
OK, closing this pull request and opened new one with squashed commits https://github.com/openwrt/packages/pull/3697

**Pull request closed without merging**
