### PR TITLE
collectd: upgrade package collectd to version 5.8.0

### PR DESCRIPTION
**Pull request by thuehn**
This patch upgrades the collectd package from 5.7.2 to 5.8.2.
All openwrt patches got either updated or deleted in case they
are already included into upstream collectd.
The new collectd 5.8.0 package compiles and got tested on current
lede trunk with latest luci on an PCengines APU. All default plugins
also iwinfo are running fine with the new version.

Signed-off-by: Thomas Huehn thomas@net.t-labs.tu-berlin.de

Maintainer: Hannu Nyman
Compile tested: x86-64, PCEngines APU 2C4, LEDE trunk r5442)
Run tested: (x86-64, PCEngines APU 2C4, LEDE trunk r5442)

### CODE REVIEW

**Comment by hnyman** [comment]
Some questions:
* Have you compile-tested all plugins?
* Is there a specific reason why you have removed the libcap dependency elimination patch and have added libcap to dependencies?

* Please do not remvoe the Openwrt/LEDE specific explanations from 600-fix-libmodbus-detection.patch
* PKG_RELEASE should be dropped back to 1 when PKG_VERSION increases

**Comment by thuehn** [comment]
Hi Hannu,

Thx for your feedback ... my comments are inline

>Have you compile-tested all plugins?
Just those plugins that are enabled in the lede Makefile and the mqtt plugin. Those compile and do work on my APU board where I test.

Is there a specific reason why you have removed the libcap dependency elimination patch 700-disable-sys-capability-check.patch and have added libcap to dependencies?
> I have fixed this.

Please do not remvoe the Openwrt/LEDE specific explanations from 600-fix-libmodbus-detection.patch
> added back this descriptions

PKG_RELEASE should be dropped back to 1 when PKG_VERSION increases
> ok

I will send a new PR

**Comment by hnyman** [comment]
> I will send a new PR

No need for that. You can just force push this PR branch to update the PR.

**Comment by thuehn** [comment]
new version pushed -f :)

**Comment by hnyman** [comment]
I will test it.  (with ar71xx and ipq806x)

But also you should compile-test all plugins (for x86). Testing just those plugins that you use, is too relaxed approach...

**Comment by hnyman** [comment]
Slightly modified (disable new plugins, avoid unnecessary file renames) and applied as https://github.com/openwrt/packages/commit/55e530747f3543dec326ab057249b52d50431916

**Comment by thuehn** [comment]
Thx Hannu !

**Pull request closed without merging**
