### PR TITLE
[zoneinfo] Updated to actual md5 sums

### PR DESCRIPTION
**Pull request by Wedmer**
Sorry. Forgot to change md5sums.

### CODE REVIEW

**Comment by champtar** [comment]
fixed with 1b5d9a6fb37c7b55e3ee50593361aec6ce914e09
i've also reset PKG_RELEASE to 1

**Comment by Wedmer** [comment]
There're no information in Contributing Guidelines about PKG_RELEASE when the counter should be encreased or reseted.

**Comment by jow-** [comment]
PKG_RELEASE should be reset to 1 if the software version is changed. You should increment it if the packaging changed (like modified support script, different depends) or if you changed something in the package which causes the resulting binaries to behave differently (like new --disable* or --enable* switches for configure). Things like correcting md5sums, changing mirror urls, adding a maintainer field or updating a comment or copyright year in a Makefile do not require a change to PKG_RELEASE.

**Comment by Wedmer** [comment]
@jow- Thanks for clarification.

**Pull request closed without merging**
