### PR TITLE
boost: Fix fiber compilation for mips

### PR DESCRIPTION
**Pull request by neheb**
The issue was that the pause instruction was emitted through an asm
directive which was not correct for some mips platforms.

Simplified boost-fiber-exclude as a result.

Removed uClibc-ng math patch. It was not correct as it broke float and
long double support (std variants use function overloads). A different
solution was applied upstream. As it's quite annoying to backport, just
wait until a new release comes with that change. ARC as a platform is
barely supported anyways.

Swapped asio patch for the upstream submission, which is unfortunately, in
limbo.

Refreshed remaining patch.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ClaymorePT 
Compile tested: Lantiq ASE

https://downloads.openwrt.org/snapshots/faillogs/mips_mips32/packages/boost/compile.txt

### CODE REVIEW

**Comment by ClaymorePT** [comment]
@neheb I'm unable to test this at the moment. If it worked for you, I'm okay with it!

**Comment by neheb** [comment]
This section looks quite funny. Looks like it can be simplified:

```
	config boost-context-exclude
		bool
		default y if (TARGET_arc700 || TARGET_archs38 || TARGET_octeon || TARGET_octeontx)
		default n

	config boost-coroutine-exclude
		bool
		default y if boost-context-exclude
		default n

	config boost-fiber-exclude
		bool
		default y if boost-coroutine-exclude
		default n

```

**Comment by neheb** [comment]
I looked at the build failure again. It's failing on boost-python. Wonder why.

It also made me think about Python 2 going EOL in a month. Should we remove boost-python or rename python3 to python? Nothing in the tree uses it.

**Comment by ClaymorePT** [comment]
Python 2 is going EOL yes, but as long as there's a Python 2 package, Boost.python for 2.0 should be available. When Python2 is removed from the tree, then at that time I will remove Boost.Python for 2.0

**Comment by jefferyto** [comment]
I've gone through the CircleCI log, and I think it's failing because it ran out of memory.

There are these errors while building host boost:
```
g++: internal compiler error: Killed (program cc1plus)
```

and these errors while building target boost:
```
mips-openwrt-linux-gcc: fatal error: Killed signal terminated program cc1plus
```

I've compiled boost with changes in this PR locally using the brcm63xx sdk and it completed successfully. Will try compiling it for ath79 as well.

**Comment by neheb** [comment]
I more or less wanted commentary on having unused Python packages :P.

I couldn't care less about CircleCI failing.

**Comment by jefferyto** [comment]
Please see https://github.com/openwrt/packages/tree/master/lang/python#transition-policy--schedule.

**Pull request merged**
