### PR TITLE
xz: update to 5.6.1

### PR DESCRIPTION
**Pull request by krant**
Maintainer: N/A
Run tested: ARMv7, Linksys WRT3200ACM, master branch

### CODE REVIEW

**Comment by mhei** [comment]
I'd prefer to have a short note in the commit description that this also includes a download origin change.

BTW: is there a reason why your SoB does not include your full name but only your username?

**Comment by 1715173329** [comment]
> BTW: is there a reason why your SoB does not include your full name but only your username?

we have accepted such sob since 7e6cd98ad481184b1a620a9862aa3713d1ab85cc

**Comment by krant** [comment]
@mhei done. Regarding SoB - it does include my name, it is in the email part

**Comment by mhei** [comment]
I know that we accept such SoBs. I asked the question out of pure curiosity. Since the email address already contains the name anyway, why do you use the username and not your full name? If you feel that I'm not allowed to ask such questions or feel offended, then sorry - this is not my intend - just tell me.

**Comment by krant** [comment]
> Since the email address already contains the name anyway, why do you use the username and not your full name?

I'm honestly not understanding. If my email already contains full name, what's the point of repeating it besides? Providing a username allows to link git to Github at least.

> If you [...] feel offended, then sorry

I feel sorry too. It is hard sometimes to distinguish genuine questions here from authority-abusing maintainers preventing useful changes to become available to the community.

**Comment by mhei** [comment]
> Providing a username allows to link git to Github at least.

Yes, good point in "offline" re-view (i.e. not in Github web UI). Thanks for clarification, appreciated.

> [...] from authority-abusing maintainers preventing useful changes

This sounds like really bad contribution experience. I hope that this are rare cases, especially here in OpenWrt community.

**Comment by nwf** [comment]
This should be reverted immediately; see https://www.openwall.com/lists/oss-security/2024/03/29/4

**Comment by 1715173329** [comment]
Yes, thanks for the hint, reverted in 9e46b47ca3ece6de6bb185ba3645299167150b59.

**Comment by nwf** [comment]
Thanks!  Sorry for not seeing the earlier commit.

**Comment by 1715173329** [comment]
No worries ;)

**Comment by krant** [comment]
Thanks to everyone reacted so fast, you're the best! Hopefully no OpenWrt device was compromised.

**Pull request merged**
