### PR TITLE
collectd: enable cpufreq plugin for mediatek

### PR DESCRIPTION
**Pull request by selanf**
tested on e8450 ubi+non-ubi

### CODE REVIEW

**Comment by feckert** [comment]
Can you please bump the PKG_RELEASE number in the Makefile.

**Comment by selanf** [comment]
Screenshot: 
image

**Comment by feckert** [comment]
Thanks Merged

**Comment by hnyman** [comment]
Interesting. I didn't even test it on my E8450/RT3200 as I though the scaling to be disabled.

**Comment by selanf** [comment]
@hnyman: You need to set another governor, by menuconfig or during runtime. Without any chnages the device runs at full speed and full temperature.
I use it this way: https://github.com/openwrt/openwrt/pull/4440 but dangowrt want to do it in another way

**Pull request merged**
