### PR TITLE
ddns-scripts: Add INWX service

### PR DESCRIPTION
**Pull request by ffflorian**
Maintainer: me / @ffflorian
Compile tested: no
Run tested: yes

Description:
This adds INWX to the list of DDNS services.

### CODE REVIEW

**Comment by feckert** [comment]
Please add a Signed-off-by to your change

**Comment by ffflorian** [comment]
> Please add a Signed-off-by to your change

Done :slightly_smiling_face:

**Comment by neheb** [comment]
Should have PKG_RELEASE bumped as well.

**Comment by ffflorian** [comment]
> Should have PKG_RELEASE bumped as well.

Should I bump to 2.8.0 or 2.7.9?

**Comment by ffflorian** [comment]
> Should have PKG_RELEASE bumped as well.

Done :slightly_smiling_face:

**Pull request merged**
