### PR TITLE
pulseaudio: update to 8.0

### PR DESCRIPTION
**Pull request by bk138**
This also drops one build-fixing patch that's not needed anymore.

Signed-off-by: Christian Beier <dontmind@freeshell.org>

### CODE REVIEW

**Comment by thess** [comment]
@tripolar - OK?

(Note: It's 2016 now)

**Comment by bk138** [comment]
Dear @tripolar , I saw you already updated PA to 8.0 on Feb 22nd. Thanks! Still, the second commit of this PR https://github.com/bk138/packages/commit/8979c9ab76e530484fb8c7cb0e90425222d51572 is needed to make PA actually work on a boxx. Do you mind merging this?

**Comment by tripolar** [comment]
```
ps w|grep pulse
 1713 pulse    10348 S <  /usr/bin/pulseaudio --system --disallow-exit --disallow-module-loading --disable-shm --exit-idle-time=-1
 3552 root      1292 S    grep pulse
```

at least it works here without a problem

```
ls -la /usr/share/pulseaudio/alsa-mixer/paths/
drwxr-xr-x    2 root     root          4096 Mar  6 22:47 .
drwxr-xr-x    4 root     root          4096 Mar  6 22:47 ..
-rw-------    1 root     root          1415 Mar  6 19:08 analog-input-aux.conf
-rw-------    1 root     root          2185 Mar  6 19:08 analog-input-dock-mic.conf
-rw-------    1 root     root          1420 Mar  6 19:08 analog-input-fm.conf
-rw-------    1 root     root          2196 Mar  6 19:08 analog-input-front-mic.conf
-rw-------    1 root     root          2298 Mar  6 19:08 analog-input-headphone-mic.conf
-rw-------    1 root     root          2360 Mar  6 19:08 analog-input-headset-mic.conf
-rw-------    1 root     root          2797 Mar  6 19:08 analog-input-internal-mic-always.conf
-rw-------    1 root     root          3155 Mar  6 19:08 analog-input-internal-mic.conf
-rw-------    1 root     root          2486 Mar  6 19:08 analog-input-linein.conf
-rw-------    1 root     root          1457 Mar  6 19:08 analog-input-mic-line.conf
-rw-------    1 root     root          2662 Mar  6 19:08 analog-input-mic.conf
-rw-------    1 root     root          1330 Mar  6 19:08 analog-input-mic.conf.common
-rw-------    1 root     root          2185 Mar  6 19:08 analog-input-rear-mic.conf
-rw-------    1 root     root          1425 Mar  6 19:08 analog-input-tvtuner.conf
-rw-------    1 root     root          1385 Mar  6 19:08 analog-input-video.conf
-rw-------    1 root     root          2056 Mar  6 19:08 analog-input.conf
-rw-------    1 root     root          5769 Mar  6 19:08 analog-input.conf.common
-rw-------    1 root     root          2139 Mar  6 19:08 analog-output-headphones-2.conf
-rw-------    1 root     root          3147 Mar  6 19:08 analog-output-headphones.conf
-rw-------    1 root     root          4095 Mar  6 19:08 analog-output-lineout.conf
-rw-------    1 root     root          1993 Mar  6 19:08 analog-output-mono.conf
-rw-------    1 root     root          3725 Mar  6 19:08 analog-output-speaker-always.conf
-rw-------    1 root     root          4521 Mar  6 19:08 analog-output-speaker.conf
-rw-------    1 root     root          1929 Mar  6 19:08 analog-output.conf
-rw-------    1 root     root         10609 Mar  6 19:08 analog-output.conf.common
-rw-------    1 root     root           159 Mar  6 19:08 hdmi-output-0.conf
-rw-------    1 root     root           161 Mar  6 19:08 hdmi-output-1.conf
-rw-------    1 root     root           161 Mar  6 19:08 hdmi-output-2.conf
-rw-------    1 root     root           161 Mar  6 19:08 hdmi-output-3.conf
-rw-------    1 root     root           163 Mar  6 19:08 hdmi-output-4.conf
-rw-------    1 root     root           163 Mar  6 19:08 hdmi-output-5.conf
-rw-------    1 root     root           163 Mar  6 19:08 hdmi-output-6.conf
-rw-------    1 root     root           163 Mar  6 19:08 hdmi-output-7.conf
-rw-------    1 root     root           712 Mar  6 19:08 iec958-stereo-output.conf

```

Which error do you get?

**Comment by bk138** [comment]
Might have something to do with my external sound card. This is what is get:
`
root@boxx_44:~# paplay YouGotmail.wav 
Stream error: No such entity
root@boxx_44:~# chmod 644 /usr/share/pulseaudio/alsa-mixer/profile-sets/*
root@boxx_44:~# chmod 644 /usr/share/pulseaudio/alsa-mixer/paths/*
root@boxx_44:~# /etc/init.d/pulseaudio restart
root@boxx_44:~# paplay YouGotmail.wav 
root@boxx_44:~# now i got mail ;-)
`

**Comment by tripolar** [comment]
please try to use cmus and also create a different user without root privileges. I just use my openwrt pulseaudio installation as remote pulse instance but cmus works without a problem here. 
```

pulseaudio --system --disallow-exit --disallow-module-loading --disable-shm --exit-idle-time=-1 --realtime=false
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please note that you most likely shouldn't be doing that.
W: [pulseaudio] main.c: If you do it nonetheless then it's your own fault if things don't work as expected.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.

```

did you configure pulseaudio?

**Comment by bk138** [comment]
Here we go:
```
root@boxx_44:~# pulseaudio --system --disallow-exit --disallow-module-loading --disable-shm --exit-idle-time=-1 --realtime=fal
se -v
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: Found user 'pulse' (UID 51) and group 'pulse' (GID 51).
I: [pulseaudio] main.c: Successfully changed user to "pulse".
I: [pulseaudio] main.c: This is PulseAudio 8.0
I: [pulseaudio] main.c: Page size is 4096 bytes
I: [pulseaudio] main.c: Machine ID is fc9a404aa3e78d444549a28456b762da.
I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
I: [pulseaudio] main.c: Using state directory /var/lib/pulse.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-8.0/modules.
I: [pulseaudio] main.c: Running in system mode: yes
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please note that you most likely shouldn't be doing that.
W: [pulseaudio] main.c: If you do it nonetheless then it's your own fault if things don't work as expected.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
I: [pulseaudio] main.c: System supports high resolution timers
W: [pulseaudio] module.c: module-detect is deprecated: Please use module-udev-detect instead of module-detect!
W: [pulseaudio] conf-parser.c: Failed to open configuration file '/usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf': Permission denied
E: [pulseaudio] module.c: Failed to load module "module-alsa-sink" (argument: "device_id=0"): initialization failed.
W: [pulseaudio] conf-parser.c: Failed to open configuration file '/usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf': Permission denied
E: [pulseaudio] module.c: Failed to load module "module-alsa-source" (argument: "device_id=0"): initialization failed.
W: [pulseaudio] module.c: module-oss is deprecated: Please use module-alsa-card instead of module-oss!
I: [pulseaudio] module-oss.c: Device opened in O_RDWR mode.
I: [pulseaudio] module-oss.c: Input -- 4 fragments of size 4096.
I: [pulseaudio] module-oss.c: Output -- 4 fragments of size 4096.
W: [pulseaudio] module-oss.c: mmap(PROT_READ) failed, reverting to non-mmap mode: Input/output error
I: [pulseaudio] source.c: Created source 0 "oss_input.dsp" with sample spec s16be 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.string = "/dev/dsp"
I: [pulseaudio] source.c:     device.api = "oss"
I: [pulseaudio] source.c:     device.description = "/dev/dsp"
I: [pulseaudio] source.c:     device.access_mode = "serial"
I: [pulseaudio] source.c:     device.buffering.buffer_size = "16384"
I: [pulseaudio] source.c:     device.buffering.fragment_size = "4096"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
I: [pulseaudio] sink.c: Created sink 0 "oss_output.dsp" with sample spec s16be 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink.c:     device.string = "/dev/dsp"
I: [pulseaudio] sink.c:     device.api = "oss"
I: [pulseaudio] sink.c:     device.description = "/dev/dsp"
I: [pulseaudio] sink.c:     device.access_mode = "serial"
I: [pulseaudio] sink.c:     device.buffering.buffer_size = "16384"
I: [pulseaudio] sink.c:     device.buffering.fragment_size = "4096"
I: [pulseaudio] sink.c:     device.icon_name = "audio-card"
I: [pulseaudio] source.c: Created source 1 "oss_output.dsp.monitor" with sample spec s16be 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.description = "Monitor of /dev/dsp"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
I: [pulseaudio] module.c: Loaded "module-oss" (index: #3; argument: "device=/dev/dsp").
I: [pulseaudio] module-detect.c: loaded 1 modules.
I: [pulseaudio] module.c: Loaded "module-detect" (index: #0; argument: "").
I: [pulseaudio] module.c: Loaded "module-esound-protocol-unix" (index: #4; argument: "").
I: [pulseaudio] module.c: Loaded "module-native-protocol-unix" (index: #5; argument: "").
I: [pulseaudio] module-stream-restore.c: Successfully opened database file '/tmp/lib/pulse/fc9a404aa3e78d444549a28456b762da-stream-volumes'.
I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #6; argument: "").
I: [pulseaudio] module-device-restore.c: Successfully opened database file '/tmp/lib/pulse/fc9a404aa3e78d444549a28456b762da-device-volumes'.
I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #7; argument: "").
I: [pulseaudio] module-default-device-restore.c: Saved default sink 'auto_null' not existent, not restoring default sink setting.
I: [pulseaudio] module-default-device-restore.c: Saved default source 'auto_null.monitor' not existent, not restoring default source setting.
I: [pulseaudio] module.c: Loaded "module-default-device-restore" (index: #8; argument: "").
I: [pulseaudio] module.c: Loaded "module-rescue-streams" (index: #9; argument: "").
I: [pulseaudio] module.c: Loaded "module-always-sink" (index: #10; argument: "").
E: [oss] module-oss.c: Failed to read data from DSP: Invalid argument
I: [pulseaudio] module.c: Loaded "module-suspend-on-idle" (index: #11; argument: "").
I: [pulseaudio] module.c: Loaded "module-position-event-sounds" (index: #12; argument: "").
I: [pulseaudio] main.c: Daemon startup complete.
I: [pulseaudio] module.c: Unloading "module-detect" (index: #0).
I: [pulseaudio] module.c: Unloaded "module-detect" (index: #0).
I: [pulseaudio] module.c: Unloading "module-oss" (index: #3).
W: [pulseaudio] module-always-sink.c: Unable to load module-null-sink
I: [pulseaudio] sink.c: Freeing sink 0 "oss_output.dsp"
I: [pulseaudio] source.c: Freeing source 1 "oss_output.dsp.monitor"
I: [pulseaudio] source.c: Freeing source 0 "oss_input.dsp"
I: [pulseaudio] module.c: Unloaded "module-oss" (index: #3).

```
This is with the out-of-the-box config. 

For using paplay on the box, I added 
`auth-anonymous=1` to `load-module module-native-protocol-unix` and PA tells me
```
I: [pulseaudio] client.c: Created 1 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
I: [pulseaudio] client.c: Freed 1 "paplay"
I: [pulseaudio] protocol-native.c: Connection died.
```

And on the user side
```
root@boxx_44:~# paplay YouGotmail.wav 
Stream error: No such entity
```

Once change the permissions of paths and profiles-sets to 644, I get
```
root@boxx_44:~# pulseaudio --system --disallow-exit --disallow-module-loading --disable-shm --exit-idle-time=-1 --realtime=fal
se -v
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: Found user 'pulse' (UID 51) and group 'pulse' (GID 51).
I: [pulseaudio] main.c: Successfully changed user to "pulse".
I: [pulseaudio] main.c: This is PulseAudio 8.0
I: [pulseaudio] main.c: Page size is 4096 bytes
I: [pulseaudio] main.c: Machine ID is fc9a404aa3e78d444549a28456b762da.
I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
I: [pulseaudio] main.c: Using state directory /var/lib/pulse.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-8.0/modules.
I: [pulseaudio] main.c: Running in system mode: yes
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please note that you most likely shouldn't be doing that.
W: [pulseaudio] main.c: If you do it nonetheless then it's your own fault if things don't work as expected.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
I: [pulseaudio] main.c: System supports high resolution timers
W: [pulseaudio] module.c: module-detect is deprecated: Please use module-udev-detect instead of module-detect!
I: [pulseaudio] alsa-util.c: Cannot disable ALSA period wakeups
I: [pulseaudio] alsa-util.c: Device front:0 doesn't support sample format s16be, changed to s16le.
I: [pulseaudio] alsa-util.c: ALSA period wakeups were not disabled
I: [pulseaudio] alsa-sink.c: Successfully opened device front:0.
I: [pulseaudio] alsa-sink.c: Selected mapping 'Analog Stereo' (analog-stereo).
I: [pulseaudio] alsa-sink.c: Successfully enabled mmap() mode.
I: [pulseaudio] alsa-sink.c: Successfully enabled timer-based scheduling mode.
I: [pulseaudio] (alsa-lib)control.c: Invalid CTL front:0
I: [pulseaudio] alsa-util.c: Unable to attach to mixer front:0: No such file or directory
I: [pulseaudio] alsa-util.c: Successfully attached to mixer 'hw:0'
I: [pulseaudio] sink.c: Created sink 0 "alsa_output.0.analog-stereo" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink.c:     alsa.resolution_bits = "16"
I: [pulseaudio] sink.c:     device.api = "alsa"
I: [pulseaudio] sink.c:     device.class = "sound"
I: [pulseaudio] sink.c:     alsa.class = "generic"
I: [pulseaudio] sink.c:     alsa.subclass = "generic-mix"
I: [pulseaudio] sink.c:     alsa.name = "USB Audio"
I: [pulseaudio] sink.c:     alsa.id = "USB Audio"
I: [pulseaudio] sink.c:     alsa.subdevice = "0"
I: [pulseaudio] sink.c:     alsa.subdevice_name = "subdevice #0"
I: [pulseaudio] sink.c:     alsa.device = "0"
I: [pulseaudio] sink.c:     alsa.card = "0"
I: [pulseaudio] sink.c:     alsa.card_name = "USB AUDIO  CODEC"
I: [pulseaudio] sink.c:     alsa.long_card_name = "BurrBrown from Texas Instruments USB AUDIO  CODEC at usb-ehci-platform.1-1, ful"
I: [pulseaudio] sink.c:     alsa.driver_name = "snd_usb_audio"
I: [pulseaudio] sink.c:     device.string = "front:0"
I: [pulseaudio] sink.c:     device.buffering.buffer_size = "352800"
I: [pulseaudio] sink.c:     device.buffering.fragment_size = "176400"
I: [pulseaudio] sink.c:     device.access_mode = "mmap+timer"
I: [pulseaudio] sink.c:     device.profile.name = "analog-stereo"
I: [pulseaudio] sink.c:     device.profile.description = "Analog Stereo"
I: [pulseaudio] sink.c:     device.description = "USB AUDIO  CODEC Analog Stereo"
I: [pulseaudio] sink.c:     alsa.mixer_name = "USB Mixer"
I: [pulseaudio] sink.c:     alsa.components = "USB08bb:29c2"
I: [pulseaudio] sink.c:     device.icon_name = "audio-card-analog"
I: [pulseaudio] source.c: Created source 0 "alsa_output.0.analog-stereo.monitor" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.description = "Monitor of USB AUDIO  CODEC Analog Stereo"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
I: [pulseaudio] alsa-sink.c: Using 2.0 fragments of size 176400 bytes (1000.00ms), buffer size is 352800 bytes (2000.00ms)
I: [pulseaudio] alsa-sink.c: Time scheduling watermark is 20.00ms
I: [alsa-sink-USB Audio] alsa-sink.c: Starting playback.
I: [pulseaudio] module.c: Loaded "module-alsa-sink" (index: #1; argument: "device_id=0").
I: [pulseaudio] alsa-util.c: Cannot disable ALSA period wakeups
I: [pulseaudio] alsa-util.c: Device front:0 doesn't support sample format s16be, changed to s16le.
I: [pulseaudio] alsa-util.c: ALSA period wakeups were not disabled
I: [pulseaudio] alsa-source.c: Successfully opened device front:0.
I: [pulseaudio] alsa-source.c: Selected mapping 'Analog Stereo' (analog-stereo).
I: [pulseaudio] alsa-source.c: Successfully enabled mmap() mode.
I: [pulseaudio] alsa-source.c: Successfully enabled timer-based scheduling mode.
I: [pulseaudio] (alsa-lib)control.c: Invalid CTL front:0
I: [pulseaudio] alsa-util.c: Unable to attach to mixer front:0: No such file or directory
I: [pulseaudio] alsa-util.c: Successfully attached to mixer 'hw:0'
I: [pulseaudio] source.c: Created source 1 "alsa_input.0.analog-stereo" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     alsa.resolution_bits = "16"
I: [pulseaudio] source.c:     device.api = "alsa"
I: [pulseaudio] source.c:     device.class = "sound"
I: [pulseaudio] source.c:     alsa.class = "generic"
I: [pulseaudio] source.c:     alsa.subclass = "generic-mix"
I: [pulseaudio] source.c:     alsa.name = "USB Audio"
I: [pulseaudio] source.c:     alsa.id = "USB Audio"
I: [pulseaudio] source.c:     alsa.subdevice = "0"
I: [pulseaudio] source.c:     alsa.subdevice_name = "subdevice #0"
I: [pulseaudio] source.c:     alsa.device = "0"
I: [pulseaudio] source.c:     alsa.card = "0"
I: [pulseaudio] source.c:     alsa.card_name = "USB AUDIO  CODEC"
I: [pulseaudio] source.c:     alsa.long_card_name = "BurrBrown from Texas Instruments USB AUDIO  CODEC at usb-ehci-platform.1-1, ful"
I: [pulseaudio] source.c:     alsa.driver_name = "snd_usb_audio"
I: [pulseaudio] source.c:     device.string = "front:0"
I: [pulseaudio] source.c:     device.buffering.buffer_size = "352800"
I: [pulseaudio] source.c:     device.buffering.fragment_size = "176400"
I: [pulseaudio] source.c:     device.access_mode = "mmap+timer"
I: [pulseaudio] source.c:     device.profile.name = "analog-stereo"
I: [pulseaudio] source.c:     device.profile.description = "Analog Stereo"
I: [pulseaudio] source.c:     device.description = "USB AUDIO  CODEC Analog Stereo"
I: [pulseaudio] source.c:     alsa.mixer_name = "USB Mixer"
I: [pulseaudio] source.c:     alsa.components = "USB08bb:29c2"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone-analog"
I: [pulseaudio] alsa-source.c: Using 2.0 fragments of size 176400 bytes (1000.00ms), buffer size is 352800 bytes (2000.00ms)
I: [pulseaudio] alsa-source.c: Time scheduling watermark is 20.00ms
I: [alsa-source-USB Audio] alsa-source.c: Starting capture.
I: [pulseaudio] module.c: Loaded "module-alsa-source" (index: #2; argument: "device_id=0").
I: [pulseaudio] module-detect.c: loaded 2 modules.
I: [pulseaudio] module.c: Loaded "module-detect" (index: #0; argument: "").
I: [pulseaudio] module.c: Loaded "module-esound-protocol-unix" (index: #3; argument: "").
I: [pulseaudio] module.c: Loaded "module-native-protocol-unix" (index: #4; argument: "auth-anonymous=1").
I: [pulseaudio] module-stream-restore.c: Successfully opened database file '/tmp/lib/pulse/fc9a404aa3e78d444549a28456b762da-stream-volumes'.
I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #5; argument: "").
I: [pulseaudio] module-device-restore.c: Successfully opened database file '/tmp/lib/pulse/fc9a404aa3e78d444549a28456b762da-device-volumes'.
I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #6; argument: "").
I: [pulseaudio] module-default-device-restore.c: Saved default sink 'auto_null' not existent, not restoring default sink setting.
I: [pulseaudio] module-default-device-restore.c: Saved default source 'auto_null.monitor' not existent, not restoring default source setting.
I: [pulseaudio] module.c: Loaded "module-default-device-restore" (index: #7; argument: "").
I: [pulseaudio] module.c: Loaded "module-rescue-streams" (index: #8; argument: "").
I: [pulseaudio] module.c: Loaded "module-always-sink" (index: #9; argument: "").
I: [pulseaudio] module.c: Loaded "module-suspend-on-idle" (index: #10; argument: "").
I: [pulseaudio] module.c: Loaded "module-position-event-sounds" (index: #11; argument: "").
I: [pulseaudio] main.c: Daemon startup complete.
I: [pulseaudio] module.c: Unloading "module-detect" (index: #0).
I: [pulseaudio] module.c: Unloaded "module-detect" (index: #0).
I: [pulseaudio] module-suspend-on-idle.c: Source alsa_input.0.analog-stereo idle for too long, suspending ...
I: [alsa-source-USB Audio] alsa-source.c: Device suspended...
I: [pulseaudio] module-suspend-on-idle.c: Sink alsa_output.0.analog-stereo idle for too long, suspending ...
I: [alsa-sink-USB Audio] alsa-sink.c: Device suspended...

```

and paplay works just fine:

```
I: [pulseaudio] client.c: Created 0 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
I: [pulseaudio] sink-input.c: Trying to change sample rate
I: [alsa-sink-USB Audio] alsa-sink.c: Trying resume...
I: [alsa-sink-USB Audio] alsa-util.c: Cannot disable ALSA period wakeups
I: [alsa-sink-USB Audio] alsa-util.c: ALSA period wakeups were not disabled
I: [alsa-sink-USB Audio] alsa-sink.c: Time scheduling watermark is 20.00ms
I: [alsa-sink-USB Audio] alsa-sink.c: Resumed successfully...
I: [alsa-sink-USB Audio] alsa-sink.c: Starting playback.
I: [pulseaudio] resampler.c: Speex appears to be compiled with --enable-fixed-point. Switching to a fixed-point resampler because it should be faster.
I: [pulseaudio] remap.c: Using mono to stereo remapping
I: [pulseaudio] speex.c: Choosing speex quality setting 1.
I: [pulseaudio] sink-input.c: Created input 0 "YouGotmail.wav" on alsa_output.0.analog-stereo with sample spec s16be 1ch 11000Hz and channel map mono
I: [pulseaudio] sink-input.c:     media.format = "WAV (Microsoft)"
I: [pulseaudio] sink-input.c:     application.name = "paplay"
I: [pulseaudio] sink-input.c:     media.name = "YouGotmail.wav"
I: [pulseaudio] sink-input.c:     native-protocol.peer = "UNIX socket client"
I: [pulseaudio] sink-input.c:     native-protocol.version = "30"
I: [pulseaudio] sink-input.c:     application.process.id = "2868"
I: [pulseaudio] sink-input.c:     application.process.user = "root"
I: [pulseaudio] sink-input.c:     application.process.host = "boxx_44"
I: [pulseaudio] sink-input.c:     application.process.binary = "paplay"
I: [pulseaudio] sink-input.c:     application.language = "C"
I: [pulseaudio] sink-input.c:     window.x11.display = "localhost:11.0"
I: [pulseaudio] sink-input.c:     application.process.machine_id = "fc9a404aa3e78d444549a28456b762da"
I: [pulseaudio] sink-input.c:     module-stream-restore.id = "sink-input-by-application-name:paplay"
I: [pulseaudio] protocol-native.c: Requested tlength=2000.00 ms, minreq=20.00 ms
I: [pulseaudio] protocol-native.c: Final latency 3960.00 ms = 1960.00 ms + 2*20.00 ms + 1960.00 ms
I: [pulseaudio] sink-input.c: Freeing input 0 "YouGotmail.wav"
I: [pulseaudio] client.c: Freed 0 "paplay"
I: [pulseaudio] protocol-native.c: Connection died.
I: [pulseaudio] module-suspend-on-idle.c: Sink alsa_output.0.analog-stereo idle for too long, suspending ...
I: [alsa-sink-USB Audio] alsa-sink.c: Device suspended...

```

**Comment by bk138** [comment]
Is there any additional info I can provide?

**Comment by champtar** [comment]
@tripolar @bk138 what's the status of this PR

**Comment by bk138** [comment]
Is there more info I shall provide?

**Comment by tripolar** [comment]
i'm sorry that I can't help you but this problem is not related to openwrt. Please go to the pulseaudio mailing list or the pulseaudio bug tracker and ask there for help.

**Comment by bk138** [comment]
@tripolar Sorry, but this is a packaging-related issue and a valid PR IMO. It basically boils down to the fact that pulseaudio running as the pulse user cannot access its files installed as 0600, owned by root. I can change https://github.com/openwrt/packages/pull/2332/commits/8979c9ab76e530484fb8c7cb0e90425222d51572 to still install the files 0600, but owned by pulse user, if you have security concerns?

**Comment by tripolar** [comment]
look at the make file, the patch got merged already - https://github.com/openwrt/packages/blob/master/sound/pulseaudio/Makefile

**Comment by bk138** [comment]
Ah you're right, 6c0d7a1db73573190f9f4ccb25a1340bb6c9a742 by @thess added this as well. Then this PR is obsolete, yes. Thanks!

**Pull request closed without merging**
