### PR TITLE
dnscrypt-proxy: update dnscrypt-resolvers.csv

### PR DESCRIPTION
**Pull request by starcms**
Maintainer: @damianorenfer, @black-roland 
Compile tested: all
Run tested: LEDE arm_cortex-a9_vfpv3

Description: Update dnscrypt-proxy-resolvers package with most up-to-date version from https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv.  Current version is more than 6 months+ out-of-date.

### CODE REVIEW

**Comment by hnyman** [comment]
@starcms 
you should
* update also PKG_RELEASE in Makefile as the packaged contents change.
* sign off your commit properly. (in commit message itself)

**Comment by starcms** [comment]
@hnyman , this is my first time :)

I did the first part.  How do I sign off my commit properly?  Thanks!!

**Comment by hnyman** [comment]
> How do I sign off my commit properly? Thanks!!

You include a Signed-off-by line  with your real name in the commit message (instead of putting it just to this PR discussion that doesnot get stored to the git history).

https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork

Example:
https://github.com/openwrt/packages/commit/c3b0a36db4e0778da32f95e28b7968a4ae4a2502

**Comment by black-roland** [comment]
@starcms Sign-off it is a simple line with your name at the end of commit description. Please see additional info [here](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#commits-in-your-pull-requests-should) and [here](https://stackoverflow.com/questions/13457203/how-to-add-the-signed-off-by-field-in-the-git-patch).

You can use `git rebase` to change your commits. For example:
```
git rebase --interactive 06b055aa916c3e31eeb0b3f908b095cb871665a6
```
Then change opened file to something like that:
```
reword 9a6e687 Update dnscrypt-resolvers.csv
reword 489cc41 Update Makefile
reword b3ae2e4 Update Makefile
```
Or if you want to get a single commit (instead of 3):
```
pick 9a6e687 Update dnscrypt-resolvers.csv
squash 489cc41 Update Makefile
squash b3ae2e4 Update Makefile
```
Then simply change your commit descriptions and add "Signed-off-by..." line at the end.

Use `git push --force` for pushing rewrited git history.

**Comment by damianorenfer** [comment]
@starcms you are right! I forgot to update it, this is why I don't think it is a good idea to mirror this kind of files.

**Comment by starcms** [comment]
@black-roland or @damianorenfer , I honestly can't figure out how to do it.  I'm using just the web interface.  I don't have any command line tools installed.  Can't figure out how to modify or delete anything.  Can you do a pull request.

**Comment by black-roland** [comment]
> this is why I don't think it is a good idea to mirror this kind of files

@damianorenfer The problem is new versions of dnscrypt releases less frequently than resolvers list. Dnscrypt recommends [this script](https://github.com/jedisct1/dnscrypt-proxy/blob/master/contrib/dnscrypt-update-resolvers.sh.in) to update resolvers. But by default, we don't have HTTPS support nor minisig on a router.

I don't know how we can solve this issue. Do you have any suggestions?

**Comment by damianorenfer** [comment]
@black-roland you are right, there is no easy solution I think too. A solution would be to create a dnscrypt-proxy-resolvers-updater (or another name, that's not the point here) package which depends on curl or GNU wget. Basically, it could be a script which downloads the resolvers file at a fixed or configurable interval or on manual triggering. And for those who don't want to use this, they will have the resolvers from the latest dnscrypt-proxy package release.

Having a package for resolvers is a nice and clean solution, but each time the resolvers list is updated we will have to do a new PR which is not very convenient I think.

Your opinion about this ?

**Pull request closed without merging**
