### PR TITLE
squid: version bump and dependency fixes

### PR DESCRIPTION
**Pull request by danielg4**
Signed-off-by: Daniel Gimpelevich <daniel@gimpelevich.san-francisco.ca.us>

### CODE REVIEW

**Comment by danielg4** [comment]
Ping

**Comment by danielg4** [comment]
Ping

**Comment by lperkov** [comment]
Can you please let me know why were this items removed?

-	--enable-auth \
-	--enable-auth-basic \
-	--enable-auth-ntlm \
-	--enable-auth-negotiate \
-	--enable-auth-digest \

**Comment by danielg4** [comment]
They were duplicates. No idea why they were in the options list twice.

**Pull request merged**
