### PR TITLE
[23.05] xfrpc: update to version 23.05

### PR DESCRIPTION
**Pull request by liudf0716**
Maintainer: @liudf0716
Compile tested: x86_64
Run tested: x86_64

Description:
   
Release notes:
https://github.com/liudf0716/xfrpc/releases/tag/2.9.644

Dengfeng Liu <liudf0716@gmail.com>

### CODE REVIEW

**Comment by 1715173329** [comment]
looks like you mixed something else in your commits.

please cherry pick commit 6cd80e07273d7e7f291f15601f0cf77f88732351 instead, so we can track this change (from master branch to stable branch).

**Comment by liudf0716** [comment]
> looks like you mixed something else in your commits.
> 
> please cherry pick commit [6cd80e0](https://github.com/openwrt/packages/commit/6cd80e07273d7e7f291f15601f0cf77f88732351) (`git cherry-pick -x 6cd80e07273d`) instead, so we can track this change (from master branch to stable branch).

I have used cherry-pick, but don't know why PKG_MIRROR_HASH report error

**Comment by 1715173329** [comment]
please drop 09c16f059170177d92bb951a4662ce44e58d80be and e302b6c8c72dad7d2260480ca9f43280f11fe2e4 anyway

**Comment by 1715173329** [comment]
> but don't know why PKG_MIRROR_HASH report error

it would be nice to switch to codeload then. e.g.
https://github.com/openwrt/packages/blob/eb711e2eb2ab896018751bf3c7a66cbff6a43317/net/dnslookup/Makefile#L11-L13

**Comment by liudf0716** [comment]
> please drop [09c16f0](https://github.com/openwrt/packages/commit/09c16f059170177d92bb951a4662ce44e58d80be) and [e302b6c](https://github.com/openwrt/packages/commit/e302b6c8c72dad7d2260480ca9f43280f11fe2e4) anyway

sorry for that.

**Pull request merged**
