### PR TITLE
devel/automake: GNU Automake

### PR DESCRIPTION
**Pull request by xypron**
Automake is a tool for automatically generating Makefile.in files compliant
with the GNU Coding Standards.

A new package automake is provided.

Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

### CODE REVIEW

**Comment by xypron** [comment]
@mhei
Thank you for reviewing.

**Comment by mhei** [comment]
Merged via cherry-picking, thanks!

**Comment by maximeguerreiro** [comment]
Hello,
Any reason this package is not available in branches (for-15.05)?

Thanks!

**Comment by hnyman** [comment]
Because it has been added after the 15.05 release was branched. 
(package has been added in Dec 2015, while 15.05 branched in May 2015).

In general, new packages are not added to the old stable branches.

**Comment by maximeguerreiro** [comment]
Oh, that was an easy answer. I thought it was because master was more like a devel branch, with tools & so on.

Thanks! Looks like I'll have to import it manually for my PKG FIXUP to work, then

**Pull request closed without merging**
