### PR TITLE
gl-mifi-mcu: make compatible with newer kernel (fix #21198)

### LINKED ISSUE #21198: gl-mifi-mcu Werror=cast-function-type
Maintainer: @nunojpg / @Ansuel
Environment: arm_cortex-a15+neon-vfpv4_musl_eabi/linux-armvirt_32 WIP 6.1 tree https://github.com/openwrt/openwrt/pull/12705

Have not recreated this myself, but making issue for reference.

Description:
https://github.com/openwrt/packages/blob/e7e66545b17649368547b0e9d248a577fb4b4703/utils/gl-mifi-mcu/Makefile#L4
`Werror=cast-function-type` in building

https://github.com/openwrt/openwrt/pull/12705#issuecomment-1565116709
```
~/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-armvirt_32/gl-mifi-mcu-1/module.c:
In function 'gl_mifi_mcu_init':
~/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-armvirt_32/gl-mifi-mcu-1/module.c:181:5:
error: cast between incompatible function types from
'irqreturn_t (* (*)(unsigned int,  void *, struct pt_regs *))(int,  void *)'
{aka 'enum irqreturn (* (*)(unsigned int,  void *, struct pt_regs *))(int,  void *)'}
to
'irqreturn_t (*)(int,  void *)'
{aka 'enum irqreturn (*)(int,  void *)'} [-Werror=cast-function-type]
  181 |     (irq_handler_t) handle_rx_start,
      |     ^
cc1: all warnings being treated as errors
```
Relevant linux change:
https://github.com/torvalds/linux/commit/7d12e780e003f93433d49ce78cfedf4b4c52adc5

Should be able to remove the `, struct pt_regs* registers` from:
https://github.com/openwrt/packages/blob/e7e66545b17649368547b0e9d248a577fb4b4703/utils/gl-mifi-mcu/src/module.c#L57
And remove some of the excessive casts:
https://github.com/openwrt/packages/blob/e7e66545b17649368547b0e9d248a577fb4b4703/utils/gl-mifi-mcu/src/module.c#L63
https://github.com/openwrt/packages/blob/e7e66545b17649368547b0e9d248a577fb4b4703/utils/gl-mifi-mcu/src/module.c#L181

### PR DESCRIPTION
**Pull request by nunojpg**

### CODE REVIEW

**Comment by BKPepe** [comment]
Same question as  https://github.com/openwrt/packages/pull/12733#issuecomment-1463532936

**Comment by Ansuel** [comment]
@BKPepe yep on the WERROR change i found many packages that were really target specific that are present in feeds... with one device depending on a package on feeds... these should be moved to core IMHO and included/depends on one target...

**Comment by jefferyto** [comment]
@nunojpg not sure if you noticed but the source branch `gl-mifi-mcu` is on the main packages repo instead of your own fork

**Comment by oskarirauta** [comment]
coova also has similar problem, not compatible with 6.1

**Comment by john-tho** [comment]
I was able to compile this for a test mt7621 6.1 build with GCC13, so thanks for for fixes.

---


> Same question as [#12733 (comment)](https://github.com/openwrt/packages/pull/12733#issuecomment-1463532936)

> because I don't know better. What do you suggest? (https://github.com/openwrt/packages/pull/12733#issuecomment-1567232433)

For making this package more target-specific, you might be able to add a depends to the KernelPackage. Something like `DEPENDS := @TARGET_ath79`, example here: https://github.com/openwrt/packages/blob/fdf1f7a85ff71a7cabf79719437ff7e10bac21fe/utils/mv88e6xxx_dump/Makefile#L29

**Comment by nunojpg** [comment]
I'm tempted to just remove gl-mifi-mcu and gl-puli-mcu as they are both device specific. Also because I don't use this devices anymore and don't have both available in any case.

**Comment by BKPepe** [comment]
That works for me. Feel free to do it.

Dne út 20. 6. 2023 18:00 uživatel Nuno Goncalves ***@***.***>
napsal:

**Pull request merged**
