### PR TITLE
Add zzzz.io dynamic dns support

### PR DESCRIPTION
**Pull request by kopf**
Adds support for the [zzzz.io](https://zzzz.io) dynamic dns service

### CODE REVIEW

**Comment by chris5560** [comment]
@kopf 
Sign-off missing !!
I'll implement into next release of ddns-scripts.
Thanks Christian

**Comment by kopf** [comment]
hey @chris5560 , sorry about that - just read the `CONTRIBUTING.md` and learned about that. 

I've force-pushed a new commit, with a revised commit message where I sign off, and have also added a string specifying expected responses from the server. 

I hope this hasn't caused any hassle. Thanks.

**Comment by jbergstroem** [comment]
I've been using zzzz successfully as a custom script. Few notes:

1. Suggesting adding `?ip=[IP]` to qs. OpenWRT might want to send a different ip than the caller ip in a distant future
2. Afaik, `zzzz.io` is the only provider that requires https. Not sure how to treat this?

**Comment by chris5560** [comment]
There are more services like zoneedit.com, cloudflare.com, domains.google.com currently require SSL requests.
To implement a check into ddns-scripts / luci-app-ddns will require to build a new services "database" and some coding.
I already thought about an uci-compatible database but it's still a thought.
Currently an update of Wiki-pages should do the job.
Christian

**Comment by chris5560** [comment]
Service added in 2.6.0-1 (merged)
Wiki updated.
Could someone please close.
Thanks
Christian

**Comment by kopf** [comment]
Thanks.

**Pull request closed without merging**
