### PR TITLE
samba4: add nfs-kernel-server/host build dependency

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @Andy2244 
Compile tested: ramips, openwrt master
Run tested: none

Description:
Fixes a compilation error:
```
[ 140/1642] Generating nfs41acl-h
/bin/sh: rpcgen: command not found
[ 141/1642] Generating perfcount_empty_c
/bin/sh: rpcgen: command not found
```
I was compiling with default options.
Note that I did not increase PKG_RELEASE since there's no change to the compiled package.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by Andy2244** [comment]
Thanks looks good.

**Comment by karlp** [comment]
headline is a bit misleading, it' sjust the host portions, but yeah, ok :)

**Comment by cotequeiroz** [comment]
Fixed it ;-)

**Comment by diizzyy** [comment]
Is that really correct?
I've compiled it several times without nfs-support just fine

**Comment by Andy2244** [comment]
Seems distro specific google turned up this:
samba.spec
```
%if 0%{?fedora}
BuildRequires: rpcgen
BuildRequires: rpcsvc-proto-devel
%else
BuildRequires: rpcbind
%endif
```

Its just a simple host build tool, so i don't mind.

**Comment by cotequeiroz** [comment]
It uses `rpcgen` to generate some source files. See if you have `staging_dir/hostpkg/bin/rpcgen`.  This is installed by `nfs-kernel-server/host`.  The patch makes sure it gets installed before samba4 gets built.  I imagine you might have it in your system, but I can't confirm that it would be picked up by the samba build.

**Comment by diizzyy** [comment]
@cotequeiroz 
I see, I have it on the host system which probably explains why it works.

**Comment by Andy2244** [comment]
@diizzyy @yousong Can we merge this?

I feel bad every-time he has to comeback and rebase/merge this PR, since a new PR from me got merged beforehand.

**Comment by yousong** [comment]
Manually applied the patch https://github.com/openwrt/packages/commit/460dbee22683c3575e97489905bdcb10ef08d62c

Thank you.

**Pull request closed without merging**
