### PR TITLE
msmtpq-ng: update and remove deprecation

### PR DESCRIPTION
**Pull request by cshoredaniel**
Maintainer: @cshoredaniel / @neheb 

Compile tested: ath79, CR5000 + WNDR3800, brcm2708 Raspberry Pi B+, recent masters
Same for run tested; used with NUT to emit notifications, sent test mails, queued and dequeued mail.

### CODE REVIEW

**Comment by neheb** [comment]
Changes are fine with me.

**Comment by cshoredaniel** [comment]
NB: I need to retest with the latest update (msmtp-scripts has had an important release so I've updated; but not yet tested on OpenWrt).

**Comment by neheb** [comment]
@cshoredaniel is this still valid? if so, please rebase.

**Comment by cshoredaniel** [comment]
Not likely to be working on this for while, if ever:

A combination of factors has interfered with working on much of anything non-local for 2-3 months now and in any event I am considering dropping OpenWrt from my roster of 'Things To Do' even when the difficulties are resolved, as I need to consider where too allocate my limited time.

**Pull request closed without merging**
