### PR TITLE
seafile: upgrade to 6.3.0

### PR DESCRIPTION
**Pull request by cotequeiroz**
Update to the last version, which adds openssl 1.1.0 compatibility.

I see libsearpc version number used to differ from upstream, and matched the rest of the suite.  I changed that, as, in my opinion, it does not have to match their version, and it hasn't been updated as often.  There's a confusion upstream as well as the actual version number.  By looking at the commit history in libsearpc, there were some memory leaks fixed on Jul 28, 2016, so I picked a commit after that.  They haven't officially tagged it as 3.0.8, but I took the hint from `configure.ac` and called it 3.0.8.  Debian, among others, has done the same.  If that's a problem, I can always go back and restore the old pattern and make it 6.3.0 as well.

I've included a couple of patches to remove the need for deprecated APIs in openssl 1.1.0, which I have sent upstream.

Maintainer: @kissg1988 
Compile tested: brcm47xx/ramips openwrt master

### CODE REVIEW

**Comment by cotequeiroz** [comment]
Hello @kissg1988 

I will do some testing here and I'll post the results.  As for travis, it bailed out way before it got to any seafile stuff.  I'll try to do a force push to see if it tries again.
Cheers,
Eneas

**Comment by cotequeiroz** [comment]
Travis still fails before getting to seafile, although now it was in a different package.

**Comment by kissg1988** [comment]
Hi @cotequeiroz

Seafile has quite a few dependencies and there's a known issue of getting failed builds when there are multiple make jobs running (see my comments [here](https://github.com/kissg1988/seafile-openwrt#known-issues)). I could never find the reason why this happens, but it's likely some timing issue about packages depending on each other or some kind of a conflict between two packages that cannot be built at the same time for an unknown reason.

If the build completes successfully with "make -j1" then I believe the output of travis can be safely ignored.

Thanks,
Gergely

**Comment by cotequeiroz** [comment]
Hi @kissg1988 

I've run tested this in an Asus RT-N56U (ramips, 128MB RAM) running openwrt master.

The package was missing many python dependencies, which are not caught at compile-time. I followed the list in `seafile-seahub-6.3.0/requirements.txt`.  I've committed them all in this PR, as it would make more sense to add them all at the same time as this upgrade.  I've listed myself as their maintainer, but that's not really something I would like to do.  Can I assign any of the to you?

`python-memcached` is listed as a dependency since the previous version, was not included previously, and was not needed to run my tests, so I didn't add it either.  It would be easy to install it if you think it is necessary.

I had to correct a patch of mine, and add another one, already applied upstream because of an SQL statement not working with sqlite.  After adding all of the python dependencies, I got it to work.  Performance is not the best with the hardware I tested on, specially when using the web interface.  Python uses a lot of RAM.  I've tried the iOS app, and it was much better.

There is one issue, though.  When it first runs setup, it could not create a django superuser: 
```
You have installed Django's auth system, and don't have any superusers defined.
Would you like to create one now? (yes/no): yes
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 44, in handle
    call_command("createsuperuser", interactive=True, database=options['database'])
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/seafile/seafile-server/seahub/seahub/base/management/commands/createsuperuser.py", line 88, in handle
    User.objects.get(email=default_username)
  File "/usr/share/seafile/seafile-server/seahub/seahub/base/accounts.py", line 92, in get
    emailuser = ccnet_threaded_rpc.get_emailuser(email)
  File "/usr/lib/python2.7/site-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/lib/python2.7/site-packages/ccnet/rpc.py", line 71, in call_remote_func_sync
    client = self.pool.get_client()
  File "/usr/lib/python2.7/site-packages/ccnet/pool.py", line 29, in get_client
    client = self._create_client()
  File "/usr/lib/python2.7/site-packages/ccnet/pool.py", line 21, in _create_client
    client.connect_daemon()
  File "/usr/lib/python2.7/site-packages/ccnet/client.py", line 131, in connect_daemon
    return self.connect_daemon_with_pipe()
  File "/usr/lib/python2.7/site-packages/ccnet/client.py", line 113, in connect_daemon_with_pipe
    raise NetworkError("Can't connect to daemon")
ccnet.errors.NetworkError: Can't connect to daemon
Error: Seahub syncdb failed

*** ERROR: Configuration failed. Please fix the issues if any and re-run the script using the command below:
*** "/etc/init.d/seafile setup"
```
The script tries to connect to the ccnet daemon through a socket, but the daemon was not running, so it would not find the socket.  If I answer no, finish setup, start the service, run `/etc/init.d/seafile setup` again, then I can create the superuser just fine.
I hope this is OK for the upgrade.
Cheers,
Eneas

**Comment by kissg1988** [comment]
Hi @cotequeiroz ,

thanks a lot for taking your time run-testing the new version!

About the dependencies, I also used to catch a few missing python deps at runtime - that's one of the reasons why making run tests is important.

To be the honest, I'm very busy in my life these days and therefore I can't even keep packages I'm already a maintainer of up-to-date so please do not specify me as the maintainer. It's fine to just leave your name there, you will never be pushed by anyone to keep the packages up-to-date if you don't have the time or just don't feel like doing it. It's not uncommon to see some other good folks updating a package in case the maintainer is inactive for a long time, this is the spirit of open source software! :)

As per my experience, package maintainers receive reminders every Sunday from a bot (?) with the address "stdowa at gmail dot com" in case a new version of some software is available but it's really just a reminder without pushing intended, I suppose.

I believe `python-memcached` is an optional dependency so it should be fine to omit it from the list of dependencies. The user can install the package by hand in case it would be required for a particular use-case. Just make a note of this somewhere (in the post-installation script maybe?) to make sure users are aware of this information.

About the post-installation issue, I'm not sure why is it happening, maybe it would help to start ccnet first and only launch the setup script afterwards? Unfortunately, I can't remember what each component of Seafile expects to be available so please bear with me if this a dumb idea.

Cheers,
Gergely

**Comment by cotequeiroz** [comment]
I'm OK with being the maintainer of the newly created packages, so I'll leave them as they are.

I'm still puzzled by the post-installation script.

I have patched the setup file so it checks know whether ccnet was started, and starts it if not, finishes the setup, and stops it, so we don't leave it running by itself.

The error message is gone, but if you run it again, it will ask for the superuser again, so I'm not sure if the purpose is to create the superuser every time, or if creation failed even though the program says it was sucessful.  It apparently works independent of the django superuser creation, but I'm not familiar enough with django to know if the superuser matters in this case. Here's my output: 
```
 # /etc/init.d/seafile setup
-----------------------------------------------------------------
This script will guide you to config and setup your seafile server.
Make sure you have read seafile server manual at

        https://github.com/haiwen/seafile/wiki

Press [ENTER] to continue
-----------------------------------------------------------------


check python modules ...
checking sqlite3
checking chardet
checking six
checking pytz
checking rest_framework
checking compressor
checking statici18n
checking jsonfield
checking dateutil
checking constance
checking openpyxl
checking python imaging library(PIL)

It seems there already exists ccnet config files in /usr/share/seafile/ccnet, Do you want to use them?
[yes or no]  yes
Where do you want to put your seafile data?  (Please use a volume with enough free space)
[default /usr/share/seafile/seafile-data ]

It seems there already exists seafile data in /usr/share/seafile/seafile-data, Do you want to use them?
[yes or no]  yes
This is your configuration
------------------------------------------
ccnet config:        use existing config in /usr/share/seafile/ccnet
seafile:             use existing config in /usr/share/seafile/seafile-data
------------------------------------------
Press ENTER if the config is right, or anything else to re-config
```
Here's where the ccnet-server is started.
```
Now initializing seahub database, please wait...

Operations to perform:
  Synchronize unmigrated apps: help, webpack_loader, staticfiles, wopi, messages, thumbnail, statici18n, compressor, password_session, constance, gunicorn
  Apply all migrations: wiki, termsandconditions, trusted_ip, api2, share, captcha, registration, post_office, group, contacts, tags, contenttypes, profile, sessions, auth, invitations, notifications, base, revision_tag, database, two_factor, admin_log, institutions, avatar, role_permissions, options
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.

You have installed Django's auth system, and don't have any superusers defined.
Would you like to create one now? (yes/no): yes
E-mail address: cote2004-github@yahoo.com
Password:
Password (again):
Superuser created successfully.
done
```
It does say the superuser was created.
```
-----------------------------------------------------------------
-----------------------------------------------------------------
Your seafile server configuration has been finished successfully.
-----------------------------------------------------------------
-----------------------------------------------------------------

To start, stop or restart seafile:

         # /etc/init.d/seafile { start | stop | restart }

To start, stop or restart seahub:

         # /etc/init.d/seahub { start | stop | restart }

If you have any problem, refer to


 Seafile server manual:      https://github.com/haiwen/seafile/wiki

 Seafile discussion group:   https://groups.google.com/forum/?fromgroups#!forum/seafile

 Seafile website:            http://www.seafile.com

for more information.
```
I'll add the commit shortly.

**Pull request merged**
