### PR TITLE
[19.07]boost: reintroduce uClibc-ng patch

### PR DESCRIPTION
**Pull request by neheb**
It's all fixed upstream. Backported a combination of three patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @ClaymorePT

### CODE REVIEW

**Comment by neheb** [comment]
Simplified some more.

**Comment by ClaymorePT** [comment]
@neheb For this case, is it necessary to pump up the release version?

**Comment by neheb** [comment]
I'd say so. Look at the packages that are generated: http://downloads.openwrt.org/releases/packages-19.07/arc_arc700/packages/

Some boost libraries that are missing will arrive with this PR.

**Comment by ClaymorePT** [comment]
@neheb Okay then. Lets merge this!

**Pull request merged**
