### PR TITLE
libmicrohttpd: update source

### PR DESCRIPTION
**Pull request by dangowrt**
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by dangowrt** [comment]
@ryzhovau

**Comment by ryzhovau** [comment]
Pardon? 
What should I do?

**Comment by dangowrt** [comment]
Sorry, thought you were the package maintainer, but turns out I should have pointed this to @FriedZombie instead. Anyway, if you are using libmicrohttpd, please test if the new version works for your application.

**Comment by dangowrt** [comment]
@ryzhovau @FriedZombie any reason not to have this merged? If not, please merge it!
Afaik having libmicrohttpd use libopenssl is a license violation btw.
Plus newer source version is available and should be used.

**Comment by FriedZombie** [comment]
Sorry for the delay, I was a bit swamped with work and travelling lately. But now things hav calmed down a bit.
I will look over the merge request at the latest tomorrow.

**Comment by dangowrt** [comment]
Hi Martijn,

On Sun, Jun 07, 2015 at 06:12:23AM -0700, Martijn Zilverschoon wrote:
> Sorry for the delay, I was a bit swamped with work and travelling lately. But now things hav calmed down a bit.
> I will look over the merge request at the latest tomorrow.

First of all thanks for the quick reply to the email and sorry for
poking around. If it happends during the next couple of days, that's
totally fine -- my goal is to have working GNUnet builds in OpenWrt
which requires *very* recent libmicrohttpd...

btw: Are there any other packages making of libmicrohttpd/libmicrospdy?
btw2: May libmicrospdy (if actually being used anywhere) should become
      a package of its own?


Cheers


Daniel

**Comment by dangowrt** [comment]
ping @FriedZombie

**Comment by dangowrt** [comment]
ping @FriedZombie

**Comment by dangowrt** [comment]
@openwrt/owners can I merge this?

**Comment by lperkov** [comment]
@dangowrt I would say yes. Please run package/libmicrohttpd/refresh in order to refresh the patches.

**Comment by dangowrt** [comment]
I refreshed the patch as @jow- suggested.

**Pull request merged**
