### PR TITLE
[19.07] getdns: update to version 1.6.0

### PR DESCRIPTION
**Pull request by jonathanunderwood**
This update also:
    - enables parallel builds
    - moves to the CMake build system
    - removes the redundant InstallDev stanza

Signed-off-by: Jonathan G. Underwood <jonathan.underwood@gmail.com>

Maintainer: me
Compile tested: x86
Run tested: x86

Description: update to version 1.6.0

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
Raised this build failure upstream: https://github.com/getdnsapi/getdns/issues/481

**Comment by neheb** [comment]
Try backporting check.

**Comment by neheb** [comment]
I'm pretty sure there are also CMake variables to manually set the include dir.

**Comment by jonathanunderwood** [comment]
Turns out that adding an explicit build dependency on the `check` packages fixes this. I am slightly confused as to why that wasn't necessary on the master branch. But, anyway, should now be good to go.

**Comment by jonathanunderwood** [comment]
@neheb this one can be merged I believe.

**Pull request merged**
