### PR TITLE
nginx-util: move to pcre2

### PR DESCRIPTION
**Pull request by Ansuel**
Convert to pcre2 library as pcre is EOL. No functional change intended.

@peter-stadler Can you check this? Not strictly pcre2 usage but at least c++ format :D

### CODE REVIEW

**Comment by neheb** [comment]
Why does this use PCRE instead of std::regex?

**Comment by Ansuel** [comment]
Different syntax and from what I can read pcre2 is more stable and
robust/faster than the integrated one.

Il Dom 24 Set 2023, 03:40 Rosen Penev ***@***.***> ha scritto:

**Comment by neheb** [comment]
Doesn’t make much sense to use it over std::regex IMO

**Comment by peter-stadler** [comment]
Looks good, although I cannot test it right now. From my side we can merge it like thus, or switch to using std::regex only ...

I looked into switching to pcre2 a while ago, but was stuck at getting to run the tests again. And then I forgot about it, while there were (or are ongoing) efforts for using a new dynamic config for nginx (replacing nginx-util) ...

Thank you very much :-)

**Pull request merged**
