### PR TITLE
nginx: new package nchan, update to package nginx-lua

### PR DESCRIPTION
**Pull request by ljubomirb**
added new package nchan, allowing easy pub/sub with websockets
updated version of package nginx-lua (new versions of nginx do not work with older versions of lua)

Signed-off-by: Ljubomir Blanusa <ljubomir.blanusa@gmail.com>

### CODE REVIEW

**Comment by ljubomirb** [comment]
I've changed name, here at the top of this page.

**Comment by champtar** [comment]
Hi @ljubomirb 
your full name must be in the commit

**Comment by ljubomirb** [comment]
Is there a way to consider name non important?
Because the issue is: **does nchan work on your machine?** It compiles on mine, but it does not work (at least with WS client), nor it puts out any error. Client can only connect, and anything that is being sent later causes error with client. I'm not sure where the problem is. Is it some openwrt nginx patch that is no longer needed, is it nchan, or kernel issue? I'm using big endian ar71xxx.
It is important to note that nchan for sure works fantastic on Debian (when installed from repository to the little endian ARM machine).
As for lua update, it now does compile without a problem (as opposed to included makefile), but I did not test how it works (I'm not familiar with lua).
Other than that, please note that new versions of nginx are being released, so this makefile pull (with nginx version 1.12.0.) may already be old.

**Comment by champtar** [comment]
Hi @ljubomirb 
Having a proper signed-off-by is mandatory,
for the other issues i will let you see with @heil

**Comment by champtar** [comment]
Hi @ljubomirb 
you need to update this PR (it now has conflicts)
@heil please comment (are you interested by this new package + update?)

**Comment by heil** [comment]
sorry i just merged it otherwise. please have a look at the actual package

**Pull request closed without merging**
