### PR TITLE
utils/crun: assign PKG_CPE_ID

### PR DESCRIPTION
**Pull request by ffontaine**
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:crun_project:crun

Maintainer: @1715173329
Compile tested: Not needed
Run tested: Not needed

### CODE REVIEW

**Comment by BKPepe** [comment]
Why this was not done by treewide commit?

**Comment by 1715173329** [comment]
> Why this was not done by treewide commit?

Agree.

**Comment by ffontaine** [comment]
I can merge all those CPE assignments in a single and massive treewide commit. However, this will be more difficult for maintainers to check that I didn't made any mistake.

**Comment by BKPepe** [comment]
Since there is lack of maintainers or reviewers, then I am not sure if openning PRs for each packages was good approach. 🤷

**Pull request merged**
