### PR TITLE
Radsecproxy ucified

### PR DESCRIPTION
**Pull request by oskar456**
Maintainer: Toke Høiland-Jørgensen / @tohojo 
Compile tested: ar71xx, TL-WDR-4300, OpenWRT 15.05 Chaos Calmer
Run tested: ar71xx, TL-WDR-4300, OpenWRT 15.05 Chaos Calmer

Description:
This pull request UCIfies configuration of `radsecproxy`. In default config file, there is just an include of the legacy config file `/etc/radsecproxy.conf`, so migration should be painless.

### CODE REVIEW

**Comment by tohojo** [comment]
From eyeballing it, this looks good, thank you! One thing, though: The default loads radsecproxy.conf, but it is no longer installed, so a new install of the package will be broken. And there is no switch to disable the daemon until it has been configured.

Also, what happens when the package is upgraded and the new version doesn't consider '/etc/radsecproxy.conf' a config file? Will it be removed (wiping out user config)?

**Comment by oskar456** [comment]
Thanks for comments. I think it does not do a big harm if the config is broken on new installation. `procd` will take care of processes respawning too fast quite well. Even with previous sample config file installed, it was unusable in its default configuration.

We could, however, add a global disable switch, to make `radsecproxy` not start by default. But I'm not sure it's really necessary.

For the upgrade case, the `/etc/radsecproxy.conf` will be kept because is was marked as config file in the old version of package, which is uninstalled during upgrade. I actually upgraded `radsecproxy` on my router during testing and it worked as expected.

**Comment by oskar456** [comment]
I've added reload hook to the init file. I will eventually squash the commits once approved.

**Comment by tohojo** [comment]
Cool, I'll go try it out :)

**Comment by hojuruku** [comment]
Ever thought about having the fun of making a procd init script that does UCI validation instead?
Then if someone comes along and wants to make a luci plugin for this app, things are nicer.

There's a bug on my TODO list in this one regarding pppoe interfaces - it's returning the Ethernet device instead, but once that gets fixed this will be a good example.

https://github.com/openwrt/packages/pull/2941

**Comment by tohojo** [comment]
Right, built and tested this. Can merge as-is, or if you want to squash the commits that is fine too.

Having the validation stuff would be nice, but will not condition merging this on it :)

**Comment by oskar456** [comment]
I squashed into two commits - UCIfied config and copyright stuff.
I'll keep validation in mind, though I don't find it very important here since most options would validate as a `string` only.

**Pull request merged**
