### PR TITLE
glib2: update version to 2.70.4

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @neheb 
Compile tested: x86_64 (APU3), lantiq_xrx200
Run tested: x86_64 (APU3), lantiq_xrx200, modemmanger uses glib2

Description:
While we're at it, and the next release is coming up, let's go with the latest stable version of branch 2.7.x.

### CODE REVIEW

**Comment by neheb** [comment]
make package/glib2/{clean,refresh}

**Comment by feckert** [comment]
Thanks for the hint. I didn't even look to see if the CI has passed.

**Comment by hnyman** [comment]
Will you also cherry-pick it for the new 22.03 branch?

**Comment by feckert** [comment]
@hnyman done https://github.com/openwrt/packages/commit/68a8c2d8dd835ff2723821a3eeccd74c64939a9a

**Comment by hnyman** [comment]
Not really sure if the failure is due to this glib2 update or not, but currently libsoup fails in master and 22.03 due to something related to (lib)pcre, and neither libsoup or pcre has changed recently.   
But the libsoup build uses glib2 host tools, so quite possibly related to this glib2 bump.

e.g.
https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/libsoup/compile.txt
https://downloads.openwrt.org/releases/faillogs-22.03/mipsel_24kc/packages/libsoup/compile.txt

```
Found ninja-1.10.2 at /builder/shared-workdir/build/sdk/staging_dir/host/bin/ninja
ninja: Entering directory `/builder/shared-workdir/build/sdk/build_dir/target-mipsel_24kc_musl/libsoup-2.74.2/openwrt-build'
[1/159] Generating libsoup/soup-resources_c with a custom command
FAILED: libsoup/soup-resources.c 
/builder/shared-workdir/build/sdk/staging_dir/hostpkg/bin/glib-compile-resources ../libsoup/soup.gresource.xml --sourcedir ../libsoup/. --sourcedir ../libsoup --c-name soup --internal --generate --target libsoup/soup-resources.c --dependency-file libsoup/soup-resources.c.d
/builder/shared-workdir/build/sdk/staging_dir/hostpkg/bin/glib-compile-resources: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:79: /builder/shared-workdir/build/sdk/build_dir/target-mipsel_24kc_musl/libsoup-2.74.2/.built] Error 1
```

**Comment by neheb** [comment]
https://github.com/openwrt/openwrt/pull/9509 fixes it. Please verify.

**Pull request merged**
