### PR TITLE
Add node host dependency to node-* packages

### LINKED ISSUE #2440: node-cyclon fails to build if npm is not installed on the host
Hi,

I have this build failure for node-cyclon (gpio support select as a module), it fails to find npm:

```
touch /home/zoobab/soft/openwrt/staging_dir/target-mips_34kc_musl-1.1.12/root-ar71xx/stamp/.node_installed
make[3]: Leaving directory '/home/zoobab/soft/openwrt/feeds/packages/lang/node'
make[3]: Entering directory '/home/zoobab/soft/openwrt/feeds/packages/lang/node-serialport'
make[3]: Leaving directory '/home/zoobab/soft/openwrt/feeds/packages/lang/node-serialport'
make[3]: Entering directory '/home/zoobab/soft/openwrt/feeds/packages/lang/node-arduino-firmata'
make[3]: Leaving directory '/home/zoobab/soft/openwrt/feeds/packages/lang/node-arduino-firmata'
make[3]: Entering directory '/home/zoobab/soft/openwrt/feeds/packages/lang/node-cylon'
AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/zoobab/soft/openwrt/build_dir/target-mips_34kc_musl-1.1.12/node-cylon-0.22.0:node-cylon-0.22.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CROSS="mips-openwrt-linux-musl-" ARCH="mips" npm_config_arch="mips" npm_config_nodedir=/home/zoobab/soft/openwrt/build_dir/target-mips_34kc_musl-1.1.12/node-v0.12.7/ PREFIX="/home/zoobab/soft/openwrt/build_dir/target-mips_34kc_musl-1.1.12/node-cylon-0.22.0/ipkg-install/usr/" /home/zoobab/soft/openwrt/staging_dir/target-mips_34kc_musl-1.1.12/host/bin/npm install -g /home/zoobab/soft/openwrt/build_dir/target-mips_34kc_musl-1.1.12/node-cylon-0.22.0
bash: /home/zoobab/soft/openwrt/staging_dir/target-mips_34kc_musl-1.1.12/host/bin/npm: No such file or directory
Makefile:94: recipe for target '/home/zoobab/soft/openwrt/build_dir/target-mips_34kc_musl-1.1.12/node-cylon-0.22.0/.built' failed
make[3]: *** [/home/zoobab/soft/openwrt/build_dir/target-mips_34kc_musl-1.1.12/node-cylon-0.22.0/.built] Error 127
```

Does it needs a host dependency towards npm?

### PR DESCRIPTION
**Pull request by stintel**
Fixes #2440.

### CODE REVIEW

**Comment by nxhack** [comment]
LGTM (ar71xx)

**Comment by blogic** [comment]
Thanks !

**Comment by hnyman** [comment]
Looks like node now fails a bit differently:
At least on some buildhosts is fails due to "npm" installer(?) wanting to use ``` mkdir '/root/.npm/serialport/1.4.6/package' ```

Looks like node's installer is not happy just writing into the build_dir and staging_dir

Examples:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx.nand/node-serialport/compile.txt
```
/home/buildbot/slave/ar71xx.nand/build/staging_dir/target-mips_34kc_musl-1.1.14/host/bin/npm install -g /home/buildbot/slave/ar71xx.nand/build/build_dir/target-mips_34kc_musl-1.1.14/node-serialport-1.4.6
npm ERR! addLocal Could not install /home/buildbot/slave/ar71xx.nand/build/build_dir/target-mips_34kc_musl-1.1.14/node-serialport-1.4.6
npm ERR! Linux 4.1.15
npm ERR! argv "/home/buildbot/slave/ar71xx.nand/build/staging_dir/target-mips_34kc_musl-1.1.14/host/bin/node" "/home/buildbot/slave/ar71xx.nand/build/staging_dir/target-mips_34kc_musl-1.1.14/host/bin/npm" "install" "-g" "/home/buildbot/slave/ar71xx.nand/build/build_dir/target-mips_34kc_musl-1.1.14/node-serialport-1.4.6"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /root/.npm/serialport/1.4.6/package
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/root/.npm/serialport/1.4.6/package'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/root/.npm/serialport/1.4.6/package']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/root/.npm/serialport/1.4.6/package' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

This seems to be buildslave-dependent, as e.g. buildslave2 has built ar71xx ok, while faraday has failed to build ar71xx.nand. Codebase for those two platforms should be the same, so there is no good reason to see different results. Apparently different buildslaves give varying directory permissions to the build job. Of course, the installation programs running inside the buildbot make process should not require access to the buildhost root. "npm" is behaving badly :-(

**Comment by nxhack** [comment]
oh... bad technique...

```
        PREFIX="$(PKG_INSTALL_DIR)/usr/" \
+       $(STAGING_DIR)/host/bin/npm config set cache $(STAGING_DIR)/npm-cache && \
        $(STAGING_DIR)/host/bin/npm install -g $(PKG_BUILD_DIR)
```

**Comment by nxhack** [comment]
```
        $(MAKE_FLAGS) \
        npm_config_arch=$(CONFIG_ARCH) \
        npm_config_nodedir=$(BUILD_DIR)/node-v$(PKG_NODE_VERSION)/ \
+       npm_config_cache=$(BUILD_DIR)/node-v$(PKG_NODE_VERSION)/npm-cache \
        PREFIX="$(PKG_INSTALL_DIR)/usr/" \
        $(STAGING_DIR)/host/bin/npm install -g $(PKG_BUILD_DIR)
```

**Comment by rmanders** [comment]
Can this also be added to the "for-15.05" branch?

**Pull request merged**
