### PR TITLE
unbound: drop odhcpd leases with wrong field count

### PR DESCRIPTION
**Pull request by EricLuehrsen**
Maintainer: me
Tested: TL-Archer-C7v2 OpenWrt master
Description: Corrects for issue with odhcpd permissiveness with host name #6769

### CODE REVIEW

**Comment by danielg4** [comment]
Nice, but this addresses only the issue of spaces in the hostname, not other invalid chars. My patch can still apply on top of this, but then there would be no accounting for NF == 8, which I haven't even seen.

**Comment by danielg4** [comment]
Also, you didn't bump the package version.

**Comment by EricLuehrsen** [comment]
DHPCv4 leases should have exactly 9 fields. DHCPv6 should have 9 (GA) or 10 (GA+ULA) fields. Anything more or less is going to cause trouble. Specific issues with odhcpd in the past have created specific (and clumsy) fixes.

**Comment by danielg4** [comment]
Agreed, but hostnames must ~ /^[[:alpha:]]([-[:alnum:]]*[[:alnum:]])?$/ to be valid, too.

**Comment by danielg4** [comment]
Revised RE: ```/^[[:alnum:]]([-[:alnum:]]*[[:alnum:]])?$/```

**Comment by EricLuehrsen** [comment]
Well you can't argue with "if dnsmasq does it that way."  :smile: That is less effort anyway.

**Comment by danielg4** [comment]
I have not confirmed it, though.

**Comment by EricLuehrsen** [comment]
Fixed now I think.

**Pull request merged**
