### PR TITLE
lighttpd: Build missing plugin mod_openssl

### PR DESCRIPTION
**Pull request by bluewavenet**
lighttpd: Build missing plugin mod_openssl

mod_openssl is missing from the package leading to the error:
lighttpd needs mod_openssl.so
in /usr/lib/lighttpd

Author-name: Rob White
Maintainer: W. Michael Petullo <mike@flyn.org>
Signed-off-by: Rob White <rob@blue-wave.net>

### CODE REVIEW

**Comment by MikePetullo** [comment]
Thank you for contributing this. Some questions:

Issue #6012 refers to the 17.01.4 release, yet this merge request is against master. Is this intentional?

Master includes the following from @pprindeville. Should you cherry-pick this into lede-17.01 instead of adding your change?

commit e13fbbad62b4287070cbab52329680d230167535
Author: Philip Prindeville <philipp@redfish-solutions.com>
Date:   Tue Jan 2 17:08:59 2018 -0700

    lighttpd: CONFIG_LIGHTTPD_SSL includes mod_openssl
    
    If we're built with CONFIG_LIGHTTPD_SSL then mod_openssl.so should
    be included into the base package. Fixes issue #5343.
    
    Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

**Comment by bluewavenet** [comment]
@MikePetullo 
Yes the reference to 17.01.4 is intentional, but perhaps a bit misleading.
See issue  #6012 
Commit e13fbba does not actually fix #5343 as the mod_openssl ipk does not get built.

**Comment by bluewavenet** [comment]
To clarify matters:
**lighttpd version 1.4.48-2 in snapshots cannot be used with ssl as the module mod_openssl does not get built.** This PR fixes this.

**Comment by bluewavenet** [comment]
@MikePetullo 
With 1.4.48-2, I get the error:
"lighttpd needs mod_openssl.so
in /usr/lib/lighttpd"
and it does not serve https.

**Comment by MikePetullo** [comment]
@bluewavenet, the latest OpenWrt build log, available at https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/lighttpd/compile.txt, says:

[...]
checking custom lib directory for kerberos5... no
checking for gss_acquire_cred in -lgssapi_krb5... no
configure: error: gssapi_krb5 libs were not found, install them or build without --with-krb5
Makefile:196: recipe for target '/data/bowl-builder/x86_64/build/sdk/build_dir/target-x86_64_musl/lighttpd-1.4.48/.configured_46257b85f028ace8755abea30775cbeb' failed
make[3]: *** [/data/bowl-builder/x86_64/build/sdk/build_dir/target-x86_64_musl/lighttpd-1.4.48/.configured_46257b85f028ace8755abea30775cbeb] Error 1
Command exited with non-zero status 2
time: package/feeds/packages/lighttpd/compile#16.35#1.56#28.41

Are you building this package yourself, or are you downloading the binaries from downloads.openwrt.org? I am doing the former, and SSL/TLS seems to work for me.

**Comment by bluewavenet** [comment]
Downloading from snapshots on the days that the build is successful. The build system for packages in snapshot seems to be in a state of flux at the moment.

**Comment by MikePetullo** [comment]
Well, building the lighttpd packages comes with a "SSL support" option. That option is selected by default. I am a little surprised that the OpenWrt-built package does not come out the same as mine. Can you provide me a copy of the binary lighttpd packages you have? I would be interested in looking at them.

**Comment by bluewavenet** [comment]
@MikePetullo 
I did not keep the ipk I downloaded from snapshot and it is currently failing to build in there so cannot re-try.
When I did have it installed, I can confirm that mod_openssl.so was not present (same result as with 1.4.48-1).
This PR was intended to provide the mod_openssl ipk for separate installation.
As you are building yourself, the lede package build is failing and Travis is giving errors on this PR, the whole issue may be due to the LEDE package build in snapshots being somewhat in a state of flux at the moment.
Waiting for stability there and then retesting is probably all we can do at the moment.
ps. I am imagebuilding on mips_24kc
pps Thanks for your continued efforts - much appreciated. :-)

**Comment by MikePetullo** [comment]
See #6012: The package at https://downloads.openwrt.org/releases/17.01.4/packages/x86_64/packages/ includes mod_openssl.so as of Mon May 21 10:18:12 2018 after merging only #6077. I suspect master will work fine once it builds again. As I said earlier, my manual build of master builds mod_openssl.so.

**Comment by bluewavenet** [comment]
@MikePetullo 
Yes indeed, fine when it builds and fine in release packages :-)

**Pull request closed without merging**
