### PR TITLE
gptfdisk: Add uclibc++ support

### PR DESCRIPTION
**Pull request by neheb**
Added a patch that adds a missing header.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @alive4ever 
Compile tested: ramips

NOTE: Relies on https://patchwork.ozlabs.org/patch/1019491/

### CODE REVIEW

**Comment by alive4ever** [comment]
I am unable to compile this pull request, with error: 
```
g++-uc: Command not found
```

**Comment by neheb** [comment]
You’re missing the uclibcxx package for some reason. Using the SDK?

**Comment by alive4ever** [comment]
Looking good so far. Got it to compile for x86_64 using OpenWrt SDK.
```
root@OpenWrt:~# opkg info cgdisk
Package: cgdisk
Version: 1.0.4-2
Depends: libc, uclibcxx, libuuid, libncursesw
Status: install user installed
Architecture: x86_64
Installed-Time: 1546295621
root@OpenWrt:~# ldd $(which cgdisk)
        /lib/ld-musl-x86_64.so.1 (0x7f75c2030000)
        libuuid.so.1 => /usr/lib/libuuid.so.1 (0x7f75c2027000)
        libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x7f75c1fd7000)
        libuClibc++.so.0 => /usr/lib/libuClibc++.so.0 (0x7f75c1fa3000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7f75c2030000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f75c1f8f000)
```

**Comment by cshoredaniel** [comment]
+run tested

**Comment by neheb** [comment]
Closing for now. Initial results were negative. I managed to partition a drive but the input did not work correctly.

**Comment by cshoredaniel** [comment]
Thank you for testing.

**Pull request closed without merging**
