### PR TITLE
pulseaudio: add lto and gc-sections to reduce size

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tripolar 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
Added patch fixing compilation with ARM platforms that lack neon.

I am not sure this is correct since I assume it would also be ran with arm64 stuff (NEON is implicit there). ping @micmac1

**Comment by neheb** [comment]
Actually...ARM64 stuff should show up as AArch64 and not hit this.

**Comment by micmac1** [comment]
Maybe just remove the simd.check neon line when neon is not available. The outcome should be the same like in the pre-meson build, where neon was force-disabled when not available.

Then you wouldn't have to keep track of patches in different directories.

```
--- a/sound/pulseaudio/Makefile
+++ b/sound/pulseaudio/Makefile
@@ -144,6 +144,13 @@ endif

 TARGET_LDFLAGS += -liconv

+define Build/Prepare
+       $(call Build/Prepare/Default)
+ifeq ($(findstring neon,$(CONFIG_TARGET_OPTIMIZATION)),)
+       $(SED) '/remap_neon\.c/d' $(PKG_BUILD_DIR)/src/pulsecore/meson.build
+endif
+endef
+
 define Build/InstallDev
        $(INSTALL_DIR) \
                $(1)/usr/lib/pkgconfig \
```

**Comment by micmac1** [comment]
I have that a quick whirl on mxs and it fixed the compile.

**Comment by micmac1** [comment]
> I have that a quick whirl on mxs and it fixed the compile.

*gave*

**Comment by micmac1** [comment]
> Actually...ARM64 stuff should show up as aarch64 and not hit this.

OK, in that case it makes sense to add an ifneq that checks CONFIG_ARCH for arm.

**Comment by neheb** [comment]
Tested. Works just fine. Your solution is much simpler.

**Pull request merged**
