### PR TITLE
python: update interpreter to 2.7.14 & update some packages

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @jefferyto 
Compile tested: https://github.com/lede-project/source/commit/e37c7636eed55a20ec3ef64602505599d5cc4030  x86_64
Run tested: https://github.com/lede-project/source/commit/e37c7636eed55a20ec3ef64602505599d5cc4030 x86_64

Description:

Python 2.7.14 came out.
I also took the opportunity to update some other packages that have newer versions released.
Since they come out at various intervals, make sense to sync them to a batch update.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Any idea if the Travis error is valid?
```
  File "/tmp/tmpREiVrI/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
make[3]: *** [install] Error 1
make[3]: Leaving directory `/tmp/tmp.5CF6AwII3n/build_dir/hostpkg/Python-2.7.14'
make[2]: *** [/tmp/tmp.5CF6AwII3n/staging_dir/hostpkg/stamp/.python_installed] Error 2
```
Looks like the urllib3 error that has been around for some time.

**Comment by commodo** [comment]
Will take a look.

**Comment by commodo** [comment]
@hnyman 
the SDK performs very much differently than just cloning the repo locally and building it from scratch

i guess, i have a new challenge to make this work on the SDK
is there a script/guide for setting up ?

i seem to have issues with missing `g++`, fortify header collisions, and all sort of other "fun" stuff

admittedly, i didn't try much the SDK before
i guess i'll try it from now on

**Comment by hnyman** [comment]
> the SDK performs very much differently than just cloning the repo locally and building it from scratch
> 
> i guess, i have a new challenge to make this work on the SDK
> is there a script/guide for setting up ?

Sorry, I have never used it myself.

Maybe @jow- or some other admins / devs , who have configured the buildbot know more about it

**Comment by commodo** [comment]
I think one fix that looks needed is to include  uclibc++.mk  stuff in the SDK

**Comment by commodo** [comment]
@hnyman 
was my fault ;
usually i do in the LEDE source folder
```
./scripts/feeds update packages ; ./scripts/feeds install -a
```

but in the case of the SDK, the base packages are not available
so
```
./scripts/feeds update -a ; ./scripts/feeds install -a
```
fixed it

then Python built fine [ from this branch ]

**Pull request merged**
