### PR TITLE
softethervpn5: Fix compilation without ENGINE support

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @Andy2244 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
Can't figure this one out. Patch is failing as the .c file has CRLF line endings. Running git diff with unix2dos or dos2unix afterwards doesn't seem to work.

**Comment by neheb** [comment]
On the bright side, the fix was merged upstream. So the next released version should fix this.

**Comment by Andy2244** [comment]
Yeah you need to keep mixed line endings, they never recreated the source to LF.

**Comment by neheb** [comment]
Right. But unix2dos gives the same failure.

**Comment by diizzyy** [comment]
Just wait for a new release by upstream

**Comment by Andy2244** [comment]
> 
> 
> Right. But unix2dos gives the same failure.

Yeah as noted, you cant use unix2dos. Check my .patch files, they have both LF and CRLF endings. You need to preserve the CRLF endings for the actual diff, code part and LF endings for the meta diff stuff.

**Comment by Andy2244** [comment]
yeah lets just wait for the new release, the upstream committed changes also look different than this patch?

**Pull request closed without merging**
