### PR TITLE
utils/jfsutils: add package

### PR DESCRIPTION
**Pull request by infabo**
This patch adds journaled file system (JFS) utilities support.

Signed-off-by: Ingo Fabbri <der_ulmen@yahoo.de>

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
If you post the package here you should add someone (usually yourself) as maintainer. 
The maintainer will be responsible of updating, checking contributions and answering to issues opened about his packages (other maintainers with commit access will actually merge the PRs).

Packages whose maintainer disappears for too long are dropped and moved to this repo https://github.com/openwrt/packages-abandoned (a graveyard of sorts, the packages there aren't built by default but their code is preserved for anyone to adopt them again).

So if you want to go ahead, please add PKG_MAINTAINER:=Ingo Fabbri <der_ulmen@yahoo.de>

to the makefile.

See this (random package) makefile for an example https://github.com/tru7/packages/blob/master/net/knxd/Makefile

**Comment by infabo** [comment]
@ bobafetthotmail I added myself as package maintainer.

**Comment by bobafetthotmail** [comment]
Please squash the commits into one.

In this patch's branch in your local github write 
**git reset HEAD~2** to delete the last two commits, but leaving modified files intact, 
**git add -i** and use its interface to select the modified/added file, 
**git commit** and you write the commit message as normal
**git push -f** to send the change on Github and in this PR.

Then you have to wait for someone that has commit access to show up and merge the PR, which should happen in weeks usually.

**Comment by infabo** [comment]
Done!

**Comment by hnyman** [comment]
I tried to compile it with the current LEDE r3383-0bf85ef048, but failed:
```
arm-openwrt-linux-muslgnueabi-gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../libfs  -I/Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include -I/Openwrt/r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/include -I/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl_eabi/usr/include -I/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl_eabi/include/fortify -I/Openwrt/r7800/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl_eabi/include   -Os -pipe -mcpu=cortex-a15 -mfpu=neon-vfpv4 -g3 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -iremap/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/jfsutils-1.1.15:jfsutils-1.1.15 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -MT ui.o -MD -MP -MF .deps/ui.Tpo -c -o ui.o ui.c
mv -f .deps/ui.Tpo .deps/ui.Po
make[5]: *** No rule to make target '../libfs/libfs.a', needed by 'jfs_debugfs'.  Stop.
make[5]: Leaving directory '/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/jfsutils-1.1.15/xpeek'
make[5]: Entering directory '/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/jfsutils-1.1.15'
make[5]: Leaving directory '/Openwrt/r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/jfsutils-1.1.15'
Makefile:260: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
```

**Comment by diizzyy** [comment]
Why is this needed at all? Is it just for the sake of availability?

**Comment by hnyman** [comment]
> Why is this needed at all? Is it just for the sake of availability?

Well, the kernel support for jfs is already there, so having the userspace tools makes sense. Filesystems are more "core" to Openwrt/LEDE than many other additions here. And based on discussion in https://github.com/lede-project/source/pull/716 the packages repo is the logical place.

But it needs to compile cleanly.

@infabo 
for which platforms you have compiled & run-tested this?

**Comment by diizzyy** [comment]
@hnyman 
I really think it's for the sake of completeness in LEDE. I don't really like the idea of adding ~6y old code that most likely has no upstream support at all and I doubt once someone seriously needed to use JFS but oh well...

**Comment by infabo** [comment]
@hnyman tested it only on openwrt chaos calmer 15.04.1. but will have a look why it is not compiling on lede trunk

@diizzyy

it's just a tiny package. calm down.

**Comment by hnyman** [comment]
> but will have a look why it is not compiling on lede trunk

You should preferably test it both with LEDE master and Openwrt master.
(No new features will be added to CC15.05 packages)

**Comment by infabo** [comment]
This makes me sick, always the same discussion. but onther question, why is there vfat support at all? a ms filesystem has no, nothing, nix, null, minus what ever batman no need for existance in any linux system in any way i can image. but wait....the support is there. wow. maybe the "nosayers" had nothing to say at that point. so either remove the kmod-jfs from lede CORE or....no, no OR. just remove the fucking jfs kernel module from the project completely. wipe it. woop it saves a bunch of 25kb and youre apparently happy. go ahead. i am out of - before i was even in.

**Comment by diizzyy** [comment]
To answer your question, several ARM and/or MIPS64 platforums uses FAT/VFAT (bootloader, kernel etc) not to mention the majority of users who hook up their USB-sticks and whatnot and want cross platform support (exFAT is to be recommended in general now days however). Why I'm hesitant to add "exotic" packages is that maintainers have a tendency to disappear and that even occurs to frequently used packages. Having packages that rarely if ever/getting used just adds more the to broken packages list for someone (if any) to pick up...

**Comment by bobafetthotmail** [comment]
@diizzyy I agree on your concerns (this place has always been a bit too much Far West-y, but since the whole OpenWRT was too it was kinda ok) but I think that the solution to the noted issue "_maintainers have a tendency to disappear and that even occurs to frequently used packages_" is to set up some kind of simple rules and enforce them, like "_if the maintainer does not answer within a month the package is dropped_" and "_maintainers that have a habit of disappearing or neglecting their packages are not allowed to add new packages (for ever, or until they fix up their other packages)_", not by restricting entry to only those packages that you/someone think may be useful, as this does not guarantee that the maintainer won't disappear.
I think restricting access arbitrarily is only going to piss off people.

**Comment by thess** [comment]
@infabo - Get this to build on the LEDE trunk with the current jfs, etc. and... 
Fix up the copyright by either removing it or adding your own and we should be good to go.

**Comment by champtar** [comment]
Hi @infabo,
Closing this for now, don't hesitate to reopen this when it ir compiling/working on latest LEDE trunk

**Pull request closed without merging**
