### PR TITLE
fio: Add to repo

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer:
Compile tested: ramips, D-Link DIR-860L, OpenWrt trunk
Run tested: ramips, D-Link DIR-860L, OpenWrt trunk

Description:
Add fio to repo

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Something I had in my local repo that someone might want to pick up.

**Comment by drastx** [comment]
@diizzyy, thanks. This is my gitgub userid

**Comment by drastx** [comment]
@diizzyy, thanks for the info I can check into it

**Comment by drastx** [comment]
Hey @diizzyy, I tried with your patch but for some reason fio doesn't even show up in menuconfig under Utils/Disk/

It does show up in the package index, and everything looks correct. Did this work for you?

**Comment by diizzyy** [comment]
Works fine

Apply patch and then
```
./scripts/feeds update -i
./scripts/feeds install -a
```

**Comment by drastx** [comment]
It doesn't work for me, I tried both:
./scripts/feeds update -a
./scripts/feeds install -a

./scripts/feeds update -i
./scripts/feeds install -a

I'll have to do a bit more digging

**Comment by diizzyy** [comment]
```
git clone https://github.com/openwrt/openwrt
cd openwrt 
./scripts/feeds update -a
./scripts/feeds install -a
cd feeds/packages
wget https://github.com/openwrt/packages/pull/5396.patch
git am 5396.patch
rm 5396.patch 
cd ../..
./scripts/feeds update -i
./scripts/feeds install -a
make menuconfig
```
Something alone those lines works just fine.

**Comment by drastx** [comment]
Yeah, it's gotta be something wrong with my main development repo. It doesn't work on my existing repo. If I start clean then it works. Thanks for confirmation

**Comment by diizzyy** [comment]
@hnyman 
Merge?

**Pull request merged**
