### PR TITLE
treewide: build CMake projects with Ninja

### PR DESCRIPTION
**Pull request by neheb**
faster to compile.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by champtar** [comment]
@neheb numbers ?
Also do we depend on host Ninja version ? if yes this might cause issues depending on the distro

**Comment by neheb** [comment]
Ninja already has a host package here. That will not be an issue.

I'll get numbers at a later date. This is a draft after all :).

**Comment by champtar** [comment]
Perfect, waiting for the numbers then :)

**Comment by neheb** [comment]
It's a little unfair honestly. Some of these packages did not have PKG_BUILD_PARALLEL set. Others that had PKG_BUILD_PARALLEL set to 0 end up compiling because...Ninja.

**Comment by champtar** [comment]
Please read it as "excited to see some faster compile time soon", with Ninja host build I'm 100% for this PR, I'm just curious at how much we can gain by switching to Ninja

**Comment by neheb** [comment]
@stangri I added a workaround for a CMake bug with Ninja. Please review.

**Comment by stangri** [comment]
@neheb -- Thanks! Would it be possible to backport the relevant ninja updates to 19.07 so that the Makefile for https-dns-proxy can stay the same for 19.07 and newer (21.02/snapshot) builds?

**Comment by neheb** [comment]
Done.

**Comment by neheb** [comment]
Was able to compile all locally.

**Comment by neheb** [comment]
With https://github.com/openwrt/packages/pull/15070 this will be ready. Just need to get the numbers.

**Comment by neheb** [comment]
```
A small selection of packages was tested going from:

Executed in  696.30 secs   fish           external
   usr time   82.98 mins  395.00 micros   82.98 mins
   sys time    9.02 mins    0.00 micros    9.02 mins

to:

Executed in  592.20 secs   fish           external
   usr time   84.84 mins  361.00 micros   84.84 mins
   sys time    8.85 mins   57.00 micros    8.85 mins

Tested by running make -j 12 and wiping staging/build_dir/target_x
```

The full suite would show a bigger speedup I think. ping @champtar

**Comment by karlp** [comment]
Can we not just pull this inside the "$(INCLUDE cmake)" bit? is there ever going to be a reason to want this disabled?  if we do, could it just be controlled by the existing PKG_PARALLEL?

**Comment by neheb** [comment]
The issue is that ninja is not in base. They also do not want it for "bloat" reasons. It'll be done eventually when meson becomes a requirement for base.

**Comment by karlp** [comment]
so if it's not in base, what pulls in ninja host build at all then?  It would seem that making all the packages simply "require" ninja like this would be doing an end run around the "don't want ninja in base" requirement and forcing their hand?

**Comment by neheb** [comment]
> so if it's not in base, what pulls in ninja host build at all then? It would seem that making all the packages simply "require" ninja like this would be doing an end run around the "don't want ninja in base" requirement and forcing their hand?

ninja-cmake includes ninja.mk which has

https://github.com/openwrt/packages/blob/master/devel/ninja/ninja.mk#L9

Ninja is just a build system. There's no requirement at all. CMake can work with GNU Make although slower.

Their hand will be forced when util-linux switches to meson which requires ninja.

**Comment by aparcar** [comment]
So `openobex` seem to fail? Can't you just remove the change for now on that specific package?

**Comment by aparcar** [comment]
Well the individual package seem to require individual fixes.

**Comment by aparcar** [comment]
How about you split this PR into single PRs which can then be approved individually by both maintainers and CI?

**Comment by neheb** [comment]
Too many honestly. This PR is just a compilation change. There's no change in compiled output.
There are around 110 packages right now. I'll rebase and push when there are around 80.

**Comment by neheb** [comment]
@micmac1 since you've dealt with mariadb, any idea why it's not working properly? It seems plugins are not being disabled.

**Comment by micmac1** [comment]
> @micmac1 since you've dealt with mariadb, any idea why it's not working properly? It seems plugins are not being disabled.

Hello Rosen,

The host compile of mariadb fails. Without the host compile the cross-compile will fail.

The host compile wants to build the special target "import_executables". Hence there is this in the mariadb Makefile:

```
define Host/Compile
        $(call Host/Compile/Default,import_executables)
endef
```

But ninja-cmake.mk seems to not set up the defines properly. The result is that it kicks off the host compile of mariadb like this:

`/openwrt/staging_dir/hostpkg/bin/ninja  -C /home/sk/tmp/openwrt/build_dir/hostpkg/mariadb-10.4.18/`

It should be something like this:

`/openwrt/staging_dir/hostpkg/bin/ninja  -C /home/sk/tmp/openwrt/build_dir/hostpkg/mariadb-10.4.18/ import_executables`

The below seems to make it work, although I suspect that may not be the best solution:

```
diff --git a/devel/ninja/ninja-cmake.mk b/devel/ninja/ninja-cmake.mk
index 1ba079203..290e86ed9 100644
--- a/devel/ninja/ninja-cmake.mk
+++ b/devel/ninja/ninja-cmake.mk
@@ -5,7 +5,7 @@ CMAKE_HOST_OPTIONS += -DCMAKE_GENERATOR="Ninja"
 CMAKE_OPTIONS += -DCMAKE_GENERATOR="Ninja"
 
 define Host/Compile/Default
-       $(call Ninja,-C $(HOST_BUILD_DIR)/$(CMAKE_BINARY_SUBDIR),)
+       $(call Ninja,-C $(HOST_BUILD_DIR)/$(CMAKE_BINARY_SUBDIR) $(1),)
 endef
 
 define Host/Install/Default
diff --git a/utils/mariadb/Makefile b/utils/mariadb/Makefile
index 03bdd51c3..40919abe6 100644
```

I think the other defines in ninja-cmake.mk might also need some reworking. The question would be if users can call them with extra arguments or not, for instance $(call Build/Compile/Default,extra arguments).

**Comment by neheb** [comment]
Interesting...

Something like that could also get rid of the openobex patch.

**Comment by neheb** [comment]
Let's see if anything blows up...

**Pull request merged**
