### PR TITLE
repo: Add more information to the issue template

### PR DESCRIPTION
**Pull request by diizzyy**
Rephrase the template a bit and add information about
older releases and forks.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@thess @hnyman @BKPepe @neheb @jefferyto @champtar @feckert @karlp @yousong

**Comment by BKPepe** [comment]
I'm not sure about forks even I understand the reasons, but could we make an exception please? :P

**Comment by jefferyto** [comment]
Perhaps we can

* Add links to bug trackers or other contact info for popular derivatives
* Urge reporters to contact their downstream project first, then report their issue here if downstream told them to, or if they can show that the problem directly affects OpenWrt (ideally they can reproduce their issue in OpenWrt)

As for older releases, perhaps we can again urge reporters to make sure their issue is reproducible in the current release or in snapshots.

**Comment by feckert** [comment]
> I'm not sure about forks even I understand the reasons, but could we make an exception please

What do you mean with exception?

I think we should not use a name 17.01 or 18.06 we should use the name **old stable** or something similar, so we do not need to changes this every time a new release is made.

Maybe:

> Issues related to **old stables** and forks are not supported or maintained and will be closed.

**Comment by diizzyy** [comment]
@BKPepe 
Forks --> https://github.com/domino-team etc
I understand that turris-os falls under that category however you guys from nic.cz are pretty much the only ones that runs it and no one tracks changes in your tree.

@feckert 
While I agree there's no simple way for us to define "old stables" to my knowledge which would need going somewhere else to look and would be annoying IMHO. Given that major releases are branched it might not be much of an issue.

**Comment by diizzyy** [comment]
@jefferyto 
Wall of text --> 99% wont read :-(
I sure how to turn all that into like 2 sentences or so.

**Comment by jefferyto** [comment]
Maybe just:

> Please make sure your issue is reproducible on the current stable version series (18.06) or a recent development snapshot build of OpenWrt.
> 
> If you are using an OpenWrt derivative, for example Turris OS, please report your issue to your OS's bug tracker.

I think updating the stable version number once a year is okay :laughing:

**Comment by BKPepe** [comment]
> > If you are using an OpenWrt derivative, for example Turris OS, please report your issue to your OS's bug tracker.

For other forks, which are not cooperating with upstream as we do now, it would be good approach, but
since Turris OS 4.x, we're doing things differently. Explained at https://github.com/openwrt/packages/pull/7976#issuecomment-458696678 

We will say that it's bug in OpenWrt or in upstream as Turris OS 4.0 is designed as a patchset, which means we're based on top of OpenWrt with our feeds and patches. Users can choose between stable or master as we're using tags from OpenWrt. You could check it from our repository, where we have file [git-hash](https://repo.turris.cz/hbs/packages/mox/git-hash), where you can check commit of each repositories, which we're using. The branch hbs points to stable release of OpenWrt. The file is automatically generated.

**Comment by jefferyto** [comment]
@BKPepe I think reporting issues to you (Turris) first is still the best way to go, because for end users, they don't usually know whether their issue is because of a patch/fork in Turris OS or if the issue originates in OpenWrt. You would be in the best position to know this :joy:

And if the issue is because of "upstream", then by all means tell the reporter to file an issue here (preferably with a note saying you sent them here).

This would be similar to how Ubuntu users file issues with Ubuntu before going up to Debian, or how software projects tell their users to file issues with their distro's packagers before going to them directly.

Obviously this would be more triage work for you, but maybe there are ways to ease that burden as well (I don't have any at the moment though :joy:).

**Comment by neheb** [comment]
Should we merge?

**Comment by diizzyy** [comment]
Any objections?

**Pull request merged**
