### PR TITLE
add package for ncp (https://www.fefe.de/ncp)

### PR DESCRIPTION
**Pull request by ashimokawa**
I am really unsure which license I should specify.
Quote from the source code:

> This is free software; copy and use it as you like.  No warranty.

So I just put in "FREE" there but I guess that's not what you guys expect ;)

### CODE REVIEW

**Comment by thess** [comment]
FREE is OK. Just add an empty _PKG_LICENSE_FILES:=_ and it will be ready to be merged.

**Comment by ashimokawa** [comment]
Done, feel free to squash

**Comment by thess** [comment]
- Needs "signed-off-by" (missed it before). Neither commit has signature.
- Prefix commit message with package name. Example: "ncp: Add new package"

I'd love to squash it for you, but I think you should do this yourself as the maintainer.

**Comment by ashimokawa** [comment]
OK, squashed, changed commit message, signed off

**Comment by thess** [comment]
Thanks

**Pull request merged**
