### PR TITLE
glib2: update to 2.68.1

### PR DESCRIPTION
**Pull request by neheb**
Removed two now pointless patches as they were added as options.

Switch to AUTORELEASE for simplicity.

Update MESON_ARGS.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tripolar 
Compile tested: mips64el

### CODE REVIEW

**Comment by neheb** [comment]
@micmac1 gsmlib fails with this. can you take a look?

**Comment by micmac1** [comment]
On Mon, Apr 12, 2021 at 11:37:04PM -0700, Rosen Penev wrote:
> @micmac1 gsmlib fails with this. can you take a look?

gsmlib does not depend on glib2. Can you recheck/provide details?

**Comment by neheb** [comment]
Some issue regarding gettext.

**Comment by micmac1** [comment]
On Tue, Apr 13, 2021 at 03:35:05AM -0700, Rosen Penev wrote:
> Some issue regarding gettext.

I cannot reproduce.

**Pull request merged**
