### PR TITLE
18.06: python3: fix _ssl build and backport python3-packages

### PR DESCRIPTION
**Pull request by yousong**
Maintainer: @commodo , @yousong 
Compile tested: x86/64 with sdk
Run tested: n/a

Description:

The python3 version bump is required for ssl support of host build.

The python3-packages backport is more for practical convenience considerations.   @laurivosandi has been trying to get this working for openwrt-18.06.  With python2 soon to be retired, having this package available in our latest release should help a bit the transition.

### CODE REVIEW

**Comment by yousong** [comment]
Config snippet for compile-test

```
CONFIG_DEVEL=y
CONFIG_PACKAGE_libpq=y
CONFIG_PACKAGE_python3-packages=y
CONFIG_PACKAGE_python3-packages-list="numpy psycopg2"
CONFIG_PACKAGE_python3-packages-extra-deps="libpq.so.5"
```

**Comment by yousong** [comment]
v2 <- v1 Update `PYTHON3_SETUPTOOLS_VERSION` and `PYTHON3_PIP_VERSION`

**Comment by yousong** [comment]
v3 <- v2 Add back `--no-build-isolation`.  pip 9.0.3 bundled with python 3.6.5 does not support it.  But pip 18.1 with python 3.6.8 has it.

**Comment by commodo** [comment]
from my side this is fine
not sure about the policy on upgrading + new stuff in releases branches;
i mean, i am not the one enforcing that

**Comment by yousong** [comment]
Python verison bump from 3.6.5 to 3.6.8 should contain only bugfix only.  This should be okay IMHO.

As for the python3-packages package from master branch, I agree that the general good practice is that new stuff/feature should not be introduced into release branch.

If the imminent retirement of python2 and benefit of production convenience are not enough to bring a few more explicit approvals, I think it's better we leave it be at the master branch.  Not disturbing release branch too much ;)

**Comment by yousong** [comment]
Thinking it again, better we leave it alone.  The pip version change alone from `9.0.3` to `18.1` is too big a change that can take time to handle ;)

**Pull request closed without merging**
