### PR TITLE
[packages] tinyproxy: handling of option XTinyproxy

### PR DESCRIPTION
**Pull request by Mathieu-Coupe**
1.) Fix the handling of XTinyproxy option to avoid syntax error when starting tinyproxy:

example:
Syntax error on line 15
Unable to parse config file. Not starting.

Signed-off-by: Mathieu Coupé <eagle.pounains@gmail.com>

Maintainer: me / @jow- 
Compile tested: no compilation, shell script
Run tested: tested on OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.228.31946-f64b152)

Description: Fix the handling of XTinyproxy option to avoid syntax error when starting tinyproxy

### CODE REVIEW

**Comment by neheb** [comment]
ping @Mathieu-Coupe can you rebase?

**Comment by Mathieu-Coupe** [comment]
Patch is up to date, and checks are now ok

**Comment by neheb** [comment]
I just looked at the change. This is changing behavior. It needs PKG_RELEASE to be bumped.

Would updating be possible? I had this pull request: https://github.com/openwrt/packages/pull/7685 that I did not runtime test.

**Comment by Mathieu-Coupe** [comment]
Hi, I'm not sure how to change PKG_RELEASE version (nor which value should I set). Any documentation ?

**Comment by jow-** [comment]
https://openwrt.org/docs/guide-developer/package-policies#versioning

**Comment by neheb** [comment]
Not sure if there's a good way to do it through GitHub's interface. Maybe go to your branch and edit the Makefile?

**Comment by neheb** [comment]
I'd squash the commits.

**Pull request merged**
