### PR TITLE
fdm: Fix download URL

### PR DESCRIPTION
**Pull request by neheb**
Sourceforge link went away. The GitHub mirror also has the wrong path.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @pfzim

### CODE REVIEW

**Comment by diizzyy** [comment]
@neheb 
Doesn't compile so this pull request makes little sense...

**Comment by neheb** [comment]
Correct. I'm just letting it rot here until I fix it. The basic premise is correct though. The main goal is to fix uscan.

**Comment by diizzyy** [comment]
Please close unless you intend to fix this soon-ish.

**Comment by diizzyy** [comment]
https://github.com/libressl-portable/portable/commit/a7f031ba55ac4a69263000357eb7f6d7fb88101a
or something like that should fix it if we need the package at all....

**Comment by neheb** [comment]
There's an easier solution. Will test.

**Comment by neheb** [comment]
In case it wasn't clear, this pull request is fixed and ready.

**Comment by neheb** [comment]
I edited the commit message to better reflect the current state.

I also removed most of the patches and replaced them with the upstream solution.

Please re-review.

**Pull request closed without merging**
