### PR TITLE
slang2: Add support for full NLS compilation

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jefferyto 
Compile tested: arc700

https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/slang2/compile.txt

### CODE REVIEW

**Comment by neheb** [comment]
I can't tell if this build failure is a false positive.

**Comment by jefferyto** [comment]
Looks like something weird happened with CircleCI. I tried compiling locally with ath79 and it went through fine. I would just try force pushing again.

I would also add `--with-iconv="$(ICONV_PREFIX)"` to `CONFIGURE_ARGS`; the detection code in configure isn't great.

**Comment by neheb** [comment]
Added. I also tested on mips64. Works fine there too. No idea what's wrong.

**Comment by neheb** [comment]
BTW, I see this line

```
checking for the onig library and header files oniguruma.h... no
```

There's also libevhtp which provides this header. I don't use the package so I have no idea what impact this has.

**Comment by neheb** [comment]
I took a look again. For some reason CircleCI seems to try to build for mipsel even though this is mips. Again, it compiles fine on mips64, which is a big endian target.

**Comment by jefferyto** [comment]
I'm still investigating what's going wrong right now, but it's not building for mipsel; it's trying to build `src/$(ARCH)elfobjs/libslang.so.2.3.2`, so with `ARCH=mips` it comes up with `mipselfobjs`.

Also, oniguruma is a regex library. libevhtp use to bundle a copy of oniguruma with its source, but they [removed it in 1.2.14](https://github.com/criticalstack/libevhtp/blob/00ccb5c80f7cfc3405ec39ce105f0f63a7425151/ChangeLog#L97). The current version in our tree (1.2.0) still has the bundled copy, but I don't think it should be used by / available to other packages.

**Comment by jefferyto** [comment]
From the build log, this is the part that failed:

```
cd src; make elf
make[4]: Entering directory '/home/build/build_dir/build_dir/target-mips_24kc_musl/slang-2.3.2/src'
/home/build/build_dir/build_dir/target-mips_24kc_musl/slang-2.3.2/autoconf/mkinsdir.sh /home/build/build_dir/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs
cp sysconf.h config.h
make[4]: *** No rule to make target '/home/build/build_dir/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs', needed by '/home/build/build_dir/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs/libslang.so.2.3.2'.  Stop.
```

`autoconf/mkinsdir.sh` (a copy of mkinstalldirs from autoconf) is suppose to create the directory `src/mipselfobjs` but it exits with an error status (but no error message).

For comparison, here is the same log fragment from my local build:

```
cd src; make elf
make[4]: Entering directory '/media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/src'
/media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/autoconf/mkinsdir.sh /media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs
mkdir -p -- /media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs
touch /media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs/tstamp
cp sysconf.h config.h
cp terminfo/default.inc terminfo.inc
cd /media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/src/mipselfobjs && mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2:slang-2.3.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/media/jeff/Jekyll/Files/openwrt/testing/ath79/staging_dir/target-mips_24kc_musl/usr/lib/libiconv-stub/include -I/media/jeff/Jekyll/Files/openwrt/testing/ath79/staging_dir/target-mips_24kc_musl/usr/lib/libintl-stub/include -fpic -Wall -W -pedantic -Winline -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wcast-align -Wshadow -Wstrict-prototypes -Wformat=2 -fPIC  -Dunix -DSLANG  -DMISC_TERMINFO_DIRS='"/etc/terminfo"' /media/jeff/Jekyll/Files/openwrt/testing/ath79/build_dir/target-mips_24kc_musl/slang-2.3.2/src/sltermin.c
```

Here, `mkinsdir.sh` execs `mkdir -p -- ...`, then the build continues normally (with `touch .../src/mipselfobjs/tstamp`).

I'm not really sure why `mkinsdirs.sh` is failing, but I won't have time to debug further until later tomorrow, so I thought I'd add a note here with what I found so far.

**Comment by neheb** [comment]
Weird. Problem with CircleCI?

**Comment by jefferyto** [comment]
I think I have a solution... Parallel build is enabled in CircleCI (`-j3`). I thought I tested this before, but when I use the same option (or just `-j2`) I get the same error.

So removing `PKG_BUILD_PARALLEL:=1` from the Makefile fixes this issue. Why `mkinsdir.sh` fails when parallel builds are enabled is still a mystery for me :man_shrugging:

**Comment by neheb** [comment]
I set PKG_BUILD_PARALLEL to 0 to specify that it doesn't work right.

**Comment by jefferyto** [comment]
@neheb Sounds good - thanks again for your help!

**Pull request merged**
