### PR TITLE
libpfring: update to 8.6.1

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation with kernel 6.6

Remove upstream backport.

Maintainer: none

### CODE REVIEW

**Comment by sbwml** [comment]
Test build on aarch64_generic platform, `.sendpage` should need to be removed on linux 6.6.

```diff
--- a/kernel/pf_ring.c
+++ b/kernel/pf_ring.c
@@ -8458,7 +8458,9 @@ static struct proto_ops ring_ops = {
   .getname = sock_no_getname,
   .listen = sock_no_listen,
   .shutdown = sock_no_shutdown,
+  #if(LINUX_VERSION_CODE < KERNEL_VERSION(6,6,0))
   .sendpage = sock_no_sendpage,
+  #endif
 
   /* Now the operations that really occur. */
   .release = ring_release,
```

**Comment by hauke** [comment]
This update also fixes a compile problem with gcc 13.

**Comment by sbwml** [comment]
> This update also fixes a compile problem with gcc 13.

gcc14 too

image

**Comment by taylorkline** [comment]
More specifically, this fixes #23621 because [this commit](https://github.com/ntop/PF_RING/commit/c0af55a921c1867db973d8885cadc425ea15b8a3) is included in `libpfring` 8.6.0 and 8.6.1.

**Comment by 1715173329** [comment]
what stops this from getting merged?

**Comment by neheb** [comment]
Merge conflict

**Comment by remittor** [comment]
For support kernel 6.6 please add this patch:
```
From blabla
From: blabla
Date: blabla
Subject: [PATCH] blabla

--- a/kernel/pf_ring.c
+++ b/kernel/pf_ring.c
@@ -8450,8 +8450,10 @@ static struct proto_ops ring_ops = {
   .getname = sock_no_getname,
   .listen = sock_no_listen,
   .shutdown = sock_no_shutdown,
+#if(LINUX_VERSION_CODE < KERNEL_VERSION(6,5,3))
   .sendpage = sock_no_sendpage,
+#endif
 
   /* Now the operations that really occur. */
   .release = ring_release,
```

**Comment by aduskett** [comment]
The patch added should be:

`patches/102-fix-kernel-6.6`
```
--- a/kernel/pf_ring.c
+++ b/kernel/pf_ring.c
@@ -8458,7 +8458,9 @@ static struct proto_ops ring_ops = {
   .getname = sock_no_getname,
   .listen = sock_no_listen,
   .shutdown = sock_no_shutdown,
+#if(LINUX_VERSION_CODE < KERNEL_VERSION(6,5,3))
   .sendpage = sock_no_sendpage,
+#endif
 
   /* Now the operations that really occur. */
   .release = ring_release,
```

**Comment by neheb** [comment]
Reworked. Should build now.

**Comment by neheb** [comment]
Huh. strange...

**Pull request merged**
