### PR TITLE
Update facebook libraries to newer versions

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @ammubhave

### CODE REVIEW

**Comment by neheb** [comment]
For some reason, the buildbots are currently failing: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/fbthrift/compile.txt

I added an explicit C++14 for a different reason.

Maybe the buildbots switched to GCC5 or something...

**Comment by aparcar** [comment]
Isn't codeload preferred over raw git?

**Comment by neheb** [comment]
It's a matter of taste honestly. The OpenWrt repository has only one codeload package.

**Comment by diizzyy** [comment]
Please use codeload whenever possible

**Comment by neheb** [comment]
Updated to latest releases. Switched back to codeload.

**Comment by neheb** [comment]
CMake update broke several components. I will update these in separate PRs.

**Pull request closed without merging**
