### PR TITLE
treewide: Capitalize submenus

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @commodo @adde88 @br101 @dangowrt @pfzim @champtar @haraldg @padre-lacroix @jmccrohan @jow- @ZeroChaos- @micmac1 @heil @ascob @yousong 
Compile tested: `make menuconfig` tested
Run tested: N/A

Description:
Capitalize submenus to keep them consistent and in alphabetical order.
I've run 
```
sed -i -e 's/\(SUBMENU:=\)\([a-z]\)/\1\u\2/' $(git grep -l 'SUBMENU:=[a-z]')
```
**and checked the results**. adjusting OpenWISP and LibElektra to match upstream capitalization, and tcprelay to Tcpre**p**lay, assuming this was a typo.
I did not change anything else in the Makefiles, so `PKG_RELEASE` increment is not needed.

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Not sure about that libelektra change. ping @haraldg 

Otherwise LGTM.

**Comment by cotequeiroz** [comment]
> 
> 
> Not sure about that libelektra change. ping @haraldg
> 
> Otherwise LGTM.

I've used the same capitalization you can see [here](https://github.com/ElektraInitiative/libelektra):
> Elektra consists of three parts:
> 
>    1. **LibElektra** is a modular configuration access toolkit to construct and integrate applications into a global, hierarchical key database. 


Of course, one could argue for the use of just **Elektra**, but that would be an actual change. :grinning:

**Comment by neheb** [comment]
Hrm fair enough.

**Comment by yousong** [comment]
Thanks for the inputs!

**Pull request merged**
