### PR TITLE
snort3: improve date filtering in report

### PR DESCRIPTION
**Pull request by efahl**
- Reduce memory footprint while running reports allowed by recent jsonfilter bug fix.  
- Improve headers and footers on report.  
- Add new match operator for date filtering.

Maintainer: @flyn-org @graysky2
Compile tested: NA
Run tested: x86 snapshot

### CODE REVIEW

**Comment by graysky2** [comment]
Reviewing the code by eye seems OK.  Full disclosure: my snort setup is using the legacy snort init script with legacy `homenet.lua` `local.lua` etc. so I am not able to test the code in this PR.

@flyn-org thoughts?

**Comment by efahl** [comment]
> using the legacy snort init script with legacy ... `local.lua`

I'm pretty sure the only thing reporting depends on is the json alert files, so if you were to stick the following snippet in your `local.lua` at the end, then run with that for a little bit, you would have some test inputs (assuming snort sees some events to log).  Oh, yeah, make sure `/etc/config/snort` has `option log_dir` set to point to wherever your logs actually reside...

```
alert_json = {
  file = true,
  fields = [[ timestamp pkt_num pkt_gen pkt_len proto dir src_addr src_port dst_addr dst_port gid sid rev action msg ]],
}
```

**Comment by efahl** [comment]
@flyn-org , got a minute to look this over?

**Comment by flyn-org** [comment]
Looks good. Recommend merge.

**Comment by graysky2** [comment]
@efahl - can you rebase?  the 3.1.84 update got merged

**Comment by efahl** [comment]
Rebased.

**Comment by graysky2** [comment]
Please merge

**Comment by efahl** [comment]
Rebased.

Anything else needed to get this merged?

**Comment by efahl** [comment]
@neheb, this should be an easy one if you're looking for lingering merges to clean up...

**Pull request merged**
