### PR TITLE
Nano and Fwknop updates

### PR DESCRIPTION
**Pull request by jp-bennett**
Maintainer: me
Compile tested: Openwrt Master, x86_64
Run tested: Openwrt Master, x86_64

Description: Update Nano and Fwknop to latest versions.
Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>

### CODE REVIEW

**Comment by jp-bennett** [comment]
Does the CI test seriously not know that email addresses are not case sensitive?

**Comment by neheb** [comment]
ROFL. Anyway, ACK on the fwknop bump.

**Comment by hnyman** [comment]
> Does the CI test seriously not know that email addresses are not case sensitive?

To me it seems that it fails to separate the commit title line from the subsequent lines. 
No empty line between title and signed-off-by lines?

```
=== Checking commit 'ffd08a733081f43d11b4de28864f39aec10e6aa3'
Author name (Jonathan Bennett) seems ok
Commit subject line seems ok (Fwknop: Update to 2.6.10 Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>')
```

**Comment by cshoredaniel** [comment]
On 2018-09-09 6:04 p.m., Jonathan Bennett wrote:
>
> Does the CI test seriously not know that email addresses are not case 
> sensitive?
>
Actually it's more complicated than that.  I discovered, after many 
years of believing that, that according to RFC the local-part (before @) 
is allowed to be case-sensitive, but the domain part is not.

Regards,

Daniel

**Pull request merged**
