### PR TITLE
docker-ce: fix cross compilation and enable build for arm and aarch64

### PR DESCRIPTION
**Pull request by juppin**
Maintainer: @G-M0N3Y-2503
Compile tested: aarch64, bcm2710, raspberry pi 3b
Compile tested: arm, imx6, custom board
Run tested: aarch64, bcm2710, raspberry pi 3b
Run tested: arm, imx6, custom board

Description:
Enable builds of docker-ce and needed tools/libraries (**containerd**, **libnetwork**, **runc**)  for **arm** and **aarch64**.
I´ve backported a build script fix for cross compilation of **docker-ce** to get the builds running inside the openwrt buildroot.

### CODE REVIEW

**Comment by juppin** [comment]
@G-M0N3Y-2503 Do you know why the ci test fails on the HASH check of **runc**?

**Comment by yousong** [comment]
> @G-M0N3Y-2503 Do you know why the ci test fails on the HASH check of **runc**?
> Local build does work as expected...

The sha256sum should be wrong since last commit.  Can you share your sha256sum of the file dl/runc-* ?

**Comment by juppin** [comment]
Hmm, if i build locally with `make package/runc/compile` i see a waring about mismatching hash, but it compiles without error...
Tried to fix the **PKG_MIRROR_HASH** with `make package/runc/check V=s FIXUP=1`, but in ci pipeline the hash does also mismatch with the updated value.
Is this related to download as git repo?

> The sha256sum should be wrong since last commit.

What do you mean with since last commit? Commit of runc repo?

> Can you share your sha256sum of the file dl/runc-* ?

`61b3d4941a4f9a7667ce979d8f86bcd97d4f3f19f264df648c3790bb3b5f2e66  dl/runc-1.0.0-rc8+91-3e425f80.tar.gz`

**Comment by yousong** [comment]
> Hmm, if i build locally with `make package/runc/compile V=s` i see a waring about mismatching hash, but it compiles without error...
> Tried to fix the **PKG_MIRROR_HASH** with `make package/runc/check V=s FIXUP=1`, but in ci pipeline the hash does also mismatch with the updated value.
> Is this related to download as git repo?
> Could we fix it with a download of the tar.gz archive instead of git clone with depth=1?
> 
> > The sha256sum should be wrong since last commit.
> 
> What do you mean with since last commit? Commit of runc repo?

Since last runc version bump: https://github.com/openwrt/packages/pull/10250/files

> 
> > Can you share your sha256sum of the file dl/runc-* ?
> 
> `61b3d4941a4f9a7667ce979d8f86bcd97d4f3f19f264df648c3790bb3b5f2e66 dl/runc-1.0.0-rc8+91-3e425f80.tar.gz`

At the time of this writing, the sha256sum of `runc-1.0.0-rc8+91-3e425f80.tar.gz` should be `11dce499b6fbdb159d2ef64b0e9b719ccdf6c59ca1cc7ac0026b1d58547fc187` as reported by ./scripts/dl_github_repo.py and tarball made by git checkout.

In current runc/Makefile, we have the following.  `PKG_HASH` should not be there for `PKG_SOURCE_PROTO` git.  `PKG_MIRROR_HASH` is different from what the build system actually got

```
PKG_MIRROR_HASH:=361658b3c61b9c727091aa10ba693f234a64aae592bb683005244a22e2778cfc
PKG_HASH:=efe4ff9bbe49b19074346d65c914d809c0a3e90d062ea9619fe240f931f0b700
``` 

Now we have another `61b3d4941a4f9a7667ce979d8f86bcd97d4f3f19f264df648c3790bb3b5f2e66`.  Is it possible that you manually intervened the preparation of that file when doing local build?

We will need to fix the runc/Makefile in the end.  It will  be helpful if we can figure out how the current situation occurred in the first.

**Comment by jneuhauser** [comment]
> Is it possible that you manually intervened the preparation of that file when doing local build?

I don´t know why the resulting hash on my machine was different than `11dce499b6fbdb159d2ef64b0e9b719ccdf6c59ca1cc7ac0026b1d58547fc187`...
I assure that I have not changed the source code or download process of runc.

I´ve deleted the file **dl/runc-***, rebased my commits to make each a single step for each package and tested the compilation on two machines... 
This resulted in `11dce499b6fbdb159d2ef64b0e9b719ccdf6c59ca1cc7ac0026b1d58547fc187` for  `dl/runc-1.0.0-rc8+91-3e425f80.tar.gz`.
I´ve rechecked the local buildoutput of runc and don´t see it complaining about hash mismatch.

@yousong 
Why is the ci build running for **mips** and not only for **arm**, **aarch64** and **x86_64** as defined in the makefile?

**Comment by yousong** [comment]
> 
> @yousong
> Why is the ci build running for **mips** and not only for **arm**, **aarch64** and **x86_64** as defined in the makefile?

Invoking `package/xx/compile` directly will compile xx regardless of whether it is selected or not.  We will need to check .config and skip xx dir if none of its packages were enabled there.  I will see if I can find time to implement that.

**Comment by G-M0N3Y-2503** [comment]
I think we need to increment the `PKG_RELEASE` variable for these 4 Makefiles for versioning reasons, If I'm not mistaken.

As for the `runc` package mirror hash, It seems I forgot to check [the failing pipeline](https://circleci.com/gh/openwrt/packages/5650?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) to make sure it's the normal failure and not another failure :(

But otherwise, this PR looks good to me.

**Comment by jneuhauser** [comment]
> I think we need to increment the PKG_RELEASE variable for these 4 Makefiles for versioning reasons If I'm not mistaken.

Increased the PKG_RELEASE on all modified packages. Thanks.

**Comment by yousong** [comment]
> > @yousong
> > Why is the ci build running for **mips** and not only for **arm**, **aarch64** and **x86_64** as defined in the makefile?
> 
> Invoking `package/xx/compile` directly will compile xx regardless of whether it is selected or not. We will need to check .config and skip xx dir if none of its packages were enabled there. I will see if I can find time to implement that.

Now if this is still interesting ;), please consider rebase to current master branch and see the check can now pass.  Thank you

**Comment by yousong** [comment]
Thank you!

**Pull request merged**
