### PR TITLE
Fix typo in ddns-scripts: s/ganid/gandi/

### PR DESCRIPTION
**Pull request by bheesham**
Maintainer: @chris5560 / @FlorianFieber ?
Compile tested: N/A, docs change.
Run tested: N/A, docs change.

Description:

Fix a super quick typo.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@feckert, @jow-: Maintainers are away from GitHub but for this small typo changes...

**Comment by feckert** [comment]
Sorry. This pullrequest does have formal issues (See CI)!
- Please update the commit header with `ddns-scripts: Fix typo s/ganid/gandi/`
- Add a valid Singed-off-by
If it's ok for you @bheesham then I'll push that directly and add your Signed-off-by.

**Comment by BKPepe** [comment]
Also missing ``PKG_RELEASE`` bump.

**Comment by bheesham** [comment]
> Sorry. This pullrequest does have formal issues (See CI)!
> 
> * Please update the commit header with `ddns-scripts: Fix typo s/ganid/gandi/`
> * Add a valid Singed-off-by
> 
> If it's ok for you @bheesham then I'll push that directly and add your Signed-off-by.

Apologies for the late reply! I rebased, edited the commit message, and signed off.


> Also missing `PKG_RELEASE` bump, but it is a typo in description, thus we will continue to enjoy vacation, thanks @Neustradamus for letting us know. :)

I can bump this if you'd like. I didn't because I wasn't sure if it warranted a version bump or not.

Thanks for taking a look all! :)

**Comment by Neustradamus** [comment]
@bheesham: Please do a change to "PKG_RELEASE:=25"

**Comment by bheesham** [comment]
Aaand done!

**Comment by feckert** [comment]
Thanks merged!!

**Pull request merged**
