### PR TITLE
avahi: convert to procd

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @thess 
Compile tested: malta

@Andy2244 can you test this?

### CODE REVIEW

**Comment by Andy2244** [comment]
Sure, can check this on Sunday, when i also update/check the new ksmbd/samba4 versions.

**Comment by neheb** [comment]
Just tested. I'm confused about this package. It creates an avahi user and group but then drops privileges to run as nobody.

And apparently that's only for the nodbus-daemon...

**Comment by neheb** [comment]
In my testing, this works fine.

**Comment by Andy2244** [comment]
Build/installed your version, but had no time to really test yet.

**Comment by neheb** [comment]
I tested /etc/init.d/avahi-daemon restart/start/stop. All works fine from what I see. This is only an init script change.

**Pull request merged**
