### PR TITLE
shairport-sync: New package from MikeBrady

### PR DESCRIPTION
**Pull request by thess**
Signed-off-by: Ted Hess <thess@kitschensync.net>

### CODE REVIEW

**Comment by thess** [comment]
@mikebrady -- This look OK to you?

**Comment by mikebrady** [comment]
Hi Ted. Thanks for doing this – it looks fine. One thing FYI is that I updated Shairport Sync to 2.2 over the weekend, and there is a version 2.2 of shairport-sync-for-openwrt – not yet the default – but it might be better to go with 2.1.15 and test 2.2 on OpenWrt a little more before updating it. Whaddyathink?

**Comment by thess** [comment]
2.1.15 was the latest tag. After you tag 2.2 either drop me a note or create a PR and we can update it. To get started I'll go with 2.1.15.

**Comment by mikebrady** [comment]
Perfect, thanks.

**Comment by probonopd** [comment]
Thanks for adding shairport-sync. Would it be possible to add a version that does not have the libavahi-client dependency as well? There is a Makefile to do this at https://github.com/probonopd/shairport-sync-for-openwrt/blob/2.1/Makefile

**Comment by mikebrady** [comment]
Hi Ted. Is there something slightly wrong with the avahi package – I get an error saying a build package for libavahi can't be found in a fresh trunk build if I select Raspberry Pi and libavahi-client? I see you're maintining that package as well (oddly, I used to too). The error surfaced building shairport-sync but it's there even when you only try to include libavahi-client.

**Comment by thess** [comment]
@probonopd -- good request. I'm going to see about building it without libavahi and then perhaps adding a service package (default port) as in MPD.

@mikebrady -- I will check this out shortly.

**Comment by thess** [comment]
@mikebrady - this should be fixed with 8f10e59f70a9dc728d93af2384bd94078a4c24d6.

**Comment by mikebrady** [comment]
Thanks Ted. I'll give it a try.

**Comment by mikebrady** [comment]
Hi Ted. Thanks for doing the package for Shairport Sync. I've been using it for a while, but I think there might be a tiny unhappiness in it. It seems to me that `shairport-sync` isn't properly entering the background mode – it doesn't write to the log file, etc. So, I think maybe you should include the `-d` option in the startup script. It seems to make it work properly for me, but I'm not a `procd` expert. What you you think?

**Comment by thess** [comment]
Using `procd` means you don't have to daemonize the process and procd retains control. If you add -d to the command line, procd will be unable to stop it among other things (It may even complain when the process detaches). If there is some functionality you want to have enabled that is already part of the daemonize option, perhaps that should be a separate option.

**Comment by mikebrady** [comment]
Thanks – I guessed there was something special going on. I'll have to dig in to `procd`, see what I need to do.

**Pull request merged**
