### PR TITLE
golang: Update to 1.23.1

### PR DESCRIPTION
**Pull request by p-w-p**
Maintainer: @jefferyto
Compile tested: all supported targets
Run tested: rockchip/armv8

Description:
The latest Go release, version 1.23, arrives six months after [Go 1.22](https://go.dev/doc/go1.22). Most of its changes are in the implementation of the toolchain, runtime, and libraries. As always, the release maintains the Go 1 [promise of compatibility](https://go.dev/doc/go1compat). We expect almost all Go programs to continue to compile and run as before.

### CODE REVIEW

**Comment by p-w-p** [comment]
CC @1715173329 @mochaaP

**Comment by BKPepe** [comment]
At least from my side, it was better as it was done in the previous PR. 
1st commit update to 1.23.0 with adding more values
and then the 2nd commit with the other update.

Doing this in one commit could be messy.

**Review by 1715173329 — APPROVED** [review]

**Comment by 1715173329** [comment]
Please update GOROOT_FINAL according to https://github.com/openwrt/packages/pull/24802#issuecomment-2358146580.

**Comment by 1715173329** [comment]
According to golang/go#62047, `GOROOT_FINAL` should be fine to remove from Makefile directly.

**Review by 1715173329 — APPROVED** [review]

**Comment by 1715173329** [comment]
Thinking it's time to give it a shot, any idea?

**Pull request merged**
