### PR TITLE
libwebsockets: remove build hostname

### PR DESCRIPTION
**Pull request by lynxis**
Maintainer: @karlp
Compile tested: x86

Using the build hostname breaks reproducible builds.

Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

### CODE REVIEW

**Comment by karlp** [comment]
Looks fine at first glace to me, will test it.  Do you have a link to where you've filed this upstream?

**Comment by karlp** [comment]
Was there a followup to this with upstream?  They merge or respond to _everything_  (They currently have 0 open issues and 3 open PRs)

**Comment by lynxis** [comment]
I didn't filed it upstream yet. Feel free to do so. My plan was first get it accepted here and push it to upstream later. Sometimes the discussion on reproducible builds and removing build timestamp/hostname/.. is more complex or can take a long time e.g. a year.

**Comment by karlp** [comment]
Well, there's not going to be discussion if you don't even file it.  I don't want to maintain this here and then get something else later.  I pointed out that this project _is_ responsive, so please do file it there so I can maintain something that will be upstreamed.

**Comment by lynxis** [comment]
https://github.com/warmcat/libwebsockets/pull/1122

**Comment by lynxis** [comment]
The patch got merged upstream and I updated the PR inlcuding the upstream patch.

**Comment by karlp** [comment]
Merged in 3531c3a6c009130426d92f29d2123addf9669b9f

**Pull request closed without merging**
