### PR TITLE
vala: refresh patch

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation.

Maintainer: @flyn-org 

@Ansuel interesting that host packages are not checked...

### CODE REVIEW

**Comment by Ansuel** [comment]
@neheb what do you mean not checked?

**Comment by neheb** [comment]
before this PR, the patch does not apply at all. But CI was green.

**Comment by Ansuel** [comment]
@neheb the test use refresh so it's really strange.

**Comment by neheb** [comment]
well, remember that it's

```
make package/x/host/refresh
```

and not

```
make package/x/refresh
```

**Comment by Ansuel** [comment]
@neheb oh! yes that is not tested! If host is not defined does that make target fails or is just ignored?

**Comment by neheb** [comment]
```
> make package/confuse/host/refresh V=s
make[2]: Entering directory '/home/mangix/devstuff/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/scripts/config'
make[1]: Entering directory '/home/mangix/devstuff/openwrt'
make[1]: *** No rule to make target 'package/confuse/host/refresh'.  Stop.
make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:232: package/confuse/host/refresh] Error 2
```

**Comment by neheb** [comment]
Superseded by https://github.com/openwrt/packages/pull/23362

**Pull request closed without merging**
