### PR TITLE
minidlna: fix issues

### PR DESCRIPTION
**Pull request by neheb**
Swapped cover resizing patch for a simpler one.

Fixed reload not working properly.

Removed service_triggers. They don't work currently.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: nobody
Compile tested: ath79

### CODE REVIEW

**Comment by jow-** [comment]
Removing the service tirggers will break LuCI support for minidlna.

**Comment by neheb** [comment]
Hrm never tested LuCI.

I don't see any reference to triggers in the original init script. Does procd make a difference here?

**Comment by jow-** [comment]
You can disregard LuCI for now. A simpler way to test is modifying a random uci value, committing it and invoking `reload_config`, that should trigger an `/etc/init.d/minidlna reload`.

The reload action as it is implemented in this PR (`procd_send_signal minidlna`) does not make much sense since there won't be any updated configuration to reload. At the very least you need to invoke the uci->/var/etc/minidlna.conf conversion machinery before sending the signal.

A bare `procd_send_signal` without additional measures makes only sense for services which parse uci natively (e.g. netifd).

**Comment by neheb** [comment]
Removed it. Reworked commit message.

**Pull request merged**
