### PR TITLE
inotify-tools: update to 3.20.1

### PR DESCRIPTION
**Pull request by reinerh**
Signed-off-by: Reiner Herrmann <reiner@reiner-h.de>

Maintainer: @dangowrt 
Compile tested: ipq806x, OpenWrt master
Run tested: ipq806x, OpenWrt master; tested watching for file changes with inotifywait

Description: Update inotify-tools upstream version to 3.20.1 and enable autoreconf run.

### CODE REVIEW

**Comment by reinerh** [comment]
I don't need them...
But there are a bunch of other packages that are also copying them.
But I'm also fine with removing them. :)

**Comment by diizzyy** [comment]
Indeed, however we don't need waste cpu cycles.

**Comment by dangowrt** [comment]
> Do we really need .a files?

Installing the .a files to staging for other packages to use to create static binaries doesn't harm and I'd find it confusing and unneeded to over-optimize InstallDev.

**Comment by dangowrt** [comment]
Thanks!

**Pull request merged**
