### PR TITLE
nut: A number of fixes and enhancements

### LINKED ISSUE #6843: nut package
Maintainer: @cshoredaniel 
Environment: (ar71xx, TP-Link Archer C7 v4, OpenWrt 18.06.0)

Description:
Seems there is a race condition which prevents **upsd** from starting.

Below is a portion of the nut-server script:
```
if [ "$have_drivers" = "true" ]; then
	    $DEBUG /usr/sbin/upsd ${runas:+-u $runas} $OPTIONS
	    $DEBUG /usr/sbin/upsdrvctl ${runas:+-u $runas} start
        fi
```
If I swap the lines and insert a 10-second delay, **upsd** starts.
```
if [ "$have_drivers" = "true" ]; then	                                                                                                                                    
            $DEBUG /usr/sbin/upsdrvctl ${runas:+-u $runas} start
            sleep 10
            $DEBUG /usr/sbin/upsd ${runas:+-u $runas} $OPTIONS
	fi
```
Also, when I try to execute forced shutdown command (**upsdrvctl shutdown**), I get the following error:
```
root@TPLINKAC1750:~# upsdrvctl shutdown
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Can't claim USB device [0764:0501]: No such file or directory
Driver failed to start (exit status=1)
```
Also, when I try to read the USB descriptors, it says "UNAVAILABLE".
```
root@TPLINKAC1750:~# lsusb -v -d 0764:0501

Bus 001 Device 003: ID 0764:0501 Cyber Power System, Inc. CP1500 AVR UPS
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0764 Cyber Power System, Inc.
  idProduct          0x0501 CP1500 AVR UPS
  bcdDevice            0.01
  iManufacturer           3 CPS
  iProduct                1 CP1500EPFCLCD
  iSerial                 2 CRNGV2000037
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     480
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
```
There seems to be a hotplug issue on the USB. If I unplug/re-plug the USB, the USB descriptors are complete when queried and the forced shutdown command succeeds.

### PR DESCRIPTION
**Pull request by cshoredaniel**
Maintainer: me 
Run tested: ath79, CR5000, current master for openwrt and openwrt-packages
In addition to while developing testing each part did a final:
  1. Did sysupgrade -n
  2. Edited nut_driver, nut_server, nut_monitor, and nut_cgi with appropriate configs via LuCi app (not yet pushed)
  3. Verifed all daemons started
  4. Queried UPS (upsc upsname@localhost)
  5. Set a variable via nut-cgi
  6. Executed a a forced shutdown (FSD) (and it came back up properly too)

Description:
The fixes #6843 by properly 'procdifying' the initscripts as well fixing a number of minor nits and adding USB hotplug support.
It also makes forced UPS shutdown (FSD) via upsmon actually work by adding a script to implement the necessary actions.

### CODE REVIEW

**Comment by cshoredaniel** [comment]
Correct me if I'm wrong, but it looks like Travis never actually got to trying to compile/package nut and some other package is what borked out?

Is there a way to retrigger Travis (without code change) once whatever is broken is fixed (local build works BTW).

**Comment by cshoredaniel** [comment]
Ooops...forgot the migration path (there have been UCI changes)...even if Travis gets working, please don't merge yet.

**Comment by cshoredaniel** [comment]
Well, broke something ... <mutters incoherently> ... will push when resolved.

**Comment by cshoredaniel** [comment]
Ok, the breakage was a need to do dirclean since I rebased against latest master for openwrt, packages, and luci.  

It's working.  And I've tested the patches with them reordered somewhat sensibly (so the first 5 I want to cherry-pick and verify on 18.06 for backporting).

Oh and I eliminated the difference in UCI; no migration is necessary.

**Comment by cshoredaniel** [comment]
Er, first **4** commits are the backport ones actually...

**Comment by cshoredaniel** [comment]
Run tested ath79, CR5000, current masters

1. Clean slate (sysupgrade -n) test.  Configs added vi LuCI.  Tested FSD
2. Rebooted, verified monitoring, FSD, CGI.  All good.

**Comment by commodo** [comment]
@cshoredaniel
In the "More Options" top-right there should be a "Trigger Build" button that let's you trigger a build [also by specifying some custom settings if you want].
That is, the button exists if you have some rights in the openwrt github account.
I'm not sure if it shows up for your PR though.

**Comment by cshoredaniel** [comment]
@commodo I don't have rights on the openwrt github account (I removed myself when I was ill and didn't think I'd be back to OpenWrt).

**Comment by malakingpusa** [comment]
Hi @cshoredaniel, we managed to compile the updated source codes and so far the forced shutdown command works.  Thanks for this.

We bumped in into some problems when we tried to use the same UCI files that was setup when we were reproducing the issue. Our next step is to start from a new /etc/config/nut_server and nut_monitor which are generated by the installed packages.

We will update you with the results.

**Comment by cshoredaniel** [comment]
@malakingpusa Hmmm....can you describe problems?  If the upsdrvctl thing, you need to stop the nut-driver before using it, as it's not meant to be used with the driver already running (and procd will restart the driver fairly quickly (i.e. before -k has a chance to read all the descriptors and do it's thing).

Can you share a sanitized version of the configs you are using so I can see what's up?

**Comment by cshoredaniel** [comment]
@malakingpusa Does your sysupgrade.conf perchance include /etc/init.d/nut-upsmon (and/dor otther nut scripts)?  if so please remove that from sysupgrade.conf and try again.

Also with the new packages (and initscripts) you should be able to do e.g.
````
/etc/init.d/nut-server stop
````
and then
````
upsdrvctl shutdown
````
and have FSD work (for a manual test).

Also now ``upsmon -c fsd`` should work too.

**Comment by cshoredaniel** [comment]
Oh, also try ``upsc CP47@localhost`` - from my tests upsc doesn't like bare upsname nowadays.

**Comment by malakingpusa** [comment]
Here is my **/etc/sysupgrade.conf**:
```
root@TPLINKAC1750:~# cat /etc/sysupgrade.conf 
## This file contains files and directories that should
## be preserved during an upgrade.
# /etc/example.conf
# /etc/openvpn/
```
When I try **upsc CP37@localhost**:
```
root@TPLINKAC1750:~# upsc CP37@localhost
Error: Driver not connected
```
This works as expected:
```
root@TPLINKAC1750:~# /etc/init.d/nut-server stop
root@TPLINKAC1750:~# upsdrvctl shutdown
Network UPS Tools - UPS driver controller reboot-7986-gdc9388a
Network UPS Tools - Generic HID driver 0.41 (reboot-7986-gdc9388a)
USB communication driver 0.33
Using subdriver: CyberPower HID 0.4
Initiating UPS shutdown
```
Why is there no **/lib/nut/usbhid-ups -a CP37** in my processes?
```
root@TPLINKAC1750:~# ps | egrep "nut|ups"
 1292 root      1100 S    /usr/sbin/upsmon -D
 1311 nut       1100 S    /usr/sbin/upsmon -D
 2146 nut       1040 S    /usr/sbin/upsd -D -u nut
 2155 root      1200 S    egrep nut|ups
```
When does the following part of the **/etc/init.d/nut-server** get executed?
```
procd_set_param command /lib/nut/${driver} -D -a "$cfg" ${RUNAS:+-u $RUNAS}
```

Right now, just have to make **upsc** work and test multiple UPSes.

**Comment by cshoredaniel** [comment]
Two questions: How long after boot are you attempting upsc (it takes some time for the driver to come up because of the way the procd + hotplug work in this case)?
If  you want to 'force' the driver to come up quickly, I think the following will work:
``/etc/init.d/nut-server stop CP37 && /etc/init.d/nut-server start CP37``
I'm puzzled by the 'no such dir' --- does it appear on subsequent flashes or just coming from the previous version?

**Comment by malakingpusa** [comment]
How long after boot are you attempting upsc (it takes some time for the driver to come up because of the way the procd + hotplug work in this case)? >> hours because i left it last night and then started again when I reported for work.

I'm puzzled by the 'no such dir' --- does it appear on subsequent flashes or just coming from the previous version? >> never encountered them with previous flashes without the new compiled packages. 

will try this command you suggested:
```
/etc/init.d/nut-server stop CP37 && /etc/init.d/nut-server start CP37
````

**Comment by cshoredaniel** [comment]
In the 'config driver' section, can you try setting
````
option vendorid [4-hex-digits-of-usb-vendord-id]
option productid [4-hex-digit-usb-product-id]
````
e.g for my setup I have

````
option vendorid 0437
option productid ffff
````

Perhaps there is some issue with hotplug messing things up without the vendorid and product id on your device (I think I tried both ways, but will try to make some time to test again).

Wait: Please use 'master' not '18.06'  The backported changes haven't been merged yet (I guess @hnyman is waiting for results with 'master')

**Comment by cshoredaniel** [comment]
@malakingpusa Please let me know the results with master; I believe you are seeing the old version of the initscripts and no hotplug because 18.06 doesn't have the updates yet.

**Comment by malakingpusa** [comment]
@cshoredaniel thanks for pointing that out. Asking our SW engineer now to compile OpenWrt from master. We will test and then update you again. Thanks.

**Comment by malakingpusa** [comment]
@cshoredaniel SW engineer is asking if we will compile source code from latest commit or latest release?

**Comment by malakingpusa** [comment]
Bumped into this issue when I tried to install **kmod-usb2**:
```
root@TPLINKAC1750:/etc/backup# opkg install kmod-usb2_4.9.124-1_mips_24kc.ipk
Installing kmod-usb2 (4.9.124-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb2:
 * 	kernel (= 4.9.124-1-0a60c6508dd4dd55f2b1728b63a404f0) * 	kernel (= 4.9.124-1-01d03f01348999520673f4931cedaac3) * 	kernel (= 4.9.124-1-01d03f01348999520673f4931cedaac3) * 	kernel (= 4.9.124-1-01d03f01348999520673f4931cedaac3) * 
 * opkg_install_cmd: Cannot install package kmod-usb2.
```
kmod-usb2 is needed by **lsusb**

**Comment by cshoredaniel** [comment]
Ah, are you building only the core and then using snapshots?  That won't work.  You need to either build everything you want and include it in the image, or you need to use snapshots build (which might already have the updated NUT code).

**Comment by malakingpusa** [comment]
Other notes:
I added options for **pollinterval** and **ignorelb** in the driver config but when i tried to read **/etc/nut/ups.conf**, this is what I get:
```
root@TPLINKAC1750:~# cat /etc/nut/ups.conf 
# Config file automatically generated from UCI config
[CP37]
driver = usbhid-ups
port = auto
serial = CRNGV2000016
offdelay = 60
ondelay = 30
pollfreq = 30
vendorid = 0764
productid = 0501
```
I need the **pollinterval** so I do not get stale data and the **ignorelb** so I can override the **battery.charge.low** parameter.

**Comment by cshoredaniel** [comment]
Ah, I missed adding those parameters to the options available driver.  By any chance can you submit a PR which adds missing parameters.   I got rid of the auto-parameter stuff (i.e. not specifically named) because I had various concerns about it, and because LuCI requires explicitly named parameters and I want the parameters documentation in the NUT package.

**Comment by malakingpusa** [comment]
@cshoredaniel submitted https://github.com/openwrt/packages/issues/7001 for this. thanks.

**Comment by malakingpusa** [comment]
Hi @cshoredaniel ,

Just to clarify, for now while waiting for the updated parameters for the driver, is it correct that I can now use the router by doing the following:

1. After boot up, kill process for **upsd**.
2. Do "**upsdrvctl start** _upsname_" (makes **/lib/nut/usbhid-ups** process) and then run **upsd**. The "**upsc** _upsname_" command will and should work at this point.
3. If time comes that I need to shutdown the UPS, I simply kill the **usbhid-ups** and **upsd** processes and finally send "**/lib/nut/usbhid-ups -a*** _upsname_ **-k**".

???

**Comment by cshoredaniel** [comment]
I believe part of your problem is https://github.com/openwrt/packages/issues/6966 (which I'm working on right now).  As a quick work around remove the leading 0 on any product id (middle number in xxxx/xxxx/* | \\ in /etc/hotplug.d/usb/30-libhid-... and also remove [ -d /var/run/nut ] from the same file, and you should need to do the killing of upsd and/or upsdrvctl start.

Also to FSD just ``upsmon -c shutdown`` and it should bring down all UPSes.

**Comment by malakingpusa** [comment]
Wow! Worked from reboot after doing the workaround you mentioned as I can see output from **upsc** command. As a result, **usbhid-ups** is now running as nut user and no longer as root.

I added another UPS and it can now detect and read status from both UPSes after reboot, of course I had to add the new UPS in the **/etc/config/nut_server**.

This is how the nut processes look now:
```
root@TPLINKAC1750:~# ps | egrep "nut|ups"
  558 nut       1436 S    /lib/nut/usbhid-ups -D -a CP37 -u nut
 1288 root      1100 S    /usr/sbin/upsmon -D
 1330 nut       1100 S    /usr/sbin/upsmon -D
 1617 nut       1044 S    /usr/sbin/upsd -D -u nut
 2030 root      1188 S    egrep nut|ups
```
Also was able to run the command ```/etc/init.d/nut-server stop && upsdrvctl shutdown```, it worked and below is the output:
```
root@TPLINKAC1750:~# /etc/init.d/nut-server stop && upsdrvctl shutdown
Network UPS Tools - UPS driver controller reboot-8011-g6bbb220255
Network UPS Tools - Generic HID driver 0.41 (reboot-8011-g6bbb220255)
USB communication driver 0.33
Using subdriver: CyberPower HID 0.4
Initiating UPS shutdown
Network UPS Tools - Generic HID driver 0.41 (reboot-8011-g6bbb220255)
USB communication driver 0.33
Using subdriver: CyberPower HID 0.4
Initiating UPS shutdown
```

Thanks for the help @cshoredaniel ! Just need that fix for the parameters so I get a reliable reading from the UPSes and avoid stale outputs.

**Comment by cshoredaniel** [comment]
@malakingpusa I'd recommend ``upsmon -c shutdown`` over ``/etc/init.d/nut-server stop && upsdrvctl shutdown`` as the former also properly shutsdown the device (e.g. filesystems etc).

But great news!

**Comment by malakingpusa** [comment]
@cshoredaniel here are the processes from a fresh reboot before trying ```upsmon -c shutdown```:
```
root@OpenWrt:~# ps | egrep "nut|ups"
  562 nut       1444 S    /lib/nut/usbhid-ups -D -a CP37 -u nut
 1296 root      1100 S    /usr/sbin/upsmon -D
 1311 nut       1100 S    /usr/sbin/upsmon -D
 1673 nut       1044 S    /usr/sbin/upsd -D -u nut
 1938 root      1188 S    egrep nut|ups
```
Then tried executing ```upsmon -c shutdown``` and here is what I got:
```
root@OpenWrt:~# upsmon -c shutdown
Network UPS Tools upsmon reboot-8011-g6bbb220255
Monitors UPS servers and may initiate shutdown if necessary.

usage: upsmon [OPTIONS]

  -c <cmd>	send command to running process
		commands:
		 - fsd: shutdown all master UPSes (use with caution)
		 - reload: reread configuration
		 - stop: stop monitoring and exit
  -D		raise debugging level
  -h		display this help
  -K		checks POWERDOWNFLAG, sets exit code to 0 if set
  -p		always run privileged (disable privileged parent)
  -u <user>	run child as user <user> (ignored when using -p)
  -4		IPv4 only
  -6		IPv6 only
```
And then I tried ```upsmon -c fsd```, command went through but UPS did not shutdown.
```
root@OpenWrt:~# upsmon -c fsd
Network UPS Tools upsmon reboot-8011-g6bbb220255
```
Here are the remaining processes after ```upsmon -c fsd```:
```
root@OpenWrt:~# ps | egrep "nut|ups"
  562 nut       1444 S    /lib/nut/usbhid-ups -D -a CP37 -u nut
 1668 nut       1044 S    /usr/sbin/upsd -D -u nut
 1966 root      1188 S    egrep nut|ups
```

**Comment by cshoredaniel** [comment]
@malakingpusa Is this with multiple UPSes or a single one? (working on a build now for the other changes so will test again).  It was working for me, but maybe I broke something?

**Comment by cshoredaniel** [comment]
@malakingpusa UPS takes about 20-30 seconds after last slave exits before UPS is shutdown and (it should) come back in about 10 seconds if UPS is still powered on.  Does that make a difference?

**Comment by ivanich** [comment]
Using blazer_usb nut driver and found that this PR brings https://github.com/openwrt/packages/pull/6897/files#diff-b43121d3cb6f04f9a4f58f93c7970813R150 option which is not available in blazer_usb thus it cannot start with the following error
Wed Sep 19 08:56:12 2018 daemon.info blazer_usb[3871]: Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (reboot-8069-ge8cbfedc72)
Wed Sep 19 08:56:12 2018 daemon.info blazer_usb[3871]:
Wed Sep 19 08:56:12 2018 daemon.info blazer_usb[3871]: Fatal error: 'pollfreq' is not a valid variable name for this driver.
Wed Sep 19 08:56:12 2018 daemon.info blazer_usb[3871]:

The second issue is permissions to /dev/bus/usb/001/00*
I can get it working with 2 steps:
- commenting out pollfreq from /etc/init.d/nut-server
- adding rw perms to  /dev/bus/usb/001/00*

I'm using latest master compiled from sources

**Comment by malakingpusa** [comment]
> 
> 
> @malakingpusa UPS takes about 20-30 seconds after last slave exits before UPS is shutdown and (it should) come back in about 10 seconds if UPS is still powered on. Does that make a difference?

hi @cshoredaniel , managed to explore this again after some serious load at the office.

while waiting for the parameters fix, just what was described here:
[If you wish to use a 'standard' NUT config just remove the symlinks in /etc/nut and replace them with regular NUT configuration files. ](https://openwrt.org/docs/guide-user/services/ups/software.nut#nut_server)

I still can query and send shutdown to UPS after that which is really an improvement.

Next step I am starting now on is to soak test the UPS to check if I won't get stale data errors over the weekend.

So far log looks good:
```
root@OpenWrt:~# tail -f /var/log/ups60.log 
2018-09-28 08:23:54 UPS: CP37 [OL] Battery Charge: 100% Runtime: 14880 seconds Load: 0 PID=1964
2018-09-28 08:24:54 UPS: CP37 [OL] Battery Charge: 100% Runtime: 14880 seconds Load: 0 PID=1964
2018-09-28 08:25:54 UPS: CP37 [OB DISCHRG] Battery Charge: 100% Runtime: 15420 seconds Load: 0 PID=1964
2018-09-28 08:26:54 UPS: CP37 [OB DISCHRG] Battery Charge: 100% Runtime: 14563 seconds Load: 0 PID=1964
2018-09-28 08:27:54 UPS: CP37 [OB DISCHRG] Battery Charge: 100% Runtime: 14563 seconds Load: 0 PID=1964
2018-09-28 08:28:54 UPS: CP37 [OL] Battery Charge: 100% Runtime: 14605 seconds Load: 0 PID=1964
2018-09-28 08:29:54 UPS: CP37 [OL] Battery Charge: 100% Runtime: 14202 seconds Load: 0 PID=1964
2018-09-28 08:30:54 UPS: CP37 [OL] Battery Charge: 100% Runtime: 14202 seconds Load: 0 PID=1964
2018-09-28 08:31:54 UPS: CP37 [OL] Battery Charge: 100% Runtime: 14116 seconds Load: 0 PID=1964
```

**Comment by cshoredaniel** [comment]
In case folks haven't seen it elsewhere: FYI I've posted PR: https://github.com/openwrt/packages/pull/7638 which ought to do must of what's now in master except the USB hotplug bits (as that's a new feature IMO).  If you can, please test and comment!

**Pull request merged**
