### PR TITLE
CGMiner: Add the package

### PR DESCRIPTION
**Pull request by qinfengling**
Cgminer is a multi-threaded multi-pool GPU, FPGA and CPU miner with ATI GPU
monitoring, (over)clocking and fanspeed support for bitcoin and derivative
coins. It can work out of box with Avalon Miner 6.0. You can choose other mines
if you like. It can support AvalonMiner nano 2,AvalonMiner 4 mini,Icarus miner
and ButterflyLabs miner now.

### CODE REVIEW

**Comment by bittorf** [comment]
please merge.

**Comment by xiangfu** [comment]
Signed-off-by Xiangfu Liu <xiangfu@openmobilefree.net>

**Comment by champtar** [comment]
hi @xiangfu 
we don't add package to 15.05 branch, it must be first in master before we can think about backporting

**Comment by xiangfu** [comment]
Hi Champtar

Yes. I didn't notice this is pull request on 15.05. sorry. will do it again on master branch. thanks.

Xiangfu

**Comment by qinfengling** [comment]
@champtar @xiangfu  I will try to pull a new one later.

**Comment by bittorf** [comment]
@qinfengling yes, please do so...

**Pull request closed without merging**
