### PR TITLE
Maintainer: Enrico Mioso <mrkiko.rs@gmail.com> Compile tested: Run tested:

### PR DESCRIPTION
**Pull request by mrkiko**
Remove ldbus package. Sorry guys.

### CODE REVIEW

**Comment by feckert** [comment]
@mrkiko ? why do you want to delete ldbus? If so please do this in a separate pull request

**Comment by feckert** [comment]
Commit https://github.com/openwrt/packages/pull/8622/commits/c1b4531c84869a40b90bd1aa8e1976d4d71f85c3 is already in https://github.com/openwrt/packages/pull/8621

**Comment by mrkiko** [comment]
OopS!! :) Sorry, I messed up with git.

Oh well - I was thinking to remove ldbus since I am not using it / checking regular updates.
Do you think I should leave it there? Any recommendation would be greatly apreciated.

**Comment by mrkiko** [comment]
@feckert I updated the pR:

**Pull request closed without merging**
