### PR TITLE
bind: add support for the 'rndc' utility

### PR DESCRIPTION
**Pull request by pprindeville**
See issue #14183 for a description.

### CODE REVIEW

**Comment by BKPepe** [comment]
I have one nitpick. Would it be possible to include in the commit message the same or similar to what is said in the issue?

**Comment by pprindeville** [comment]
> I have one nitpick. Would it be possible to include in the commit message the same or similar to what is said in the issue?

@BKPepe Done.

**Review by nmeyerhans — APPROVED** [review]
LGTM

**Comment by pprindeville** [comment]
Thanks!

**Pull request merged**
