### PR TITLE
i2pd: Add package

### PR DESCRIPTION
**Pull request by dangowrt**
Maintainer: @yangfl 
Compile tested: x86/generic, git HEAD
Run tested: x86/generic, git HEAD

Description:
I2P (Invisible Internet Protocol) is a universal anonymous network layer. All communications over I2P are anonymous and end-to-end encrypted, participants don't reveal their real IP addresses.

### CODE REVIEW

**Comment by yangfl** [comment]
Really? Why open another pr with the same issue?

**Comment by dangowrt** [comment]
@yangfl I just fixed the dependencies (ie. added 'boost' meta-package) and wanted to see if that fixes the travis issue. Now it gets killed because it takes too long to build boost...

**Comment by dangowrt** [comment]
@yangfl feel free to update your previous PR instead so I'll close this one (ie. add '+boost' to the package dependencies and fix the MAINTAINER line so it containes your full name and email address)

**Comment by yangfl** [comment]
ok updated

**Pull request closed without merging**
