### PR TITLE
glib2: update to 2.65

### PR DESCRIPTION
**Pull request by neheb**
Modified to use meson as upstream has abandoned autotools.

Added license information.

Cleaned up Makefile for consistency between packages.

Added hack to compile static libs.

Removed old patches and add new ones.

Removed BUILD_PARALLEL options. These are default with ninja/meson.

Removed gettext build dependencies. glib2 now includes its own solution.

Meson rpath issues were fixed. This can now come back.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tripolar 
Compile tested: ath79 arc700

ping @BKPepe since you reverted the previous one.

### CODE REVIEW

**Comment by neheb** [comment]
ping @yousong since I'm touching spice

ping @pnd10 since I'm touching gkrellmd

**Comment by yousong** [comment]
Please be more specific for the addition of nls.mk for spice.  I do not see how we "Needs it for uClibc-ng as a result of the glib2 change".

**Comment by neheb** [comment]
Needs it. Otherwise undefined reference to iconv functions.

**Comment by lucize** [comment]
tested on aarch64

**Comment by yousong** [comment]
> Needs it. Otherwise undefined reference to iconv functions.

This is going to be cumbersome if all Makefiles using glib2 will need to include nls.mk.  Generally, if B depends on C, A depends on B, we expect B will pull in C automatically for A, be it pkgconfig or whatever.

Ref: #11652

**Comment by neheb** [comment]
It really depends on the package. The ones that use pkgconf to grab the linker flags are affected.

**Comment by lucize** [comment]
with this I have 
`/home/build/staging/build_dir/hostpkg/gobject-introspection-1.60.2/tmp-introspect0o2umax8/Gio-2.0: symbol lookup error: /home/build/staging/build_dir/hostpkg/gobject-introspection-1.60.2/tmp-introspect0o2umax8/Gio-2.0: undefined symbol: g_memory_monitor_warning_level_get_type
`
I'll try to see if I can figure it out

**Comment by neheb** [comment]
What OS are you compiling on?

**Comment by lucize** [comment]
ubuntu 18.04, is something about a new feature GMemoryMonitor to monitor for low-memory, don't know where to search the problem atm

**Comment by lucize** [comment]
for test I tried 2.63.2 and it compiled 

somehow the package also searches libgio-2.0.so.0 in [...]/gio/modules/ if is present but then it fails with additional `libgio-2.0.so: undefined symbol: g_io_module_load`
also the package tries to link against [...]/lib and fails early if is not there
I'll do more research

**Comment by neheb** [comment]
I tried this on WSL (Ubuntu 18.04). Seems this is still somewhat broken...

```
mangix@x ~/d/openwrt (master) [1|0]> ldd staging_dir/hostpkg/lib/* | grep /usr
ldd: staging_dir/hostpkg/lib/cmake: not regular file
ldd: staging_dir/hostpkg/lib/gettext: not regular file
ldd: staging_dir/hostpkg/lib/gio: not regular file
ldd: staging_dir/hostpkg/lib/glib-2.0: not regular file
ldd: staging_dir/hostpkg/lib/libffi-3.2.1: not regular file
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f5ba55f0000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f4347400000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f46d8310000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f2a9e980000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fcbd1120000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f8ca7ab0000)
ldd: staging_dir/hostpkg/lib/libxslt-plugins: not regular file
ldd: staging_dir/hostpkg/lib/meson: not regular file
ldd: staging_dir/hostpkg/lib/pkgconfig: not regular file
ldd: staging_dir/hostpkg/lib/terminfo: not regular file
ldd: staging_dir/hostpkg/lib/vala-0.48: not regular file
```

**Comment by lucize** [comment]
I think that something is missing in meson as I tried building mesa with meson vs autotools
and with messon I get

```
WARNING: Library target 'GLESv1_CM' has 'name_prefix' set. Compilers may not find it from its '-lGLESv1_CM' linker flag in the 'glesv1_cm.pc' pkg-config file.
WARNING: Library target 'GLESv1_CM' has 'name_prefix' set. Compilers may not find it from its '-lGLESv1_CM' linker flag in the 'glesv1_cm-uninstalled.pc' pkg-config file.
WARNING: Library target 'GLESv2' has 'name_prefix' set. Compilers may not find it from its '-lGLESv2' linker flag in the 'glesv2.pc' pkg-config file.
WARNING: Library target 'GLESv2' has 'name_prefix' set. Compilers may not find it from its '-lGLESv2' linker flag in the 'glesv2-uninstalled.pc' pkg-config file.
```

```
Failed to load /usr/lib/xorg/modules/extensions/libglx.so: Error relocating /usr/lib/libGL.so.1:  O: initial
-exec TLS resolves to dynamic definition in /usr/lib/libGL.so.1
```

**Comment by neheb** [comment]
Updated to 2.65.0 and rebased.

**Comment by neheb** [comment]
Added patch to get rid of distutils host dependency.

**Comment by neheb** [comment]
Fixed host linking issues with rpath. This is ready.

**Comment by yousong** [comment]
> It really depends on the package. The ones that use pkgconf to grab the linker flags are affected.

Sorry, I can make guess that maybe pkg-config for glib2 will pull in things like `-liconv`?  There are many other packages also depends on glib2, only spice got this issue?

If it's glib2 pulling in iconv dependencies, is it possible to have glib2 depends on that and let those depending on glib2 just have it automatically?

**Comment by neheb** [comment]
glib2 already depends on libiconv. The issue is with the linker flags, not the dependencies.

**Comment by neheb** [comment]
```
/home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_arc700_gcc-9.3.0_uClibc/lib/gcc/arc-openwrt-linux-uclibc/9.3.0/../../../../arc-openwrt-linux-uclibc/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
make[8]: *** [Makefile:775: test_logging] Error 1
make[8]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common/tests'
make[7]: *** [Makefile:726: all] Error 2
make[7]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common/tests'
make[6]: *** [Makefile:459: all-recursive] Error 1
make[6]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common'
make[5]: *** [Makefile:391: all] Error 2
make[5]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common'
make[4]: *** [Makefile:536: all-recursive] Error 1
make[4]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3'
make[3]: *** [Makefile:445: all] Error 2
make[3]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3'
make[2]: *** [Makefile:63: /home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/.built] Error 2
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/feeds/packages/libs/spice'
time: package/feeds/packages/spice/compile#36.38#5.45#42.33
make[1]: *** [package/Makefile:113: package/feeds/packages/spice/compile] Error 2
make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:235: package/spice/compile] Error 2
```

**Comment by yousong** [comment]
> ```
> /home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_arc700_gcc-9.3.0_uClibc/lib/gcc/arc-openwrt-linux-uclibc/9.3.0/../../../../arc-openwrt-linux-uclibc/bin/ld: cannot find -liconv
> collect2: error: ld returned 1 exit status
> make[8]: *** [Makefile:775: test_logging] Error 1
> make[8]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common/tests'
> make[7]: *** [Makefile:726: all] Error 2
> make[7]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common/tests'
> make[6]: *** [Makefile:459: all-recursive] Error 1
> make[6]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common'
> make[5]: *** [Makefile:391: all] Error 2
> make[5]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common'
> make[4]: *** [Makefile:536: all-recursive] Error 1
> make[4]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3'
> make[3]: *** [Makefile:445: all] Error 2
> make[3]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3'
> make[2]: *** [Makefile:63: /home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/.built] Error 2
> make[2]: Leaving directory '/home/mangix/devstuff/openwrt/feeds/packages/libs/spice'
> time: package/feeds/packages/spice/compile#36.38#5.45#42.33
> make[1]: *** [package/Makefile:113: package/feeds/packages/spice/compile] Error 2
> make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
> make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:235: package/spice/compile] Error 2
> ```
> 
> edit; to clarify, that's without nls.mk

Thanks for the dump!  I think there are now two things to be done to improve it

 - Also skip building tests for spice-common
 - Patch pkg-config to automatically include search path for iconv or its stubs.

In my opinion, glib2 is used by so many packages that it would be too tedious to have to scatter that `$(ICONV_DEPENDS)` all over the tree.

**Comment by neheb** [comment]
> > ```
> 
> > /home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_arc700_gcc-9.3.0_uClibc/lib/gcc/arc-openwrt-linux-uclibc/9.3.0/../../../../arc-openwrt-linux-uclibc/bin/ld: cannot find -liconv
> 
> > collect2: error: ld returned 1 exit status
> 
> > make[8]: *** [Makefile:775: test_logging] Error 1
> 
> > make[8]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common/tests'
> 
> > make[7]: *** [Makefile:726: all] Error 2
> 
> > make[7]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common/tests'
> 
> > make[6]: *** [Makefile:459: all-recursive] Error 1
> 
> > make[6]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common'
> 
> > make[5]: *** [Makefile:391: all] Error 2
> 
> > make[5]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/subprojects/spice-common'
> 
> > make[4]: *** [Makefile:536: all-recursive] Error 1
> 
> > make[4]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3'
> 
> > make[3]: *** [Makefile:445: all] Error 2
> 
> > make[3]: Leaving directory '/home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3'
> 
> > make[2]: *** [Makefile:63: /home/mangix/devstuff/openwrt/build_dir/target-arc_arc700_uClibc/spice-0.14.3/.built] Error 2
> 
> > make[2]: Leaving directory '/home/mangix/devstuff/openwrt/feeds/packages/libs/spice'
> 
> > time: package/feeds/packages/spice/compile#36.38#5.45#42.33
> 
> > make[1]: *** [package/Makefile:113: package/feeds/packages/spice/compile] Error 2
> 
> > make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
> 
> > make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:235: package/spice/compile] Error 2
> 
> > ```
> 
> > 
> 
> > edit; to clarify, that's without nls.mk
> 
> 
> 
> Thanks for the dump!  I think there are now two things to be done to improve it
> 
> 
> 
>  - Also skip building tests for spice-common

Sure

> 
>  - Patch pkg-config to automatically include search path for iconv or its stubs.

Eh no. --disable-nls is passed for a reason.

> 
> 
> 
> In my opinion, glib2 is used by so many packages that it would be too tedious to have to scatter that `$(ICONV_DEPENDS)` all over the tree.

Last I checked this was actually the only problematic package: I can check again.

**Comment by yousong** [comment]
> > * Patch pkg-config to automatically include search path for iconv or its stubs.
> 
> Eh no. --disable-nls is passed for a reason.
> 
> >

Only produce those search paths when `-liconv` or `-lintl` is to be output from pkg-config call.

**Comment by neheb** [comment]
There's no reason to patch pkg-config at all. Everything is working as intended.

**Comment by neheb** [comment]
Merging now that the whole meson mess was fixed.

I expect some packages to break. I will fix as needed.

**Pull request merged**
