### PR TITLE
msgpack-c: Update to 6.0.0

### PR DESCRIPTION
**Pull request by 1715173329**
Maintainer: tmate-ssh-server @aparcar / me
Compile tested: rockchip/armv8
Run tested: nanopi-r2s

Description:
- msgpack-c: Update to [6.0.0](https://github.com/msgpack/msgpack-c/releases/tag/c-6.0.0)
  Removed 010-no-gtest.patch as upstream no longer detects it.

- tmate: fix build against msgpack-c 6.0
  This patch is taken from https://git.alpinelinux.org/aports/commit/?id=f923597f4bdea424dc28b1d026269df060596fac

- tmate-ssh-server: fix build against msgpack-c 6.0
  This patch is taken from https://git.alpinelinux.org/aports/commit/?id=f923597f4bdea424dc28b1d026269df060596fac

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]
Looks OK. 👍

**Comment by aparcar** [comment]
Im seeing some CI failures?

**Comment by BKPepe** [comment]
Not related to this PR, though and it happened even in the past. CI tries to install two same packages libavahi, but once without dbus support and at the same time with the support and of course it is going to fail.

**Comment by 1715173329** [comment]
Yep, thanks @BKPepe.

And we should remove arc from build test, the last target based on it, arches38, is now source-only. There's no new SDK for it.

powerpc_8540 should be renamed to powerpc_8548 as well: https://github.com/openwrt/openwrt/commit/2cad88b99fdae9766de84e6c1cb56f111eb53748

**Comment by hnyman** [comment]
@1715173329 

msgpack-c needs help to compile with cmake 4.1.2. Currently broken.

Either version bump to 7.0.0 or at least the backport of upstream commit https://github.com/msgpack/msgpack-c/commit/8957d6ec075b8d83a733aeee3c4a61a1a2a965ca

Ps. Same cmake 4 compatibility issue goes probably for several other packages that you are involved with.

**Comment by 1715173329** [comment]
Thanks for the heads up, I will check them later.

**Pull request merged**
