### PR TITLE
strongswan: swanctl: add support for replay window

### PR DESCRIPTION
**Pull request by tiagogaspar8**
Maintainer: Philip Prindeville <philipp@redfish-solutions.com>, Noel Kuntze <noel.kuntze@thermi.consulting>
Compile tested: Archer C7 v4 on latest master
Run tested: Archer C7 v4 on latest master

Description:

Add support for replay window configuration in UCI.

### CODE REVIEW

**Review by pprindeville — APPROVED** [review]
LGTM

**Comment by tiagogaspar8** [comment]
Hey everyone,

Can we merge this? This is just a simple config option implementation.

Thanks!

**Comment by feckert** [comment]
Please bump the PKG_RELEASE.

**Comment by tiagogaspar8** [comment]
Each time this happens I get a little bit more disappointed with myself...

Thanks for the review Florian

**Comment by feckert** [comment]
Thanks merged!
That's what reviews are for :-)

**Pull request merged**
