### PR TITLE
shadowsocks-libev：Fixed in 'mbedtls 3.6 version' compilation failure …

### PR DESCRIPTION
**Pull request by zxlhhyccc**
…issue

The added patch is available in 'mbedtls 3.6 version'.

thank @msdos03 assist！

### CODE REVIEW

**Comment by msdos03** [comment]
I think we should consider whether 
`*clen += tlen;` should be removed.
That seems to be redundant after this change,
but I'm not sure.

**Comment by zxlhhyccc** [comment]
@msdos03 I think it's better not to move.

**Comment by msdos03** [comment]
> @msdos03 Delete `*clen += tlen; ` Can you test it?

I have tested it.
First, after deleting this line, it still works fine.
Second, I replaced this line with `printf("mlen: %d, tlen: %d, clen: %d\n", mlen, tlen, *clen);`
and get following output
```
mlen: 7, tlen: 16, clen: 23
mlen: 2, tlen: 16, clen: 18
mlen: 1918, tlen: 16, clen: 1934
mlen: 2, tlen: 16, clen: 18
mlen: 7, tlen: 16, clen: 23
mlen: 2, tlen: 16, clen: 18
mlen: 1895, tlen: 16, clen: 1911
mlen: 2, tlen: 16, clen: 18
mlen: 7, tlen: 16, clen: 23
mlen: 2, tlen: 16, clen: 18
mlen: 1782, tlen: 16, clen: 1798
```
The original *clen returned by `mbedtls_cipher_auth_encrypt_ext` equals to mlen + tlen, so I think this line is redundant.
I think reserving this line will cause potential out of bounds error.

**Comment by zxlhhyccc** [comment]
@msdos03 You mean 'mlen' and 'clean'  will cause potential out of bounds error？

**Comment by msdos03** [comment]
> @msdos03 You mean `mlen` and `clean` will cause potential out of bounds error？

Yes, what's your opinion?

**Comment by zxlhhyccc** [comment]
@msdos03 The point is I don't know how they work.What is their working status after deleting them?

**Comment by msdos03** [comment]
> @msdos03 The point is I don't know how they work.What is their working status after deleting them?

mlen is the plain text input length, clen is the cipher text output length, tlen is the authentication tag length which only present in cipher text. The old function use seperate cipher text and authentication tag buffer, but the new function use one buffer for both things. So the old function returns only cipher text length to clen, but the new function returns cipher text + authentication tag length to clen.

**Comment by zxlhhyccc** [comment]
@msdos03 `mlen: 1895` and `clen: 1911` is bounds error？

**Comment by msdos03** [comment]
> @msdos03 `mlen: 1895` and `clen: 1911` is bounds error？

No, `*clen += tlen;` is supposed to make clen equals to mlen + tlen, because the old function only returns cipher text lenth which equals to plain text length (mlen), but what the new function returns is already cipher text length + tag tength (mlen + tlen). If we still add tlen to it, clen will be larger than the whole buffer, which may cause potential bounds error.

**Comment by zxlhhyccc** [comment]
@msdos03 
Patch changed to the following?
````
--- a/src/aead.c
+++ b/src/aead.c
@@ -178,9 +178,8 @@ aead_cipher_encrypt(cipher_ctx_t *cipher
     case AES192GCM:
     case AES128GCM:
 
-        err = mbedtls_cipher_auth_encrypt(cipher_ctx->evp, n, nlen, ad, adlen,
-                                          m, mlen, c, clen, c + mlen, tlen);
-        *clen += tlen;
+        err = mbedtls_cipher_auth_encrypt_ext(cipher_ctx->evp, n, nlen, ad, adlen,
+                                          m, mlen, c, mlen + tlen, clen, tlen);
         break;
     case CHACHA20POLY1305IETF:
         err = crypto_aead_chacha20poly1305_ietf_encrypt(c, &long_clen, m, mlen,
````

**Comment by zxlhhyccc** [comment]
@msdos03 `*clen += tlen;` change `clen += mlen + tlen;` what will happen?

**Comment by zxlhhyccc** [comment]
@msdos03 I took a look at it. You had a point. I changed the patch.

**Comment by zxlhhyccc** [comment]
@msdos03 This pr is closed, I resubmit pr...

**Pull request closed without merging**
