### PR TITLE
python3: Update to 3.8.3, refresh patches

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me, @commodo 
Compile tested: armvirt-64, 2020-05-17 snapshot sdk
Run tested: none

Description:
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
@sdwalker I haven't been getting any uscan emails for updates to this package. Is there anything I can do to help fix this?

**Comment by commodo** [comment]
for python at least a run-test would be nice;

**Comment by jefferyto** [comment]
I'm not sure what instability you would expect from a point release, but I have done as you asked:

Run tested: armvirt-64 (qemu), 2020-05-17 snapshot sdk

**Comment by sdwalker** [comment]
> 
> 
> @sdwalker I haven't been getting any uscan emails for updates to this package. Is there anything I can do to help fix this?

The watch file has been corrected to look at the tarballs linked from https://www.python.org/downloads/source/ instead of using https://www.python.org/ftp/python/ directly.

**Comment by jefferyto** [comment]
@sdwalker Thanks!

**Pull request merged**
