### PR TITLE
treewide: fix service status

### PR DESCRIPTION
**Pull request by ynezz**
Maintainer:  @danwrt, @dibdot, @liudf0716, @mhaas
Compile tested: n/a
Run tested: n/a
Description:

  Fix breaking change introduced in the main tree with a commit
  openwrt/openwrt@7519a36774ca ("base-files,procd: add generic service status") where the
  old service `status` function doesn't work anymore and needs to be
  renamed to `status_service`.

### CODE REVIEW

**Comment by karlp** [comment]
This is _exactly_ why I said it was wrong.   What about non-procd services?  You're breaking them, and the user provided final script should _always_ be able to override things!

**Comment by ynezz** [comment]
> What about non-procd services? You're breaking them

Good, I finally understand what you've meant, should be fixed.

> Can't we rework the procd service status thing to simply call the user provided status() if it exists?

Wouldn't it be confusing, why is `status` so special? I mean, there're `stop_service` and `start_service` callbacks, but for `status` I would expect `status_service` and not just `status`.

**Comment by jow-** [comment]
Good question, I think it boils down to the fact that so far we alwasys avoided to change the init script logic in such a way that existing implementations break.

**Comment by neheb** [comment]
Is this ready?

On a side note, I tried converting haveged to price but failed. Have not tried recently as urngd works better.

**Comment by hnyman** [comment]
> On a side note, I tried converting haveged to procd but failed. 

Which specific problem did you run into?  I did that conversion as 4f717a6f65 and have so far noticed no special problems.

**Comment by neheb** [comment]
From looking at your commit, my problem was that I quoted all of the parameters. I recently did this with transmission and broke it (since fixed).

It conflicts with shellcheck which says to quote it.

**Comment by dibdot** [comment]
@ynezz meanwhile I've fixed this issue for adblock, banIP & travelmate in separate commits.

**Comment by dibdot** [comment]
@ynezz Please note, that your change introduce another problem: the "EXTRA_HELP" in rc.common overwrites available EXTRA_COMMANDS! E.g. dropbear no longer prints the available EXTRA_COMMAND "killclients" ...

**Comment by neheb** [comment]
ping @ynezz 

Please rebase.

**Comment by ynezz** [comment]
> @ynezz Please note, that your change introduce another problem: the "EXTRA_HELP" in rc.common overwrites already available EXTRA_HELP! E.g. dropbear no longer prints the available EXTRA_HELP/COMMAND "killclients" ... the command itself works like before.

@dibdot should be fixed in 953c27df315ded7fae45daba0229ced4309e4baa

**Pull request merged**
