### PR TITLE
pps-tools: install timepps.h in location specified by RFC 2783

### PR DESCRIPTION
**Pull request by sdwalker**
Upstream commit: dc78a6a8aad7688a7277c110d2aee8e06887b69d

Signed-off-by: Stephen Walker <stephendwalker+github@gmail.com>

### CODE REVIEW

**Comment by champtar** [comment]
@wigyori ?

**Comment by diizzyy** [comment]
@wigyori Ping?

**Comment by champtar** [comment]
As @wigyori doesn't seems active anymore,
@sdwalker if you want to send a PR to be maintainer of pps-tools I would gladly accept it.
Closing for now.

**Comment by wigyori** [comment]
This went off of my radar for a long time. If @sdwalker doesn't take it over I'm happy to keep owning this - whichever you prefer @champtar 

-w-

**Comment by champtar** [comment]
Hi @wigyori,
If you still have have time/want to maintain this package go for it
I was just trying to reduce the PR backlog, and you didn't look very active.

I can't reopen the PR as @sdwalker deleted his repo (or branch) apparently

**Pull request closed without merging**
