### PR TITLE
python3: Update to 3.10.4

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me
Compile tested: armvirt-32, 2022-03-27 snapshot sdk
Run tested: none

Description:
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
What a strange failure that I can't seem to reproduce locally. Maybe once the host stuff gets fixed this will go away too.

**Comment by jefferyto** [comment]
The CI errors are because of openwrt/gh-action-sdk@v4, the fix is https://github.com/openwrt/gh-action-sdk/pull/7.

**Comment by neheb** [comment]
Interesting. Thought it was something I did.

**Comment by hnyman** [comment]
Now the CI seems to work again. (and also this shows green ;-)

**Pull request merged**
