### PR TITLE
stubby: fix typo

### PR DESCRIPTION
**Pull request by salim-b**
Signed-off-by: Salim B <salim@posteo.de>

### CODE REVIEW

**Comment by feckert** [comment]
Please add a sign off and also add a valid commit header `stubby: fix typo`

**Comment by salim-b** [comment]
> Please add a sign off and also add a valid commit header `stubby: fix typo`

Is it ok now?

**Comment by feckert** [comment]
No sorry. You have to edit your [commit](https://github.com/openwrt/packages/pull/13150/commits/b6ba8298710605f4034cf169e3ccdd81d7f4d6e7) and not the pull request.

**Comment by salim-b** [comment]
> No sorry. You have to edit your [commit](https://github.com/openwrt/packages/pull/13150/commits/b6ba8298710605f4034cf169e3ccdd81d7f4d6e7) and not the pull request.

Ok, I tried to do this (`git commit --amend`)... but it just resulted in more commits 😅 If it's not fine now, I give up.

**Comment by neheb** [comment]
Merged separately.

**Pull request closed without merging**
