### PR TITLE
collectd: add uci config support

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @hnyman @jow-
Compile tested: no compilation needed only script changes
Run tested: x86_64, APU3, OpenWrt master

Description:
Add uci support to collectd. I was inspired by the uci of luci-app-statistics. But not all modules are ported yet. That's the first PR.

### CODE REVIEW

**Comment by feckert** [comment]
@jow @hnyman ping

**Comment by hnyman** [comment]
Does does this work ok together with luci-statistics?

**Comment by feckert** [comment]
Not out of the box we have to convert the luci-app-statistics uci to the new uci config of the new collectd uci binding. But I think that is no Problem. There are only smal changes I have made. Normaly only naming. For now luci-app-statistics could hijack this package as before.

**Comment by neheb** [comment]
I would run the init script through shellcheck.

**Comment by feckert** [comment]
@neheb thanks for your feedback
I have update the shellcheck hints.

**Comment by feckert** [comment]
I am not sure if we should have /etc/collectd.conf include because this is referenced as alt_config_file in the new uci default config. Any advice?

**Comment by feckert** [comment]
@neheb @hnyman could we give them a try? If yes I would like to merge this.

**Pull request merged**
