### PR TITLE
lpeg: Update to 1.0.1

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @srdgame 
Compile tested: ramips

### CODE REVIEW

**Comment by karlp** [comment]
have you tested compatibility of this with the various packages that use lpeg?

**Comment by neheb** [comment]
git grep -i lpeg shows no depending packages.

**Comment by karlp** [comment]
ahh the joy of lua.  None of them need to declare the dependencies.  If you've  not found or used anything that needs lpeg, please leave it alone.

**Comment by neheb** [comment]
never getting merged

**Pull request closed without merging**
