### PR TITLE
fwknop: Update to 2.6.10

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jp-bennett 
Compile tested: ipq806x

### CODE REVIEW

**Comment by lucize** [comment]
@neheb sorry, did you forget to bump package version ?

**Comment by jp-bennett** [comment]
I'm hoping to be able to run test this this weekend, then I'll also sign off.

**Comment by jp-bennett** [comment]
This appears to be an incomplete patch.  See #6983

**Comment by neheb** [comment]
Correct. Will close.

**Pull request closed without merging**
