### PR TITLE
apfree_wifidog: Add apfree_wifidog package

### PR DESCRIPTION
**Pull request by liudf0716**
Maintainer: Dengfeng Liu 
Compile tested: ar71xx,LEDE 17.01
Run tested: ar71xx,LEDE 17.01

Description:
Add a package for apfree_wifidog, which is enhanced wifidog and continuous maintenance.
its github address is 
https://github.com/liudf0716/apfree_wifidog

This package depends latest libevent 2.1.8-stable, which  PR is 

https://github.com/lede-project/source/pull/837

Signed-off-by: Dengfeng Liu <liudengfeng@kunteng.org>

### CODE REVIEW

**Comment by KazukiShimada** [comment]
Thanks, Dengfeng Liu.

Dear Comitters.
I hope you have a look and merge this if it's OK.
Thanks in advance.

**Comment by liudf0716** [comment]
@KazukiShimada  thanks for your supporting

**Comment by Tr4cer0ute** [comment]
Great project.

**Comment by liudf0716** [comment]
@Tr4cer0ute thanks

**Pull request closed without merging**
