### PR TITLE
luaposix: add missing libs to .ipk

### LINKED ISSUE #829: luaposix: module 'posix.deprecated' not found
luaposix module fails to load on current trunk.

```
root@eg-018C06:/# opkg list-installed | grep posix
luaposix - v33.2.1-1
root@eg-018C06:/# lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)
> require("posix")
/usr/lib/lua/posix.lua:40: module 'posix.deprecated' not found:
	no field package.preload['posix.deprecated']
	no file './posix/deprecated.lua'
	no file '/usr/share/lua/posix/deprecated.lua'
	no file '/usr/share/lua/posix/deprecated/init.lua'
	no file '/usr/lib/lua/posix/deprecated.lua'
	no file '/usr/lib/lua/posix/deprecated/init.lua'
	no file './posix/deprecated.so'
	no file '/usr/lib/lua/posix/deprecated.so'
	no file '/usr/lib/lua/loadall.so'
	no module 'posix.deprecated' in file '/usr/lib/lua/posix.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/posix.lua:40: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: ?
> 
```

### PR DESCRIPTION
**Pull request by mstorchak**
Fixes #829 
Signed-off-by: Maxim Storchak <m.storchak@gmail.com>

### CODE REVIEW

**Comment by karlp** [comment]
I can't even actually build this at the moment, after pulling an update.

```
make[4]: Entering directory `/home/karlp/src/openwrt-trunk-upstream/build_dir/target-mips_34kc_uClibc-0.9.33.2/luaposix-release-v33.2.1'
depbase=`echo ext/posix/posix.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile ccache_cc -DHAVE_CONFIG_H -I.   -I ./ext/include -I ./ext/posix -D_XOPEN_SOURCE=700 -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include    -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -DLUA_USE_LINUX -fpic -std=gnu99  -MT ext/posix/posix.lo -MD -MP -MF $depbase.Tpo -c -o ext/posix/posix.lo ext/posix/posix.c &&\
mv -f $depbase.Tpo $depbase.Plo
OpenWrt-libtool: compile:  ccache_cc -DHAVE_CONFIG_H -I. -I ./ext/include -I ./ext/posix -D_XOPEN_SOURCE=700 -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -DLUA_USE_LINUX -fpic -std=gnu99 -MT ext/posix/posix.lo -MD -MP -MF ext/posix/.deps/posix.Tpo -c ext/posix/posix.c  -fPIC -DPIC -o ext/posix/.libs/posix.o
/bin/sh ./libtool  --tag=CC   --mode=link ccache_cc   -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -DLUA_USE_LINUX -fpic -std=gnu99  -module -avoid-version -lcrypt   -lrt   -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib  -o ext/posix/posix.la -rpath /usr/lib/lua/5.1 ext/posix/posix.lo   
OpenWrt-libtool: link: ccache_cc -shared  -fPIC -DPIC  ext/posix/.libs/posix.o   -lcrypt -lrt -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/karlp/src/openwrt-trunk-upstream/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib  -Os -mno-branch-likely -mips32r2 -mtune=34kc -msoft-float -mips16 -minterlink-mips16   -Wl,-soname -Wl,posix.so -o ext/posix/.libs/posix.so
ext/posix/.libs/posix.o: In function `Putime':
posix.c:(.text+0x565e): warning: the use of OBSOLESCENT `utime' is discouraged, use `utimes'
OpenWrt-libtool: link: ( cd "ext/posix/.libs" && rm -f "posix.la" && ln -s "../posix.la" "posix.la" )
test -d ./doc || mkdir ./doc
/usr/bin/ldoc -c build-aux/config.ld -d /home/karlp/src/openwrt-trunk-upstream/build_dir/target-mips_34kc_uClibc-0.9.33.2/luaposix-release-v33.2.1/doc .
lua: /usr/share/lua/5.1/ldoc.lua:18: module 'pl.class' not found:
	no field package.preload['pl.class']
	no file './pl/class.lua'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/share/lua/5.1/pl/class.lua'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/share/lua/5.1/pl/class/init.lua'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/lib/lua/5.1/pl/class.lua'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/lib/lua/5.1/pl/class/init.lua'
	no file './pl/class.so'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/lib/lua/5.1/pl/class.so'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/lib/lua/5.1/loadall.so'
	no file './pl.so'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/lib/lua/5.1/pl.so'
	no file '/home/karlp/src/openwrt-trunk-upstream/staging_dir/host/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/share/lua/5.1/ldoc.lua:18: in main chunk
	[C]: ?
make[4]: *** [doc/classes/posix.curses.chstr.html] Error 1
make[4]: Leaving directory `/home/karlp/src/openwrt-trunk-upstream/build_dir/target-mips_34kc_uClibc-0.9.33.2/luaposix-release-v33.2.1'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/karlp/src/openwrt-trunk-upstream/build_dir/target-mips_34kc_uClibc-0.9.33.2/luaposix-release-v33.2.1'
make[2]: *** [/home/karlp/src/openwrt-trunk-upstream/build_dir/target-mips_34kc_uClibc-0.9.33.2/luaposix-release-v33.2.1/.built] Error 2
make[2]: Leaving directory `/home/karlp/src/owrt-packages2/lang/luaposix'
make[1]: *** [package/feeds/packages/luaposix/compile] Error 2
make[1]: Leaving directory `/home/karlp/src/openwrt-trunk-upstream'
make: *** [package/luaposix/compile] Error 2
karlp@pojak:~/src/openwrt-trunk-upstream (eg200)$
```

It looks to me like it's trying to use a host ldoc?

**Comment by mstorchak** [comment]
Hm.. maybe. I have
```
checking for ldoc... false
```
on my host, and it builds fine. I'll check what can be done here...

**Comment by karlp** [comment]
Seems I installed ldoc while trying to build it locally.  There's a bit in local.mk that does different things if you have ldoc or not.  Ideally the openwrt package should just not even try and build the docs, but I can't figure out how to do that form their multi stage pile of autotooling cruft.

But it's definitely finding the wrong ldoc.  (I think this patch as submitted is fine, but this discussion should be moved to another ticket)

**Comment by karlp** [comment]
Confirmed however, this fixes the original issue. :+1:

**Comment by champtar** [comment]
@karlp if it's all ok maybe you can merge :)

**Comment by karlp** [comment]
Indeed I can! I sometimes forget that :)  Merged via rebase in 61a0a47bb6e5ba5eb5c7510e1796c9b8b234241e

**Pull request closed without merging**
