### PR TITLE
zerotier: update to 1.8.2

### PR DESCRIPTION
**Pull request by mwarning**
Signed-off-by: Moritz Warning <moritzwarning@web.de>

Maintainer: me
Compile tested: ath79/generic, OpenWrt master
Run tested: not tested

Update und switch back to release source package.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Please mention in the commit message that you changed the download source.

**Comment by mwarning** [comment]
done, since this is a patch release, a run test should not be necessary.

**Comment by KA2107** [comment]
Looks like ZeroTier 1.8.3 has been released. Thank you.
https://github.com/zerotier/ZeroTierOne/blob/master/RELEASE-NOTES.md

**Comment by mwarning** [comment]
fyi https://github.com/openwrt/packages/pull/17187

**Pull request merged**
