### PR TITLE
shairport-sync: update to latest version

### PR DESCRIPTION
**Pull request by Noltari**
- update to latest (2.4.1) version
- add support for config files
- switch uci to config files

Based on: https://github.com/openwrt/packages/pull/1815

Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

### CODE REVIEW

**Comment by thess** [comment]
@Noltari - Thanks for this work. I do prefer keeping the uci support integrated also.
A couple of items that I thought should be included in this submission would be to use polarssl instead of openssl (config option) and to remove the MAINTAINER tag and put both our names as PKG_MAINTAINER (comma separated). Once that is done (by either of us), I will merge this update.

**Comment by Noltari** [comment]
I'm currently at work, so I can't not test this or update the pull request until I get home, but I think these are the changes you requested:
https://gist.github.com/Noltari/ecce35b25df0572639cf

**Comment by Noltari** [comment]
Maybe it would be better to provide two build variants and default to polarssl, since it's smaller than openssl:
https://gist.github.com/Noltari/2381c8b14a62b8a24de3
I think this option is better. What do you think?

**Comment by Noltari** [comment]
Okay, I've updated the PR with the changes proposed in the variants version.
@thess do you agree with these changes?

**Comment by thess** [comment]
Thanks again for doing the heavy lifting -  I'll merge this tomorrow after I get a chance to try out something. Good stuff

**Comment by Noltari** [comment]
Ok no problem, but remember that dbus is currently broken, so if you're going to test this you need to revert it to v1.9.14:
https://github.com/openwrt/packages/issues/1821

**Comment by thess** [comment]
OK good - I'll mege this now. I do have an update that makes avahi no longer a dependency. Also, I really don't think we need both an openssl and polarssl build always. I was going to make openssl an option for private builds only.I'll post the PR in a  couple days for you guys to comment on.

**Pull request merged**
