### PR TITLE
vim: update to 9.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
https://www.vim.org/vim90.php

Maintainer: @ratkaj
Runtested: Linksys E8450

### CODE REVIEW

**Comment by neheb** [comment]
Personally I'd rather see neovim here but 🤷

**Comment by PolynomialDivision** [comment]
> Personally I'd rather see neovim here but shrug

Why don't you add it? Just add a PROVIDES:=vim to both packages?

**Comment by jmarcet** [comment]
I've had to add two deps to build vim-fuller:

```
diff --git a/utils/vim/Makefile b/utils/vim/Makefile
index a88759bd2..0c91775f8 100644
--- a/utils/vim/Makefile
+++ b/utils/vim/Makefile
@@ -48,6 +48,7 @@ endef
 
 define Package/vim-fuller
   $(call Package/vim/Default)
+  DEPENDS:=+libncursesw +libsodium
   TITLE+= (Big)
   PROVIDES:=vim vim-full
   CONFLICTS:=vim vim-full
```

**Comment by PolynomialDivision** [comment]
@jmarcet Can you try again? I also tried to add `--without-tlib=ncursesw` but this did not work. Do you have some special config that uses ncursesw?

https://www.linuxfromscratch.org/blfs/view/svn/postlfs/vim.html

**Pull request merged**
