### PR TITLE
Remove incorrect use of PKG_SHA256SUM

### PR DESCRIPTION
**Pull request by zorun**
Maintainers: @lynxis @dibdot (please ACK)
Compile tested: ar71xx LEDE c19381dfca92a2eb80d35f294515a777da2cb7be

Description:

OpenWRT/LEDE only understands the PKG_MD5SUM variable, and detects if the
hash is e.g. SHA256 by looking at the length of the hash.  See https://wiki.openwrt.org/doc/devel/packages#buildpackage_variables

This affects libs/libmicrohttpd, mail/ssmtp and utils/mc.

Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>

### CODE REVIEW

**Comment by thess** [comment]
No need to bump PKG_RELEASE for _mc_ and _ssmtp_ - package binaries have not changed.

**Comment by zorun** [comment]
Indeed, fixed.

**Comment by lynxis** [comment]
@zorun @thess I plan to put this on the lede-dev ml. I like to have a clear move to the sha256sum instead of reusing md5sum variable. But let discuss this on the lede-dev list, will send a mail tomorrow.

**Comment by dibdot** [comment]
@zorun thanks for bringing this up!
@thess @zorun it's odd to me to save a sha256 hash in a variable called "pkg_md5sum" ... either we are going back to bad old md5sum or we enhance the build system to accept a "pkg_sha256sum" as well.

**Comment by champtar** [comment]
Hi all,
no need to wait for a patch for both OpenWrt and LEDE
merging this now so we check source hash again

**Comment by lynxis** [comment]
I'm quite unhappy about this commit.I jut found out it breaks the support of libmicrohttpd for the 15.05 openwrt branch.

**Comment by champtar** [comment]
???
@lynxis this commit is in master branch, how can this break 15.05 ?

**Pull request merged**
