### PR TITLE
python3: update to version 3.7.4

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @jefferyto , @commodo 
Compile tested: Turris MOX, cortexa53, OpenWrt master
Run tested: Turris MOX, cortexa53, OpenWrt master

Description:
- Update setuptools to 40.8.0
- Update pip to 19.0.3
- Refreshed patches
Two patches are no necessary as they are included in this release

### CODE REVIEW

**Comment by commodo** [comment]
Thanks :)

**Comment by BKPepe** [comment]
@jefferyto is this ok with you?

**Comment by BKPepe** [comment]
@commodo can you please look at it again? @jefferyto may I get your approval as well to merge it?

**Comment by commodo** [comment]
Thanks again :)

**Pull request merged**
