### PR TITLE
open-iscsi: add package open-iscsi

### PR DESCRIPTION
**Pull request by lucize**
iscsi initiator utilities

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Maintainer: me 
Tested x86
 depends on #11830 and https://github.com/openwrt/openwrt/pull/2918

### CODE REVIEW

**Comment by lucize** [comment]
@stintel I saw in the issues section that you too are interested in this

**Comment by stintel** [comment]
> @stintel I saw in the issues section that you too are interested in this

Remind me where exactly you saw that?

**Comment by lucize** [comment]
@stintel 
https://github.com/open-iscsi/open-iscsi/issues/193

**Comment by stintel** [comment]
> @stintel
> [open-iscsi/open-iscsi#193](https://github.com/open-iscsi/open-iscsi/issues/193)

Ah right. I thought you meant OpenWrt related. I am running a lot of machines with Gentoo Hardened + musl, that's what I opened that issue for. I have no interest in running open-iscsi on OpenWrt.

**Comment by micmac1** [comment]
It's a good package to include in my opinion. Don't have any use for it myself. But lots of people use iSCSI with their NAS boxes. So there's a good argument to be made to have it in OpenWrt as well. Thanks!

**Comment by micmac1** [comment]
Maybe look into Gentoo's patches. They have at least two that seem to smooth things over with musl:

open-iscsi-2.0.874-musl-ethtool-compat.patch
open-iscsi-2.0.874-musl-fixes.patch

[Link](https://github.com/gentoo/gentoo/tree/master/sys-block/open-iscsi/files)

Maybe they have some interesting patches for the related packages as well (open-isns or what have you).

**Comment by micmac1** [comment]
Alpine also does some patching for musl: [Link](https://git.alpinelinux.org/aports/tree/main/open-iscsi?h=master)

**Comment by lucize** [comment]
@micmac1 I'll look into the patches, from what I tested seems to work as it should, I have only the procd init script left, but anyway it depends on kmod that from experience it will take a while to go in

**Comment by lucize** [comment]
using procd and issuing iscsiadm -k 0 crashes the whole system, can't get a trace, nothing is showing in the console so I made a classic script.
for sure the init.d script it can be better, please advise
at shutdown it doesn't check for mounted targets, I'll try to make something to detect iscsi mounted devices

**Comment by lucize** [comment]
added check for mounted iscsi partition and try to unmount them on stop also some fedora patches
procd still crashes the whole system, not sure whos is to blame for this

**Comment by neheb** [comment]
Please rebase

**Comment by neheb** [comment]
```
WARNING: Makefile 'package/feeds/packages/open-iscsi/Makefile' has a dependency on 'kmod-iscsi-initiator', which does not exist
```

**Comment by lucize** [comment]
yes, is unusable without the kmod, there is a PR open in base

**Comment by lucize** [comment]
@neheb this can go in now

**Pull request merged**
