### PR TITLE
rp-pppoe: Add back from oldpackages with build fixes and enhanced pac…

### PR DESCRIPTION
**Pull request by dfc-d**
…kaging

Add back from oldpackages with fixes for build errors and UCIfication
(for future LuCI app).

NOTE: Untested packages have been marked with @BROKEN.  This can
be undone of others report success with the relay and sniffer

Signed-off-by: Daniel Dickinson <openwrt@daniel.thecshore.com>

### CODE REVIEW

**Comment by dfc-d** [comment]
I have the LuCI app for this for which I will issue a pull request soon.

**Comment by dfc-d** [comment]
I forgot to mention I pushed a rebase removing the client per Jo's comment, and by default (unless @BROKEN) only building the server.

**Comment by dfc-d** [comment]
I've pushed some default configs I've been using that give a completely working pppoe-server, once /etc/config/pppoe is configured (although one really will want to add system users other than just the root system user for this to really make sense, since it's not particularly advisable for pppoe logins to be done as system root).

**Comment by dfc-d** [comment]
I have to verify this with an actual build yet, though; will advise once that has been done.

**Comment by thierrydt** [comment]
I've done a quick test for pppoe-relay with your package. Compile and install is ok.
But the init script doesn't support stop/restart/reload, so after reconfig a reboot would be required.
I configured a pppoe-relay instance with both client and server interfaces being separate bridge interfaces, which seemed to work fine.
Why didn't you re-use the existing datamodel as used in AA package 'rp-pppoe '? Now we have to fix config when upgrading a board from AA to CC.

**Pull request closed without merging**
