### PR TITLE
ariang: Update from 1.3.2 to 1.3.6

### PR DESCRIPTION
**Pull request by ArielHeleneto**
Maintainer: @Ansuel 
Compile tested: AXT1800 (an qualcommax/ipq60xx) and x86
Run tested: AXT1800 (an qualcommax/ipq60xx) and x86

Description:

    Fix the problem that cannot create new task after clearing checksum option
    Other bug fix and user interface optimization

    Support overriding aria2 global settings with empty content when create new download task (#712)
    Other bug fix and user interface optimization

    Update Traditional Chinese translation (#705, thx @ChiaYen-Kan)
    Other bug fix and user interface optimization

    Add check-integrity to task settings tab (#693, thx @raytrap)
    Fix a spelling mistake (#696, thx @rusq)
   
    Some issues occuered and I have to re open a new Pull (old one is #22120 )

### CODE REVIEW

**Comment by BKPepe** [comment]
CI is failing for you, can you check it, why it fails for you and also fill the PR template?

**Comment by ArielHeleneto** [comment]
> CI is failing for you, can you check it, why it fails for you and also fill the PR template?

Oh hullo I tried to fix it and could you please approval the CI?

It may be failed again due to my lack experience for updating a package. This is my first time I think.

Strongly thank you.

**Comment by ArielHeleneto** [comment]
seems that CI works fine and risc-v luajit problems has no connection to my pr

**Comment by BKPepe** [comment]
1st commit looks good now.

**Comment by ArielHeleneto** [comment]
> 1st commit looks good now. 2nd commit:
> 
>     * nitpick: Commit subject should not contain the dot at the end
>       Why it is required? Can you describe such change in the commit description? It is not enough to say just "include two more png files".

fix commit message and add detailed message. (those png is added because of the update to 1.3.6)

**Comment by BKPepe** [comment]
I am thinking about this. Since those two PNGs were introduced in 1.3.6, then it should be only in one commit instead of two because if you decide to checkout or have only one commit, then it will not work, because of missing png files, right?

**Comment by ArielHeleneto** [comment]
> I am thinking about this. Since those two PNGs were introduced in 1.3.6, then it should be only in one commit instead of two because if you decide to checkout or have only one commit, then it will not work, because of missing png files, right?

fixed

**Review by 1715173329 — APPROVED** [review]
The build errors seem irrelevant, so LGTM.

**Pull request merged**
