### PR TITLE
icecast: fix whitespace in init file

### PR DESCRIPTION
**Pull request by egorenar**
Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>

Maintainer:  @thess, @andrenarchy
Compile tested: Netgear R9000, OpenWrt SNAPSHOT r16368-9f31c417a2 
Run tested: Netgear R9000, OpenWrt SNAPSHOT r16368-9f31c417a2

### CODE REVIEW

**Comment by neheb** [comment]
Ummm is there a functional change here?

**Comment by egorenar** [comment]
> Ummm is there a functional change here?

Nope, just cleaned up whitespace.

**Comment by neheb** [comment]
Needs a PKG_RELEASE bump. I still don’t get the point of this change though.

**Comment by egorenar** [comment]
I noticed strange whitespace in icecast's init file and thought it might be nice to clean it up for future.
But I agree it's not that important. Leave the decision to merge it or not to you :)

**Pull request merged**
