### PR TITLE
cgi-io: allow underscore character in filename/mimetype

### PR DESCRIPTION
**Pull request by ptpt52**
underscore character in filename/mimetype should be allowed

### CODE REVIEW

**Comment by jow-** [comment]
I can't see a single media type with underscore here: http://www.iana.org/assignments/media-types/media-types.xhtml

Whats the use-case for this? Allowing underscores in filenames is fine.

**Comment by ptpt52** [comment]
@jow- 

I'm just looking at theoretically to see if it's allowed, if the minitype allows underscore, it should.

I'm going to invent a mimetype with an underscore, right?

**Comment by ynezz** [comment]
FYI this is not a proper place submitting changes into `cgi-io` package, the upstream is at https://git.openwrt.org/project/cgi-io.git, so [Sending patches by git send-email](https://openwrt.org/docs/guide-developer/working-with-git-email) applies here.

**Comment by ptpt52** [comment]
> FYI this is not a proper place for submitting changes into `cgi-io` package, the upstream is at https://git.openwrt.org/project/cgi-io.git, so [Sending patches by git send-email](https://openwrt.org/docs/guide-developer/working-with-git-email) applies here.

done

**Pull request closed without merging**
