### PR TITLE
zerotier: update to 1.8.8

### PR DESCRIPTION
**Pull request by chazikai24**
Compile tested: WRT1900ACV2 19.07;X86 OPENWRT
Run tested: WORKS WELL

Description:
Fix  Issues :https://github.com/mwarning/zerotier-openwrt/issues/99
update to 1.8.8

zerotier_1.8.8_arm_cortex-a9_vfpv3-d16 and zerotier_1.8.8-1_x86_64 test OK.

### CODE REVIEW

**Comment by mwarning** [comment]
@chazikai24 I think you need to add your "Signed-off-by: " line to the commit message (`git commit -s --amend --no-edit`).

**Comment by mwarning** [comment]
Tested on a "Nexx WT3020 8M" (ramips/mt7620):
* OpenWrt master: starts and is responsive
* OpenWrt 21.02: starts and is responsive

LGTM

**Comment by chazikai24** [comment]
> @chazikai24 I think you need to add your "Signed-off-by: " line to the commit message (`git commit -s --amend --no-edit`).

OK.I have Signed off the commit.

**Review by BKPepe — CHANGES_REQUESTED** [review]
You are doing more changes than you say in the commit description. Well to be correct, in the commit subject, you said that zerotier should be updated to 1.8.8, but you are touching -fPIE in Makefile and patch. It should be done in separate commit to know why it is necessary to remove it or you can do it in single commit, but it should be described as well.

**Comment by chazikai24** [comment]
> You are doing more changes than you say in the commit description. Well to be correct, in the commit subject, you said that zerotier should be updated to 1.8.8, but you are touching -fPIE in Makefile and patch. It should be done in separate commit to know why it is necessary to remove it or you can do it in single commit, but it should be described as well.

disable fPIE to fix this [error](https://github.com/mwarning/zerotier-openwrt/issues/99)
I revised the commit again.

**Comment by mwarning** [comment]
@chazikai24 I just noticed that you wrote you tested with OpenWrt 19.07 - that is rather old. Can you test with OpenWrt master?
Also, I created a new MR to fix the pipeline https://github.com/openwrt/packages/pull/18300
I also would like to add you the signed off line, but I think OpenWrt only allows real names (can anyone confirm?)

**Comment by chazikai24** [comment]
> @chazikai24我刚刚注意到你写的你用 OpenWrt 19.07 测试过——那是相当旧的。可以用 OpenWrt master 测试吗？ 另外，我创建了一个新的 MR 来修复管道#18300 我也想给你添加已签名的离线，但我认为 OpenWrt 只允许实名（有人可以确认吗？）

It doesn't matter to me. I'm just an amateur.I will close with this comment.You can fix the error by yourself in #18300 .
Sorry for my bad english.

**Comment by mwarning** [comment]
@chazikai24 ok, thank you for your help! :)

**Pull request closed without merging**
