### PR TITLE
transmission: fix source URL

### PR DESCRIPTION
**Pull request by ryzhovau**
Another self-explained PR. [Checked](https://github.com/Entware-ng/entware-packages/commit/93228ef8afd6dbf1c47ba1b7586394d546428867) on Entware-ng.

@mstorchak, @nmav.

### CODE REVIEW

**Comment by diizzyy** [comment]
Hmm... 

I'd suggest the following, as github can be down at times...
http://transmission.cachefly.net/ \
https://github.com/transmission/transmission-releases/raw/master/

**Comment by mstorchak** [comment]
@diizzyy for some reason cachefly.net didn't work for me. It redirects to download.php at transmission official site which doesn't exist. 
I agree in general, but maybe it would make sense to pull from development repo https://github.com/transmission/transmission/releases ?
Is there any particular reason to use transmission-releases?

Ack, anyway.

**Comment by ryzhovau** [comment]
@mstorchak, I don't how to deal with Github releases gracefully. You see, the last transmission release is https://github.com/transmission/transmission/archive/2.92.tar.gz, so we have to be sure there will be no other file with similar name `2.92.tar.gz`.

**Comment by mstorchak** [comment]
Yeah, this approach is a pain, I agree.

**Comment by diizzyy** [comment]
@mstorchak  cachefly works fine here?
` wget http://transmission.cachefly.net/transmission-2.92.tar.xz
--2016-11-03 04:53:02--  http://transmission.cachefly.net/transmission-2.92.tar.xz
Resolving transmission.cachefly.net (transmission.cachefly.net)... 66.225.197.197
Connecting to transmission.cachefly.net (transmission.cachefly.net)|66.225.197.197|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3378116 (3.2M) [application/octet-stream]
Saving to: ‘transmission-2.92.tar.xz’

transmission-2.92.t 100%[=====================>]   3.22M  9.26MB/s   in 0.3s

2016-11-03 04:53:02 (9.26 MB/s) - ‘transmission-2.92.tar.xz’ saved [3378116/3378116]`

**Comment by mstorchak** [comment]
Ah, I see. Yes, *this* works, simply going to  http://transmission.cachefly.net/ redirects to a non-existing page. Sorry for the confusion.
As I understand the problem is the way github forms URL for tags (aka releases). The solution would be to switch to git download method use hash to define exact commit, but since that's not me who has submitted pull request, I won't insist :).

**Comment by ryzhovau** [comment]
@mstorchak, I thought you are the maintainer:)

**Comment by mstorchak** [comment]
I am, kind of :). But your contribution looks good enough to me, so I Ack it as is, although it's not perfect from my point of view. Thank you for this update!
Perhaps later I change download method to git+hash.

**Pull request merged**
