### PR TITLE
dockerd: misc maintainence

### PR DESCRIPTION
**Pull request by G-M0N3Y-2503**
Maintainer: @G-M0N3Y-2503
Compile tested: x86_x64, VirtualBox, `openwrt-21.02`
Run tested: x86_x64, VirtualBox, `openwrt-21.02`

Description:
* `wan` blocking rule now jumps to `REJECT` instead of `DROP` to be consistent with other firewall rules  
* Refactored `/etc/config/dockerd` 
  * Default config only sets defaults dictated by OpenWrt, Otherwise, docker defaults can be assumed.
  * Normalized quotation marks
 * Mitigated case where `wan` blocking rule wasn't added if previous `iptables` command was taking too long
 * ~~Updated patch file format~~

### CODE REVIEW

**Comment by G-M0N3Y-2503** [comment]
Is there something we have to do differently for this branch rather than the master branch?

**Comment by feckert** [comment]
@G-M0N3Y-2503 From my point of view, that should fit. The only thing that puzzles me is why the CI fails.

I have already merged the master. That should fit.

**Comment by G-M0N3Y-2503** [comment]
> The only thing that puzzles me is why the CI fails.
The rebase didn't work either...

I did find that it appears there are do docker images for this branch or the CI isn't configured for this branch yet, maybe the CI doesn't work right now.

https://hub.docker.com/r/openwrtorg/sdk/tags

**Comment by neheb** [comment]
https://downloads.openwrt.org/snapshots/faillogs/arm_mpcore/packages/

a bunch of go packages are failing. ping @jefferyto

**Comment by G-M0N3Y-2503** [comment]
> a bunch of go packages are failing.

the error for these pipelines is different from that error.

We're getting `manifest for openwrtorg/sdk:x86_64-openwrt-21.02 not found: manifest unknown: manifest unknown` and I believe it's because that docker image doesn't exist.

**Comment by jefferyto** [comment]
@neheb let's use #14879 to track 1.16 related errors

**Comment by jefferyto** [comment]
I don't believe CI has been set up for 21.02 yet: https://github.com/openwrt/packages/pull/14834#issuecomment-783549674

**Comment by neheb** [comment]
Please rebase against current master.

**Comment by G-M0N3Y-2503** [comment]
> Please rebase against current master.

I assumed you meant current `openwrt-21.02` and now I'm getting dirty patches errors for other packages
```
Now at patch 025-choose-python-config-version.patch
Patch 025-choose-python-config-version.patch is unchanged
mkdir -p ./patches
rm -f ./patches/* 2>/dev/null >/dev/null
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/001-enable-zlib.patch' -> './patches/001-enable-zlib.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/003-do-not-run-distutils-tests.patch' -> './patches/003-do-not-run-distutils-tests.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/004-do-not-write-bytes-codes.patch' -> './patches/004-do-not-write-bytes-codes.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/006-do-not-add-multiarch-paths-when-cross-compiling.patch' -> './patches/006-do-not-add-multiarch-paths-when-cross-compiling.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/007-distutils-do-not-adjust-path.patch' -> './patches/007-distutils-do-not-adjust-path.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/008-distutils-use-python-sysroot.patch' -> './patches/008-distutils-use-python-sysroot.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/010-do-not-add-rt-lib-dirs-when-cross-compiling.patch' -> './patches/010-do-not-add-rt-lib-dirs-when-cross-compiling.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/013-getbuildinfo-date-time-source-date-epoch.patch' -> './patches/013-getbuildinfo-date-time-source-date-epoch.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/014-remove-platform-so-suffix.patch' -> './patches/014-remove-platform-so-suffix.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/015-abort-on-failed-modules.patch' -> './patches/015-abort-on-failed-modules.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/016-adjust-config-paths.patch' -> './patches/016-adjust-config-paths.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/024-musl-find_library.patch' -> './patches/024-musl-find_library.patch'
'/home/build/openwrt/build_dir/target-x86_64_musl/Python-3.9.1/patches/025-choose-python-config-version.patch' -> './patches/025-choose-python-config-version.patch'
make[2]: Leaving directory '/home/runner/work/packages/packages/lang/python/python3'
time: package/feeds/packages_ci/python3/refresh#4.72#1.63#5.45
make[1]: Leaving directory '/home/build/openwrt'
Dirty patches detected, please refresh and review the diff
Error: Process completed with exit code 1.
```
and others about commits that aren't mine
```
=== Checking commit '9afc761a47a4785c1af442f5c172050d069e71cb'
Author name (Gerard Ryan) seems ok
Commit subject line seems ok (dockerd: Normalized config quotation marks)
Signed-off-by match author
=== Checking commit '4a5a7d5b22d59d1b8d747d3f9b10def2448cacc5'
Author name (Gerard Ryan) seems ok
Commit subject line seems ok (dockerd: Updated patch file format)
Signed-off-by match author
=== Checking commit '681eced8ba5185c91a8bc43f31baa6cb14bfec24'
Pull request should not include merge commits
Author name (Rosen Penev) seems ok
Commit subject line MUST start with '<package name>: ' (Merge pull request #14889 from stangri/21.02-vpn-policy-routing)
Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Rosen Penev <rosenp@gmail.com>')
=== Checking commit 'dc8a73d171cbe0bfe073ec0833f0be6b7ba34b3e'
Author name (Stan Grishin) seems ok
Commit subject line seems ok (vpn-policy-routing: custom user scripts improvements)
Signed-off-by match author
```
:thinking:

**Comment by feckert** [comment]
As @jefferyto has already pointed out, the CI for the new release branch *openwrt-21.02 has not yet been set up for the package feed. We still retrieve the sdk from the master branch.

I think the following variables need to be adjusted here.
https://github.com/openwrt/packages/blob/openwrt-21.02/.circleci/config.yml#L10

The release keys must also be entered here.
https://github.com/openwrt/packages/blob/master/.circleci/Dockerfile

Unfortunately, I'm not familiar with the Github CI, but I could stage a pullrequest.
However, this would then have to be checked by those who are familiar with the github CI.

**Comment by neheb** [comment]
Should be fine now.

**Comment by G-M0N3Y-2503** [comment]
It seems to me that the CI isn't using the correct branch somehow.  
Would deleting this PR and making a new one workaround this?

**Comment by neheb** [comment]
Don't worry about it. CircleCI has been experiencing mass failure recently.

**Comment by jefferyto** [comment]
CircleCI on the openwrt-21.02 branch is still using the sdk for [master](https://github.com/openwrt/packages/blob/46b84dc3354098bd36c041c3af9f582d87cb39b1/.circleci/config.yml#L10), maybe that's why it isn't working?

**Pull request merged**
