### PR TITLE
python3: update to python 3.7.0

### PR DESCRIPTION
**Pull request by crza**
Maintainer: @commodo 
Compile tested: octeon, Edgerouter Lite, trunk
Run tested: octeon

Description:
Update to current python 3 release.

Fixes python3 host SSL module build -> host-pip can use https:// urls again.
Updates Pip to 10.0.1
rebased patches

### CODE REVIEW

**Comment by commodo** [comment]
@crza
[ sorry for the late reply ; i don't do much stuff during the weekend ]
thanks for the patch :)
i was thinking of updating to 3.7.0 since it was released last week

if you want to do that, please go ahead and update this PR with that; 
if not, i will do that sometime this week

thanks
Alex

**Comment by crza** [comment]
Unfortunately I don't have time this week.
I tried to update, but _uuid module fails to build.

It doesn't detect <uuid.h>, which definitely exists, but at least ./toolchain-mips64_octeonplus_64_gcc-7.3.0_musl/linux-4.14.53/include/linux/uuid.h isn't included.

configure doesn't find uuid.h or uuid/uuid.h
I "fixed" it via ac_cv_header_uuid_h=yes in files/config.site
Is that way correct?

Anyway: python 3.7 seems to work on octeon after that.

**Comment by commodo** [comment]
overall looks good
will try you patchset and come back 

thanks
Alex

**Comment by commodo** [comment]
@crza 
tested; all looks good;
the approach for `ac_cv_header_uuid_h=yes ` is perfectly fine :)

fine from me to merge this ( @hnyman )

**Pull request merged**
