### PR TITLE
freeradius3: update version 3.2.4

### PR DESCRIPTION
**Pull request by esaaprillia**
Maintainer:
Compile tested:
Run tested:

Description:

https://github.com/FreeRADIUS/freeradius-server/releases/tag/release_3_2_4

don't make the DH file. It's not needed for OpenSSL >=1.1.0
https://github.com/FreeRADIUS/freeradius-server/commit/afbf93b9679f4011e397610e26dd4f05992ea981

update freeradius version 3.2.4

added freeradius3 package module

refresh patch

### CODE REVIEW

**Comment by esaaprillia** [comment]
@neheb

**Comment by esaaprillia** [comment]
@neheb 

freeradius3 failed to create on snapshots

but freeradius3 builds successfully here

can you see the error

https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a53/packages/freeradius3/compile.txt

**Comment by neheb** [comment]
‘’’
linux-musl/bin/ld.bfd: cannot find @LIBREADLINE@: No such file or directory
collect2: error: ld returned 1 exit status
‘’’

**Comment by esaaprillia** [comment]
> ‘’’ linux-musl/bin/ld.bfd: cannot find @LIBREADLINE@: No such file or directory collect2: error: ld returned 1 exit status ‘’’

can we try adding this

```
PKG_BUILD_PARALLEL:=0
```

**Comment by neheb** [comment]
I guess. New PR please.

**Pull request merged**
