### PR TITLE
ola: Update to 0.9.6, tidy up makefile, try to resolve build dependencies

### PR DESCRIPTION
**Pull request by bk138**
Hi there again,

Trying to get someting happening for https://github.com/openwrt/packages/issues/808, this is a new PR which

* updates ola to 0.9.6
* incorporates @mhei's changes

Please lemme know if #808 still persists and if so, what I can do. Thanks!

### CODE REVIEW

**Comment by champtar** [comment]
hi @bk138,
please edit you commit to use the same mail address as in MAINTAINER var
(in signed-off-by, and also for the commit author, so github detect that it's you)

**Comment by bk138** [comment]
@champtar done.

**Comment by noodlenz** [comment]
Hello

I have compiled on OpenWrt Barrier Breaker 14.07  -  openwrt-HW556a
I build the default build first
   "git clone git://git.openwrt.org/14.07/openwrt.git"
then updated packages
   "./scripts/feeds update packages"
   "./scripts/feeds install ola"
then build OLA
   "make package/ola/compile V=s"
then make menuconfig  and added OLA
build - OK

The default makefile - excludes microhttpd so I can not see the OLA web interface.
I can run from the command line - OK

I will play around with the makefile so microhttpd is included.
I have been testing OLA 9.5 using the hand build version from https://github.com/bk138/packages/tree/ola-squashed.

I will continue testing as I want to use the osc plugin on  OPENWRT .

Thanks  for great software :-)

**Comment by bk138** [comment]
Hi! I've excluded the Web interface on purpose to keep the package small. If you manage to package it in another ipk with the right dependencies, go ahead! 

Am 23. Juli 2015 02:36:32 MESZ, schrieb noodlenz <notifications@github.com>:
>Hello
>
>I have compiled on OpenWrt Barrier Breaker 14.07  -  openwrt-HW556a
>I build the default build first
>   "git clone git://git.openwrt.org/14.07/openwrt.git"
>then updated packages
>   "./scripts/feeds update packages"
>   "./scripts/feeds install ola"
>then build OLA
>   "make package/ola/compile V=s"
>then make menuconfig  and added OLA
>build - OK
>
>The default makefile - excludes microhttpd so I can not see the OLA web
>interface.
>I can run from the command line - OK
>
>I will play around with the makefile so microhttpd is included.
>I have been testing OLA 9.5 using the hand build version from
>https://github.com/bk138/packages/tree/ola-squashed.
>
>I will continue testing as I want to use the osc plugin on  OPENWRT .
>
>Thanks  for great software :-)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openwrt/packages/pull/1516#issuecomment-123917109

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request merged**
