### PR TITLE
[23.05]natmap: update to 20240603

### PR DESCRIPTION
**Pull request by p-w-p**
Maintainer: @ysc3839,@heiher
Compile tested: armv8, snapshot/23.05
Run tested: armv8, snapshot/23.05

Description:
natmap: update to 20240603

### CODE REVIEW

**Comment by 1715173329** [comment]
Use `git cherry-pick -x` to back port commits.

**Comment by 1715173329** [comment]
needs rebase

**Comment by 1715173329** [comment]
missing 1d542b8919a0e98836055bdd251e0345b80a0bc6

**Comment by p-w-p** [comment]
> needs rebase

Done. Thank you for your assistance~

**Comment by p-w-p** [comment]
> missing [1d542b8](https://github.com/openwrt/packages/commit/1d542b8919a0e98836055bdd251e0345b80a0bc6)

Done. Thank you for helping me deal with this series of issues!

**Comment by 1715173329** [comment]
and don't forget 22.03 release ;)

**Comment by p-w-p** [comment]
> and don't forget 22.03 release ;)

Done~ https://github.com/openwrt/packages/pull/24444

**Pull request merged**
