### PR TITLE
Python3: Add python3-pip, python3-setuptools and their dependencies

### PR DESCRIPTION
**Pull request by FlorianFieber**
I wrote these a while ago and just rebased them on the current master branch. 

I'm not using them myself any longer, so I don't think I'll maintain them. Nevertheless, someone might need them, thus this pull request. I left the maintainer for python3-pip and python3-setuptools empty; if someone is willing to adopt these packages, I'll fill them in.

### CODE REVIEW

**Comment by commodo** [comment]
I'll take them, since I own the Python(2) versions.
And that means I just duplicate the effort on these.

Could you please sync up with the latest python-pip and python-setuptools ?
The `Build/Compile`  rules were updated to:
```
define Build/Compile
    $(call Build/Compile/Py3Mod,,\
        install --root="$(PKG_INSTALL_DIR)" --prefix="/usr" \   # THIS IS DIFFERENT
        --single-version-externally-managed \                            # THIS IS DIFFERENT 
    )
endef
```
and preinst + postinst rules were removed.

You might need to create separate PRs for `python3-setuptools` and `python3-pip`.
A maintainer will tell if you if that's required.

Rest looks fine.

**Comment by FlorianFieber** [comment]
I was just about to fix a bug in the pre/postinst routines in the python(2)-pip and -setuptools packages and saw that they were removed in the meantime. I'll adapt it.

**Comment by FlorianFieber** [comment]
I tried to adapt it, but something is still wrong: Now my host path is part of the pip/easy_install shebang…
```
# head -1 /usr/bin/pip3
#!/path/of/staging_dir/host/bin/python3
```
https://github.com/FlorianFieber/openwrt-packages/commit/757971aa0024e9aa003a706b84b19a3a73c8b272

Any ideas?

**Comment by commodo** [comment]
I think it needs a Python3 update there.
See https://github.com/openwrt/packages/blob/master/lang/python/files/python-package.mk  line 113 (__PYVENV_LAUNCHER__) 
Plus maybe a patch to python3-setuptools:

https://github.com/openwrt/packages/blob/master/lang/python-setuptools/patches/0002-fix-pyvenv-environment-get.patch

And all should be good from there.
This should fix it for python3-pip.

**Comment by FlorianFieber** [comment]
Yes, that did the trick, thank you.

**Comment by hnyman** [comment]
@commodo 
is this ok for merge?

**Comment by commodo** [comment]
@hnyman 
Still a few minor things that would need update; but they're nitpicks.
Let's pull this in as is, if that's fine with you.
From a functional point-of-view this PR is fine
Python 3.5.1 just came out and I have to prep an update for that too
And I'll implement my nitpicks in that PR.

**Pull request merged**
