### PR TITLE
audit: fix dependency error when libev also selected

### PR DESCRIPTION
**Pull request by flyn-org**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: @tpetazzoni
Compile tested: x86_64 master

Description:
See also https://github.com/openwrt/packages/pull/10664#issuecomment-691456775.

### CODE REVIEW

**Comment by neheb** [comment]
I don't like this. I've seen this fail with both MPD and gammu.

How about fording the bundled version?

As usual, PKG_RELEASE should be bumped.

**Comment by flyn-org** [comment]
Sorry---what do you mean by "fording?" Is that a typo?

**Comment by aparcar** [comment]
Please bump the PKG_RELEASE and also rebase, I added the breaking `arc_archs` to CI testing.

**Comment by neheb** [comment]
> Sorry---what do you mean by "fording?" Is that a typo?

forcing. Was tryping on a phone.

**Comment by flyn-org** [comment]
> forcing. Was tryping on a phone.

Got it. I stared at what you typed for some time, but for some reason "forcing" did not occur to me!

I decided to go the other direction---audit now unconditionally depends on libev. I am not convinced it is not an OpenWrt build idiosyncrasy that is causing auditd to link against the system libev. From what I can tell, audit still builds its libev parts even when linking against the system libev.

@aparcar, I do not think the CI here would have caught this. This was a case where the package build failed only when libev was also installed. This is the case on the build servers, but not this CI.

**Pull request merged**
