### PR TITLE
irqbalance: add support for interval and banirq

### PR DESCRIPTION
**Pull request by fantom-x**
Maintainer: @hnyman 
Compile tested: R7800
Run tested: R7800

Added the ability to change the sampling interval and a list of IRQ's to ignore via /etc/config/irqbalance

### CODE REVIEW

**Comment by fantom-x** [comment]
Added back an empty line that I removed by mistake

**Comment by fantom-x** [comment]
I will resolve the conflicts here now

**Comment by fantom-x** [comment]
`Pull request should not include merge commits`

Do I need to submit a new PR?

**Comment by hnyman** [comment]
You should have git rebased the branch on refreshed master, and then force-pushed the new changes to this feature branch.

Do whatever is easiest for you. 
git skills can likely help you to recover, but might be easiest to do a new PR

recovery would likely be
* reset this feature branch to the previous correct commit (before the merge commit).
* Then update master itself for upstream
* then rebase this feature branch on master (and fix the version numbers)
* force-push

**Comment by fantom-x** [comment]
> * then rebase this feature branch on master (and fix the version numbers)

That will teach me not to use **git merge**.

It is now fixed.

**Comment by hnyman** [comment]
Yeah, git merge is almost always wrong (or at least leads into squashing) with these PRs, where have a proper feature branch that you can overwrite with force push after a rebase.

**Comment by fantom-x** [comment]
Do both change have a chance of being back ported to 19.07?

**Comment by hnyman** [comment]
If there is no negative feedback, I can cherry pick them later.
If I forget it, please remind me in a week or so

**Pull request merged**
