### PR TITLE
strongswan: update to version 5.9.3

### PR DESCRIPTION
**Pull request by pprindeville**
Maintainer: me, @Thermi
Compile tested: x86_64, generic, HEAD (db9784bedd)
Run tested: same, installed on production router

Description:

Update to latest release 5.9.3.

### CODE REVIEW

**Review by Thermi — APPROVED** [review]
lgtm

**Comment by pprindeville** [comment]
> lgtm

Thanks, but the CI/CD checks are failing and I can't figure out why... complaining about a dirty patch...

**Comment by neheb** [comment]
make package/strongswan/{clean,refresh}

**Comment by Thermi** [comment]
I made a version with proper git patches at #16107. If you can approve running the CI, we can see if it fixed the issues.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/16107 Was merged.

**Pull request closed without merging**
