### PR TITLE
p910nd: multiple instances

### PR DESCRIPTION
**Pull request by Npeca75**
Compile tested: ramips, rb760igs, 23.05 snapshot
Run tested: ramips, rb760igs, 23.05 snapshot

Description:
In case we have multiple device defined in `/etc/config/p910nd` then init script will try to start multiple instance with same instance name

Drop instance name as resolution

### CODE REVIEW

**Comment by BKPepe** [comment]
Ping recent contributor - @systemcrash

**Review by systemcrash — APPROVED** [review]
Would it make sense to number each instance? I'm fine with this change otherwise.

**Comment by BKPepe** [comment]
I can not approve it unless some things are narrow down.

1. CI fails due to:
```
: === Checking commit 'bd041d5c68d19ffe3720dd10d210cecfe2d51107'
: Commit subject line MUST start with '<package name>: ' (p910nd multiple instances)
: Signed-off-by match author
```

2. NoReply addresses are not allowed.

3. Even for your change, you need to bump ``PKG_RELEASE`` number. This is because running system on your router will not see that there is new version. Your changes will be applied only for new installations and what about the existing ones? That's why we will update the ``PKG_RELEASE`` number, too.

**Comment by systemcrash** [comment]
Aside from the commit formatting issues...

**Comment by Npeca75** [comment]
> unless some things are narrow down

sorry @BKPepe 
it is my first PR in OWRT so i need to learn how things work here ...
ok, will do as you suggested

**Comment by systemcrash** [comment]
@Npeca75 what is the effect of your change?

**Comment by Npeca75** [comment]
> @Npeca75 what is the effect of your change?

hi @systemcrash 

```
 4070 root      1060 S    {p910nd} /usr/sbin/p9100d -d -b -f /dev/usb/lp0 0
 4071 root      1060 S    {p910nd} /usr/sbin/p9101d -d -b -f /dev/usb/lp1 1
```

this way i could run 2 instance of p910nd at once

**Review by systemcrash — APPROVED** [review]

**Comment by systemcrash** [comment]
@Npeca75 

> ```
> : Signed-off-by match author
> ```

**Comment by 1715173329** [comment]
please use your real email instead of "noreply".

**Comment by Npeca75** [comment]
> @Npeca75
> 
> > ```
> > : Signed-off-by match author
> > ```

Hi @systemcrash 
i was made a mistake, to be precise, i was too lazy to fork/clone/modify/push :) for this small change
so, i modified code directly on github web and sent PR

when i realized that commit message is incorrect, sorry, first time PR in OWRT, there was no other way than to clone fork, amend commit message, and push
while changing commit message, i put my real name, real email and pushed
but, check formalities rejected this email, and complained that it need to be xxx@users.noreply.github.com 

so, what you suggest?
to replace signed-off with real email and someone will merge with failed formalities test?
or to leave as it is ?
or something else ? :)

**Comment by 1715173329** [comment]
okay... if you like please leave your real email, i can manually rebase it

**Comment by systemcrash** [comment]
> so, what you suggest? to replace signed-off with real email and someone will merge with failed formalities test? or to leave as it is ? or something else ? :)

Or change it as it is registered in your github account. That's what the automated check looks for, that your account email matches the commit (which should be real email).

**Comment by Npeca75** [comment]
> Or change it as it is registered in your github account. That's what the automated check looks for, that your account email matches the commit (which should be real email).

ok, done
Signed-off-by: Peca Nesovanovic <peca.nesovanovic@sattrakt.com>
which is my email registered in github
hope it will pass this time :(
sorry for noise

**Comment by systemcrash** [comment]
Looks correct. I think you got it 👌

**Comment by systemcrash** [comment]
> > Or change it as it is registered in your github account. That's what the automated check looks for, that your account email matches the commit (which should be real email).
> 
> ok, done Signed-off-by: Peca Nesovanovic [peca.nesovanovic@sattrakt.com](mailto:peca.nesovanovic@sattrakt.com) which is my email registered in github hope it will pass this time :( sorry for noise

There's an email setting in github profile called "Keep my email addresses private". I think it's that one. But this PR is ready anyway.

**Comment by 1715173329** [comment]
Merged, thank you!

**Pull request merged**
