### PR TITLE
lsof: update to 4.94.0

### PR DESCRIPTION
**Pull request by neheb**
Upstream switched to GitHub and changed their tarball. Adjusted.

Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @mstorchak 
Compile tested: ath79

### CODE REVIEW

**Comment by mstorchak** [comment]
@neheb , why did you decide to drop the reproducible build patch?

**Comment by nulh** [comment]
2ecbc0442388a71340c5e8e43617459aae45a176

**Review by nulh — CHANGES_REQUESTED** [review]
2ecbc0442388a71340c5e8e43617459aae45a176

**Comment by mstorchak** [comment]
Most of the packages use codeload.github.com. maybe lsof should follow?
`https://codeload.github.com/lsof-org/lsof/tar.gz/$(PKG_VERSION)?`

**Comment by neheb** [comment]
The date patch no longer applies. A quick look indicates upstream fixed this in their own way.

I don't use codeload as they provide a tarball.

**Comment by mstorchak** [comment]
LGTM
We'll see if any extra work is required to restore reproducible builds here https://tests.reproducible-builds.org/openwrt/openwrt_ath79.html

**Pull request merged**
