### PR TITLE
fwknop: fix building without gpg

### PR DESCRIPTION
**Pull request by drizzt**

### CODE REVIEW

**Comment by sbyx** [comment]
@oneru

**Comment by oneru** [comment]
@drizzt I'm curious what case presents a problem.  How do I reproduce your problem?

**Comment by drizzt** [comment]
@oneru just try to build fwknop with "# CONFIG_FWKNOPD_GPG is not set" in .config (in my case using the 15.05 branch):

In file included from fko_common.h:156:0,
                 from base64.c:37:
fko_context.h:37:21: fatal error: gpgme.h: No such file or directory
   #include <gpgme.h>

**Comment by teknoraver** [comment]
@oneru right, when a package is not set the knob is not set, as the comment says, not set to "n"
you must check for != 'y'

**Comment by oneru** [comment]
@drizzt @teknoraver Ah, building fwknop without fwknopd, correct? Let me do a couple test compiles to confirm, and then I'll sign off on the change.  Thanks!

**Comment by drizzt** [comment]
Building fwknop without GPG support

**Comment by oneru** [comment]
@drizzt Strangely enough, I can't seem to reproduce the error.  That's fine, the patch seems correct.  You might do a pull request to backport to 15.05 too, if it breaks compiling for you there.

**Pull request merged**
