### PR TITLE
acme: add haproxy support

### PR DESCRIPTION
**Pull request by lialosiu**
Maintainer: @tohojo
Compile tested: (x86-64, x86, 21.02.0-rc4)
Run tested: (x86-64, x86, 21.02.0-rc4, tests done)

Description:

acme: add haproxy support.

If haproxy was installed, deploy cert file to haproxy and restart haproxy.

### CODE REVIEW

**Comment by tohojo** [comment]
Please fix the commit message: the title should be 'acme: add haproxy support', and you need to write a description as well. Also, your signed-off-by should use your real name.

You don't need to close & reopen the pull request to do this, you can just force-push to the source branch, and the PR will be updated...

**Comment by lialosiu** [comment]
> Please fix the commit message: the title should be 'acme: add haproxy support', and you need to write a description as well. Also, your signed-off-by should use your real name.
> 
> You don't need to close & reopen the pull request to do this, you can just force-push to the source branch, and the PR will be updated...

Sorry, my English so poor🤣
I am trying to fix this.

**Comment by tohojo** [comment]
Alright, that's better as far as the commit message is concerned! 

One more thing: could you please add the new variable to the example config as well (just setting it to 0 is fine)? That way it'll be easier to discover for people; and if you could open a separate pull request for luci-app-acme adding it there as well, that would be great! :)

**Comment by lialosiu** [comment]
new variable added to example config file now :)
I am never try to coding for luci app, so I may take some time to learning it, I will try my best. 😁

**Review by tohojo — APPROVED** [review]

**Pull request merged**
