### PR TITLE
sqlite3: update to version 3.31.1

### PR DESCRIPTION
**Pull request by jkelecic**
Signed-off-by: Josip Kelečić <josip.kelecic@sartura.hr>

Compile tested:ipq40xx, 8devices jalapeno
Run tested: sqlite3 shell tested, works

Description: Re-done PR with proper signoff and template

### CODE REVIEW

**Comment by ja-pa** [comment]
Note, this should be also cherrypicked to 19.0x since it probably fixes some security issues https://advisories.mageia.org/MGASA-2020-0070.html

**Comment by BKPepe** [comment]
ping @micmac1 as he is maintainer of this package.

**Comment by micmac1** [comment]
> Signed-off-by: Josip Kelečić [josip.kelecic@sartura.hr](mailto:josip.kelecic@sartura.hr)
> 
> Compile tested:ipq40xx, 8devices jalapeno
> Run tested: sqlite3 shell tested, works
> 
> Description: Re-done PR with proper signoff and template

Looks good to me, thank you!

If anybody with commit access can merge this that would be great. Thanks!

**Comment by micmac1** [comment]
> Note, this should be also cherrypicked to 19.0x since it probably fixes some security issues https://advisories.mageia.org/MGASA-2020-0070.html

Once this is committed I'll cherry-pick it to 18 and 19. Thanks!

**Pull request merged**
