### PR TITLE
miredo: Initial version 1.2.6

### PR DESCRIPTION
**Pull request by wosk**
Teredo IPv6 tunneling utility

First PR with miredo: https://github.com/openwrt/packages/pull/4201

Compile and Run tested: x86 (on QEMU) and ramips (D-Link DIR-300-B1), OpenWrt version: latest master.
Tests done: IPv6 address accepted. Ping successful through the NAT to target openwrt.

Description:
Miredo is an open-source Teredo IPv6 tunneling software, for Linux and the BSD operating systems. It includes functional implementations of all components of the Teredo specification (client, relay and server). It is meant to provide IPv6 connectivity even from behind NAT devices.

Signed-off-by: Nikita Vostokov <yawosk@yandex.com>

### CODE REVIEW

**Comment by wosk** [comment]
Bump. I`m waiting for somebody who could review or have access to merge this pull request

**Comment by neheb** [comment]
Can we get the commits squashed into one?

**Comment by neheb** [comment]
This fails with libcap installed. I suggedt adding

```
CONFIGUR_VARS += \
ac_cv_header_sys_capability_h=no
```

**Comment by wosk** [comment]
@neheb 
> Can we get the commits squashed into one?
Off course. I could squash all commits to one after all issues will be closed.
Otherwise you could squash all commits on merging if "Allow squash merging" enabled in repo settings.

**Comment by neheb** [comment]
The single commit makes it easier to review. Nothing more.

In any case, this looks relatively fine. Merging.

**Comment by ksx4system** [comment]
any progress? :)

**Pull request merged**
