### PR TITLE
spice: convert to meson

### PR DESCRIPTION
**Pull request by neheb**
Faster compilation.

Removed autotools patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @yousong 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
Odd. I don't get this error locally.

**Comment by neheb** [comment]
This might be more trouble than it's worth...

@dhewg do you know how to pass MESON_ARGS to subprojects?

**Comment by dhewg** [comment]
Nope, I didn't use subproject() myself yet. Passing all of MESON_ARGS sounds wrong though, there might be main project specific args in there. What's the issue, which args are missing?

**Comment by neheb** [comment]
In the Makefile I have an empty \ with the arguments after meant for the sub project.

**Comment by dhewg** [comment]
I think you need support of the parent project to pass those on. Either patch those in or expose a parent arg to set the sub args:
https://gitlab.freedesktop.org/spice/spice/-/blob/master/meson.build#L59

**Comment by neheb** [comment]
@dhewg according to IRC, the format is -Dsubproject:option=x. Tested locally. Seems to work.

**Comment by neheb** [comment]
Abandoning this. It requires multiple upstream backports. Maybe next version...

**Comment by dhewg** [comment]
> @dhewg according to IRC, the format is -Dsubproject:option=x. Tested locally. Seems to work.

Huh, good to know, didn't know that existed.

**Pull request closed without merging**
