### PR TITLE
getdns: properly remove libbsd support

### PR DESCRIPTION
**Pull request by neheb**
Also fixed compilation without deprecated OpenSSL APIs.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @jonathanunderwood 
Compile tested: ath79

Fixes: https://github.com/openwrt/packages/issues/12741

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
This looks promising, thanks for beating me to it!

But it's unclear to me why that openssl patch is necessary. Can we break that out into a separate commit with a bit more of an explanation to aid future maintenance?

**Comment by neheb** [comment]
It's just a missing header.

**Comment by jonathanunderwood** [comment]
> It's just a missing header.

But I wasn't seeing any build breakage without it, hence my ask for a bit more detail and a separate commit, so in the future we know why it was needed.

 Has that patch been submitted upstream?

**Comment by neheb** [comment]
https://github.com/getdnsapi/getdns/pull/482

Doubt it'll get merged since it seems it's an unbound tool.

Split up the commits.

**Comment by jonathanunderwood** [comment]
Thanks @neheb really appreciate it.

**LGTM**

**Comment by jonathanunderwood** [comment]
Aside: I wonder why are we enabling DSA in OpenWRT - it's known to be broken and insecure.

**Comment by neheb** [comment]
https://github.com/getdnsapi/getdns/blob/develop/CMakeLists.txt#L140

**Comment by jonathanunderwood** [comment]
> https://github.com/getdnsapi/getdns/blob/develop/CMakeLists.txt#L140

Interesting - I hadn't spotted that. Actually tempted to disable DSA in a future package release.

**Comment by neheb** [comment]
I think that should be done.

**Pull request merged**
