### PR TITLE
cryptsetup: Update to 2.0.6

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dangowrt 
Compile tested: ar71xx

### CODE REVIEW

**Comment by neheb** [comment]
Note that this has changed since the initial pull request. I have now changed the dependencies for speed and size reasons.

Example:
Before: libgcrypt - 353.6 KB
After: 
kmod-crypto-user - 12.4 KB
kmod-crypto-hmac - 2.9KB
kmod-crypto-sha256 - 5.5KB
kmod-crypto-cbc - 2.9KB

File sizes taken from mt7621 packages under https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/packages/

Note that these are optional packages except for the first. In the case of mvebu, CESA (a built-in driver) provides everything. The other crypto packages shouuld be used when no crypto driver is available.

libgcrypt provides mainly C implementations except for x86 and ARM. The kernel stuff includes MIPS assembly in some cases.

Tested on Turris Omnia (mvebu) and mt7621 with experimental crypto driver.

**Comment by cshoredaniel** [comment]
Thank you for mentioning the testing...especially since I'm using this package again soon and like to know it's not going to break on me.

**Comment by neheb** [comment]
Oh this is hillarious.

You would think the crypto back ends would be used for all the crypto, but no.

It turns out that OpenSSL or libgcrypt is used ONLY for hashing. The actual encryption is handled by the kernel in every case.

Meaning crypto-cbc or crypto-xts is needed no matter what.

This really begs the question as to why have any variant besides the kernel.

**Comment by neheb** [comment]
Thinking about removing the OpenSSL variant. Thoughts?

https://github.com/neheb/packages/commit/79376894ba6c108d52ed05698963b03d2016cec9

**Comment by neheb** [comment]
ping @dangowrt

**Comment by cshoredaniel** [comment]
@neheb some other merge has created a conflict here.

**Comment by neheb** [comment]
@dangowrt rebased. What do you think about https://github.com/neheb/packages/commit/79376894ba6c108d52ed05698963b03d2016cec9 ?

**Comment by neheb** [comment]
Removed OpenSSL variant, as suggested.

**Comment by neheb** [comment]
Reworded initial commit. No other changes.

**Comment by neheb** [comment]
@hnyman maintainer ACKed in https://github.com/neheb/packages/commit/79376894ba6c108d52ed05698963b03d2016cec9#commitcomment-32140475

**Comment by hnyman** [comment]
> maintainer ACKed

Well, as the maintainer @dangowrt  has commit right by himself, I assume that he will likely merge the PR by himself.

**Comment by dangowrt** [comment]
Thanks and sorry for the delay.

**Pull request merged**
