### PR TITLE
haproxy: update to v2.8.0

### PR DESCRIPTION
**Pull request by zhanhb**
- New major LTS release (https://www.mail-archive.com/haproxy@formilux.org/msg43600.html)

Maintainer: @gladiac
Compile tested: ramips/mt7621 OpenWrt 23.05-SNAPSHOT r23183-848759c236
Run tested: ramips/mt7621 OpenWrt 23.05-SNAPSHOT r23183-848759c236

### CODE REVIEW

**Comment by jefferyto** [comment]
Please rebase on master to pick up the latest CI changes.

**Comment by gladiac** [comment]
LGTM; I have been running v2.8.0 on my r7800 for 3 weeks now (I had the PR prepared for a while) and it works well. Let's ship it.

**Comment by zhanhb** [comment]
I'm not sure if I need to add the recent patches.

**Comment by gladiac** [comment]
> I'm not sure if I need to add the recent patches.

There is nothing major in there. We will ship these fixes automatically with v2.8.1 when it lands.

**Comment by zhanhb** [comment]
Sounds great. I'll keep this PR clean.

**Comment by 1715173329** [comment]
if possible please also create a PR for the 23.05 branch, thanks!

**Pull request merged**
