### PR TITLE
traceroute: Add to repo

### PR DESCRIPTION
**Pull request by diizzyy**
Maintainer:
Compile tested: 
ramips, D-Link DIR-860L, OpenWrt master
octeon, EdgeRouter Lite, OpenWrt master
mvebu, Linksys WRT3200ACM, OpenWrt master

Run tested: 
ramips, D-Link DIR-860L, OpenWrt master
octeon, EdgeRouter Lite, OpenWrt master
mvebu, Linksys WRT3200ACM, OpenWrt master

Description:
Add new and modern traceroute to repo

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Something I had in my local repo that someone might want to pick up.

**Comment by champtar** [comment]
this package is 25K, any big advantages vs busybox version or https://downloads.lede-project.org/snapshots/packages/mips_24kc/base/iputils-traceroute6_20101006-1_mips_24kc.ipk which is 6K
(I expect ipv4 version to also be 6K)

**Comment by diizzyy** [comment]
The iputils package suite is heavily outdated and offers more or less nothing compared to busybox these days.

* IPv4 + IPv6 (one binary)
* Supports ASN lookup (busybox doesn't do this at all)
* Supports ICMP, UDP, UDPLITE and TCP (busybox on does ICMP and UDP)
* Support DCCP Requests (not supported by busybox)
* Can be used to discover MTU easily (you can do this with scripting but this is neater)

Standard traceroute that ships with major Linux distributions such as Fedora, RHEL, Debian, Mandriva, Gentoo and Ubuntu so also consistency.

**Comment by champtar** [comment]
@pprindeville do you want to be maintainer of this package?

**Comment by diizzyy** [comment]
I'll keep in it my own repo

**Pull request closed without merging**
