### PR TITLE
lm-sensors: use codeload and add ABI_VERSION

### PR DESCRIPTION
**Pull request by dengqf6**
Maintainer: @jow- 
Compile tested: mvebu

Description:
Use codeload URL suggested by @neheb
Add `ABI_VERSION:=5` to libsensors

### CODE REVIEW

**Comment by dengqf6** [comment]
@hnyman

**Comment by hnyman** [comment]
If upstream has downloadable tar.gz available, we should use it. Codeload can be used to avoid git clone, but is there any need for that here?

**Comment by dengqf6** [comment]
@hnyman 
The pervious link actually redirects to codeload

**Comment by hnyman** [comment]
applied as db10582fd

**Pull request closed without merging**
