### PR TITLE
linknx: Fix compilation with full NLS

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tru7 
Compile tested: arc700

### CODE REVIEW

**Comment by tru7** [comment]
I had no objection but as long as it fails on buildpr for NLS it's no improvement.

**Comment by neheb** [comment]
It also fails here slightly different: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/linknx/compile.txt

It's failing because of a linking error.

**Comment by neheb** [comment]
Tried a few things. Couldn't find a good solution. Closing.

**Comment by tru7** [comment]
@neheb I tried a few things myself. When adding the nls.mk it needs a -liconv linker flag at the end of the line to avoid failing on my test platform. When I add this to EXTRA_LDFLAGS it's added at the start of line and does not help. Do you know of a method to have it added at the end of line? Is this a problem of the upstream code?

Do I interpret it correctly that your try would fix building on ARC platform (which are the only ones where linknx is failing)?

**Comment by neheb** [comment]
On ARC it's slightly different as it's using the iconv-stub. My theory for the failure is that the stub directory is being included twice.

**Pull request closed without merging**
