### PR TITLE
watchcat: regression

### PR DESCRIPTION
**Pull request by djpremier**
Description:
Issue: #7148
Commit of version 18.06: https://github.com/openwrt/packages/commit/9f5ea1c289fae8be30387b37c1c52950c130ea74

### CODE REVIEW

**Comment by hnyman** [comment]
It is a bit strange:
the fix in #7169 by @nunojpg was merged to 18.06, but not to the master of that time. If it would have been merged into master, it would be also in the later 19.07

**Comment by nunojpg** [comment]
I guess I did fail to apply it into master first... I will do it.

**Comment by nunojpg** [comment]
Fixed with 55ae829a14f0d0cddfad1f3372897043cc6f341b
Fixed on master with 178a359275b6df809661adbd385fad3dff6c289b

**Comment by nunojpg** [comment]
@djpremier thanks for raising the issue

**Comment by djpremier** [comment]
@nunojpg 😉

**Pull request closed without merging**
