### PR TITLE
gnutls: update and cleanups

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Maintainer: @bobafetthotmail 

None of the patches got upstreamed?

### CODE REVIEW

**Review by nmav — APPROVED** [review]

**Comment by nmav** [comment]
LGTM. I don't understand the question on the description though.

**Comment by rmandrad** [comment]
after applying this patch I now have a compile issue with the libztd dependency

**Comment by PolynomialDivision** [comment]
> after applying this patch I now have a compile issue with the libztd dependency

Could you provide more information?

**Comment by rmandrad** [comment]
sure - 

`removed '/home/rmandrad/rmandradopenwrt/bin/packages/aarch64_cortex-a53/packages                                                      /libgnutls_3.7.4-1_aarch64_cortex-a53.ipk'
mkdir -p /home/rmandrad/rmandradopenwrt/bin/targets/ipq807x/generic/packages /ho                                                      me/rmandrad/rmandradopenwrt/build_dir/target-aarch64_cortex-a53_musl/gnutls-3.7.                                                      6/ipkg-aarch64_cortex-a53/libgnutls/CONTROL /home/rmandrad/rmandradopenwrt/stagi                                                      ng_dir/target-aarch64_cortex-a53_musl/pkginfo
install -d -m0755 /home/rmandrad/rmandradopenwrt/build_dir/target-aarch64_cortex                                                      -a53_musl/gnutls-3.7.6/ipkg-aarch64_cortex-a53/libgnutls/usr/lib
cp -fpR /home/rmandrad/rmandradopenwrt/build_dir/target-aarch64_cortex-a53_musl/                                                      gnutls-3.7.6/ipkg-install/usr/lib/libgnutls.so.* /home/rmandrad/rmandradopenwrt/                                                      build_dir/target-aarch64_cortex-a53_musl/gnutls-3.7.6/ipkg-aarch64_cortex-a53/li                                                      bgnutls/usr/lib/
find /home/rmandrad/rmandradopenwrt/build_dir/target-aarch64_cortex-a53_musl/gnu                                                      tls-3.7.6/ipkg-aarch64_cortex-a53/libgnutls -name 'CVS' -o -name '.svn' -o -name                                                       '.#*' -o -name '*~'| xargs -r rm -rf
Package libgnutls is missing dependencies for the following libraries:
libzstd.so.1
make[3]: *** [Makefile:276: /home/rmandrad/rmandradopenwrt/bin/packages/aarch64_                                                      cortex-a53/packages/libgnutls_3.7.6-1_aarch64_cortex-a53.ipk] Error 1
`

**Comment by rmandrad** [comment]
note that prior to these commits it was compiling with

	--with-system-priority-file="" \
	--without-libzstd \
	--without-zlib

**Comment by PolynomialDivision** [comment]
@rmandrad https://github.com/openwrt/packages/pull/18868

**Pull request merged**
