### PR TITLE
domoticz: fix compilation with python 3.9

### PR DESCRIPTION
**Pull request by neheb**
Added Fedora patch to fix compilation.

Added python3 dependency as it seems it's needed now.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dwmw2 
Compile tested: ath79

Fixes: https://github.com/openwrt/packages/issues/13757

### CODE REVIEW

**Comment by kofec** [comment]
I'm testing your solution now but mean time I'm thinking about submenu for domoticz with options:
- python
- OpenZWave  `MESSAGE(STATUS "==== OpenZWave not found, support disabled!")`
- telldus  `message(STATUS "Not found telldus-core (telldus-core.h), not adding tellstick support")`
as probably only this option can be easily disable

**Comment by kofec** [comment]
I can confirm that this commit fix the issue with python3.9 and now all is fine.

**Comment by neheb** [comment]
Cleaned up the package a little bit.

Replaced custom boost 1.73 patch with upstream one. Removed CFLAG that
was supposed to fix this but didn't do anything.

Get rid of nls.mk. boost no longer uses it.

**Comment by neheb** [comment]
Nasty. nls.mk only exists because of telldus-core. I'll need to patch that before i can remove it here.

**Comment by devbis** [comment]
Hey @neheb 

I tried your patches and they really helped to compile Domoticz with python3.9.
Unfortunately, while running Domoticz itself it doesn't see system python and cannot load python plugins. Python version is displayed as None 
(E.g. Zigate plugin)

```
2020-10-29 00:39:33.820 Sunrise: 06:51:00 SunSet: 17:09:00
2020-10-29 00:39:33.821 Day length: 10:18:00 Sun at south: 11:60:00
2020-10-29 00:39:33.821 Civil twilight start: 06:21:00 Civil twilight end: 17:39:00
2020-10-29 00:39:33.822 Nautical twilight start: 05:46:00 Nautical twilight end: 18:13:00
2020-10-29 00:39:33.823 Astronomical twilight start: 05:12:00 Astronomical twilight end: 18:47:00
2020-10-29 00:39:33.860 Active notification Subsystems: (0/13)
2020-10-29 00:39:33.876 Starting shared server on: :::6144
2020-10-29 00:39:33.720 Status: Domoticz V2020.2 (c)2012-1970 GizMoCuz
2020-10-29 00:39:33.721 Status: Build Hash: 0, Date: 1970-01-01 03:00:00
2020-10-29 00:39:33.721 Status: Startup Path: /usr/share/domoticz/
2020-10-29 00:39:33.825 Status: PluginSystem: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.
2020-10-29 00:39:33.864 Status: WebServer(HTTP) started on address: :: with port 8080
2020-10-29 00:39:33.880 Status: TCPServer: shared server started...
2020-10-29 00:39:33.880 Status: RxQueue: queue worker started...
2020-10-29 00:39:35.882 Status: EventSystem: reset all events...
2020-10-29 00:39:35.885 Status: EventSystem: reset all device statuses...
2020-10-29 00:39:35.888 Status: NotificationSystem: thread started...
2020-10-29 00:39:35.889 Status: EventSystem - Python: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.
2020-10-29 00:39:35.891 Status: EventSystem: Queue thread started...
2020-10-29 00:39:35.893 Status: EventSystem: Started
```

photo_2020-10-29 00 46 03

```
root@OpenWrt:/# python --version
Python 3.9.0
```

Can you please fix this issue in your pull request?

**Comment by neheb** [comment]
I'll let @dwmw2 handle that. I don't use domoticz.

**Comment by devbis** [comment]
I've found a way to fix 
```
Failed dynamic library load, install the latest libpython3.x library that is available for your platform.
```
and make plugins work. 

Prior to this line 
https://github.com/domoticz/domoticz/blob/development/hardware/plugins/DelayedLink.h#L198

one should add 
```
if (!shared_lib_) FindLibrary("python3.9", true);
```

That fixes the python3.x library load issue and makes domoticz works well with plugins.
It would be nice if you add this one-line addition to the pull request.

**Comment by neheb** [comment]
Oh great.

**Comment by neheb** [comment]
@devbis added

**Pull request merged**
