### PR TITLE
python-curl: fix compilation with libcurl-wolfssl

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @valdi74 
Compile tested: arm, WRT3200ACM, openwrt master
Run tested: none.

Description:
This allows compilation when libcurl is build with wolfssl as its SSL backend.
It currently fails because of the `--single-version-externally-managed` default option.
```
error: option --single-version-externally-managed not recognized
```
I'm setting empty `PYTHON[3]_PKG_SETUP_ARGS`, and then adding the SSL options, to avoid duplicate code in case an option is needed in the future.  There's no need to increase `PKG_RELEASE` as it does not change the final package (the ones that could be built before).

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

### CODE REVIEW

**Comment by BKPepe** [comment]
I am not sure if this will work with WolfSSL. Because there is no support in python-curl.

**Comment by neheb** [comment]
WolfSSL has an OpenSSL compatibility layer. Will that work?

**Comment by BKPepe** [comment]
Will check it in a day or two as it needs to be run tested.

**Comment by cotequeiroz** [comment]
I will run-test this as soon as I am able.  There's a warning at build time about the SSL backend:
```
libcurl was compiled with SSL support, but configure could not determine which library was used; thus no SSL crypto locking callbacks will be set, which may cause random crashes on SSL requests
```
We may be able to use the compatibility layer, since I see the required calls (1.0.x API) are defined in `wolfssl/openssl/ssl.h`.  In theory it should work, either by adding `-I$(STAGING_DIR)/usr/include/wolfssl`, or by patching the sources.  I'll give this a try.

**Comment by cotequeiroz** [comment]
My first tests were with the PR in its current form:
It appears to work if curl (more on that later) works: 
```
# python
Python 2.7.16 (default, May 09 2019, 11:51:38)
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> c = pycurl.Curl()
>>> c.setopt(c.URL, 'https://google.com/')
>>> c.perform()
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
>>> c.close()
>>> quit()
```
I found out that playing with wolfssl in openwrt is never straightforward.  curl fails with some (many) sites:
```
>>> c.setopt(c.URL, 'https://openwrt.org/')
>>> c.perform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pycurl.error: (35, 'SSL_connect failed with error -424: Extension type not allowed in handshake message type')
```
This seems to be a `curl`-`wolfssl`-TLS 1.3 problem, more than a `python-curl` problem:
```
# curl https://openwrt.org/
curl: (35) SSL_connect failed with error -424: Extension type not allowed in handshake message type
# curl --tlsv1.2 https://openwrt.org/ 
<!DOCTYPE html>
```
Note that google.com supports TLS 1.3, while openwrt.org doesn't.  The build warning is about locking, so my tests did not get close to the problem.

**Comment by BKPepe** [comment]
Send the patch to upstream, please.

**Comment by BKPepe** [comment]
I see that you sent the patch to upstream. https://github.com/pycurl/pycurl/pull/577 That's nice.

**Comment by cotequeiroz** [comment]
I added a patch, submitted upstream (pycurl/pycurl#577), using the openssl code with the wolfssl compatibility layer.  I've tested it with some of the examples in the source dir (the few that failed did not appear to be related to this).
@BKPepe beat me to even explain this :smile:

**Comment by cotequeiroz** [comment]
The patch was merged upstream, and I've refreshed it here to have the commit reference.

**Comment by BKPepe** [comment]
@valdi74 Can I get your approval as you are maintainer of python-curl package?

**Comment by valdi74** [comment]
I approve.

**Comment by cotequeiroz** [comment]
Thank you.

**Pull request merged**
