### PR TITLE
[OpenWrt 18.06] python,python3: move shebang handle in install script

### PR DESCRIPTION
**Pull request by BKPepe**
When I wanted to have almost identical Makefile for package 'youtube-dl' also in OpenWrt 18.06, I noticed that in /usr/bin/youtube-dl as shebang, there is this one:

`#!/home/pepe/xiaomi/openwrt-sdk-18.06.2-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64/staging_dir/hostpkg/bin/python2.7
`

I could cherry-pick it to the branch directly, but nobody will notice that and it's not right. When I cherry-pick commit from #8196 which was done by @commodo I have the correct shebang. 

`#!/usr/bin/python2`

@jefferyto , @commodo any thought to have it included in OpenWrt 18.06?

### CODE REVIEW

**Comment by commodo** [comment]
[just remembered]
Maybe bump PKG_RELEASE as well

**Comment by BKPepe** [comment]
Ok. Bumped PKG_RELEASE.

**Comment by commodo** [comment]
> @jefferyto , @commodo any thought to have it included in OpenWrt 18.06?

from my side: this is a fix commit definitely worth having in a release branch

**Comment by jefferyto** [comment]
I'm ok with including this fix for 18.06, but would prefer to use the latest version of that code... There was an issue with symlinks being overwritten (#8550).

**Comment by BKPepe** [comment]
During the weekend, I prepared it but didn't get to test it. Once I test it, I will push the changes and let you know.

**Comment by BKPepe** [comment]
Sorry that it took so long. Rebased, tested. It works.

**Comment by BKPepe** [comment]
Right, we should do that, but I am a little bit afraid doing that as we are talking about bumping affected packages in only stable version, which we have. It was *somehow* working before that and with this change, it will work as it should. :D

**Comment by jefferyto** [comment]
It probably wasn't working before but no one bothered to file an issue :joy:

**Pull request merged**
