### PR TITLE
ddns-scripts: Add servercow.de as DDNS provider

### PR DESCRIPTION
**Pull request by jummo**
Run tested: x86-64 22.03

Description:
Add ddns provider servercow.de.
Description of usage at https://cp.servercow.de/plugin/support_manager/knowledgebase/view/46/dns-update-through-fritzbox-router/

### CODE REVIEW

**Comment by mhei** [comment]
As "Test Formalities" buildbot already mentioned: please prefix your commit with the package name. And you can omit the Maintainer field from the PR description: it looks that this package does not have a dedicated maintainer at the moment and your e-mail address in there is not correct. Beside this, the change looks good to me - though I did not test it.

**Comment by mhei** [comment]
I just noticed that you closed your previous PR. You should update this PR like follows:
Use `git commit --amend` in your local branch to edit the commit message. Then use `git push --force` to push to your remote repo branch. Then this PR is automatically updated. Finally edit the PR's description.

**Review by mhei — CHANGES_REQUESTED** [review]
Please change the following:
- the package name is "ddns-scripts"
- please bump PKG_RELEASE

**Comment by BKPepe** [comment]
1. Subject should not end with dot
2. There is missing commit description as it is required here: https://openwrt.org/submitting-patches#submission_guidelines

Previous PR to reference it here https://github.com/openwrt/packages/pull/22997#issuecomment-1873841259

**Review by mhei — APPROVED** [review]

**Pull request merged**
