### PR TITLE
https-dns-proxy: update to 2023-05-25-1

### LINKED ISSUE #19366: https-dns-proxy: dmesg page fault
Maintainer: @stangri 

-- | Value
-- | --
Model | TP-Link Archer C7 v2
Architecture | Qualcomm Atheros QCA9558 ver 1 rev 0
Target Platform | ath79/generic
Firmware Version | OpenWrt 22.03.0 r19685-512e76967f / LuCI openwrt-22.03 branch git-22.245.77528-487e58a
Kernel Version | 5.10.138

Description:

added in https-dns-proxy into imagebuilder [here](https://firmware-selector.openwrt.org/). At boot, the kernel log shows:

```
[   78.258834] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 63222510
[   78.268317] epc = 77e72df4 in libc.so[77df4000+a9000]
[   78.273488] ra  = 77e74b04 in libc.so[77df4000+a9000]
...
[   89.156259] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 6322251a
[   89.165861] epc = 77dc2dc0 in libc.so[77d44000+a9000]
[   89.171129] ra  = 77dc4b04 in libc.so[77d44000+a9000]
...
[   94.439188] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 63222520
[   94.448917] epc = 77e2cdf4 in libc.so[77dae000+a9000]
[   94.454103] ra  = 77e2eb04 in libc.so[77dae000+a9000]
[   99.763575] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 63222525
[   99.773390] epc = 77e66dc0 in libc.so[77de8000+a9000]
[   99.778544] ra  = 77e68b04 in libc.so[77de8000+a9000]
[  104.985969] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 6322284c
[  104.995583] epc = 77e4adf4 in libc.so[77dcc000+a9000]
[  105.000758] ra  = 77e4cb04 in libc.so[77dcc000+a9000]
[  129.174846] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 63222865
[  129.184505] epc = 77e78dc0 in libc.so[77dfa000+a9000]
[  129.189687] ra  = 77e7ab04 in libc.so[77dfa000+a9000]
[  134.335382] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 6322286a
[  134.344791] epc = 77e4adc0 in libc.so[77dcc000+a9000]
[  134.350131] ra  = 77e4cb04 in libc.so[77dcc000+a9000]
[  139.404103] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 6322286f
[  139.413861] epc = 77e28dc0 in libc.so[77daa000+a9000]
[  139.419098] ra  = 77e2ab04 in libc.so[77daa000+a9000]
[  144.494286] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 63222874
[  144.503690] epc = 77de2df4 in libc.so[77d64000+a9000]
[  144.508995] ra  = 77de4b04 in libc.so[77d64000+a9000]
[  149.580321] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 63222879
[  149.589720] epc = 77eb2dc0 in libc.so[77e34000+a9000]
[  149.595016] ra  = 77eb4b04 in libc.so[77e34000+a9000]
[  154.672733] do_page_fault(): sending SIGSEGV to https-dns-proxy for invalid read access from 6322287e
[  154.682129] epc = 77eb4dc0 in libc.so[77e36000+a9000]
[  154.687367] ra  = 77eb6b04 in libc.so[77e36000+a9000]
```

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test name resolution

Description:
* update to a new upstream commit, fixes #19366
* update patches/010-cmakelists-remove-cflags.patch as upstream file was update
* remove patches/020-cmakelists-add-version.patch as version is now set elsewhere
* add patches/020-src-options.c-add-version.patch to set the version information
* adjust PROCD START time to 95

### CODE REVIEW

**Comment by stangri** [comment]
Huge thanks to @schmaller for investigation and suggested fix.

**Comment by systemcrash** [comment]
When can a typical user expect this to land in the repos used by 22.03.x?

**Comment by stangri** [comment]
> When can a typical user expect this to land in the repos used by 22.03.x?

24-48 hours after [this](https://github.com/openwrt/packages/pull/21178) is merged. I'd like to wait a week or so to see if there are any issues reported in snapshots or 23.05 before I merge this for the current release.

**Comment by Ohfalderal** [comment]
@stangri - updated a 22.03.0 TP-Link C7 and raised the verbosity... and immediately see segmentation faults logged.

**Comment by stangri** [comment]
> @stangri - updated a 22.03.0 TP-Link C7 and raised the verbosity... and immediately see segmentation faults logged.

Did you have better experience with the out of the tree patch before?

**Comment by Ohfalderal** [comment]
@stangri 
> > @stangri - updated a 22.03.0 TP-Link C7 and raised the verbosity... and immediately see segmentation faults logged.
> 
> Did you have better experience with the out of the tree patch before?

No (and when corrected for 22.. will the patch be applied to the 21.. version?)

**Pull request merged**
