### PR TITLE
libwebsockets: update to latest stable 4.3.3 (released on 2023/11/20)

### PR DESCRIPTION
**Pull request by liudongmiao**
remove the previous patches are there were fixed in 4.3.3.

Maintainer: OpenWrt.org
Compile tested: ath79-generic-openwrt-23.05 (docker sdk tag)
Run tested: ath79/generic, OpenWrt 23.05.2, Netgear WNDR3800

Description: Update libwebsockets to latest stable 4.3.3, released on 2023/11/20

Refer for latest stable: #23562

### CODE REVIEW

**Comment by BKPepe** [comment]
Commit description does not say anything about backported patch.

**Comment by liudongmiao** [comment]
Just fix and make a force push (I hate foce push).

**Comment by liudongmiao** [comment]
@BKPepe the ci seems fail at patching.. However, I have use the latest master SDK, it works well.

**Comment by BKPepe** [comment]
CI fails because of:
```
Dirty patches detected, please refresh and review the diff
Error: Process completed with exit code 1.
```

**Comment by liudongmiao** [comment]
use https://github.com/openwrt/packages/pull/23562 instead of this.

**Pull request closed without merging**
