### PR TITLE
ubnt-manager/prometheus-node-exporter-lua: add airos monitoring

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add ubnt-manager for managing airos devices. Based on that package ubnt-manager-collector collects statistics.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@champtar

**Comment by champtar** [comment]
In the Prometheus makefile you are missing `call BuildPackage` and you need to bump the version

**Comment by PolynomialDivision** [comment]
Thanks. Fixed it.

**Comment by aparcar** [comment]
Looks fine to me, overall I recommend rewriting the whole Lua code with https://github.com/jow-/ucode

**Comment by PolynomialDivision** [comment]
Thanks for your reviews. I would like to merge this first and then go on rewriting again.

It was suggested that I use:
- snmp instead of ssh (I am unsure if I would like to do this)
- rewrite with ucode

Ubnt-manager should not only be used for "monitoring". We focus on automation of tasks and that's why I focus in creating some app, that configures ubiquiti devices automatically.

**Comment by aparcar** [comment]
If this is useful please merge, I'd recommend a combination of SNMP and Ansible. That approach is less invasive (compared to frequent SSH logins) and doesn't store all credential on an Internet facing device.

**Comment by PolynomialDivision** [comment]
For me it is useful, so I will merge. Let's see how it will go on. :) Thanks for your feedback.

**Comment by PolynomialDivision** [comment]
I am very sorry. I was very sure I fixed it. o.O
https://github.com/openwrt/packages/pull/18234

**Pull request merged**
