### PR TITLE
shairplay: Update to 2018-08-24

### PR DESCRIPTION
**Pull request by neheb**
Switched to codeload for easier package bumping.

Added PKG_BUILD_PARALLEL for faster compilation.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @Noltari 
Compile tested: ramips

### CODE REVIEW

**Comment by neheb** [comment]
Relies on https://github.com/openwrt/packages/pull/8113

**Comment by neheb** [comment]
Fascinating...So Build/InstallDev from the avahi package is not being installed by CircleCI. Guess this needs PKG_BUILD_DEPENDS or something...

**Comment by neheb** [comment]
Nope, didn't work. I can't see an obvious way to fix this. The Build/InstallDev entry for avahi is guarded by it being the dbus variant.

@thess any thoughts?

**Comment by neheb** [comment]
Fascinating...

After deleting both build_dir and staging_dir I was able to reproduce the error.

**Comment by neheb** [comment]
Replaced workaround with patch from upstream.

**Comment by thess** [comment]
Whoops sorry - @Noltari. I wasn't thinking when I merged this.

**Pull request merged**
