### PR TITLE
nfs-kernel-server: update to 2.4.3

### PR DESCRIPTION
**Pull request by jmarcet**
Maintainer: Peter Wagner <tripolar@gmx.at>
Compile tested: x86_64 master
Run tested: x86_64 master

Description:

There have been two updates which we miss.

### CODE REVIEW

**Comment by neheb** [comment]
musl 1.2.0 breaks with nfs-kernel-server. Needs this patch:

```
--- a/support/nfs/cacheio.c
+++ b/support/nfs/cacheio.c
@@ -238,7 +238,7 @@ cache_flush(int force)
 	    stb.st_mtime > now)
 		stb.st_mtime = time(0);
 	
-	sprintf(stime, "%ld\n", stb.st_mtime);
+	sprintf(stime, "%lld\n", (long long)stb.st_mtime);
 	for (c=0; cachelist[c]; c++) {
 		int fd;
 		sprintf(path, "/proc/net/rpc/%s/flush", cachelist[c]);
--- a/utils/idmapd/idmapd.c
+++ b/utils/idmapd/idmapd.c
@@ -172,7 +172,7 @@ flush_nfsd_cache(char *path, time_t now)
 	int fd;
 	char stime[32];
 
-	sprintf(stime, "%ld\n", now);
+	sprintf(stime, "%lld\n", (long long)now);
 	fd = open(path, O_RDWR);
 	if (fd == -1)
 		return -1;
@@ -625,8 +625,8 @@ nfsdcb(int UNUSED(fd), short which, void *data)
 		/* Name */
 		addfield(&bp, &bsiz, im.im_name);
 		/* expiry */
-		snprintf(buf1, sizeof(buf1), "%lu",
-			 time(NULL) + cache_entry_expiration);
+		snprintf(buf1, sizeof(buf1), "%llu",
+			 (long long)time(NULL) + cache_entry_expiration);
 		addfield(&bp, &bsiz, buf1);
 		/* Note that we don't want to write the id if the mapping
 		 * failed; instead, by leaving it off, we write a negative
@@ -653,8 +653,8 @@ nfsdcb(int UNUSED(fd), short which, void *data)
 		snprintf(buf1, sizeof(buf1), "%u", im.im_id);
 		addfield(&bp, &bsiz, buf1);
 		/* expiry */
-		snprintf(buf1, sizeof(buf1), "%lu",
-			 time(NULL) + cache_entry_expiration);
+		snprintf(buf1, sizeof(buf1), "%llu",
+			 (long long)time(NULL) + cache_entry_expiration);
 		addfield(&bp, &bsiz, buf1);
 		/* Note we're ignoring the status field in this case; we'll
 		 * just map to nobody instead. */
```

**Comment by diizzyy** [comment]
@tripolar 
Ping

@neheb 
I think it's better to avoid including patches that aren't needed but I do see your point.

**Comment by neheb** [comment]
@diizzyy that patch and more were upstreamed. Will come with version 2.4.4.

**Comment by diizzyy** [comment]
If that's the case we can update to 2.4.4 when it's released or backport if OpenWrt updates to musl 1.2.0 earlier than the release of 2.4.4?

**Comment by neheb** [comment]
Sure. Waiting for 2.4.4 is easiest.

**Comment by jmarcet** [comment]
> musl 1.2.0 breaks with nfs-kernel-server. Needs this patch:
> 
> ```
> --- a/support/nfs/cacheio.c
> +++ b/support/nfs/cacheio.c
> @@ -238,7 +238,7 @@ cache_flush(int force)
>  	    stb.st_mtime > now)
>  		stb.st_mtime = time(0);
>  	
> -	sprintf(stime, "%ld\n", stb.st_mtime);
> +	sprintf(stime, "%lld\n", (long long)stb.st_mtime);
>  	for (c=0; cachelist[c]; c++) {
>  		int fd;
>  		sprintf(path, "/proc/net/rpc/%s/flush", cachelist[c]);
> --- a/utils/idmapd/idmapd.c
> +++ b/utils/idmapd/idmapd.c
> @@ -172,7 +172,7 @@ flush_nfsd_cache(char *path, time_t now)
>  	int fd;
>  	char stime[32];
>  
> -	sprintf(stime, "%ld\n", now);
> +	sprintf(stime, "%lld\n", (long long)now);
>  	fd = open(path, O_RDWR);
>  	if (fd == -1)
>  		return -1;
> @@ -625,8 +625,8 @@ nfsdcb(int UNUSED(fd), short which, void *data)
>  		/* Name */
>  		addfield(&bp, &bsiz, im.im_name);
>  		/* expiry */
> -		snprintf(buf1, sizeof(buf1), "%lu",
> -			 time(NULL) + cache_entry_expiration);
> +		snprintf(buf1, sizeof(buf1), "%llu",
> +			 (long long)time(NULL) + cache_entry_expiration);
>  		addfield(&bp, &bsiz, buf1);
>  		/* Note that we don't want to write the id if the mapping
>  		 * failed; instead, by leaving it off, we write a negative
> @@ -653,8 +653,8 @@ nfsdcb(int UNUSED(fd), short which, void *data)
>  		snprintf(buf1, sizeof(buf1), "%u", im.im_id);
>  		addfield(&bp, &bsiz, buf1);
>  		/* expiry */
> -		snprintf(buf1, sizeof(buf1), "%lu",
> -			 time(NULL) + cache_entry_expiration);
> +		snprintf(buf1, sizeof(buf1), "%llu",
> +			 (long long)time(NULL) + cache_entry_expiration);
>  		addfield(&bp, &bsiz, buf1);
>  		/* Note we're ignoring the status field in this case; we'll
>  		 * just map to nobody instead. */
> ```

Strange, I am using it with musl myself and did not notice any breakage,

**Comment by neheb** [comment]
https://patchwork.ozlabs.org/project/openwrt/patch/20200330044732.1954941-1-rosenp@gmail.com/

**Comment by neheb** [comment]
version 2.5.1 was released.

**Comment by jmarcet** [comment]
I updated to v2.5.1, everything seems to be working fine on x86-64.

Upstream has changed a little bit and the patch for musl-1.2.0 compatibility doesn't seem necessary anymore although I'm using musl-1.1.24 so I am not 100% sure.

**Comment by neheb** [comment]
Yeah it's upstreamed.

**Pull request merged**
