### PR TITLE
smstools3: Fix NLS build dependencies

### LINKED ISSUE #1859: error build smstools3 (use libiconv-full)
make[3]: Entering directory '/magazyn/Pliki/openwrt/trunk/feeds/packages/utils/smstools3'
. /magazyn/Pliki/openwrt/trunk/include/shell.sh; gzip -dc /magazyn/Pliki/openwrt/trunk/dl/smstools3-3.1.15.tar.gz | tar -C /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/.. -xf - 

Applying ./patches/001-smsd.patch using plaintext: 
patching file src/smsd.c

Applying ./patches/002-Makefile.patch using plaintext: 
patching file src/Makefile
touch /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/.prepared_cbfe09455b5053d5fe735ed375b08c37
rm -f /magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.smstools3_installed
(cd /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/./; if [ -x ./configure ]; then find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/ -name config.guess | xargs -r chmod u+w; find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/ -name config.guess | xargs -r -n1 cp --remove-destination /magazyn/Pliki/openwrt/trunk/scripts/config.guess; find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/ -name config.sub | xargs -r chmod u+w; find /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/ -name config.sub | xargs -r -n1 cp --remove-destination /magazyn/Pliki/openwrt/trunk/scripts/config.sub; AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CFLAGS="-D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64 " CXXFLAGS="-D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64 " CPPFLAGS="-I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include " LDFLAGS="-L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -liconv "   ./configure --target=mips-openwrt-linux --host=mips-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info    ; fi; )
rm -f /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/.configured_*
touch /magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/.configured_yyyyyyyy
make -C "/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/src" CC="mips-openwrt-linux-musl-gcc" CFLAGS='-D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"' LFLAGS='-L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/lib -L/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib -znow -zrelro -liconv  -L"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/lib"' all
make[4]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/src'
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o extras.o extras.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o locking.o locking.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o cfgfile.o cfgfile.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o logging.o logging.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o alarm.o alarm.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o smsd_cfg.o smsd_cfg.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o charset.o charset.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mips-openwrt-linux-musl-gcc -D NUMBER_OF_MODEMS=1 -D USE_ICONV -D DISABLE_INET_SOCKET -W -Wall -D_FILE_OFFSET_BITS=64  -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/usr/include -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/fortify -I/magazyn/Pliki/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include  -I"/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/usr/lib/libiconv-full/include"   -c -o stats.o stats.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
stats.c:30:16: fatal error: mm.h: No such file or directory
 #include <mm.h>
                ^
compilation terminated.
<builtin>: recipe for target 'stats.o' failed
make[4]: *** [stats.o] Error 1
make[4]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/src'
Makefile:74: recipe for target '/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/.built' failed
make[3]: *** [/magazyn/Pliki/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.11/smstools3/.built] Error 2
make[3]: Leaving directory '/magazyn/Pliki/openwrt/trunk/feeds/packages/utils/smstools3'
package/Makefile:191: recipe for target 'package/feeds/packages/smstools3/compile' failed
make[2]: *** [package/feeds/packages/smstools3/compile] Error 2
make[2]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
package/Makefile:188: recipe for target '/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.package_compile' failed
make[1]: *** [/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.11/stamp/.package_compile] Error 2
make[1]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
/magazyn/Pliki/openwrt/trunk/include/toplevel.mk:177: polecenia dla obiektu 'world' nie powiodły się
make: *** [world] Błąd 2

### PR DESCRIPTION
**Pull request by thess**
Use NLS macros for includes & ldflags.
Fixes #1859 

@erdoukki, @ryzhovau - plese review

Signed-off-by: Ted Hess <thess@kitschensync.net>

### CODE REVIEW

**Comment by ryzhovau** [comment]
1. Package compiles with `BUILD_NLS=y` without errors, 
2. LD flags are ignored, because package expects `LFLAGS` instead of `LDFLAGS` (see deleted `Build/Compile` section).

PS I'm not a maintainer of this package.

**Comment by jow-** [comment]
For handling `LFLAGS` I suggest something like that:

`MAKE_VARS += LFLAGS="$(TARGET_LDFLAGS)"`

**Comment by thess** [comment]
Thanks @jow-. CFLAGS was not being handled correctly either. This should be correct now.

@ryzhovau - sorry to bother. You had been the last one to work on this issue.

@erdoukki - please review

**Comment by thess** [comment]
@erdoukki - If no objections, I'll merge this

**Pull request merged**
