### PR TITLE
snort3: update to 3.1.64.0

### PR DESCRIPTION
**Pull request by graysky2**
Upstream bump

Maintainer: @flyn-org

### CODE REVIEW

**Comment by graysky2** [comment]
Note that this needs https://github.com/openwrt/packages/pull/21459 or it will fail to build

**Comment by flyn-org** [comment]
Can you force-push this to your libdaq branch? Combining both into one pull request would allow the CI checks to run.

**Comment by graysky2** [comment]
Done

**Comment by flyn-org** [comment]
Merge #21459 instead, which now includes the snort3 update.

**Comment by 1715173329** [comment]
this pr is included in #21459. closing

**Pull request closed without merging**
