### PR TITLE
python-cryptography: Update to 3.0

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: me, @commodo 
Compile tested: armvirt-32, 2020-07-26 snapshot sdk
Run tested: armvirt-32 (qemu), 2020-07-26 snapshot

Description:
Also:
* Remove patches that are included in the update
* Replace the python3 dependency with a smaller list (python3-urllib is needed because it is a dependency of python3-email)

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I used the stdlib checking script to find stdlib dependencies, though there is one (non-standard) [import](https://github.com/pyca/cryptography/blob/3.0/src/cryptography/hazmat/bindings/openssl/binding.py#L142) that it wasn't able to find. (I wonder how often this kind of import occurs in other packages.)

**Comment by neheb** [comment]
Hrm I have a deprecated OpenSSL patch for this package. I guess I need to update it...

**Comment by jefferyto** [comment]
@neheb If you mean the patches from #9372, the original PR (pyca/cryptography#4765) was merged and part of 3.0.

**Comment by neheb** [comment]
different one. https://github.com/neheb/packages/commit/4e074b24a6b2209aa27cca0617a22284293b214d

I don't plan on making that a PR here.

**Pull request merged**
