### PR TITLE
BCP38: don't slow down established connections

### PR DESCRIPTION
**Pull request by edwintorok**
Enabling BCP38 causes an iptables rule to be inserted before this rule (on forwarding_rule chain):
ACCEPT     all  --  anywhere             anywhere             ID:66773300 ctstate RELATED,ESTABLISHED

This makes all forwarded packets go through the BCP38 ipset match, which slows
down download speed from 440 Mbit/s to 340 Mbit/s.

AFAICT that is not necessary: packets are rejected based on destination IP, so if they are rejected when trying to establish a new connection you won't have packets in the established state that would match the BCP38 rules anyway.

Put BCP38 match rule in first chain after established connections are handled:
enabling BCP38 doesn't affect download speed.

To test:

* disable BCP38
```sh
uci set bcp38.@bcp38[0].enabled=0
uci commit
/etc/init.d/firewall reload
```
* measure download speed from a machine on the LAN
* enable BCP38 (use your wan interface)
```sh
uci set bcp38.@bcp38[0].enabled=1
uci set bcp38.@bcp38[0].interface='pppoe-wan'
uci commit
/etc/init.d/firewall reload
```
* measure download speed from a machine on the LAN again
* Check that BCP38 is effective, e.g.  from a machine on the LAN do:
```sh
 ping -c 2 192.0.2.1
PING 192.0.2.1 (192.0.2.1) 56(84) bytes of data.
From 192.168.1.1 icmp_seq=1 Destination Net Unreachable
From 192.168.1.1 icmp_seq=2 Destination Net Unreachable
```

With this patch applied the 2 speeds should be about the same, without this patch I see a visible   drop of  100 Mbit/s (>20%).

I tested on this router:
```
system type		: Qualcomm Atheros QCA9558 ver 1 rev 0
machine			: TP-LINK TL-WR1043ND v2
processor		: 0
cpu model		: MIPS 74Kc V5.0
BogoMIPS		: 358.80
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp dsp2
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
```

### CODE REVIEW

**Comment by tohojo** [comment]
Huh. Had no idea it could have that kind of performance impact. 

Sticking it in the forwarding_lan_rule means it will only be applied to the lan zone, though. That's not necessarily desirable - if one has other zones, bcp38 should work for those too.

Perhaps simply adding a state=NEW to the rule would give a similar improvement?

Also, your commit lacks a signed-off-by tag...

**Comment by edwintorok** [comment]
Thanks for the suggestion, using 'state NEW' to avoid jumping to the BCP38 chain works well.
I've updated my branch, and included the Signed-off-by line.

**Comment by tohojo** [comment]
Cool. Have you tested it with high rate UDP traffic as well? Not sure if this will make the state tracker do more work than it would otherwise (don't think so, but better be sure). :)

**Comment by edwintorok** [comment]
I don't see a difference with UDP, looks like it can process UDP packets much faster than TCP (almost twice as fast), so the iptables rules don't have much effect:
```
Socket  Message  Elapsed      Messages                
Size    Size     Time         Okay Errors   Throughput
bytes   bytes    secs            #      #   10^6bits/sec

212992    1500   10.00      684876      0     821.85
212992           10.00      160754            192.90
```
```
Socket  Message  Elapsed      Messages                
Size    Size     Time         Okay Errors   Throughput
bytes   bytes    secs            #      #   10^6bits/sec

212992    1500   10.00      684719      0     821.66
212992           10.00      155436            186.52
```

I've updated my branch to also properly clean up the iptables rules I modified (multiple /etc/init.d/firewall reload should result in just one BCP38 chain)

**Comment by tohojo** [comment]
Awesome. In that case I'm fine with merging this. Could you add a version bump to the Makefile as well? Then we should be good to go :)

**Comment by edwintorok** [comment]
Should I bump `PKG_VERSION` or `PKG_RELEASE`? I'm not too familiar with how openwrt handles package versioning when the package contains just openwrt specific scripts.

**Comment by hnyman** [comment]
Core functionality changes, so bump the more major one, PKG_VERSION (from 4 to 5)

**Comment by edwintorok** [comment]
ok let me just test it one more time

**Comment by edwintorok** [comment]
k, version bumped and script looks good, thanks for the guidance.

**Comment by tohojo** [comment]
Looks good. Thanks! :)

**Pull request merged**
