### PR TITLE
Add OpenOCD embedded debugging software

### PR DESCRIPTION
**Pull request by paulfertser**

### CODE REVIEW

**Comment by champtar** [comment]
hi @paulfertser,

for now, hidapi is building, but
openocd is not building on my machine
```
cmsis_dap_usb.c:34:20: fatal error: hidapi.h: No such file or directory
 #include <hidapi.h>
                    ^
compilation terminated.
make[10]: *** [libocdjtagdrivers_la-cmsis_dap_usb.lo] Error 1
make[10]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/src/jtag/drivers'
make[9]: *** [all-recursive] Error 1
make[9]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/src/jtag/drivers'
make[8]: *** [all-recursive] Error 1
make[8]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/src/jtag'
make[7]: *** [all] Error 2
make[7]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/src/jtag'
make[6]: *** [all-recursive] Error 1
make[6]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/src'
make[5]: *** [all] Error 2
make[5]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa'
make[2]: *** [/tmp/openwrt-cc/build_dir/target-mips_34kc_uClibc-0.9.33.2/openocd-v0.8.0-258-gd537cfa/.built] Error 2
make[2]: Leaving directory `/tmp/openwrt-cc/feeds/packages/utils/openocd'
make[1]: *** [package/feeds/packages/openocd/install] Error 2
make[1]: Leaving directory `/tmp/openwrt-cc'
make: *** [package/openocd/install] Erreur 2
```

**Comment by paulfertser** [comment]
Can you please tell me what's wrong there? See what I have on my local machine, what might be different about yours?
```
paul@laptop ~/openwrt/openwrt-git/staging_dir $ find -name hidapi.h
./target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include/hidapi/hidapi.h
paul@laptop ~/openwrt/openwrt-git/staging_dir $ cat ./target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/pkgconfig/hidapi-libusb.pc 
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include

Name: hidapi-libusb
Description: C Library for USB HID device access from Linux, Mac OS X, FreeBSD, and Windows. This is the libusb implementation.
Version: @VERSION@
Libs: -L${libdir} -lhidapi-libusb
Cflags: -I${includedir}/hidapi
```

**Comment by champtar** [comment]
can you run ```find / -name hidapi.h```,
to be sure you don't have hidapi.h somewhere else

**Comment by paulfertser** [comment]
You're right; reproduced, working on a fix.

**Comment by paulfertser** [comment]
champtar, I've fixed hidapi makefile to produce a better pkg-config file. I noticed libftdi also comes with a broken .pc but somehow that doesn't manifest itself during the build, not sure why yet.

**Comment by champtar** [comment]
it's now building on ar71xx.
if you can provide a fix for libftdi, it would be great
In any case thanks @paulfertser

**Comment by paulfertser** [comment]
champtar, I took a look at libftdi brokenness some more, and figured out that:

1. pc file is broken but it doesn't break the build because ftdi.h header file gets installed to usr/include directly, not to a libftdi subdirectory as the pc file states, so even though the -I flag ends up bogus, including still works, as the file itself is in the default include search path;

2. The reason for the pc file ending up broken is what I guess a misuse of some CMake facilities or probably a CMake bug, not sure, since I do not like CMake much and do not feel like digging the details here on my own;

3. The packaged version is 0.20 which is from there old branch, all of the development happens on libftdi1 since long, so if something is worth fixing here, it should be fixed in the actual version, not the ancient. How do you actually notify an official OpenWrt package maintainer that he's packaging an old version? Is there some procedure or is it just wishful thinking that by adding MAINTAINER variable to the Makefile you deal with outdated software properly?

**Comment by dangowrt** [comment]
Also looks like libftdi1 is used rather than libftdi, build complains:
Package openocd is missing dependencies for the following libraries:
libftdi1.so.2

**Comment by paulfertser** [comment]
Hey,

Yes, indeed, OpenOCD autodetects libftdi1 presense and uses it if available. My oh my, I wonder why I had an impression OpenWrt provides only the old libftdi and haven't taken a look at libftdi1 package.

Thanks to Nico its pkgconfig file is fixed now, and everything builds fine after correcting dependencies properly in openocd, see github proprietary "pull request" #851 .

Who is supposed to notify libftdi1 upstream now with regard to the .pc file? Should I do it? Or will Álvaro handle communication with them?

**Comment by paulfertser** [comment]
BTW, where should I have looked to spot the build breakage on buildbots? I actually tried finding the logs even before you notified me of this libftdi1 problem and looked e.g. at http://buildbot.openwrt.org:8010/builders/ar71xx/builds/767/steps/compile_5/logs/stdio but couldn't find any mention of the relevant packages there. And yet two steps later I see e.g. hidapi getting indexed: http://buildbot.openwrt.org:8010/builders/ar71xx/builds/767/steps/compile_7/logs/stdio . So what is the proper way here?

**Pull request merged**
