### PR TITLE
fix 1631

### LINKED ISSUE #1631: Host python build miscompiling pyexpat, breaking e.g. glib2 build
Hello,

When python is selected in config, it's built for both host and the target, and the host version overwrites the symlink in `staging_dir/host/bin/` . This becomes problematic for glib2 as it uses pyexpat as part of its gio tests and OpenWrt's host python lacks pyexpat, see below why.

For both host and target python builds the in-tree copy of libexpat is used but for the host build it's not used properly, see the resulting command:

    gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -O2 -I/home/paul/openwrt-trunk/staging_dir/host/include -I/home/paul/openwrt-trunk/staging_dir/host/usr/include -I/usr/include/ncursesw -I/usr/include/ncurses -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_EXPAT_CONFIG_H=1 -DUSE_PYEXPAT_CAPI -I/home/paul/openwrt-trunk/build_dir/host/Python-2.7.10/./Modules/expat -I. -IInclude -I./Include -I/home/paul/openwrt-trunk/staging_dir/host/include -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/home/paul/openwrt-trunk/build_dir/host/Python-2.7.10/Include -I/home/paul/openwrt-trunk/build_dir/host/Python-2.7.10 -c /home/paul/openwrt-trunk/build_dir/host/Python-2.7.10/Modules/pyexpat.c -o build/temp.linux-x86_64-2.7/home/paul/openwrt-trunk/build_dir/host/Python-2.7.10/Modules/pyexpat.o

Due to the way how OpenWrt arranges host builds, `-I/home/paul/openwrt-trunk/staging_dir/host/include` appears earlier in the include path than `-I/home/paul/openwrt-trunk/build_dir/host/Python-2.7.10/./Modules/expat` and as the result pyexpat.o expects unprefixed function names while every object in Modules/expat exports python-namespaced function names. It's discovered only later when importing the module fails with `undefined symbol: XML_SetCommentHandler` which just happened to be the first function referenced. The build continues, just the resulting python lacks pyexpat.

Please feel free to contact me on IRC to discuss this in a more detailed way, if needed.

### PR DESCRIPTION
**Pull request by k0ste**
Signed-off-by: Konstantin Shalygin <kostya@opentech.ru>

### CODE REVIEW

**Comment by commodo** [comment]
Neat. 
So that does it  :)
The only thing now required is to update your patch a bit:
* please do not change indentation; ideally the change should be just the added line
* please update the commit title to something like : "python: add --with-system-expat for host python (fixes 1631)" ; this conforms to the guidelines on contributing
* (i am writing from my phone now but) if you did not add a "Signed-off-by", please add one. Also part of contribution guidelines. 

Thanks :)

**Comment by k0ste** [comment]
@commodo, sorry I really don't read CONTIBUTING.MD, cause I just want build openwrt, instead of this: 1 pull, 2 bugreports to my linux dirsto :). I fix remarks.

**Comment by sbyx** [comment]
Merged manually.

**Comment by commodo** [comment]
Thanks :)

**Pull request closed without merging**
