### PR TITLE
ddns-scripts: add dynu.com and bump pkg release

### PR DESCRIPTION
**Pull request by diizzyy**
Adds dynu.com as service and bumps pkg release

Signed-off-by: Daniel Engberg daniel.engberg.lists@pyret.net

### CODE REVIEW

**Comment by diizzyy** [comment]
@chris5560 
Updated pull reqs, sorry for the additional noise.
dynu.com doesn't seem to do IPv6 at all.

**Comment by chris5560** [comment]
Looks OK for me. Please merge.
Many Thanks.
Christian

**Comment by hnyman** [comment]
After merging the previous PR, there is now conflict with PKG_RELEASE.

Please either
 - remove the commit with version bump (as version was just bumped with your other PR)
 - fix version bump to be 2-->3 instead of 1-->3

**Comment by hnyman** [comment]
I applied manually the first commit as https://github.com/openwrt/packages/commit/7e38b9befebad6e4fed0ed53ac2085a2e326a9d8

**Pull request closed without merging**
