### PR TITLE
gnunet: Add libatomic dependency

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @dangowrt 
Compile tested: ath79

While I can't reproduce the error, this is what I've done previously to failing packages.

https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/gnunet/compile.txt

### CODE REVIEW

**Comment by diizzyy** [comment]
@neheb 
This is apparently an incorrect fix according to
https://github.com/openwrt/packages/issues/8086

**Comment by neheb** [comment]
Yeah. Maybe passing -latomic to LDFLAGS will fix it. I will take a look.

**Comment by neheb** [comment]
This is now fixed. @dangowrt

**Comment by neheb** [comment]
this was fixed

**Pull request closed without merging**
