### PR TITLE
netdata: update to version 1.30.0

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainers: me, @diizzyy
Compile tested: Turris MOX, mvebu/cortexa53, OpenWrt 19.07.7
Run tested: Turris MOX, mvebu/cortexa53, OpenWrt 19.07.7

Description:
- update to version [1.30.0](https://github.com/netdata/netdata/releases/tag/v1.30.0)

Screenshot from 2021-04-06 22-38-49

### CODE REVIEW

**Comment by neheb** [comment]
Should https://github.com/openwrt/packages/pull/14053 be merged first?

**Comment by BKPepe** [comment]
It's independent, and it waits until the commit itself is improved, so it is not a blocker and this can go through first.

**Comment by diizzyy** [comment]
There seems to be some brokenness from upstream such as https://github.com/netdata/netdata/issues/10891 so I think we should wait on next release.

**Comment by BKPepe** [comment]
Okay, I was not aware of it. Let's wait until there is a new release.

**Comment by BKPepe** [comment]
Updated to version [1.30.1](https://codeload.github.com/netdata/netdata/tar.gz/v1.30.1).

**Review by neheb — APPROVED** [review]

**Comment by diizzyy** [comment]
Still somewhat broken but it should work fine on Linux at least and we don't use the mqtt part afaik, LGTM

**Pull request merged**
