### PR TITLE
squid-4x: add package

### PR DESCRIPTION
**Pull request by ratkaj**
Maintainer: me / marko.ratkaj@sartura.hr / @ratkaj
Compile tested: LEDE master, mvebu/brcm2708/brcm63xx
Run tested: LEDE master, mvebu/brcm2708/brcm63xx

Description:
This is a Beta version of Squid that includes several new features that might be interesting to some people. We have been using this for a while now with no issues.

The most important of these new features are:

1. Configurable helper queue size
2. Helper concurrency channels changes
3. SSL support removal
4. Helper Binary Changes
5. Secure ICAP
6. Improved SMP support
7. Improved process management
8. Initial GnuTLS support

Hoping for a discussion and review.

Im also willing to backport some of the package changes and fixes to version 3.5.x stabile.

Signed-off-by: Marko Ratkaj <marko.ratkaj@sartura.hr>

### CODE REVIEW

**Comment by lucize** [comment]
using it almost since this PR with about ~200+ clients on a x86 machine, no problems so far

**Comment by diogosimao** [comment]
Is [squid-4x](https://github.com/openwrt/packages/pull/5196) available any where as [squid-3x](http://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/squid_3.5.27-1_mips_24kc.ipk)?

I would love to give it a try since I am experience major router slow down and pages won't load after starting squid and applying firewall rule.

**Comment by ratkaj** [comment]
Hi @diogosimao 

pull request wasn't merged but you can download the entire patch form this pull request and then apply it on your packages. Given it's popularity i will update the pull request as soon as i find the time. 

To reference your question from #4241
It should work well with ClamAV/SquidClamAV. I tested the same setup. ClamAV uses a lot of resources (RAM) so i hope you have some good hardware. I used ClearFog Base for testing this and it did work well.

Not sure about those instructions though, i didn't use them and I no longer have a backup of  my config.

**Comment by ratkaj** [comment]
Merged #6210 so i will close this.

**Pull request closed without merging**
