### PR TITLE
treewide: avoid deref symlinks when installing .so

### PR DESCRIPTION
**Pull request by yousong**
This is inspired by commit openwrt/openwrt@38b22b1e7022d6b386ce25f39d05cc33fc659240 .

Size reduction before compression is huge.

@openwrt/developer , We may need to patch INSTALL_XX to at least warn against symlinks.

```
-rwxr-xr-x 1 yousong yousong  33312 Jun  8 11:51 usr/lib/gnunet/libgnunet_plugin_psycstore_mysql.so
-rwxr-xr-x 1 yousong yousong  33312 Jun  8 11:51 usr/lib/gnunet/libgnunet_plugin_psycstore_mysql.so.0
-rwxr-xr-x 1 yousong yousong  33312 Jun  8 11:51 usr/lib/gnunet/libgnunet_plugin_psycstore_mysql.so.0.0.0
-rw-r--r-- 1 yousong yousong 251992 Jun  8 11:51 usr/lib/libdevmapper.so.1.02
-rw-r--r-- 1 yousong yousong  29088 Jun  8 11:51 usr/lib/libfstrm.so
-rw-r--r-- 1 yousong yousong  29088 Jun  8 11:51 usr/lib/libfstrm.so.0
-rw-r--r-- 1 yousong yousong  29088 Jun  8 11:51 usr/lib/libfstrm.so.0.1.0
-rwxr-xr-x 1 yousong yousong   8264 Jun  8 11:51 usr/lib/libi2c.so
-rwxr-xr-x 1 yousong yousong   8264 Jun  8 11:51 usr/lib/libi2c.so.0
-rwxr-xr-x 1 yousong yousong   8264 Jun  8 11:51 usr/lib/libi2c.so.0.1.1
-rwxr-xr-x 1 yousong yousong  62056 Jun  8 11:51 usr/lib/libloragw.so.0
-rwxr-xr-x 1 yousong yousong   5420 Jun  8 11:51 usr/lib/libnatpmp.so.1
lrwxrwxrwx 1 yousong yousong     19 Jun  8 11:51 usr/lib/libnetconf2.so -> libnetconf2.so.0.12
lrwxrwxrwx 1 yousong yousong     22 Jun  8 11:51 usr/lib/libnetconf2.so.0.12 -> libnetconf2.so.0.12.20
-rw-r--r-- 1 yousong yousong 182376 Jun  8 11:51 usr/lib/libnetconf2.so.0.12.20
-rwxr-xr-x 1 yousong yousong  86504 Jun  8 11:51 usr/lib/liboath.so
-rwxr-xr-x 1 yousong yousong  86504 Jun  8 11:51 usr/lib/liboath.so.0
-rwxr-xr-x 1 yousong yousong  86504 Jun  8 11:51 usr/lib/liboath.so.0.1.3
-rwxr-xr-x 1 yousong yousong  79000 Jun  8 11:51 usr/lib/libpagekite.so
-rwxr-xr-x 1 yousong yousong  79000 Jun  8 11:51 usr/lib/libpagekite.so.1
-rwxr-xr-x 1 yousong yousong  79000 Jun  8 11:51 usr/lib/libpagekite.so.1.0.0
-rwxr-xr-x 1 yousong yousong  49880 Jun  8 11:51 usr/lib/libprocps.so
-rwxr-xr-x 1 yousong yousong  49880 Jun  8 11:51 usr/lib/libprocps.so.7
-rwxr-xr-x 1 yousong yousong  49880 Jun  8 11:51 usr/lib/libprocps.so.7.1.0
-rw-r--r-- 1 yousong yousong 301720 Jun  8 11:51 usr/lib/libre2.so
-rw-r--r-- 1 yousong yousong 549928 Jun  8 11:51 usr/lib/libtins.so.4.0
-rw-r--r-- 1 yousong yousong  29136 Jun  8 11:51 usr/lib/libuhttpd.so
-rw-r--r-- 1 yousong yousong  29136 Jun  8 11:51 usr/lib/libuhttpd.so.2.2.1
-rw-r--r-- 1 yousong yousong  12496 Jun  8 11:51 usr/lib/lua/uhttpd.so
-rwxr-xr-x 1 yousong yousong  17072 Jun  8 11:51 usr/lib/moc/decoder_plugins/libffmpeg_decoder.so
-rwxr-xr-x 1 yousong yousong   4184 Jun  8 11:51 usr/lib/prosody/util/compat.so
-rwxr-xr-x 1 yousong yousong   8352 Jun  8 11:51 usr/lib/prosody/util/encodings.so
-rwxr-xr-x 1 yousong yousong   8396 Jun  8 11:51 usr/lib/prosody/util/hashes.so
-rwxr-xr-x 1 yousong yousong   4272 Jun  8 11:51 usr/lib/prosody/util/net.so
-rwxr-xr-x 1 yousong yousong   8392 Jun  8 11:51 usr/lib/prosody/util/poll.so
-rwxr-xr-x 1 yousong yousong  17088 Jun  8 11:51 usr/lib/prosody/util/pposix.so
-rwxr-xr-x 1 yousong yousong   8376 Jun  8 11:51 usr/lib/prosody/util/ringbuffer.so
-rwxr-xr-x 1 yousong yousong   8372 Jun  8 11:51 usr/lib/prosody/util/signal.so
-rwxr-xr-x 1 yousong yousong   4180 Jun  8 11:51 usr/lib/prosody/util/table.so
-rwxr-xr-x 1 yousong yousong   4192 Jun  8 11:51 usr/lib/prosody/util/time.so

```

### CODE REVIEW

**Comment by chunkeey** [comment]
I think $(INSTALL_BIN/DATA) might also change/force the files permissions to something, while $(CP) might not.

**Comment by yousong** [comment]
> I think $(INSTALL_BIN/DATA) might also change/force the files permissions to something, while $(CP) might not.

True.

_BIN and _DATA differ on the executable bit.  For dynamic libraries this does not matter much.

I think it's acceptable we trust upstream projects' build system to set proper permission bits, at least for now.  We can fix them case by case if needed.  But if bad permissions were put in place on purpose to compromise the system, it's a far bigger security issue of the open source ecosystem we operate in.

**Comment by neheb** [comment]
Actually, the libnatpmp change is wrong. There is only one file.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/pull/9236 does the same change

**Comment by yousong** [comment]
> Actually, the libnatpmp change is wrong. There is only one file.

The change was still made so that if people are to follow existing examples, they will be less likely to make the same mistakes.  Quote the paragraph in the commit message:

> Some of them do not have symlinks and are not affected, but the change
is still applied for consideration of best practices just in case

I think it's better we prevent this from happening by improving the build system.

/hold this pull request for now.

**Comment by yousong** [comment]
I downloaded all artifacts from circleci, then extracted and checked them with the following commands.  I think this pull is ready for merge.

```
find r -type l | while read l; do
        rl="$(readlink -f "$l")"
        if [ ! -f "$rl" ]; then
                echo "$l"
        fi
done

find r -type f -perm -002 | while read f; do
        echo "$l"
done
find r -type f -perm -020 | while read f; do
        echo "$l"
done
```

There are too much corner cases to cover when shadowing install command with a shell version.  That can be a maintenance burden.  I will find other ways to prevent this dups from happening again, something like checking the package content for dups.

**Comment by mhei** [comment]
What about this one:
```diff --git a/rules.mk b/rules.mk
index 80cb3d63f4..1e2415adc6 100644
--- a/rules.mk
+++ b/rules.mk
@@ -283,6 +283,7 @@ INSTALL_SUID:=install -m4755
 INSTALL_DIR:=install -d -m0755
 INSTALL_DATA:=install -m0644
 INSTALL_CONF:=install -m0600
+INSTALL_LIB:=cp -fpR --no-preserve=mode
 
 TARGET_CC_NOCACHE:=$(TARGET_CC)
 TARGET_CXX_NOCACHE:=$(TARGET_CXX)```

It copy, preserves the links and resets the file mode to 0644 (at least in my quick test). I'm not sure about umask interaction, but a quick test to change umask in shell when invoking make seems to make no influence to resulting file mode...

**Comment by neheb** [comment]
That will not work on buxybox cp.

**Comment by mhei** [comment]
Does this matter, i.e. do we use busybox cp for this or host's native cp?

**Comment by neheb** [comment]
Host. Alpine Linux uses busybox instead of GNU utilities.

**Comment by yousong** [comment]
> What about this one:
> 
> ```diff
> index 80cb3d63f4..1e2415adc6 100644
> --- a/rules.mk
> +++ b/rules.mk
> @@ -283,6 +283,7 @@ INSTALL_SUID:=install -m4755
>  INSTALL_DIR:=install -d -m0755
>  INSTALL_DATA:=install -m0644
>  INSTALL_CONF:=install -m0600
> +INSTALL_LIB:=cp -fpR --no-preserve=mode
>  
>  TARGET_CC_NOCACHE:=$(TARGET_CC)
>  TARGET_CXX_NOCACHE:=$(TARGET_CXX)
> ```
> 
> It copy, preserves the links and resets the file mode to 0644 (at least in my quick test). I'm not sure about umask interaction, but a quick test to change umask in shell when invoking make seems to make no influence to resulting file mode...

Umask 022 was set by build system before each invoke of submake.

There are cases where people depend on the link-deref behavior of install command to install only the sonamed file.  That is valid use case and can actually save space.

**Comment by yousong** [comment]
Thanks for your suggestions!

**Pull request merged**
