### PR TITLE
apache: fix compilation without deprecated OpenSSL APIs 

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1

### CODE REVIEW

**Comment by neheb** [comment]
ping @cotequeiroz OpenSSL patch has been in my tree for a long time. Does it look reasonable?

**Comment by BKPepe** [comment]
Is it run tested? Last time, I tried it, I was not able to run it, because of https://github.com/openwrt/packages/issues/4840.

**Comment by cotequeiroz** [comment]
I've looked at the patch, and it seems fine.

I agree with @BKPepe that this needs run-testing.

This package appears to have only experienced apache users in mind.  It is not reasonably easy to setup  in its current form.

I'm assuming you'll need to come up with a working config file to be able to run-test it.  So, consider adjusting the initial config file so that it runs when installed.  Or, if it is safer to not have a working config, then it may be worth to add a comment to an otherwise working config file, and have it deliberately fail with a `You_need_to_configure_this_fist` line or something of the sort.

**Comment by neheb** [comment]
ping @lucize since it seems he uses it

**Comment by lucize** [comment]
I switched from it in using haproxy and/or nginx but I could try a run test

**Comment by neheb** [comment]
A small note: The current version in the tree seems to have been pulled. This is what I'm currently getting during compilation:

```
SHELL= flock /home/mangix/devstuff/openwrt/tmp/.httpd-2.4.37.tar.bz2.flock -c '         /home/mangix/devstuff/openwrt/scripts/download.pl "/home/mangix/devstuff/openwrt/dl" "httpd-2.4.37.tar.bz2" "3498dc5c6772fac2eb7307dc7963122ffe243b5e806e0be4fb51974ff759d726" "" "@APACHE/httpd/"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror.netcologne.de/apache.org/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror.aarnet.edu.au/pub/apache/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror.csclub.uwaterloo.ca/apache/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://mirror.cogentco.com/pub/apache/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://mirror.navercorp.com/apache/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://ftp.jaist.ac.jp/pub/apache/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure ftp://apache.cs.utah.edu/apache.org/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (78) RETR response: 550
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure ftp://apache.mirrors.ovh.net/ftp.apache.org/dist/httpd/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to apache.mirrors.ovh.net port 21: Connection refused
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/httpd-2.4.37.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6866k  100 6866k    0     0  1081k      0  0:00:06  0:00:06 --:--:-- 1501k
```

**Comment by lucize** [comment]
@neheb 
so for now I've got this:
`AH00136: Server MUST relinquish startup privileges before accepting connections.  Please ensure mod_unixd or other system security module is loaded.
`
it needs mod_unixd.so to be included in the build, but I'll test more

**Comment by neheb** [comment]
It's interesting that this package does not install any of the mods...

**Comment by p3g4asus** [comment]
Tested this version. The debug log output is similar to the previous releases, including proxy part. It still produces segmentation faults. So no change for #4840.

**Comment by Matux95** [comment]
Sorry to late to access now, you should have done Yyyy alphabet times

**Comment by Matux95** [comment]
66666*

**Comment by neheb** [comment]
ping @micmac1 I changed the pull request to only add the deprecated API change as the new version was merged.

**Comment by neheb** [comment]
```
Package apache is missing dependencies for the following libraries:
libgdbm.so.6
```

Someone messed up.

**Comment by micmac1** [comment]
Hi Neheb, everybody,

Apart from run-testing, I'd like for this patch to make it upstream first. Some may think that's a bit conservative :)

In my opinion there's no benefit for the user. Best case is the user doesn't realize any difference (stuff just works), so, no change for the user. Any other case -> OpenSSL troubles. That's why I think there's not much of an upside including this.

The upside in my view would be to get this patch upstream, where it gets proper review and testing. And afterwards everybody benefits when this is resolved and one day in the future some deprecated symbols may be removed from OpenSSL.

I understand that opinions will be different for other people. And as you and others may know better _and_ have write access to this repo (which I don't have) I accept that somebody may override and apply this patch. I can promise you there won't be any hard feelings from my side. :)

Kind regards,
Seb

**Comment by neheb** [comment]
Rebased.

**Comment by neheb** [comment]
I'll merge. I'm sick and tired of having this in my branch. I'll see about upstreaming when I can.

Note that I've upstreamed most of these changes in other projects.

**Comment by BKPepe** [comment]
Sorry, but if you are sick and tired of having this in your branch, but you could upstream it and we don't need to have carry patch *until* you upstream it and I am not satisfied with neither with "I'll see about upstreaming when I can". That's not a good approach at all. Even maintainer said to you that it should be upstreamed and you are still merging this. So... we don't need to have maintainers at all.

**Pull request merged**
