### PR TITLE
rp-pppoe: fix typo

### PR DESCRIPTION
**Pull request by zhaojh329**
Signed-off-by: Jianhui Zhao <zhaojh329@gmail.com>

Maintainer: nobody
Compile tested:
Run tested:

Description:

### CODE REVIEW

**Comment by feckert** [comment]
thanks

**Comment by BKPepe** [comment]
Where is bump of `PKG_RELEASE`?

**Comment by zhaojh329** [comment]
> Where is bump of `PKG_RELEASE`?

I'm sorry, I forget.

**Comment by BKPepe** [comment]
Fixed in https://github.com/openwrt/packages/commit/af93af4a4fa279dc5a3077832ac484ca769eada9

**Pull request merged**
