### PR TITLE
transmission: split packages depending on selected cryptography library

### PR DESCRIPTION
**Pull request by obsy**
Signed-off-by: Cezary Jackiewicz <cezary@eko.one.pl>

### CODE REVIEW

**Comment by hnyman** [comment]
I applied the patch manually and the seven packages do get built.

But the TITLE explanations are so long that they are not shown properly in menuconfig. I propose that you delete the "A free, lightweight" advertisement from the default title leaving just "Bittorrent client", and shorten the polarssl/openssl explanations to just " (with PolarSSL)" style. Then menuconfig shows the title properly.

The web interface (?) package is missing the TITLE += addition.
I tried this:
```
  TITLE+= (web interface) 
```

**Comment by obsy** [comment]
Ok, I made these changes. Thanks.

**Comment by hnyman** [comment]
Well, this change causes a missing dependency on the Luci side:
luci-app-transmission has depended on transmission-daemon, which does not exist any more (as it was split to -openssl and -polarssl). Thus luci-app-transmission can't be installed.

I will remove the dependency from there, but that will then create the need to install transmission itself and luci-app separately.

**Comment by hnyman** [comment]
Luci fixed by https://github.com/openwrt/luci/commit/4612c241d276d7f4b3bb8919b0f3319bf525c237

**Comment by obsy** [comment]
Hmm, transmission-daemon-{polarssl,openssl} provides transmission-daemon, should be working. Or depends on sth like polarssl || openssl

**Comment by hnyman** [comment]
It has been a "selects" dependency that has pulled the transmission-daemon along the Luci app. Now there are two equal choices for the daemon package, and there is no way to know which variant the user wants to be installed.

(The same situation is with luci-app-openvpn, and also there the dependency has been left empty.)

**Comment by dfc-d** [comment]
You can uses PROVIDES:=transmission-daemon on both packages and depend
on +transmission-daemon.  Of course PROVIDES needs a fix in trunk to
select the non-default option if using IB, but that's a separate
issue... (IB sorts the lists of packages the user supplies which means
that the package the user supplies is installed as well as the default
one, unless the sort happens to put the user supplied one first).

Regards,

Daniel

**Pull request merged**
