### PR TITLE
rp-pppoe: Add back from oldpackages with build fixes and enhanced pac…

### PR DESCRIPTION
**Pull request by dfc-d**
…kaging

Add back from oldpackages with fixes for build errors and UCIfication
(for future LuCI app).

Signed-off By: Daniel Dickinson

### CODE REVIEW

**Comment by dfc-d** [comment]
Marked relay as broken (as untested) the same as already done with client and was intended for relay.

**Comment by yousong** [comment]
I'd like to suggest that we use "thinner" uci layer for such services.  UCI can be useful for fitting third-party programs into OpenWrt environment, e.g. procd service management, netifd interface event trigger, stdout/stderr logging etc.

But in my opinion another full-fledged layer for translating every single options of those original services is overkill and serves not much good.  Usability is also hurt because many times users will need to consult both the original services manual and uci config manual (and/or service script) to find the correspondence.

In the case of pppoe-server, since it only accepts command line options and does not support parsing a config file, I would suggest we just add a single uci option `args` for those arguments, or `list arg "xxx"` and concatenate in the service script.  just my two cents :)

**Comment by dfc-d** [comment]
My reasoning is that I intend to add a LuCI app - just args isn't the way to do that.

**Comment by dfc-d** [comment]
Ultimately you are right that uci for the sake of uci doesn't make sense; but for integration with LuCI or other automated processing, a full layer is what is needed.

**Comment by jow-** [comment]
The very existence of the rp-pppoe-client caused some confusion among users in the past - do we actually need it or is the existing ppp-mod-pppoe good enough for all PPPoE client needs?

If so I'd suggest to keep server and relay but not the client.

**Comment by dfc-d** [comment]
Reprioritizing my project queue and this didn't make the cut.  Leaving branch intact in case someone wants to revive it.

**Pull request closed without merging**
