### PR TITLE
freeradius3: Enable the EAP-PWD module.

### PR DESCRIPTION
**Pull request by Robby-**
Maintainer: @LucileQ
Compile tested: ARM, Linksys EA3500, master
Run tested: ARM, Linksys EA3500, master, tests: successful authentication using EAP-PWD

Description:
This enables the EAP-PWD module, which allows for logging in with only
a username and password, while still being secure (see the links below
for the details of this EAP method, if interested).

https://en.wikipedia.org/wiki/Extensible_Authentication_Protocol#EAP_Password_(EAP-PWD)

Also found this blog post which talks about EAP-PWD and its benefits:
https://dustri.org/b/eap-pwd-wifi-security-done-right.html

### CODE REVIEW

**Comment by Robby-** [comment]
@cotequeiroz: Hi, thank you, I have fixed the DCO issue. Travis is still failing, but looking at the log of it shows that its because of other commits, unrelated to mine. Not much I can do about that.

I mentioned you as package maintainer because the PR template said to check the [history of the Makefile](https://github.com/openwrt/packages/commits/master/net/freeradius3/Makefile) and Lucile's name wasn't a GitHub username, so I just took the most recent username instead. Thank you for telling me the correct username. I will change it.

**Comment by Robby-** [comment]
It turns out I was able to make Travis happy as well after all.

**Comment by alexshpilkin** [comment]
@cotequeiroz Is this blocked on @LucileQ?

**Comment by cotequeiroz** [comment]
There is no response.  @hnyman, can you please take a look at this?

**Pull request merged**
