### PR TITLE
dawn: fix x86 compiling

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Fixes: #12410

### CODE REVIEW

**Comment by BKPepe** [comment]
Compiled & run tested?

**Comment by PolynomialDivision** [comment]
> Compiled & run tested?
Yes. ;)

**Comment by neheb** [comment]
This is the only change: https://github.com/berlin-open-wireless-lab/DAWN/commit/2151db28ef24c856be1ffad836a7d20afdd9fba1
 
No real change.

**Comment by BKPepe** [comment]
I think that this still does not explain, why if there is pull request template it gets removed each time and there are just fixes or changelog.

**Pull request merged**
