### PR TITLE
libgpiod: update to 1.6.3

### PR DESCRIPTION
**Pull request by mhei**
Maintainer: me
Compile tested: mxs
Run tested: mxs

Signed-off-by: Michael Heimpold <mhei@heimpold.de>

### CODE REVIEW

**Comment by neheb** [comment]
Was this the project that needed kernel 5.5 and above or was that something else?

**Comment by mhei** [comment]
Yes, you're right. At least, this was my understanding, too. I'm just wondering, that it actually compiles without warnings and also runs on the target with kernel v5.4.94.
I'd mark this PR as draft for now, I'd study the sources once again just be sure that this is expected behavior...

**Comment by neheb** [comment]
There's also version 1.4.5. Could update to that

**Comment by john-tho** [comment]
> it actually compiles without warnings and also runs

I saw that libgpiod 1.6.2 includes a commit that allows compiling with older kernel headers:
https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/commit/?h=v1.6.x&id=325873cf2e9b85550e296a00d44c5a56aaf475bd
```
+ * These are symbols first available in linux v5.5. In order to allow to build
+ * libgpiod with kernel headers as early as v4.8 we redefine them here for pre
+ * v5.5 build environments. Certain features will not work on older kernels.
```
1.6.3 and 1.4.5 are the current versions now

**Comment by neheb** [comment]
Makes sense.

**Comment by mhei** [comment]
Will have a look.

**Comment by mhei** [comment]
Compile and run tested on mxs platform with both kernel 5.4 and 5.10.

**Review by neheb — APPROVED** [review]

**Pull request merged**
