### PR TITLE
django1: Rename django1-restframework, add python3-django1

### PR DESCRIPTION
**Pull request by jefferyto**
Maintainer: @commodo, @cotequeiroz, @peter-stadler 
Compile tested: armvirt-64, 2020-02-03 snapshot sdk
Run tested: armvirt-64, 2020-02-03 snapshot (run tested `django-admin` only)

Description:
76a07cb: django1-restframework: Rename to django-restframework39, add Py3 package

8b36cfb: django1: Add python3-django1 package

This adds a Python 3 version of the django1 package.

This also adds a python-django1-common package that contains a `django-admin` script based on [the one in Debian][1]. This allows python-django1 and python3-django1 to be installed at the same time.

python3-django conflicts with python-django1 (via python-django1-common) and python3-django1.

This also updates older Python 3 Django plugin packages to depend on python3-django1, and newer plugin packages to depend on "django", which both python3-django and python3-django1 provide.

Because of this dependency on either version of Django, the `MDEPENDS` for Python 3 Django plugin packages no longer functions correctly and has been removed.

[1]: https://salsa.debian.org/python-team/modules/python-django/blob/debian/buster/debian/django-admin

### CODE REVIEW

**Comment by jefferyto** [comment]
Regarding renaming django1-restframework: Apologies for not commenting on #11179 before it was merged. The naming was too confusing for me and not sustainable after adding python3-django1. Both versions of restframework are compatible with both versions of Django.

Regarding adding python3-django1: This is very similar to @commodo's work in #11084.

While I know that Django plans to end extended support for 1.11 in April, I don't believe seafile will be updated to use a newer version of the framework by then. I would rather do extra work to move seafile to Python 3 now, then move it to a newer Django later (whenever that happens).

**Comment by jefferyto** [comment]
FYI I also plan on updating seafile-seahub to 7.1.1 beta (which includes the switch to Python 3) after this, then updating it again to a stable 7.1 version when it is released.

**Comment by commodo** [comment]
generally speaking: i feel this is getting a bit out-of-hand with intermediate packages;

and all this to accommodate seafile [which, I feel] is a pretty bad piece of SW **[1]**; and I know I maintain it, but I did not know how bad it is when I took it over;
and I am not saying this to offend anyone, but it is what I feel, and after some attempts to try to work with it, I came to this conclusion;

maybe we should approach this from a different perspective;
rather than making all Py2/Py3/Django1/Django/Django-Restframework packages work, we should probably just package/build seafile into it's own build and install everything under some /opt folder as the maintainers intended to;
[same is done for RPi]
see recommended directory layout: https://download.seafile.com/published/seafile-manual/deploy/using_sqlite.md#user-content-Deploying%20and%20Directory%20Layout

it looks to me that trying to use the common packages/stuff for seafile is getting more difficult as they are still sticking to Django 1.11 [and now it's at Django 3];
and now we are probably getting people who would want newer Django stuff, but we can't support well, because of the distribution of effort we have with making everything also work with seafile;

bottom line [from my side is]:
1. I would NACK this change; and just wait until April and see from there; I admit that I started the Django/Django1 splits, but I did not think we would get quite in this state;
2. If anyone wants to replace me as maintainer for all Seafile and all Django stuff + whatever required packages for Seafile [libzdb, bash, sudo, etc], I am also willing to give away my maintainer role for it [with no hard feelings or anything]; but this would unblock things before April :)

**[1]** I have some arguments about why I feel seafile is bad:
* for once, just looking at their commits, a lot of them are just things being thrown into the repo without much discussion; some random examples:  https://github.com/haiwen/seahub/pull/4370  https://github.com/haiwen/seahub/pull/4367  https://github.com/haiwen/seahub/pull/4382
* just the amount of effort spent trying to upgrade stuff without breaking seafile is not worth it;
* even so, i am somewhat optimistic that Seafile would improve over time, but currently just upgrading it is difficult, since they rarely upgrade their base Django stuff;

**Comment by peter-stadler** [comment]
I did not look into the details, will do that later/tomorrow ...

The renaming is fine for me, `django-restframework39` is clearly better :-)

Regarding seafile: Has anyone installed it? I was not able to run it the last time I tried (before and after #11179): It complained about a dependency and after installing that about missing tables in the database, I gave up after creating one. Maybe it is working if the DB was created with an old version ...
Botttom line: For me it is good to put all seafile stuff in an opt folder and/or the update to the beta.

**Comment by jefferyto** [comment]
@commodo Honestly I don't really care about Seafile, but I want to remove Python 2 as quickly as possible after 31 March. I don't want to keep Python 2 around to wait for Seafile to update their Django dependency.

When April comes, all Python 2 packages will be removed and there will only be two versions of Django (python3-django and python3-django1) and one version of all Django plugins (python3-django-*, which can work with either version of Django). The intermediate steps may be complicated but they are intermediate only (and is work that can be done now instead of waiting for some indeterminate time later).

BTW [seafile depends on djangorestframework](https://github.com/haiwen/seahub/blob/v7.1.1-server/requirements.txt#L14) but it doesn't specify a version. (In fact only Django is pinned to a specific version.) It may work with 3.11 and we can get rid of 3.9, I don't know, but right now I'm just trying to get to Python 3 first.

I'm sorry this is complicated, but I am using my time to make this happen. Please trust me, I usually know what I am doing :joy:

If you want to remove seafile completely or move it into a self-contained version, that's ok too; I will mark all seafile packages as "Won't Fix" in #8893 and expect the packages to be removed starting 1 April.

You are also free to remove yourself as maintainer if you no longer have the time or interest. There are other packages in the feed with no maintainer. (I don't have the time or interest to take over, I just want to move it to Python 3.)

**Comment by peter-stadler** [comment]
Please note: [restframework39](https://pypi.org/project/djangorestframework/3.9.4/) works with django 1.11 -- 2.2 not 3.xt

**Comment by jefferyto** [comment]
Thanks @peter-stadler - I've updated gone through each Django plugin and adjusted the dependencies where appropriate. Basically, all of the Django plugins used for seafile are older versions that were released before Django 3 was available, so I have made them depend on python3-django1 instead of django. I plan on updating these packages with current versions after this PR and also adjusting the dependencies where possible.

I wanted to ask you about python3-drf-nested-routers: I have left it unchanged (in this force push), but the package/currently released version (0.91) is quite old as well. From it's [readme](https://github.com/alanjds/drf-nested-routers/tree/v0.91.0#requirements--compatibility) it doesn't appear to be compatible with Django 3 or djangorestframework 3.9/3.11. Do you know which versions it is compatible with?

**Comment by peter-stadler** [comment]
There is no newer release, but it seems to be on the way for [official support](https://github.com/alanjds/drf-nested-routers/compare/fix-drf311) of django-restframework 3.11: If I understand that branch right, it fixes only wrong user code. So there should be no real need to update that fast ...
Currently it is used only for etesync-server; I experienced no problems with it.

**Comment by jefferyto** [comment]
I see, thanks again @peter-stadler - I will leave drf-nested-routers as it is.

**Comment by commodo** [comment]
Hmmm.
New plan proposal:
1. mark seafile as BROKEN
2. cleanup deps for Django
3. i'll continue working on it to make it self-contained;

**Comment by jefferyto** [comment]
I guess I didn't say this before, so I'll say it now: I think making seafile a self-contained package/app is a mistake.

By making an app self-contained, that means the app maintainer is committing themselves to not just updating the app but also all of its dependencies. For example, when there is an update to python-cryptography, is it better for the maintainer of that package to update it once, or for all maintainers of apps to update it in their self-contained apps? Who is going to be more alert on updates and security fixes?

(Yes, I know that's how they do it in the Go world and I'm the Go maintainer here, but that doesn't mean I think they are right.)

I also don't think the people who make seafile are saying users should install it in a self-contained way (if it suppose to be self-contained, then their tarballs would contain all dependencies and they would not ask users to install dependencies through pip). Python programs in general are not designed or developed to be self-contained (yes there is virtualenv, but it creates separate "worlds" for programs, the programs themselves are not developed any differently). I don't know of any major distros that have Python apps in their package repos that are self-contained.

Yes, seafile has a lot of dependencies, but we are in the middle of the updating process. When this process is finished, all of the Django plugin packages can/should be upgraded to their latest versions, making them usable for other Django programs. There will be two Django packages, one if seafile updates to the newest Django later on. There will only be Python 3 packages.

Maybe there is something I am missing? Can you explain why you feel it is complicated?

If you want to proceed with your plan, I can't stop you, you are the maintainer. But I presume you are trying to make seafile work / keep it working, because there are people who use it. Marking it as broken / having it be broken when Python 2 is removed, this doesn't help them.

**Comment by commodo** [comment]
> Maybe there is something I am missing? Can you explain why you feel it is complicated?

I guess, the only way to explain, is to let you have a few cracks at it  [i.e. seafile] :)

We are disagreeing a bit on how to do things:
1. I wanted to upgrade Seafile and eliminate some [Django] Py2 variants [now] - where you are somewhat disagreeing
2. You want to keep [or add more] Py2 variants [now] until April, and then upgrade Seafile - where I am somewhat disagreeing
3. I would be fine to wait until April, when we can drop all the Py2 variants - from my side, I am don't understand the rush to upgrade Seafile now, but ok ¯\_(ツ)_/¯

Anyway, I would say: first try to do the whole upgrade of Seafile + Py3 conversion, and when that is ready, it becomes more obvious about this change.
Without the Seafile upgrade, I am not sure how much of this change is good or not.

There was also a mention:

> FYI I also plan on updating seafile-seahub to 7.1.1 beta (which includes the switch to Python 3) after this, then updating it again to a stable 7.1 version when it is released.

I can guess, there was no attempt to do it yet :)
Feel free to try, and use some of my existing work

This one updates to 7.1.1: https://github.com/commodo/packages/commits/seafile-update3
There are a few other seafile bits left over from other time: https://github.com/commodo/packages/branches/all?utf8=%E2%9C%93&query=seafile

**Comment by jefferyto** [comment]
> We are disagreeing a bit on how to do things:

So the basic disagreement is, you want to add Py3 variants and drop Py2 variants at the same time (it doesn't matter to you if this happens now or later), I want to Py3 variants now and drop Py2 variants later.

There was a giant discussion in #8520 about the transition plan. I don't recall you raising this issue when the plan was under discussion.

I don't see any functional difference between adding and dropping variants at the same time or separately. Doing both at the same time feels better (for you as the developer) but increases the risk of something breaking (which impacts the user).

Give me a logical reason why adding and dropping variants must happen at the same time, please.

Perhaps I should have been more explicit about the expectations of transitioning programs to Py3 before the 31 March deadline. (Honestly I wish I had set up an earlier deadline for programs.) I have been hounding people on #8893 about this since last May.

The rush is I want to get #8893 done, so that I can start planning on how to remove Python 2 as quickly and safely as possible starting on 1 April. (No, it will not be one giant PR where we remove everything at once. It will happen in stages, basically multiple giant PRs, where hopefully there are no broken dependencies between each stage.) I can't start this planning when there are still programs in the repo that use Python 2 (i.e. seafile, but node and nmap are still in progress).

(There is also an [abandoned packages feed](https://github.com/openwrt/packages-abandoned). Python 2 packages will go there, not just dropped without a trace.)

You're only seeing your own packages (seafile, django); I'm concerned about the Py3 transition for the whole project. I've been willing to manage this project-wide process on my own but I never thought I would need to fight the other Python maintainer on this.

> first try to do the whole upgrade of Seafile + Py3 conversion

I am trying to do this conversion. It can't happen without python3-django1, but you won't allow adding python3-django1 without also dropping python-django1 at the same time.

> I can guess, there was no attempt to do it yet :)

I am already working on it, but honestly I'm ready to stop and give up arguing with you about this.

**Comment by commodo** [comment]
I'm sorry that I upset you.
I do appreciate all the work the you are doing.

Please finish upgrading Seafile and let's re-discuss then.

**Comment by neheb** [comment]
I'm confused about this PR. Is this made to keep seafile working after the Python 2 removal?

If so, I would much rather remove seafile and then reintroduce it. The package as it exists today is a complete mess. Example:

https://github.com/openwrt/packages/blob/master/net/seafile-server/Makefile#L42

I bet most of those dependencies are bogus. I also do not like the bash dependency one bit. I would patch it out and fix the bashisms with shellcheck.

Another example:

https://github.com/openwrt/packages/blob/master/libs/libzdb/Makefile#L37

This library depends on three separate SQL libraries while seafile AFAIK only uses MariaDB.

**Comment by commodo** [comment]
> I'm confused about this PR. Is this made to keep seafile working after the Python 2 removal?

Yep [in part].
It's also a transient state until we get to that point. i.e. new packages are added [for seafile] that will later be unused [by seafile]

> If so, I would much rather remove seafile and then reintroduce it.

I also agree that seafile is a mess, and I did not know how messy it is before taking it.
Not sure if removing it [as a temporary measure] is a good idea.
I think, it's either we remove it [completely], or move it to the abandoned-packages [I only found out here that we have this], or try to fix it.

> The package as it exists today is a complete mess. Example:
> 
> https://github.com/openwrt/packages/blob/master/net/seafile-server/Makefile#L42

Those dependencies in that list [unfortunately] are fine as-they-are [for the most part]. Seafile is a messy project itself, and trying to package it reflects that mess.

> I bet most of those dependencies are bogus.

Maybe one or two are bogus/left-over; but for the most part, they are needed.

> I also do not like the bash dependency one bit. I would patch it out and fix the bashisms with shellcheck.
> 

bash is needed. I have started to patch-it-out, but it's low on my list, since migrating it to Py3 is a bit higher, since there are more Python & Django packages that it needs.
I'm also a bit afraid of patching-it-out via shellcheck; shellcheck is good for static-bash analysis, but it still needs testing. To account for the stuff where `ash` differs.


> Another example:
> 
> https://github.com/openwrt/packages/blob/master/libs/libzdb/Makefile#L37
> 
> This library depends on three separate SQL libraries while seafile AFAIK only uses MariaDB.

I did not have time to look over libzdb.
Seafile takes enough energy as-is with Python & Django and this whole 2-to-3 conversion and the disagreements we've had so far.

To re-conclude a bit:
* seafile is pretty bad to maintain; it may get better, but who knows [when]?
  * seahub is the bad one here requiring most deps; it's typical for many big Python projects, but a lot of times you just rely on `pip` ; OpenWrt doesn't [based on what i know] have many big Python projects as Seafile [seahub module]
* i'm fine to keep maintaining Seafile as-is in the hopes things would slowly get better;
  * i also don't like the fact that they ignore my single-simple PR https://github.com/haiwen/seahub/pull/3607  ; no feedback whatsoever
  * if Seafile is too much hassle for the OpenWrt packages ecosystem, I am also fine to take it out and move it to abandoned; but it's likely I would also abandon it [I know how this sounds]
* as always, if anyone wants to take this over, I am also fine with giving it away :)

**Comment by commodo** [comment]
well, i didn't agree with this PR
but no stress if it's merged  ¯\_(ツ)_/¯

**Comment by jefferyto** [comment]
While I do want this to be merged, I don't think it should have been merged without approval from the maintainer.

**Pull request merged**
