### PR TITLE
snort3: update to 3.1.48.0-1

### PR DESCRIPTION
**Pull request by graysky2**
Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

Signed-off-by: John Audia <therealgraysky@proton.me>

Maintainer: @flyn-org 

This should be merged before https://github.com/openwrt/packages/pull/19989

### CODE REVIEW

**Comment by flyn-org** [comment]
Do you have any idea what happened to the arm_cortex-a9_vfpv3-d16 build? The last update (https://github.com/openwrt/packages/actions/runs/3567274808/jobs/5994764026) built fine, but this one failed.

**Comment by graysky2** [comment]
@flyn-org - it seems inconsistent as you point out.  I have no insights into the build checks.

**Comment by 1715173329** [comment]
It's caused by the commit https://github.com/snort3/snort3/commit/795105e3859042a019f7bb743e88559814a39340.

> \# we use '+' as a separator for 'sed' to avoid conflicts with '/' in paths from LEXER_OUT

sadly we also have a '+' in folder name: `build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi`

**Comment by graysky2** [comment]
Nice piece of detective work, @1715173329 
What if i change the '+' to a '|' for our stuff?

**Comment by graysky2** [comment]
> edit: I guess this change can be upstreamed?

I don't see why not?

**Comment by graysky2** [comment]
@1715173329 - good to merge?

**Comment by 1715173329** [comment]
lgtm, but can you create a PR to upstream for this change ;)

**Comment by graysky2** [comment]
> lgtm, but can you create a PR to upstream for this change ;)
https://github.com/snort3/snort3/pull/281

**Pull request merged**
