### PR TITLE
bandwidthd: Update to 2.0.1-35

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @padre-lacroix 
Compile tested: mvebu

### CODE REVIEW

**Comment by neheb** [comment]
Travis timed out. Should be good though.

**Comment by padre-lacroix** [comment]
There is no difference between 2.0.1-34 and 2.0.1-35 in the source code.  2.0.1-35 was for a new package for Centos 7, which is irrelevant for OpenWrt. 
The resulting executable is identical, therefore this commit serves no purpose!

**Comment by neheb** [comment]
Except it does make uscan happy :)

**Comment by padre-lacroix** [comment]
If it makes uscan happy, then I guess that it does not hurt to update!

**Pull request merged**
