### PR TITLE
openfortivpn: update to 1.22.1

### PR DESCRIPTION
**Pull request by maurerr**
Maintainer: me
Compile tested: x86
Run tested: x86

### CODE REVIEW

**Comment by 1715173329** [comment]
cc maintainer @lucize

**Comment by lucize** [comment]
LGTM

**Comment by 1715173329** [comment]
CI says:
> Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Marius Durbaca <maurerr@users.noreply.github.com>')

Please update your commit.

**Comment by maurerr** [comment]
> CI says:
> 
> > Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Marius Durbaca [maurerr@users.noreply.github.com](mailto:maurerr@users.noreply.github.com)')
> 
> Please update your commit to use real email.

well my commit is signed-of using my real email - that's just github CI playing tricks

**Comment by 1715173329** [comment]
https://github.com/openwrt/packages/commit/25c4eed6a137d730f47f41ec576d515929fdcb46.patch

> From: Marius Durbaca <maurerr@users.noreply.github.com>

**Comment by maurerr** [comment]
got it - thanks @1715173329

**Comment by 1715173329** [comment]
Merged, thank you!

**Pull request merged**
