### PR TITLE
prometheus-node-exporter-lua: update dawn exporter

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add dawn exporter to Makefile.
Add hostname to export.

Maintainer: @champtar 
Compile tested: 621297e86736556f772a3a1e3907c4ad9223bd74
Run tested: r14034-b735bbc

### CODE REVIEW

**Comment by aparcar** [comment]
So the dawn exporter was already there but not installable?

**Comment by PolynomialDivision** [comment]
> So the dawn exporter was already there but not installable?

Seems like it. Not sure if I wrote the dawn exporter myself and never installed it via opkg again.

**Comment by neheb** [comment]
```
schedule.c:359:36: error: 'SIOCGSTAMP' undeclared (first use in this function); did you mean 'SIOCGARP'?
     ioctl(pb.i.iif->rx_mcast_sock, SIOCGSTAMP, &(pb.i.tv_stamp)) ;
                                    ^~~~~~~~~~
                                    SIOCGARP
```

I swear I had a patch for this...

**Comment by aparcar** [comment]
I guess this fails individually of this PR, so I'm okay merging it and @neheb you add the patch once you find it?

**Comment by neheb** [comment]
Yeah it was merged in the routing repo. This needs a rebase. Or a rerun?

**Comment by PolynomialDivision** [comment]
> Yeah it was merged in the routing repo. This needs a rebase. Or a rerun?

I can rebase. 1s

**Comment by PolynomialDivision** [comment]
Can I somehow fix this lint code base check?

**Comment by neheb** [comment]
I don’t know any Lua so I can’t help there.

**Comment by neheb** [comment]
https://github.com/openwrt/packages/blob/c9bba5b6f1f0f9727aa2fefa2e94e4fad4a87691/utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/dawn.lua#L38

Rename as it shadows another variable of the same name above.

**Comment by neheb** [comment]
Some of those lua files begin with #!/usr/bin/lua . That's interesting.

**Comment by PolynomialDivision** [comment]
But I still have those erros:
```
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/dawn.lua:4:52: accessing undefined variable metric
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/dawn.lua:5:41: accessing undefined variable metric
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/dawn.lua:6:42: accessing undefined variable metric
```

**Comment by neheb** [comment]
Those are an issue with the linter probably.

**Comment by PolynomialDivision** [comment]
Thx.

**Pull request merged**
