### PR TITLE
p910nd: set bidi only if not already set

### PR DESCRIPTION
**Pull request by systemcrash**
Fixes: https://github.com/openwrt/packages/issues/23774

### CODE REVIEW

**Comment by systemcrash** [comment]
@BKPepe do not need to edit the PR text. The commit text already had `closes`. That's enough isn't it? ( I suppose having text in PR visible to maintainers is not bad)

**Comment by systemcrash** [comment]
ping

**Comment by systemcrash** [comment]
ping @BKPepe

**Comment by BKPepe** [comment]
@systemcrash , I am not the only one with the merge rights. In my point of view, it is better to use specific keywords in the pull requests (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests), because if it is in the commit description then with each force push, you will spam the referenced issue and thats not wanted at least in my eyes, though.

**Comment by systemcrash** [comment]
This doesn't need any force pushes. It's ready. The fix was verified before the PR.

**Pull request merged**
