### PR TITLE
mwan3: close flock fd when starting mwan3.user scripts

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: me
Compile tested: no
Run tested: no

Description:
Fixes deadlock with multiple init script calls.
Fixes https://github.com/openwrt/openwrt/issues/15994

### CODE REVIEW

**Comment by feckert** [comment]
@BKPepe Thanks for the hint. This is only a [workaround](https://github.com/openwrt/openwrt/issues/15994#issuecomment-2254677758) . 
The entire locking in mwan3 must be changed! See the [comments](https://github.com/openwrt/openwrt/issues/15994#issuecomment-2258884581).
Unfortunately I don't have the time now to fix it correctly for the upcoming release. So I think we should use the workaround fix.

**Comment by BKPepe** [comment]
It is missing bump in PKG_RELEASE, in such cases, I miss autorelease variable, which we have in past. :-( Yeah, I looked at the issue in the main repo, and for me, it seems like, we need to backport this fix to the stable releases because no one will rewrite the entire mwan3 in the foreseeable future, though.

**Comment by feckert** [comment]
@BKPepe Done with commit https://github.com/openwrt/packages/commit/0532015a2968fd09c8d9c0044b509324cbca7ec8

**Comment by BKPepe** [comment]
What? Why you would do that in the first place? 

In the master branch, there is version 2.11.16 and in the OpenWrt 23.05 branch, there is 2.11.8.
You will increase there only PKG_RELEASE and backport this small workaround and you suggested to backport all those changes? Hmm, this is not how this should work. :-)

**Comment by BKPepe** [comment]
Backports are done in the standard approach how they should be: https://github.com/openwrt/packages/commit/18c3e8d6c2bf665e0b49582225fbeeedb03cdd9f (OpenWrt 23.05). That's why there is cherry pick and this method is done here multiple times while backporting smth to stable releases.

**Comment by feckert** [comment]
Ok thanks for my feedback. I would have seen it the same way. I was just unsure, so I wanted to ask again.

**Pull request merged**
