### PR TITLE
zerotier: add configuration reload trigger

### PR DESCRIPTION
**Pull request by kolbyjack**
Backporting #17247 to 21.02 branch as was suggested in the PR discussion

### CODE REVIEW

**Comment by BKPepe** [comment]
You should use ``git cherry-pick -x``, so we know in the git history that it was cherry-picked. Otherwise LGTM

**Comment by kolbyjack** [comment]
> You should use `git cherry-pick -x`, so we know in the git history that it was cherry-picked. Otherwise LGTM

I didn't know about -x, re-picked

**Comment by BKPepe** [comment]
Now, there's is missing ``PKG_RELEASE`` bump, which was in previous commit.

**Comment by BKPepe** [comment]
Superseded by this commit: https://github.com/openwrt/packages/commit/15b41a6751e9f7a81c0532765e73a3c507ef9a86 pushed directly.

**Pull request closed without merging**
