### PR TITLE
shairport-sync: support before/after entering active state and more events in UCI config

### PR DESCRIPTION
**Pull request by davidandreoletti**
Maintainer: @mikebrady 
Compile tested: NanoPi R4s / OpenWRT SNAPSHOT 
Run tested:  NanoPi R4s / OpenWRT SNAPSHOT

Description:
- Add before/after active state event callbacks in UCI config.
- Add volume change event callbacks in UCI config.
- Add unfixable error event callbacks in UCI config.

Why ?
- Other event callbacks were included in UCI config but not these ones. Now, with these new ones, one can start/stop other process when shairport-sync receive audio data or volume changes. I happen to need both.

### CODE REVIEW

**Comment by davidandreoletti** [comment]
@BKPepe / @mikebrady I believe this is now in a good state for review.

**Comment by davidandreoletti** [comment]
@Noltari / @BKPepe The maintainer gave a "thumbs up" on the PR. Would you mind giving your input/merge please ?

**Comment by Noltari** [comment]
> @Noltari / @BKPepe The maintainer gave a "thumbs up" on the PR. Would you mind giving your input/merge please ?

@davidandreoletti as @BKPepe already pointed out [on your other PR](https://github.com/openwrt/packages/pull/23630#issuecomment-2051109785), PKG_RELEASE should be bumped.

**Comment by davidandreoletti** [comment]
> @Noltari Got it. PKG_RELEASE bumped. There are 3 PR in review for the same package. Each PR has different bumped PKG_RELEASE:
> 
> * [shairport-sync: support before/after entering active state and more events in UCI config #23629](https://github.com/openwrt/packages/pull/23629) => PKG_RELEASE=4
> * [shairport-sync:  mqtt support #23630](https://github.com/openwrt/packages/pull/23630) => PKG_RELEASE=5
> * [shairport-sync: fixed diagnostics setting generation in shairport-sync's native conf file #23836](https://github.com/openwrt/packages/pull/23836) => PKG_RELEASE=6
> 
> I will resolve merge conflicts as they arise. Please merge in ascending order if possible.

@Noltari The current PR is the 1st of 3 PRs needing review/merging for the same package. Would you mind being the 1st to start the review, please ?

**Review by Noltari — APPROVED** [review]

**Comment by davidandreoletti** [comment]
@neheb This PR is approved and needs someone to merge it. 

May I ask for your help ?

**Pull request merged**
