### PR TITLE
nginx: Add missing WebDAV methods support (PROPFIND & OPTIONS)

### PR DESCRIPTION
**Pull request by zhouruixi**
Description:
Nginx provide WebDAV methods **PUT**, **DELETE**, **MKCOL**, **COPY**, and **MOVE** with http_dav_module. But most WebDAV clients that require additional WebDAV methods (**PROPFIND** & **OPTIONS**) to operate.So, add missing methods support with @arut's nginx-dav-ext-module.

Example config:
>location / {
>&ensp; dav_methods PUT DELETE MKCOL COPY MOVE;
>&ensp; dav_ext_methods PROPFIND OPTIONS;
>&ensp;
>&ensp; root /var/root/;
>}

Maintainer: @arut
Compile tested: mt7620, ar71xx, marvell mvebu; 6031ab345df86c285ea55d6523d6888cc596f63d
Run tested: mt7620, ar71xx, marvell mvebu;

### CODE REVIEW

**Comment by zhouruixi** [comment]
With this PR will got two warnings below (nginx's rtmp and ts module have the same problem):

> **``Makefile:523: warning: overriding commands for target `/tmp/tmp.pLxEfZ9kXO/dl/nginx-dav-ext-module-1.15.2-430fd774fe838a04f1a5defbf1dd571d42300cf9.tar.gz'``**
> **``Makefile:515: warning: ignoring old commands for target `/tmp/tmp.pLxEfZ9kXO/dl/nginx-dav-ext-module-1.15.2-430fd774fe838a04f1a5defbf1dd571d42300cf9.tar.gz'``**

[https://travis-ci.org/openwrt/packages/builds/415029575#L3897](url)

**Comment by hnyman** [comment]
You should highlight this to nginx package maintainers like @Ansuel

**Comment by Ansuel** [comment]
@zhouruixi i think the best way to implement this is create another flag 
something like NGINX_DAV_EXT

**Comment by zhouruixi** [comment]
@Ansuel I  created a flag named  NGINX_DAV_EXT. 

But i think this extra module is more like a patch of http_dav_module, because without this extra module WebDAV clients can't work at all! And this way is more complex than my commit before(0db6ba24a5bd14de3fdaf0163bb39d713b80e325).

Which is better? It's up to you :)

**Comment by Ansuel** [comment]
without the extra option webdav doesn't work at all ?

**Comment by zhouruixi** [comment]
Android (tested): Atleast ES File Explorer and Solid Explorer doesn't work without this extra module .

I'll test it on Linux and Windows tomorrow
Linux: try mount with davfs2
Windows: try NetDrive 3, etc.

**Comment by zhouruixi** [comment]
@Ansuel 
WebDAV clients doesn't work without the extra module in my case.

|  | Linux(davfs2) | Android(ES File Explorer) | Windows(CarotDAV) | MAC OS |
| ------ | ------ | ------ | ------ | ---- |
| without ext mod | X | X | X | ? |
| with ext mod | √ | √ | O | ? |

I don't have MAC OS, so ~

√:  works well
X: doesn't work at all
O: works with some problems 
? : need to tested

----------

image

**Comment by Ansuel** [comment]
@zhouruixi then let's include it by default sorry for all the mess... tell me when changes are done

**Comment by zhouruixi** [comment]
Done, please check it. @Ansuel

**Comment by Ansuel** [comment]
@hnyman ok for me to merge this

**Pull request merged**
