### PR TITLE
nfs-kernel-server: add nfsnobody user and group

### PR DESCRIPTION
**Pull request by mstorchak**
Signed-off-by: Maxim Storchak <m.storchak@gmail.com>

### CODE REVIEW

**Comment by mstorchak** [comment]
This user/group is useful with squash_root and squash_all export options:
```
/mnt/data -rw,async,root_squash,no_subtree_check,mountpoint=/mnt/data,anonuid=32767,anongid=32767 192.168.1.0/24
```

**Comment by mstorchak** [comment]
@tripolar

**Comment by mstorchak** [comment]
I haven't bumped release here to not introduce conflict with #2780 
If possible, please land them close to each other.

**Comment by tripolar** [comment]
i don't think it's a good idea to merge this,a there is no default /mnt/data export. i think this would just confuse users. if someone wants to use this "feature" it should be done in the users environment in my opinion

**Comment by mstorchak** [comment]
That was just an example. The PR is only about adding user and group.

**Comment by mstorchak** [comment]
`man 5 exports`:
> By default, exportfs chooses a uid and gid of 65534 for squashed access.
These values can also be overridden  by  the  anonuid  and  anongid  options.

65534 is nobody and nogroup, which are used quite extensively:
```
 packages> grep -r nogroup  * | wc -l
      32
```
That's why I propose to create a dedicated IDs for NFS.

**Comment by mstorchak** [comment]
@tripolar, any chance you change your mind after reading my justifications?

**Comment by tripolar** [comment]
i think this will just confuse users as this user/group isn't even used to run nfsd. i'm sorry but i think this shouldn't be included into. i'm sorry

**Comment by mstorchak** [comment]
Got it. Thank you for your review.

**Pull request closed without merging**
