### PR TITLE
stunnel: add stop_service to init script

### PR DESCRIPTION
**Pull request by databeille**
procd seems not able to stop the service.
Trying to fix this roughfully.

Signed-off-by: Julien Paquit <julien@databeille.com>

### CODE REVIEW

**Comment by sbyx** [comment]
Please read and follow our guidlines: https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

**Comment by databeille** [comment]
@sbyx My apologies, hope it complies now.

**Comment by thess** [comment]
Missing or incomplete.
* Commit needs Signed-off-by (not necessary for pull-request comment)
* PKG_RELEASE needs to be bumped (change to overall package contents)
* While you're at it - update copyright to 2015
* Commit comment should start with package name (Ex: stunnel: add stop_service to init script)

It seems that if you have 'forground = yes' in your stunnel.conf, stop_service should work. Is this not so?

@mhass please review.

**Comment by databeille** [comment]
@thess right, procd stops stunnel correctly if "foreground = yes" :)

**Comment by thess** [comment]
So, if we don't need this change, please close this PR.

**Pull request closed without merging**
