### PR TITLE
dockerd: refactoring uciadd and ucidel handling

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @G-M0N3Y-2503 
Compile tested: not needed only script changes
Run tested: x86_64, APU3, OpenWrt master, Addin and deleting config options with uciadd and ucidel

Description:
This change makes the handling of adding and deleting interface, device-bridges and firewall more robust for dockerd. This change is also necessary to be configuration compliant with the uci option `device` again. With this change, I have also adjusted the log message.

Should replace and close #15788

### CODE REVIEW

**Review by G-M0N3Y-2503 — APPROVED** [review]
Otherwise, looks good to me.
just bump the release number.

Thanks for the work @feckert

**Comment by feckert** [comment]
@G-M0N3Y-2503 I have added your suggestion for improvement. Can you verify this again?

**Comment by G-M0N3Y-2503** [comment]
> @G-M0N3Y-2503 I have added your suggestion for improvement. Can you verify this again?

It looks much cleaner now, great work and thanks!
I'm just about to test it myself too, but if it works for you, that's good enough for me.

**Comment by G-M0N3Y-2503** [comment]
just quickly tested it and seems good

**Comment by feckert** [comment]
@G-M0N3Y-2503 thanks for testing an verification my changes.
I would also like to bring this into the new stable branch openwrt-21.02. Is there anything against it from your point of view?

**Comment by G-M0N3Y-2503** [comment]
> @G-M0N3Y-2503 thanks for testing an verification my changes.
> I would also like to bring this into the new stable branch openwrt-21.02. Is there anything against it from your point of view?

From what I can see there shouldn't be anything different. So it should be fine.
If you'd like to do it for me, that would be great!

**Pull request merged**
