### PR TITLE
[22.03] python3: bump to version 3.10.9

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: @jefferyto 
Compile tested: x86 https://github.com/openwrt/openwrt/commit/7396263680b951211f33f2aa266b11bdd0047adc
Run tested: x86 https://github.com/openwrt/openwrt/commit/7396263680b951211f33f2aa266b11bdd0047adc

-------------------------------------

Refresh patches.
Bump setuptools to 65.5.0
Bump pip to 22.3.1

Signed-off-by: Alexandru Ardelean <alex@shruggie.ro>

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]

**Comment by jefferyto** [comment]
Was there a reason why this update was made directly on the openwrt-22.03 branch and not first done on master, then cherry picked back into 22.03?

**Comment by jefferyto** [comment]
Also FYI: https://github.com/pypa/pip/commit/fa4b2efbabffb96536c10bfb94477912a0f20e7f is part of pip 23.0 but the version included here is 22.3.1.

And pyproject_hooks continues to have [the same code](https://github.com/pypa/pip/blob/23.0.1/src/pip/_vendor/pyproject_hooks/_in_process/__init__.py) that the patch addresses, i.e. loading `_in_process.pyc` in addition to `_in_process.py`.

The patch didn't apply because the upstream code was modified, not because it isn't necessary anymore. As long as pyproject_hooks/pip needs to load `_in_process.py` and we continue to only ship .pyc files, the patch will be needed.

**Comment by commodo** [comment]
> Was there a reason why this update was made directly on the openwrt-22.03 branch and not first done on master, then cherry picked back into 22.03?

i started working on python 3.11 for master; and wanted to do that instead of an intermediate jump to 3.10.x;
but got derailed;
are you working on it? or shall i move forward with it?

**Comment by commodo** [comment]
> Also FYI: [pypa/pip@fa4b2ef](https://github.com/pypa/pip/commit/fa4b2efbabffb96536c10bfb94477912a0f20e7f) is part of pip 23.0 but the version included here is 22.3.1.
> 
> And pyproject_hooks continues to have [the same code](https://github.com/pypa/pip/blob/23.0.1/src/pip/_vendor/pyproject_hooks/_in_process/__init__.py) that the patch addresses, i.e. loading `_in_process.pyc` in addition to `_in_process.py`.
> 
> The patch didn't apply because the upstream code was modified, not because it isn't necessary anymore. As long as pyproject_hooks/pip needs to load `_in_process.py` and we continue to only ship .pyc files, the patch will be needed.

oh; crap....
well, i forgot what i was doing there;
maybe i was overjoyed they dropped it and didn't pay attention;

**Comment by jefferyto** [comment]
> are you working on it? or shall i move forward with it?

I'm working on it, just have a lot of things to catch up on.

**Pull request merged**
