### PR TITLE
Add Open-ZWave and Domoticz

### PR DESCRIPTION
**Pull request by stintel**
Maintainer: me
Compile tested: LEDE 17.01 r3045-e038c60 on x86/64 and ar71xx
Run tested: LEDE 17.01 r3045-e038c60 on x86/64 and ar71xx

Replaces #2883.

Description:
Add 2 new packages: Open-ZWave and Domoticz. See the old PR for background info. Dependencies are non-optional since most of them can't be disabled with the current CMake config, and due to the size and the fact that Domoticz uses an sqlite db, it's near impossible to run them on devices with limited flash.

Domoticz puts everything in /opt by default, and doesn't separate variable and static data. This is quite messy, so there are some changes to improve the behavior. The ```-userdata``` option is used to configure the directory that will hold variable data. On my system, this is its current content:
```
/var/lib/domoticz/
/var/lib/domoticz/domoticz.db
/var/lib/domoticz/domoticz.db-wal
/var/lib/domoticz/domoticz.db-shm
/var/lib/domoticz/zwcfg_0xe29e5387.xml
/var/lib/domoticz/zwscene.xml
/var/lib/domoticz/backups
/var/lib/domoticz/backups/hourly
/var/lib/domoticz/backups/hourly/backup-hour-16.db
/var/lib/domoticz/backups/hourly/backup-hour-17.db
/var/lib/domoticz/backups/hourly/backup-hour-18.db
/var/lib/domoticz/backups/hourly/backup-hour-19.db
/var/lib/domoticz/backups/hourly/backup-hour-20.db
/var/lib/domoticz/backups/hourly/backup-hour-21.db
/var/lib/domoticz/backups/hourly/backup-hour-22.db
/var/lib/domoticz/backups/daily
/var/lib/domoticz/backups/monthly
/var/lib/domoticz/domocookie.txt
```

The default location for userdata is /var/lib/domoticz. This is tmpfs by default, so the user will have to configure a different path to keep the data across reboots. This is intentional, to avoid users from filling up their flash when running with the default config.

A new option ```-scripts``` has been added, pointing to ```/usr/share/domoticz/scripts/```. Originally this used the ```-userdata```, mixing variable with non-variable data.

The init script has no ujail support because that conflicts with running as unprivileged user. Domoticz has no option to specify the user it runs as, so it has to be done via procd, but procd jails require to run as root. As procd-ujail is optional and disabled by default, this would result in Domoticz running unjailed, as root, on most systems, which is simply not acceptable in my opinion.

There are two devices that require the old libusb-compat. I added a patch to disable them, to avoid depending on ancient libraries. If someone really needs these devices supported, check with upstream to port them to libusb-1.0.

I completely ripped out hidapi and udev dependencies from Open-ZWave. There is only one old HID-based controller that requires this. See https://github.com/OpenZWave/open-zwave/issues/590.

### CODE REVIEW

**Comment by diapolon** [comment]
Hi, it compile on at91 platform but, on openzwave package, need to add "libpthread" dependence

**Comment by stintel** [comment]
Hi @diapolon , thank you for your feedback. I have added the libpthread dependency to the openzwave package.

**Comment by dwmw2** [comment]
Hm, my original version in #2007 had `ssl_cert` and `ssl_cert_pass` options. And `ssl_port` worked, which it doesn't seem to for me in this version, at first test (on LEDE 17.01, admittedly)

**Comment by stintel** [comment]
@dwmw2 Thanks for your feedback. Added options sslcert and sslpass (same name as in domoticz), and changed sslwww so it no longer is a bool.

One thing you should keep in mind is that Domoticz will run as unprivileged user, so it's impossible to bind port 443. Running this as root is a big no-go for me. We could do this with capabilities (cap_net_bind_service), but the SDK doesn't support this afaict.

**Comment by dwmw2** [comment]
Hm, I have a vague recollection of trying to run unprivileged and having difficulty accessing hardware devices. Not quite to the point of transferring the evohome and ZWave controllers over yet though, so I can't trivially test.

We don't want port 443 anyway as uhttpd/luci live there, so we'd have to work out a passthrough/proxy mechanism. I tend to run on port 8443. I've submitted a patch upstream to support a separate `-sslkey` option: https://github.com/domoticz/domoticz/pull/1195

**Comment by dwmw2** [comment]
We discussed the fact that Domoticz is huge and people are likely to need external storage to use it on typical devices.... Maybe it does make sense to keep it all in /opt/domoticz instead of spreading it around in the "proper" places?

**Comment by stintel** [comment]
The init script sets group permissions on the device node, so that it's possible to run unprivileged. This requires you to set the device node(s) in /etc/config/domoticz. As per your suggestion I am thinking of adding a hotplug script. To avoid having to maintain a list of known devices, I would still let it use the devices configured in /etc/config/domoticz. Does that make sense?

I don't like keeping things in /opt. People can always use extroot.

**Comment by dwmw2** [comment]
The problem with identifying devices by name is that it changes with the phase of the moon. That's why I have hotplug scripts which look like this...

```
#!/bin/sh

PRODID="10c4/ea60/100"
SYMLINK="aeon_zstick_v2"
#logger -t Hotplug "Product ${PRODUCT} DEVICE_NAME ${DEVICE_NAME}"

if [ "${PRODUCT}" = "${PRODID}" ]; then
	if [ "${ACTION}" = "add" ]; then
		sleep 1
		DEVICE_NAME=$(ls /sys/$DEVPATH | grep tty)

		if [ -z ${DEVICE_NAME} ]; then
			logger -t Hotplug Warning DEVICE_NAME is empty
			exit
		fi

		logger -t Hotplug Device name of cp210 is $DEVICE_NAME
		ln -s /dev/$DEVICE_NAME /dev/${SYMLINK}
		logger -t Hotplug Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created
	fi

	if [ "${ACTION}" = "remove" ];
		then rm /dev/${SYMLINK}
		logger -t Hotplug Symlink /dev/${SYMLINK} removed
	fi
fi
```
and similarly but...
```
PRODID="10ac/102/101"
SYMLINK="evohome_usb"
```
And in fact at times even that hasn't been sufficient because many serial USB devices appear identical. So we'd want to be able to do it by physical port number too.

If you want to extend the config to handle that, sure. But you might do better to ship some defaults, like the above, and let people tweak them manually.

**Comment by diapolon** [comment]
Hi @stintel , which zwave adapter do you use? i have tried with aeon lab gen5 and zwave.me uzb1 but i cannot get it to recognize..

**Comment by stintel** [comment]
@diapolon I am using the Aeon Labs Zstick Gen5. Maybe you need ```opkg install kmod-usb-acm```? Not sure if I want to add this as a hard dependency to libzwave, not all hardware requires it...

**Comment by diapolon** [comment]
@stintel , usb-acm is installed, but dmesg report error and lsusb dont find device. I have used openwrt, now i try to compile lede...

**Comment by stintel** [comment]
@diapolon please show the error from dmesg.

**Comment by diapolon** [comment]
when i insert adapter i have:

[ 1555.000000] usb 2-1: new full-speed USB device number 2 using at91_ohci
[ 1555.140000] usb 2-1: device descriptor read/64, error -62
[ 1555.390000] usb 2-1: device descriptor read/64, error -62
[ 1555.640000] usb 2-1: new full-speed USB device number 3 using at91_ohci
[ 1555.780000] usb 2-1: device descriptor read/64, error -62
[ 1556.030000] usb 2-1: device descriptor read/64, error -62
[ 1556.280000] usb 2-1: new full-speed USB device number 4 using at91_ohci
[ 1556.700000] usb 2-1: device not accepting address 4, error -62
[ 1556.840000] usb 2-1: new full-speed USB device number 5 using at91_ohci
[ 1557.260000] usb 2-1: device not accepting address 5, error -62
[ 1557.260000] usb usb2-port1: unable to enumerate USB device

**Comment by stintel** [comment]
@diapolon unfortunately that looks like a kernel or hardware problem. If you keep running into it, I would report it upstream. Just to be sure, try power-cycling your device.

**Comment by diapolon** [comment]
@stintel is compiled related: after compiled lede i report same error, i downloaded lede rc1, installed needed package and it work!

**Comment by stintel** [comment]
@diapolon good that it works. Out of curiosity, what hardware is this?

**Comment by diapolon** [comment]
@stintel , is a device in development based on this module: http://www.acmesystems.it/aria

**Comment by stintel** [comment]
@dwmw2 I added a hotplug script that sets permissions on device nodes and creates symlink if configured in /etc/config/domoticz. Looking forward to your feedback.

**Comment by dwmw2** [comment]
In this world of crappy devices without serial numbers, I need to do the matching based on which port it's plugged into, too.

```
#!/bin/sh

. /lib/functions.sh

handle_devices() {
        local cfg="$1"
        local devname prodid symlink devpath

        config_get prodid "$cfg" prodid
        config_get symlink "$cfg" symlink
        config_get devpath "$cfg" devpath

        [ "$prodid" != "$PRODUCT" ] && return
        [ -n "$devpath" ] && [ ${DEVPATH##*/} != "$devpath" ] && return

        devname="$(ls /sys/$DEVPATH/tty)"
        [ -c "/dev/$devname" ] || return

        if [ "$ACTION" = "add" ]; then
                chgrp domoticz "/dev/$devname"
                chmod g+rw "/dev/$devname"
                [ -n "$symlink" ] && ln -s "/dev/$devname" "/dev/$symlink"
        elif [ "$ACTION" = "remove" ]; then
                [ -n "$symlink" ] && rm "/dev/$symlink"
        fi
}

config_load "domoticz"
config_foreach handle_devices "device"
```

For bonus points, you could match on serial# too. Even though a lot of crappy devices (including mine) don't have it.

**Comment by dwmw2** [comment]
```
config device
        option prodid '67b/2303/202'
        option devpath '2-1:1.0'
        option symlink 'ttyUSB-port1'

config device
        option prodid '67b/2303/202'
        option devpath '2-2:1.0'
        option symlink 'ttyUSB-port2'
```

**Comment by dwmw2** [comment]
Here it is with serial numbers too...
```
#!/bin/sh

. /lib/functions.sh

SERIAL="$(cat /sys$DEVPATH/serial)" 2>/dev/null
# interfaces don't have serial; only devices
[ -z "$SERIAL" ] && SERIAL=$(cat /sys$DEVPATH/../serial) 2>/dev/null

handle_devices() {
        local cfg="$1"
        local devname prodid symlink devpath serial

        config_get prodid "$cfg" prodid
        config_get symlink "$cfg" symlink
        config_get devpath "$cfg" devpath
        config_get serial "$cfg" serial

        [ -n "$prodid" ] && [ "$prodid" != "$PRODUCT" ] && return
        [ -n "$devpath" ] && [ "$devpath" != "$DEVICENAME" ] && return
        [ -n "$serial" ] && [ "$serial" != "$SERIAL" ] && return

        devname="$(ls /sys/$DEVPATH/tty)"
        [ -c "/dev/$devname" ] || return

        if [ "$ACTION" = "add" ]; then
                chgrp domoticz "/dev/$devname"
                chmod g+rw "/dev/$devname"
                [ -n "$symlink" ] && ln -s "/dev/$devname" "/dev/$symlink"
        elif [ "$ACTION" = "remove" ]; then
                [ -n "$symlink" ] && rm "/dev/$symlink"
        fi
}

config_load "domoticz"
config_foreach handle_devices "device"
```

**Comment by stintel** [comment]
Added a hardcoded startupdelay which I think is absolutely horrible, but procd does not support waiting for the process to quit during restart. This causes domoticz to not be able to bind the event socket, because the old process still has it open. On my APU2 with SSD it takes 7 (!) seconds for Domoticz to shut down, so made the startup delay 10 seconds.

Absolutely not happy with this change, but until procd supports waiting for the process to quiet, it will have to do.

**Comment by derrij** [comment]
Please, help me compile domoticz with openzwave support

i made silminks for openzwave 
```javascript
ubuntu@ddd:~$ ls /home/ubuntu/source/build_dir/target-mipsel_24kc_musl
drwxr-xr-x 25 ubuntu ubuntu  4096 Feb 15 09:28 domoticz-3.5877
lrwxrwxrwx  1 ubuntu ubuntu    71 Feb 15 09:19 openzwave -> /home/ubuntu/source/build_dir/target-mipsel_24kc_musl/openzwave-1.4.164
drwxr-xr-x 13 ubuntu ubuntu  4096 Feb 15 09:28 openzwave-1.4.164
lrwxrwxrwx  1 ubuntu ubuntu    71 Feb 15 09:20 open-zwave-read-only -> /home/ubuntu/source/build_dir/target-mipsel_24kc_musl/openzwave-1.4.164
```
but i got error 
```javascript
-- Curl libraries found at: /home/ubuntu/source/staging_dir/target-mipsel_24kc_musl/usr/lib/libcurl.so
-- Curl includes found at: /home/ubuntu/source/staging_dir/target-mipsel_24kc_musl/usr/include
-- Found OpenSSL: /home/ubuntu/source/staging_dir/target-mipsel_24kc_musl/usr/lib/libssl.so;/home/ubuntu/source/staging_dir/target-mipsel_24kc_musl/usr/lib/libcrypto.so (found version "1.0.2k") 
-- ==== OpenZWave not found, support disabled!
-- ==== WiringPi include file (wiringPi.h) not found. GPIO support disabled.```

**Comment by stintel** [comment]
You shouldn't make symlinks in build_dir, just switch the packages feed to my domoticz branch in feeds.conf:
```src-git packages https://github.com/stintel/openwrt-packages.git;domoticz```
And then run:
```
./scripts/feeds update
./scripts/feeds install domoticz
```

**Comment by dwmw2** [comment]
```
		DEVICE_NAME=$(ls /sys/$DEVPATH | grep tty)
```
That was working. You broke it :)
```
        [ -n "$prodid" ] && [ "$prodid" != "$PRODUCT" ] && return
        [ -n "$devpath" ] && [ "$devpath" != "$DEVICENAME" ] && return
        [ -n "$serial" ] && [ "$serial" != "$SERIAL" ] && return
```
Those too.

**Comment by stintel** [comment]
Any of the @openwrt/package-maintainers feels like reviewing? If no objections, I am going to merge it this weekend.

**Comment by stintel** [comment]
Merged this due to no objections for ~2 weeks.

**Comment by Kheamu** [comment]
Hello! Tell me,please, why in domoticz OpenWRT, installed on router, don't show aqara wireless remote switches? The same switches correct shows in domoticz, installed on Raspberry Pi.

**Comment by kofec** [comment]
You should write on forum about it not here

**Pull request merged**
