### PR TITLE
dosfstools: update to v4.0

### PR DESCRIPTION
**Pull request by Noltari**
Maintainer: @zxdavb
Compile tested: brcm2708/bcm2710 LEDE r1815
Run tested: -

This updates dosfstools to the latest release available and uses the new
automatically generated Makefiles instead of a hard coded compilation.

Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Please switch to the xz tarball, it's much more efficient and saves bandwidth

**Comment by Noltari** [comment]
@diizzyy done!

**Comment by diizzyy** [comment]
@Noltari Thanks!

**Comment by hnyman** [comment]
@Noltari 
you might need to take over the maintainership, as the original maintainer @zxdavb has not been very active here. (no code contributions since the PR importing this package in early 2015).

**Comment by zxdavb** [comment]
@Noltari That is a good idea! I don't currently use this package (although I was desperate for it back then).

**Comment by Noltari** [comment]
@zxdavb do you want me to take over the maintainership?

**Comment by zxdavb** [comment]
@Noltari Yes please, if you're willing to take over maintainership, the community (and I) would be grateful.

**Comment by Noltari** [comment]
@zxdavb done, thanks!

**Pull request closed without merging**
