### PR TITLE
nextdns: Update to version 1.6.4

### PR DESCRIPTION
**Pull request by rs**
Update to version 1.6.4

### CODE REVIEW

**Comment by BKPepe** [comment]
Changelog? Indication of compile test and run testing?

**Comment by rs** [comment]
This is automated push of new versions. Nothing changes in the package itself other than the code for the installed binary.

**Comment by rs** [comment]
Added: 

> Refactor the package so init script is installed from the binary instead of an init script embedded in the package.

**Comment by BKPepe** [comment]
> 
> 
> Added:
> 
> > Refactor the package so init script is installed from the binary instead of an init script embedded in the package.

This change is no-go for me. Same reasoning as here:
https://github.com/openwrt/packages/pull/10797#pullrequestreview-335591352

**Comment by rs** [comment]
The current package is broken, it breaks users config on upgrade, so it’s an urgent fix.

Our software deal with many different router firmware and OS. It is unpractical to maintain init scripts and configs in packages for each platform, so the binary can install itself and manage its config, this way the package is just about installing the binary and call install.

To change settings, we tell our users to use `nextdns config set ...` which will interact with the platform config system (icu in the case of openwrt).

OpenWRT was the first firmware we supported, that is why we had a different approach when we first created this package.

Regarding GPL, we are MIT, so I don’t see any incompatibility.

**Comment by BKPepe** [comment]
ping @openwrt/package-maintainers - we are no tracking init changes in this repository anymore?

**Comment by hnyman** [comment]
> we are no tracking init changes in this repository anymore?

There are also other packages that either do not have init scripts or have the init script elsewhere. For example, of the widely used packages SQM (sqm-scripts) has its init script in author's own repo, not here and also the whole install process is defined in the files in the outside repo.

That is rare, but not forbidden.

Having init scripts, default config etc. here makes it easier to track changes or notice possible problems with new global features. Some of the apps with the "outside files" approach have got burned in recent uci/luci changes, as their files have been outside the repo, so that treewide modifications due to new features have not reached those apps. 

So, I would prefer having init scripts etc here, but that is not an absolute requirement.

**Pull request merged**
