### PR TITLE
libmicrohttpd: update to 0.9.49

### PR DESCRIPTION
**Pull request by dangowrt**
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by thess** [comment]
@friedzombie - please review

**Comment by dangowrt** [comment]
@friedzombie ?

**Comment by dangowrt** [comment]
@friedzombie @sbyx ?!?

**Comment by dangowrt** [comment]
@friedzombie @sbyx @jow- What's going on?

**Comment by thess** [comment]
FWIW - I think you should just merge this now and we'll back it out if @friedzombie objects.

**Pull request merged**
