### PR TITLE
ChinaDNS: add package

### PR DESCRIPTION
**Pull request by aa65535**
ChinaDNS is a DNS forwarder that filter DNS poisoning in china.
ChinaDNS automatically queries local DNS servers to resolve Chinese domains and queries foreign DNS servers to resolve foreign domains. It is smart enough to work only with a Chinese IP range file, which doesn't change often.

Signed-off-by: Jian Chang <aa65535@live.com>

### CODE REVIEW

**Comment by hgl** [comment]
I'm a ChinaDNS user. Wonderful project.

Just my 2 cents:

* START should probably be less than 60, before dnsmasq is started. It's very likely dnsmasq will be using ChinaDNS as an upstream dns server.
* port 5353 is used by `nas` (which is needed if you use broadcom-wl)

**Comment by thess** [comment]
Agreed - port 5353 is normally (IANA registered) for Multicast DNS (Bonjour/Zeroconf).

@aa65535 - Please note comments

**Comment by aa65535** [comment]
@thess Thanks! fixed.

**Comment by hgl** [comment]
@aa65535 forgot to mention, maybe the server option can be changed into a list type option?

Also I still think START should probably be less than 60 unless there is a more typical use case that I don't notice.

**Comment by aa65535** [comment]
@hgl 
The server must include local DNS and foreign DNS, use a list type option is error prone.
ChinaDNS mostly using ss-tunnel as the upstream server, `START=90` will not affect the dnsmasq.

**Comment by hgl** [comment]
@aa65535 First, I want to thank you for the contribution.

But I don't think
```
option server '114.114.114.114,8.8.4.4'
```
conveys any more meaning than
```
list server '114.114.114.114'
list server '8.8.4.4'
```
Why is the later more error prone?

> ChinaDNS mostly using ss-tunnel as the upstream server, START=90 will not affect the dnsmasq.

So you are saying dnsmasq shouldn't use ChinaDNS as an upstream server? I wonder how that works for lan hosts? If I'm encouraged to point my hosts to ChinaDNS directly, they lost the ability to resolve local domains if I'm not wrong.

When I have this package installed, should I point my dnsmasq to localhost#5300?

**Pull request closed without merging**
