### PR TITLE
acme-acmesh: Update to 3.0.7

### PR DESCRIPTION
**Pull request by kevbo-oh**
Maintainer: @tohojo @hgl
Compile tested: ath79
Description: Update to 3.0.7.
Signed-off-by: Kevin White <kwhite@kevbo.org>

### CODE REVIEW

**Comment by kevbo-oh** [comment]
I updated the commit comment to add Signed-off-by.  Not sure how to re-trigger the test.

**Comment by 1715173329** [comment]
I don't see the updated commit. Maybe need `git push --force`.

**Comment by kevbo-oh** [comment]
Sorry, I clearly hadn't amended the commit correctly before.  Hopefully I've done it right now.

**Comment by tohojo** [comment]
You'll need to squash everything into a single commit with a correct sign-off. Right now the PR contains 6 commits, which is making the bot sad...

**Comment by kevbo-oh** [comment]
OK, hopefully it is correct now.

**Comment by kevbo-oh** [comment]
I'm sorry about the mess here.  I use git all the time for internal stuff, but don't do pull requests very often.

**Comment by kevbo-oh** [comment]
At this point, I don't know how to solve this.  The log in Test Formalities says:
: Commit subject line seems ok (acme-acmesh: Update to 3.0.7 Signed-off-by: Kevin White <kwhite@kevbo.org>)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Kevin White <kwhite@kevbo.org>')

Those are the same.  I copy/pasted the lines into two separate text files and ran diff on them.  They're the same.  Unless the Signed-off-by line in my commit log needs to be surrounded by single quotes (which I'm pretty sure isn't the case).

git log on my end shows this:

```
commit cf065793e40d7c67b1cac1e1fe7da05b3bc07d5f (HEAD -> openwrt-23.05, origin/openwrt-23.05)
Author: Kevin White <kwhite@kevbo.org>
Date:   Fri Nov 17 07:16:27 2023 +0000

    acme-acmesh: Update to 3.0.7
    Signed-off-by: Kevin White <kwhite@kevbo.org>

```

**Comment by tohojo** [comment]
You need a blank line between the subject and the signed-off-by...

**Comment by kevbo-oh** [comment]
I have done so.  Hopefully this time...

**Comment by tohojo** [comment]
Yes, that seems to have done the trick! 🥳 Care to make an identical PR against the master branch as well? :)

**Comment by kevbo-oh** [comment]
Done.  Hopefully correctly.

**Comment by tohojo** [comment]
Alright, looks like everything worked now - thanks for the patch! :)

**Pull request merged**
