### PR TITLE
Bluez: Update to 5.49

### PR DESCRIPTION
**Pull request by jmv2009**
Signed-off-by: Johnny Vogels 35307256+jmv2009@users.noreply.github.com

Maintainer: @tripolar (suggested, is pulseaudio maintainer) /@nicolas Thill nico@openwrt.org
Compile tested: (x86, generic, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done) - Not tested - pending

Description:
This should work.

### CODE REVIEW

**Comment by diizzyy** [comment]
```git checkout patch-15``` (not needed if you're already on this branch)
```
git rebase -i HEAD~2
git push --force
```
https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/ for further information.

**Comment by jmv2009** [comment]
How to do it on the website?

**Comment by diizzyy** [comment]
Unfortunately not, you need to use the command line tool.

**Comment by jmv2009** [comment]
This may take me a week.

**Comment by diizzyy** [comment]
In short

```
mkdir upstream
cd upstream
git clone -b patch-15 https://github.com/jmv2009/packages.git
```
You only need to do this once
```
git config --global core.editor "nano"
git config --global user.name "Johnny Vogels"
git config --global user.email 35307256+jmv2009@users.noreply.github.com
```
**Email should be a valid one**

```git rebase -i HEAD~2```
* Change the last commit to squash
* Edit commit msg (don't remove sign-off)

```git push --force```

**Comment by jmv2009** [comment]
Do I get to send a password somewhere?

**Comment by diizzyy** [comment]
It'll ask for your username and password when you push (git push....) your changes

**Comment by jmv2009** [comment]
Thanks, I'll try tomorrow.

**Comment by jmv2009** [comment]
By the way, I don't know how to "change the last commit to squash". Git is still quite alien to me.

**Comment by diizzyy** [comment]
After you enter ```git rebase -i HEAD~2``` it'll show something similar to this:
https://cdn-images-1.medium.com/max/800/0*4uDByCeozZ_Cbg4u.png
Replace pick on the last line (ie last commit) with squash
https://cdn-images-1.medium.com/max/1800/0*9VVmICAVdIv8cbGG.png
Next screen will show the commit message from both commits which you'll need to edit.

**Comment by jmv2009** [comment]
Done, should be good to go. Please test.

**Comment by hnyman** [comment]
@psycho-nico @tripolar 
Any comments?

@jmv2009 
> Run tested: (put here arch, model, OpenWrt version, tests done) - Not tested
> 
> Description:
> This should work.

Please test your own changes...

**Comment by diizzyy** [comment]
I'll try to give this a go during the weekend

**Comment by diizzyy** [comment]
This needs some work to be usable, I'll do a pull request later today.

**Comment by hnyman** [comment]
superseded by #5988

**Pull request closed without merging**
