### PR TITLE
django,numpy,pytz: bump package versions

### PR DESCRIPTION
**Pull request by commodo**
Maintainer: me, @peter-stadler 
Compile tested: x86 https://github.com/openwrt/openwrt/commit/682843adadd753f174c4d7a8b1e487f7ee91e53a
Run tested: x86 https://github.com/openwrt/openwrt/commit/682843adadd753f174c4d7a8b1e487f7ee91e53a

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
Would you mind also updating the pytz version in the [Django 1.11 host pip requirements](https://github.com/openwrt/packages/blob/6e3c3c4b7c487b7f62821ad5bb7c74af014a9108/lang/python/host-pip-requirements/Django-1.11.txt) file? :pray:

**Comment by commodo** [comment]
> Would you mind also updating the pytz version in the [Django 1.11 host pip requirements](https://github.com/openwrt/packages/blob/6e3c3c4b7c487b7f62821ad5bb7c74af014a9108/lang/python/host-pip-requirements/Django-1.11.txt) file? 🙏

Sure
Will do it tomorrow 
My workday is done for today

**Comment by commodo** [comment]
> > Would you mind also updating the pytz version in the [Django 1.11 host pip requirements](https://github.com/openwrt/packages/blob/6e3c3c4b7c487b7f62821ad5bb7c74af014a9108/lang/python/host-pip-requirements/Django-1.11.txt) file? pray
> 
> Sure
> Will do it tomorrow
> My workday is done for today

Oh. I am starting to remember some things about this file.
Maybe it would be interesting to somehow make a tighter coupling with the Makefile of each package.
I can see myself forgetting about these host-pip-requirements files later again.

**Comment by commodo** [comment]
Changelog v1 -> v2:
* updated pytz version in `packages/lang/python/host-pip-requirements/Django-1.11.txt `

**Comment by jefferyto** [comment]
> Maybe it would be interesting to somehow make a tighter coupling with the Makefile of each package.

Setting this package data in one place and having it reflected everywhere it is needed would be ideal, though I don't have any good ideas for this at the moment :joy:

**Pull request merged**
