### PR TITLE
i2pd: update to version 2.46.1

### PR DESCRIPTION
**Pull request by dbermond**
Maintainer: @yangfl (David Yang)
Build system: Arch Linux x86_64
Build tested: r7800 OpenWrt git master (r22104-01262c921c)
Run tested: r7800 OpenWrt git master (r22104-01262c921c)

### CODE REVIEW

**Comment by yangfl** [comment]
LGTM

**Comment by dbermond** [comment]
Upstream shortly released version 2.46.1 with some fixes after 2.46.0.

Updated here. Working fine for me.

**Comment by dbermond** [comment]
By looking at the logs, it seems the compile error is happening in the new openssl 3.0 that was [just pushed](https://github.com/openwrt/openwrt/commit/7e7e76afca7877b97bc049d8f5a83a840a20a2af) to openwrt git master branch, and not in i2pd itself:

```
make[2]: Entering directory '/home/build/openwrt/feeds/base/package/libs/openssl'
mkdir -p /home/build/openwrt/bin/targets/armvirt/32/packages /home/build/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/openssl-3.0.8/ipkg-arm_cortex-a15_neon-vfpv4/libopenssl-afalg/CONTROL /home/build/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/pkginfo
install -d -m0755  /home/build/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/openssl-3.0.8/ipkg-arm_cortex-a15_neon-vfpv4/libopenssl-afalg/usr/lib/engines-1.1
install -m0755  /home/build/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/openssl-3.0.8/ipkg-install/usr/lib/engines-1.1/afalg.so /home/build/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/openssl-3.0.8/ipkg-arm_cortex-a15_neon-vfpv4/libopenssl-afalg/usr/lib/engines-1.1
install: cannot stat '/home/build/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/openssl-3.0.8/ipkg-install/usr/lib/engines-1.1/afalg.so': No such file or directory
make[2]: Leaving directory '/home/build/openwrt/feeds/base/package/libs/openssl'
time: package/feeds/base/openssl/compile#0.33#0.14#0.39
make[2]: *** [Makefile:403: /home/build/openwrt/bin/packages/arm_cortex-a15_neon-vfpv4/base/libopenssl-afalg_3.0.8-1_arm_cortex-a15_neon-vfpv4.ipk] Error 1
make[1]: *** [package/Makefile:116: package/feeds/base/openssl/compile] Error 1
    ERROR: package/feeds/base/openssl failed to build.
```

It was building fine for me with openssl 1.1, before the commit that introduced openssl 3.0.

**Comment by BKPepe** [comment]
Could you rebase your branch on top of the master branch, please? :) It should fix the CI.

**Comment by dbermond** [comment]
Branch rebased.

openssl 3.0 (and not i2pd) still fails to build in 2 architectures.

**Comment by BKPepe** [comment]
Not related to your PR, merging.

**Pull request merged**
