### PR TITLE
sendmail: update to 8.16.1

### PR DESCRIPTION
**Pull request by neheb**
Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @val-kulkov 
Compile tested: mvebu

### CODE REVIEW

**Comment by BKPepe** [comment]
You are doing many changes in your commit than just an update with refreshed patches.

**Comment by neheb** [comment]
Not really. patch 100 needed to be redone. The removed patches do not apply as they've been taken care of upstream.

**Comment by BKPepe** [comment]
Which is not stated in the commit message.

**Comment by neheb** [comment]
Updated.

**Pull request merged**
