### PR TITLE
nginx: bump to 1.17.0

### PR DESCRIPTION
**Pull request by Ansuel**
@hnyman 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Run-tested?
I've also noticed that the diagnostics page in LuCI seems to be broken (running the tests that is), is that something you can confirm?

**Comment by dengqf6** [comment]
Is it a good idea to use mainline branch (1.17.x) instead of stable branch (1.16.x) ?

**Comment by Ansuel** [comment]
@diizzyy i notice only the ping is broken and respond with error 405... nslookup and trace works

**Comment by BKPepe** [comment]
My thoughts:

- Exactly the same as it was said. Why would you like to use mainline branch instead of stable?
- The other one don't remove Github pull request template from your post and instead of it fill it, please.
For which platform you compile it and run-tested?

**Comment by BKPepe** [comment]
Let's close it for now. Feel free to re-open it anytime.

**Pull request closed without merging**
