### PR TITLE
lua-eco: update to 2.1.0

### PR DESCRIPTION
**Pull request by zhaojh329**
Signed-off-by: Jianhui Zhao [zhaojh329@gmail.com](mailto:zhaojh329@gmail.com)

Maintainer: me
Compile tested: x86, x86, master
Run tested: x86, x86, master, tests done

Description:
Release notes for 2.1.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.1.0

### CODE REVIEW

**Comment by zhaojh329** [comment]
@1715173329 
Build openssl-3.0 failed for arc.

**Comment by 1715173329** [comment]
Just ignore it, as well as the ppc 8540.

**Comment by 1715173329** [comment]
Please mention your extra changes (updated description, switched default SSL engine to mbedtls, added new network module) in the commit message.

**Comment by zhaojh329** [comment]
> Please mention your extra changes (updated description, switched default SSL engine to mbedtls, added new network module) in the commit message.

Done.

**Pull request merged**
