### PR TITLE
btrfs-progs: add Build/InstallDev

### PR DESCRIPTION
**Pull request by crashtua**
Signed-off-by: Eugene Chekanskiy <echekanskiy@gmail.com>

Maintainer: @neheb 
Compile tested: master, x86-generic
Run tested: master, x86-generic

Description:
Add copying headers and libs to staging directory to be able to compile libs and software depended on btrfs headers.

### CODE REVIEW

**Comment by neheb** [comment]
Increment the release number please.

**Comment by crashtua** [comment]
@neheb done.

**Comment by champtar** [comment]
Sorry @crashtua I merged another btrfs-prog PR and your PR now has conflicts
Please rebase

**Comment by champtar** [comment]
@crashtua you need to rebase (we don't accept merge commits in PR)

**Comment by neheb** [comment]
in the interest of saving time, I will roll this up in my next bump.

**Comment by crashtua** [comment]
@neheb thanks a lot of taking care of this.

**Pull request closed without merging**
