### PR TITLE
libupm: Update to 1.7.1

### PR DESCRIPTION
**Pull request by neheb**
The libmraa update introduced several API changes that broke libupm.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @blogic 
Compile tested: ar71xx mvebu

### CODE REVIEW

**Comment by neheb** [comment]
Note: Requires https://github.com/openwrt/packages/pull/7415

**Comment by neheb** [comment]
execvp: /usr/bin/env: Argument list too long

Alright I give up

**Comment by nxhack** [comment]
@neheb 
My custom package works fine.
https://github.com/nxhack/openwrt-intel-iot-devkit/tree/dev/libupm

**Comment by neheb** [comment]
Looks more detailed. The depends thing seems correct. Do you mind if I take yours and update this pull request?

**Comment by nxhack** [comment]
Hi @neheb 

Of course there is no problem. Please check both libmraa and libupm.

https://github.com/nxhack/openwrt-intel-iot-devkit/tree/dev/libmraa
https://github.com/nxhack/openwrt-intel-iot-devkit/tree/dev/libupm

**Pull request merged**
