### PR TITLE
abseil-cpp: Add package

### PR DESCRIPTION
**Pull request by vidplace7**
Maintainer: me
Compile tested:
- OpenWRT One master/snapshot (local)
- CI at [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic/actions/runs/12367901614)

Description:
Adds new package `abseil-cpp`. This is a dependency for many Google C libraries / projects. Notably `protobuf` >= 22.x, but also: gRPC, tensorflow, and many others.

Pre-requisite in order to update the `protobuf` package.
https://protobuf.dev/support/migration/#abseil

### CODE REVIEW

**Comment by vidplace7** [comment]
CC @BKPepe

**Comment by commodo** [comment]
i just feel like randomly ranting here that C++ is a terrible language, mostly because people tend to write weirdly-complicated code (using template magic),  and it eventually can need a ton of RAM just to compile things, which makes it's usage in the embedded space all the more weird (or seemingly out of place)

this PR however, is fine as-is :)

**Comment by vidplace7** [comment]
Per @vortexilation https://github.com/openwrt/packages/pull/25566#issuecomment-2553125799 this addition breaks builds of the `node` package. I was able to reproduce this failure.
```
../deps/v8/third_party/abseil-cpp/absl/container/internal/hashtablez_sampler.cc:75:6: error: no declaration matches 'void absl::lts_20240722::container_internal::HashtablezInfo::PrepareForSampling(int64_t, size_t)'
```

Node implements a bundled `abseil-cpp` which appears to conflict with the shared `abseil-cpp` implemented in this package.

CC: @nxhack

**Comment by vortexilation** [comment]
@vidplace7 
You need the patch from [here ](https://github.com/openwrt/packages/issues/25483)(beginning).

**Pull request merged**
