### PR TITLE
net/stunnel: add uci config support

### PR DESCRIPTION
**Pull request by feckert**
Maintainer: @diizzyy 
Compile tested: not needed
Run tested: lantiq_xrx200/x86_64, lede-17.01, configuration generation with uci

Description:
Add uci config support for stunnel.

### CODE REVIEW

**Comment by diizzyy** [comment]
Someone else needs to review this, I'm not familiar with UCI.

**Comment by feckert** [comment]
@diizzyy any suggestion?

**Comment by diizzyy** [comment]
@feckert 
I'm not sure what you want me to tell you, I have no idea about UCIs inner workings and I have no idea who would be suitable, sorry.

**Comment by feckert** [comment]
@dizzyy independently you are familiar with uci yes or no. Maybe you could verify if the options make sense and test if your working natvice configuration could be configured with the uci interface?

**Comment by diizzyy** [comment]
@feckert I know the intention of it but I usually end up not using it in the end as I find it just obfuscating configurations.

**Comment by feckert** [comment]
@hnyman sorry for the ping do you know someone which could review my stunnel uci integration?
diizzyy the maintainer is not familiar with uci and could not review my changes.
Thanks for help.

**Comment by diizzyy** [comment]
It's fine with me adding this, it looks good given my limited knowledge.

**Comment by feckert** [comment]
@hnyman could you please review my PR?

**Comment by hnyman** [comment]
Yeah, we can add it.
But please bump the PKG_RELEASE in Makefile

**Comment by feckert** [comment]
@hnyman @diizzyy thanks for your time to review my PR :-)

**Comment by hnyman** [comment]
@feckert 
Can you rebase it one more time.
Diizzyy's version bump to 5.44 was merged first, so there is now conflict.

**Pull request merged**
