### PR TITLE
net-snmp: fix compilation with GCC 14

### PR DESCRIPTION
**Pull request by vortexilation**
Missing header & incompatible pointer type is now an error

Maintainer: @stintel
Compile tested: x86_64
Run tested: Test needed, test not done, since I am not using snmpd.

Description:

Functionalities wise not tested but seems to be passed compilation.
I am fairly new in github or git, assistance might be needed from developers.

Sorry for the last 2 failed PR attempt.

### CODE REVIEW

**Comment by stintel** [comment]
Was this submitted upstream?

**Comment by vortexilation** [comment]
No, only personal trial. 

I don't think upstream will accept ieee802dot11.c module.

**Review by neheb — APPROVED** [review]

**Comment by vortexilation** [comment]
Need update, submitted the wrong commit.

**Comment by vortexilation** [comment]
@neheb 
Please kindly review my new commit, as previously is the wrong changes.

Also How to squash the commit into one and push?.

**Comment by neheb** [comment]
```
git rebase -i HEAD~2
```

replace pick with s on the last commit.
git push --force

**Comment by neheb** [comment]
```
large_fd_set.c: In function 'LFD_SET':
large_fd_set.c:97:39: error: initialization of 'u_int32_t *' {aka 'unsigned int *'} from incompatible pointer type 'long unsigned int *' [-Wincompatible-pointer-types]
   97 |     NETSNMP_FD_MASK_TYPE *fds_array = p->fds_bits;
      |                                       ^
large_fd_set.c: In function 'LFD_CLR':
large_fd_set.c:105:39: error: initialization of 'u_int32_t *' {aka 'unsigned int *'} from incompatible pointer type 'long unsigned int *' [-Wincompatible-pointer-types]
  105 |     NETSNMP_FD_MASK_TYPE *fds_array = p->fds_bits;
      |                                       ^
large_fd_set.c: In function 'LFD_ISSET':
large_fd_set.c:113:45: error: initialization of 'const u_int32_t *' {aka 'const unsigned int *'} from incompatible pointer type 'const long unsigned int *' [-Wincompatible-pointer-types]
  113 |     const NETSNMP_FD_MASK_TYPE *fds_array = p->fds_bits;
      |                                             ^
make[4]: *** [Makefile:101: large_fd_set.lo] Error 1
```

Make another PR. Reverting this brokenness.

**Comment by vortexilation** [comment]
@neheb
Thank you for approving my first contribution, I didn't get that error before, maybe because I am using glibc?, I will see what I can do about it.

**Comment by stintel** [comment]
Please always test using musl, this is the default libc for all but one target.

**Comment by vortexilation** [comment]
Ok, sorry for these.

**Pull request merged**
