### PR TITLE
boost: 1.65.1 Update

### PR DESCRIPTION
**Pull request by ClaymorePT**
Maintainer:  @ClaymorePT
Compile tested: LEDE 17.01 -> BCM2710 (Raspberry Pi 3)
Run tested: None

Description:
This commit updates the boost libraries to version 1.65.1

This new version is a bug-fix update for Boost 1.65.0, so no new libraries.
As always, more information about this release can be found in [1].

[1]: http://www.boost.org/users/history/version_1_65_1.html

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

### CODE REVIEW

**Comment by ClaymorePT** [comment]
@champtar Could this be an issue with Travis?
I'm unable to see in the report, the error where boost fails to build.

I'm currently building Boost with this proposed makefile, using a clean LEDE 17.01.2 source and it's OK.

**Comment by champtar** [comment]
Hi @ClaymorePT 
https://travis-ci.org/openwrt/packages/builds/276651421#L2327
please also try LEDE master, as you are updating packages master

**Comment by ClaymorePT** [comment]
Hello again @champtar 

I just tested against LEDE Master and everything went well.

The travis CI is not run with ```V=s ``` and because of that, I cannot see the details of the compile log. 
Is it possible to obtain that information?
Thank you.

**Comment by champtar** [comment]
Hi @ClaymorePT 
Travis only show you the logs of your package, and in this case it's not failing in your package
We need to improve travis script to print failed logs

**Comment by champtar** [comment]
I'll try to build it with the sdk and merge

**Comment by ClaymorePT** [comment]
OK @champtar 
Thank you for your support.

**Pull request merged**
