### PR TITLE
libnet: Change PKG_SOURCE_URL to use @SF macro.

### PR DESCRIPTION
**Pull request by neheb**
More flexible with more mirrors.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: ???

### CODE REVIEW

**Comment by neheb** [comment]
Force pushed a new commit. Apparently removing files at the end still works???

**Comment by neheb** [comment]
Any problems with this?

**Comment by diizzyy** [comment]
@hnyman 
Ok to merge?

**Comment by hnyman** [comment]
That "$(PKG_NAME)-dev" makes no sense to me.
Better to write openly "libnet-dev"

cc to maintainer @mislavn

**Comment by mislavn** [comment]
@hnyman I'm fine with the proposed change.

**Comment by neheb** [comment]
Plain name is now used.

**Pull request merged**
