### PR TITLE
mdnsresponder: update to IETF104

### PR DESCRIPTION
**Pull request by flyn-org**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer:
Compile tested: x86_64

Description:
I am still investigating which patches are still needed. I have removed them all for now.

### CODE REVIEW

**Comment by hnyman** [comment]
@MikePetullo 
ready to merge? Or are you still looking for which patches are still needed?

> I am still investigating which patches are still needed. I have removed them all for now.

**Comment by neheb** [comment]
Is this ready?

**Comment by diizzyy** [comment]
It isn't even run-tested so no, it's not.

**Comment by neheb** [comment]
ping @flyb-org

**Comment by flyn-org** [comment]
I have now also run tested on x86_64 and compile tested on mips_24kc.

**Pull request merged**
