### PR TITLE
krb5: update to 1.20.1

### PR DESCRIPTION
**Pull request by flyn-org**
Signed-off-by: W. Michael Petullo <mike@flyn.org>

Maintainer: me
Compile tested: x86_64 on master

Description:

### CODE REVIEW

**Comment by dangowrt** [comment]
Please write a commit description (not just commit title), it is mandatory for commits in this repository.

**Comment by flyn-org** [comment]
@dangowrt, I added a commit description.

**Review by dangowrt — COMMENTED** [review]
Commit description seems wrong:
"Besides updating the package to 1.20.1, this commit removed two packages that the new release made unnecessary."
```diff
- packages
+ patches
```

**Comment by flyn-org** [comment]
Fixed typo: s/packages/patches/g.

**Comment by dangowrt** [comment]
Thank you!

**Pull request merged**
