### PR TITLE
glib2: fix host build

### PR DESCRIPTION
**Pull request by neheb**
Seems to need -liconv.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @tripolar 
Compile tested: ath79

### CODE REVIEW

**Comment by tripolar** [comment]
there is a build error

../../../build_dir/build_dir/target-mips_24kc_musl/glib-2.64.2/meson.build:1:0: ERROR: Compiler gcc can not compile programs.

**Comment by neheb** [comment]
Yeah and I have no idea why. I'm only modifying host LDFLAGS, which should have no impact on the target build.

I tested this locally. All packages requiring glib2 and glib2/host build.

**Comment by tripolar** [comment]
thanks for all your patches!

**Comment by neheb** [comment]
OK I see what happened. With this change, it requires nlk.mk to fix CircleCI. The buildbot should be fine though.

I'll add back nls.mk with my next PR.

**Comment by lucize** [comment]
@neheb  I've added nls.mk but don't seems to fix my problem

```
The Meson build system
Version: 0.54.0
Source dir: /home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2
Build dir: /home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2/openwrt-build
Build type: cross build
Project name: glib
Project version: 2.64.2

../../../../build_dir/target-aarch64_generic_musl/glib-2.64.2/meson.build:1:0: ERROR: Compiler gcc can not compile programs.

A full log can be found at /home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2/openwrt-build/meson-logs/meson-log.txt
Makefile:129: recipe for target '/home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2/.configured_a17fb5ef857664f03cd0ce37cc5ea591' failed
make[3]: *** [/home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2/.configured_a17fb5ef857664f03cd0ce37cc5ea591] Error 1
make[3]: Leaving directory '/home/build/source/feeds/packages/libs/glib2'

```

**Comment by lucize** [comment]
I have HOST_LDFLAGS += -liconv

```
Is cross compiler: False.
Sanity check compiler command line: gcc /home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2/openwrt-build/meson-private/sanitycheckc.c -o /home/build/source/build_dir/target-aarch64_generic_musl/glib-2.64.2/openwrt-build/meson-private/sanitycheckc.exe -O2 -I/home/build/source/staging_dir/host/include -I/home/build/source/staging_dir/hostpkg/include -I/home/build/source/staging_dir/target-aarch64_generic_musl/host/include -I/home/build/source/staging_dir/host/include -I/home/build/source/staging_dir/hostpkg/include -I/home/build/source/staging_dir/target-aarch64_generic_musl/host/include -pipe -D_FILE_OFFSET_BITS=64 -L/home/build/source/staging_dir/host/lib -L/home/build/source/staging_dir/hostpkg/lib -L/home/build/source/staging_dir/target-aarch64_generic_musl/host/lib -liconv
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status

-----

../../../../build_dir/target-aarch64_generic_musl/glib-2.64.2/meson.build:1:0: ERROR: Compiler gcc can not compile programs.

```

**Comment by lucize** [comment]
made a dirclean but still complains about `/usr/bin/ld: cannot find -liconv`

**Comment by hnyman** [comment]
Still fails after "make dirclean, 
HEAD of master, r13023-8d9c1087e4
making for mvebu on Ubuntu 19.10

```
/Openwrt/wrt3200/staging_dir/host/bin/python /Openwrt/wrt3200/staging_dir/hostpkg/lib/meson/meson.py  --buildtype plain --native-file /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-native.txt --cross-file /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-cross.txt  -Dselinux=disabled -Dlibmount=disabled -Dinternal_pcre=true -Dman=false -Ddtrace=false -Dsystemtap=false -Dgtk_doc=false -Dbsymbolic_functions=true -Dforce_posix_threads=true -Dfam=false -Dinstalled_tests=false -Dnls=disabled -Doss_fuzz=disabled -Dxattr=true /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2
The Meson build system
Version: 0.54.0
Source dir: /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2
Build dir: /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build
Build type: cross build
Project name: glib
Project version: 2.64.2

../../../../build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/meson.build:1:0: ERROR: Compiler gcc can not compile programs.

A full log can be found at /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build/meson-logs/meson-log.txt
make[3]: *** [Makefile:134: /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
```

Meson log:
```
perus@ub1910:/Openwrt/wrt3200$ cat /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build/meson-logs/meson-log.txt
Build started at 2020-04-19T16:01:40.743769
Main binary: /Openwrt/wrt3200/staging_dir/host/bin/python
Build Options: -Dselinux=disabled -Dlibmount=disabled -Dinternal_pcre=true -Dman=false -Ddtrace=false -Dsystemtap=false -Dgtk_doc=false -Dbsymbolic_functions=true -Dforce_posix_threads=true -Dfam=false -Dinstalled_tests=false -Dnls=disabled -Doss_fuzz=disabled -Dxattr=true -Dbuildtype=plain '--cross-file /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-cross.txt' '--native-file /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-native.txt'
Python system: Linux
The Meson build system
Version: 0.54.0
Source dir: /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2
Build dir: /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build
Build type: cross build
None of 'PKG_CONFIG_PATH_FOR_BUILD' are defined in the environment, not changing global flags.
None of  are defined in the environment, not changing global flags.
Project name: glib
Project version: 2.64.2
None of 'CFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'LDFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CPPFLAGS_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CC_LD_FOR_BUILD' are defined in the environment, not changing global flags.
Sanity testing C compiler: gcc
Is cross compiler: False.
Sanity check compiler command line: gcc /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build/meson-private/sanitycheckc.c -o /Openwrt/wrt3200/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/openwrt-build/meson-private/sanitycheckc.exe -O2 -I/Openwrt/wrt3200/staging_dir/host/include -I/Openwrt/wrt3200/staging_dir/hostpkg/include -I/Openwrt/wrt3200/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/host/include -I/Openwrt/wrt3200/staging_dir/host/include -I/Openwrt/wrt3200/staging_dir/hostpkg/include -I/Openwrt/wrt3200/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/host/include -pipe -D_FILE_OFFSET_BITS=64 -L/Openwrt/wrt3200/staging_dir/host/lib -L/Openwrt/wrt3200/staging_dir/hostpkg/lib -L/Openwrt/wrt3200/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/host/lib -liconv
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status

-----

../../../../build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/glib-2.64.2/meson.build:1:0: ERROR: Compiler gcc can not compile programs.
```

**Comment by neheb** [comment]
It needs libiconv in PKG_BUILD_DEPENDS. Once built, it works. Including nls.mk does that in addition to using it, meaning -liconv is needed for the TARGET_LDFLAGS.

There’s still the issue of gkrellmd not building with that change. Maybe one other package.

**Comment by neheb** [comment]
Turns out, the hostpkg stuff ends up linking to the host instead of staging_dir/hostpkg ...

I didn't notice this as I have glib2 installed locally.

**Comment by neheb** [comment]
Continued here: https://github.com/openwrt/packages/issues/11900

**Comment by hnyman** [comment]
I still feel that the changes might be needed to be reverted until a fix is found. 

Right now it is impossible to privately build OpenWrt unless you have glib2 installed at the buildhost, right?

**Comment by neheb** [comment]
glib2/host only. not glib2.

**Comment by BKPepe** [comment]
Why this was merged at the first place, when CI failed? As suggested by @hnyman I agree that we should revert it as soon as we can until there's a fix for it. There is nothing wrong by doing that. I will do it.

**Pull request merged**
