### PR TITLE
go2rtc: update to 1.9.7

### PR DESCRIPTION
**Pull request by vooon**
Maintainer: me
Compile tested: x86_64, OpenWrt master
Run tested: x86_64, Master, camera's continue to work

Description:

- Update to 1.9.7

### CODE REVIEW

**Comment by vooon** [comment]
@1715173329 sorry, yesterday Alex released new patch. I'm testing now.

**Comment by 1715173329** [comment]
Not at all ;)

**Comment by vooon** [comment]
Well, build is ok. But i do not have a connectivity to the target site...
Most likey it works. Probably i'll fix vpn channels later this week...

**Comment by vooon** [comment]
@1715173329 i restored the link and tested. All green.

**Pull request merged**
